dolphin-emu/dolphin

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/QtUtils/SignalBlocking.h
Source/Core/DolphinQt/Settings/GeneralPane.cpp

I ran into this while implementing a 'reset all settings' feature. Turns out that blocking signals on QWidget doesn't block events from its children, so what happened is that I called reset settings, all settings were reset, then the GUI got the request to update itself, and during the update one of the GUI elements called its 'I have been changed' signal, which stored the current GUI back to the settings, reverting my reset. Not ideal!
Is there a better way to handle this? This is the best I could come up with, but maybe someone has a less boilerplate-y idea...

Qt/GeneralPane: Don't trigger config change events when populating GUI.

---

Source/Core/Common/FileUtil.cpp

There are several problems with this statement:
* It tries to return [Directory containing Dolphin]/Dolphin.app/Contents/MacOS instead of the [Directory containing Dolphin]/Dolphin.app that is assumed by callers of the function.
* It uses std::string's find_last_of function, which returns the last instance of any character in the string rather than the last occurrence of the string as a whole.
* The haystack string is initialized with GetBundleDirectory() which returns [Directory containing Dolphin]/Dolphin.app, which would make the search fail if it were actually using a function that found the last instance of the string.
These errors coincidentally cancel each other out, but better to just remove the statement.

FileUtil: Remove redundant statement

---

Source/Core/VideoBackends/OGL/OGLRender.cpp

This is mainly intended for debugging fifo.ci.

OGLRender: Log video backend info, in addition to showing it via OSD

---

Source/Core/Core/Debugger/PPCDebugInterface.cpp

Fix "braces around scalar initializer [-Wbraced-scalar-init]" warning.

Debugger: Fix warning on Debian builder

---

Source/Core/Common/DynamicLibrary.h

The default implementations of DynamicLibrary's copy and move constructors and assignment operators are unsafe.

Common: Make DynamicLibrary non-copyable

---

Source/Core/Common/FileUtil.cpp
Source/Core/VideoBackends/Software/EfbInterface.cpp

After dolphin-emu/fifoci#47, fifoci now shows log messages at the info level.  This greatly inflated the log sizes; however, as some spammy log messages are included.  [`pr-fifoci-ogl-lin-mesa`](https://dolphin.ci/#/builders/16/builds/5902) has a 9 MB, 69091-line log, of which 63854 lines are related to various FileUtil operations.  And [`pr-fifoci-sw-lin-mesa`](https://dolphin.ci/#/builders/17/builds/5893) has a **572 MB, 5128601-line log**, of which 63345 lines were related to FileUtil, and **5060654** were related to the software renderer saying that the RGB565_Z16 pixel format isn't correctly supported multiple times for every single pixel drawn.  (The hardware renderers also do not correctly support RGB565_Z16 at this time, but they don't have any such logging.)
I've removed the …

Reduce logspam at info level

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

In a code block where a guest register is accessed at least twice and the last access is a write and the register is not discardable immediately after the second-to-last instruction (perhaps there is an instruction in between that can cause an exception), currently Dolphin's JITs will flush the register after the second-to-last instruction.
It would be better if we replaced the flush after the second-to-last instruction with a flush that only happens if the exception path is taken. This change accomplishes that by marking guest registers as "in use" not just when they are used as inputs but also when they are used as outputs, preventing the loop in DoJit from flushing the register until after the last access.

PPCAnalyst: Count outputs as being in use

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp

This makes codegen faster (by perhaps 10-20% in the case of Jit64, I didn't measure too closely), which helps speed up NBA Live 2005 a little. But the game still has serious performance issues.

Jit: Skip redundant flushes

---

Source/Core/DiscIO/VolumeGC.cpp
Source/Core/DiscIO/VolumeVerifier.cpp

Turns out there's some Freeloader disc for the GC that triggers this despite being a good dump. This warning is mostly intended to catch Wii games that have been truncated at the 4.00 GiB or 4.38 GiB mark anyway, and if someone does have a Datel dump that has been truncated, they'll still get the "unusual size" warning.

VolumeVerifier: Skip "lacks some data" check for Datel discs

---

Source/Core/Common/StringUtil.h
Source/Core/DolphinLib.props
Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp
Source/Core/DolphinQt/Config/Mapping/MappingCommon.h
Source/Core/InputCommon/CMakeLists.txt
Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp
Source/Core/InputCommon/ControllerInterface/MappingCommon.h

Some of the functions in MappingCommon would be useful to use on mobile in the future.

Move parts of MappingCommon out of DolphinQt

---

Source/Core/Common/TraversalClient.cpp
Source/Core/Common/TraversalClient.h
Source/Core/Common/TraversalProto.h
Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp

This changes the "External" address display to that as seen by the traversal server (when using the traversal server).
e.g. When a 2nd device on my LAN tries to host with the traversal server at port 2626 my router maps the external port to 1025.
Other routers will do similar things.
Maybe network problems can be better diagnosed with this information?
"Direct" connection display still assumes the external port is unchanged.

NetPlayDialog: Display external IP/Port as seen by the traversal server.

---

CMakeLists.txt
Source/Core/CMakeLists.txt
Source/Core/UICommon/AutoUpdate.cpp

This PR introduces a new CMake option (``ENABLE_AUTOUPDATE``) and a new define (``AUTOUPDATE``), which allows one to disable automatic updater support in Windows and macOS builds.

CMakeLists: Add flag to enable / disable automatic update support

---

Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp

Flawed `optional` logic required inputs eventually be released (relying on since-removed 500ms confirmation delay PR #9685).
This un-breaks generation of hotkey (`@()`) and `&` expressions.

MappingCommon: Fix detection of hotkey and conjunction expressions.

---

Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/MenuBar.h

* Adds a "Reset Ignore Panic Handler" button to the Options subgroup in the MenuBar; It will only appear if Debug mode is enabled
* The button will do nothing if Config -> Interface -> Use Panic Handlers is disabled
Originally, I was going to make this a toggle like Automatic Start and Boot to Pause. Since Main.cpp calls SetEnabledAlert directly and there is no way to call MenuBar qActions from Main.cpp, I opted to go with a stateless button. User usage of the button also made little sense to have a toggle, since Config -> Interface already has a "Use Panic Handlers".
When a person debugging runs into an exception like this, sometimes there are 5000+ messages and the only choice is to choose "Ignore for this session". There really should be a "pause" option for those scenarios, but that's …

DolphinQt: Add "Reset Ignore Panic Handler" MenuBar Option

---

Data/Sys/GameSettings/REX.ini

With "Store EFB Copies to Texture Only" set to True (the default setting), areas of Excite Truck appear darker than on console. For example, in Sylvan Glen under the Bronze cup, all of the trees appear very dark, nearly black. On console, this does not occur.
Start of the race on Dolphin: https://youtu.be/KjJ-55lwFkE?t=817
Start of the race on Console: https://youtu.be/0W9blwA8AG4?t=699
Setting EFBToTextureEnable = False fixes this issue and does not appear to introduce any performance impacts, so I am recommending that this be disabled by default for this game.

Create REX.ini file for Excite Truck visual issues

---

Data/Sys/GameSettings/GYRE41.ini

So funny story: the author of the "widescreen" patch for Rayman Arena (which is a patch ported from gamemasterplc's widescreen code Rayman 3) told me that it fixes the infamous hang in Rise and Shrine.  Now, Rayman Arena is a serious bastard of a game, and has hanged in Dolphin on this map as far back as I could get the game to run in Dolphin.  I thought to myself:
"How in the world could a widescreen patch work-around the bug???"
So I tried it.  And it worked.  So I began studying the code and found out it wasn't exactly a widescreen patch, it was a no culling patch.  But here's the thing: Rayman Arena already has almost no culling.  The only thing it culls is a few character models and item boxes at the start of the match.  The impact of the no culling cheat is actually very subtle, …

GameINI: Rayman Arena - Add Disable Culling Patch that fixes "Rise and Shrine" Hang

---

Source/Core/DiscIO/Blob.h
Source/Core/DiscIO/CISOBlob.h
Source/Core/DiscIO/CompressedBlob.h
Source/Core/DiscIO/DirectoryBlob.h
Source/Core/DiscIO/DriveBlob.h
Source/Core/DiscIO/FileBlob.h
Source/Core/DiscIO/ScrubbedBlob.h
Source/Core/DiscIO/TGCBlob.h
Source/Core/DiscIO/VolumeFileBlobReader.cpp
Source/Core/DiscIO/VolumeFileBlobReader.h
Source/Core/DiscIO/WIABlob.cpp
Source/Core/DiscIO/WIABlob.h
Source/Core/DiscIO/WbfsBlob.h
Source/Core/DolphinQt/ConvertDialog.cpp
Source/Core/DolphinTool/CMakeLists.txt
Source/Core/DolphinTool/ConvertCommand.cpp
Source/Core/DolphinTool/DolphinTool.vcxproj
Source/Core/DolphinTool/HeaderCommand.cpp
Source/Core/DolphinTool/HeaderCommand.h
Source/Core/DolphinTool/ToolMain.cpp

This PR adds more diagnostics to dolphin-tool.  The block size, compression method, and compression level are all now accessible from the command line.

More dolphin-tool features and options

---

Source/Core/VideoCommon/FramebufferShaderGen.cpp

ANGLE raises a compilation error otherwise.

VideoCommon: Remove redundant in qualifiers

---

Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp

This allows any game to specify a different IOS as the IOS used to boot the game.
The target of this is primarily smash bros, as this allows SDHC cards to be used with the game if [Beero's SDHC](http://forums.kc-mm.com/index.php?topic=65342.0) Gecko Code is used.
Because the target of this is Smash Bro's, the default config for Smash has been updated to override the boot IOS to 58.
I put this under [Core], but I'm not sure that's the best place for this option, if there is a better place tell me, and I'll move it.

Add Override for Boot IOS for Wii Titles

---

Source/Core/DolphinQt/Settings/GeneralPane.cpp

This should fix https://forums.dolphin-emu.org/Thread-custom-speed-limit-value-that-isn-t-multiple-of-10-is-lost-when-config-is-saved

DolphinQt: Set emulation speed setting only when the combobox is actually touched.

---

Source/Core/DolphinTool/ConvertCommand.cpp
Source/Core/DolphinTool/ConvertCommand.h

This was requested by a forum user, and I thought why not. It's a simple change to make since DiscIO already supports it, and I assume command-line users know roughly what they're doing.

DolphinTool: Allow converting non-GC/Wii files

---

Source/Core/VideoBackends/OGL/OGLShader.cpp

The object label was using an invalid enumeration as the identifier that wasn't valid in the OpenGL spec.  In most implementations this warns but in some implementations it can cause a crash!
Fixes https://bugs.dolphin-emu.org/issues/12868

VideoBackends: fix opengl object label identifier

---

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

This PR allows to search/replace value from the Memory widget using a negative offset.

MemoryWidget: Add negative offset search support

---

Source/Core/DiscIO/VolumeGC.cpp

DTLX01 can be either a Freeloader or Action Replay, so it's inappropriate to always use the same title and cover for it.

DiscIO: Don't return GameTDB ID for any Datel disc

---

Externals/imgui/CMakeLists.txt
Externals/imgui/README.txt
Externals/imgui/imconfig.h
Source/Core/VideoCommon/RenderBase.cpp

The first commit calls the `IMGUI_CHECKVERSION` macro, which is intended to prevent issues like the one I caused after #10188 where the wrong version of imgui was linked.  The second commit is also future-proofing.
The third commit switches to Common's `ASSERT` macro for the `IM_ASSERT` macro.  This does mean imgui now depends on both common and fmt, but since imgui is only used by dolphinqt (and the cmakelists file is added by dolphin in the first place), I don't think this is a problem.  In my opinion, it's better to use the same assert window for everything, rather than have the default assert/retry/ignore one appear sometimes.
Examples by removing the call to `ImGui::CreateContext()` in `Renderer::InitializeImGui`:
Before:
After:
I did attempt to avoid the direct dependency by …

Externals: Use Common ASSERT for IM_ASSERT

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/CheatSearchFactoryWidget.cpp
Source/Core/DolphinQt/Config/ARCodeWidget.cpp
Source/Core/DolphinQt/Config/CommonControllersWidget.cpp
Source/Core/DolphinQt/Config/ControllerInterface/DualShockUDPClientWidget.cpp
Source/Core/DolphinQt/Config/FreeLookWidget.cpp
Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp
Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
Source/Core/DolphinQt/GCMemcardManager.cpp
Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp
Source/Core/DolphinQt/NetPlay/NetPlaySetupDialog.cpp
Source/Core/DolphinQt/QtUtils/NonDefaultQPushButton.cpp
Source/Core/DolphinQt/QtUtils/NonDefaultQPushButton.h
Source/Core/DolphinQt/ResourcePackManager.cpp
Source/Core/DolphinQt/Settings/GameCubePane.cpp
Source/Core/DolphinQt/Settings/GeneralPane.cpp
Source/Core/DolphinQt/Settings/PathPane.cpp
Source/Core/DolphinQt/Settings/WiiPane.cpp

As described in [issue 11184](https://bugs.dolphin-emu.org/issues/11184), the first button on each pane, widget or window gets highlighted and selected. This is the default behaviour for QPushButtons in a QDialog. By setting the autoDefault to false for the buttons, the close or cancel button in the bottom becomes the default which is then highlighted. This makes more sense than highlighting the first random button. This also makes it so that when pressing enter, the window closes instead of performing whatever functionality the first button on a window has.

Change the highlighted button on each window

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java

Trying to change it while a game is running does nothing. DolphinQt already inactivates it while a game is running.

Android: Mark MAIN_FALLBACK_REGION as not runtime editable

---

Source/Android/app/build.gradle
Source/Android/build.gradle

This PR updates the target and compile SDK version to 32. See the [Android 12L announcement](https://developer.android.com/about/versions/12/12L) for more information on Android 12L.
I have tested this on the Android Emulator. Adding and booting games works fine.
It's worth noting that the on-screen controls don't play nicely with the split-screen mode: 
However, this is nothing related to the Android SDK version and already happens on the current SDK version (31) on odd form factors, like the one you can see in the first screenshot.

Android: Increase target and compileSdk version to 32 (Android 12L/Sv2)

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h

u32 felt better with a bit wider spacing. Float is aligned to the first digit, which looks way better.
Note that's just my debug font. Height spacing varies a bit based on font, I don't think there's a definite way to set that.

Debugger MemoryViewWidget: fixed, tighter spacing

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Debugger/CodeDiffDialog.cpp
Source/Core/DolphinQt/Debugger/CodeDiffDialog.h
Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Source/Core/DolphinQt/Debugger/CodeWidget.h
Source/Core/DolphinQt/DolphinQt.vcxproj

For original PR, see #7679
TryTwo has since gone dark.
All credit for initial version of CodeDiff to TryTwo.
The PR, has been changed quite a bit. See final comments in thread.
---original description---
Adds a button to the code widget to open the differencing window.
Uses the profiler to record the functions that run, then the user adds the recording to an exclude or include list. The include list has the excludes subtracted from them, then gets displayed. The lists are symbol-based to avoid capturing a function multiple times. Allows finding specific functions based on when they run.
For example, recording the player standing still then pressing exclude, followed by moving around then pressing include, will find functions related to movement and movement animations. Specifically …

Qt/Debugger CodeWidget: Record and find specific functions by differencing

---

CMakeLists.txt
Source/VSProps/Base.props

msvc: enable conformant __cplusplus macro

---

Source/VSProps/Base.props

msbuild: don't explicitly set _SECURE_SCL

---

Source/Core/DolphinLib.vcxproj
Source/Core/InputCommon/CMakeLists.txt
Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.h
Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp
Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.h
Source/Core/InputCommon/ControllerInterface/Wiimote/WiimoteController.cpp
Source/Core/InputCommon/ControllerInterface/Win32/Win32.cpp
Source/Core/InputCommon/ControllerInterface/XInput/XInput.h

Why?
To support more than four Xbox 360/One controllers: https://bugs.dolphin-emu.org/issues/11400
To support Xbox One trigger rumble motors.
Xbox 360 and DS4 controllers (over USB) work as expected with analog triggers and rumble support.
Battery levels of Xbox controllers are also exposed.

InputCommon: Add Windows.Gaming.Input to ControllerInterface.

---

Source/Core/DolphinQt/MenuBar.cpp

When manually checking for updates, use the Dev track if autoupdates are disabled.
Fixes https://bugs.dolphin-emu.org/issues/12873.

Updater: Fix manual update check when autoupdate is disabled

---

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

Data preview has automatic spacing per byte.
Float is only for singles.
Integer can accept both unsigned and signed numbers up to 4 bytes.
Hex is right aligned and based on the view type.  Leading zeroes are always filled automatically.
View-based input:
-   "-2" integer in u8 view is FE, and in u16 view it's FF FE
-   "1" hex in u32 view is 00 00 00 01, and in u16 view it's 00 01
-   "123" hex in u8 view is 01 23 and 12345 -> 01 23 45. (u8 x3)
-  "12345" hex in u16 view is  00 01 23 45 (u16 x2)
Fixed a bug where an empty address offset would throw an error.
Loses the ability for infinite length hex string input, but still has it for ascii. Hex max length is 8 bytes.  I could go back and redo it if people actually slam massive hex strings in there.
Not sure if anyone is against …

Debugger: MemoryWidget: add float and integer input types. Add input preview.

---

Source/Core/DolphinLib.props
Source/Core/DolphinLib.vcxproj

It was accidentally put into the main DolphinLib.vcxproj in #7614.

msbuild: Move WGInput to DolphinLib.props

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml

Some ROMs don't have fullscreen feature, for example Pixel Experience, so have a option for that is better. Also you don't need put the app on fullscreen anymore with that.

Android: Implement expand display cutout option.

---

Source/Core/DolphinQt/Settings.cpp

This works around (or fixes?) a weird issue I discovered while testing #10542 where the default font was rendered with a point size of 9, but reported a font size of 12 to QFontMetrics.
Before:
After:
If this causes issues on Linux or macOS, we can put it behind a define instead.

Qt: Set font size for default debug font.

---

Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/UberShaderPixel.cpp

Previously we were using this workaround when using framebuffer fetch to emulate dual source blending, but it seems like we also need to use it when using framebuffer fetch to emulate logic ops, otherwise some Adreno devices get a crash when compiling OpenGL ES ubershaders.
Using the workaround in specialized shaders doesn't seem to be necessary, but I've made the same change there for consistency.
This gets us closer to fixing https://bugs.dolphin-emu.org/issues/12791 but doesn't actually fix it.

Shadergen: Use real_ocol0 workaround for shader logic ops

---

Source/Core/VideoBackends/Software/SWRenderer.cpp
Source/Core/VideoCommon/PixelEngine.cpp
Source/Core/VideoCommon/PixelEngine.h
Source/Core/VideoCommon/RenderBase.cpp

I currently implement screenshots [in the hardware fifoplayer](https://github.com/Pokechu22/fifoplayer/blob/archive/snapshot-issue-12576/source/main.cpp#L541) using EFB peeks.  However, this gave a transparent image with the software renderer, because the software renderer ignored the [pixel engine](http://hitmen.c02.at/files/yagcd/yagcd/chap5.html#sec5.2) alpha read mode (the hardware backends had them working).  This PR implements the alpha read mode, and also does some related cleanup of a bunch of PE registers (though those registers don't actually seem to be implemented?)
This won't result in changes with FifoCI, as EFB peeks and pokes are not recorded in fifologs since they don't use the graphics fifo.

Software: Implement pixel engine alpha read mode

---

Source/Core/Common/DebugInterface.h
Source/Core/Common/GekkoDisassembler.cpp
Source/Core/Common/GekkoDisassembler.h
Source/Core/Core/Debugger/PPCDebugInterface.cpp
Source/Core/Core/Debugger/PPCDebugInterface.h
Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.h

Backend:
Updates disassembler instructions. Mostly spaces and commas. PS load/store uses 0x notation. Required for new features.
Adds function to PPCDebugInterface to calculate target memory address for load/store instructions.
Code widget new feature:
-Context menu for copying or showing memory target in load/store instructions. Only works if the PC is near the instruction (register consistency).
/edit removed trace and diff for their own PRs
/edit2 changed breakpoint memory to 'show in memory'.

Debugger: Get target memory in load/store instructions

---

Source/Core/Common/Logging/Log.h
Source/Core/Common/Logging/LogManager.cpp
Source/Core/VideoCommon/FrameDump.cpp

Noticed this while making #10571. Unfortunately you can't just pass a `va_list` to a variadic function, so this printed garbage when the log message included arguments.

VideoCommon/FrameDump: Fix log messages with arguments.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java

`((Runnable) () -> init(context)).run()` is just a more complicated way of writing `init(context)`, and doesn't on its own launch a thread.

Android: Actually use a thread for DirectoryInitialization

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableButton.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableDpad.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableJoystick.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayPointer.java

According to the documentation, `getActionIndex` should only be used with `ACTION_POINTER_DOWN` and `ACTION_POINTER_UP`. We've had a few crashes reported in the Play Console regarding invalid pointer indices for `getY`, and I'm hoping this will help with that.

Android: Only use getActionIndex for ACTION_POINTER_DOWN/ACTION_POINTER_UP

---

Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp

Rebase of #10472, since the author of that one ignored our change requests.

DolphinQt/HacksWidget: Re-enable texture accuracy slider if it was disabled because of a custom value.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp
Source/Core/Core/NetPlayServer.cpp
Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
Source/Core/VideoCommon/BPFunctions.cpp
Source/Core/VideoCommon/VertexShaderManager.cpp
Source/Core/VideoCommon/VideoConfig.cpp

This should fix https://bugs.dolphin-emu.org/issues/9105 (an issue where a blue line appears in Wii Sports Resort's archery at 3x IR or higher).
The issue was caused by the game trying to reset the depth on a part of the screen by drawing a rectangle over it (object 264 in the fifolog), followed by it clearing the color of that region using an EFB copy, but at higher IRs these two things stop matching exactly.
<details><summary>Specifics</summary>
Object 264 has this:
```
BP register BPMEM_SCISSORTL
Scissor Top: 402
Scissor Left: 788
BP register BPMEM_SCISSORBR
Scissor Bottom: 489
Scissor Right: 852
BP register BPMEM_SCISSOROFFSET
Scissor X offset: 171
Scissor Y offset: 171
```
i.e. a scissor with a top coordinate of `402-(171*2)`=60, a left coordinate of 446, a bottom coordinate of 147, …

Round viewport coordinates when vertex rounding is enabled

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/VideoCommon/FrameDump.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

So people who want truly lossless dumps can specify that in their INI, regardless of what video codec they use.
This is mostly useful on Linux or when building with a custom ffmpeg, as our built-in Windows ffmpeg is (intentionally) very limited.

VideoCommon/FrameDump: Allow user to specify a pixel format.

---

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

The contents of a file can be stored into memory. Useful for hijacking a game file or code at any time.

MemoryWidget: Load Files to Memory

---

Source/Core/Core/HW/GCPadEmu.cpp

Currently, the axes for the main and C sticks range from 0-255, with
128 being the mid-point; but this isn't symmetrical: the negative axis
has 128 values not including 0, while the positive axis has 127 values
not including 0.
Normalizing so that the range is 1-255 makes the positive and negative
axes symmetrical. The inability to yield 0 shouldn't be an issue as a
real GC controller cannot yield it anyway.

Make pos/neg analog axes symmetrical

---

BuildMacOSUniversalBinary.py

For `{arch}` to be converted, the string needs to be an f-string.  See e.g. the end of https://dolphin.ci/#/builders/26/builds/2728/steps/4/logs/stdio:
> ```
> Built Universal Binary successfully!
> Building and running unit tests for: {arch}
> Building and running unit tests for: {arch}
> x86_64 Unit Tests: PASSED
> arm64 Unit Tests: FAILED (1)
> ```
This change is untested, but should be checkable once the osx build occurs.

Apple M1: Fix "Building and running unit tests" message

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/VideoBackends/Software/Clipper.cpp
Source/Core/VideoBackends/Software/Clipper.h
Source/Core/VideoBackends/Software/Rasterizer.cpp
Source/Core/VideoBackends/Software/Rasterizer.h
Source/Core/VideoBackends/Software/SWVertexLoader.cpp
Source/Core/VideoBackends/Software/SWVertexLoader.h
Source/Core/VideoBackends/Software/Tev.cpp
Source/Core/VideoCommon/VertexManagerBase.h
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

CullMode::All is often used with zfreeze to draw a triangle for the reference plane without it showing up (see the [note on `GX_SetCoPlanar`](https://github.com/devkitPro/libogc/blob/70323c888069f6bdd032b2e0b644a5cbefbfe179/gc/ogc/gx.h#L2904-L2905)).  However, this was broken in the software renderer.  I've fixed it by re-using the infrastructure in VertexManagerBase used by the hardware backends, but this is a bit jank.

Software: Fix zfreeze with CullMode::All

---

Source/Core/Common/StringUtil.cpp

This prints floating point values nicer to the INI, and possibly other places; eg. `0.2` instead of `0.200000003`. For those worried about precision loss, fmt guarantees that writing floats with the default formatting round-trip correctly. [See the 'none' formatting type for floats here](https://fmt.dev/latest/syntax.html), and [the readme specifically mentions round-trip guarantees](https://github.com/fmtlib/fmt/blob/master/README.rst) -- also I've used fmt for some time now professionally and as far as I can tell this is true.
The `#` additionally forces the generation of a decimal point even when it wouldn't be necessary, which means values won't be misidentified as integers when parsing without type information.
(note that I noticed this because of [this extremely silly list of ini …

Common/StringUtil: Use simpler formatting for floats and doubles.

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h
Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

Added Int8/16/32 and double..
- Do we want signed displays?
- 1.234e+09 syntax looks like it could be better, but what would I replace it with? Remove the +?
- Int8 looks terrible, but will look fine if we add a dual view  - two different column types with 4 bytes per row
- I left display type as a group, as it will likely get more items soon.
- Do we need to rename U8/16/32?
- Thoughts on sidebar rearrangement?
Most importantly, what else do I need to add? Do we need more customization in this PR like bytes per row?  A dual-view would require a lot of rearranging in the Update function to pass two view types through it. I think I would spin off column value updates and breakpoint tagging updates to two different functions, but will take suggestions on a better method to do it.

Debugger MemoryWidget: More display types, use combo box for options

---

Data/Sys/GameSettings/D43E01.ini

Changed "$Swords/Shields/boots/tunics" to "$Swords/Shields/Boots/Tunics" for consistent capitalization in the line.

Minor text capitalization

---

Source/Core/Common/ChunkFile.h
Source/Core/Core/IOS/Network/Socket.cpp
Source/Core/Core/State.cpp
Source/Core/UICommon/GameFileCache.cpp
Source/Core/VideoCommon/CPMemory.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/FreeLookCamera.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp

`DoVoid()` didn't check the extents of the buffer it's reading from or writing to -- because it didn't know them! This could cause crashes when eg. loading a truncated savestate, or when the state read and state write logic disagreed on the number of bytes to read/write.

Common/PointerWrap: Prevent reads/writes past the end of the buffer.

---

Source/Android/app/src/main/res/layout/card_game.xml

Remove background on card
Increase max # of lines for game title
Root layout is now a linear layout with the card view rounding the corners on the box art
Depending on 
Before - 
After -

Android: Modernize game card

---

Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
Source/Android/app/src/main/res/values/styles.xml

The ripple effect was not visible when pressing a button. I've also fixed the color edge effect since it used the primary color and was therefore invisible too.
Before:
https://user-images.githubusercontent.com/26326692/164316507-742c5f24-b7c2-4658-bd2c-39b28ea802d4.mp4
After:
https://user-images.githubusercontent.com/26326692/164316509-82b045d6-ffd5-4b2b-b85f-99c7f5bbc36e.mp4

Android: Fix in game menu rippleColor and colorEdgeEffect

---

Source/Core/InputCommon/GCAdapter.cpp
Source/Core/InputCommon/GCAdapter_Android.cpp

> Remove unnecessary atomic usage in GCAdapter.cpp
Makes `s_controller_payload_size` non-atomic. You can safely read or write non-atomic integers on multiple threads, as long as every thread reading or writing it holds the same mutex while doing so (here, `s_mutex`).
Removing the atomic accesses makes the code faster, but the actual performance difference is probably negligible.
> Remove unnecessary atomic usage in GCAdapter_Android.cpp
Makes `s_controller_payload_size` non-atomic for the same reason. However `s_controller_write_payload_size` must remain atomic to avoid UB (though I doubt it needs to be seq_cst), since it's being read without a lock held. This threading system may have race conditions, I'm not sure.
Along the way I also noticed that `ResetRumble()` (apparently called on …

Remove atomic usage and fix mutex locking in GCAdapter code

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h
Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

Relies on  #10563.  Restores the dual views ability that WX had, and improves on it.
Looking for input on how customizable it should be. Currently it's always 4 bytes per row and the left side is always hex. It auto chooses the size/columns based on what is on the right.  The second display type box, for bytes per row, doesn't do anything in dual view, because it's always 4 bytes or 8 bytes for a double.
I think the left side always being hex is fine.
Currently Double has a small breakpoint display bug.  I also just added the Hex8/Hex16 ability to the left side, so it got a little more complicated than just having Hex32. I'll maybe need to clean it up more.

Debugger MemoryWidget: Add dual views

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

Q0 is used as a scratch register by EmitBackpatchRoutine.
Fixes a vertex explosion in Spider-Man 2 that was uncovered by PR #10453.

JitArm64: Always lock Q0 in psq_stXX

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h
Source/Core/DolphinQt/Debugger/MemoryWidget.cpp

User-visible changes:
- Sidebar can now be resized by the user.
- Right-click menu only shows up when the clicked cell actually has meaningful options for it.
- Right-click menu now has the option to copy the current value of the cell to clipboard.
Internal changes mostly for readability:
- Less transient state on the MemoryViewWidget itself.
- Cells now hold information whether they are the row breakpoint cell or not (instead of that being determined by being in column 0).
- Cells now hold information whether they are a value cell with a valid value or not (which is used to enable/disable the Copy Hex and Copy Value options).

Qt/MemoryWidget: Light refactoring and quality of life features.

---

Source/Core/VideoBackends/Vulkan/ShaderCompiler.cpp

Two fairly minor improvements:
* Close the output stream on shader compile error before showing the panic alert: This fixes the file showing up as 0 bytes in Windows Explorer (although the file would still display properly when opened).
* Include the info log in the shader compile error panic alert: The other backends do this, and it is helpful for quickly identifying errors during development.
Here's what the warning looked like beforehand:
And here's the new warning:
And the relevant code on other backends, for reference:
https://github.com/dolphin-emu/dolphin/blob/2e01dc0c82b5f73215e3425ab45ff6c7ee50b389/Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp#L357-L376
https://github.com/dolphin-emu/dolphin/blob/2e01dc0c82b5f73215e3425ab45ff6c7ee50b389/Source/Core/VideoBackends/D3DCommon/S …

Vulkan: Improve shader compile error handling

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/Core/DolphinAnalytics.cpp
Source/Core/VideoBackends/D3D/D3DMain.cpp
Source/Core/VideoBackends/D3D12/VideoBackend.cpp
Source/Core/VideoBackends/Null/NullBackend.cpp
Source/Core/VideoBackends/OGL/OGLMain.cpp
Source/Core/VideoBackends/OGL/OGLRender.cpp
Source/Core/VideoBackends/Software/Clipper.cpp
Source/Core/VideoBackends/Software/Rasterizer.cpp
Source/Core/VideoBackends/Software/Rasterizer.h
Source/Core/VideoBackends/Software/SWRenderer.cpp
Source/Core/VideoBackends/Software/SWRenderer.h
Source/Core/VideoBackends/Software/SWmain.cpp
Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
Source/Core/VideoCommon/BPFunctions.cpp
Source/Core/VideoCommon/BPFunctions.h
Source/Core/VideoCommon/BPMemory.h
Source/Core/VideoCommon/BPStructs.cpp
Source/Core/VideoCommon/RenderBase.cpp
Source/Core/VideoCommon/Statistics.cpp
Source/Core/VideoCommon/Statistics.h
Source/Core/VideoCommon/VertexShaderManager.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

This fixes [the rendering issue in Major Minor's Majestic March](https://bugs.dolphin-emu.org/issues/12223).
There are some situations where the emulated scissor configuration results in multiple real scissors being needed.  I couldn't find an easy way to implement that on the hardware backends, but I did implement it in software.  For the hardware backends, I pick the biggest one.  This affects Major Minor, but only briefly during scrolling loading screens (right near the end and only for ~4 frames).  Compare frames [204](https://user-images.githubusercontent.com/8334194/145466628-d64f39a7-0c74-432b-a021-e892654b42a8.png) and [205](https://user-images.githubusercontent.com/8334194/145466693-8fc27e5f-b6f8-4a73-886b-08503bd411a2.png) in major_minor_loading_long.dff.  Here's what's drawn …

Rework scissor handling

---

Source/Core/VideoCommon/TextureCacheBase.cpp

Messed this up in #10592. It's harmless, but prints irrelevant error messages during the state size measuring step.

TextureCacheBase: Don't log error while measuring state size.

---

Source/VSProps/Base.props

mostly replaces some embedded paths with fake or relative paths, which keeps outputs identical even if built from different directories.

msbuild: improve reproducible builds

---

Source/VSProps/Base.props

This reverts commit f2c5c052bc5402856123b0f57c7c5a50be97ba49.
debuggers using path-based searching don't seem smart enough
to find a relative path if it's not relative to their pwd.
Using pdbaltpath is only really useful for sharing build outputs between different locations (e.g. between pr and release buildbots, with how windows buildbot is currently setup). Since we don't actually cache build outputs on windows yet and sharing between locations isn't a requirement for that, we can worry about the optimization later.

Revert "msbuild: use pdbaltpath to strip dirname of pdb"

---

Source/Core/Common/Inline.h

This is compiler dependent, not OS dependent.

Change _WIN32 check to a _MSC_VER check in Inline.h

---

Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h

u16 gets promoted to s32 where changing the uppermost bit is UB.

AX: prevent undefined behavior

---

Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/WiiUtils.cpp

#10611, but without the Qt parts. Restores the Online System Update to working order.
delroth set up a fake NUS server that implements the ``NetUpdateSOAP`` endpoint by returning the correct titles for each region along with the Wii U CDN URL. (There appears to be multiple URLs which point to the same CDN, which makes it possible to do things like download a Wii title from the Wii U CDN.) Responses from this endpoint were created by looking at [a sample response from the server when it was still running](https://gist.github.com/icefire/138604) along with [a complete list of titles for each region as archived by yellows8's bot](https://yls8.mtheall.com/ninupdates/reports.php?date=10-19-15_01-40-04&sys=rvl). 
For more technical information, see [this …

WiiUtils: Change default NUS Shop URL to Dolphin's fake NUS

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/CheckBoxSettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/FilePickerViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/InputBindingSettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RumbleBindingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SingleChoiceViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SliderViewHolder.java

Replaces calls to getAdapterPosition (deprecated) with getBindingAdapterPosition. It's more specific and functions the same way as before.

Android: Replace deprecated method calls for adapter position

---

Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/MMU.h

When I was creating PR #9964, I ended up refactoring WriteToHardware a bunch. This PR applies most of those refactorizations to ReadFromHardware.
See commit descriptions for details.

PowerPC: Refactor ReadFromHardware

---

BuildMacOSUniversalBinary.py
CMakeSettings.json
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/CheatSearchFactoryWidget.cpp
Source/Core/DolphinQt/Config/CommonControllersWidget.cpp
Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp
Source/Core/DolphinQt/Config/ToolTipControls/ToolTipWidget.h
Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/GBAWidget.cpp
Source/Core/DolphinQt/GameList/GameList.cpp
Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/QtUtils/ParallelProgressDialog.h
Source/Core/DolphinQt/RenderWidget.cpp
Source/Core/DolphinQt/TAS/IRWidget.cpp
Source/Core/DolphinQt/TAS/StickWidget.cpp
Source/Core/DolphinQt/TAS/TASInputWindow.cpp
Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp
Source/Core/DolphinQt/qt6.natvis
Source/VSProps/QtCompile.props
Source/VSProps/qtmoc.props

The main point of this PR is to generate builds that can be tested, track bugs and comments on the [qt submodule update](https://github.com/shuffle2/ext-win-qt/tree/qt6.3.0). Would love review of the [build config](https://github.com/shuffle2/ext-win-qt/blob/qt6.3.0/Qt6.3.0/dolphin-x64.yml). I was able to disable a significant enough portion of the Qt modules such that I could add the compressed pdbs into the repo and still come in at less total size than the previous commit.
I've removed the pdb archives from the qt repo to minimize size as much as possible, but not sure what the best way to keep them available for people is. any ideas?
An ARM64 build is [here](https://drive.google.com/file/d/1vKfsEoC7WPPFwv0IjE-axxk7BY3XVlZq/view?usp=sharing)
Some known issues:
None!, Find some!
Fixed …

update to Qt6 on windows, support Qt6 elsewhere

---

Source/Core/DolphinQt/Debugger/RegisterColumn.h
Source/Core/DolphinQt/Debugger/RegisterWidget.cpp

Adds new context options to change entire column's display type at once.  I simply named it "All Hexadecimal" etc.

Debugger RegisterWidget Add option to change column's display type

---

Source/Android/app/src/main/AndroidManifest.xml
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/AlertMessage.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatDetailsFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RunRunnableViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateRegionSelectDialogFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/SystemMenuNotInstalledDialogFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/SystemUpdateResultFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/ConvertFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThreadUtil.java
Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
Source/Android/app/src/main/res/values/styles.xml
Source/Android/app/src/main/res/values/themes.xml

themes.xml now contains a collection of colors, attributes, and styles. No visuals have changed, but this will allow for a more flexible theming system in the future for custom day/night/etc themes. This also removes a bunch of redundant code that is now written as global styles and inherited themes.

Android: Modernize theming system

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/State.cpp

This fixes ugly error messages (and potentially crashes, the state read logic doesn't seem to check if it reads past the end of the buffer...) when you try to load a GameCube savestate with MMU enabled when MMU is off and vice-versa.

HW/Memmap: Refuse to load savestate if memory settings are different.

---

Source/Core/DolphinQt/Config/ToolTipControls/ToolTipWidget.h

fixes balloon remaining onscreen when parent gets
hidden via escape key for example.
fixes https://bugs.dolphin-emu.org/issues/12891

Qt: hide balloon tooltip when parent gets hidden

---

Source/Core/DolphinQt/Settings/InterfacePane.cpp

Like #10484 but for the InterfacePane. Extracted from #10495 to reduce the size of that.

Qt/InterfacePane: Don't trigger config change events when populating GUI.

---

Source/Core/DolphinQt/Settings/GameCubePane.cpp

Like #10484 but for the GameCubePane. Extracted from #10495 to reduce the size of that.

Qt/GameCubePane: Don't trigger config change events when populating GUI.

---

Source/Core/DolphinQt/Settings.cpp

as a bonus, the buttons render with native windows style instead of the ugly boxy versions, too.
I've only tested with win11
before:
after:

qt/win: remove hack for tab bar scroll buttons

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h

More refactoring of this thing to make it more usable.
User-facing changes:
- Removes the (imo infuriating) behavior that clicking anywhere in the table centers the table on that row.
- Instead adds a scrollbar that can be used to navigate the view.
Keyboard keys (up/down/pageup/pagedown) can still be used like before, no major change there yet -- though they do now respect the bytes per row, which they didn't before.
Internal changes:
The table is now a member of the MemoryViewWidget rather than the widget itself. This was necessary because I made a custom scrollbar that can deal with the infinitely-long memory view (since it wraps around), and attached that to the side of the memory table but still handle it as part of the MemoryViewWidget. The scrollbar always jumps back to the center …

Qt/MemoryViewWidget: Replace the click-to-center behavior with a scrollbar.

---

Source/Core/Core/Movie.cpp

Previously, if a movie is started and its savestate is missing, then it'll just silently play the movie from the start of the game.  That's not great behavior, so I added a panic alert to this case:
I've hit this case because I renamed my movie file without renaming the savestate.  Other situations (such as the savestate being from an incompatible version) aren't covered (in the incompatible version case, you currently get an on-screen display message instead).

Show a panic alert if movie is missing its starting savestate

---

Source/Core/Core/HW/EXI/EXI.h

This warning was caused by #10364; see e.g. [this build log](https://dolphin.ci/#/builders/19/builds/5831).  The bug in question is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80351, and it seems to be solvable by explicitly using `std::initializer_list` instead of `auto`.  The warning is generated only for the first `auto` initializer list, but we need to change both `SLOTS` and `MEMCARD_SLOTS` as if only `SLOTS` is changed, then `MEMCARD_SLOTS` becomes the first `auto` initializer list and generates a warning.  An alternative solution is to mark `SLOTS` as `[[maybe_unused]]`, which does _not_ require changing `MEMCARD_SLOTS`, but that seems a bit silly.  (I've requested an account on the GCC bugzilla to add some additional notes there, but it hasn't been created yet.)

Work around false SLOTS defined but not used warning on GCC

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/AXStructs.h
Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp

Also more renaming. Not sure if fixing the ramp makes a noticeable difference anywhere.

AX: fix missing ramp of main surround channel

---

BuildMacOSUniversalBinary.py

CMake has trouble detecting Qt if only ``QT_DIR`` is specified. If we place the path to Qt on ``CMAKE_PREFIX_PATH`` as well, it will detect it fine.

BuildMacOSUniversalBinary: Place the Qt path on CMAKE_PREFIX_PATH

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp

In old GameCube titles the DPL2 bit implicitly activates the AUXB_LR channels. Also, setting the AUXA bit activates all three channels (LRS). This fixes the audio test in Rogue Squadron 2 ([issue 12902](https://bugs.dolphin-emu.org/issues/12902)).
The other commit is just a theoretical accuracy improvement for AXWii. In practice it should not affect any games.

AX: handle DPL2 mixer control in old GameCube titles

---

Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/HW/ProcessorInterface.h

Fixes unknown opcodes 0x0f and 0xff when resetting titles, e.g. https://bugs.dolphin-emu.org/issues/12492.
I was able to consistently reproduce and test this by recording a movie with the GameCube Preview Disc.  I eventually ended up getting lucky and reproducing the issue the first time around, giving a very short movie file that allowed for fast testing.  I also hex-edited the movie to set it to dual core, and confirmed that the same issue happened there (and the movies synced with that change, surprisingly).  [PreviewDiscUnknownOpcode.zip](https://github.com/dolphin-emu/dolphin/files/8076912/PreviewDiscUnknownOpcode.zip)
Here are some log files from reproducing the issue before and after this PR, with additional debug logging: …

ProcessorInterface: Implement PI_FIFO_RESET

---

docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex

I tested the DSP bootloading process mentioned here and determined that 1024 bytes are transferred during this process, at least with the other registers configured as they are in libogc.
I booted a simple payload which finished by setting a mailbox register to a specific value, and padded it with NOPs until that value no longer appeared in the mailbox.

Add tested DSP bootloading transfer size to docs

---

Source/Core/Core/Core.cpp
Source/Core/Core/Core.h
Source/Core/DolphinQt/Host.cpp
Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinQt/RenderWidget.cpp

The fix in PR #8715 worked for panic alerts from the CPU thread, but there were still problems with panic alerts from the GPU thread in dual core mode. This change attempts to fix those.
I have assumed that the reason we use `RunAsCPUThread` when calling `SetFullscreen` is because we want to wait for the GPU thread to be inactive. (Because it can't be the CPU thread itself that we're waiting for, right? The CPU thread shouldn't directly interact with `g_renderer`.) However, I'm not entirely sure about this. If my assumption was wrong, then this PR is probably not the best solution.

DolphinQt: Fix the panic alert deadlock, dual core edition

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp

No functional changes except that for AXGC we now read 9 * 3 = 27 u16 values from memory instead 32 (not sure why the old code did that).

AX: refactor buffer initialization

---

Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/VideoCommon/VideoBackendBase.cpp
Source/Core/VideoCommon/VideoConfig.cpp

This results in the list of available antialiasing modes being updated; before, it would only show the modes available for the adapter that was selected when the graphics window was opened (or the backend was last changed).
The list of available modes is updated by `GraphicsWindow::OnBackendChanged`'s call to `VideoBackendBase::PopulateBackendInfoFromUI`, and then `EnhancementsWidget::LoadSettings` updates the UI.  Both of these are connected to the `GraphicsWindow::BackendChanged` signal.
I have a dedicated NVIDIA GeForce GTX 1650 Ti GPU and also an integrated Intel GPU; the NVIDIA one supports up to 8x AA while the Intel one supports 16x (but becomes horrendously slow in that case).  The D3D "Microsoft Basic Render Driver" also claims to support 16x AA (but I don't think it actually …

Fix antialiasing modes being determined from the wrong graphics adapter

---

Source/Core/Core/DolphinAnalytics.cpp
Source/Core/Core/DolphinAnalytics.h
Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
Source/Core/VideoBackends/Software/SWVertexLoader.cpp
Source/Core/VideoCommon/CPMemory.h
Source/Core/VideoCommon/VertexLoader.cpp
Source/Core/VideoCommon/VertexLoaderARM64.cpp
Source/Core/VideoCommon/VertexLoaderBase.cpp
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexLoaderX64.cpp
Source/Core/VideoCommon/VertexLoader_Normal.cpp
Source/Core/VideoCommon/XFMemory.h
Source/UnitTests/VideoCommon/VertexLoaderTest.cpp

This is somewhat similar to #8717.  At least in some cases, on real hardware this mismatched configuration can result in a hang, but Dolphin was previously allowing it without any warnings (I ran into this [when experimenting with embossing](https://gist.github.com/Pokechu22/0589a46b2dea081e24470b3275766cc0)).
I've also added a check that the CP and XF matrix index registers match, since it's weird that they are duplicated (we currently always use the CP one with the hardware backends, and the XF one for the software renderer), and the XF input vertex spec register doesn't include a count for matrix indices (so if per-vertex matrix indices are enabled, it's not clear how XF knows which ones are in use).
<details><summary>Ways this could be triggered</summary>
As far as I can tell, this …

Show panic alerts if the CP configuration doesn't match the XF configuration

---

Source/Core/Common/Logging/Log.h
Source/Core/Common/Logging/LogManager.cpp
Source/Core/Core/HW/EXI/BBA/TAPServer_Apple.cpp
Source/Core/Core/HW/EXI/EXI_DeviceEthernet.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp
Source/Core/VideoCommon/FrameDump.cpp

I've gotten annoyed by accidentally trying to use fmt strings with `INFO_LOG`, so I've removed the printf-based logs (now only the `_FMT` variants remain).  This was originally planned in #9286 for after assertions were changed to fmt, which I did in #10209.  Renaming the `_FMT` variants to the original names could be done later on.
Note that the logging in FrameDump is receiving printf format strings and args from libav, so that still needs to handle printf strings.  #10572 added a separate logging method to handle this, but I've moved the formatting to within the libav log callback.  An alternative would be to keep `GENERIC_LOG_V` (possibly renaming it to `GENERIC_LOG_VPRINTF`), but it's only used here so I don't know how necessary that is.

Remove printf-style logging

---

Source/Core/Core/DSP/Interpreter/DSPIntCCUtil.h

I added this comment in #10045, but I specified "val1" twice by accident.

DSPInterpreter: Fix typo in isOverflow comment

---

Source/Core/DolphinQt/DolphinEmu.entitlements
Source/Core/DolphinQt/DolphinEmuDebug.entitlements

This allows the Steam overlay library to be injected into our process on macOS.

DolphinQt: Add com.apple.security.cs.allow-dyld-environment-variables to entitlements

---

Source/Android/app/src/main/res/layout/card_game.xml

Use strict dpi that follows the relative dimensions provided by GameTDB. Turns out this works for most of the games on the DB, but there are instances where images provided are not the typical 160x224 resolution. In that case, there will be small borders around the image.
Before landscape - 
After landscape - 
Example of non-standard res in master and this PR -

Android: Fix game card in landscape

---

Source/Core/Core/Config/MainSettings.cpp

Suggested in https://github.com/dolphin-emu/dolphin/pull/8067#discussion_r878611999.

MainSettings: Make MAIN_CUSTOM_RTC_VALUE default value less magical

---

Data/Sys/GameSettings/GPO.ini
Data/Sys/GameSettings/GPS.ini

Adjusted the texture accuracy setting to the safest value for both PSO Episode 1 & 2 and Episode 3, this fixes the issue displaying texts within the game where letters and numbers are randomly missing.

GameDB: Adjusted graphic settings for PSO EP1&2 and PSO EP3

---

Data/Sys/GameSettings/ROX.ini

This game has a chopping minigame that doesn't work without this setting.  There's a video and everything on our Wiki: https://wiki.dolphin-emu.org/index.php?title=Order_Up!
User on discord helped verify that this setting fixes it.  It still seems to struggle with very fast swings but I was unable to test it myself on Wii/Bluetooth Passthrough, so I don't know if that's just how the game is or if it's still a tad touchy.  Still, this makes it actually playable, to the point where the user could still get a "perfect" on the task.

INI: add RealWiiRemoteRepeatReports False to Order Up!

---

Source/Core/Core/Config/SessionSettings.cpp
Source/Core/Core/Config/SessionSettings.h
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/DVD/DVDInterface.h
Source/Core/Core/IOS/DI/DI.cpp

@JosJuice Is this what you had in mind?

IOS/DI: Fake the error 001 read when running DirectoryBlobs or Riivolution-patched games.

---

docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex

A typo I noticed.  I also changed it to a link to the ILRR instruction.
This also updates the history section for both this PR and #10662 - this is something the GFDL requires (and I'm not 100% sure that this is enough either).  Maybe git history is sufficient for this purpose (MediaWiki revision history is, to my understanding), but it's also useful to have a specific revision that can be pointed back to.  (It might be worth contacting Duddie if anyone knows how to to see about relicensing to CC-BY-SA or similar.)

docs/DSP: Fix "ILLR" typo in Instruction Memory section

---

Source/Core/Common/Logging/Log.h
Source/Core/Common/Logging/LogManager.cpp
Source/Core/Core/CMakeLists.txt
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/HSP/HSP.cpp
Source/Core/Core/HW/HSP/HSP.h
Source/Core/Core/HW/HSP/HSP_Device.cpp
Source/Core/Core/HW/HSP/HSP_Device.h
Source/Core/Core/HW/HSP/HSP_DeviceARAMExpansion.cpp
Source/Core/Core/HW/HSP/HSP_DeviceARAMExpansion.h
Source/Core/Core/HW/HSP/HSP_DeviceNull.cpp
Source/Core/Core/HW/HSP/HSP_DeviceNull.h
Source/Core/Core/HW/HW.cpp
Source/Core/Core/State.cpp
Source/Core/DolphinLib.props

Repurposed for just HSP support for now, since merging that will be easier and I can get to GB Player when this interface is merged.

Preliminary HSP support

---

Source/Core/Common/Network.cpp
Source/Core/Common/Network.h

Noticed this while trying to write up an explanation for how and why to use BitCast in #10690. Trivial change.

Common/Network: Use std::array in IPv4Header.

---

Source/Core/Core/State.h

This struct is directly serialized into a savestate, we probably shouldn't rely on implicit padding bytes...

Core/State: Make memory layout of StateHeader more explicit.

---

Data/Sys/GameSettings/GPO.ini
Data/Sys/GameSettings/GPS.ini

PSO EP1&2 and PSO EP3 tends to easily desync and crash the GPU/CPU threads when dual core mode is enabled (the default setting for most games on Dolphin) and since this game is constantly writing to your memory card while playing online, theres a chance these crashes will happen while the game is accessing/writing resulting in game data corruption making you lose all your progress and characters. So to avoid this, It's recommended to run this game in Single Core mode all the time.
Which why this PR is including now enabling Single Core Mode by default for both games.

GameDB: Enabled Single Core Mode for PSO EP1&2 and EP3 improving online game stability

---

Source/Core/DolphinQt/GameList/GameList.cpp

For whatever reason, QTableView [always has home/end move to the first/last column](https://github.com/qt/qtbase/blob/067b53864112c084587fa9a507eb4bde3d50a6e1/src/widgets/itemviews/qtableview.cpp#L1900-L1913) (though it also moves to the first/last row if control is held), even with `QAbstractItemView::SelectRows` and even though the documentation says [it should move to the top-left or bottom-right element](https://doc.qt.io/qt-6/qabstractitemview.html#CursorAction-enum).  This makes home/end useless for the list view in the game list.  This PR overrides it to treat it as if control is held when using home or end.
Note that the [list view](https://github.com/qt/qtbase/blob/067b53864112c084587fa9a507eb4bde3d50a6e1/src/widgets/itemviews/qlistview.cpp#L1287-L1290)'s home button handler …

GameList: Have home/end keys move to first/last row

---

Source/Core/Core/DSP/DSPTables.cpp
Source/Core/Core/DSP/Interpreter/DSPIntArithmetic.cpp
Source/Core/Core/DSP/Interpreter/DSPIntTables.cpp
Source/Core/Core/DSP/Interpreter/DSPInterpreter.h
Source/Core/Core/DSP/Jit/x64/DSPEmitter.h
Source/Core/Core/DSP/Jit/x64/DSPJitArithmetic.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitTables.cpp
Source/DSPSpy/tests/cmpaxh_test.ds
docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex

The old name implies that it works on the address registers (like `DAR`/`IAR`/`SUBARN`/`ADDARN`), while the new name is consistent with `TSTAXH` and `MULAXH`.  This PR also adds a test that covers `CMPAXH` and `TSTAXH`.  This PR is intended to be merged before #10692.
-----
Note that `CMPAR` wasn't included in the manual until #10048 (specifically 211c2b5d99e48966c816ff59554976d511cc09ea), but was described in some notes without giving it a name (on http://hitmen.c02.at/html/gc_tools.html for DSP Suite, look in the zip's gcdspsuite/doc/reverse.txt and reverse_new.txt):
```
0xc100 - 0xd100
|110r a001 ---- ----|
compare $acca with $(1a+r)
$acca < $(r1a)	28
$acca > $(r1a)	21
$acca = $(r1a)	25	// equal only if acc.1c == 0
```
In the initial megacommit, it existed in the table as CMPAXH and as …

DSP LLE: Rename CMPAR to CMPAXH

---

Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinQt/Settings.cpp

Remove a Windows/Qt5 only section of Main.cpp now that Windows has a minimum Qt version of 6.3.
The SetCurrentUserStyle comment was overly specific; the bug also occurs with light-mode macOS, Windows with Qt 6.3, or an empty stylesheet_name.

Windows: Remove unused Qt5 block and reference

---

Source/Core/Core/DSP/DSPAssembler.cpp
Source/Core/Core/DSP/DSPAssembler.h
Source/Core/Core/DSP/DSPCodeUtil.cpp
Source/Core/Core/DSP/DSPCore.h
Source/Core/Core/DSP/DSPDisassembler.cpp
Source/Core/Core/DSP/DSPTables.cpp
Source/Core/Core/DSP/DSPTables.h
Source/DSPSpy/tests/arith_test.ds
Source/DSPSpy/tests/cond_test.ds
Source/DSPSpy/tests/ld_test.ds
Source/DSPSpy/tests/neg_test.ds

Among other changes to the error/warning messages, this trims trailing newline characters in the line. Before (on windows) the \r would corrupt the output and make them very hard to understand (as the error message would be drawn over the code line, but part of the code line would peek out from behind it).
Other than that, it's mostly removal of magic numbers (or reduction in how magical they are, as I'm not touching some of the code involving `partype_t` currently but using the `DSP_REG_X` constants helps with it.)
For example, before, if you were to add `MOVR $acc1, $ac0.m` (invalid because the second operand of `MOVR` must be either hte low or high part of `$ax0` or `$ax1`, but I didn't realize this, and because of another typo) into `dsp_base_noirq.inc`, you would get this output:
``` …
```

DSPAssembler: Rework errors and warnings, and related cleanup

---

Source/Android/app/build.gradle
Source/Android/build.gradle
Source/Android/gradle/wrapper/gradle-wrapper.properties

the actual fix is just the AGP downgrade (see https://issuetracker.google.com/issues/232060576 - plz upvote that). 
currently active PRs which touch cmake files that are based on commits with AGP >= 7.1.0 would need to rebase on this commit.

fix the android buildbot

---

Source/Core/Common/FileUtil.cpp
Source/Core/Common/FileUtil.h

Launching and then immediately closing Dolphin results in 51 (out of 81 total) lines of "Common\FileUtil.cpp:916 I[COMMON]: GetSysDirectory: Setting to [Dolphin Sys path]:". Most lines happen during startup and thus only show up in dolphin.log but 10 also appear in the log widget. Starting a game creates more such lines.
Unless I've misunderstood something the Sys path is constant for any given Dolphin session, and so there's no reason to recreate it each time GetSysDirectory is called. 
This PR creates and logs the Sys directory path once, and also does some minor refactoring and removes the extraneous colon at the end of the line.

Remove GetSysDirectory spam

---

Source/Core/DolphinQt/CheatSearchWidget.cpp
Source/Core/DolphinQt/CheatSearchWidget.h
Source/Core/DolphinQt/CheatsManager.cpp
Source/Core/DolphinQt/CheatsManager.h
Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
Source/Core/DolphinQt/Debugger/BreakpointWidget.h
Source/Core/DolphinQt/Debugger/WatchWidget.cpp
Source/Core/DolphinQt/Debugger/WatchWidget.h
Source/Core/DolphinQt/MainWindow.cpp

When an address is sent to memory widget, it doesn't go in the memory address target box and must still be copied there before being able to get edited.  This is a bit annoying, but forcibly changing the target address could be annoying as well.  This wouldn't be a big issue if we could edit cells directly.  I think we need another PR to improve this some way.

Debugger MemoryWidget: Navigate to memory from breakpoint widget and cheat search.

---

Source/DSPSpy/main_spy.cpp

The current code expects new mail almost immediately after the last map was sent for it to be saved properly. However, I have a test program that ends up looping for 32768 iterations before it sends more mail; this resulted in an incomplete result dump. I've changed it to wait a frame between checking for mail, which solves that issue. This does slow down dumping, but the end speed matches the speed at which the UI updates the registers so this isn't a big deal (the UI waits a frame between mail normally). (Theoretically, it could take even longer for dumping to finish, so this is not a perfect solution. However, for tests that take that long to run, it would be better to save the existing results instead of re-running the test and saving that; that'd be something to do with later …

DSPSpy: Fix incomplete result dumps

---

Source/Core/Core/DSP/Jit/x64/DSPEmitter.h
Source/Core/Core/DSP/Jit/x64/DSPJitArithmetic.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitCCUtil.cpp

There were 3 bugs here:
- The input register for the full register wasn't actually being used; it was read into RCX but RCX wasn't used by Update_SR_Register16_OverS32 (except as a scratch register).  The way the DSP LLE recompiler uses registers is in general confusing, so this commit changes a few uses to have a variable for the register being used, to make code a bit more readable.  (Default parameter values were also removed so that they needed to be explicitly specified).
- Update_SR_Register16 was doing a 64-bit test, when it should have been doing a 16-bit test.  For the most part this doesn't matter due to sign-extension, but it does come up with e.g. `ORI` or `ANDI`.  This change might fix bugs in official uCode, but it's unlikely.
- Update_SR_Register16_OverS32 did the over s32 …

DSP LLE JIT: Fix Update_SR_Register16_OverS32

---

Source/Core/Core/DSP/Interpreter/DSPIntArithmetic.cpp
Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp
Source/Core/Core/DSP/Interpreter/DSPInterpreter.h
Source/Core/Core/DSP/Jit/x64/DSPJitArithmetic.cpp
Source/DSPSpy/tests/40bit_ins_test.ds
Source/DSPSpy/tests/40bit_test.ds
docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex

Along with various typo fixes in both the DSP manual and comments in Dolphin's DSP code.  The new sections are based on studying Dolphin's DSP interpreter, and not by hardware testing.
This is a draft because I am considering replacing the existing "Perform an additional operation depending on destination register." messages in various instructions with a more explicit back-reference to the "16-bit and 40-bit modes" subsection (along with adding it to any instructions where it's missing but exists in Dolphin), but haven't done so yet.

docs/DSP: Add sections on 16-bit and 40-bit modes and on main and extended opcode writing to the same register

---

Source/Core/DolphinQt/Settings/WiiPane.cpp

this was noticeable after resizing the config window.
before:  
after:

qt: fix wiipane usb list layout

---

Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/Settings.cpp
Source/Core/DolphinQt/Settings.h

fixes a crash on close
fixes 12924

qt: unregister Settings' DevicesChanged callback during shutdown

---

Source/Core/Core/DSP/Interpreter/DSPIntBranch.cpp
Source/Core/Core/DSP/Interpreter/DSPIntExtOps.cpp
Source/Core/Core/DSP/Interpreter/DSPIntLoadStore.cpp
Source/Core/Core/DSP/Interpreter/DSPIntMisc.cpp
Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp
Source/Core/Core/DSP/Interpreter/DSPInterpreter.h
Source/Core/Core/DSP/Jit/x64/DSPEmitter.h
Source/Core/Core/DSP/Jit/x64/DSPJitBranch.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitUtil.cpp

Discovered while working on #10692.  `LOOP` and `BLOOP` experience the same saturation as other instructions.  Documentation will be updated by the other PR.
Here's the relevant hardware test from #10692, as well as its results on master and this PR: [40bit_ins_test.zip](https://github.com/dolphin-emu/dolphin/files/8820890/40bit_ins_test.zip).  (The results are actually for running on #10715 versus running on #10715 + #10709 + this PR; the later combination gives results that exactly match real hardware.)

DSP LLE: Apply saturation to LOOP and BLOOP with $ac0.m and $ac1.m

---

Source/Core/Core/DSP/DSPAssembler.cpp
Source/UnitTests/Core/IOS/FS/FileSystemTest.cpp

Now that the nightly-generic builder is working it uncovered a couple warnings I haven't seen from the other builders.
The other warnings it gave are covered by #10624.

Fix warnings on generic builder

---

CMakeLists.txt
Source/Core/Common/GL/GLInterface/GLX.cpp
Source/Core/Core/IOS/FS/HostBackend/FS.cpp
Source/Core/DolphinQt/CMakeLists.txt

This PR adds an easy flag to disable/enable things necessary for a Steam build, and makes changes to DolphinQt to create a build that will run in the Steam Runtime.
I built and tested this PR with Steam Runtime version 1, ``scout``, using the revision currently being used in general availability with the Steam client ([which is what Valve recommends for games](https://gitlab.steamos.cloud/steamrt/scout/sdk)).
Building Dolphin for the Steam Runtime is just like building for a regular Linux system. However, it must must be done within the Steam Runtime environment to prevent system libraries leaking into the application. A chroot environment or Docker container can be used, as outlined [here](https://github.com/ValveSoftware/steam-runtime#building-in-the-runtime).
Some extra CMake flags are …

DolphinQt: Add support for a Steam Runtime build

---

Source/Android/app/src/main/AndroidManifest.xml

Without this, debug builds of Dolphin fail to launch. The OS tries to locate org.dolphinemu.dolphinemu.debug.DolphinApplication but fails to find it because its actual name is org.dolphinemu.dolphinemu.DolphinApplication.
Partially reverts PR #10649.

AndroidManifest.xml: Re-add package="org.dolphinemu.dolphinemu"

---

Data/Sys/GameSettings/RKA.ini

Ultimate Shooting Collection needs Medium Texture Cache for some text to render correctly.

Add Medium Texture Cache setting to Ultimate Shooting Collection INI.

---

Data/Sys/GameSettings/GK5.ini

This game has stale icache values in the logs during certain loadscreens, and after disabling them I was able to play through the entire game, with one crash that may have been related to savestates and memory cards since during that loadscreen it said the memory card did not match.
This does cause invalid reads to be spit out during parts of the game, but you can safely skip them.  Enabling MMU seems to surpress the invalid reads without side-effects, but the aforementioned memcard/savestate crash was with MMU on.
I did 100% complete the game with this set in order to verify that we can finally mark this annoying game as playable.

Disable icache emulation for Monster House

---

Source/Core/Core/MemTools.cpp

The parameter `send_msg` cannot be `nullptr` in the first developer betas of macOS Ventura and iOS 16. Fixes crashing when fastmem is enabled (https://bugs.dolphin-emu.org/issues/12944).

MemTools: Always provide a valid pointer in send_msg for mach_msg_overwrite

---

Tools/lint.sh

speedup for running script under wsl2 when sources are mounted from host

lint: use git.exe if the source resides on v9fs

---

Source/Core/Common/BitUtils.h

C++23 deprecates std::aligned_storage_t while alignas works since C++11.
This fixes issue 12925.

Common: replace std::aligned_storage_t with alignas

---

Source/Core/AudioCommon/Mixer.cpp
Source/Core/AudioCommon/Mixer.h
Source/Core/AudioCommon/WaveFile.cpp
Source/Core/AudioCommon/WaveFile.h

Fixes cases of audio dumps being "too loud" and in game audio controls having no effect within the dump.
See [Issue 12945](https://bugs.dolphin-emu.org/issues/12945)

Have audio dumps apply volume

---

Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/ConfigManager.h
Source/Core/Core/HW/EXI/EXI.cpp
Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.h
Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardRaw.h
Source/Core/Core/Movie.cpp
Source/Core/Core/NetPlayServer.cpp
Source/Core/DolphinQt/GCMemcardManager.cpp
Source/Core/DolphinQt/GameList/GameList.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/Settings/GameCubePane.cpp

I've been aware for quite some time now that our handling of raw memory card paths is [quite confusing and inconsistent](https://bugs.dolphin-emu.org/issues/12886). This should unify that into something sensible, hopefully breaking as few existing configurations as possible.
For details read the linked issue report, but in summary: Previously the code would behave sensibly if the path in the INI ended in `.{region}.raw`, and misbehave in various ways if it didn't. In particular, if the configured path contained no region specifier, the behavior *depended on whether the file existed or not*, which effectively picks a different file on the first run compared to subsequent ones. Changing the path in the GUI did not verify whether the path contained a region specifier, which could easily get …

Raw Memory Card Path handling unification and consistency fixes.

---

Source/Core/DiscIO/WIABlob.cpp

Makes dolphin able to create rvzs of Wii discs with a > 2mb chunk size without filling them with garbage.
`ProcessAndCompress` would pass `RVZPack` a pointer to a local single-group-sized buffer, but tell it to read from the offset that it would if that buffer was the size of a chunk, making it read past the end of the buffer for groups that weren't group 0.
Side note: 16mb zstandard chunks work just fine on modern computers for most games*, and decompress faster than 2mb lzma chunks
\* Games that use DTK audio have trouble due to DTK audio emulation not respecting disk seek times, but they have trouble at 2mb too

Fix creation of rvz with > 2mb chunk size

---

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp

There's a fun bug in SDL 2.0.22 where it'll crash on macOS if you try to init it on something other than the main thread
It's been fixed in the latest git releases, but 2.0.24 isn't scheduled for release for a while

InputCommon: SDL 2.0.22 init crash workaround

---

Source/Core/UICommon/AutoUpdate.cpp

www appears to just be using "win" for deciding which binary to serve, so add a new identifier for arm64

updater: use new platform id for win-arm64

---

Source/Core/UICommon/ResourcePack/Manager.cpp
Source/Core/UICommon/ResourcePack/Manager.h

Someone on Discord had an issue where Dolphin would crash immediately when opening it, and this turned out to be the cause. If you have a `.zip` file in the `ResourcePacks` folder that doesn't contain a manifest, `Init()` dereferences a null pointer trying to sort them.
While I was here I also adjusted the code so it doesn't re-parse the zip files on every single comparison operation.

ResourcePack: Avoid crashes on invalid packs during Init().

---

Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
Source/Core/Core/IOS/USB/Host.cpp
Source/Core/Core/IOS/USB/LibusbDevice.cpp
Source/Core/Core/LibusbUtils.cpp
Source/Core/Core/LibusbUtils.h
Source/Core/InputCommon/GCAdapter.cpp
Source/Core/UICommon/USBUtils.cpp

This PR adds logging when libusb functions fail, using `LibusbUtils::ErrorWrap` from #10604.
I haven't tested this much beyond confirming that it builds.  But hopefully adding additional error logging makes debugging easier.

Improve libusb error logging

---

Source/Core/VideoCommon/FPSCounter.cpp

This small PR makes it more clear that FPS_REFRESH_INTERVAL is referring to microseconds so it is renamed to FPS_REFRESH_INTERVAL_US

Rename FPS_REFRESH_INTERVAL in VideoCommon/FPSCounter

---

Source/Core/Core/DSP/DSPHWInterface.cpp

No interrupt is generated in this case. The homebrew liband uCode writes zero fairly frequently, so logging it results in spam.
For reference:
https://github.com/devkitPro/libogc/blob/6c104219be4f3741c59446948052311a405de7cf/libasnd/dsp_mixer/dsp_mixer.s#L334
https://github.com/devkitPro/libogc/blob/6c104219be4f3741c59446948052311a405de7cf/libasnd/dsp_mixer/dsp_mixer.s#L348
https://github.com/devkitPro/libogc/blob/6c104219be4f3741c59446948052311a405de7cf/libasnd/dsp_mixer/dsp_mixer.s#L385

DSPLLE: Don't log when DIRQ is set to 0

---

Source/Core/Core/DSP/Jit/x64/DSPJitBranch.cpp
Source/DSPSpy/tests/loop_counter_test.ds

The loop ends when the counter reaches 0, and the counter is unsigned; before, it was doing a signed 16-bit comparison if the value was less than or equal to 0 after subtracting 1 from the value.
This wasn't caught by #10716 because the saturation results in a value of 0x7fff or 0x8000, neither of which trigger the bug.
I ran into this when investigating the CARD uCode, as it ends up using BLOOP with a counter set to 0xFFFF if the input length is set to 0.  (This isn't something that happens in practice (as far as I can tell the input length is always 8 normally), nor is it behavior that seems _intended_, but it confused me because the interpreter and recompiler were giving different results.)

DSP LLE Recompiler: Fix LOOP and BLOOP when the counter is between 0x8001 and 0xFFFF

---

Source/.clang-format

From https://clang.llvm.org/docs/ClangFormatStyleOptions.html:
```
LS_Latest (in configuration: Latest) Parse and format using the latest supported language version. Cpp11 is a deprecated alias for Latest
```

Replace Cpp11 with Latest in .clang-format

---

Source/Core/Core/CMakeLists.txt
Source/Core/Core/IOS/Network/IP/Top.cpp

Currently, having an IPv6 nameserver as the first to the host makes Dolphin immediately fall back to the default/backup nameserver. This PR aims to find and use the host's first IPv4 nameserver, if possible.
This PR additionally aims to expand the amount of platforms using the host's first result. On macOS, this requires linking against `libresolv` as it's not within the standard library.

IP/Top: Expand host nameserver usage

---

Source/Core/Common/x64CPUDetect.cpp

this came up in conversation on irc.

windows: detect and warn if running x64 dolphin on arm64

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/GBA.cpp
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.h
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp

These are used by *all* uCodes, though not all uCodes support `MAIL_RESUME` or `MAIL_CONTINUE`.
Extracted from [my WIP card ucode HLE stuff](https://github.com/pokechu22/dolphin/tree/archive/dsp-hle-card-ucode-2), since this is also applicable to the homebrew asndlib/aesndlib ucode.

DSPHLE: Move CDD1 constants to UCodes.h

---

Source/Core/Core/HW/DSPHLE/DSPHLE.cpp
Source/Core/Core/HW/DSPHLE/MailHandler.cpp
Source/Core/Core/HW/DSPHLE/MailHandler.h
Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.h
Source/Core/Core/HW/DSPHLE/UCodes/CARD.cpp
Source/Core/Core/HW/DSPHLE/UCodes/CARD.h
Source/Core/Core/HW/DSPHLE/UCodes/GBA.cpp
Source/Core/Core/HW/DSPHLE/UCodes/GBA.h
Source/Core/Core/HW/DSPHLE/UCodes/INIT.cpp
Source/Core/Core/HW/DSPHLE/UCodes/INIT.h
Source/Core/Core/HW/DSPHLE/UCodes/ROM.cpp
Source/Core/Core/HW/DSPHLE/UCodes/ROM.h
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.h

Split from #10732.  This (specifically the halted change) fixes booting Datel titles with DSP HLE ([issue 12943](https://bugs.dolphin-emu.org/issues/12943)).

DSPHLE: Handle mail more accurately

---

Source/Core/VideoCommon/ShaderCache.cpp
Source/Core/VideoCommon/ShaderCache.h
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureConversionShader.cpp
Source/Core/VideoCommon/TextureConversionShader.h
Source/Core/VideoCommon/UberShaderPixel.cpp
Source/Core/VideoCommon/UberShaderPixel.h
Source/Core/VideoCommon/UberShaderVertex.cpp
Source/Core/VideoCommon/UberShaderVertex.h

- Adds names to ubershaders
- Removes palette from names of texture decoding shaders that don't require a palette
- Also prevents separate versions from being made for each palette type, since they don't use palettes

VideoCommon: Better shader names

---

Source/Core/Core/CMakeLists.txt
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp
Source/Core/DolphinLib.props

This PR adds an HLE version of the [libasnd ucode](https://github.com/devkitPro/libogc/blob/master/libasnd/dsp_mixer/dsp_mixer.s), which is used by older homebrew (and is simpler than the newer libaesnd ucode).
I've done very limited testing with the `oggplayer` and `mp3player` examples included in libogc ([these](https://github.com/dolphin-emu/dolphin/files/8931901/asnd.zip)), which covers a single voice with 16-bit mono or stereo samples (though the stereo samples use the same data for both channels).  For those, it works, but I'm not sure what else actually uses libasnd so I haven't tested further.
I've only implemented the newest version that's included with libogc. Older versions probably won't be _too_ hard to implement, as there have only been 3 commits on it, but I noticed that …

DSPHLE: Add HLE version of libasnd ucode

---

Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp

This was a conflict between 8a144a735f4116650f59e6931fed86c1c00fa03c and b063f15dccf030e9b4fdeac189f779181d25db9c; since #10763 had not been rebased, it built correctly, but once it was merged with master, #10761 was present and thus it failed to build.
Because of the build error, no entry will be visible for #10763 on https://dolphin-emu.org/download/ so I've titled this PR to mention the new feature, even though it was actually from the other PR.

DSPHLE: Add HLE version of libasnd ucode and fix build error

---

Source/Core/Core/HW/DSPHLE/MailHandler.cpp
Source/Core/Core/State.cpp

Should fix https://github.com/dolphin-emu/dolphin/pull/10761#issuecomment-1166286482 but I haven't actually verified it. They should definitely be stored in the state either way though.

DSPHLE: Add variables in CMailHandler to savestate.

---

Source/Core/Core/HW/DSPHLE/DSPHLE.cpp

`DSPHLE::Initialize` sets the halt and init bits to true (i.e. m_dsp_control.Hex starts as 0x804), which is reasonable behavior (this is the state the DSP will be in when starting a game from the IPL, as after `__OSStopAudioSystem` the control register is 0x804).
However, `CMailHandler::m_halted` defaults to false, and we only call `CMailHandler::SetHalted` in `DSPHLE::DSP_WriteControlRegister` when `m_dsp_control.DSPHalt` changes, so since `DSPHalt` defaults to true, if the first thing that happens is writing true to `DSPHalt,` we won't properly halt the mail handler.
Now, we call `CMailHandler::SetHalted` on startup. This fixes Datel titles when the IPL is skipped with DSP HLE (though this configuration only works once https://bugs.dolphin-emu.org/issues/8223 is fixed by #10746).
For …

DSPHLE: Properly reflect initial halt state in mail handler

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot.h
Source/Core/Core/Boot/Boot_BS2Emu.cpp

These values were obtained by setting a breakpoint at a game's entry point, and then observing the register values with Dolphin's register widget.
There are other registers that aren't handled by this PR, including CR, XER, SRR0, SRR1, and "Int Mask" (as well as most of the GPRs). They could be added in a later PR if it turns out that their values matter, but probably most of them don't.
This fixes Datel titles booting with the IPL skipped (see https://bugs.dolphin-emu.org/issues/8223), though when booted this way they are currently missing textures. Due to somewhat janky code, Datel overwrites the syscall interrupt handler and then immediately triggers it (with the `sc` instruction) before they restore the correct one. This works on real hardware due to icache, and also works in Dolphin …

BS2Emu: Set HID0/1/2/4 and MSR with correct default values

---

Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
Source/Core/DolphinQt/Config/Mapping/MappingWidget.h
Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.h
Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp
Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.cpp
Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h

Reimplemented feature from  #10665.
I also moved "Virtual Notches" to the new dialog.
Do we like that?
What should the setting be called? "Gate Size", "Gate Radius"?

ControllerEmu: Allow changing the target gate radius of octagon sticks.

---

Source/Core/Common/Network.cpp
Source/Core/Common/Network.h
Source/Core/Core/IOS/Network/Socket.cpp
Source/Core/Core/IOS/Network/Socket.h
Source/Core/Core/NetworkCaptureLogger.cpp
Source/Core/Core/NetworkCaptureLogger.h

Some Capcom games _(namely, Monster Hunter 3 and Monster Hunter G)_ use non-blocking connect then directly call some network/ssl functions. Unfortunately, it seems that mbedtls doesn't support SSL handshake when the connection is in progress (i.e. not fully completed yet). The same happens with network calls returning `ENOTCONN` instead of `EAGAIN`. In sum, the games will abort the connection if Dolphin isn't quick enough to connect before the network function is called. Obviously, it doesn't happen if you host locally the servers that the games are connecting to. However, it will happen if they are on the Internet and the network is too slow.
This PR refactors parts of the network code and fix some error codes. I'm unaware of other games affected by this issues. I wrote 2 hardware tests, …

Socket: Fix some non-blocking connect edge cases

---

Source/Core/VideoCommon/VertexShaderManager.cpp

Graphics mods have the ability to move objects by modifying the projection matrix (similar to how FreeLook works), however previous mods were impacting more draw calls than expected.  This is because we wouldn't revert the graphics mod projection until the emulated hardware received a new projection change.  This change will make the projection "dirty" triggering it on the subsequent draw, ensuring that the projection is properly reset.
Here's an unmodded example:
Here's a mod that moves the minimap (and removes the "quick menu") in master.  You can see it moves more than just the minimap:
Here it is in this PR, only the minimap is moved:

VideoCommon: fix projection graphics mod affecting more than intended

---

Source/Core/DolphinQt/Config/GraphicsModListWidget.cpp

Some other minor fixes to graphics mods.
1.  The way the graphics mods UI works is it allows you to change your settings but only saves them when the window closes (to avoid additional disk writes).  However, it was rather jarring when you hit "Reload" after making changes because it would revert to your previous save.  Now if you click "Reload" (to see new graphics mods or to pickup new changes), it will save first..then reload.
2. Add word wrap to the description.  Long descriptions would cause the UI to spaz out.  Now it works properly.
Before:
After:

More Graphics Mods Fixes

---

Source/Core/Common/Logging/LogManager.cpp
Source/Core/Core/HW/SI/SI_DeviceKeyboard.h

I decided to compile dolphin with clang and resolve some of the warnings that came up, there are a couple of warnings generated by code in Externals, mainly cubeb and mgba, that should be fixed upstream (maybe they already are), but combined with the other warning removal PR's this should make dolphin mostly warning-clean.

Resolve additional warnings generated by clang

---

Source/Core/Common/ChunkFile.h
Source/Core/Common/Logging/ConsoleListener.h
Source/Core/Core/DSP/DSPDisassembler.cpp
Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/State.cpp
Source/Core/DolphinQt/WiiUpdate.cpp
Source/Core/VideoBackends/Software/Rasterizer.cpp
Source/Core/VideoCommon/BPFunctions.h
Source/Core/VideoCommon/Statistics.cpp

These annoyed me, so I fixed them.
These warnings are being resolved by #10610
/Core/Common/FifoPlayer.cpp : void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct CPState’ with no trivial copy-assignment; use copy-initialization instead [-Wclass-memaccess]
/Core/VideoCommon/CPMemory.cpp : void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct CPState’ with no trivial copy-assignment; use copy-initialization instead [-Wclass-memaccess]
This warning is being resolved by #10374
/Core/Core/HW/EXI/EXI.h : 'ExpansionInterface::SLOTS’ defined but not used [-Wunused-variable]

Resolve Linux GCC Warnings

---

Source/Core/DolphinQt/Debugger/RegisterWidget.cpp

Before, Dolphin would crash if you right-clicked in the blank space on the bottom-right, or if you right-clicked outside of the table without having first clicked on a register. Now, the context menu properly appears, with only "update" listed (I'm not entirely sure what that does, though).
Note that right-clicking outside of the table will use the currently selected register's context menu (instead of the update-only one); this behavior existed beforehand.
I also did a quick check of other uses of `customContextMenuRequested`, and they all seem to check that a selection exists (or else don't depend on having a selection at all), though I wasn't too deep in this checking (as long as it looked like an `if`-statement existed, I decided it was probably good).

RegisterWidget: Fix crash when right-clicking when there is no selected cell

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h
Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

It seems to work fine, but not really happy with how I coded it.  It seems like MemoryView and Memory widget should share the same update functions, but I wasn't sure how to responsibly put that together.  
Was anyone else working on this?  Thought I'd PR it to open a discussion.

Debugger MemoryViewWidget: Allow direct editing of memory cells.

---

Source/Core/VideoCommon/AsyncShaderCompiler.cpp
Source/Core/VideoCommon/AsyncShaderCompiler.h
Source/Core/VideoCommon/ShaderCache.cpp

This PR refactors shader precompilation ("Compile shaders before starting") to be interruptable. Previously, user was unable to close emulation gracefully during that step and had to either wait or forcibly terminate the process.
Additionally, UI window will now clear after finishing or aborting shader precompilation - so ImGui's message box will not linger until game renders something.

Make shader precompilation interruptable

---

Source/Core/AudioCommon/Mixer.cpp
Source/Core/AudioCommon/Mixer.h
Source/Core/AudioCommon/WaveFile.cpp
Source/Core/AudioCommon/WaveFile.h
Source/Core/Core/HW/AudioInterface.cpp
Source/Core/Core/HW/AudioInterface.h
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/GBACore.cpp
Source/Core/Core/HW/SystemTimers.cpp
Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
Source/Core/Core/State.cpp

This PR aims to resolve issue 12951. Its current status right now should reduce the gradual desync, but not completely eliminate it. Eliminating it would be a bit complicated here, as either audio dumps would need to be reworked into some format that accepts non-integer sample rates (which I haven't has any luck finding such), or resampling the audio to an integer sample rate (probably the most "simple" here). Keeping this as draft for now.

Reduce gradual audio desyncing in dumps and apply the correct sample rate for GameCube audio

---

Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp

Loading configs while another thread is messing with stuff just doesn't feel like a good idea.  It's hard to tell how much `LoadConfig` and `UpdateReferences` overlap in object usage, but it's definitely not zero because Thread Sanitizer keeps complaining about things.
Hopefully fixes Wiimote Scanning Thread crashes on startup (where main thread calls `LoadConfig` while wiimote scanning thread is in `UpdateReferences`)

InputCommon/ControllerEmu: Use more locks

---

Source/Core/Common/FileUtil.cpp

`File::Copy()` fails with empty files because `<<` sets failbit on the destination stream if nothing was written. The macOS updater uses `File::Copy()` in a workaround for an OS quirk. A recent PR added empty files to the `Sys` folder, breaking the macOS updater.
Fixes https://bugs.dolphin-emu.org/issues/12968.

FileUtil: Only attempt to write to the destination in Copy if there is actually content to write

---

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
Source/Core/DolphinQt/Config/Mapping/IOWindow.h

The "Range" slider wasn't connected to anything.
The spin box behaved poorly because of the attempt to connect it to the slider.
I've removed the slider and relocated the spin box.
I've changed the maximum values to 1000% (for inputs) and 100% (for outputs).
A user in discord unsurprisingly made their rumble stop working with it set to like 104.
There's no use case for over 100 on outputs.
Negative values are still useful for inverting wheel force feedback.
I've renamed "Range" to "Multiplier".

DolphinQt: Renamed "Range" to "Multiplier" in advanced mapping window and improved UX.

---

Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.h

Reducing this value can produce a less jittery pointer with reduced drift correction.
A user reported they had better results with 1% vs the default 2%.
The best name for the setting that I could come up with is "Accelerometer Influence".
I think it's descriptive and accurate enough. Anything else I can think if is ambiguous or too long.

WiimoteEmu: Expose IMU pointing accelerometer weight setting.

---

Data/Sys/Load/GraphicMods/Super Mario Sunshine/metadata.json

Makes the goop look proper at high resolution without affecting the heat waves. Pretty self explanatory from the below screenshots, notice the reduced blockiness. I took a bit of a shotgun approach based on the goop map textures I observed in practice. More in-depth testing would be appreciated to see if there's any dimensions I missed.
Without graphics mod
With graphics mod

Data: Add Super Mario Sunshine goop map graphics mod

---

Data/Sys/Load/GraphicMods/Rune Factory Frontier/metadata.json

This was one of the very first games I tried (I really like Rune Factory games) when I was designing graphics mods but I somehow missed the EFB texture that defined bloom.  While testing the inputs/output PR, I took another look at the game and managed to find the effect that controlled bloom.

Data: Add Rune Factory Frontier bloom definition graphics mod

---

Data/Sys/Load/GraphicMods/Super Mario Galaxy/metadata.json

Just was looking at the wiki today and noticed it talked about bloom issues in Super Mario Galaxy.
It is most noticeable when selecting a Galaxy, not sure if it's anywhere else.  However, like SMG2, it seems that the bloom effect matches the DOF effect in size/format.
Bloom at 6x IR no mod:
Bloom at 6x IR with native resolution mod:

Data: add Super Mario Galaxy bloom definition graphics mod

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/Memmap.h
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/MMU.h

This is used when fastmem isn't available. Instead of always falling back to the C++ code in MMU.cpp, the JIT translates addresses on its own by looking them up in a table that Dolphin constructs. This is slower than fastmem, but faster than the old non-fastmem code.
This is primarily useful for iOS, since that's the only major platform nowadays where you can't reliably get fastmem. I think it would make sense to merge this feature to master despite this, since there's nothing actually iOS-specific about the feature. It would be of use for me when I have to disable fastmem to stop Android Studio from constantly breaking on segfaults, for instance.

JitArm64: Implement "soft MMU"

---

Source/Core/UICommon/UICommon.cpp

This PR adds support for ``portable.txt`` on macOS. Placing a file named ``portable.txt`` next to ``Dolphin.app`` will force Dolphin to create and use a user directory in the same folder as the app.
While this is a very un-Mac like behavior (apps aren't supposed to store files next to the app bundle!), it's useful for development.

UICommon: Add support for portable.txt on macOS

---

Data/Sys/GameSettings/GBZ.ini

Opening and closing menus have annoying purple flashing when XFB to Texture Only is enabled.

GameINI: Disable XFB to Texture Only with Resident Evil 0

---

Source/Core/VideoCommon/GeometryShaderGen.cpp
Source/Core/VideoCommon/TextureConversionShader.cpp
Source/Core/VideoCommon/TextureConverterShaderGen.cpp
Source/Core/VideoCommon/UberShaderPixel.cpp

Fix Direct3D shader warnings X3571 (negative pow() base), X4000 (potentially uninitialized variables), and X3557 (forced unrolling of single-iteration loop).
These warnings appear in both Direct3D 11 and 12. They all appear in Twilight Princess with Hybrid Ubershaders, though other games and settings probably trigger them as well.
Fixes most of [10578](https://bugs.dolphin-emu.org/issues/10578); I've been unable to trigger warning X3578 (Output value 'ocol1' is not completely initialized, see also [9994](https://bugs.dolphin-emu.org/issues/9994)) and so suspect it's been fixed in the meantime, but I haven't bisected it.

VideoCommon: Fix D3D shader compilation warnings

---

Source/Core/VideoCommon/ShaderCache.cpp

This probably causes the reported crashes on Steam Deck.

ShaderCache: Fix inverted usage of palette_format.

---

Externals/spirv_cross/CMakeLists.txt
Source/Core/VideoBackends/D3DCommon/CMakeLists.txt

#10673 broke CMake builds on Windows, this fixes it.

Fix CMake Windows build after #10673 (HLSL from SPIRV).

---

Source/Core/Common/Arm64Emitter.h
Source/Core/Common/BitUtils.h
Source/UnitTests/Core/PowerPC/JitArm64/MovI2R.cpp

Simplify logical immediate encoding logic.
This is based on the observation that if a valid repeating element exists, it repeats through `value`. Thus it does not matter which one you analyse. Thus we skip over the least significant element if LSB = 1 by masking it out with `inverse_mask_from_trailing_ones`, to avoid the degenerate case of a stretch of 1 bits going 'round the end' of the word.

Arm64Emitter: Simplify LogicalImm logic

---

Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
Source/Core/VideoCommon/DriverDetails.cpp
Source/Core/VideoCommon/DriverDetails.h
Source/Core/VideoCommon/UberShaderPixel.cpp

Intel's Metal driver seems to have issues with dynamic sampler indexing
Also includes a small performance fix for Intel on MoltenVK

VideoCommon: Fix ubershaders on MoltenVK Intel

---

Source/Core/Common/BitUtils.h

Came up when I was rebasing the Metal branch (which also added a ctz implementation)

Common: Fix CountTrailingZeros for weird compilers

---

Source/Core/Common/Network.cpp
Source/Core/Common/Network.h
Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp

In this PR, the code in Common/Network and BBA/Builtin is refactored a bit. A potential oversight regarding the IP header checksum is addressed. There should be no change behaviour beside that.
@schthack @nolrinale 
Could you please give this PR a try to make sure it doesn't introduce any regression?
This PR is ready to be reviewed & tested.

Common/Network+BBA/Builtin: Cleanup

---

Data/Sys/Load/GraphicMods/Sin and Punishment - Star Successor/metadata.json

Adds bloom definitions for Sin and Punishment: Star Successor for use with bloom removal and native resolution bloom.
Original
No bloom
Native resolution bloom

Add Bloom Definitions for Sin and Punishment 2

---

Source/Core/VideoCommon/VideoBackendBase.cpp

Removes the requirement that backends manually populate every field in `backend_info` (they now only have to populate features that differ from the default value)
Fixes an issue where switching from a renderer that supported Framebuffer Fetch (e.g. MoltenVK or Metal) to OpenGL would leave the fbfetch support flag enabled.
Alternative Option: Fix the one bug in OpenGL and hope it's the only one like it

VideoCommon: Clear backend_info before populating

---

Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VertexManagerBase.h

When using deferred readbacks, there was a system set up to not flush command buffers if multiple EFB copies were issued in succession, but it only ever checked whether it needed to flush when an EFB copy was issued, so things ended up looking like this (CPU/GPU activity traces from Metroid Prime 3 Elysia @ 3x IR):
After the change, which also rechecks whether it needs to flush after each draw:
Brings the scene in question from 53fps to 60fps on my laptop.
Side note, counter is updated after every EFB copy, so if the cutoff was 10 and the following was issued:
EFB Copy, 4 Draws, EFB Copy, 4 Draws, EFB Copy, 4 Draws, EFB Copy
there would be no flushes in the middle (or at the end).
No flush at the end is definitely a bug, but is no flushes in the middle a bug?  I went back and forth on …

VideoCommon: Remember to flush command buffers after multiple EFB copies

---

Source/Core/Core/Config/FreeLookSettings.cpp
Source/Core/Core/Config/FreeLookSettings.h
Source/Core/Core/FreeLookManager.cpp
Source/Core/DolphinQt/Config/FreeLookWidget.cpp
Source/Core/DolphinQt/Config/FreeLookWidget.h

Before, Free Look would accept background input by default, which means it was easy to accidentally move the camera while typing in another window. (This is because HotkeyScheduler::Run sets the input gate to `true` after it's copied the hotkey state, supposedly for other threads (though `SetInputGate` uses a `thread_local` variable so I'm not 100% sure that's correct) and for the GBA windows (which always accept unfocused input, presumably because they won't be focused normally).

Free Look: Add background input setting (disabled by default)

---

Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp
Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm

This is both unnecessary and not threadsafe.

InputCommon: Get rid of static strings.

---

Source/Core/DolphinQt/Settings/WiiPane.cpp

The current UI has a really long checkbox name, which looks kinda weird. Some strings also had problems obeying title case, making them stand out among the rest of the dialog.

DolphinQt: Make SD sync strings look nicer

---

Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/HW/EXI/EXI_DeviceEthernet.cpp
Source/Core/Core/NetworkCaptureLogger.cpp
Source/Core/Core/NetworkCaptureLogger.h
Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
Source/Core/DolphinQt/Debugger/NetworkWidget.h

This PR allows to dump BBA network traffic into a PCAP file.
It seems to produce a legit PCAP file when I entered LAN mode of Kirby Air Ride. I haven't tested it beyond this point.
A screenshot of the option in the Network widget:

NetworkCaptureLogger: Add GameCube BBA support

---

Source/Core/VideoBackends/OGL/OGLRender.cpp
Source/Core/VideoBackends/Software/Rasterizer.cpp
Source/Core/VideoBackends/Software/Tev.cpp
Source/Core/VideoBackends/Vulkan/VKPipeline.cpp
Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
Source/Core/VideoCommon/BPMemory.h
Source/Core/VideoCommon/DriverDetails.h
Source/Core/VideoCommon/GXPipelineTypes.h
Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/PixelShaderGen.h
Source/Core/VideoCommon/PixelShaderManager.cpp
Source/Core/VideoCommon/RenderState.cpp
Source/Core/VideoCommon/RenderState.h
Source/Core/VideoCommon/ShaderCache.cpp
Source/Core/VideoCommon/UberShaderPixel.cpp
Source/Core/VideoCommon/UberShaderPixel.h

Adds a fixup pass that runs between the pipeline uid cache and actual pipeline generation that applies fixups based on the current backend's supported features.
A number of bugs (in particular `BUG_BROKEN_DUAL_SOURCE_BLENDING`) found themselves spread across VideoCommon and the backends, with each place having to guess at what the other would do, risking a failed pipeline compile if any disagreed.  With the new implementation, a single pass runs over the entire pipeline at a point where all other decisions have been finalized, so it can make decisions based on what is actually about to happen, rather than trying to guess.
I'm not super happy with the new location either though.  Other recommendations welcome.
Reasons for the new location:
- The UID cache is shared among all backends and …

Add a post-cache shader UID fixup pass 

---

Source/Core/VideoCommon/TextureConversionShader.cpp
Source/Core/VideoCommon/TextureConverterShaderGen.cpp

Followup to #10466. Resolves the following error:
ERROR: 0:85: '&' does not operate on 'uvec3' and ‘int'
This is @tellowkrinkle’s fix.

Fix OpenGL error on M1 Mac.

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Core/Core.cpp
Source/Core/DolphinNoGUI/MainNoGUI.cpp
Source/Core/DolphinQt/HotkeyScheduler.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/UICommon/UICommon.cpp
Source/Core/UICommon/UICommon.h

We currently have two different code paths for initializing controllers: Either the frontend (DolphinQt) can do it, or if the frontend doesn't do it, the core will do it automatically when booting. Having these two paths has caused problems in the past due to only one frontend being tested (see PR #9086). I would like to get rid of the latter path to avoid further problems like this.

Require frontend to initialize controllers

---

Source/Core/VideoCommon/TextureConversionShader.cpp

Looks like a copy-paste gone wrong. The compute shaders for the other formats use a group size of 8 * 8, whereas the CMPR compute shader is supposed to use a flattened 64 * 1 as I understand it.

VideoCommon: Fix CMPR compute shader layout

---

Source/Android/jni/MainAndroid.cpp

Should fix https://bugs.dolphin-emu.org/issues/12980.

Android: Call WiimoteReal::InitAdapterClass before controller init

---

Source/Core/Core/IOS/IOSC.cpp
Source/Core/Core/State.cpp

See https://github.com/dolphin-emu/dolphin/commit/1f4ddea5f711a11df931d19f5b5d65264f8653a9#commitcomment-78962594

IOS: Add IOSC::KeyEntry::misc_data to savestate.

---

Source/Core/DiscIO/VolumeVerifier.cpp

One of the Dragon Quest X expansions (S4SJGD) uses lowercase instead of the usual uppercase for the IOS59 file on its update partition.

VolumeVerifier: Ignore case when looking for IOS on update partition

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/HeaderSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/HyperLinkHeaderSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/InputStringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SettingsItem.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/MenuTag.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/HeaderHyperLinkViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/HeaderViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/InputStringSettingViewHolder.java
Source/Android/app/src/main/res/layout/dialog_input_string.xml
Source/Android/app/src/main/res/values/arrays.xml
Source/Android/app/src/main/res/values/strings.xml

This adds xlink kai support to the android version of Dolphin, so multiplayer is possible from Android as well.
Below are some screenshots to show what these changes do:

Android: XLink Kai Android UI option

---

Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp

See https://forums.dolphin-emu.org/Thread-unable-to-pair-remotes-hci-command-timeout, which was apparently introduced by #10729.
My guess as to what's happening here is that `device_descriptor.iSerialNumber` is 0, and `libusb_get_string_descriptor_ascii` doesn't like 0 [as it indicates a special case](https://github.com/libusb/libusb/blob/ba698478afc3d3a72644eef9fc4cd24ce8383a4c/libusb/descriptor.c#L1092-L1102), returning `LIBUSB_ERROR_INVALID_PARAM` in that case (which matches the log). However, I haven't tested this change at all.

BTReal: Treat libusb_get_string_descriptor_ascii failure as non-fatal warning

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/WiiUtils.java
Source/Android/app/src/main/res/values/strings.xml
Source/Android/jni/WiiUtils.cpp

Android: Bring SD card settings up to date with DolphinQt

---

Source/Core/VideoCommon/VertexLoaderManager.cpp

https://bugs.dolphin-emu.org/issues/12977 indicates that this happens on startup of Spider-Man 2, even in single-core. I don't have the game, so I can't directly determine why this is happening, but presumably real hardware does not hang in this case, so we can make it less obtrusive.

Convert CP/XF matrix indices mismatch panic alert to a warning

---

Source/Core/VideoCommon/RenderState.cpp

Small fix for #10747
We don't use dual source blend for SrcColor and InvSrcColor, only SrcAlpha and InvSrcAlpha.
Fixes gpus using the `BUG_BROKEN_DUAL_SOURCE_BLENDING` bug on games that draw using `SrcColor` as a blend factor without using any of the SrcAlpha-based factors.
Found this after I made the same mistake in the Metal renderer.  Don't know what games it affects (if any), as the game that broke in Metal (Mario Sunshine) also used Src1Alpha as its SrcBlendFactor (and therefore wouldn't be affected here).

VideoCommon: Fix IsDualSrc check for dst blend factors

---

Readme.md

When building dolphin, the wiki has lots of helpful information for dependencies. I am proposing to add a direct link to that page on the wiki under the building for linux section on the README

Readme: Referencing the wiki when building for linux

---

Source/Core/VideoBackends/Metal/CMakeLists.txt
Source/Core/VideoBackends/Metal/MTLMain.mm
Source/Core/VideoBackends/Metal/MTLUtil.mm

In the spirit of keeping the differences between my iOS fork and upstream minimal (and since the Metal backend already has support for iOS), here's a bunch of changes to make sure Metal APIs that are unavailable on non-macOS platforms are not used when targeting non-macOS.

Metal: Prevent usage of macOS-only APIs on non-macOS platforms

---

Source/Core/Core/CMakeLists.txt
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.h
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp
Source/Core/DolphinLib.props

This PR adds an HLE version of the [libaesnd ucode](https://github.com/devkitPro/libogc/blob/master/libaesnd/dspcode/dspmixer.s), which is used by newer homebrew (particularly homebrew with MOD music).
The libaesnd is a more advanced compared to the libasnd ucode, in that it uses more DSP features (in particular the stack registers, the wrapping registers, the accelerator, and extended instructions), but the actual ucode is organized in a cleaner way so this was easier to port.  (That's not to say libasnd isn't impressive in its own way; it was developed when fewer DSP features were understood, and the tooling had to be developed with it.)
I've done limited testing with the [modplay example](https://github.com/dolphin-emu/dolphin/files/9007662/modplay.zip) included with libogc, and with …

DSPHLE: Add HLE version of libaesnd ucode

---

Source/Core/AudioCommon/CubebUtils.cpp
Source/Core/Common/IniFile.cpp
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/GeckoCodeConfig.cpp
Source/Core/Core/PowerPC/PPCSymbolDB.cpp
Source/Core/Core/PowerPC/SignatureDB/MEGASignatureDB.cpp
Source/Core/Core/TitleDatabase.cpp
Source/Core/DiscIO/VolumeVerifier.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/Settings/BroadbandAdapterSettingsDialog.cpp
Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.cpp
Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInput.cpp
Source/Core/InputCommon/ControllerInterface/OSX/OSX.mm
Source/Core/InputCommon/ControllerInterface/OSX/OSXJoystick.mm
Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp
Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
Source/Core/InputCommon/InputProfile.cpp

StripWhitespace maintains old behavior

StripSpaces: only strip spaces

---

Source/Core/Core/HW/HSP/HSP_DeviceARAMExpansion.cpp

Looks like the memcpy here had its args in the wrong order.

Fix ARAM Expansion Writes

---

Source/Core/Core/HW/DSPHLE/UCodes/AESnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.h
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp

The first version is exclusive to [EDuke32 Wii](https://wiibrew.org/wiki/EDuke32_Wii) (see https://bugs.dolphin-emu.org/issues/12990). The second version fixes a bug with `MAIL_TERMINATE` (that hasn't been merged into libogc, and currently only exists in Extrems' libogc2). Like with #10793, I did some checking to confirm that the source and binaries matched, and also checked padding behavior (see [aesnd_ucode_versions_extra.zip](https://github.com/dolphin-emu/dolphin/files/9185568/aesnd_ucode_versions_extra.zip)).
<details><summary>Hashes of various possible versions for search purposes</summary>
```
Hashes of EDuke32/compiled.bin: ector cd6b5364 crc 09f1147b adler f50b2b12 fletcher 5bc2a588; 03de bytes (01ef words)
Hashes of EDuke32/compiled_pad.bin: ector 5ad4d933 crc 97c86f4e adler …
```

DSPHLE: Support EDuke32 Wii libaesnd uCode

---

Source/Core/Common/ArmCPUDetect.cpp
Source/Core/Common/CPUDetect.h
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Common/x64CPUDetect.cpp
Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
Source/Core/VideoCommon/VertexLoaderX64.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/UnitTests/Common/x64EmitterTest.cpp

* ARM64: implement all detection for windows
* ARM64: implement model_name detection for macos, freebsd, improve on linux
* ARM64: report MIDR in standard format
* x64: report Family/Model/Stepping in standard format
* make reported summary a bit easier to parse
* remove unused flags
* added ARMv8 AFP detection on all non-macos platforms
Notably FMA4 is also not actually used; the emitter got support but the related ops are never used. I've only removed flags which are never referenced, so same may apply to other flags as well.

CPUDetect: improve win/arm64 support

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/AbstractCheat.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/Cheat.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/CheatsViewModel.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/GraphicsMod.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/GraphicsModGroup.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/ReadOnlyCheat.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatDetailsFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsDisabledWarningFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/GraphicsModsDisabledWarningFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/SettingDisabledWarningFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/layout/fragment_cheat_list.xml
Source/Android/app/src/main/res/layout/fragment_cheat_warning.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Android/jni/AndroidCommon/IDCache.cpp
Source/Android/jni/AndroidCommon/IDCache.h
Source/Android/jni/CMakeLists.txt
Source/Android/jni/Cheats/GraphicsMod.cpp
Source/Android/jni/Cheats/GraphicsModGroup.cpp
Source/Core/DolphinQt/Config/GraphicsModListWidget.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.h

Because PR #10518 (graphics mods) was merged right before the previous progress report, I didn't have time to make graphics mods available in the Android GUI in time before the progress report. But let's get it merged in time for the next progress report, shall we?

Android: Add graphics mods support to GUI

---

Source/UnitTests/Core/DSP/HermesText.cpp

Most of these correspond to changes made in devkitPro/libogc@b1b8ecab3af3745c8df0b401abd512bdf5fcc011.
The numeric vlaues of ACC0 and ACC1 in Dolphin are different (see b06d38389bddf9fc5962aecbe1b31292a71b80a5, though I'm not sure when this difference first appeared). Technically it's not even necessary to list the registers at the start like this anymore, but old programs do it, so it seems useful to have a test that covers it.
The binary itself does not need to be changed; the warnings were simply stating that "although you wrote $ACL0, the generated binary instead is using $ACC0" or similar; by changing the code to use $ACC0 directly the warnings are resolved.
These warnings were introduced by #10750, which added `HermesTest` based on data that was already in the repo.

UnitTests: Fix warnings from HermesText

---

Externals/zlib-ng/CMakeLists.txt

This should hopefully fix https://github.com/dolphin-emu/dolphin/pull/10888#issuecomment-1196214126
@theofficialgman please verify.

CMake: Set SKIP_INSTALL_ALL for zlib-ng to avoid installing it.

---

Source/Core/Common/Logging/Log.h
Source/Core/Common/Logging/LogManager.h

Adding this due to 14 days of on and off debugging all because of the last log type being wrong, this will just grab that last type automatically.

LogManager: Dynamically get last log type

---

Source/Core/Common/Image.cpp

😳forgot to put IEND in the png

SavePNG: make sure to finalize image file

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/DiscIO/DirectoryBlob.cpp
Source/Core/DiscIO/DirectoryBlob.h
Source/Core/DiscIO/RiivolutionParser.cpp
Source/Core/DiscIO/RiivolutionParser.h
Source/Core/DiscIO/RiivolutionPatcher.cpp
Source/Core/DiscIO/RiivolutionPatcher.h

As far as I can tell, Riivolution cannot do this on console (probably because it's not very useful on Wii games?). So here's a custom extension for it.
These work exactly like the `file` and `folder` patch commands but use `dolphin_sys_file` and `dolphin_sys_folder` instead, so eg:
```
<dolphin_sys_file external="bi2.bin" disc="/bi2.bin" />
```
If you have other suggestions for how to do this, feel free, but I think this is a fairly straightforward solution to the problem.
(Implements a request from https://forums.dolphin-emu.org/Thread-riivolution-replace-main-dol)

Riivolution: Add custom extension to patch boot.bin, bi2.bin, and apploader.img.

---

Source/Android/app/src/main/res/values/arrays.xml
Source/Core/Core/HW/EXI/EXI_Device.h

The Broadband Adapter Option names were a bit confusing before, so let's clean them up.

BBA - Rename Built In BBA to BBA (HLE)

---

Source/Core/Core/HW/DSPHLE/UCodes/AESnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.h
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp

Here are some tests with the current libogc and also extremscorner/libogc2@5cf525b151f3399a26176edaae23e9e037732c1d and extremscorner/libogc2@ac91c274586509d77244b9f225868164f7bb148d. `modplay` has been edited to call `AESND_Reset()` before `exit(0)`, which correctly results in a hang on DSP LLE and a warning log on DSP HLE for all versions other than the most recent libogc2 version. All have had their makefiles edited to have `LIBS` use `~/dkp/libogc2/lib/wii/libaesnd.a` or `~/dkp/libogc2/lib/wii/libasnd.a` instead of `-laesnd` or `-lasnd`. Before, the libogc2 versions would result in an unknown ucode CRC. [audio_examples.zip](https://github.com/dolphin-emu/dolphin/files/9194427/audio_examples.zip)
I also tested https://wiibrew.org/wiki/OpenTTD and confirmed that its audio plays …

DSPHLE: Support padded versions of libasnd and libaesnd uCodes

---

Source/Core/Core/HLE/HLE_OS.cpp

The hooks that call these are Start hooks, so the real PPC function is called afterwards and takes care of any state changes.

HLE_OS: Don't modify emulated state in printf hooks.

---

Source/Core/Core/PowerPC/PPCSymbolDB.cpp

It's easiest to illustrate the bug that I fixed with an example from System Menu 4.3U (the functions I'm using here are arbitrary, chosen just because they're short):
|Step|Before|After|
|-|-|-|
|Set address to 815344f0|![image](https://user-images.githubusercontent.com/8334194/181865460-0cb29dd4-a104-43af-8bce-ff0f2d5c98fb.png)|![image](https://user-images.githubusercontent.com/8334194/181865464-1526c7f9-5e82-4cce-8973-bfe81a1e24d2.png)|
|Add function at 815344f4|![image](https://user-images.githubusercontent.com/8334194/181865465-38155fc7-56c4-47bd-b035-ec39114a0a46.png)|![image](https://user-images.githubusercontent.com/8334194/181865466-40752915-0fb1-46d5-8e56-92be2f86ead5.png)|
|Add function at 8153450c|![image](https://user-images.githubusercontent.com/8334194/181865468-f44addc1-9c86 …

PPCSymbolDB: Fix getting symbol for the last function

---

Source/Core/Common/Crypto/SHA1.cpp

there's no emitted code difference, it's only a cast.

SHA1/arm64: fix casting warning on certain gcc

---

Source/VSProps/Configuration.Base.props

allows using arm64-native toolchain on arm64.

msbuild: set PreferredToolArchitecture based on host OS arch

---

Source/Core/Core/HW/GPFifo.cpp
Source/Core/Core/HW/GPFifo.h
Source/Core/Core/HW/MMIO.h
Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/State.cpp
Source/UnitTests/Core/MMIOTest.cpp

See #10454. Fixes https://bugs.dolphin-emu.org/issues/12981. Only the last commit has behavior differences; the rest are refactoring.
Before #10454, writing 1 to PI_FIFO_RESET would do nothing (this logging is from [a modified build](https://github.com/Pokechu22/dolphin/tree/archive/extra-unknown-opcode-logging-2)):
```
VideoCommon\CommandProcessor.cpp:98 W[CP]: Dumping fifo information: Reset
CP: Read 0078fda0 Write 0078fda0 Dist 00000000/00000000 (should be equal)
GP fifo: Size 1b
33 99 ff ff 00 00 00 00 3f 80 00 00 61 20 15 61 56 61 21 3d 53 35 61 40 00 00 17
Video: Read 001c8f99 Write 001c8fe0 Dist 00000047 (computed)
81 00 04 42 b6 1e ea 43 38 e3 4c 33 99 ff ff 00 00 00 00 00 00 00 00 42 ef b8 84 43 38 e3 4c 33 99 ff ff 3f 80 00 00 00 00 00 00 42 ef b8 84 43 5f 49 b2 33 99 ff ff 3f …
```

ProcessorInterface: Reset both GPFifo and Fifo on PI_FIFO_RESET

---

Source/Core/Common/CMakeLists.txt
Source/Core/Common/Crypto/AES.cpp
Source/Core/Common/Crypto/AES.h
Source/Core/Core/IOS/ES/TitleManagement.cpp
Source/Core/Core/IOS/IOSC.cpp
Source/Core/Core/IOS/WFS/WFSI.cpp
Source/Core/Core/IOS/WFS/WFSI.h
Source/Core/DiscIO/NANDImporter.cpp
Source/Core/DiscIO/NANDImporter.h
Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DiscIO/VolumeWii.cpp
Source/Core/DiscIO/VolumeWii.h
Source/Core/DiscIO/WIABlob.cpp

Similar to the SHA1 PR, creates a wrapper around the "generic" path and overrides for arch-specific accelerated implementation.  
Unlike SHA1 PR, this changes the API, so callers can manage IV and data buffers better, resulting in less data movement and more clarity about when IV is being updated or not.
In testing, VAES.256 instructions did offer decent further speedup on x64, but at the moment, it doesn't seem worth increasing the instruction set support matrix, maybe in the future.
Time for `DolphinTool verify -a sha1` on a wii game stored as gcz, in seconds:
| cpu | master (no sha1 nor aes) | sha1+aes |
| -------- | -------- | -------- |
| amd zen2 | 55 | 9 |
| qc sq1 | 69 | 15 |
It's restricted to `-a sha1` to cut out md5, which is not optimized and would therefor cause all timings …

Implement hw accelerated AES

---

Source/Core/Common/Hash.cpp
Source/Core/Common/Hash.h
Source/Core/DiscIO/VolumeVerifier.cpp
Source/Core/VideoCommon/NativeVertexFormat.h
Source/Core/VideoCommon/TextureCacheBase.cpp

For "larger" buffer sizes, like those used by `CompressedBlobReader`, I've seen it be up to 20x faster (smaller buffers are generally faster as well, but not by as large a margin). Admittedly it's still a really small amount of wall clock time either way. 
edit: actaully looking more, this seems to be a large speedup for `CompressedBlobReader` use cases that read larger chunks. Haven't measured exactly, but the adler32 call for netplay's 8MiB chunks goes from taking 12-13% of *total* time, to < 1% of it (zlib-ng has chosen `adler32_avx2` on my system, fwiw)

Common/Hash: use zlib-ng for adler32. small cleanups.

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp

"Common/GekkoDisassembler.h" became used by Release builds with commit 77e9aa48bc217f9143d7ee2dca4b213a1505a02f, but this got left in by mistake.

Remove Vestigial Preprocessor Block in Jit64/Jit.cpp

---

Source/Core/Core/PowerPC/PPCCache.cpp
Source/Core/Core/PowerPC/PPCCache.h
Source/Core/Core/State.cpp

These lookup tables total 4 megabytes, and contain data that's entirely redundant to the actual cache state (as part of an optimization, though I'm not sure whether the optimization actually is useful). This change instead recomputes these lookup tables when loading the state (which involves filling the lookup table with a marker (0xff), and then setting the 128 * 8 valid entries (1 kilobyte)).
This is intended to be a simplified version of #10826 (which I have further plans for, and which currently removes the lookup table entirely).

PPCCache: Stop storing lookup table in savestates

---

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp

This PR adds minimal IGMP support. It doesn't seem to provide any noticeable benefit. The IGMP packets are sent to the router to register to a multicast address. It's used just before the games start communicating via the SSDP multicast address.

BBA/BuiltIn: Add minimal IGMP support

---

Data/Sys/GameSettings/RLI.ini

See https://bugs.dolphin-emu.org/issues/12987. The alpha value of 0x82 was determined by disabling all objects other than the highlight (and object 0 which clears the screen) in the hardware fifoplayer ([image](https://user-images.githubusercontent.com/8334194/182483314-c85aa06b-5986-4fac-ba26-68137736c0c3.png)), and then checking the output color (which is 0xAAAAAB or 0xABABAB depending on the pixel). [0x82 gives the closest result](https://user-images.githubusercontent.com/8334194/182483706-a908cf56-517b-4989-9815-c709f562a7fb.png) (though it's not a perfect match for every pixel, likely due to other slight inaccuracies with lighting). After that I compared across all of the provided fifologs, and things seem to be a generally good match (some differences are a value of 3, but I think …

GameSettings: Set MissingColorValue for Lego Indiana Jones 1

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java

Without this, if the user finishes selecting a directory before directory initialization finishes, `MainPresenter.onDirectorySelected` will segfault when trying to read the `MAIN_RECURSIVE_ISO_PATHS` setting.
An alternative would be to use`AfterDirectoryInitializationRunner` after the user selects the directory instead of before, but it might be confusing for the user to deal with the usage statistics prompt when they were expecting to add a folder.

Android: Use AfterDirectoryInitializationRunner on FAB press

---

Source/Core/Common/Image.cpp
Source/Core/Common/Logging/LogManager.cpp
Source/Core/Common/Logging/LogManager.h
Source/Core/Common/Profiler.cpp
Source/Core/Common/Timer.cpp
Source/Core/Common/Timer.h
Source/Core/Core/Core.cpp
Source/Core/Core/Core.h
Source/Core/Core/DolphinAnalytics.cpp
Source/Core/Core/HW/DVD/DVDThread.cpp
Source/Core/Core/HW/SystemTimers.cpp
Source/Core/Core/IOS/DolphinDevice.cpp
Source/Core/Core/IOS/DolphinDevice.h
Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
Source/Core/Core/IOS/USB/Bluetooth/BTReal.h
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/State.cpp
Source/Core/VideoCommon/FPSCounter.cpp
Source/Core/VideoCommon/HiresTextures.cpp
Source/Core/VideoCommon/OnScreenDisplay.cpp
Source/Core/VideoCommon/PostProcessing.cpp
Source/Core/VideoCommon/RenderBase.cpp

- refactors Common::Timer to be much simpler and (hopefully) clear
- moves unrelated code out of Common::Timer
- Windows: disables some recent power throttling OS features. I'm not sure how effective this is, someone should test on laptop or something.
- internally uses `std::chrono` in most places

Timer improvements

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

If a 64-bit register is passed to WriteConditionalExceptionExit, the LDR instruction in it will read too much data. This seems to be harmless right now, but causes problem in one of my PRs.

JitArm64: Pass 32-bit temp GPR to WriteConditionalExceptionExit

---

Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/DVD/DVDInterface.h
Source/Core/Core/HW/Memmap.cpp

The masking was removed in d3aad1d6d527a06166806d38bd065ab1d7484d50, based on a Wii hardware test. Based on https://bugs.dolphin-emu.org/issues/12970 the masking should apply in GameCube mode, though. (I have not actually tested this, as I do not have easy access to a GameCube.)

DVDInterface: Mask upper bits of DIMAR in GC mode

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.h
Source/Core/Core/HW/DSPHLE/UCodes/CARD.cpp
Source/Core/Core/HW/DSPHLE/UCodes/CARD.h
Source/Core/Core/HW/DSPHLE/UCodes/GBA.cpp
Source/Core/Core/HW/DSPHLE/UCodes/GBA.h
Source/Core/Core/HW/DSPHLE/UCodes/INIT.cpp
Source/Core/Core/HW/DSPHLE/UCodes/INIT.h
Source/Core/Core/HW/DSPHLE/UCodes/ROM.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.h
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.h
Source/Core/Core/State.cpp

The accuracy improvements are:
* The request mail must be 0xabba0000 exactly; both the low and high parts are checked
* The address is masked with 0x0fffffff
* Before, the global state meant that after the GBA uCode had been used once, it would accept 0xcdd1 commands immediately. Now, it only accepts them after execution has finished.
This is somewhat based on my WIP [HLE version of the Card uCode](https://github.com/Pokechu22/dolphin/blob/archive/dsp-hle-card-ucode-2/Source/Core/Core/HW/DSPHLE/UCodes/CARD.cpp), which the GBA uCode has some similarities with. I briefly checked the accuracy changes above, but I haven't done a thorough read-through of the GBA uCode myself.
This PR also bundles #10753.

DSPHLE: Eliminate global state in GBA and AX uCode + accuracy improvements

---

Source/Core/VideoCommon/VertexShaderManager.cpp

This normalization was added in 02ac5e95c84a1d9a46df1dc4102342fb653e36ee, and changed to use floats in 4bf031c0646e91b35777f1ba4e2b0328063bb666.  The conversion to floats means that sometimes there is insufficient precision for the normalization process, which results in values of NaN or infinity.  Performing the whole process with doubles prevents that, but games also sometimes set the values to NaN or infinity directly (possibly accidentally due to the values not being initialized due to them not being used in the current configuration?).
The version of Mesa currently in use on FifoCI (20.3.5) has issues with NaN.  Although this bug has been fixed (https://gitlab.freedesktop.org/mesa/mesa/-/commit/b3f3287eac066eae16dce0e47aad3229dcff8257 in 21.2.0), FifoCI is stuck with the older …

Sanitize and use increased precision when normalizing light directions

---

Source/Core/VideoCommon/Spirv.cpp

See baldurk/renderdoc#2673 (and baldurk/renderdoc#2337) for more context; this fixes viewing the shader source in renderdoc v1.21. `stage_filename` is "vs", "gs", "ps", or "cs" for vertex, geometry, fragment [i.e. pixel], and compute shaders respectively (see `CompileVertexShader` etc. in the same file).

Vulkan: Call setSourceFile in addition to addSourceText

---

Source/Core/VideoCommon/Spirv.cpp
Source/Core/VideoCommon/VideoConfig.h

Prior to 7854bd71098fe556ddc9839ad08d27fab7ecba33, this was used by the debugger for the OpenGL and D3D9 plugins to control logging (via PRIM_LOG and INFO_LOG/DEBUG_LOG in VideoCommon code; PRIM_LOG was changed in 77215fd27ccb7cdeb82fed24a7a8d4d4ad4c33a4), and also framedumping (removed in 64927a2f81fe64503060c949ead525995fd63a2a and 2d8515c0cf754806dc38222c4461053e12df1194), shader dumping (removed in 2d8515c0cf754806dc38222c4461053e12df1194 and this commit), and texture dumping (removed in 54aeec7a8ff6b6e5d050637b6cce8df6d9a8b633). Apart from shader dumping, all of these features have modern alternatives, and shader source code can be seen in RenderDoc if "Enable API Validation Layers" is checked (which also enables source attachment), so there's no point in keeping this around.

VideoCommon: Remove old iLog field

---

Data/Sys/GameSettings/SGL.ini
Data/Sys/GameSettings/SGLEA4.ini

See https://bugs.dolphin-emu.org/issues/12436 for the black screen issue. I only own a US copy, so the patch only exists for the US release, but (assuming the EU release has debug symbols too) it shouldn't be too hard to create one for it. The patch isn't enabled by default because ideally we'd instead fix the underlying issue instead.
The texture cache issue is only visible when the black screen issue is fixed.

GameSettings: Use Safe Texture Cache and add patch for black screens for Gormiti: The Lords of Nature!

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp

This command does not upload the MAIN buffers to CPU memory. This was functionally fixed in f11a40f85806e2fa69ef2bb8d7513d580fedff69 without updating the comments and variable names.

AX: fix comments and variable names (NFC)

---

Source/Core/Core/HW/WiiSave.cpp

this appears to have caused a crash for a user, but I haven't gotten confirmation this actually fixes their crash (I think they may have nuked everything and started fresh)
i tend to think their actual corruption happened before this, but this check should be there anyway, I think.
related: it's gross to have this huge thing on the stack

WiiSave: protect against a stack buffer overflow

---

Source/Core/Common/Timer.cpp

People really like running old OS
fixes https://bugs.dolphin-emu.org/issues/13007

back out using std::chrono for timezone stuff

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Core/Host.h
Source/Core/Core/IOS/DolphinDevice.cpp
Source/Core/DolphinNoGUI/MainNoGUI.cpp
Source/Core/DolphinQt/Host.cpp
Source/Core/DolphinTool/ToolHeadlessPlatform.cpp
Source/Core/UICommon/DiscordPresence.cpp
Source/Core/UICommon/DiscordPresence.h
Source/DSPTool/StubHost.cpp
Source/UnitTests/StubHost.cpp

This adds ioctlvs to /dev/dolphin that allows a game mod or homebrew running under Dolphin to set custom Discord rich presence client IDs and statuses. This can be used for mods to show more context about what's being done in-game (what stage/track/song is being played in-game, the user's current star/coin progress, etc) to the user's Discord status.
The basic flow is as follows:
- Guest Wii software calls IOCTL_DOLPHIN_DISCORD_SET_CLIENT on /dev/dolphin with input vector 0 set to the Discord client ID.
- The Wii software then can call IOCTL_DOLPHIN_DISCORD_SET_PRESENCE, providing each input value (aside from party ID and secrets) as 10 individual input vectors.
- When Dolphin next loads a title or closes the game, the original Dolphin client ID is re-applied along with the original …

Add Discord presence ioctlv to /dev/dolphin

---

Source/Core/Common/Arm64Emitter.cpp

This was causing a bug in the rounding of paired single multiplication operands. If Force25BitPrecision was called for quad registers, the element size of its ADD instruction would get treated as if it was 16 instead of the intended 64, which would cause the result of the calculation to be incorrect if the carry had to pass a 16-bit boundary.
Fixes one of the two bugs reported in https://bugs.dolphin-emu.org/issues/12998.

Arm64Emitter: Fix encoding of size for ADD (vector)

---

Source/Core/Core/PowerPC/Interpreter/Interpreter_FPUtils.h

Fixes the Dolphin bug mentioned in https://github.com/dolphin-emu/hwtests/issues/45.
Because this doesn't fix any observed behavior in games (no, 1080° Avalanche isn't affected), I haven't implemented this in the JITs, so as to not cause unnecessary performance degradations.

Interpreter: Fix rounding edge case in frsp

---

Externals/SDL/SDL2.vcxproj

for a Windows.Gaming.Input fix

SDL: update submodule to 5aa438e80aabe3570c0ef807d9b22bcd9835ced6

---

Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayCommon.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/NetPlayServer.h
Source/Core/Core/SyncIdentifier.h

Removed code duplicating comments, renamed a few variables, and updated some syntax.
No functional changes AFAIK

NetPlayServer.cpp OnConnect() Minor Code Updates

---

Readme.md

The old readme had lots of outdated information, more specifically regarding the files and folders in the Sys and User directories. I have removed this information, as I do not think it particularly belongs in the readme, and perhaps would be better suited to places like the Github wiki (although that itself is significantly outdated), or perhaps a thread in the forum. I have also updated the command line usage section.

Rewrite readme

---

CMakeLists.txt

```
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Source/UnitTests/Common/BitFieldTest.cpp:234:27: error: call to consteval function 'fmt::basic_format_string<char, BitField<0, 64, unsigned long, unsigned long> &>::basic_format_string<char [7], 0>' is not a constant expression
EXPECT_EQ(fmt::format("{:02x}", object.full_u64),
^
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Source/UnitTests/Common/BitFieldTest.cpp:234:27: note: undefined constructor 'basic_format_string<char [7], 0>' cannot be used in a constant expression
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Externals/fmt/include/fmt/core.h:3115:28: note: declared here
FMT_CONSTEVAL FMT_INLINE basic_format_string(const S& s) : str_(s) {
^
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Source/UnitTests/Common/BitFieldTest.cp …
```

Workaround FreeBSD/clang/fmt bug

---

Source/Android/app/build.gradle

If the property isn't set, we don't initialize the release config, so we shouldn't use it. This fixes building issues for me.
https://github.com/dolphin-emu/dolphin/blob/7d2d5d914bf3cacbecbb0bf8a642b616744aad54/Source/Android/app/build.gradle#L36-L45
Before, I was getting this message when running `gradlew assemble`:
```
> Task :app:packageRelease FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
> SigningConfig "release" is missing required property "storeFile".
```
I haven't tested this change in a setup which has an actual signing config (and don't really want to set one up myself).

Android: Don't set the signingConfig if keystore property isn't set

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java

Previously if write access was given, revoked, and the user returned to the app, the UI will lock up and not load completely. Now the user is prompted for write access after revoking and the UI will load correctly now.

Android: Prevent app lockup when revoking write access

---

Source/Core/Core/IOS/FS/HostBackend/FS.cpp

This accounts for a shocking amount of writes to `fst.bin`, in particular during dolphin startup.

IOS/FS: Skip writing FST if SetMetadata() changes nothing.

---

AndroidSetup.md

The old instructions would result in this:
```
C:\Users\Pokechu22\source\repos\dolphin>Source\Android\gradlew assemble
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
FAILURE: Build failed with an exception.
* What went wrong:
Directory 'C:\Users\Pokechu22\source\repos\dolphin' does not contain a Gradle build.
A Gradle build should contain a 'settings.gradle' or 'settings.gradle.kts' file in its root directory. It may also contain a 'build.gradle' or 'build.gradle.kts' file.
To create a new Gradle build in this directory run 'gradlew init'
For more detail on the 'init' task see …
```

Android: Improve documentation on command-line build

---

Source/Core/DiscIO/DirectoryBlob.cpp
Source/Core/DiscIO/DirectoryBlob.h

I found this while trying to debug https://bugs.dolphin-emu.org/issues/12965, though this does not actually fix that issue.
What's happening here is that the `ContentPartition` chunks inside DirectoryBlob are designed to look from the outside as if they are encrypted/hashed, but present their filesize without the headers such a partition would actually have. This confuses non-`ReadWiiDecrypted()` reads near the end of the partition, because the offset with headers gets compared against the size without headers so the read is considered out of bounds and returns a failure.
~~I also round the size up to a full group because otherwise this read in `VolumeWii::EncryptGroup()` fails on the last not-full-group-sized chunk of the partition:~~ …

DirectoryBlob: Fix partition size mixup for encrypted Wii discs.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheManager.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/AfterDirectoryInitializationRunner.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java

In the past, directory initialization could fail for two reasons: The user was rejecting the storage permission, or external storage wasn't mounted. With the introduction of scoped storage, the first of these two couldn't happen anymore; if the user rejects the storage permission, we just use the app-specific directory instead of the `dolphin-emu` directory.
By making it so Dolphin force quits if external storage isn't mounted, we can get rid of our code for handling retrying directory initialization after it fails. I think this slight hit to UX is worth it considering that basically nobody has an Android device with detachable primary external storage anymore. And the UX hit is very small; the user just has to manually open the app again after remounting external storage. The toast about …

Android: Force quit app if external storage isn't mounted

---

Source/Core/VideoBackends/D3DCommon/SwapChain.h
Source/Core/VideoBackends/Vulkan/VKSwapChain.h

See individual commit messages for details on when these were added/became unused.

VideoCommon: Remove unused swap chain functions

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp

Fixes https://bugs.dolphin-emu.org/issues/13017. With uCode switching, the existing instance of AXUCode is re-activated when GBAUCode is done, but if the state remains as WaitingForNextTask, it won't be able to do anything. Instead, it needs to be in WaitingForCmdListSize.
(When the AX uCode is resumed, startpc is set to 0x0030, at least for 0x07f88145; this is the same location as MAIL_RESUME jumps to, so DSP_RESUME should be sent when the resuming happens; that's already handled by AXUCode::Update.)
The Zelda uCode already handled this, as it already tracked states prior to #10768:
https://github.com/dolphin-emu/dolphin/blob/86d760b8143989627bdff1be4474ce2fe59db8e9/Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp#L208-L214
I don't actually have a game that uses uCode switching with the GBA …

DSPHLE/AX: Set state to WaitingForCmdListSize when switching uCodes

---

Source/Core/DolphinQt/GameList/GameTracker.cpp
Source/Core/DolphinQt/GameList/GameTracker.h

when refreshing gamelist, `GameFileCache::Save` took up 70% of entire runtime, and populating the list was slow.
with this change, `GameFileCache::Save` takes up near zero of overall runtime, and list updates quickly.

qt: defer writing gamelist cache until EndRefresh

---

Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayClient.h
Source/Core/Core/NetPlayProto.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/NetPlayServer.h
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/NetPlay/GameDigestDialog.cpp
Source/Core/DolphinQt/NetPlay/GameDigestDialog.h
Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Source/Core/DolphinQt/NetPlay/NetPlayDialog.h

use the new, fast, sha1 for netplay "checksum" (i hate that that term is used here, lol)

netplay: use sha1 instead of md5

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PicassoUtils.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/viewholders/GameViewHolder.java
Source/Android/app/src/main/res/layout/card_game.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp

Following a request from @MayImilae in #10600, you can now disable the text below game covers. Additionally there is a fallback to display the game title over the error image if an image is not found.
Setting - 
Enabled - 
Fallback -

Android: Add option to disable game cover text

---

Source/Core/Common/MinizipUtil.h
Source/Core/UICommon/ResourcePack/ResourcePack.cpp

walking the zip prevents minizip from re-reading the same
data repeatedly from the actual backing filesystem.
also improves most usages of minizip to allow for >4GB,
files altho we probably don't need it
drops time to "install" https://forums.dolphin-emu.org/Thread-sonic-adventure-2-battle-hd-project-v2-3-june-21-2019 from 9:30 (MINUTES) to 25 seconds (which is still pretty slow imo).
fwiw i tested also with the buffered minizip layer, and there's no speedup. likely because we just read the entire file once. there might be further speedup by decoupling the read + write operations (so it's not serialized), but meh.

ResourcePack: dont scan for individual files

---

Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
Source/Core/Core/State.cpp

- Use a structured binding in a place that was previously a problem (see commit message for details).
- Use time_since_epoch now that the standard specifies it as Unix time.
This PR used to replace the workaround function FillWithFallbacks(table) in Jit64_Tables.cpp with table.fill(...) now that array.fill is constexpr, but the android and freebsd builders don't support constexpr fill. It also used to add make_unique_for_overwrite in a couple places, but most of the builders don't support that.

Address c++20 TODO comments

---

Externals/MoltenVK/patches/0002-Fix-crash-in-vkCreateSwapchainKHR_on_macOS_10.14_and_earlier.patch

MoltenVK v1.1.11 attempts to access an API only available on macOS Catalina and newer. This patch ensures it only attempts to access the API on macOS versions that supports it. (Because I'd rather not migrate to using an 'unstable' revision of MoltenVK, I "cherry picked" the GitHub-generated patch file from KhronosGroup/MoltenVK#1690 into our patches folder so our patching system will apply it. This file should be removed when updating to the next MoltenVK version.)

MoltenVK: Add patch to resolve a crash on macOS Mojave

---

Source/Core/Common/Network.cpp
Source/Core/Common/Network.h
Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp
Source/Core/Core/HW/EXI/BBA/BuiltIn.h

This PR implements the SSDP multicast support properly. It fixes one issue I had where my Windows host, its Linux VM and my smartphone couldn't see each other joining/leaving the LAN consistently. This method also seems firewall friendly, I don't see packets being dropped anymore on Wireshark.
The UDP port not opening issue isn't fixed in this PR. If the Windows discovery service is enabled, the VM and its hosts can't see each other consistently (shouldn't matter as I don't expect many people to use Dolphin in a VM to play LANs/online).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/10920)

BBA/BuiltIn: Add SSDP multicast support

---

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp
Source/Core/Core/HW/EXI/BBA/BuiltIn.h
Source/Core/Core/HW/EXI/EXI_DeviceEthernet.h

This PR implements the UPnP HTTP listener used by Kirby Air Ride and Mario Kart Double Dash. If someone on the same network of these GC games visits the URL `http://<GameCube_IP>:1900/rootDesc.xml`, they can grab the UPnP XML file. I confirmed this behaviour using Nintendont on a real Wii (since I don't have a BBA adapter). **This URL can only be accessed from another IP (i.e. an IP other than the one used by Dolphin).**
@schthack @nolrinale 
This might also address this issue https://dolp.in/i12996 as this PR fixes an issue where partial data isn't sent when closing the connection. I touched the TCP emulation part so you might want to test this out to make sure it doesn't impact PSO servers.
This PR doesn't fix MKDD timer stuck at 172 when there are more than 2 players. Depends on …

BBA/BuiltIn: Add UPnP HTTP listener

---

Source/Core/VideoBackends/Software/Rasterizer.cpp

The masking was incorrect. This affects the main menu of The Last Avatar, though that menu also relies on copy filter functionality that is not correctly handled in the software renderer so the difference is not obvious; that game shuffles textures across all indices for some reason, so this issue would presumably result in subtle flickering.
This was originally implemented in #10549; see comments there for some hacked-together visualizations of what's going on. I've created a separate pull request just to isolate the fifoci difference (and provide an obvious minimal change that fixes the bug).

Software/Rasterizer: Fix indirect stage using texture coordinates/maps >= 4

---

Source/Core/VideoBackends/Metal/MTLObjectCache.h

In C++20, the expression `DepthStencilSelector{} == DepthStencilSelector{}` is non-conforming code without this change.
The underlying reason for this reversed operators in C++20 results in two candidates being produced:
```cpp
bool operator==(DepthStencilSelector& /*this*/, DepthStencilSelector const& other);
bool operator==(DepthStencilSelector const& other, DepthStencilSelector& /*this*/);
```
This results in an ambiguity due to there being two viable candidates.
Making `this` a `const` reference solves this problem.

MTLObjectCache: Correct signature of equality operator

---

Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp
Source/Core/VideoCommon/TextureInfo.cpp

ref: clang `-Wreorder-ctor` warning

Ensure constructor initializer order matches initialization order

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ContentHandler.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PicassoUtils.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/TvUtil.java

If `GameFile.getCustomCoverPath` returns a mangled URI, we need to unmangle it before passing it to Picasso, since Picasso has no concept of Dolphin's mangled URIs.

Android: Fix reading custom covers with SAF

---

Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp
Source/Core/InputCommon/ControllerInterface/Win32/Win32.cpp

this is mostly just modernization / cleanup. fixes https://bugs.dolphin-emu.org/issues/13009
adds a comment about the memory leak described in https://bugs.dolphin-emu.org/issues/13006 . I haven't added the hack-fix; it should be fixed in future windows release and tbh I don't think it's a big enough deal to have such a workaround in the meantime.
I have fleshed out the c++/winrt changes to add proper error handling and take care of the TODOs.
https://github.com/libsdl-org/SDL/pull/6145 should also fix the issue of SDL seeing joysticks twice.

ciface/win32 and WGInput bug fixes

---

Source/Core/AudioCommon/AudioCommon.cpp
Source/Core/AudioCommon/AudioCommon.h
Source/Core/Core/Core.cpp
Source/Core/Core/HW/AudioInterface.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/GBACore.cpp
Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
Source/Core/Core/System.cpp
Source/Core/Core/System.h
Source/Core/DolphinQt/GBAWidget.cpp

Global state elimination, part 1 of too many.
I'm not 100% sure if this is the correct approach? It does require later refactoring out all the `Core::System::GetInstance()` calls into passing the class around, but that seems easier than just going directly there from the current state.

AudioCommon: Move sound stream variables to Core::System.

---

Source/Core/Core/HW/DSPLLE/DSPSymbols.cpp
Source/Core/Core/HW/DSPLLE/DSPSymbols.h

Seems this was missed in #9348.

DSPLLE: Remove dead DSPSymbolDB.

---

Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp
Source/Core/InputCommon/ControllerInterface/CoreDevice.h

There's a deadlock here that can happen if thread A calls `UpdateReferences()` while thread B holds the `DeviceContainer::m_devices_mutex` and before releasing it also calls `UpdateReferences()`. The `UpdateReferences()` first locks the `s_get_state_mutex`, then locks the `m_devices_mutex` (indirectly first via the `HasConnectedDevice()` call, but also potentially later down the `UpdateReferences()` chain in eg. `ControlExpression::UpdateReferences()`). If `m_devices_mutex` is already locked by another thread that subsequently tries to acquire the `s_get_state_mutex` -- for example, the HotkeyScheduler thread calling `UpdateInput()` which in turn triggers a `InvokeDevicesChangedCallbacks()` which in turn also triggers `UpdateReferences()` -- they both try to lock the mutex the other …

InputCommon: Fix deadlock in EmulatedController::UpdateReferences().

---

Source/Core/Common/EnumMap.h
Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
Source/Core/VideoBackends/Software/Rasterizer.cpp
Source/Core/VideoBackends/Software/Rasterizer.h
Source/Core/VideoBackends/Software/SWVertexLoader.cpp
Source/Core/VideoBackends/Software/Tev.cpp
Source/Core/VideoBackends/Software/Tev.h
Source/Core/VideoCommon/BPMemory.h
Source/Core/VideoCommon/BPStructs.cpp
Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/PixelShaderGen.h
Source/Core/VideoCommon/UberShaderPixel.cpp
Source/Core/VideoCommon/XFStructs.cpp

This is mainly focused on software renderer changes, combined with some various fifo analyzer changes and typo fixes.

Refactor various bits of graphics code for readability

---

Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp

@shuffle2 This fixes the crash. As far as I can tell this is a bug with the Steam overlay but I have no idea how to verify that or how to report this.
The code is just the existing `TryGetBatteryReport()` function from the winrt headers rolled out and with a null check in the right place, which is, for reference:
```
#define WINRT_IMPL_SHIM(...) (*(abi_t<__VA_ARGS__>**)&static_cast<__VA_ARGS__ const&>(static_cast<D const&>(*this)))
template <typename D> WINRT_IMPL_AUTO(winrt::Windows::Devices::Power::BatteryReport) consume_Windows_Gaming_Input_IGameControllerBatteryInfo<D>::TryGetBatteryReport() const
{
void* value{};
check_hresult(WINRT_IMPL_SHIM(winrt::Windows::Gaming::Input::IGameControllerBatteryInfo)->TryGetBatteryReport(&value));
return winrt::Windows::Devices::Power::BatteryReport{ …
```

WGInput: Work around crash with Steam overlay.

---

Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTarget.cpp

The efb/xfb names were not being calculated properly when defining actions that used them as textures.  This made it impossible to write mods to skip (or technically move/scale) these draw calls.
I found this when trying to make a bloom replacement shader mod for Arc Rise Fantasia using the pp PR.  I was removing bloom and applying the new bloom shader but a corner of the screen was unbloomed.  Turns out the game was drawing in the corner to try and write over the place where it drew the bloom EFB copy.  When I tried to get rid of that draw and I couldn't, I found this bug :)

VideoCommon: fix graphics target texture names for efb/xfb

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/NANDRepairDialog.cpp
Source/Core/DolphinQt/NANDRepairDialog.h

This is so that if you have a lot of titles that need repair the dialog can still fit on screen. Someone on Discord ran into this...
Old:
New:

Qt: Make custom dialog for NAND Repair.

---

Source/Core/DolphinNoGUI/DolphinNoGUI.exe.manifest
Source/Core/DolphinQt/DolphinQt.manifest
Source/Core/DolphinTool/DolphinTool.exe.manifest
Source/Core/WinUpdater/Updater.exe.manifest

With the dropping of support for Windows versions lower than 10, we should also update the .manifest files to reflect this. https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#supportedos

Update supportedOS values in .manifest files

---

Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/DolphinQt/Settings/GameCubePane.cpp
Source/Core/DolphinQt/Settings/GameCubePane.h

More convenience stuff.
Current state: No textbox is shown for options that don't have a path to configure. If a memory card is selected, the textbox is only shown if the path is non-default. If AGP is selected, the textbox is always shown.
The region shown is whatever the user has selected last if available, which I suspect is the least confusing option.
If you try to manually write or paste an invalid path (missing region, already in other card, whatever) it will revert your change.

Qt: Show currently configured Memory Card path in the config window.

---

Source/Core/AudioCommon/Mixer.cpp

Compare #10664. I haven't been able to reproduce any buffer overflows (other than the audio dumping one from #10741), but hopefully these assertions will make them more obvious when they happen.
(I didn't add any assertions to `Mixer::MixerFifo::PushSamples` because that code *should* already be free of overflows due to the masking.)

Mixer: Add assertions regarding num_samples versus buffer length

---

Source/Core/Core/HW/DVD/DVDThread.cpp
Source/Core/Core/HW/DVD/FileMonitor.cpp
Source/Core/Core/HW/DVD/FileMonitor.h

Removes global state in FileMonitor.cpp.

HW: Convert FileMonitor::Log into a class.

---

Source/Android/app/src/main/res/values/styles.xml

The text color would change based on dark/light mode but since it is always on a black background it would look bad.
Before - 
After -

Android: Fix save state menu text color

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot.h
Source/Core/Core/BootManager.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayProto.h

I realized this would be quite simple to do during #11047. Removes (or, well, reduces the scope of, I suppose) the weird thing where a global `netplay_client` stores the netplay settings.

Netplay: Pass netplay settings via BootSessionData.

---

Externals/libspng/spng.vcxproj

Previously was only defined for things including it. Not really a bug, but it was leaking symbols into exports.

spng: define SPNG_STATIC when compiling spng itself

---

Source/Android/app/src/main/res/values/themes.xml

These lines that were originally used to change the color edge effect and color control highlight for the dedicated Emulation Activity theme are no longer necessary. I also didn't really like how the color control highlight (this applied to all clickable objects in the app) looked when so dark.
Before - 
After -

Android: Change color control highlight to system default

---

Source/Android/app/src/main/res/anim/fade_in.xml
Source/Android/app/src/main/res/anim/fade_out.xml
Source/Android/app/src/main/res/values-night-v31/themes.xml
Source/Android/app/src/main/res/values-v31/themes.xml
Source/Android/app/src/main/res/values/styles.xml
Source/Android/app/src/main/res/values/themes.xml

Since we have so many alert dialogs throughout the app, I thought it would look nice to have animations for zooming and fading in.
Before - 
After -

Android: Add custom window animation to alert dialogs

---

Source/Android/app/src/main/res/values-night-v31/themes.xml
Source/Android/app/src/main/res/values-v31/themes.xml
Source/Android/app/src/main/res/values/themes.xml

Looks like I missed these in the previous PR. Now all themes will not have the dark color edge effect.

Android: Remove other color edge effect definitions

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/ConvertActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionBootActivity.java
Source/Android/app/src/main/res/layout-land/activity_user_data.xml
Source/Android/app/src/main/res/layout-w680dp-land/activity_convert.xml
Source/Android/app/src/main/res/layout/activity_convert.xml
Source/Android/app/src/main/res/layout/activity_riivolution_boot.xml
Source/Android/app/src/main/res/layout/activity_user_data.xml
Source/Android/app/src/main/res/values/strings.xml

This adds collapsing top app bars to make each activity more consistent with one another. CheatsActivity still isn't really compatible with collapsing top app bars but hopefully I could introduce that later.
Landscape
Before - 
After -
Portrait
Before -
After -
Before -
After -
Before -
After -

Android: Add more top app bars

---

Source/Android/app/src/main/res/values-night/bools.xml
Source/Android/app/src/main/res/values-v27/themes.xml
Source/Android/app/src/main/res/values/bools.xml
Source/Android/app/src/main/res/values/themes.xml

Since you can change the color of the navigation bar background in APIs >= 27 I'm making it match the background.
APIs >= 27
Light - 
Dark -
APIs < 27

Android: Match navigation bar color to background

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/ConvertActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionBootActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThemeHelper.java
Source/Android/app/src/main/res/layout/activity_cheats.xml
Source/Android/app/src/main/res/layout/activity_main.xml
Source/Android/app/src/main/res/layout/activity_settings.xml

To create more visual separation between list contents and the top app bar, the color will slightly change when collapsing the top app bar on the settings activity. Additionally this fixes visual bugs where an incorrect color would flash when expanding the collapsed toolbar and on some API levels top app bars would have a shadow appear underneath which is now removed.
Every activity with a collapsing top app bar will now tint on scroll
Before - 
After -
Green
Pink

Android: Change top app bar color on scroll

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/PlatformPagerAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/res/values/styles.xml

This lets us use tab highlights
Before -
After -

Android: Remove TabLayout workaround

---

Source/Core/VideoCommon/VertexLoaderBase.cpp
Source/Core/VideoCommon/VertexLoaderBase.h
Source/Core/VideoCommon/VertexLoader_Color.cpp
Source/Core/VideoCommon/VertexLoader_Color.h
Source/Core/VideoCommon/VertexLoader_Normal.cpp
Source/Core/VideoCommon/VertexLoader_Normal.h
Source/Core/VideoCommon/VertexLoader_Position.cpp
Source/Core/VideoCommon/VertexLoader_Position.h
Source/Core/VideoCommon/VertexLoader_TextCoord.cpp
Source/Core/VideoCommon/VertexLoader_TextCoord.h

This increases performance in Mario Galaxy 1 on the hub space ship from ~85 FPS to ~112 FPS. (5900X, downclocked to 2.2Ghz for testing).

Optimize GetVertexSize

---

Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayClient.h

Sending the power button event over netplay is completely unsynced, which means more likely than not two instances of Dolphin will start the graceful shutdown sequence at different points in time, desyncing in the process. This wouldn't be so bad -- we're shutting down anyway -- except that inputs may still be queried by the game during the shutdown. This can lead to a situation where one instance has fully shut down, but another instance is still waiting for an input.
By stopping Netplay as soon as the power button event is received, we can work around this; that means it won't wait for input that may never come.
@JMC47 Can you test if this fixes known cases of hangs on shutdown, especially when Wiimote disconnects are involved?

NetPlayClient: Treat power button event as a netplay stop.

---

Data/license.txt
LICENSES/MSVC-Redist.txt
Source/Core/DolphinQt/CMakeLists.txt
Source/VSProps/Base.Dolphin.props

From the GPLv2 (emphasis added):
> The source code for a work means the preferred form of the work for making modifications to it. For an executable work, complete source code means all the source code for all modules it contains, plus any associated interface definition files, plus the scripts used to control compilation and installation of the executable. However, as a special exception, the source code distributed need not include anything that is normally distributed (in either source or binary form) with the major components (compiler, kernel, and so on) of the operating system on which the executable runs, **unless that component itself accompanies the executable**.
By shipping the Visual C++ DLLs with the executable, the system library exception no longer applies, meaning we're …

Revert "windows: distribute vcredist loose files"

---

Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/FifoPlayer/FifoRecorder.cpp
Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/OpcodeDecoding.h
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexLoaderManager.h

~~I struggled a bit to find a place where to put the cache but I'm pretty happy with having it in the callback.
The hit rate came out at 97% in Mario Galaxy. (I hooked it up to the stats HUD for testing.)~~
Together with #11066 Mario Galaxy goes from 85 fps to 140 fps on the hub world. (5900X, downclocked to 2.2 GHz)

OpcodeDecoding: Cache vertex sizes

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/VideoCommon/VertexLoaderARM64.cpp
Source/Core/VideoCommon/VertexLoaderARM64.h
Source/Core/VideoCommon/VertexLoaderX64.cpp
Source/Core/VideoCommon/VertexLoaderX64.h
Source/UnitTests/VideoCommon/VertexLoaderTest.cpp

Fixes https://bugs.dolphin-emu.org/issues/12952.  I haven't tested the ARM change at all other than verifying that it compiles (so it's probably completely broken), but I have tested the x64 change.

VideoCommon: Fix direct normal+tangent+binormal with index3 set

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/PowerPC.h

@dvessel Could you check if this solves the issue you described in https://github.com/dolphin-emu/dolphin/pull/10808#issuecomment-1252614711?

JitArm64: Enforce correct alignment of SPR_TL

---

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/DolphinQt/Config/Graphics/SoftwareRendererWidget.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Source/Core/DolphinQt/Settings/AudioPane.cpp
Source/Core/DolphinQt/Settings/InterfacePane.cpp
Source/Core/DolphinQt/Settings/PathPane.cpp
Source/Core/DolphinQt/Settings/WiiPane.cpp

Now that all builds are on C++20 a couple of new deprecation warnings are generated.
The `QKeySequence` warning is an upstream issue, in the way that you are intended to call it, from what I can tell.

Resolve C++20 deprecation warnings

---

Source/VSProps/Base.Dolphin.props

Forgot that Windows doesn't use CMake still. Specify `/p:Steam=true` with msbuild to create a Steam build for Windows. 
I've also added a build flag to disable the auto updater. Use `/p:AutoUpdate=false` to disable the auto updater functionality.

msbuild: Add property for creating Steam builds on Windows

---

Source/Core/InputCommon/ControllerEmu/ControllerEmu.h

Use std::llround in MapFloat

---

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

Move dump buttons and "set value from file" to the menu.
Trying to put lesser used buttons in a more logical place and free up room for possibly other items later.
- I can do a  sub-menu for dumps, if that seems better.
- It may not be obvious that "Set value from file" uses the address box's address.

Debugger MemoryWidget: Create mini-menu at top of sidebar.

---

Source/Core/Common/MsgHandler.h
Source/Core/DiscIO/VolumeVerifier.cpp

See https://github.com/dolphin-emu/dolphin/pull/10932#discussion_r978568501

 VolumeVerifier: Add missing assignment to summary_text, and prevent such errors in the future by adding [[nodiscard]] to GetStringT().

---

Source/Core/DolphinQt/Config/CommonControllersWidget.cpp
Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp
Source/Core/DolphinQt/Config/GamecubeControllersWidget.h
Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp
Source/Core/DolphinQt/Config/WiimoteControllersWidget.h

(without triggering signals)
Prep work for allowing opening the Controller settings mid-Netplay without everything breaking. See https://github.com/dolphin-emu/dolphin/pull/11070#issuecomment-1251600186.
To be clear, the intent of this PR is having the Controller GUI properly reflect the current state if it's changed programmatically by Netplay (or anything else). The eventual target (not in this PR) is that during Netplay, the dropdowns for the GC controller ports and Wiimotes will be greyed out (because we don't support them changing mid-session), but the Configure buttons next to them will still work so you can change your mappings, along with harmless-to-Netplay settings like Background Input.

Qt/Controllers: Refresh GUI on settings change.

---

Source/Core/Common/Matrix.h
Source/Core/InputCommon/ControllerEmu/ControllerEmu.h

Extracted from #11070 for easy review.

Add TVec and RawValue equality operators.

---

Source/Core/Core/BootManager.cpp
Source/Core/Core/Config/NetplaySettings.cpp
Source/Core/Core/Config/NetplaySettings.h
Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayProto.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/WiiRoot.cpp
Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Source/Core/DolphinQt/NetPlay/NetPlayDialog.h

Reduces the amount of different netplay settings for syncing save data from four independent boolean options to one tri-state option and one boolean option.
Old options:
- Write Save Data On / Off
- Load Wii Save On / Off
- Sync Saves On / Off
- Sync All Wii Saves On / Off
(don't ask me what some of these combinations even do)
New options:
- No Save Data / Load Host's Save Data Only / Load and Write Host's Save Data
- Use All Wii Saves On / Off
This should both make more sense to the user and make it easier to reason about the code.

Netplay: Simplify save data options.

---

Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/System.cpp
Source/Core/Core/System.h
Source/Core/DolphinQt/Settings/AdvancedPane.cpp
Source/Core/DolphinQt/Settings/AdvancedPane.h

* Adds `Pause on Panic` to Config -> Advanced
* JitBase.cpp change is necessary because otherwise the JIT splices would break on the next block rather than the instruction that threw the exception.
* Defaults to OFF since this has the same performance hit that enabling MMU does.
* Currently, this is only affecting panics for invalid read/writes. Ex `stw r4, r5` where r5 is a non-valid address (ex 99232100)
* Additionally, I also check for the flag in Interpreter.cpp for Unknown Instruction. I do not want to default this to pause/break as this will negatively impact a user who runs into an Unknown Instruction that doesn't crash Dolphin or the emulation. This will be updated with the Panic message rewrite future PR.
* When debugging games/homebrew if a read/write exception occurs, there is …

Core/DolphinQt: Add Pause on Panic Option for DSI Exceptions and Unknown Instruction

---

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp

This PR is an attempt to fix the following crash: https://bugs.dolphin-emu.org/issues/13032
This was the only part of the code I could find where a check was missing that could produce a crash of Dolphin. I'm unsure if it's related to the described issue. Regardless, I managed to exhaust the BBA network stack and crash Dolphin by requesting the UPnP URL with multiple tabs of a web browser.
The PR addresses these issues by:
- checking the pointer to prevent the `nullptr` dereference crash
- skipping UPnP requests to itself which _(shouldn't happen on real hardware and)_ are ignored but used to hold onto a network slot forever due to them being ignored.

BBA/BuiltIn: Fix a crash during network stack exhaustion

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp

When a guest register is an immediate, it may be necessary to move this value into a register. This is handled by `gpr.R()`, which lacks context on how the register will be used. This leads to cases where the immediate is written to a register, only for it to be overwritten. Take for example this code generated by `srwx`:
```
0x5280031b   mov    w27, #0x18
0x53187edb   lsr    w27, w22, #24
```
`gpr.BindToRegister()` does have this context through the `do_load` parameter, but didn't handle immediates. By adding this logic, we can intelligently skip the write when `do_load` is false.

JitArm64: Skip redundant imm to register writes

---

Data/Sys/GameSettings/SJB.ini

Defer EFB Copies causes visual issues in this game, so let's disable it.

Goldeneye 007 (Wii) - Disable Defer EFB Copies

---

Data/Sys/GameSettings/GDREAF.ini
Data/Sys/GameSettings/GDRP69.ini

This game follows the anti-pattern of calling memset on a buffer in the midst of being DMA copied to ARAM, then calling a DVD read function that effectively cancels the memset with dcbi instructions. Dolphin does not emulate dcache for performance reasons, so this patch removes the offending memset call.
Patches are included for two regions and are enabled by default.
https://bugs.dolphin-emu.org/issues/12759

GameSettings: Add patch for Dead to Rights audio

---

Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp

Tested on an official DOL-014 (251 blocks) memory card by executing the 0xf4 command on a card with content along its entire length and then dumping the whole card: it reads as 0xff all the way through. Therefor, the current implementation is already consistent with hardware.

EXI_DeviceMemoryCard: Drop comment about ChipErase behaviour

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

A (partial) port of #9481 to ARM64. This commit adds special cases for immediate values equal to 0 or 0xFFFFFFFF, allowing for more efficient or no code to be generated.
The 'after' examples showcase the generated code after applying both this PR and #11094.
---
**and**
<details><summary>Special case 0</summary>
Before:
```
0x52800017   mov    w23, #0x0
0x0a170319   and    w25, w24, w23
```
After:
Nothing, register is set to constant zero.
</details>
<details><summary>Special case 0xFFFFFFFF</summary>
Before:
```
0x1280001a   mov    w26, #-0x1
0x0a1a033a   and    w26, w25, w26
```
After:
```
0x2a1903fa   mov    w26, w25
```
</details>
---
**or**
<details><summary>Special case 0 (a != j)</summary>
Before:
```
0x52800004   mov    w4, #0x0
0x2a0a0084   orr    w4, w4, w10
```
After:
``` …
```

JitArm64: boolX constant optimizations

---

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp

Those who've seen some of my previous PRs (#9262 or #9425) probably know what to expect by now.
Major optimizations include precomputing the complement (`andcx`, `orcx`, and `eqvx`), handling special cases (0 and `0xFFFFFFFF`), and preferring shorter instructions.
For those wondering, special case `0xFFFFFFFF` is missing for OR because I couldn't find a game doing this. I also had some ideas for `nandx` and `norx` when Rc = 1, but I've never seen that happen so I didn't bother.
---
**and**
<details><summary>Precompute complement (andcx)</summary>
Before:
```
BF 00 01 00 00       mov         edi,100h
F7 D7                not         edi
41 23 FE             and         edi,r14d
```
After:
```
41 8B FE             mov         edi,r14d
81 E7 FF FE FF FF    and         edi,0FFFFFEFFh
``` …

Jit64: boolX constant optimizations

---

Source/Core/DolphinQt/Debugger/CodeWidget.cpp

Before, only the symbols box would update. However, if you edit the symbol of a function in the call stack (which seems like something that would happen reasonably often while debugging), the call stack would be out of date until it was updated by clicking on it. Callers and calls were more of an edge case; for them to be out of date, you would need to right-click on an instruction in a function other than the one containing the currently-selected instruction (though it would also affect recursive functions).

Debugger/CodeWidget: Update callstack/callers/calls on symbol changes

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheManager.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Source/CMakeLists.txt
Source/Core/UICommon/GameFileCache.cpp
Source/VSProps/Base.Dolphin.props

This is intended to fix https://bugs.dolphin-emu.org/issues/13053, which is a crash caused by `sGameFileCache` being null when `addOrGet` is called.
I've also included some other changes related to `GameFileCacheManager`. Please read the commits for details.

Android: Allocate GameFileCache on GUI thread

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java

Not only SystemMenuNotInstalledDialogFragment requires directory initialization to have completed, but also isSystemMenuInstalled.

Android: Improve checking in MainPresenter.launchWiiSystemMenu

---

Source/Core/Common/FatFsUtil.cpp
Source/Core/Common/FatFsUtil.h

FatFsUtil code refactoring so #11072 can be implemented without having to modify FatFs itself. See also #11107.

FatFsUtil: Add ability to provide callbacks for the FatFs code.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/AlertMessage.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/NativeConfig.java
Source/Android/jni/Config/NativeConfig.cpp
Source/Core/Common/Config/Config.h
Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/Settings/InterfacePane.cpp
Source/Core/UICommon/UICommon.cpp

This fixes a problem where changing the Use Panic Handlers setting on Android wouldn't take effect until the app was restarted.

Move a SetEnableAlert call to UICommon

---

Source/Core/Core/CMakeLists.txt
Source/Core/Core/HW/Wiimote.cpp
Source/Core/Core/HW/Wiimote.h
Source/Core/Core/HW/WiimoteEmu/Extension/Shinkansen.cpp
Source/Core/Core/HW/WiimoteEmu/Extension/Shinkansen.h
Source/Core/Core/HW/WiimoteEmu/ExtensionPort.h
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
Source/Core/DolphinLib.props
Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtension.cpp
Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtension.h

This Wiimote extension is only compatible with Densha de Go! Shinkansen EX. I don't actually have access to the physical controller and the game doesn't have symbols, so this is all based on guesswork but it seems to work pretty well. We don't support LED outputs yet. All you can do with the door lockout light is map it to a rumble effect^^

Add emulated Shinkansen controller

---

Source/Core/VideoBackends/Vulkan/VKTexture.cpp
Source/Core/VideoBackends/Vulkan/VKTexture.h
Source/Core/VideoCommon/DriverDetails.cpp
Source/Core/VideoCommon/DriverDetails.h

After profiling Mario Galaxy on my Snapdragon 865 phone, I realized that the video thread spends a ridiculous amount of time in `vkCmdCopyImageToBuffer`.
Turns out the driver allocates a temporary image every single time. After playing around for a bit, I've noticed that it doesn't do that when copying from a linear tiled image. So we can just do that blit ourselves and reuse the image.
EDIT: I should clarify, this is mostly a problem when "Store EFB copies to texture only" is disabled.

Vulkan: Workaround slow vkCmdCopyImageToBuffer on QCom

---

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp
Source/Core/VideoBackends/Vulkan/CommandBufferManager.h
Source/Core/VideoBackends/Vulkan/Constants.h
Source/Core/VideoBackends/Vulkan/VulkanContext.cpp

In order to keep the GPU busy when Dolphin does EFB readbacks, there's the option to automatically flush the command buffer at specific points instead of just before a readback or at the end of the frame.
The problem with this is that Dolphin currently only has 2 Vulkan command buffers and when both of those are in use, it will just wait for one to become available. So flushing more often could make CPU-GPU parallelism worse if the GPU didn't finish the command buffers faster than Dolphin was flushing.
My Snapdragon 865 phone sits at <30% GPU utilization with Mario Galaxy (1x res) while the CPU spends most of its time waiting for the CPU to finish. So flushing more often is definitely beneficial because it allows the GPU to start working sooner.
This PR raises the number of command …

Vulkan: Raise number of command buffers

---

Source/Core/Common/WorkQueueThread.h
Source/Core/Core/State.cpp
Source/Core/Core/State.h

While trying to determine the cause of #10546 I noticed that there's some unfortunate locking happening in the state saving construct, which could lead to us temporary locking up if a second savestate request comes in or if emulation is paused while another is still compressing/writing to disk. This is my attempt to improve this.
In my experience it's noticeably more responsive now saving multiple states in a row or trying to load right after saving, at least when I artificially increase the savestate disk writing function time with Sleep(), which should be roughly equivalent to writing to a slow HDD. Saving a state and then pausing the game also no longer locks up the emulator until the state is done saving.

Core/State: Rewrite threading behavior when multiple Save requests are happening.

---

Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp

This matters because the backends for which the tooltip appears, Null and Software, are translated.

DolphinQt/HacksWidget: Make backend name in GPU Texture Decoding/Bounding Box tooltip translatable

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

a is being used both as an immediate and as a register here. Since it's being used as a register, it must be loaded.

JitArm64: Fix divwx BindToRegister condition

---

Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/DSP.h
Source/Core/Core/System.cpp
Source/Core/Core/System.h

I also tried to make the variables actually fit our current coding style guidelines while I was here.
(this file needs a bit more naming cleanup in general though, why the heck is there both a `ARAMInfo` and a `ARAM_Info` struct that have different stuff)

HW: Move DSP variables to Core::System.

---

Source/DSPSpy/main_spy.cpp
Source/DSPSpy/tests/st3_test.ds
docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex

Noticed while tracing in a BLOOP using DSPSpy with $st{0..3} unmasked. BLOOPI assumed to follow the pattern.

docs/DSP: Trivial adjustment to BLOOP{,I} sub-operation order

---

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp

So people will actually tell us the error code when this happens. (https://bugs.dolphin-emu.org/issues/13060)

Vulkan/CommandBufferManager: Show error code in PanicAlerts.

---

Source/Core/VideoCommon/BPStructs.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/FramebufferManager.cpp
Source/Core/VideoCommon/FramebufferManager.h
Source/Core/VideoCommon/RenderBase.cpp

I assume DrawDone and or Tokens are used to synchronize with the GPU before reading back data from the EFB.
So instead of just invalidating the EFB peek cache, I take it as a hint and queue an update to all previously used EFB tiles.
If there is work between DrawDone/Token and the actual EFB read, the read hits a prepopulated cache and doesn't stall both threads and the GPU.
It helps Super Mario Galaxy, getting the game up to 60 FPS on my Snapdragon 865 phone (instead of ~40) in some scenes. Unfortunately Galaxy also likes to invalidate the peek cache after a DrawDone/Token and even if I enable DeferEFBInvalidations, the GPU still doesn't finish in time.
This is the sort of change that probably needs a lot more testing as it could impact other games. Perhabs it should be a config option? …

VideoCommon: Update EFB peek cache on draw done and tokens

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h

Fixes a Rogue Squadron II regression from PR #11094.
This `set_dirty` stuff is pretty tricky to reason about. I thought I was clever when coming up with `set_dirty`, but maybe I was too clever for my own good...

JitArm64: Fix BindToRegister in case Immediate && !set_dirty

---

Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp

This silently fails writing save data if eg. the file is readable but not writable. We should notify the user in this case.

HW/GCMemcardDirectory: Add error message if opening GCI fails.

---

Source/Core/Common/ChunkFile.h
Source/Core/Core/HW/AudioInterface.cpp
Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/DSPHLE/DSPHLE.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/EXI/EXI_Channel.cpp
Source/Core/Core/HW/GCMemcard/GCIFile.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
Source/Core/Core/HW/SI/SI.cpp
Source/Core/Core/HW/VideoInterface.cpp
Source/Core/Core/HW/WII_IPC.cpp
Source/Core/Core/State.cpp
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/PixelEngine.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp

This was added in 385d8e2b15c8accce3b4e4b4f3dc90f63e3fbee4, but became somewhat redundant with Do in 4c7bbd96e435a7516b05d3e8c791ab41505e2e0f, and completely redundant now that `std::is_trivially_copyable_v` is well-supported.

Common/PointerWrap: Remove DoPOD

---

Source/Core/Core/HW/HW.cpp
Source/Core/Core/HW/MemoryInterface.cpp
Source/Core/Core/HW/MemoryInterface.h
Source/Core/Core/State.cpp

This PR adds MemoryInterface variables to save states. Hopefully, this will reduce the frequency of desyncs in Dolphin - although it remains to be seen what effect this will have.

Added MemoryInterface variables to savestates

---

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp

I'm not sure if there's any particular reason this isn't done? This looked wrong to me skimming over it the code, at least.

JitCache: Erase address from noSpeculativeConstantsAddresses when block is invalidated.

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/Memmap.h

This existed in the initial megacommit (though I don't know why) as IO_SIZE. It was used in Memmap's Init() to compute totalMemSize, but I don't know if it actually did anything then. That use was removed in 2d0f714546cba64ec9191c4e3e0b60351ad3e539, but the constant persisted until cc858c63b8d04c5ce407c7efd0ae8abc654e73a0, when it became a static variable.

Memmap: Remove unused IO size field

---

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp

#11090 had a subtle bug that broke deferred freeing of Vulkan resources.
This led to rapid increase in memory usage in Opoona until OOM because Dolphin allocates new textures every single frame for that game.
@iwubcode

VideoBackends:Vulkan: Fix command buffer cleanup

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/VideoCommon/VideoConfig.h

Having a submission thread with Vulkan is common practice and recommended basically everywhere. I'd expect most Vulkan apps on Android to have one, so I don't see why this is disabled on Android. The more frequent flushing is only done when there are CPU readbacks (for example EFB peeks) and giving the GPU a head start in those cases is definitely beneficial too.
This relies on #11090 to not slow things down.

Remove special treatment for Android in video settings

---

Data/Sys/Load/GraphicMods/The Last Story/metadata.json

Add bloom definitions for TLS menu and also add some more HUD definitions to hide text
Original
No Bloom
Native

Update The Last Story GraphicsMod

---

BuildMacOSUniversalBinary.py

The flags `--steam` and `--no-autoupdate` (automatically parsed by `argparse`) will be used when creating Steam builds on macOS.

BuildMacOSUniversalBinary: Add flags to create a Steam build

---

Source/Core/Common/ENetUtil.cpp
Source/Core/Common/ENetUtil.h
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayServer.cpp

Someone on Discord said they had a crash in `enet_peer_send()`. I don't quite see how that would happen, but I suppose we should check the return values anyway and at least log errors.

Check return values of ENet functions when sending packet.

---

Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Paired.cpp

All `HandleNaNs` does with the `xmm_out` parameter is emit `MOVAPD` at the end if `xmm_out != xmm`. The caller might as well do that themselves.

Jit64: Remove HandleNaNs's xmm_out parameter

---

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp

`jo.accurateSinglePrecision` is always true, so it's not like this matters much...

Jit64: Fix single FPRF when !jo.accurateSinglePrecision

---

Readme.md

This unhides the dolphin-emu and dolphin-tool convert usage, which were hidden because the backticks preceding them were not on their own line.

Fix formatting in Readme

---

Source/Core/DolphinLib.props
Source/Core/VideoCommon/CMakeLists.txt
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/MoveAction.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/MoveAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/PrintAction.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/PrintAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/ScaleAction.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/ScaleAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/SkipAction.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/SkipAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionData.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VertexShaderManager.cpp

As I've started work on multiple graphics mod features, they've all needed the same thing:  adding parameters to the hook API.  Rather than having to update every action added every time, I think it makes more sense to have a common API of structures that can be updated, cutting down on the number of places that need changing.

VideoCommon: add structures to graphics mods internal API

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStorePaired.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h

This being an std::map is completely unnecessary.

Jit64: Convert constantGqr to std::array.

---

Source/Core/Core/State.cpp
Source/Core/VideoCommon/CPMemory.cpp
Source/Core/VideoCommon/CPMemory.h
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VideoState.cpp

The tangent/binormal cache theoretically matters for RS2/RS3 (see #10584), although in practice these games reconfigure it each frame so it shouldn't matter for savestates.
The CP state part is simplification only; there should be no change in behavior from it.

Include tangent/binormal cache in savestates and simplify saving CP state

---

Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/HW/VideoInterface.cpp

`base` is an unsigned variable, so we can make things little more consistent by making the loop index unsigned so we aren't doing bit arithmetic with signed types.
Some other RegisterMMIO calls already use unsigned values for this sort of thing, so those don't need to be touched
No behavioral changes, just a nitpicky consistency thing.

HW: Use unsigned indices in RegisterMMIO where applicable

---

Source/Core/Core/HW/EXI/BBA/TAP_Unix.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Source/Core/DolphinQt/Debugger/JITWidget.cpp
Source/Core/DolphinQt/DiscordJoinRequestDialog.cpp
Source/Core/DolphinQt/GameList/GameList.cpp
Source/Core/DolphinQt/HotkeyScheduler.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/NetPlay/ChunkedProgressDialog.cpp
Source/Core/DolphinQt/Translation.cpp
Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp
Source/Core/VideoBackends/Vulkan/VulkanLoader.cpp
Source/Core/VideoBackends/Vulkan/VulkanLoader.h
Source/DSPTool/DSPTool.cpp

`StringFromFormat` uses `printf` strings.  There are still 2 remaining places where it is used: CubebUtils.cpp (where it's formatting a printf-style message from a library) and HLE_OS.cpp (where it's formatting a printf-style message from games).

Remove most uses of StringFromFormat in favor of fmt

---

Source/Core/Core/HW/WiimoteEmu/Camera.cpp

The Wii Remote camera data includes a size for each visible IR object.
Previously the simulated "size" was the just the maximum possible value scaled down based on distance from the sensor bar.
I've measured the values that a real wii remote produces at different sensor bar distances and implemented math to simulate it.
I don't expect any games to really use this data and I'm sure this differs from remote to remote, but it's an improvement over the previously completely made up number,

WiimoteEmu: Improve simulated IR point size accuracy.

---

Source/Core/Core/HW/VideoInterface.cpp
Source/Core/Core/State.cpp

This PR simplifies the DoState() method of VideoInterface by saving/loading everything in 1 line (since all of the variables in the namespace are now contained in one struct that can be written to with p.do()).

VideoInterface: Simplify saving VideoInterface

---

Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp

Minor emulated Wii Remote behavior fix.
The `want_determinism` check seemed odd to me and I don't think it was appropriate even before this change.

WiimoteEmu: Minor emulated Wii Remote behavior fix.

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp

Jumping to `dispatcher` requires first subtracting the downcount, otherwise `dispatcher` may unpredictably jump to CoreTiming::Advance, which could break determinism compatibility with JitArm64. We should jump to `dispatcher_no_check` instead.

Jit64: Jump to dispatcher_no_check from InitializeSpeculativeConstants

---

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp

Improves accuracy but isn't known to affect any games.
This turned out to be fairly convenient to implement; ORing with the PPC default NaN will quieten SNaNs and do nothing to QNaNs.

Jit64: Turn SNaN into QNaN in HandleNaNs

---

Source/Core/Core/PowerPC/Jit64/JitAsm.cpp

The breakpoint check in Jit.cpp makes it redundant.
Normally this redundant check doesn't cause any issues, but if you create a breakpoint and enable logging without breaking, you get two log messages if the breakpoint is at the beginning of a block. See https://bugs.dolphin-emu.org/issues/13044.
This is also a tiny performance improvement for when debugging is active, since we no longer check for breakpoints for blocks that never had any breakpoints to begin with.

Jit64: Remove breakpoint check from JitAsm.cpp

---

Source/Core/Common/FatFsUtil.cpp
Source/Core/Core/IOS/Network/KD/VFF/VFFUtil.cpp

Lack of zero-initialization on the `FATFS` struct causes https://github.com/dolphin-emu/dolphin/pull/11072#issuecomment-1279971536 because it tries to flush a sector it hasn't written to (because the dirty bit happens to initialize nonzero and FatFs doesn't clear it on mount...). Doesn't actually fix the News and Forecast channels though.

Zero-initialize structures passed to FatFs functions.

---

Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp

IOS/NetKDRequest: Don't abort on first unset bit in subtask mask.

---

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp
Source/Core/VideoBackends/Vulkan/CommandBufferManager.h
Source/Core/VideoBackends/Vulkan/StateTracker.cpp
Source/Core/VideoBackends/Vulkan/StateTracker.h

Dolphin currently creates one massive descriptor pool per frame. If it ever runs out of descriptors or descriptor sets,
it executes the current command buffer, hoping that will result in a fresh pool.
The problem is that after #11090, executing the current command buffer will not result in a fresh descriptor pool.
That PR decoupled command buffers and descriptor pools to allow us to use more command buffers which in turn reduces
potential waiting for the previous one to finish when flushing more often (mostly on weak mobile GPUs).
So right now, when descriptor set allocation fails, it just starts a new command buffer and then tries again with the exact same descriptor pool. I don't know how often this actually happens in games, given that the descriptor pool is pretty huge but we should …

VideoBackends:Vulkan: Allocate descriptor pools as needed

---

Source/Core/Core/IOS/DI/DI.cpp
Source/Core/Core/IOS/Device.cpp
Source/Core/Core/IOS/Device.h
Source/Core/Core/IOS/FS/FileSystemProxy.cpp
Source/Core/Core/IOS/Network/IP/Top.cpp
Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp
Source/Core/Core/IOS/STM/STM.cpp
Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp
Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
Source/Core/Core/IOS/USB/Host.cpp
Source/Core/Core/IOS/USB/OH0/OH0Device.cpp
Source/Core/Core/State.cpp

There was an extra call to p.do(m_is_active) in IOS::HLE::Device::DoState(). This PR eliminates that extra call, and simplifies the DoState() method for the Device class.

IOS: Simplify IOS::HLE::Device savestate method

---

Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/UberShaderPixel.cpp

When doing some testing on a separate PR, I noticed that the NES Legend of Zelda (on the Gamecube Collector's Edition) would give a shader compiler error when using D3D.
The compiler error was:
> ERROR: 0:160: 'assign' :  cannot convert from ' const 4-component vector of float' to 'layout( location=0 index=0) out 4-component vector of uint'
This PR fixes that error.

VideoCommon: fix uint shader compiler error when using d3d

---

Source/Core/VideoCommon/VertexManagerBase.h

Densha de GO! Shinkansen EX uses 27mb per frame, and we want enough space for the CPU to be encoding one frame while the GPU is rendering the previous
Increases frame rate for Vulkan and DX12
In the scene mentioned on https://bugs.dolphin-emu.org/issues/12920
Vulkan (i7-4980HQ, GT 750M) 22fps → 35fps
Similar improvements on an AMD Radeon Pro 5600M but I'm too lazy to boot into Windows for an exact measurement right now

VideoCommon: Increase uniform stream buffer size to 64mb

---

CMake/FindPowerShell.cmake
Source/Core/Common/CMakeLists.txt
Source/Core/Common/build_info.txt.in
Source/Core/DolphinLib.vcxproj
Source/Core/MacUpdater/MacUI.mm
Source/Core/UICommon/AutoUpdate.cpp
Source/Core/UpdaterCommon/Platform.h
Source/Core/UpdaterCommon/UpdaterCommon.cpp
Source/Core/WinUpdater/CMakeLists.txt
Source/Core/WinUpdater/Main.cpp
Source/Core/WinUpdater/Platform.cpp
Source/Core/WinUpdater/WinUI.cpp
Source/Core/WinUpdater/WinUpdater.vcxproj

I've changed the PR so that the metadata is in a loose .txt file next to the Dolphin binary. I think that will make implementing it on MacOS simpler (which someone who knows what they're doing on macos can implement).
The PR results in updating safely failing (no files are changed) the update if any of these conditions occur (note this behavior describes actual PR state, the discussion following this post is outdated):
1) OS version is lower than one specified by incoming build
2) VC++ Redist version is lower than one specified by incoming build AND installing the Redist update fails.
1) The Redist version takes into account the version indicated in the existing dolphin install as well as the one actually installed on the system. This means someone with loose redist DLLs can update …

WinUpdater: Check OS and VC++ Redist versions

---

Source/Core/Core/IOS/IOS.cpp

This avoids issues with devices relying on `s_ios`, which would be a `nullptr` while still in the constructor.
For example the ES device will call `InitIPC` which makes sure `s_ios` is not `nullptr`, which it always is while still in the constructor.

IOS::HLE::Kernel::InitIPC: Replace s_ios check with Core::IsRunning

---

Source/Core/InputCommon/GCAdapter.cpp
Source/Core/InputCommon/GCAdapter.h

This is in preparation for #10489 (GCAdapter ControllerInterface support).
The main thing is processing input in the read thread rather than the `Input` function so device changes and input work when a game isn't running.
I also did some other general cleanups.

GCAdapter: Code cleanups.

---

Data/Sys/GameSettings/GZLP01.ini

The old code caused the black and white effect in some rooms not to work. The new one works properly.

GZLP01.ini – Update Cheatcode to Remove Distance Blur

---

Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp

The upper bits are masked away by the preceding LSR, and the lower bits are masked away by the following BFXIL.

JitArm64: Remove unnecessary instruction from ConvertDoubleToSingle

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp

The previous implementation of Force25BitPrecision was essentially a translation of the x86-64 implementation. It worked, but we can make a more efficient implementation by using an AArch64 instruction I don't believe x86-64 has an equivalent of: URSHR. The latency is the same as before, but the instruction count and register count are both reduced.

JitArm64: Reimplement Force25BitPrecision

---

Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp

Micro-optimization. Some CPUs can fuse CMP+B, TST+B, arith+CBZ, etc.
I also moved things around for CMP+CSET and TST+CSET – which I'm not sure if any CPUs support – but it doesn't hurt anything, so I might as well.

JitAsm64: Reorder instructions in routines to allow macro-op fusion

---

Source/Core/InputCommon/CMakeLists.txt
Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.h
Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm

`CGWindowListCreateDescriptionFromArray` would send a request to WindowServer and block until it got a response.  This had two issues:
1. The call took ~200µs on average.  Dolphin's main emulation thread seems to call UpdateInput() about 5 times per frame during Wii emulation, wasting 1ms per frame
2. Since you're now waiting for WindowServer to get back to you, what if it just happens to be busy when you made your request?  About 5% of calls take >1ms, some upwards of 2ms.
Changes QuartzKeyboardAndMouse to use a KVO observer on the window to update a position variable under a mutex.
Also modifies QuartzKeyboardAndMouse to calculate mouse coordinates relative to the main view, rather than the entire window (which includes the window's titlebar).

InputCommon:QuartzKB&M: Use KVO to watch window position

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h

JitArm64: FIFO optimization improvements

---

Source/Core/Core/HW/WiimoteEmu/Extension/Shinkansen.cpp
Source/Core/Core/HW/WiimoteEmu/Extension/Shinkansen.h

Directional button ordering everywhere else in the dialog is Up, Down, Left, Right.
Now the Shinkansen extension matches.
I've also eliminated the unused digital button mappings for the levers.
`L-Analog` has effectively been renamed to just `L` (and same for R/R-Analog).
I'll add a mapping indicator for the `Triggers` group in another PR.

WiimoteEmu: Shinkansen Tweaks

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64Common/BlockCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitAsmCommon.h

The new `dispatcher_no_timing_check` is the same as `dispatcher_no_check` except it includes the "stepping check" in debug mode. This lets us avoid the `m_enable_debugging ? dispatcher : dispatcher_no_check` dance.

Jit64: Add dispatcher_no_timing_check jump target

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp

Some refactorization to get rid of duplicated code. Preparation for implementing AccurateNaNs in JitArm64.

JitArm64: Merge ps_mulsX, ps_maddXX, and parts of fp_arith

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/WiiUtils.java
Source/Android/app/src/main/res/values/strings.xml
Source/Android/jni/WiiUtils.cpp
Source/Core/Core/Boot/AncastTypes.h
Source/Core/Core/Boot/DolReader.cpp
Source/Core/Core/Boot/DolReader.h
Source/Core/Core/CMakeLists.txt
Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/Core/IOS/ES/Formats.h
Source/Core/Core/IOS/IOS.cpp
Source/Core/DiscIO/Enums.cpp
Source/Core/DiscIO/Enums.h
Source/Core/DolphinQt/MenuBar.cpp

This PR adds support for loading the encrypted Ancast images which are used in the vWii mode of the Wii U.
This allows booting the Wii System Menu from extracted vWii NAND dumps.
Some things which should probably be discussed before merge:
- Should the Ancast verification + decryption be moved out of the DolReader? If so where?
- The option in the menu bar will be called `Load Wii System Menu v4.3E (vWii)`. Is this fine?
The vWii never had actual versions, and there are 3 different revisions of the vWii System Menu (v512, v544, v608). All of them show v4.3 if you patch the menu to open settings.

Support for loading vWii System Menu

---

Source/Core/Core/FifoPlayer/FifoRecorder.cpp

See the individual commit messages for details.  
[These fifologs](https://github.com/dolphin-emu/dolphin/files/8723364/RS2Gameplay.7z.zip) are for the first commit (a regression from #9718) (images: [broken](https://user-images.githubusercontent.com/8334194/169202911-2f4a5b6c-c243-4c2e-9c13-5b34fd91f2b4.png), [fixed](https://user-images.githubusercontent.com/8334194/169202915-189e3f32-327f-4db6-b951-f7ac0f2968f4.png)).  JMC provided some luigi's mansion fifologs; here's images: [broken](https://user-images.githubusercontent.com/8334194/169219922-6b03eb9a-1595-4a2b-97ca-baf108f357b7.png), [fixed](https://user-images.githubusercontent.com/8334194/169219915-3faf1d6b-67a6-411f-9b09-26034856b44e.png).

Fifo recorder: Fix various indexed vertex component bugs

---

Source/Core/UICommon/AutoUpdate.cpp
Source/Core/UpdaterCommon/UpdaterCommon.cpp

Fixes https://bugs.dolphin-emu.org/issues/12151
IMO better way to fix the issue than https://github.com/dolphin-emu/dolphin/pull/10990
I (hopefully) haven't modified the logic at all on macos - I'm not sure if it should be or not.
The core of the problem was that `File::Copy(updater_path, reloc_updater_path);` was failing silently. This is actually a pervasive problem in dolphin: many uses of filesystem-related Common functions have no error handling by their callers. I tried adding `[[nodiscard]]` to funcs in FileUtil but fixing such issues quickly became a large change that I'm not necessarily concerned with at the moment (maybe someone else wants to do it?). For instance, the macos path uses `File::CopyDir` in here and that func doesn't even return success indication at all (and the …

WinUpdater: Defer modifying any files until Updater.exe

---

Source/Core/UpdaterCommon/UpdaterCommon.cpp

Currently, the updater is broken 😱 because it would try to read itself from the just-moved-from location and fail

WinUpdater: fix renaming of Updater

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml

This adds PR #10890's new setting to the Android GUI. I'm curious to see if any Android users might get a performance improvement from it.
Due to how our settings work on Android, I haven't implemented disabling the checkbox when the graphics backend doesn't support both GS and VS for point/line expansion, but I don't think that's critical to have.

Android: Add "Prefer VS for Point/Line Expansion" to GUI

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp
Source/Core/Core/PowerPC/PPCAnalyst.h
Source/Core/DolphinQt/Debugger/JITWidget.cpp

None of this seems to be used for anything. I'm guessing it was used at some point in the past?

PPCAnalyst: Remove unused variables and methods in BlockStats and BlockRegStats.

---

Source/Core/Core/HW/WiimoteEmu/Extension/Shinkansen.cpp

For consistency with GameCube controllers and GBAs. I missed this when reviewing the PR.
Also adding some i18n comments while I'm at it.

WiimoteEmu: Change Shinkansen Start/Select to START/SELECT

---

Data/Sys/GameSettings/RLI.ini

In 3465b2af2717ea1e54f866c2857c455b1761efe0 (#10937) I incorrectly put it under [Video_Settings] instead of [Video_Hacks], so it didn't work. https://bugs.dolphin-emu.org/issues/12987 should now properly be fixed.

GameSettings: Properly set MissingColorValue for Lego Indiana Jones 1

---

Source/Core/AudioCommon/WaveFile.cpp
Source/Core/Core/HW/DSP.cpp

This fixes missing audio in various Datel titles; see https://bugs.dolphin-emu.org/issues/12281. They send a large number of samples at the same time, since they don't have to deal with an actual DSP program generating them. Before, we were sending all of the samples at once, which would be too large to ever fit in the buffer in `Mixer.cpp` and thus the code that prevents overflowing the buffer rejected the samples. This new approach should be more hardware-accurate, though I haven't done any testing related to it.
Compared to #10738, this change does not result in audio desyncs after pressing tab to disable the speed limit, and I never encountered any duplicated sound effects on Datel titles.
This PR reverts #720 (but it keeps the length 0 change from #762).  Other PRs that are good for …

DSP: Copy audio dma samples one block at a time

---

Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/XFMemory.h

See https://bugs.dolphin-emu.org/issues/13070.
I hardware tested this using the `codcamp.dff` fifolog from that issue, along with a version I hex-edited, using the [hardware fifoplayer](https://github.com/pokechu22/fifoplayer/tree/improved): [codcamp.7z.zip](https://github.com/dolphin-emu/dolphin/files/9857430/codcamp.7z.zip). Note that the last object in this fifolog needs to be disabled to get rid of a white screen (and the one before it can be removed to disable bloom). Specifically, I edited object 476 on frame 0, at offsets 00175d49 and 00175d54. The default version uses XFMEM_VTXSPECS with Num normals: Invalid (3) and CP_VAT_REG_A with Normal elements: 3 (normal, tangent, binormal) (1), while my hex-edited version uses Num normals: Normal only (1) and Normal elements: 1 (normal) …

VideoCommon: Treat invalid normal count as NormalTangentBinormal

---

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp
Source/Core/VideoBackends/Vulkan/CommandBufferManager.h

Makes the multiple threads actually able to run at the same time
Fixes https://bugs.dolphin-emu.org/issues/12961

VideoBackends:Vulkan: Improve backend multithreading

---

Source/Core/VideoCommon/VertexLoader_Color.cpp
Source/Core/VideoCommon/VertexLoader_Position.cpp
Source/Core/VideoCommon/VertexLoader_TextCoord.cpp

I originally added these in 2b1d1038a6acf0acf75b03ca93c85de6fe6cdf18 (#9718), for both the `TPipelineFunction` and the size. The size was moved into the header in fdcd2b7d009cece6ad090143ce954aed713bb11c (#11066) (making the size functions obsolete), but it seems that the functions themselves are no longer needed now.
I think I didn't use this approach before because it would have required `ComponentFormatTable` and `ComponentCountRow` to be templated, which would end up resulting in lines that were too long and thus wrapped in awkward places. (I *think* they didn't get inferred properly.) Now that we only need `TPipelineFunction`, the templating is not needed, and this ends up being a more readable version of the version with the wrapper functions.
This PR replaces #11159.

VertexLoader: Remove "too many initializer values" workaround functions

---

Source/Core/Core/Config/GraphicsSettings.h

This enum doesn't even exist. The correct one is forward-declared in FreeLookSettings:
https://github.com/dolphin-emu/dolphin/blob/d367b3ec3bba9ca53deb3d08d636c75115a68b31/Source/Core/Core/Config/FreeLookSettings.h#L8-L11

GraphicsSettings: Remove unused FreelookControlType enum forward declaration

---

Data/Sys/GameSettings/RHA.ini

Prevents severe graphical issues in "Tanks" Minigame.

Disable Vertex Rounding in Wii Play

---

Data/Sys/GameSettings/SMN.ini

Vertex Rounding causes severe animation issues on 3D models, so let's disable it.  Also correct the game title to match the wiki.

Disable Vertex Rounding in New Super Mario Bros. Wii

---

Data/Sys/GameSettings/GXX.ini

Fixes invalid read spam during normal battles and Pokemon Bingo.  Also reannotated the INI file to say what each setting fixed for future reference.

Enable MMU in Pokemon XD

---

Data/Sys/GameSettings/SF8.ini

This enhancement causes a rather distracting outline around the main characters.  Let's disable it for users who use this setting in other games so they don't have to go hunting around to figure out what is breaking rendering.

Disable Force Texture Filtering in DKCR

---

Source/Core/DolphinQt/RenderWidget.cpp
Source/Core/DolphinQt/RenderWidget.h

Now the "Pause on Focus Loss" setting will not unpause unless it actually performed the pause.
This fixes issue: https://bugs.dolphin-emu.org/issues/13071
I've purposely removed the `Config::Get(Config::MAIN_PAUSE_ON_FOCUS_LOST)` check in the `WindowActivate` event to produce the following desirable behavior:
The user notices the emulator is pausing on focus loss but they don't want this.
They open the config (causing the emulator to automatically pause).
They disable the "Pause on Focus Loss" setting and close the config window.
The emulator automatically resumes, despite the setting now being disabled, because it was automatically paused previously.
This is what they want. They want the game to be running now.

DolphinQt: Fix window focus from unpausing after a manual pause.

---

Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
Source/Core/DolphinQt/Config/Mapping/MappingWindow.h

The "All devices" option in the device list is confusing.
It's not a device selection. It only changes the behavior for the mapping buttons, allowing them to produce "full-path" input expressions for the non-selected device.
e.g. With "Keyboard Mouse" selected you can press a button on your PS5 controller to create an `SDL/0/PS5 Controller:Button 2` input expression with "All devices" activated.
I've moved the feature to a menu of the "Refresh" button to hopefully make it more apparent that it is a configuration mode and not a device selection.
The feature is disabled every time the dialog is opened (same as old behavior).

DolphinQt: Make "All Devices" mapping hopefully less confusing.

---

Source/Core/VideoBackends/D3D12/DX12Texture.h

This pulls out the D3D12 fix for calculating the subresource from my post processing overhaul.
See section "subresource indexing" in https://learn.microsoft.com/en-us/windows/win32/direct3d12/subresources
Example, if our level count is 2 and our layer count is 3.  We want to access the 2nd level and the 2nd layer.
We'd have this in master:
`CalcSubresources(1, 1) => 4`
vs this with the change:
`CalcSubresources(1, 1) => 3`

VideoBackends: fix d3d12 subresource calculation

---

Source/Android/app/build.gradle
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/InputBindingSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/InputBindingSettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RumbleBindingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThemeHelper.java

Basically an up to date version of #8969 
`android.preference.PreferenceManager` is deprecated so it's being replaced by the androidx version.

Android: Use androidx preference manager

---

Source/Core/Common/Debug/MemoryPatches.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp

For a long while, multiple patched instructions at a time could only be restored in reverse order of patching. This PR fixes the oversight, allowing users to restore patched instructions in any order they like.

MemoryPatches: Fix instruction patches

---

Source/Core/DiscIO/VolumeVerifier.cpp

When searching for a disc where the revision doesn't match any disc in the datfile, the loop would never get to the part where serials_exist is set to true, leading to a bogus error message.

VolumeVerifier: fix bogus "serial/version missing" error

---

Source/Core/VideoBackends/D3D12/D3D12BoundingBox.cpp
Source/Core/VideoBackends/D3D12/D3D12Renderer.cpp
Source/Core/VideoBackends/D3D12/DescriptorHeapManager.cpp
Source/Core/VideoBackends/D3D12/DescriptorHeapManager.h

Fixes [issue 13087](https://bugs.dolphin-emu.org/issues/13087)
The last commit is the interesting one. I explain the bug in the commit message.

VideoBackends:D3D12: Fix hang in Twilight Princess

---

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.h

Always update the combobox when a new target address is sent.
The main problem was that navigating to an address from another widget wouldn't update the address box.  It worked for peeking at a section, then going back to the original, unchanged search address, but not much else.  I added a 10 slot history of addresses so you could keep your old address. All navigated to addresses (from other widgets) will go into the text box and history box automatically and the original address that gets overwritten will be saved in the combo box too.
Two issues in doing this were the offset box and typed addresses.  The offset box is too cumbersome to worry about imo, selecting an address from the combobox will add the offset box to it.  Typed addresses don't feel like they should immediately be added …

MemoryWidget: Make search address a combobox that holds address history.

---

Source/Core/Common/FileUtil.cpp

this should™ fail less and behave more like posix rename()
intended to fix https://bugs.dolphin-emu.org/issues/13093 , hopefully fixes more stuff as well..

windows: Rename: use std::filesystem::rename for posix behavior

---

Data/Sys/GameSettings/R9G.ini

Disable "Force Texture Filtering" in Owls of Ga'Hoole

---

Source/Core/VideoBackends/Vulkan/CommandBufferManager.h

Fixes:
```
35:01:531 VideoBackends/Vulkan/VulkanContext.cpp:745 E[Host GPU]: Vulkan debug report: (Validation) Validation Error: [ VUID-VkDescriptorPoolCreateInfo-maxSets-00301 ] Object 0: handle = 0x7f1,b8d,3cd,e70, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa1,70e,236 | vkCreateDescriptorPool(): pCreateInfo->maxSets is not greater than 0. The Vulkan spec states: maxSets must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkDescriptorPoolCreateInfo-maxSets-00301)
```

VideoBackends:Vulkan: Fix 0 size descriptor pools

---

Source/Core/VideoBackends/OGL/OGLShader.cpp
Source/Core/VideoBackends/OGL/OGLTexture.cpp

This fixes GL_INVALID_VALUE errors when using GPU texture decoding.

OGL: fix compute shader labels

---

Source/Android/app/src/main/res/values-w300dp/integers.xml
Source/Android/app/src/main/res/values-w400dp/integers.xml
Source/Android/app/src/main/res/values/integers.xml

On some displays, the game cards could start to clip if the width of the display was small enough. This ensures that we can go down to as little as 1 card per row and in-between.
Before - 
After -

Android: Add more game grid sizes for long displays

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/Jit_Util.cpp

Otherwise we might throw the result away. Fixes https://bugs.dolphin-emu.org/issues/13083.

JitArm64: Move MMIO handler result before popping stack

---

Source/Core/DolphinLib.props
Source/Core/InputCommon/CMakeLists.txt
Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Source/Core/InputCommon/ControllerInterface/ControllerInterface.h
Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.h
Source/Core/InputCommon/ControllerInterface/InputBackend.cpp
Source/Core/InputCommon/ControllerInterface/InputBackend.h
Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Source/Core/InputCommon/ControllerInterface/SDL/SDL.h
Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
Source/Core/InputCommon/ControllerInterface/evdev/evdev.h

This adds an `InputBackend` interface for `ControllerInterface` to use to init/deinit/populate the various input backends with fewer `#ifdefs`.
Moving the input backend code into classes also eliminates their global state.
I've only changed SDL, evdev, and DSU so far. Maybe that is enough for this PR.

ControllerInterface: Add InputBackend interface.

---

Data/Sys/GameSettings/GEME7F.ini
Data/Sys/GameSettings/GEMJ28.ini

Allows the NTSC and NTSC-J versions to use full frame rendering.  This allows them to behave correctly with Dolphin's Force Progressive hack.  Without this patch, the game shake up and down 1 pixel every other frame.
Codes originally from Swiss, written by Extrems.

Add Force Progressive Patch for Egg Mania

---

Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

Optimize generated code for `cmp`/`cmpl`, mostly by introducing handling for specific constant values.
---
**cmpl**
<details><summary>a == 0</summary>
Before:
```
0x52800019   mov    w25, #0x0
0xb94087b6   ldr    w22, [x29, #0x84]
0xcb16033b   sub    x27, x25, x22
```
After:
```
0xb94087b9   ldr    w25, [x29, #0x84]
0xcb1903fb   neg    x27, x25
```
</details>
---
**cmp**
<details><summary>a == 0</summary>
Before:
```
0x52800016   mov    w22, #0x0
0xb94093b5   ldr    w21, [x29, #0x90]
0x93407ed7   sxtw   x23, w22
0x93407eb9   sxtw   x25, w21
0xcb1902f9   sub    x25, x23, x25
```
After:
```
0xb94093b7   ldr    w23, [x29, #0x90]
0x4b1703f9   neg    w25, w23
0x93407f39   sxtw   x25, w25
```
</details>
<details><summary>a == -1</summary>
Before:
```
0x12800015   mov    w21, #-0x1
0x93407eb9 …
```

JitArm64: Optimize cmp

---

Source/Core/VideoBackends/Software/Clipper.cpp
Source/Core/VideoCommon/Statistics.h

This is clearer and reduces IntelliSense problems.

VideoCommon/Statistics: Require semicolons after statistics macros

---

Source/Core/Common/CMakeLists.txt
Source/Core/Common/Debug/CodeTrace.cpp
Source/Core/Common/Debug/CodeTrace.h
Source/Core/DolphinLib.props
Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.h
Source/Core/DolphinQt/Debugger/RegisterWidget.cpp
Source/Core/DolphinQt/Debugger/RegisterWidget.h

Adds CodeTrace file and two "simple" uses for it: Auto-stepping through code to track a value from the PC, and register widget auto-stepping until a target register appears.
When right-clicking PC in codeview, new options appear. Operates on target (left-most) register in instruction. Tracks the target value, not just the register, so tracking can hop to another register or memory if the value is shuffled there. May track multiple registers at once if the value is duplicated.
- Run until target value is hit: Simply autostep until target appears again. 
- Added run until hit for the register widget as well. Runs the code until the selected register appears.
- Run until target value is used: Silently tracks target register's value through load/store/moves until it is used (pointer, …

Debugger: Implement base code tracing logic. and feature to auto-step through code.

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h

Everything in the table was being re-created on every update. Future work needs the table to persist.
Added CreateTable(), move all constants and semi-constants into it. It is called when the table size changes, font changes, or the displayed data type changes. 
Update() now updates address values and calls other update functions. Ideally it would only be called when addresses change (scroll, setting a different target address, etc) and after CreateTable(). Cleaning up update logic can be done in another PR, as it depends on MemoryWidget.
UpdateColumns() could be renamed to UpdateDataColumnValues() because it's for updating displayed memory values. This function is smaller than before, which is useful for future PRs. Many constants being re-created were moved. The address is now pulled …

MemoryViewWidget refactor memory table

---

Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/NetPlayServer.h

This allows the 'save collection' part to run even if no clients are connected. Fixes [issue 13095](https://bugs.dolphin-emu.org/issues/13095), if we interpreted that one correctly anyway.

NetPlay: Split SyncSaveData() into two parts.

---

Source/Core/Core/Boot/Boot.cpp

I recently talked to a homebrew developer who was trying to add exception handlers at link time but found out that Dolphin was overwriting their exception handlers. I figure that's not the usual way to do exception handlers, but... making us load the executable after setting up memory rather than before is easy, and matches what we do when booting discs, so I suppose there's no reason not to do it. It also matches the intent of why Dolphin is writing default exception handlers – we're writing them because some homebrew relies on exception handlers being left around from whatever program was running before it (see PR #6247).

Boot: Load DOL/ELF after memory setup

---

Source/Android/app/src/main/res/layout-notouch/fragment_emulation.xml
Source/Android/app/src/main/res/layout-port-notouch/fragment_emulation.xml

When inflating this layout, the layout inflater doesn't expect a View and rather a descendant of ViewGroup. This resulted in a crash which is resolved by using a FrameLayout instead.
Basically, running the emulation activity on an Nvidia Shield (or any device without a touchscreen) will crash without this fix.

Android: Use FrameLayout as root for notouch emulation layout

---

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp

I've seen multiple people not realize that the Actions is a menu that's clickable. Does this improve the situation, by making a second menu option which makes it clearer that it's a menu bar?

MemoryWidget: Split Actions into Import and Export.

---

Source/Core/VideoCommon/NativeVertexFormat.h

The default compiler-generated initializer isn't required to initialize padding, making for fun non-determinism when playing back fifologs
See: https://gcc.godbolt.org/z/vev3n47d9
Note: I'm not sure the compiler-generated copy constructor is required to copy padding either, but all notable C++ compilers do, and we static_assert that PortableVertexDeclaration is trivially copyable
(Fixes the random missing textures on the M1 fifoplayer)

VideoCommon: Zero PortableVertexDeclarations on initialization

---

Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/PrintAction.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/PrintAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionData.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.h
Source/Core/VideoCommon/TextureCacheBase.cpp

I missed this in my initial graphics mod review.  I created a texture load hook but never called into it!  This fixes that.
This change will be used in a couple upcoming graphics mod PRs.

VideoCommon: call texture load graphics mod hook when textures are loaded

---

Source/Core/DolphinQt/RenderWidget.cpp
Source/Core/VideoCommon/RenderBase.cpp
Source/Core/VideoCommon/RenderBase.h

Fix for https://bugs.dolphin-emu.org/issues/12652. Includes the commit from #10458.
@Pokechu22 As far as I can tell this works fine, can you see if you can figure out why you thought you couldn't acquire the lock during shutdown?

ImGui render context race condition fix: Lock context during Init/Shutdown.

---

Source/Android/app/src/main/res/layout/list_item_cheat.xml

Sometimes a gecko code would have a title long enough to appear over the checkbox. This is now prevented by marking the text's boundary a 16dp before the start of the checkbox.

Android: Fix list_item_cheat text

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

[M1 GPUs currently have a bug where rendering with mipmaps is slightly nondeterministic](https://github.com/tellowkrinkle/MetalBugReproduction/releases/tag/BrokenMipmapRender) (the differences always happen at the edges of triangles, so I'm guessing it's an issue with helper invocations / bad derivatives leading to picking the wrong mip level).  This (and the issue fixed by #11246) has kept the M1 fifoci offline, as it had a lot of issues with false positives.
Add an option to disable mipmaps so we can use the M1 fifoci again.

VideoCommon: Add option to disable mipmaps

---

CMakeLists.txt
Externals/expr/CMakeLists.txt
Externals/expr/LICENSE
Externals/expr/include/expr.h
Externals/licenses.md
Source/Core/Core/CMakeLists.txt
Source/Core/Core/PowerPC/BreakPoints.cpp
Source/Core/Core/PowerPC/BreakPoints.h
Source/Core/Core/PowerPC/Expression.cpp
Source/Core/Core/PowerPC/Expression.h
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/DolphinLib.props
Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
Source/Core/DolphinQt/Debugger/BreakpointWidget.h
Source/Core/DolphinQt/Debugger/NewBreakpointDialog.cpp
Source/Core/DolphinQt/Debugger/NewBreakpointDialog.h
Source/VSProps/Base.Dolphin.props

A rebase of abandoned #9334 and fixed the one issue posted in that PR.
**To Do in future PRs:**
- Add callstack-based conditionals.
- Add string support for symbol conditional.
- Expand to memory breakpoints.
- Improve writing to registers/memory. Does not seem to work conditionally.
- Make a  help window.
If anyone thinks I should add any of those points to this PR let me know.
Jit and JitAsm have " ABI_CallFunction(PowerPC::CheckBreakPoints); ", which I think causes the breakpoint check to happen twice and two breakpoint log messages are made for one hit.  Is that intentional?
/edit [Check my private branch here](https://github.com/TryTwo/dolphin/tree/Conditional_Memory_Complete) for a branch with callstack and memory breakpoints.

Conditional breakpoints

---

Source/Android/app/src/main/res/values/styles.xml

This brings the ripple color for the default theme more in line with the other themes.
Before - 
After -
Button Ripple in another theme -

Android: Change alert dialog button ripple color for default theme

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/GlideUtils.java

As mentioned by @JosJuice in #11245, I have offloaded the unmangling of the custom cover path to another thread.
(On UI Thread)
Performance Before - 
Performance After -

Android: Offload cover path unmangling to another thread

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/SystemUpdateProgressBarDialogFragment.java
Source/Android/app/src/main/res/layout/dialog_progress_tv.xml

Previously the TV activity would crash when attempting to update the wii system menu because components that inherit from AppCompat themes could not be inflated.

Android: Use progress bar that does not inherit from AppCompat on leanback

---

Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp
Source/Core/DolphinQt/Config/Mapping/MappingWidget.h

The removed hacks are no longer needed now that the base-class, `ElidedButton`, overrides `sizeHint`.
This fixes: https://bugs.dolphin-emu.org/issues/11707

DolphinQt: Allow mapping buttons to expand horizontally.

---

Source/Core/Common/FileUtil.cpp
Source/Core/Common/FileUtil.h
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/Updater.cpp
Source/Core/DolphinQt/Updater.h
Source/Core/UICommon/AutoUpdate.cpp
Source/Core/UICommon/AutoUpdate.h

Fixes error reporting during update checks and adds error messages for several things that can go wrong while triggering an update.
On master, any error during an update check either incorrectly reports Dolphin is up to date (for manual checks) or is just logged (for automatic checks). This PR reports the correct errors, and also shows a message box for all manual check results and certain automatic results to make issues more visible.
Event details:
- Up to date: (Unchanged from master, only shown for manual checks):
"You are running the latest version available on this update track."
- Check request failed: (Error, manual):
"Unable to contact update server."
- Invalid JSON in server response: (error, manual and automatic):
"Invalid JSON received from auto-update service: {error …

Add updater error messages

---

Source/Core/Common/ChunkFile.h
Source/Core/Core/IOS/FS/HostBackend/FS.cpp
Source/Core/Core/IOS/FS/HostBackend/FS.h
Source/Core/Core/State.cpp

This change makes all files and folders in NAND be recursively saved/loaded in save states. More specifically, when a movie is being created/played back, the full contents of the Dolphin Emulator/WiiSession folder will be saved/restored recursively.

HostFileSystem: Set all NAND folders to be saved in save states

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/RunRunnable.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RunRunnableViewHolder.java
Source/Core/DolphinQt/Settings/WiiPane.cpp
Source/Core/DolphinQt/Settings/WiiPane.h

It won't work, since Dolphin is keeping the SD card file open.

Disable SD card conversion while emulation is running

---

Source/Core/Core/IOS/DolphinDevice.cpp
Source/Core/Core/IOS/DolphinDevice.h
Source/Core/UICommon/DiscordPresence.cpp

Upstream's current `GetSystemTime` function returns the elapsed time. According to the comment, the change was made with the goal of making "buggy emulated code less likely to have issues". However, the old functionality is applicable when generating Unix timestamps for Discord rich presence.
If this implementation of generating these timestamps is not preferred, I am open to suggestions on alternative methods.

Add DolphinDevice::GetSystemTime to allow for accurate Unix timestamp generation

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

Optimize multiplication for various constants. We introduce a `MultiplyImmediate` function, which contains the logic much like the one that exists for x86, and reuse it in both `mulli` and `mullwx`.
Also a minor register allocation improvement for `mulli`.
---
<details><summary>Multiplication by 0</summary>
Before:
```
0x52800019   mov    w25, #0x0
0x1b197f5b   mul    w27, w26, w25
```
After:
```
```
</details>
<details><summary>Multiplication by 1 (example 1)</summary>
Before:
```
0x52800038   mov    w24, #0x1
0x1b1a7f1b   mul    w27, w24, w26
```
After:
```
0x2a1a03fb   mov    w27, w26
```
</details>
<details><summary>Multiplication by 1 (example 2)</summary>
Before:
```
0x52800039   mov    w25, #0x1
0x1b1a7f3a   mul    w26, w25, w26
```
After:
```
```
</details> …

JitArm64: Optimize multiplication

---

Source/Core/VideoCommon/FramebufferManager.cpp
Source/Core/VideoCommon/FramebufferManager.h

Small thing I noticed after #11098 got merged.
Otherwise we might never hit the early return if either depth or color doesnt have any active tiles.

VideoCommon:FramebufferManager: Mark cache as valid after refresh

---

Source/Core/Core/HW/SI/SI_Device.h
Source/Core/Core/HW/SI/SI_DeviceGCController.cpp

Avoids a panic when loading recent swiss. Not enough to have it run, unfortunately.

SI: Ignore non-standard setGameID command

---

Source/Core/VideoCommon/FramebufferManager.cpp
Source/Core/VideoCommon/FramebufferManager.h

VideoCommon/FramebufferManager: Further EFB cache cleanup

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
Source/Android/app/src/main/res/anim/anim_card_game_in.xml
Source/Android/app/src/main/res/anim/anim_card_game_out.xml

Subtle animation when using controller navigation.

Android: Animate covers on focus change

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
Source/Android/app/src/main/res/layout/fragment_grid.xml
Source/Android/app/src/main/res/values-w1000dp/integers.xml
Source/Android/app/src/main/res/values-w1050dp/dimens.xml
Source/Android/app/src/main/res/values-w300dp/integers.xml
Source/Android/app/src/main/res/values-w400dp/integers.xml
Source/Android/app/src/main/res/values-w500dp/integers.xml
Source/Android/app/src/main/res/values-w750dp/integers.xml
Source/Android/app/src/main/res/values-w820dp/dimens.xml
Source/Android/app/src/main/res/values/dimens.xml
Source/Android/app/src/main/res/values/integers.xml

In order to avoid getting stuck making a new dimension file every time a new device is found we take a known value for how large the game card will be, take the screen size, and adjust the grid accordingly.

Android: Dynamically adapt grid span to card_game size

---

Source/Android/app/src/main/res/values/dimens.xml

Spacing required by each card before was a little bit too much. The span of the list will appear more appropriately now. (6dp spacing on both sides instead of 8.5dp)

Android: Adjust card_width

---

Source/Core/Common/NandPaths.cpp
Source/Core/Common/NandPaths.h
Source/Core/Core/IOS/ES/ES.h
Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/Core/IOS/ES/Formats.h
Source/Core/Core/IOS/ES/NandUtils.cpp
Source/Core/Core/IOS/ES/TitleManagement.cpp
Source/Core/Core/IOS/ES/Views.cpp

Adds support for the V1Ticket format within ES.
`ES::TicketReader` has been edited to support this format, as well as a couple ES IOCTLV's.
I have only encountered this file format within the Japanese channel Wii no Ma, where it is used in the theatre to track purchased movies. This has been tested with that channel and works perfectly.

IOS/ES: Add support for V1Ticket

---

Source/Core/Core/HW/Memmap.cpp

@booto spotted this on IRC, there were five values for six struct members. This is harmless (false converts to 0, and `shm_position` and `active` get overwritten before use anyway), but might as well fix it.

Memmap: Fix initialization of PhysicalMemoryRegion.

---

Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Paired.cpp

fregsIn will include FD for double-precision instructions, since for dependency tracking purposes the instruction does read the upper half of FD. This is not what we want in HandleNaNs.
The consequence of this bug is that if an instruction was supposed to output a NaN and FD happens to contain a NaN and FD happens to be the same register as an unused register in the instruction encoding, the NaN in FD could get used as the output instead of the correct NaN. This isn't known to affect any games, which isn't especially surprising considering that there's only one game that needs AccurateNaNs anyway.

Jit64: Don't use fregsIn in HandleNaNs

---

Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexLoaderManager.h
Source/Core/VideoCommon/XFStructs.cpp

A bit of a micro optimization:
With this PR CheckCPConfiguration runs 350 times instead of 35k times. (Mario Galaxy)

VideoCommon:VertexLoaderManager: Reduce CPConfig checks

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java

Sometimes getMeasuredWidth would report 0 when the layout is being inflated. This ensures that the grid waits until the correct measurement is reported before we set the grid span.

Android: Fix condition where we set grid span too early

---

Source/Core/Common/CommonPaths.h
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
Source/Core/Core/NetPlayServer.cpp
Source/Core/DolphinQt/GameList/GameList.cpp
Source/Core/DolphinQt/Settings/GameCubePane.cpp
Source/Core/DolphinQt/Settings/GameCubePane.h

Let's try this again.
I feel like people request this once a week, so we should really implement this in some form. The previous attempt (at #10379) got stalled because a) no one reviews UI code and b) we couldn't even agree on a proper UI for this, so I'll just take a hard stance this time and say this uses the exact same UI that is already in use for the raw memory cards.
This intentionally does not use the existing internal 'GCI folder override' settings (which were designed for Netplay) because they ignore the automatic region handling, which should be kept because mixing Western and Japanese text encodings on the same memory card can cause issues.
I've thought long and hard about how to present to the user what path they are configuring, and I ended up with a similar thing to what we …

Add config setting for base GCI folder path.

---

Source/Core/Core/HW/GBAPadEmu.cpp
Source/Core/Core/HW/GBAPadEmu.h
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MainWindow.h
Source/Core/DolphinQt/TAS/GBATASInputWindow.cpp
Source/Core/DolphinQt/TAS/GBATASInputWindow.h

When emulated GBAs were added to Dolphin, it was possible to control them using the GC TAS input window. (Z was mapped to Select.) Unaware of this, I broke the functionality in b296248.
To make it possible to control emulated GBAs using TAS input again, I'm adding a proper TAS input window for GBAs, with a real Select button and no analog controls.

DolphinQt: Add GBA TAS input window

---

Source/Core/WinUpdater/Main.cpp

ie, don't blindly assume working directory is directory Updater.exe is in.
This should fix the weird issue where a chain of Dolphin.exe -> Updater.exe -> Dolphin.exe -> Updater.exe requests UAC because it tries to open `Updater.log` in `C:\Windows\System32` (which is the working directory inherited from the permissions downgrade via `explorer.exe`).
Technically the arguments *could* request a different path to write the update to, but that shouldn't really happen in practice I think...?

Updater: Check for write permissions in directory of Updater.exe.

---

Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/VertexLoader.cpp
Source/Core/VideoCommon/VertexLoader.h
Source/Core/VideoCommon/VertexLoaderARM64.cpp
Source/Core/VideoCommon/VertexLoaderARM64.h
Source/Core/VideoCommon/VertexLoaderBase.cpp
Source/Core/VideoCommon/VertexLoaderBase.h
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexLoaderManager.h
Source/Core/VideoCommon/VertexLoaderUtils.h
Source/Core/VideoCommon/VertexLoaderX64.cpp
Source/Core/VideoCommon/VertexLoaderX64.h
Source/Core/VideoCommon/VertexLoader_Normal.cpp
Source/Core/VideoCommon/VertexLoader_Position.cpp
Source/Core/VideoCommon/VertexLoader_TextCoord.cpp
Source/UnitTests/VideoCommon/VertexLoaderTest.cpp

DataReader is generally jank - it has a start and end pointer, but the end pointer is generally not used, and all of the vertex loaders mostly bypassed it anyways.
Wrapper code (the vertex loaer test, as well as Fifo.cpp and OpcodeDecoding.cpp) still uses it, as does the software vertex loader (which is not a subclass of VertexLoader). These can probably be eliminated later.
I've also included a commit that enables the vertex loader comparison functionality temporarily, so that fifoci will ensure that this doesn't cause any problems with the software vertex loader.

VertexLoader: Eliminate use of DataReader

---

Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/Jit_Util.cpp

This new function is like MOVP2R, except it masks out the lower 12 bits, returning them instead of writing them to the register. These lower 12 bits can then be used as an offset for LDR/STR. This lets us turn ADRP+ADD+LDR sequences with a zero offset into ADRP+LDR sequences with a non-zero offset, saving one instruction.

Arm64Emitter: Add MOVPage2R utility function

---

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStoreFloating.cpp

The old code would first MOV the old imm into Ra and then do an ADD. We can skip the ADD and just MOV the new imm.

Jit64: Use MOV instead of ADD for updating imm Ra

---

Source/Core/Core/CoreTiming.cpp
Source/Core/Core/CoreTiming.h
Source/Core/Core/HW/AudioInterface.cpp
Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/DVD/DVDThread.cpp
Source/Core/Core/HW/EXI/EXI.cpp
Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.h
Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/HW/SI/SI.cpp
Source/Core/Core/HW/SystemTimers.cpp
Source/Core/Core/HW/WII_IPC.cpp
Source/Core/Core/IOS/DI/DI.cpp
Source/Core/Core/IOS/DI/DI.h
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/PowerPC/GDBStub.cpp
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/PixelEngine.cpp
Source/UnitTests/Core/CoreTimingTest.cpp

More steps towards de-globalization.

CoreTiming: Pass Core::System to Events.

---

Data/Sys/GameSettings/RHT.ini

Fixes video hangs in single core and unknown opcodes during FMVs in Dualcore.
Game is technically playable in Single Core without this, but you have to wait an absolute eternity during the opening cutscene, as it is unskippable.  Dualcore will usually crash with unknown opcodes.
This is 100% a hack, but until we have a CPU timing rewrite, maybe it'd be best to take care of the most extreme cases of games not running at all by default instead of forcing users to figure it out.

GameINI:  Enable slight CPU Overclock for Manhunt 2

---

Data/Sys/GameSettings/GW9.ini

Fixes invisible character models in Revenge Mode.

Force EFB2RAM in WWE WrestleMania XIX

---

Source/Core/AudioCommon/AudioCommon.cpp
Source/Core/AudioCommon/AudioCommon.h
Source/Core/Core/Core.cpp
Source/Core/Core/HW/CPU.cpp
Source/Core/Core/HW/DSP.cpp
Source/Core/DolphinQt/HotkeyScheduler.cpp
Source/Core/DolphinQt/Settings.cpp
Source/Core/DolphinQt/Settings/AudioPane.cpp

The other side of the global state elimination, actually pass around the System class instead of fetching the global instance.

AudioCommon: Pass Core::System to AudioCommon functions.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java
Source/Android/app/src/main/res/layout/dialog_game_details_tv.xml

Previously the app would crash when opening the game details dialog because Material Dividers inherit from AppCompat and the leanback activity does not. This creates a new layout file with leanback-specific accommodations and code is duplicated in GameDetailsDialog to prevent inflation crashes.
I'm not happy with the amount of code I have to duplicate here, but it's the simplest fix I could think of given that I'd like to stick to data binding and keeping material components on the mobile version.

Android: Fix GameDetailsDialog on leanback

---

Source/Core/Common/x64Emitter.h
Source/Core/Core/HW/AudioInterface.cpp
Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/EXI/EXI_Channel.cpp
Source/Core/Core/HW/MMIO.cpp
Source/Core/Core/HW/MMIO.h
Source/Core/Core/HW/MMIOHandlers.h
Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/HW/SI/SI.cpp
Source/Core/Core/HW/VideoInterface.cpp
Source/Core/Core/HW/WII_IPC.cpp
Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Source/Core/Core/PowerPC/JitArm64/Jit_Util.cpp
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/PixelEngine.cpp
Source/UnitTests/Core/MMIOTest.cpp

De-globalizing the MMIO handlers.
I'd like some input here on if this is a good way to do it. The only other approach I can think of would be to capture the system instance in every single complex handler, which IMO is worse, but ymmv.

HW: Pass System to MMIO handlers.

---

Source/Core/Core/PowerPC/BreakPoints.cpp
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Debugger/BreakpointDialog.cpp
Source/Core/DolphinQt/Debugger/BreakpointDialog.h
Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
Source/Core/DolphinQt/Debugger/BreakpointWidget.h
Source/Core/DolphinQt/DolphinQt.vcxproj

This PR allows users to edit existing breakpoints by opening the context menu of a breakpoint and clicking `Edit...`. This also makes it so when you add a new breakpoint that shares the same address as an existing one, the existing breakpoint becomes the new one that the user has just created.

Debugger BreakpointWidget: Edit breakpoints dialog

---

Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
Source/Core/Core/HW/GCMemcard/GCMemcard.h
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.h
Source/Core/Core/NetPlayServer.cpp

Intended to fix [issue 12999](https://bugs.dolphin-emu.org/issues/12999), though I don't know whether it actually does.

GCMemcardDirectory: GCI filename cleanup and fixes.

---

Source/Core/AudioCommon/CubebStream.cpp
Source/Core/AudioCommon/CubebStream.h
Source/Core/Core/HW/EXI/EXI_DeviceMic.cpp
Source/Core/Core/HW/EXI/EXI_DeviceMic.h

oops
(one should always re-check your code before merging, even if the code has been sitting there for ages unchanged...)

Correctly call CoUninitialize() on Cubeb helper class destruction.

---

Source/Core/VideoBackends/OGL/OGLNativeVertexFormat.cpp
Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp
Source/Core/VideoBackends/OGL/ProgramShaderCache.h

Should make #11208 not break half the fifoci traces
(Note: The full issue is that [`OGL::Renderer` only sets the pipeline if it changed](https://github.com/dolphin-emu/dolphin/blob/d7593dd7215d92ea0b5eb8fa8b592f3ed758b2ea/Source/Core/VideoBackends/OGL/OGLRender.cpp#L1236-L1237), not expecting it to be partially unbound.  This doesn't affect anything by itself because without CPUCull, we never create a vertex format without immediately using it in a pipeline, but with CPUCull, we can create a vertex loader and then cull all the triangles that used it before switching back to the previous pipeline, completely skipping it.)

VideoBackends:OGL: Creating vertex formats shouldn't unbind anything

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp

1. In some cases, ps_merge01 can be implemented using one instruction.
2. When we need two instructions for ps_merge01, it's best to start with a MOV to avoid false dependencies on the destination register.
3. ps_merge10 can be implemented using a single EXT instruction.

JitArm64: Optimize ps_mergeXX

---

Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Paired.cpp

HandleNaNs assumes that a NaN in a ps0 input always results in a NaN in the ps0 output, and correspondingly for ps1. This isn't the case for ps_mulsX and ps_sumX.

Jit64: Correctly handle NaNs for ps_mulsX/ps_sumX

---

Data/Sys/GameSettings/RLEEFS.ini

A call to GXCopyDisp(), made once before the title screen for no apparent purpose, is causing heap corruption, but it isn't observed on real hardware thanks to the data cache. Skipping the call works too, preventing a crash on the main menu.
Fixes https://bugs.dolphin-emu.org/issues/12699
My investigation was prompted by this comment: https://github.com/dolphin-emu/dolphin/pull/11183#issuecomment-1288432004
For reference, this is virtually the same bug found in Monster High: #9316

GameSettings: Add patch for Ten Pin Alley 2 (RLEEFS)

---

Source/Android/app/src/main/res/values/themes.xml

For some reason the default setting for display cutouts doesn't apply to the main activity. So this fixes the main activity getting cut off by display cutouts in landscape mode.
Before (Imagine there's a camera hole on the left side) - 
After -

Android: Letterbox content with display cutouts in landscape

---

Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/JitInterface.h
Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Source/Core/DolphinQt/Debugger/JITWidget.cpp
Source/Core/UICommon/Disassembler.cpp
Source/Core/UICommon/Disassembler.h

A few fixes, mostly improving the JIT widget (although one also affects selecting "view code" in the memory widget/registers widget).

Jit widget fixes

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/res/drawable/dialog_round.xml

This removes a bunch of restricted api calls in favor of Google's much more nicely packaged ElevationOverlayProvider. The dialog looks the same as before.

Android: Greatly simplify MotionAlertDialog theming

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThreadUtil.java
Source/Android/app/src/main/res/layout/dialog_indeterminate_progress.xml

Always felt a bit off that we would just have text and not an indeterminate progress bar. This fixes that. (Also I checked, this does not crash the TvMainActivity)
Before - 
After - 
https://user-images.githubusercontent.com/14132249/205419054-725106da-4594-41d8-9d6e-21592be7b883.mp4

Android: Use progress indicator in short loading scenarios

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h

Highlighting wasn't doing much before. Now it lets you know what address is being targeted. The colors can be changed, I just set it to normal.  A stylesheet needed to be used, or else the selected item coloring is removed when focus is lost, which isn't good. 
There is also a thin outline box on whatever cell you click, without changing the highlighting on the target. 
I'm not sure if set focus is needed anymore, but it seemed a little broken when the table was given the slider navbar, so I fixed that.  I think it was mostly a highlighting thing, but then I overrode the highlighting altogether.

Debugger MemoryViewWidget: always highlight target address 

---

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp
Source/Core/VideoBackends/Vulkan/CommandBufferManager.h
Source/Core/VideoBackends/Vulkan/VKRenderer.cpp

Synchronize with the submission thread if the last present is not done yet.
Right now we could potentially run `vkAcquireNextImageKHR` before the previous image is presented
and even run out of buffers. This is an easy fix.
Vulkan spec for `vkAcquireNextImageKHR`:
> If the number of currently acquired images is greater than the difference between the number of images in swapchain and the value of [VkSurfaceCapabilitiesKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceCapabilitiesKHR.html)::minImageCount as returned by a call to [vkGetPhysicalDeviceSurfaceCapabilities2KHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceSurfaceCapabilities2KHR.html) with the surface used to create swapchain, timeout must not be UINT64_MAX

VideoBackends:Vulkan: Synchronize presentation

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/InsetsHelper.java
Source/Android/app/src/main/res/layout/activity_cheats.xml

The sliding panel layout was in the way of the top app bar and prevented the up button from being pressed. This anchors the panel to the bottom of the top app bar and removed unnecessary hardcoded padding.
Before - 
After -

Android: Fix cheats layout

---

Source/Android/app/build.gradle
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThemeHelper.java
Source/Android/app/src/main/res/drawable/ic_back.xml
Source/Android/app/src/main/res/drawable/tv_card_background.xml
Source/Android/app/src/main/res/values-night/bools.xml
Source/Android/app/src/main/res/values-v27/themes.xml
Source/Android/app/src/main/res/values-v29/themes.xml
Source/Android/app/src/main/res/values/arrays.xml
Source/Android/app/src/main/res/values/bools.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Android/app/src/main/res/values/styles.xml
Source/Android/app/src/main/res/values/themes.xml
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp

Now you can chose the theme mode independent of the system. This also allows all Android versions to use a dark theme now. The system-wide toggle was only introduced in Android 10 so users below that version can enjoy this now. This also includes AndroidTV users who used to be stuck with the mode mismatch between the main and settings UI.
Note - Similar to app themes, theme modes have to be loaded before directory initialization is ready. So we save the proper key the same way.
Demo -

Android: Add theme mode switcher

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/InsetsHelper.java
Source/Android/app/src/main/res/layout/activity_emulation.xml
Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
Source/Android/app/src/main/res/values/dimens.xml
Source/Android/app/src/main/res/values/styles.xml

Previously mentioned in #11313 
Before when using the "Expand to Cutout Area" setting, camera notches/other device insets could get in the way of the ingame menu fragment. Now we apply padding based on inset and this accounts for RTL layouts.
Additionally, I've removed unused attributes from the xml and slightly tweaked the padding of the fragment itself to appear clearer.
Before (camera would appear in the way of text on the left) - 
After -

Android: Pad menu fragment when expanding to cutout area

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/ConvertActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatListFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionBootActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/InsetsHelper.java
Source/Android/app/src/main/res/values/dimens.xml

This pulls the activity-specific code out of InsetsHelper. I think I prefer it this way so if there's a change to an activity's insets, we could just change the specific activity's setInsets method and not worry about having to split up more methods in InsetsHelper.
Nothing functional is changed here, the organization is just different.

Android: Have each activity manage insets separately

---

Source/Core/Core/HW/GCKeyboardEmu.cpp
Source/Core/Core/HW/GCKeyboardEmu.h
Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp
Source/Core/DolphinQt/Config/Mapping/GCKeyboardEmu.cpp
Source/Core/DolphinQt/Config/Mapping/GCKeyboardEmu.h

Some confused users choose "Keyboard" instead of "Standard Controller" when then intend to play with a keyboard.
This renames "Keyboard" to "Keyboard Controller" and adds some warning text to the mapping dialog.

Rename "Keyboard" to "Keyboard Controller"

---

Source/Core/Core/Debugger/PPCDebugInterface.cpp
Source/Core/Core/PowerPC/BreakPoints.cpp
Source/Core/Core/PowerPC/BreakPoints.h
Source/Core/Core/PowerPC/GDBStub.cpp
Source/Core/DolphinQt/Debugger/BreakpointDialog.cpp
Source/Core/DolphinQt/Debugger/BreakpointDialog.h
Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
Source/Core/DolphinQt/Debugger/BreakpointWidget.h
Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp

I think it's fairly straightforward. I copied the conditional instruction BP changes.

Debugger: Add conditional breakpoints to memory BPs

---

Source/Android/app/src/main/AndroidManifest.xml
Source/Android/build.gradle

We're currently running AGP 7.0.4 because of broken incremental builds as documented here https://issuetracker.google.com/issues/232060576?pli=1
However, upgrading to the latest version comes with several benefits that should be considered even when dealing with this bug.
This release will allow us to -
- Upgrade to [MDC 1.7.0](https://github.com/material-components/material-components-android/releases/tag/1.7.0) with the new MaterialSwitch component and changes to navigation bars that will help in my work on larger layouts
- Use [Baseline Profiles](https://developer.android.com/topic/performance/baselineprofiles/overview) that will make initial app performance much more consistent (~30% faster launch times)
- Avoid undocumented behavior since AGP 7.0.4 only supports up to API 31 and …

Android: Upgrade AGP to 7.3.1

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayProto.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h
Source/Core/VideoCommon/RenderBase.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

A new attempt at #8645, reimplemented from scratch -- the implementation is pretty trivial anyway...
This got stuck in discussion hell last time because MayImilae was against placing the option in the Enhancement tab. I'll be frank, I completely disagree with that point (see below for why), but if that becomes a sticking point again I will move the option elsewhere (or just not show it in the GUI at all), since I'd rather have the option *somewhere* than not at all.
~~I tried out a Radio Button style for this, I'm not sure how much I like it. I can also change this to a dropdown if people think that's better.~~ see further down for the current state
---
The reason why I think this belongs in Enhancements is primarily one of user expectations: Not only has the option existed there in …

Core: Add option to force linear texture filtering.

---

Externals/MoltenVK/CMakeLists.txt

The MoltenVK changelog can be found [here](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.1).

Externals: Update MoltenVK to 1.2.1

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp

This reverts commit 351d095ffffccd424763cb77b13f716b5e4155c1.
In hindsight, my attempted optimization messes with the return predictor, unlike real tail calls. So I think it does more bad than good.

Revert "JitArm64: Optimize a few tail calls"

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/InvertedSwitchSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/LogSwitchSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SettingsItem.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SwitchSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SwitchSettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/ConvertFragment.java
Source/Android/app/src/main/res/layout-ldrtl/list_item_cheat.xml
Source/Android/app/src/main/res/layout/fragment_convert.xml
Source/Android/app/src/main/res/layout/list_item_cheat.xml
Source/Android/app/src/main/res/layout/list_item_setting_switch.xml

This also removes some unnecessary calls to notifyItemChanged to preserve switch animations/interactions and some layout changes to make the switches avoid system gestures.
<details>
Before - 
After - 
</details>

Android: Replace Checkbox with MaterialSwitch

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThemeHelper.java
Source/Android/app/src/main/res/values-night/themes.xml
Source/Android/app/src/main/res/values/dolphin_colors.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp

Makes all background colors black in dark mode when enabled through a ThemeOverlay. Applied the same way as a theme/mode.
Demo -

Android: Add black backgrounds toggle

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java

I'm not sure how this passed through our automated checks but PR #11325 got merged with a semantic error that breaks the Android port. This PR fixes that and allows the Android port to be built again...

Android: fix compile error

---

Source/Android/app/build.gradle
Source/Android/build.gradle
Source/Android/gradle.properties
Source/Android/settings.gradle

This properly allows for Kotlin support in the app module. I've additionally formatted the gradle files to follow Google's templates.
I've already tested using the Java to Kotlin coverter on ThemeHelper.java and it works great.

Android: Introduce Kotlin support

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp

In commit 6f4f4e057e58d1720db7a68f80f6dcc24c686a3e on line 552, the background of the memory viewer was filled to be white. In dark mode this would make it impossible to see the contents of the viewer.

Fix MemoryViewWidget background colour

---

Source/Android/app/src/main/res/layout/activity_cheats.xml

Before the background wouldn't follow the black backgrounds setting and just use the default surface color for a given theme. Now it follows the theme settings corectly.

Android: Use colorSurface attribute for cheats activity background

---

Source/Core/VideoBackends/D3D/D3DPerfQuery.cpp
Source/Core/VideoBackends/D3D/D3DPerfQuery.h
Source/Core/VideoBackends/D3D12/D3D12PerfQuery.cpp
Source/Core/VideoBackends/D3D12/D3D12PerfQuery.h
Source/Core/VideoBackends/OGL/OGLPerfQuery.cpp
Source/Core/VideoBackends/OGL/OGLPerfQuery.h
Source/Core/VideoBackends/Vulkan/StagingBuffer.cpp
Source/Core/VideoBackends/Vulkan/VKPerfQuery.cpp
Source/Core/VideoBackends/Vulkan/VKPerfQuery.h

Queries in the Vulkan renderer are completely broken right now:
- We're trying to access the results before the queries have executed.
- Query results get attributed to the wrong query type.
- The query pool isn't properly reset before reusing the queries.
This seems to have be a regression caused by 604ab67c7f28dc03a82ee7aa1bcc487d39ea6f8c. 
The last commit is somewhat unrelated but it's something I noticed.

VideoBackends: Query fixes and cleanups

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/GridOptionDialogFragment.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Source/Android/app/src/main/res/drawable/ic_list.xml
Source/Android/app/src/main/res/drawable/ic_list_tv.xml
Source/Android/app/src/main/res/layout/fragment_grid_options.xml
Source/Android/app/src/main/res/layout/fragment_grid_options_tv.xml
Source/Android/app/src/main/res/menu/menu_game_grid.xml
Source/Android/app/src/main/res/values-night-v31/themes.xml
Source/Android/app/src/main/res/values-v31/themes.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Android/app/src/main/res/values/styles.xml
Source/Android/app/src/main/res/values/themes.xml

This moves the toggles for downloading covers and showing/hiding game titles to the Main/TvMainActivity. Since showing/hiding covers isn't possible on the TV version, that option is removed entirely. (I'm still working on a new layout to avoid duplicating code like this, but I need more changes like this first)
This also prevents unnecessary viewmodel updates whenever returning from another activity.
Mobile Demo - 
https://user-images.githubusercontent.com/14132249/206937250-db83eb8f-e0ae-4683-9da9-b015be7832f6.mp4
TV Demo - 
https://user-images.githubusercontent.com/14132249/206937272-3668c146-e308-4f0d-93f8-e27424016d4c.mp4

Android: Move game grid options to MainActivity

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp

The calculation of each address in lmw/stmw currently has a dependency on the calculation of the previous address. By removing this dependency, the host CPU should be able to pipeline the loads/stores better. The cost we pay for this is up to one extra register and one extra MOV instruction per guest instruction, but often nothing.
Making EmitBackpatchRoutine support using any register as the address register would let us get rid of the MOV, but I consider that to be too big of a task to do in one go at the same time as this.

JitArm64: Improve pipelining of lmw/stmw

---

Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp

The [Desert Bus homebrew](https://wiibrew.org/wiki/Desert_Bus) uses custom libasnd DSP ucode. Specifically, v1.0.4 and v1.0.5 are modified versions of the ucode that was added to the libogc repo in devkitpro/libogc@b1b8ecab3af3745c8df0b401abd512bdf5fcc011 (although the binary that was added in that commit does not match the code, and a matching binary only started being used in 2020 - see #10763 for my other notes). That libogc patch is attributed to the author of the homebrew, for what it's worth.
<details><summary>The difference between the libogc code and v1.0.4 is this, which swaps the left and right channels for stereo audio:</summary>
```diff
diff --git a/dsp_mixer.s b/dsp_mixer_desert_bus_v1.0.4.s
index 3b52614..9de5b84 100644
--- a/dsp_mixer.s
+++ b/dsp_mixer_v1.0.4.s
@@ -834,10 …
```

DSPHLE: Add Desert Bus libasnd ucode variants

---

Source/Core/Common/Arm64Emitter.h
Source/Core/Common/BitUtils.h
Source/Core/Common/MathUtil.h
Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Source/Core/VideoBackends/Metal/MTLStateTracker.mm
Source/Core/VideoCommon/VideoCommon.h

With the upgrade to C++20, std::countl_zero and std::countr_zero can replace these home-spun implementations from the BitUtil.h library.

Replace BitUtils with C++20: Counting Zeroes

---

Source/Core/VideoBackends/Vulkan/VKVertexManager.cpp

I am looking at NDK releases from before f039149198657c1891e1c6462ed30c31ed4b8486, but cannot tell what has changed about std::min.  Still, surely this is fixed by now.  Was it a compile error, or a logic error?

Follow-up on a four-year-old Android NDK workaround

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SwitchSettingViewHolder.java
Source/Android/app/src/main/res/layout/list_item_setting_switch.xml

Before you couldn't grab and flick a switch. This is now consistent with the rest of the UX.
Before - 
After -

Android: Allow users to interact with switches in settings

---

AndroidSetup.md
Contributing.md

This removes some of the old build instructions and adds better information about how to import the correct code style.

Bring Android documentation up-to-date

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/TwoPaneOnBackPressedCallback.java

This prevents the keyboard from being stuck in an open state if the user slides the panel while focused on a text box. Now it closes gracefully.

Android: Close soft keyboard on panel close

---

Source/Core/DolphinQt/TAS/GBATASInputWindow.cpp

We should expose Enable Controller Input and the turbo settings for GBA just like we do for GameCube controllers and Wii Remotes. I just forgot about it when implementing the GBA TAS input window.

DolphinQt: Add settings to GBA TAS input window

---

Source/Core/VideoCommon/PerformanceMetrics.h

A typo in the original commit made the speed counter sample the last 6 seconds (because of some smoothing it ends up being more like 10 seconds)
This commit reverts it back to its original 0.5s

Video Common: Fix Speed Counter Sample Size

---

Source/Core/Core/IOS/ES/NandUtils.cpp

An incorrectly made if statement would cause `ESDevice::GetTitlesWithTickets` to always return 0 titles owned.

Fix ESDevice::GetTitlesWithTickets always returning 0 titles owned

---

Source/Android/jni/AndroidCommon/AndroidCommon.cpp
Source/Android/jni/AndroidCommon/AndroidCommon.h
Source/Android/jni/Cheats/ARCheat.cpp
Source/Android/jni/Cheats/GeckoCheat.cpp
Source/Android/jni/Cheats/GraphicsModGroup.cpp
Source/Android/jni/Cheats/PatchCheat.cpp
Source/Android/jni/GameList/GameFileCache.cpp
Source/Android/jni/MainAndroid.cpp

If we're in a function that isn't just going to immediately return to Java, leaking local references can lead to problems eventually.

Android: Make more meticulous use of DeleteLocalRef

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml

Whenever the app is not using the default theme, the ingame menu fragment will get a new elevation color like an alert dialog.
This is following an old suggestion from @JosJuice but I can't remember where they mentioned it.
Before - 
After -

Android: Elevate ingame menu fragment with color

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot.h
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Boot/Boot_WiiWAD.cpp
Source/Core/Core/Core.cpp

Removing a bit of `Core::System::GetInstance()`.

Core/Boot: Pass System instance to BootUp() and related.

---

Source/Core/Core/IOS/Network/KD/NWC24Config.cpp
Source/Core/Core/IOS/Network/KD/NWC24Config.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp

In the KD request `IOCTL_NWC24_REQUEST_GENERATED_USER_ID`, the nwc24msg.cfg and nwc24msg.cbk have many of their fields edited, such as the Wii Friend Code and creation stage.
However, the checksum was not being written, causing whatever calls the request to delete the edited data and revert back to the default files.
By writing the checksum, the Wii Number is properly written along with the creation stage and increment id, which should allow for `IOCTL_NWC24_REQUEST_REGISTER_USER_ID` to properly be handled with the default Wii NAND in the future.

Set checksum for NWC24Config during creation

---

Source/Core/Core/Boot/Boot.cpp

Previously, if a user on Windows launched Dolphin from the command line and specified a path to an M3U file and included backslashes in this path, Dolphin would fail to resolve relative paths in the M3U file.
Thanks to Tartifless on Discord for managing to narrow down the conditions under which the problem happens. I've heard reports every now and then about relative paths not working in M3U files ever since the M3U feature was added, but never managed to reproduce it.

Boot: Fix handling of M3U file paths containing backslashes

---

Source/Core/VideoBackends/Software/Tev.cpp

This was added in #10394 for both the hardware and software backends to work around an issue with Mario Kart Wii, Fortune Street, and Baten Kaitos. However, it seems like the software renderer handles blending well enough that we don't need this (and in any case, it's easy to change blending in the software renderer).
Some experimentation with #11387 (not pushed) showed that the software renderer's logic would also produce correct results on the hardware backends with this hack removed, but would require fbfetch (currently); if a better solution is found the hack can also be removed from the hardware backends.

Software: Remove alpha=1 blending special-case

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/MenuTag.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml

Back when this was just the FPS setting, having it in the top level of the graphics settings was reasonable. But now it's seven settings. Let's add a new submenu for them.

Android: Move FPS-related settings to a submenu

---

Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.cpp
Source/Core/Core/HW/WiimoteEmu/Extension/UDrawTablet.cpp

UDraw is confirmed working. Drawsome is untested, but probably working.

WiimoteEmu: Expose mappings for lifted UDraw and Drawsome stylus.

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitAsmCommon.h

Plus two miscellaneous debugger features that I found along the way when reading Jit64's code for comparison: bJITNoBlockLinking and tracing.
Fixes https://bugs.dolphin-emu.org/issues/13127.

JitArm64: Implement breakpoints

---

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp

Before:
After:
I have mixed feelings on this since it adds a second translatable string, although it looks like the same thing applies for combo boxes, not just input fields. It's still annoying that both need to be manually set, and I doubt they would ever have distinct translations beyond the colon.
The same thing already applies to PNG compression level (from #10143) for what it's worth.

AdvancedWidget: Add title for performance sample window tooltip

---

Source/Core/Core/PowerPC/MMU.cpp

`em_address + size` can overflow and become 0. It shouldn't happen with the kinds of memory mappings games use in practice, though.

PowerPC: Fix theoretically possible infinite loop in WriteToHardware

---

CODE_OF_CONDUCT.md

[Rendered](https://github.com/delroth/dolphin/blob/coc/CODE_OF_CONDUCT.md)
This stems from the current discussions around having an official Dolphin Discord. We're going to have more users and developers interacting over there than we've had before, and given the general state of gaming communities on the internet I'd like to make it clear what's acceptable and not acceptable for us. If we define clearer rules for Discord, I don't really see any reason why not apply them globally to anywhere humans interact for the project: GitHub, bug tracker, IRC, forums, etc.
This Code of Conduct is derived from https://asahilinux.org/code-of-conduct/ which itself has a long lineage in the open source community (used by Django and Ceph, two other major open source projects of comparable size to ours). …

Adopt a Code of Conduct for Dolphin.

---

Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h

On X11, mouse wheel inputs are almost impossible to produce since the ButtonPress and ButtonRelease events are sent simultaneously. I'd previously attempted to fix this by adding an input buffer (#8815) but that wasn't quite right, and doing a completely working implementation of that seems tricky. As an alternative, XInput2 does expose the scroll wheel as an axis (similar to on Windows), so this provides that as an axis (Axis Z), and from my testing seems to work fairly reliably.

InputCommon/XInput2: Added an axis output for the scroll wheel

---

Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm

Fix a bug I introduced back in #10979
Cocoa uses a different coordinate system from Carbon (Carbon's origin is the top left while Cocoa's is the bottom left)
Switches to methods that use Cocoa's coordinate system

InputCommon:QuartzKB&M: Fix mouse y coordinates

---

Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/ShaderGenCommon.cpp
Source/Core/VideoCommon/VideoConfig.h

Fixes https://forums.dolphin-emu.org/Thread-manual-texture-sampling-does-not-work-with-stereoscopic-3d.
Otherwise, `texelFetch()` will use an out-of-bounds layer for game textures (that have 1 layer; EFB copies have 2 layers in stereoscopic 3D mode), which is undefined behavior (often resulting in a black image). The fast texture sampling path uses `texture()`, which always clamps (see https://www.khronos.org/opengl/wiki/Array_Texture#Access_in_shaders), so it was unaffected by this difference.

PixelShaderGen: Clamp texture layer when using manual texture sampling with stereoscopic 3D

---

Source/Core/Core/DolphinAnalytics.cpp
Source/Core/VideoBackends/OGL/OGLRender.cpp

This PR adds the presence of fbfetch support to the analytics system. Based on #11387 it looks like fbfetch will be needed to accurately emulate blending behavior (impacting bloom in some games, as well as the menus in mario kart wii and a white box on fortune street, although we have a separate hack that fixes those), so it would be good to know how many users actually will have access to it.
This PR also checks for support of `GL_EXT_shader_framebuffer_fetch` on regular OpenGL, instead of just OpenGL ES. Intel GPUs support it. I think the only effects of this are that ubershaders will use fbfetch and the fbfetch fallback becomes available if logic ops or dual source blend aren't supported. (Side note: it looks like analytics also tracks dual source blend support, but doesn't track logic …

DolphinAnalytics: Track support of framebuffer fetch

---

Tools/lint.sh

The parameters used for the `stat` command are only valid when using GNU coreutils. On OSes that use BSD tools (for example, macOS), the command will fail and the script will exit.

lint: Don't check for WSL2 host path on non-Linux OSes

---

Source/Core/VideoCommon/IndexGenerator.cpp
Source/Core/VideoCommon/VertexManagerBase.cpp

Fixes Pocoyo Racing ([issue 13136](https://bugs.dolphin-emu.org/issues/13136)), and also log spam about "Too little remaining index values. Use 32-bit or reset them on flush." on Super Mario Sunshine's grass special stage and some smash custom levels ([issue 10312](https://bugs.dolphin-emu.org/issues/10312)).
The problem with Pocoyo Racing is that it uses 65535 (0xffff) vertices in a single draw command, which caused `GetRemainingIndices` to overflow, acting as if there was space for more vertices even though there wasn't. Then the game draws 3681 more vertices, and the indices corresponding to those vertices are all messed up because of the overflow, resulting in vertex explosions. The index generator actually can handle 0xffff indices for vertices with one more value reserved for …

IndexGenerator: Fix off-by-one in GetRemainingIndices

---

Externals/curl/curl.vcxproj

For some reason, when this is included, the linking step creates a temporary file in %TEMP% with a random name; the file is deleted afterwards and a new random name is used on a later build. Because this file doesn't exist on a later build, curl gets re-linked each time, and then all of the projects that depend on curl also get re-linked. This adds around 10 seconds to the build time even for small changes.
To make things worse, I don't think libcurl.rc does anything useful since we statically link curl; I believe the metadata contained in it only applies when building a dll. (It does seem to be included in curl.lib, but gets discarded when linking Dolphin.exe.)
See Build\x64\Release\curl\curl.tlog\Lib-link-cvtres.write.1.tlog for the log that shows this path (the file is also mentioned …

Externals: Exclude libcurl.rc from the build

---

Source/Core/DolphinLib.props
Source/Core/DolphinLib.x64.props

Before, it was also compiled on ARM builds, but since it was unused it wasn't linked (and thus its dependency on the nonexistent x64Emitter didn't cause any link issues).
https://github.com/dolphin-emu/dolphin/blob/7444f90e45928f15bcb7d6c4ccf98f06634062c5/Source/Core/Core/DSP/Jit/DSPEmitterBase.cpp#L14-L21

Move x64 DSP JIT into DolphinLib.x64.props

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/InsetsHelper.java
Source/Android/app/src/main/res/layout/activity_cheats.xml
Source/Android/app/src/main/res/layout/fragment_cheat_list.xml

When using a fullscreen mode on some phones that remove the navigation bar, inset callbacks will not be fired. To account for this we set the workaround view at a height of 1 to prevent the view from filling the entire screen due to this activity using a Constraint layout.

Android: Fix use of fullscreen modes on Cheats Activity

---

BuildMacOSUniversalBinary.py
CMakeLists.txt
Readme.md

This should be all that's required to make the Updater gracefully tell people on < 10.15 to update.
If we can go higher than 10.15, I'd love to know :)
This will unblock std::filesystem stuff

update min macos version to 10.15

---

Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Source/Core/Core/DolphinAnalytics.cpp
Source/Core/Core/DolphinAnalytics.h
Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/MMU.h
Source/Core/Core/PowerPC/PPCCache.cpp
Source/Core/Core/PowerPC/PPCCache.h
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/Core/PowerPC/PowerPC.h
Source/Core/Core/State.cpp
Source/Core/DolphinQt/Settings/AdvancedPane.cpp
Source/Core/DolphinQt/Settings/AdvancedPane.h

This adapts the instruction cache implementation used by the interpreter into a general purpose PPC cache, enabling the ability to emulate the data cache. Due to the very negative impact on performance, I made it an option in Config > Advanced that defaults to off. 
Enabling will make Dolphin compatible with [CTGP Revolution](https://chadsoft.co.uk/), as well as make older versions of CTGP (that normally work on Dolphin) more stable by properly emulating a mistake it relies on, where an instruction patch does not immediately apply due to [the data cache not being flushed](https://github.com/Chadderz121/wii-ct-code/blob/8aaf1a879d276b55c4eb2abdf916e2727e4dfa81/bad0/bad0Data/mod/mod0.mod#L30). In addition, fixes to the IABR and UPMC registers were made to allow CTGP to function properly. …

Implement PowerPC data cache

---

Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/HW/GPFifo.cpp
Source/Core/Core/HW/GPFifo.h
Source/Core/Core/HW/HW.cpp
Source/Core/Core/HW/Memmap.h
Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/System.cpp
Source/Core/Core/System.h

~~Do not merge this yet, this appears to noticeably impact performance...~~ e: On second try I'm actually getting slighty better performance post-refactor so what the heck do I know, modern CPUs are a mystery.
Someone should also check the ARM JIT change.

HW/GPFifo: Refactor to class, move to Core::System.

---

Source/Android/app/src/main/res/layout-land/activity_user_data.xml
Source/Android/app/src/main/res/layout-w680dp-land/activity_convert.xml
Source/Android/app/src/main/res/layout/activity_cheats.xml
Source/Android/app/src/main/res/layout/activity_convert.xml
Source/Android/app/src/main/res/layout/activity_main.xml
Source/Android/app/src/main/res/layout/activity_riivolution_boot.xml
Source/Android/app/src/main/res/layout/activity_settings.xml
Source/Android/app/src/main/res/layout/activity_user_data.xml
Source/Android/app/src/main/res/layout/list_item_header.xml

This disables focus on the workaround view and reverts and [old change](https://github.com/dolphin-emu/dolphin/commit/77e51ab5271f1d6db265feb1c41e1a14866d101c) that afaik isn't valid after testing on API 26 and 27.

Android: Disable focus on non-actionable UI

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml

It's a little inconvenient to pull the statistics out from SAF, but it's useful for Android benchmarking.

Android: Expose "Log Render Time to File" toggle

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/InsetsHelper.java

This partially reverts a change made in #11410 in hopes of fixing fullscreen modes on Samsung devices when using the cheats activity.

Android: Ignore workaround view height if 0

---

Source/Core/DolphinQt/Info.plist.in

https://developer.apple.com/documentation/bundleresources/information_property_list/lsapplicationcategorytype This makes it show up in the Launchpad Games folder

Set LSApplicationCategoryType to games

---

Source/Core/DolphinQt/CMakeLists.txt

The `RPATH` of the `.so` files in `plugins/platforms` expect there to be a `plugins` folder. It's easier to just copy the entire `plugins` folder instead of modifying the platform plugins.

CMakeLists: Copy entire plugins folder on Steam Runtime build

---

Source/Core/DolphinQt/TAS/GBATASInputWindow.cpp

This generated a warning on GCC about the operation being potentially undefined (-Wsequence-point). I'm not sure if that was actually the case, but either way it is a mistake.

DolphinQt: Fix typo in GBA TAS input window

---

Source/Core/AudioCommon/Mixer.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/CoreTiming.cpp
Source/Core/Core/CoreTiming.h
Source/Core/Core/HW/SystemTimers.cpp
Source/Core/VideoCommon/PerformanceMetrics.cpp
Source/Core/VideoCommon/PerformanceMetrics.h

- Throttles before every single event with `std::this_thread::sleep_until`
- If the sleep function over sleeps, then the next few calls to sleep will be skipped until it maintains timings again. So this whole system will remain relatively stable regardless of the way that sleep is implemented.
- This means that events schedules in the `CoreTimingManager` now happen the instant they are supposed to
- New Timings +/- 10µs (tested on macOS)
- Old Timings +/- 1000µs (on every operating system due to design)
This commit can turn these frame times (Wii Sports Resort):
Into these frame times (Wii Sports Resort - Immediate XMB ON): (just stunning)
Wii Sports Resort - Immediate XMB OFF: (notice that vblanks have an std of 0ms)
---
Here is with the metal frame time viewer:
Before:
After:

CoreTiming: Throttle Before Every Event Using std::chrono

---

Source/Android/app/src/main/res/layout/fragment_grid_options.xml

Previously on displays with a small width, text would appear under the switch. Now the text will break into a new line.

Android: Fix grid options text borders

---

CMakeLists.txt

The pkgconfig file for `minizip-ng` is [`minizip.pc.cmakein`](https://github.com/zlib-ng/minizip-ng/blob/master/minizip.pc.cmakein).

CMake: search for shared `minizip-ng` as `minizip`

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/Memmap.h

See the comment added by this pull request. We were previously guarding against overshooting in address calculations, but not against undershooting. Perhaps someone assumed that the displacement of an x86 loadstore was treated as unsigned?
Note: While the comment says we can undershoot by up to 2 GiB, in practice Jit64 as it currently behaves won't actually undershoot by more than 0x8000 if my analysis is correct. But address space is cheap, so let's guard the full 2 GiB.

Core: Allocate 2 GiB of guard pages below fastmem area

---

Source/Core/Core/CoreTiming.cpp
Source/Core/Core/CoreTiming.h

Fixes regression from #11348, where loading a save state from the past would cause issues.

Reset Throttle on savestate load

---

Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MainWindow.h
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/MenuBar.h

MenuBar: Add action which opens the user folder

---

Source/Core/UICommon/UICommon.cpp

This PR moves the user folder to `%appdata%\Dolphin Emulator` to minimize the chances that external software can interfere with Dolphin when accessing it (shoutouts to OneDrive and various anti-virus scanners).
Here is how the user directory is determined on Windows with my changes:
1. If the file `portable.txt` or the registry value `HKCU\Software\Dolphin Emulator\LocalUserConfig` exists, a folder named `User` next to the executable will be selected as the user directory.
2. If Dolphin finds a registry value in `HKCU\Software\Dolphin Emulator\UserConfigPath`, it will use that as the user directory. This functionality dates back to at least 4.0 stable.
3. **NEW**: If the old user directory at `%userprofile%\My Documents\Dolphin Emulator` exists, Dolphin will use that as the user …

UICommon: Change default user directory location to AppData on Windows

---

Source/Core/DolphinQt/MenuBar.cpp

Last minute change: "Open User Folder" -> "Open Global User Directory", since the latter is what we've used in the past.

MenuBar: Tweak string for open user folder option

---

Source/Android/app/src/main/res/layout/fragment_saveload_state.xml
Source/Android/app/src/main/res/values/styles.xml

Previously each button had its size hardcoded. Now the button will follow the size of the internal textview and avoid cutting off text.

Android: Fix large strings in save/load savestate fragment

---

Source/Core/DolphinQt/MenuBar.cpp

This reverts PR #11451.
The user folder can be either global or local. If it is local, we shouldn't call it global.
See also PR #10216.

Revert "MenuBar: Tweak string for open user folder option"

---

Source/Core/VideoCommon/VertexLoaderBase.cpp
Source/Core/VideoCommon/VertexLoader_Normal.cpp
Source/Core/VideoCommon/VertexLoader_Position.cpp
Source/UnitTests/CMakeLists.txt
Source/UnitTests/UnitTests.vcxproj
Source/UnitTests/UnitTestsMain.cpp

Fixes the generic nightly builder (see https://github.com/dolphin-emu/dolphin/pull/10808#issuecomment-1380187782).
I didn't catch this because I did my testing using `COMPARE_VERTEXLOADERS`, which did not check the various caches. The issue was the software vertexloader not writing to the tangent/binormal caches, but this was obscured since the JIT vertexloader _did_ load to them.
Additionally, `COMPARE_VERTEXLOADERS` wouldn't be visible in unit tests since logging wasn't enabled. I changed that to asserts, and also changed the test system to register a custom message alert handler (as otherwise the assertion popup would appear on the msvc buildbot and never close, forcing the 20-minute timeout, and on other platforms a failed dolphin assertion wouldn't be treated as a test failure).

VertexLoader: Fix loading tangent/binormal caches with NormalIndex3

---

Externals/implot/CMakeLists.txt
Externals/implot/implot.vcxproj

`implot_demo.cpp` depends on functions from `imgui_demo.cpp`, which we do not have. Appears to cause linking errors only on my fork, but I figured I would upstream this anyway.

implot: Don't compile `implot_demo.cpp`

---

Source/Core/Core/NetPlayClient.cpp

In the NetPlayClient::Connect function, a packet is sent to the host, and the next received packet is treated as the response. However, sometimes, a ping response from the traversal server will arrive in-between, which breaks everything. In certain high-latency situations, it may even occur every time. This PR simply ignores any packets from the traversal server during this interaction.

Netplay: Fix traversal connections occasionally not working

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Source/Core/Core/CoreTiming.cpp
Source/Core/Core/CoreTiming.h
Source/Core/Core/HW/VideoInterface.cpp
Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
Source/Core/DolphinQt/Config/Graphics/HacksWidget.h
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

This hack uses the improved pacing branch to look at the amount of time ahead / behind of the timings the emulation is. If the emulation is more that 40ms behind the timings (length of the audio buffer) then it will skip sending an VI to the CPU in order to prevent the game from requesting to draw a new frame. While this is "hacky," it is the most compatible way to induce a frame skip when GPU limited and is very non invasive compared to the old frame skip and automatically works with every video backend.
Here is an image to help visualize the timings:
This image is old so the only thing incorrect is the size of the buffer, which is now the same as TimingVariance, which is 40ms.
Heres a video of an old version. The audio is full speed but the video is not: …

VideoCommon: VI Skip

---

Data/Sys/GameSettings/GZ2.ini
Data/Sys/GameSettings/GZL.ini
Data/Sys/GameSettings/RZD.ini

These games do some funky VI stuff which causes VI Skip to be completely incompatible with them, so let's disable it.

Disable VI Skip in Wind Waker and Twilight Princess

---

Source/Core/DolphinQt/Settings/GeneralPane.cpp

We've decided this track will never be used in the future. Releases will continue using the "beta" branch internally, though we'll have the user-visible strings use a different name instead.
(Note: Dolphin provided builds have always defaulted to 'beta' as the auto-update track, so anyone who set 'stable' did so manually.)

DolphinQt/Settings: remove 'stable' track from auto-updater options

---

Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp

A few weeks ago, a vtuber tweeted that they had to remove a vod of their stream because Dolphin Emulator showed some personal information during the steam, and left a warning to everyone else that Dolphin shows the account name of the computer. And yea, we do, we show the full directory of the memory card every time a memory card is written, and due to mandatory Microsoft account nonsense, that is very likely to contain someone’s real name.
Fortunately this is very easy for us to solve. This change simply removes the filename from wrote memory card contents string. That’s it. All functionality of the wrote memory card OSD message remains the same, it just doesn’t say where the memory card is anymore. This also has the benefit of shrinking our wrote to memory card message so it's much less …

Remove Memory Card Path from the Wrote to OSD Message

---

Source/Core/Core/Core.cpp

It turns out all OSD messages, _every single one_, are written to the titlebar. We've just never seen them because the FPS/VPS etc display is in the title bar and it replaces it in a fraction of a second. This was only visible when saving savestates because it halts emulation for a moment while writing.
This is dumb, let's not do that anymore. Fixes [issue 12604](https://bugs.dolphin-emu.org/issues/12604).
Before -
After - 
There is still dox potential in the saving states from the OSD but that's for a separate PR.

Don't Write OSD Messages to the Titlebar

---

Source/Core/UICommon/DiscordPresence.cpp

not entirely sure discord should be compiled-time decision, but make it build at least.

buildfix if discord isn't enabled

---

.gitattributes

modifying sln via VS always uses clrf, so let's just go with it

gitattributes: set eol=clrf on *.sln

---

Source/Core/AudioCommon/WASAPIStream.cpp
Source/Core/Common/HRWrap.cpp

comdef generates a link requirement which can't be used on uwp/xbox

windows: replace comdef dependency with winrt

---

Source/Core/Common/ArmCPUDetect.cpp
Source/Core/Common/CMakeLists.txt
Source/Core/Common/WindowsRegistry.cpp
Source/Core/Common/WindowsRegistry.h
Source/Core/Core/DolphinAnalytics.cpp
Source/Core/DolphinLib.props
Source/Core/WinUpdater/Platform.cpp

this value is not modified by compatibility mode
drop reporting service pack numbers. no longer used
AFAIK ignoring the fact that dolphin or updater is running under compatibility mode should raise no problems for our use case.

windows: prefer os version from registry

---

Source/Core/DolphinQt/Main.cpp

See https://bugs.dolphin-emu.org/issues/12913 for more information.
I initially put this workaround in a launch script just for the Steam runtime, but now that I think about it, this bug affects *every* Linux build using Qt 6.3+. We should probably workaround this issue on those systems too.

DolphinQt: Add workaround for Qt 6.3+ bug on Linux

---

Source/Core/Common/FileSearch.cpp
Source/Core/Common/FileUtil.cpp
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/Boot/Boot.cpp
Source/Core/DiscIO/GameModDescriptor.cpp

just use std::filesystem
let's see if we can finally get rid of it...

get rid of HAS_STD_FILESYSTEM

---

CMakeLists.txt
Source/VSProps/Base.props

The only effective change is enabling [/Zc:enumTypes](https://learn.microsoft.com/en-us/cpp/build/reference/zc-enumtypes?view=msvc-170) (pls read)
This has the possibility to change binary representation of enums. However, Dolphin compiles and (seems to) run fine, so I don't see this introducing issues at the moment. IMO it only modifies behavior in weird edge cases, which probably aren't in use in the codebase, anyway.

msvc: update c++ conformance flags

---

Source/Android/app/src/main/res/menu/menu_game_grid.xml

Previously the string was "Settings" and not "Grid Options"

Android: Fix grid options menu string

---

Externals/MoltenVK/CMakeLists.txt

The changelog can be found [here](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.2).

Externals: Update MoltenVK to 1.2.2

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/layout/dialog_slider.xml
Source/Android/app/src/main/res/values/strings.xml

Additionally I changed the slider step size based on how large the total range is. This makes large ranges like the one used for this sample window much easier to control. Since we haven't had to control values greater than 100 before, I've also increased the size of the value text field.
Audio Slider -
Sample Window Slider -

Android: Add slider for Performance Sample Window

---

Source/Android/jni/AndroidCommon/AndroidCommon.cpp
Source/Core/Common/ArmCPUDetect.cpp
Source/Core/Common/Debug/CodeTrace.cpp
Source/Core/Common/FileUtil.cpp
Source/Core/Common/NandPaths.cpp
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/HW/EXI/BBA/XLINK_KAI_BBA.cpp
Source/Core/Core/HW/EXI/EXI_DeviceEthernet.cpp
Source/Core/Core/IOS/FS/HostBackend/FS.cpp
Source/Core/Core/PowerPC/PPCSymbolDB.cpp
Source/Core/Core/PowerPC/SignatureDB/SignatureDB.cpp
Source/Core/DiscIO/RiivolutionParser.cpp
Source/Core/DiscIO/RiivolutionPatcher.cpp
Source/Core/DiscIO/VolumeVerifier.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Settings/GameCubePane.cpp
Source/Core/InputCommon/ControllerInterface/Touch/ButtonManager.cpp
Source/UnitTests/Common/StringUtilTest.cpp

Obsoletes these functions in favor of the standard member functions added in C++20.

Common: Replace StringBeginsWith/StringEndsWith with std equivalents

---

Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/Core.h
Source/Core/Core/HW/VideoInterface.cpp

Why?
- There's already an FPS widget that the user can enable.
- I don't think constantly updating values such as the FPS count should be in the title bar. 
~~I can also further clean it up while I'm already touching this code. For example, I could remove the DSP section (which displays either HLE or LLE).~~
EDIT: This will be done separately in another PR in the future. I want to keep it simple.
Screenshots
Before:
After:

Core: Remove FPS, VPS and speed percentage from window title

---

Source/Core/Core/CoreTiming.h

Gives two members without explicit initialization default values to be consistent with the rest of the class and also ensuring deterministic values on construction.

CoreTiming: Zero initialize all CoreTimingManager throttle members

---

Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h

There's nothing really about this that would require constraining it to only std::string instances.

StringUtil: Make StringUTF8CodePointCount take string_view

---

Source/Core/Common/BitSet.h

This was able to be constexpr since C++14.
Consistency change and may now allow initializer_list overloads to be resolved at compile-time (assuming compilers weren't smart enough to do that anyway without the constexpr specifier)

Common/BitSet: Mark initializer_list constructor as constexpr

---

Source/Core/Core/State.cpp

Though less important compared to #11470, save states also show the full path in the OSD message and could potentially dox a streamer who is playing a game in Dolphin. This is a simple fix - it removes the path from the OSD message so only the name of the state file is revealed.
Also makes the state messages less intrusive.
Before -
After -

Remove Filepath from State Save/Load OSD Messages

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/DolphinLib.props
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h
Source/Core/VideoCommon/CMakeLists.txt
Source/Core/VideoCommon/CPUCull.cpp
Source/Core/VideoCommon/CPUCull.h
Source/Core/VideoCommon/CPUCullImpl.h
Source/Core/VideoCommon/ConstantManager.h
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VertexManagerBase.h
Source/Core/VideoCommon/VertexShaderManager.cpp
Source/Core/VideoCommon/VertexShaderManager.h
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h
Source/Core/VideoCommon/XFMemory.h

Twilight Princess and Metroid Prime 3 seem to like alternating between lines/points and degenerate triangles (working around some hardware bug?).  Since each switch requires a change in draw configuration, this puts a lot of strain on the render backend, as it encodes ~27k draw calls per frame in the case of Twilight Princess.
To avoid this, pre-run the coordinate transform part of the vertex shader on the CPU and cull triangles there, skipping the draw entirely if all its vertices would get culled by the GPU.  Nearly halves the number of draw calls in Twilight Princess, bringing it down to just 15k, bringing its frame rate from ~22fps to ~32fps on my laptop, a nearly 50% improvement!
This also seems to help Densha De Go, giving a ~15% improvement.  Not sure what it's drawing, but …

Cull vertices on the CPU

---

Source/Core/Core/HW/DSPLLE/DSPHost.cpp
Source/DSPTool/DSPTool.cpp

This caused me a lot of trouble, as DSPSpy was breaking when compiled with `-O0`. It ended up being the case that `dsp_code` was placed at `0x800ba400` at `-O2`, `0x800ba320` at `-O1`, and `0x800bb3ee` at `-O0`.  I don't know if the alignment at `-O1` and higher was just a coincidence or not.
The symptom of misaligned code was either no mail at all from the DSP (instead showing the DSP ROM's `0x8071feed` mail) or the appearance of an exception occuring (instead showing dspspy exception handler's `0x8bad0001` mail). I also sometimes got hangs. My guess is that it just rounded the address up or down, but I'm not 100% sure of this and don't want to investigate it currently since I'm busy investigating edge cases that things actually rely on (somewhat). This behavior can be investigated …

DSPLLE: Add assertion for bad DMA alignment

---

Source/Core/Core/HW/DSPLLE/DSPHost.cpp

This reverts commit e140516130f18b118f5b258d366379af72cefc70. This assert triggers for AX and AXWii uCode games (including the Wii System Menu) for various addresses that seem to be 4-byte aligned. Worse still, if the DSP thread is in use (i.e. for DSP LLE recompiler, but not for DSP LLE interpreter), Dolphin completely hangs after the panic alert. Perhaps the data DMA has fewer restrictions compared to the instruction DMA?
The change to DSPTool (e391a281024a8f8283160b03aa3703405e037ed7) has not been reverted, as it still fixes broken behavior for DSPSpy at -O0 on real hardware.

Revert "DSPLLE: Add assertion for bad DMA alignment"

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/DateTimeChoiceSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SettingsItem.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/DateTimeSettingViewHolder.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SettingViewHolder.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SwitchSettingViewHolder.java
Source/Android/app/src/main/res/values/arrays.xml
Source/Android/app/src/main/res/values/strings.xml

These were all oddly not available in the Android app. Now they are.
- IPL Skip Main Menu
- Accurate CPU Cache
- Frame Dump Compression Level
- Force Linear/Nearest filtering options
- Emulated Memory Size Override
- Custom RTC
- A few headers that should've been there
I'm also really happy with the work I put into the RTC selector so here's a demo.

Android: Reveal several hidden settings

---

Data/Sys/GameSettings/G2M.ini
Data/Sys/GameSettings/GM8.ini
Data/Sys/GameSettings/GZ2.ini
Data/Sys/GameSettings/R3M.ini
Data/Sys/GameSettings/RM3.ini
Data/Sys/GameSettings/RZD.ini

These games greatly benefit from CPU Culling, and there isn't much reason not to just blanket enable it for all users.  There is no case where you'd want it disabled.

Add CPU Cull to Twilight Princess and Metroid Prime Series

---

Source/Core/VideoBackends/Metal/MTLObjectCache.mm
Source/Core/VideoCommon/PostProcessing.cpp
Source/Core/VideoCommon/RenderBase.cpp

Fixes nogui on Intel HD 4000 macs

VideoCommon: Avoid creating pipelines with no render targets

---

Source/Core/Core/HW/SystemTimers.cpp
Source/Core/VideoCommon/PerformanceMetrics.cpp
Source/Core/VideoCommon/PerformanceMetrics.h

This makes the speed % more useful, along with reducing the differences between the MAX Speed sample window and the normal speed sample window.

Tie Speed to CPU Speed and not VPS

---

Data/Sys/Load/GraphicMods/Metroid Prime 3 - Corruption/metadata.json

3x IR, mods disabled:
3x IR, native resolution bloom:
3x IR, bloom disabled:
Only tested with the standalone version of Metroid Prime 3; this may or may not work for Trilogy.

Add bloom definitions for Metroid Prime 3

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/VideoBackends/Metal/MTLRenderer.mm
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

I added the presentDrawable option in #11028 and it looks like it improves frame pacing on 60hz displays, so default it on when vsync is on, since it looks like we disable vsync during fast forward
@dvessel could you test and see if it works without the special config option now?  (You'll still need to force 59.94hz)
And then make sure fast forward still works
Note: This means users of <60hz displays will have to set `MTLUsePresentDrawable=0` in their configs.  Hopefully most people have ≥60hz displays.

VideoBackends:Metal: Default to presentDrawable when vsync is on

---

Source/Core/AudioCommon/CMakeLists.txt
Source/Core/AudioCommon/OpenSLESStream.cpp
Source/Core/AudioCommon/OpenSLESStream.h

OpenSLES code is only compiled on android, but instead of checking via CMake we search for OpenSLES on all platforms, and then compile that code if we find it. Just in case a non-android build finds OpenSLES, both of the files are wrapped in #ifdefs. Instead, this PR will only search for and compile the files on Android, thus not generating a false warning that OpenSLES was not found on regular builds.

Restrict OpenSLES to Android via CMake

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java

The step size for the slider ended up being 10, but Android wanted it to be a divisor of the slider's range (which is 128 - 64 = 64).

Android: Fix crash when attempting to change MEM2 size

---

Source/UnitTests/CMakeLists.txt

This properly adds the header include paths when using system fmt

CMake: Use imported target for fmt in tests

---

Source/Core/Core/Movie.cpp

The movie config layer is not active for recording, only playback. Thus, recording ends up stuck with default SYSCONF settings.
The fix somewhat hacky, but seems to work.
This fixes https://bugs.dolphin-emu.org/issues/12822

Fix SYSCONF movie settings

---

Source/Core/VideoBackends/Vulkan/VKTexture.cpp

Usually most textures have one layer so this doesn't matter but it does in #11300

VideoBackends: update Vulkan's 'CopyRectangleFromTexture' to copy one layer

---

Source/Core/VideoBackends/Vulkan/VulkanLoader.h

These cause a lot of warnings when compiling with clang. 
And the [example VmaUsage.h](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/VmaUsage.h#L94) appears to disable them

Ignore nullability-completeness warnings in VMA

---

Source/Core/Core/ActionReplay.cpp
Source/Core/Core/ActionReplay.h
Source/Core/Core/GeckoCode.cpp
Source/Core/Core/GeckoCode.h

Some functions in these interfaces just require a range of GeckoCodes and don't depend on the container type, so we can make these a little more flexible by using spans

ActionReplay/GeckoCode: Make use of std::span where applicable

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FloatSliderSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/IntSliderSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/PercentSliderSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SliderSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java

This reverts part of #11413 where we tried to calculate the appropriate slider step size based on the given range. This turned out to be inappropriate because there can be settings like Emulated CPU Clock Speed % that go up to 400%. Users would like to have the ability to change that by a step size of 1. Seeing as we could get caught in a cycle of constantly adjusting section of a slider that can be stepped by 1, changing the step for each slider individually seemed like a better solution.

Android: Set each slider step size manually

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java

I made a false assumption about this older boolean force filtering setting being used. It is no longer referenced in dolphin and has been removed for that reason.

Android: Remove unused force filtering setting

---

Source/Android/jni/AndroidCommon/AndroidCommon.cpp
Source/Android/jni/AndroidCommon/AndroidCommon.h

Several of these can take a string_view rather than needing to specifically use std::string.

AndroidCommon: Make use of std::string_view where applicable

---

Source/Core/Common/Network.cpp

Macros that expand to include the standard `defined` macro are undefined. This is pretty trivial to fix. We can just do the test and then define the name itself if it's true, rather than making the set of definition checks the macro itself.

Common/Network: Resolve -Wexpansion-to-defined warning

---

Source/Core/Core/IOS/USB/Emulated/Skylander.cpp
Source/Core/DolphinQt/SkylanderPortal/SkylanderPortalWindow.cpp

The real Skylanders cards are Mifare 1K classic cards with a 4-byte NUID so this mimics the real cards. The calculation used before could cause duplicate NUIDs very easily.
Added an icon to the Skylanders portal window

Improve the data in the first data block of the skylanders figures

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AbstractBooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AbstractFloatSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AbstractIntSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AbstractLegacySetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AbstractSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AbstractStringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AdHocBooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AdHocStringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/FloatSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/LegacyFloatSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/LegacyStringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/ScaledIntSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/WiimoteProfileBooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/WiimoteProfileStringSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/DateTimeChoiceSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java

A little refactoring to cut down on the size of the very big SettingsFragmentPresenter class.
I ended up adding a bunch of @NonNull annotations in various settings classes so I could make the parameters `Settings` instead of `Settings?` in the new Kotlin code.

Android: Create ScaledIntSetting class

---

Source/Core/Core/IOS/Network/KD/NetKDTime.cpp

_From PR #11431_
Related to [issue 9754](https://dolp.in/i9754).
Since GetEmulatedTime returns a timestamp based off the computer's timezone, it needs to be changed to UTC here. 
This allows for the News Channel to produce the correct "Last Updated" time.
This code is based off from a function in [Core/Movie.cpp](https://github.com/dolphin-emu/dolphin/blob/2ad92776c61cf126e933ca4c5c7c6237a310e193/Source/Core/Core/Movie.cpp#L204), which uses the same method.
By using a NAND dump with the latest news data, the "last updated" time is accurate to the console's results.

NetKDTime: Use UTC based timestamp instead of localtime.

---

Source/Core/VideoBackends/D3D/DXTexture.cpp
Source/Core/VideoBackends/D3D/DXTexture.h
Source/Core/VideoBackends/D3D12/DX12Texture.cpp
Source/Core/VideoBackends/D3D12/DX12Texture.h
Source/Core/VideoBackends/Metal/MTLTexture.h
Source/Core/VideoBackends/Metal/MTLTexture.mm
Source/Core/VideoBackends/Null/NullTexture.cpp
Source/Core/VideoBackends/Null/NullTexture.h
Source/Core/VideoBackends/OGL/OGLTexture.cpp
Source/Core/VideoBackends/OGL/OGLTexture.h
Source/Core/VideoBackends/Software/SWTexture.cpp
Source/Core/VideoBackends/Software/SWTexture.h
Source/Core/VideoBackends/Vulkan/VKTexture.cpp
Source/Core/VideoBackends/Vulkan/VKTexture.h
Source/Core/VideoCommon/AbstractTexture.h

Dolphin only loads to layer 0, but there may be cases where we want to load into other layers, like #11300

VideoBackends: add a way to load data into a specific level AND layer

---

Source/Core/DolphinQt/Config/GraphicsModListWidget.cpp
Source/Core/DolphinQt/Config/GraphicsModListWidget.h

Supersedes #11405.
Adds an easier way to navigate to the graphics mod folder rather than manually sorting through possibly long and winding file structures. ("Abrir directorio"= Open Folder in Spanish).

DolphinQt: Add button to open graphics mod folder on settings

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SwitchSettingViewHolder.java

Seems like I accidentally deleted this in #11460 when preparing the guards around the IPL setting. Now this makes sure we don't have problems on recycle and can no longer change settings when marked as not editable during runtime.

Android: Fix settings being editable when marked otherwise

---

Source/Android/app/build.gradle

This was initially opened as a proposal to fix the Android builders (which was found to actually be a problem with how the container image was created), but I'll leave this open in case not requiring a specific CMake version is something we want to do.

Android: Don't enforce a particular CMake version

---

Tools/lint.sh

Starting with grep 3.8, egrep throws the following warning
egrep: warning: egrep is obsolescent; using grep -E
Whch is annoying... so we will use grep -E

lint: replace egrep with grep -E

---

Source/Core/Core/CoreTiming.cpp

It's kinda complicated to explain why I would want to do this but here it goes.
It does not actually matter where the VI Skip Activation is, all that matters is that:
1. It's not too close to 0 [on time] because that causes unnecessary sleeping
2. It's not too close to -100ms, because that causes slow down
3. It's shorter than the audio buffer (prevents skips when going from >100% to <100%)
The current VI Deadline is exactly the length of the audio buffer which CAN cause stutters when VI Skip begins to activate. This should get rid of that stutter.

Set VI Skip Activation to Half The Audio Buffer

---

Data/Sys/Shaders/sharp_bilinear.glsl

Attempt at porting [this shader](https://github.com/libretro/slang-shaders/blob/master/interpolation/shaders/sharp-bilinear.slang) to Dolphin, for those who prefer a more pixel-y look. Honestly it looks pretty bad to me for 3D games, but ymmv.
I'm not sure this algorithm is completely correct; I attempted to do the equivalent with ImageMagick like this:
```
magick RSBP01_2021-07-04_01-56-21.png -scale 1920x1704! native_scaled_point.png
magick native_scaled_point.png -filter triangle -resize 1920x1096! native_scaled_final.png
```
and the resulting image is slightly different. So... not sure. I'll need to experiment a bit more so I actually understand how this code works, I think.
For reference:
[Native resolution screenshot](https://user-images.githubusercontent.com/4522237/124371142-360226 …

Add sharp bilinear postprocessing shader.

---

Data/Sys/Shaders/integer_scaling.glsl

Feature request:  https://bugs.dolphin-emu.org/issues/12725
Integer Scaling scales based on xfb * IR and adds black bars on all sides if needed.
There is probably a way to have the shader downscale/upscale so it isn't locked, but I couldn't get it right and I think shader options are broken.

Post-processing: Add integer scaling shader

---

Source/Core/Common/CommonPaths.h
Source/Core/UICommon/UICommon.cpp

Having a Steam-specific user directory will allow us to enable Steam Cloud, so that users can have their save files synchronized across machines. The paths are as follows:
* Windows: `%appdata%\Dolphin Emulator (Steam)`
* macOS: `~/Library/Application Support/Dolphin (Steam)`
* Linux: `~/.config/dolphin-emu-steam`, `~/.local/share/dolphin-emu-steam`, and `~/.cache/dolphin-emu-steam`
In addition, the user directory logic has been simplified for Windows builds on Steam. Basically, the registry keys and the old user directory are ignored. (We cannot check the user directory registry key because it is set to the non-Steam path on newer installs.)
While I was here, I also took the opportunity to clean up `CommonPaths.h`, since the names used for the defines were a bit outdated.

CommonPaths: Add Steam-specific user directory and clean up

---

Source/Core/VideoBackends/OGL/OGLGfx.cpp

Fixes a regression from PR #11522 ("Kill Renderer").

OGL: Fix GLES crashing on initialization

---

Source/Core/VideoBackends/D3D/DXPipeline.cpp
Source/Core/VideoBackends/D3D/DXPipeline.h
Source/Core/VideoBackends/D3D12/DX12Pipeline.cpp
Source/Core/VideoBackends/D3D12/DX12Pipeline.h
Source/Core/VideoBackends/Metal/MTLObjectCache.mm
Source/Core/VideoBackends/Metal/MTLPipeline.h
Source/Core/VideoBackends/Metal/MTLPipeline.mm
Source/Core/VideoBackends/OGL/OGLPipeline.cpp
Source/Core/VideoBackends/OGL/OGLPipeline.h
Source/Core/VideoBackends/Vulkan/VKPipeline.cpp
Source/Core/VideoBackends/Vulkan/VKPipeline.h
Source/Core/VideoCommon/AbstractPipeline.h

This allows us to re-create the pipeline easily (with tweaked changes).  used in #11300

VideoCommon: store the configuration used to create the AbstractPipeline

---

Source/Core/VideoCommon/TextureCacheBase.h

It was used for `valid_bind_points`, which was removed in 88bd10cd30d487cc3efba20875b32df7cdacb686 (and the declaration was more recently removed in 606c18210dd4f651655b2c84e9e332e6c6c6e21b).

TextureCacheBase: Remove unused bitset include

---

Source/Core/Common/ENetUtil.cpp

I got a crash report on Discord yesterday that I traced back to here.
Unfortunately this isn't a real fix, more like a bandaid. I'm guessing what actually happens is that `m_server` in `NetPlayClient` becomes null through a disconnect but something is still trying to send stuff afterwards, but the stack in the crashdump I have looks borked so I'm not actually sure.

ENetUtil: Add check for valid socket in SendPacket().

---

Source/Android/app/src/main/res/values/strings.xml
Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp

The fact that VI Skip used "VI" made it very difficult to explain on the blog. There are SO many things called VI already! This small changes clarifies what VI Skip is to resolve that issue, and makes it not use the "VI" anymore so it no longer conflicts with the other VI things.
I only changed the Qt and Android GUIs, not the INI or internal options. Since there was already some consensus in favour of this on discord and samb gave it a +1, the goal is to get this merged fast so we can get it into the report and publish. And not break anything.
I'll need someone else to test on Android, but here is the change on Linux.

Rename VI Skip to VBI Skip

---

Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionFactory.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionFactory.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp

Used in #11300 and #10362 to load additional files next to the config files.

VideoCommon: allow graphics mods to have access to the file path where the config exists to load additional files

---

.tx/config

Transifex's old CLI client was deprecated in November 2022. This updates our config so it can be used with the new client.
I don't need this merged immediately, but I will need it merged within two weeks or so for the next round of translation syncing.

Update Transifex config for new client

---

Data/Sys/GameSettings/GIC.ini
Data/Sys/GameSettings/GIQ.ini
Data/Sys/GameSettings/GU2.ini
Data/Sys/GameSettings/GU3.ini
Data/Sys/GameSettings/GU4.ini

This PR provides a small batch of GameINI updates:
- **The Incredibles**: Removes EFBToTextureEnable = False because there is no noticeable difference with this option enabled/disabled after testing several times, seems like it might have been added by mistake?
- **2-in-1 compilations**: Updated game settings to match the single-game releases and fixed an incorrectly named game entry (GU3.ini).

GameINI: Heavy Iron updates

---

Source/Core/DiscIO/FileBlob.h

Randomly noticed this. I think this is just wrong, if harmless.

DiscIO/FileBlob: Make m_size unsigned.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Source/Android/app/src/main/res/values/strings.xml
Source/Core/DolphinQt/Config/GameConfigEdit.cpp
Source/Core/DolphinQt/Config/GameConfigWidget.cpp

Following a suggestion from @mbc07, this renames the "Speed up Disc Transfer Rate" option to "Emulate Disc Speed" and inverts the setting. Since we have no guarantee as to whether or not the improved version of instant reads will ever be created, this allows us to keep the current implementation in a way that will hopefully reduce encourage reckless user behavior.
Additionally, this PR exposes the option in the Android GUI.

Rename "Speed up Disc Transfer Rate" to "Emulate Disc Speed"

---

Source/Core/Core/HLE/HLE.cpp
Source/Core/Core/HLE/HLE.h
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp

This got broken in 7cecb28bdf6443362a6ab20e0042ddb3b407ebec.
Fixes Gecko codes, probably among other things.

JIT: Fix calls to HLE::Execute.

---

Source/Core/Common/FileUtil.cpp
Source/Core/Common/FileUtil.h

replaces most stuff
incorporates #10955 
needs #10994 to be merged first for platforms that didn't previously use std::filesystem to compile

fileutil: use std::filesystem

---

Source/Core/Core/PowerPC/PPCCache.cpp

The previous code only updated the PLRU on cache misses, which made it so that the least recently inserted cache block was evicted, instead of the least recently used/hit one.
This regressed in 9d39647f9e3be1bdc2ee2cfc5ce6af2e560b4cc1 (part of #11183, but it was fine in e97d3804373b31724d0f092d8132e5ba23dec4a5), although beforehand it was only implemented for the instruction cache, and the instruction cache hit extremely infrequently when the JIT or cached interpreter is in use, which generally keeps it from behaving correctly (the pure interpreter behaves correctly with it).
I'm not aware of any games that are affected by this, though I did not do extensive testing.

PPCCache: Update PLRU on any cache access

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/Memmap.h
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp

Previously we would only backpatch overflowed address calculations if the overflow was 0x1000 or less. Now we can handle the full 2 GiB of overflow in both directions.
I'm also making equivalent changes to JitArm64's code. This isn't because it needs it – JitArm64 address calculations should never overflow – but because I wanted to get rid of the 0x100001000 inherited from Jit64 that makes even less sense for JitArm64 than for Jit64.

Jit64: Properly handle backpatching overflowed address calculations

---

Source/Core/Common/HookableEvent.h

A registration might happen during static initialization, which opens us up to issues with ordering of static initialization.

HookableEvent: Switch to construct on first use

---

Source/Core/VideoCommon/RenderState.cpp

This works around an Intel driver bug where, on D3D12 only, dual-source blending behaves incorrectly if the second source is unused on. This bug is visible in skyboxes in Super Mario Sunshine, which first draw clouds and sun flare in greyscale and then draw the sky afterwards with a source factor of 1 and a dest factor of 1-src_color (this results in the clouds being tinted blue). This process is done on an RGB888 framebuffer, so alpha update is disabled. (Color update is enabled; note that if you look at this in Dolphin's fifo analyzer, it won't be enabled because they use the BP mask functionality to only change the blending functions and not alpha/color update.)
Here are some examples of how this renders ([SMSSkyFifologs.zip](https://github.com/dolphin-emu/dolphin/files/10349115/SMSSkyF …

VideoCommon: Clear blend configuration if color/alpha update disabled

---

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp

This fixes a few mistakes that @Pokechu22 spotted in PR #11554.

Follow-up fixes for "Properly lock CPU before accessing emulated memory"

---

Source/Core/VideoBackends/OGL/OGLConfig.cpp
Source/Core/VideoCommon/GeometryShaderGen.cpp
Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/ShaderGenCommon.cpp
Source/Core/VideoCommon/ShaderGenCommon.h
Source/Core/VideoCommon/UberShaderPixel.cpp
Source/Core/VideoCommon/VideoConfig.h

`gl_Layer` isn't accessible from fragment shaders until OpenGL 4.3, so pass it separately
Is this worth adding a feature flag or should we just do it for all OpenGL?

VideoCommon: Fix stereoscopic 3D on OpenGL < 4.3 (macOS)

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

This fixes a regression from 592ba31. When `a` was a constant 0 and `b` was a non-constant 0x80000000, the 32-bit negation operation would overflow, causing an incorrect result. The sign extension needs to happen before the negation to avoid overflow.
Note that I can't merge the SXTW and NEG into one instruction. NEG is an alias for SUB with the first operand being set to ZR, but "SUB (extended register)" treats register 31 as SP instead of ZR.
I've also changed the order for the case where `a` is a constant 0xFFFFFFFF. I don't think the order actually affects correctness here, but let's use the same order for all the cases since it makes the code easier to reason about.

JitArm64: Fix special cases of cmp

---

Source/Core/Common/FileUtil.cpp
Source/Core/Common/FileUtil.h
Source/UnitTests/Common/FileUtilTest.cpp

This was accidentally changed in 7e6436db347c3cc479d768180de158a0f9c88226.
Compare the old code:
https://github.com/dolphin-emu/dolphin/blob/9d139ea84e426a0829fcb7c8bd1959f341427349/Source/Core/Common/FileUtil.cpp#L252-L287
to the new code:
https://github.com/dolphin-emu/dolphin/blob/8f91cb62e67109bda98d373474e4c4495b8f9f65/Source/Core/Common/FileUtil.cpp#L213-L226
Specifically the part where the old code returns as soon as it doesn't find any more directory separators.

Common/FileUtil: Revert behavior of CreateFullPath().

---

Externals/FreeSurround/source/FreeSurroundDecoder.cpp
Externals/FreeSurround/source/KissFFTR.cpp

Doing so is not allowed (presumably because compilers are allowed to use a different algorithm for allocating between the two/store extra data such as the length of the array before the pointer).
This bug existed in the original implementation at https://web.archive.org/web/20140708092159/http://www.hydrogenaud.io/forums/index.php?showtopic=52235 and causes Valgrind to emit a warning. Note that this ended up happening even if DSPLLE and the DPL decoder are not enabled in Dolphin.
<details><summary>Here's the warning in question:</summary>
```
==115== Thread 12 Emuthread - Sta:
==115== Mismatched free() / delete / delete []
==115==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==115==    by 0xBBA07B: …
```

Externals/FreeSurround: Fix pointer created through new[] being freed via delete

---

Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp

WriteExternalExceptionExit() can write more than the maximum offset of the small jump.
Fixes this issue in Resident Evil Archives (the REmake port for the Wii):
https://cdn.discordapp.com/attachments/521711075721478145/1075605414311374929/image.png

Jit64: Use 5 byte jump in mtmsr for the CP interrupt check.

---

Source/Core/DolphinQt/ConvertDialog.cpp

Before these changes you could tell Dolphin to convert a game file into the same format it is already in, leading to the FileDialog using the input path as the default destination path
An unsuspecting user could then click Save and Dolphin would try to convert the input file by writing the destination file on top of it... leading to an I/O error and the input file being entirely removed
Instead of denying the user the ability to select the format already used by the input file (which would be annoying if someone wants to convert from RVZ to RVZ but with other compression settings), we can check if the input and destination paths are equal and error out before having the input file accidentally removed

Check the input and destination paths before converting a game file onto itself

---

Source/Core/DolphinQt/Settings/AudioPane.cpp

This resulted in the labels being solid black even when audio stretching is disabled the first time the settings are opened, but then properly being greyed out after changing a setting (even the audio backend or DSP emulation engine, not just whether audio stretching is enabled).
<details><summary>Old:</summary>
</details><details><summary>New:</summary>
</details>
See the code in `SaveSettings`:
https://github.com/dolphin-emu/dolphin/blob/74abf482347e3073d2115a10ff72019567d03f3c/Source/Core/DolphinQt/Settings/AudioPane.cpp#L314-L321

AudioPane: Fix inconsistent initial state of audio stretching labels

---

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/InputCommon/ControlReference/ExpressionParser.cpp

I fixed a few memory leaks I found with valgrind. Note that I tested on Dolphin running in WSL, which is a very jank setup. There are still a few errors reported, but I'm guessing they're related to the setup instead.
<details><summary>New valgrind output</summary>
```
$ valgrind --leak-check=full --track-origins=yes --show-leak-kinds=definite,indirect,possible Binaries/dolphin-emu
==27794== Memcheck, a memory error detector
==27794== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==27794== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==27794== Command: Binaries/dolphin-emu
==27794==
==27794== error calling PR_SET_PTRACER, vgdb might block
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pokechu22'
==27807== Warning: invalid file …
```

Fix various memory leaks
