dolphin-emu/dolphin

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/GridOptionDialogFragment.kt
Source/Android/app/src/main/res/layout/fragment_grid_options.xml
Source/Android/app/src/main/res/layout/fragment_grid_options_tv.xml

This makes the bottom sheet dialog fragments more consistent and solves a bug where the view inside the bottom sheet could move independently from the background.

Android: Simplify the grid options dialog fragment

---

Source/Core/UICommon/UICommon.cpp

This PR migrates `SetUserDirectory` to use Windows Implementation Libraries, as specified by now implemented TODOs.

Address WIL todos in UICommon.cpp

---

Source/Core/Core/IOS/ES/TitleManagement.cpp

This broke formatting the system memory; see https://bugs.dolphin-emu.org/issues/13176. After calling `ticket.DeleteTicket()`, `ticket.m_bytes` was 0-length, but calling `ticket.IsV1Ticket()` still attempted to read from m_bytes.
This was introduced in 2fd9852ca89e4f07f6231ec3ddab5656f2b7856c (#11240), although it didn't actually cause a crash until 929fba08e733ceb02e51cbeb684a50103865e2da (#11383).
I'm not 100% sure if deleting a V1 ticket requires special logic (probably not), or if the process of deleting a V1 ticket could convert it into a V0 ticket somehow (I added an assertion for this). @noahpistilli may know more.

IOS/ES: Fix crash when deleting tickets

---

Source/Core/Common/FileUtil.cpp
Source/Core/Common/FileUtil.h
Source/Core/Core/IOS/FS/HostBackend/FS.cpp
Source/Core/Core/Movie.cpp
Source/Core/Core/WiiRoot.cpp
Source/Core/UpdaterCommon/UpdaterCommon.cpp

It can only copy files, not directories, so make that clear in the name. (also so I can free up the name for a generic copy-any function)
I originally wanted to name this just `CopyFile()` but then realized that Windows.h has a `#define` for that, so that'd be probably more trouble than it's worth. If you have a better name suggestion feel free.

Common/FileUtil: Rename Copy() to CopyRegularFile().

---

CMake/FindLIBMGBA.cmake

Includes use `mgba/` and `mgba-util/` as part of path, making compilation fail when relying on include directory supplied here was actually needed.
Discovered by having both mGBA and dolphin installed in `~/.local`. Confirmed to fix the issue.

Fix build when using mGBA in unorthodox location

---

Source/Core/Common/Random.cpp
Source/Core/Common/Random.h
Source/UnitTests/Core/PowerPC/JitArm64/MovI2R.cpp

decreases runtime significantly and lessens dependency on mbedtls
move to same construct used by https://github.com/dolphin-emu/dolphin/blob/master/Source/UnitTests/Common/FloatUtilsTest.cpp
the longest-running tests on my device (release build, surface pro x, SQ1):
before
```
6.199 MovI2R_32BitValues
5.756 MovI2R_Rand
1.084 MultiThreaded
0.505 LargeFloatVertexSpeed
0.469 CrashMacro
0.271 MultiThreaded
0.182 SignAndVerify
0.162 TexCoordSingleElement/0
0.161 TexCoordSingleElement/2
0.159 TexCoordSingleElement/1
```
after
```
1.568 MultiThreaded
1.564 MovI2R_32BitValues
0.878 MovI2R_Rand
0.528 CrashMacro
0.488 LargeFloatVertexSpeed
0.297 MultiThreaded
0.184 SignAndVerify
0.182 TexCoordSingleElement/2
0.178 TexCoordSingleElement/3
0.177 TexCoordSingleElement/0
```

use std-provided randomness for JitArm64 unittests

---

Source/Core/VideoBackends/D3D/D3DState.cpp
Source/Core/VideoBackends/D3D/D3DState.h

Built on top of #11550 , used by a future feature.

VideoBackends: use a bitset for D3D11's state management

---

Source/Core/VideoCommon/ShaderGenCommon.cpp

The HLSL compiler incorrectly decides isnan can't be true, so this workaround was originally added in 5.0-15109 but was dropped during the conversion to SPIR-V in 5.0-16815. I've readded it and converted it to glsl.
This bug rebroke shadow-eyes.dff on Direct3D 11 and 12 and gave console warnings during shader compilation.

D3D: Restore workaround for erroneous NaN optimization

---

Source/Core/DolphinQt/GameList/GameListModel.cpp

See https://bugs.dolphin-emu.org/issues/12931

Qt/GameList: Also filter by filename when searching.

---

Source/Core/Common/FileUtil.cpp
Source/Core/Common/FileUtil.h
Source/Core/Core/IOS/WFS/WFSI.cpp
Source/Core/Core/WiiRoot.cpp
Source/Core/UICommon/AutoUpdate.cpp

Cleaning up some of the nonsense. @shuffle2 please check this. I moved the `equivalent()` check into the error case of `Copy()` because [std::filesystem::copy() is defined to fail instead of destroying files in this situation](https://en.cppreference.com/w/cpp/filesystem/copy) and it's pretty unlikely in the first place.
There's one behavior of `Copy()` that I don't quite like, which is that if the source is a file and the destination is a folder it copies the file into the folder instead of either failing or overwriting the folder, it kinda feels like a situation that could surprise. But that's just what std::filesystem::copy() does, so it's probably okay to keep as-is...?

Common/FileUtil: Migrate CopyDir() to a more clear interface.

---

Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp

I also changed LoadConfig, but that change doesn't affect correctness, it's only so it looks neat by matching SaveConfig.
This bug was added in PR #8729, the PR that introduced DefaultValue::Disabled. The bug can't actually be triggered in master, but it can be triggered in PR #11385.

InputCommon: Fix ControlGroup::SaveConfig with DefaultValue::Disabled

---

Source/Core/UICommon/UICommon.cpp

If the Load/DynamicInputTextures directory doesn't exist Dolphin will log a bunch of errors on startup (though this happens before the Log window is set up so it only appears in the console and file), and likewise when starting a game.
UICommon::CreateLoadPath already creates empty folders for the other subdirectories if needed, so this PR does that for DynamicInputTextures too.

UICommon: Create Load/DynamicInputTextures directory on startup

---

Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/DiscIO/RiivolutionPatcher.cpp

Fixes https://bugs.dolphin-emu.org/issues/13138
Searching the file system for a file every time the given path does not exist is not particularly efficient, but I don't think it matters much. Most XML files seem to be well-behaved anyway.

RiivolutionPatcher: Use capitalization of file that exists in the host file system if possible.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.kt

Bug I noticed that happens if you try to do a config change while on the user data import warning dialog and then press `Yes` to start. The app crashes because it did not have the view model initialized properly.

Android: Initialize TaskViewModel earlier in User Data Activity

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SingleChoiceViewHolder.java
Source/Android/app/src/main/res/layout-ldrtl/list_item_setting.xml
Source/Android/app/src/main/res/layout/list_item_setting.xml
Source/Android/app/src/main/res/values/strings.xml

The settings GameCube Controller N and Wii Remote N (where N is a number) have two purposes: You can select what controller type you want to use, and also, when you select a controller type (even if you're selecting the one that already is selected), the mapping settings open. This second part is less discoverable than it ideally should be. I'm changing it so that there now is a button for opening the mapping settings instead.

Android: Add a button for accessing controller mappings

---

Source/Core/Common/Assert.h
Source/Core/Core/CheatSearch.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/MMIO.h
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/DolphinQt/CheatSearchWidget.cpp
Source/Core/DolphinQt/GCMemcardManager.cpp
Source/Core/VideoCommon/LightingShaderGen.cpp
Source/Core/VideoCommon/TextureConversionShader.cpp

This PR doubles as a way to ask what are Dolphin Emulator's plans for moving to C++20?  Is the issue that GCC still defaults to C++17 in version 12?  Other compiler support reasons?
And just how far should [[likely]] and [[unlikely]] be taken?  Nullptr checks seem like obvious candidates.  Any path that leads to a PanicAlert as well.  There are a lot of switch case defaults which only exist to catch stuff which should never happen.

[[unlikely]] ASSERT and minor ASSERT usage changes

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Common/Thread.cpp
Source/Core/Common/Thread.h
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.h
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h

This second stack leads to JNI problems on Android, because ART fetches the address and size of the original stack using pthread functions (see [GetThreadStack in art/runtime/thread.cc](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r18:art/runtime/thread.cc;l=1262)), and (presumably) treats stack addresses outside of the original stack as invalid. (What I don't understand is why some JNI operations on the CPU thread work fine despite this but others don't.)
Instead of creating a second stack, let's borrow the approach ART uses: Use pthread functions to find out the stack's address and size, then install guard pages at an appropriate location. This lets us get rid of a workaround we had in the MsgAlert function.
By the way, on Windows it was already the case that we …

Jit: Don't use a second stack

---

Source/Core/Core/Core.cpp

This is a small regression from KillRenderer, which caused duplicated frames to be counted on the FPS counter when the "Skip Presenting Duplicated Frames" option was disabled.

Fix duplicated FPS

---

Source/Core/Common/HookableEvent.h
Source/Core/VideoCommon/AbstractGfx.cpp
Source/Core/VideoCommon/AbstractGfx.h

The callback handle was being discarded, resulting in the callback immediately unregistering. 
Should fix issues with vsync not disabling during fast-forwarding, along with a bunch of other regressions that probally haven't been reported. 
I also added `[[nodiscard]]` to `HookableEvent::Register` so we will get some warning about such mistakes in the future.

Fix KillRenderer config changed regression

---

Externals/mGBA/mgba.vcxproj
Externals/mGBA/mgba.vcxproj.filters

A prerequisite for https://github.com/dolphin-emu/dolphin/pull/11611

Update mgba to 59ebf1c12dcbbe0141000cddccf667cd42e386a1

---

Source/Core/DolphinQt/Debugger/WatchWidget.cpp
Source/Core/DolphinQt/Debugger/WatchWidget.h

This is a workaround for https://bugs.dolphin-emu.org/issues/13190.
There's definitely a better way to solve this but I'm really unsure what the proper way to deal with it is, so this should at least resolve the pseudo-infinite-loop in the meantime.

Qt/WatchWidget: Don't update if not paused.

---

Source/Core/Core/IOS/Network/Socket.cpp

This fixes a longstanding issue where Dolphin could not host or connect to LAN rooms when using the Mario Kart Wii [LAN Multiplayer mod](https://wiki.tockdom.com/wiki/LAN_Multiplayer), available both standalone and in some custom track distributions. I have been unable to identify unmodified commercial games that benefit from this change. 
I understand that Dolphin supports setting socket options when requested, but it seems that a real Wii console supports sending broadcast packets even without the permission being explicitly set. To be more specific, I do not see these permissions being requested by the mod, but I admit that I am no Wii networking expert. 
I do not do error logging here, as it is a best-effort approach, and sockets not meant to broadcast seemingly fail to apply this …

Network/Socket: Enable broadcast permissions in socket requests

---

Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
Source/Core/DolphinQt/Config/ControllersWindow.cpp
Source/Core/DolphinQt/Config/ControllersWindow.h
Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp
Source/Core/DolphinQt/Config/WiimoteControllersWidget.h

In 5.0 an error message was displayed in the Controller Settings if a Bluetooth adapter wasn't found. That message was lost in the transition from wx to Qt, so this PR restores it.
I kept the 5.0 wording but removed the GroupBox since the current Controller layout doesn't have nested GroupBoxes.
Appearance:
5.0 Appearance:

Config: Restore Bluetooth adapter missing message in Controller Settings

---

Source/Core/DiscIO/Blob.cpp
Source/Core/DiscIO/Blob.h
Source/Core/DiscIO/CMakeLists.txt
Source/Core/DiscIO/SplitFileBlob.cpp
Source/Core/DiscIO/SplitFileBlob.h
Source/Core/DolphinLib.props
Source/Core/UICommon/GameFileCache.cpp

I occasionally see people struggling with the combine-after-ripping step, so I figured this would be useful to have, and it's pretty simple to implement.

DiscIO: Add support for CleanRip-style split ISOs.

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp

x86 address displacements are treated as signed, not unsigned.

Jit64: Fix the offsetAddedToAddress correction

---

Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
Source/Core/Core/HW/WiimoteEmu/MotionPlus.cpp
Source/Core/Core/HW/WiimoteEmu/MotionPlus.h
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
Source/Core/DolphinQt/TAS/TASCheckBox.cpp
Source/Core/DolphinQt/TAS/TASControlState.cpp
Source/Core/DolphinQt/TAS/TASControlState.h
Source/Core/DolphinQt/TAS/TASInputWindow.cpp
Source/Core/DolphinQt/TAS/TASInputWindow.h
Source/Core/DolphinQt/TAS/TASSpinBox.cpp
Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp
Source/Core/DolphinQt/TAS/WiiTASInputWindow.h

Will manually controlling both an accelerometer and a gyroscope at the same time be reasonable to do? No idea. Was this easy to implement thanks to the input override system? Yes.
Fixes https://bugs.dolphin-emu.org/issues/12443.

DolphinQt: Add MotionPlus support to TAS input

---

Source/Android/app/src/main/AndroidManifest.xml
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/DocumentProvider.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
Source/Android/app/src/main/res/values-v24/bools.xml
Source/Android/app/src/main/res/values/bools.xml

Apparently, being unable to access the Dolphin user folder (to install texture mods for example) is one thing that drives users to forks that shall not be named because those revert the scoped storage changes.
The Play Store and newer Android versions force us to implement scoped storage, so we place Dolphins user files in /sdcard/Android/data/org.dolphinemu.dolphinemu. On Android 13, this folder is not accessible to users.
So we just adopt the same solution as Skyline and RetroArch, we implement a custom DocumentProvier. This makes Dolphin show up as a file provider in the Android file manager and allows users to do things like editing the ini files or install texture mods.
cc @t895

Android: Implement DocumentProvider

---

Data/Sys/GameSettings/GSB.ini

For some reason the Japanese version of Sonic Adventure 2: Battle has a different first three letters of the GameID than the other versions, meaning that it wasn't properly applied. (The Japanese version is GSBJ8P, whereas the other versions are GSNP8P, and GSNE8P.)

Fix missing GameINI for Japanese version of Sonic Adventure 2: Battle

---

Source/Android/app/src/main/AndroidManifest.xml

Fixes side by side installation of debug, benchmark and release builds.

Android: Use $applicationId for DocmentProvider authority

---

Data/Sys/GameSettings/GAS.ini

Basically the same thing as #11643, but for Sonic Adventure DX: Director's Cut instead.

Fix missing GameINI for Japanese version of Sonic Adventure DX: Director's Cut

---

Source/Core/DolphinQt/TAS/TASSpinBox.cpp

This regressed in 0300b44d23b149a0b93dd0aa2e77d20a02882ddf. Specifically, the sliders and the stick/IR widgets did not update, but the spin boxes did update.
This was based on @JosJuice's suggestion. It doesn't seem to cause any infinite loops of widgets updating the spin boxes updating widgets. For what it's worth #8268 had an infinite loop at some point which I solved using my own `ReentranceBlocker` that allows 2 levels of recursion, but there was more complication there with 4 sliders and a total weight value compared to just x and y values.

DolphinQt: Fix TAS widgets not updating with enable controller input

---

Source/Core/AudioCommon/Mixer.cpp
Source/Core/AudioCommon/Mixer.h
Source/Core/Core/IOS/USB/Emulated/Skylander.cpp
Source/Core/Core/State.cpp

This PR introduces the ability to play the audio that would normally play through the Trap Team portal speaker via Dolphin.
The Trap Team speaker is 1 channel, so code has been replicated from the Wiimote speaker to duplicate each sample, and play it as stereo audio. The audio data is 16 bit unsigned pcm @ 8khz sample rate. 
Here's a [video](https://youtu.be/TdzfQtUZTO4) of it working, where the audio you hear from the portal is while the villain is being trapped.

Skylander Portal: Play Trap Team Audio

---

Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp

Fixes the deadlock below, which is the same bug as [issue 13027](https://bugs.dolphin-emu.org/issues/13027) and (I think) [issue 13154](https://bugs.dolphin-emu.org/issues/13154).
The following steps will cause a deadlock which soon leads to a hang:
1. Set Wii Remote 1 to Emulated Wii Remote
2. Select Connect Wii Remotes for Emulated Controllers
3. Pair a physical Wii Remote, which gets assigned to Wii Remote 1
4. Use the Remote's power button to turn it off
5. Wait until the console prints the error "Wiimote::IORead failed. Disconnecting Wii Remote".
At this point the deadlock has already happened although the GUI is still responsive for the moment. Any number of things will trigger the actual hang, including:
- Changing a Wii Remote option
- Starting a game
- Quitting Dolphin
There are …

ControllerInterface: Fix deadlock when Wii Remote disconnects

---

Source/Android/app/src/main/res/layout/list_item_header.xml

Android: Make header padding appear even

---

Source/Core/Core/HW/AudioInterface.cpp
Source/Core/Core/HW/AudioInterface.h
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/DVD/DVDInterface.h
Source/Core/Core/State.cpp

This should be equivalent, and 672 bytes is small enough that having it on the stack should be fine.

HW/DVDInterface: Avoid heap allocation in DTK callback.

---

BuildMacOSUniversalBinary.py

Apparently, this script just never supported setting the distributor, which means all of our universal macOS builds had their distributor set to "None".
I'll make a companion PR on sadm shortly.

BuildMacOSUniversalBinary: Add support for setting the distributor

---

Data/Sys/GameSettings/G6S.ini
Data/Sys/GameSettings/GJF.ini
Data/Sys/GameSettings/GKH.ini
Data/Sys/GameSettings/GTY.ini
Data/Sys/GameSettings/GYT.ini
Data/Sys/GameSettings/R9G.ini
Data/Sys/GameSettings/RO7.ini
Data/Sys/GameSettings/RO8.ini
Data/Sys/GameSettings/RQL.ini
Data/Sys/GameSettings/RST.ini
Data/Sys/GameSettings/RXI.ini
Data/Sys/GameSettings/SF2.ini
Data/Sys/GameSettings/SFU.ini

This PR provides a batch of GameINI updates:
- Adds EFBAccessEnable = True to several games to fix an issue where a splash logo displayed at boot would be missing.
- Sets SafeTextureCacheColorSamples to 512 as the minimum for a few games to fix choppy/pixelated FMVs.
- Add vertex rounding to Star Wars: The Force Unleashed and Ty 1 to fix a few visible lines in the HUD of these games specifically. (I'll admit this one isn't that necessary and I can remove it if there are any concerns).
- Disable texture filtering for several games to prevent broken FMVs.
If anyone wonders why Force Unleashed II has 2 GameINIs, the game for some weird reason has 2 entirely different serials in the PAL and NTSC-U regions, no idea why. And also, Force Unleashed I had DeferEFBCopies = False removed, because I …

GameINI: Krome updates

---

Source/Core/Common/TypeUtils.h
Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.h
Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Source/Core/Core/PowerPC/PPCAnalyst.cpp
Source/Core/Core/PowerPC/PPCAnalyst.h
Source/Core/Core/PowerPC/PPCTables.cpp
Source/Core/Core/PowerPC/PPCTables.h

Previously, Interpreter_Tables.cpp contained both the information for running an instruction in the interpreter AND the flags used for that instruction everywhere (including the JITs). Furthermore, this couldn't be `const`, as the last 3 members of `GekkoOPInfo` were mutable (for statistics purposes) (and also, those 3 members were explicitly set to 0 on all instructions, even though that wasn't useful information)).
Using C++20 features (`consteval` ~~as well as `constexpr` `std::array::fill`~~ (Android still doesn't support this)) these are now created at compile time, and also verify that there are no duplicate entries. The stats portion of `GekkoOPInfo` is now handled by a pointer to a separate array which allows the rest of it to be `const`.

Use C++20 features to create opcode tables at compile time

---

Source/Android/jni/AndroidCommon/AndroidCommon.cpp

Previously we were translating "w" to "w", which unlike in C++ doesn't truncate. See https://issuetracker.google.com/issues/180526528, and for reference, https://en.cppreference.com/w/cpp/io/c/fopen and https://en.cppreference.com/w/cpp/io/basic_filebuf/open.
This issue was brought to my attention by the recently published issue CVE-2023-21036 in the screenshot editing tool on Pixel phones. I'm not aware of any code in Dolphin that actually uses "w" with an existing file on Android (when we ask the user for a location to save to using SAF, a new file is always created), but still, best to fix this.

Android: Translate C++ "w" to ParcelFileDescriptor "wt"

---

Source/Core/WinUpdater/WinUI.cpp

This should fix https://forums.dolphin-emu.org/Thread-recent-update-triggering-this-error-on-auto-update
I *think* just adding quotes on both ends is enough, because a valid path on Windows cannot contain quotes by itself.

WinUpdater: Quote path for args when relaunching Dolphin.

---

Source/Core/Core/WiiRoot.cpp

A change made in 0d095b4 didn't take into account that the movie system doesn't set `sync_titles`.

Core: Fix starting movie recording with existing Wii save

---

Data/Sys/GameSettings/DLS.ini
Data/Sys/GameSettings/G3F.ini
Data/Sys/GameSettings/GDV.ini
Data/Sys/GameSettings/GFH.ini
Data/Sys/GameSettings/GH9.ini
Data/Sys/GameSettings/GIS.ini
Data/Sys/GameSettings/GK2.ini
Data/Sys/GameSettings/GLR.ini
Data/Sys/GameSettings/GNW.ini
Data/Sys/GameSettings/GNWE69.ini
Data/Sys/GameSettings/GOS.ini
Data/Sys/GameSettings/GQC.ini
Data/Sys/GameSettings/GSW.ini
Data/Sys/GameSettings/GSX.ini
Data/Sys/GameSettings/GUM.ini
Data/Sys/GameSettings/GUT.ini
Data/Sys/GameSettings/GWJ.ini
Data/Sys/GameSettings/GWY.ini
Data/Sys/GameSettings/HCL.ini
Data/Sys/GameSettings/R4Z.ini
Data/Sys/GameSettings/RML.ini
Data/Sys/GameSettings/RQR.ini
Data/Sys/GameSettings/SCY.ini
Data/Sys/GameSettings/SNT.ini
Data/Sys/GameSettings/SQI.ini

Very minor PR to make game settings more consistent for some bools (MMU, CPUThread and LowDCBZHack), replacing 0/1 with False/True.
While searching for 0/1 bools I found 2 unused variables, `UseDualCore` and `Patch Region`, so:
Changed `UseDualCore = 0` to `CPUThread = False` in `GDV.ini` (not even sure if it's needed? Couldn't find any info on the initial commit, on the wiki or the forums, tried a single race and it seemed fine with and without Dual Core, so idk...).
And removed the `Patch Region` line from `GNWE69.ini`, while I was at it I moved `ImmediateXFBEnable = False` from that same file to a new `GNW.ini` (unless there's a good reason this is only applied to the USA version?).
Hope this is fine!

[GameSettings] Change remaining 0/1 bools to False/True

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp

Should fix https://github.com/dolphin-emu/dolphin/pull/11671#discussion_r1142821268, I think?

JitArm64: Use 64-bit register for pointer when falling back to interpreter.

---

Source/Core/Common/ArmFPURoundMode.cpp
Source/Core/Common/FPURoundMode.h
Source/Core/Common/GenericFPURoundMode.cpp
Source/Core/Common/x64FPURoundMode.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/PowerPC/Gekko.h
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/UnitTests/Core/PowerPC/JitArm64/ConvertSingleDouble.cpp

Makes these utilities' namespace consistent with the majority of the Common library.

Common: Move FPU-related helpers into Common namespace

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsActivity.kt

Silly mistake I made during the coil switchover.
And while I was looking at our coroutines, `launchWhenStarted` and `launchWhenResumed` were deprecated (fastest deprecation I've ever seen). So I changed them to `launch`.

Android: Long press leanback game card fix

---

Source/Core/Common/build_info.txt.in

this should be reverted after next beta is built
see https://bugs.dolphin-emu.org/issues/13206
i've paused updates on the buildbot to ensure it doesn't update in the interim (even tho it shouldn't cause a problem)

windows: temporarily hardcode VCToolsVersion to 14.34.31931.0

---

Source/Core/AudioCommon/SurroundDecoder.h
Source/Core/Common/FixedSizeQueue.h
Source/Core/DolphinQt/Config/LogWidget.h
Source/UnitTests/Common/FixedSizeQueueTest.cpp

Gets this out of the global namespace.

Common: Move FixedSizeQueue into Common namespace

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayPointer.java

Potential fix to this crash detected in the play console.
```
Exception java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue (MotionEvent.java)
at android.view.MotionEvent.getX (MotionEvent.java:2412)
at org.dolphinemu.dolphinemu.overlay.InputOverlayPointer.onTouch (InputOverlayPointer.java:116)
at org.dolphinemu.dolphinemu.overlay.InputOverlay.onTouch (InputOverlay.java:345)
at android.view.View.dispatchTouchEvent (View.java:14385)
at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3143)
at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2814)
at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3143)
at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2814)
at …
```

Android: Ignore input from invalid pointer identifier

---

Source/Core/Core/PowerPC/Interpreter/ExceptionUtils.h
Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Branch.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_FPUtils.h
Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStorePaired.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Paired.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp

I missed these the last time around.
95% of this is just making the `ExceptionUtils.h` and `Interpreter_FPUtils.h` global-free, this just propagates around quite a bit.

Interpreter: Remove remaining System::GetInstance() and global ppcState.

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/Jit_Util.cpp
Source/Core/Core/PowerPC/JitArm64/Jit_Util.h
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp

*Completely untested* because I have no 64-bit ARM device to test this on. Please actually try this before merging.

JitArm64: Avoid System::GetInstance() and ppcState.

---

Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp

This is a follow up to #11470. In that one I only did Memory Cards, and forgot to do the GCI Folder as well. Whoops.
This removes the GCI Folder path from the wrote to OSD message, to make it less likely that streamers will get dox'd from Dolphin. That is all.
Before:
After:

Remove GCI Folder Path from the Wrote to OSD Message

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/HW/GPFifo.cpp
Source/Core/Core/MemTools.cpp
Source/Core/Core/PowerPC/BreakPoints.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/JitInterface.h
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/PPCCache.cpp
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/Core/System.cpp
Source/Core/Core/System.h
Source/Core/DolphinQt/Debugger/CodeDiffDialog.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/UICommon/Disassembler.cpp
Source/UnitTests/Core/PageFaultTest.cpp

`InvalidateICacheLineFromJIT()` has a weird signature so we don't have to rewrite the JIT function that calls it, but I think that's fine for now -- I might do a follow-up PR on that one, since the Jit64 should really use `ABI_CallFunctionPRR()` instead of the manual stuff it's doing... Otherwise pretty straightforward.

JitInterface: Refactor to class, move to System.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/DocumentProvider.kt
Source/Android/app/src/main/res/values/strings.xml

Now that we have the DocumentsProvider, we can change the file manager button in the settings to directly open that.
cc @t895 @MayImilae

Android: Make button in the settings open user folder

---

Data/Sys/Shaders/asciiart.glsl

This extension is currently required to get good performance.
So instead of maybe triggering a GPU hang, let's just disable the shader and show a warning instead.
Sadly our postprocessing framework does not support reporting a warning, so the way to display the warning is a bit hacky.
But this is an ascii-art shader, we already have a font in the shader, so let's use it.

Shaders: Add error message for asciiart shader if shader_subgroup is missing.

---

Source/Core/DolphinQt/GameList/GameList.cpp

When right-clicking a game in the game list and choosing `Open Wii Save Folder` for game without save data, nothing happen. This PR checks the Wii save path and show a message box when no save is found (making the behaviour consistent with GC save).

GameList: Check Wii save path

---

Source/Core/DolphinQt/RenderWidget.cpp

The `QByteArray` returned by `QString::toUtf8()` was being freed so the char pointer was pointing to freed memory.
Found via ASan, didn't notice any issues during normal runtime.
This was triggered after hitting a key combo with alt (ex. toggle fullscreen) probably happens with others
```
=================================================================
==411946==ERROR: AddressSanitizer: heap-use-after-free on address 0x603000401968 at pc 0x55fa9385d2f5 bp 0x7ffc5a78c790 sp 0x7ffc5a78c788
READ of size 1 at 0x603000401968 thread T0
#0 0x55fa9385d2f4 in ImGuiIO::AddInputCharactersUTF8(char const*) /home/user/projects/dolphin/Externals/imgui/imgui.cpp:1176:12
#1 0x55fa93e9d0ed in VideoCommon::OnScreenUI::SetKey(unsigned int, bool, char const*) …
```

DolphinQt: RenderWidget fix heap-use-after-free

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/MacUpdater/CMakeLists.txt

Switches codesign targets from blindly attempting to codesign the places where targets might be placed to using generator expressions so cmake inserts the actual location of the target.
Also changes storyboard compiling from a `POST_BUILD` step to using proper dependency tracking.  In addition to avoiding the above issue, this also means that if someone edits the `.storyboard`, it will properly be recompiled.

CMake: Use generator expressions for codesign targets

---

Source/Core/DolphinQt/Config/FilesystemWidget.cpp
Source/Core/DolphinQt/Config/LogConfigWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Source/Core/DolphinQt/Settings/InterfacePane.cpp

Various objects didn't have expected parent management or only conditionally used, resulting in them not being managed and leaking
```
Indirect leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x559caf9473dd in operator new(unsigned long) (/home/user/projects/dolphin/Build/Binaries/dolphin-emu+0x6c73dd)
#1 0x559caf9c48cf in FilesystemWidget::CreateWidgets() /home/user/projects/dolphin/Source/Core/DolphinQt/Config/FilesystemWidget.cpp:59:18
#2 0x559caf9c453b in FilesystemWidget::FilesystemWidget(std::shared_ptr<DiscIO::Volume>) /home/user/projects/dolphin/Source/Core/DolphinQt/Config/FilesystemWidget.cpp:48:3
#3 0x559cafabacb2 in PropertiesDialog::PropertiesDialog(QWidget*, UICommon::GameFile const&) /home/user/projects/dolphin/Source/Core/DolphinQt/Config/PropertiesDialog.cpp:81:44
#4 …
```

DolphinQt: Fix memory leaks

---

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/JitInterface.h

This is an updated version of PR #11701 that also changes the argument order for JitArm64.

Jit: Change argument order for InvalidateICacheLine(s)FromJIT

---

Source/Core/DolphinQt/TAS/IRWidget.cpp
Source/Core/DolphinQt/TAS/StickWidget.cpp

This is a pretty inconsequential change, I just noticed this as I was skimming TAS-related code.
Even if your mouse moved ever-so-slightly as to not change the x/y position of the stick, or if you held down left-click and dragged your mouse off of the stick widget, it would continuously fire the ChangedX/Y signal as well as queue up a Qt re-draw for the widget.
~~I have no idea if this actually helps performance to any noticeable degree, but I just figured this is likely more beneficial than it could be harmful.~~
This appears to reduce window latency issues encountered when holding down frame advance and rotating the stick at the same time. It does not get rid of the latency, but definitely reduces it.

DolphinQt: StickWidget and IRWidget check for changed x/y before signaling change

---

Source/Core/Common/x64Emitter.h

Noticed a log message about this while playing around with #11025.

Jit64: Fix possibly redundant MOV in ABI_CallFunctionPR().

---

Source/Core/Core/PowerPC/BreakPoints.cpp
Source/Core/Core/PowerPC/BreakPoints.h
Source/Core/Core/PowerPC/Expression.cpp
Source/Core/Core/PowerPC/Expression.h
Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/PPCAnalyst.cpp
Source/Core/Core/PowerPC/PPCCache.cpp
Source/Core/Core/PowerPC/PPCTables.cpp
Source/Core/Core/PowerPC/PPCTables.h
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.h
Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Source/Core/DolphinQt/Debugger/CodeWidget.h
Source/Core/DolphinQt/Debugger/RegisterWidget.cpp
Source/Core/DolphinQt/Debugger/RegisterWidget.h
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/CommandProcessor.h
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/UnitTests/Core/CoreTimingTest.cpp
Source/UnitTests/Core/PowerPC/JitArm64/FPRF.cpp
Source/UnitTests/Core/PowerPC/JitArm64/Fres.cpp
Source/UnitTests/Core/PowerPC/JitArm64/Frsqrte.cpp

The only remaining one are the reference in `System` and the references in `PowerPC.cpp`, which will be replaced when refactoring `PowerPC.cpp` to a class.

Replace most remaining global ppcState references.

---

CMakeLists.txt
Source/Core/Common/CMakeLists.txt
Source/Core/VideoBackends/CMakeLists.txt

Building it on Linux is unnecessary as Direct3D and Metal are unavailable.
These checks match the checks used in VideoBackends/CMakeLists.txt:
https://github.com/dolphin-emu/dolphin/blob/d32e47cfdee975924240029ccea7f8c45bf9edb9/Source/Core/VideoBackends/CMakeLists.txt#L5-L13

CMake: Don't include SPIRV-Cross except on Windows and macOS

---

Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

This splits 'GetTexture()' in `TextureCacheBase` into two functions.  'GetTexture()' remains the way we look up a texture entry but a new function 'CreateTextureEntry()' is defined to handle the creation.  In addition, this cleans up the hi res texture logic so that it's all in one place.
There are a few advantages:
* Code is a bit cleaner
* Less branching for hi res textures (possibly compiler would optimize this but still)
* Allows for a `CustomTextureData` to be replaced or enhanced later (used in my PRs)

VideoCommon: split cache entry creation into a separate function

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp

This fixes a minor issue introduced by [PR#11554](https://github.com/dolphin-emu/dolphin/pull/11554).
In the constructor of `MemoryViewWidget` we connect the `Settings::EmulationStateChanged` signal to `MemoryViewWidget::UpdateColumns()`. This poses a problem with TASing because a frame advance step implicitly changes the emulation state. When we hold down the frame advance key, this signal is then fired multiple times in quick succession.
On every instance that this signal is fired, it turns out that `UpdateColumns()` would wait to acquire the CPU lock and begin re-writing data in the memory view table, even if the debugging UI was not enabled. This extra time spent acquiring the CPU lock would cause TAS Input windows to become unresponsive and laggy.
Simply checking for widget …

DolphinQt: Prevent MemoryViewWidget updates when hidden

---

Source/Core/DolphinQt/Settings/InterfacePane.cpp

See https://bugs.dolphin-emu.org/issues/13232; this was introduced in 7dde0c3c319577fd913e4de72a6113a8998ada49 (#11726). Apparently, providing a parent for a widget that is not visible makes your new widget visible when the parent is later made visible, in addition to managing the deletion of the widget; [the documentation](https://doc.qt.io/qt-6/qwidget.html#QWidget) does not specify this (only that if the parent is visible you need to explicitly show it).
CC @mackal since this is weird behavior.

DolphinQt: Fix mouse lock checkbox appearing when it shouldn't

---

Source/Core/Core/IOS/DI/DI.cpp

There's no good way to use this with non-global state, and it's only used in a few places, so let's just get rid of it.

IOS/DI: Remove RegisterWrapper.

---

Readme.md

The old URL redirects to the new URL for now, but apparently it will stop doing that in a few months. Let's update it in the Readme.

Readme: Update Transifex URL

---

Source/Core/Core/IOS/FS/FileSystem.h
Source/Core/Core/IOS/FS/FileSystemCommon.cpp
Source/Core/Core/IOS/FS/HostBackend/FS.cpp

The stats should actually match console now, which means block sizes for saves, channels and free blocks according to the Wii Menu should now match console too.
I've tested this by taking a NAND dump, importing that in Dolphin into an empty Wii folder, and then running [this self-written homebrew](https://gist.github.com/AdmiralCurtiss/6468753cebe9277e16a0f50370cb3ebd) ([binary](https://github.com/dolphin-emu/dolphin/files/11125202/dir-stats.zip)) and comparing the output.
[console-stats.txt](https://github.com/dolphin-emu/dolphin/files/11125211/console-stats.txt)
[dolphin-stats-before.txt](https://github.com/dolphin-emu/dolphin/files/11125212/dolphin-stats-before.txt)
[dolphin-stats-after.txt](https://github.com/dolphin-emu/dolphin/files/11125213/dolphin-stats-after.txt)
The log output …

IOS/FS: More accurate emulation of GetDirectoryStats() and GetNandStats().

---

Source/Core/Common/HookableEvent.h

This fixes a crash when recording fifologs, as the mutex is [acquired](https://github.com/dolphin-emu/dolphin/blob/0cd70c2aa51ce09460a9027199b422f787d80ffe/Source/Core/Common/HookableEvent.h#L105-L108) when [`BPWritten` calls `AfterFrameEvent::Trigger`](https://github.com/dolphin-emu/dolphin/blob/0cd70c2aa51ce09460a9027199b422f787d80ffe/Source/Core/VideoCommon/BPStructs.cpp#L351), but then acquired again when [`FifoRecorder::EndFrame` calls `m_end_of_frame_event.reset()`](https://github.com/dolphin-emu/dolphin/blob/0cd70c2aa51ce09460a9027199b422f787d80ffe/Source/Core/Core/FifoPlayer/FifoRecorder.cpp#L437). [`std::mutex`](https://en.cppreference.com/w/cpp/thread/mutex) does not allow calling `lock()` if the thread already owns the mutex, while …

HookableEvent: Use std::recursive_mutex instead of std::mutex

---

Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp

WiiConnect24 Channels will correct their entry in the DLList if needed before their call to `DownloadNowEx`.
Since we load the DLList on IOS reload, these changes are not reflected until next IOS reload.

IOS/Network/KD: Reload DLList on call to DownloadNowEx

---

Source/Core/Core/NetPlayServer.cpp

This was previously copying each pair out of the vector returned by GetInterfaceListInternal() when we just need to emplace the first entry of each pair.
Noticed while doing #11748

NetPlayServer: Prevent unnecessary copies in GetInterfaceSet()

---

Source/Core/Common/UPnP.cpp
Source/Core/Common/UPnP.h
Source/Core/Core/NetPlayServer.cpp

Keeps these utilities consistent with the rest of most of the Common library.

Common/UPnP: Move interface into Common namespace

---

Externals/MoltenVK/CMakeLists.txt

The MoltenVK changelog can be found [here](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.3).

Externals: Update MoltenVK to 1.2.3

---

Source/Core/Common/Crypto/bn.cpp
Source/Core/Common/Crypto/bn.h
Source/Core/Common/FileUtil.cpp
Source/Core/Common/HttpRequest.cpp
Source/Core/Common/HttpRequest.h
Source/Core/Common/SettingsHandler.cpp
Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/FifoPlayer/FifoRecorder.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.cpp
Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp
Source/Core/Core/HW/MemoryInterface.cpp
Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/HW/WiimoteEmu/DesiredWiimoteState.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Main.cpp
Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
Source/Core/UpdaterCommon/UpdaterCommon.cpp
Source/Core/VideoCommon/CPMemory.cpp
Source/Core/VideoCommon/ShaderCache.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/VertexLoaderManager.cpp

I could not get the three `-Wignored-attributes` warnings across AES.cpp and SHA1.cpp to go away.  I even briefly tried editing libstdc++, but it did not work.  For GCC, the `-Wunknown-pragmas` warning is still happening in CPUCull.cpp despite the pragmas trying to ignore that diagnostic.  I tried moving them out of the #if #else #endif block to see if that would fix it, but it did not.  There is room for debate whether the changes for `-Wunused-const-variable` are best.  It's either that or changing to an unscoped enum.
I am not situated to test MSVC quickly, so I have not bothered with it.

Resolve GCC/Clang Warnings

---

Source/Android/app/build.gradle
Source/Android/app/src/main/AndroidManifest.xml
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/DocumentProvider.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java

Fixes a bunch of bugs with the DocumentProvider and adds the ability to copy, delete and move folders.
I've also changed the app names of debug and release builds to avoid confusion for developers who have multiple versions of Dolphin (such as the Play Store release build + DEBUG) installed.

Android: Document Provider improvements

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/Core/Config/AchievementSettings.cpp
Source/Core/Core/Config/AchievementSettings.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, the AchievementsManager created in a previous PR is further implemented to activate achievements, leaderboards, and rich presence within the achievement runtime as retrieved from the RetroAchievements API, preparing them to be compared to memory.

Retroachievements activate

---

Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinQt/Settings.cpp
Source/Core/UICommon/CommandLineParse.cpp

Before, Settings::SetDebugModeEnabled was used; this calls SetBaseOrCurrent() which will usually permanently change the base configuration setting for the debugger to true. Thus, the debugger would remain active even if the --debugger command line option was removed. Now, it remains active only for the current run, like other command-line options.
Note that SetBaseOrCurrent is also used by the "Show Debugging UI" option under Options -> Interface; this means that if the debugger is turned off (or off and then back on) by the user while --debugger is specified, this will be reset to whatever the base configuration had when Dolphin is closed and reopened. This behavior is consistent with the rest of the UI.
To my understanding, the --debugger option is something from 5.0 stable/DolphinWx …

Treat --debugger command line as a temporary setting

---

Source/Core/Common/GL/GLInterface/GLX.cpp
Source/Core/Common/MemoryUtil.cpp
Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp
Source/Core/Core/PowerPC/GDBStub.cpp
Source/Core/DolphinNoGUI/PlatformWin32.cpp
Source/Core/DolphinQt/QtUtils/FlowLayout.cpp
Source/Core/DolphinQt/QtUtils/WinIconHelper.cpp
Source/Core/DolphinQt/Settings/GameCubePane.cpp
Source/Core/DolphinQt/ToolBar.cpp
Source/Core/UICommon/Disassembler.cpp
Source/Core/UICommon/ResourcePack/ResourcePack.cpp
Source/Core/VideoBackends/D3D12/DX12Context.cpp
Source/Core/VideoBackends/OGL/OGLTexture.cpp
Source/Core/VideoBackends/OGL/OGLTexture.h
Source/Core/WinUpdater/Main.cpp
Source/Core/WinUpdater/WinUI.cpp

This PR extracts the functional changes to Dolphin's source code from PR #11709, as that PR is held up by [requiring CMake 3.25 support](https://github.com/dolphin-emu/dolphin/pull/11716) on all platforms.  Preferring nullptr over zero as a null pointer constant is a [coding guideline](https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md#general-1) for the Dolphin Emulator project, as well as a [C++ Core Guideline](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-nullptr), though I'm sure I don't have to tell you this.

Embrace nullptr over NULL and 0

---

Source/Core/VideoBackends/Metal/MTLStateTracker.h
Source/Core/VideoBackends/Metal/MTLStateTracker.mm

In #11647, the user was also kind enough to give the first ever test of the Metal renderer's PerfQuery implementation and it was pretty broken: https://twitter.com/sup39x1207/status/1635115984108548096
Hopefully it's now less broken, but I still don't know how to get that test screen to verify

VideoBackends:Metal: Fix perf queries

---

Source/Core/Common/LinearDiskCache.h
Source/Core/VideoBackends/Vulkan/ObjectCache.cpp
Source/Core/VideoCommon/ShaderCache.cpp
Source/Core/VideoCommon/ShaderCache.h

Gets the interface out of the global namespace.

Common/LinearDiskCache: Move interface into Common namespace

---

Source/Core/DolphinQt/Config/Graphics/GraphicsBool.cpp
Source/Core/DolphinQt/Config/Graphics/GraphicsBool.h

In older versions of Dolphin GraphicsBoolEx was used to create a pair of radio buttons selecting one of Virtual XFB and Real XFB, but this was removed with the introduction of Hybrid XFB in #5498.
In the meantime GraphicsRadioInt was introduced to allow for Graphics radio buttons with multiple options, and boolean options should use checkboxes, so GraphicsBoolEx is now redundant.

Qt: Remove unused class GraphicsBoolEx

---

Source/Core/Common/ENet.h
Source/Core/Common/TraversalClient.cpp
Source/Core/Common/TraversalClient.h

Previously this was using the default deleter (which just calls delete on the pointer), which is incorrect, since the ENetHost instance is allocated through ENet's C API, so we need to use its functions to deallocate the host instead.

Common/TraversalClient: Use correct deleter with g_MainNetHost

---

Source/Core/Core/PowerPC/PPCCache.cpp
Source/Core/Core/PowerPC/PPCCache.h

Memory Override + Write-Back Cache emulation = game crash

Do not use magic numbers for RAM sizes/masks in PPCCache

---

Source/Core/Core/NetPlayServer.cpp

Test build for the user mentioned in #11283.

Netplay: Check if save is readable before marking it for sync.

---

Source/Core/VideoBackends/OGL/OGLConfig.cpp
Source/Core/VideoBackends/OGL/OGLConfig.h
Source/Core/VideoBackends/OGL/OGLTexture.cpp
Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp

See https://bugs.dolphin-emu.org/issues/13198 (where I wrote a bit about the history of the relevant dolphin code, and `sampler2DMSArray` in the GLES specs (though I haven't checked the main GL specs)) / https://gitlab.freedesktop.org/mesa/mesa/-/issues/8405. This change is untested, and the way we handle enabling extensions is a bit of a mess.
I'm also not sure if we should be disabling MSAA in some other way. Currently we say it's always enabled for ES 3.1 and ES 3.2, which seems odd. (Relatedly, though we [check the max samples](https://github.com/dolphin-emu/dolphin/blob/560a23957c7bef98a782ef6e7a73da06dc540a8b/Source/Core/VideoBackends/OGL/OGLConfig.cpp#L541-L543), we don't use that value and instead [hardcode a list of them](https://github.com/dolphin-emu/dolphin/blob/560a23957c7bef9 …

OGL: Only specify precision for sampler2DMSArray when it is defined

---

Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/IOS.h
Source/Core/Core/IOS/Network/IP/Top.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/SSL.cpp
Source/Core/Core/IOS/Network/Socket.cpp
Source/Core/Core/IOS/Network/Socket.h
Source/Core/Core/State.cpp
Source/Core/DolphinQt/Debugger/NetworkWidget.cpp

This was a global instance previously due to what seems to be legacy reasons.
I originally wanted to put this into one of the Network-related devices but there didn't seem to be a good single spot for it, so it just ended up in Kernel. I'm also not entirely sure why the Kernel uses `shared_ptr` for its device instances, can any of them actually outlive the Kernel itself? I've replicated this for the socket manager but I actually don't see any reason why it can't just be a `unique_ptr` instead.
@leoetlino Please review.
(As a side-note, I think I've noticed a logic error in the IOS savestating logic; nothing guarantees that devices in `m_device_map` are synced correctly with the ones in the savestate. You'd have to load a state from an IOS version than has different devices than the …

IOS/WiiSockMan: Move instance to IOS Kernel.

---

Source/Core/Core/IOS/IOS.cpp

Doesn't make much sense to have this active without a game.
(Noticed this while working on IOS deglobalization stuff.)

IOS: Only construct DolphinDevice on EmulationKernel IOS instances.

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/ConfigControls/ConfigBool.cpp
Source/Core/DolphinQt/Config/ConfigControls/ConfigBool.h
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.h
Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
Source/Core/DolphinQt/Config/Graphics/HacksWidget.h
Source/Core/DolphinQt/DolphinQt.vcxproj

GraphicsBool is used by the panes in the Graphics config window to create checkboxes that change their associated config setting, and update their own state when something else changes the config setting.
Despite its current name nothing about this class is particular to the Graphics window, so renaming it to ConfigBool better reflects its purpose. This should also make it less confusing when ConfigBools are eventually added to the other config windows.
I'll convert the other Graphics controls in other PRs; I figure it'll be simpler to review this one if everything's the same type.

Qt: Rename GraphicsBool to ConfigBool

---

Source/Core/Common/TraversalClient.cpp
Source/Core/Common/TraversalClient.h
Source/Core/Common/TraversalProto.h
Source/Core/Common/TraversalServer.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayClient.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/NetPlayServer.h
Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Source/Core/DolphinQt/NetPlay/NetPlayDialog.h

Moves the TraversalClient and TraversalProto interfaces into the Common namespace to make them consistent with the rest of Common and move them out of the global namespace

Common/Traversal: Move interface into Common namespace

---

Source/Core/DolphinQt/Debugger/NetworkWidget.cpp

This is similar to https://github.com/dolphin-emu/dolphin/pull/11623 where the Core state change invoked by the CPUThreadGuard does indirectly cause another Update() call.
I really think we need a better system here -- maybe the state change from the CPUThreadGuard/RunAsCPUThread shouldn't actually send any state change events? But this works around the problem in the meantime...

Qt/NetworkWidget: Don't update if not paused.

---

Source/Core/DolphinQt/Main.cpp

Before this change, dolphin was using rounded mode, which rounds up to integer scale factor at .5 or down otherwise. This means that if dolphin was started on a screen with 150% scaling, dolphin would actually be at 200%, which causes it to be larger than expected/ other apps. However, dolphin would still react to dpi scaling changes - so changing to 150% after opening the app would cause it to change size in an odd way and look somewhat bad until it is restarted.
using pass through causes dolphin to always be at the screen’s actual dpi scaling.

DolphinQt: use default dpi rounding mode (passthrough)

---

Source/Core/DolphinQt/DolphinQt.manifest
Source/Core/DolphinQt/Main.cpp

* Allow more correct behavior of Qt managing DPI awareness programmatically
* Fix handling of Qt-specific commandline args (now you can `-style fusion` and it will work)

DolphinQt: fix some usability issues

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.cpp
Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.h
Source/Core/DolphinQt/Config/FreeLookWidget.cpp
Source/Core/DolphinQt/Config/FreeLookWidget.h
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.h
Source/Core/DolphinQt/DolphinQt.vcxproj

(Same as #11780 but for combo boxes)
GraphicsChoice is used by the panes in the Graphics config window to create combo boxes that change their associated config setting, and update their own state when something else changes the config setting.
Despite its current name nothing about this class is particular to the Graphics window, so renaming it to ConfigChoice better reflects its purpose. This should also make it less confusing when ConfigChoices are eventually added to the other config windows.

Qt: Rename GraphicsChoice to ConfigChoice

---

Source/Core/DolphinQt/Debugger/CodeDiffDialog.cpp
Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Source/Core/DolphinQt/MainWindow.cpp

This is required for switching system color scheme (dark/light) dynamically at runtime.
see https://github.com/dolphin-emu/dolphin/pull/11789#issuecomment-1521211807

DolphinQt: reset stylesheets on colorSchemeChanged

---

Source/Core/DolphinQt/Config/Graphics/GraphicsWindow.cpp
Source/Core/DolphinQt/Config/Graphics/GraphicsWindow.h

These variables are only used in CreateMainLayout and so can be removed from the header and replaced with local variables.
Some of these were necessary until #11100 to switch between showing the normal graphics settings vs the software renderer settings.

Qt/GraphicsWindow: Remove unnecessary member variables

---

Source/Core/UICommon/VideoUtils.cpp
Source/Core/UICommon/VideoUtils.h

The ability to change the fullscreen resolution througnh the UI was removed in #6196, leaving this function unused.

VideoUtils: Remove unused function GetAvailableResolutions

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/ConfigControls/ConfigRadio.cpp
Source/Core/DolphinQt/Config/ConfigControls/ConfigRadio.h
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.h
Source/Core/DolphinQt/DolphinQt.vcxproj

(Continuing the Graphics* to Config* conversion)
GraphicsRadioInt is used by the panes in the Graphics config window to create radio buttons that change their associated config setting, and update their own state when something else changes the config setting.
Despite its current name nothing about this class is particular to the Graphics window, so renaming it to ConfigRadioInt better reflects its purpose. This should also make it less confusing when ConfigRadioInts are added to other config panes.

Qt: Rename GraphicsRadioInt to ConfigRadioInt

---

Externals/mbedtls/CMakeLists.txt
Source/Core/VideoBackends/Metal/MTLUtil.mm

So all those M1 iPads can enjoy their high res texture packs
Note: This means Xcode 14.3 will be required for anyone compiling for iOS.  Should I add anything to cmake for that?

Enable BCn texture support on iOS where available

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.cpp
Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.h
Source/Core/DolphinQt/Config/GameConfigWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h
Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
Source/Core/DolphinQt/DolphinQt.vcxproj

GraphicsSlider is used by the panes in the Graphics config window to create sliders that change their associated config setting, and update their own state when something else changes the config setting.
Despite its current name nothing about this class is particular to the Graphics window, so renaming it to ConfigSlider better reflects its purpose. This should also make it less confusing when ConfigSliders are added to other config panes.

Qt: Rename GraphicsSlider to ConfigSlider

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/ConfigControls/ConfigInteger.cpp
Source/Core/DolphinQt/Config/ConfigControls/ConfigInteger.h
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h
Source/Core/DolphinQt/DolphinQt.vcxproj

GraphicsInteger is used by the panes in the Graphics config window to create spin boxes that change their associated config setting, and update their own state when something else changes the config setting.
Despite its current name nothing about this class is particular to the Graphics window, so renaming it to ConfigInteger better reflects its purpose. This should also make it less confusing when ConfigIntegers are added to other config windows.

Qt: Rename GraphicsInteger to ConfigInteger

---

Source/Core/Common/StringUtil.cpp

The ifdef'd path for OpenBSD was added with 2c355b81f20fe0d40ac825375073d21b211732b9 with the addition of NetBSD support, but it does not build on OpenBSD.
```
Source/Core/Common/StringUtil.cpp:551:11: error: no matching function for call to 'libiconv'
iconv(conv_desc, reinterpret_cast<const char**>(&src_buffer), &src_bytes, &dst_buffer,
^~~~~
/usr/local/include/iconv.h:80:15: note: expanded from macro 'iconv'
#define iconv libiconv
^~~~~~~~
/usr/local/include/iconv.h:82:15: note: candidate function not viable: no known conversion from 'const char **' to 'char **' for 2nd argument
extern size_t iconv (iconv_t cd,  char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft);
^
/usr/local/include/iconv.h:80:15: note: expanded from macro 'iconv'
#define iconv libiconv
^
1 error …
```

Fix build of iconv code on OpenBSD

---

Source/Core/MacUpdater/CMakeLists.txt

Looks like `MACOSX_PACKAGE_LOCATION` doesn't work on folders
I couldn't find another way that properly puts a dependency on the storyboard file, so we'll just have to go back to hoping no one edits the storyboard

CMake: Fix storyboard copying

---

Source/Core/Core/CMakeLists.txt
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/IOS/USB/Emulated/Infinity.cpp
Source/Core/Core/IOS/USB/Emulated/Infinity.h
Source/Core/Core/IOS/USB/Host.cpp
Source/Core/Core/IOS/USB/Host.h
Source/Core/Core/System.cpp
Source/Core/Core/System.h
Source/Core/DolphinLib.props
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.cpp
Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.h
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MainWindow.h
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/MenuBar.h

Description
---
This PR introduces the ability to emulate the Infinity Base within Dolphin, another Wii peripheral device that can be a hassle to set up, and is currently unavailable for use on MacOS (without sudo) or Android. Where the Skylanders portal was a port from RPCS3, the Infinity code was written from scratch based on reverse engineering done with an Infinity 1.0 Base, and other pieces of research found online. [Here's a video of the functionality in action](https://youtu.be/agcioTM9hqs)
Tasks
---
Currently Working:
Nice to Haves:
Proper Color structures - similar to the Skylander Portal. Requires investigation.
Hopefully this might inspire a developer to look in to seeing how we can optimise Infinity within Dolphin 😄

Feature: Emulate Infinity Base

---

Source/Core/Common/Thread.cpp

86c1f6e1e7e2abcc3f42e1182134e632b218b6d3 introduced code that had not been build tested on OpenBSD.
https://bugs.dolphin-emu.org/issues/13241

Fix building on OpenBSD

---

Source/Core/DolphinQt/MainWindow.cpp

This fixes the following behavior I encountered.
1. Emulation > Save State > Save State to File. Close dialog without setting filename
2. Observe on-screen message "Saving state to " (no filepath given), and observe xxxxx.tmp file being created in main Dolphin directory
3. Repeat step 1 and 2 to observe more .tmp files being created
4. Start Movie Recording, repeat step 1 to now also see blank ".dtm" file present
Looks like Dolphin will always write savestate data to a temp file and then try to rename it. Ultimately when the provided filename is blank (because the QFileDialog was closed without the name being set) the rename will fail and the temp file will remain.
I figured this filename check should also be done for the load state scenario, as all this does is prevent a load failure in …

Qt: Prevent savestate load/save on empty filename

---

Source/Core/DolphinQt/Config/ARCodeWidget.cpp
Source/Core/DolphinQt/Config/ARCodeWidget.h
Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp
Source/Core/DolphinQt/Config/GeckoCodeWidget.h

This PR adds the ability to sort codes by enabled state which can be useful when you want to disable some codes but the code list is huge.

Gecko/ARCode: Add sort by enabled state

---

Source/Core/Core/PowerPC/JitInterface.cpp

We can use JitInterface's system member variable to avoid needing this

JitInterface: Remove global system accessor

---

Source/Core/Common/JitRegister.cpp
Source/Core/Common/JitRegister.h
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
Source/Core/Core/PowerPC/Jit64Common/TrampolineCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/VideoCommon/VertexLoaderX64.cpp

Makes the namespace consistent with other common utilities.

Common/JitRegister: Move interface into Common namespace

---

Data/Sys/GameSettings/GC6.ini
Data/Sys/GameSettings/GXX.ini

These games seem to constantly have unused vertices, and this is worst shown in the Shadow Pokemon purification cutscene. The Shadow Pokemon purification cutscene is even worse on XD with forced single core mode, as instead of having FPS dropping with VPS staying 60ish, it will drop both, resulting in audio stuttering. Turning on CPUCall seems to have a 7/8 reduction of draw calls for that cutscene (~800 -> ~100), doubling performance (~70% max to ~150% max on my setup). Many other areas of the game seem to benefit from this setting too, having some kind of performance boost (although this is best seen in 60 FPS areas as the 30 FPS areas generally don't struggle)

Add CPUCull to Pokemon Colosseum and Pokemon XD inis.

---

Data/Sys/GameSettings/RSO.ini
Source/Core/Core/DolphinAnalytics.cpp
Source/Core/Core/DolphinAnalytics.h
Source/Core/VideoCommon/VideoBackendBase.cpp

See https://bugs.dolphin-emu.org/issues/13248.
Before:
After:
You can also see the menu performance before in [this video](https://www.youtube.com/watch?v=mxlwQfDiQzg) (which was coincidentally uploaded a day ago).
This game is doing several weird rendering things which I'll need to investigate further. I *also* encountered the game hanging (though music still played) after I failed, but I haven't been able to consistently reproduce it.

GameINI: Enable bounding box for "Solitaire & Mahjong"

---

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/PowerPC/PPCTables.cpp
Source/Core/Core/PowerPC/PPCTables.h

Gets rid of a lingering dependency on the interpreter in common code and a bunch of indirect inclusions.

PPCTables: Remove unnecessary includes

---

Source/Core/Common/SymbolDB.h
Source/Core/Core/PowerPC/PPCSymbolDB.cpp

Avoids default constructing an entry in the map that just gets immediately overwritten. Also gets rid of some redundant map lookups.

PPCSymbolDB: Use emplace() where applicable

---

Source/Core/DolphinQt/Main.cpp

This reverts commit cfe36836688ae21ae32383958504fbc5f6c21660 (PR #11788).
On Windows systems with 125% DPI scaling, this was causing both icons and the OSD to be upscaled by 25% using nearest neighbor scaling, which looks really bad. @shuffle2 has said that this will be improved later, but we should revert it for now for the sake of the upcoming beta build.

Revert "DolphinQt: use default dpi rounding mode (passthrough)"

---

Source/Core/InputCommon/CMakeLists.txt
Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Source/Core/InputCommon/ControllerInterface/ControllerInterface.h
Source/Core/InputCommon/ControllerInterface/SteamDeck/SteamDeck.cpp
Source/Core/InputCommon/ControllerInterface/SteamDeck/SteamDeck.h

This code adds an alternate way of accessing the Steam Deck's controls without going through Steam's input remapper. This has the following advantages:
* can use motion controls without having to separately install [a system service](https://github.com/kmicki/SteamDeckGyroDSU)
* can independently use the thumb sticks, touch pads, and back grip buttons (which do not map cleanly to an emulated Xbox 360 controller)
This works by opening the hidraw device corresponding to the Deck controls and manually parsing the input reports.
This does not inherently conflict with having Steam running (both processes can read input reports at the same time), but Steam will continue to respond to special buttons like the "STEAM" or "..." buttons.
This code does not support hotplugging or having multiple …

Support Steam Deck controls natively through hidraw

---

Source/UnitTests/CMakeLists.txt

So you can actually see which test case fails in the buildbot output.
https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-output-on-failure

CMake: Set --output-on-failure flag for unittests target.

---

Source/Android/jni/WiiUtils.cpp
Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Boot/Boot_WiiWAD.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/HW/WiiSave.cpp
Source/Core/Core/IOS/DI/DI.cpp
Source/Core/Core/IOS/Device.cpp
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/ES/ES.h
Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/Core/IOS/ES/Formats.h
Source/Core/Core/IOS/ES/Identity.cpp
Source/Core/Core/IOS/ES/NandUtils.cpp
Source/Core/Core/IOS/ES/TitleContents.cpp
Source/Core/Core/IOS/ES/TitleInformation.cpp
Source/Core/Core/IOS/ES/TitleManagement.cpp
Source/Core/Core/IOS/ES/Views.cpp
Source/Core/Core/IOS/FS/FileSystemProxy.cpp
Source/Core/Core/IOS/FS/FileSystemProxy.h
Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/IOS.h
Source/Core/Core/IOS/WFS/WFSI.cpp
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/WiiRoot.cpp
Source/Core/Core/WiiUtils.cpp
Source/Core/Core/WiiUtils.h
Source/Core/DiscIO/VolumeVerifier.cpp
Source/Core/DolphinQt/MenuBar.cpp

@leoetlino You were interested in this back in #11787. I think this is a pretty good solution all things considered.

IOS: Further deglobalization and emulation/maintainance code splitting.

---

Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/Core.cpp
Source/Core/Core/HW/DVD/FileMonitor.cpp
Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/Core/IOS/FS/HostBackend/FS.cpp
Source/Core/Core/IOS/USB/USBV4.cpp
Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DolphinNoGUI/MainNoGUI.cpp
Source/Core/DolphinQt/Config/FilesystemWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinTool/ToolMain.cpp
Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp
Source/Core/UICommon/AutoUpdate.cpp
Source/Core/WinUpdater/Main.cpp
Source/UnitTests/Common/StringUtilTest.cpp

Moves a few of the lightly used utilities into the Common namespace to get them out of global scope. This doesn't touch all of the utility functions, since a few are heavily used and best suited to their own PR

Common/StringUtil: Move some utilities into the Common namespace

---

Source/Core/Common/MemArena.h
Source/Core/Common/MemArenaAndroid.cpp

This is a port of ffbe6cb21f35ea8502da8c029266b566e2833a60 (#9834) to Android. Completely untested, @JosJuice can you check if this works correctly?

Common/MemArenaAndroid: Keep fastmem region mapped.

---

Source/Core/Common/MemArena.h
Source/Core/Common/MemArenaAndroid.cpp
Source/Core/Common/MemArenaUnix.cpp
Source/Core/Common/MemArenaWin.cpp
Source/Core/Core/HW/Memmap.cpp

Noticed this while reviewing #11737.
First commit: Both [CreateFileMapping](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-createfilemappingw) and [MapViewOfFileEx](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffileex) want their memory size/offset (respectively) as two separate high bits and low bits parameters, for what I assume are ancient legacy reasons.
Second commit: The last parameter of [CreateFileMapping](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-createfilemappingw) is a name so that other functions can find this memory mapping using the same name. This is explicitly what we not want and it can be set to NULL to not give it a findable name, so let's just do that.
With these commits …

Common/MemArenaWin: Improve file mapping logic.

---

Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp

This is a fix for a bug I found while putting together a series that reworks XInput2 to fix https://bugs.dolphin-emu.org/issues/10668 (and two duplicates).  Because this fix is necessary regardless of whether you take that series, I've sent it as its own pull request for ease of review and merging.  
---
XInput2 was created to support multiple pointer/keyboard pairs (often called MPX for multi-pointer X).  Dolphin's XInput2 implementation has always supported MPX by creating a KeyboardMouse object per master pointer.  Since commit bbb12a7, Dolphin's keyboard state is filtered by the output of XQueryKeymap.  As a core X function, XQueryKeymap queries "the" keyboard, which by default is the first master keyboard.  As a result, Dolphin will ignore keys pressed on other master keyboards …

XInput2: Accept input from keyboards other than the first master

---

Source/Core/Core/ConfigManager.cpp
Source/Core/Core/ConfigManager.h
Source/Core/UICommon/DiscordPresence.cpp
Source/Core/UICommon/GameFile.cpp

Rehash of #10390 but cleaner. Discord allows for using URL's for their RPC images. Documented as of this [PR](https://github.com/discord/discord-api-docs/pull/4371#event-6029119110).
The image will be the Dolphin logo if GameTDB does not have a cover for the current game.
Otherwise, the cover of the game will appear in the RPC.

UICommon/DiscordPresence: Use GameTDB covers for RPC

---

Source/Core/DolphinQt/CMakeLists.txt

`QT_DIR` isn't defined when I attempt to create testing builds, but it works on the buildbot for whatever reason. Switching to `Qt6_DIR` fixes my local builds.

DolphinQt: Adjust variable name for Qt root directory in steamrt builds

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, the AchievementsManager created in a previous PR is further implemented to peek into game memory, process that within the rcheevos library, and handle achievement events that occur, resulting in the API calls to award achievements, submit scores/times to leaderboards, and generate and post Rich Presence for the currently played game.

RetroAchievements Memory, Events, and Awarding

---

Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.h

Also remove munmap from ReserveMemoryRegion in MemArenaAndroid and put it into ReleaseMemoryRegion, otherwise the lookup table would break.
Only works on Linux and Android so far.
It gives around 2% performance boost on my x86_64 desktop when running with the speed limit disabled, on the arm64 device i've tested it the gains are less significant. But ofc might be that my testing method is wrong, and i wouldn't be surprised if the performance improvement is less or even imagined.
I'm filing a PR in this WIP state cause i'd like to know if i'm doing something wrong or whether the performance gains are real and whether it makes sense to continue with this work or not. I will fix the formatting to match dolphins code style after that.
In this branch i have extended the map even further and …

 Jit: Improve block lookup performance through a shm memory segment. 

---

Readme.md
Source/Core/Common/build_info.txt.in
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
Source/PCH/pch.h

bump minimum VS version to 17.6 and rollback some workarounds
I'll re-enable auto updates on the buildbot once beta is built (is it built already?)

update to VS 17.6

---

Source/Core/Core/IOS/WFS/WFSI.h

This warning came about after 46ad8b9d68b7eff720a6f33e6029ddd36ab8edaa
```
In file included from /home/ports/pobj/dolphin-5.0.0.20230429/dolphin-5.0.0.20230429/Source/Core/Core/IOS/WFS/WFSI.cpp:4: /home/ports/pobj/dolphin-5.0.0.20230429/dolphin-5.0.0.20230429/Source/Core/Core/IOS/WFS/WFSI.h:54:6: warning: private field 'm_aes_key' is not used [-Wunused-private-field]
u8 m_aes_key[0x10] = {};
^
```

Silence AES warning

---

Source/Core/UICommon/DiscordPresence.cpp

```
/home/ports/pobj/dolphin-5.0.0.20230429/dolphin-5.0.0.20230429/Source/Core/UICommon/DiscordPresence.cpp:27:13: warning: unused variable 's_using_custom_client' [-Wunused-variable]
static bool s_using_custom_client = false;
^
```

Fix s_using_custom_client warning with DiscordPresence

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp

BLR optimization was completely disabled for both x86 and arm64.
Block map fallback is my bad, sorry.

Blr and block map fixes

---

Source/VSProps/Base.props

fixes build failures related to pch (supposedly, i haven't noticed the error locally)
https://stackoverflow.com/a/76316717/375416

msvc: disable building std modules

---

Source/Core/DolphinQt/Config/Graphics/PostProcessingConfigWindow.cpp
Source/Core/DolphinQt/Config/Graphics/PostProcessingConfigWindow.h

-The float sliders initial value wasn't calculated correctly
-Fix the checkbox dependencies not being applied until a setting was changed for the first time

Qt: Fix some Post Process Configuration Widget issues

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, the AchievementsManager created in a previous PR is further implemented to display on-screen popup messages to notify the player when important events such as achievement unlocks and leaderboard submissions take place, utilizing the imGui code in OnScreenDisplay to handle these messages.

Retroachievements popups

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/infinitybase/InfinityConfig.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/infinitybase/model/Figure.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/infinitybase/ui/FigureSlot.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/infinitybase/ui/FigureSlotAdapter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/skylanders/ui/SkylanderSlotAdapter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
Source/Android/app/src/main/res/layout/dialog_create_infinity_figure.xml
Source/Android/app/src/main/res/layout/dialog_nfc_figures_manager.xml
Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
Source/Android/app/src/main/res/layout/list_item_nfc_figure_slot.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Android/jni/AndroidCommon/IDCache.cpp
Source/Android/jni/AndroidCommon/IDCache.h
Source/Android/jni/CMakeLists.txt
Source/Android/jni/InfinityConfig.cpp
Source/Android/jni/SkylanderConfig.cpp
Source/Core/Core/IOS/USB/Emulated/Infinity.cpp
Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.cpp

Building off of https://github.com/dolphin-emu/dolphin/pull/11546, this PR intends to bring the Infinity Base functionality over to Android, creating a UI largely the same as the Skylanders Portal, using Material GUI components. Note, that this should be tested with someone with a better phone than me as I only have a Nokia 5!

Android: Infinity Base UI

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.kt

Should fix one of the reported crashes on Google Play. The issue can happen if you leave the activity during directory initialization.

Android: Don't show analytics dialog for destroyed activity

---

Source/Core/Core/HotkeyManager.cpp
Source/Core/Core/HotkeyManager.h
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/Mapping/HotkeyUSBEmu.cpp
Source/Core/DolphinQt/Config/Mapping/HotkeyUSBEmu.h
Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/HotkeyScheduler.cpp
Source/Core/DolphinQt/HotkeyScheduler.h
Source/Core/DolphinQt/MainWindow.cpp

Ready to merge. 
Creating two new hotkeys that open the Skylanders Portal and Infinity Base menus, so the game doesn't need to be exited each time. Added a tab in the hotkey settings menu for "USB Emulation" to set the hotkeys. 
Default hotkeys:
Skylanders Portal of Power: `Ctrl+P`
Infinity Base: `Ctrl+I`
This commit is not dependent on the Skylanders menu overhaul, can be merged with the current USB emulation menus.

Add hotkey to open Skylanders and Infinity Menus

---

Source/Core/Core/AchievementManager.cpp

Fixing a bug with the RetroAchievements integration where certain combinations of configurations would result in a malformed API request and an attempt to dereference the null response.

Fix RetroAchievements Login Crash

---

CMake/FindMBEDTLS.cmake

The Mbed TLS system library required by Dolphin is not found on Arch Linux because the library is [installed in a `mbedtls2` subdirectory](https://archlinux.org/packages/extra/x86_64/mbedtls2/files/) to avoid conflict with the current Mbed TLS version 3.

CMake: Fix build with legacy system Mbed TLS

---

Source/Core/InputCommon/ControllerInterface/Android/Android.cpp

Instead of InputEvent.getDevice followed by InputDevice.getId. Should hopefully fix https://bugs.dolphin-emu.org/issues/13237, while also being simpler.

ControllerInterface/Android: Use InputEvent.getDeviceId

---

Source/Core/DolphinQt/Main.cpp

This reverts commit 20e14aab06b127870f8ca5bd170fda4c560bef82.

Revert "Revert "DolphinQt: use default dpi rounding mode (passthrough)""

---

Data/Sys/Shaders/lens_distortion.glsl

`any()` failed to build on my machine, but it doesn't seem to be necessary

Video: Fix lens_distortion post process shader not compiling

---

Source/Core/DolphinQt/Config/Graphics/PostProcessingConfigWindow.cpp

Same fix as https://github.com/dolphin-emu/dolphin/pull/11846 but applied to int sliders instead of float ones

Qt: Fix some Post Process Configuration Widget issues #2

---

Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.h
Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
Source/Core/DolphinQt/Achievements/AchievementsWindow.h
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MainWindow.h
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/MenuBar.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, I add an AchievementsWindow, a dialog accessible through the main window's menu bar, that here contains settings and login for RetroAchievements, and in the future, visual data about the player's unlocks and rankings on the site.

Retroachievements dialog

---

Source/Core/VideoBackends/Metal/MTLBoundingBox.mm

AMD Metal drivers have a goofy bug where the bbox buffer stops being coherent with the cpu if you copy to it from a private (gpu) buffer and don't do anything else with it in that command buffer.
[Test case available here if anyone's curious](https://github.com/TellowKrinkle/MetalBugReproduction/releases/tag/BrokenSharedBufferCoherency)
The old way was actually missing a required fence wait on the upload fence (to prevent the GPU from attempting the copy before it uploaded the copy source), but that's not the actual cause of the breakage, as indicated by the above test case, which doesn't disable hazard tracking and therefore doesn't have any fence requirements.
Side note, if anyone has any AMD GPUs running not-Ventura, please run the linked test case and report back, I'd love to figure …

VideoBackends:Metal: Allocate bounding box uploads on a cpu buffer

---

Source/Core/Common/FatFsUtil.cpp
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/DolphinQt/Settings/WiiPane.cpp
Source/Core/DolphinQt/Settings/WiiPane.h

Add SD card size option for converting folder -> file.

---

Source/Core/DolphinLib.props
Source/Core/VideoCommon/Assets/CustomAsset.cpp
Source/Core/VideoCommon/Assets/CustomAsset.h
Source/Core/VideoCommon/Assets/CustomAssetLibrary.cpp
Source/Core/VideoCommon/Assets/CustomAssetLibrary.h
Source/Core/VideoCommon/CMakeLists.txt

@AdmiralCurtiss  - I know you've been reviewing a lot and I hope to make things easier for you when I can.  Not sure why I didn't think of this originally but here's a more thinned down version of #11858 .  Hopefully more mergeable :).  Also, moved assets to 'Assets' folder.  I've been sticking everything in GraphicsMods which is just bad practice...  (CustomTextureData will move to 'Assets' too in a future review)
For those not following along, this adds a generic `CustomAsset` interface that can be used to load specific data for a particular object we consider an Asset (think of a texture).  This also provides a `CustomAssetLibrary` which knows given an `AssetID` (a string) what asset to load.  What that load looks like is dependent on the library implementation itself (no …

VideoCommon: add custom asset implementation and asset library

---

Data/Sys/GameSettings/RWA.ini

Prevents missing characters in text in menus.
Example in the main menu on medium and Fast settings:
Main menu on Safe:

WALL•E - Use 'Safe' Texture Cache Accuracy

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/MenuTag.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt

Accessing any of the submenus "Buttons", "Motion Simulation" or "Motion Input" for Wii Remotes 2-4 would actually lead to the corresponding submenu for Wii Remote 1.

Android: Fix submenus for Wii Remote 2-4

---

Source/Core/DolphinLib.props
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.h
Source/Core/VideoCommon/CMakeLists.txt

VideoCommon: add  an asset library that loads directly from the filesystem

---

Source/Core/DolphinNoGUI/CMakeLists.txt
Source/Core/DolphinNoGUI/MainNoGUI.cpp
Source/Core/DolphinNoGUI/Platform.h
Source/Core/DolphinNoGUI/PlatformMacos.mm

Previously dolphin no-gui on MacOS only had the headless option, this adds another platform that uses Appkit.
~~I still need to add all of the keydown event's that the other platforms have.~~ This is all complete as well
~~Just wanted to get feedback while I add the events.~~ Events are now added

NoGUI: Create MacOS platform

---

Source/Core/VideoCommon/Assets/CustomAsset.h
Source/Core/VideoCommon/Assets/TextureAsset.cpp

I was looking back over the asset logic and wondered if there might be a problem.
If in the middle of an asset being reloaded, imagine that a callee has called `GetData()`.  This would give them a pointer to that data.  If they are still operating on that data when the asset is reloaded, then the data would be modified on the asset reload thread.  This could be potentially dangreous at worst or lead to incorrect data at best.  To avoid this, I return a `shared_ptr` ensuring that the callee will have access to the original data for the lifetime of the smart ptr.

VideoCommon: prevent potential data issue when reloading Asset data

---

Source/Core/Core/CoreTiming.cpp
Source/Core/Core/CoreTiming.h
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/CommandProcessor.h
Source/Core/VideoCommon/Fifo.h
Source/Core/VideoCommon/OpcodeDecoding.cpp

When faced with this error, users often don't try disabling dual core, even though the error message suggests it. Perhaps the message is just too long and lists too many things?
To try to improve the situation, I'm rewording the message and making it say different things depending on what settings you are using.

VideoCommon: Reword the unknown opcode error message

---

Source/Core/VideoCommon/Assets/CustomTextureData.cpp
Source/Core/VideoCommon/Assets/CustomTextureData.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp

This can't actually happen in our code today but it was split out of #11681

VideoCommon: avoid segfault when loading a PNG with no custom texture data levels

---

Source/Core/VideoCommon/Assets/CustomAsset.cpp
Source/Core/VideoCommon/Assets/CustomAsset.h
Source/Core/VideoCommon/Assets/CustomAssetLoader.cpp
Source/Core/VideoCommon/Assets/CustomAssetLoader.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.h
Source/Core/VideoCommon/Assets/TextureAsset.cpp

For the most part, this review adds additional locks in place for thread safety.  There were a few places where locks were being held onto too long, that has been updated as well.

VideoCommon: add additional locks around asset access / usage

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/Core/Core.cpp

Somewhere in the process of getting the memory peeking right for achievements, the AchievementManager call to DoFrame went missing. This restores it properly.

RetroAchievements Bugfix: Fixed Missing DoFrame Call

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/Core.h
Source/Core/DolphinNoGUI/MainNoGUI.cpp
Source/Core/DolphinQt/Host.cpp
Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinQt/Settings.cpp
Source/Core/DolphinTool/ToolMain.cpp
Source/UnitTests/UnitTestsMain.cpp

Core's `PauseAndLock()` states that `// WARNING: PauseAndLock is not fully threadsafe so is only valid on the Host Thread`, but there's absolutely no protection against doing this.
This adds an `ASSERT()` that we are indeed the host thread. To do that, this moves DolphinQt's `IsHostThread()` function into Core, and adds relevant `DeclareAsHostThread()` calls to all entry points.
This may expose erroneous usages of `Core::RunAsCPUThread()` and similar functions, which if found should be fixed before this is merged.

Core: Assert that only the Host thread may call PauseAndLock().

---

Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h

This series reworks XInput2 to fix https://bugs.dolphin-emu.org/issues/10668 (and two duplicates).  The first commit in this series is the (only) commit in #11758.  GitHub won't let me make a pull request based off another pull request (it redirects me to my fork).  I thought I was helping by fixing one bug per PR, but actually I just created noise.  Sorry about that!
---
Bug 10668 is a complaint that while Dolphin is open, Openbox does not respond to clicks on the root window, and Dolphin only sees clicks on the root window or window decorations, not inside Dolphin's own windows.  The root cause of this conflict is special X server behavior that causes button press events to grant the receiving client an implicit passive grab on the pointer.  Because only one client can get the grab, the …

Xinput2: use raw events and queries

---

Source/Core/Core/Core.cpp

Fixes https://bugs.dolphin-emu.org/issues/13274.

Core: Declare emu thread as CPU thread while shutting down

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.kt

Since the ThemeProvider interface changed `fun getThemeId()` to `var themeId`, I had to adjust how it was used in the EmulationActivity. Similar case for `fun getConfiguredControllerType()`.

android: Fix compilation error from Kotlin changes

---

Source/Core/Core/HW/VideoInterface.cpp

The emulated system has full access to this register so it could potentially write garbage in there. Garbage could also be loaded from a savestate.
YAGCD says only the lowest bit is used so that's what I've done here, but someone would have to actually test this on hardware to be sure.

VI: Prevent out-of-bounds access when clock register is a nonstandard value.

---

Source/Core/Common/EnumFormatter.h
Source/Core/Common/EnumMap.h
Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/VideoCommon/ShaderGenCommon.h

The minimum GCC version is going to become GCC 10.  (#10969)

Remove old GCC version workarounds

---

Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp

I've received a report from an Android user with a gamepad (a "BSP-D3") where one physical trigger is controlling two analog axes at the same time. This was causing RemoveSpuriousTriggerCombinations to delete both axes, which is clearly not a desireable outcome.
With this change, now the axis with the greatest smoothness is kept, or both in case they have the same smoothness.

InputCommon: Don't treat two analog inputs as a spurious trigger combo

---

CMake/FindMBEDTLS.cmake

This breaks any further can-compile checks in other CMakeLists if no MBEDTLS was found.
(Noticed this while fighting with libcurl over in #11853.)

Fix lingering CMAKE_REQUIRED_INCLUDES variable from FindMBEDTLS.

---

Source/Core/VideoCommon/PostProcessing.cpp

- An assert would be erroneously thrown when shaders declared an array of 4 int or float options, despite 4 being the max supported (a simple <= / < mistake)
- When changing the type of a shader option (e.g. from bool to float), the serialization would be stuck appending the value from the previous option type, making the shader fail to build permanently until the cache were cleaned

Video: Fix Post Process shader options issues

---

Data/Sys/Load/GraphicMods/Super Mario Sunshine/metadata.json

The native resolution goop graphics mod for Super Mario Sunshine was missing one of the textures which is used in the intro level.
Before:
And after:

Data: Add missing Super Mario Sunshine goop map texture to graphics mod

---

Source/Core/Core/HW/GCMemcard/GCMemcardUtils.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardUtils.h
Source/Core/DolphinQt/GCMemcardManager.cpp
Source/Core/DolphinQt/GCMemcardManager.h

Generifies bits of the interface so that some functions aren't explicitly tied down to only using std::vector.
While we're in the area, we can tidy up the EnumMap definitions in the GCMemcardManager so that there's no duplication of the constant name over and over.

GCMemcardUtils: Make use of std::span where applicable 

---

Source/Core/Core/Debugger/PPCDebugInterface.cpp
Source/Core/DolphinQt/Settings/BroadbandAdapterSettingsDialog.cpp
Source/Core/InputCommon/ControlReference/ExpressionParser.cpp

I noticed that a few usages of std::regex in the codebase were suboptimal.  I would prefer to make these static const *globals* in their respective compilation units, but that is sometimes hard to sell despite the performance savings.
Also, a lot of std::regex usage comes from baffling design decisions in the debugger parts of Dolphin.  Hopefully in the future I or someone else can rework the debugger to use raw UGeckoInstructions rather than disassembled instructions, but it seems like a huge task.

static const std::regex

---

Source/Core/DolphinQt/Debugger/BreakpointDialog.cpp
Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
Source/Core/DolphinQt/Debugger/CodeDiffDialog.cpp
Source/Core/DolphinQt/Debugger/CodeDiffDialog.h
Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Source/Core/DolphinQt/Debugger/MemoryViewWidget.h

Gets rid of some trivially removable string churn in Update()-related member functions. Most being accidentally passing by value rather than const reference.

Debugger: Remove some trivial string copies

---

Source/Core/Core/PowerPC/ConditionRegister.h

This allows the compiler to eliminate a static constructor that initializes the table, and instead precompute all of the data ahead of time.
e.g. We get something like so on GCC without constexpr:
```asm
_GLOBAL__sub_I_PowerPC::ConditionRegister::s_crTable:
movdqa  xmm0, XMMWORD PTR .LC0[rip]
movaps  XMMWORD PTR PowerPC::ConditionRegister::s_crTable[rip], xmm0
movdqa  xmm0, XMMWORD PTR .LC1[rip]
movaps  XMMWORD PTR PowerPC::ConditionRegister::s_crTable[rip+16], xmm0
movdqa  xmm0, XMMWORD PTR .LC2[rip]
movaps  XMMWORD PTR PowerPC::ConditionRegister::s_crTable[rip+32], xmm0
movdqa  xmm0, XMMWORD PTR .LC3[rip]
movaps  XMMWORD PTR PowerPC::ConditionRegister::s_crTable[rip+48], xmm0
movdqa  xmm0, XMMWORD PTR .LC4[rip]
movaps  XMMWORD PTR PowerPC::ConditionRegister::s_crTable[rip+64], xmm0 …
```

PowerPC/ConditionRegister: Mark PPCToInternal() as constexpr

---

Source/Core/Core/Core.cpp
Source/Core/Core/System.cpp
Source/Core/Core/System.h
Source/Core/InputCommon/DynamicInputTextureManager.cpp
Source/Core/VideoCommon/HiresTextures.cpp
Source/Core/VideoCommon/HiresTextures.h
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

This moves high resolution textures to be loaded as assets by the asset loader system.  This makes the high resolution textures load in an asynchronous manner and also allows for them to be reloaded automatically:
High resolution textures did have some particular behaviors that didn't fit very well in the asset loader system, I've listed them below.
**Change**:  The OSD messages about all textures being loaded was removed.
**Response**:  I know that this message is useful for debugging.  This doesn't make sense for the asset loader though because an asset can be loaded at any time (not just on start up).  My idea is to add an imgui window that lists a count of every asset type loaded.  I haven't done this yet.  If this is a blocker, I can implement it in a separate review before merging …

VideoCommon: migrate texture packs to use the asset loader system

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/ConfigControls/ConfigFloatSlider.cpp
Source/Core/DolphinQt/Config/ConfigControls/ConfigFloatSlider.h
Source/Core/DolphinQt/DolphinQt.vcxproj

Needed by:
https://github.com/dolphin-emu/dolphin/pull/11850
This is almost identical to `ConfigSlider` that was already there, though works with floats instead.
Screenshot:

Qt: Add float config tooltip slider

---

Source/Core/VideoBackends/Metal/MTLMain.mm

macOS 13.3 finally lets us use all our cores when compiling shaders, turn that on
Improves launch time with Compile Shaders Before Starting + Ubershaders
For anyone who wants to test, clear your Metal shader cache with
```sh
rm -r $TMPDIR/../C/org.dolphin-emu.dolphin/com.apple.metal
```

VideoBackends:Metal: Enable shouldMaximizeConcurrentCompilation when available

---

Source/Core/Common/GL/GLInterface/AGL.mm

Fixes a crash introduced by c63f0f37cd84d627dd40ace3205c689efc068ac0 when opening OpenGL settings while a game wasn't running

Common:AGL: Support making temporary contexts from the main thread

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/CustomFilePickerFragment.kt

A very minor bug that became more obvious when this code was translated to Kotlin.

Android: Check file name extensions locale-independently

---

Source/Android/app/build.gradle
Source/Android/app/proguard-rules.pro

Right now the custom drivers work fine in debug builds but don't work in release builds even if both are done by our CI and based off the same code.
@bylaws suggested this as a fix.

Android: Fix Adrenotools in release builds

---

Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.cpp

GetFigureList() is a static member function, so we can just call it directly instead of going through the system instance.

InfinityBaseWindow: Remove unnecessary system instance accessor

---

Source/Core/DolphinQt/QtUtils/ParallelProgressDialog.h

Ensures we always have a deterministic state. While we're in the same area, we can mark `WasCanceled()` as const.

ParallelProgressDialog: Initialize all data members 

---

Source/Core/DiscIO/DiscExtractor.cpp

NKit stores some data in the disc and partition headers.  Since the extracted filesystem format (GCReEx format?) cannot be an NKit format, it makes sense to remove this info.  This will be helpful for a niche scenario in which a user extracts an NKit format ISO using Dolphin, then rebuilds the ISO using either Dolphin (which surprisingly is able to) or a third party tool, as the NKit data being left in will produce false-positives when loading the rebuilt disc in Dolphin Emulator.

Remove NKit data when extracting a GCN/Wii disc volume

---

Source/Core/Common/CMakeLists.txt
Source/Core/Core/CMakeLists.txt
Source/Core/Core/Debugger/DebugInterface.h
Source/Core/Core/Debugger/PPCDebugInterface.h
Source/Core/Core/PowerPC/BreakPoints.cpp
Source/Core/Core/PowerPC/BreakPoints.h
Source/Core/Core/PowerPC/PPCSymbolDB.cpp
Source/Core/Core/PowerPC/PPCSymbolDB.h
Source/Core/DolphinLib.props

The base DebugInterface now depends on the Core's CPUThreadGuard, and utilities in Common shouldn't be depending on Core facilities. So, we can move this into the core library instead.

Common: Move DebugInterface.h into Core

---

Source/Core/VideoCommon/Assets/TextureAsset.cpp

This was a regression from the asset system being used for texture packs.  Apparently, despite the log message, an incorrect texture aspect ratio or having the texture size not being a multiple of the original does not reject the texture from being used.
A user was reporting that they were not able to see some textures or use a dynamic input texture pack because the textures broke one or both of these rules.
Since the errors aren't fatal, I downgraded them to a warning

VideoCommon: don't reject game textures which have the wrong size

---

Data/Sys/GameSettings/GIA.ini

Defer EFB Copies to RAM is necessary in order to avoid white bars obscuring the screen: see [https://wiki.dolphin-emu.org/index.php?title=Ice_Age_2:\_The_Meltdown_(GC)#White_Bars](https://wiki.dolphin-emu.org/index.php?title=Ice_Age_2:_The_Meltdown_(GC)#White_Bars)

Fix white bars in Ice Age 2: The Meltdown (GC)

---

Source/Core/Core/PowerPC/PPCCache.cpp

The pointer is being passed to functions that take arguments as void*, so we don't need to cast here.

PPCCache: Remove redundant reinterpret_casts

---

Source/Core/Common/x64Emitter.cpp
Source/Core/Common/x64Emitter.h
Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitBranch.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitExtOps.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitMultiplier.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitUtil.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Branch.cpp
Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Source/Core/Core/PowerPC/Jit64Common/BlockCache.cpp
Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
Source/Core/Core/PowerPC/Jit64Common/TrampolineCache.cpp
Source/Core/VideoCommon/VertexLoaderX64.cpp
Source/UnitTests/Common/x64EmitterTest.cpp

Replace the bool parameter force5bytes in J, JMP, and J_CC with an enum class. Many callers set that parameter to the literal 'true', which was unclear if you didn't already know what it did.

XEmitter: Add enum class Force5Bytes

---

Source/Core/UICommon/ResourcePack/Manager.cpp
Source/Core/UICommon/ResourcePack/Manager.h

There's nothing going on with behavior here that would prevent these from being const qualified.
Also better communicates that this function isn't intended to modify the given resource pack.

UICommon/ResourcePack: Allow priority helpers to take arguments by const reference

---

Source/Core/DolphinTool/ConvertCommand.cpp
Source/Core/DolphinTool/HeaderCommand.cpp
Source/Core/DolphinTool/ToolMain.cpp
Source/Core/DolphinTool/VerifyCommand.cpp
Source/Core/DolphinTool/VerifyCommand.h

A subset of changes from https://github.com/dolphin-emu/dolphin/pull/11943 which I believe to be most agreeable.

DolphinTool: Sensible changes

---

Source/Core/DolphinTool/ConvertCommand.cpp
Source/Core/DolphinTool/HeaderCommand.cpp
Source/Core/DolphinTool/VerifyCommand.cpp

`const std::string& optparse::Values::operator[](const std::string& d) const` is the tool for the job when working with string args.

DolphinTool: Less string copies

---

Source/Core/DolphinQt/Debugger/NetworkWidget.cpp

In all instances, these variables should be signed rather than unsigned.

Qt/NetworkWidget: Get rid of some trivial sign conversions

---

Source/Core/Common/CMakeLists.txt
Source/Core/Common/EnumUtils.h
Source/Core/Core/DSP/DSPDisassembler.cpp
Source/Core/Core/DSP/Jit/x64/DSPJitRegCache.cpp
Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/ES/Identity.cpp
Source/Core/Core/IOS/ES/TitleManagement.cpp
Source/Core/Core/IOS/FS/FileSystemProxy.cpp
Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/Network/KD/VFF/VFFUtil.cpp
Source/Core/Core/IOS/Network/Socket.h
Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
Source/Core/Core/IOS/WFS/WFSI.cpp
Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.cpp
Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
Source/Core/Core/WiiUtils.cpp
Source/Core/DolphinLib.props
Source/Core/VideoBackends/Vulkan/VKGfx.cpp
Source/Core/VideoCommon/CPMemory.cpp
Source/Core/VideoCommon/NativeVertexFormat.h
Source/Core/VideoCommon/UberShaderCommon.cpp
Source/Core/VideoCommon/UberShaderVertex.cpp

Mirrors the C++23 \<utility\> function, `std::to_underlying`.
This is an extract of changes from https://github.com/dolphin-emu/dolphin/pull/11932.

EnumUtils: Add Common::ToUnderlying

---

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp

Fixes RS2 again, probably among lots of other things. See also #11967.

Jit64: Fix trampolines after #11834.

---

Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.cpp
Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.h

Part D of splitting https://github.com/dolphin-emu/dolphin/pull/11913

DITConfiguration: Use File::ReadFileToString

---

Source/Core/Common/Arm64Emitter.h
Source/Core/Common/x64Emitter.h

This should prevent future occurrences of the type of problem that was fixed in PR #11969.

Arm64Emitter/x64Emitter: Use nodiscard for FixupBranch

---

Source/Core/Common/x64Emitter.cpp
Source/Core/Common/x64Emitter.h
Source/UnitTests/Common/x64EmitterTest.cpp

Title.
I also want to explicitly assign the enum values (_MM_HINT_NTA, etc.); I can throw that in this PR or make a new one if that's worth the effort.

xEmitter: Convert PrefetchLevel to enum class

---

Source/Core/VideoBackends/D3D12/DX12Pipeline.cpp

This was an oversight caused by my multi-output texture change.  This code was pulled from an older PR, I can't say why I did it this way.  Maybe multiple logic ops RTs are invalid or maybe it was that it would negatively impact users due to the integer format required? (am i remembering right?)  Anyway, this fixes a validation error that causes d3d12 to crash with the error:
> ERROR: ID3D12Device::CreateGraphicsPipelineState: The render target format at slot 0 is format (R8G8B8A8_UNORM).  This format does not support logic ops. The Pixel Shader output signature indicates this output could be written, and the Blend State indicates logic op is enabled for this slot.
When I get to using multiple-output textures, I will revisit

VideoBackends: fix d3d12 error when validation layers enabled

---

Source/Core/AudioCommon/WaveFile.cpp
Source/Core/Common/Debug/Watches.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/InputCommon/ControllerInterface/CoreDevice.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp
Source/Core/UICommon/UICommon.cpp

Part C of splitting https://github.com/dolphin-emu/dolphin/pull/11913

Replace std::ostringstream usage with fmt::format

---

Source/Android/jni/CMakeLists.txt
Source/Android/jni/Config/NativeConfig.cpp
Source/Android/jni/Host.cpp
Source/Android/jni/Host.h
Source/Android/jni/MainAndroid.cpp
Source/Core/Core/Core.cpp

Not sure if I caught everything that needs a host lock, but at least now emulation and settings work with the host thread check enabled.

Android: Re-add host thread check

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
Source/Android/jni/MainAndroid.cpp

Fixes a weird problem encountered in certain custom ROMs where the getExternalCacheDir method occasionally returns a null value.

Use getCacheDir if getExternalCacheDir returns null.

---

Source/Core/Common/SymbolDB.h

This saves ~25% of warnings on Ubuntu / GCC 11.
```
../Source/Core/Common/SymbolDB.h:41:38: warning: declaration of ‘name’ shadows a member of ‘Common::Symbol’ [-Wshadow]
41 |   explicit Symbol(const std::string& name) { Rename(name); }
|                   ~~~~~~~~~~~~~~~~~~~^~~~
../Source/Core/Common/SymbolDB.h:45:15: note: shadowed declaration is here
45 |   std::string name;
|               ^~~~
```
```bash
$ git checkout 27db8d4123
$ cmake . -G Ninja -B build/vanilla -DLINUX_LOCAL_DEV=true
$ cmake --build build/vanilla 2>&1 | grep ": warning:" | wc -l
273
$ git checkout 4ef2f2c710
$ cmake . -G Ninja -B build/patch -DLINUX_LOCAL_DEV=true
$ cmake --build build/patch 2>&1 | grep ": warning:" | wc -l
204
```

Minor fix: Rename Symbol constructor parameter to prevent shadowing

---

Source/Core/Core/IOS/Network/KD/NetKDTime.cpp

DST was not taken into account when generating the timestamp, which would cause the timestamp returned to be an hour ahead when observing DST.
This fixes the Forecast and News Channels' `FORE/NEWS00000006` error as the file would be expired upon downloading.

IOS/KD/Time: Take into account DST for AdjustedUTC

---

Source/Android/jni/MainAndroid.cpp

Another instance of the host thread check failing.

Android: Declare host thread when generating analytics ID

---

Source/Core/Core/Core.cpp

Fixing all the places it's used turned out to be a more complicated task than anticipated. So let's remove this for now so we don't confuse users with cryptic error messages...
(Seriously, I've been trying to fix the Wiimote Scanning Thread to comply with this for multiple days now and I cannot find a good solution for it.)
To be clear, I still think this should be fixed, but it's not great to annoy users with a popup whenever they want to use Wiimotes in the meantime.

Core: Remove host thread assert in PauseAndLock().

---

Source/Core/VideoCommon/Assets/CustomAsset.h
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

VideoCommon: move cached texture asset to 'CustomAsset' common code

---

Source/Core/Common/NandPaths.cpp
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/Debugger/PPCDebugInterface.cpp

Now superseded by Common::FromChars

Kill AsciiToHex

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt

Don't allow changing it per game because we can only install one driver. Also don't allow changing it while in-game.

Android: Remove GPU driver from per-game settings

---

Source/Core/DolphinQt/SkylanderPortal/SkylanderPortalWindow.cpp

Also changed the spelling of "Superchargers" to "SuperChargers".

DolphinQt: Add i18n comments for Skylanders strings

---

Source/Core/DolphinQt/Config/Graphics/ColorCorrectionConfigWindow.cpp

Trying to translate an empty string will return a long metadata string for the loaded translation file rather than the expected empty string.

DolphinQt: Don't translate empty strings

---

Data/Sys/GameSettings/HAF.ini
Data/Sys/GameSettings/HAT.ini
Data/Sys/GameSettings/HATE01.ini
Data/Sys/GameSettings/HATJ01.ini
Data/Sys/GameSettings/HATP01.ini

We only use six-character INIs for settings that have to be set on a per-version basis.

GameSettings: Restore HAT.ini

---

Source/Core/Common/Align.h

Small optimization to `AlignUp`, [optimizers did not like the old one](https://gcc.godbolt.org/z/e3YxhreMd)
Saves ~1 instruction, except on clang where it saves ~4 instructions

Common: Better AlignUp implementation

---

Source/Core/DolphinQt/Config/Graphics/PostProcessingConfigWindow.cpp

1 ) When first opened, the (user selected) post process shader config widget would print the wrong values on the text label next to int range sliders. For example if the range was from 1 to 6, and the value loaded from the config was 1, the label would print 0 when first opened, to then start showing the correct value once the slider was first moved.
This mirrors the behaviour of the float slider code below:
```auto* const value_box = new QLineEdit(QString::asprintf("%f", m_config_option->m_float_values[i]));```
2 ) The defautl int slider value would also be set wrong on first load, as it was being divided by the slider max instead of the slider step amount (again, just like for the float implementation). This is a mistake I had made with my previous submission.

Qt: Fix some Post Process Configuration Widget issues #3-4

---

Source/Core/Core/HW/WiimoteReal/IOWin.cpp

I'm getting an `S_FALSE` here every couple seconds on Windows, which is not an error and thus triggers an assert in `winrt::hresult_error`. I have no idea what this means -- I can't find any documentation on what `S_FALSE` from `WriteFile()` means -- but it seems to not actually cause problems...?
e: Further debugging this, this is actually caused by my keyboard of all things. I guess it tries to figure out if my keyboard is a bluetooth device...? I'm surprised there isn't a better way for that.

WiimoteReal/IOWin: Don't try to print error message for non-errors.

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

We can utilize the fact that if swapping two instructions causes another swap to become possible, that swap involves one of the two instructions we just swapped. There's need to search for new swap opportunities as far back as the beginning of the block; we can just go one step back.

PPCAnalyst: Reduce number of iterations in ReorderInstructionsCore

---

Data/Sys/Load/GraphicMods/Skylanders Spyro's Adventure/metadata.json

With all these Portal additions, this was kinda missing...
Tested on the American version of the game (SSPE52).
Before (6x resolution)
Native resolution bloom
Bloom removal

Add Bloom Definitions for Skylanders: Spyro's Adventure

---

Source/Core/Common/GekkoDisassembler.cpp
Source/Core/Common/GekkoDisassembler.h

m_type is written to in several places but never read, and so serves no purpose.

GekkoDisassembler: Remove unread variable and associated enum

---

Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

VideoCommon: allow multiple texture assets to associate with a texture cache entry

---

Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VertexShaderManager.cpp

Noticed this when looking over my texture create callback.  The graphics mod iteration was actually copying each action.  Granted just a pointer so probably negligible but still worth fixing I think!

VideoCommon: don't do pointer copies during graphics mod callback iteration

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.h
Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementProgressWidget.h
Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
Source/Core/DolphinQt/Achievements/AchievementsWindow.h
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, I add an AchievementsProgressWidget and an AchievementsHeaderWidget to be added to AchievementsWindow, for the player to view data about their current progress and points.

RetroAchievements - Achievement Progress Tab

---

Source/Core/DolphinLib.props
Source/Core/VideoCommon/Assets/CustomAssetLibrary.h
Source/Core/VideoCommon/Assets/CustomAssetLoader.cpp
Source/Core/VideoCommon/Assets/CustomAssetLoader.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.h
Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/Assets/ShaderAsset.h
Source/Core/VideoCommon/CMakeLists.txt

Here's an asset that describes a pixel shader.  I've based my design somewhat off of _Unity_ game engine but I believe other modern graphics renders follow something somewhat similar.
This shader asset contains the shader code for the shader itself, as well as a description of the inputs which match what we want to expose from the shader code.  The inputs are just the type (and eventually the default data value), not the actual data that is being held.  This makes these assets highly reusable.  At the moment, I've only exposed a 2D texture sampler type.  But in the future there will be uniform support for colors/integers/etc and likely will also include inputs for cube-maps, 3d textures, and named render targets.
With the data type defined, where does the actual data come from?  That is …

VideoCommon: add a pixel shader asset

---

Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionData.h
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

Previously, we defined our graphics mod callback for texture creates.  Now we can call into it.
A texture create is passed the texture name and the texture width/height as input.  As output it provides a list of additional textures to load and an additional list of dependencies that might influence that list of textures  (ex: a config file that says how many textures to load).

VideoCommon: call into graphics mods create texture callback

---

Source/Core/Core/HW/SI/SI.cpp
Source/Core/Core/HW/SI/SI.h
Source/Core/Core/HW/SI/SI_DeviceGCController.cpp
Source/Core/Core/HW/SI/SI_DeviceGCController.h

By misusing Config, this netplay-related code opened up a race condition between Config::OnConfigChanged() and SerialInterface::SerialInterfaceManager::UpdateDevices() that could cause iterator invalidation.

Fix unsafe netplay code in SI_DeviceGCController

---

Source/Core/DolphinLib.props
Source/Core/VideoCommon/Assets/CustomAssetLibrary.h
Source/Core/VideoCommon/Assets/CustomAssetLoader.cpp
Source/Core/VideoCommon/Assets/CustomAssetLoader.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.h
Source/Core/VideoCommon/Assets/MaterialAsset.cpp
Source/Core/VideoCommon/Assets/MaterialAsset.h
Source/Core/VideoCommon/CMakeLists.txt

This is the last of my asset reviews (for now!).  This adds a material asset for pixel shaders.  As I mentioned in my shader asset review, a material provides the data for a shader.  Any shader input _values_ will be in the material asset.  This makes shaders reusable.  Ex: you can have a single shader that might draw an outline around an object with an exposed color, one material that says to make the outline red and another that says to make the outline blue.
At the moment, materials are very simple.  The only input is a named texture asset.  In the future, materials will also handle other forms of data (color, integers, booleans, etc) that will be passed to the runtime shader as uniforms.
In the short term, this will be used by the revamped #11300 .

VideoCommon: add material asset

---

Source/Core/VideoBackends/D3D/D3DMain.cpp

Dolphin no longer supports Windows 7, so the fact that there are (were?) more people who use Windows 7 than who use a GPU that doesn't support the required feature is no longer relevant.

D3D: Remove Windows 7 mention in logic ops warning

---

Readme.md

Not doing so results in the following error :
CMake Error at Externals/cubeb/CMakeLists.txt:30 (message):
Could not find sanitizers-cmake: run
git submodule update --init --recursive
in base git checkout
As the advice is correct, update readme with the correct command.

readme: Add '--recursive' to git submodule command

---

Source/Core/Common/CommonFuncs.cpp
Source/Core/Common/CommonFuncs.h
Source/Core/Common/Network.cpp

This PR is an alternative approach to https://github.com/dolphin-emu/dolphin/pull/12037 which tries to fix a compilation issue related to `strerror_r`.
@AnErrupTion
Does this approach fix your compilation issue on musl libc?

Common: Add a strerror_r wrapper

---

CMakeLists.txt

Should be self explanatory.
Allows for using shared zlib-ng if found by pkgconfig, similar to how zstd works.

Allow shared zlib-ng

---

Source/Core/DolphinQt/Config/Graphics/ColorCorrectionConfigWindow.cpp
Source/Core/DolphinQt/Config/Graphics/ColorCorrectionConfigWindow.h

This PR contains a collection of improvements and fixes for the Color Correction window, originally introduced in PR #11850:
* Restored default padding around the widgets
* Made the window resizable and made sure it doesn't fall apart during resizing
* Trimmed/Removed unnecessary fractional part of float numbers where applicable (visual only, they still have the same precision code side)
* Converted "SDR Display Gamma sRGB" checkbox and "SDR Display Custom Gamma" slider into a secondary group box with radio buttons to more explicitly show the relation between the two
* Various tooltip fixes
* Added missing title to "Game Gamma" tooltip and mentioned default value in the tooltip description
* Added tooltip to "HDR Paper White Nits" slider
* Removed unnecessary line breaks where applicable …

Qt: Color Correction window fixes

---

Source/Core/VideoCommon/Assets/CustomAsset.h

FreeBSD compiler was complaining about my usage of the defaulted copy/move constructor in `CustomAsset` (for good reason!).  This should silence those warnings.

VideoCommon: fix some compiler warnings for CustomAsset

---

Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp
Source/Core/InputCommon/GCAdapter.cpp

https://bugs.dolphin-emu.org/issues/13284
After sleep-wake on Linux, talking to the GC USB adapter fails with `LIBUSB_ERROR_IO` because the kernel driver regains ownership over the adapter device. Previously Dolphin would continually try talking to the adapter in an infinite loop, burning a full CPU core and failing to receive new input from the adapter.
The minimal solution is to `libusb_detach_kernel_driver()` the adapter again, but I've been told that the best approach to handling `LIBUSB_ERROR_IO` is to instead call `libusb_reset_device` and reinitialize the device. This PR calls `libusb_reset_device` when the system sleep-wakes and talking to the GC adapter returns `LIBUSB_ERROR_IO`.
Another bug I found:
- If you launch Dolphin with all GC controllers set to not Adapter, then pick …

Fix GC Adapter breaking and burning a full CPU core after sleep-wake on Linux

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
Source/Android/app/src/main/res/values/strings.xml

Adds the `Enable WiiConnect24 via WiiLink` checkbox. Allows for the onboard WiiLink patches to function if enabled.

Add Enable WiiLink checkbox to Android GUI

---

Source/Core/VideoCommon/HiresTextures.cpp

After designing the new asset loading system and integrating it to work with custom textures in #11681 , I had to remove the OSD message that came when textures were loaded.  This had the side effect of making it hard for our support staff to diagnose if a user had custom textures installed correctly.
I knew this would be an issue but didn't see a way around it.  The asset system can constantly load assets, either at startup or other times.  How do we know we're done?  We don't.
But then it came to me, do we need to know that?  No!  Users just want to know if things are installed properly.  A simple message when building up the asset list (either the list directly handed to the asset system or the list of assets to watch for during the course of the game) will suffice.
And that's exactly …

VideoCommon: add startup message to know if custom textures are installed

---

Source/Core/AudioCommon/CubebUtils.cpp

To avoid conflicts with KDE's file manager.
Before:
After:

cubeb: Change name to "Dolphin Emulator"

---

Source/Core/Core/IOS/USB/Emulated/Skylander.cpp

I initially thought the 0x01 side was both sides (equavalent to just C. However, this turned out to be something I forgot I implemented in my personal interface. 0x01 does not seem to change any colors. Handling of 0x01 in SetLEDs maintained because it's still used for the implementation of the C command
Recently discovered how exactly the last 2 bytes of the J command for timing data.

Skylanders: Update J command documentation

---

Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

A user on the forums pointed this out.  Previously, we were still dumping textures for games if the custom texture hadn't asynchronously loaded yet.

VideoCommon: skip the texture dump if a custom texture is available, regardless if it is loaded or not

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp

I am not sure what bugs this mistake may cause, but it seems like a mistake to me.

Announce RSCRATCH clobbering in Jit64::Cleanup() when profiling is enabled

---

Source/Core/Core/CoreTiming.cpp
Source/Core/Core/CoreTiming.h

This might save a bit of perf during the main loop and also potentially improves the design a bit for achievements.

Core: save core timing parameters into variables updated during refresh

---

Source/Core/DolphinQt/Settings/InterfacePane.cpp

This will hopefully reduce confusion on e.g. https://bugs.dolphin-emu.org/issues/13306.

Rename "Show Debugging UI" to "Enable Debugging UI"

---

Source/Core/Common/TraversalServer.cpp

Fixed a bug where in the extremely unlikely change that HostIDs collide, a new HostID is generated to be used. I'm not sure what the full impact would be if there was a collision, but I imagine it'd be stuck in this while loop until the HostID that collided got old enough to be reused. So 30s + however long the code is refreshed for.

[Minor Bugfix]  Extremely rare HostID collision bugfix

---

Source/UnitTests/Core/IOS/FS/FileSystemTest.cpp

Noticed this while working on something else. This should work correctly as of #11711.

UnitTests: Enable cluster check in FileSystemTest.GetDirectoryStats.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.kt

`or` is the bitwise or operator.
Fixes file pickers in the settings not saving your choice.

Android: Fix SettingsActivity.onActivityResult

---

Source/Core/Common/GekkoDisassembler.cpp
Source/Core/Common/GekkoDisassembler.h

GekkoDisassember.m_flags is written to but never read, so it can be removed.
With the removal of m_flags the dmode parameter is no longer used in functions nooper, dab, rrn, ldst, and fdabc, so remove it from them.

GekkoDisassembler: Remove unused member and parameters

---

Externals/imgui/CMakeLists.txt
Externals/imgui/imconfig.h
Externals/imgui/imgui.cpp
Externals/imgui/imgui.h
Externals/imgui/imgui.vcxproj
Externals/imgui/imgui_demo.cpp
Externals/imgui/imgui_draw.cpp
Externals/imgui/imgui_internal.h
Externals/imgui/imgui_tables.cpp
Externals/imgui/imgui_widgets.cpp
Externals/imgui/imstb_rectpack.h
Externals/imgui/imstb_textedit.h
Externals/imgui/imstb_truetype.h
Externals/imgui/misc/README.txt
Externals/imgui/misc/cpp/README.txt
Externals/imgui/misc/cpp/imgui_stdlib.cpp
Externals/imgui/misc/cpp/imgui_stdlib.h
Source/Core/VideoCommon/OnScreenUI.cpp
Source/Core/VideoCommon/OnScreenUI.h

This updates imgui to its latest release 1.89.7 and due to breaking changes updates implot to 0.15.
Updating broke our handoff of the IO from QT to ImGui.  This review also fixes that and moves us to use `AddKeyEvent` which is the new recommended way of handling key events.
Finally, I included `imgui_demo.cpp` as it is pretty handy to be able to see all the demo controls working when doing development.  It is left out of compilation with `IMGUI_DISABLE_DEMO_WINDOWS` but can be enabled if someone wants to reference it.

Externals / VideoCommon: update imgui to 1.89.7 (and implot to 0.15)

---

Source/Core/VideoCommon/NetPlayChatUI.cpp

After updating imgui in #12065 , looks like I broke the netplay chat window.  A user on discord reported the following error:
This PR fixes that by using a hidden label for the `InputText` field.

VideoCommon: update NetplayChatUI's chat message to avoid imgui error

---

Source/Core/Common/CommonFuncs.cpp
Source/Core/Common/CommonFuncs.h
Source/Core/Core/HW/WiimoteReal/IOWin.cpp

See https://github.com/dolphin-emu/dolphin/pull/11978#issuecomment-1619856382

WiimoteReal/IOWin: Use correct error type in the default case.

---

Source/Core/Core/IOS/FS/FileSystem.h
Source/Core/Core/IOS/FS/HostBackend/FS.cpp
Source/Core/Core/IOS/FS/HostBackend/FS.h
Source/Core/Core/WiiUtils.cpp
Source/Core/Core/WiiUtils.h
Source/Core/DolphinQt/MenuBar.cpp

This adds stats to the NAND Check feature that tell you how much of your NAND is used, and if it is overfilled.
I'm not 100% happy about the way this is presented, maybe someone has a good idea here. It would also be nice if we had actual options to safely delete stuff in case it's overfull, without having the user manually go to the NAND directory and deleting stuff there..

Add file size stats to NAND Check.

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp

The Cortex-X2 and Cortex-X3 (and possibly others) recognize MOVI with 64-bit elements as a zeroing idiom, but not MOVI with other sizes.

JitArm64: Prefer MOVI with 64-bit elements for zeroing

---

Source/Core/VideoBackends/D3D12/DX12Texture.cpp
Source/Core/VideoBackends/D3D12/DX12Texture.h

Verify that DXFramebuffer's integer RTV descriptor's cpu_handle has been allocated before using it, and if it hasn't use the non-integer RTV descriptor instead. This fixes a Dolphin crash in Twilight Princess, and possibly other games (Issue [13312](https://bugs.dolphin-emu.org/issues/13312)).
As an optimization to save space in the descriptor heap, DXFramebuffer's integer descriptor is only initialized if the given abstract texture format has different integer and non-integer RTV formats. This previously wasn't accounted for by GetIntRTVDescriptorArray, which could cause DX12::Gfx::BindFramebuffer to call OMSetRenderTargets with an invalid descriptor which would lead to a crash.
Triggering the bug was fortunately rare because integer formats are only used when blending is disabled and …

D3D12: Only use framebuffer integer descriptor if allocated

---

Source/Core/Core/ConfigLoaders/BaseConfigLoader.cpp

When WiiConnect24 Standby is enabled, we would disabled it upon shutdown because 
> If it is enabled, it prevents us from receiving shutdown commands in the State Transition Manager (STM)
which would cause the emulator to hang on shutdown.
Upon removing the lines of code, it shuts down gracefully as far as I can tell. Please test.

Remove force disable WC24 Standby

---

Source/Core/VideoCommon/HiresTextures.cpp

A user using a dynamic input texture pack notified me to let me know that the DIT texture pack's button textures were not taking precedence over another pack.  The reasoning for this is that when I [switched over texture packs to use the asset loader](https://github.com/dolphin-emu/dolphin/pull/11681), I accidentally updated the asset map with the latest texture asset, instead of choosing the initial value.  This caused the ordering of precedence for texture packs to be reversed, which caused the issue.

VideoCommon: fix regression with texture load order

---

Source/Core/DolphinQt/GameList/GameList.cpp

This PR fixes an issue with export wii save files that is detailed [here](https://bugs.dolphin-emu.org/issues/13216).
Trying to export a wii save while emulation is running creates some error messages and then appears to export the wii save normally but these are options that, in the previous UI of dolphin, were disabled during emulation.

Disable Wii Save Options When Emulation Is Running

---

Source/Core/VideoCommon/AbstractFramebuffer.h

Move the declaration of m_additional_color_attachments so its initialization order matches that of the constructor.
This was the simplest way to fix the warning, but if someone wants to argue the declaration should be somewhere else I could reorder the constructor initializers instead.

AbstractFramebuffer: Fix Android reorder-ctor warning

---

Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MainWindow.h

Before, right-clicking on the toolbar would allow toggling all dock widgets, including the debugger ones even when they are disabled. (See https://doc.qt.io/qt-5/qmainwindow.html#createPopupMenu for this behavior, and https://bugs.dolphin-emu.org/issues/13306 for an example of where it caused issues.)

Disable right-click menu on main window

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

ARM64 has a special logical immediate encoding scheme, that can be used with `AND`, `ORR`, and `EOR`. By taking advantage of this, we no longer need to materialize the immediate value in a register, saving instructions and/or reducing register pressure.
---
<details><summary>andx</summary>
Before:
```
mov    w26, #-0x80000000
and    w27, w27, w26
sxtw   x24, w27
```
After:
```
and    w27, w27, #0x80000000
sxtw   x26, w27
```
</details>
<details><summary>orx</summary>
Before:
```
mov    w23, #0x1
orr    w23, w25, w23
```
After:
```
orr    w23, w25, #0x1
```
</details>
<details><summary>norx</summary>
Before:
```
mov    w25, #-0x2001
orr    w23, w23, w25
mvn    w23, w23
```
After:
```
orr    w23, w23, #0xffffdfff
mvn    w23, w23
```
</details>
<details><summary>xorx</summary>
Before:
``` …
```

JitArm64: Use LogicalImm in boolX

---

Source/Core/Core/Core.cpp

SD resync failure happens from time to time (e.g. if the folder is open in another program), and usually results in data loss due to it being largely invisible to the end-user until reboot. This PR adds a dialog box to notify the user that such an event has happened, and how to fix it before it is too late.

Prevent SD data loss from silent resync failure

---

Source/Core/InputCommon/GCAdapter.cpp

CONTROLLER_OUTPUT_INIT_PAYLOAD_SIZE is only used by the libusb implementation, so put the appropriate ifdefs around it.
Also fixes the spelling of some constants while I'm there.

Gcadapter: fix Android unused constant warning

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/ToolTipControls/ToolTipPushButton.cpp
Source/Core/DolphinQt/Config/ToolTipControls/ToolTipPushButton.h
Source/Core/DolphinQt/DolphinQt.vcxproj

I noticed the 'Configure' button for Color Correction doesn't use our fancy tooltips and when I went to add it I realized we didn't have a class for that. So here it is.

DolphinQt: Add ToolTipPushButton.

---

Source/Core/InputCommon/ControllerInterface/Android/Android.cpp

The Google Play Console is showing some users getting a crash here, and indeed, InputDevice.getDevice can return null.

ControllerInterface/Android: Add null check to AddDevice

---

Source/Core/Common/NandPaths.cpp

Android interprets char as unsigned char, so comparing the char parameter in IsIllegalCharacter with 0 triggers a tautological-unsigned-char-zero-compare warning.
Casting the parameter to an unsigned char and removing the comparison with 0 resolves the warning while needing one less comparison on all platforms.

NandPaths: Resolve Android tautological comparison warning

---

Source/Core/VideoBackends/D3D12/D3D12Gfx.cpp

Pulled from #11783 an oversight from the original change where we switched over to using a constant ( #11550 )

VideoBackends: update SRVDescriptorTable size in DX12 to use pixel sampler constant

---

Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/MMU.h

Thanks to @mkwcat for identifying the problematic code.

Retrieve page table information from the data cache

---

Source/Core/VideoCommon/Assets/CustomAssetLibrary.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp

This allows me to fabricate times (without creating a file) in a future feature.
Unfortunately, only windows (VS) supports `clock_cast` which is needed to convert file times to a system clock.  I have implemented an approximation for other systems.  Users on Linux/Mac/Android would need to test texture packs to make sure this doesn't break existing behavior (in particular the auto reloading which is used for Dynamic Input Textures).

VideoCommon: asset load time is now stored as a chrono system_clock time

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java

You're not allowed to just show toasts on any thread you want.

Android: Move DirectoryInitialization toast to UI thread

---

Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h

It looks slightly weird here and I'm not sure why, it seems like our tooltip doesn't handle the bottom spacing correctly when the tooltip is so short?

DolphinQt/EnhancementsWidget: Use custom tooltip for Color Correction button.

---

Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/Core/PowerPC/PowerPC.h
Source/Core/DolphinQt/Settings/AdvancedPane.cpp
Source/Core/DolphinQt/Settings/AdvancedPane.h

- Use fancy tooltips for MMU, Pause on Panic, and Write-back Cache.
- Bold the three above mentioned settings when they are overridden by GameINI.
- The RAM Override and RTC Override checkboxes now correctly check themselves when overridden by GameINI.
Before:
After:

DolphinQt/AdvancedPane: UI improvements.

---

Data/Sys/Shaders/AutoHDR.glsl
Source/Core/Core/Config/GraphicsSettings.h

Follow up to:
https://github.com/dolphin-emu/dolphin/pull/11850
This is based on my AutoHDR ReShade shader (https://github.com/Filoppi/PumboAutoHDR/tree/master), which has been developed as an alternative to SpecialK HDR and Windows 11 HDR. For the purpose of Dolphin, I simplified it a lot and only kept the most popular AutoHDR algorithm.
Screenshots are HDR (you can't see the difference in SDR screenshots):
[AutoHDR comaprison 1.zip](https://github.com/dolphin-emu/dolphin/files/11888114/AutoHDR.comaprison.1.zip)
[AutoHDR comaprison 2.zip](https://github.com/dolphin-emu/dolphin/files/11888117/AutoHDR.comaprison.2.zip)
[AutoHDR comaprison 3.zip](https://github.com/dolphin-emu/dolphin/files/11888118/AutoHDR.comaprison.3.zip)
I wouldn't say it's mind blowing, it's not magic, but if you have …

Add AutoHDR post process shader

---

Source/Core/DolphinQt/Config/LogWidget.cpp

This got broken by c2e29153e9e1e831f4b29bbc7e19ebf39d18bc79, though I don't really understand why.

DolphinQt/LogWidget: Restore log window colors.

---

Source/Core/InputCommon/InputConfig.cpp

This only matters for analytics, but still.

InputConfig: Update IsControllerControlledByGamepadDevice for Android input overhaul

---

Source/Core/Core/NetPlayServer.cpp

using portmapping with hosting while using traversal server (which is possible by checking the option while under "direct connect" and flipping back to traversal server) causes dolphin to request a mapping to external port 0.
In UPnP a mapping to external port 0 is actually the wildcard, which means that connection requests on all external ports (that are not otherwise mapped) will be forwarded to the client.
Additionally it seems like using port mapping with traversal server is probably not expected behavior, as the option checkbox disappears when traversal server is used.

Do not try portmapping when using traversal server

---

Source/Core/DolphinQt/TAS/TASInputWindow.cpp

From #12072, no reply to suggested change.

DolphinQt/TASInputWindow: Make 'Enable Controller Input' translatable.

---

Source/Core/Core/Core.cpp
Source/Core/Core/HW/EXI/EXI.cpp
Source/Core/Core/HW/EXI/EXI.h
Source/Core/Core/HW/EXI/EXI_Channel.cpp
Source/Core/Core/HW/EXI/EXI_Channel.h
Source/Core/Core/HW/EXI/EXI_Device.cpp
Source/Core/Core/HW/EXI/EXI_Device.h

The ExpansionInterfaceManager::PauseAndLock function does nothing but call other functions that have no effect.
ExpansionInterfaceManager::PauseAndLock calls CEXIChannel::PauseAndLock, which in turn calls IEXIDevice::PauseAndLock. None of the classes deriving from IEXIDevice override PauseAndLock, and the implementation in IEXIDevice does nothing.

EXI: Remove pointless PauseAndLock functions

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Branch.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/JitInterface.h
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/Core/PowerPC/PowerPC.h

Not sure if this is worth the time, but i made it so here we go.
Basically turns the membase switch into a single instruction (except when msr changes, then it's more).

Jit: Load the memory register only when the msr bits have changed and do not use jumps to load it.

---

Source/Core/Core/PowerPC/Jit64/JitAsm.cpp

`m_jit.EmitUpdateMembase();` would emit the code into a different region of memory, so the register wasn't updated correctly.
Should fix https://bugs.dolphin-emu.org/issues/13336

Jit64: Actually update membase register after GlobalAdvance().

---

Source/Core/Core/HLE/HLE_OS.cpp
Source/Core/Core/HLE/HLE_OS.h
Source/Core/Core/HLE/HLE_VarArgs.cpp
Source/Core/Core/HLE/HLE_VarArgs.h
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/MMU.h

This is incomplete and not tested, I just was reminded that I had this. I may or may not come back to this, someone else is free to take this over if they want...
For reference, I'm unsure of the exact circumstances, but I *have* seen Dolphin crash from a game invoking a HLE-hooked `printf()`, which is what triggered me going down this path.

HLE_OS: Manually handle printfs from emulated software to prevent emulated software from crashing Dolphin with an invalid printf formatting string.

---

Source/UnitTests/Common/x64EmitterTest.cpp

Add some missing x64Emitter unit tests.

x64EmitterTest: add J/J_CC/CALL unit tests

---

Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModAsset.cpp

This was in #12040 but not in #11300 and probably should be there.

VideoCommon/GraphicsModAsset: Error out if config key is not a string.

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/CMakeLists.txt
Source/Core/Common/SmallVector.h
Source/Core/DolphinLib.props
Source/Core/VideoCommon/BPFunctions.cpp

We had one implementation of this type of data structure in Arm64Emitter and one in VideoCommon. This moves the Arm64Emitter implementation to its own file and adds begin and end functions to it, so that VideoCommon can use it.
You may notice that the license header for the new file is CC0. I wrote the Arm64Emitter implementation of SmallVector, so this should be no problem.

Move SmallVector to Common

---

Source/Core/Common/FloatUtils.h

Resolve warning caused by using values from two different enums in a conditional expression which was deprecated in c++20.
The warning is -Wdeprecated-anon-enum-enum-conversion in clang and -Wenum-compare in gcc.
An alternate resolution would be to convert the anonymous enums into static constexpr variables, but I'm not sure if the enums are leftovers from earlier c++ versions or if there's still a good reason to have them.

JitArm64: Resolve deprecated enum conversion warning

---

Source/Core/Core/PowerPC/Jit64Common/Jit64PowerPCState.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h

Modify PPCSTATE_OFF and PPCSTATE_OFF_ARRAY macros when using GCC to avoid useless log spam. Specifically, use a consteval lambda with gcc _Pragma statements to disable the -Winvalid-offsetof warning inside the macros.
Each successful build (and many failing ones) on the Android buildbot generates almost 300 cases of -Winvalid-offsetof, resulting in thousands of lines of log spam per build. In addition to bloating the log filesize these spurious warnings make it harder to find actual warnings.
These warnings are generated by calls to the macros PPCSTATE_OFF and PPCSTATE_OFF_ARRAY, which in turn are used by many other macros used by the JIT. The ultimate cause is that offsetof is only conditionally supported on non-standard-layout types, which includes the PowerPCState struct.
To address …

GCC: Suppress PPCSTATE_OFF invalid-offsetof warnings

---

Source/Core/DiscIO/DiscScrubber.cpp
Source/Core/DiscIO/DiscScrubber.h
Source/Core/DiscIO/ScrubbedBlob.cpp
Source/Core/DiscIO/VolumeVerifier.cpp

Keeping the pointer creates use-after-free opportunities, and we don't have much reason to keep it around anyway.
This solves a problem in the unmerged PR #12036.

DiscIO: Don't keep volume pointer in DiscScrubber

---

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp

This PR fixes some ASCII characters not being drawn properly on the memory view.
Without this PR, underscores aren't drawn on my system. Removing the `-1` from `(m_font_vspace - 1)` fixes the underscore issue. However, it was drawn under the table cell's border and couldn't be seen unless I changed the address and move the cursor elsewhere. Adding 1~2 (pixels?) allows the underscore character to be drawn right above the cell border but without spacing between it. That's why I added an extra 2 (i.e. 4 in total) to have at least a bit of spacing between the underscore and the cell's (dotted) border.
Before this PR:
This PR:
I'm open to suggestions if you've better ways to address this.

MemoryViewWidget: Fix some characters being truncated

---

Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/Core/IOS/ES/Formats.h

Remove unused member variable m_fs_core from SharedContentMap and UIDSys to resolve unused-private-field warnings on Android.

IOS: Remove unused member variable from SharedContentMap and UIDSys

---

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64Common/BlockCache.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.h
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.h
Source/Core/Core/PowerPC/JitInterface.cpp

Jumping between linked blocks currently works as follows: First, at the end of the first block, we check if the downcount is greater than zero. If it is, we jump to the `normalEntry` of the block. So far so good. But if the downcount wasn't greater than zero, we jump to the `checkedEntry` of the block, which checks the downcount *again* and then jumps to `do_timing` if it's less than zero (which seems like an off by one error – Jit64 doesn't do anything like this). This second check is rather redundant. Let's jump to `do_timing` where we previously jumped to `checkedEntry`.
Jit64 doesn't check the downcount on block entry. See PR #7634.

JitArm64: Never check downcount on block entry

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp

Makes the generated code slightly less redundant in some cases.

JitArm64: Avoid loading compilerPC multiple times if it's already in a register.

---

Source/Core/DolphinQt/HotkeyScheduler.cpp

Because CPU thread config changed callbacks are no longer instant, `g_Config.iEFBScale` doesn't yet contain the new value when the hotkey OSD code tries to read it.
Should fix https://bugs.dolphin-emu.org/issues/13343.

Use latest resolution value for resolution hotkey OSD

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableButton.kt
Source/Android/app/src/main/res/menu/menu_overlay_controls_gc.xml
Source/Android/app/src/main/res/menu/menu_overlay_controls_wii.xml
Source/Android/app/src/main/res/values/arrays.xml
Source/Android/app/src/main/res/values/strings.xml

Added latching buttons, buttons which turn on when you press them and off when you press them again.
This is necessary to play games which require you to press more than 2 buttons at once.

Added latching buttons (Android)

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h

Refactored the message displayed when a leaderboard is submitted to so that it properly generates and uses a FormattedValue.

RetroAchievements - Fixed Leaderboard Scored message format

---

Source/Core/VideoCommon/Present.cpp
Source/Core/VideoCommon/Present.h

- There was always a black line around one of the 4 edges (top/left/bottom/right) of the window because the final output size wasn't calculated right (unless the aspect ratio was set to stretch)
- The `Auto-Adjust Window Size` setting was calculating the window size based on the resolution of the window in the previous frame if we used the "stretch" aspect ratio setting, so it's result would be self influence in a loop and behave unreliably (e.g. when changing resolution between Auto/Native/2x the automatic window scaling would behave randomly)
- The `Auto` internal resolution scaling wasn't working correctly if the window weird aspect ratios (e.g. 32:9), beacuse it would account for the the portion of the image that will show black bars into the calcuations to find the best matching …

Video: Fix issues with the window presentation

---

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/DolphinQt/MenuBar.cpp

This fixes a problem where changing the JIT debug settings on Android while a game was running wouldn't cause the changed settings to apply to code blocks that already had been compiled.

Jit: Automatically clear cache when JIT settings are updated

---

Source/UnitTests/Core/PageFaultTest.cpp

Using GTEST_SKIP instead of just returning from the function shows that a test was skipped in the test summary. If GTEST_SKIP is called the rest of the function won't be run, just like with the return.
GTEST_SKIP wasn't available until gtest 1.10, and we updated to 1.12.1 in #11438.

PageFaultTest: Use GTEST_SKIP instead of early return

---

Source/Core/Common/MemArena.h
Source/Core/Common/MemArenaAndroid.cpp
Source/Core/Common/MemArenaUnix.cpp
Source/Core/Common/MemArenaWin.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.h

Whenever JitBaseBlockCache::Clear() got called, it threw away the memory mapping for the fast block map and created a new one. This new mapping typically got mapped at the same address at the old one, but this is not guaranteed. The pointer to the mapping gets embedded in the generated dispatcher code in Jit64AsmRoutineManager::Generate(), which is only called once on game boot, so if the new mapping ended up at a different address than the old one, the pointer in the ASM pointed at garbage, leading to a crash.
This fixes the issue by guaranteeing that the new mapping is mapped at the same address.
---
@krnlyng You might be interested in this.

JitCache: Fix potentially dangling pointer to fast block map.

---

Source/Core/Common/MemoryUtil.cpp
Source/Core/Common/MemoryUtil.h
Source/Core/Core/Core.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp

While both fastmem and the BLR optimization depend on fault handling, the BLR optimization doesn't depend on fastmem, and there are cases where you might want the BLR optimization but not fastmem. For me personally, it's useful when I try to use a debugger on Android and have to disable fastmem so I don't get SIGSEGVs all the time, but it would be especially useful for iOS users.

Jit: Allow BLR optimization without fastmem

---

Source/Core/Core/IOS/Network/KD/NWC24DL.cpp
Source/Core/Core/IOS/Network/KD/NWC24DL.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp

The flag in an application's `nwc24dl.bin` entry can have a bit set which signifies that the downloaded file will not have an RSA signature. Along with not having the signature, it will also not have the `NWC24::WC24File` header, or 320 null bytes before the actual data.

IOS/KD: Check if a file has an RSA signature

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FloatSliderSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/IntSliderSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SliderSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SliderViewHolder.kt

By not setting a stepSize, stepSize was getting set to the default value of 0, which is an Int. This later caused a crash when trying to cast it to Float.

Android: Fix controller float sliders crashing

---

Source/Core/Common/CMakeLists.txt
Source/Core/Common/Crypto/HMAC.cpp
Source/Core/Common/Crypto/HMAC.h
Source/Core/Common/HttpRequest.cpp
Source/Core/Common/HttpRequest.h
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/CMakeLists.txt
Source/Core/Core/IOS/Network/KD/Mail/MailCommon.h
Source/Core/Core/IOS/Network/KD/Mail/WC24Send.cpp
Source/Core/Core/IOS/Network/KD/Mail/WC24Send.h
Source/Core/Core/IOS/Network/KD/NWC24Config.cpp
Source/Core/Core/IOS/Network/KD/NWC24Config.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.h
Source/Core/DolphinLib.props

This PR implements both a scheduler for WiiConnect24 as well as the NWC24_CHECK_MAIL_NOW ioctl.
I have decided to split #11746 into separate PR's for easier reviewing.

IOS/KD: Implement NWC24_CHECK_MAIL_NOW

---

Source/Core/VideoCommon/VideoBackendBase.cpp

`g_graphics_mod_manager` wasn't shutdown in `VideoBackendBase::ShutdownShared` causing
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```
on macOS.
The cause of the error was `EventHook` in `GraphicsModManager` calling it's deconstructor, by which time the mutex in the static `Storage` was already destroyed.

VideoCommon: Deinit Graphics Mod Manager explicitly

---

Source/Core/VideoCommon/Assets/CustomAssetLibrary.cpp
Source/Core/VideoCommon/Assets/CustomTextureData.cpp
Source/Core/VideoCommon/Assets/CustomTextureData.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.h
Source/Core/VideoCommon/Assets/TextureAsset.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp

Pulled from #11783
Testing would amount to checking texture packs to make sure custom texture support isn't broken.  I've checked a few as well as DIT generation.

VideoCommon: add ability to load cube maps into custom texture data

---

Source/Core/VideoCommon/Assets/TextureAsset.cpp
Source/Core/VideoCommon/Assets/TextureAsset.h

This includes a texture sampler as well as a type describing what type of texture it is (ex: 2d Texture, cubemap, or maybe even a 3d texture eventually!).
Not used currently.  Trying to create small PRs as I build up for the next big thing..

VideoCommon: add TextureData structure with metadata

---

Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.cpp

Also moves the pixel shader asset cache time  calculation back to the texture creation.  I think this is a little more logical.

VideoCommon: additional error checking for CustomPipelineAction

---

Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/Assets/ShaderAsset.h

This adds a couple of additional sampler definitions to the ShaderAsset.  This allows for distinguishing between a 2d sampler defined by assets and a 2d sampler that was defined by an alternate source (ex: Dolphin has a definition for an array of samplers in `PixelShaderGen` for instance).  This distinction isn't super necessary at the moment but will be important later on if a user wants to add 2d textures with their own sampler information and independent resolution (needs #12136 )
I add two separate entries.  One called `Type_SamplerArrayShared_Main` that denotes the main texture, in a sampler array this is where the sampler would come from and also sets the requirement for the size of the texture.  `Type_SamplerArrayShared_Additional` is an additional texture which follows the sampler …

VideoCommon: add additional texture sampler types to ShaderAsset

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp

This refactors the Rich Presence generation to store to a member field that can be exposed to the UI to display the Rich Presence in the achievement header. It still updates at its original rate of once per two minutes, but calls an update on the dialog when that ticks.

RetroAchievements - Add Rich Presence to Achievement Dialog Header

---

Source/Core/DolphinQt/MainWindow.cpp

Moved AchievementManager Init further down in the MainWindow constructor; its original position was because it had an impact on the contents of the menu bar, and this is no longer the case. On top of this, if achievements are enabled and there's an API token already in the config (meaning the emulator will attempt to verify credentials and "log in"), it opens the Achievements dialog as a way of notifying the player that the achievements are active.

RetroAchievements - Rearranged startup process

---

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp

Questionable how many people still build 32-bit these days but it should work at least.

Core/JitCache: Don't try to allocate the fast block map on 32-bit builds.

---

Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp

Should fix https://bugs.dolphin-emu.org/issues/13178.
Jit64 doesn't need to do this because it stores PC directly into ppcState instead of first storing it in a register.

JitArm64: Store PC on debug exit

---

Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/PPCAnalyst.cpp

This bug has been lurking in the code ever since I added the discard functionality. It doesn't seem to be triggered all that often, and on top of that the emitted code only runs conditionally, so I'm not sure if people have been affected by this bug in practice or not.

Jit: Don't discard before gather pipe interrupt check

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp

We need to check for the address of the *previous* instruction, because checking fifoWriteAddresses happens not at the end of the instruction that triggered it but at the start of the next instruction.

Jit: Use correct address when checking fifoWriteAddresses

---

Source/Core/Common/MemArenaUnix.cpp

This came up during the discussion that led to the #12173 fixes.
In short: When `/proc/sys/vm/overcommit_memory` is 0 (which appears to be the default in the Linux kernel), Linux refuses `mmap` requests of private anonymous memory that it knows cannot actually be fulfilled by the current amount of free RAM and swap. This causes the fast block lookup optimization to fail on low-memory (<= 4 GB) devices. This behavior makes sense (more or less) if you assume that all the allocated memory will actually be written to, but with our LazyMemoryRegion here, we assume that only a tiny amount will actually be touched before the memory will be reset or free'd. So the suggestion came up to just set `MAP_NORESERVE` -- which supresses the check and allows the allocation anyway.
I think this is …

Common/MemArena: Set MAP_NORESERVE in LazyMemoryRegion on Linux.

---

Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/Assets/ShaderAsset.h
Source/Core/VideoCommon/Assets/TextureAsset.cpp
Source/Core/VideoCommon/Assets/TextureAsset.h

Exposes cubemap as a valid cubemap sampler and allows cubemap as a valid texture.  Getting a bit closer to cubemap being loadable (reproducing #11783 in the modern asset based system)

VideoCommon: add cubemap to ShaderAsset and TextureAsset

---

Source/Core/Common/HttpRequest.cpp

Should fix https://bugs.dolphin-emu.org/issues/13353.

Common: Fix HttpRequest::GetLastResponseCode stack corruption

---

Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.h

And in order to avoid a double dereference in the dispatcher, directly store the normalEntry in the map.
The index to the block map becomes ((((DR<<1) | IR) << 30) | (address >> 2)). This has been chosen since the msr bits change less often than the address, thus we keep nearby entries together.
Also in the fast lookup table case, do not call the C dispatcher in case the assembly dispatcher didn't find a block, since it wouldn't find a block either due to the 1:1 mapping.

JitArm64/Jit64: Extend the fast lookup mmap-ed segment further to avoid needing to check the msr bits.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CoilUtils.kt

This fixes a bug where custom cover loading was initiated but would finish by the time another image view would be in the place of the previous one.
Turns out before I didn't really understand how to use coil for async loads properly. This should feed it everything it needs.

Android: Use custom image loader for game covers

---

Source/Core/Core/HW/AddressSpace.cpp

Memory widget search functionality would not work for MEM2 region. `Match()` restricts our physical address from exceeding 0x01FFFFFF. This means that we can access cached/uncache MEM1 as our physical addresses are 0x00000000 - 0x017FFFFF. However, this logic does not work for MEM2, as our physical address is 0x10000000 to 0x117FFFFF (I believe). Searching starting from MEM2 does not show a match until 0xC0000000.
At first I assumed we would just modify `memory_area`, however, the call to `MMU::HostIsRAMAddress()` in `EffectiveAddressSpaceAccessors::Search()` appears to sufficiently check for valid memory bounds. Notably, we want to allow RAM searches for instances where you increase the size of MEM1 or MEM2 via Config->Advanced tab. In these instances, the current code does not allow for …

Debugger/Memory: Fix mem2 search

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
Source/Android/app/src/main/res/layout/dialog_slider.xml

In some settings where the default value could not be evenly divided by the step size for the slider, there would be a crash. This increases the precision of all double numeric settings to 0.5 and now shows the decimal that you couldn't see before.
This is because we started tracking the value of the slider as a Float in #12095 instead of cutting off the decimal value with an Int.
Additionally, this moves the TextView from the right side of the slider to the top in the slider dialog. I really should've just kept this back in #10725

Android: Float slider settings fix

---

CMakeLists.txt

After code changes made in #12190, compile errors occur if system library version fmt < 10 is installed.

Require system library fmt >= 10.1

---

Source/Core/Core/IOS/Network/KD/NWC24DL.cpp
Source/Core/Core/IOS/Network/KD/NWC24DL.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp

Some download entries such as announcements can have empty filenames which would cause an invalid open with FatFS.
I tested this with a member in the Dolphin Discord who was experiencing crash and it no longer crashes with this patch.

IOS/KD: Fix crash with KD Scheduler

---

Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp

Fairly self-explanatory PR - the GetDeviceByIOSID method can return null, and I have noticed this happening when a usb device is removed during gameplay (for Skylanders or Disney Infinity for example) where the core still attempts to read from the USB device while the remove hooks are being thrown. Will prevent crashes when doing this in-game.

HIDv4: Check Device Not Null Before Attaching

---

Source/Core/InputCommon/ControllerInterface/SteamDeck/SteamDeck.cpp

As described in the code comment, a recent change to the Steam client disables sending of gyro data if Steam Input doesn't think the gyro is being used. This change adds some code to periodically try re-enabling the gyro data (so that users to not have to manually perform a workaround by assigning dummy unused behavior in Steam Input).
It is not sufficient to merely do this once at launch because opening and closing the Steam or performance ("..." button) overlays will disable gyro data again.
The magic number of 250 was originally chosen because the Deck controls poll at 250 Hz, and so the intent was to re-enable gyro data once per second. However, this was before I remembered that UpdateInput is nonblocking and not actually called at this frequency. In any case, the exact number here is …

Steam Deck: Periodically reenable gyro

---

Source/Core/Common/FileUtil.cpp

This is an extremely small patch that fixes an exception thrown if you try to use POSIX pipes as control inputs (as detailed in [this wiki article](https://wiki.dolphin-emu.org/index.php?title=Pipe_Input)).
On the current `master`, if you have a POSIX pipe in Dolphin's "Pipes" folder, it will crash on startup with the following message:
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
what():  filesystem error: cannot get file size: Operation not supported [<filename>]
```
This happens because `ScanDirectoryTree` attempts to get the size of all non-directories, which as the exception explains is not valid for FIFO pipes.
This patch adds an additional check for `is_fifo()` in addition to the existing check for `is_directory()`, returning 0 for …

FileUtil: Don't try to retrieve size for FIFO pipe

---

Source/Core/DolphinQt/MainWindow.cpp

- Select slot 2 and exit & launch Dolphin again. 
- Slot 2 is correctly selected in the menu, but saving from selected slot using a Hotkey saves to slot 1.
-> m_state_slot value is never reloaded from Qt.ini

SaveStates : Fix MainWindow.m_state_slot is not restored from Qt.ini Emulation/StateSlot.

---

Source/Core/DolphinQt/HotkeyScheduler.cpp

Current behavior of the Decrease Emulation Speed hotkey results in an unintended resetting of speed. Pressing the hotkey allows speed to go from 100% to 90% all the way to 10%. A subsequent press of the hotkey will then cause a rollover back to 100% speed. Subsequent presses will bring speed down to 10% again, repeating the cycle. This does not match the behavior prior to the Qt migration, and I personally don't think it should act this way!

DolphinQt: Fix decrease emulation speed hotkey rollover

---

Source/Core/Core/PowerPC/Jit64/RegCache/CachedReg.h

This would normally be an incredibly unimportant change, but I discovered that `PPCCachedReg::GetLocationType` is the cause of the single hottest path on the CPU/GPU thread when repeatedly loading savestates, as TASers do. For whatever reason, the `==` operator comprises ~14% of the thread's CPU cycles during savestate loads. This caught my eye, so I looked further and noticed a small improvement.
`==` is acting on `std::optional<Gen::OpArg>` and `Gen::OpArg`. Thus this is scenario 21 from [this documentation](https://en.cppreference.com/w/cpp/utility/optional/operator_cmp). We see that this operator first checks to see if the optional object contains a value. Only after that does it call `Gen::OpArg::operator==`. However, the check to see if the optional object contains a value is …

PowerPC: reduce location assert cost

---

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h

When evaluating whether jo.fastmem should be set to true, we check the value of jo.fastmem_arena. However, due to a change made in 28e8117b90, jo.fastmem_arena wasn't set until after the first time we set jo.fastmem, so jo.fastmem would end up always being false until the next time RefreshConfig was called.
Fixes https://bugs.dolphin-emu.org/issues/13364.

Jit: Fix fastmem initialization order

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/Core/Config/AchievementSettings.cpp
Source/Core/Core/Config/AchievementSettings.h
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.h
Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, I add the functionality to download player, game, and achievement badges (icons) from the RetroAchievements server and display them in the Achievement dialog within the header and the Progress tab.

RetroAchievements - Badges

---

Source/Core/Common/IOFile.cpp
Source/Core/Common/IOFile.h
Source/Core/DiscIO/Blob.h
Source/Core/DiscIO/CISOBlob.cpp
Source/Core/DiscIO/CISOBlob.h
Source/Core/DiscIO/CompressedBlob.cpp
Source/Core/DiscIO/CompressedBlob.h
Source/Core/DiscIO/DirectoryBlob.cpp
Source/Core/DiscIO/DirectoryBlob.h
Source/Core/DiscIO/DiscScrubber.cpp
Source/Core/DiscIO/DiscScrubber.h
Source/Core/DiscIO/FileBlob.cpp
Source/Core/DiscIO/FileBlob.h
Source/Core/DiscIO/NFSBlob.cpp
Source/Core/DiscIO/NFSBlob.h
Source/Core/DiscIO/RiivolutionPatcher.cpp
Source/Core/DiscIO/ScrubbedBlob.cpp
Source/Core/DiscIO/ScrubbedBlob.h
Source/Core/DiscIO/SplitFileBlob.cpp
Source/Core/DiscIO/SplitFileBlob.h
Source/Core/DiscIO/TGCBlob.cpp
Source/Core/DiscIO/TGCBlob.h
Source/Core/DiscIO/VolumeFileBlobReader.cpp
Source/Core/DiscIO/VolumeFileBlobReader.h
Source/Core/DiscIO/WIABlob.cpp
Source/Core/DiscIO/WIABlob.h
Source/Core/DiscIO/WbfsBlob.cpp
Source/Core/DiscIO/WbfsBlob.h

A deep-copy method CopyReader has been added to BlobReader (virtual) and all of its subclasses (override). This should create a second BlobReader to open the same set of data but with an independent read pointer so that it doesn't interfere with any reads done on the original Reader.
As part of this, IOFile has added code to create a deep copy IOFile pointer onto the same file, with code based on the platform in question to find the file ID from the file pointer and open a new one. There has also been a small piece added to FileInfo to enable a deep copy, but its only subclass at this time already had a copy constructor so this was relatively minor.

Added CopyReader to BlobReader and all subclasses

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/Core/Config/AchievementSettings.cpp
Source/Core/Core/Config/AchievementSettings.h
Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, I add event handling for achievement progress. If an achievement involves a measured value (for example, 120 stars), the achievement framework will throw an event every time the number of stars is updated. This PR will reflect that by popping a notification up on screen and by adding a progress bar to the Progress tab in the Achievements dialog.

RetroAchievements - Progress Notifications

---

Data/Sys/GameSettings/SFI.ini

See https://bugs.dolphin-emu.org/issues/13356. Testing there determined that forcing a specific value for SafeTextureCacheColorSamples is not needed.

Disable Store EFB Copies to Texture Only for Mystery Case Files: The Malgrave Incident

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp

Simple change to allow resolution multipliers up to 12x.
Qt UI also updated.
This has been tested on OpenGL, DX11, DX12 and Vulkan.
This especially makes more sense now that we have proper downsampling of the image (area resampling) (https://github.com/dolphin-emu/dolphin/pull/11999). When playing at 12x, the temporal stability is incredibly high, and texture show more detail if we had high resolution texture packs. The performance impact is minimal.
`GFX_MAX_EFB_SCALE` was not even respected by the "Auto Internal Resolution Scale" setting, so on 8k monitors resolution could already go beyond 8x (to 12x or 13x).
I've made the change to respect it in this PR `https://github.com/dolphin-emu/dolphin/pull/12170` so we can be sure we don't try to allocate textures bigger than the maximum …

Add support for resolutions multipliers up to 12x (~8k)

---

Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardRaw.h

The current implementation of [MemoryCard::IsAddressInBounds](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/HW/GCMemcard/GCMemcardRaw.h#L33) only checks that the provided address  is in bounds, without checking that also address+length is in bounds.
This leads to heap buffer overflow in MemoryCard::{Read/Write/ClearBlock} functions.
This can be exploited to achieve RCE on the host.

Fix heap buffer overflow in GCMemcardRaw

---

Source/Core/VideoCommon/Assets/CustomAssetLibrary.cpp
Source/Core/VideoCommon/Assets/CustomAssetLibrary.h
Source/Core/VideoCommon/Assets/CustomAssetLoader.cpp
Source/Core/VideoCommon/Assets/CustomAssetLoader.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.h
Source/Core/VideoCommon/Assets/TextureAsset.cpp
Source/Core/VideoCommon/Assets/TextureAsset.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.cpp
Source/Core/VideoCommon/HiresTextures.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h
docs/CustomPipelineGraphicsMod.md

Previously we used the raw texture data ( `CustomTextureData` ) for texture assets.  There may be times where we want additional metadata for our assets, examples include:
* The type information, to [distinguish cube maps](https://github.com/dolphin-emu/dolphin/pull/11783)
* Custom sampler information to [change the sampler](https://github.com/dolphin-emu/dolphin/pull/11235) that Dolphin uses or create a new sampler altogether!
* Whether the texture uses arbitrary mipmaps
Now textures use `TextureData` which includes `CustomTextureData` but also allows for other metadata as well.  The names are confusing, I need to update `CustomTextureData` to something else..
While this is standalone, if #12140 is merged, this will need to be updated.
**Testing** - simply make sure custom texture packs …

VideoCommon: use 'TextureData' for texture assets to support texture metadata

---

Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp

This got broken in #12171.
Currently this only shows two items by default, which is rather inconvenient:
https://cdn.discordapp.com/attachments/549875374327332884/1161284935747907594/image.png

Qt/EnhancementsWidget: Fix size of resolution dropdown.

---

Source/Core/VideoCommon/VideoConfig.cpp

This was seen for a custom shader feature I was working on but someone on Discord mentioning a similar issue when changing anti-aliasing options.

VideoCommon: wait for the GPU to be finished doing any work before invalidating pipelines when graphics config changes

---

Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/Config/GraphicsModListWidget.cpp
Source/Core/DolphinQt/Config/GraphicsModListWidget.h
Source/Core/DolphinQt/DolphinQt.vcxproj
Source/Core/DolphinQt/QtUtils/ClearLayoutRecursively.cpp
Source/Core/DolphinQt/QtUtils/ClearLayoutRecursively.h

This is needed over in #12027 to avoid memory leaks.

DolphinQt: Move GraphicsModListWidget::ClearLayoutRecursively() to QtUtils.

---

Source/Core/Core/AchievementManager.cpp

Both of these functions access `m_game_data` and don't lock themselves, so they must be called in a way that guarantees that `m_game_data` is not modified during the call.

AchievementManager: Call ActivateDeactivateLeaderboards() and ActivateDeactivateRichPresence() under lock.

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/DolphinQt/Achievements/AchievementLeaderboardWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementLeaderboardWidget.h
Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
Source/Core/DolphinQt/Achievements/AchievementsWindow.h
Source/Core/DolphinQt/CMakeLists.txt
Source/Core/DolphinQt/DolphinQt.vcxproj

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, I add a leaderboards tab to the Achievements dialog, and add the necessary calls to the RetroAchievements server to collect the relevant information. Each leaderboard is shown with the player's current score, if one is submitted, and a selection of other players' submissions they may find useful.

RetroAchievements - Leaderboards Tab

---

Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/Assets/ShaderAsset.h

The third PR for getting custom shader uniforms supported in Dolphin.  This updates the shader asset to supply additional properties (also adds an enum formatter to match the material asset)

VideoCommon: add additional properties to ShaderAsset to support custom shader uniforms

---

Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/Assets/TextureAsset.cpp

This ensures we have proper locale independent behavior.  That was always the plan but...well...whoops :)

VideoCommon: use ToLower function in assets when parsing json

---

Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp

No need to do this manually when we have a utility function now.

DolphinQt/AchievementProgressWidget: Use ClearLayoutRecursively() to clear layout.

---

Source/Core/Core/Core.cpp
Source/Core/VideoCommon/OnScreenDisplay.cpp
Source/Core/VideoCommon/OnScreenDisplay.h

Needed for #12196.
This is very much not my corner of the codebase so please look at this in detail for any potential errors. It seems to behave correctly though, in both Single Core and Dual Core.
Here's a branch with the AchievementManager changes needed for that to actually push the icons, since that makes testing a bit easier:
https://github.com/AdmiralCurtiss/dolphin/tree/osd-icons-achievements

VideoCommon: Add support for icons in OSD messages.

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, I add to the Badges functionality to incorporate badges in the OnScreenDisplay messages that pop up during various achievement-related events.

RetroAchievements - On Screen Images

---

Source/Core/Core/IOS/USB/Emulated/Skylander.h

SkylanderPortal is final, so having member variables be protected instead of private is pointless and potentially misleading.

SkylanderPortal: Make protected variables private

---

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp

There was a time when Xbox 360 controllers had their left/right trigger inputs combined under DirectInput and SDL making them effectively unusable.
Exposing those interfaces confused users so they were hidden to force use of XInput.
It seems SDL has resolved this combined trigger situation and this hack is no longer needed.
A user on Discord wanted to use SDL for friendliness with some frontend or something, so this hack might as well be removed now.

ControllerInterface/SDL: Remove Xbox 360 controller disabling hack.

---

Source/Core/Core/CheatSearch.cpp

Use std::equal_to<T>() and so on for the last value comparison functions since they exist and we already include the functional header.
I didn't replace the functions used for comparing against a specific value because I'd need to use bind and it's not really any clearer or less verbose than the lambda.

CheatSearch: Use std comparison function objects

---

Source/Core/VideoBackends/OGL/OGLConfig.cpp
Source/Core/VideoCommon/UberShaderVertex.cpp
Source/Core/VideoCommon/VertexShaderGen.cpp

Fixes some mishandling of drivers with features of an ancient GPU but some much newer extensions like Asahi Linux (e.g. GL 3.2 with SSBOs supported only in fragment shaders)
Note: We still fail to compile fbfetch shaders, I'll handle those later

Fix shader compiles on Asahi Linux

---

Source/Core/VideoCommon/Present.cpp

This triggers an assert in TCacheEntry::SetXfbCopy() otherwise if you load a savestate that was made before the first XFB has been rendered.

VideoCommon: Don't swap on state load when there's no XFB.

---

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp

Instructions referencing registers r8-r15 take an additional byte to encode. `reg_downcount` may be assigned to one of these registers, so it is a small size win to store the downcount value in `RSCRATCH` first.
Additionally, we can eliminate a `MOV` by being slightly more conscious about our registers.
Before:
```
33 D2                xor         edx,edx
44 8B 6D 64          mov         r13d,dword ptr [rbp+64h]
45 85 ED             test        r13d,r13d
7E 30                jle         0000023546B43F6D
44 8B B5 D4 02 00 00 mov         r14d,dword ptr [rbp+2D4h]
41 8B C5             mov         eax,r13d
BF 07 00 00 00       mov         edi,7
F7 F7                div         eax,edi
41 8D 56 FF          lea         edx,[r14-1]  
3B C2                cmp         eax,edx  
0F 42 D0 …
```

Jit_LoadStore: Minor dcbx register optimizations

---

Tools/perf-disassemble.sh

perf now passes the proper no-show-raw-insn option instead of no-show-raw.
Keep no-show-raw as a fallback for older kernels/perf-toolings.
See also: https://github.com/torvalds/linux/commit/c5baf9089246c1356705c9ba36d767ee8ce43dd2

Tools: fix perf-disassemble.sh.

---

Source/Core/Core/State.cpp

Special thanks to @TryTwo for identifying this regression.
On core state changes (Play/Pause for example), Dolphin reads the headers of all savestates associated with the currently running game. Normally this just involves reading the state header, which is uncompressed, thus reads are quick and simple. Changes introduced in #12217 change the behavior when calling `ReadHeader()` in `State.cpp`, whose aim is to just get each state's timestamp. Instead of reading just the legacy header, `ReadStateHeaderFromFile()` reads what we consider to be the NEW header, which includes version information. To support legacy savestate version checks, we decompress the state using LZ4 to retrieve the version info to copy over to our new header. However, this decompression does not need to occur if we …

Core: Fix UI slowdown for savestate timestamp reads

---

Source/Core/Core/Debugger/PPCDebugInterface.cpp

Fixes:
FromChars cannot return a value prefixed with 0x.
Possible regex failures on  rX, rY, rZ instruction forms.

PPCDebugInterface:  Tweak regex in GetMemoryAddressFromInstruction to fix bugs

---

Source/Core/DolphinQt/CheatSearchFactoryWidget.cpp

Add stretch to bottom of factory widget to prevent the Data Type QGroupBox from getting stretched out awkwardly.
Before/After:

Cheats Manager: Fix factory widget spacing

---

Source/Core/Core/State.cpp

Plus another minor robustness issue I ran into while testing. Turns out `localtime()` can return a nullptr, and `wcsftime()` asserts if you pass it one.
I noticed this back when reviewing #12217. The code previously did this indirectly via `std::map<double, int>`, the key being the timestamp, which required a questionable workaround for the case where multiple states have the same timestamp. By having a particular combination of timestamps in the on-disk savestates, you could cause this workaround to infinitely loop, locking up Dolphin. This avoids this completely by refactoring the logic and just using `std::vector` instead.
Admittedly, this is pretty difficult to trigger by accident, but if you just manually edit two states to have eg. 1e300 as the timestamp this triggers, because …

Core/State: Refactor logic for determining the relative age of existing savestates.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Common/CodeBlock.h
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.h
Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/PowerPC.cpp
Source/Core/Core/PowerPC/PowerPC.h
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/MenuBar.h
Source/Core/DolphinQt/Settings/AdvancedPane.cpp
Source/Core/VideoCommon/VertexLoaderARM64.cpp
Source/Core/VideoCommon/VertexLoaderX64.cpp

Now that PR #10575 is merged, the JIT automatically clears its cache when this setting is changed, making this reasonable to implement.

PowerPC: Allow toggling write-back cache during emulation

---

Source/Core/Common/ENet.cpp
Source/Core/Common/ENet.h
Source/Core/Common/TraversalClient.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayServer.cpp

A few days ago, I was asked about "unknown event type: 42" errors appearing in the Dolphin log. After investigating, it turned out that these logging calls were added in #11704, without taking into account the Dolphin-specific hack for skipping events relating to traversal and wake-up packets in the main ENet code.
This PR adjusts the logging so that these skipped events are not logged as errors, in case someone asks about this in future. It also gives the 42 constant a name. I put it in ENet.h since that was the lowest common denominator of all the places where it was used.

Netplay: Don't log skippable events as errors

---

Source/Core/Core/FifoPlayer/FifoRecorder.cpp

Since ccf92a3e56764d6378c436a8040519a5bffc3372, recording fifologs multiple times after launching dolphin caused all initial state to not be saved (the initial contents of bpmem, cpmem, etc were all zeroed out). For some games, this was not noticeable, as most registers were set each frame, but for others, this resulted in completely broken fifologs. (Note that recording fifologs also required 05181f6b88fd8ee671113bcafb81c65027f911a4 and 9e0755a5983d8d9a277cea284534fb32a545f270 to be cherry-picked due to other, since fixed, regressions.)
This was because previously, `Renderer::CheckFifoRecording` was called every frame, but ccf92a3e56764d6378c436a8040519a5bffc3372 changed it into a callback (`m_end_of_frame_event`) that was removed when recording ended. Thus, before, …

Fix regression when recording multiple fifologs

---

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp

In the AMD64 JIT, the `tw*` instructions did fail to update `PPCSTATE(pc)` before raising the exception, so the program exception was taken with incorrect SRR0.
This is a one-line change so I figured it would be best to open a PR rather than open a bug report.
The ARM64 JIT does things properly as far as I can tell.

JIT64 (Jit_Integer): for twx instructions, raise exception with correct SRR0

---

Source/Core/Core/CMakeLists.txt
Source/Core/Core/IOS/Crypto/AesDevice.cpp
Source/Core/Core/IOS/Crypto/AesDevice.h
Source/Core/Core/IOS/Crypto/Sha.cpp
Source/Core/Core/IOS/Crypto/Sha.h
Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/IOS.h
Source/Core/DolphinLib.props

with libogc supporting the sha & aes engine, and applications starting to use them, its become needed for dolphin to get a basic implementation of these devices.
using mbedtls i have implemented the devices, and they are confirmed working.
you can test them using the following dol : [crypto.zip](https://github.com/dolphin-emu/dolphin/files/12937862/crypto.zip)
this is an example i wrote for libogc
the implementation is done by looking at the work done for StarStruck

IOS: implement /dev/aes & /dev/sha

---

Source/Core/Core/IOS/Network/KD/Mail/WC24Send.cpp
Source/Core/Core/IOS/Network/KD/Mail/WC24Send.h
Source/Core/Core/IOS/Network/KD/NWC24DL.cpp
Source/Core/Core/IOS/Network/KD/NWC24DL.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp

As pointed out by @AdmiralCurtiss in #12184, when the `WC24SendList::ReadSendList` and/or `NWC24Dl::ReadDlList` fail, their class member `m_data` is being used by IOS when called. 
This PR fixes it by exiting any function which calls an `m_data` member which failed to initialize. It also deletes the corrupted file, where either Dolphin or the Wii Menu will regenerate it for later use.

IOS/KD: Disable download and mail when files are invalid

---

Source/Core/Common/ENet.cpp
Source/Core/Common/ENet.h
Source/Core/Common/TraversalClient.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayServer.cpp

Try 2.
Should fix https://bugs.dolphin-emu.org/issues/13385 which was probably introduced by #12258.

Netplay: Fix building on clang 17.

---

Source/UnitTests/Common/FloatUtilsTest.cpp

This was discussed in #12249. We have a unit test that validates that the Jit64 result matches the interpreter, but the interpreter results itself are not being tested. This diff adds a new test case validating the interpreter results against a hard-coded list.

UnitTests: Test frsqrte against known values

---

Source/Core/DolphinQt/Debugger/CodeDiffDialog.cpp
Source/Core/DolphinQt/Styles/Dark/dark.qss

Before: 
After:
Note that the top header text is no longer being cutoff.
Would help if people could test this. I don't know what window uses sorting arrows and I was just focused on fixing this one window.
I suggest adding dark.qss to the Styles folder for easy switching.

UI, CodeDiffDialog: Fix table widget display issues, including dark style.

---

Source/Core/DolphinQt/Config/ToolTipControls/BalloonTip.cpp
Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/QtUtils/SetWindowDecorations.cpp
Source/Core/DolphinQt/Settings.cpp
Source/Core/DolphinQt/Settings.h
Source/Core/DolphinQt/Settings/InterfacePane.cpp
Source/Core/DolphinQt/Settings/InterfacePane.h

This has been requested a few times since the introduction of the Windows dark style. #12180 also attempted to do this but it seemingly stalled out.
Windows-only for now. I'd have to investigate if there's a way to override the system style when it's automatically managed by Qt for the other OSes.
---
UI-wise, this reuses the User Style dropdown to now also switch between System, Light, and Dark. (On OSes other than Windows Light and Dark will not be in the dropdown.) The checkbox to enable user styles has been removed, the dropdown is now always visible and shows both our builtin and the user styles.
Before:
After:

DolphinQt: Allow forcing light or dark style on Windows.

---

Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp

DolphinQt/AchievementHeaderWidget: Fix wrong label for hard unlock count.

---

Source/Core/Core/PowerPC/MMU.cpp

Due to a bug introduced when refactoring in 2015 (commit 821db9798c62d14261116d79e17ec3ba09e64706), the store bit in DSISR is set incorrectly when the faulting address is non-zero, and not on a write.
I assume this wasn't noticed due to the parameter actually being used in the log for when the MMU is disabled.
This is a single-line fix, so again I feel a PR is more appropriate than a bug report.

MMU: on DSI exception, don't set store bit in DSISR on read

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp

This fixes some oversights I made when creating PR #10046. One is a bug fix and one is a slight performance improvement.

JitArm64: Fix some oddities with non-dirty immediates

---

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp

Fix -WSwitch warning about unhandled enum value SDL_NUM_LOG_PRIORITIES.
log_level is initialized to LNOTICE right before the switch statement so this doesn't cause any behavior changes.

SDL: Add default case to switch statement

---

Source/Core/Core/IOS/Network/Socket.h

The move assignment operator for a class is implicitly deleted when the class has a non-static reference data member, which is true of WiiSocket's m_socket_manager member.
Explicitly declaring the operator as default generated a -Wdefaulted-function-deleted warning on Clang.

WiiSocket: Explicitly delete move assignment operator

---

Source/Core/VideoCommon/BPMemory.cpp
Source/Core/VideoCommon/RenderState.cpp

I've not tested this on hardware, but it fixes [issue 12271 (shadow people in Deal or No Deal - Special Edition)](https://bugs.dolphin-emu.org/issues/12271).
The software renderer uses (pseudo code):
```c++
if (bpmem.blendmode.blendenable)
{
if (bpmem.blendmode.subtract)
SubtractBlend
else
BlendColor
}
else if (bpmem.blendmode.logicopenable)
LogicBlend
else
dstClrPtr = color;
```
Until now VideoCommon used:
```c++
if (bpmem.blendmode.subtract)
SubtractBlend
else if (bpmem.blendmode.blendenable)
BlendColor
else if (bpmem.blendmode.logicopenable)
LogicBlend
else
dstClrPtr = color;
```
The diff is much smaller when whitespace is ignored.

VideoCommon: copy software renderer logic for blend mode priorities

---

Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/VideoBackends/Software/TextureEncoder.cpp
Source/Core/VideoCommon/BPMemory.h
Source/Core/VideoCommon/BPStructs.cpp

I noticed that several registers (mostly those related to tmem) didn't have useful descriptions in the fifo analyzer while looking into https://bugs.dolphin-emu.org/issues/13377. This adds descriptions for those (and makes a few other related cleanup changes). There should be no noticeable changes to emulation behavior.

Add descriptions for more BP registers

---

Source/Core/Core/HW/DSPHLE/UCodes/AXStructs.h

This fixes overly loud sounds in Freestyle Metal X ([issue 13120](https://bugs.dolphin-emu.org/issues/13120)).

AX: make volume field signed

---

Source/Core/VideoCommon/BPStructs.cpp

This caused us to update the indirect texture information in shaders more often than we needed to, which probably doesn't matter in practice since it's only used in ubershaders and copyyscale and stride are generally only updated before EFB/XFB copies, which generally will have other changes afterwards.

Fix accidental fallthrough in BPStructs

---

Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/PowerPC.h
Source/Core/Core/State.cpp

The current TLB implementation does not use the VSID at all.
This is incorrect behaviour (I think the diagram on [A Quick Introduction to the PPC Memory Management System](https://www.usenix.org/legacy/publications/library/proceedings/osdi99/full_papers/dougan/dougan_html/node3.html) explained the correct behaviour easily for me).
The incorrect behaviour leads to previously cached pages still being used until they are flushed out of the TLB, which could lead to an application or game reading or writing to the "wrong" pages.

MMU: Use VSID in segment register as additional TLB lookup key

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.h
Source/Core/Core/PowerPC/Jit64Common/TrampolineCache.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/MMU.cpp

Dolphin's JITs have a minor terminology problem: The term "fastmem" can refer to either the system of switching between a fast path and a slow path using backpatching, or to the fast path itself. To hopefully make things clearer, I'm adding some new terms, defining the old and new terms as follows:
Fastmem: The system of switching from a fast path to a slow path by backpatching when an invalid memory access occurs.
Fast access: A code path that accesses guest memory without calling C++ code.
Slow access: A code path that accesses guest memory by calling C++ code.

Jit: Define new terms related to fastmem

---

Data/Sys/Shaders/AutoHDR.glsl

This gives more consistent results.
My main ReShade has also been updated with the same change: https://github.com/Filoppi/PumboAutoHDR

Make AutoHDR work with color luminance instead of average

---

Data/Sys/Shaders/default_pre_post_process.glsl

This just cleans the code. Area sampling is only useful if the area that each pixel samples is perfectly defined. This is to prevent issues with blurring when scaling from similar resolutions. This replaces weird estimations about the size of pixels from the target and replaces them with stricter, integer coordinates from the target, that are then projected onto the source.

Corrected Area Sampling Range

---

Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h

Technically it is signed in the 0x7699af32 ucode but that's only used by the Wii Startup Disc which never uses negative values.
This fixes [issue 13396](https://bugs.dolphin-emu.org/issues/13396).

AX: fix envelope volume for Wii ucodes

---

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

Let's aim for making as few heap allocations as possible while jitting.

Jit: Get rid of short-lived std::vectors

---

Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/IOS.h

The game [Truth or Lies](https://wiki.dolphin-emu.org/index.php?title=Truth_or_Lies) does this for some reason.
This regression was introduced in #12244 (5.0-20284).

IOS: fix crash when closing invalid file descriptor

---

Source/Core/Core/HW/DSPHLE/UCodes/AESnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp

Fixes https://bugs.dolphin-emu.org/issues/13401. This was added in libogc 2.4.0, PR devkitPro/libogc#143. We already implemented the padded version in libogc2/libogc-rice in #10892.
<details><summary>Hashes of relevant versions</summary>
[aesnd_ucode_versions_2023.zip](https://github.com/dolphin-emu/dolphin/files/13401501/aesnd_ucode_versions_2023.zip) contains 3 ucodes relevant to this change:
```
Hashes of DSP_UC_2e5e4100.bin: ector 2e5e4100 crc 8e2da39f adler 6ed62d5e fletcher 664dee8d; 0400 bytes (0200 words)
Hashes of DSP_UC_002e5e41.bin: ector 002e5e41 crc 5ba4fb19 adler 2dca2d5e 03e8 bytes (01f4 words)
Hashes of DSP_UC_802e5e41.bin: ector 802e5e41 crc 7380067f adler 311f2d5f 03e8 bytes (01f4 words)
```
`DSP_UC_2e5e4100.bin` is the padded version from libogc2, which is the same as …

DSPHLE: Support 2023 libaesnd uCode

---

Externals/expr/include/expr.h

1 dollar sign + 1 negative sign + 10 characters for the longest number + 1 null terminator = 13 characters.
Fixes compilation error with certain flags.

expr: increase size of `varname`

---

Source/Core/Core/Core.cpp
Source/Core/Core/Core.h
Source/Core/DolphinQt/Debugger/CodeDiffDialog.cpp

bug: https://bugs.dolphin-emu.org/issues/13277
Frame advance was reporting the incorrect emulation state to prevent flickering UI updates, which was breaking debugger widgets and crashing dolphin. Replaced with the option to not report a state change on SetState().
Applied the new option in CodeDiff, because it's a similar quick, temporary state switch.
Breakpoints now work correctly, and playing from a breakpoint will finish the frame advance and then pause.

Core: Add option to not report state change to SetState (bugfix)

---

Source/Core/Common/PcapFile.cpp
Source/Core/Core/NetworkCaptureLogger.cpp
Source/Core/Core/NetworkCaptureLogger.h

This PR addresses a concurrency issue between RecvHandlePacket and SendFromDirectFIFO while logging BBA packets in a PCAP file. I chose not to implement the lock in the PCAP class to avoid performance impacts in cases where there are no concurrency.

BBA/HLE: Fix random PCAP file corruption

---

Data/Sys/GameSettings/SGLPA4.ini

Same workaround as @Pokechu22's NTSC version (8316c7af9964f19cc54c3533e017252f922ceee9).

GameSettings: port Gormiti black screen fix to PAL version

---

Source/Core/VideoBackends/Metal/MTLMain.mm

Bug: https://bugs.dolphin-emu.org/issues/13404
On macOS 13.6 / Intel Iris with Metal 2, when starting any game, Dolphin crashes immediately with this message:
> -[MTLIGAccelDevice setShouldMaximizeConcurrentCompilation:]: unrecognized selector
It seems that even on macOS 13.3+, not all devices implement this selector (first implemented in #11911).
As the behavior is an optional optimization anyway, we now perform a dynamic detection to avoid crashing if the feature is not available.

Metal: fix crash by enabling concurrent compilation only if available

---

Source/Core/Core/IOS/Network/KD/Mail/WC24Send.h

Prevents double inclusions from occurring in the same TU.

WC24Send: Add missing header guard

---

Source/Core/VideoCommon/Assets/CustomAssetLibrary.h

This is used as a base pointer inside CustomPipelineAction to handle any derived type, so this should probably really have a virtual destructor to ensure those derived objects are torn down properly.

CustomAssetLibrary: Add virtual destructor

---

Source/Core/DolphinQt/SkylanderPortal/SkylanderModifyDialog.cpp
Source/Core/DolphinQt/SkylanderPortal/SkylanderPortalWindow.cpp
Source/Core/DolphinQt/SkylanderPortal/SkylanderPortalWindow.h

Just some churn I noticed that could be eliminated fairly easy. Also has some other minor changes that were noticed along the way that are fairly minor

SkylandersPortalWindow: Remove unnecessary string conversions

---

Source/Core/VideoBackends/Vulkan/VKPipeline.cpp

Just to make it a bit easier to read.

Vulkan: use EnumMap for blend factor luts (NFC)

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/DolphinQt/Config/Graphics/ColorCorrectionConfigWindow.cpp
Source/Core/VideoCommon/VideoConfig.h

This is widely used across HDR implementations (and SDR to HDR conversions)
Source:
https://www.google.com/search?q=paper+white+203+itu
The change is tiny anyway, but at least the value now is based on something that isn't "arbitrary".

Change HDR paper white default to 203 to match the ITU recommendations

---

Source/Core/DolphinQt/NetPlay/NetPlaySetupDialog.cpp

Add a spacer between the alert text and Connect button to prevent the alert text from migrating down with larger window heights.
Before:
After:

NetPlaySetupDialog: Fix spacing in Connect tab

---

Source/Android/jni/Config/NativeConfig.cpp
Source/Android/jni/MainAndroid.cpp

PR #12117 got rid of the need to be the host or CPU thread when writing to the config.

Android: Remove HostThreadLocks that are no longer needed

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp

The point of farcode is to provide a separate location for code that rarely runs, so that it doesn't pollute the icache. Taking a conditional branch is something that happens very often, so the code for that shouldn't be in farcode.

JitArm64: Don't use farcode for conditional branch instructions

---

Source/Core/DolphinLib.props
Source/Core/VideoCommon/AbstractTexture.cpp
Source/Core/VideoCommon/AbstractTexture.h
Source/Core/VideoCommon/CMakeLists.txt
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h
Source/Core/VideoCommon/TextureUtils.cpp
Source/Core/VideoCommon/TextureUtils.h

This PR moves the texture dump logic out of the texture cache to a free function so that it can be used elsewhere if desired.  Some slight changes were made that could be considered a slight performance boost when using this capability (depending on configuration).

VideoCommon: move texture dump to a free function

---

Source/Core/Core/Movie.cpp

Fix Dolphin crashing when selecting "Start Recording Input" when using OpenGL and single core.
Uses RunOnCPUThread instead of RunAsCPUThread in BeginRecordingInput to ensure OpenGL functions are accessed from a thread with an OpenGL context created.
Background: Most OpenGL functions require an OpenGL context to have been created on that thread before calling the function; when that isn't the case they return invalid results which can cause crashes when passed into other functions.
Dolphin creates the OpenGL context in the EmuThread which then becomes either the CPU-GPU thread or the Video thread for single and dual core respectively. OpenGL functions must therefore be called from that thread.
Movie::BeginRecordingInput was called from the Host thread and runs a block of code which …

Movie: Fix crash when starting input recording on OpenGL single core

---

Source/Core/Core/PowerPC/PPCCache.cpp

This is more accurate, although it should not make a difference in practice.  See pages 137 and 140 of [the PowerPC 750cl manual](https://fail0verflow.com/media/files/ppc_750cl.pdf).
I tested and confirmed that Scooby Doo: Mystery Mayhem and Ed, Edd n Eddy: The Mis-Edventures still work correctly.

PPCCache: Always invalidate on icbi, even if icache is disabled

---

Source/Core/DolphinQt/Debugger/CodeDiffDialog.cpp
Source/Core/DolphinQt/Debugger/CodeDiffDialog.h

Proper usage of Code Diff can crash dolphin, which is expected / not a bug.  Being able to save your work and reload it is very helpful for recovering from a crash.  There's also a general use of saving at a certain point, so you can return to it.
I wasn't sure where to save the data, so I put it in Logs and added the gameID so you can have one for each game.  Also, not sure if it's fine to just make it a .txt extension. The output is in a readable text format if the user wants to open it and mess with it.
@dreamsyntax needs to test and confirm it's doing everything needed.

CodeDiffDialog: Add saving/loading results to a file.

---

Source/Core/Core/Debugger/Debugger_SymbolMap.cpp

There's a double counting typo that limits the callstack to 11 items when it should be 20.

Callstack: Bugfix. Fix loop to allow for more lines.

---

Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/State.cpp
Source/Core/Core/System.cpp
Source/Core/Core/System.h
Source/Core/DolphinLib.props
Source/Core/VideoCommon/BPStructs.cpp
Source/Core/VideoCommon/CMakeLists.txt
Source/Core/VideoCommon/CPUCull.cpp
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VertexShaderManager.cpp
Source/Core/VideoCommon/VertexShaderManager.h
Source/Core/VideoCommon/VideoBackendBase.cpp
Source/Core/VideoCommon/VideoState.cpp
Source/Core/VideoCommon/XFStateManager.cpp
Source/Core/VideoCommon/XFStateManager.h
Source/Core/VideoCommon/XFStructs.cpp

At the moment, changes to xf state are tracked in `VertexShaderManager`.  This makes it impossible to know what state changed outside of that class.  For new graphics mod features, it is useful to know what state changed and then do something with that information and having a separate class gives that capability.
Once the graphics mod changes are pushed up, I'll link this PR to that to show how it is being used.

VideoCommon: move xf state management to its own class

---

Source/Core/Core/HLE/HLE.cpp
Source/Core/Core/HLE/HLE.h
Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/PPCAnalyst.cpp

Not sure if this was causing correctness issues – it depends on whether the HLE code was actually reading the discarded registers – but it was at least causing annoying assert messages in one piece of homebrew.

PPCAnalyst: Don't discard registers across HLE'd functions

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h

This way, the number of loop iterations is equal to the number of set bits in the bitset rather than the number of bits in the bitset, which is a good improvement because usually very few bits are set.

JitArm64: Optimize Arm64GPRCache::FlushRegisters/FlushCRRegisters

---

Source/Core/VideoBackends/OGL/OGLConfig.cpp

Having a Warning Log with a blank list of missing extensions can make it look like something is wrong when it isn't, so use an Info Log saying everything is fine instead.

OGLConfig: Only use Warn Log when OGL extensions are missing

---

Source/Core/DiscIO/Enums.cpp
Source/Core/DiscIO/Enums.h
Source/Core/DolphinTool/DolphinTool.vcxproj
Source/Core/DolphinTool/HeaderCommand.cpp

Adds a `--json` option to the `header` command in `DolphinTool` to output the data as a JSON string, for easier parsing by third-party tools.
Also adds some new data with actual information about the game (name, region, country, id, revision).
Example usage: programmatically verifying ROMs without hashing the whole file (can take a while on slower machines), like to ensure the user has the correct ROM for a Crowd Control integration

Tool/Header: Add JSON output mode; game data

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This analysis needs to scan backwards, not forwards.

PPCAnalyst: Fix gprBlockInputs calculation

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp

We had two nearly identical copies of the gather pipe exception checking code right next to each other, with the only difference being the register used. Let's unify them, like in Jit64.

JitArm64: Deduplicate the gather pipe exception check

---

Source/Core/Core/PowerPC/Jit64/Jit_LoadStorePaired.cpp
Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

This functionality was in Jit64 but not JitArm64.

JitArm64: Write PC when calling MMU.cpp

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

This does require another register, but we skip having to use shifted ADD, which takes two cycles on some CPUs, and we gain instruction-level parallelism.

JitArm64: Optimize mfsrin/mtsrin address calculations

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp

Instead of materializing the quiet bit in a register and ORing the NaN with it, we can perform an arithmetic operation on the NaN. This is a cycle or two slower on some CPUs in cases where generating the quiet bit pipelined well, but this is farcode that rarely runs, so instruction fetch latency is the bigger concern. And for non-SIMD cases, we also save a register.

JitArm64: Use one instruction for making NaNs quiet

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

This makes Jit64::mtmsr more optimized in particular.

Jit: Handle imm msr in EmitStoreMembase

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp

When we execute a JIT block, we have to make sure that both the PC and the DR/IR bits of MSR are the same as they were when the block was compiled. When jumping to a block from the dispatcher, this is done in the way you would expect: By checking the PC and the relevant MSR bits. However, when returning to a block using the BLR optimization, we only check the PC. Checking the MSR bits is done by instead resetting the stack when the MSR changes, making PC checks afterwards fail.
Except... We were only resetting the stack on rfi instructions. There are actually many more ways for the MSR to change, and we weren't covering those at all. I looked into resetting the stack on all of them, but it would be pretty cumbersome both in terms of writing the code and in terms of how often at runtime …

Jit: Check MSR state in BLR optimization

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.kt
Source/Core/Core/Config/MainSettings.cpp

This updates the default IP for the HLE BBA, as the existing IP is apparently no longer in use by schtserv (@schthack please feel free to comment here).  The new IP was found [here](https://schtserv.com/).
For the sake of discussion, alternatively consider populating the default IP with 8.8.8.8, and providing a link to a Wiki from the tooltips or inline descriptions, which would then reference other IPs such as schtserv and sylverant (currently 138.197.20.130 as found [here](https://sylverant.net/connecting-to-sylverant/)).  Maintainers of these servers could then more easily update the Wiki with network etc. changes than having to create a PR to do so in the codebase.
On one hand this approach would be more standardized and balanced, however the current method may be better overall since …

Update default IP for HLE BBA

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h
Source/Core/Core/PowerPC/PPCAnalyst.cpp
Source/Core/Core/PowerPC/PPCAnalyst.h

By flushing the condition registers as soon as we no longer need them, we reduce the register pressure.
Split out from PR #9857 for ease of review.

JitArm64: Add flush/discard support for condition registers

---

Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp

This is a recent regression introduced in c70dcf99dd7b434d5196feb47f2a6e87bb34234b.

Jit64: fix invalid instruction encoding

---

Source/Core/Core/IOS/Network/KD/NWC24Config.cpp
Source/Core/Core/IOS/Network/KD/NWC24Config.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.h

Registers the user's mail account to whatever server is in the `nwc24msg.cfg`. Solves the 109144 (WC24 Account not registered) error.
Also useful for registering accounts with WiiLink (#11903) for when that is supported.

IOS/KD: Implement Request Register User ID

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This fixes a frequently occurring JitArm64 assert which was caused by merging PR #9857 without adapting it to the changes made in PR #12138.

PPCAnalyst: Don't discard CR before gather pipe interrupt check

---

Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp

This must have broken in a rebase of one of my recently merged PRs.
Dolphin still worked correctly with this bug, for two reasons:
1. Most AArch64 users are not on Windows, and therefore normally do have the entry points map.
2. When the bug was triggered, Dolphin would fall back to the slower path rather than crashing.

JitArm64: Fix JitAsm without entry points map

---

Source/Core/Common/TraversalClient.cpp
Source/Core/Common/TraversalClient.h
Source/Core/Common/TraversalProto.h
Source/Core/Common/TraversalServer.cpp
Source/Core/Core/Config/NetplaySettings.cpp
Source/Core/Core/Config/NetplaySettings.h
Source/Core/Core/NetPlayClient.h
Source/Core/Core/NetPlayProto.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/NetPlayServer.h
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Source/Core/DolphinQt/NetPlay/NetPlayDialog.h

The currently popular methods for NAT traversal involve having two clients send each other a UDP packet. This adds an entry to their NAT, linking their endpoint to the other client, which means the other client can reply, allowing communication. However, this doesn't work for everyone: some NATs, upon receiving an unsolicited packet, will add an entry linking that packet's source to the NAT itself, which completely blocks communication. The solution is to ensure the first packet does not reach the other side, by giving it an appropriate TTL value.
Dolphin happens to be quite well set up for this: the host fires the first shot, so it can configure one TTL value to use for all connecting clients. I propose an additional input field on the netplay setup menu, where the desired TTL can be …

Traversal: Use low TTL for probe packet

---

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/MMU.h

This gets rid of the odd argument order we were using for JitArm64.

PowerPC: Unify "FromJit" MMU functions

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

See the individual commits for details.

JitArm64: Use ADDI2R for psq_lXX/psq_stXX immediate offsets

---

Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.h

If a download task was not found by the scheduler, it will set the time before next download to 11 minutes.

IOS/KD: Set download span if download task not found

---

Source/Core/Common/HttpRequest.cpp
Source/Core/Common/HttpRequest.h
Source/Core/Core/CMakeLists.txt
Source/Core/Core/IOS/Network/KD/Mail/MailCommon.h
Source/Core/Core/IOS/Network/KD/Mail/WC24FriendList.cpp
Source/Core/Core/IOS/Network/KD/Mail/WC24FriendList.h
Source/Core/Core/IOS/Network/KD/Mail/WC24Send.cpp
Source/Core/Core/IOS/Network/KD/Mail/WC24Send.h
Source/Core/Core/IOS/Network/KD/NWC24Config.cpp
Source/Core/Core/IOS/Network/KD/NWC24Config.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.h
Source/Core/Core/IOS/Network/KD/VFF/VFFUtil.cpp
Source/Core/Core/IOS/Network/KD/VFF/VFFUtil.h
Source/Core/DolphinLib.props

Implements the ability to send mail to other consoles and emails through the scheduler.
You might notice that `AddRegistrationMessages` is implemented and not used. That was a last minute decision made by me as if it were used it would infinitely send registration messages to the target console as we can never fully register them as a friend. That will be implemented in the receive ioctl.

IOS/KD: Implement Send Mail

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp

Dolphin would crash when running with a fastmem arena but without fastmem. This regression was caused by merging 9192128c50 without adapting it after the merge of 0606433404.

JitArm64: Fix updating MEM_REG with imm MSR without fastmem

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This should have been done when rebasing 6cc4f593e5 after the merge of 3a00ff625e. There are no correctness implications as far as I know, only very minor performance implications.

PPCAnalyst: Clear crInUse on HLE

---

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp

This PR fixes libogc `if_config` which fails to initialise because it uses ARP to check if the IP address offered by the DHCP is available. If it receives an ARP response, it declines the DHCP offer and return an error.
I haven't tested this PR on my BBA games yet but only tested it on some devkitPPC socket examples for GC homebrews.

BBA/HLE: Fix GC homebrew if_config not working

---

Data/Sys/GameSettings/RJ3.ini

This enables AccurateNaNs for "Jeep Thrills".
Solves the blue screen issue [Bug 13118](https://bugs.dolphin-emu.org/issues/13118)
Alternatively the issue is not present if bJITPairedOff = true in Jit64::ps_muls ie. Interpreter::ps_muls0/Interpreter::ps_muls1

Gameini: Enable AccurateNaNs for "Jeep Thrills"

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java

When Dolphin is not open, attempting to launch a game from a frontend launcher will result in the user opening Dolphin and being taken back to the frontend launcher. 
This is caused by calling `parent.finish()` before `AfterDirectoryInitializationRunner` is complete, thus canceling the launch of the game.
Fixed by calling `activity.finish()` after `AfterDirectoryInitializationRunner` is initialized and complete.

Android: Fix issue when launching a game when Dolphin is not open

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/BootManager.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.h

The changes in this PR are for improving when and how the AchievementManager loads games so it can properly protect against players switching apps and opening homebrews while properly allowing multi-disc or multi-file support. This will happen by calculating a new hash whenever the currently playing media changes, and shutting down the AchievementManager* if the new hash does not reference the same game as the previous hash.
*This does not load a new game, this closes the AchievementManager entirely and it will not be reopened until all games are closed and a new boot is performed.

RetroAchievements - Improved Game Loading

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/VideoCommon/OnScreenUI.cpp
Source/Core/VideoCommon/OnScreenUI.h

This is a portion of an integration with the RetroAchievements tools and libraries for connecting to the website, downloading data, unlocking achievements and submitting to leaderboards for games running in Dolphin. In this PR, I handle achievement events for when a "challenge" is "primed" or unprimed, and display the results on screen.
A "challenge" (not an official term) in this context is the completion of a portion of a game while meeting certain optional conditions. Examples would be completing a level in under a certain amount of time or a boss fight without taking damage. While a challenge is currently active, emulators that support RetroAchievements will display the achievement's badge in the corner of the screen to denote that the challenge is still active and valid. If the …

RetroAchievements - Challenge Icons

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/ConfigChangedCallback.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheManager.java
Source/Android/jni/AndroidCommon/IDCache.cpp
Source/Android/jni/AndroidCommon/IDCache.h
Source/Android/jni/CMakeLists.txt
Source/Android/jni/Config/ConfigChangedCallback.cpp

This way the Settings class doesn't contain a hardcoded reference to a specific setting. And Settings.loadSettings no longer calls getBoolean, which is a step towards fixing the crash when recreating EmulationActivity after process death.

Android: Use config changed callback for tracking recursive scan setting

---

Source/Core/VideoCommon/OnScreenUI.cpp

Fixed a bug in OSUI created by the challenge icons that caused a small rectangle to appear in the bottom right corner of the screen.

Bugfix - small square in bottom right corner

---

Source/Core/VideoBackends/Software/EfbCopy.cpp

The current implementation of [EfbCopy::ClearEfb](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/VideoBackends/Software/EfbCopy.cpp) doesn't check whether `left + bpmem.copyTexSrcWH.x` and `top + bpmem.copyTexSrcWH.y` are in-bound. This omission leads to an out-of-bounds write access with an arbitrary value. 
This issue can cause crashes and, in the worst-case scenario can lead to RCE on the host machine.
Here is a POC that triggers the bug:
```c++
// Setting corrupted width & height (max values are 2**10)
GX_SetDispCopySrc(640 - 1, 528 - 1, pow(2, 10), 1);
GX_SetDispCopyDst(rmode->fbWidth, xfbHeight);
// Trigger the vulnerability
GX_CopyDisp(xfb[curr_fb], GX_TRUE);
GX_SetCopyClear(background, GX_MAX_Z24);
``` 
> [!NOTE]
> This vulnerability can only be exploited with …

Fix out of bound write in EfbCopy::ClearEfb

---

Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp

WiimoteDevice spams DisasmDialog signals while a game is starting.  While booting, dolphin will incorrectly report as being paused, so a DisasmDialog update at that time will cause errors.  The pause/play button will update to the wrong state for a few moments. Debugger widgets will get triggered and the incorrectly reported pause state causes them to read instructions/memory when they shouldn't as well.
Even if the incorrect state reporting is fixed, this still doesn't need to spam signals while booting.
According to the comment in WiimoteDevice, DisasmDialog is used to update the Wiimote state in the menubar.  This has a few states:
1. Game is running. Will only be active while playing a game, otherwise disabled.
2.  BT passthrough. This can only be set when a game is not …

WiimoteDevice. Bugfix. Remove signal spam while starting a game.

---

CMakeLists.txt

Dolphin now relies on ENET_SOCKOPT_TTL which was [merged upstream](https://github.com/lsalzman/enet/pull/217) but not released yet. This fix assumes that enet continues its current versioning scheme.

CMake: update required enet version

---

Source/Core/VideoCommon/Present.cpp

There's no need to self reference a global of the class itself when we can just call the function directly.

VideoCommon/Present: Remove use of g_presenter inside Presenter class

---

Source/Core/Common/MemArena.h
Source/Core/Common/MemArenaWin.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp

A third possible fix https://bugs.dolphin-emu.org/issues/13387. This is probably the cleanest of the solutions.
Instead of allocating one big memory block from Windows, we just allocate a small 'zero block' and then map that repeatedly over the memory space. When a block is written to for the first time, we then swap the block of the region that is written to out with a fresh allocation. On clear, we map back to the zero block and deallocate the real data blocks.
I arbitrarily picked 8 MB for the block size. Larger blocks means better hit rate for already mapped blocks and a smaller lookup table for whether a block is already mapped, but potentially more memory wasted that's not actually being used.
Thanks to @PJB3005 for the idea, see …

Common/MemArenaWin: Rewrite LazyMemoryRegion by repeatedly mapping the same block of memory for unwritten regions.

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

Normally we only flush registers right at the end of each PPC instruction. However, for PPC instructions that use a lot of registers one at a time, it's beneficial to do this flushing work in the middle of the instruction instead, reducing the risk of register starvation and improving pipelining.

JitArm64: Flush in the middle of lmw/stmw/mfcr

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/Config/MainSettings.cpp
Source/Core/Core/Config/MainSettings.h
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/MenuBar.h

To aid in debugging, this makes it possible to disable the recently added 32/64 GiB region which hasn't had a proper name so far.

Add "large entry points map" setting

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp

If a is one of the registers that will be loaded/stored, we must not discard it early. Sorry for this fixup of a fixup...

JitArm64: Add additional condition for lmw/stmw a discard

---

Source/Core/Core/AchievementManager.cpp

I have a feeling the 'disabled' logic is gonna need a refactor in the future in general, but this should get rid of the message in the meantime.

AchievementManager: Only nag user about disabled achievements when they were actually enabled before.

---

Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp

Fixes the IPL fonts when you don't have a dump in your user directory. My bad.

HW/CEXIIPL: Fix loading files at nonzero offset in LoadFileToIPL().

---

Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

Custom asset data is loaded on a separate thread and stored in a `shared_ptr`.  When something wants some of that asset data, a copy of the `shared_ptr` will be provided.  At any time the separate thread can destroy the original `shared_ptr` copy, meaning something that wants to use that data must keep that `shared_ptr` around as long as it wants that copy of the data.
In `TextureCache`, I was loading a `shared_ptr`, getting a pointer to one of its member variables, then letting that `shared_ptr` copy die.  So it was undefined how long that member pointer would be valid.
A user on discord had a crash that looked eerily like it could be caused by this.  This PR fixes that issue by holding onto the `shared_ptr` instead of the member pointer.

VideoCommon: prevent a potential custom texture crash

---

Source/Android/app/build.gradle.kts

I needed this in my editor branch for some C++20 features that the current Android SDK was lacking.
@JosJuice / @t895

Android: update NDK to 26.1.10909125 in order to pick up new compiler features

---

Source/Core/DolphinQt/Config/ConfigControls/ConfigFloatSlider.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomShaderCache.cpp

Orders the initializer list the way that the members would actually be initialized in.
Resolves some -Wreorder warnings

General: Resolve -Wreorder warnings

---

Source/Core/UICommon/GameFile.cpp
Source/Core/UICommon/GameFile.h

GameFile: Default GameBanner operator==

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h
Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/BootManager.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/CoreTiming.cpp
Source/Core/Core/FreeLookConfig.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/State.cpp
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementLeaderboardWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp
Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
Source/Core/DolphinQt/Achievements/AchievementsWindow.h
Source/Core/DolphinQt/Config/FreeLookWidget.cpp
Source/Core/DolphinQt/HotkeyScheduler.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/VideoCommon/OnScreenUI.cpp

This is more idiomatic (and consistent with any other singletons we have) for accessing the instance itself. Changing `GetLock()` to return a reference makes using the returned mutex with any kind of scope guard a little more convenient, since there's no need to explicitly dereference the returned pointer.
Also gets rid of a decent chunk of unnecessary includes on the Qt side of things as well.

AchievementManager: Make GetInstance() and GetLock() return a reference

---

Source/Core/Core/WC24PatchEngine.cpp
Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/PostProcessing.cpp

Resolves warnings related to functions with external linkage not having any prototype declarations. In these cases, it's sufficient to make them internally linked with static.

General: Resolve -Wmissing-declaration warnings

---

Source/Core/DolphinQt/Config/GraphicsModListWidget.cpp

Translators should always know where text is going to be appended and have the ability to move things around to fit the language better.

GraphicsModListWidget: Add string specifier to By and Description fields

---

Source/Core/DolphinQt/Host.cpp
Source/Core/DolphinQt/Host.h

Gets rid of an unused static along with dead prototypes

DolphinQT/Host: Remove unused TLS variable tls_is_host_thread 

---

Source/Core/Common/SettingsHandler.cpp
Source/Core/Common/SettingsHandler.h

We can make AddSetting make use of std::string_view, and also greatly simplify the code doing the removal of the carriage returns.

Common/SettingsHandler: Minor convenience changes

---

Source/Core/Core/SyncIdentifier.h

Lets us remove a bunch of code and a dependency on the <tuple> header.

Core/SyncIdentifier: Default operator==

---

Source/Android/jni/AndroidCommon/AndroidCommon.h
Source/Core/Common/TraversalClient.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/UnitTests/Common/FloatUtilsTest.cpp

These spam the output log quite a bit (particularly the AndroidCommon one). These are easy enough to fix.

General: Resolve -Wsign-compare warnings

---

Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
Source/Core/InputCommon/ControlReference/ExpressionParser.h

A few cases were making copies of ControlQualifier instances, which hold 3 strings, so we can be churning memory a little. We can instead pass those by reference or move them instead.

ExpressionParser: Get rid of some redundant copies

---

Source/Core/VideoCommon/Assets/CustomAssetLibrary.cpp

There's a direct analogue of this function within DirectFilesystemAssetLibrary that *is* used, however, so we can get rid of this one.

CustomAssetLibrary: Remove unused GetAssetSize() function

---

Source/Core/DiscIO/RiivolutionPatcher.cpp
Source/Core/DiscIO/RiivolutionPatcher.h

The main interface for these only take in patches and iterate over them in a contiguous sequence, so we can reasonably generify the interface.
Also I noticed that there were a few global system `GetInstance()` calls present that could be removed via the use of CPUThreadGuard's GetSystem() member function instead, so those are included in a separate commit.

RiivolutionParser: Make use of std::span where applicable

---

Source/UnitTests/VideoCommon/VertexLoaderTest.cpp

The ways the assertion macros expand end up generating -Wdangling-else warnings. Trivial enough to fix by just bracing the if statements.

VertexLoaderTest: Resolve -Wdangling-else warnings

---

Source/Core/VideoBackends/D3D/D3DBoundingBox.cpp
Source/Core/VideoBackends/D3D/D3DBoundingBox.h
Source/Core/VideoBackends/D3D12/D3D12BoundingBox.cpp
Source/Core/VideoBackends/D3D12/D3D12BoundingBox.h
Source/Core/VideoBackends/Metal/MTLBoundingBox.h
Source/Core/VideoBackends/Metal/MTLBoundingBox.mm
Source/Core/VideoBackends/Null/NullBoundingBox.h
Source/Core/VideoBackends/OGL/OGLBoundingBox.cpp
Source/Core/VideoBackends/OGL/OGLBoundingBox.h
Source/Core/VideoBackends/Software/SWBoundingBox.cpp
Source/Core/VideoBackends/Software/SWBoundingBox.h
Source/Core/VideoBackends/Vulkan/VKBoundingBox.cpp
Source/Core/VideoBackends/Vulkan/VKBoundingBox.h
Source/Core/VideoCommon/BoundingBox.cpp
Source/Core/VideoCommon/BoundingBox.h

Crosses off a lingering TODO.
Also amends a few nearby cases where a u32 cast was being repromoted to size_t.

VideoCommon: Use std::span for BoundingBox::Write()

---

Source/Core/Core/IOS/Network/KD/Mail/WC24Send.cpp
Source/Core/Core/IOS/Network/KD/VFF/VFFUtil.cpp
Source/Core/Core/IOS/Network/KD/VFF/VFFUtil.h

Same behavior, but allows different containers to be used.
In one case it also gets rid of needing to construct a std::vector.

VFFUtil: Use std::span with WriteToVFF

---

Source/Core/Common/Debug/Watches.cpp
Source/Core/Core/ActionReplay.cpp
Source/Core/Core/GeckoCodeConfig.cpp
Source/Core/Core/HW/WiimoteEmu/I2CBus.cpp
Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/Socket.cpp
Source/Core/Core/PatchEngine.cpp
Source/Core/Core/SysConf.cpp
Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp

In several cases, using std::erase_if or std::erase greatly simplifies a lot of code compared to the remove-erase idiom.
Put into separate commits, but can be squashed if necessary.

General: Make use of std::erase_if/std::erase where applicable

---

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp

Regression from 5.0-20555 / #11988.
This should fix the various 'games no longer boot' issues we've had recently such as
https://bugs.dolphin-emu.org/issues/13428
https://bugs.dolphin-emu.org/issues/13425
https://bugs.dolphin-emu.org/issues/13419
I have verified that Resident Evil works again, the others should be confirmed separately.

JitCommon: Fix feature_flags truncation in index calculation.

---

Source/Core/Core/Debugger/PPCDebugInterface.cpp

We can just initialize register_index, even if it gets overwritten later on via Common::FromChars.

PPCDebugInterface: Silence trivial -Wmaybe-uninitialized warning

---

Source/Core/DolphinQt/CheatSearchWidget.cpp

Previously, the parameter wasn't being used, because it was being shadowed by another CPUThreadGuard at its only would-be usage point.

CheatSearchWidget: Make use of CPUThreadGuard parameter in UpdateTableRows()

---

Source/Core/Core/HLE/HLE_OS.cpp
Source/Core/Core/WC24PatchEngine.cpp
Source/Core/DolphinQt/Config/ConfigControls/ConfigFloatSlider.cpp
Source/Core/VideoCommon/LightingShaderGen.cpp

This should get rid of the remaining -Wshadow warnings in our code (on GCC 13 anyway, I don't know about Clang).

General: Resolve lingering -Wshadow warnings

---

Source/Core/VideoCommon/OpcodeDecoding.h

Had this happen recently and noticed that the popup message is useless for debugging.

VideoCommon: add message to XF load assert

---

Source/Core/VideoCommon/Assets/MaterialAsset.cpp
Source/Core/VideoCommon/Assets/MaterialAsset.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.cpp

This is another PR for adding support for custom shader uniforms to Dolphin.  This time, we extend the Material asset to include additional properties (int, int2, ... float, float2,...bool) and add some helper functions to get the material data to the GPU (not used yet, will be used in a future PR).

VideoCommon: add additional data types to material asset

---

Source/Core/Core/CPUThreadConfigCallback.cpp

This isn't used, but is likely kept around so the one-timed execution of a magic static is taken advantage of.
Technically this could also use `std::call_once` instead if that's a more preferable approach.
Resolves a -Wunused-but-set-variable warning.

CPUThreadConfigCallback: Mark static ID as [[maybe_unused]]

---

Source/Core/VideoBackends/Software/SWGfx.cpp
Source/Core/VideoBackends/Software/SWGfx.h

Fixes a build failure with clang 17.
The destructor needs to be in the cpp file, since we have a forward declared std::unique_ptr type as part of the class. So technically the default inline destructor could invoke without seeing the full data type definition.

Software/SWGfx: Default destructor in cpp file

---

Source/Core/Core/IOS/Crypto/Sha.cpp

Gets rid of a trivial warning with GCC by adding default handling for a missing enum value.

General: Resolve -Wswitch warnings

---

Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp

This function is used in debug asserts, so in release builds this will go unused and otherwise generate a warning.

DSPInterpreter: Mark IsProperlySignExtended() as [[maybe_unused]]

---

Externals/mbedtls/library/CMakeLists.txt

It's actually kind of wild that these flags are enabled by default for Clang. They produce an incredible amount of console output spam.
Let's remove them, especially since we've made other changes to this CMakeLists.txt
Just imagine pages and pages of this:

Externals/mbedtls: Disable -Wdocumentation related warnings

---

Source/Core/DolphinQt/GBAWidget.cpp
Source/Core/DolphinQt/GBAWidget.h

Previously we were always taking the buffer by value, even if it wasn't being stored anywhere and only read from.
We can use a std::span for the same thing.
Gets rid of a redundant copy of the video buffer in `GBAHost::FrameEnded()`

GBAWidget: Use std::span with SetVideoBuffer()

---

Source/Core/Common/Crypto/AES.cpp
Source/Core/Common/Crypto/SHA1.cpp

The alias for `__m128i` is typically something like:
```cpp
typedef long long __m128i __attribute__((__vector_size__(16), __may_alias__));
```
and the part that ends up not getting preserved is the `__may_alias__` attribute specifier.
So, in order to preserve that, we can just use a wrapper struct, so the data type itself isn't being passed through the template.

Common/Crypto: Resolve -Wignored-attributes warnings

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CoilUtils.kt

Allows the Coil memory cache to use up to 90% of the application's available memory. Previously this could cause problems with reloading images in very large libraries of games.

Android: Allow Coil image cache to use more memory

---

Source/Core/DolphinQt/GameList/GameListModel.cpp

A harmless case of it, but this can still cause warnings.

GameListModel: Remove fallthrough in data()

---

Source/Core/DolphinQt/Host.cpp

Quite a bizarre include.
Also resolves an indirect include (lol), since this TU was including the system header that way.

DolphinQt/Host: Convert inclusion of Fifo.cpp to Fifo.h

---

Source/Core/Core/HW/CPU.cpp

We can just pass in the m_system member instead.

HW/CPU: Remove remaining global system accessors

---

Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/MIOS.cpp
Source/Core/Core/IOS/MIOS.h

We can pass the system instance through the EmulationKernel instance.

IOS/MIOS: Eliminate global system accessors

---

Source/Core/Core/IOS/Network/NCD/Manage.cpp
Source/Core/Core/IOS/Network/NCD/WiiNetConfig.cpp
Source/Core/Core/IOS/Network/NCD/WiiNetConfig.h

We can pass in the existing system instance from the ncd/manage instance.

WiiNetConfig: Eliminate usages of the global system accessor

---

Source/Core/VideoBackends/Metal/MTLStateTracker.h

We're now hitting an out-of-bounds write assert in `RelWithDebInfo` builds after upgrading macOS to 14.2 and Xcode to 15.1. (found by @TellowKrinkle)

MTLStateTracker: Increase fragment buffer array size to 3

---

Externals/expr/include/expr.h

We already made changes to this library, so we can also resolve the lone shadowing warning within it
With this, most warnings for code that we control are all gone.
The main warnings left over are from mgba and cubeb (which both should *really* be checking if they're the top-level project, and disabling warnings for their code respectively if not)

Externals/expr: Resolve -Wshadow warning

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h

Two fixes: verify that there's an API token before attempting to automatically log in, and don't attempt to hash a game and load it unless achievements are enabled and the player is logged in. This prevents multiple API requests that we already know will fail, one of which will display an unnecessary error message to the player.

Retroachievements - Fixed Login Checks

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt
Source/Android/app/src/main/res/values/strings.xml
Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp

There aren't very many games (that we know of) that use arbitrary mipmap detection.  Users have noticed a number of games that have blurring or stuttering by turning this on.  It seems a lot more prevalent than the few games we are trying to fix with the option turned on.
I opened this for discussion, so curious on thoughts.
As an aside, my personal viewpoint is a heuristic is unnecessary and the targets that need arbitrary mipmap detection should be defined in configuration, instead of trying to figure out which ones they are.

Core: disable arbitrary mipmap detection by default

---

Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp

If Post-Processing Effect: (off) is selected or changed to this value, LoadShaderFromFile() attempts to read the non-existent (off).glsl file.
`VideoCommon/PostProcessing.cpp:56 E[Video]: Post-processing shader not found: {...}/dolphin/Build/Binaries/Sys/Shaders/(off).glsl`

VideoCommon: Fix "Post-processing shader not found" when (off) is selected.

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

Fixes a regression from PR #12124 that, depending on the host memory layout, could cause either a host crash or a guest crash when running F-Zero GX.

JitArm64: Use 64-bit register for address in mtsrin

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

JitArm64: Add rlwinmx case for only shifting

---

Source/Core/VideoBackends/D3D/DXTexture.cpp
Source/Core/VideoBackends/D3D12/DX12Texture.cpp
Source/Core/VideoBackends/Metal/MTLGfx.mm
Source/Core/VideoBackends/OGL/OGLTexture.cpp
Source/Core/VideoBackends/OGL/OGLTexture.h
Source/Core/VideoBackends/Vulkan/StateTracker.cpp
Source/Core/VideoBackends/Vulkan/VKSwapChain.cpp
Source/Core/VideoBackends/Vulkan/VKTexture.cpp
Source/Core/VideoCommon/AbstractTexture.cpp
Source/Core/VideoCommon/FrameDumper.cpp
Source/Core/VideoCommon/FramebufferManager.cpp
Source/Core/VideoCommon/OnScreenDisplay.cpp
Source/Core/VideoCommon/OnScreenUI.cpp
Source/Core/VideoCommon/PostProcessing.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureConfig.h

Dolphin leverages a (2D) texture array for all its GC/Wii native textures.  However, to support more interesting graphical features, I expanded to add cube map (#12061 ) support.  This worked but was done as a texture flag.  Now I want to add support for a standard 2d texture.  Having it as a flag is odd, so I introduced a new type enumeration that dictates what the texture format is.  At the moment, the possibilities are 2d texture array, 2d texture, or cube map.  In the future (if needed) this could be expanded to 3d textures, cube map arrays, etc as well.
This also adds support for 2d textures from a texture perspective (samplers need more work)
EDIT:  Thank you @TellowKrinkle for the help on the Metal backend.

VideoBackends / VideoCommon: add type enum to dictate how the texture is used; support texture 2d

---

Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/Assets/ShaderAsset.h

Mirroring the logic done in #12240 this adds a default value variant to the shader asset.  This value will be used to populate a material when it is initially created from a shader (and allowing the user to reset a modified value to the default if desired).
We also use the type information from the variant instead of an explicit type enum.

VideoCommon: update shader asset to provide a variant default value

---

Source/Core/VideoBackends/D3D12/D3D12Gfx.cpp
Source/Core/VideoBackends/D3D12/DescriptorAllocator.cpp
Source/Core/VideoBackends/Metal/MTLStateTracker.h
Source/Core/VideoBackends/Vulkan/ObjectCache.cpp
Source/Core/VideoCommon/Constants.h

I'm investigating changing the process of how graphics mod texture samplers are handled, instead of piggybacking off of the 8 pixel shader samplers that can be used on the native GC/Wii, the user can define their own samplers.
The question is how to handle this.  One way is to look at each backend and query what the sampler count is, then request that many resources.  However, this adds complexity to the code base.  Currently we have a hardcoded 8 which is assumed for the GC/Wii.  I'd like to expand this to 12 or 16 but not sure if some devices will see issues.
Opening this PR to do some testing and see what issues might occur on different devices with the hardcoded approach and will evaluate if using a more complex approach is needed.

VideoBackends / VideoCommon: update max pixel shader samplers from 8 to 16

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

This way we get some additional optimized cases for rlwnmx with imm b.

JitArm64: Call rlwinmx implementation from rlwnmx with imm b

---

Source/Core/Core/ConfigLoaders/MovieConfigLoader.cpp
Source/Core/Core/Movie.h

Fixes https://bugs.dolphin-emu.org/issues/10357 / https://bugs.dolphin-emu.org/issues/11827

Add SYSCONF widescreen setting to dtm header

---

Source/Core/Core/Config/GraphicsSettings.cpp
Source/Core/Core/Config/GraphicsSettings.h
Source/Core/Core/HW/VideoInterface.cpp
Source/Core/Core/HW/VideoInterface.h
Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GeneralWidget.h
Source/Core/DolphinQt/HotkeyScheduler.cpp
Source/Core/VideoCommon/Present.cpp
Source/Core/VideoCommon/Present.h
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h
Source/Core/VideoCommon/Widescreen.cpp
Source/Core/VideoCommon/Widescreen.h

This PR adds support for a user specified aspect ratio.
The main purpose of this is to allow users to play at specific game aspect ratios that don't match their screen.
For example, to play Super Mario Galaxy with the 21:9 cheat/mod, unless I had a 21:9 monitor, under normal circumstances I'd have to use the "Stretch" aspect ratio mode and size the window myself, by making a rough guess, withought having the possiblity of making the window fullscreen (black borders).
With this change it's now be possible to play (e.g.) games at 21:9 on both a 16:9 screen or a 32:9 one.
Another advantage this PR gives is that users can use the 1:1 aspect ratio, or the XFB native output aspect ratio (e.g. 640x528, pixel perfect nearest neighbor with no stretching). It's my understanding that this feature …

Add support for custom aspect ratios

---

Source/Core/Core/HW/EXI/EXI.cpp
Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.h

We can pass the core timing instance into the Init() call.

Core/EXI/EXI_DeviceMemoryCard: Remove global system accessor

---

Data/Sys/GameSettings/GC8JA4.ini

For buttons and some character icons the game loads palleted PNGs and tiles the pallet indices directly into C4 textures but fails to take into account that PNG and C4 use opposite nibble orders. This causes adjacent pixel columns to be swapped, see [issue 13370](https://bugs.dolphin-emu.org/issues/13370).
Also disable Immediate XFB for the Japanese release. It has the same black screen and flickering issues as the other regions.
Before:
After:

GameSettings: fix C4 texture tiling in Crash Nitro Kart

---

Source/Core/Core/Debugger/Debugger_SymbolMap.cpp
Source/Core/Core/Debugger/Debugger_SymbolMap.h
Source/Core/Core/PowerPC/Expression.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/DolphinQt/Debugger/CodeWidget.cpp

We don't need to pass in both a reference to a System instance and a CPUThreadGuard instance at the same time. We can just pass in the the cpu thread guard and retrieve the system instance from it.
Also removes an unused function and makes GetCallstack() a little nicer by moving callstack entries into the output vector instead of churning copies.

Core/Debugger_SymbolMap: Minor interface cleanup

---

Source/Core/Core/Debugger/PPCDebugInterface.cpp

We can use the CPUThreadGuard instance to get the active system instance.

Core/Debugger/PPCDebugInterface: Remove global system accessor

---

Source/Core/Core/HW/SystemTimers.cpp
Source/Core/Core/PatchEngine.cpp
Source/Core/Core/PatchEngine.h

We can pass the system instance into ApplyFramePatches() instead, especially considering the patch engine callback already has it available.

Core/PatchEngine: Get rid of global system accessors

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/HW/HW.cpp
Source/Core/Core/IOS/DI/DI.h
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/IOS.h
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/SSL.cpp
Source/Core/Core/IOS/Network/Socket.cpp

Removes all global system accessors in IOS.cpp. Most are resolved by just passing via parameters.
Given this moves quite a bit around, I've separated the changes into a few commits to make it easier to review.

Core/IOS/IOS: Remove global system accessors

---

Source/Core/Core/GeckoCode.cpp

We can use the CPUThreadGuard instance to retrieve the system instance instead.
Plus some minor changes noticed while in the area.

Core/GeckoCode: Remove global system accessors

---

Source/Core/UICommon/UICommon.cpp

This can be passed through via the IOS instance.

UICommon: Remove global system accessor in TriggerSTMPowerEvent()

---

Source/Core/Core/CheatSearch.cpp

We can retrieve the system via the CPUThreadGuard instances.

CheatSearch: Get rid of global system accessors

---

Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/ES/ES.h
Source/Core/Core/IOS/IOS.cpp

We can pass the core timing instance into the function.

Core/IOS/ES: Remove global system accessor in InitializeEmulationState()

---

Source/Core/VideoBackends/Vulkan/ObjectCache.cpp
Source/Core/VideoCommon/Constants.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionFactory.cpp

In #12370 I increased the max pixel samplers to 16, after having a handful of users test various backends and devices.  Unfortunately, my biggest fear came true, some Android devices seem to have issues with this change.  For reasons I can't explain, there are graphical issues that occur on some games (Zelda:WW and Zelda:TP were reported) on at least some devices (Pixel6).
The feature 12370 was implemented for was a new approach to how custom shaders are handled.  Given that custom shaders are an enhancement and could potentially be a heavy performance operation on weaker Android devices anyway, I've reverted the pixel shader count there and log an error saying custom shaders are unsupported on Android.
In the future, a more flexible approach could be looked at (for instance, changing the …

VideoCommon: revert max pixel samplers back to 8 for Android

---

Source/Core/Core/HW/GPFifo.cpp
Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/System.cpp
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/CommandProcessor.h
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/VideoBackendBase.cpp

Makes the use of the interface a little less noisy, especially given how much of the interface depends on an instance being present.

VideoCommon/CommandProcessor: Pass system instance through constructor

---

Source/Core/Common/Arm64Emitter.cpp

So somehow I forgot that AArch64 uses three-operand encoding...
Fixes a regression from 6303416201 which manifested in various ways, such as incorrect rendering of the Wind Waker title screen.

JitArm64: Fix the "do nothing" cases of ANDI2R and friends

---

Source/Core/Common/CMakeLists.txt
Source/Core/Common/TraversalServer.cpp
Source/Core/Core/DSP/DSPTables.cpp
Source/Core/Core/DSP/DSPTables.h
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/Network/IP/Top.cpp
Source/Core/Core/NetPlayServer.cpp

On macOS, we get some noisy warnings about sprintf
e.g.
Rather than disable the warning, it's trivial enough to just resolve them by converting over to fmt (which is better anyway, given the formatting is type generic).
The only remaining in-source usages now are confined to DSPAssembler (which isn't trivial to flip over).

Core: Use fmt over sprintf in trivial cases

---

Source/Core/Core/System.cpp
Source/Core/VideoCommon/BPStructs.cpp
Source/Core/VideoCommon/PixelEngine.cpp
Source/Core/VideoCommon/PixelEngine.h
Source/Core/VideoCommon/VideoBackendBase.cpp

Simplifies the interface in terms of usage. Also lets us get rid of a global system accessor and be consistent with most other manager types.

VideoCommon/PixelEngine: Passthrough system instance in constructor

---

Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/Network/Socket.cpp
Source/Core/Core/IOS/Network/Socket.h

This PR fixes the crash mentioned in https://dolp.in/i13442.
I suppose it's introduced in https://github.com/dolphin-emu/dolphin/pull/11767. Since the instance was moved to the kernel, it's destroyed when the kernel is. When the socket manager is destroyed so are its sockets which will abort pending operations. Pending operations relied on `GetIOS()` to abort them. However, this function will return `nullptr` on force shutdown because `s_ios.reset()` is called. So it wasn't able to call member functions of the IOS instance being destructed and was dereferencing `nullptr` instead.
I created a simple test case to reproduce the issue which is accepting a socket connection. You just need to run it _(and not connect to it)_, then force shutdown the homebrew by pressing the stop button twice on …

Socket: Fix a nullptr dereference when operations are pending

---

Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Source/Core/Core/IOS/Network/KD/NetKDRequest.h

In the last few months I've had a handful of random crashes when shutting down emulation which happened in NetKDRequestDevice::KDDownload().
The first was the result of using-after-freeing of some of NetKDRequestDevices's members by its WorkQueueThreads, which this PR resolves by calling the latter's Shutdown function in NetKDRequestDevice's destructor so the threads are finished before destroying any members.
The other crash was caused by one of two possible nullptr dereferences. The first is when calling GetIOS() in KDDownload(), which could return nullptr if called after IOS::HLE::Shutdown had reset s_ios. The other happened with the following sequence: 
* The work thread called GetIOS and got the non-null s_ios ptr.
* The CPU thread called s_ios.reset(), which runs EmulationKernel's …

NetKDRequestDevice: Fix sporadic crashes during emulation shutdown

---

Data/Sys/Shaders/default_pre_post_process.glsl

I noticed sharp bilinear was shifting pixels around when the dolphin emulation output image resolution exactly matched the window size (like, no rescaling at all, at native game resolution).
The top part of the image would shift up and the bottom one would shift down. Any other resampling method wasn't affected by this. I checked the reference code that inspired the feature, and noticed we used ceil instead of floor.
https://github.com/libretro/slang-shaders/blob/0830c831ce18cdd144d8447dc2bec8de498bd237/interpolation/shaders/sharp-bilinear-simple.slang
Flooring seems to make it look better in all cases from what I could see, and it's now even more similar to area resampling.
Video showcasing the problem (and how the fix behaves): …

Fix sharp bilinear using ceil instead of floor

---

Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp

Unfortunately this doesn't fix the missing reverb in Mario Kart Double Dash :/

DSPHLE/Zelda: fix use of wrong reverb buffer

---

Source/Core/Common/CommonFuncs.cpp

These messages can be localized, so we can't just assume it's all ASCII.

Common: Fix encoding handling in GetWin32ErrorString

---

Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Source/Core/InputCommon/ControllerInterface/ControllerInterface.h
Source/Core/InputCommon/ControllerInterface/CoreDevice.h
Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.h
Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.h
Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
Source/Core/InputCommon/ControllerInterface/InputBackend.cpp
Source/Core/InputCommon/ControllerInterface/InputBackend.h
Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.cpp
Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.h
Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.h
Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm
Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Source/Core/InputCommon/ControllerInterface/SteamDeck/SteamDeck.cpp
Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp
Source/Core/InputCommon/ControllerInterface/Wiimote/WiimoteController.cpp
Source/Core/InputCommon/ControllerInterface/Wiimote/WiimoteController.h
Source/Core/InputCommon/ControllerInterface/XInput/XInput.cpp
Source/Core/InputCommon/ControllerInterface/XInput/XInput.h
Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h
Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
Source/Core/InputCommon/ControllerInterface/evdev/evdev.h

This specific issue was already addressed by https://github.com/dolphin-emu/dolphin/pull/11635
though I felt like there was something more we could do, and wasn't too happy with the
likelihood of devices update calls being skipped (due to m_devices_population_mutex being locked).

Input: Improve Controller Interface devices threading

---

Source/Core/Common/StringUtil.cpp

They're not in the header so no one else can call them anyway.

Common/StringUtil: Use internal linkage for codepage conversion functions.

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp

This was introduced in 6a9f565ac4ddc65b2fdbf2293282ddd432ba89ae.

Fix Logic Inefficiency in Arm64GPRCache::FlushRegisters

---

Source/Core/Common/BitSet.h
Source/UnitTests/Common/BitSetTest.cpp

Use 1 of the same type as the stored value when shifting left during BitSet iterator incrementation. This prevents undefined behavior caused by shifting an int more than 31 bits in BitSet64.
Previously iterator incrementation could either hang or prematurely report it had reached the end of the BitSet64.

BitSet64: Fix iterator incrementation

---

Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp

Aims to fix https://bugs.dolphin-emu.org/issues/13444.

Jit: Reload RMEM/MEM_REG on ISI exception

---

Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/DolphinQt/Config/Graphics/GraphicsWindow.cpp

This fixes an issue where the game specific graphics backend would be saved as the global setting after playing a game.
This also now displays the currently running graphics backend when looking in the graphics configuration window.

Qt: Handle Overridden Graphics Backend

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp

JitArm64: Don't fall back to interpreter on low DCBZ hack

---

Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp

This fixes [issue 8034](https://bugs.dolphin-emu.org/issues/8034) (echo effect in Mario Kart Double Dash). The effect is not actually missing but simply too quiet.
The ucode does not multiply `vpb.dolby_volume_current` into the `quadrant_volumes` in-place like the HLE code does but instead does some redundant multiplies. The HLE code avoids this but then accidentally computes reverb volumes with two factors which both have been pre-multiplied by the current volume.

DSPHLE/Zelda: fix reverb volume being multiplied by current volume twice

---

Source/Core/VideoBackends/Vulkan/ObjectCache.cpp
Source/Core/VideoCommon/Constants.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionFactory.cpp

A user had reported that #12370 caused some graphical issues for them.  I made the PR #12456 to change the pixel sampler count back to 8 for Android builds and that was merged before the user had a chance to test it.  The actual issue was a JIT bug ( #12458 ).
This PR now reverts the samplers back to 16 on Android, making every platform consistent.
Apologies again for not marking 12456 as a draft originally.

VideoCommon: allow Android to take advantage of 16 pixel samplers once more

---

Source/Core/Core/Boot/Boot.cpp

We already have the System at all call sites.

Core/Boot: Avoid global system accessor when setting disc.

---

Source/Core/Core/Debugger/CodeTrace.cpp

In all instance this method is called, the instruction comes from SaveCurrentInstruction(), which already sets the address to the PC.
Avoids the use of the global system.

Core/CodeTrace: Take address from given instruction in GetInstructionAttributes().

---

Source/Core/Core/BootManager.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/Core.h

Gets rid of a few calls to `Core::System::GetInstance()`.

Core: Pass System through more of the emulation thread init process.

---

Source/Core/VideoBackends/Vulkan/VKGfx.cpp

When resizing the Dolphin emulation window (when using the Vulkan backend), you get greeted with this:
Along with (in the logs):
```
VideoBackends/Vulkan/VKGfx.cpp:287 E[MASTER]: Warning: Failed to grab image from swap chain: 0X3B9ACDEB VK_SUBOPTIMAL_KHR
```
Choosing to ignore for this session apparently causes no issues, so maybe it shouldn't pop up in the first place. Which is what this PR does.
I'm absolutely not sure whether this PR does the correct thing.
[Here's how PCSX2 does it.](https://github.com/PCSX2/pcsx2/blob/10389dc3f18a41ba84dd0fea5f95af9419918e59/pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp#L2379)

VKGfx: Don't panic for VK_SUBOPTIMAL_KHR

---

Data/Sys/GameSettings/SRQ.ini

This was causing the game to output thousands of FPS during the loading screen when it would run uncapped if Immediately Present XFB was enabled.
Please see [redmine 13447](https://bugs.dolphin-emu.org/issues/13447) for reference

Gameini: Disable "Immediately Present XFB" for Racquet Sports

---

Data/Sys/GameSettings/R8A.ini

This is another one of those games that has an optional screenshot feature where the images end up all black if you have Store EFB Copies to Texture Only turned on. Like for other such games, let's not force Store EFB Copies to Texture Only off, since it's a large performance impact for a feature most players won't use.
There's one wrinkle here. As part of teaching the player how to take screenshots, the game forces the player to take a screenshot before it lets them progress in the story. However, the game doesn't care what's in the screenshot, so you can progress just fine even if Store EFB Copies to Texture Only is turned on. I personally tested it.

GameSettings: Don't force EFB to RAM for PokéPark Wii

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h

The FlushMode enum was used only sometimes in JitArm64_RegCache. This refactor applies it everywhere relevant.

Arm64RegCache: Use FlushMode everywhere

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FloatSliderSetting.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.kt

The gate size is 79.37125 by default, and the step size is 0.5. Android throws an exception if we try to show the slider with the value set to something that isn't divisible by the step size. To avoid this problem, round the value.

Android: Fix crash when trying to edit gate size setting

---

Source/Core/Core/HW/DSPHLE/UCodes/AESnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.h

This changes the `AESndAccelerator` instance from global state to state local to each `AESndUCode` instance. I'm not sure whether this has side-effects (is this state intendend to persist across unload and reload of an UCode?), so this may need a different approach if it does.
Untested.

Core/DSPHLE: Move AESndAccelerator instance into AESndUCode.

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.h
Source/Core/Core/State.cpp

Genuinely don't understand why this was global state before. The entire state of the accelerator is reset on every call to GetInputSamples(), and that's the only function that uses it.

Core/DSPHLE: Deglobalize HLEAccelerator state in AX and AXWii UCodes.

---

Source/Core/Core/DSPEmulator.cpp
Source/Core/Core/DSPEmulator.h
Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/DSPHLE/DSPHLE.cpp
Source/Core/Core/HW/DSPHLE/DSPHLE.h
Source/Core/Core/HW/DSPHLE/MailHandler.cpp
Source/Core/Core/HW/DSPHLE/MailHandler.h
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AESnd.h
Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
Source/Core/Core/HW/DSPHLE/UCodes/CARD.cpp
Source/Core/Core/HW/DSPHLE/UCodes/GBA.cpp
Source/Core/Core/HW/DSPHLE/UCodes/GBA.h
Source/Core/Core/HW/DSPHLE/UCodes/ROM.cpp
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.h
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.h

~~There's two global Accelerator instances in AESnd and AXVoice that still need to be cleaned up, but otherwise this *should* be everything. I've left those out here because the lifetime requirements of those are rather unclear to me, so moving them eg. into the UCode classes could actually affect behavior, so it's better to have those as a separate PR for bisecting/debugging later.~~
This should be everything now.

Core/DSPHLE: Clean up global System access.

---

Source/Core/Core/HW/SI/SI_Device.cpp
Source/Core/Core/HW/SI/SI_Device.h
Source/Core/Core/HW/SI/SI_DeviceGBA.cpp
Source/Core/Core/HW/SI/SI_DeviceGBAEmu.cpp

We can just pass in the system timer instance where needed instead of using the global accessor

HW/SI: Remove remaining global system accessors

---

Source/Core/InputCommon/ControllerInterface/SteamDeck/SteamDeck.cpp

Also update the names of the setting post-Steam Deck commits to SDL
I believe this fixes https://bugs.dolphin-emu.org/issues/13412, but it needs more testing from people that aren't me.

Steam Deck: Pad out feature report to 64 bytes

---

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/MMU.h

For correctness, we need to check not only the start address of the memory access but also the end address.

PowerPC: Add access size parameter to MMU::IsOptimizableRAMAddress

---

Source/Core/Core/HW/HW.cpp
Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/WII_IPC.cpp
Source/Core/Core/HW/WII_IPC.h
Source/Core/Core/HW/WiimoteCommon/WiimoteHid.h
Source/Core/Core/HW/WiimoteEmu/Camera.cpp
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
Source/Core/Core/IOS/Device.h
Source/Core/Core/IOS/IOS.cpp
Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp
Source/Core/Core/State.cpp
Source/Core/Core/System.cpp
Source/Core/Core/System.h

Also adds two variables to savestates that previously weren't stored.

Core/IOS/WiiIPC: Refactor to class, move to System.

---

Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsMod.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsMod.h
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModAsset.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModAsset.h
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModFeature.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModFeature.h
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTarget.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTarget.h
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTargetGroup.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTargetGroup.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp

Pulled out from #12280 .  Used to write the metadata back when saving the editor changes.

VideoCommon: add ability to serialize graphics mod to json object

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

It seems like I made a small mistake in PR #12320. Locking W0 when `jo.memcheck` is true is only necessary for load instructions, not store instructions.

JitArm64: Remove unnecessary locking of W0 in psq_stXX

---

Source/Core/DolphinQt/Debugger/AssembleInstructionDialog.cpp
Source/Core/DolphinQt/Debugger/AssemblerWidget.cpp

This reverts the parts of commit c8c9928eb1 that made translatability worse rather than better. Changing "Error in column %2" to "%1 in column %2" not only means that the translators have to check the i18n comments to know what word hides behind %1, but there's also the problem that the translator might need to translate "Error" in this context differently from the standalone string "Error". Having to copy-paste some HTML tags may be annoying for translators, but it's a far less serious problem.

Partially revert "DolphinQt/Assembler: improve translatability"

---

Source/Core/VideoCommon/VideoBackendBase.cpp

Fixes https://bugs.dolphin-emu.org/issues/13302. I've verified that Intel HD Graphics 3000 boots games again in D3D11 with this change, though obviously bounding box based effects (tested in TTYD) are still broken.

VideoCommon: Only initialize Bounding Box if supported by GPU/driver.

---

Data/Sys/GameSettings/RTK.ini

This game requires safe texture cache accuracy for dialog text to render correctly

GameINI: Octomania text fix

---

Source/Core/DolphinQt/Debugger/AssemblerWidget.cpp

Putting the handling of the dirty flag in only one string makes it clearer for translators what's going on.

DolphinQt: Rework dirty flag handling in AssemblerWidget::TabTextForEditor

---

Source/Core/Core/Core.cpp

This reverts commit e86d713600b5e97af9904518b47152c97949c85e.
A proper fix was added in 86c1f6e1e7e2abcc3f42e1182134e632b218b6d3, so the workaround is no longer necessary.

Revert "Android: Attach CPU thread to JVM early"

---

Source/Core/Common/CMakeLists.txt
Source/Core/Common/JsonUtil.h
Source/Core/DolphinLib.props
Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/Assets/ShaderAsset.h

This adds a way to serialize a shader asset to json.  This will be used in the editor to serialize changes out to disk (see #12280 )  
This also adds a way to calculate the default value of a shader asset property value given a typename (used in the editor when picking a typename from a drop down) and to get a list of typenames available for the shader asset (used to populate a drop down in the editor with available types).

VideoCommon: add some helper functions for shader asset

---

Source/Core/Core/PowerPC/Jit64/RegCache/FPURegCache.cpp
Source/Core/Core/PowerPC/Jit64/RegCache/FPURegCache.h
Source/Core/Core/PowerPC/Jit64/RegCache/GPRRegCache.cpp
Source/Core/Core/PowerPC/Jit64/RegCache/GPRRegCache.h
Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.cpp
Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.h

Given we have fixed allocation orders, we can just directly return a span instead of a pointer and a size via an out parameter.
Makes it a little more convenient, since we get both pieces of info at once, and also have the ability to iterate directly off the span out of the box.

Jit64/JitRegCache: Simplify GetAllocationOrder()

---

Source/Core/Core/Config/AchievementSettings.h

Makes the header a little more consistent with others (and also we should still have a header guard be present at all times).

AchievementSettings: Move pragma once out of ifdef

---

Source/Core/DolphinQt/Debugger/GekkoSyntaxHighlight.cpp

Copy-paste error. Ultimately GPR and FPRs use the same highlighting style anyway, so this is mostly just a correctness change.

GekkoSyntaxHighlight: Fix FPR terminal highlighting being treated as GPRs

---

Source/Core/Core/Debugger/CodeTrace.cpp

`std::set`'s `lower_bound()` is optimized better than the generic implementation of `std::lower_bound()` (because it's tailored to handle bidirectional iterators)
`std::lower_bound()` works best on random access iterators, where the number of comparisons can be logarithmic. However, since `std::set`'s iterators are bidirectional iterators, the comparisons will actually be linear in practice when using `std::lower_bound()`.
So, we can use `std::set`'s version which is guaranteed to be logarithmic.

CodeTrace: Use std::set::lower_bound() over std::lower_bound()

---

Source/Core/Core/HW/EXI/EXI_DeviceAGP.cpp
Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp

Silences some compiler warnings

Core: Get rid of some unannotated fallthrough cases

---

Source/Core/DolphinQt/MenuBar.cpp

Fixes a little visual inconsistency in the UI, where the assembler would always be shown, but all other debug-related utilities would be hidden.

DolphinQt/MenuBar: Hide assembler option if debug UI is disabled

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/Config/AchievementSettings.cpp
Source/Core/Core/Config/AchievementSettings.h

The Host URL setting in the RetroAchievements config will, if set, be used as the host URL for all server requests for achievements. This allows for an easy switch to the RetroAchievements staging server for testing.

Add host URL setting to achievements config

---

Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionData.h
Source/Core/VideoCommon/VertexManagerBase.cpp
docs/CustomPipelineGraphicsMod.md

We're finally close to finishing out this saga.  Custom pipeline action (the graphics mod action used to handle drawing with custom shader pipelines) is getting some major updates after a number of PRs were merged.
* A variety of texture samplers are now supported.  Cube maps, generic 2D, and even your own arrays.  This means users can supply textures that have their own sampler properties, as well as not be tied to the game texture's resolution
* No longer is the shader/texture asset updates tied to the texture create/load events for graphic mods.  This fixes a bug where targeting EFBs with a custom shader required targeting an additional non-EFB texture to trigger
* Prepares for graphics mod 2.0 by passing all texture units to the graphics mod action.  This will fix any issues with …

VideoCommon: update custom pipeline action to support a variety of texture samplers, support for materials, and more!

---

Source/Core/VideoCommon/Assets/ShaderAsset.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsMod.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModAsset.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModFeature.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.h
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTarget.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTargetGroup.cpp

Lets us construct some elements directly inside the container as opposed to moving into them and also makes it shorter to read in certain instances.
(note: in GraphicsTarget, the "projection" string for the ProjectionTarget visitor would always get overwritten, so I removed it. If that was intended to actually be a meaningful string, let me know)

GraphicsMod/ShaderAsset: Lessen object churn a little bit

---

Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.h

We pass a JIT instance all the way down to EmuCodeBlock, which is accessible under protected as well, so this isn't really necessary.

Jit64AsmCommon: Remove redundant m_jit member from CommonAsmRoutines

---

Source/Core/Core/IOS/Network/KD/NetKDTime.cpp
Source/Core/Core/Movie.cpp
Source/Core/Core/Movie.h
Source/Core/Core/State.cpp

fmt provides general drop-in thread-safe replacements for a few time handling functions, so we can move over to those to make several functions thread-safe, getting rid of the need to be extra careful when using them.

Core: Make use of reentrant time utilities where applicable

---

Source/Core/Common/Matrix.cpp
Source/Core/Common/Matrix.h

Just trying to make our matrix class a little more general purpose.
I was looking at some functionality for determining the winding order of a (GLTF) mesh and found out you can calculate this by determining if the global transform's determinant is negative.  Not sure if this will be something I use or not but wanted to make these changes in case I decide to do that.

Common: add determinant functions to Matrix33 and Matrix44

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

The type checking is duplicated here, which makes this seem a little weird, so we can get rid of it.

PPCAnalyst: Merge duplicate expression in ReorderInstructionsCore()

---

Source/Core/VideoCommon/PostProcessing.cpp

All `release()` does is relinquish the pointer, rather than free the memory associated with it.

PostProcessing: Don't potentially leak memory in BlitFromTexture()

---

Source/Core/Core/AchievementManager.cpp

post_data included passwords and API keys in plaintext so continuing to include it in logs is a security liability.

Removed post data from Achievement request logs

---

Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VertexManagerBase.h

This PR refactors drawing into its own function during a flush so that it can be reused in the future (multi-pass drawing for custom shaders and/or custom meshes).
Pulled out of #12280

VideoCommon: refactor drawing into its own function

---

Source/Core/DolphinLib.props
Source/Core/VideoCommon/CMakeLists.txt
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomPipeline.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomPipeline.h

Right now the custom pipeline logic is in a specific graphics mod class.  However, I have other use cases for how that functionality could be used, so I decided to move it to another class.
Pulled out of #12280

VideoCommon: refactor the custom pipeline logic to be reusable

---

Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/UberShaderPixel.cpp

These have been there a while but I just happened to notice them when testing some changes in my editor PR.
Two issues fixed:
* We deal with floats for color information so that users don't have to deal with integer math.  However, if the shader uses integer based colors for output, the custom shader will fail with an error
* When per pixel lighting is not defined, we shouldn't be trying to use pixel lighting uniforms in the pixel shader because they won't exist!
These bugs are present in both our specialized and uber pixel shaders.

VideoCommon: fix some issues when compiling custom shaders

---

Source/Core/Core/AchievementManager.cpp

rcheevos expects these multi-byte peeks to have the opposite endianness so they need to be swapped before rcheevos gets them.

Reverse endianness of achievement memory peeks

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp

I from what I can tell, `ARM64FloatEmitter::ABI_PushRegisters` expects an XReg temporary, not a WReg. Otherwise, it may emit code with incongruent usage of WRegs then XRegs:
This causes a segmentation fault. While I have never witnessed this happening from the usage in `JitArm64::dcbx`, it's better in principle to fix it. This error mislead me in my own usage of `ARM64FloatEmitter::ABI_PushRegisters`. It may be worth adding a runtime assertion in `ARM64FloatEmitter::ABI_PushRegisters` to enforce this.

Add Missing EncodeRegTo64 in JitArm64::dcbx

---

Source/Core/VideoCommon/NativeVertexFormat.h
Source/Core/VideoCommon/RenderState.h
Source/Core/VideoCommon/TextureConfig.h
Source/Core/VideoCommon/VertexLoaderBase.h

We can specify the `std::` portion on the struct to perform the specialization instead of creating a namespace, which makes things a little less noisy.

VideoCommon: Collapse hash specialization namespaces

---

Source/Core/DolphinQt/Config/GraphicsModListWidget.cpp
Source/Core/DolphinQt/Config/GraphicsModListWidget.h
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.cpp
Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.h

Allows using keys that aren't directly std::string as the key. This lets us use std::string_view for the incoming path name, making it more flexible with other string types.
Forgot that I noticed this when doing the picojson changes until now.

GraphicsModGroup: Allow heterogenous lookup for GetMod()

---

Source/Core/Common/HookableEvent.h
Source/Core/Core/FifoPlayer/FifoRecorder.cpp
Source/Core/VideoCommon/BPStructs.cpp
Source/Core/VideoCommon/FrameDumper.cpp
Source/Core/VideoCommon/FramebufferManager.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomShaderCache.cpp
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp
Source/Core/VideoCommon/Present.cpp
Source/Core/VideoCommon/ShaderCache.cpp
Source/Core/VideoCommon/Statistics.cpp
Source/Core/VideoCommon/TextureCacheBase.h
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoEvents.h
Source/Core/VideoCommon/Widescreen.cpp

Instead, we make the event take a reference to the system and then pass it in when the event is triggered.
This does introduce two other accessors, but these are much easier to refactor out over time, and without modification to the existing event interface.

VideoCommon/Statistics: Remove global system accessor from s_after_frame_event

---

Source/Core/Core/ConfigManager.cpp
Source/Core/Core/ConfigManager.h
Source/Core/DolphinQt/MenuBar.cpp
Source/Core/DolphinQt/MenuBar.h

This has been dead since at the very least the move to Qt, possibly longer.
This was apparently used at one point to automatically start a game when Dolphin was opened, a feature which can easily be replicated with a batch file.
https://github.com/dolphin-emu/dolphin/blob/3570c7f03a2aa90aa634f96c0af1969af610f14d/Source/Core/DolphinWX/Main.cpp#L285

Core/ConfigManager: Remove dead bAutomaticStart flag.

---

Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomPipeline.cpp

We can just use holds_alternative here instead.
Also addresses two other minor things that were noticed when crossing this warning off.

CustomPipeline: Resolve unused variable warning 

---

Source/Core/VideoCommon/VertexLoaderManager.cpp

This isn't used anywhere, so it can be removed.

VertexLoaderManager: Remove unused entry struct

---

Source/Core/Core/CheatSearch.cpp
Source/Core/DolphinQt/CheatSearchWidget.cpp

Core::RunAsCPUThread is obsoleted by CPUThreadGuard reference already passed into the function. The nonsense lambda in CheatSearchWidget is from changes in fdb7328c737f2bba148b903491b66fa62cc03703.

CheatSearch: Remove redundant lambdas

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/controlleremu/EmulatedController.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/ProfileDialogPresenter.kt
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
Source/Android/jni/Input/EmulatedController.cpp
Source/Core/Core/FreeLookManager.cpp
Source/Core/Core/HW/GBAPad.cpp
Source/Core/Core/HW/GCKeyboard.cpp
Source/Core/Core/HW/GCPad.cpp
Source/Core/Core/HW/Wiimote.cpp
Source/Core/Core/HotkeyManager.cpp
Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
Source/Core/InputCommon/InputConfig.cpp
Source/Core/InputCommon/InputConfig.h
Source/Core/InputCommon/InputProfile.cpp

Fixes an regression from PR #12215 where the Android GUI would write an incorrect game INI key when setting a per-game profile for a GameCube controller, as well as a much older bug that affects loading GameCube keyboard controller profiles from a game INI on all platforms. Read the commit descriptions for details.

InputCommon: Fix profile path inconsistencies

---

Source/Core/Common/Arm64Emitter.cpp

Unlike ADD (immediate), MOV (register) treats SP as ZR. Therefore the ADDI2R optimization that was added in 67791d227c can't optimize ADD to MOV when exactly one of the registers is SP.
There currently isn't any code in Dolphin that calls ADDI2R with parameters that would trigger this case.

Arm64Emitter: Don't optimize ADD to MOV for SP

---

Source/Android/app/src/main/res/values/strings.xml

Google Play's policies require us to tell the user the size of any large download.
The size seems to vary by just a megabyte or two across regions in my testing, so I'm listing a rough size for all the regions.
I'm also taking the opportunity to shorten the message to make it easier to read.

Android: Mention download size in the Wii Menu not installed message

---

Source/Core/Core/HW/EXI/EXI_DeviceEthernet.cpp

This PR prevents Dolphin from being killed when receiving `BBA_IOB`. Apparently, in some circumstances, the game might be in such situation and it might be non-fatal. For instance, when sending tons of UDP packet to an unbound port this situation can happen. This seems to only affect BBA TAP adapter.
I was able to replicate the issue on Windows 10 _(OpenVPN 2.4.11's TAP Adapter V9)_ with Mario Kart: Double Dash and Kirby Air Ride. It happens during the matchmaking sequence, right after Dolphin's BBA acquired an IP address and announced it via ARP.
The following python script can be used to spam UDP packets to an unbound port _(Wireshark can be used to find Dolphin's BBA IP using arp filter)_:
```python
#! /usr/bin/env python
from random import randint
from socket import *
def …
```

EXI: Don't kill Dolphin when receiving BBA_IOB

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp

This fixes an issue introduced by 3b0444be6bf38ca5c20f5b9b8916c54fd8f6fa36 where the m_accelerator would not be initialized when loading a savestate if the current UCode mismatched the UCode in the savestate, leading to a crash.

Core/DSPHLE: Construct accelerator in AX and AXWii constructors.

---

Source/Core/VideoCommon/Assets/CustomAssetLibrary.h
Source/Core/VideoCommon/Assets/CustomAssetLoader.cpp
Source/Core/VideoCommon/Assets/CustomAssetLoader.h
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp
Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.h
Source/Core/VideoCommon/Assets/MeshAsset.cpp
Source/Core/VideoCommon/Assets/MeshAsset.h

Now that the mesh asset is an object we can fill out.  Custom mesh loading can be added to the asset loader for use by the rest of the system.
The custom mesh still isn't renderable (coming in a future PR) but it can be loaded if called in code!

VideoCommon: make mesh asset data loadable by asset loader

---

Source/Core/Common/IOFile.h

When performing a default compilation with recent GCC & glibc, the use of -Werror=nonnull causes a build error.
The error is given as IOFile::ClearError() can call std::clearerr() with a null file, which can trigger a null-pointer dereference in libc.
Change the std::clearerr() call to be conditional on a file being open.

IOFile: avoid clearing errors on null file struct

---

Source/Core/DolphinTool/ConvertCommand.cpp

Use "bzip2" instead of "bzip" in optparse's compression choices for the convert command. This is both more accurate and matches what the ParseCompressionTypeString function expects.
The mismatch between the two parsing functions prevented compression using bzip2 because either ParseCompressionTypeString or optparse would generate an error when using "bzip" or "bzip2" respectively.
Fixes https://bugs.dolphin-emu.org/issues/13427
This appears to have been broken since DolphinTool was created so there shouldn't be any backward compatibility issues.

DolphinTool: Fix parsing of command line bzip2 flag

---

Source/Core/VideoCommon/Assets/CustomAssetLoader.cpp
Source/Core/VideoCommon/Assets/CustomAssetLoader.h

When assets exceeded the reserved memory limit (ex: a large texture pack), we were going over that reserved amount because we were not stopping future loads of assets from occurring (we were only reporting it).  This should hopefully fix the crash that a user was seeing.  Will see if they can test.

VideoCommon: handle asset memory going over reserved limit correctly

---

Source/Core/DolphinQt/Config/ToolTipControls/BalloonTip.cpp
Source/Core/DolphinQt/Config/ToolTipControls/BalloonTip.h
Source/Core/DolphinQt/Config/ToolTipControls/ToolTipWidget.h

Rework BalloonTip drawing to resolve the following issues:
* Fix irregularly shaped corners
Before: 
After: ![corners after](https://github.com/dolphin-emu/dolphin/assets/73494713/82b852e0-025b-47e3-a76c-c8a47caab0de)
* Remove extra space for BalloonTips with no message or no title
Before:
After:
* When the target tip location is not on a screen, put the tooltip on
the mouse's screen instead of the primary screen
* Fix message getting cut off when the title was too long
Before:
After:
* Expose border width as a parameter
* Fix spacing and sizing issues with larger border widths
Before border 5:
After border 5:
Before border 20:
After border 20:
Before border comically large:
After border comically large:
Note: The second commit is purely for reviewing purposes, and lets you …

Balloontip drawing rework

---

Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/UberShaderPixel.cpp

A nonzero index makes no sense for framebuffer fetch (where are you reading from?), and Mesa doesn't like it when you supply an index.  I can't understand GLSL spec well enough to tell whether it should be allowed or not, but we might as well not do it.
Fixes ubershader compiles on the upcoming Asahi Linux OpenGL 3.3 driver.
Please test whatever Android phones use framebuffer fetch and make sure I didn't break anything for them

VideoCommon: Don't use indexed output for fbfetch

---

CMakeLists.txt

I've been experimenting with embedding Dolphin as a dependency with CMake's `FetchContent`, but the use of `CMAKE_USER_MAKE_RULES_OVERRIDE` complicates this; the various compiler flag checks use this option, but they all fail with errors similar to the following:
```
-- Performing Test FLAG_C_HAVE_SSE2
CMake Error at C:/Users/Jesse/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeRCInformation.cmake:27 (include):
include could not find requested file:
CMake/FlagsOverride.cmake
Call Stack (most recent call first):
C:/Users/Jesse/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/Platform/Windows-MSVC.cmake:530 (enable_language)
C:/Users/Jesse/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/Platform/Windo …
```

Simplify including Dolphin via `FetchContent`

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/Core.cpp
Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp

Most obviously, there is no longer a warning message to the player in the achievement window that achievements are disabled if a game is not currently running.

Improved achievements disabled messaging

---

Source/Core/Core/IOS/FS/HostBackend/FS.cpp

A user on Discord is running into this assert and I'm not sure how that's possible, so log more info here.

IOS/FS: Display the invalid path in the ASSERT in BuildFilename().

---

Source/Core/Common/CMakeLists.txt
Source/Core/Common/TimeUtil.cpp
Source/Core/Common/TimeUtil.h
Source/Core/Core/State.cpp
Source/Core/DolphinLib.props

This is an old bug that was originally fixed by 99a3bbc0552cfea13cd2928c67e53c7638b289ac and then re-introduced by 6a86b35e88be70eb1d01573f08a1df35696d47f1 when switching to `fmt::localtime()`, which throws on invalid input instead of returning, which crashes Dolphin because we build without exceptions.

Core: Fix crash when inspecting a savestate with a timestamp that causes localtime() to error out

---

Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/CustomPipelineAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/MoveAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/PrintAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/ScaleAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/Actions/SkipAction.h
Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionFactory.cpp

This just moves the factory names to be a static inside each class so that they can be reused in the future when serializing any action data.

VideoCommon: move factory names to be a static inside each action class

---

Source/Core/Core/AchievementManager.cpp
Source/Core/Core/AchievementManager.h

Two minor updates to improve the Achievement Manager's handling of a player's completion rate.
One, if an achievement is counted for zero points (either it's actually zero and serves as an alert, as some sets do, or it's counted as zero because it's unofficial) it now also doesn't contribute to the number count of achievements.
Two, the determinations for mastery/completion are now improved to check (1) that the achievement triggering this is not a zero-point achievement and (2) that it has not already been unlocked at this level on the site, which should be sufficient to determine that the unlocking of this particular achievement completes/masters the game.

Fixes to Achievement points count/mastery

---

Source/Core/VideoCommon/Widescreen.cpp
Source/Core/VideoCommon/Widescreen.h

Fix aspect ratio heuristics getting stuck to widescreen (or to non widescreen) (`m_is_game_widescreen` variable) if the user first forced the aspect ratio to 16:9/4:3 and then set it back to Auto.
This specifically happens in games 2D main menus, which have no 3D graphics so the aspect ratio heuristics fail to determine whether the game was widescreen or not. The behaviour can be replicated in _The Legend of Zelda: Four Swords Adventures_ 60Hz mode.
Video showcasing the problem:
https://github.com/dolphin-emu/dolphin/assets/7011366/fad3c4e3-ba1b-4c09-89f4-976ec3fac3d1

Fix aspect ratio heuristics getting stuck to a state

---

Source/Core/Core/AchievementManager.cpp

Failing to do this was causing challenge icons to carry over into the next game if a game was closed while the icons were active, even if the next game to run was a completely different game entirely with completely different badges.

Clear active challenges when game closes

---

Source/Core/DolphinQt/Debugger/CodeWidget.cpp

This seems to be the more modern way of doing case-insensitive QString comparisons. It's probably faster, too.

CodeWidget: Simplify Case-Insensitive Contains

---

Source/Core/VideoCommon/VertexManagerBase.h

Ensures that this always has a deterministic value on construction like everything else in the class.

VertexManagerBase: Initialize m_ticks_elapsed on construction

---

Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Source/Core/DolphinQt/HotkeyScheduler.cpp
Source/Core/VideoCommon/Present.cpp
Source/Core/VideoCommon/VideoConfig.h

Follow up to https://github.com/dolphin-emu/dolphin/pull/12170 as discussed there and on discord.
Specifically, this PR adds a "Custom Relative" aspect ratio, meaning that the user specified aspect ratio will relative to the VI determined aspect ratio. This means that specifying 4:3 and 16:9 as custom relative ARs will act identically as selecting 4:3 and 16:9 as aspect ratio mode.
This also adds a "Raw" aspect ratio mode to see pixels 1:1 with no scaling at all. This has been long asked by users.
Video:
https://github.com/dolphin-emu/dolphin/assets/7011366/bc761acf-6a1a-4387-9787-c7f00af3c251

Add Custom Relative and Raw (Squared Pixels) aspect ratios

---

Source/Core/Core/AchievementManager.cpp

Check an achievement's category and only request RetroAchievements to award if it is CORE and not UNOFFICIAL.

Don't Publish Unofficial Achievements

---

Source/Core/Core/AchievementManager.cpp

Not only was the extra call to the update callback in the AchievementEventHandler method unnecessary, it was getting called on events that don't even need to be tracked here, causing a lot of lag when it turned out one achievement was repeatedly spamming Achievement Reset Events as a shortcut.

Remove the update callback on all events

---

Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp
Source/Core/DolphinQt/Debugger/BranchWatchDialog.h
Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Source/Core/DolphinQt/Debugger/CodeWidget.h

Window icon was missing from QDialog lacking a parent.
Giving the QDialog a parent revealed I had failed to make it properly non-modal, necessitating further changes.
Settings save less often, now only upon destruction.
Construction of BranchWatchDialog is now deferred.

BranchWatchDialog: Fix Misc. Errata

---

Source/Core/Core/PowerPC/PPCSymbolDB.cpp
Source/Core/Core/PowerPC/PPCSymbolDB.h

This can be accessed through the CPUThreadGuard.

PPCSymbolDB: Eliminate Redundant Member

---

Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp

WiimoteReal: fix typo in WiimoteReal.cpp

---

Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp

My bad, I was using Clang instead of GCC and failed to notice these false-positive -Wshadow warnings.

BranchWatchDialog: Fix GCC Warnings

---

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp

It seems the BBA/HLE interface doesn't set the TCP push flag when receiving data. The data might not be processed immediately if the PSH flag isn't set. The following filter in Wireshark usually don't display packets on network dumps but surprisingly does with BBA/HLE network dumps: `tcp.len > 0 && tcp.flags.ack == 1 && tcp.flags.push == 0`.
~~I'll set it as a draft for the time being until it's tested and/or a hardware test written.~~
Here is a hardware test and the associated network dumps captured from dolphin without this PR, with this PR and Wireshark:
[net_http_get_loop.zip](https://github.com/dolphin-emu/dolphin/files/14349147/net_http_get_loop.zip)
**NB:** The IP address and domain are hardcoded (93.184.216.34, www.example.com), so please make sure they are still valid before …

BBA/HLE: Add missing PSH flag

---

Source/Core/Core/DSP/Jit/x64/DSPJitRegCache.cpp

A `DynamicReg` instance is 80 bytes in size, and we iterate over an array of 37 of them, so this just gets rid of some unnecessary copy churn.

DSPJitRegCache: Take DynamicReg instances by reference in FlushRegs()

---

Data/Sys/GameSettings/REG.ini

Fixes hang on game loading by turning off dual core. Sorry for submitting the same pull request twice, I had to close the old one because I accidentally added a second commit and Github wouldn't let me get rid of it

GameINI: Fix Emergency Mayhem hang on loading

---

Source/Core/DolphinQt/CheatSearchWidget.cpp
Source/Core/DolphinQt/CheatSearchWidget.h
Source/Core/DolphinQt/CheatsManager.cpp
Source/Core/DolphinQt/CheatsManager.h
Source/Core/DolphinQt/MainWindow.cpp

OnResetClicked and GenerateARCode appear to have been using the CPUThreadGuard in error.

CheatsManager/CheatSearchWidget: Avoid Global System Accessor

---

Source/Core/AudioCommon/CubebUtils.cpp

Cubeb logs a message at CUBEB_LOG_NORMAL verbosity every time you start or stop a stream which can get a bit annoying when using frame advance at Dolphin's default verbosity.

Cubeb: change log level from NOTICE to INFO

---

Source/VSProps/Base.props

I'm using vcpkg on my machine and this resulted in multiple defined symbols because vcpkg dependencies were being pulled in.

VSProps: Set VcpkgEnabled to false

---

Source/Core/AudioCommon/CubebUtils.cpp

Follow-up to #12638. I blindly changed the level without checking whether it had any effect. `LogWithFullPath()` doesn't check whether the log level is enabled, it only uses it for printing.

Cubeb: check correct log level

---

Data/Sys/GameSettings/GPH.ini

Based on Billiard's recommendations in this discussion: https://discord.com/channels/521709831132807179/521711075721478145/1216164450936160417
I've tested a handful of menus, cutscenes, FMVs, ~~and the first 10 minutes of gameplay. I still want to play past the final boss with this before publishing the PR because I know the post-credit loads have weird aspect ratio even on console.~~
Myself and another community member have played through the entire game, including minigames, w/o issue.

Fix aspect ratio swapping in Pitfall: The Lost Expedition

---

Source/Core/VideoCommon/VideoBackendBase.cpp

Modern hardware has better performance with D3D.
Outdated hardware has better compatibility with D3D.
Uninformed Windows uses are leaving performance and compatibility on the table with OpenGL defaults.

VideoCommon: Prefer D3D11/12 over OpenGL on Windows.

---

Source/Core/Core/Core.cpp
Source/Core/Core/Core.h

This small function has been unused for a very long time. I believe the last uses for it were removed in  dfe84ce0acf288157a867f0df1678930b281fd40 (Feb 3, 2011) and fb4c82fb48b756b348140993c36d3177a869aa52 (Feb 15, 2011). Despite being unused, it was greatly simplified by a81631b58e3a77f8d088c574fc048f3fb37a7c51 (May 25, 2012) to simply return the result of `IsRunning() && IsCPUThread()`. I say it's time to let this function retire.

Core: Remove Unused IsRunningInCurrentThread Function

---

Source/Core/DolphinQt/Config/ToolTipControls/BalloonTip.cpp

This fixes `BalloonTip` showing up at totally wrong x positions or on completely wrong monitors.
Things still get funky at screen edges, but that hasn't changed.

DolphinQt: Fix BalloonTip positioning on secondary monitors.
