dolphin-emu/dolphin

Data/Sys/Shaders/PerceptualHDR.glsl, Source/Core/VideoBackends/Metal/MTLMain.mm, Source/Core/VideoBackends/Metal/MTLUtil.h, Source/Core/VideoBackends/Metal/MTLUtil.mm
This PR:
1. Add HDR to Metal
3. Add PerceptualHDR
PerceptualHDR Menu:
=> Add HDR to Metal + Perceptual HDR

Source/Core/Common/JsonUtil.cpp, Source/Core/Common/JsonUtil.h
This adds some more utility functions to help with writing `picojson` logic.  `ReadStringFromJson` and `ReadBoolFromJson` were added to match the existing numeric capability.  They all now return a `optional` as that was more flexible than passing in the default.
Similarly, I updated `ToJsonArray` to support any array type that the json library natively supports (strings or bools).
=> Common: add even more json utility functions

Source/Core/InputCommon/GCAdapter.cpp
This is a replacement for PR #5799.
Apparently the 16ms timeout can be a little too tight for usbip.
Fixes: https://bugs.dolphin-emu.org/issues/10408
100ms is mentioned to be satisfactory.
Note that transfers are done in threads. Increasing this timeout will not slow down emulation. It will reduce the responsiveness of controllers when the higher timeouts were necessary, as opposed to entirely not working.
=> GCAdapter: Adjust libusb transfer timeout to 100ms.

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/BootManager.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/Core/HW/VideoInterface.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp, Source/Core/Core/Movie.cpp, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinNoGUI/PlatformFBDev.cpp, Source/Core/DolphinNoGUI/PlatformHeadless.cpp, Source/Core/DolphinNoGUI/PlatformMacos.mm, Source/Core/DolphinNoGUI/PlatformWin32.cpp, Source/Core/DolphinNoGUI/PlatformX11.cpp, Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/MainWindow.cpp
Part 1 of an effort to remove global state from one of the biggest offenders.
=> Core: Avoid (Some) Global System Accessor

Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp
Not sure if the behavior I'm implementing here is what real hardware does, but since this is a buffer overflow, I'd like to get it fixed quickly. Hardware verification can happen later.
https://bugs.dolphin-emu.org/issues/13506
=> Core: Fix IPL device m_cursor overflow

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/Core/HW/Wiimote.cpp, Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, Source/Core/Core/PowerPC/JitInterface.cpp, Source/Core/DolphinQt/Host.cpp, Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/MainWindow.cpp
Part 2b of an effort to remove global state from one of the biggest offenders.
It's a fine function, but CPUThreadGuard is more vogue. Also, its potential for being confused with RunOnCPUThread will not be missed. If `Core::RunAsCPUThread` should not be removed for some reason, let me know.
=> Core: Remove RunAsCPUThread

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.h, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.h, Source/Core/DolphinQt/Debugger/RegisterWidget.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.h, Source/Core/DolphinQt/Settings.h
As small as it may be, this is an unnecessary copy.
=> DolphinQt Settings: Signal Debug Font By Const Reference

Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/Core/Movie.cpp, Source/Core/Core/State.cpp, Source/Core/DolphinQt/GBAWidget.cpp
Part 2a of an effort to remove global state from one of the biggest offenders.
=> Core::RunOnCPUThread: Avoid Global System Accessor

Source/Android/app/src/main/res/values/arrays.xml, Source/Android/app/src/main/res/values/strings.xml
This PR simply exposes the tapserver options in Serial Port 1 on Android. They already exist and work, but are not selectable.
I've tested the tapserver options myself with Phantasy Star Online Episode I & II and they work fine.
=> Add tapserver BBA and Modem Adapter UI options to Android

Source/Core/Common/FileUtil.cpp
I mistakenly put `D_DUMP_IDX` here instead of `D_DUMPDEBUG_IDX`. Note that, in practice, the BranchWatch user folder appears where I intended, so I don't know what would cause this erroneous statement to overwrite the correct location set on line 861.
=> FileUtil: Fix BranchWatch User Path

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/Boot/Boot.h, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/Host.h, Source/Core/Core/IOS/MIOS.cpp, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.h, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp, Source/Core/DolphinQt/Debugger/CodeWidget.h, Source/Core/DolphinQt/Host.cpp, Source/Core/DolphinQt/Host.h, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h, Source/Core/DolphinTool/ToolHeadlessPlatform.cpp, Source/DSPTool/StubHost.cpp, Source/UnitTests/StubHost.cpp
There were three distinct mechanisms for signaling symbol changes in DolphinQt: `Host::NotifyMapLoaded`, `MenuBar::NotifySymbolsUpdated`, and `CodeViewWidget::SymbolsChanged`. The behavior of these signals has been consolidated into the new `Host::PPCSymbolsUpdated` signal, which can be emitted from anywhere in DolphinQt to properly update symbols everywhere in DolphinQt.
This PR:
- Addresses a DolphinQt shortcoming I found while creating Branch Watch Tool, and resolves a TODO left in its design.
- Does not fix widgets that currently do nothing to update symbols properly, such as BreakpointWidget.
- Does not communicate to Core when symbols are changed, which is relevant to obscure mechanisms such as JitRegister.
I am open to critique on the design and location of the new signal.
=> DolphinQt: A Ubiquitous Signal For When Symbols Change

Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureCacheBase.h, Source/Core/VideoCommon/TextureUtils.cpp, Source/Core/VideoCommon/TextureUtils.h
This allows users to place already handled textures in subdirectories and easily spot newly dumped textures for purposes of texture pack creation. They can relocate the files into subdirectories either during or outside of emulation.
Note that the directory is scanned upon first dump. Files moved completely outside of the texture dumping directory during emulation will not enable them to be re-dumped until the next emulation session as the scan is only done once.
This is a behavior change. Previously, `File::Exists` was used on every dump attempt.
Fixes: https://bugs.dolphin-emu.org/issues/4411
The feature is always enabled (as long as texture dumping is on).
I don't think this needs a setting to turn it on/off. It's minimally resource intensive compared to the actual texture dumping …
=> VideoCommon: Scan texture dumping directory + subdirectories to not re-dump existing files.

Source/Core/Core/HW/DSPHLE/UCodes/ASnd.cpp, Source/Core/Core/HW/DSPHLE/UCodes/ASnd.h, Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp
@Wohlstand realized that the left and right channels are reversed by the asnd uCode, observable with e.g. a stereo file played with the oggplayer example. (But the oggplayer uses a mono file by default, where this is not observable). See devkitPro/libogc#169. This was fixed in devkitPro/libogc#170.
Dolphin already had those channels swapped (matching the behavior of the previous uCodes), and also already had a variant that swapped the channels back (#11354, from the desert bus homebrew, which has other weird quirks).
[asnd_2024_versions.zip](https://github.com/dolphin-emu/dolphin/files/14736472/asnd_2024_versions.zip)
```
Hashes of 2024/DSP_UC_5DBF8BF1.bin: ector 5dbf8bf1 crc ce5e93e7 adler 490ec76d 0606 bytes (0303 words)
Hashes of 2024/DSP_UC_373A950E.bin: ector 373a950e crc 4548a0e4 …
```
=> DSPHLE: Implement 2024 libasnd uCodes

Source/Core/Core/HW/Memmap.h, Source/Core/Core/IOS/Device.cpp, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/ES/Identity.cpp, Source/Core/Core/IOS/ES/TitleContents.cpp, Source/Core/Core/IOS/ES/TitleManagement.cpp, Source/Core/Core/IOS/ES/Views.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.cpp, Source/Core/Core/IOS/Network/IP/Top.cpp, Source/Core/Core/IOS/Network/SSL.cpp, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/IOS/Network/Socket.h, Source/Core/Core/IOS/Network/WD/Command.cpp, Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/Core/IOS/WFS/WFSI.cpp, Source/Core/Core/IOS/WFS/WFSSRV.cpp
Typically when someone uses GetPointer, it's because they want to read from a range of memory. GetPointer is unsafe to use for this. While it does check that the passed-in address is valid, it doesn't know the size of the range that will be accessed, so it can't check that the end address is valid. The safer alternative GetPointerForRange should be used instead.
Note that there is still the problem of many callers not checking for nullptr.
This is the first part of a series of changes that will remove the usage of GetPointer in different parts of the code base. This commit gets rid of every GetPointer call from our IOS code except for a particularly tricky one in BluetoothEmuDevice.
=> IOS: Remove calls to GetPointer

Source/Core/DolphinQt/CheatSearchFactoryWidget.cpp, Source/Core/DolphinQt/CheatSearchWidget.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp
Move CheatManager's child widgets into scroll areas to allow making the window smaller than the default, as one can already do with many of Dolphin's other windows.
In CheatSearchWidget, enable word wrapping for the label describing the address space and search type to help it fit better inside a narrower window.
=> CheatsManager: Allow making the window smaller

Source/Core/Core/HW/Memmap.cpp
`IOS::HLE::IOCtlVRequest::Dump` sometimes tries to call `GetPointerForRange` with an address of 0 and a size of 0. Address 0 is valid, but we were mistakenly also trying to check that address 3FFFFFFF is valid, which it isn't.
Fixes https://bugs.dolphin-emu.org/issues/13514.
=> Memmap: Don't show panic alert for 0 length range

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp, Source/Core/Core/HW/EXI/BBA/BuiltIn.h
While writing a hardware test, I found that `connect` was implemented as always being successful. The previous implementation assumed that the connection succeeded (whereas it hasn't yet). Then, a game might call `send`/`recv` which will fail but will be reported as successful as well. So the game will assume the data is properly handled when in reality it wasn't since the socket wasn't properly connected yet. It also means sent data is lost since it was assumed as successful so the game has no way to know it failed.
This PR defers the successful connect packet and depends on https://github.com/dolphin-emu/dolphin/pull/12533 for the time being. Here is a test case (based on the previous hardware test) but with an unreachable IP address hardcoded instead of example's one: …
=> BBA/HLE: Don't assume connect is successful

Source/Core/Core/Movie.cpp
=> Movie: simplify silly loop

Source/Core/Core/Debugger/Debugger_SymbolMap.cpp, Source/Core/Core/Debugger/Debugger_SymbolMap.h, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.h
Part 3 of stopping using GetPointer. This gets rid of the last GetPointer call in IOS, which I skipped in part 1.
=> IOS::HLE::BluetoothEmuDevice: Remove calls to GetPointer

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
When writing the software FMA code, I didn't realize that we can't overwrite d if d is the same register as one of the inputs and HandleNaNs is going to be called. This fixes that.
=> Jit64: Preserve inputs when software_fma && m_accurate_nans

Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.cpp
Currently the dialog makes you wait one second before it shows anything. Instead, trigger the first scan manually.
=> Qt: trigger first USB device scan without a timer

Source/UnitTests/Common/SettingsHandlerTest.cpp
This PR adds tests verifying that an LF is added if the first attempt to encode a line results in a null byte, and that another LF is added if the second encoding attempt again results in a null byte. It also adds corresponding tests of decrypting the resulting buffers.
=> Add SettingsHandler unit tests exercising the edge case fixed in PR #8704

Source/Core/VideoCommon/BPStructs.cpp, Source/Core/VideoCommon/OpcodeDecoding.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/XFStructs.cpp
This fourth part of my series of patches to get rid of unsafe uses of GetPointer takes care of the "easy" cases in VideoCommon. Three uses of GetPointer now remain in Dolphin: VertexLoaderManager, TextureInfo, and the software renderer's TextureSampler.
=> VideoCommon: Remove calls to GetPointer

Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp, Source/Core/InputCommon/ControlReference/ControlReference.h, Source/Core/InputCommon/ControlReference/ExpressionParser.cpp, Source/Core/InputCommon/ControlReference/FunctionExpression.cpp, Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.cpp, Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h
The problem:
When the "..." button is clicked, the numeric setting is converted to an input expression. Unfortunately integers are also valid keyboard `Input` names and get handled by `CoalesceExpression`.
Despite the expression being 1, the "Sideways Wii Remote" setting turns off, because the keyboard's 1 key is not being pressed..
When the dialog is closed, the expression is correctly converted to a simple `true` value, but in the meanwhile, it's `false`, which is especially strange when quickly opening and closing the advanced window.
The Wii Remote Extension setting has the same issue.
The solution:
The sign of the value is always included to not match any `Input` names.
Alternatively, instead of always including the `+` sign, decimal places could be always included, but this is maybe …
=> NumericSetting: Stop values from binding to numbered input names.

Source/Core/DolphinQt/Config/VerifyWidget.cpp, Source/Core/DolphinQt/Config/VerifyWidget.h
Removing the private `slots` macro is necessary to avoid the MOC requiring `Core::State` to be a Qt meta type on Linux (would require including Settings.h). The `slots` macro is not required in Qt5+ regardless.
=> VerifyWidget: Listen for Core::State OnEmulationStateChanged

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
It was possible for sAlertMessageLock.notify() to be called before sAlertMessageLock.wait(), causing Dolphin to deadlock. In particular, this was guaranteed to happen if displayAlertMsg was called from the UI thread while the emulation activity is being destroyed, because runOnUiThread runs the passed-in anonymous function immediately when called from the UI thread.
By replacing Object.wait/Object.notify with Semaphore.acquire/Semaphore.release, it no longer matters what order the methods are called in.
=> Android: Fix race condition in displayAlertMsg

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/TaskDialog.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/UserDataImportWarningDialog.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/TaskViewModel.kt
Also tweak the API so that the caller-specified `task` returns a result directly, instead of requiring it to internally call `setResult`. This refactoring has a few benefits:
1. The compiler now requires the task to complete with a result, preventing mistakes where the caller forgets to call `setResult`.
2. All task-related state is updated atomically, so observers will never transiently observe inconsistent states where the task is completed but no result is available, or the task is "not running" but isn't yet "complete."
This PR also fixes a bug where calling `runTask` on a completed `TaskViewModel` would cause its task to re-run even if `clear` hadn't been called first.
I tested this PR by exporting and importing user data in the app running on an emulator.
=> Refactor `TaskViewModel` to track task-related state in a single `MutableLiveData` instance

Data/Sys/Shaders/PerceptualHDR.glsl
This is a rather Niche, but fairly large improvement to the PerceptualHDR Shader.
Turns out that the HLG (Hybrid Log Gamma) response function is becoming more popular, and people are phasing out the PQ EOTF function. I decided to try using the HLG function in the perceptual shader, and it tracks a lot better with what the shader is supposed too look like. 
Before Graph:
After Graph:
Apparently when using PQ's EOTF, the derivative near zero isn't even 1. I did not really account for this. But when using HLG, it tracks a lot better:
Try to look at the dark areas, it will show you why this HLG is superior:
**SDR:**
**HLG:**
**EOTF:**
It's hard to tell because these are not HDR screenshots, however it is apparent when viewing that when using the HLG transfer function, the amount of alteration …
=> Use Hybrid Log Gamma in PerceptualHDR

Source/Core/Core/ConfigLoaders/GameConfigLoader.cpp
After digging into configuration loading, I wanted to give a try at tackling a bug I discovered a while ago
( https://bugs.dolphin-emu.org/issues/13096 )
Currently, Dolphin only recognize PadProfileX (pointing to the "GCPad" folder) and WiimoteProfileX (pointing to the "Wiimote" folder) for loading controller mapping parameters.
As such, it's not currently possible to specify a GBA control map in a game-specific INI (unless you step in relative paths territory).
Since GBA profiles are stored in their own third folder, I propose to add a third parameter "GBAProfileX", using the very same loading process and naming convention as the other two.
Since this wasn't supported before, this shouldn't have adverse effect (even for people like me using relative paths, the relative path would still …
=> Fix path-loading of GBA map configurations

Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h, Source/Core/VideoCommon/FrameDumper.cpp, Source/Core/VideoCommon/FrameDumper.h, Source/Core/VideoCommon/Present.cpp, Source/Core/VideoCommon/Present.h, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
Allows the frame dumper to use the raw emulation output (XFB) resolution, avoiding any scaling if possible.
This should make comparisons much more reliable as pixels wouldn't be smushed together or stretched.
Currently even if `bInternalResolutionFrameDumps` is enabled, dumps are done after scaling to the target aspect ratio (which is almost always different from the raw emulation render), so they aren't really raw, they are scaled, but they scaling isn't done with gamma correction as the post process effects pipeline doesn't run on them.
This PR adds an enum with 3 dumping resolution choices:
Some possible future improvements related to this:
- Save the target aspect ratio number in the output file name, so it could be stretched in post.
- Remove the `VIDEO_ENCODER_LCM` (4) limit, or …
=> Frame dump at raw internal resolution

Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
Current compilers don't seem to optimize this automatically.
https://alive2.llvm.org/ce/z/dbNnec
=> DSPHLE/Zelda: simplify AFC decoding

Source/Core/InputCommon/ControllerInterface/Android/Android.cpp, Source/Core/InputCommon/ControllerInterface/Android/Android.h, Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp, Source/Core/InputCommon/ControllerInterface/ControllerInterface.h, Source/Core/InputCommon/ControllerInterface/InputBackend.cpp, Source/Core/InputCommon/ControllerInterface/InputBackend.h, Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.cpp, Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.h, Source/Core/InputCommon/ControllerInterface/Quartz/Quartz.h, Source/Core/InputCommon/ControllerInterface/Quartz/Quartz.mm, Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm, Source/Core/InputCommon/ControllerInterface/Win32/Win32.cpp, Source/Core/InputCommon/ControllerInterface/Win32/Win32.h, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h
This makes the handling of input backends uniform within ControllerInterface.cpp.
End behavior should be mostly unchanged.
This is a precursor to some future input-related cleanups.
=> Implement missing InputBackend classes.

Source/Core/InputCommon/ControllerInterface/Android/Android.cpp
This was broken by a9a9fdd9e9. Because Init didn't run, the Android input backend would crash whenever it tried to call into JVM code.
=> Android/ControllerInterface: Run the init code

Source/Core/Common/SettingsHandler.cpp, Source/Core/Common/SettingsHandler.h, Source/Core/Core/Boot/Boot_BS2Emu.cpp, Source/Core/Core/IOS/DolphinDevice.cpp, Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp, Source/UnitTests/Common/SettingsHandlerTest.cpp
`SettingsHandler::Buffer` is a type alias to a `std::array` of `u8`. Moving a `std::array` of primitives doesn't actually avoid any copies, since the elements are stored inline (https://stackoverflow.com/a/28988913). Changing these methods to take a const ref instead of an rvalue ref makes it clear that we are actually copying the arrays.
=> Pass `SettingsHandler` buffers by const ref instead of rvalue ref (since the contents are copied either way)

Source/Core/Core/Debugger/DebugInterface.h, Source/Core/Core/Debugger/Debugger_SymbolMap.cpp, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/Debugger/PPCDebugInterface.h, Source/Core/Core/PowerPC/PPCSymbolDB.cpp, Source/Core/Core/PowerPC/PPCSymbolDB.h, Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/ThreadWidget.cpp, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/QtUtils/FromStdString.h
Should save a lot of deep copies.
=> PPCSymbolDB: GetDescription by std::string_view

Source/Core/Common/FileUtil.cpp
Neglecting this case in `File::RebuildUserDirectories` leaves `RetroAchievements.ini` in `/home/<username>/.local/share/dolphin-emu/Config/` rather than `/home/<username>/.config/` as expected.
=> RetroAchievements: Put "RetroAchievements.ini" in the correct config location for POSIX

Source/Core/AudioCommon/AudioCommon.cpp
Set the default sound backend to cubeb instead of the default
being none.
=> Set default sound backend on OpenBSD to cubeb

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp, Source/Core/Core/HW/EXI/BBA/BuiltIn.h, Source/Core/Core/HW/EXI/EXI_DeviceEthernet.h
This PR is based on https://github.com/dolphin-emu/dolphin/pull/12533 and https://github.com/dolphin-emu/dolphin/pull/12555. I needed to refactor it to deduplicate parts of the code and to allow some parts to be easier to modify in the future.
It shouldn't have any functional change.
=> BBA/HLE: Code refactoring

Source/Core/AudioCommon/AudioCommon.cpp
Default to Cubeb instead of the NULL backend on Linux when ALSA isn't valid.
=> AudioCommon: When ALSA is absent on Linux, default to Cubeb backend

Source/Core/VideoCommon/Present.cpp, Source/Core/VideoCommon/VideoEvents.h
Dolphin doesn't have a good idea of when a frame is "finished".  If a game uses a single XFB as its presentation, then we can assume that the XFB creation is a good indication.  However, there are many cases where this is not accurate (see the article about [hybrid xfb](https://dolphin-emu.org/blog/2017/11/19/hybridxfb/)).
@phire [theorized](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/VideoCommon/BPStructs.cpp#L351) that you could look at the VI settings to determine when a frame would be finished in the future.  Discussing with @booto , I do not see how you could deduce this with any accuracy.
However, my editor PR and graphics mods 2.0 are _highly dependent_ on knowing when the frame ends.  Not only is it used for tracking objects in the scene but also it is used for …
=> VideoCommon: add xfbs hashes to present info if available

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h, Source/Core/VideoCommon/Statistics.cpp, Source/Core/VideoCommon/Statistics.h, Source/Core/VideoCommon/VertexManagerBase.cpp, Source/Core/VideoCommon/VertexManagerBase.h, Source/Core/VideoCommon/Widescreen.cpp
This is useful to find widescreen heuristic game ini values after PR #11419 and #12169.
=> VideoCommon: Show average projection to viewport ratio for widescreen heursitic game ini values.

Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h, Source/Core/UICommon/GameFileCache.cpp
Append (Disc 1) label to the first disc of two-disc games, rather than only labelling the second disc.
I don't own any two-disc games so my testing was necessarily hacky; if someone with a larger collection can test it with some real two-disc games that'll be helpful.
I got the list of game ids from the wiki, so hopefully that template is complete.
=> GameList: Show (Disc 1) for first disc of two-disc games

Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/FS/HostBackend/FS.cpp, Source/Core/Core/IOS/IOS.cpp, Source/Core/UICommon/ResourcePack/ResourcePack.cpp
I am currently working on some additions to this Clang-Tidy check, and running it on some C++ codebases to test my changes.
This should be safe as it seems Dolphin requires a C++ standard and/or a compiler version that will always have `starts_with` included. (In CMakeLists: C++23 for MSVC, GCC 10, Clang 12). Dolphin builds on my setup following changes.
```
python3 ~/llvm-project/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py \
-clang-tidy-binary="~/llvm-project/build/bin/clang-tidy" \
-clang-apply-replacements-binary="~/llvm-project/build/bin/clang-apply-replacements" \
-checks="-*,modernize-use-starts-ends-with" \
-header-filter=".*" \
-fix -format
```
This improves readability. There's also a theoretical performance improvement replacing `find(...) == 0` by `compare(...) == 0` or …
=> Apply Clang-Tidy's modernize-use-starts-ends-with

Source/Core/Core/PatchEngine.cpp, Source/Core/Core/PatchEngine.h, Source/Core/Core/PowerPC/JitCommon/JitBase.h, Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.h, Source/Core/Core/PowerPC/PPCAnalyst.h
Almost every place I found pretends this is unsigned anyway. PatchEngine acknowledges `downcountAmount` is an int... and casts a `u32` into an `int` in doing so. `BeginProfiling` and `EndProfiling` I wrote, so I know that's fine to change too. `BlockStats::numCycles` only ever has unsigned values added to it, and only ever adds to `downcountAmount`.
=> Change JitState::downcountAmount to a u32

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.h
`RCOpArg::ExtractWithByteOffset` is only used in one place: a special case of `rlwinmx`. `ExtractWithByteOffset` first stores the value of the specified register into `m_ppc_state` (unless it's already there), and then returns an offset into `m_ppc_state`. Our use of this function has two undesirable properties (except in the trivial case `offset == 0`):
1. `ExtractWithByteOffset` calls `StoreFromRegister` without going through any of the usual functions. This violated an assumption I made when working on my constant propagation PR and led to a hard-to-find bug.
2. If the specified register is in a host register and is dirty, `ExtractWithByteOffset` will store its value to `m_ppc_state` even when it's unnecessary. In particular, this always happens when `rlwinmx` uses the same register as …
=> Jit64: Clean up ExtractWithByteOffset

Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.h, Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h
If "Relative Input" is enabled then "Mouse Controlled Pointing" will not work properly.
Some users don't understand the "Relative Input" setting so it's probably a good idea to set it for them.
=> DolphinQt/Mapping: Disable relative input when "Mouse Controlled Pointing" button is pressed.

Source/Core/Core/HW/EXI/BBA/TAPServerConnection.h
This also fixes a -Wshadow warning because there is a function-local equivalent in ReadThreadHandler().
=> TAPServerConnection: drop unused enum class ReadState

Source/Core/Common/CMakeLists.txt, Source/Core/Common/SpanUtils.h, Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/FifoPlayer/FifoRecorder.cpp, Source/Core/Core/HW/Memmap.cpp, Source/Core/Core/HW/Memmap.h, Source/Core/DolphinLib.props, Source/Core/VideoBackends/Software/TextureSampler.cpp, Source/Core/VideoCommon/BPStructs.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureDecoder.h, Source/Core/VideoCommon/TextureDecoder_Common.cpp, Source/Core/VideoCommon/TextureInfo.cpp, Source/Core/VideoCommon/TextureInfo.h, Source/Core/VideoCommon/VertexLoaderManager.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp, Source/Core/VideoCommon/VideoState.cpp
To ensure memory safety, callers of GetPointer have to perform a bounds check. But how is this bounds check supposed to be performed? GetPointerForRange contained one implementation of a bounds check, but it was cumbersome, and it also isn't obvious why it's correct.
To make doing the right thing easier, the first commit of this PR changes GetPointer to return a span that tells the caller how many bytes it's allowed to access. Then, the second commit adds bounds checks to two of the three callers of GetPointer. The third caller, VertexLoader, will have to wait due to its tight optimization.
=> Memmap: Replace GetPointer with GetSpanForAddress

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
This lets us avoid `avx_op`'s "ugly" case.
=> Jit64: Inline avx_op into fp_arith

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SettingViewHolder.kt
Because `SettingViewHolder` is used in `RecyclerView`s, we have to explicitly unset `STRIKE_THRU_TEXT_FLAG` when we don't want it, otherwise it might be left over from when the `SettingViewHolder` was representing a different setting.
=> Android: Unset STRIKE_THRU_TEXT_FLAG for editable settings

Source/Core/DolphinQt/SkylanderPortal/SkylanderPortalWindow.cpp
We don't have prompts like this for any other path handled by Dolphin. If the folder doesn't exist, let's just create it.
=> DolphinQt: Don't ask user about creating Skylanders folder

CMakeLists.txt
This resolves https://bugs.dolphin-emu.org/issues/13515 and supersedes https://github.com/dolphin-emu/dolphin/pull/12611. I was able to confirm this change fixes the build errors with the latest version of minizip-ng.
=> Externals: minizip-ng Forward Compatibility

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
We can implement the same behavior in one instruction less.
=> JitArm64: Skip UBFX in mfcr

Source/Core/Common/CodeBlock.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.h
This is a JitArm64 version of PR #12213.
Due to limitations on how far you can jump with a single AArch64 branch instruction, going above the former limit of 128 MiB of code (counting nearcode and farcode combined) requires a bit of restructuring. With the restructuring in place, the limit now is 256 MiB. See the new large comment in Jit.h for a description of the new memory layout.
=> JitArm64: Increase farcode & nearcode cache size

Source/Core/Core/CheatSearch.cpp
When a Cheat Search is using a signed integer data type and "Display values in Hex" is checked, show the bytes of Last Value and Current Value in two's complement rather than with signed magnitude as was previously happening.
Before:
After:
=> CheatSearch: Use two's complement for negative hex values

Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
I couldn't reproduce the issue (https://bugs.dolphin-emu.org/issues/13524), but the code was slightly wrong anyway, as the enum indexes weren't guaranteed to match the Qt drop down list indexes (they currently did match, but possibly not in the future).
The user mentioned that the issue only appears when using game specific inis. I haven't tried with these as I've never manually used that system. There's nothing special about the output resampling settings serialization, it looks like any other video enhancement setting to me. If anybody else has any idea what could be the reason of the issue, let me know.
=> Qt: fix 13524 - output resampling mode not loading correctly from ini

Source/Core/VideoCommon/OnScreenUI.cpp
When a movie is not being recorded, `movie.GetCurrentInputCount()` is always zero. We should hide this if that's the case.
=> VideoCommon: Only show input count when recording

Source/Core/DolphinNoGUI/PlatformWin32.cpp, Source/Core/DolphinQt/RenderWidget.cpp, Source/Core/DolphinQt/RenderWidget.h
On Windows 11, when playing windowed in a separate window/widget from the main emulator window, we don't want the window to have rounded corners, as it prevents the corner pixels from being visible
Here's how it would look, there's not much to it:
=> Remove rounded corners on emulation render window

Source/Core/Core/CheatSearch.cpp, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/Movie.cpp, Source/Core/Core/PatchEngine.cpp, Source/Core/DiscIO/RiivolutionPatcher.cpp, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Config/HardcoreWarningWidget.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings/GeneralPane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.cpp
Bugfix for hardcore-disabled items being disabled when hardcore was true but achievement integration was false, which should mean hardcore is effectively disabled. Now everything checks the IsHardcoreModeActive method in AchievementManager which processes the setting AND the game state to determine if hardcore mode is actually active.
=> Disabled Hardcore Mode when Achievements disabled

CMakeLists.txt, Source/Core/Core/CMakeLists.txt, Source/Core/Core/HW/WiimoteReal/IOhidapi.cpp, Source/Core/DolphinNoGUI/CMakeLists.txt, Source/Core/InputCommon/CMakeLists.txt, Source/Core/UICommon/CMakeLists.txt, Source/Core/VideoBackends/OGL/CMakeLists.txt, Source/UnitTests/CMakeLists.txt
I've tested this on OpenBSD 7.5 amd64 by compiling and starting a game. The build instructions in the wiki will have to be updated after this commit (they're much simpler now). The OpenGL renderer isn't working, but I don't know graphics stuff and believe this is because it doesn't work with my iGPU (Core i7-4770). The 5 year old version of Dolphin on OpenBSD doesn't work either, but again, I think it's hardware compatibility. The software renderer did work, however.
I've also tested this by compiling it on FreeBSD 13.2 amd64, I only had to disable UPNP because its compilation failed, but that's an external dependency and not Dolphin code.
I intend to try testing it on NetBSD, but my NetBSD machine is a Pentium 4 (32-bit single core from 2002) with 1GB of RAM and I don't know if it has …
=> port to OpenBSD

Source/Core/DolphinQt/CheatSearchWidget.cpp, Source/Core/DolphinQt/Config/FilesystemWidget.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt/Debugger/RegisterWidget.cpp, Source/Core/DolphinQt/Debugger/ThreadWidget.cpp, Source/Core/DolphinQt/Debugger/WatchWidget.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp, Source/Core/DolphinQt/Updater.cpp
I have personally gone around and verified every widget still executes. This is not every memory leak, just the ones that were obvious. A notable change: The GameList context menu has a slot for `Host::EmulationStateChanged`, and every un-deleted context menu was cluttering this signal's responsibilities.
=> DolphinQt: Properly Delete (Some) Widgets

Source/Core/UICommon/CMakeLists.txt
Tested on OpenBSD 7.5 amd64 and FreeBSD 13.2 amd64 by me. I needed to disable achievements on FreeBSD, doesn't seem to be this PR's fault.
@mitaclaw also tested it on Manjaro Linux.
=> fix linking against LLVM shared library

Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp
If achievements were disabled but a player token is in settings, prior to this change the Achievement Manager dialog would show a box with no player name and score zero, which is unnecessary.
=> Hide Achievement Dialog Header When Disabled

Source/Core/Core/PowerPC/PowerPC.cpp, Source/Core/Core/PowerPC/PowerPC.h
This was something I noticed back when I was considering adding a virtual function to CPUCoreBase to return an identifying enum. Nothing seems to be using this code anymore.
=> PowerPC: Remove Dead Config Code

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp, Source/Core/Core/HW/EXI/BBA/BuiltIn.h, Source/Core/Core/HW/EXI/EXI_DeviceEthernet.h
This PR is based on https://github.com/dolphin-emu/dolphin/pull/12559 and updates the way BBA/HLE polls data. It does so by sleeping less often and pulling data as soon as possible and as much as possible.
I suspect this PR has improved the matchmaking stability. My Windows build seems to match consistently my Android phone and the other way around. It might be a coincidence since I don't have a lot of device to test it.
This PR is ready to be tested.
=> BBA/HLE: Increase polling efficiency

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
The "welcome message" that shows up to players when a game starts up and Achievements are active will now either tell the player upon load that there's no support for achievements, or will wait until the first attempt to load the game's badge either succeeds or fails and then display a full message with title and progress and status. This is in part facilitated by a boolean field for when to display a welcome message, set to true upon loading and to false upon a message being displayed.
=> Retooled Achievements Welcome Message

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/DolphinNoGUI/PlatformMacos.mm, Source/Core/DolphinNoGUI/PlatformX11.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/RenderWidget.cpp
Part 5 of an effort to remove global state from one of the biggest offenders. This is my last planned change to Core.cpp, leaving `Core::DisplayMessage` and `Core::SaveScreenshot` unchanged. I believe these remaining uses of `Core::System::GetInstance` are open design questions that shouldn't be tackled in the same way I have for the other functions.
=> Core::SetState: Avoid Global System Accessor

Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
All relevant games other than Pikmin 1 Wii seem to always set the two dwords to zero, so previously they were ignored during command dispatch and now we still ignore them but in the right place.
=> DSPHLE/Zelda: set COMBINED_CMD_0D flag appropriately

Source/Core/Common/SettingsHandler.cpp, Source/Core/Common/SettingsHandler.h, Source/Core/Core/Boot/Boot_BS2Emu.cpp, Source/Core/Core/IOS/DolphinDevice.cpp, Source/UnitTests/Common/SettingsHandlerTest.cpp
Also make the `Decrypt` method private.
As far as I can tell, the only motivation for exposing the `SetBytes` and `Reset` methods is to allow `CBoot::SetupWiiMemory` to use the same `SettingsHandler` instance to read settings data and then write it back. It seems cleaner to just use two separate instances, and require a given `SettingsHandler` instance to be used for either writing data to a buffer or reading data from a buffer, but not both.
A natural next step is to split the `SettingsHandler` class into two classes, one for writing data and one for reading data. I've deferred that change for a future PR.
=> Eliminate SettingsHandler's `SetBytes` and `Reset` methods

Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/JitAsm.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Tested using Mario Kart: Double Dash (USA) with the following breakpoints:
```
[BreakPoints]
$00000800 nlbc srr0 == 0x800be4f8
$800be4f4 nlb
$800be4f8 nlb
$80000800 nb
```
At effective address 800be4f8, there is a `stfd` instruction that is frequently executed while the FPU is not unavailable (the exception handler enables it). Note that the fourth breakpoint is a workaround for a Dolphin bug where setting breakpoints at effective addresses in physical memory while address translation is enabled won't invalidate the JitCache correctly to recompile with the new breakpoint. The other three breakpoints are hit in the following unexpected order:
```
Core/PowerPC/PowerPC.cpp:679 N[MI]: BP 800be4f4  --- (000001c0 000001c0 09a7ec80 7082f0c1 00000010 804ebce8 0000000c ffffffff ffffffff 00000000) …
```
=> Jit64/JitArm64: Check Breakpoints Before FPU Availability

Source/Core/Common/Arm64Emitter.cpp
The lack of this assert led to a bug I had to fix [a while back](https://github.com/dolphin-emu/dolphin/pull/12540), so better to enforce it.
=> Arm64FloatEmitter: 64-Bit Assert In ABI_PushRegisters

Source/Core/DolphinQt/SkylanderPortal/SkylanderPortalWindow.cpp
Skylanders created via the Dolphin UI are created with the .sky extension by default, but Skylanders are often backed up with a different file extension depending on the method used, so I have added these types to the QT File filters so that they can be selected by default.
=> IOS/USB: Change Skylander File Type Filter

Source/Core/Core/PowerPC/Jit64/RegCache/GPRRegCache.cpp
This comment was added 15 years ago in 1c1425a406. The bug the comment refers to was fixed one day later in 41ce35deb3.
=> Jit64: Remove outdated comment about R12

Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.cpp
This was a mistake I made in 83b280d903.
=> DolphinQt: Fix double argument in Infinity error message

Source/Core/DolphinQt/Settings/GeneralPane.cpp
Doing this causes the settings to be reloaded before they're done saving, effectively discarding the user's changes.
Broken by 2328539a76a338d4c3e591e4a96e5ea49a661bb3
=> DolphinQt/Settings/GeneralPane: Don't emit a ConfigChanged signal while saving config

Source/Core/DolphinQt/HotkeyScheduler.cpp
Dolphin manages hot key handling on a separate thread.  One of the features it provides is a way to trigger frame advances.  Advancing a frame uses `SetState` which is only expected to be called from the host thread.  We can resolve this by wrapping the frame step in a `QueueHostJob`
=> DolphinQt: trigger frame advance from hotkeys on the host thread

Source/Core/VideoCommon/OnScreenUI.cpp
In imgui 1.87 they introduced a new input system.  One of the advantages of this input system was an input queuing system to keep input smooth when frame times were inconsistent.  We switched over to this system for keyboard events when updating imgui as part of an interface breakage but we didn't update our mouse clicks to use this system.
This code updates our mouse handling to use the input event system.
=> VideoCommon: use imgui input queue for mouse clicks

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
There were several places in the code where we allocate a scratch register to temporarily hold a value. However, when the destination register is never read, we may use it as a scratch register and skip explicitly allocating one.
This should reduce register pressure a little.
=> JitArm64: Skip temp regs where possible

Source/Core/InputCommon/ControllerEmu/StickGate.cpp
This prevents "Modifier/Range" values from saving if they are the default of 50%.
It was annoying that even non-configured Wii Remotes produced many of these ini file lines.
It changes this:
```ini
[Wiimote3]
Device = XInput2/0/Virtual core pointer
Source = 0
Tilt/Modifier/Range = 50.
Nunchuk/Stick/Modifier/Range = 50.
Nunchuk/Tilt/Modifier/Range = 50.
Classic/Left Stick/Modifier/Range = 50.
Classic/Right Stick/Modifier/Range = 50.
Guitar/Stick/Modifier/Range = 50.
Drums/Stick/Modifier/Range = 50.
Turntable/Stick/Modifier/Range = 50.
uDraw/Stylus/Modifier/Range = 50.
Drawsome/Stylus/Modifier/Range = 50.
[Wiimote4]
Device = XInput2/0/Virtual core pointer
Source = 0
Tilt/Modifier/Range = 50.
Nunchuk/Stick/Modifier/Range = 50.
Nunchuk/Tilt/Modifier/Range = 50.
Classic/Left …
```
=> InputCommon: Fix unnecessary "Modifier/Range" ini file entries.

CMakeLists.txt, Externals/hidapi/CMakeLists.txt
I've tested this on OpenBSD 7.5 and NetBSD 10.0 only. 
OpenBSD works, and compilation goes further than it used to before failing on NetBSD.
=> use pkg-config to find libusb

CMakeLists.txt
I've tested this on OpenBSD 7.5 and NetBSD 10.0.
On OpenBSD, it detects the system libfmt is too old and uses the Externals/ one. On NetBSD, generating the build system succeeds, but compilation fails for unrelated reasons (Dolphin doesn't run on NetBSD).
=> use pkg-config to find libfmt

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
BFI takes two cycles on many CPUs, whereas AND (immediate) only takes one.
=> JitArm64: Minor mtfsfix optimization

Source/Core/Core/PowerPC/PPCAnalyst.cpp
BI contains both the field and the flag (5 bits total), so we need to shift away the 2 flag bits to get the 3 field bits. (Same as the CRBA/CRBB handling in the code just below the BI code.)
=> PPCAnalyst: Fix handling of FL_READ_CR_BI

Source/Core/Core/PowerPC/JitCommon/JitBase.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h
Branch targets always start a new block, so this variable isn't useful.
=> PPCAnalyst: Remove unused member isBranchTarget

CMakeLists.txt
This is based on https://en.cppreference.com/w/cpp/compiler_support. I'm not actually entirely sure what the needed Xcode version is.
=> CMake: update required compiler versions for std::bitcast support

Source/Core/DiscIO/Volume.h, Source/Core/DiscIO/VolumeWad.cpp, Source/Core/DiscIO/VolumeWad.h
The offset-based overload hasn't been in use since f754a1a548f2e599e4cc2d1d799f2d21b520076f.
=> DiscIO: drop unused Volume::CheckContentIntegrity() overload

Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp, Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
This is the same fixup as in Jit64::FixGTBeforeSettingCRFieldBit.
=> Interpreter: Fix GT when setting SO of CR

Source/Android/app/build.gradle.kts, Source/Android/gradle.properties
Fix deprecated `android.defaults.buildfeatures.buildconfig`
Also cleaned up quotation marks around baselineProfile, and removed two unused libraries.
=> Android: Fix Gradle deprecation

Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.h, Source/Core/DolphinQt/Debugger/BranchWatchTableModel.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Fixing some minor defects of the Branch Watch Tool. Here's the rundown:
- Sorting the table is no longer case-sensitive.
- BranchWatchDialog, BranchWatchProxyModel, and BranchWatchTableModel classes now have the Rule of Five defined.
- Replaced a "Core.h" include with a forward declaration.
- Resolved the Linux Qt6 FIXME because a recent package update seems to have fixed the issue I was previously avoiding.
=> Branch Watch Tool: Fixes

Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigRadio.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigRadio.h, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.h
Add BalloonTips to the Config->Interface pane by replacing the widgets with ConfigControls.
I aimed to make the tooltips reasonable but I'm assuming and open to them being workshopped.
This incidentally fixes the problem where changing any setting in the Interface pane would cause the UI to be unresponsive for a moment. That happened because every change caused the app's stylesheet to be set, which apparently takes several seconds when all the widgets are already created. Now the pause only happens when actually changing the style.
=> InterfacePane: Add BalloonTips

Source/Core/DolphinQt/MainWindow.cpp
https://bugs.dolphin-emu.org/issues/11191
https://bugs.dolphin-emu.org/issues/13355
On Windows:
InitControllers()  -> GetWindowSystemInfo -> wsi.render_window being set will set/save the initial geometry, which will cause sizing bugs until it's set again by the user resizing/repositioning.
Not tested on other platforms.  I don't see any problem with moving InitControllers() down, but someone should double check.
If the normal sized window is very small there will still be some issues with maximized windows restoring geometry, but that's more of a Qt bug.
=> MainWindow, Bugfix: Initialize geometries before calling GetWindowSystemInfo

Source/Core/Core/AchievementManager.cpp
Also fixed an Achievement log that was reporting even when achievements were disabled.
=> Properly reset Discord presence after game close

Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.h
Add theme-aware buttons, ability to edit addresses, and a popup for conditional editing.
If a base address is changed, it will delete the breakpoint and then create a new breakpoint at the new address. Useful for moving a conditional to another address.
Removed selecting rows, which breaks the old delete button. Delete moved to context menu.
This new style can result in new odd states for breakpoints. Such as a Memory Breakpoint that is enabled, but has Read + Write disabled, resulting in nothing being done.  Previously Read and/or Write would always be true. Not sure it matters.
If the buttons are no good, they can be replaced with 3-state combo boxes. Break/Log/B+L.
=> BreakpointWidget: Add ability to directly edit breakpoints

Source/Core/Common/Version.cpp, Source/Core/Common/Version.h, Source/Core/Core/AchievementManager.cpp
Requested agent syntax is "Dolphin/5.0-23456"
=> Add user agent to headers for all RetroAchievements server calls

Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureCacheBase.h, Source/Core/VideoCommon/VertexManagerBase.cpp
Currently, texture samplers are set during binding, with no way to access them (or replace them).  By splitting the get and the set process into separate functions, it will allow for further reuse in the future.
=> VideoCommon: pull texture sampler out of texture cache for later reuse

Source/Core/VideoCommon/OnScreenUI.cpp
Similar to #12787 , this event was overlooked earlier.  I believe this is the last one that needs to be updated.
=> VideoCommon: use imgui mouse position event when the mouse position changes

Source/Core/Core/PowerPC/MMU.cpp
The updated behavior more closely emulates the functionality of physical hardware.
=> MMU: Remove erroneous continue statement

Source/Core/DolphinQt/MainWindow.cpp
I accidentally broke batch mode (for keeping the main window hidden) in #12794.  Hopefully that's the only thing I missed, as I don't know another way to initialize the Window before it is initialized somewhat randomly with bugs on Windows platforms.
=> MainWindow: Fix batch mode

Source/Core/Core/AchievementManager.h, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/BootManager.cpp, Source/Core/Core/CheatSearch.cpp, Source/Core/Core/CheatSearch.h, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/CoreTiming.cpp, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/FreeLookConfig.cpp, Source/Core/Core/HW/DVD/DVDInterface.cpp, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/Movie.cpp, Source/Core/Core/PatchEngine.cpp, Source/Core/Core/State.cpp, Source/Core/DiscIO/RiivolutionPatcher.cpp, Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings/GeneralPane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/VideoCommon/OnScreenUI.cpp, Source/Core/VideoCommon/OnScreenUI.h
This lets us reduce the number of USE_RETRO_ACHIEVEMENTS ifdefs in the code base, reducing visual clutter. In particular, needing an ifdef for each call to IsHardcodeModeActive was annoying to me. This also reduces the risk that someone writes code that accidentally fails to compile with USE_RETRO_ACHIEVEMENTS disabled.
We could cut down on ifdefs even further by making HardcodeWarningWidget always exist, but that would result in non-trivial code ending up in the binary even with USE_RETRO_ACHIEVEMENTS disabled, so I'm leaving it out of this PR. It's not a lot of code though, so I might end up revisiting it at some point.
=> Use a stub AchivementManager when USE_RETRO_ACHIEVEMENTS isn't defined

Source/Core/Common/Assembler/GekkoLexer.cpp
All references to r1 and r2 in the disassembler get replaced with sp (stack pointer) and rtoc (register table of contents) respectively. When writing these instructions in the assembler, it fails to resolve:
This commit allows them to be used interchangeably
I considered adding an extra enum entry `TokenType::Alias` but the current approach seemed straightforward enough as-is
=> Assembler: Add aliases for r1 and r2

Source/Core/DolphinQt/MainWindow.cpp
It was erasing the saved UI geometry for when batch mode is off.  Initializing then hiding the window will make sure it re-saves the UI geometry.  If this has an issue, possibly not saving the UI geometry while in batch mode would work.
@Owlet7  can you download this and check for any issues?
=> MainWindow: Fix batch mode (again).

Data/Sys/GameSettings/RRB.ini, Data/Sys/GameSettings/RY2.ini, Data/Sys/GameSettings/RY3.ini, Data/Sys/GameSettings/SOJ.ini, Data/Sys/GameSettings/SR4.ini, Data/Sys/GameSettings/SR5.ini, Data/Sys/GameSettings/WR2.ini
This PR provides a batch of GameINI updates:
- Sets SafeTextureCacheColorSamples to proper values for a few games to fix choppy/pixelated FMVs.
- Disable texture filtering for several games to prevent broken FMVs.
- Disable ImmediateXFBEnable to prevent some potential crashes.
- Add Vertex Rounding to Rabbids Go Home to fix visible lines in fans/air vents (which are common).
I've also added Rabbids Lab since it's currently broken and uses the same codebase as Rabbids Go Home. Also, this game is an unoptimized mess and I would've added more fixes if it weren't for the severely degraded performance.
=> GameINI: Ubisoft updates

Source/UnitTests/Common/MathUtilTest.cpp
This PR tests `GetWidth` and `GetHeight` behavior for both signed and unsigned types because the implementation differs between those cases.
=> Add some unit tests for the `Rectangle` class

Source/Core/VideoCommon/TextureConfig.cpp
Somehow missed this when adding the texture type.
=> VideoCommon: add texture type to texture config comparison

Source/Core/DolphinTool/ExtractCommand.cpp
The `--quiet` flag should suppress all non-error messages. 
---
This change is useful in a personal wrapper I have around `dolphin-tool` (and other extract tools). My wrapper outputs it's own extraction success messages, but allows any warnings/errors to be displayed. Since `dolphin-tool extract` outputs everything to stderr, this PR would negate me having to capture and filter stderr to suppress the success message. displayed immediately. https://github.com/nvllsvm/dotfiles/blob/7456f47280aa7f5e1f7385225c41a5335cba7148/scripts/terminal/archive#L802-L813
=> Suppress extract success message when quiet flag is set

Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomPipeline.cpp
Previously we were always using a linear sampler state when a texture asset was used in a custom pipeline, now we use the texture's sampler.
Also noticed a place where the texture wasn't being checked for nullptr, so fixed that.
=> VideoCommon: update custom pipeline to use a texture's sampler instead of linear sampler if the texture is used

Source/Core/Core/AchievementManager.cpp
AchievementManager maintains a unique pointer to a copy of the current volume so it can asynchronously hash that volume. It is not needed otherwise, so I can release that pointer when hashing is complete. This change fixes a bug whereby changing discs in a game and then changing to a different game would result in the loaded volume pointer still being loaded with and hashing to the previous game.
=> Release Achievement Manager Loaded Volume

Source/Core/DolphinQt/HotkeyScheduler.cpp
Prior to this change, attempting to decrease the speed limit below 100% in hardmode would display the new attempted speed and then warn that the speed can not be decreased below 100%; this disables that first message under those conditions.
=> Remove Extra Speed Limit Message

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
Add a two second timer to Achievement Progress Indicators to wait until two seconds after the previous message (when it should have decayed out automatically) before posting any new ones.
=> Only Display One Progress At A Time

Source/Core/Common/SocketContext.cpp, Source/Core/Core/IOS/Network/Socket.cpp
This PR fixes online connection issues for people using ReShade. This issue happens when using ReShade with and without addons, including while disabling network hooks.
It seems that the way it injects itself changes sockets behaviour. It might have downgraded the socket version somehow but I wasn't able to find how or when. This PR fixes the issue by handling the WS 1.1 edge case as suggested by Microsoft documentation.
=> Socket: Fix connect issues when using ReShade

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/Host.h, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Host.cpp, Source/Core/DolphinQt/Host.h, Source/Core/DolphinQt/TAS/TASInputWindow.cpp, Source/Core/DolphinQt/TAS/TASInputWindow.h, Source/Core/DolphinTool/ToolHeadlessPlatform.cpp, Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp, Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp, Source/DSPTool/StubHost.cpp, Source/UnitTests/StubHost.cpp
Enable emulator hotkeys and controller input (when that option is enabled) when a TAS Input window has focus, as if it was the render window instead.  This allows TASers to use frame advance and the like without having to either switch the focused window or disabling Hotkeys Require Window Focus (which also causes keypresses to be picked up while other apps are focused).
Cursor updates are disabled when the TAS Input window has focus, as otherwise the Wii IR widget (and anything else controlled by the mouse) becomes unusable. The cursor continues to work normally when the render window has focus.
=> TAS Input: Enable emulator hotkeys and controller input when TAS Input window has focus

Source/Core/Core/AchievementManager.cpp
Now should properly update the Achievements dialog whenever the displayed state of an achievement/leaderboard changes.
=> Added missing dialog updates to achievement events

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/VideoCommon/OnScreenUI.cpp, Source/Core/VideoCommon/OnScreenUI.h
If an icon is displayed on screen before it downloads, it was displaying a default icon but it would fail to load the actual icon even after it was downloaded. This fixes that.
=> Refactored Challenge Icons to handle icon updates

Source/Core/Common/CMakeLists.txt, Source/Core/Common/JsonUtil.cpp, Source/Core/Common/JsonUtil.h, Source/Core/DolphinLib.props, Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.cpp, Source/Core/VideoCommon/Assets/DirectFilesystemAssetLibrary.cpp, Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsMod.cpp, Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.cpp
I was doing this enough in a branch that I figured I should probably make some functions out of it.  And hey, it turns out it can clean up a bit of our code in master too!
I tested all areas impacted:  DiT, texture loading, and graphics mods.
(also JsonUtil.cpp wasn't added to the source file, which triggered the `SaturatingCast` error, so that was fixed based on our [previous discussion](https://github.com/dolphin-emu/dolphin/pull/12653))
=> Common: add Json helper utilities for loading or saving to a file

Source/Core/InputCommon/ControllerInterface/CoreDevice.h, Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp, Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.h, Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h
Priorities weren't set for the keyboard-mouse devices on Linux/macOS which was sometimes resulting in a different device being configured by default (or when the "Default" button was pressed).
=> ControllerInterface: Adjust sort priorities to ensure default keyboard-mouse device is first.

CMake/CCache.cmake
The [official ccache documentation](https://github.com/ccache/ccache/wiki/CMake) recommends to set `CMAKE_C(XX)_COMPILER_LAUNCHER` to ccache to enable ccache. These also work as envionment variables (supported by CMake itself) so one can get use of ccache with every CMake project. However, using these instructions generates the following error during building with dolphin:
ccache: error: Recursive invocation (the name of the ccache binary must be "ccache")
This is because Dolphin adds an additional command ccache layer (ccache ccache compiler ...).
This fixes that issue by checking for `CMAKE_C(XX)_COMPILER_LAUNCHER` before inserting our own. Also, use `CMAKE_C(XX)_COMPILER_LAUNCHER` to add ccache because the CMake docs discourages the use of `RULE_LAUNCH_COMPILE` in favour of …
=> CMake: Fix CCache support when already using _LAUNCHER

Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.h, Source/Core/DolphinQt/Debugger/BranchWatchTableModel.cpp, Source/Core/DolphinQt/Debugger/BranchWatchTableModel.h
First I rewrote the Table Context Menu code to only construct it once (lazily) and hide/show/activate/deactivate actions based on what column was right clicked to bring it up. Right clicking the table's scroll area when all columns are hidden will now bring up the Column Visibility Menu. I also made the `OnTableSetNOP` and `OnTableSetBLR` functions follow DRY.
Next, I made it possible to set breakpoints en-mass from a selection in the Branch Watch Tool. This works for the origin, destination, and symbol columns.
=> Branch Watch Tool: Add Set Breakpoints Submenu

Source/Core/DolphinQt/Achievements/AchievementLeaderboardWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp
rc_client provides basic sorting buckets as a possible option when retrieving the list of achievements or leaderboards; this enables them and labels them in the dialog.
=> Add Sorting to Achievements Dialog

Source/Core/DolphinQt/Achievements/AchievementBox.cpp, Source/Core/DolphinQt/Achievements/AchievementBox.h
Label now appears atop the progress bar and reports the progress as the formatted text returned by rcheevos instead of a simple percentage.
=> Improved Achievement Progress Label

Source/Core/DolphinQt/Achievements/AchievementBox.cpp
This field was completely hiding the progress bar in dark mode without this.
=> Make achievement progress text label transparent

Data/Sys/GameSettings/GUP.ini
Adjusts widescreen heuristic values to work properly for both the original game and the widescreen hack versions.
---
Prior behavior: While using a widescreen hack (not dolphin's built in one), when the camera skews the aspect would incorrectly change to 4:3. Only restoring to 16:9 when a subtitle renders.
https://github.com/dolphin-emu/dolphin/assets/14857235/574971f1-270b-4c51-8461-460bb3c34d07
After behavior:
* Original game continues to stay in 4:3, including alternate viewport modes such as 2P split screen.
* Widescreen hack applied variants properly stay in 16:9 in all cases.
* Tested against widescreen hack variants of the game, works as expected.
* Tested original game
Credit to Billiard for determining values.
=> GameINI: Shadow The Hedgehog widescreen heuristic

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/infinitybase/ui/FigureSlotAdapter.kt, Source/Android/app/src/main/res/values/strings.xml, Source/Core/Core/IOS/USB/Emulated/Infinity.cpp, Source/Core/Core/IOS/USB/Emulated/Infinity.h, Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.cpp, Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.h
This was raised to me by a user that pointed out that you can have 2 "Power Discs" underneath the playset/power disc in the Hexagon space on the infinity base, so I have added 2 more slots to the qt and android UIs, as well as changing the behaviour of one of the C++ methods to allow for this. Removed the infinityListPosition from the Android version, as now the position in the UI list is ordered and doesn't need to have a separate UI list position and backend base position.
=> IOS/USB Add 2 more Spaces for Disney Infinity figures

Source/Core/VideoCommon/VideoConfig.cpp
This causes Dual Core to lock up during the boot sequence, because it tries to wait for a not-yet-running GPU thread.
Fixes https://bugs.dolphin-emu.org/issues/13559
=> Core/VideoCommon: Revert change from #12828

Source/Core/DolphinQt/Achievements/AchievementBox.cpp
The measured_progress C string for achievements to display potentially contains junk data after the null terminator, which was rendering in the QString in the dialog. This trims those junk characters.
=> Trim extra characters from measured progress

Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/InterfacePane.cpp
Can be re-added when we get rid of the global settings singleton.
=> DolphinQt: fix some warnings

Source/Core/DolphinQt/Settings/AdvancedPane.cpp
CPU Clock Override slider now increments 1% in the UI, with the new lower limit being 1% instead of 6%.
Prior implementation made it impossible to set exactly 150% in the GUI. 147% -> 152%.
Now users can set exact clock % without needing to edit INIs.
The upper limit of 400% is unchanged.
The lower limit of 6% is now 1%.
The INI value behavior is unchanged.
For testing, navigate to:
Config -> Advanced -> Clock Override
This is a DolphinQt change only so Android is unchanged. Android can already slide from 0% to 400% at 1% increments.
=> DolphinQt: Adjust CPU Clock Override slider

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
rc_client calls the provided memory peeker asynchronously in the callback for starting a session, to validate/invalidate the memory used for achievements. Dolphin cannot access memory from any thread but host or CPU so this access has a small chance of being invalid. This commit adds a MemoryVerifier that the AchievementManager will use to perform this, before changing the peek method back to the original MemoryPeeker for normal operation.
=> Add MemoryVerifier to AchievementManager Startup

Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp, Source/Core/DolphinQt/Settings.h
Rerendering the entire Achievements dialog every EmulationStateChanged signal is far too often when it turns out that signal fires multiple times to confirm game close, for example. This change results in only the settings changing on EmulationStateChanged, and having the Hardcore mode toggle (which DOES require redrawing the entire dialog) emit its own signal alongside EmulationStateChanged.
=> Decouple Hardcore from EmulationStateChanged

Data/Sys/GameSettings/GIT.ini
Fixes random crashes and unknown opcode errors.  Tested past the first boss.  There were no visual issues, unknown opcode popups, or any other kind of visual anomalies.  The only downside is that the framerate is fairly inconsistent, but that is normal for this game even on console.  The game ran full speed.
Credit to snow from RetroAchievements for helping me realize how easy of a fix this was.
=> Disable Dualcore in Geist

Source/Core/DolphinQt/Achievements/AchievementBox.cpp, Source/Core/DolphinQt/Achievements/AchievementBox.h, Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
Due to the new events provided by the rc_client refactor, there is no way to easily identify if an achievement has moved to a different sort bucket or if its measured value has changed - the events concern popup messages specifically, because every other supported emulator at this time can only bring up the list of achievements while the game is paused and therefore redraw this list from scratch every time it is accessed. This is not the case with Dolphin, so if this list will be kept reasonably up to date with the current game state, it needs to be refreshed manually. Here I set this up to do so whenever the Rich Presence updates, which internally happens every ten seconds.
=> Update Achievement List when Rich Presence Updates

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
Fix a warning on the Android builder by returning `bool` instead of `const bool` from AreChallengesUpdated().
=> AchievementManager: Fix -Wignored-qualifiers warning

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
Spotted and removed these in #12868 as well, but that might take a bit longer to land.
=> JitArm64: Remove unused temp_gprs

Source/Core/Core/PatchEngine.cpp, Source/Core/Core/PatchEngine.h, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp
All usages of this have been removed many years ago in cbe9c3e040a466bba410f025e026ed84f3f8b1c0
=> Core/PatchEngine: Remove remnants of Speedhack system

Source/Android/jni/InfinityConfig.cpp, Source/Core/Core/IOS/USB/Emulated/Infinity.cpp, Source/Core/Core/IOS/USB/Emulated/Infinity.h, Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.cpp, Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.h
Convert Infinity Base Position values to an enum to make it easier to understand the values being passed
=> IOS/USB: Use Enum for Infinity Base Positions

CMake/ScmRevGen.cmake, Source/Core/Common/make_scmrev.h.js
Prevents the current ref from being shown in the DolphinQt window title while HEAD is on a tag.
=> ScmRevGen: Set commits ahead to zero when on a tag

Source/Core/Core/AchievementManager.cpp
Starting or ending a challenge now displays a popup naming the challenge along with the active icon.
=> Add Messages for Challenges

Source/Android/app/build.gradle.kts
Right now, we assign a versionCode to each Android build of Dolphin by counting the total number of git commits made. This has worked fine so far, but it won't work as-is for the new release process.
Let's say we're currently on commit 20000. If we want to create a release under the new release process, we would create a release branch, add a new commit on it that updates the release name in CMake files and so on, and create a tag for that commit. The Android build of this release commit would get the version code 20001. However, the master branch is also going to get a commit with the version code 20001 sooner or later, and this commit would be an entirely different commit than commit 20001 on the release branch. This isn't much of a problem for people downloading Dolphin from …
=> Android: Adopt a new versionCode scheme

.tx/config, Readme.md
By request from delroth, I changed the name of our Transifex organization so it's named after the Dolphin project rather than after him. This broke old links and the .tx/config file.
=> Update Transifex organization name

Source/Core/DolphinQt/Host.cpp, Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h
Holding down frame advance was overloading Qt with update calls, causing issues 
Not sure if this is the best method.   If there are other times blocking updates would be useful, the names could be made to be more general.
New behavior:  Updates calls on first frame advance (for quick 1-frame advances). Blocks all other calls until finished, then reports a new OnStateChanged  (paused usually) call. 
It could also just do an UpdateDisasmDialog, but things are getting messy with that signal and widgets are more reliable with using OnStateChanged.
=> Frame Advance:  Fix UI update spam when continuously advancing.

Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MainWindow.h
Related #12794
Remove Show() and redistribute its logic to other places.
bugfix:  SetQWidgetWindowDecorations(this); not called before show() for Windows darkmode titlebar.
The actual call to (QWidget) show() needed to come sooner. Show() was originally left alone, but with other checks needing to move with (QWidget) show(), this function became less useful.  Show() was originally created to fix the render widget appearing behind the main window when a game is auto-launched on boot, but that appears to work fine in this iteration.
@CasualPokePlayer  I can't actually test this myself. I tried dark mode in two different Windows versions and neither set a different title bar color while in dark mode (outside dolphin).
=> MainWindow: Bugfix. Windows Dark mode titlebar not being set.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/DolphinApplication.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ActivityTracker.kt, Source/Android/jni/ActivityTracker.cpp, Source/Android/jni/CMakeLists.txt, Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/Core/Core.cpp, Source/Core/Core/Core.h
There are two pieces of functionality to be added here. One, we want to disallow pausing too frequently, as it may be used as an artificial slowdown. This is handled within the client, which can tell us if a pause is allowed. Two, we want to call rc_client_idle on a periodic basis so the connection with the server can be maintained even while the emulator is paused.
=> Handle Pausing in AchievementManager

Source/Core/VideoCommon/Assets/TextureAsset.cpp, Source/Core/VideoCommon/Assets/TextureAsset.h
Finally getting into texture asset sampling tests in my editor branch.  This allows serializing a texture asset to json and also modifies reading from json so that the values (filter mode / wrap mode) are able to be independent.
=> VideoCommon: add way to serialize Texture Asset to json, update to deserialize values independently

Source/Core/Common/Crypto/SHA1.h
I also tried updating the `CalculateDigest()` below to use spans but for some reason the compiler is bad at automatically deducing the template type if you do that. Oh well, this is still worthwhile on its own IMO.
```
template <typename T>
inline Digest CalculateDigest(std::span<const T> msg)
{
static_assert(std::is_trivially_copyable_v<T>);
ASSERT(std::numeric_limits<size_t>::max() / sizeof(T) >= msg.size());
return CalculateDigest(reinterpret_cast<const u8*>(msg.data()), sizeof(T) * msg.size());
}
```
```
C:\dolphin\Source\Core\Core\IOS\ES\Identity.cpp(194): error C2665: 'Common::SHA1::CalculateDigest': no overloaded function could convert all the argument types
C:\dolphin\Source\Core\Common/Crypto/SHA1.h(48): note: could be 'Common::SHA1::Digest Common::SHA1::CalculateDigest(const …
```
=> Common/Crypto/SHA1: Use span and string_view for Context::Update()

Externals/xxhash/CMakeLists.txt, Source/Core/VideoBackends/Vulkan/CMakeLists.txt, Source/Core/VideoCommon/CMakeLists.txt
(For future reference, every change like 2b9aee5c8fd784d7bfe736074547c114af878326 needs to make sure all our targets link to the name they specify as the third argument to dolphin_find_optional_system_library_pkgconfig rather than some other name, or they won't link against the right thing when using the pkgconfig dependency)
=> Properly link against xxhash

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
We mustn't use m_system when it is nullptr. This was causing Dolphin to crash on Android whenever an activity was recreated or resumed while emulation is running, which is super common.
=> Fix AchievementManager::SetBackgroundExecutionAllowed crash

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
0c14b0c8a70799072ddccb648006914af7c62855 made Dolphin load a file from the Sys folder the first time `AchievementManager::GetInstance()` is called. Because Android calls `AchievementManager::GetInstance()` from `setBackgroundExecutionAllowedNative`, this had two negative consequences on Android:
1. The first time `setBackgroundExecutionAllowedNative` gets called is often before directory initialization is done. Getting the path of the Sys folder before directory initialization is done causes a crash.
2. `setBackgroundExecutionAllowedNative` is called from the GUI thread, and we don't want file I/O on the GUI thread for performance reasons.
This change makes us load the data from the Sys folder the first time the data is needed instead. This also saves us from having to load the data at …
=> RetroAchievements: Delay calling LoadApprovedList

Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
On Windows, when the current display scale is set to over 150%, the breakpoint icons are in the wrong location. For example, at 200%:
This is because the size of the QPixmap is consistent until devicePixelRatioF > 1.5
- 100% - pix.size: QSize(24, 24)
- 125% - pix.size: QSize(24, 24)
- 150% - pix.size: QSize(24, 24)
- 165% - pix.size: QSize(40, 40)
- 175% - pix.size: QSize(42, 42)
- 200% - pix.size: QSize(48, 48)
- 225% - pix.size: QSize(48, 48)
The simple fix is to use an immediate value of 24 and ignore the size
=> BreakpointWidget: Correct icon position

Source/Core/Core/IOS/IOS.cpp
This fixes a regression from https://github.com/dolphin-emu/dolphin/commit/962230f91e06a60b2395de6f0974fdd213854d4c onwards, where the state in `InitIPC` was still `State::Starting`, causing the WiiIPC ack to never be generated.
This causes the vWii System Menu to be stuck waiting on the IPC to be initialized, as described in https://github.com/dolphin-emu/dolphin/pull/11186 where the `IsRunning` check was added.
=> IOS::HLE::EmulationKernel::InitIPC: Fix WiiIPC ack generation

Source/Core/Core/AchievementManager.cpp, Source/Core/DolphinQt/Achievements/AchievementLeaderboardWidget.cpp
Now that we have some test data, it wasn't showing up in the leaderboards tab; this fixes it to ensure (1) that the right ID is being passed to UpdateRow and (2) the map of leaderboard entries is being populated correctly.
=> Fix Leaderboards Tab

Source/Core/DolphinQt/MenuBar.cpp
Makes the Achievements menu visible to all users. Achievements can be tested unofficially, and will become official at 5PM EST July 15, 2024.
=> Show Achievements in Menu Bar always

Source/Core/Core/AchievementManager.cpp
'spam' in an OSD message just sounds wrong to me. I've taken the new phrasing mostly from pcsx2:
https://github.com/PCSX2/pcsx2/blob/cd3e11bff77bb5a7f44c5a39cb534b670c09abd7/pcsx2/Hotkeys.cpp#L97
This also rounds the seconds to two digits after the comma, because it would print things like `0.06673333333333334` before which is not very helpful.
=> AchievementManager: Improve error message for repeated pausing

Data/Sys/GameSettings/GC6E01.ini, Data/Sys/GameSettings/GC6J01.ini, Data/Sys/GameSettings/GC6P01.ini, Data/Sys/GameSettings/GXXE01.ini, Data/Sys/GameSettings/GXXJ01.ini, Data/Sys/GameSettings/GXXP01.ini
@JMC47 I remember you talking about this, I think?
This comes up surprisingly often in support where people can't save after beating Mt. Battle. I think what's happening is that the save itself is storing the memory card ID and GCI folders are technically a new memory card on each boot, but I never investigated the exact details, I just know that these patches work around the issue.
=> GameINI: Enable Pokémon Colosseum/XD save patches by default

Source/Core/Core/AchievementManager.cpp
Without the `static` this goes on the stack and then leaves scope before it's actually dereferenced in the callback.
=> AchievementManager: Don't point to stack for login error message

Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
Emergency PR to disable the leaderboards tab for launch if we are not satisfied with its testing yet.
=> Disable Leaderboards Tab

Source/Core/DolphinQt/Achievements/AchievementBox.cpp
Was previously showing locked badges/statuses for achievements unlocked in a previous session.
=> Fixed incorrect unlock information in Achievements dialog

Data/Sys/GameSettings/RDJ.ini
Workaround for https://bugs.dolphin-emu.org/issues/13544
It's unfortunate as this game is demanding to run full speed, but I've been able to play at full on a Ryzen 5 2600 Six-Core Processor speed using VBI skip with no noticeable issue. I believe this is better than random hangs which locks your entire game.
=> Disable Dual Core in Death Jr.: Root of Evil

Source/Core/Core/AchievementManager.cpp, Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
Resolves the leaderboard request spam that DDoS'd the server upon the Gamecube launch, by removing the request being spammed. Also fixes a minor logic issue with the leaderboard display that wasn't obvious until there was data to display.
=> RetroAchievements - Leaderboard Spam Fix

Source/Core/Core/IOS/FS/HostBackend/File.cpp
When attempting to open a directory via `IOS_Open` on console, it returns error code -101, and in the latest version of Dolphin, it currently returns -106.
=> IOS: Fix return code inaccuracy

Source/Core/Common/Assembler/AssemblerTables.cpp
Change OperandDesc variables to not be underscore-prefixed in order to comply with https://eel.is/c++draft/lex.name#3.1 (fixes compilation under newlib; e.g. devkitPro)
The offenders we (me and people from the emudev community) found were `_B`, `_S`, `_L` and `_C`, as these are most likely already defined in the newlib used by devkitPro.
In any case, this doesn't cause any harm and solves many headaches for people like me who are trying to port Dolphin to unusual devices.
If I'm missing anything, I'll happily fix it.
Thanks :D
=> Fix double-definition under newlib

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Common/x64Emitter.cpp, Source/Core/Common/x64Emitter.h
As it is, this seems like it would only hinder codegen (assuming no LTO).
=> Emitters: Define Trivial Getters Inline

CMakeLists.txt
Dolphin currently fails to build when the Linux system building it includes headers/pkgconfigs for minizip-ng built in both minizip-ng mode and legacy compat mode (the minizip API).
This is because minizip-ng is checked for in cmake however the code is not actually compatible against minizip-ng built in non-legacy mode. Until that is rectified Dolphin should just check for a pkgconfig for minizip. If the system has a pkgconfig for minizip with a version >= 4 then the system package is minizip-ng built in compat mode which is exactly what we want.
=> cmake: Fix building with system minizip-ng

Source/Core/DolphinTool/ExtractCommand.cpp
Probably more useful than enumerating filesystem entries non-recursively, at least I've never had that use case.
=> DolphinTool: list filesystem recursively

Source/Core/Core/Core.cpp, Source/Core/Core/Debugger/CodeTrace.cpp, Source/Core/Core/Debugger/DebugInterface.h, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/Debugger/PPCDebugInterface.h, Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/HW/CPU.cpp, Source/Core/Core/HW/CPU.h, Source/Core/Core/PowerPC/BreakPoints.cpp, Source/Core/Core/PowerPC/BreakPoints.h, Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/PowerPC.cpp, Source/Core/Core/PowerPC/PowerPC.h, Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BreakpointDialog.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.h, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Fixes many annoying bugs and inconsistencies when using the debugger:
- Run to Here now actually does what it says on the name (fixes https://bugs.dolphin-emu.org/issues/13532). It also can't be used without a game running.
- You can create breakpoints while a game isn't running (the button isn't disabled anymore).
- Some cleanups to the API:
- Misleading names were changed
- Functions were used where it makes sense, less pointless reimplementations
- Notably, Step Out and the Interpreter don't manually check for breakpoints, but use the same implementation as the Cached Interpreter and JIT. This means that they don't break on log-only breakpoints anymore.
- Pressing Continue while on top of a breakpoint did nothing. Now it... does something! (It resumes, like on Cached Interpreter and …
=> Debugger: Various fixes

Data/Sys/Load/GraphicMods/Need for Speed Nitro/metadata.json
Screenshots at 4x resolution
The DOF isn't *exactly* DOF, tell me if you want the name changed.
Before
Native bloom
No bloom
No DOF
Native bloom + No DOF
=> Add Bloom definitions for Need for Speed: Nitro

Source/Android/app/src/main/res/values/strings.xml, Source/Core/DolphinQt/Settings/GeneralPane.cpp
This PR changes `Dual Core (speedup)` to `Dual Core (speedhack)`. That's all.
If we are ever to remove Dual Core's default enabled status in the distant future, we'll need to start by changing users perception of the option. This extremely tiny change was suggested on discord, and I think it's brilliant. It's a subtle way to help users understand what Dual Core is - a hack - which we can use as a building block for the future.
Before
After
=> Dual Core Labeling Update

Source/Android/jni/MainAndroid.cpp
Based on feedback I received on https://github.com/dolphin-emu/dolphin/pull/12714.
In a race condition, the core could shut down between the `JitInterface::GetCore` nullptr check and the `JitInterface::JitBlockLogDump` call which constructs a `CPUThreadGuard`. In this scenario, nothing horrible happens—`JitBlockLogDump` also checks for a nullptr—but it would be a failure to display the correct feedback to the user.
=> MainAndroid: Thread Correctness In WriteJitBlockLogDump

Source/Core/Core/ConfigManager.cpp
Taiwanese games share the same region code as Japan, however they have a different character at the 3rd index which differentiates them. 
i.e: RHAW01 for Taiwanese Wii Play as opposed to RHAJ01 for Japanese Wii Play.
=> Display Taiwanese covers for Taiwanese games

Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/GeneralPane.cpp, Source/Core/DolphinQt/Settings/GeneralPane.h
I aimed to make the tooltips accurate and detailed, but encourage double-checking.
=> GeneralPane: Add BalloonTips

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
When the immediate value is zero, we can do a negation. On ARM64 the NEG/NEGS instructions are just an alias for SUB/SUBS with a hardcoded WZR.
Before:
```
ldr    w22, [x29, #0x28]
mov    w21, #0x0                 ; =0
subs   w22, w21, w22
```
After:
```
ldr    w22, [x29, #0x28]
negs   w22, w22
```
=> JitArm64_Integer: Optimize subfic for zero

Data/Sys/GameSettings/SVX.ini
According to this very old report https://bugs.dolphin-emu.org/issues/6972, this was needed to prevent flickering pre-rendered cutscenes.
Now, after (I imagine) the Hybrid XFB era, the cutscenes work perfectly fine regardless of `EFBToTextureEnable`. So let's boost the performance!
(Though, pre-rendered cutscenes *do* flicker with "Immediately Present XFB" (again, regardless of `EFBToTextureEnable`). Should I force disable that, instead of deleting `SVX.ini` completely?)
=> SVX.ini: Replace `EFBToTextureEnable=False` with `ImmediateXFBEnable=False`

Source/Core/Core/BootManager.cpp
`Layer::Save` only does its thing if the layer has `is_dirty == true`.
But SYSCONF could have been modified by other layers, so if the base layer wasn't made dirty by anything else, then it wouldn't be restored.
Fixes https://bugs.dolphin-emu.org/issues/13580.
=> Config: Don't depend on `is_dirty` to save SYSCONF during restore

Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
A more complete fix would also prevent reordering breakpoints when actually editing one.
=> Debugger: keep breakpoints ordered by address

Source/Core/DolphinQt/Settings/GeneralPane.cpp
Add #if statements to only create and set analytics descriptions if analytics are enabled in the build settings.
=> GeneralPane: Fix building with analytics disabled

Source/Core/AudioCommon/WaveFile.cpp, Source/Core/Common/ColorUtil.cpp, Source/Core/Common/Crypto/AES.cpp, Source/Core/Common/GL/GLInterface/AGL.mm, Source/Core/Common/GL/GLX11Window.cpp, Source/Core/Core/HLE/HLE_VarArgs.cpp, Source/Core/Core/HW/EXI/BBA/TAP_Win32.cpp, Source/Core/Core/HW/WiimoteEmu/DesiredWiimoteState.cpp, Source/Core/DolphinNoGUI/Platform.cpp, Source/Core/DolphinQt/CheatSearchFactoryWidget.cpp, Source/Core/DolphinQt/CheatSearchWidget.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/InputCommon/ControllerInterface/Quartz/Quartz.mm, Source/Core/VideoCommon/AbstractFramebuffer.cpp, Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomShaderCache.cpp, Source/Core/VideoCommon/PerfQueryBase.cpp
Move some #includes around to match the [Contributing guidelines](https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md#cpp-code-headers).
The codebase is inconsistent about whether Dolphin sections (Common/DolphinQt/Core/etc.) have a space between their include blocks, so I matched the file's style where there was one and otherwise added a space.
=> Adjust order and spacing of various #includes

Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
The _trans macro marks strings for translation but doesn't do anything at runtime. For that, we need to use a function like GetStringT.
=> InputCommon: Translate ExpressionParser error messages

Source/Core/DolphinQt/QtUtils/ClearLayoutRecursively.cpp
Use QObject->deleteLater() instead of the delete operator to destroy child widgets of the layout. This prevents crashes caused by pending Qt events trying to access the now-destroyed widget.
=> QtUtils/ClearLayoutRecursively: Fix potential crash

Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
When a trivial getter is available, it ought to be used to encourage encapsulation.
=> JITs: Consistently Use Trivial `IsDebuggingEnabled` Getter

Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
The `QPushButton::pressed` signal was likely used by mistake, e.g. https://github.com/dolphin-emu/dolphin/pull/8263. Fixes for the mistaken uses of this signal in the BranchWatchDialog were wrapped into https://github.com/dolphin-emu/dolphin/pull/12977 to avoid merge conflicts down the line.
@LillyJadeKatrin This touches your RetroAchievements work. I assume we agree the intended signal here was `QPushButton::clicked`?
=> DolphinQT: Listen For `clicked` Signal Rather Than `pressed`

Source/Core/UICommon/AutoUpdate.cpp
While the update process will delete the files within the old bundle after updating to a version with an embedded updater, it won't delete the folder structure of the bundle, so we should clean those leftovers up.
Example of a Dolphin installation after updating from 2407-150 to 2407-165 (#12968):
=> AutoUpdate: Remove the old updater app on macOS if it exists

Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
This fixes the sound effect in Pikmin 2 that plays when saving has completed.
Tracked as [issue 8855](https://bugs.dolphin-emu.org/issues/8855), originally reported over 9 years ago in [issue 8051](https://bugs.dolphin-emu.org/issues/8051) by @pauldacheez.
Before:
https://github.com/dolphin-emu/dolphin/assets/123798/6ab638b3-fb40-4e01-ab37-6e934964e36f
After:
https://github.com/dolphin-emu/dolphin/assets/123798/5cabe58f-1923-4322-89d8-675a4658a575
=> DSPHLE/Zelda: fix Pikmin 2 save sound (issue 8855)

Source/Core/DolphinQt/MenuBar.cpp
Update the checkmarked slot in the Select State Slot menu when the `Increase Selected State Slot` or `Decrease Selected State Slot` hotkeys are pressed.
The actual selected save slot was being changed correctly before this commit; this just fixes the menu checkmark.
=> MenuBar: Update checkmarked Select State Slot when hotkeys are pressed

Source/Core/DolphinQt/Config/VerifyWidget.cpp
https://releases.llvm.org/10.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-no-automatic-move.html
=> Constness of 'result' prevents automatic move [performance-no-automatic-move]

Source/Core/UICommon/CMakeLists.txt
This compile definition was removed in https://github.com/dolphin-emu/dolphin/pull/12756 because it was complicated by changes in https://github.com/dolphin-emu/dolphin/pull/12716. Thus, the LLVM disassembler would never actually be used in UICommon's Disassembler class.
=> CMakeLists: Fix LLVM Usage In UICommon

Source/Core/UICommon/UICommon.cpp
This change detects when dolphin is running inside a 
flatpak sandbox and ensures xdg directories are used.
Running in flatpak requires adhering to the xdg spec
because other paths aren't guaranteed to be accessible.
Doing otherwise leads to errors when eg. the configuration
file is readable but not writeable, among other possible cases.
=> Detect when running inside a flatpak sandbox

Source/Core/DolphinQt/ConvertDialog.cpp, Source/Core/DolphinTool/ConvertCommand.cpp, Source/Core/DolphinTool/HeaderCommand.cpp
Never seen title IDs in decimal.
Also some small wording changes for dump conversions.
=> DolphinTool: print title IDs in hex

BuildMacOSUniversalBinary.py, CMakeLists.txt, Source/Core/Common/CommonPaths.h, Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinEmu.entitlements, Source/Core/DolphinQt/DolphinEmuDebug.entitlements, Source/Core/UICommon/UICommon.cpp
This died a long time ago, so let's remove it since the code is just rotting.
=> Remove Steam support

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/UnitTests/CMakeLists.txt, Source/UnitTests/UnitTests.vcxproj
For a long time now, we've had a problem where game INIs persist in the copied Sys folder if they've been deleted from the original Sys folder. (I still have hundreds of game INIs locally that only set EmulationStateId, and we removed those game INIs 6 years ago. On the buildbot, we do occasionally clear out the build directories manually, so I'd assume it's not quite as bad there.)
This PR fixes the problem by deleting the output Sys folder before copying the original Sys folder to the output Sys folder. This should be a bit slower, but in my testing, the difference seems small. At least if you have an SSD, which I really hope people have nowadays!
=> Delete output Sys folder before copying to it

Source/Core/Common/BitUtils.h, Source/Core/Core/HW/DSPHLE/UCodes/AX.h, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
`std::bit_cast` participates in overload resolution only if `sizeof(To) == sizeof(From)` and both `To` and `From` are *TriviallyCopyable* types, so the static assertions here can be removed. `[[nodiscard]]` was added as well.
I tested uses of the now changed `Common::BitCastToArray` in `MemoryViewWidget::ConvertTextToBytes` and `GameFile::GetSyncHash`'s `GetHash` helper, and it worked as expected. I was unable to hit a breakpoint for the remaining uses of either function in Ax/AxWii code, so hopefully it is doing sane things all around. This changes what the compiler must optimize from a `std::memcpy` call to a trivial copy assignment, and I'm assuming the latter is easier for the compiler to work with.
The changes to the template parameter names was a personal choice; I felt it better …
=> BitUtils: Constexpr BitCastToArray, Remove BitCastFromArray

Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
This implements the GetTimeTriggers IOCTL within KD.
Function copies the scheduler span into an out buffer.
I have observed this to be called in the Wii Fit Body Check Channel, not sure where else it appears though.
=> IOS/KD: Implement Get Time Triggers

Source/UnitTests/UnitTests.vcxproj
Input/output tracking is intended to speed up incremental builds by skipping a target when it doesn't need to be built. However, this seems to be unreliable for UnitTests' AfterBuild target. Let's remove it.
It's still the case that UnitTests' AfterBuild target will be skipped if UnitTests doesn't need to be rebuilt. (Note that UnitTests always needs to be rebuilt if MakeScmRev changed.)
I haven't seen these problems with DolphinQt's rather similar input/output tracking. This may be because DolphinQt's one also has the exe file as an input/output.
=> UnitTests: Remove MSBuild input/output tracking

Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp, Source/Core/Core/HW/DSPHLE/UCodes/Zelda.h
The biquad filter is used in all Pikmin games for cursor sound effects in the main menu, although the difference is subtle.
EDIT: It's also used for some instruments in sequenced songs.
The low-pass filter is used at least by Pikmin 2 Wii during the spaceship crash in the intro and fixes the missing "puff" sound effects whenever there is black smoke coming out of the engine.
Before:
https://github.com/dolphin-emu/dolphin/assets/123798/795fc7d8-a653-48d7-a0c0-d29d92467d98
After:
https://github.com/dolphin-emu/dolphin/assets/123798/b587737c-2e8a-41e0-8742-75e379f64981
=> DSPHLE/Zelda: Add two missing filters

Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h
Fixes https://bugs.dolphin-emu.org/issues/13593. Before, it would attempt to use the old shader, which did not exist for the new stereo mode. Changing the postprocessing shader afterwards would work properly, although passive 3D only has one option, so it was just broken without restarting Dolphin.
This also fixes the UI not updating when using one of the stereo toggle hotkeys.
=> Fix postprocessing shader not changing when setting stereo mode

Source/Core/DolphinQt/Settings/GeneralPane.cpp
The description of the Speed Limit setting currently uses a lot of complicated terms, like "emulated time" (known to many Dolphin developers, but in my experience not known by even advanced emulator users) and "maximum time scale" (I have never heard it before). The meaning of "sustainable" is also unclear in context.
This commit rewords the description to be easier to understand.
=> DolphinQt: Simplify the Speed Limit description

Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp
Changes the RetroAchievements "Log In" button's text to "To login, stop the current emulation." when the button is disabled because an emulation session is active. This allows a user to understand why the button is disabled, and how this state can be resolved.
Previously, it could be unclear why this button was disabled without an understanding of the underlying system.
=> RetroAchievements: Add instructive text to disabled login button

Source/Core/Common/TypeUtils.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp, Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp, Source/Core/Core/PowerPC/PPCTables.cpp
This temporary solution was put in place by https://github.com/dolphin-emu/dolphin/pull/11400 due to the Android NDK being deficient. The NDK has updated since then, so this is no longer necessary.
=> TypeUtils: Remove Common::Fill

Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/Core/DolphinAnalytics.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h, Source/Core/VideoCommon/Present.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
I use Dolphin to play games in a mix of side-by-side 3D and flat 2D. I make use of the hotkey functionality to disable/enable 3D. My 3D glasses have two 1080p screens in them, so when in SBS mode, the aspect ratio of the viewport is 32:9 (each eye is 16:9).
One problem I've noticed is that content being displayed at 16:9 in 2D suddenly becomes squared off when 3D is enabled. This is surprising; if it was widescreen content, why wouldn't it remain widescreen?
In my opinion the "aspect ratio" setting under Graphics is intended to be the aspect ratio of the CONTENT, not the viewport. So when enabling side-by-side 3D, the aspect ratio of the viewport should be double the given value. And when enabling top-and-bottom 3D, the aspect ratio of the viewport should be half the given value.
This …
=> Graphics: Adapt aspect ratio when SBS/TAB 3D is used

Source/Core/DolphinQt/HotkeyScheduler.cpp
Allow connecting or disconnecting multiple Wii Remotes simultaneously instead of only handling the highest index whose hotkey is pressed. This allows using a single hotkey to toggle multiple remotes.
=> HotkeyScheduler: Handle Wii Remote connections independently

Data/Sys/GameSettings/SL2P01.ini, Data/Sys/GameSettings/SLSP01.ini, Data/Sys/GameSettings/ST7P01.ini
Without PAL60 enabled these PAL games display a message that you are running an incompatible video mode and return to the Wii Menu.
=> Gameini: Enable PAL60 for Some PAL Games

Source/Core/DiscIO/WIABlob.cpp
This PR fixes a case of undefined behaviour that caused crashes when compiling Dolphin with Clang and LTO enabled and loading a Metroid Prime 3 RVZ.
A vector of length 0 can have a null data pointer, which causes UB when passed to memcpy, so this PR changes the code to only copy when we actually have data to copy.
This issue was initially encountered in [dolphin-primehack](https://github.com/xiota/dolphin-primehack/issues/1), but also occurs with upstream dolphin.
=> RVZ: Fix undefined behaviour when copying 0 bytes to a null pointer

Source/Core/DolphinQt/MainWindow.cpp
Set the Render window as the parent of the Confirm On Stop confirmation dialog when Keep Window On Top is enabled, ensuring it will always be visible.
Previously, when Keep Window On Top was enabled the Confirm On Stop dialog could be hidden by the Render window in the following situations:
* Clicking Stop in the Main Window
* Clicking the Main Window's close button
* Pressing the Stop hotkey while in FullScreen mode
This was particularly troublesome because the Confirm On Stop dialog is modal, preventing the user from moving the Render window out of the way if it was obscuring the dialog.
Fixes [#13247](https://bugs.dolphin-emu.org/issues/13247).
=> MainWindow: Prevent Confirm On Stop dialog from being hidden by the Render window

Data/Sys/GameSettings/SON.ini
I don't fully understand how the game renders the lyrics but it involves EFB copies and the game notices if they don't work: `N[OSREPORT]: Capturing failed: at TEXELDAT_NORMALTEXT of Old` ("Old" being the first syllable of "Old MacDonald".)
During the song the game renders each syllable first fully in white and then in blue with a growing quad for the currently sung syllable. Also note how the red background of the syllable texture bleeds through some not fully opaque texels.
=> GameSettings: force EFB-to-RAM for My First Songs

Source/Core/VideoBackends/Vulkan/VulkanLoader.cpp, Source/Core/VideoBackends/Vulkan/VulkanLoader.h
This is a minor improvement to add line numbers to the LOG_VULKAN_ERROR define. Basically error logs for Vulkan will now look like:
```
// This
25:03:347 VideoBackends/Vulkan/VulkanLoader.cpp:247 E[Video]: (WaitForCommandBufferCompletion:278) vkWaitForFences failed:  (2: VK_TIMEOUT)
// Instead of
15:45:154 VideoBackends/Vulkan/VulkanLoader.cpp:247 E[Video]: (WaitForCommandBufferCompletion) vkWaitForFences failed:  (2: VK_TIMEOUT)
```
=> vulkan: Add line number to vulkan error logger

Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp
This was accidentally using the instruction's output instead of the instruction's input when the input and output registers were the same.
=> Interpreter: Fix subfic carry calculation

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreterEmitter.cpp
I wasn't aware that even with a size of zero, it's still [not safe](https://en.cppreference.com/w/cpp/string/byte/memcpy) to pass a nullptr to `std::memcpy`. When `CachedInterpreterEmitter::PoisonCallback` is written, UB is happening.
=> CachedInterpreterEmitter: Fix `std::memcpy` UB

Source/Core/Core/Boot/Boot_BS2Emu.cpp, Source/Core/Core/Debugger/BranchWatch.cpp, Source/Core/Core/Debugger/BranchWatch.h, Source/Core/Core/PowerPC/Gekko.h, Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.h, Source/Core/DolphinQt/Debugger/BranchWatchTableModel.cpp, Source/Core/DolphinQt/Debugger/BranchWatchTableModel.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp
- While in the reduction phase, Branch Watch snapshot files will now only contain hits found in the selection. Previously, all hits from the collection were being written despite some no longer being relevant.
- When I created the Branch Watch Dialog, I employed a novel coding style that abused lambdas and the values of assignment statements. I have come to realize this design choice was sub-optimal, plus I have found new design patterns while working on my JIT Widget Refresh project. Across six commits, I have refactored the Branch Watch Dialog to meet the quality I am currently capable of. The sixth refactoring commit contains some notable changes to the construction of context menus in the Branch Watch Tool. Creating breakpoints while the core is not initialized is no longer forbidden …
=> Branch Watch Tool: Refactors, Fixes, and Features

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
The low-pass and biquad filters run in set40 mode where accessing ac#.m returns the value of ac#.hm clamped to 16 bits.
This fixes the crackling in "Need for Speed: Nitro" ([issue 13610](https://bugs.dolphin-emu.org/issues/13610)).
Also make the lower bound match hardware (-0x8000 instead of -0x7FFF).
=> DSPHLE/AX: fix low-pass/biquad clipping

Source/Core/Core/HW/SI/SI_Device.cpp, Source/Core/Core/HW/SI/SI_Device.h
This PR is just like a previous PR of mine: https://github.com/dolphin-emu/dolphin/pull/12762. I found another instance of dead config code by searching for things like `#include <iosfwd>` and stream operator overloads. This now dead code was originally added by https://github.com/dolphin-emu/dolphin/pull/8418/commits/cfbabd4c4116ed042c8e0002ed480e3f4a3dade3.
=> SI_Device: Remove Dead Config Code

Source/Core/DolphinQt/CheatsManager.cpp, Source/Core/DolphinQt/CheatsManager.h, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.h, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.h
Create CheatsManager's ARCodeWidget and GeckoCodeWidget once on startup (in CheatsManager's constructor), and trigger updates to their contents when the current game changes.
Previously, ARCodeWidget and GeckoCodeWidget would be recreated every time a game was started or shutdown. If either of these widgets was the visible tab this would cause the tab to switch to CheatSearchFactoryWidget (since the other tabs temporarily didn't exist), and also could cause a crash if the user initiated a game shutdown and then opened a code edit window before the shutdown finished.
=> CheatsManager: Create Action Replay and Gecko code widgets only once

Readme.md, Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/DolphinTool/DolphinTool.vcxproj, Source/Core/DolphinTool/VerifyCommand.cpp
Allows the user to generate a [RetroAchievements Game Identification](https://docs.retroachievements.org/developer-docs/game-identification.html#nintendo) hash via the command line for GameCube games in all file formats supported by Dolphin. RA does a quick hash of selected files within a disc image, rather than a very slow full MD5 hash.
```
> .\dolphintool.exe verify -i "game.rvz" -a rchash
9be90fd0a49908be157f8c001794699e
```
This is useful for external game launchers like LaunchBox, who need to identify which files are supported by RA so that information can be queried and displayed on their frontend.
This usually done by RAHasher, an external tool provided by the RA developers with the reference implementation on how to hash game files for each platform they support. However, while …
=> Add generation of rcheevos hash as an option in DolphinTool

Data/Sys/GameSettings/DAX.ini, Data/Sys/GameSettings/GMS.ini, Data/Sys/GameSettings/GZ2.ini, Data/Sys/GameSettings/GZL.ini, Data/Sys/GameSettings/RMG.ini, Data/Sys/GameSettings/RZD.ini, Data/Sys/GameSettings/SB4.ini, Data/Sys/GameSettings/SOU.ini
Arbitrary Mipmap Detection doesn't work when GPU Texture Decoding is enabled, so disable GPU Texture Decoding for games where the .ini enables Arbitrary Mipmap Detection.
This skips GMS.ini because that's handled in https://github.com/dolphin-emu/dolphin/pull/13056.
=> GameSettings: Disable GPU Texture Decoding when needed

Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp
If texture dumping is enabled, notify the user on emulation startup using an On Screen Display message.
Also notify the user when texture dumping is toggled.
Addresses https://bugs.dolphin-emu.org/issues/12445.
=> Texture Dumping: Show OSD message on startup and when toggled

Source/Core/Core/GeckoCode.cpp, Source/Core/Core/GeckoCode.h
This was originally added by https://github.com/dolphin-emu/dolphin/commit/80b09c074e610304d3e34ba05c80c41a6d872507 in service of the now absent `Gecko::GeckoCode::Compare` function. `Gecko::GeckoCode::Compare` was modified to no longer use `Gecko::GeckoCode::Exist` by https://github.com/dolphin-emu/dolphin/commit/e91c0222b4a223a8917c70a444aba0c787efb7f9, and was later removed by https://github.com/dolphin-emu/dolphin/commit/e8cd5a3979d6b475d6f0a5299184a32a43850ee0. Nothing uses `Gecko::GeckoCode::Exist` today.
=> GeckoCode: Remove Dead Code

Data/Sys/GameSettings/RGW.ini, Data/Sys/GameSettings/WR2.ini
Saving rabbid with EFB Copies to Texture Only:
Rabbid's texture is saved as fully black.
Saving rabbid without EFB Copies to Texture Only:
Intended behavior.
=> GameINI: Fix tattoo texture saving in Rabbids Go Home

Data/Sys/GameSettings/G8ME01.ini
This is causing graphical glitches on some sprites, specifically the partner character after loading a game.
=> GameINI: Remove Broken Cheat from "Paper Mario: The Thousand Year Door"

Source/Core/DolphinQt/CheatSearchWidget.cpp
Before, Dolphin would randomly crash when updating the cheat search when automatic refresh was enabled. (Having a large number of addresses listed, e.g. by starting with an "any value" search, may contribute). The crash was due to QTableWidget::item returning nullptr in RefreshGUICurrentValues, presumably due to the table being resized on the UI thread while the emulated CPU thread was updating the values. I've fixed this by pausing the CPU thread for the entirety of OnNextScanClicked; this eliminated crashes in my testing.
```
>	Dolphin.exe!CheatSearchWidget::RefreshGUICurrentValues(unsigned __int64 begin_index, unsigned __int64 end_index) Line 608	C++
Dolphin.exe!CheatSearchWidget::UpdateTableRows(const Core::CPUThreadGuard & guard, unsigned __int64 begin_index, unsigned __int64 …
```
=> Fix random crash when using the cheat search

Source/Android/jni/Cheats/GeckoCheat.cpp, Source/Core/Common/ArmCPUDetect.cpp, Source/Core/Common/NandPaths.cpp, Source/Core/Common/StringUtil.cpp, Source/Core/Common/StringUtil.h, Source/Core/Common/x64CPUDetect.cpp, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/FreeLookManager.cpp, Source/Core/Core/HotkeyManager.cpp, Source/Core/Core/IOS/WFS/WFSSRV.cpp, Source/Core/InputCommon/ControllerEmu/StickGate.cpp, Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp, Source/UnitTests/Common/StringUtilTest.cpp
With 12 uses of `JoinStrings` in the codebase vs 36 uses of `fmt::join`, fmtlib's range adapter for string concatenation with delimiters is clearly the preferred option.
=> StringUtil: Remove `JoinStrings`

Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.h, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp, Source/Core/DolphinQt/Debugger/CodeWidget.h, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.h, Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.h, Source/Core/DolphinQt/Host.h, Source/Core/DolphinQt/MainWindow.cpp
There were three distinct mechanisms for signaling breakpoint changes in DolphinQt, and the wiring had room for improvement. The behavior of these signals has been consolidated into the new `Host::PPCBreakpointsChanged` signal, which can be emitted from anywhere in DolphinQt to properly update breakpoints everywhere in DolphinQt.
This improves a few things:
- For the `CodeViewWidget` and `MemoryViewWidget`, signals no longer need to propagate through the `CodeWidget` and `MemoryWidget` (respectively) to reach their destination (incoming or outgoing).
- For the `BreakpointWidget`, by self-triggering from its own signal, it no longer must manually call `Update()` after all of the emission sites.
- For the `BranchWatchDialog`, it now has one less thing it must go through the `CodeWidget` …
=> DolphinQt: A Ubiquitous Signal For When Breakpoints Change

Source/Core/Common/IniFile.cpp, Source/Core/Common/IniFile.h, Source/Core/Common/StringUtil.cpp, Source/Core/Common/StringUtil.h
Migrating `Common::CaseInsensitiveLess` to StringUtil.h will hopefully discourage rolling one's own solution in the future for case-insensitive associative containers when this (quite robust!) solution already exists.
`Common::CaseInsensitiveStringCompare::IsEqual` was removed in favor of using the `Common::CaseInsensitiveEquals` function.
The `a.size() != b.size()` condition in `Common::CaseInsensitiveEquals` can be removed, since `std::ranges::equal` already checks this condition (confirmed in libc++).
And of course, I confirmed config files with weirdly capitalized keys are still loaded and saved as they were before.
=> IniFile: Migrate `Common::CaseInsensitiveLess` to StringUtil

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
Explicitly state that Manual Texture Sampling disables the Texture Filtering setting and that GPU Texture Decoding disables Arbitrary Mipmap Detection, rather than just saying they're incompatible.
=> Graphics: Clarify relationship between incompatible settings

Source/Core/DiscIO/VolumeVerifier.cpp
This runtime assertion was added before `std::is_sorted` became constexpr in the codebase.
=> VolumeVerifier: Promote `DEBUG_ASSERT` to `static_assert`

Source/Core/Core/Boot/Boot.cpp
When HLE-ing the apploader, this is necessary to avoid `Error #002` errors. Homebrew doesn't care.
=> Boot: write Apploader version into memory

Source/Core/VideoCommon/FramebufferManager.cpp
I've been told bounding box is broken on Auto-IR
Pixel shaders not getting up-to-date efb scale seems like a possible cause
This is completely untested, and I have no clue what to test here, but @JMC47 might
=> VideoCommon: Dirty pixel shader manager on efb scale changes

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.h, Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
A couple improvements to what messages are given to the user upon failures: failing to log in, and failing to load data because the emulator version (user agent) is blocked.
=> Achievements Fail Messaging

Source/Core/VideoBackends/D3D/D3DGfx.cpp, Source/Core/VideoBackends/D3D/D3DGfx.h, Source/Core/VideoBackends/D3D12/D3D12Gfx.cpp, Source/Core/VideoBackends/D3D12/D3D12Gfx.h, Source/Core/VideoBackends/Metal/MTLGfx.h, Source/Core/VideoBackends/Metal/MTLGfx.mm, Source/Core/VideoBackends/OGL/OGLGfx.cpp, Source/Core/VideoBackends/OGL/OGLGfx.h, Source/Core/VideoBackends/Software/SWGfx.cpp, Source/Core/VideoBackends/Software/SWGfx.h, Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp, Source/Core/VideoBackends/Vulkan/CommandBufferManager.h, Source/Core/VideoBackends/Vulkan/VKGfx.cpp, Source/Core/VideoBackends/Vulkan/VKGfx.h, Source/Core/VideoBackends/Vulkan/VKSwapChain.cpp, Source/Core/VideoBackends/Vulkan/VKSwapChain.h, Source/Core/VideoCommon/AbstractGfx.h, Source/Core/VideoCommon/Present.cpp
If `vkAcquireNextImageKHR` failed, it wouldn't signal the semaphore it was given, but we'd mark it as used anyways, making us wait for it forever.
Also handles the case where `vkAcquireNextImageKHR` returns `VK_ERROR_OUT_OF_DATE_KHR` immediately after resize (e.g. because the user is still resizing the window) by skipping presentation and trying again next frame.
Thanks to @CasualPokePlayer for tracking down the root cause for both of these issues
=> VideoBackends:Vulkan: Prevent freezes during window resize on Linux

Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTReal.h
When trying to get Bluetooth passthrough to work, it helps to know whether Dolphin is trying to connect to the right USB device.
=> Bluetooth: show vid:pid in error message

Source/Core/VideoCommon/VideoBackendBase.cpp
Prevent potential issues when creating the Graphics window (and thus calling PopulateBackendInfo) while the core state is Stopping, like we already do while it's Starting or Running.
=> VideoBackendBase: Only populate backend info when uninitialized

Data/Sys/GameSettings/SK8.ini, Data/Sys/GameSettings/SKY.ini, Data/Sys/GameSettings/SSP.ini
See commits for reasoning.
I did not forget Swap Force (already done in #12958) nor SuperChargers Racing (different engine, doesn't need either).
Incorrect:
Correct:
Incorrect:
Correct:
=> GameINI: Add Skylanders titles

Source/Core/VideoBackends/Metal/MTLUtil.mm
Still waiting on confirmation that this is everything from https://github.com/OatmealDome/dolphin-ios/issues/163, but this should fix some issues newer iPhone users were having with bbox
=> VideoBackends:Metal: Fix bbox on newer iOS devices

Source/Core/VideoBackends/Vulkan/ObjectCache.cpp, Source/Core/VideoBackends/Vulkan/VKMain.cpp, Source/Core/VideoBackends/Vulkan/VKVertexManager.cpp, Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoBackends/Vulkan/VulkanContext.h
Honeykrisp (Mesa Vulkan driver for Apple GPUs) is in fact *not* MoltenVK, and doesn't appreciate being given things that are only accepted by our custom modified MoltenVK
~~Note: Haven't actually tested this on Apple + MoltenVK yet, will test soon~~ Tested, fbfetch seems to be working fine
=> Vulkan: Don't do MoltenVK things on Asahi Linux

Source/Core/VideoCommon/VertexShaderManager.cpp
When the inverted depth range is unsupported and zRange is greater than farZ then min_depth becomes a negative value and far_depth will then exceed a depth of 1.0 (which is outside the scope of most backends and greater than GX_MAX_DEPTH of the console).
This happens when the backend supports depth clamping the min_depth is not clamped to zero.
Solves most of the issues in Direct3D 11 I've found, specifically this fixes all the depth issues present in [#11720](https://bugs.dolphin-emu.org/issues/11720)
=> Use Vertex Depth Range when zRange Exceeds farZ

Source/Core/Core/ConfigManager.cpp
This problem was introduced in 8842a0f402ffe60a80ce7894bfd36afd039009fc and is likely a copy-paste error.
Fixes the problem mentioned in the issue comment
https://bugs.dolphin-emu.org/issues/13640#note-2.
=> Core: Include partition when calling GetGameTDBID for non-game partition

Source/Core/VideoBackends/Vulkan/VulkanLoader.h
Fixes assertion failures people were getting in vk_mem_alloc after #13050
=> VideoBackends:Vulkan: Increase VMA Vulkan Version to 1.2

Source/Core/VideoCommon/XFStructs.cpp
Indexed XF loads specify the number of 32-bit words (generally floats, but light data has some integers) to load, not the number of bytes. This was only a mistake in the fifo analyzer text; the actual implementation already loaded words.
=> Fifo analyzer: Fix indexed XF loads showing "bytes" instead of "words"

Source/Core/Core/FifoPlayer/FifoPlayer.cpp
The light LIT fifolog from https://bugs.dolphin-emu.org/issues/13635 has position data at physical address 11ae3180. This works fine when using the memory viewer in physical mode, but the corresponding virtual address (91ae3180) previously didn't show anything in effective mode. It works fine now though.
This shouldn't affect playback of fifologs as everything in there uses physical addresses; this only impacts the memory viewer.
This logic was copied from CBoot::SetupBAT:
https://github.com/dolphin-emu/dolphin/blob/339f9311fb86aaf081f2e9ea2ca2c1a1071b35d6/Source/Core/Core/Boot/Boot_BS2Emu.cpp#L114-L137
=> FifoPlayer: Set up additional BATs in Wii mode

Data/Sys/GameSettings/RZI.ini, Source/Core/Core/HW/WII_IPC.cpp
This fixes the texture glitching issue Kolano listed on the wiki: https://wiki.dolphin-emu.org/index.php?title=Winter_Sports_3:_The_Great_Tournament#Downhill_Skiing_Textures.
As a bonus, you also get an unrelated cleanup commit.
=> GameSettings: safe texture cache for "Winter Sports 3: The Great Tournament"

Source/Core/Core/FifoPlayer/FifoRecorder.cpp, Source/Core/Core/HW/GBACore.cpp, Source/Core/Core/HW/WiimoteReal/IOWin.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/DiscIO/Blob.cpp, Source/Core/DiscIO/CompressedBlob.cpp, Source/Core/DiscIO/DirectoryBlob.cpp, Source/Core/DiscIO/LaggedFibonacciGenerator.cpp, Source/Core/DiscIO/TGCBlob.cpp, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DiscIO/WIABlob.cpp, Source/Core/UpdaterCommon/UpdaterCommon.cpp, Source/DSPSpy/ConsoleHelper.h
The algorithms `std::copy` and `std::fill` have alternate forms called `std::copy_n` and `std::fill_n`. These algorithms replace a common idiomatic way of using the copy and fill algorithms, yet they have not been used in several places where they could have been. These changes have very little to do with modernizing algorithms using C++20 ranges, but these are potential changes I noticed while evaluating the entire codebase, thus I am proposing them in case they are deemed valuable.
=> Ranges Algorithms Modernization - N

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
No need to materialize the constant in a register if it's zero, we can just use `WZR`.
Before:
```
mov w27, #0x0 ; =0
str w27, [x29, #0x1178]
```
After:
```
str wzr, [x29, #0x1178]
```
=> JitArm64: Optimize mtspr

Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MainWindow.h, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h
This Windows-specific method of obtaining the current color scheme is now redundant. Since the colorSchemeChanged signal is already being used, it's simpler to just read the mode from QStyleHints as well.
=> Remove unneeded Win32 code for color scheme

Source/Core/DolphinNoGUI/PlatformX11.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/UICommon/CMakeLists.txt, Source/Core/UICommon/DBusUtils.cpp, Source/Core/UICommon/DBusUtils.h, Source/Core/UICommon/UICommon.cpp, Source/Core/UICommon/UICommon.h, Source/Core/UICommon/X11Utils.cpp, Source/Core/UICommon/X11Utils.h
This is a fix for https://bugs.dolphin-emu.org/issues/10392, which has been a problem for at least 7 years now. I've implemented support for several D-Bus interfaces to inhibit the screensaver on Linux, which covers all the desktop environments that I could find that support it. As the xdg-screensaver method doesn't work at all any more, I've removed it completely.
As this uses Qt's D-Bus module, it requires dolphin-emu-nogui to be linked against libQt6DBus.so as well. This only happens if Dolphin is built with Qt enabled, otherwise it is simply skipped. If this isn't acceptable, I can move it into DolphinQt instead.
=> Linux: Use D-Bus to inhibit screensaver

Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
=> DolphinQt/MappingIndicator: Use Settings::IsThemeDark instead of reimplementing it.

Source/Core/InputCommon/ControllerEmu/ControlGroup/MixedTriggers.cpp
I've observed at least two users with non-working trigger inputs because they carelessly set the `Threshold` setting to 100%, effectively making them impossible to activate (because the test was `button_value > threshold`).
This changes the test to `button_value >= threshold` and prevents a threshold value below 1% in the UI.
Maybe this will prevent someone frustration in the future.
=> ControllerEmu: Change trigger threshold check to prevent user error.

Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
This hides the tab bar on the mapping windows if there are fewer than 2 tabs (GameCube Controller, GBA, Microphone, Keyboard).
Before:
After:
I think this resolves this issue: https://bugs.dolphin-emu.org/issues/11019
=> DolphinQt: Auto hide the mapping window tab bar.

Source/Core/DiscIO/WiiSaveBanner.cpp, Source/Core/DiscIO/WiiSaveBanner.h, Source/Core/DolphinQt/Config/InfoWidget.cpp
Fixes: https://bugs.dolphin-emu.org/issues/13062
=> DolphinQt: Restrict size of banner image in game properties info tab.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/ConvertActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionBootActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThemeHelper.kt
Dolphin has been using edge-to-edge rendering for a little while now, but it has required a bit of manual work. Now that edge-to-edge is becoming something expected of apps in Android 15, there's a nicer API we can use.
Tested on Android 8, 11 and 13, with no changes in behavior noted.
=> Android: Use enableEdgeToEdge

Source/Android/app/build.gradle.kts
So far, Dolphin hasn't been able to run on Android devices that use a 16 KiB page size. 16 KiB page sizes are a very new Android feature that no phones have shipped with so far, so we're still compatible with the phones that exist out there, but let's get this fixed before phones start shipping with 16 KiB page sizes.
Because I couldn't get Android Studio's emulator to work, I haven't been able to confirm that this change actually makes Dolphin fully compatible with devices that use a 16 KiB page size. But I have confirmed that this doesn't break anything on a regular 4 KiB page size device.
=> Android: Add 16 KiB page size support

Source/Core/Core/Boot/Boot.cpp
Checksum and descriptions from Redump.
=> Boot: don't error for NTSC IPL v1.2 of DOL-001 consoles

Data/Sys/GameSettings/S7E.ini, Data/Sys/GameSettings/STZ.ini
Fixes hang on opening logos by turning off dual core. This game is also included in Transformers: Ultimate Battle Edition, where the same issue occurs, so dual core is disabled there too.
=> GameINI: Fix Transformers: Dark of the Moon hang on opening logos

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/app/src/main/res/values/strings.xml
Recently we have been getting some requests to make the existing vsync setting available in the Android GUI:
https://bugs.dolphin-emu.org/issues/13650
https://forums.dolphin-emu.org/Thread-vsync-toggle-for-android
I don't quite understand why enabling the vsync setting is helpful when Android already enforces vsync, but I guess having the option available doesn't hurt. I'm putting the setting under Advanced, unlike in DolphinQt, since there's no clear reason why the typical user would want to use this setting.
=> Android: Add vsync setting

Source/Core/VideoCommon/CommandProcessor.cpp
Many games call GXSetGPFifo() without first waiting for the GP to finish consuming outstanding commands in the previous GP fifo. Normally, Dolphin runs OpcodeDecoding in 1000-cycle time slices. In that time frame, GXSetGPFifo() has probably completed and the GP read pointer now points to entirely new memory. If the last GP fifo copy ended in an incomplete command, the new GP fifo would most likely desync for a while. To avoid all this, give the GP a time slice right now to copy the remaining data from the previous GP fifo.
=> VideoCommon: fix common opcode decoding errors

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AX.h, Source/Core/Core/HW/DSPHLE/UCodes/AXStructs.h, Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.h
Three bugs specific to older Wii games:
- The size difference between high-pass and biquad filter was not accounted for, causing wiimote related fields to be corrupted.
- Wiimote sample buffer pointers were advanced by 32 samples per millisecond instead of 6 samples. Usually hidden by the first bug.
- PB updates on Wii were being byte-swapped twice, but I've not actually found any Wii games that make use of PB updates.
This fixes wiimote audio in at least the following games:
- Excite Truck
- Ice Age 2: The Meltdown
- Kororinpa: Marble Mania
- Rapala Tournament Fishing
- Shrek the Third
- Super Monkey Ball: Banana Blitz
- Tiger Woods PGA Tour 07
- WarioWare: Smooth Moves ([issue 11725](https://bugs.dolphin-emu.org/issues/11725))
- Wing Island
=> DSPHLE/AXWii: fix wiimote audio in multiple games

Readme.md
The readme didn't specify which windows 10 version is minimally supported in the System Requirements
=> Readme: specify  which windows 10 version is minimum

Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsMod.cpp, Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsMod.h, Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsModGroup.cpp
In C++20, algorithms from the standard library evolved to feature new niceties and additional compile-time checks. Simultaneously, the way user-defined types should overload comparison operators was revamped by C++20 with the new "spaceship operator" `<=>`.  When standard-library comparison function objects, such as `std::less` or `std::equal`, were given the ranges update treatment, it became a requirement that all six comparison operator overloads (`<`, `<=`, `>`, `>=`, `==`, `!=`) must exist for the compared type. Due to this combination of factors, a few user-defined types in Dolphin's codebase required their comparison operator overloads be modernized before their usage in standard algorithms could be modernized. I have isolated these changes so that they may be recognized and more …
=> Ranges Algorithms Modernization - Compare

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/DolphinQt/Settings/AudioPane.cpp, Source/Core/DolphinQt/Settings/AudioPane.h
Turbo meaning overriding the emulation speed limit (tab).
Adds new Miscellaneous Settings groupbox to bottom of audio panel.
Uses Config::SetCurrent to temporarily mute audio and DeleteKey to undo it.
Small issue is that the audio still crackles a little when coming out of turbo muted.
=> Audio: Add option to temporarily mute audio when using turbo

Data/Sys/GameSettings/GUP.ini
Adjusts the Texture Cache settings/slider to 512 samples which equates to the 'middle' option in the UI.
If using the 'Safe' Texture Cache Accuracy mode, the left screen will only render bloom in 2P modes.
If using the 'Fast' Texture Cache Accuracy mode, the Intro Movie will drop frames near the end when the "Shadow the Hedgehog" game title letters appear. This mode also can result in artifacts/bleed from bloom effects in some situations.
See https://wiki.dolphin-emu.org/index.php?title=Shadow_the_Hedgehog for screenshot examples.
=> GameINI: Shadow the Hedgehog texture cache default

Source/UnitTests/Common/SettingsHandlerTest.cpp
This is needed for `std::ranges::equal()`, on Windows with CMake compilation fails otherwise.
=> Add missing algorithm header in SettingsHandlerTest.cpp

Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
We currently call `Unlock` manually everywhere, which is annoying, especially when the register is only sometimes allocated. By adding a small class we can relieve ourselves of this burden.
Just a quick diff to gauge how other devs feel about this.
=> JitArm64: Release temporary regs with RAII

CMakeLists.txt
It never actually worked.  Our bundled zlib-ng uses zlib compat mode, making it override system zlib. The zlib-ng found by pkg-config will not, and all its functions will be prefixed with `zng_`. Therefore the two aren't actually compatible.  Selecting system zlib-ng in reality just causes compile failures as zlib symbols fail to link.
@Mystro256 (or anyone else looking to restore the ability to use system zlib-ng), the proper solution would be to either
- Make the option one to use system zlib (not ng), and allow people to pick it if they don't mind slower zlib-related tasks (or if their system ships zlib-ng as the system zlib)
- Edit Dolphin and its dependencies to use `zng_` prefixed functions everywhere, and remove the `set(ZLIB_COMPAT ON)` from `Externals/zlib-ng/CMakeLists.txt` (and …
=> Remove option for shared zlib-ng

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Some small optimizations for when the register cache flushes multiple registers at once.
=> JitArm64: Allow ppcState STP optimization for imm

docs/DolphinDeviceIOCTLs.md
This documentation previously resided on WiiBrew before being moved to the [Dolphin Wiki](https://wiki.dolphin-emu.org/), however, I believe it is too developer-focused to remain there. This PR moves it to the repository to (hopefully) increase its discoverability and allow future PRs related to this device implementation to also update the documentation in one go (as suggested by @JosJuice).
=> Migrate /dev/dolphin documentation to the repository

Source/Core/Common/SettingsHandler.cpp, Source/Core/Common/SettingsHandler.h, Source/Core/Core/Boot/Boot_BS2Emu.cpp, Source/Core/Core/IOS/DolphinDevice.cpp, Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp, Source/UnitTests/Common/SettingsHandlerTest.cpp
This PR is the follow-up to PR #12737. Now that we can only use a single `SettingsHandler` instance for either reading or writing settings, but not both, it makes sense to separate out the reading and writing APIs into separate classes.
=> Split `SettingsHandler` into separate reader and writer classes

Source/Core/Core/ConfigManager.cpp, Source/Core/Core/PatchEngine.cpp, Source/Core/Core/PatchEngine.h
We currently don't have a way to apply game patches before the first frame has rendered. Riivolution has this feature but I'm not sure there is a good way to use it for patches we want to ship enabled by default. Instead, apply Dolphin OnFrame patches (and only those) right after boot. The apploader, if any, is still not patchable.
You can test this with the following SSX Tricky (GSTE69) patch that limits the initial EFB clear height to the XFB height in order to avoid a [buffer overflow into the start of the GP fifo](https://bugs.dolphin-emu.org/issues/12818):
```
[OnFrame]
$Fix startup error
0x8012707C:dword:0xA0DF0006
```
=> Core: apply Dolphin OnFrame patches right after boot

Flatpak/SDL2/SDL2.json, Flatpak/fill_release_node.sh, Flatpak/org.DolphinEmu.dolphin-emu.metainfo.xml.in, Flatpak/org.DolphinEmu.dolphin-emu.yml
Includes the following:
- `org.DolphinEmu.dolphin-emu.metainfo.xml.in` this file contains general information and metadata that is used by most linux based app stores (kde discover, gnome software, flathub.org, etc) to showcase dolphin.
- `fill_release_node.sh` a script to automatically fill in the release information in the metainfo file when building the flatpak.
- `SDL2.json` manifest to build the vendored version of SDL from the `Exports` directory, it's only temporarily needed until the kde runtime is updated with the current SDL2 version and should be deleted after.
- `org.DolphinEmu.dolphin-emu.yml` the manifest itself.
=> Add manifest for building as a flatpak

Source/Core/VideoCommon/VertexLoaderManager.cpp
Seems people are hitting the "needs primitive breaking" assert with VS expansion enabled.  Assuming the games that are doing it are using line lists or point lists (probably point lists, not sure what you'd want with 8K lines), this should fix it.  If games are making 16K long line strips, I will scream.
Note: I've tested running a game that doesn't hit the assert, but the actual primitive breaking is completely untested.  Please test.
=> VideoCommon: Implement primitive breaking for primitive lists

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/GeckoCode.cpp, Source/Core/Core/HLE/HLE.cpp, Source/Core/Core/Host.h, Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/PowerPC.cpp, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Debugger/JITWidget.cpp, Source/Core/DolphinQt/Debugger/JITWidget.h, Source/Core/DolphinQt/Debugger/JitBlockTableModel.cpp, Source/Core/DolphinQt/Debugger/JitBlockTableModel.h, Source/Core/DolphinQt/Host.cpp, Source/Core/DolphinQt/Host.h, Source/Core/DolphinTool/ToolHeadlessPlatform.cpp, Source/DSPTool/StubHost.cpp, Source/UnitTests/StubHost.cpp
It was brought to my attention that loading symbols causes the HLE patch engine to invalidate JIT blocks, potentially leading to stale references in `JitBlockTableModel`. Upon further examination, I noticed a few other places I failed to consider could cause stale references, so I addressed those as well. The "solution" of simply putting `Host_JitCacheInvalidation` in many disparate places across the codebase is not ideal, but I unfortunately cannot emit this signal from the JitCache's `InvalidateICache`(`Line`) functions because those functions gets called by `icbi`/`dcbi`/etc. tens of thousands of times whenever booting most software. I am actively pursuing a better solution, but I'd rather not leave my latest merged project with such a glaring flaw for too long, especially when …
=> JitBlockTableModel: Catch All Block Invalidating Events (I Hope)

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
`SDL_JOYDEVICEREMOVED` event `jdevice.which` value was incorrectly used as a device "index" instead of an "instance id", causing `GameController` objects to not be found and removed.
(Broken in #12085)
Index and instance-ID values initially align, so hotplug appeared to work and then totally fell apart after the first unplug.
=> ControllerInterface/SDL: Fix device removal event processing.

Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MainWindow.h
As promised: this PR cleans up 44 uses of `Core::System::GetInstance` in MainWindow.cpp, many of which I am responsible for.
=> MainWindow: Avoid Global System Accessor

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Disables the DualSense controller's Player LED.
Does not apply to Android, as Android itself manages the Player LED.
System default before Dolphin runs (windows/linux)
When Dolphin runs (before change)
When Dolphin runs (after change)
----
* There is no option to disable the Player LEDs currently.
* The player LED is exceptional bright (and its a white LED). This is distracting/bright when playing in low lighting conditions.
* You can already tell which player is which due to the customized primary LED colors.
* I've seen people use SteamInput or DS4Windows specifically to turn off the Player LED. This alleviates users having to do that.
In the future I would like to build a UI to allow customization of the Primary LEDs, and at that point I'd add in a Player LED toggle.
In the interim …
=> InputCommon: Disable Player LED for DualSense Controllers by default

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.kt, Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Config/MainSettings.cpp, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp, Source/Core/VideoCommon/VideoBackendBase.h
In the Graphics window's General tab, recommend the platform's default video backend in the Backend tooltip instead of always recommending OpenGL.
Resolves https://bugs.dolphin-emu.org/issues/13660.
Tested on Windows and macOS (which now recommend Direct3D 11 and Metal respectively).
=> Generalwidget: Recommend default video backend

Source/Core/InputCommon/ControllerInterface/Android/Android.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.h, Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp, Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.cpp, Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp, Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp, Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
The old `AddAnalogInputs` name unsurprisingly confused people in the past.
I renamed the function and explained its use in a comment.
=> InputCommon: Rename AddAnalogInputs to AddFullAnalogSurfaceInputs.

Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp, Source/Core/Core/IOS/USB/USB_HID/HIDv4.h
Between races during Skylanders Superchargers Racing (with both a real and the emulated portal), the game calls IOCTL_USBV4_SHUTDOWN, which then removes from memory references to connected devices. When the next race begins, the game calls IOCTL_USBV4_GETVERSION, then IOCTL_USBV4_GETDEVICECHANGE, however because we haven't added or removed a device manually, TriggerDeviceChangeReply is not called to populate the references in memory to the already attached devices. I have added a new flag that is set to true when Shutdown is called, so that we call  TriggerDeviceChangeReply after shutdown during gameplay.
Fixes https://bugs.dolphin-emu.org/issues/13282
=> IOS/USB: Reconnect HIDv4 Devices after shutdown

Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
The disabled code for dumping a wave file no longer compiles.
`WaveFileWriter` no longer has `AddMonoSamples`.
I don't think we want disabled code like this, anyways.
=> WiimoteEmu: Remove disabled and no-longer-compiling wav dumping code.

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Host.h, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Host.cpp, Source/Core/DolphinTool/ToolHeadlessPlatform.cpp, Source/DSPTool/StubHost.cpp, Source/UnitTests/StubHost.cpp
The GDB stub is capable of adding and removing breakpoints. Failing to signal here:
- Leaves the breakpoint, code, and memory widgets with outdated visual information.
- Potentially leaves the JIT widget with stale references to invalidated JIT blocks. (eek!)
I opted against creating the `Host_PPCBreakpointsChanged` function during https://github.com/dolphin-emu/dolphin/pull/13065 because nothing needed it then, but now something does.
=> GDBStub: Signal Breakpoint Changes To Host

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Before:
After:
We're still exposing XInput and WGInput *and* SDL (using XInput). But it's an improvement.
=> ControllerInterface/SDL: Disable SDL's Windows.Gaming.Input controller handling.

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp
If the host is in hardcore mode, all joining players will be set to hardcore mode; if not, all joining players will be set to softcore.
=> Force NetPlay Clients to Host Hardcore Status

CMakeLists.txt, Externals/SDL/CMakeLists.txt, Flatpak/SDL2/SDL2.json, Flatpak/org.DolphinEmu.dolphin-emu.yml
Changes since 2.30.6 per https://github.com/libsdl-org/SDL/releases/tag/release-2.30.9
```
2.30.9
Fixed audio issues on Android 15
Fixed rare audio distortion and crash when audio devices are changed on Windows
Fixed the PS5 controller face buttons on Amazon Fire TV
Fixed detecting the Steam Virtual Gamepad on macOS
Added support for wired XBox controllers on macOS 15.0 Sequoia
Added support for the Steam Virtual Gamepad on macOS Sequoia
Fixed the Steam Virtual Gamepad from showing up when games aren't running under Steam
Fixed flicker when entering/exiting fullscreen or moving the window between scaled and non-scaled displays under Wayland.
Fixes for data addresses above 2gb on Emscripten
Fixed horizontal mousewheel scale on Emscripten
2.30.8
Fixed a crash in XInput code at startup
Fixed …
```
=> Externals: Update SDL to 2.30.9

Data/Sys/GameSettings/SCD.ini, Data/Sys/GameSettings/SHU.ini
This fixes text on the menu and in-game.
Previously tested by @JMC47 (though I'm not sure if it was the regular version or the special edition that was tested; the main difference is that the special edition has an option for a questionable cel-shading effect).
There's still a possibility of some audio issues in this game, but I don't own it (so I couldn't confirm if it was an HLE vs LLE difference) and couldn't find any videos of it on real hardware that had stereo audio.
=> GameINI: Use Safe Texture Cache for Cabela's Dangerous Hunts 2011

Source/Core/InputCommon/GCAdapter.cpp
The read thread could call Reset, which in turn tried to join the read thread, leading to a SIGABRT. This manifested as Dolphin consistently crashing when disconnecting a GC adapter and having a chance of crashing a few seconds after connecting a GC adapter.
=> Android/GCAdapter: Don't join current thread

Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp, Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h, Source/Core/DolphinQt/Config/Mapping/MappingWidget.h, Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
`INDICATOR_UPDATE_FREQ = 30` was causing my variable refresh rate monitor to run at 30hz when within the controller mapping window (in Plasma/Wayland).
Making the system mouse cursor and everything run at 30hz is terrible.
Mapping indicators now update at the screen refresh rate as advertised by Qt.
I'm not sure if this is the ideal way to do this, but it's a major improvement over a 30hz mouse cursor.
I'll note that this does seem to properly change frequency as I drag the window to differently spec'd monitors.
=> DolphinQt: Update mapping indicators at screen refresh rate.

Data/Sys/GameSettings/GED.ini
The patch introduced in PR #13154 also fixed the hang after the Allan Poe quote that occurs when running Eternal Darkness in Dual Core mode. Gave a more throughout test in Dolphin 2412 by playing Chapters 0 and 1 with Dual Core and haven't noticed any other issues, so I think it's safe to drop this override now...
=> GameINI: drop Single Core override from Eternal Darkness

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Controller battery level is now exposed for pass-through to emulated wii remote.
Tested with a DualSense controller on Linux.
=> ControllerInterface/SDL: Add Battery Input.

Source/Core/DolphinQt/TAS/IRWidget.cpp, Source/Core/DolphinQt/TAS/IRWidget.h, Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp
This apparently didn't compile on macOS six years ago before c++20, but it should be fine by now.
While I'm at it, make the constants upper case per convention.
=> IRWidget: Move header constants into class

.gitignore
[See the command reference for more information.](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#idm384)
=> gitignore: Ignore flatpak-builder's cache directory

Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
=> DolphinQt: Make mapping window spinboxes horizontally expanding.

Source/Core/Common/SymbolDB.h, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/Boot/Boot.h, Source/Core/Core/Boot/DolReader.h, Source/Core/Core/Boot/ElfReader.cpp, Source/Core/Core/Boot/ElfReader.h, Source/Core/Core/Debugger/RSO.cpp, Source/Core/Core/PowerPC/PPCSymbolDB.cpp, Source/Core/Core/PowerPC/PPCSymbolDB.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp
This PR adds code that checks for extra information following symbol names that is often present in CodeWarrior symbol maps, namely the names of the .a/.o files that symbol belongs to. If present, the symbol name string is truncated to remove the extra text from the symbol name.
=> Core: Store object name separately for symbols

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/Jit_Util.cpp
The value being stored must be loaded into a register. In the case of an immediate value, this means it must be materialized. The value is eventually byteswapped before performing the store.
This can be simplified for the value 0 for two reasons:
- ARM64 has a dedicated zero register, so does not need to be materialized.
- Byteswapping zero is still zero, so we can skip this step.
We could skip byteswapping for all values by immediately materializing the byteswapped value in a register, but the benefits are not so clear there (if the value needs to be materialized anyway, it is better to do it up front).
Before:
```
0x5280001b   mov    w27, #0x0                 ; =0
0xb9404fba   ldr    w26, [x29, #0x4c]
0x12881862   mov    w2, #-0x40c4              ; =-16580
0x0b020342   add    w2, w26, …
```
=> JitArm64_LoadStore: Optimize zero stores in stX

Data/Sys/GameSettings/GFH.ini
This fixes the loading screens that show a walking animation.
=> GameSettings: set EFBAccessEnable=True for Neighbours from Hell

Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h
Normally, the asserts added in 34b0a6ea90 are only triggered when something actually went wrong in Dolphin. But there is one exception: In FallBackToInterpreter, we flush all registers regardless of whether they're discarded. This is fine as long as none of the discarded registers are inputs to the instruction that the interpreter will run.
To avoid false positive asserts, this change adds a parameter to Flush that controls whether to skip the asserts for discarded registers.
Additionally, an assert for discarded registers is added to Arm64FPRCache::Flush. (Previously JitArm64 asserted for GPRs (and CRs) only, whereas Jit64 asserted both for GPRs and FPRs. I most likely didn't think of FPRs when writing 34b0a6ea90.)
=> Jit: Skip discarded registers when flushing for interpreter fallback

Source/Core/Core/AchievementManager.h, Source/Core/DolphinTool/VerifyCommand.cpp
This was causing compilation errors when building without USE_RETRO_ACHIEVEMENTS.
=> AchievementManager: Add required forward declarations

Source/Core/VideoBackends/Vulkan/VKSwapChain.cpp
`VKSwapChain` will use whatever `VK_FORMAT_R8G8B8A8_UNORM` or `VK_FORMAT_B8G8R8A8_UNORM` surface format comes last in the array returned by `vkGetPhysicalDeviceSurfaceFormatsKHR`, but the ordering of items within the array is seemingly arbitrary.
On some devices running MoltenVK, the last `VK_FORMAT_B8G8R8A8_UNORM` format happens to be one with the `VK_COLOR_SPACE_HDR10_ST2084_EXT` color space. Using this will cause non-HDR content to be rendered in an HDR-enabled `CAMetalLayer`.
This bug might affect other drivers as well?
Thanks to @TellowKrinkle for the help.
=> VKSwapChain: Always use surface formats with a normal sRGB color space if not RGBA16F

Source/Android/jni/AndroidCommon/AndroidCommon.cpp, Source/Core/Common/FileSearch.cpp, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/Movie.cpp, Source/Core/DiscIO/NANDImporter.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp
In C++20, algorithms from the standard library evolved to feature new niceties and additional compile-time checks. A few of these updated algorithm functions (found in the `std::ranges` namespace) have new return values, and thus code beyond the expression being modernized must also be updated. I have isolated these changes so that they may be recognized and more easily understood.
=> Ranges Algorithms Modernization - Return

Source/Core/Core/AchievementManager.h
This is an implementation detail that doesn't need to be exposed.
=> AchievementManager: Make SetHardcoreMode private

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Config/ConfigControls/ConfigBool.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigBool.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigControl.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigFloatSlider.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigFloatSlider.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigInteger.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigInteger.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigRadio.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigRadio.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.h, Source/Core/DolphinQt/Config/GameConfigWidget.cpp, Source/Core/DolphinQt/Config/GameConfigWidget.h, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.h, Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp, Source/Core/DolphinQt/Config/Graphics/HacksWidget.h, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/GameList/GameList.cpp
*edit* Reworked and ready to be reviewed.
Follows iwubcode's suggestion below.  Adds tabs to game properties window that allows editing game-specific GFX settings.  Uses the existing GFX widgets as new tabs, but passes a game layer to them that's outside the global game layer system.  This is the solution I came to after trying multiple things.
Features:
- Right click gfx option to remove it from the ini
- Edit multiple games at once
- Edit while a game is running, but only activates settings when window is closed (not sure how safe it is to do it more often).
Notes:
This PR integrates with the ConfigBool, etc widgets that set most GFX settings.  The GFX settings outside of this system require too much editing for this PR. They would need to be conditionally redirected to the custom …
=> Add ability to edit game-specific GFX settings from game properties tab.

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Prefer BLENDVPD over VBLENDVPD if the latter doesn't save any instructions.
VBLENDVPD allows separate source and destination registers, which can eliminate a MOVAPD/MOVSD. However, on Intel since Skylake, VBLENDVPD takes additional uops to execute compared to BLENDVPD (according to https://uops.info). On AMD and older Intel microarchitectures there is no difference.
=> Jit_FloatingPoint: fselx - Prefer BLENDVPD over VBLENDVPD

Source/Core/DolphinQt/Config/ConfigControls/ConfigBool.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigFloatSlider.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigInteger.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigRadio.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.h
During a final refactor and fixup, some member variables accidentally got changed to references.
=> Qt crash hotfix

Source/UnitTests/Common/StringUtilTest.cpp
This PR leaves coverage of paths containing Windows drives to a follow-up PR, since some of the edge case handling there is platform-specific.
=> Add some unit test coverage of the `SplitPath` function

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.kt
It happened due to a typo from SECTION_GFX_HARDWARE
=> Android: Fix VSync option not working

Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.h, Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp, Source/Core/DolphinQt/Config/Graphics/HacksWidget.h
See https://github.com/dolphin-emu/dolphin/pull/13234#issuecomment-2561573588
We have to extend the ConfigSlider class a little bit for this use case, but it's pretty straightforward.
Less code and makes it work with the per-game config system. Seems like the obvious way to go to me?
=> DolphinQt/HacksWidget: Convert accuracy slider to ConfigSlider

Source/Core/Common/CMakeLists.txt, Source/Core/Common/Contains.h, Source/Core/Common/NandPaths.cpp, Source/Core/Core/Config/DefaultLocale.cpp, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/Debugger/CodeTrace.cpp, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/State.cpp, Source/Core/Core/WC24PatchEngine.cpp, Source/Core/Core/WiiUtils.cpp, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DolphinLib.props, Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/NetPlay/ChunkedProgressDialog.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/InputCommon/ControllerInterface/Android/Android.cpp, Source/Core/UICommon/ResourcePack/ResourcePack.cpp, Source/Core/UICommon/X11Utils.cpp, Source/Core/VideoBackends/Vulkan/VKSwapChain.cpp, Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoCommon/GraphicsModSystem/Runtime/CustomPipeline.cpp, Source/Core/VideoCommon/VertexManagerBase.cpp, Source/Core/VideoCommon/VideoConfig.cpp
In C++23, two new standard library algorithms were introduced: `std::ranges::contains` and `std::ranges::contains_subrange`. These algorithms are replacements for common idiomatic uses of `std::find`(`_if`) and `std::search`. Unfortunately, we are not yet able to use C++23 features in this codebase. Fortunately, we don't have to wait, as implementing this function [is easy](https://en.cppreference.com/w/cpp/algorithm/ranges/contains#Possible_implementation)! I have isolated these proposed changes so that they may be considered and hopefully accepted.
=> Ranges Algorithms Modernization - Contains

Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h, Source/Core/VideoCommon/FrameDumpFFMpeg.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
Replaces FFV1 codec checkbox with Ut Video.  To still use FFV1, one would have to uncheck "Use lossless" and set DumpCodec =  ffv1, which is currently what it takes to use Ut Video.
Users who previously had FFV1 checked will need to re-enable the Use Lossless replacement.
Requested here:
https://bugs.dolphin-emu.org/issues/13657
<details>
<summary>Abandoned Plan</summary>
Requested here:
https://bugs.dolphin-emu.org/issues/13657
Problem: "UseFFV1" should no longer be needed, but I'm not sure how/where to convert that over so it doesn't collide.
</details>
=> AdvancedWidget: Replace FFV1 codec with Ut Video

CMake/DolphinInjectVersionInfo.cmake, CMake/ScmRevGen.cmake, CMakeLists.txt, Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Info.plist.in, Source/Core/MacUpdater/CMakeLists.txt, Source/Core/MacUpdater/Info.plist.in, Source/Core/VersionInfo.plist.in
Some generators (like `Unix Makefiles` and `Xcode`) copy an app's `Info.plist` at configure time. This causes a problem when we need to generate the `Info.plist` at build time, like how we currently do it with ScmRevGen.
Instead of generating the `Info.plist` directly in ScmRevGen, provide an `Info.plist` without any version information to CMake at configure time, have ScmRevGen generate a separate plist file with the version information at build time, and then merge the two together to create the final `Info.plist`.
Fixes https://bugs.dolphin-emu.org/issues/13669.
(This PR also includes a bonus fix for codesigning in Xcode.)
=> ScmRevGen: Don't generate Info.plist files directly

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
MUL and SUB can be combined in one instruction.
Before:
```
0x1b1a7c01   mul    w1, w0, w26
0x4b010318   sub    w24, w24, w1
```
After:
```
0x1b1ae018   msub   w24, w0, w26, w24
```
=> JitArm64_LoadStore: Small dcbx optimization

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.h
This PR implements a bunch of missing optimization opportunities regarding the carry flag.
- addex
<details><summary>Optimize InPPCState for 0</summary>
Before:
```
0x394bd3b8 ldrb w24, [x29, #0x2f4]
0x2a1803f9 mov w25, w24
```
After:
```
0x394bd3b9 ldrb w25, [x29, #0x2f4]
```
</details>
<details><summary>Optimize InHostCarry for 0</summary>
Before:
```
0x5280001b   mov    w27, #0x0                 ; =0
0x1a1f037b   adc    w27, w27, wzr
```
After:
```
0x1a9f37fb   cset   w27, hs
```
</details>
<details><summary>Optimize InHostCarry for -1</summary>
Before:
```
0x1280001a   mov    w26, #-0x1                ; =-1
0x1a1f035a   adc    w26, w26, wzr
```
After:
```
0x5a9f23fa   csetm  w26, lo
```
</details>
- addzex
<details><summary>Optimize ConstantFalse for 0</summary>
Before:
```
0x52800119 …
```
=> JitArm64_Integer: Carry flag optimizations

Source/Core/Core/ConfigLoaders/MovieConfigLoader.cpp, Source/Core/Core/Movie.h
Recently there was some issues in TASVideos trying to sync a Donkey Kong Country Returns TAS. It eventually was synced by directly using the config from the TAS author. The exact setting which caused the desync was narrowed down to being in SYSCONF, with the country code. The TAS author lives in the US, so the country code matched the US country code, while the person attempting to sync the TAS did not live in the US.
Adding SYSCONF country code to the DTM should avoid this being an issue for future Dolphin versions.
=> Add SYSCONF country code to DTM

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp, Source/Core/DolphinQt/Config/Mapping/IOWindow.h, Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt/Config/Mapping/MappingButton.h, Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp, Source/Core/DolphinQt/Config/Mapping/MappingCommon.h, Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWidget.h, Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWindow.h, Source/Core/DolphinQt/QtUtils/BlockUserInputFilter.cpp, Source/Core/DolphinQt/QtUtils/BlockUserInputFilter.h, Source/Core/InputCommon/ControllerInterface/CoreDevice.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.h
Normal Mapping Window:
Multiple input mappings can be queued/un-queued/cleared without the UI blocking.
This allows for quicker batch input mapping for power users.
Mapping a mouse-click itself requires clicking *not* on a mapping button.
Each mapping button interaction resets the timeout.
Waiting for the timeout cancels all queued input mappings.
Interacting with the window in other ways cancels in-progress mappings appropriately.
https://github.com/user-attachments/assets/86bd87a9-4740-4068-8f5d-b3bf52bd991f
"Advanced" Window:
The live previews now update while detecting inputs.
Button labels are renamed to be more clear.
https://github.com/user-attachments/assets/97cbf69d-4d38-452c-9725-09f5668a8efb
Output/Rumble test in the "Advanced" window is also now non-blocking.
Clicking it while …
=> DolphinQt/InputCommon: Make input mapping and output testing non-blocking.

Source/Core/Core/DSP/DSPAssembler.cpp, Source/Core/VideoCommon/PostProcessing.cpp
Logic of the form, `while (!eof)`, is almost always "wrong".
The success of the actual read needs to be tested, which may or may not trigger eof.
The three pieces of code I found with `while (!eof)` did *also* test that the read was successful, so the behavior was correct, but the `eof` checks were still unnecessary and made the loops awkward.
=> Core/VideoCommon: Fix some weird (!eof) logic.

Source/Core/Common/Logging/Log.h, Source/Core/Common/MsgHandler.h, Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp
This PR fixes compilation with libfmt 11.0 and later. Without this fix, the build fails on Arch Linux with fmt 11.1.1.
The main changes are that `fmt::detail::is_compile_string` no longer exists and that `fmt::string_view` is no longer directly constructible from compile time format strings (not sure exactly why), but manually constructing a `fmt::format_string` before converting to `fmt::string_view` works.
The change to fmt v11 also brought up that BBA/HLE `BuiltIn.cpp` seems to contain an invalid format string that hasn't been caught previously, fixed that as well.
Tested compilation and basic functionality with the bundled fmt 10.2.1 and with fmt 11.1.1.
I'm not sure if the implementation is perfect, I'll try to find a cleaner way to do this that requires fewer `#ifdef`s and I'm also …
=> Fix compiling with libfmt>=11.0

Source/Core/Common/IniFile.cpp
`values` uses a case insensitive comparison, so erasing the equivalent key in `keys_order` also must do so.
=> Common/IniFile: Fix case sensitivity mismatch in IniFile::Section::Delete()

Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp, Source/Core/DolphinQt/Config/Mapping/GCPadWiiUConfigDialog.cpp
"GameCube Adapter for Wii U" is an outdated and confusing name.
Nintendo seems to currently name the device, "GameCube™ Controller Adapter".
I added "(USB)" to hopefully prevent confusion with the "Standard Controller".
Renaming this is somewhat of a blocker for #10489.
I'm open to other suggestions.
=> DolphinQt: Rename "GameCube Adapter for Wii U".

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
No games seem to use this, so this isn't useful as a performance optimization, but it's required for correctness because the (sh == 0) case of our implementation doesn't handle zero masks.
=> JitArm64: Handle rlwinmx with zero mask

Source/Android/jni/MainAndroid.cpp
When we boot the core, it needs to have a valid surface to draw graphics to. Our Kotlin code does wait for a valid surface to exist before it calls NativeLibrary.Run, but there's a chance for the surface to be deleted before Run locks s_surface_lock. If that happens, the core boots without a valid surface, which presumably would cause a crash. (I haven't been able to reproduce the problem myself.)
=> Android: Wait for surface in Run

Source/Core/Core/PowerPC/PPCSymbolDB.cpp
~~This PR is an attempt to debug https://github.com/dolphin-emu/dolphin/pull/13195 issues.~~ I'm migrating the change here since it seems to fix the flatpak issue.
This PR refactors parts of the loading/saving process of symbol map. This PR fixes issues I had where some symbols weren't loaded properly (which might get saved later). Here are some examples on how they can alter existing symbol maps.
This issue was also caused by the `namepos`/`strstr` logic which is flawed when the name is small and equals to part of the symbol address, size or vaddress. Moreover, checking for a space doesn't work when alignment is 16. I've seen this alignment value on some `*fill*` symbols.
```diff
-80468370 00000008 80468370 0 TRKPositionFile (entry of .text)  TRK_Hollywood_Revolution.a …
```
=> PPCSymbolDB: Refactor SymbolMap Save/Load

Source/Core/Core/PowerPC/PPCSymbolDB.cpp
Symbol maps ending in CRLF were not properly loading on non-windows systems.
Test map used:
https://github.com/ShadowTheHedgehogHacking/shadow-symbols-and-dmw/blob/main/GUPE8P.map
```
48261 symbols loaded, 0 symbols ignored.
```
```
windows:  48261 symbols loaded, 0 symbols ignored.
mac:  37436 symbols loaded, 10825 symbols ignored.
linux:  37436 symbols loaded, 10825 symbols ignored.
```
`all platforms: 48261 symbols loaded, 0 symbols ignored.`
=> PPCSymbolDB: Fix loading maps with CRLF endings

Source/Core/VideoCommon/HiresTextures.cpp, Source/Core/VideoCommon/HiresTextures.h, Source/Core/VideoCommon/TextureCacheBase.cpp
Resolves duplicate OSD messages for Loading and Found custom textures. 
Upon VideoBackend initialization HiresTexture::Init will be called, which previously called HiresTexture::Update.
This PR removes HiresTexture::Init as it no longer serves a purpose.
**Before:**
**After:**
**Reproduce Steps:**
1. Enable Graphics -> Advanced -> Load Custom Textures
2. (Optional) Enable Prefetch Custom Textures (this changes the message between Loading and Found)
3. Launch a game
4. Observe the double message
**Suggested Testing:**
1. Test with game window embedded in Main Window, and without
2. Test with DynamicInputTexture scenarios
3. Test with multi-layer texture scenarios (e.g. 'GUP' folder and 'GUPR8P' folder)
4. Launching a game from the Wii menu and make sure the textures load. - iwubcode
=> Core/VideoCommon: Fix duplicate OSD Custom Textures messages

Data/Sys/GameSettings/GS2E78.ini
Summoner: Goddess Reborn will reinitialize the sound system buffers during transitions while sounds are still being played. There are still pointers in the sound list to sounds in those buffers when the buffers get cleared, so the game crashes with a null pointer dereference if an Audio Interface DMA interrupt is triggered while in that state. 
This patch will clean up the pending sound list during sound system reinitialization before continuing to the sound system initialization call previously at 0x8017E338 (On GS2E78).
I would need to work with other people to patch the other regions of the game. If they need patching that is.
=> GameINI: fix `Summoner: Goddess Reborn` sound system crash during transitions

Data/Sys/GameSettings/G2M.ini, Data/Sys/GameSettings/GM8.ini
All of the GameCube versions of *Metroid Prime* and *Metroid Prime 2: [Dark] Echoes* only support 4:3, not 16:9.  
Currently, Dolphin's widescreen heuristic will fail to detect this and will erratically switch between 4:3 and 16:9 when Aspect Ratio is set to Auto.  
These changes prevent the erratic aspect ratio switching by manually declaring that the game is solely 4:3.
=> Force Metroid Prime GCN and Metroid Prime 2 GCN to be 4:3

Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigControl.h, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
When a game starts and the game config is loaded, the signal block on ConfigChanged will prevent options from updating properly, such as triggering an enable/disable for some options that are linked.  The signal block was used to prevent triggering a Save.
Programmatic updates that change the value to something different from the config need to be saved. "VBI skip" triggering "skip duplicate XFBs" is one example. 
ConfigChanged updates change the value of an option to be consistent with the new config, and should not trigger a Save, because that triggers another ConfigChanged.
I dropped the SignalBlocker in favor of an m_updating bool, to only block the re-saving.
A different solution would be to just shove every enable/disable/etc check under the ConfigChanged signal. I don't really like …
=> Qt: Fix some options not changing enabled status on game start.

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
When I wrote 71e97665192ef45487262fcdd4df2286208e61cd, there was an interaction I didn't take into account: When setting eq, SetCRFieldBit assumes that all bits in the passed-in host register except the least significant bit are 0. But if we use BIC/EON/ORN, all bits except the least significant bit get set to 1. This can cause eq to end up unset when it should be set.
This pull request fixes the issue.
=> JitArm64: Fix creqv/crorc setting eq bit

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
Sorry, this is a proper version of PR #13277.
Apparently `closeEvent` isn't actually a Qt signal, it's just a member function.
Don't ask me why the code compiled that way.
This fixes the `qt.core.qobject.connect: QObject::connect: signal not found in IOWindow` message that I introduced.
=> DolphinQt: Fix QObject::connect: signal not found in IOWindow error.

Externals/minizip-ng/CMakeLists.txt, Externals/minizip-ng/minizip-ng.vcxproj, Source/Core/Common/MinizipUtil.h, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/UICommon/ResourcePack/ResourcePack.cpp
Minizip-ng 4.0.8 introduced a change where the compatibility layer was split into multiple source files. This caused dolphin to fail to build.  This PR aims to remedy that.
I tested compilation and launching a game that uses a resource pack, which both worked fine for me.
=> Fix build with minizip-ng>=4.0.8

Source/Core/Common/CMakeLists.txt, Source/Core/Common/MemArena.h, Source/Core/Common/MemArenaDarwin.cpp
This implements all the `MemArena` and `LazyMemoryRegion` functions using Mach APIs. We can't use the generic Unix implementation on some Apple platforms as they don't support shared memory. However, we can easily re-create the existing functionality with [`mach_make_memory_entry_64`](https://fdiv.net/2019/08/13/mirror-mirror-or-dont-fly-handle).
Also, I use the normal `vm` APIs instead as the newer `mach_vm` APIs aren't available on those same platforms. As far as I can tell, [the `mach_vm` APIs were introduced to properly handle a scenario where virtual memory is manipulated cross-process and the architectures differ (for example, one is 32-bit and the other is 64-bit)](https://stackoverflow.com/a/67116629). We don't need to worry about that.
First part in a (probably very long) PR …
=> MemArena: Add Darwin implementation

Source/Core/InputCommon/ControlReference/ExpressionParser.cpp, Source/Core/InputCommon/ControlReference/ExpressionParser.h
=> InputCommon/ExpressionParser: Require delimited tokens actually have their terminating delimiter.

Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt/Config/Mapping/MappingButton.h, Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp, Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h, Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
The bold text was ugly and this is more visually similar to the other indicators.
[Screencast_20250117_235817.webm](https://github.com/user-attachments/assets/fcad6fa6-564a-4397-a85e-d9afda8ddeaf)
=> DolphinQt: Replace MappingButton bold text with graphical indicators.

Data/Sys/GameSettings/GWR.ini
As mentioned in
https://wiki.dolphin-emu.org/index.php?title=Wave_Race:_Blue_Storm, the menu may freeze otherwise.
* Data/Sys/GameSettings/GWRE01.ini [Core]: Add CPUThread = False option.
=> GameSettings: Set CPUThread to False in GWRE01.ini.

Source/Core/Core/NetPlayServer.cpp
Proper local IPs are now shown instead of `127.0.0.1`.
=> NetPlay: Implement GetInterfaceListInternal for Windows.

Source/VSProps/Base.Dolphin.props
=> VSProps: Remove unused Steam preprocessor definition

Source/Core/DolphinQt/AboutDialog.cpp
This prevents the About Dialog window from being resized, which lead to this result:
It now cannot be maximized or otherwise resized:
=> AboutDialog: Disable resizing the About window

Source/Core/Core/HW/WiimoteReal/IOLinux.cpp
The "found a device..." NOTICE-level log was very spammy with "Continuous Scanning" enabled.
Also cleaned up some of the other related log messages.
=> Core/WiimoteReal: Make Wii Remote scan logging less spammy on Linux.

Source/Core/Core/HW/WiimoteEmu/Extension/Drums.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Drums.h
I did some tests by sending MIDI commands directly to a GHWT kit, and figured out that a lot of the "random" bits were actually just part of the velocity, and that there is actually a full 7 bits of velocity here, not just 3.
It turns out these kits actually just outright send MIDI data raw over the extension port, the MIDI velocity is just `0x7f - midi_velocity` and the MIDI note is just `0x7f - velocity_id`. The drums will even happily forward any MIDI note and velocity, not just the ones the pads are hardcoded with.
=> WiimoteEmu: Fix Drum Extension Velocity

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
`Motor L` would disable `Motor R` and vice versa, making a config like``` `Motor L` | `Motor R` ``` ultimately only activate `Motor R`.
This fixes that.
Also added support for trigger rumble motors (mainly for Xbox One controllers).
=> InputCommon: Make SDL Motor L/R Outputs not fight each other and support trigger rumble.

Source/Core/Core/PatchEngine.cpp
This was necessary before we added locking inside FilterApprovedPatches, but not anymore.
=> Core: Remove redundant lock for FilterApprovedPatches call

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.h, Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.h
Update 2023:
Add menu items to Memory Widget's mini-menu for auto updates.  I saw another PR saying the mini-menu is confusing, but we need some place for all these little options. New ideas welcome. Burger flyout menu?
I'm also not sure MemoryWidget needs to receive update calls, so I removed those to avoid any issues.
/Resurrect Bringing this back with @Dentomologist 's method.  Needs a bit more work.  The new guard stuff makes it easier to use.
Also came up with a stylesheet / dark mode compliant highlighting scheme for recently changed items.
=> MemoryView auto-update while running and color recently changed cells.

Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWindow.h, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuGeneral.cpp, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuGeneral.h
I've seen at least one user rightfully confused about where to go when the "..." button didn't do what they expected.
Clicking the "Configure Extension" button switches to the `Extension` tab.
The button is disabled when extension "None" is selected.
=> DolphinQt: Add a "Configure Extension" button under the extension selection combo box.

Source/Core/InputCommon/GCAdapter.cpp
This is an issue I noticed while working on #13288.
=> Fix segfault when passing invalid arguments

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
The computed value is only used when the register is equal to zero, so we can fully precompute it and materialize the constant instead. In other words, we change from
```
return reg == 0 ? (reg | 1ULL << 63) : reg;
```
to
```
return reg == 0 ? 1ULL << 63 : reg;
```
The number of instructions remains the same, but we eliminate an unnecessary dependency on the register value.
Before:
```
0xb241037a   orr    x26, x27, #0x8000000000000000
0xeb1f037f   cmp    x27, xzr
0x9a9a137b   csel   x27, x27, x26, ne
```
After:
```
0xd2f0001a   mov    x26, #-0x8000000000000000 ; =-9223372036854775808
0xeb1f037f   cmp    x27, xzr
0x9a9a137b   csel   x27, x27, x26, ne
```
=> JitArm64_SystemRegisters: Small FixGTBeforeSettingCRFieldBit optimization

Source/Core/Common/SmallVector.h
Elements are now constructed with placement-new.
=> Common: Make SmallVector work with non-standard-layout types.

Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/VideoCommon/VertexLoaderBase.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
Being able to set the vertex loader type without having to recompile Dolphin is useful on some platforms. This also makes it easier to use the native vs. software comparison loader, as Dolphin doesn't need to be rebuilt.
Not sure if this is worth upstreaming, but I figured that I could just PR it and see.
=> VertexLoaderBase: Allow the vertex loader type to be set via config

Source/Core/Core/HW/EXI/BBA/TAP_Win32.cpp
A refactor of an infinite loop found in the source files that did not match Dolphin's guidelines as per Contributing.md. This is a small first patch so that I can get comfortable with Dolphin's contribution workflow. If anything is amiss, let me know. Thanks.
=> Refactor: infinite loop based on Dolphin's style guidelines

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp, Source/Core/DolphinQt/Config/Mapping/IOWindow.h, Source/Core/InputCommon/ControlReference/ExpressionParser.cpp, Source/Core/InputCommon/ControlReference/ExpressionParser.h
`QSyntaxHighlighter` is a neat idea, allowing just altered "blocks" to be reformatted, but making this work properly requires the parser state be stored for each text block as a single int value, and rigging that up would just be a huge hassle.
Prior to this change only the altered block was re-formatted, hoping other blocks wouldn't need re-formatting, which really isn't a safe assumption.
It seems our expressions are often a single block or are edited left-to-right so a highlighting failure wasn't often seen but incorrect highlighting could be coerced by temporarily deleting delimiters mid-string and whatnot.
This change stops the use of `QSyntaxHighlighter` and just re-parses and re-formats the entire document on change.
Unicode characters are also now properly handled.
=> InputCommon/DolphinQt: Fix sometimes broken syntax highlighting in IOWindow.

Source/Core/InputCommon/ControlReference/ExpressionParser.cpp, Source/Core/InputCommon/ControlReference/ExpressionParser.h, Source/Core/InputCommon/ControlReference/FunctionExpression.cpp, Source/Core/InputCommon/ControlReference/FunctionExpression.h
Assignment-operator was always broken when interacting with comma-operator and other assignment-operators.
Before:
All of these should evaluate as 1.
After:
All the above now evaluate as 1 as they should.
LHS is evaluated before RHS (consistent for all binary operators).
Conditional operator produces an l-value.
Making `Expression::GetValue` non-const eliminated a bunch of ugly `mutable` usage.
=> InputCommon: Fix input expression assignment operator behavior.

Source/Core/InputCommon/ControlReference/ExpressionParser.cpp, Source/Core/InputCommon/ControlReference/FunctionExpression.cpp, Source/Core/InputCommon/ControlReference/FunctionExpression.h
Made function argument parsing error mention parenthesis instead of comma.
Made `FunctionExpression::ValidateArguments` look at previously set arguments instead of having to provide them.
Made `FunctionExpression::SetArguments` no longer call/return `ValidateArguments()` since it's not obvious that would happen from the name.
=> InputCommon/ExpressionParser: Function argument parsing minor cleanup.

Source/Core/DolphinQt/Settings.cpp
A number of settings in the `debugger` group were wrongly using a newly constructed `QSettings` object instead of the singleton object that `GetQSettings()` provides.
This made the application create a spurious, extra configuration file in the user directory:
```
~/.config/Dolphin Emulator/dolphin-emu.conf
```
Notice that,  by default, the application configuration files are stored in `~/.config/dolphin-emu`; not in `~/.config/Dolphin Emulator`.
=> DolphinQt: Use global settings object also for debugger settings.

CMakeLists.txt, Source/Core/AudioCommon/AudioCommon.cpp, Source/Core/AudioCommon/CMakeLists.txt, Source/Core/AudioCommon/CubebStream.h, Source/Core/Core/CMakeLists.txt, Source/Core/Core/HW/EXI/EXI_Device.cpp, Source/VSProps/Base.Dolphin.props
Cubeb doesn't support some platforms, so we should have the ability to disable it.
Outside of AudioCommon, `CEXIMic` uses Cubeb to get microphone input, so I added a panic alert when the Microphone device is selected and Cubeb is unavailable.
=> CMakeLists: Add flag to disable Cubeb

Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h, Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp, Source/Core/DolphinQt/TAS/WiiTASInputWindow.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/Attachments.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Attachments.h, Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h
Change the displayed controls in the TAS Input window when the controller's extension (including MotionPlus) is changed.
This previously required restarting Dolphin after the attachment was changed, as the controls were never updated after the WiiTASInputWindow was created at Dolphin startup.
=> WiiTASInputWindow: Update controls when attachment changes

Source/UnitTests/Common/StringUtilTest.cpp
The goal of this PR is to test Windows-specific behavior that is working as intended for `SplitPath`.
There are some behaviors of the current implementation that this PR does not test. For example:
* A Windows path like `"C:/dir/some_file.txt"` parses fine on non-Windows platforms, with the same output.
* An invalid path like `"C:/malformed_dir/:some_file.txt"` parses fine on Windows, with the output path being `"C:/malformed_dir/:"`.
I referenced this page to figure out what exactly qualifies as a valid Windows path: https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats.
=> Add a `SplitPath` unit test exercising Windows paths with drive letters

Data/Sys/GameSettings/SPQ.ini
Seems to resolve an issue with the menu as per the following conversation:
https://discord.com/channels/521709831132807179/521711075721478145/1333569568060342272
=> GameSettings: Set EFBAccessEnable=True for "I SPY: Spooky Mansion"

Data/Sys/GameSettings/RUFEMV.ini, Data/Sys/GameSettings/RUFP99.ini
Game communities have attempted to add gecko codes to the wiki for their specific game. These codes don't necessarily fall into the agreed 16:9 or FPS enhancement codes and are removed if noticed. The game communities still want these codes to be accessible to new players and some codes are hidden away on the internet (or worse, locked away in a discord).
The runey codes are regularly suggested as the only way to play the game.  I also added a code [from the community](https://www.reddit.com/r/runefactory/comments/14rpd5l/til_there_were_a_handful_of_items_in_frontier/) that was for some Japanese only items.
I have verified all the ntsc runey codes personally.
=> Data: update Rune Factory Frontier with community gecko codes

Source/Core/VideoCommon/PerformanceMetrics.cpp
Move ImGui::End() calls out of if(ImGui::Begin()) blocks.
ImGui::Begin's function comment in imgui.cpp says: `You always need to call ImGui::End() even if false is returned.`
In practice this didn't cause problems because the windows in question don't have title bars and thus can't be collapsed (which would cause Begin to return false), and so the block containing ::End would always run, but let's do it the proper way.
=> PerformanceMetrics: Call ImGui::End() unconditionally

Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
A minor thing that was bugging me.
=> WiimoteEmu: Use a named constant instead of a magic number for speaker data writes.

Flatpak/dolphin-emu-wrapper, Flatpak/org.DolphinEmu.dolphin-emu.yml
Writing a script into the repository root causes ScmRevGen to mark the build as `dirty`.
=> Flatpak: Move wrapper script outside of the manifest

Source/Core/Core/PowerPC/BreakPoints.cpp, Source/Core/Core/PowerPC/BreakPoints.h, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Should make loading tons of memory breakpoints instant.
I believe hammering DBATUpdated() is the main source of lag.  I also noticed some instability when a memory breakpoint is triggered while in the middle of loading multiple memory breakpoints, so I thread guarded the entire batch being loaded, which happens near instantly as DBATUpdated is only being hit once.
I assume removing multiple MBPs has the same issue, but can't test GDBStub, which does that. I included it in the fix.
=> Breakpoints: Fix lag when loading multiple memory breakpoints

Source/Core/VideoCommon/AsyncShaderCompiler.cpp
A simple refactor of an infinite loop in accordance with Dolphin's style guidelines. As of now, this appears to be the last one in the source. At least according to VSCode's file search functionality.
=> Refactor: Infinite loop in AsyncShaderCompiler according to style guidelines

Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.h
Before this change, if the core starts up or shuts down while a Branch Watch Tool context menu is open, menu actions would remain enabled or disabled in an outdated way.
=> Branch Watch Tool: Refresh Context Menus OnEmulationStateChanged

Source/Core/VideoCommon/PerformanceMetrics.cpp
Allow users to move the FPS, VPS, Speed, and Performance Graph overlays.
=> PerformanceMetrics: Allow users to move overlays

Source/Core/Core/IOS/USB/LibusbDevice.cpp, Source/Core/InputCommon/GCAdapter.cpp
I was working on updating GCAdapterDriver so it works for more devices, and noted that we would need to skip detaching the kernel driver in LibusbDevice too, much like we already do for GCAdapter.
https://github.com/secretkeysio/GCAdapterDriver/pull/27
I have already added all the PS3 and Wii controllers i can think of, and there is a test build of GCAdapterDriver on that pull request that has these devices included.
=> LibusbDevice: Don't detach kernel drivers on macOS

Source/Core/VideoBackends/D3D/D3DBase.h, Source/Core/VideoBackends/D3D/D3DGfx.h, Source/Core/VideoBackends/D3D/D3DSwapChain.h, Source/Core/VideoBackends/D3D/D3DVertexManager.cpp, Source/Core/VideoBackends/D3D/DXPipeline.h, Source/Core/VideoBackends/D3D/DXTexture.h, Source/Core/VideoBackends/D3D12/D3D12Gfx.h, Source/Core/VideoBackends/D3D12/D3D12SwapChain.h, Source/Core/VideoBackends/D3D12/D3D12VertexManager.h, Source/Core/VideoBackends/D3D12/DX12Context.cpp, Source/Core/VideoBackends/D3D12/DX12Shader.h, Source/Core/VideoBackends/D3D12/DX12Texture.h, Source/Core/VideoBackends/D3D12/DescriptorAllocator.h, Source/Core/VideoBackends/D3D12/DescriptorHeapManager.h, Source/Core/VideoBackends/D3D12/VideoBackend.h, Source/Core/VideoBackends/D3DCommon/D3DCommon.cpp
This allows D3D11 and D3D12 to use DXGI 1.6 and D3D11 to use its latest version (11.4)
=> VideoBackends: Use DXGI 1.6 and D3D11_4

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h
The main optimizations here take advantage of ARM64's `ADD`/`SUB` instructions which can encode a (shifted) 12-bit immediate value, allowing us to skip materializing the immediate in a register. This either means we save an instruction, we end up with an equal amount of instructions if it needs to be materialized for a subsequence use. I didn't implement the (shifted) 12-bit additions for `cmpl`, as I was unable to find games where this occurred.
The second optimization consists of skipping the sign extension step in `cmp` if possible.
Finally, I fixed a const correctness issue I accidentally introduced in #13120.
---
<details><summary>cmp - Subtract 12-bit constant</summary>
Before:
```
0x52800416   mov    w22, #0x20                ; =32
0x93407f78   sxtw   x24, w27
0xcb36c318   sub …
```
=> JitArm64_Integer: cmp/cmpl optimizations

Source/Android/app/src/main/res/values/strings.xml, Source/Core/Common/FatFsUtil.h, Source/Core/Core/Core.cpp, Source/Core/DolphinQt/Settings/WiiPane.cpp
Before:
After:
I think the old names were too similar and clicking the wrong one could be unfortunate.
A user on discord just clicked the wrong one.
Files are on both ends of the conversion so it might not be immediately obvious that "File" is the raw SD Card file.
"Pack" and "Unpack" make it more clear what is going on.
=> DolphinQt: Rename the pack/unpack SD Card buttons.

Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWindow.h, Source/Core/InputCommon/ControllerInterface/CoreDevice.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.h, Source/Core/InputCommon/ControllerInterface/MappingCommon.cpp, Source/Core/InputCommon/ControllerInterface/MappingCommon.h
This feature was removed in #9685 because the delay it introduces during button mappings is annoying.
The default behavior is unchanged.
By enabling this new setting, auto generation of `|` mappings using sequential button presses is again possible.
Pressing X followed by Z with the setting enabled:
[Screencast_20250201_001656.webm](https://github.com/user-attachments/assets/f335a8d8-a876-404a-aac1-7198a3d41ce8)
Users occasionally ask how to map two buttons without having to press them at the same time.
Telling them to enable this setting is easier than explaining how to use the advanced mapping window.
I also did some other minor code cleanups.
=> DolphinQt/Mapping: Add setting to enable waiting for alternate mappings.

Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt/Config/Mapping/MappingButton.h, Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWidget.h, Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWindow.h
~~This is based-on/depends-on PR #13320. (merge that first and I'll rebase this)~~
When the setting is enabled, if the current mapping is successful then the next mapping button is activated and waits for mapping.
Now that mapping is non-blocking, this feature is less terrible than it used to be when it was removed in #8031.
Clicking the active mapping button stops the process.
Queuing specific buttons takes precedence over iterative mapping queuing the next button.
=> DolphinQt: Add setting to enable iterative input mappings.

Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
Before:
After:
Light themes are unaffected.
=> DolphinQt/Mapping: Adjust dark theme indicator gate color calculation.

Source/Core/Core/PatchEngine.cpp
Checks if msr.DR and msr.IR are valid when patch engine calls ApplyStartupPatches. Solves the issue [here](https://bugs.dolphin-emu.org/issues/13674).
From the conversation with @AdmiralCurtiss at #13312.
=> Core: Check if msr.DR and msr.IR are valid at ApplyStartupPatches

Source/Core/Core/CMakeLists.txt, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/HW/CPU.cpp, Source/Core/Core/HW/CPU.h, Source/Core/Core/TimePlayed.cpp, Source/Core/Core/TimePlayed.h, Source/Core/DolphinLib.props, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/GameList/GameListModel.h, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.h
This adds a total "Time Played" tab in the QT interface - the time is started at the beginning of emulation and ended when emulation shuts down. A general TimePlayed class is implemented which the desktop QT interface pulls from. This does not require a standard exit of emulation to count the time. 
Edit (January 2025): A toggle has been added to allow the user to disable time tracking if desired.
=> Track Time Played (Core and QT)

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/UserDataImportWarningDialog.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/TaskViewModel.kt
Instead of having UserDataImportWarningDialog set an `onResultDismiss` callback that examines `mustRestartApp`, and having UserDataActivity set `mustRestartApp`, just have UserDataActivity set the callback directly.
This approach is no more data-race-y than the previous approach, and it simplifies the code. (The behavior of restarting the app when the task finishes is specific to the user data import flow, and there is no reason for TaskViewModel to be directly aware of it.)
I tested this PR by running the app in an Android emulator and importing user data, and verifying that the app restarts the same way it did before.
=> Eliminate TaskViewModel's `mustRestartApp` field

Data/Sys/GameSettings/LULZHB.ini
LULZ is forced to 4:3 because of the default for L being Sega Master System Virtual Console games. This commit fixes that.
=> Fix LULZ (Homebrew Channel) being forced to 4:3

Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/DolphinAnalytics.h, Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Extension.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Extension.h, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp, Source/Core/Core/Movie.cpp, Source/Core/Core/Movie.h
DTM file Wii Remote data now uses `SerializedWiimoteState` (the format that NetPlay uses).
All extensions can be recorded and played back.
Swapping extensions mid-movie works.
Movie code no longer clumsily handles extension encryption.
Data in the DTM file is no longer based on the current reporting mode and can more easily be manually edited.
Removed analytics `GameQuirk::DIRECTLY_READS_WIIMOTE_INPUT` as it's no longer relevant.
This (probably never seen) behavior should now be properly handled and deterministic in TAS.
=> Core/Movie: Make DTM Wii Remote data use SerializedWiimoteState.

Source/Core/Core/HW/SI/SI.cpp, Source/Core/Core/HW/SI/SI_DeviceGCController.cpp, Source/Core/Core/HW/SI/SI_DeviceNull.cpp
Inspired by #8282
I've not included the change for selective polling based on EN0,1,2,3 values, though that also looks interesting.
Fixes https://bugs.dolphin-emu.org/issues/11323
Mario Kart Wii now properly displays a message on gamepad unplug.
Eternal Darkness no longer freezes on gamepad unplug.
=> SI: Set NOREP, ERRSTAT, and ERRLATCH when GetData returns false.

Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp
Fixes a regression that I introduced in #13323.
=> DolphinQt: Fix MappingButton not updating text on middle-click clear.

Source/Core/DolphinQt/CMakeLists.txt
This removes a lot of deprecation warning noise from the build when compiling with Qt newer than the one in Externals (6.5.1).
=> CMake: disable Qt deprecation warnings we can't fix

Data/Sys/GameSettings/GMF.ini
Fixes flashing screen in case its enabled globally.
=> GameSettings: Set ImmediateXFBEnable = False for Medal of Honor: Frontline

Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/VideoCommon/PerformanceMetrics.cpp
Clamp overlays to the render window with some padding, reset their positions when the render window changes sizes, and add an .ini-only setting (for now) to allow moving the overlays which is off by default.
=> PerformanceMetrics: Add clamping, resetting on resize, and setting

Source/Core/VideoCommon/VertexShaderGen.cpp
This was requested by @Tilka .
I normally prefer anonymous namespaces but given I still have a lot of changes to make to these files, I figured taking a lighter approach would be less disruptive to my other PRs.
=> VideoCommon: mark 'WriteTexCoordTransforms' as 'static'

Data/Sys/Load/GraphicMods/Dragon Ball Z Budokai Tenkaichi 3/metadata.json
=> GraphicMods: Fix typo in DBZ Budokai Tenkaichi 3/metadata.json

BuildMacOSUniversalBinary.py, CMake/FindFFmpeg.cmake, CMakeLists.txt
Also includes a fix for BuildMacOSUniversalBinary.py
=> CMake: fix various typos

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/BootManager.cpp, Source/Core/Core/BootManager.h, Source/Core/Core/Config/UISettings.h, Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h, Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp
Found via `codespell -q 3 -S "./Externals,./Data/Sys/wiitdb-??.txt,*.po,*.pot" -L andf,asnd,bootup,bufferin,clen,collet,datas,delt,fpr,inout,inport,interm,pixelx,re-use,re-used,sav,stateman,strat,wil`
=> Core/Core: fix typos

Data/Sys/GameSettings/GL8.ini
Tomb Raider: Legend has a graphical bug, as documented in the issue report [here.](https://bugs.dolphin-emu.org/issues/13749?next_issue_id=13748)
This .ini entry fixes the issue.
UNRESOLVED
RESOLVED
=> Fix graphical corruption bug in Tomb Raider: Legend

Data/Sys/GameSettings/GL8.ini
… Legend
As the PS2 version is the only one with proper 16:9 widescreen, this cheat has been tested on the NTSC version, but is labeled as region free, to bring 16:9 widescreen.
BEFORE
AFTER
=> Added widescreen code for Tomb Raider: Legend GL8.ini

Data/dolphin-emu.desktop, Flatpak/org.DolphinEmu.dolphin-emu.yml, Source/Core/DolphinQt/Main.cpp
This moves the declaration of `env QT_QPA_PLATFORM=xcb` from the desktop file/flatpak args to DolphinQt's `Main.cpp`.
This is particularly useful for users attempting to launch dolphin from the command line by launching the `dolphin-emu` executable.
=> Enforce XCB within code

Source/Core/Core/State.cpp
Show the "Decompressing State..." message for 2 seconds, instead of the half-second duration that caused it to be halfway faded out immediately.
=> State: Show "Decompressing State..." OnScreenDisplay message for longer

Source/Core/Core/Core.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp, Source/Core/VideoCommon/VideoBackendBase.h
This eliminates an unnecessary function. Emu start/stop is hard enough to follow as it is.
=> Core/VideoBackendBase: Call ExitGpuLoop from Core to eliminate Video_ExitLoop.

Data/Sys/GameSettings/F.ini, Data/Sys/GameSettings/FAAE01.ini, Data/Sys/GameSettings/FAGE01.ini, Data/Sys/GameSettings/GP6E01.ini, Data/Sys/GameSettings/GP7E01.ini, Data/Sys/GameSettings/GZ2E01.ini, Data/Sys/GameSettings/PZLE01.ini, Data/Sys/GameSettings/RLI.ini, Data/Sys/GameSettings/RM8E01.ini, Data/Sys/Shaders/PerceptualHDR.glsl, Data/Sys/Shaders/asciiart.glsl, Data/Sys/Shaders/default_pre_post_process.glsl, Data/Sys/Shaders/nightvision2.glsl, Data/Sys/Shaders/nightvision2scanlines.glsl
Found via `codespell -q 3 -S "./Externals,./Data/Sys/wiitdb-??.txt,*.po,*.pot" -L andf,asnd,bootup,brocken,bufferin,clen,collet,datas,delt,diety,extint,fpr,inout,inport,interm,nd,nin,ontop,pixelx,re-use,re-used,sav,stateman,strat,transer,wil`
=> Data: fix various typos

Source/Core/VideoBackends/Null/NullGfx.h, Source/Core/VideoBackends/Software/SWRenderer.h, Source/Core/VideoCommon/AsyncRequests.cpp, Source/Core/VideoCommon/AsyncRequests.h, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/RenderBase.h
This was unnecessary since #7753.
`Renderer::PokeEFB` was just iterating `AsyncRequests`'s merged pokes and individually sending them to `FramebufferManager` which then handled the batching all over again.
Also `PullEventsInternal` isn't used in "single core" mode so the unnecessary merging didn't even happen there.
=> VideoCommon: Don't merge EFBPoke AsyncRequests.

Source/Core/Core/Movie.cpp, Source/Core/Core/Movie.h, Source/Core/VideoCommon/VideoConfig.cpp
More VideoConfig cleanups.
`MovieManager::SetGraphicsConfig` isn't needed. This stuff is already handled by `MovieConfigLayerLoader`:
https://github.com/dolphin-emu/dolphin/blob/5ed8b7bc9d8f70d5dae4f009939ac9715adf83b4/Source/Core/Core/ConfigLoaders/MovieConfigLoader.cpp#L46
=> Movie: Eliminate MovieManager::SetGraphicsConfig.

Source/Core/Core/HW/VideoInterface.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
This value was only used by `VideoInterfaceManager::OutputField` (CPU Thread). It doesn't need to exist in `VideoConfig`.
=> VideoConfig: Eliminate bForceProgressive.

Source/Core/Core/State.cpp, Source/Core/VideoCommon/VertexShaderManager.cpp, Source/Core/VideoCommon/VertexShaderManager.h
The value of `m_viewport_correction` never changed from `Common::Matrix44::Identity()`.
It must be a remnant from long ago.
=> VertexShaderManager: Eliminate unnecessary m_viewport_correction member.

Source/Core/Core/HW/VideoInterface.cpp
This fixes a frame pacing problem in many games that becomes apparent with the improvements of #13387 
Super Mario Sunshine:
```
(VI->BeginField): Address: 004C8D80 | WPL 40 | STD 80 | EQ 6 | PRB 40 | ACV 224 | PSB 19 | Field Odd
HorizScaling: 0100 | fbwidth 640 | 8108100 | 8108100
(VI->BeginField): Address: 004C8D80 | WPL 40 | STD 80 | EQ 6 | PRB 41 | ACV 224 | PSB 18 | Field Even
HorizScaling: 0100 | fbwidth 640 | 8108100 | 8108100
```
Odd/Even PRB/PSB values differ and we present *before* PSB causing bad pacing between odd/even fields.
Before:
After:
Just a side note: these values are state-saved so comparisons cannot be done if you are loading a state. :)
Also, you really won't be able to observe a difference without #13387
=> VideoInterface: Adjust even-field to match odd-field pacing when PSB values differ.

Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
I think this was an unusual recommendation. V-Sync will probably hurt frame-pacing.
=> DolphinQt: Don't recommend v-sync for optimal frame pacing in tool-tip.

Source/Core/VideoBackends/Software/Tev.cpp, Source/Core/VideoBackends/Software/Tev.h, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/UberShaderPixel.cpp
This fixes [issue 13734](https://bugs.dolphin-emu.org/issues/13734): "Z-textures are incorrectly affected by swaptable". This was reported by @fadedled, who presumably noticed this while working on [Seta GX](https://github.com/fadedled/seta-gx).
I've not hardware-tested this myself beyond running the repro case using the [hardware fifoplayer](https://github.com/dolphin-emu/fifoplayer).
=> Fix depth texture being incorrectly affected by swap table

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/HW/WiimoteReal/IOLinux.cpp, Source/Core/Core/HW/WiimoteReal/IOLinux.h
This adds the option to configure real Wiimotes by specifying their Bluetooth addresses in the configuration file.  This allows off-brand Wiimotes to work without using the Bluetooth Passthrough option, if you know their Bluetooth addresses beforehand.
Despite correctly setting the LAP to `0x9e8b00` _(Limited Inquiry Access Code (LIAC))_ in `WiimoteScannerLinux::FindWiimotes` while scanning, which is indeed enough to make off-brand / knock-off Wiimotes respond to a Bluetooth Inquiry, some (several? all?) bluetooth adapters seem to override and ignore this given LAP value when performing the Inquiry, and actually use the `0x9e8b33` value _(General Inquiry Access Code (GIAC))_ as if a null pointer have been given to `hci_inquiry`, as inspection of USB/Bluetooth packets by Wireshark …
=> feat(linux): allow configuring real wiimotes with known bluetooth addresses

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Comparing with an immediate 0 has the same effect but is much easier to read.
=> JitArm64: Replace a comparison to SP

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/AndroidCommon/IDCache.h, Source/Android/jni/MainAndroid.cpp, Source/Core/Common/Logging/LogManager.cpp, Source/Core/Common/Logging/LogManager.h
Storing the log type names in a map results in them getting re-sorted by their keys, which doesn't quite give us the sorting we want. In particular, the Achievements category ended up being sorted at R (for RetroAchivements) instead of at A. Every use of the map is just iterating through it, so there's no real reason why it has to be a map anyway.
=> Android: Replace log type names map with array

Source/Core/VideoCommon/OnScreenUI.cpp
This undoes one of the changes of PR #13181. I'm guessing the relevant code changed between when the PR was last pushed to and when it was merged.
=> Fix broken merge of PR #13181

Source/Core/Common/VariantUtil.h, Source/Core/Core/HW/WiimoteEmu/DesiredWiimoteState.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Classic.h, Source/Core/Core/HW/WiimoteEmu/Extension/DesiredExtensionState.h, Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.h, Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.h, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h, Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.h, Source/Core/Core/HW/WiimoteEmu/Extension/Turntable.h, Source/Core/Core/HW/WiimoteEmu/Extension/UDrawTablet.h
The old code relied on variant alternative indices matching ExtensionNumber values.
That wasn't inherently an issue, but there was a lot of boilerplate to handle that and ensure that it was maintained.
High-level behavior remains unchanged.
DTM format is unchanged.
=> WiimoteEmu: Clean up variant handling in DesiredExtensionState.

Source/Core/Core/HW/VideoInterface.cpp
`GetTicks()` is often a few cycles further than the `ticks` argument which already has `cycles_late` applied to give us the event's original `ticks`.
It looks like this value is only used for reading `VI_HORIZONTAL_BEAM_POSITION`.
I don't expect this to really affect much but maybe someone else can confirm if this is a sensible change.
=> VideoInterface: Update m_ticks_last_line_start from the event's ticks value.

Source/Core/Core/HW/ProcessorInterface.cpp, Source/Core/Core/PowerPC/MMU.cpp, Source/Core/VideoCommon/AsyncRequests.cpp, Source/Core/VideoCommon/AsyncRequests.h, Source/Core/VideoCommon/VideoBackendBase.cpp, Source/Core/VideoCommon/VideoBackendBase.h
This eliminates the union and switch-statement event handler in `AsyncRequests`.
Now any function can be pushed to the GPU thread rather than the fixed set of event types that were kept in a union.
This PR is a precursor to a proper version of #13421.
Video backend init needed to happen on the GPU thread and that should be easy with these changes 
I think I should also then be able to easily eliminate all the mutex locks in `AsyncRequets`.
=> AsyncRequests Cleanups.

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Assembler/GekkoLexer.cpp, Source/Core/Common/CompatPatches.cpp, Source/Core/Common/GL/GLExtensions/GLExtensions.cpp, Source/Core/Common/Intrinsics.h, Source/Core/Common/Matrix.h, Source/Core/Common/TraversalProto.h, Source/Core/Common/WindowSystemInfo.h, Source/Core/Common/x64ABI.h
Found via `codespell -q 3 -S "./Externals,./Data/Sys/wiitdb-??.txt,*.po,*.pot" -L andf,asnd,bootup,brocken,bufferin,clen,collet,datas,delt,diety,extint,fpr,inout,inport,interm,nd,nin,ontop,pixelx,re-use,re-used,sav,stateman,strat,transer,wil`
=> Core/Common: Fix typos

Source/Core/VideoCommon/FrameDumpFFMpeg.cpp, Source/Core/VideoCommon/FrameDumper.cpp, Source/Core/VideoCommon/Present.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
These don't need to be in `VideoConfig`.
=> VideoConfig: Eliminate frame dumping members.

Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
This assignment was not needed.
It already appropriately happens here: https://github.com/dolphin-emu/dolphin/blob/5ed8b7bc9d8f70d5dae4f009939ac9715adf83b4/Source/Core/VideoCommon/VideoConfig.cpp#L80
=> DolphinQt/GeneralWidget: Eliminate unnecessary g_Config usage.

Source/Core/VideoCommon/UberShaderPixel.cpp
Users were reporting a shader value may not be fully initialized.  This was a missing change from https://github.com/dolphin-emu/dolphin/pull/13345.  I really hate that requirement.
Anyway, this fixes that error by initializing `RawTexColor`
=> VideoCommon: initialize uninitialized state value in pixel ubershader

Contributing.md
Fixes the following error in the clang-format command for all staged files:
```
git diff --cached --name-only | egrep '[.](cpp|h|mm)$' | xargs clang-format -i
egrep: warning: egrep is obsolescent; using grep -E
error: cannot use -i when reading from stdin.
```
=> Contributing.md: Replace egrep with grep -E in clang-format command.

Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.h, Source/Core/Core/Movie.cpp
TaTaCon NetPlay and TAS users rejoice.
The TaTaCon native data format has 5 bytes of padding. Now just the relevant byte is stored.
This change provides a a total savings of of 5 bytes per input frame!
=> WiimoteEmu: Make TaTaCon DesiredState use only one byte of space.

Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h, Source/Core/VideoCommon/PerformanceMetrics.cpp, Source/Core/VideoCommon/PerformanceMetrics.h
`GetCPUTimePoint` was implemented assuming a constant `GetTicksPerSecond` but this isn't always the case.
The returned nanoseconds would jump in time when ticks-per-second changed, such as when booting a GC game from the Wii menu.
"Max Speed" values would be wildly wrong until the sample window left this transition period.
While this is a weird edge-case, I think calculating time from cycles-delta rather than cycles-since-boot is less problematic and not any more complicated.
I've also eliminated a mutex in `PerformanceMetrics` by writing an `atomic<double> m_max_speed` in the Core thread rather than relying on locking around the sample data.
=> PerformanceMetrics: Eliminated a mutex. Code cleanups.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/controlleremu/EmulatedController.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/AndroidCommon/IDCache.h, Source/Android/jni/Input/EmulatedController.cpp, Source/Core/Core/HW/GCPadEmu.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Classic.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Drums.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Extension.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Extension.h, Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h, Source/Core/Core/HW/WiimoteEmu/Extension/Shinkansen.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Turntable.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/DolphinQt/TAS/TASInputWindow.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Attachments.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Attachments.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h, Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp, Source/Core/InputCommon/ControllerEmu/ControllerEmu.h, Source/Core/InputCommon/ControllerEmu/StickGate.cpp, Source/Core/InputCommon/ControllerEmu/StickGate.h
The Wii Remote `Extension` classes previously derived from `ControllerEmu` giving them redundant/unused "default device" and "expression variables" members.
Common functionality has been moved to a `ControlGroupContainer` class.
This eliminated the redundant members and some unnecessary function arguments.
`Attachments` config save/loading is now appropriately handled in an overridden virtual function instead of using ` if (type == GroupType::Attachments)`.
`MapFloat` and `MapToFloat` static member functions changed into more-appropriate free-functions.
I'm mainly just moving code around here. Behaviors should be entirely unchanged.
=> InputCommon/ControllerEmu: Break out functionality of EmulatedController to eliminate redundant members.

Source/Android/jni/Input/EmulatedController.cpp, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/Core.cpp, Source/Core/Core/HW/GCKeyboard.cpp, Source/Core/Core/HW/GCKeyboard.h, Source/Core/Core/HW/GCPad.cpp, Source/Core/Core/HW/GCPad.h, Source/Core/Core/HW/Wiimote.cpp, Source/Core/Core/HW/Wiimote.h, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/IOS/MIOS.cpp, Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/InputCommon/DynamicInputTextureManager.cpp, Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.cpp, Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.h, Source/Core/InputCommon/InputConfig.cpp, Source/Core/InputCommon/InputConfig.h
While working on an optimized system for asset loading, I wanted to make sure Dynamic Input Textures (DIT) still worked.  While doing so, I found that images were being written to disk six times for one actual change.  This PR reduces the image write down to the expected one time.
The reason for the six times was that the generate texture logic was being called on `LoadConfig()` and `SaveConfig()`.  I recall struggling on where to put the generation code previously that would hit every scenario (profile loading, game loading, and the various options in the input mapping window).  When the input mapping is ran, multiple loads/configs are called, which causes excessive generation.  I've removed the logic from those two functions and instead called them in each location.
=> Core / DolphinQt / InputCommon: reduce the number disk writes when using DynamicInputTextures

Source/Core/Common/Config/Config.h, Source/Core/Common/Config/Layer.h, Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.h, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/VideoBackends/D3D/D3DState.cpp, Source/Core/VideoBackends/D3D12/DescriptorHeapManager.cpp, Source/Core/VideoBackends/Metal/MTLObjectCache.mm, Source/Core/VideoBackends/OGL/SamplerCache.cpp, Source/Core/VideoBackends/Vulkan/ObjectCache.cpp, Source/Core/VideoCommon/RenderState.cpp, Source/Core/VideoCommon/RenderState.h, Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
Based on #9975.
I've done the UI and config changes to hopefully get Pokechu22's nice improvements merged.
I've also mirrored the changes in the Metal backend.
Users with the old "Default" saved will now see "1x Anisotropic" in the UI which maintains the same graphical behavior. ("Default" previously forced 1xAF)
This is `[Enhancements] MaxAnisotropy = 0` in the ini file.
When the new "Default" (-1) is saved, the `MaxAnisotropy` key is deleted from the from the ini file so old versions of Dolphin don't blow up with a `-1`. The `-1` value isn't saved, just default-loaded.
=> Use Game Requested Anisotropic Filtering

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/HW/EXI/EXI.cpp, Source/Core/Core/HW/EXI/EXI.h, Source/Core/Core/HW/EXI/EXI_DeviceAD16.cpp, Source/Core/Core/HW/EXI/EXI_DeviceAD16.h, Source/Core/Core/State.cpp, Source/Core/DolphinQt/Settings/GameCubePane.cpp, Source/Core/DolphinQt/Settings/GameCubePane.h
This fixes AD16, some kind of boot progress indicator device. With this fix, the GameCube IPL triggers another issue in Dolphin (see joint [issue 12438](https://bugs.dolphin-emu.org/issues/12438)), so I've disabled AD16 by default and left it out of the GUI. You can enable it by starting Dolphin with `-C Dolphin.Core.SerialPort2=3` on the command line.
=> Fix AD16 and make SP2 configurable

Source/Core/Core/Core.cpp
Prior to this, when `Skip Presenting Duplicate Frames` was turned off, `PerformanceMetrics` would still "skip" duplicate XFBs.
Now, when `Skip Presenting Duplicate Frames` is turned off, performance statistics show the full frame rate.
The default state with `Skip Presenting Duplicate Frames` turned on is unchanged.
In this new state, Luigi's Mansion (a "30fps" game) no longer appears to have terrible frame pacing.
I think it was just a symptom of the duplicate XFB logic not being an absolutely perfect way to detect a duplicate frame.
I'll mention that frame stepping still has the same old logic. "Duplicate" XFBs are skipped even if `Skip Presenting Duplicate Frames` is turned off. Is that really desirable? I would think it should stop on any presented field?
=> Fix performance statistics when Skip Duplicate Frames is turned off.

Data/Sys/GameSettings/SDAE5G.ini
This fixes [issue 10821](https://bugs.dolphin-emu.org/issues/10821) by patching the race condition in the game. An alternative fix would be to delay the AID interrupt a little longer, but that would slow down emulation of well-behaved games.
Thanks to @hthh for debugging this!
=> GameSettings: fix startup crash in "The Daring Game for Girls"

Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Original:
The left side is given more space and everything is aligned better:
=> Debugger CodeWidget: Small layout tweak

Installer/Installer.nsi, Readme.md, Source/Core/Common/Timer.cpp, Source/Core/Common/build_info.txt.in, Source/Core/Core/Config/DefaultLocale.cpp
With #13426 possibly needing a newer version of Windows 10 and a long-standing graphics mod crash (see https://bugs.dolphin-emu.org/issues/13352 ... which could easily be addressed to be fair), I wondered if we could try doing this #11452 once more.
This updates our minimum version of Windows 10 to 1903.  With Windows 10 going to end of life toward the end of 2025, this seems like a reasonable step toward supporting a more modern version of Windows.
This reverts #10963 and adds the changes from #11452 .
Discuss!
=> Update our minimum windows 10 version to 1903 and reinstate code that depends on it

Source/Core/DolphinQt/Config/CheatCodeEditor.cpp
Gecko codes in Dolphin feature a dedicated field for the creator of the cheat code. When saved into the INI file, the code name and the creator name are concatenated, and then inserted in the `[Gecko]` section:
```ini
[Gecko]
$<cheat code name> [<creator>]
<code line 1>
<code line 2>
<code line 3>
<...>
$<other cheat code name> [<creator>]
<code line 1>
<code line 2>
<code line 3>
<...>
```
On the other hand, enabled codes are listed under the `[Gecko_Enabled]` section, but in this case the creator name is omitted from the line:
```ini
[Gecko_Enabled]
$<cheat code name>
$<other cheat code name>
```
Having the creator name in the `[Gecko]` section but not in the `[Gecko_Enabled]` section is arguably not ideal, but this is legacy behavior in Dolphin.
The **Cheat Code Editor** dialog is not …
=> DolphinQt: Extract creator name from code name in Gecko codes.

Source/Core/Core/HW/CPU.cpp
It was annoying seeing two threads called "CPU thread" in my debugger.
=> Core: Name the play time tracker thread.

Source/Core/Core/PowerPC/PPCSymbolDB.cpp, Source/Core/VideoBackends/Software/SWEfbInterface.cpp, Source/Core/VideoCommon/PerformanceMetrics.cpp
This fixes a few warnings I see pop up on fresh builds.
Namely:
- PPCSymbolDB & PerformanceMetrics:  Resolve shadowed variable warnings(` [-Wshadow]`)
- SWEfbInterface: Add missing static for declarations (`[-Wmissing-declarations]`)
=> Fix shadowed variable warnings and missing declarations

Source/Core/AudioCommon/Enums.h, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigChoice.h, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/AudioPane.cpp, Source/Core/DolphinQt/Settings/AudioPane.h
Updated the image to the current version.
Placing everything under the config system will make things easier to use and re-arrange long term, especially if someone wants to change up the UI.  Also, it will allow Local game-ini options to be bolded and possibly set directly.
``AudioCommon::UpdateSoundStream(Core::System::GetInstance())`` I assumed this didn't need to be called for things that can only be changed before running a game.  If an audio update is actually required for such things, I would trigger it on OnEmulationStateChanged.
=> AudioPanel: Refactor to use Config system.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/InputDetector.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/MappingCommon.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/MotionAlertDialog.kt, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/AndroidCommon/IDCache.h, Source/Android/jni/CMakeLists.txt, Source/Android/jni/Input/InputDetector.cpp, Source/Android/jni/Input/MappingCommon.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.h
This is an Android continuation of PR #13162. We now call InputDetector::Update immediately after receiving an input event from Android instead of periodically calling it in a sleep loop. This improves detection of very short inputs, which are especially likely to occur for volume buttons on phones (or at least on my phone) if you don't intentionally keep them held down.
=> Android: Don't use separate thread for MotionAlertDialog

Source/Core/Core/PowerPC/MMU.cpp, Source/Core/VideoBackends/Null/NullGfx.cpp, Source/Core/VideoBackends/Null/NullGfx.h, Source/Core/VideoBackends/Software/SWEfbInterface.cpp, Source/Core/VideoBackends/Software/SWEfbInterface.h, Source/Core/VideoCommon/EFBInterface.cpp, Source/Core/VideoCommon/EFBInterface.h
This fixes my regression from #13423 
Thanks to @iwubcode for discovering it
I accidentally removed this check, making EFB Access always enabled and out-of-bounds access trigger an assert, breaking DQX and maybe more.
https://github.com/dolphin-emu/dolphin/blob/ca9b34a6d1e7ad03c4879239e9c5b79a6c47522e/Source/Core/VideoCommon/VideoBackendBase.cpp#L116
I've re-added this check and moved the AsyncRequest usage from MMU into EFBInterface which is closer to how things were organized before.
=> VideoCommon: Fix out-of-bounds and disabled EFB access.

Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp
I caused this in #13162 
@Dentomologist brought this to my attention.
It was maybe only a problem on Windows? I don't see it in Linux.
Broken:
Fixed:
=> DolphinQt: Fix blank square in MappingWindow's top-left corner.

Source/Core/Core/IOS/FS/FileSystemCommon.cpp, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DolphinTool/ExtractCommand.cpp, Source/Core/UICommon/GameFile.cpp, Source/Core/VideoCommon/TextureInfo.cpp, Source/Core/VideoCommon/VertexLoaderX64.cpp
Using the [`-Wnrvo`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wnrvo) flag introduced by GCC 14, I identified a few places where NRVO was clearly intended, but is fumbled.
=> GCC: Remedy NRVO Fails

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp, Source/Core/DolphinQt/Debugger/CodeWidget.h, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.h, Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.h
Makes it possible to jump directly to address search box for code view and memory view by pressing CTRL+G. Similar to many debuggers/disassemblers/IDEs.
=> [Debugger] CTRL+G support in code and memory view

Source/Core/VideoBackends/Metal/MTLObjectCache.h, Source/Core/VideoBackends/Metal/MTLObjectCache.mm
This is an attempt to fix my regression of #13368 
Ideally `SamplerSelector` wouldn't be so fragile with all those magic numbers, but it is what it is.
=> VideoBackends/Metal: Fix anisotropic filtering handling.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/app/src/main/res/values/strings.xml, Source/Core/AudioCommon/Mixer.cpp, Source/Core/AudioCommon/Mixer.h, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/DolphinQt/Settings/AudioPane.cpp
- Replace a lot of the granule copying either reusing buffers or writing directly into granules when updating.
- All Jumping and Looping is handled on one thread, allowing the other thread to handle just pushing audio. This removes a possibility of an extremely rare race condition, and allows extremely small buffer sizes to play back more smoothly. 
- Previous change makes it significantly more likely to play nicely with VBI Skip.
- Adds Audio Buffer Size option to allow users to choose between latency and smoothness
This also potentially helps very low end android devices.
=> AudioCommon: Increased Granule Synthesis Performance

Source/Core/VideoCommon/VertexManagerBase.cpp
Attempts to fix regression caused by #12535 that impacts mali Android devices.
=> VideoCommon: fix a mali draw bug that causes crashes in some games

Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h
Sorry, this should fix the crash that I introduced in #13426.
=> CoreTiming: Fix Precision Frame Timing in Dual Core mode on Windows.

Data/Sys/GameSettings/RMH.ini
Bug: MH Tri has super bloom issues.
https://bugs.dolphin-emu.org/issues/13689
Relevant PR: Changes global default for EFBAccessEnable
https://github.com/dolphin-emu/dolphin/pull/13140
Set EFBAccessEnable = True to return it to normal behavior.
=> Game setting fix: Monster Hunter Tri bloom

Source/Core/Core/CoreTiming.cpp, Source/Core/Core/HW/SystemTimers.cpp, Source/Core/Core/HW/SystemTimers.h, Source/Core/Core/HW/VideoInterface.cpp, Source/Core/VideoCommon/PerformanceMetrics.cpp, Source/Core/VideoCommon/PerformanceMetrics.h
This is a followup to #13387 and #13397.
I've eliminated the 100hz `PerfTrackerCallback` in `SystemTimers`.
It was only needed for `CountPerformanceMarker` which is now called from `VideoInterface`.
The ~60hz `Throttle` call in `VideoInterfaceManager::EndField` is now also skipped if "VBlank" data isn't asked for.
This might marginally reduce stuttering and improve pacing.
This should reduce the CPU-spinning of `PrecisionTimer` in #13426 from around 28% to maybe more like 12%.
`PerformanceMetrics` is now informed of clock speed changes to adjust previous samples to keep speed/max_speed values accurate during the transition period.
This is the same logic that's applied to the `Event::time` values in `CoreTiming::AdjustEventQueueTimes`.
`PerformanceMetrics` now uses the configured …
=> Core: Move CountPerformanceMarker to VideoInterface to eliminate a Throttle call. PerformanceMetrics: Fixes/Cleanups.

Source/Core/VideoCommon/BPStructs.cpp
I noticed this problem when I started working on frame pacing improvements.
"Immediate XFB" unsafely uses `CoreTiming::GetTicks` in "Dual Core" mode.
The result is currently just used for frame dumping and custom shaders, so it's not a major problem yet, but the value existing at all is encouraging more important things to use it in the future and be a bigger problem.
I don't see an easy fix other than completely eliminating the value and making frame-dumping/custom-shaders get timing by other means.
I don't know if there is a sensible way for the current ticks to even be gotten here.
I guess if we could get the time that this command was written from the CPU it could be done?
I haven't wrapped my head around all that yet so I've added a TODO for now.
Maybe someone more knowledgeable will …
=> BPStructs: Add TODO for unsafe usage of GetTicks.

Source/Core/Core/IOS/Network/IP/Top.cpp
The `GetSystemDefaultInterfaceOrFallback()` function is costly. Let's not pay for something we don't use. This fixes the following performance regression that can occur in some online games _(e.g. Monster Hunter 3)_:
=> IP/Top: Fix performance regression in GetInterfaceOpt

Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.cpp
This allows IMU accelerometer and gyroscope to function when only some of the directions are mapped.
Especially for "Free Look", users may not want to map every gyroscope direction.
A user just ran into this on discord. Free Look rotation wasn't working at all because they only had "Yaw" mappings.
=> InputCommon: Activate IMU Accelerometer and Gyroscope mappings when any direction has a bound input.

Source/Core/DolphinQt/Settings/AudioPane.cpp
See https://github.com/dolphin-emu/dolphin/pull/13122#issuecomment-2779905362
Before:
After:
=> DolphinQt/AudioPane: Fix Audio backend dropdown not using translated names

Source/Core/Common/MemArenaDarwin.cpp
Fixes https://bugs.dolphin-emu.org/issues/13785.
=> MemArenaDarwin: Initialize all address variables passed to vm_map

Source/Core/DiscIO/Volume.h
Replaces #13517 due to branch rename
=> DiscIO/Volume: Fix Partition struct comparison operators

Source/Core/DolphinQt/Config/ConfigControls/ConfigControl.h
Previously showed the default value if the game setting didn't exist, which meant it could be confusing as to what the actual option would end up being.
Also, for the note in the commit. Global Game settings are loaded through a workaround in GameConfigWidget that is a little complicated.
=> Game config settings: Show global value when no game setting exists.

Source/Core/Core/HW/CPU.cpp, Source/Core/Core/TimePlayed.cpp, Source/Core/Core/TimePlayed.h
When you use TimePlayed, you have to provide a game ID either when creating the object or when calling GetTimePlayed on it. If you don't provide a game ID when creating the object, function calls that don't take a game ID will silently fail, except for Reload. This isn't very obvious, and there's no strong benefit to storing the game ID inside TimePlayed anyway (it just lets TimePlayed skip calling EscapeFileName), so this commit removes the TimePlayed constructor that takes a game ID and instead makes the functions that need game IDs always take a game ID argument.
=> Core: Don't store game ID inside TimePlayed

Source/Core/Common/Timer.h
`RemoveDirectory` macro in windows.h was breaking the cmake build.
=> Common/Timer: Change HANDLE to void* to avoid including Windows.h to fix cmake build.

Source/Core/DiscIO/CISOBlob.h, Source/Core/DiscIO/CompressedBlob.h, Source/Core/DiscIO/DirectoryBlob.h, Source/Core/DiscIO/FileBlob.h, Source/Core/DiscIO/FileSystemGCWii.h, Source/Core/DiscIO/NFSBlob.h, Source/Core/DiscIO/RiivolutionPatcher.h, Source/Core/DiscIO/ScrubbedBlob.h, Source/Core/DiscIO/VolumeGC.h, Source/Core/DiscIO/VolumeWad.h, Source/Core/DiscIO/VolumeWii.h, Source/Core/DiscIO/WIABlob.h, Source/Core/DiscIO/WbfsBlob.h
This pull request updates several classes in the `DiscIO` module to use the `final` specifier, ensuring that these classes cannot be further subclassed. This change improves code clarity and enforces stricter type safety by explicitly marking these classes as non-extendable.
=> DiscIO: Make classes final

Source/Core/DiscIO/CISOBlob.h, Source/Core/DiscIO/FileSystemGCWii.cpp, Source/Core/DiscIO/Volume.h, Source/Core/DiscIO/VolumeGC.h, Source/Core/DiscIO/WbfsBlob.cpp
This pull request updates several constants across the `DiscIO` module to use `constexpr` instead of `const`. This change ensures that these constants are evaluated at compile time, improving performance and aligning with modern C++ best practices. The changes are primarily focused on improving code consistency and maintainability.
=> DiscIO: Make variables constexpr

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ActivityTracker.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java
dolphin-start event was being generated twice for the normal end-user case, as can be seen in analytics data for some years. The problem occured when:
* Android reaped the process hosting the dolphin activity (e.g. for power/memory saving). and
* Dolphin activity was in "stopped" state for > 6 hours before being switched back to.
Under above conditions, both calls to ReportStartToAnalytics would be performed, as dolphin thought it was being launched anew, and also thought it had been asleep for > 6 hours.
fixes https://bugs.dolphin-emu.org/issues/13675
=> Prevent android generating duplicate analytics events

Source/Core/Core/HW/SI/SI.cpp, Source/Core/Core/HW/SI/SI_Device.h, Source/Core/Core/HW/SI/SI_DeviceDanceMat.cpp, Source/Core/Core/HW/SI/SI_DeviceDanceMat.h, Source/Core/Core/HW/SI/SI_DeviceGBA.cpp, Source/Core/Core/HW/SI/SI_DeviceGBA.h, Source/Core/Core/HW/SI/SI_DeviceGBAEmu.cpp, Source/Core/Core/HW/SI/SI_DeviceGBAEmu.h, Source/Core/Core/HW/SI/SI_DeviceGCAdapter.cpp, Source/Core/Core/HW/SI/SI_DeviceGCAdapter.h, Source/Core/Core/HW/SI/SI_DeviceGCController.cpp, Source/Core/Core/HW/SI/SI_DeviceGCController.h, Source/Core/Core/HW/SI/SI_DeviceGCSteeringWheel.cpp, Source/Core/Core/HW/SI/SI_DeviceGCSteeringWheel.h, Source/Core/Core/HW/SI/SI_DeviceKeyboard.cpp, Source/Core/Core/HW/SI/SI_DeviceKeyboard.h, Source/Core/Core/HW/SI/SI_DeviceNull.cpp, Source/Core/Core/HW/SI/SI_DeviceNull.h
This fixes a regression that I caused in PR #13365
The GBA device `GetData` implementations returned `false` to signify "no data", but that caused `SetNoResponse` to be called.
`GetData` now returns an enum. This makes the meaning of the return value less confusing and allows the GBAs to return no data without signaling no response.
Fixes: https://bugs.dolphin-emu.org/issues/13786
=> SI: Fix GBA link by having a separate response for "error" and "no data".

Source/Core/Core/HW/DVD/DVDInterface.cpp
`GetDiscType()` uses `DVDThread::m_disc` which is `nullptr` when loading wiiware.
=> DVDInterface: Fix crash when playing wiiware.

Source/Core/Core/AchievementManager.cpp
In Achievement Manager, RetroAchievements disables pausing too frequently when running but there's no sense of doing this if RetroAchievements does not currently have a game running.
=> AchievementManager: Always allow pausing if game not loaded

Source/Core/AudioCommon/AudioCommon.cpp
fixes: https://bugs.dolphin-emu.org/issues/13787
=> AudioCommon: Make cubeb sound backend default on Linux.

Source/Core/Common/CMakeLists.txt, Source/Core/Common/WaitableFlag.h, Source/Core/Core/CMakeLists.txt, Source/Core/Core/IOS/USB/Common.cpp, Source/Core/Core/IOS/USB/Common.h, Source/Core/Core/IOS/USB/Emulated/Infinity.cpp, Source/Core/Core/IOS/USB/Emulated/Infinity.h, Source/Core/Core/IOS/USB/Emulated/Skylanders/Skylander.cpp, Source/Core/Core/IOS/USB/Emulated/Skylanders/Skylander.h, Source/Core/Core/IOS/USB/Host.cpp, Source/Core/Core/IOS/USB/Host.h, Source/Core/Core/IOS/USB/LibusbDevice.cpp, Source/Core/Core/IOS/USB/LibusbDevice.h, Source/Core/Core/IOS/USB/OH0/OH0.cpp, Source/Core/Core/IOS/USB/OH0/OH0.h, Source/Core/Core/IOS/USB/USBScanner.cpp, Source/Core/Core/IOS/USB/USBScanner.h, Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp, Source/Core/Core/IOS/USB/USB_HID/HIDv4.h, Source/Core/Core/IOS/USB/USB_HID/HIDv5.cpp, Source/Core/Core/IOS/USB/USB_HID/HIDv5.h, Source/Core/Core/IOS/USB/USB_VEN/VEN.cpp, Source/Core/Core/IOS/USB/USB_VEN/VEN.h, Source/Core/Core/System.cpp, Source/Core/Core/System.h, Source/Core/DolphinLib.props
Some games open two USB interfaces, e.g. `/dev/usb/oh0` and `/dev/usb/hid`. This was causing us to run two scanning threads at once, using up more CPU time for scanning than we need to.
=> IOS: Only have one USB scanning thread

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/IOS/USB/LibusbDevice.cpp, Source/Core/Core/IOS/USB/LibusbDevice.h, Source/Core/UICommon/USBUtils.cpp
This lets you use PS3 Rock Band controllers with Wii Rock Band and Guitar Hero games.
A normal user will probably never have any reason to disable this behavior, but I figured maybe there's some person out there who would like to disable it. (For instance, I know there's a mod for RB3 that's trying to implement the same kind of cross-console controller compatibility, and that can only be tested if the behavior I'm adding is disabled.) So the behavior is controlled by an INI-only setting.
I have properly tested the following PIDs:
* 0x0218 -> 0x3138
* 0x2338 -> 0x3338
* 0x2538 -> 0x3538
I have tested all other Wii PIDs by editing the source code to map one of the PS3 PIDs above to the "wrong" Wii PID. All of them work (though I have to say, playing 5-button guitar like that is extremely …
=> IOS: Disguise Rock Band PlayStation USB devices as Wii equivalents

BuildMacOSUniversalBinary.py, CMakeLists.txt, Readme.md, Source/Core/Common/MemoryUtil.cpp, Source/Core/VideoBackends/Metal/MTLUtil.mm
Bumps the minimum macOS version to 11.0 Big Sur. I've also gone ahead and removed some checks for macOS 10.15 which were missed when the last version bump happened.
Approximately ~2.6% of our macOS users within the past 30 days (and have analytics enabled) are running a version of macOS 10.15 Catalina.
<details>
<summary>Analytics data</summary>
macOS Version | Unique Users
| -- | -- |
15.5.0 | 1
15.4.0 | 571
15.3.2 | 4484
15.3.1 | 4869
15.3.0 | 626
15.2.0 | 802
15.1.1 | 560
15.1.0 | 411
15.0.1 | 304
15.0.0 | 265
14.7.5 | 4
14.7.4 | 247
14.7.3 | 67
14.7.2 | 67
14.7.1 | 74
14.7.0 | 70
14.6.1 | 917
14.6.0 | 195
14.5.0 | 905
14.4.1 | 323
14.4.0 | 169
14.3.1 | 113
14.3.0 | 155
14.2.1 | 163
14.2.0 | 37
14.1.2 | 43
14.1.1 | 66
14.1.0 | 58
14.0.0 | 102
13.7.5 | 12
13.7.4 | 420
13.7.3 | 55
13.7.2 …
=> CMakeLists: Bump minimum macOS to 11.0

Source/Core/Common/Buffer.h, Source/Core/Common/CMakeLists.txt, Source/Core/Common/LinearDiskCache.h, Source/Core/Core/State.cpp, Source/Core/Core/State.h, Source/Core/DolphinLib.props
In my investigating of what makes save states slow I noticed that the large buffers are unnecessarily zero-initialized (indirectly within `vector`/`make_unique`).
While there are other things making save states even more slow, zero-initialization of the ~100MB buffer does take a measurable amount of time so I think it's worth eliminating.
I've introduced `Common::UniqueBuffer` and `Common::SharedBuffer` as lighter alternatives to `std::vector`.
They are effectively just a smart pointer and size pair.
Save state code now uses `UniqueBuffer` instead of `vector`/`make_unique`.
=> Core/State: Avoid unnecessarily value-initializing large buffers.

Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.h
That tab was getting too tall.
The warnings are less visible, but I'm not so sure they worked anyways?
=> DolphinQt: Use tooltips on Advanced tab.

Source/Core/Core/IOS/Network/IP/Top.cpp
The NLMSG_OK() issue is known upstream since at least 2013:
https://lore.kernel.org/lkml/1386942898-21620-1-git-send-email-doront@mellanox.com/
It came up again in 2015:
https://lore.kernel.org/lkml/1425534428-24182-1-git-send-email-vapier@gentoo.org/
So far it's not been fixed or replaced.
=> IOS/Network: fix some warnings

BuildMacOSUniversalBinary.py
If the build folder is created from an older commit (i.e. PRs based on commits prior to when #13477 was merged) and this flag is not set, the last value set for this flag will be used instead. The last used value on our build machine is macOS 10.15, causing the deployment target to still be that version.
=> BuildMacOSUniversalBinary: Explicitly specify CMAKE_OSX_DEPLOYMENT_TARGET in CMake flags

Source/Core/DolphinQt/MainWindow.cpp
Fixing an oversight: this was causing the debugger to be disabled if achievements were disabled but hardcore mode was still enabled in the .ini. This fix properly checks for hardcore state via AchievementManager which takes both settings into account.
=> Fix debugger disabled bug

Source/Core/Common/FileUtil.cpp
It was being done manually, which a TODO comment advised against. Using generic_string() from std::filesystem::path solves this.
=> Core/Common/FileUtil.cpp: Use std path utility for automatic path separator handling.

Source/Core/VideoCommon/PerformanceMetrics.cpp
Fix overlays stacking on top of each other or not moving to the edge of the screen when enabling or disabling overlays while emulation is active.
This change only applies when Config::GFX_MOVABLE_PERFORMANCE_METRICS is False.
=> PerformanceMetrics: Fix window arrangement

Source/Android/app/build.gradle.kts, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFile.kt, Source/Android/app/src/main/res/layout/dialog_game_details.xml, Source/Android/app/src/main/res/layout/dialog_game_details_tv.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/GameList/GameFile.cpp
This is an Android continuation of PR #11469.
Unlike in DolphinQt, there isn't much space to show playtimes directly in the game list, so I've put it in the game details dialog instead.
=> Android: Show time played in game details

Source/Core/Common/Config/Config.h, Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/Core/CPUThreadConfigCallback.h, Source/Core/Core/FreeLookConfig.cpp, Source/Core/Core/FreeLookConfig.h, Source/Core/Core/FreeLookManager.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MainWindow.h, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/UICommon/UICommon.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
The primary thing this PR does is fix a use-after-free during Dolphin shutdown caused by a ConfigChangedCallback trying to access `MainWindow` after it's destroyed. This didn't cause any visible issues in Release builds (not that we should rely on that), but crashed in Debug builds (at least with Visual Studio) with an Access Violation.
To prevent this sort of thing from happening in the future I've also added `[[nodiscard]]` to the return value of `Config::AddConfigChangedCallback` and `CPUThreadConfigCallback::AddConfigChangedCallback`, which in turn required handling the return value for a handful of callers that don't already do so and calling RemoveConfigChangedCallback for them during shutdown.
=> MainWindow: Fix use-after-free during Dolphin shutdown

Data/Sys/GameSettings/RNK.ini
Disable Dual Core for NERF N-Strike by default, as the game refuses to boot with Dual Core enabled.
=> GameINI: Disable Dual Core for NERF N-Strike

Data/Sys/Shaders/default_pre_post_process.glsl
Here's a new and better gamma correction technique for sampling textures (for when we are resampling, which is basically always).
With this, we do resampling in linear space as before, but we also do it on the gamma space luminance of the colors (in parallel). This will tell us the exact brightness intensity our eyes would expect ("perceptually accurate"), while avoiding hue shifts due to non gamma corrected sampling (modulating colors in gamma space generates new incorrect/unexpected colors). It basically takes the best of both worlds.
This restores the slightly thicker borders of fonts and sprites, or anything that has a lot of contract on edges, but without having random hues in them (thus the gradients would be more perceptually correct). UI's readability should be improved with this …
=> Improve gamma corrected resampling by acknowledging the perceptual luminance

Source/Core/Common/WorkQueueThread.h, Source/Core/DolphinQt/GameList/GameTracker.cpp, Source/Core/VideoCommon/Assets/CustomAssetLoader.cpp, Source/UnitTests/Common/CMakeLists.txt, Source/UnitTests/Common/WorkQueueThreadTest.cpp, Source/UnitTests/UnitTests.vcxproj
`WorkQueueThread` is now implemented with `WaitableSPSCQueue`.
It is simpler, with fewer moving parts, and the worker no longer needs a mutex to access the queue.
A "single producer" `WorkQueueThreadSP` is introduced that uses no mutex for management of the worker.
PR #13475 will eliminate the mutex in `Event` making it entirely mutex-free.
I suspect most/all usages of `WorkQueueThread` are managed by a single thread and can be changed to `WorkQueueThreadSP`, but I'll assess that in future PRs.
I replaced the `Shutdown(bool cancel = false)` interface with `Shutdown()` which completes work, and `StopAndCancel()` which cancels work.
I added some unit tests.
=> WorkQueueThread: Implement in terms of WaitableSPSCQueue. Add unit tests.

Externals/zstd/CMakeLists.txt
Results in a "MSVC_RUNTIME_LIBRARY value 'MultiThreadedDLL' not known for this ASM compiler" otherwise, and [zstd doesn't support the relevant ASM code for MSVC anyway](https://github.com/facebook/zstd/blob/6af3842118ea5325480b403213b2a9fbed3d3d74/lib/common/portability_macros.h#L105-L130).
(we should really setup a cmake windows build on our build system one of these days)
=> Externals/zstd: Disable ASM for MSVC compiler in CMake

Source/Core/Common/SPSCQueue.h, Source/Core/Common/SmallVector.h, Source/Core/Common/TypeUtils.h
In #13431 I figured out a `union` trick for `SPSCQueue` to delay construction of objects without having to resort to indirect storage or scary `std::launder` nonsense.
I've moved that trick to a `ManuallyConstructedValue` template and and made `SmallVector` also use it.
=> Common: Move some duplicate container element construction logic into a ManuallyConstructedValue template.

Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
This is the first step towards using the C++23 standard library method for [converting an enum to its underlying type](https://en.cppreference.com/w/cpp/utility/to_underlying).
=>  DolphinQt/FIFO/FIFOAnalyzer: Use Common::ToUnderlying

Data/Sys/GameSettings/RKP.ini, Data/Sys/GameSettings/SK4.ini
The game is extremely sensitive to any timing change.
With dual-core on, changes in emulation speed will cause the game to start constantly freezing and unfreezing at random. Pressing and releasing Tab is just asking for the game to implode, especially if you do it repeatedly.
Without dual-core, pressing and releasing Tab doesn't cause issues.
Shrek Forever After may suffer from the same issue, as it uses the same engine. Someone should test it (maybe before this PR is merged).
=> GameINI: Enable Single Core for Kung Fu Panda and Shrek Forever After

Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h
This is just the cleanups of #13392 
I decided to make this a separate PR so discussion/reviews in that PR can be about just the setting itself.
Previous Throttle code adjusted time points every call leading to potential rounding errors and accumulated drift over time.
Time points are now adjusted by exact seconds to avoid this.
=> CoreTiming: Cleanups to avoid drift from cumulative rounding errors.

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
All valid PPC imm masks (except for all zeroes and all ones) are also valid AArch64 imm masks. This lets us optimize things a little.
Note that because I'm now ANDing rS before rotating it, its AND mask is rotated left. All AArch64 imm masks can be rotated by any amount and still be valid AArch64 imm masks.
=> JitArm64: Use AArch64 imm masks in rlwimix slow case

Source/Core/DolphinQt/Host.cpp
Fix the following bug:
* Have a moveable ImGui overlay enabled, such as the Statistics window.
* Pause the game.
* Click and hold on the overlay's title bar as if you were going to move it. Because the screen isn't updating while the game is paused, you won't be able to actually move the overlay.
* Press the Frame Advance hotkey several times until it stops responding.
At this point emulation hotkeys are no longer responsive. This can be resolved by selecting Play from the toolbar or menu, or selecting Frame Advance from the menu a couple times, but it's annoying and not obvious what's gone wrong or how to fix it.
Why the bug is happening:
* Doing a framestep while clicking on the overlay title bar causes ImGui to set IO.WantCaptureKeyboard to true, indicating that ImGui is requesting …
=> DolphinQt: Fix unresponsive hotkeys when clicking overlay during a framestep

Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
The "VI Skip" PR #11367 added logic to automatically check the SkipDuplicateFrames box when ImmediateXFB or VBISkip were enabled.
Automatically changing SkipDuplicateFrames when I enable ImmediateXFB is annoying.
The ImmediateXFB code path entirely avoids the duplicate frame check so it's just irrelevant.
VideoConfig forces SkipDuplicateFrames when VBISkip is enabled so it's also not explicitly needed there.
https://github.com/dolphin-emu/dolphin/blob/23ad07b3688a1145c22ac72dfc35b0d2f9f834ff/Source/Core/VideoCommon/VideoConfig.cpp#L144
The mentioned settings now only disable the SkipDuplicateFrames box, which is the behavior prior to #11367.
=> DolphinQt: Don't auto toggle GFX_HACK_SKIP_DUPLICATE_XFBS.

Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/Core/HW/CPU.cpp, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/VideoCommon/PerformanceMetrics.cpp, Source/Core/VideoCommon/PerformanceMetrics.h, Source/Core/VideoCommon/PerformanceTracker.cpp, Source/Core/VideoCommon/PerformanceTracker.h
libvideocommon instantiates the g_perf_metrics variable, which contains PerformanceTracker objects.
The destructors for these objects modify the s_on_state_changed_callbacks vector, which lives in libcore.
This means libvideocommon must be torn down before libcore. However, libcore's functions need g_perf_metrics, so libcore needs libvideocommon to be loaded.
Break the dependency cycle by moving g_perf_metrics to libcore.
This fixes a segmentation fault with LTO enabled.
=> Core, VideoCommon: Fix crash at shutdown due to destructor order

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ActivityTracker.kt
PR #13520 made it so analytics start events can only be generated when starting the main activity. However, some users launch Dolphin's emulation activity from a separate frontend application, bypassing Dolphin's main activity. This change adjusts the logic so that start events can be generated if any activity is started after 6 hours of inactivity. This more closely matches the behavior we had before PR #13520, while still ensuring duplicate start events aren't generated.
I've also fixed the inconsistent indentation in `ActivityTracker.kt`.
=> Android: Allow reporting start to analytics for non-main activity

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt
There's no guarantee that directory initialization has completed by this point, so we can't safely use NativeLibrary.
I'm making this change because of a crash being reported in Google Play Console. The exact way it's crashing is mysterious to me, so I'm not sure if this commit fixes the crash, but I think this commit is a reasonable change to make even if it doesn't fix the crash. Backtrace from Google Play Console:
```
#00  pc 0x0000000000469074  /data/app/~~m0kqybFNfeqnDenQFc53XQ==/org.dolphinemu.dolphinemu-Mtaw0lU8DVUQbte2ZjBp3w==/lib/arm64/libmain.so (std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, …
```
=> Android: Don't call NativeLibrary methods during class init

Source/Core/Core/HW/DVD/DVDThread.h, Source/Core/Core/IOS/Network/IP/Top.h, Source/Core/Core/IOS/Network/KD/NetKDRequest.h, Source/Core/VideoBackends/Vulkan/CommandBufferManager.h
These places only manage their queue from a single thread.
Using `WorkQueueThreadSP` eliminates the mutex locking.
=> Core and Vulkan: Change WorkQueueThread to WorkQueueThreadSP in a few places.

Source/Android/app/src/main/res/layout-ldrtl/list_item_mapping.xml
Probably a copy-paste error from layout-ldrtl/list_item_setting.xml. This error made it so a long setting name could overlap with the checkbox next to it if Dolphin was running with right-to-left layout.
The incorrect ID was apparently also causing the app:lintVitalRelease build task to fail. I guess we're not running that build task, because I only heard of this from someone building Dolphin locally.
=> Android: Fix incorrect ID in layout-ldrtl/list_item_mapping.xml

Source/Core/Core/CoreTiming.cpp
Fixes an error when building with `-DUSE_RETRO_ACHIEVEMENTS=OFF`. Regression from #13499.
=> CoreTiming: Add missing SystemTimers.h include

Source/Core/UICommon/DiscordPresence.h
The header isn't implicitly included on musl.
Bug: https://bugs.gentoo.org/952952
=> UICommon: Include implicit header

Source/Core/Common/Config/Config.cpp
Different threads are adding and calling callbacks, so this should have some locking. This is both to ensure thread safety when accessing `s_callbacks` and to ensure that there won't be situations where a callback gets called after it's removed.
`s_callback_guards` is also accessed from multiple threads and has therefore been made atomic.
=> Config: Add locking for config changed callbacks

Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h, Source/Core/DolphinQt/QtUtils/ModalMessageBox.cpp, Source/Core/DolphinQt/QtUtils/ModalMessageBox.h
Implements https://bugs.dolphin-emu.org/issues/12887
This is my first PR for a feature, so I'd really appreciate feedback on what to improve and/or do differently!
=> Implement importing multiple saves from an export folder

Source/Core/Common/Logging/LogManager.cpp, Source/Core/Common/Logging/LogManager.h, Source/Core/DolphinQt/Config/LogWidget.cpp, Source/Core/DolphinQt/Config/LogWidget.h
This fixes a memory leak that would occur when the Android frontend calls LogManager::Init more than once in order to reload settings.
Note that the log window listener is now owned by LogManager instead of by the frontend, making it consistent with the other log listeners.
=> LogManager: Stop using manual memory management

Source/Core/InputCommon/ControllerInterface/SDL/SDLGamepad.h
Verify a touchpad is present before polling it for input. Without this check, if you have a controller that doesn't have a touchpad the Debug log gets spammed with the message `error: Parameter 'touchpad' is invalid`, and its touchpad values quickly shoot to -inf.
One would think every touchpad supports at least 1 finger, but in case there's some weird edge case check the finger count to be sure.
=> SDL: Check if touchpad exists before getting input

Source/Core/AudioCommon/CubebUtils.cpp, Source/Core/AudioCommon/CubebUtils.h
Our cubeb logging is broken on Linux.
```
56:00:998 onst char *):924 I[Audio]: Requested buffer attributes maxlength 4294967295, tlength 4800, prebuf 4294967295, minreq 1200, fragsize 1200
56:01:006 onst char *):1035 I[Audio]: Output buffer attributes maxlength 4194304, tlength 3600, prebuf 2404, minreq 1200, fragsize 1200
56:01:006 onst char *):1049 I[Audio]: Cubeb stream (0x77fb9c005620) init successful.
56:01:691 onst char *):1115 I[Audio]: Cubeb stream (0x77fb9c005620) started successfully.
56:01:693 onst char *):1131 I[Audio]: Cubeb stream (0x77fb9c005620) stopped successfully.
56:01:958 onst char *):1115 I[Audio]: Cubeb stream (0x77fb9c005620) started successfully.
56:02:813 AudioCommon/AudioCommon.cpp:83 I[Audio]: Shutting down sound stream
56:02:813 onst char *):1131 I[Audio]: …
```
=> AudioCommon/CubebUtils: Fix logged file name.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.kt
Old cruft from when the Android code was loading INI files manually. We don't have any handling for failing to load settings anymore.
This change also updates related comments to reflect how things actually work nowadays.
=> Android: Remove unused onSettingsFileNotFound and friends

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/HW/DVD/DVDInterface.cpp
Update the rcheevos submodule with new hashes and provide the updated wiring to AchievementManager to properly hash and load Wii and WiiWare titles.
Note that this is merely support; actual achievements will be released and available when a rollout is complete.
=> RetroAchievements - Wii and WiiWare Support

Source/Core/DolphinQt/GameList/GameList.cpp
When a game in the Game List is double-clicked by a mouse button other than the left button, don't start the game. This prevents things like accidentally starting a game when trying to close a context menu.
Fixes https://bugs.dolphin-emu.org/issues/12272.
The Game List's empty widget (shown when you don't have any paths set up, or games in those paths) continues to respond to right/other clicks since there's no other action to confuse that with.
=> GameList: Ignore non-left double-clicks

Data/Sys/GameSettings/GCA.ini, Data/Sys/GameSettings/GFO.ini, Data/Sys/GameSettings/GFW.ini, Data/Sys/GameSettings/GJY.ini, Data/Sys/GameSettings/GNO.ini, Data/Sys/GameSettings/GQ4.ini, Data/Sys/GameSettings/GQQ.ini, Data/Sys/GameSettings/GU6.ini, Data/Sys/GameSettings/GYA.ini, Data/Sys/GameSettings/R38.ini, Data/Sys/GameSettings/R6B.ini, Data/Sys/GameSettings/RBY.ini, Data/Sys/GameSettings/RN3.ini, Data/Sys/GameSettings/RQ4.ini, Data/Sys/GameSettings/RUS.ini, Data/Sys/GameSettings/SDB.ini
This PR provides a batch of GameSettings updates:
- Sets SafeTextureCacheColorSamples to proper values to fix choppy/pixelated FMVs.
- Disable texture filtering for several games to prevent broken FMVs.
- Disable ImmediateXFBEnable to prevent some FMV hangs in Nicktoons: Battle for Volcano Island and Barnyard Wii specifically.
=> GameSettings: Various Nick games fixes

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/QtUtils/NonAutodismissibleMenu.cpp, Source/Core/DolphinQt/QtUtils/NonAutodismissibleMenu.h
A new class that derives from `QMenu` has been introduced. Menus of this `NonAutodismissibleMenu` type will stay visible when a _checkable_ action is triggered.
This is convenient in menus that feature a series of check boxes that toggle visibility of third components (e.g. the **List Columns** menu), allowing the user to toggle several actions at once.
For now, the new type is used in the top menu bar.
=> DolphinQt: Use non-autodismissable menus in menu bar.

Externals/bzip2/CMakeLists.txt, Externals/liblzma/CMakeLists.txt, Externals/minizip-ng/CMakeLists.txt, Externals/zstd/CMakeLists.txt
The context of noticing the missing includes for minizip-ng was that I was packaging dolphin-2407 for gentoo where using system packages is preferred if viable. This unusual setup meant that includes that were used indirectly were missing.
=> Add missing cmake includes and remove unused cmake includes

Source/Core/Core/AchievementManager.cpp
Within AchievementManager, CloseGame being called when LoadGame fails was causing m_queue.Cancel to be called within a lock when Cancel itself locks until it is empty, causing a deadlock. This is resolved by cancelling the queues outside of the lock when they are safe to wait for resolutions.
=> AchievementManager: Fix unknown hash achievements deadlock

Source/Core/Common/Buffer.h, Source/Core/Common/Image.cpp, Source/Core/Common/Image.h, Source/Core/DolphinQt/Achievements/AchievementBox.cpp, Source/Core/InputCommon/ImageOperations.cpp, Source/Core/UICommon/GameFile.cpp, Source/Core/VideoCommon/Assets/CustomTextureData.cpp, Source/Core/VideoCommon/Assets/CustomTextureData.h
Using `Common::UniqueBuffer` avoids unnecessary zero-initialization of these buffers.
I suppose it also prevents any inadvertent copying of the data.
=> Common and VideoCommon: Change texture data from std::vector to Common::UniqueBuffer.

Data/Sys/GameSettings/WMOEE9.ini, Data/Sys/GameSettings/WMOJE9.ini, Data/Sys/GameSettings/WMOPE9.ini
The game sets up a fifo breakpoint callback that just writes a flag to memory. The hang occurs right after calling GXEnableBreakPt(). It is a busy loop that repeatedly compares the same register without reloading it from memory. I guess the developers forgot to make the variable atomic and never noticed because on hardware the breakpoint is hit immediately so the flag is already set when it is loaded for the first (and only) time. This patch grows the loop by one instruction to include the flag load in the loop.
This fixes [issue 13730](https://bugs.dolphin-emu.org/issues/13730).
=> GameSettings: fix startup hang in Moki Moki

CMakeLists.txt
This allows for `zlib` to be provided by the system. This includes the case where the distro builds and ships `zlib-ng` in `zlib` compat mode.
For some reason, `minizip-ng` from Externals cannot find `check_function_exists` if `zlib` is provided by the system while  `minizip` is not, which is why the CMakeLists was modified.
This is a followup to #13089.
=> CMake: Allow shared zlib

Source/Core/AudioCommon/CubebStream.cpp, Source/Core/AudioCommon/CubebStream.h, Source/Core/Common/WorkQueueThread.h, Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/Core/HW/EXI/EXI_DeviceMic.cpp, Source/Core/Core/HW/EXI/EXI_DeviceMic.h, Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp, Source/Core/Core/IOS/Network/KD/NetKDRequest.h
There were a few places that used `Common::WorkQueueThread<std::function<void()>>`.
I've added an `AsyncWorkThread` that makes doing that a bit less ugly.
=> Common: Add AsyncWorkThread.

Source/Core/DolphinQt/TAS/TASControlState.h
As far as I understand the existing code is valid, but libstdc++ 15 claims `std::atomic<State>` has no default-ctor.
=> DolphinQt/TAS: Use non-default std::atomic struct constructor to fix build with libstdc++ 15.

Source/Core/Core/HW/MMIO.cpp, Source/Core/Core/HW/ProcessorInterface.cpp, Source/Core/Core/State.cpp, Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/CommandProcessor.h
This fixes the shutdown error in SpongeBob Globs of Doom.
~Might also fix the [occasional errors in Dave Mirra Freestyle BMX 2](https://bugs.dolphin-emu.org/issues/9802).~ The errors still happen.
=> VideoCommon: reset some CP registers during PI_FIFO_RESET 

Data/Sys/GameSettings/GPT.ini
Prince of Persia: Sands of Time exhibits screen tearing on FMVs in Dolphin. Tested the setting (suggested by Amphitryon in the Discord) on PC and Android and can confirm the tearing previously seen is gone with EarlyXFBOutput disabled.
=> GameINI: fix screen tearing in PoP:SoT FMVs

Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp
This PR changes the log level of this message as it can be sent a lot when polling inputs from a keyboard. Thus, killing performance by a lot. HIDv5.cpp doesn't log INTRMSG in such a way. If needed, log messages can be added into specific devices instead.
=> IOS/USB: Change HIDv4.cpp LogLevel to avoid INTRMSG killing performance

Source/Core/Core/AchievementManager.h
Fixes: c796691d008263f214364bbb986e3ad2c900ae94
With -DUSE_RETRO_ACHIEVEMENTS=OFF
```
/home/ask/sources/dolphin/Source/Core/Core/Boot/Boot.cpp: In member function ‘bool CBoot::BootUp(Core::System&, const Core::CPUThreadGuard&, std::unique_ptr<BootParameters>)::BootTitle::operator()(const DiscIO::VolumeWAD&) const’:
/home/ask/sources/dolphin/Source/Core/Core/Boot/Boot.cpp:626:49: error: no matching function for call to ‘AchievementManager::LoadGame(const DiscIO::VolumeWAD*)’
626 |       AchievementManager::GetInstance().LoadGame(&wad);
|       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/ask/sources/dolphin/Source/Core/Core/Boot/Boot.cpp:626:49: note: there is 1 candidate
In file included from /home/ask/sources/dolphin/Source/Core/Core/Boot/Boot.cpp:31: …
```
=> Remove filename option from stubbed AchievementManager::LoadGame

Flatpak/org.DolphinEmu.dolphin-emu.yml
This is `/etc/flatpak-builder/defaults.json` on `org.kde.Sdk` 6.8:
```json
{
"libdir": "/usr/lib/x86_64-linux-gnu",
"cflags": "-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ",
"cxxflags": "-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ",
"cppflags": "",
"ldflags": "-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed "
}
```
=> Flatpak: Don't use CFLAGS and CXXFLAGS provided by the SDK

Source/Core/Core/HW/SI/SI.cpp, Source/Core/Core/HW/SI/SI.h
When an `SIDevice` was plugged/unplugged a flag was set to prevent additional changes for one second so the system has time to acknowledge the change or whatever. One second seems excessive, but anyways, that's the existing behavior.
Now that only happens when a device is specifically *unplugged*.
This allows an `SIDevice` to always be disconnected as soon as requested.
I don't think it makes sense to leave a device connection lingering, even if it was recently attached.
We don't want some potentially stale/stuck data getting read for the remaining timeout.
If we desire a device to be disconnected then it should *now* be disconnected.
After unplugging a device, plugging in a new one is still prevented for 1 second, which again, seems excessive.
The state version doesn't need a bump. The …
=> HW/SI: Don't require waiting a second before disconnecting an SIDevice.

Source/Core/Common/GekkoDisassembler.cpp
The time base registers appear twice, so I'm using the same r/w suffixes as Ghidra does to tell them apart.
The assembler still needs updating but it didn't quite match even before this change.
=> GekkoDisassembler: standardize SPR names and add missing ones

Source/Core/Common/Crypto/SHA1.cpp
This fixes an out-of-bound array access error that a user was getting in the 2503a flatpak.
```
/usr/include/c++/14.2.1/array:208: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = unsigned char; long unsigned int _Nm = 64; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```
The offending line:
https://github.com/dolphin-emu/dolphin/blob/8a9a082c6960754e514a05147184678855254cf6/Source/Core/Common/Crypto/SHA1.cpp#L116
It was called with a size of zero, so there wasn't actually any bad access, but stdlibs are getting picky about how you use `std::array::operator[]` it seems.
The quick fix is to always use `.data()` for this sort of thing.
`block[block_used]` -> …
=> Crypto/SHA1: Fix past-the-last-element std::array access and modernize code.

Source/Core/VideoCommon/VertexShaderGen.cpp
I realize how difficult #13346 would be to review, so I'm going to split it out in pieces.  This will also allow me to catch any fifo errors more easily.
This exposes functions getting the position/normal matrices.  This also introduces a slight optimization by only calculating the bitangent/tangent if we really need it (emboss).
=> VideoCommon: move transform matrices to accessible functions in VertexShaderGen

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
A couple portions of AchievementManager were still limiting to MEM1 despite everything else supporting Wii.
=> AchievementManager: MEM2 Support

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/FloatSetting.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/app/src/main/res/values/strings.xml, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h, Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/HW/VideoInterface.cpp, Source/Core/Core/HW/VideoInterface.h, Source/Core/Core/IOS/DolphinDevice.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.h, Source/Core/VideoCommon/FrameDumpFFMpeg.cpp, Source/Core/VideoCommon/FrameDumpFFMpeg.h
Rebase of #11486, which seems to have been abandoned.
The highlight of this feature is the ability to **play games at higher than 60 FPS**, at normal gameplay speed, and without affecting the audio.
https://github.com/user-attachments/assets/d33119c7-994a-4414-a9f9-0e8ed8f7cb4a
(More videos on #11486)
This feature works, it's simple and non-invasive, and put formally, it is very cool.
However, the current user experience isn't the best.
Here are the current problems, with proposed solutions. I'm asking for feedback on the "IMO"s.
A game with more FPS is obviously going to be more demanding for the emulated console, but if the emulated CPU clock doesn't change, then the console is basically going to be underclocked.
At best, this will cause the game to not run at the target frame rate …
=> Add VBI Frequency Override

Data/Sys/GameSettings/GPL.ini, Data/Sys/GameSettings/GWH.ini
Disable Dual Core for Piglet's Big Game and Winnie The Pooh's Rumbly Tumbly Adventure since it uses the same engine, as these games are very unstable and prone to freezing/crashing with Dual Core enabled.
=> GameINI: Disable Dual Core for Piglet's Big Game

Source/Core/Core/PowerPC/Interpreter/Interpreter.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
On real hardware, stswi and stswx don't trigger any of the special behavior for uncached unaligned writes that was implemented in 543ed8a. This is confirmed by a hwtest (a new commit in https://github.com/dolphin-emu/hwtests/pull/42).
This change fixes Dolphin's stswi and stswx implementations so they stop triggering the special behavior, bringing them back to the behavior they had before 543ed8a. No games are known to be affected, but @extremscorner has reported that it affects homebrew they've made.
=> PowerPC: Correctly handle stswi/stswx to uncached memory

Data/Sys/GameSettings/GJN.ini
This game requires EFB Access to display some images: the splash logo at boot, the title screen, and loading screens.
The performance difference during gameplay is in the margin of error.
The title screen performance *tanks* with EFB Access: it becomes barely over full speed on my computer, despite the actual game being playable at 9x speed.
Also in this game, for some reason, after the attract demo plays, the title screen performance becomes worse: with EFB access, the post-attract performance is less than 15 VPS.
But without EFB Access, players wouldn't know that they need to press Start (and not any other button) to play this beloved classic.
(And after pressing Start, the title screen is over.)
A black screen.
=> GameINI: Enable EFB Access for Jimmy Neutron Boy Genius

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/MainWindow.cpp
The issue was fully described by @Dentomologist in discord.
In short, an async task could potentially trigger shutdown which tries to wait on completion of the async task itself.
The async task callbacks now happen on the host thread.
This does complicate things, and I'm not entirely happy about that, but it does seem to solve the problem.
`AchievementManager::CloseGame` could use `QueueOnObject` to run on the host-thread, but I really haven't wrapped my head around the consequences of that.
A flag could be set for the worker to skip processing of remaining tasks. The host-thread could re-enable processing later. This seemed more hacky to me.
WorkQueueThread could be altered so `Cancel` can be called from within a job, but that also seems hacky to me.
=> RetroAchievements: Fix potential deadlock on shutdown.

Source/Core/DolphinQt/Config/CheatWarningWidget.cpp, Source/Core/DolphinQt/Config/GameConfigWidget.cpp, Source/Core/DolphinQt/Config/GraphicsModWarningWidget.cpp, Source/Core/DolphinQt/Config/Mapping/GCKeyboardEmu.cpp, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtensionMotionInput.cpp, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuMotionControlIMU.cpp, Source/Core/DolphinQt/QtUtils/QtUtils.cpp, Source/Core/DolphinQt/QtUtils/QtUtils.h
This adjusts a few places where we have an icon with some warning/info text that had duplicated layout-creation, icon-creation, and size-calculation code.
This moves and increases size of the icon at the top of the game config pane.
Before:
After:
It slightly reduces the size of the icon in a few other places.
All After:
Update:
Replaced Motion Input "WARNING: " text with an icon:
=> DolphinQt: Add utility function for creating label text with a standard icon.

Data/Sys/GameSettings/SH8.ini, Data/Sys/GameSettings/SUV.ini
This keeps the in-game bloom effect from becoming brighter and brighter, see [issue 13797](https://bugs.dolphin-emu.org/issues/13797).
=> GameSettings: disable efb2tex for two Cabela's games

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/AdvancedMappingDialog.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.kt
If you already have a mapping set in the advanced mapping dialog and want to change it, the easiest way to do it is to press Clear and then select the new mapping from the list. But pressing Clear causes the dialog to close, forcing you to open it again, which is inconvenient. This commit makes it so the Clear button doesn't close the dialog.
=> Android: Don't dismiss AdvancedMappingDialog when pressing Clear

Source/Core/DolphinQt/Config/ControllersWindow.cpp, Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp, Source/Core/DolphinQt/Config/WiimoteControllersWidget.h
Fix the UI hanging for several seconds when opening the Controllers window.
Move the scan for Bluetooth adapters onto a separate thread so the Host thread doesn't have to wait for it.
Only automatically scan for adapters once, when opening the Controllers window for the first time. Add a Refresh button to let the user refresh the adapter list afterward.
=> WiimoteControllersWidget: Fix UI hang when opening Controllers window

Data/Sys/GameSettings/GM2.ini, Data/Sys/GameSettings/GMB.ini, Data/Sys/GameSettings/GQN.ini, Data/Sys/GameSettings/RKM.ini
This PR resolves FIFO error crashes for several titles as reported by the Dolphin Wiki:
* Alvin and the Chipmunks - This game straight up refuses to boot to the title screen with Dual Core enabled for me.
* Mortal Kombat: Armageddon - This game does indeed crash on a few occasions with Dual Core on. Also, enabling Vertex Rounding actually fixes the shadow lines despite what the Dolphin Wiki says otherwise.
* Mortal Kombat: Deception - Not listed on the wiki, but suffers from the same Dual Core crashing issues. No shadow lines from what I can see though.
* Super Monkey Ball 1 & 2 - Both games have issues running with Dual Core, from constant freezes to crashes.
* Virtua Striker 2002 - This game straight up refuses to boot to the title screen with Dual Core enabled for me. It also sometimes …
=> GameINI: Disable Dual Core for several games

Source/Core/Core/IOS/USB/USBScanner.cpp, Source/Core/Core/IOS/USB/USBScanner.h
I maintain a project for emulating various rhythm game controllers (https://santroller.com/)
Currently on consoles it automatically detects what console is in use and emulates the correct device for a given console, but the intrinsic it uses for that doesn't work for dolphin, so i've just added support for sending a control request to make these devices jump to the right mode.
=> LibusbDevice: Send wakeup command to Santroller devices

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/MainWindow.cpp
LoadGameCallback was calling CloseGame due to a bug found previously where closing a game during loading and opening a new one was causing the achievements implementation to get confused which game was running. This, however, was causing deadlocks, because CloseGame was cancelling the queue LoadGameCallback was sitting on, causing the function to wait for itself to finish before finishing. This removes the CloseGame call. I have been unable to reproduce the original issue anymore, I don't know what could have happened in the changes made since then that could have resolved it, but it's not happening with the same steps it used to, so I believe for now this is safe but will continue to monitor.
In the process, made a minor, mostly cosmetic change to the displayed message for an unsupported …
=> AchievementManager - LoadGameCallback 

Source/Core/DolphinQt/Config/PropertiesDialog.cpp
This is probably controversial. :)
This makes the `Info` tab first in the game properties dialog.
Game right-click -> Properties now initially shows the `Info` tab.
I think this is the sort of thing that should be shown by default for "Properties".
e.g. Right-clicking a file in your OS file explorer and choosing "Properties" will show information like this.
`Game Config` is now an additional click away.
I think this is fine, and maybe even good. I don't think `Properties` should take users right to the game-specific config.
Most users probably don't even belong in there.
Opinions?
=> DolphinQt: Make the Info tab first in the game properties dialog.

Data/Sys/GameSettings/GSM.ini
* The game does not have a built in widescreen mode
* There exists no widescreen hack currently
* There is a first person hack, this adjustment keeps 4:3 this case as well
To trigger the constant switching pre-change, enter the training level and move the camera around, or invoke UI pop ups
https://github.com/user-attachments/assets/b872a7c1-1f43-49c3-ba24-2537c2c8abfa
=> GameINI: Spider-Man SuggestedAspectRatio to 4:3

Source/Core/DolphinQt/HotkeyScheduler.cpp
We have a general policy of not translating OSD strings due to the OSD font not having good enough support for languages other than English.
=> DolphinQt: Don't translate Wii Speak OSD string

Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Fixes [this bug report](https://bugs.dolphin-emu.org/issues/13551) (Wii Menu is corrupt).
Checksum was not being set when I flushed the config files, causing the menu to throw that error.
=> IOS/KD: Set Checksum when flushing NWC24Config

Data/Sys/GameSettings/GUP.ini
Saw a high volume of dual core causing crashes with the launch of RA set.
=> GameINI: Disable Dual Core for Shadow the Hedgehog

Data/Sys/GameSettings/G97.ini, Data/Sys/GameSettings/RL6.ini, Data/Sys/GameSettings/SN2.ini, Data/Sys/GameSettings/SR4.ini
This PR resolves Dual Core crashes for a few more games I found on the wiki and the bugs tracker:
* Interactive Multi Game Demo Disc v3 - This game comes with Sonic Adventure 2, which is known for crashing with Dual Core enabled.
* NERF N-Strike Elite - This game hangs/freezes with Dual Core enabled. I'm also putting the Double Blast Bundle compilation disc since it has the same issues.
* Raving Rabbids: Travel in Time - This game crashes with Dual Core enabled on startup for me. Also, even with Dual Core disabled, the game still crashes if you try to skip the opening FMV for some weird reason. Probably linked to [this post somehow](https://bugs.dolphin-emu.org/issues/13233#note-4).
=> GameINI: Disable Dual Core for more games

Source/Core/Common/Config/Config.cpp
Trying to change the speed limit in the UI with "hardcore mode" enabled would cause `AchievementManager::SetHardcoreMode` to `Config::SetBaseOrCurrent` within a "ConfigChangedCallback" which would deadlock.
This fixes that.
=> Config: Make s_callbacks_lock recursive to fix hardcore mode deadlock.

Data/Sys/GameSettings/GIHP78.ini
FMVs have horrible video stuttering without it.
Gameplay FPS penalty is in the margin of error.
Tested on GIHP78.
It might be possible that the NTSC version is not affected? (Most FMVs on the PAL version are encoded at 25 FPS, but the ones encoded at 30 FPS do not seem to have the issue.)
https://github.com/user-attachments/assets/9dde4c9b-8134-4d57-96d6-11bfca7ab0fb
=> GameINI: Set texture cache accuracy for Scooby-Doo! Night of 100 Frights PAL

Source/Android/app/src/main/AndroidManifest.xml
Google Play is now blocking distribution for Android TV unless we explicitly set the android.hardware.microphone hardware feature as `android:required="false"`, because it's inferring `android.hardware.microphone` from the `android.permission.RECORD_AUDIO` we added for Wii Speak emulation, with `android:required` defaulting to true. I was under the belief that setting `android:required="false"` on `android.permission.RECORD_AUDIO` would solve this, but looking closer at the definition of `<uses-permission>`, it doesn't actually support `android:required` attributes, so that presumably has no effect.
=> Android: Add android.hardware.microphone to manifest

Data/Sys/GameSettings/SCYE4Q.ini, Data/Sys/GameSettings/SCYP4Q.ini, Data/Sys/GameSettings/SCYR4Q.ini, Data/Sys/GameSettings/SCYX4Q.ini, Data/Sys/GameSettings/SCYY4Q.ini, Data/Sys/GameSettings/SCYZ4Q.ini, Data/Sys/GameSettings/SQI.ini, Data/Sys/GameSettings/SQIE4Q.ini, Data/Sys/GameSettings/SQIP4Q.ini, Data/Sys/GameSettings/SQIY4Q.ini, Data/Sys/GameSettings/STSE4Q.ini, Data/Sys/GameSettings/STSP4Qr1.ini, Data/Sys/GameSettings/STSP4Qr2.ini, Data/Sys/GameSettings/STSX4Q.ini, Data/Sys/GameSettings/STSY4Qr0.ini, Data/Sys/GameSettings/STSY4Qr1.ini, Data/Sys/GameSettings/STSZ4Q.ini
Adds a (enabled by default) game patch for the Disney Trio of Destruction that repairs their performance by allowing them to use fastmem.  Makes their performance actually decent enough to play, though they are still quite heavy at times.  I'm able to get full speed most of the time in all three titles, outside of a few rough moments.
As I do not have every single revision, I wasn't able to add codes for every revision, but based on cheat code addresses I can find online alongside the revisions I do have, I am fairly confident in all of the patches I added.  If a user with that revision does report a crash, it should be very easy to fix.
=> GamePatch: Disney Trio of Destruction Pagetable Speedhack.

Source/Core/VideoCommon/PixelShaderGen.cpp
I saw an error during testing that triggered this warning.  I really hate this error in d3d..
=> VideoCommon: ensure pixel shader gen input structure is completely initialized

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h, Source/Core/DolphinQt/Settings/AdvancedPane.cpp
Followup of #13499 which eliminated the time drift from cumulative rounding errors.
`MaxFallback` (default: 100ms) has already existed to reset the throttle if emulation strays too far from the target time, such as from a CPU bottleneck.
If stutters exceeds 100ms before Dolphin can catch up, it will adjust the reference time and effectively commit to running >100ms in the past.
That is not ideal for internet play and a user has reported it as a cause of issue with Wiimmfi.
https://bugs.dolphin-emu.org/issues/13609 (fixed)
I've added a new setting, `CorrectTimeDrift`. When enabled, `MaxFallback` is ignored to instead pursue accurate elapsed time.
I've added a "Timing" section on the "Advanced" tab for now.
"Sync with Host Refresh Rate" and "Reduce Input Latency" settings might also go …
=> CoreTiming: Add setting to pursue accurate overall emulation runtime

Source/Core/DolphinQt/Config/PropertiesDialog.cpp, Source/Core/DolphinQt/Config/PropertiesDialog.h, Source/Core/DolphinQt/GameList/GameList.cpp
Previously, if you right-click a game, select Properties, and then do it again on the same game, you'd get multiple property windows for the same game, which is... a mess.
With this change, attempting to do so will instead raise the already-existing window.
(Is it fine to just raise, or would it be preferable to do other things as well?
I'm asking because with the current PR, if the property window is minimized, then nothing visibly happens when clicking properties, which may be poor UX.)
Note that in order to check whether the properties window is already opened for the game, only the ~~GameID~~ filepath is compared.
=> GameList: Prevent opening Properties multiple times for the same game

Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.cpp, Source/Core/DolphinQt/Config/ConfigControls/ConfigSlider.h, Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.h
Part of refactoring things into the config system.  Sliders are especially important because they feel laggy as you drag them due to spamming updates.  Once they are under the Config system we could reduce the update interval, which should make things more responsive.
I had to add a new ConfigSliderU32 class to deal with the unsigned and their extra scale factor.
No visual changes.
=> Advanced Panel convert QSliders into ConfigSliders

Source/Core/AudioCommon/AudioCommon.cpp, Source/Core/Common/FatFsUtil.cpp, Source/Core/Common/SettingsHandler.cpp, Source/Core/Common/TimeUtil.cpp, Source/Core/Common/TimeUtil.h, Source/Core/Core/Core.cpp, Source/Core/Core/NetworkCaptureLogger.cpp, Source/Core/Core/State.cpp, Source/Core/VideoCommon/FrameDumpFFMpeg.cpp
[fmt 11.2.0](https://github.com/fmtlib/fmt/releases/tag/11.2.0) deprecates `fmt::localtime` in favor of `std::localtime`.
This PR follows this recommendation.
=> fmt: Replace deprecated `fmt::localtime` usage with `Common::LocalTime`

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/AudioUtils.kt, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/AndroidCommon/IDCache.h, Source/Core/AudioCommon/OpenSLESStream.cpp, Source/Core/AudioCommon/OpenSLESStream.h
This can reduce audio latency according to https://developer.android.com/ndk/guides/audio/opensl/opensl-prog-notes#perform.
Previously we were using the hardcoded values of 48000 Hz and 256 frames per buffer. The sample rate we use with this change is 48000 Hz on all devices I'm aware of, but the buffer size does vary across devices.
Terminology note: The old code used the term "sample" to refer to what Android refers to as a "frame". "Frame" is a clearer term to use for this, so I've changed OpenSLESStream's terminology. One frame consists of one sample per channel.
=> Android: Ask system for optimal audio buffer size and sample rate

Source/Core/AudioCommon/AlsaSoundStream.h
PR #13697 removed some includes that were in fact in use.
=> AudioCommon: Re-add missing includes

Source/Android/jni/Input/ControlGroup.cpp, Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWidget.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
I was creating a controller config that would automatically detect my Controller or Wiimote and act accordingly but the Point and Point Passthrough sections didn't have the advanced config button as the checkboxes are created separate from the rest.
Accidentally nuked the repository closing previous pull request #13701
Cleaned commit history, fixed ptr issue and removed the failed build files I accidentally added per jordan-woyak's request
=> MappingWidget: Add Advanced Configuration Button to Point And Point Passthrough "Enable" boxes

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp, Source/Core/VideoBackends/Vulkan/CommandBufferManager.h, Source/Core/VideoBackends/Vulkan/VKGfx.cpp
This flag was introduced in #11262.
The usage was racey in that `m_last_present_failed` was not updated until after `m_last_present_done` was `Set()`.
Moving `m_last_present_done.Set()` to the end of `SubmitCommandBuffer` would be an easy enough fix, but the flag isn't even needed. We can just `WaitForWorkerThreadIdle`.
=> Vulkan: Eliminate m_last_present_done flag.

Data/Sys/GameSettings/SBLE5G.ini, Data/Sys/GameSettings/SBLP5G.ini
The bean menu in this game does not react when the analog control stick is moved perfectly to the right (0 degress). This happens when the analog stick is mapped to digital inputs.
Currently, Dolphin contains a hardcoded controller hack to work around this issue. With this patch, it should no longer be needed; see #13177.
=> GameSettings: add bean menu patch for A Boy and His Blob

Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/MMU.h
Simple refactor to remove a bool argument. The PR also simplifies the branching returns.
=> Core/PowerPC: Split 'IsRAMAddress' method into 'IsEffectiveRAMAddress' and 'IsPhysicalRAMAddress' methods

Source/Core/Common/CommonFuncs.cpp, Source/Core/Common/CommonFuncs.h, Source/Core/Core/HW/WiimoteReal/IOWin.cpp, Source/Core/Core/IOS/USB/Host.cpp
This is confirmed to fix the recently reported BSOD issues certain users experience.
=> Host: Implement a Windows-only implementation of `GetDeviceNameFromVIDPID`

Source/Core/DolphinQt/DolphinQt.vcxproj
Add a missing ClInclude line in DolphinQt.vcxproj for NonAutodismissibleMenu.h. Missing the ClInclude doesn't break compilation, but prevents various IntelliSense features in Visual Studio from working properly with the file.
=> DolphinQt: Add DolphinQt.vcxproj ClInclude line

Source/Core/Common/SymbolDB.cpp, Source/Core/Common/SymbolDB.h, Source/Core/Core/PowerPC/PPCSymbolDB.cpp, Source/Core/Core/PowerPC/PPCSymbolDB.h, Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp, Source/Core/DolphinQt/Debugger/CodeWidget.h, Source/Core/DolphinQt/Debugger/EditSymbolDialog.cpp, Source/Core/DolphinQt/Debugger/EditSymbolDialog.h, Source/Core/DolphinQt/DolphinQt.vcxproj
*Warning: backup your symbol map before testing* Could have saving issues.
Adds a new type of symbol called Note that is always displayed on top of other symbols.  The purpose is to mark individual lines or sections of code as something, such as a bookmark or an explanation of what it is.  For example, if you have a 300 line function and want to have the ability to quickly navigate to an instruction in the center, you would just put a note there.
Adds note search box as a tabbed option next to the symbols search box.
Adds new popup dialog for editing symbols and notes.
The custom note loading logic is important, as it lets you overlap multiple notes of different sizes. I wasn't sure if I should make it a part of the function map, so I kept it separate and much simpler than a function …
=> Debugger Add note-type symbols .

Source/Core/DolphinQt/Debugger/CodeWidget.cpp
If it isn't cleared, the old data will persist. Especially bad if a game without symbols is loaded, as it would never get cleared and would show the last valid calls/callers from the previous game.
=> CodeWidget: Clear calls/callers if no symbol exists.

Data/Sys/GameSettings/SMNP01.ini
It's been there since the very first public commit. And enabling it gives absolutely no difference in performance.
Plus the fact that it's only there for the PAL version, it's probably been forgotten.
=> GameINI: Remove NSMBW PAL speed hack

Source/Core/DolphinQt/MainWindow.cpp
Show an error message when attempting to play an input recording while RetroAchievements hardcore mode is active, instead of silently doing nothing.
=> MainWindow: Show hardcore mode error for recording playback

Source/Core/Common/SymbolDB.cpp, Source/Core/Common/SymbolDB.h, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/Boot/Boot.h, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/IOS/MIOS.cpp, Source/Core/Core/PowerPC/PPCSymbolDB.cpp, Source/Core/Core/PowerPC/PPCSymbolDB.h, Source/Core/DolphinQt/MenuBar.cpp
Fix a potential crash from emuthread and Qt accessing m_functions at the same time.
Guard against checking map file while it is being loaded by emuthread on boot.
Don't clear and reload a map on boot if the correct one is already loaded.
A few cleanups.
=> PPCSymbols: Restructure loading on boot and add a mutex to prevent crashes.

Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
Some Wii Numbers numerically are less than 15 digits. In such a case it should be left 0 padded to 16 digits as shown in the Wii Message Board.
KD sends the Wii Number as a 0 padded string rather than integer, meaning Wii numbers that are less than 16 digits may fail to register to Wii Mail or send mail.
=> IOS/KD: Pad Wii Numbers to 16 digits

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Fix two similar errors in the validation logic of MemoryWidget's hex input that caused some inputs to fail unnecessarily.
* When the `Hex` box was checked `0x` was added to the front of the input, but if the user also typed `0x` (or `-0x`) that would result in a double prefix that failed validation. This PR skips adding the prefix again in that case.
* When the `Hex Byte String` input type was selected, adding a `0x` prefix or having the `Hex` box checked (or both) would cause validation to fail. This happened because the validation regex doesn't allow for a `0x` prefix, which in turn is because the `QByteArray::fromHex` function which actually parses the input doesn't expect any prefix and would end up adding an extra `00` byte to the front of the output. When `Hex Byte String` is …
=> MemoryWidget: Fix hex input validation errors

Source/Core/Common/Contains.h
A small patch to use standard library implementations instead of ad hoc ones as requested by TODOs.
=> Common: Replace Contains and ContainsSubrange with C++23 std::ranges equivalents

Source/Core/VideoCommon/VideoBackendBase.cpp
Remove redundant reset of `g_presenter` in `ShutdownShared`, which is already reset earlier in the function.
=> VideoBackendBase: Remove redundant unique_ptr reset

Source/Core/AudioCommon/Mixer.cpp
It's a common misconception that constexpr on an array means that it is static. Really it just means that it can be used in a constexpr context. Other than that, its just a normal const array.
[godbolt link to show the asm before / after](https://godbolt.org/z/j69v1a67q).
=> AudioCommon/Mixer: make large array in Mixer::MixerFifo::Enqueue() static so that it's not created on the stack.

Source/Core/Common/IOFile.h
Require `IOFile::ReadArray` and `IOFile::WriteArray` to be called with a trivially copyable type. These functions call [`std::fread`](https://en.cppreference.com/w/cpp/io/c/fread.html) and [`std::fwrite`](https://en.cppreference.com/w/cpp/io/c/fwrite.html) respectively, which trigger undefined behavior when the objects are not trivially copyable.
=> IOFile: Require trivially copyable types

Source/Core/Core/HW/EXI/EXI_DeviceAGP.cpp
Fix creation of a `.sav` file in the current working directory on emulation shutdown when a GameCube device slot is set to `Advance Game Port` and the `GBA Cartridge Path` is empty.
Fixes https://bugs.dolphin-emu.org/issues/12975.
=> CEXIAgp: Don't create save file if path is empty

Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h, Source/UnitTests/Core/CoreTimingTest.cpp
When `CoreTimingManager::ScheduleEvent` was called from a non-CPU thread it would read `m_globals.global_timer` which is not thread-safe.
Non-CPU thread scheduled events aren't that frequent, but there are a few instances.
A notable one comes from `DSPManager::GenerateDSPInterruptFromDSPEmu`.
`m_ts_queue` now holds `Event`s with `cycles_into_future` time values and `global_timer` is added later, from the CPU thread in `MoveEvents`.
=> CoreTiming: Fix unsafe usage of m_globals.global_timer in ScheduleEvent from non-CPU thread.

Source/Core/Core/IOS/USB/Bluetooth/LibUSBBluetoothAdapter.cpp, Source/Core/Core/IOS/USB/Host.cpp, Source/Core/Core/LibusbUtils.cpp, Source/Core/Core/LibusbUtils.h
`libusb_get_string_descriptor_ascii` turns non-ascii characters to `'?'`.
I've added a `GetStringDescriptor` that properly converts the UTF-16 string to UTF-8.
=> LibusbUtils: Add GetStringDescriptor function.

Data/Sys/GameSettings/GMN.ini, Data/Sys/GameSettings/GTR.ini, Data/Sys/GameSettings/R22.ini, Data/Sys/GameSettings/R7X.ini, Data/Sys/GameSettings/S75.ini, Data/Sys/GameSettings/SCA.ini, Data/Sys/GameSettings/SDW.ini, Data/Sys/GameSettings/SK8.ini, Data/Sys/GameSettings/SKY.ini, Data/Sys/GameSettings/SSP.ini, Data/Sys/GameSettings/SVX.ini
Don't feel like splitting this in multiple PRs.
Mostly added comments to settings I added in the past.
But also:
- Remove obsolete settings for Lost in Shadow, Calling and FlingSmash (according to [this Discord post](https://discord.com/channels/521709831132807179/521710974827495435/1385341558618062951), can't test any of these games).
- Disable Dual Core for Monopoly Streets (causes crashes according to [the wiki page](https://wiki.dolphin-emu.org/index.php?title=Monopoly_Streets#Dual_Core_Crash), can't test).
- Enable `EFBAccessEnable` for Need for Speed: Nitro. This is only used during car painting, and has no performance impact anywhere else in the game.
- Set `EarlyXFBOutput` to false for Tetris Worlds and Monsters, Inc. Scream Arena. (Maybe other Radical Entertainment games are …
=> GameINI: Misc updates

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Fix a copy-paste error causing `MemoryWidget`'s splitter to load the wrong state data when creating the `MemoryWidget`.
For me this caused the side panel to be scrunched up every time I started Dolphin, but the exact effects probably depend on the state of your `MemoryWidget` and `CodeWidget`.
=> MemoryWidget: Fix splitter state restoration

.gitmodules
This removes the branch specification for submodules, which allows Git to use the commit checked-out. This recently came up with SDL3, which was checked out to a commit outside of the "SDL2" branch, and lead to some breakages.
I also made all submodules use shallow clones to lower disk usage, and made some URLs that didn't end in `.git` use `.git` for consistency sake.
This can be tested using `git submodule sync` for git to consider the changes made to `.gitmodules`, and then `git submodule deinit .` and `git submodule update --init --recursive` to test pulling the submodules.
=> .gitmodules: Various ameliorations

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Fix two bugs in the Memory tab that occurred when viewing a memory range starting shortly before `0xffffffff`.
Bug 1: When there was at least one visible memory address at or after `0x0` none of the values would be displayed even when some of the addresses were valid. This happened because the loop condition in `GetValues` immediately returned false since `m_address_range.first > m_address_range.second`, causing `m_values` to be empty. This in turn led every address to be considered `INVALID_MEMORY` in `UpdateColumns`.
Bug 2: When `m_address_range.second` was equal to `0xffffffff` `GetValues` would enter an infinite loop. This happened because `address` would overflow to 0 after printing the last value in the table, causing the loop condition `address <= m_address_range.second` to be true …
=> MemoryViewWidget: Fix updates at end of address space

Source/Core/Common/CMakeLists.txt, Source/Core/Common/CommonFuncs.cpp, Source/Core/Common/CommonFuncs.h, Source/Core/Common/WindowsDevice.cpp, Source/Core/Common/WindowsDevice.h, Source/Core/Core/HW/WiimoteReal/IOWin.cpp, Source/Core/Core/IOS/USB/Host.cpp, Source/Core/DolphinLib.props
Otherwise we include the notoriously finnicky and define-filled Windows headers in the entire codebase through CommonFuncs.h
(note: this was needed for me to compile on Windows with CMake, the tests would fail to compile otherwise)
=> Common: Move GetDeviceProperty() into its own header

Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp, Source/Core/VideoBackends/Vulkan/CommandBufferManager.h, Source/Core/VideoBackends/Vulkan/VKMain.cpp, Source/Core/VideoBackends/Vulkan/VKSwapChain.h
Fixes validation errors.
See https://docs.vulkan.org/guide/latest/swapchain_semaphore_reuse.html
The validation error that is fixed is:
```
45:10:838 VideoBackends/Vulkan/VulkanContext.cpp:860 E[Host GPU]: Vulkan debug message: vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] (VkSemaphore 0x1b0.000.000.01b) is being signaled by VkQueue 0x7f5.b68.8f8.170, but it may still be in use by VkSwapchainKHR 0x2b0.000.000.02b.
Here are the most recently acquired image indices: [0], 1.
(brackets mark the last use of VkSemaphore 0x1b0.000.000.01b in a presentation operation)
Swapchain image 0 was presented but was not re-acquired, so VkSemaphore 0x1b0.000.000.01b may still be in use and cannot be safely reused with image index 1.
Vulkan insight: One solution is to assign each image its own …
```
=> Vulkan: Fix present semaphores reuse

Source/Core/VideoBackends/Vulkan/VKPipeline.cpp, Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoCommon/BPFunctions.cpp, Source/Core/VideoCommon/VertexShaderManager.cpp, Source/Core/VideoCommon/VideoCommon.h, Source/Core/VideoCommon/VideoConfig.h
This PR uses the unrestricted depth range extension to natively support oversized depth ranges while still clamping the result to the `[0, 2^24)` range using `VK_EXT_depth_range_unrestricted` and `VK_EXT_depth_clamp_control`.
=> Vulkan: Add support for unrestricted depth range.

Source/Core/DolphinQt/Config/GameConfigWidget.cpp
The widgets in the `Properties`->`Game Config`->`General` tab currently have their titles appear by themselves in a `BalloonTip` and their descriptions appear in a separate standard tooltip.
Use `ToolTipWidget::SetDescription` insead of `QWidget::setTooltip` to put the description in the `BalloonTip` instead.
Before:
After:
=> GameConfigWidget: Unify tooltips

Source/Core/Core/LibusbUtils.cpp
Reported to fix: https://bugs.dolphin-emu.org/issues/13849
Might also fix: https://bugs.dolphin-emu.org/issues/12384
=> LibusbUtils: Change libusb_init failure from an ASSERT_MSG to an ERROR_LOG_FMT

Data/Sys/GameSettings/SP4.ini
Having ImmediateXFB enabled in _Pétanque Master_ causes the game to lag immensely and have seizure-inducing flickering visuals, so it is disabled by this PR.
=> GameINI: Disable ImmediateXFB for Pétanque Master

Source/Core/Core/PowerPC/PPCSymbolDB.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
I believe the expensive `FillInCallers` call in `CodeViewWidget::Update` is unnecessary. From what I can see callers will be recalculated in `UpdateFunctionCallers` in `CodeWidget` on demand.
This brings `CodeViewWidget::Update` from ~20ms per update to ~10ms on my machine, making scrolling with the mouse much snappier. Now if only Qt allowed aggregating scroll events...
=> CodeViewWidget: Improve Update performance

Source/Core/Core/HW/EXI/EXI_DeviceEthernet.h
`exi_status.interrupt` is read and written from the core thread, but also a worker thread function,`BuiltInBBAInterface::ReadThreadHandler` calls `CEXIETHERNET::RecvHandlePacket` to set a bit when data is received.
https://github.com/dolphin-emu/dolphin/blob/4d0cf1315e599bbeed67ef9eca993874869e3e85/Source/Core/Core/HW/EXI/EXI_DeviceEthernet.cpp#L637
I have only just begun to look at the EXI_DeviceEthernet code, and other parts are potentially questionable, but I think this addresses a particularly egregious case of thread unsafety.
I figure explicit memory orders can be specified in another PR.
=> HW/EXI_DeviceEthernet: Make interrupt state atomic.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.kt, Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/Core.h
When Android sends Dolphin to the background, emulation *must* pause, otherwise emulation continues running and continues outputting audio to the user. RetroAchievements mustn't be allowed to override it.
=> Android: Don't let RetroAchievements override onPause

Source/Core/DolphinQt/Settings.cpp
This PR only affects the Windows build.
External stylesheets now apply our dark palette based on the system "Dark" mode.
Previously, they would always use the light palette on launch (or the already loaded palette on style change).
Before:
After:
Things still look like "Before" if you use an external stylesheet intended for dark mode.. in light mode, but I think that's a less common situation.
=> DolphinQt: Fix Windows dark theme when using external stylesheets.

Source/Core/Common/Assembler/GekkoIRGen.cpp, Source/Core/Core/AchievementManager.cpp, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/IOS/USB/Emulated/Skylanders/SkylanderFigure.cpp, Source/Core/Core/IOS/USB/OH0/OH0.cpp, Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/PowerPC/Jit64Common/ConstantPool.cpp, Source/Core/Core/State.cpp, Source/Core/DolphinQt/GameList/GameTracker.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp, Source/Core/VideoCommon/ShaderCache.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp
Fix some common anti-patterns with these data structures.
- You can dereference the iterator returned by `find` to access the underlying value directly, without an extra `operator[]`/`at`.
- Rather than checking for an element before insertion/deletion, you can just do the operation and if needed check the return value to determine if the insertion/deletion succeeded.
=> Avoid map/set double lookups

Source/Core/VideoCommon/TextureCacheBase.cpp
Non-default anisotropy was always forcing linear filtering.
I broke this in #13368
Before:
After:
=> VideoCommon: Fix "Force Nearest" texture filter setting.

Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.h
This hack was introduced 11 years ago in https://github.com/dolphin-emu/dolphin/commit/9b20280bcff0b31b1deb4a5b3e6560ac853b40e7
They claimed some "programs" don't properly detect movement if the Nunchuk stick is pushed perfectly vertically or horizontally.
The old commit message said "it's expected by some emulated programs".
Which "programs"?
I find it somewhat hard to believe any legitimate game behaves in this manner.
It would be apparent on real hardware.
If it turns out these games actually exist, we can add the hack back with a proper comment mentioning the actual problem-game.
=> ControllerEmu: Remove nunchuk stick data hax.

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/DSP/DSPCore.cpp, Source/Core/Core/DSP/DSPHost.h, Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/HW/DSPLLE/DSPHost.cpp, Source/Core/Core/HW/DSPLLE/DSPLLE.cpp, Source/Core/Core/Host.h, Source/Core/Core/State.cpp, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Host.cpp, Source/Core/DolphinTool/ToolHeadlessPlatform.cpp, Source/DSPTool/DSPTool.cpp, Source/DSPTool/StubHost.cpp, Source/UnitTests/StubHost.cpp
Remove the functions `Host_UpdateMainFrame`, `Host_RefreshDSPDebuggerWindow`, and `DSP::Host::UpdateDebugger` because they don't do anything useful (or at all, in most cases).
=> Host: Remove unnecessary functions

Source/Core/AudioCommon/Mixer.cpp, Source/Core/AudioCommon/Mixer.h, Source/Core/AudioCommon/NullSoundStream.cpp
Fixes: https://bugs.dolphin-emu.org/issues/13848
=> AudioCommon/Mixer: Skip sample processing when NullSoundStream is being used.

Source/Core/AudioCommon/Mixer.cpp, Source/Core/AudioCommon/Mixer.h
Basically, dolphin would begin to fade audio immediately after looping, but typically dolphin would push new audio right after looping, so the fading would be premature. 
This basically forces dolphin to wait a little bit before fading out the audio. This lets dolphin fill in larger lag spikes more consistently. It's a minor change, but helps for lag in the 40%-50% speed area.
It also removes an atomic read that was happening on each sample, which might help slower devices. (I doubt it would make a huge difference) 
TLDR; This makes dolphin wait 40ms longer before fading out the volume, which gives the emulator enough time to push new audio, making it sound more consistent.
=> Fade audio after an entire loop

Source/Core/DolphinQt/Config/GameConfigEdit.cpp, Source/Core/DolphinQt/Config/GameConfigHighlighter.cpp, Source/Core/DolphinQt/Config/GameConfigHighlighter.h
This fixes an issue reported on Discord.
To reproduce:
Open the `Properties` for `Monster Hunter Tri`.
Use the `Gecko Codes` `Download Codes` button. (This will create a > 2MB ini file)
Navigate to the `Game Config` `Editor` tab.
The UI will hang.. I think indefinitely..?
`QSyntaxHighlighter` is causing this.. but I don't really know why.
Even just trying to set a format on every block (without regex) inside `highlightBlock` doesn't fix the hang.
This PR manually highlights blocks on `contentsChange`, which works around the issue.
=> DolphinQt: Make GameConfigHighlighter better handle large files.

Source/Core/Core/IOS/FS/HostBackend/FS.cpp
This is to prevent someone (me) from accidentally deleting their entire /tmp directory just by not initializing the config system correctly.
=> IOS/FS: add safety assert

Source/Core/Core/HW/VideoInterface.cpp, Source/Core/Core/HW/VideoInterface.h
Small fixup of #13046: changing the VBI Frequency slightly affected the aspect ratio due to rounding errors.
This PR fixes it by ignoring the setting when calculating the aspect ratio.
=> HW/VideoInterface: Don't affect aspect ratio with VBI Frequency Override

Source/Core/VideoBackends/D3D/DXTexture.cpp, Source/Core/VideoBackends/OGL/OGLTexture.cpp
This code path had probably never been used before. I'm not a GFX backend expert, but I think these changes are correct.
The DX11 bug throws an error saying wrong type. 
The GL bug corrupts/scrambles everything.
=> GFX: Fix bugs for AbstractStagingTextures that perform an Upload.

Source/Core/Core/PowerPC/MMU.cpp
This has been possible for a long time now (see https://dolphin-emu.org/blog/2016/09/06/booting-the-final-gc-game/#side-effects-of-a-hardcode-rewrite), but it seems like people still aren't aware of it.
(The easiest way to get this message to appear is to pause a game, then change r13 to a garbage value in the registers widget, since it's used as a pointer to the small data area and thus accessed frequently.)
=> Mention enable MMU in the DSI Exception message (Invalid read from ###/Invalid write to ###)

Source/Core/Core/AchievementManager.cpp
Previous changes to the patch allowlist format were not reflected in AchievementManager; this corrects that and re-enables patches and codes in hardcore mode.
=> Fixed Patch Allowlist Check

Source/Core/VideoCommon/PixelShaderGen.cpp
They appear to be unused since #13432.
=> VideoCommon: Remove unused EnumMaps from PixelShaderGen

Source/Core/Core/ActionReplay.cpp, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/Debugger/PPCDebugInterface.h, Source/Core/Core/PatchEngine.cpp
Previously, applying a patch while the game was running had no effect, since the icache wasn't invalidated.
This PR fixes it.
=> ActionReplay/PatchEngine: Make writes invalidate cache

Source/Core/Common/Timer.cpp, Source/Core/Common/Timer.h, Source/Core/Core/HW/CPU.cpp
Fixes: https://bugs.dolphin-emu.org/issues/13844
Linux and Windows are tested.
FreeBSD and macOS are untested, but documentation implies they will function appropriately.
=> Common/Timer: Add a SteadyAwakeClock class to make play time tracking ignore time while suspended.

Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GridProxyModel.cpp, Source/Core/DolphinQt/GameList/GridProxyModel.h
Since Grid View doesn't have a header for users to change sorting options with, use List View's sorting in Grid View too.
Resolves https://bugs.dolphin-emu.org/issues/12958.
=> GameList: Use List View's sorting for Grid View

Source/Core/Common/MathUtil.h, Source/UnitTests/Common/MathUtilTest.cpp
Using `std::cmp_less` and `std::cmp_greater` handle the mismatched signedness logic for us.
Explicit `static_cast<T>` in the floating point path eliminated a warning produced in `MathUtilTest`:
```
MathUtil.h:68:17: warning: implicit conversion from 'const int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-const-int-float-conversion]
```
Using `>=` instead of `>` fixed a floating point edge case that Dentomologist identified.
=> MathUtil: Simplify SaturatingCast implementation and fix edge case.

Source/Core/VideoBackends/Software/Rasterizer.cpp
The old code was added in 45024133e2aae56846bd19c3a584bac84044e467.
=> VideoSW: fix clamping after vertex color interpolation

Source/Core/Core/ActionReplay.cpp, Source/Core/Core/ActionReplay.h, Source/Core/Core/GeckoCode.cpp, Source/Core/Core/GeckoCode.h, Source/Core/Core/PatchEngine.cpp
Informing the user never hurts.
The count for AR and Gecko codes is intentionally combined. <sub><sup>In the future, I'd like to merge their tabs in the UI as well...</sup></sub>
=> PatchEngine: OSD message showing number of enabled patches and cheats

Source/Core/DolphinQt/Styles/Dark/dark.qss
Honestly this is just making it consistent with the rest of the style and fixing the text alignment. I also made the green a bit darker so that the percentage remains readable.
---
Old:
New:
=> DolphinQt/Styles/Dark: Adjust progress bar

Source/Core/Core/AchievementManager.cpp
Avoid creating and then destroying a leaderboard list when `AchievementManager::m_client->game` is null, as doing so causes a crash due to reading uninitialized memory caused by a bug in rcheevos.
This can be triggered by starting a game with an invalid or expired login token.
See https://github.com/RetroAchievements/rcheevos/pull/458 for details.
Fixes https://bugs.dolphin-emu.org/issues/13880.
=> RetroAchievements: Avoid crash due to uninitialized memory read

Source/Core/Common/Arm64Emitter.cpp
The instruction implementations that were shifting the size by 4 would emit an incorrect instruction when given a size of 64. The correct implementation is to count the number of leading or trailing zeroes in the size parameter, which is what IntLog2 does.
No callers are affected by this, as they all use sizes other than 64. Actually, some of these instructions are even invalid with a size of 64, but I'm changing them anyway for consistency with the others.
=> Arm64Emitter: Replace shifting size by 4 with IntLog2 minus 3

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/DocumentProvider.kt
Adds `DocumentsContract.Root.FLAG_LOCAL_ONLY` to the list of the flags in order to show up for third-party apps for easier file syncing with local/cloud file server providers
=> Android: Set Dolphin documents as Local only

Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.h
Show "(off)" instead of "" when the default post-processing effect is selected. This also indirectly fixes issues with keyboard navigation of the post-processing effect combobox when the default is selected, resolving https://bugs.dolphin-emu.org/issues/13863.
m_post_processing_effect was previously using the ConfigStringChoice constructor that assumes the text and data of each option are identical. This is true for all the other effects, but since "(off)" has the config value of "" this assumption was failing for it, causing the combobox to be blank.
The first commit is a refactoring commit that mostly removes some unnecessary abbreviation that's bugged me whenever I've run across it.
=> EnhancementsWidget: Fix selection of disabled postprocessing option

Source/Core/Core/Debugger/BranchWatch.cpp, Source/Core/Core/Debugger/BranchWatch.h
IsolateWasOverwritten and IsolateNotOverwritten share the same basic logic and have almost exactly the same code, with the only difference being the comparison function used to keep or discard branches. To avoid unnecessary code duplication and ensure that the functions stay in sync after any future changes, create a helper function that takes the comparison function as a parameter and have IsolateWasOverwritten and IsolateNotOverwritten call that helper.
=> BranchWatch: Extract shared function logic

Data/Sys/GameSettings/R4QE01.ini, Data/Sys/GameSettings/R4QJ01.ini, Data/Sys/GameSettings/R4QK01.ini, Data/Sys/GameSettings/R4QP01r1.ini, Data/Sys/GameSettings/R4QP01r2.ini
A request from the Mario Strikers community, they wanted this cheat added that allows the game to be more accessible with a traditional controller (by disabling Captain Mega Strikes)
=> Data: add gecko code for Mario Strikers Charged that allows disabling captain mega strikes

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp, Source/Core/DolphinQt/Achievements/AchievementsWindow.h, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h
The callback mechanism AchievementManager had until now only supported one caller registering a callback, and it didn't have any synchronization. This isn't a problem for DolphinQt, but the PR to add Android support for RetroAchievements exposes these problems. Let's replace it with HookableEvent, which can handle all of this.
=> AchievementManager: Use HookableEvent instead of std::function callbacks

Source/Core/Common/Matrix.cpp, Source/Core/Common/Matrix.h
Used in my model skinning replacement logic.  Forget where I pulled the equation from.
=> Core: support inverting a 4x4 matrix

Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
PR #13387 causes the emulator to race through to the next presentation which can cause written Wii remote reports to have improper timing.
With this PR, writes are now performed at the proper times on a thread separate from reads.
I've done some minor code clean up, but WiimoteReal is really in need of a big overhaul.
Theoretically this would improve speaker data.
In practice it doesn't seem to help much.
This should at least eliminate any regressions introduced by #13387 (if they were even noticeable).
=> WiimoteReal: Send reports with proper timing for theoretically better speaker data.

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.h, Source/Core/VideoCommon/OnScreenUI.cpp, Source/Core/VideoCommon/PerformanceMetrics.cpp
Spinbox added to Settings -> Interface. imgui windows needed a fixup to work with changing sizes.
The default font is blocky when upscaled. We can add another PR to change the default font after.
The graph numbers are hard-set to 14 size because it looks really bad if they get bigger than about 16. Any windows that want a constant font can use PushFont(NULL, size); then PopFont();
=> Qt/Imgui: Add SpinBox to adjust imgui font size.

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/Core/ActionReplay.cpp, Source/Core/Core/GeckoCode.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp
When RetroAchievements Hardcore mode is enabled, show an icon for each code in ARCodeWidget and GeckoCodeWidget indicating whether it's an approved code or not.
Hardcore enabled:
Hardcore disabled (unchanged from master):
=> CodeWidgets: Show code approval in Hardcore mode

Source/Core/DolphinQt/Config/ToolTipControls/BalloonTip.cpp, Source/Core/DolphinQt/Config/ToolTipControls/BalloonTip.h, Source/Core/DolphinQt/Config/ToolTipControls/ToolTipWidget.h
On master, putting the cursor in the part of a ToolTipWidget where the arrow would be prevents the BalloonTip from showing up (or flickering for a moment and immediately closing). This happens because once the cursor is over the BalloonTip it's no longer in the ToolTipWidget, triggering the latter's leaveEvent which closes the balloon.
In this PR, when that happens the BalloonTip tracks the cursor until it either leaves the ToolTipWidget's bounding box or leaves the BalloonTip and goes back to the ToolTipWidget, then respectively closes the BalloonTip or leaves it open.
=> BalloonTip: Don't hide when the BalloonTip blocks the cursor

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/DolphinApplication.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/GCAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/WiimoteAdapter.java, Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, Source/Core/InputCommon/GCAdapter.cpp
We can register a BroadcastReceiver to have Android tell us when a GC adapter gets connected or disconnected instead of having a loop where we continuously call `SleepCurrentThread(1000)` and poll the current status. When waiting for a GC adapter to connect, this both reduces power usage and improves responsiveness. Additionally, we can get rid of the `Reset` call from the read thread, making PR #13203 unnecessary.
=> Android: Detect GCAdapter hotplug using BroadcastReceiver

Source/Core/DolphinQt/Settings/GeneralPane.cpp, Source/Core/DolphinQt/Settings/GeneralPane.h
When Hardcore Mode is active, clarify in the Speed Limit tooltip that values less than 100% won't slow emulation.
=> GeneralPane: Add Hardcore Mode tooltip clarifications

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Fix a regression from d1ba84987 that caused freezes or graphical/audio glitches in various games.
Examples:
`Super Mario Galaxy 2` and `Super Mario Sunshine` freeze on startup with accompanying audio glitches.
`IKARUGA` has a bunch of graphical static-squares in the intro Atari sequence.
`Super Mario Galaxy` has an audio glitch on startup.
=> Jit64: Fix dcbz regression

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Multiple users have reported hangs on shutdown when having an 8BitDo Ultimate 2 controller connected.
I cannot reproduce this issue but the testing of one user makes it seem like this is a promising workaround for it.
https://bugs.dolphin-emu.org/issues/13866
We have our own DirectInput backend and few game controllers require it these days anyways.
If a true fix is found we can revert this.
Users that "need" SDL DirectInput handling in the interim can manually set an environment variable: `SDL_JOYSTICK_DIRECTINPUT=1`
=> SDL: Disable DirectInput handling to work around hangs on shutdown.

Source/Core/Common/x64Emitter.cpp, Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Reverts #13985 (itself a partial revert of #13929) with the AVX path properly fixed.
Sorry for not catching it... (it was moving YMM8 instead of YMM0)
Tested the Pikmin games.
=> dcbz: Fix AVX path

Source/Core/DolphinQt/Settings/PathPane.cpp, Source/Core/DolphinQt/Settings/WiiPane.cpp, Source/Core/UICommon/UICommon.cpp
When opening a file dialog to set the location of a custom path, use the corresponding user path as the starting location instead of the current custom path.
When no custom path was set the dialog would previously be opened with a blank path. This causes Windows (not sure about other platforms) to open the dialog at the same location where the last dialog was closed, or at the current working directory if no previous dialog had been opened.
If a nonempty custom path has been set then it has also set the corresponding user path, so the behavior in that case is unchanged.
This also creates `D_WFSROOT_IDX` in `UICommon::CreateDirectories` so that there's a folder to go to when opening that dialog.
=> Settings: Open file dialogs at user path instead of custom path

Source/Core/Common/CMakeLists.txt, Source/Core/Common/CommonFuncs.cpp, Source/Core/Common/CommonFuncs.h, Source/Core/Common/Network.cpp, Source/Core/Common/Network.h, Source/Core/Common/UnixUtil.h, Source/Core/Core/HW/WiimoteReal/IOLinux.cpp, Source/Core/Core/HW/WiimoteReal/IOLinux.h, Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
This improves WiimoteReal (the `Emulate the Wii's Bluetooth adapter` and `Connect Wii Remotes for Emulated Controllers` paths) mainly on Linux.
Increased the inquiry length parameter to 3.84 seconds.
It was previously 1.28s on Linux (and still 2.56s on Windows).
It's now the value that Wii games use and it seems to be much more reliable on Linux.
Majorly cleaned up and fixed bugs in the WiimoteReal/IOLinux code.
Fixed the issue where a Wii remote could not be reconnected after being disconnected.
`WiimoteLinux::IORead` failed to account for `poll` returning signals on the interrupt socket.
https://bugs.dolphin-emu.org/issues/13615
Bluetooth adapters can now be unplugged/replugged while Dolphin is running.
It previously would fail forever if an adapter was unplugged at any point.
Increased …
=> WiimoteReal/IOLinux: Improvements, fixes, and code cleanups.

Source/Core/DolphinQt/CheatSearchWidget.cpp, Source/Core/DolphinQt/CheatSearchWidget.h
I'm pulling this out of #12342 to make it a bit easier to review.
* Add function `GetTableRowCount`.
* Add some const.
* Rename `m_session` to `m_last_value_session`. This makes the name a bit more precise now, and will be necessary to distinguish it from `m_current_value_session` in #12342.
=> CheatSearchWidget: Minor refactoring
