dolphin-emu/dolphin

Source/Core/Common/Logging/LogManager.h
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/OGL/Render.h

This did give a decent slowdown on some drivers.

OGL: disable driver warnings fetch

---

Source/Core/DolphinWX/ISOProperties.cpp

Date given by Dolphin did not match up with build dates found from tcrf.net

Change Build Date to Apploader Date

---

Data/Sys/GameSettings/G6ME69.ini
Data/Sys/GameSettings/G6MP69.ini
Data/Sys/GameSettings/GFGEA4.ini
Data/Sys/GameSettings/GKGE01.ini
Data/Sys/GameSettings/GNQE69.ini
Data/Sys/GameSettings/GNZE69.ini
Data/Sys/GameSettings/GNZP69.ini
Data/Sys/GameSettings/GSMD52.ini
Data/Sys/GameSettings/GSME52.ini
Data/Sys/GameSettings/GSMF52.ini
Data/Sys/GameSettings/GSMP52.ini
Data/Sys/GameSettings/GSWD64.ini
Data/Sys/GameSettings/GSWE64.ini
Data/Sys/GameSettings/GSWF64.ini
Data/Sys/GameSettings/GSWI64.ini
Data/Sys/GameSettings/GSWJ64.ini
Data/Sys/GameSettings/GSWP64.ini
Data/Sys/GameSettings/GSWS64.ini
Data/Sys/GameSettings/R44J8P.ini
Data/Sys/GameSettings/RNHP99.ini
Data/Sys/GameSettings/RSBE01.ini
Data/Sys/GameSettings/RSBJ01.ini
Data/Sys/GameSettings/RSBK01.ini
Data/Sys/GameSettings/RSBP01.ini
Data/Sys/GameSettings/RSND69.ini
Data/Sys/GameSettings/RSNE69.ini
Data/Sys/GameSettings/RSNF69.ini
Data/Sys/GameSettings/RSNP69.ini
Data/Sys/GameSettings/RSNX69.ini

Update/addition of  Madden NFL 06 (gc), Frogger Beyond (gc), DONKEY
KONGA (gc), Madden NFL 2005 (gc), NBA STREET Vol.2 (gc), Spider-Man
(gc), Star Wars: Rogue Leader (gc), NO MORE HEROES (wii), Super Smash
Bros. Brawl (wii), The Simpsons Game (wii), Suzumiya Haruhi no Heiretsu
(wii).
Fixes issues 7978, 7894, 7883.

Gameini updates.

---

Source/Core/Core/ConfigManager.cpp

Changed default freelook hotkey to match description

---

Source/Core/Core/HW/SI_DeviceDanceMat.cpp
Source/Core/Core/HW/SI_DeviceDanceMat.h
Source/Core/Core/HW/SI_DeviceGCController.cpp
Source/Core/Core/HW/SI_DeviceGCController.h
Source/Core/Core/HW/SI_DeviceGCSteeringWheel.cpp
Source/Core/Core/HW/SI_DeviceGCSteeringWheel.h

Directional constant Force Feedback (in the steering wheel) tested and works fine.

Fixed the GC Steering Wheel and Dance Mat identification.

---

Source/Core/DiscIO/Volume.h
Source/Core/DiscIO/VolumeCommon.cpp
Source/Core/DolphinQt/GameList/GameFile.cpp

I also slightly modified the CACHE_REVISION warnings for consistency.

Added CACHE_REVISION warnings

---

Source/Core/VideoBackends/D3D/Render.cpp
Source/Core/VideoBackends/D3D/TextureCache.cpp
Source/Core/VideoBackends/D3D/TextureCache.h
Source/Core/VideoBackends/D3D/main.cpp
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/OGL/TextureCache.cpp
Source/Core/VideoBackends/OGL/TextureCache.h
Source/Core/VideoBackends/OGL/main.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h
Source/Core/VideoCommon/VertexManagerBase.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

This PR tries to pick some patches of #384 which are only cleanup. So this PR should have no impact on neither performance nor compatibility.

Texcache cleanup 2

---

Source/Core/Common/x64Emitter.cpp
Source/Core/Common/x64Emitter.h
Source/Core/Core/PowerPC/JitCommon/Jit_Util.cpp
Source/Core/Core/PowerPC/JitCommon/Jit_Util.h
Source/Core/VideoBackends/D3D/VertexManager.cpp
Source/Core/VideoCommon/CMakeLists.txt
Source/Core/VideoCommon/CPMemory.h
Source/Core/VideoCommon/DataReader.h
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/VertexLoader.cpp
Source/Core/VideoCommon/VertexLoader.h
Source/Core/VideoCommon/VertexLoaderBase.cpp
Source/Core/VideoCommon/VertexLoaderBase.h
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexLoaderX64.cpp
Source/Core/VideoCommon/VertexLoaderX64.h
Source/Core/VideoCommon/VertexLoader_Color.cpp
Source/Core/VideoCommon/VertexLoader_Normal.cpp
Source/Core/VideoCommon/VertexLoader_Position.cpp
Source/Core/VideoCommon/VertexLoader_TextCoord.cpp
Source/Core/VideoCommon/VideoCommon.vcxproj
Source/Core/VideoCommon/VideoCommon.vcxproj.filters
Source/UnitTests/Common/x64EmitterTest.cpp

~~The last commit should be dropped before this is merged.~~

VertexLoader: rewrite x64 JIT

---

Source/Core/VideoBackends/OGL/GLExtensions/GLExtensions.cpp
Source/Core/VideoBackends/OGL/Render.cpp

This adds support for OES_draw_elements_base_vertex and EXT_buffer_storage.

Add support for two new OpenGL ES extensions.

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

These were fairly simple to implement.

[AArch64] Implement mfspr/mtspr XER routines.

---

Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp

Rebased version of #1540 by @konpie

Fixed the emulated wiimote speaker's ADPCM sample rate.  Patch by hk.konpie

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h

Basically stolen from the x86 recompiler. Works well on AArch64 as well!

[AArch64] Implement TU/TL merging.

---

Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.h

These had some minor errors in them that I discovered with the hardware test and Viewtiful Joe.
All work as they should now.

[AArch64] Fix all of the paired store instructions.

---

Source/Core/Core/Movie.cpp
Source/Core/DolphinWX/VideoConfigDiag.cpp
Source/Core/DolphinWX/VideoConfigDiag.h
Source/Core/VideoBackends/D3D/TextureCache.cpp
Source/Core/VideoBackends/OGL/TextureCache.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

degasus killed it; this is just the funeral.  (I would suggest appending "?w=1" to the GitHub URL if you want to review this.)

Remove EFB to RAM cache, and simplify code.

---

Source/Core/DolphinWX/InputConfigDiag.cpp

Fixes slight sizing issues on high DPI displays.

InputConfigDiag: Fit buttons to their text

---

Source/Core/Core/Core.cpp
Source/Core/Core/HW/GCKeyboard.cpp
Source/Core/Core/HW/GCPad.cpp
Source/Core/Core/HW/Wiimote.cpp
Source/Core/Core/HotkeyManager.cpp
Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/Frame.h

Stability fixes for the pad configurable hotkeys.
Windows test build: http://dl.dolphin-emu.org/prs/pr-2010-dolphin-latest-x64.7z

Hotkey fixes

---

Source/Core/DolphinWX/FrameTools.cpp

Both forms are used, but one word is more common.

Web Site -> Website

---

Source/Core/DolphinWX/FrameTools.cpp

Text change after seeing confusion in https://code.google.com/p/dolphin-emu/issues/detail?id=8007

Reword "Boot from DVD Drive" -> "DVD Backup" menu option

---

Source/Core/Core/BootManager.cpp
Source/Core/Core/CoreParameter.cpp
Source/Core/Core/CoreParameter.h
Source/Core/DolphinWX/ISOProperties.cpp
Source/Core/DolphinWX/ISOProperties.h

It isn't hooked up to anything anymore, and it isn't the sort of thing we
want users messing with anyway.

Remove setting "BlockMerging".

---

Source/Core/DolphinWX/VideoConfigDiag.cpp

All of the other descriptions for drop-down menus use select.

Change Wording

---

Tools/perf-disassemble.sh

Tools: add disassemble script for perf

---

Source/Core/Core/PowerPC/Jit64/JitAsm.cpp

Fixes a regression from #1856's ac54c6a.

Jit64: turn short jmp into near jmp

---

Source/Core/DolphinWX/Main.cpp

This has been driving me nuts!

DolphinWX: fix -e parameter

---

Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DiscIO/VolumeWad.h
Source/Core/DolphinQt/GameList/GameFile.cpp
Source/Core/DolphinWX/ISOFile.cpp

Thanks to JosJuice for helping me with this.

VolumeWad: Return version number for WADs

---

Source/Core/DiscIO/CompressedBlob.cpp

This should fix issue [#8206] (https://code.google.com/p/dolphin-emu/issues/detail?id=8206).
-[Unknown]

DiscIO: On decompress to file, write last blocks correctly

---

Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp
Source/Core/Core/PowerPC/Jit64IL/JitIL.cpp
Source/Core/Core/PowerPC/Jit64IL/JitIL.h
Source/Core/Core/PowerPC/Jit64IL/JitIL_Tables.cpp
Source/Core/Core/PowerPC/JitArm32/Jit.cpp
Source/Core/Core/PowerPC/JitArm32/Jit.h
Source/Core/Core/PowerPC/JitArm32/JitArm_Tables.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Source/Core/Core/PowerPC/JitILCommon/JitILBase.h
Source/Core/Core/PowerPC/PPCAnalyst.cpp

This should more reliably show an error message for illegal
instructions.

Improve illegal instruction handling.

---

Source/Core/Core/PowerPC/JitArm32/JitAsm.cpp

Credits to Sonicadvance.
Don't worry about historic, i'm going to fix that.
That's fix weird textures on many games(Fire Emblem, Digimon Rumble Arena 2, Tony Hawk Pro Skater 4, etc)

[ARMv7] Fix unsigned/signed stores 

---

Source/Core/Core/PowerPC/PPCTables.h

Should make it easier for newcomers to get up to speed.
Based off of what @Sonicadvance1 told me in IRC.

PowerPC: Document the instruction table flags

---

Source/Core/Core/PowerPC/PPCTables.h

Corrects some slight mistakes pointed out by @FioraAeterna

PPCTables: Correct some flag descriptions

---

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp

Doesn't fix any known issue at the moment, but I ran into this bug with
dynamic-bat.

Fix registersInUse in Jit64::lmw.

---

Source/Core/DolphinWX/ConfigMain.cpp

~~Todo: Add tooltips for Idle Skipping and Pal60~~
Should be about ready to go.

Added more settings tooltips

---

Source/Core/AudioCommon/Mixer.cpp
Source/Core/AudioCommon/Mixer.h

Reverts dolphin-emu/dolphin#1629
Broken audio: https://code.google.com/p/dolphin-emu/issues/detail?id=8266
Performance regression: https://forums.dolphin-emu.org/Thread-unofficial-ishiiruka-dolphin-custom-version?pid=361657#pid361657
And dithering issues: https://github.com/dolphin-emu/dolphin/pull/2108

Revert "High quality resampler"

---

Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp

This previously shifted off-by-one

Interpreter: Fix Helper_UpdateCR1

---

Source/Core/Core/PowerPC/JitArm32/JitArm_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm32/JitArm_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitCommon/Jit_Util.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/PowerPC.h

The implementation of IsOptimizableGatherPipeWrite is extremely simple
now, but it will get a bit more complicated with dynamic-bat.

Refactor gather-pipe address checking.

---

Source/Core/Core/Boot/Boot.cpp

Fixes a crash launching F-Zero GX.

Hack around our terrible GC BIOS emulation.

---

Source/Android/src/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Core/Common/FileUtil.cpp
Source/Core/DolphinQt/Main.cpp
Source/Core/DolphinWX/Main.cpp
Source/Core/DolphinWX/MainAndroid.cpp
Source/Core/DolphinWX/MainNoGUI.cpp
Source/Core/UICommon/UICommon.cpp
Source/Core/UICommon/UICommon.h

The UI should decide on where it wants the user directory, not our core system.
This is in anticipation of some upcoming work on Android which will need proper user directory setting.

Move user directory detection location to UICommon.

---

Source/Core/Core/CoreParameter.cpp
Source/Core/Core/CoreParameter.h
Source/Core/DolphinWX/ISOProperties.cpp
Source/Core/DolphinWX/ISOProperties.h

https://code.google.com/p/dolphin-emu/issues/detail?id=8259

ISOProperties: Allow opening region-free INIs with "Show Defaults" button

---

Source/Core/Core/HotkeyManager.cpp
Source/Core/InputCommon/ControllerInterface/ExpressionParser.cpp

* Make the keybindings work when one key of the expression is not available;
* Fix default hotkey bindings for Linux ;
* Avoid conflict with global shortcuts.

Fix hotkeys for Linux

---

Data/Sys/GameSettings/DD2P41.ini
Data/Sys/GameSettings/GQN.ini
Data/Sys/GameSettings/RKM.ini
Data/Sys/GameSettings/ROD.ini
Data/Sys/GameSettings/RQW.ini
Data/Sys/GameSettings/S2E.ini
Data/Sys/GameSettings/SD2.ini
Data/Sys/GameSettings/SD2J01.ini
Data/Sys/GameSettings/SE3.ini
Data/Sys/GameSettings/SJD.ini
Data/Sys/GameSettings/SJDJ01.ini
Data/Sys/GameSettings/SJO.ini
Data/Sys/GameSettings/SJX.ini
Data/Sys/GameSettings/SMO.ini
Data/Sys/GameSettings/SVT.ini

Well, I own some games that doesn't have INIs in Dolphin and a bunch of them already have INIs but they're very outdated. This Pull Request tries to address that...

Missing Game INIs & minor updates

---

Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp

Attempt at fixing issue [6951](https://code.google.com/p/dolphin-emu/issues/detail?id=6951).

ProgramShaderCache: Do plenty of error checking before writing shaders to the disk.

---

Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStorePaired.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp
Source/Core/Core/PowerPC/PPCAnalyst.cpp
Source/Core/Core/PowerPC/PPCTables.h

An attempt at cleaning up the instruction table a little/making it more correct.

Interpreter: Flag cleanups/fixes.

---

Source/Core/Core/PowerPC/Jit64IL/JitIL_Tables.cpp
Source/Core/Core/PowerPC/JitILCommon/JitILBase.h
Source/Core/Core/PowerPC/JitILCommon/JitILBase_LoadStore.cpp
Source/Core/Core/PowerPC/JitILCommon/JitILBase_LoadStoreFloating.cpp

I've added lhau, lhaux, lfsu, and lfdu. Also, because stfd already implements stfdu, I updated the table to reflect this.

Add various loads and stores to JitIL

---

Source/Core/Common/GekkoDisassembler.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.h
Source/Core/Core/PowerPC/Interpreter/Interpreter_Branch.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp
Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp
Source/Core/Core/PowerPC/Jit64IL/JitIL_Tables.cpp
Source/Core/Core/PowerPC/JitArm32/JitArm_Tables.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp

These are illegal opcodes, and should be treated as such.

Remove remnants of old fake opcodes.

---

Source/Core/Core/PowerPC/JitCommon/JitBackpatch.cpp
Source/Core/VideoBackends/OGL/GLInterface/GLX.h
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/UnitTests/Core/MMIOTest.cpp

Fix warnings

---

Source/Core/Core/HW/DSPLLE/DSPLLE.cpp

Fixed dsp lle thread never starting because of dspjit initialization happening after the dsp thread check.

Fixed dsp lle thread never starting

---

Source/Core/DolphinWX/InputConfigDiag.cpp

Remove TM character which breaks our buildbot

---

Source/Core/Core/HW/DVDInterface.cpp

Fix terrible Speed Up Disc Transfer Rate mistake

---

Source/Core/VideoBackends/D3D/D3D.vcxproj

This hasn't been necessary for ages

D3D: Remove dependency on wxWidgets

---

Source/Core/Core/Core.cpp
Source/Core/Core/Core.h
Source/Core/Core/CoreTiming.cpp
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/Main.cpp
Source/Core/DolphinWX/MainNoGUI.cpp

Re-enable the asserts disabled by #2038, and fix the issue that necessitated disabling them - the fix is rather simple, but it exposed a race condition which I fixed as well.

Fix threading issues

---

Source/Core/Core/HW/GCKeyboard.cpp
Source/Core/Core/HW/GCPad.cpp
Source/Core/Core/HW/Wiimote.cpp
Source/Core/DolphinWX/InputConfigDiag.cpp
Source/Core/DolphinWX/InputConfigDiagBitmaps.cpp
Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Source/Core/InputCommon/ControllerInterface/ControllerInterface.h
Source/Core/InputCommon/InputConfig.h

No longer needed after 780eef6.
Might make things a bit faster.

Cleaned up the controller locking mechanism

---

Source/Core/DolphinWX/FrameTools.cpp

FrameTools: Use AppendRadioItem for constructing the frameskip menu

---

Source/Core/VideoCommon/VertexLoaderX64.cpp

Fix code broken by merge

---

Source/Core/DolphinWX/ISOProperties.cpp

I broke it for individual files but not folders in 4.0-6016.

Fix extracting files from Wii discs

---

Source/Core/DolphinWX/ISOProperties.cpp
Source/Core/DolphinWX/ISOProperties.h

Fixes https://code.google.com/p/dolphin-emu/issues/detail?id=8494

ISOProperties: Correctly handle partitions with 0 files

---

Source/Core/DolphinWX/AboutDolphin.cpp

DolphinWX: Fix branch information display in the about dialog.

---

Source/Core/DolphinWX/AboutDolphin.cpp

Change about page branch info to wxStaticText

---

Source/Core/VideoCommon/PixelEngine.cpp

Current link throws a "Page Not Found" error. 
This PR fixes the issue.

Fix dead link

---

.gitignore

Would make my life a lot easier :)

Ignore vim swapfiles

---

Readme.md

Mostly so a year from now I don't forget how to do it again.

Add Android build instructions to Readme.md.

---

Readme.md

Having the <> in the column names makes them invisible.

Fix the ABI/toolchain table in Readme.md.

---

Source/Core/Core/HW/CPU.cpp

Reverts pull request #2362, fixes issue 8542.

---

Source/Core/Core/HW/GCMemcardDirectory.cpp
Source/Core/Core/HW/GCMemcardDirectory.h

Needs testing on Mac/linux, and with a larger number of games than I have time for.

GCI folder: flush 1 second after last block is written

---

Source/Core/DolphinWX/VideoConfigDiag.cpp

Explicit wxGetTranslation usage isn't necessary

VideoConfigDiag: Simplify string translation handling

---

Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp

Fix build without UPnP

---

Source/Core/DolphinWX/HotkeyDlg.cpp

Previously no keypresses would be recognized during the button press phase.

HotkeyDlg: Fix keypress event binding

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

Causes flickering in games ever since PR #2172.
No idea why

[AArch64] Disable psq_l.

---

Source/Core/VideoCommon/PixelShaderGen.cpp

The zfreeze option freezes the depth plane of the rasterization.
So this is done before the TEV stages, where the z-textures are applied.

PixelShaderGen: apply zfreeze before ztextures

---

Source/Core/Common/x64CPUDetect.cpp

On non-Windows platforms, ECX was not being initialized to 0.
Also cleaned up a bit. Only tested on Linux.

x64CPUDetect: fix AVX2/BMI1/BMI2/HTT detection

---

Source/Core/Core/DSP/DSPCaptureLogger.h

DSPCaptureLogger: Add virtual destructor

---

Readme.md

Adds some documentation for Wii Networking Files that were added to the emulator since this was written.

Add documentation for Wii network files

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/DolphinWX/MainAndroid.cpp

Add an interface for enabling block profiling and writing the results out to file.

[Android] Block profiling JNI interface

---

Source/Core/Common/FifoQueue.h

Unit tests still pass successfully

FifoQueue: Use atomics instead of volatile members

---

Data/Sys/GameSettings/G2R.ini
Data/Sys/GameSettings/GDD.ini
Data/Sys/GameSettings/GFO.ini
Data/Sys/GameSettings/GHR.ini
Data/Sys/GameSettings/R6Q.ini
Data/Sys/GameSettings/RLS.ini
Data/Sys/GameSettings/RTU.ini
Data/Sys/GameSettings/RZF.ini
Data/Sys/GameSettings/RZY.ini

Gameinis are added/updated for:
Shrek SuperSlam, Disney's Donald Duck Goin' Quackers, The Fairly
OddParents: Shadow Showdown, Hot Wheels World Race, MySims Agents, Punch
Out, Alien Syndrome, My Word Coach, Secret Files Tunguska and Secret
Files 2 Puritas Cordis.

Gameini updates

---

Source/Core/DolphinWX/GameListCtrl.cpp

Fixes issue 5799
https://code.google.com/p/dolphin-emu/issues/detail?id=5799

Append Disc 2 to Titles for Multi-Disc Games

---

Source/Core/DolphinWX/Config/InterfaceConfigPane.cpp
Source/Core/DolphinWX/Config/InterfaceConfigPane.h

This button is dead since PR #2234

DolphinWX: Drop dead hotkey button.

---

Source/Core/DiscIO/Volume.h
Source/Core/DiscIO/VolumeCommon.cpp

I forgot it when I added the method.

Volume: Mark ReadWiiNames parameter as const

---

Source/Core/Common/Logging/LogManager.cpp

https://code.google.com/p/dolphin-emu/issues/detail?id=7959
@JMC47 Please test this and check that the three different types of logging are applied correctly.

Honor logging settings at startup

---

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp

BLENDVPD uses XMM0 as an implicit mask and I'd like to use it for #2381. This is a separate PR because #2496 depends on it.

Jit64: swap XMM registers for later optimization

---

Source/Core/Core/ConfigManager.cpp
Source/Core/Core/HotkeyManager.cpp
Source/Core/DolphinWX/Frame.cpp

Fixes the double pressed buttons (eg fullscreen is broken)
Uses the new hotkey framework by default.

Hotkeys fixes 2

---

Source/Core/VideoCommon/HiresTextures.cpp

This is why I should wait for people to review, even if I get annoyed
that nobody seems to care. :duncecap:

Undo accidental screwup of some HiresTextures code from project-moration

---

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp

This reverts commit 794a311b114f6e7f561a847457e52ced296ba111 from #2496.
Fixes [issue 8640](http://dolp.in/i8640). No idea what's wrong and I don't have a bulldozer to debug with.

Revert "Jit64: add FMA4 support to fmaddXX"

---

Source/Core/Core/BootManager.cpp

Needed for https://code.google.com/p/dolphin-emu/issues/detail?id=8637

Config: Add SyncOnSkipIdle GameIni option

---

Source/Core/Common/Common.h
Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/MainNoGUI.cpp
Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Source/Core/InputCommon/ControllerInterface/SDL/SDL.h

Reverts dolphin-emu/dolphin#2530

Revert "SDL: handle SDL_QUIT event"

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

Still causing issues with games.
Disable it again until I can spend enough time debugging it.

[AArch64] Disable psq_l again.

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp

This can be even more optimized in the future when the register cache supports constant caching.
Requires PR #2555 to be merged prior to this one.

[AArch64] Optimize gatherpipe stores

---

Source/Android/app/build.gradle
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/GameGridActivity.java

I'd like to put together an About screen with this type of information and make it look real nice, but this should be good enough until that happens.

Android: Show the version name as a subtitle in the GameGridActivity.

---

Source/Core/Common/FileSearch.cpp

Forces the file search to be case insensitive.

Fix File Extension Search Being Case Sensitive

---

Source/Core/VideoCommon/TextureCacheBase.cpp
Source/Core/VideoCommon/TextureCacheBase.h

Thanks to d﻿egasus for pointing out that FreeTexture is basically only used by RemoveTextureFromCache. With this pr both is joined together as FreeTexture.

Code cleanup for FreeTexture after merging PR #2097

---

Source/Core/DolphinQt/GameList/GameFile.cpp
Source/Core/DolphinQt/GameList/GameFile.h
Source/Core/DolphinWX/ISOFile.cpp
Source/Core/DolphinWX/ISOFile.h

For consistency with the other Get methods.

Move GetCompany() to ISOFile.h/GameFile.h

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/SettingsFragment.java

There aren't any AArch64 devices with v14 Qualcomm drivers. So it is dead code.

[Android] Remove dialog telling individuals that their drivers are terrible.

---

Source/Core/Common/ArmCPUDetect.cpp
Source/Core/Common/CPUDetect.h
Source/Core/DolphinWX/MainAndroid.cpp

Drops ARMv7 feature detection.

[AArch64] Clean up our CPUDetect.

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp

[AArch64] Fix a few bugs in the FPR cache.

---

Source/Core/Core/PowerPC/GDBStub.cpp

I have no idea if the GDB stub WORKS, but at least it will actually compile after this.

PowerPC: Fix GDBStub build

---

Source/Android/app/src/main/AndroidManifest.xml
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/OverlayConfigActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/OverlayConfigButton.java
Source/Android/app/src/main/res/xml/preferences.xml

Yeah um, let's just pretend like this never happened.

Android: Don't delete the Input Overlay configuration screen.

---

Source/Core/Common/Hash.h

It has no function definition.

Hash: Remove the HashFNV prototype

---

CMakeLists.txt
Source/Core/DolphinWX/ControllerConfigDiag.cpp
Source/Core/DolphinWX/Main.cpp
Source/Core/DolphinWX/Main.h
Source/Core/InputCommon/ControllerInterface/OSX/OSXKeyboard.h

Two warning fix patches and one linking issue.

Trivial fixes

---

Source/Core/Common/x64FPURoundMode.cpp

x64FPURoundMode: fix comments

---

Source/Core/VideoBackends/OGL/Render.cpp

Restores behavior that was removed.

Render: Add an OSD notification for screenshot saving

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java

Not sure how this didn't make it in those last PRs, maybe it got crushed with one of the rebases.

Android: Don't crash trying to hide toolbar in game.

---

Source/Core/Common/FileSearch.cpp
Source/Core/DolphinQt/GameList/GameTracker.cpp

Fixes https://code.google.com/p/dolphin-emu/issues/detail?id=8697&can=3

Fix DoFileSearch returning the passed-in directories themselves.

---

CMakeTests/FindPolarSSL.cmake

The compile test always failed :|

CMake: fix PolarSSL test

---

Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp

We can merge these two branches into one.

Jit64: Eliminate branch in GenFres

---

Source/Core/Core/PowerPC/JitArm64/Jit.cpp

Seems like this flag was missed.
This patch was mostly done by HdkR.

JitArm64: Implement EXCEPTION_FPU_UNAVAILABLE support.

---

CMakeLists.txt
Source/Core/Common/CodeBlock.h
Source/Core/Common/MemoryUtil.cpp
Source/Core/Common/MemoryUtil.h
Source/Core/Common/x64Emitter.h
Source/Core/Core/DSP/Jit/DSPJitUtil.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.h
Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStorePaired.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
Source/Core/Core/PowerPC/Jit64IL/IR_X86.cpp
Source/Core/Core/PowerPC/Jit64IL/JitIL.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/PowerPC/JitCommon/Jit_Util.cpp
Source/Core/Core/PowerPC/JitCommon/Jit_Util.h
Source/Core/Core/PowerPC/JitCommon/TrampolineCache.cpp
Source/UnitTests/Common/x64EmitterTest.cpp

This reverts commit 0f7f8f87747ae825c3b5adeae35cbb66114d2ba1, reversing
changes made to 9f1505435877cf8f5abe7b66fb2717c7e39c1988.
This was already reverted in master, for good reasons (that I can't exactly remember) and needs to be reverted in stable too.

Revert "Merge pull request #2358 from Tilka/pie"

---

Source/Core/DolphinWX/Frame.cpp

Also while I was at it I changed a hardcoded 10 in a savestate-related loop to State::NUM_STATES.

Forgot to add the Load Last Slot 9/10 hotkey to a switch in #2739.

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Common/CodeBlock.h
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64IL/JitIL.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

Same feature as we already support for Jit64

JitArm64: Farcache

---

Source/Core/Core/Core.cpp

Also changes s_drawn_video into an atomic, as it's used across threads as well.

Core: Change a volatile into an atomic

---

Readme.md

Probably other places this should be documented as well, but this is a start.

Android: Add system requirements to Readme.md

---

Source/Core/VideoBackends/D3D/FramebufferManager.cpp
Source/Core/VideoBackends/D3D/XFBEncoder.cpp
Source/Core/VideoCommon/RenderBase.cpp

Trying to address https://code.google.com/p/dolphin-emu/issues/detail?id=8818
It needs testing/verification.

Video: Trying to fix D3D/XFB disabled regression

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

Added some conditionals to check if one register is cached, but not both.

[AARCH64] Optimized addx()

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp

JitArm64: fix lfd

---

Source/Core/VideoCommon/VertexShaderManager.cpp

Someone suggested on IRC that we should make a database of memory locations in GameCube games which contain the 'Widescreen' setting so we can automatically detect if the game is in 4:3 or 16:9 mode. 
But that's hardly optimal, when the game actually tells the gpu what aspect ratio to render in. 10 min and 6 lines of code later, this is the result. Not only does it detect the correct aspect ratio, it does so on the fly.
I'm a little surprised that nobody thought about doing this before.
Tested with F-Zero GX and Burnout 2.
Burnout 2 doesn't detect the changed aspect ratio until you actually start a race, as the menu is completely orthographic and doesn't even attempt to adjust for the 16:9 aspect ratio, except for the spinning cars, which are a video.

Heuristic to detect if a gamecube game is rendering 16:9 widescreen.

---

Source/Core/Common/StringUtil.cpp
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Source/Core/DolphinWX/Frame.cpp
Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp

Fix some warnings

---

Source/Core/Core/PowerPC/GDBStub.cpp

Trivial buildfix; would be nice to have on the stable branch, since it's zero-risk.

PowerPC: Fix GDBStub build (stable)

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp

JitArm64: fix cmpli and disable addzex

---

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp

Revert "Jit64: use BMI1's ANDN for andcx"

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/Jit.h

We have to reset m_lastCacheFlushEnd on clearing.

JitArm64: Fix jit clearing

---

Data/Sys/GameSettings/G2R.ini
Data/Sys/GameSettings/GAC.ini
Data/Sys/GameSettings/GB3.ini
Data/Sys/GameSettings/GBV.ini
Data/Sys/GameSettings/GBX.ini
Data/Sys/GameSettings/GDD.ini
Data/Sys/GameSettings/GE5.ini
Data/Sys/GameSettings/GFG.ini
Data/Sys/GameSettings/GFO.ini
Data/Sys/GameSettings/GIL.ini
Data/Sys/GameSettings/GMN.ini
Data/Sys/GameSettings/GNH.ini
Data/Sys/GameSettings/GOB.ini
Data/Sys/GameSettings/GP8.ini
Data/Sys/GameSettings/GZP.ini

The HLE issues are gone since 4.0-7359.

Remove forced DSP LLE from game INIs

---

Source/Core/DolphinWX/TASInputDlg.cpp

Followup to #2834 where I forgot to stage all of my changes. Oops!

DolphinWX: Finish removing bandaid from 704f787

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp

Improves performance in povray bench by 2%

[AArch64] Implement frspx

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp

Initial patch is from degasus doing the base implementation.
I fixed all the issues with it and optimized it in the process.
This improves povray bench times by 4.8%

[AArch64] Implement the cr instructions

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp

Improves the povray benchmark time by 5.6%

[AArch64] Implement fctiwzx

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Source/Core/Core/PowerPC/JitArmCommon/BackPatch.h

Improves povray performance by ~4%

[AArch64] Implement stfiwx

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.h

Gets the povray bench to better times than the Wii.

[AArch64] Implement fdivx/fdivsx/mfcr/mtcrf.

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp

If the register was only a lower pair and it needed the full register, then we need to load the high 64bits.
Which we weren't doing before.

[AArch64] Fix a bug in the register cache.

---

Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp

My previous code was embarrassingly buggy.

Jit64: fix bugs in the FPSCR instructions

---

Source/Core/VideoCommon/BPMemory.h
Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/PixelShaderGen.h
Source/Core/VideoCommon/XFMemory.h

Pinging @degasus to look at this.

VideoCommon: Convert some defines into enums

---

Source/Core/DolphinWX/MemcardManager.cpp

Also gets rid of pointer casting.

MemcardManager: Remove explicit delete and new

---

Source/Core/Common/CommonFuncs.h
Source/Core/Core/HW/EXI_DeviceGecko.cpp
Source/Core/Core/HW/WiimoteReal/IOWin.cpp
Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
Source/Core/DolphinWX/MainNoGUI.cpp
Source/Core/VideoCommon/Debugger.cpp

There's already a function in Thread for this.

CommonFuncs: Remove SLEEP macro

---

Source/Core/VideoCommon/VertexLoaderARM64.cpp

Just some minor improvements noticed by dumping the vertex loader blocks.

[AArch64] Minor improves to the vertex loader JIT

---

Source/Core/DolphinWX/Cheats/CheatSearchTab.cpp
Source/Core/DolphinWX/Cheats/CheatSearchTab.h

Automatically updates the cheat values within the list in the background as memory changes.

CheatSearchTab: Make the search results list auto update address values

---

Source/Core/Core/HotkeyManager.h
Source/Core/Core/NetPlayServer.h
Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.h
Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.h
Source/Core/InputCommon/ControllerInterface/ForceFeedback/ForceFeedbackDevice.h
Source/Core/InputCommon/ControllerInterface/XInput/XInput.cpp
Source/Core/InputCommon/ControllerInterface/XInput/XInput.h

Also fixes mismatched initializer list order as well.

 Add missing override specifiers

---

Source/Core/DolphinWX/Main.cpp
Source/Core/DolphinWX/Main.h

Fixes https://bugs.dolphin-emu.org/issues/8919

Implemented CLI switch to disable confirm on stop

---

Source/Core/Core/PowerPC/JitCommon/Jit_Util.cpp

Don't know if this fixes any known bugs.

Jit64: fix errors in FPRF calculation

---

Source/Core/DiscIO/DiscIO.vcxproj.filters

DiscIO/VS: Remove an empty filter

---

Source/Core/VideoCommon/TextureCacheBase.cpp

This checks every TEXTURE_KILL_THRESHOLD frames, to see if the hash for the memory area of the efb copy has hanged. If it has changed, the efb copy can be removed, it wouldn't be used anymore. Before this pr, some efb copies would never be deleted.
Fixes issue https://bugs.dolphin-emu.org/issues/6101 and possibly some other VRAM leaks.

Perform garbage collection for efb copies

---

Source/Core/DolphinQt/DolphinQt.vcxproj.filters
Source/Core/DolphinQt/GameList/GameGrid.cpp
Source/Core/DolphinQt/GameList/GameTracker.cpp
Source/Core/DolphinQt/GameList/GameTree.cpp
Source/Core/DolphinQt/MainWindow.cpp
Source/Core/DolphinQt/MainWindow.h
Source/Core/DolphinQt/SystemInfo.cpp

DolphinQt: Use more C++11, add more sanity to VS projects.

---

Source/Core/DolphinWX/Debugger/DebuggerPanel.cpp
Source/Core/DolphinWX/Debugger/DebuggerPanel.h

This suddenly decided to pop up :|

Debugger: fix -Wunused-private-field warning

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp

Also gets rid of magic numbers in volume ramp generation.

AX: Use ArraySize over sizeof division

---

Source/Core/VideoBackends/OGL/GLInterface/AGL.cpp
Source/Core/VideoBackends/OGL/GLInterface/AGL.h
Source/Core/VideoBackends/OGL/GLInterface/EGL.cpp
Source/Core/VideoBackends/OGL/GLInterface/EGL.h
Source/Core/VideoBackends/OGL/GLInterface/GLX.cpp
Source/Core/VideoBackends/OGL/GLInterface/GLX.h
Source/Core/VideoBackends/OGL/GLInterface/WGL.cpp
Source/Core/VideoBackends/OGL/GLInterface/WGL.h
Source/Core/VideoBackends/OGL/GLInterfaceBase.h
Source/Core/VideoBackends/Software/SWmain.cpp

Reverts dolphin-emu/dolphin#3054
OSX is completely broken now.

Revert "GLInterface: Fix VideoSW on linux + OSX"

---

Source/Core/Core/PowerPC/JitCommon/Jit_Util.cpp

Jit_Util: Replace two MDisp usages with MatR

---

Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_es.cpp
Source/Core/DiscIO/Volume.h
Source/Core/DiscIO/VolumeCommon.cpp
Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DiscIO/VolumeWad.h
Source/Core/DiscIO/VolumeWiiCrypted.cpp
Source/Core/DiscIO/VolumeWiiCrypted.h
Source/Core/DolphinQt/GameList/GameFile.cpp
Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/DolphinWX/ISOFile.cpp

Gets rid of external swaps at every usage.

DiscIO: Do swapping in GetTitleID implementations

---

Source/Core/Core/HW/AudioInterface.cpp

This was created to address the problem with VC titles loading.
Needs testing.

AI: reduce overhead of sample counter

---

Source/Core/Common/BitField.h

See the [citra pull request](https://github.com/citra-emu/citra/pull/914) this is brought over from for more information.

Common: Fix BitField mask generation.

---

Source/Core/Core/Core.cpp
Source/Core/Core/HW/CPU.cpp
Source/Core/Core/HW/CPU.h
Source/Core/Core/HW/HW.cpp
Source/Core/Core/PowerPC/GDBStub.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/DolphinWX/Debugger/CodeWindow.cpp
Source/Core/DolphinWX/FrameTools.cpp

There's not much point to a class with only static member functions.

CPU: Convert CCPU into a namespace

---

Source/Core/Core/HW/DVDInterface.cpp
Source/Core/Core/HW/StreamADPCM.cpp
Source/Core/Core/HW/StreamADPCM.h

No need to have a class with only static member functions

StreamADPCM: Convert into a namespace

---

Source/Core/Core/HW/DSPHLE/UCodes/UCodes.h

Plain cleanup, no functional change

UCodes: Minor cleanup

---

Source/Core/DolphinWX/ControllerConfigDiag.cpp

ControllerConfigDiag: Amend button sizing issues on hi-DPI displays

---

Source/Core/Core/HW/DSPHLE/DSPHLE.cpp

This is already present in the DSPHLE class directly

DSPHLE: Remove duplicated struct

---

Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp

Make sure FORCE_EARLY_Z is defined for GLES

---

Source/Core/VideoCommon/TextureCacheBase.cpp

There's no known bug that is fixed by this, but it's the correct thing to do, even if it makes things slower.

Check the hash before applying efb copies as partial texture updates

---

Source/Core/Common/BitField.natvis
Source/Core/Common/Common.vcxproj
Source/Core/Common/Common.vcxproj.filters

Bitfield: Add .natvis for easier debugging of BitFields in Visual Studio

---

Source/Core/DolphinQt/Utils/Resources.cpp

DolphinQt: Add international flag to Resources

---

Source/Core/DiscIO/Blob.h
Source/Core/DiscIO/FileSystemGCWii.cpp
Source/Core/DiscIO/FileSystemGCWii.h
Source/Core/DiscIO/Filesystem.h
Source/Core/DiscIO/VolumeCreator.cpp
Source/Core/DiscIO/VolumeCreator.h
Source/Core/DiscIO/WiiWad.cpp
Source/Core/DiscIO/WiiWad.h

Maybe some of this should stay for documentation purposes?

DiscIO: drop unused stuff

---

Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_net.cpp

Fixes some network issues where the game/system asked for POLLHUP specifically.

Don't send return-only events to poll

---

Source/Core/DolphinWX/VideoConfigDiag.cpp
Source/Core/DolphinWX/VideoConfigDiag.h

The checkbox is removed, and the dropdown now looks like this:
~~None
2x MSAA
2x SSAA
4x MSAA
4x SSAA
6x MSAA
6x SSAA
8x MSAA
8x SSAA~~
EDIT:
None
2x MSAA
4x MSAA
8x MSAA
2x SSAA
4x SSAA
8x SSAA

Remove SSAA checkbox and add SSAA to AA dropdown

---

Source/Core/DolphinWX/Frame.cpp

Fixes cases of frame advance speed increase/decrease hotkey not actually doing anything.

Fix Frame Advance Hold Delay Changes

---

Source/Core/DolphinQt/GameList/GameFile.cpp
Source/Core/DolphinWX/ISOFile.cpp

This is obviously simpler for DolphinQt, but I'm not as sure about DolphinWX.

ISOFile/GameFile: Simplify IsElfOrDol

---

Source/Core/DiscIO/VolumeDirectory.cpp

Blobs are not for regular file reading.

DiscIO: Don't use PlainFileReader in VolumeDirectory

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/Memmap.h

It now uses the same error checking as CopyFromEmu and CopyToEmu.

Memmap: More error checking for Memset

---

Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_hid.cpp

Makes fixes discussed in #3302.

Update Error Log to Remove Old Issue Tracker URL

---

Source/Core/Core/ActionReplay.cpp
Source/Core/Core/ActionReplay.h
Source/Core/DolphinWX/Cheats/CheatSearchTab.cpp
Source/Core/DolphinWX/Cheats/CreateCodeDialog.cpp
Source/Core/DolphinWX/Cheats/CreateCodeDialog.h
Source/Core/DolphinWX/ISOProperties.cpp
Source/Core/DolphinWX/ISOProperties.h

Fixes a 5.0 blocker: https://bugs.dolphin-emu.org/issues/8950

Fix Cheat Manager not saving created codes

---

Source/Core/Common/TraversalClient.cpp
Source/Core/Common/TraversalClient.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp
Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.h

This feature is important to host netplay using traversal connection.
Depending on the router, We need to open closed port to host, but we don't know which port will be used...

 [Netplay] Add "Force Netplay Listen Port" feature that was in old netplay branch

---

Source/Core/VideoCommon/DriverDetails.h

I'm not familiar enough with this code to know if the rest of the comment is still accurate. Please let me know if anything else needs to be changed.

Remove Google Code Reference and Fix Grammar

---

Source/Core/DolphinWX/Config/AdvancedConfigPane.cpp
Source/Core/DolphinWX/Config/InterfaceConfigPane.cpp

- theme and language selectors wrapped into one GridBagSizer for better
appearance
- missing left padding added to checkbox on Advanced Pane

minor General Config GUI improvements

---

Source/Core/DolphinWX/MainAndroid.cpp

MainAndroid: Fix size logging

---

Source/Core/VideoBackends/D3D/Render.cpp

Issue tracker reference: https://bugs.dolphin-emu.org/issues/9144
This was due to specifying negative source coordinates for the texture copy, which must lie within the bounds of the source and destination textures. The behavior now is to clamp the copy region to [0 <= size <= backbuffer size], resulting in a copy region that can be smaller than the backbuffer, but never larger.
This results in screenshots that are cropped to the visible area of the backbuffer, without extra borders. This doesn't match GL behavior, but GL is passing negative coordinates to glReadPixels(), which on my test system results in either a solid colour or random junk (UB?). D3D doesn't have this luxury it's a block of GPU memory. Perhaps we should change GL too?
I've also changed the screenshot texture/buffer to …

D3D: Fix crash when taking screenshot with crop enabled

---

Source/Core/Common/GL/GLInterface/WGL.cpp

Would have a memory leak on game end

Fix minor memory leak in WGL interface.

---

Source/Core/Core/HW/VideoInterface.cpp

The same XFB addr was always being used by VI for each field because it was being sampled from the associated VI register before being updated (one field updated it much later than the other).

VI: wait until start of ACV to sample XFB addr

---

Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp

Tested and works on my machine™.

ZeldaHLE: Add support for New Play Control! Pikmin 1

---

Source/Core/Core/HW/EXI_Channel.cpp
Source/Core/Core/HW/EXI_Channel.h
Source/Core/Core/HW/EXI_Device.cpp
Source/Core/Core/HW/EXI_Device.h
Source/Core/Core/HW/SI.cpp
Source/Core/Core/HW/SI.h
Source/Core/Core/HW/SI_Device.cpp
Source/Core/Core/HW/SI_Device.h

Gets rid of explicit delete and new with regards to channel management.

EXI/SI: Get rid of explicit delete and new

---

Languages/gettextize
Source/Core/Common/Assert.h
Source/Core/Common/MsgHandler.cpp
Source/Core/Common/MsgHandler.h
Source/Core/Core/HW/GCPadEmu.cpp
Source/Core/Core/State.cpp
Source/Core/DiscIO/CompressedBlob.cpp
Source/Core/DolphinWX/Config/GameCubeConfigPane.cpp
Source/Core/DolphinWX/Debugger/CodeWindowFunctions.cpp
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/VideoCommon/OpcodeDecoding.cpp

Covers everything requested in this post, except progress dialogs ([issue 8832](https://bugs.dolphin-emu.org/issues/8832)) and the Apply button ([issue 9102](https://bugs.dolphin-emu.org/issues/9102)): https://forums.dolphin-emu.org/Thread-dolphin-translation-moving-to-transifex?pid=391733#pid391733
I also did some fixes that were related to the requests, like cleaning up other wxFileSelector strings and other GameCubeConfigPane strings.

Mark more strings for translation

---

Source/Core/DolphinQt2/GameList/GameFile.cpp

DQt2: Repackage the unique_ptr in GameFile into a QSharedPointer

---

Source/Core/DolphinQt/GameList/GameFile.cpp
Source/Core/DolphinQt/GameList/GameFile.h

Untested, because I can't reproduce it with Visual Studio. https://bugs.dolphin-emu.org/issues/9170

DolphinQt: Attempt at fixing issue 9170

---

Source/Core/Core/BootManager.cpp

Very slightly, just really pulling the save and restore tasks into methods instead of having them in the middle of a different function. This indirectly fixes the same thing #2619 fixes, and is supposed to be preventive so a similar thing doesn't happen again.
I haven't actually checked if this error exists as I think it does, but this should also fix an error where settings from movie playbacks or netplay sessions playing homebrew would overwrite the global settings.

BootManager: Slightly clean up the config_cache.

---

Source/Core/Core/Boot/Boot_DOL.cpp
Source/Core/Core/Boot/Boot_DOL.h
Source/Core/Core/Boot/Boot_WiiWAD.cpp
Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_es.cpp
Source/Core/DiscIO/NANDContentLoader.cpp
Source/Core/DiscIO/NANDContentLoader.h
Source/Core/DiscIO/WiiWad.cpp
Source/Core/DiscIO/WiiWad.h

Changed over to using vector to hold the respective data sets.

NANDContentLoader/WiiWAD: Get rid of raw delete and new

---

Data/Sys/GameSettings/G3L.ini
Data/Sys/GameSettings/G8M.ini
Data/Sys/GameSettings/GAF.ini
Data/Sys/GameSettings/GAL.ini
Data/Sys/GameSettings/GKY.ini
Data/Sys/GameSettings/GL5.ini
Data/Sys/GameSettings/GL7.ini
Data/Sys/GameSettings/GM4.ini
Data/Sys/GameSettings/GMS.ini
Data/Sys/GameSettings/GSR.ini
Data/Sys/GameSettings/GUP.ini
Data/Sys/GameSettings/GYQ.ini
Data/Sys/GameSettings/NAB.ini
Data/Sys/GameSettings/NAD.ini
Data/Sys/GameSettings/NAE.ini
Data/Sys/GameSettings/NAL.ini
Data/Sys/GameSettings/R25.ini
Data/Sys/GameSettings/R92.ini
Data/Sys/GameSettings/RMC.ini
Data/Sys/GameSettings/RPB.ini
Data/Sys/GameSettings/RUU.ini
Data/Sys/GameSettings/SB4.ini
Data/Sys/GameSettings/SMN.ini
Data/Sys/GameSettings/WPS.ini

Naming changed for the StereoConvergence setting, and my old PR was having rebase issues, so I've made a new PR to account for this.

Add StereoConvergence settings to various gameini files

---

Source/Core/VideoBackends/Software/SWVertexLoader.cpp
Source/Core/VideoCommon/LightingShaderGen.h
Source/Core/VideoCommon/VertexShaderGen.cpp

Reverts dolphin-emu/dolphin#3315
Looks like we will need those hardware tests after all.

Revert "ShaderGen: Toggle value of uninitialized color."

---

Source/Core/Core/FifoPlayer/FifoAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.cpp

FifoAnalyzer: Fix a few warnings that visual studio missed.

---

Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp

Ignored the mouse position unless the cursor is over the Dolphin window.

---

Source/Core/Core/HW/BBA-TAP/TAP_Unix.cpp

This allows you to run multiple instances of Dolphin that touch the BBA (Up to a 32 interface limit)
I will update the wiki guide once merged.

Support multiple bridge interfaces in Linux.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/TvMainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java

This also allows setting the user directory.
This is mainly for FifoCI in the future.

[Android] Add support for launching a game through activity monitor.

---

Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64/Jit.h
Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp
Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64IL/JitIL_Tables.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Source/Core/Core/PowerPC/JitILCommon/JitILBase.h
Source/Core/Core/PowerPC/JitILCommon/JitILBase_FloatingPoint.cpp

I don't even know if it compiles.

JitArm64: fix fcmpo/fcmpu

---

Source/Core/VideoCommon/AVIDump.cpp

Cleaning up and fixing some issues with AVIDump from #2002 without the ffmpeg implementation.

AVIDump Clean Up and Fixes

---

Source/Android/app/src/main/res/layout-television/activity_emulation.xml
Source/Android/app/src/main/res/layout/fragment_emulation.xml

Encountered this when testing out the Wii U Gamecube Adapter.

[Android] Disable screen lock when a title is running.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/UserPreferences.java
Source/Core/DolphinWX/VideoConfigDiag.cpp
Source/Core/DolphinWX/VideoConfigDiag.h
Source/Core/VideoBackends/D3D/main.cpp
Source/Core/VideoBackends/OGL/main.cpp

They share the same format, so there is no need to separate their configs.

VideoConfig: Use "GFX.ini" for both D3D and OGL.

---

Source/Core/DolphinWX/Config/GCAdapterConfigDiag.cpp
Source/Core/DolphinWX/ControllerConfigDiag.cpp

Tarukonga is Japanese. People who don't speak Japanese are unlikely to understand it.

Use the English name for DK Bongos in the English version of Dolphin

---

Source/Core/Core/CoreTiming.cpp
Source/Core/Core/CoreTiming.h
Source/Core/Core/HW/ProcessorInterface.cpp

Fix assert on reset button hit.

---

Source/Android/app/build.gradle
Source/Android/app/src/main/AndroidManifest.xml
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/DolphinApplication.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/PlatformGamesFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameDatabase.java

The first of many "architect the Android code to kill duplicate code" PRs.
In particular, this code gets rid of Loaders in the UI, which are how Google wants you to do asynchronous DB access. It's a lot of code though, and it's really unreliable. RxJava is much cleaner and easier to maintain, and we'll be able to use it for a lot of the other async operations we need.

[Android] Refactor DB read code to use RxJava

---

Source/Core/Core/MemTools.cpp
Source/Core/Core/MemTools.h

Another unused global variable.

MemTools: Get rid of a global variable

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameDatabase.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameProvider.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/AssetCopyService.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SettingsSaveService.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CPUHelper.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Log.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java

This PR makes it so that all log calls go through a static class that uses the same TAG every time. 
Reduces some code duplication, and probably should've been done a long time ago.

[Android] Refactor logging

---

Source/Core/Core/HW/EXI_DeviceIPL.cpp

Fix a typo on the size passed in to the IPL descrambler.

---

Source/Core/Core/HW/GCPad.cpp
Source/Core/Core/HW/SI.cpp

Fix hotkeys not reporting inputs.

---

Source/Core/Core/DSPEmulator.cpp
Source/Core/Core/DSPEmulator.h
Source/Core/Core/HW/DSP.cpp

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3525)

DSPEmulator: Make CreateDSPEmulator return a unique_ptr

---

Source/Core/DiscIO/VolumeWiiCrypted.cpp

We totally ignore [the region setting on a Wii Disc](http://wiibrew.org/wiki/Wii_Disc#Region_setting). Instead, the 4th byte of the Game ID is used, similar to GameCube titles. There are some Wii titles from different regions that use 'X' for this fourth byte. This code should use the region setting from the disc, but also use a more specific country enum value if it makes sense for that region (e.g. various European countries for PAL).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3515)

DiscIO: Use specified Wii region for discs

---

Source/Core/Core/Core.cpp
Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/HW/VideoInterface.cpp
Source/Core/Core/HW/VideoInterface.h
Source/Core/VideoCommon/AVIDump.cpp

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3540)

VideoInterface: Change a global into a translation-unit local variable

---

Source/Android/build.gradle
Source/Android/gradle/wrapper/gradle-wrapper.properties

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3548)

[Android] Fix android builds

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Animations.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Pixels.java

Pull some animations into static helper methods, as they're likely to be used elsewhere.
Similarly, adds some static helpers for device-dependent pixel conversion. They aren't used yet, but are likely to be very soon.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3517)

[Android] Refactor animations

---

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp

The x86/x64 add and sub instructions (and a few more) can set OF, which causes merged branches to take wrong jumps. The easiest way to fix this seems to be to recalculate the flags with test afterwards.
This fixes [Issue 8787](https://bugs.dolphin-emu.org/issues/8787).
I wrote some test cases for some instructions; if someone is interested, I can submit a PR at hwtests.
Proper emulation of PPC SO flag remains to be done, though I don't know if there is a game using it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3212)

JIT x64: Recalculate flags after add/sub

---

Source/Core/DolphinWX/AboutDolphin.cpp
Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/DolphinWX/WxUtils.cpp
Source/Core/DolphinWX/WxUtils.h

https://bugs.dolphin-emu.org/issues/9275
Untested, because I don't have OS X. I'm creating this PR so @MaJoRoesch can test it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3533)

DolphinWX: Support 2x images for all resources

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsActivityPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsActivityView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFrameLayout.java
Source/Android/app/src/main/res/animator/settings_enter.xml
Source/Android/app/src/main/res/animator/settings_exit.xml
Source/Android/app/src/main/res/animator/settings_pop_enter.xml
Source/Android/app/src/main/res/animator/setttings_pop_exit.xml
Source/Android/app/src/main/res/layout/fragment_settings.xml

Add a little bit of #materiyolo #swag to the Settings UI screen. Have to get something for all that work on that last PR.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3557)

[Android] Add fragment transition animations to the Settings UI screen

---

Source/Core/VideoBackends/D3D/main.cpp
Source/Core/VideoBackends/OGL/main.cpp
Source/Core/VideoBackends/Software/SWmain.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/OpcodeDecoding.h

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3563)

OpcodeDecoder: Add namespace

---

Source/Core/VideoCommon/TextureCacheBase.h

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3559)

TextureCacheBase: Simplify init/comparison of TCacheEntryConfig

---

Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayClient.h
Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp

Should be separated fairly well for individual reviewing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3567)

NetPlayClient: Minor changes

---

Source/Core/VideoBackends/D3D/Render.cpp
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/Software/DebugUtil.cpp
Source/Core/VideoBackends/Software/EfbCopy.cpp
Source/Core/VideoBackends/Software/SWRenderer.cpp
Source/Core/VideoCommon/BPStructs.cpp
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/Fifo.h
Source/Core/VideoCommon/OpcodeDecoding.cpp
Source/Core/VideoCommon/PixelEngine.cpp
Source/Core/VideoCommon/XFStructs.cpp

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3560)

Fifo: get rid of global variables

---

Source/Core/AudioCommon/Mixer.cpp
Source/Core/AudioCommon/Mixer.h

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3514)

Mixer: Minor changes

---

Source/Core/VideoBackends/D3D/Render.cpp
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoCommon/AVIDump.cpp
Source/Core/VideoCommon/AVIDump.h

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3426)

Add support for framedumping to OpenGL ES.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/USBPermService.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_GCAdapter.java
Source/Core/InputCommon/GCAdapter_Android.cpp

This gets it to the point that users will be able to use the GC Adapter as soon as they set the SIDevice to the Wii U Gamecube controller adapter.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3553)

Implement requesting permission for using the GC Wii U Adapter.

---

Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/NetPlayServer.h

A few small things (use of unique_ptr like in netplay client for async sending, formatting, and two out-of-bounds reads)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3575)

Small netplay server cleanup & fix

---

Source/Core/Core/BootManager.cpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3576)

BootManager: Minor changes

---

Source/Android/app/src/main/AndroidManifest.xml
Source/Android/app/src/main/res/values/arrays.xml
Source/Android/app/src/main/res/values/strings.xml

bandaid++
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3584)

[Android] Change SettingsActivity label to "Settings" instead of "CPU Settings"

---

Externals/mbedtls/library/CMakeLists.txt

Fixes 5.0 blocker bug #9208
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3600)

Remove mbedtls install target

---

Source/Core/VideoCommon/VideoCommon.h

Simply removing two functions that wasn't used anywhere.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3611)

VideoCommon: Remove unused pow functions

---

Source/Core/DolphinQt2/GameList/GameList.cpp

Before and after
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3618)

DQt2: properly space row height of table gamelist

---

Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/DolphinWX/GameListCtrl.h

Read the commits for details.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3347)

DolphinWX: Fixes for compressing multiple games at once

---

CMakeTests/CheckLib.cmake

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3621)

Extend libav check to find versions without pkg-config

---

Source/Core/Core/HW/MMIO.cpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3627)

MMIO: correct error message

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp

This PR tries to merge some floating point instruction generators to share some common code.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3617)

JitArm64: Merge FP functions.

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/Memmap.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitCommon/Jit_Util.cpp

I can undo the vertical alignment if not desired.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3638)

Memmap: Make the MMIO mapping a unique_ptr

---

Source/Core/VideoBackends/D3D12/D3DBase.h

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3641)

D3DBase: Fix missing return statement

---

Source/Core/VideoBackends/D3D/NativeVertexFormat.cpp
Source/Core/VideoBackends/D3D12/NativeVertexFormat.cpp
Source/Core/VideoBackends/D3D12/NativeVertexFormat.h

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3643)

NativeVertexFormat: Minor changes

---

Source/Core/DolphinWX/Main.cpp
Source/Core/VideoBackends/D3D/main.cpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3648)

Rename Direct3D to Direct3D 11

---

Source/Core/VideoBackends/D3D12/ShaderCache.cpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3644)

ShaderCache: Minor changes

---

Source/Core/Core/HW/VideoInterface.cpp

Yeah.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3663)

Fix typo in VideoInterface code

---

Data/Sys/GameSettings/SQD.ini

Fixes Issue 5892 - https://bugs.dolphin-emu.org/issues/5892
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3657)

Add Safe Texture Cache to Gunblade NY & LA Machineguns INI

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/FileAdapter.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3596)

[Android] Fix crash when we don't have access to a folder.

---

Data/Sys/GameSettings/R44.ini

Fixes issue 9369: https://bugs.dolphin-emu.org/issues/9369
If we can find a real fix before 5.0 release, that should be made into a separate PR.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3674)

Force Slow Depth on Suzumiya Haruhi no Heiretsu

---

Source/Core/Core/HW/DVDInterface.cpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3679)

DVDInterface: Log seek offsets with a more intuitive sign

---

Source/Core/Core/PowerPC/JitArm64/Jit.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp

We used MOVI2R() + ADD(), now we try to fit everything within ADD() itself. As this instruction is very high in profile, this should matter a bit.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3685)

JitArm64: Optimize addi

---

Source/Core/Core/HW/SI.cpp
Source/Core/Core/HW/SI.h
Source/Core/Core/State.cpp

Fixes issue 9343: https://bugs.dolphin-emu.org/issues/9343
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3667)

Fix savestates if a device is changed after a savestate is made

---

Source/Core/VideoCommon/VertexLoaderManager.h

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3675)

Fix building with PCH disabled.

---

Source/Core/VideoBackends/D3D12/Render.cpp

`DX12::Renderer::SetSamplerState()` contains a bug where a variable with the `s_` prefix is not actually static and not actually initialized either. This leads to a fun scenario where the newly generated sampler state is compared against random bytes from the stack to decide whether to actually apply it or not.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3692)

D3D12: Fix uninitialized variable in SetSamplerState

---

Source/Core/Common/GekkoDisassembler.cpp
Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/NetPlayServer.cpp
Source/Core/VideoBackends/D3D12/D3DState.cpp

Found by Lintian https://lintian.debian.org/
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3655)

Fix some very minor spelling mistakes

---

Source/Core/Core/HW/SI.cpp
Source/Core/Core/HW/SI_Device.cpp
Source/Core/Core/HW/SI_Device.h
Source/Core/Core/NetPlayClient.cpp
Source/Core/DolphinWX/FrameTools.cpp

Fix for https://bugs.dolphin-emu.org/issues/9298.
Also use a newly introduced function in netplay to check if the device can be assimilated to a GC controller.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3589)

Fix recording a movie with the GC Adapter

---

Data/Sys/GameSettings/GBS.ini
Data/Sys/GameSettings/GM2.ini
Data/Sys/GameSettings/GM3.ini
Data/Sys/GameSettings/GMD.ini
Data/Sys/GameSettings/GQX.ini
Data/Sys/GameSettings/GZL.ini
Data/Sys/GameSettings/NAE.ini
Data/Sys/GameSettings/R44.ini
Data/Sys/GameSettings/RNJ.ini
Data/Sys/GameSettings/S59.ini
Data/Sys/GameSettings/SF8.ini
Data/Sys/GameSettings/SOU.ini
Data/Sys/GameSettings/WMJ.ini
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/SettingsFile.java
Source/Android/app/src/main/res/values-ja/strings.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Core/DolphinWX/VideoConfigDiag.cpp
Source/Core/VideoCommon/PixelShaderGen.cpp
Source/Core/VideoCommon/PixelShaderGen.h
Source/Core/VideoCommon/VertexShaderGen.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

This Pull Requests reinstates the Fast Depth option and all its associated GameINIs.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3686)

Revert "Merge pull request #3578 from Armada651/forced-slow-depth"

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/FileListItem.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameDatabase.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3703)

[Android] Make sure the file extension check isn't case sensitive

---

Source/Core/DolphinWX/Config/GeneralConfigPane.cpp

@MaJoRoesch asked for this.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3690)

[Config UI] add "normal speed" to speed limit 100%

---

Source/Core/Core/NetPlayServer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3721)

NetPlayServer: Get rid of some explicit deallocations

---

Installer/Installer.nsi

Fixes issue 9389: https://bugs.dolphin-emu.org/issues/9389
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3715)

Update Installer to delete old Install directory

---

Source/Android/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3731)

Fix Android buildbot

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3732)

CMake: fix warning

---

Source/Core/Common/SysConf.cpp
Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb.cpp
Source/Core/Core/Movie.cpp
Source/Core/Core/Movie.h

Fixes issue 9159: https://bugs.dolphin-emu.org/issues/9159
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3668)

Apply Wii Settings on Movie Recording/Playback

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3738)

.gitignore: ignore emacs temp files

---

Source/Android/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3764)

Android: Update gradle version

---

Source/Core/Common/MathUtil.h
Source/Core/VideoBackends/D3D/Render.cpp
Source/PCH/pch.h
Source/UnitTests/Common/MathUtilTest.cpp
Source/UnitTests/VideoCommon/VertexLoaderTest.cpp

```
[19:18] <@shuffle2> https://github.com/dolphin-emu/dolphin/commit/aeee5be5ef123a3b98b8fb413573b077b580e380
[19:18] <@shuffle2> someone should update this now
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3760)

pch: Update Visual Studio version check

---

Source/Core/DolphinWX/DolphinWX.vcxproj

Fixes issue 9455: https://bugs.dolphin-emu.org/issues/9455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3777)

Only copy relevant files for Windows builds

---

.gitignore
Readme.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3785)

Update Windows build instructions and .gitignore

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/AssetCopyService.java
Source/Android/jni/CMakeLists.txt
Source/Android/jni/MainAndroid.cpp

This directory was just missed. This will fix some Wii games magically....
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3767)

Android: Also copy sys/Wii directory.

---

Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp
Source/Core/Core/PowerPC/PPCTables.cpp

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3658)

Interpreter: simplify some helpers

---

Source/Core/DolphinWX/NetPlay/NetWindow.cpp

Previously, two-disc games would appear exactly the same, and not
necessarily in disc order, which made it a pain.
Edit: And since netplay selects games based on title, this actually fixes the remote selection as well (previously it would select one at ~random)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3793)

Add information about disc number in the netplay setup

---

Source/Core/DolphinQt2/GameList/GameList.cpp
Source/Core/DolphinQt2/GameList/GameList.h

Small usability change.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3532)

Qt - Enter key opens selected game in the game list.

---

Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/DolphinQt2.vcxproj.filters

This needs to be merged before any other Qt work.
After this is merged all open Qt PR's that introduce new files need to add those files to DolphinQt2.vcxproj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3837)

Brings visual studio build files up to date with recent Qt changes

---

Data/Sys/GameSettings/SFP.ini

Fixes [issue 9531](https://bugs.dolphin-emu.org/issues/9531).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3839)

Set Medium Texture Cache for Fantastic Football Fan Party

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/FileListItem.java

Untested. I'm not sure why this was missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3844)

Fix reading CISO files on Android

---

Source/Core/Core/HW/DSP.cpp

We really need hardware tests for this one. But this will do as a quick fix for [issue 9509](https://bugs.dolphin-emu.org/issues/9509) for 5.0
The fix is slightly fragile, so I'd like all games tested.
Games to Test:
---
This change is totally [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3829)

Increase Audio DMA Interrupt delay to 200 cycles (Fix assorted Namco games)

---

Source/Core/DolphinQt2/DolphinQt2.vcxproj

Changed to match dolphinwx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3842)

[Qt] VS build no longer adds all of Data to Binary

---

Source/Core/Core/NetPlayClient.cpp

Trying to fix https://bugs.dolphin-emu.org/issues/9497
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3802)

Disable wiimotes on game start if running in netplay

---

Source/Core/DolphinWX/GameListCtrl.cpp

Fixes https://bugs.dolphin-emu.org/issues/9567
Credit pretty much goes to JosJuice. They basically told me exactly what function to use lol
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3860)

[UI] Fix Gamelist encoding bug

---

Source/Core/DiscIO/Blob.cpp

Regression from PR #3795. Fixes https://bugs.dolphin-emu.org/issues/9565
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3868)

SectorReader: Fix reading the last block of the disc.

---

Source/Core/Core/FifoPlayer/FifoPlayer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3873)

Undo the addition of a translatable string during the string freeze

---

Source/Core/Core/Movie.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3872)

Movie: Improve handling of non-hexadecimal revision strings

---

Data/Sys/GameSettings/R9I.ini

Fixes issue 9577: https://bugs.dolphin-emu.org/issues/9577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3875)

Force Skip EFB Access from CPU off for Pikmin Wii

---

Installer/Installer.nsi
Installer/dolphin-emu.spec

Fixes issue 9585: https://bugs.dolphin-emu.org/issues/9585
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3882)

Update Installer for Dolphin 5.0 (Bundle VC++2015 Redist)

---

Readme.md

This was changed in 00c21e7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3886)

Update installer script filename in readme

---

Data/Sys/GameSettings/SHW.ini

Fixes issue 9596: https://bugs.dolphin-emu.org/issues/9596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3898)

Force Virtual XFB for Hollywood Squares

---

Data/Sys/GameSettings/R3A.ini
Data/Sys/GameSettings/R4F.ini

Works around issue 9597: https://bugs.dolphin-emu.org/issues/9597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3901)

Force Real XFB and EFB2RAM for Story Hour: Adventures and Story Hour: Fairy Tales

---

Source/Core/Common/Analytics.cpp

Fixes #9606.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3907)

analytics: Disable ALPN only on Windows.

---

Source/Core/Core/Analytics.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3908)

analytics: More accurate video backend name.

---

Data/Sys/GameSettings/G6Q.ini

Fixes https://bugs.dolphin-emu.org/issues/9613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3914)

Game INI updates

---

Data/Sys/GameSettings/WR9.ini
Data/Sys/GameSettings/WRX.ini

Fixes issue 9616: https://bugs.dolphin-emu.org/issues/9616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3917)

Change Mega Man 9/10 Scaled EFB from 2 to -1

---

Data/Sys/GameSettings/GLR.ini
Data/Sys/GameSettings/GSW.ini

yeah
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3922)

[GameINI] Properly force LLE recompiler on RS2 and 3

---

Source/Core/InputCommon/ControllerInterface/Android/Android.cpp
Source/Core/InputCommon/ControllerInterface/Android/Android.h
Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Source/Core/InputCommon/ControllerInterface/ControllerInterface.h
Source/Core/InputCommon/ControllerInterface/DInput/DInput.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInput.h
Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.h
Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.h
Source/Core/InputCommon/ControllerInterface/Device.h
Source/Core/InputCommon/ControllerInterface/OSX/OSX.h
Source/Core/InputCommon/ControllerInterface/OSX/OSX.mm
Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.cpp
Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.h
Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Source/Core/InputCommon/ControllerInterface/SDL/SDL.h
Source/Core/InputCommon/ControllerInterface/XInput/XInput.cpp
Source/Core/InputCommon/ControllerInterface/XInput/XInput.h
Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h
Source/Core/InputCommon/ControllerInterface/Xlib/Xlib.cpp
Source/Core/InputCommon/ControllerInterface/Xlib/Xlib.h
Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
Source/Core/InputCommon/ControllerInterface/evdev/evdev.h

Needed for future hotplug support, as we'll need to access/add devices from different threads.
This was previously added in #3890 but doing it separately as it needed changes to other input backends (apart from evdev).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3892)

ControllerInterface: Add synchronisation

---

Source/Android/jni/MainAndroid.cpp
Source/Core/DiscIO/Volume.h
Source/Core/DiscIO/VolumeDirectory.cpp
Source/Core/DiscIO/VolumeDirectory.h
Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DiscIO/VolumeWad.h
Source/Core/DolphinWX/ISOFile.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3934)

Undo some comment formatting changes from b5104a7

---

Source/Core/Common/FixedSizeQueue.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3933)

FixedSizeQueue: modernize (std::array, std::move)

---

Source/Core/Common/BitSet.h

solved conflicts due to Reformatting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3931)

constexpr added to BitSet.h. conflicts solved

---

Source/Core/InputCommon/ControllerInterface/Device.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3940)

Device: Use std::tie for operator==

---

Source/Core/Core/PowerPC/JitInterface.cpp

(There's another bFakeVMEM in Memmap.h.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3948)

Delete dead variable named bFakeVMEM.

---

Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp

Mostly comment changes; also gets rid of an unnecessary call to
CheckExceptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3947)

Misc cleanup in Interpreter.

---

Source/Core/Common/MemoryUtil.cpp
Source/Core/Core/Analytics.cpp
Source/Core/VideoBackends/Null/PerfQuery.h

Fix all the things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3945)

Warning fixes 2016

---

Source/Core/Core/FifoPlayer/FifoRecorder.cpp

Same thing, less code. Also less error prone to future modification in the case someone early returns, for whatever reason, and forgets to unlock the mutex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3957)

FifoRecorder: Use lock_guard instead of explicit lock/unlock

---

Source/UnitTests/Common/BusyLoopTest.cpp

Running this test 100 times is not worth to spend 1 second.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3960)

BusyLoopTest: Only run 10 times.

---

Source/Core/Core/FifoPlayer/FifoAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoAnalyzer.h
Source/Core/Core/FifoPlayer/FifoDataFile.cpp
Source/Core/Core/FifoPlayer/FifoDataFile.h
Source/Core/Core/FifoPlayer/FifoPlaybackAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/FifoPlayer/FifoPlayer.h
Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.h
Source/Core/Core/FifoPlayer/FifoRecorder.cpp
Source/Core/DolphinWX/FifoPlayerDlg.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3965)

FifoPlayer: Cull some explicit delete and new instances

---

Source/Core/Core/PowerPC/JitCommon/JitBase.h

Fixes a small bug from #3496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3966)

Fix broken debug builds in visual studio

---

Source/Core/Core/FifoPlayer/FifoAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoAnalyzer.h
Source/Core/Core/FifoPlayer/FifoPlaybackAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoPlaybackAnalyzer.h
Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/FifoPlayer/FifoPlayer.h
Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.h
Source/Core/Core/FifoPlayer/FifoRecorder.cpp
Source/Core/Core/FifoPlayer/FifoRecorder.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3975)

FifoPlayer: Remove unnecessary headers/namespace cleanup

---

Source/Core/Core/BootManager.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayProto.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/DolphinWX/NetPlay/NetWindow.cpp

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3878)

Sync the "enable cheat" setting over netplay

---

Source/Core/Core/FifoPlayer/FifoPlayer.cpp

Reverts dolphin-emu/dolphin#3873
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3874)

Revert "Undo the addition of a translatable string during the string freeze"

---

Source/Core/DolphinWX/GameListCtrl.cpp

Caused by a commit of mine, cb3b1b6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3982)

DolphinWX: Fix a mix-up

---

Readme.md

Dolphin [no longer runs properly on OS X 10.9 Mavericks](https://forums.dolphin-emu.org/Thread-osx-10-9-5-dolphin-quit-unexpectedly?pid=413520#pid413520) and [the supported operating systems section in the FAQ has been updated to reflect that](https://dolphin-emu.org/docs/faq/#what-operating-systems-are-supported). The GitHub page should be consistent with the official requirements that are listed elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3994)

Update OS X Requirement to 10.10

---

Source/Core/Core/Core.cpp
Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
Source/Core/Core/HW/EXI_DeviceIPL.cpp
Source/Core/Core/HW/SI_DeviceGCAdapter.cpp
Source/Core/DolphinWX/Config/ConfigMain.cpp
Source/Core/DolphinWX/ControllerConfigDiag.cpp
Source/Core/InputCommon/GCAdapter.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3979)

Use g_want_determinism more

---

Source/Core/DolphinWX/Debugger/CodeWindowFunctions.cpp
Source/Core/DolphinWX/FrameTools.cpp

I missed these the first go around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4008)

Finish Menu Capitalization Fixes

---

Source/Core/Core/HW/EXI_Channel.cpp
Source/Core/Core/HW/EXI_Channel.h

Really basic change. Also drops Hungarian notation from the variable name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4011)

EXI_Channel: Use std::array

---

Source/Core/Core/HW/BBA-TAP/TAP_Apple.cpp
Source/Core/Core/HW/BBA-TAP/TAP_Unix.cpp
Source/Core/Core/HW/BBA-TAP/TAP_Win32.cpp
Source/Core/Core/HW/EXI_DeviceAGP.cpp
Source/Core/Core/HW/EXI_DeviceAGP.h
Source/Core/Core/HW/EXI_DeviceEthernet.cpp
Source/Core/Core/HW/EXI_DeviceEthernet.h
Source/Core/Core/HW/EXI_DeviceMic.cpp
Source/Core/Core/HW/Sram.cpp
Source/Core/Core/HW/Sram.h

Just applies const to some applicable areas within EXI-related files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4026)

EXI: Misc const correctness changes

---

Source/Core/DolphinWX/DolphinWX.vcxproj.filters

The header file was in the correct filter, but the cpp file wasn't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4029)

VS: Add MD5Dialog.cpp to the correct filter hierarchy

---

Source/Core/DolphinWX/NetPlay/MD5Dialog.cpp
Source/Core/DolphinWX/NetPlay/MD5Dialog.h
Source/Core/DolphinWX/NetPlay/NetWindow.h

Unused variable and missing 'override'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4038)

trivial warning fixes

---

Source/Core/Core/HW/ProcessorInterface.cpp
Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_stm.h

Fixes issue 8328.
As far as I know, this works the same way as console. Games will generally
react to the reset button the same way as Home->Reset, so this is
only marginally useful, but possibly nice to have in certain situations.
Note that if you try to use Reset, and you're running a WAD which isn't
installed, it will likely crash because WADs respond to the reset button
by launching themselves with ES_LAUNCH.  It might be a good idea to add some
sort of hack to make this work as expected.
It would be easy to extend this to support the power button, but it's
unclear how exactly that should be exposed in the UI. See also issue 8979.
Needs to be rebased once PR #3811 is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

Make reset button (Emulation -> Reset) work correctly for Wii games.

---

Source/Android/app/build.gradle
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableButton.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableJoystick.java
Source/Android/app/src/main/res/layout/fragment_emulation.xml
Source/Android/app/src/main/res/menu/menu_emulation.xml
Source/Android/app/src/main/res/values/strings.xml

-Implemented ability to configure game controls by moving them around individually. Controls save locations once they are placed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4040)

Android: Configurable Control Placement

---

Source/Core/Core/PowerPC/CachedInterpreter.cpp
Source/Core/Core/PowerPC/CachedInterpreter.h
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
Source/Core/Core/PowerPC/Jit64/JitAsm.h
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Source/Core/Core/PowerPC/Jit64IL/JitIL.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.h
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/Core/PowerPC/PowerPC.h

Reverts dolphin-emu/dolphin#4004
Apparently there are some major issues, I recommend reverting until someone has time to look into this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4060)

Revert "JitCache: Support for VMEM + MSR bits"

---

Contributing.md

This changes the guide to reflect the new formatting rules, and adds
instructions for using clang-format to automatically check and fix
most formatting issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3952)

Contributing: Update guide for clang-format

---

Source/Core/Core/HW/SI_DeviceGBA.cpp
Source/Core/Core/HW/SI_DeviceGBA.h

Basic stuff
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4070)

SI_DeviceGBA: const correctness

---

Source/Core/AudioCommon/AudioCommon.cpp
Source/Core/AudioCommon/AudioCommon.h

Noticed this in #4074 but it wasn't related to the changes being made in it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4075)

AudioCommon: const correctness

---

Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/FifoPlayer/FifoPlayer.h
Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.cpp
Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.h
Source/Core/Core/FifoPlayer/FifoRecorder.cpp
Source/Core/Core/FifoPlayer/FifoRecorder.h
Source/Core/VideoCommon/RenderBase.cpp

Noticed these while doing an unrelated change which I've yet to open a pull request for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4077)

FifoPlayer: const correctness

---

Source/Core/Core/HW/GCKeyboard.cpp
Source/Core/Core/HW/GCKeyboard.h
Source/Core/Core/HW/GCKeyboardEmu.cpp
Source/Core/Core/HW/GCKeyboardEmu.h
Source/Core/Core/HW/GCPad.cpp
Source/Core/Core/HW/GCPad.h
Source/Core/Core/HW/GCPadEmu.cpp
Source/Core/Core/HW/GCPadEmu.h
Source/Core/Core/HW/SI_DeviceAMBaseboard.cpp
Source/Core/Core/HW/SI_DeviceGCAdapter.cpp
Source/Core/Core/HW/SI_DeviceGCController.cpp
Source/Core/Core/HW/SI_DeviceKeyboard.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/InputCommon/GCAdapter.cpp
Source/Core/InputCommon/GCAdapter.h
Source/Core/InputCommon/GCAdapter_Android.cpp
Source/Core/InputCommon/GCAdapter_Null.cpp

It's unnecessary to use pointers for this sort of thing considering the input structs are very trivial. It's definitely not significant enough to warrant out parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4079)

HW: Make GC input retrieval functions return by value

---

Source/Core/Core/NetPlayClient.cpp

Basic stuff. Pointed out by @meffij on IRC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4086)

NetPlayClient: Remove duplicate header inclusion

---

Source/Core/Core/NetPlayClient.cpp

Missed this in the previous PR; whoops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4087)

NetPlayClient: Remove another duplicate inclusion

---

Source/Core/Common/CodeBlock.h

Same thing, less code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4096)

CodeBlock: In-class initialize variables

---

Source/Core/Common/SysConf.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4097)

SysConf: Minor simplifications to initial generating

---

Source/Core/VideoBackends/D3D/TextureCache.cpp

Relatively straightforward change.
This will bring D3D11 to feature parity with D3D12 and GL for texture dumping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3861)

D3D11: Support texture dumping of non-zero mipmap levels

---

Source/Core/DolphinWX/Config/GameCubeConfigPane.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4110)

Fix choosing certain localized EXI devices

---

Source/Core/Common/CodeBlock.h
Source/Core/Common/MemoryUtil.cpp
Source/Core/Common/MemoryUtil.h
Source/Core/Core/Core.cpp
Source/Core/Core/DSP/DSPCore.cpp
Source/Core/Core/DSP/DSPHWInterface.cpp
Source/Core/Core/HW/DSP.cpp
Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
Source/Core/Core/HW/EXI_DeviceIPL.cpp
Source/Core/Core/PowerPC/Jit64/Jit.cpp
Source/Core/VideoBackends/OGL/StreamBuffer.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/HiresTextures.cpp
Source/Core/VideoCommon/TextureCacheBase.cpp
Source/UnitTests/Core/PageFaultTest.cpp

Gets these out of the global namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3386)

Common: Namespace MemoryUtil

---

Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/Fifo.h
Source/Core/VideoCommon/MainBase.cpp

Self-explanatory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4132)

Fifo: Make SyncGPUReason an enum class

---

Source/Core/Core/HLE/HLE_OS.cpp

No real point to using an out parameter for something like this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4133)

HLE_OS: Return string from GetStringVA by value

---

Source/Core/DolphinWX/VideoConfigDiag.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4143)

Fix Graphics Settings Capitalization

---

Source/Core/VideoCommon/BPStructs.cpp

Visual Studio's code analyzer complains about these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4177)

BPStructs: remove case statements which never match.

---

Source/Core/Core/PowerPC/JitCommon/Jit_Util.cpp

As requested by @phire
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4183)

Simplify an if condition after PR #4078

---

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp

#4137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4191)

Fix the master build.

---

Source/Core/Common/SymbolDB.h
Source/Core/Core/Boot/ElfReader.cpp
Source/Core/Core/Debugger/PPCDebugInterface.cpp
Source/Core/Core/HW/DSPLLE/DSPDebugInterface.cpp
Source/Core/Core/PowerPC/PPCAnalyst.cpp
Source/Core/Core/PowerPC/PPCSymbolDB.cpp
Source/Core/Core/PowerPC/PPCSymbolDB.h
Source/Core/DolphinWX/Debugger/CodeWindowFunctions.cpp
Source/Core/DolphinWX/Debugger/DSPDebugWindow.cpp

Small changes. Commit messages are fairly self-explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4211)

SymbolDB: Minor changes

---

Source/Core/Core/PowerPC/PPCSymbolDB.cpp

See [CodeWarrior documentation](http://www.nxp.com/files/soft_dev_tools/doc/ref_manual/CWMCUPABTR.pdf) in Linker maps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4213)

PPCSymbolDB: Rename unknown variable

---

Source/Core/DiscIO/NANDContentLoader.cpp
Source/Core/DiscIO/NANDContentLoader.h

Commit messages tell all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4214)

NANDContentLoader: Minor changes

---

Source/Core/VideoBackends/Software/SWOGLWindow.cpp
Source/Core/VideoBackends/Software/SWOGLWindow.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4232)

SWOGLWindow: Minor changes

---

Source/Core/VideoBackends/Software/SWVertexLoader.cpp
Source/Core/VideoBackends/Software/SWVertexLoader.h

trivial stuff
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4225)

SWVertexLoader: Value initialize SetupUnit instance

---

Source/Core/VideoBackends/Software/Clipper.cpp
Source/Core/VideoBackends/Software/Clipper.h
Source/Core/VideoBackends/Software/DebugUtil.cpp
Source/Core/VideoBackends/Software/DebugUtil.h
Source/Core/VideoBackends/Software/NativeVertexFormat.h
Source/Core/VideoBackends/Software/Rasterizer.cpp
Source/Core/VideoBackends/Software/Rasterizer.h
Source/Core/VideoBackends/Software/TextureEncoder.cpp

Self explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4237)

Software: const correctness

---

Source/Core/VideoBackends/Null/FramebufferManager.h

Didn't cause any issues (yet). Just happened to notice this when making an unrelated change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4239)

Null: Add missing header guard

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4251)

PPCAnalyst: Convert #define into a constant

---

Source/Core/DiscIO/WiiWad.cpp
Source/Core/DiscIO/WiiWad.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4247)

WiiWad: Minor changes

---

Source/Core/Core/HW/DVDInterface.cpp
Source/Core/Core/State.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4242)

DVDInterface: Make changing discs savestate-safe

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4256)

PPCAnalyst: Compress loop into std::any_of

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4259)

PPCAnalyst: Get rid of two casts

---

Source/Core/DolphinWX/Debugger/CodeWindow.cpp

Here are the summary of the changes:
- Single step: Fix an oddity when a breakpoint is hit at the beginning of a block, then after, a single step is performed and finally, hitting play, the breakpoint will be skipped even in the case when it would be hit again.  This was done by using the interpreter version of single step.  Also, remove some redundant update request.
- Step over: fix some GUI lags. due to redundant draw calls.
- Step out: Add consideration for conditional branching by checking the condition as the interpreter does.  Now, every bclr instructions except those that changes the LR (because it would not be the end of the function) will cause the end of the step out and not just blr instructions.  Also now stops if a bp is detected and finally, remove redundant GUI updates …

Fix a bunch of debugger stepping issues.

---

Source/Core/Core/PowerPC/MMU.cpp

The previous code is considered undefined behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4262)

MMU: Get rid of type punning in FP read/write functions

---

Source/Core/Core/PowerPC/MMU.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4263)

MMU: Remove useless casts

---

Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/DolphinWX/GameListCtrl.h

Same thing, less code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4261)

GameListCtrl: Use unique_ptr for underlying GameListItems

---

Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4264)

SystemRegisters: Get rid of pointer casting

---

Source/Core/VideoBackends/Software/Clipper.cpp
Source/Core/VideoBackends/Software/DebugUtil.cpp
Source/Core/VideoBackends/Software/EfbCopy.h
Source/Core/VideoBackends/Software/NativeVertexFormat.h
Source/Core/VideoBackends/Software/Rasterizer.h
Source/Core/VideoBackends/Software/SWRenderer.h
Source/Core/VideoBackends/Software/SWVertexLoader.cpp
Source/Core/VideoBackends/Software/SWVertexLoader.h
Source/Core/VideoBackends/Software/SWmain.cpp
Source/Core/VideoBackends/Software/SetupUnit.cpp
Source/Core/VideoBackends/Software/TextureSampler.cpp
Source/Core/VideoBackends/Software/TransformUnit.cpp
Source/Core/VideoBackends/Software/Vec3.h
Source/Core/VideoBackends/Software/VideoBackend.h

Gets rid of indirect includes and unused stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4240)

Software: Clean out unnecessary includes/fwd decls

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinWX/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4254)

Check for errors when postprocessing macOS app bundle

---

Source/Core/DolphinWX/LogWindow.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4274)

LogWindow: Minor changes

---

Source/Core/Core/HW/Memmap.cpp
Source/Core/Core/HW/Memmap.h
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Source/Core/Core/PowerPC/MMU.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4188)

Dynamic bat: Merge failure and small cleanup

---

Source/Core/Core/BootManager.cpp

Hopefully will have a real PR to replace sysconf code soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4278)

quick fix to prevent heap corruption in sysconf code

---

Source/Core/DolphinWX/Config/AdvancedConfigPane.cpp
Source/Core/DolphinWX/Config/InterfaceConfigPane.cpp
Source/Core/DolphinWX/Debugger/RegisterView.cpp
Source/Core/DolphinWX/FifoPlayerDlg.h

Minor fixes for warnings that were introduced in recently merged PRs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4283)

Fix a few warnings

---

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp

Replaces https://github.com/dolphin-emu/dolphin/pull/3402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4281)

Jit64: use domain-appropriate instructions

---

Source/Core/Core/PowerPC/Jit64/Jit.cpp

@degasus / hthh...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4289)

Fix static_assert raised by commit 789975e3

---

Source/Core/Core/DSPEmulator.h
Source/Core/Core/HW/DSPHLE/DSPHLE.cpp
Source/Core/Core/HW/DSPHLE/DSPHLE.h
Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
Source/Core/Core/HW/DSPLLE/DSPLLE.h

Same thing, less duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4314)

DSPEmulator: Move common variable into base class

---

Source/Core/VideoBackends/D3D/Render.cpp
Source/Core/VideoBackends/D3D12/Render.cpp
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/Vulkan/Renderer.cpp
Source/Core/VideoBackends/Vulkan/Renderer.h
Source/Core/VideoCommon/RenderBase.cpp
Source/Core/VideoCommon/RenderBase.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4318)

Renderer: Move framedumping logic to VideoCommon.

---

Source/Core/VideoCommon/Fifo.cpp

This fixes a regression of PR #3490.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4269)

Fifo: Fix SyncGPU on dual core mode.

---

Source/Core/Core/DSP/DSPCore.cpp
Source/Core/Core/DSP/DSPCore.h
Source/Core/DolphinWX/Debugger/DSPRegisterView.cpp
Source/Core/DolphinWX/Debugger/DSPRegisterView.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4310)

DSPRegisterView: Minor changes

---

Source/Core/DolphinWX/ISOProperties.cpp
Source/Core/DolphinWX/ISOProperties.h

According to @JMC47, @degasus forgot to remove this in one of his PRs.
Just cleaning that up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4329)

[UI] Remove idle skipping from game properties

---

Source/Core/VideoBackends/D3D/Render.cpp
Source/Core/VideoBackends/D3D/Render.h
Source/Core/VideoBackends/D3D12/Render.cpp
Source/Core/VideoBackends/D3D12/Render.h
Source/Core/VideoBackends/Null/Render.h
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/OGL/Render.h
Source/Core/VideoBackends/OGL/VertexManager.cpp
Source/Core/VideoBackends/Software/SWRenderer.h
Source/Core/VideoBackends/Vulkan/Renderer.cpp
Source/Core/VideoBackends/Vulkan/Renderer.h
Source/Core/VideoCommon/AVIDump.cpp
Source/Core/VideoCommon/AVIDump.h
Source/Core/VideoCommon/RenderBase.cpp
Source/Core/VideoCommon/RenderBase.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4326)

Framedump: Merge screenshot code with framedumping.

---

Source/Core/Core/State.cpp
Source/Core/VideoCommon/Fifo.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4341)

SyncGPU: Fix savestate.

---

Source/Android/app/src/main/res/values/styles.xml

My eyes no longer bleed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4348)

Android: Use the light theme for emulation

---

Source/Core/VideoBackends/Software/SWRenderer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4346)

VideoSW: Use VideoCommon frame dumping.

---

Source/Core/AudioCommon/AudioCommon.cpp
Source/Core/AudioCommon/AudioCommon.h
Source/Core/DolphinWX/Config/AudioConfigPane.cpp
Source/Core/DolphinWX/Config/AudioConfigPane.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4336)

AudioConfigPane/AudioCommon: various GUI cleanups

---

Source/Core/Core/Movie.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4367)

Movie: Add missing includes

---

Source/Core/DolphinWX/Config/AdvancedConfigPane.h
Source/Core/DolphinWX/Config/GCAdapterConfigDiag.cpp
Source/Core/DolphinWX/Config/GCAdapterConfigDiag.h
Source/Core/DolphinWX/Config/GameCubeConfigPane.h
Source/Core/DolphinWX/Config/GeneralConfigPane.h

Adds necessary headers where applicable, and gets rid of them where possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4369)

DolphinWX: Minor include changes to config panes/dialogs

---

Source/Core/VideoCommon/PixelShaderGen.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4378)

PixelShaderGen: Fix implicit type conversions.

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Source/Core/Core/PowerPC/JitArm64/Jit_Util.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4392)

JitArm64: Get rid of MOVI2R as much as possible

---

Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/Frame.h
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/Main.cpp
Source/Core/DolphinWX/Main.h

This is a rebase I did from pr #3843 with the permission of the author.
From my understanding, for some reasons, if you are in some environement (I know so far my arch linux, linux mint 17.x + I think 16 and ubuntu 14.04 with unity), the FindFocus function from wx just doesn't work well, it seems to tell dolphin has the focus even though it wouldn't be the case.  This would cause 2 main issues:
* Pause on focus lost simply never works
* Hotkeys and input would be processed by dolphin even when it doesn't have the focus and background input disabled
Compared to the original PR, what I did is I addressed the last unresolved review, but most of the original pr is there.  Basically, the idea is to set a flag when the main frame gets activated and the helper method would return just that.
I …

Fix window focus detection on Linux (rebase from #3843)

---

Source/CMakeLists.txt
Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
Source/Core/Core/State.cpp
Source/Core/InputCommon/ControllerInterface/OSX/OSXKeyboard.mm
Source/Core/VideoBackends/D3D12/D3DState.cpp
Source/Core/VideoCommon/DriverDetails.h

See title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4383)

Fix minor comment typos

---

Source/Core/Common/MemoryUtil.cpp
Source/Core/Core/HW/BBA-TAP/TAP_Unix.cpp
Source/Core/Core/HW/DVDInterface.cpp
Source/Core/DolphinWX/Frame.cpp
Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp

Fairly straightforward warning fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4376)

Warning fixes

---

Source/Core/DolphinWX/MainMenuBar.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4381)

DolphinWX: Small debug text fixes

---

Source/Core/Core/Movie.cpp

Fixes https://bugs.dolphin-emu.org/issues/9681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4368)

Movie: Add missing calls to UpdateWantDeterminism

---

Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.cpp
Source/Core/DolphinWX/Cheats/CheatSearchTab.cpp
Source/Core/DolphinWX/Debugger/CodeView.cpp
Source/Core/DolphinWX/Debugger/DSPDebugWindow.cpp
Source/Core/DolphinWX/Debugger/DebuggerPanel.cpp
Source/Core/DolphinWX/Debugger/JitWindow.cpp
Source/Core/DolphinWX/Debugger/MemoryView.cpp
Source/Core/DolphinWX/Debugger/RegisterView.cpp
Source/Core/DolphinWX/Debugger/WatchView.cpp
Source/Core/DolphinWX/Debugger/WatchWindow.h
Source/Core/DolphinWX/MainMenuBar.cpp
Source/Core/DolphinWX/MainToolBar.cpp
Source/Core/DolphinWX/NetPlay/PadMapDialog.cpp
Source/Core/DolphinWX/WXInputBase.cpp

Also a few small non-debug text changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4412)

More debug text fixes

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp

This fixes slowmem load instruction with update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4415)

JitArm64: Also push/pop gpr.R(addr).

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java
Source/Core/Core/HW/SystemTimers.cpp
Source/Core/Core/HW/WiimoteReal/IOhidapi.cpp
Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.cpp

Continuation of changes from #4391.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4421)

Change "Wiimote" to "Wii Remote" in Logs

---

Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/OGL/Render.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4344)

OGL: Use PBO for framedump, with async readback.

---

Source/Core/VideoCommon/AVIDump.cpp
Source/Core/VideoCommon/RenderBase.cpp
Source/Core/VideoCommon/RenderBase.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4345)

Renderer: Threaded frame dumping.

---

Source/Core/DolphinWX/Frame.h
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/MainToolBar.cpp
Source/Core/DolphinWX/MainToolBar.h
Source/Core/DolphinWX/WxEventUtils.cpp
Source/Core/DolphinWX/WxEventUtils.h

Deduplicates some code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4428)

DolphinWX: Move common wxUpdateUIEvent functions to WxEventUtils

---

Source/Core/VideoBackends/Vulkan/Renderer.cpp
Source/Core/VideoBackends/Vulkan/Renderer.h

Very brief testing on AMD seems fine. Needs testing on NV/Intel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4435)

Vulkan: Implement asynchronous frame dumping.

---

Source/Core/DolphinWX/Debugger/CodeWindow.cpp
Source/Core/DolphinWX/Debugger/CodeWindow.h
Source/Core/DolphinWX/Frame.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4442)

CodeWindow: Remove unused constructor parameter

---

Source/Core/DolphinWX/NetPlay/NetPlayLauncher.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4444)

NetPlayLauncher: Add missing #pragma once

---

Source/Core/InputCommon/ControllerInterface/OSX/OSX.mm
Source/Core/InputCommon/ControllerInterface/OSX/OSXJoystick.h
Source/Core/InputCommon/ControllerInterface/OSX/OSXJoystick.mm
Source/Core/InputCommon/ControllerInterface/OSX/OSXKeyboard.h
Source/Core/InputCommon/ControllerInterface/OSX/OSXKeyboard.mm
Source/Core/InputCommon/ControllerInterface/OSX/RunLoopStopper.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4362)

ControllerInterface: enable hotplugging on macOS

---

Source/Core/DolphinWX/FifoPlayerDlg.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4450)

Update FIFO Player Window Capitalization

---

Source/Core/VideoBackends/OGL/Render.cpp

Pretty simply change, this was a regression introduced by #4436.
When minimizing a window you get a client area size of (0, 0), at least on Windows. Also fixes a potential divide by zero in Renderer::RenderText, as well as replacing C-style casts with static_cast.
The variables themselves should probably be unsigned as well, but there's a few of these in RenderBase that would need to be changed (e.g. target width/height, backbuffer width/height).

OGL: Fix assertion when minimizing window

---

Source/Core/DolphinWX/FrameTools.cpp

~~This basically reverts this PR https://github.com/dolphin-emu/dolphin/pull/1118~~
Fixes this issue: https://bugs.dolphin-emu.org/issues/9703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4030)

Fix focus bug when using the "render to main window" feature

---

Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/OGL/Render.h

Regression from #4436, fixes https://bugs.dolphin-emu.org/issues/9950

OGL: Fix black screen when MSAA is enabled

---

Source/Core/VideoCommon/PixelShaderGen.cpp

Fixes the white box in the fortune street fifolog.

PixelShaderGen: Fix incorrect indexing of tevLerpBias

---

Source/Core/Core/PowerPC/SignatureDB/CSVSignatureDB.cpp
Source/Core/Core/PowerPC/SignatureDB/CSVSignatureDB.h
Source/Core/Core/PowerPC/SignatureDB/DSYSignatureDB.cpp
Source/Core/Core/PowerPC/SignatureDB/DSYSignatureDB.h

Noticed this *after* merging #4497 ;_;

SignatureDB: Add missing license headers

---

Source/Core/Common/FileUtil.cpp

Fixes a warning under recent glibc.

Common: Replace deprecated readdir_r with readdir

---

Source/Core/Core/Movie.cpp
Source/Core/Core/Movie.h

Also add similar comments to the variables `memcards` and `bongos`.

Movie: Replace incorrect name and comment for numControllers

---

Readme.md

I've linted the markdown to improved legibility and to avoid errors in markdown rendering.

Linted markdown for the README

---

Source/Core/Core/HW/DSPHLE/DSPHLE.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AX.h
Source/Core/Core/HW/DSPHLE/UCodes/CARD.cpp
Source/Core/Core/HW/DSPHLE/UCodes/CARD.h
Source/Core/Core/HW/DSPHLE/UCodes/GBA.cpp
Source/Core/Core/HW/DSPHLE/UCodes/GBA.h
Source/Core/Core/HW/DSPHLE/UCodes/INIT.cpp
Source/Core/Core/HW/DSPHLE/UCodes/INIT.h
Source/Core/Core/HW/DSPHLE/UCodes/ROM.cpp
Source/Core/Core/HW/DSPHLE/UCodes/ROM.h
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.h
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.h

We must be able to construct the HLE without emulating the initialization
on loading a savestate.

DSPHLE: Seperate HLE construction and initialization.

---

Source/Core/Core/DSP/DSPCore.cpp
Source/Core/Core/DSP/Jit/DSPEmitter.cpp
Source/Core/Core/DSP/Jit/DSPEmitter.h

Minor changes that seemed suitable to keep together. Each commit should be fairly self-contained.

DSPEmitter: Minor cleanup

---

Source/Core/DolphinWX/Config/GameCubeConfigPane.cpp

Ah the joys of writing thousands of lines of code...

Should fix being unable to change memory card slot A

---

Source/Core/AudioCommon/Mixer.cpp
Source/Core/AudioCommon/WaveFile.cpp

This has feature parity with the dump frames warning when the file exists.

Display warning when dumping audio if file exists

---

Source/Core/Core/DSP/DSPDisassembler.h

DSPDisassembler: directly initialize AssemblerSettings struct members

---

Source/Core/Common/FileUtil.cpp
Source/Core/Common/FileUtil.h

A few minor changes that aren't significant enough for their own PRs.

IOFile: Minor changes

---

Source/Core/Core/Movie.cpp

Fixes issue 10008: https://bugs.dolphin-emu.org/issues/10008

Add missing new lines for OSD

---

Source/Core/DolphinWX/FrameTools.cpp

This window is for GameCube controller input (unless I am mistaken).

Clarify GameCube Controller in TAS Input

---

Source/Core/Core/HLE/HLE.cpp

Another table that got kinda mangled with the codebase formatting.

HLE: Align table formatting

---

Source/Core/VideoBackends/Software/SWOGLWindow.cpp

texture2D is a legacy function.

VideoSW: Fix GL ES shader.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsAdapter.java

Untested, should fix the second part of [issue 9916](https://dolp.in/i9916).

Android: fix software renderer settings string

---

Source/Core/AudioCommon/WaveFile.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/ConfigManager.h

Hides the warning just like the option for silent video dumping.

Add Silent Audio Dumping INI Option

---

Source/Core/DolphinWX/MainMenuBar.cpp

Make refresh list option more clear as to what it does and more consistent with other usage in the UI.

Change "Refresh List" to "Refresh Game List" in Menu

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFragmentPresenter.java

Follow-up for #4631. Maybe this time?

Android: fix software renderer 2nd edition

---

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp

Attempt re-adding the missing AXWii DSP_SYNC

---

Source/Core/Core/Debugger/PPCDebugInterface.cpp
Source/Core/Core/PowerPC/BreakPoints.cpp
Source/Core/Core/PowerPC/BreakPoints.h
Source/Core/Core/PowerPC/MMU.cpp
Source/Core/DolphinWX/Debugger/BreakpointView.cpp
Source/Core/DolphinWX/Debugger/MemoryCheckDlg.cpp
Source/Core/DolphinWX/Debugger/WatchView.cpp

Minor changes that don't necessarily deserve their own pull request; mostly just cleanup. Each commit should be self-contained.

BreakPoints: Minor changes

---

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp

I guess they were just missed.

Jit64: Use PPCSTATE reg if possible.

---

Source/Core/DiscIO/VolumeCreator.cpp

RVT-R (Wii debug) disc images are basically the same as retail, except they use a different set of keys and signatures. This patch checks for the debug issuer, and if found, uses the debug key instead of the retail key.
Tested with a recently dumped RVT-R prototype of Sonic and the Black Knight.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/4479)

Support for RVT-R disc images

---

Source/Core/Core/HW/GCMemcard.cpp
Source/Core/Core/HW/GCMemcard.h
Source/Core/Core/HW/GCMemcardDirectory.cpp
Source/Core/Core/HW/GCMemcardDirectory.h
Source/Core/Core/HW/GCMemcardRaw.cpp
Source/Core/Core/HW/GCMemcardRaw.h

A few function reference and pointer parameters are only read from.

GCMemcard: Const-correctness changes

---

Source/Core/Common/ColorUtil.cpp
Source/Core/Common/ColorUtil.h
Source/Core/Core/HW/GCMemcard.cpp

The data it points to isn't modified.

ColorUtil: Make decodeCI8image's pal parameter const

---

Source/Core/Core/HW/DSP.cpp

HW/DSP: Use member initializers with structs/unions where applicable

---

Source/Core/Core/PowerPC/Jit64IL/IR_X86.cpp
Source/Core/Core/PowerPC/JitILCommon/IR.cpp
Source/Core/Core/PowerPC/JitILCommon/IR.h

Similar to #4666. Just a bunch of really minor things.

IR: Minor changes

---

Source/Android/build.gradle

Just updating to the latest gradle version
(Also testing out for my first PR before I start looking into more stuff)

Updated gradle to latest version

---

CMakeLists.txt

This is based off discussion on IRC.

CMakeLists: Make CMake 3.5.0 the minimum requirement

---

Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter.h
Source/Core/Core/PowerPC/Interpreter/Interpreter_Branch.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp
Source/Core/Core/PowerPC/PPCTables.cpp

Just minor stuff, mostly stylistic, which I figured I'd get out of the way first before moving onto more involved changes with regards to table construction/populating.

Interpreter: Minor changes

---

Source/Core/Core/HW/EXI/EXI_Channel.cpp
Source/Core/Core/HW/EXI/EXI_Channel.h

Just a minor clean up. Each individual commit is relatively self-contained.

EXI_Channel: Minor cleanup

---

Source/Core/Core/HW/SI/SI_Device.cpp
Source/Core/Core/HW/SI/SI_Device.h
Source/Core/Core/HW/SI/SI_DeviceGCAdapter.cpp
Source/Core/Core/HW/SI/SI_DeviceGCController.cpp
Source/Core/Core/HW/SI/SI_DeviceGCSteeringWheel.cpp
Source/Core/Core/HW/SI/SI_DeviceKeyboard.cpp

A cleanup in the same vein as #4709—this one cleans up the SI device base class.

SI_Device: Minor cleanup

---

Source/Core/Core/HW/WiimoteEmu/Attachment/Attachment.cpp
Source/Core/Core/HW/WiimoteEmu/Attachment/Attachment.h
Source/Core/Core/HW/WiimoteEmu/Attachment/Classic.cpp
Source/Core/Core/HW/WiimoteEmu/Attachment/Classic.h
Source/Core/Core/HW/WiimoteEmu/Attachment/Drums.cpp
Source/Core/Core/HW/WiimoteEmu/Attachment/Drums.h
Source/Core/Core/HW/WiimoteEmu/Attachment/Guitar.cpp
Source/Core/Core/HW/WiimoteEmu/Attachment/Guitar.h
Source/Core/Core/HW/WiimoteEmu/Attachment/Nunchuk.cpp
Source/Core/Core/HW/WiimoteEmu/Attachment/Nunchuk.h
Source/Core/Core/HW/WiimoteEmu/Attachment/Turntable.cpp
Source/Core/Core/HW/WiimoteEmu/Attachment/Turntable.h

Fairly basic stuff as far as changes go. Each commit should be fairly well isolated from one another.

Attachments: Minor cleanup

---

Source/Core/AudioCommon/SoundStream.h

This wasn't being used anywhere, and I'm not sure how long it's not been in use.

Remove dead audio dumping code

---

Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DiscIO/VolumeWad.h

Minor, straightforward changes to VolumeWad.

Minor cleanup to VolumeWad

---

Source/Core/VideoCommon/BPMemory.cpp
Source/Core/VideoCommon/BPMemory.h

BPMemory: Minor changes

---

CMakeLists.txt
Externals/curl/lib/CMakeLists.txt
Externals/wxWidgets3/CMakeLists.txt
Source/Android/app/build.gradle
Source/CMakeLists.txt
Source/Core/AudioCommon/OpenALStream.cpp
Source/Core/Common/Common.h
Source/Core/Common/x64CPUDetect.cpp
Source/Core/Core/FifoPlayer/FifoDataFile.cpp
Source/Core/Core/PowerPC/JitCommon/JitCache.h
Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/ISOFile.h
Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp
Source/Core/DolphinWX/NetPlay/PadMapDialog.cpp
Source/Core/DolphinWX/X11Utils.cpp
Source/Core/DolphinWX/X11Utils.h
Source/VSProps/Base.props

This again improves the Windows compatibility.

CMake cleanup

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot.h
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Boot/Boot_WiiWAD.cpp
Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/IPC.cpp
Source/Core/Core/IOS/IPC.h

Set up the IOS memory information area with real values based on the required IOS.

Set up IOS RAM information area with real values.

---

Source/Core/Core/DSP/DSPCore.cpp
Source/Core/Core/DSP/Jit/DSPEmitter.cpp
Source/Core/Core/DSP/Jit/DSPEmitter.h
Source/Core/Core/DSP/Jit/DSPJitArithmetic.cpp
Source/Core/Core/DSP/Jit/DSPJitBranch.cpp
Source/Core/Core/DSP/Jit/DSPJitCCUtil.cpp
Source/Core/Core/DSP/Jit/DSPJitExtOps.cpp
Source/Core/Core/DSP/Jit/DSPJitLoadStore.cpp
Source/Core/Core/DSP/Jit/DSPJitMisc.cpp
Source/Core/Core/DSP/Jit/DSPJitMultiplier.cpp
Source/Core/Core/DSP/Jit/DSPJitUtil.cpp

Amends the variable names to follow our coding style.

DSPEmitter: Amend member variable naming

---

Source/Core/Core/HW/EXI/EXI_Channel.cpp
Source/Core/Core/HW/EXI/EXI_Device.cpp
Source/Core/Core/HW/EXI/EXI_Device.h
Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp

Cleans up the base class for all EXI devices. Each commit should be fairly self-explanatory.

EXI_Device: Minor cleanup

---

Source/Core/DolphinWX/MemcardManager.cpp
Source/Core/DolphinWX/MemcardManager.h

Same thing, but with less need to care about explicit deallocation.

MemcardManager: Use unique_ptr over raw pointers

---

Tools/deploy-mac.py

We currently recur over libraries we've already fixed up, needlessly attempting to do nothing over again.

Tools: Fix recurring multiple times over the same library in deploy-mac.py

---

Source/Core/DolphinWX/MemcardManager.cpp
Source/Core/DolphinWX/MemcardManager.h

Just two really minor changes.

MemcardManager: Minor changes

---

Data/Sys/GameSettings/SKA.ini
Data/Sys/GameSettings/SKG.ini
Data/Sys/GameSettings/SKO.ini

This prevents the games from flickering.

GameINI: Enable XFB for Karaoke Revolution Glee 1-3

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Core/Core.cpp
Source/Core/Core/Core.h
Source/Core/Core/Debugger/PPCDebugInterface.cpp
Source/Core/Core/HW/DSPLLE/DSPDebugInterface.cpp
Source/Core/Core/Movie.cpp
Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Source/Core/Core/PowerPC/JitInterface.cpp
Source/Core/Core/PowerPC/PowerPC.h
Source/Core/DiscIO/FileMonitor.cpp
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinWX/Cheats/CheatSearchTab.cpp
Source/Core/DolphinWX/ControllerConfigDiag.cpp
Source/Core/DolphinWX/Debugger/CodeWindow.cpp
Source/Core/DolphinWX/Debugger/CodeWindowFunctions.cpp
Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/DolphinWX/MainMenuBar.cpp
Source/Core/DolphinWX/MainNoGUI.cpp
Source/Core/DolphinWX/MainToolBar.cpp
Source/Core/DolphinWX/SoftwareVideoConfigDialog.cpp
Source/Core/DolphinWX/WxEventUtils.cpp
Source/Core/InputCommon/GCAdapter.cpp
Source/Core/InputCommon/GCAdapter_Android.cpp

Prevents constants from polluting the namespace.

Core: Convert State enum into an enum class

---

Source/Core/DolphinWX/NetPlay/NetWindow.cpp
Source/Core/DolphinWX/NetPlay/NetWindow.h

This doesn't need to be publicly accessable.

NetWindow: Make chat messages queue private

---

Source/Core/Core/HW/EXI/EXI_DeviceAD16.cpp
Source/Core/Core/HW/EXI/EXI_DeviceAD16.h

Mainly just coding style amendments

EXI_DeviceAD16: Minor changes

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot.h
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Boot/Boot_WiiWAD.cpp
Source/Core/Core/Boot/ElfReader.cpp
Source/Core/Core/Boot/ElfReader.h

Makes for less source files needing to be rebuilt when changes are made.

Boot: Minor include changes

---

Source/Core/DolphinWX/GameListCtrl.cpp

Several of the things done while performing a scan are logically their own behavior (e.g. loading a titles file, checking if an entry should be added, etc).

GameListCtrl: Separate some scanning code into functions

---

Source/Core/InputCommon/ControllerEmu/ControlGroup/Buttons.cpp

Buttons: Use a delegating constructor

---

Source/Core/InputCommon/ControlReference/ControlReference.cpp
Source/Core/InputCommon/ControlReference/ControlReference.h
Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp
Source/Core/InputCommon/ControllerEmu/ControllerEmu.h

None of these parameters are modified.

ControllerEmu: Add const to UpdateReferences() first reference parameter

---

Source/Core/DolphinWX/FrameTools.cpp

This is pretty unnecessary, and was suggested to be removed on IRC.

Remove IsReadOnly check when stop recording

---

Source/Core/Core/IOS/Network/IP/Top.cpp

Some platforms (e.g. Haiku) define SOL_SOCKET to be -1, which obviously
does not work with static arrays. Plus, this is cleaner.

IOS/Network/Net: Use a conversion function instead of a static array for SOCKOPT mapping

---

Source/Core/Core/IOS/FS/FileIO.cpp

Fixes a logic bug I introduced as part of #4942. We were not handling the "read past EOF" case correctly, which caused requested_read_length to underflow in some cases. Thanks to booto for quickly catching the logic issue and JMC47 for testing it.
Also fixes a comparison check (though this is unlikely to change anything).

IOS/FFSP: Fix the "past EOF" check

---

CMakeLists.txt
Externals/cpp-optparse/CMakeLists.txt
Externals/cpp-optparse/OptionParser.cpp
Externals/cpp-optparse/OptionParser.h
Externals/cpp-optparse/cpp-optparse.vcxproj
Externals/cpp-optparse/cpp-optparse.vcxproj.filters
Source/Core/DolphinWX/CMakeLists.txt
Source/Core/DolphinWX/DolphinWX.vcxproj
Source/Core/DolphinWX/Main.cpp
Source/Core/DolphinWX/Main.h
Source/Core/DolphinWX/MainNoGUI.cpp
Source/Core/UICommon/CMakeLists.txt
Source/Core/UICommon/CommandLineParse.cpp
Source/Core/UICommon/CommandLineParse.h
Source/Core/UICommon/UICommon.vcxproj
Source/dolphin-emu.sln

Split from #4912. In the future, this will allow for setting arbitrary options on the command line. For now, there should not be any functional change.

Use cpp-optparse for command line parsing

---

Source/Core/Common/SysConf.cpp
Source/Core/Common/SysConf.h

SysConf: Use vectors instead of raw pointers

---

Source/Android/jni/ButtonManager.cpp
Source/Core/Common/IniFile.cpp
Source/Core/Common/IniFile.h
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/BootManager.cpp
Source/Core/Core/HW/EXI/EXI_DeviceAGP.cpp
Source/Core/Core/HW/GCMemcardRaw.cpp
Source/Core/Core/HotkeyManager.cpp
Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/WiiRoot.cpp
Source/Core/DolphinWX/Config/GameCubeConfigPane.cpp
Source/Core/DolphinWX/Config/InterfaceConfigPane.cpp
Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/Input/InputConfigDiag.cpp
Source/Core/DolphinWX/NetPlay/NetWindow.cpp
Source/Core/DolphinWX/X11Utils.cpp
Source/Core/DolphinWX/X11Utils.h
Source/Core/VideoCommon/AVIDump.cpp

Basic integral support that should have been there in the first place. 'Inspired'/'unlazied' from review on #4958

IniFile: Handle s64/u64 values

---

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp

Thanks @aldelaro5 for an easy way to reproduce those issues.

JitCache: Fix two block invalidation issues.

---

CMakeLists.txt
Source/CMakeLists.txt
Source/Core/CMakeLists.txt
Source/Core/Common/CMakeLists.txt
Source/Core/Core/CMakeLists.txt
Source/Core/DiscIO/CMakeLists.txt
Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinWX/CMakeLists.txt
Source/Core/InputCommon/CMakeLists.txt
Source/Core/UICommon/CMakeLists.txt
Source/Core/VideoBackends/Null/CMakeLists.txt
Source/Core/VideoBackends/OGL/CMakeLists.txt
Source/Core/VideoBackends/Software/CMakeLists.txt
Source/Core/VideoBackends/Vulkan/CMakeLists.txt
Source/Core/VideoCommon/CMakeLists.txt
Source/DSPTool/CMakeLists.txt
Source/UnitTests/CMakeLists.txt

Normalizes tabs to spaces to follow our codebase.
This gets it all over with so it's less of a pain in general to make changes to the CMake build files.

CMakeLists: Normalize whitespace

---

Source/Core/Core/HW/GCKeyboardEmu.cpp
Source/Core/Core/HW/GCPadEmu.cpp
Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Source/Core/Core/HotkeyManager.cpp
Source/Core/DolphinWX/Input/InputConfigDiag.cpp
Source/Core/DolphinWX/Input/InputConfigDiag.h
Source/Core/DolphinWX/Input/WiimoteInputConfigDiag.cpp
Source/Core/InputCommon/CMakeLists.txt
Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/Buttons.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/Buttons.h
Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/Force.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/MixedTriggers.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/ModifySettingsButton.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/Slider.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.cpp
Source/Core/InputCommon/ControllerEmu/ControlGroup/Triggers.cpp
Source/Core/InputCommon/ControllerEmu/Setting/BackgroundInputSetting.cpp
Source/Core/InputCommon/ControllerEmu/Setting/BackgroundInputSetting.h
Source/Core/InputCommon/ControllerEmu/Setting/BooleanSetting.cpp
Source/Core/InputCommon/ControllerEmu/Setting/BooleanSetting.h
Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.cpp
Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h
Source/Core/InputCommon/ControllerEmu/Setting/Setting.h
Source/Core/InputCommon/InputCommon.vcxproj
Source/Core/InputCommon/InputCommon.vcxproj.filters

@lioncash pinging you because you've been working on this stuff.

InputCommon: move Setting classes out of ControlGroup

---

Source/Core/VideoBackends/Vulkan/Renderer.cpp

This was causing issues when toggling the crop setting, as well as some widescreen hacks.
May fix https://bugs.dolphin-emu.org/issues/10118

Vulkan: Fix issue where target rectangle changes weren't detected

---

Source/Core/Core/Boot/Boot_WiiWAD.cpp

Boot_WiiWAD: Simplify state_checksum()

---

Source/Core/Core/IOS/ES/ES.cpp

This partially restores a hack which causes ES to fake ticket views for IOS titles.
This is necessary because we still allow users to boot games from the game list, so, with no way of making sure the required IOSes are installed beforehand, games may OSPanic() when they try to reload to some IOS version and just find out that the IOS is not installed (something which *never* happens on the real console, of course).
A warning is printed in the logs to make sure technical users know the IOS titles are being faked. To try and keep things accurate in all other cases, this hack is only active when it is needed (when the current title is a disc title which was launched from the game list).

IOS/ES: Partially restore hack to fake IOS titles

---

Source/Core/VideoBackends/Vulkan/RasterFont.cpp

https://bugs.dolphin-emu.org/issues/10146

Fix issue 10146 (compilation issue because of colliding defines)

---

Source/Core/Core/IOS/ES/ES.cpp

Using DiscIO's NAND content loader is the wrong way to get the ticket for a title, because it checks whether the TMD is present and the validity check fails if it isn't. This is not the correct behaviour: we should just read the ticket from /ticket without caring about TMDs.

IOS/ES: Fix GetViews to not check for the TMD

---

Source/Core/Core/IOS/Network/IP/Top.cpp
Source/Core/Core/IOS/Network/IP/Top.h

Localizes behavior and separates the code out from the IOCtl/IOCtlV switch blocks.

IOS/Network/IP/Top: Separate behaviors into their own functions

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/HW/DVDInterface.cpp
Source/Core/Core/HW/DVDInterface.h

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/3582)

DVDInterface: Cleanup for setting/getting whether a disc is inside

---

Source/Core/Core/HW/DSPLLE/DSPLLE.cpp

DSPLLE: Remove commented out code

---

Source/Core/DolphinWX/MainMenuBar.cpp

Make the option consistent with other usage in menu.

Change "Fullscreen" Menu Option to "Toggle Fullscreen"

---

Source/Core/Core/HW/SI/SI_DeviceGCController.cpp
Source/Core/Core/HW/SI/SI_DeviceGCController.h
Source/Core/Core/HW/SI/SI_DeviceGCSteeringWheel.cpp

Follow up to #5078, which normalizes variable/parameter conventions.

SI_DeviceGCController: Minor cleanup

---

Source/Core/Core/HW/GCMemcard/GCMemcard.h
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.h
Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp
Source/Core/Core/HW/GCMemcard/GCMemcardRaw.h

More variable convention normalizing. This normalizes all stuff related to the MemoryCardBase hierarchy, as I plan to shuffle that around a bit and want to "kick off the dirt" first.

GCMemcard: Minor cleanup

---

Source/Core/Core/HW/SI/SI.cpp

Stronger typing (no implicit pointer decay), nicer aggregate initialization. Also gets rid of magic constants where applicable.

SI: Convert SI buffer from a C array to std::array

---

Source/Core/Core/NetPlayClient.cpp

Gets rid of two -Wshadow warnings

NetPlayClient: Eliminate variable shadowing

---

Source/Core/Core/NetPlayClient.cpp
Source/Core/Core/NetPlayClient.h
Source/Core/Core/NetPlayServer.cpp
Source/Core/Core/NetPlayServer.h

Minor const correctness changes I noticed while getting rid of variable shadowing in NetPlayClient.

NetPlayServer/NetPlayClient: const correctness

---

Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp

Change of behaviour was introduced by 4aa5291.

Jit64AsmCommon: Use correct quantization table

---

Source/Core/Core/FifoPlayer/FifoDataFile.cpp
Source/Core/Core/FifoPlayer/FifoDataFile.h
Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Source/Core/Core/FifoPlayer/FifoPlayer.h
Source/Core/Core/FifoPlayer/FifoRecorder.cpp
Source/Core/Core/FifoPlayer/FifoRecorder.h

FifoPlayer: In-class initialize member variables where applicable

---

Source/Core/Core/ARDecrypt.cpp

Fairly basic stuff. Noticed these while trying to read up on how all the AR code stuff works.

ARDecrypt: const correctness

---

Source/Core/VideoCommon/VertexLoaderBase.cpp
Source/Core/VideoCommon/VertexLoaderBase.h

VertexLoaderBase: In-class initialize class members where applicable

---

Source/Core/Common/IniFile.cpp
Source/Core/Common/IniFile.h

Fairly minor changes that don't deserve their own individual PR. Mostly just cleanup.

IniFile: Minor changes

---

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp

Note that the 16 byte alignment was unnecessary.
No other code (that I could find) currently uses the red zone.

EmuCodeBlock: Place ConvertDoubleToSingle temporaries on the stack

---

Source/Core/VideoCommon/Statistics.cpp
Source/Core/VideoCommon/VertexLoaderBase.cpp
Source/Core/VideoCommon/VertexLoaderBase.h
Source/Core/VideoCommon/VertexLoaderManager.cpp
Source/Core/VideoCommon/VertexLoaderManager.h
Source/Core/VideoCommon/VertexLoaderX64.cpp

Just another C++03-ism hanging around.

VertexLoader: Return debug strings by value

---

Source/Core/Core/HW/VideoInterface.cpp
Source/Core/Core/HW/VideoInterface.h

Minor miscellaneous changes that don't deserve their own PR.

VideoInterface: Minor changes

---

Source/Core/Core/Core.vcxproj.filters

Core: Amend VS filter tag

---

Source/Core/Core/Movie.cpp
Source/Core/Core/Movie.h
Source/Core/DolphinWX/Debugger/CodeWindowFunctions.cpp
Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/Frame.h
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/Input/InputConfigDiag.cpp
Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
Source/Core/InputCommon/ControlReference/ExpressionParser.h

Keeps more dialog state internal to the main UI frame.

Frame: Make TAS dialogs private

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/GameBannerRequestHandler.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PicassoUtils.java

It doesn't look that good since the banners are 96x32 but it still better
than nothing.

[Android] Load the game banner from the ROM and use it if no screenshot is available

---

Source/Core/Core/IOS/ES/Views.cpp

We had missing checks *and* were checking for the out vector size improperly.
Rewritten based on the actual behaviour in IOS.

IOS/ES: Fix GetTMDView

---

Source/Core/Common/FileSearch.cpp
Source/Core/Common/FileSearch.h
Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
Source/Core/DolphinWX/Config/InterfaceConfigPane.cpp
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/DolphinWX/Input/InputConfigDiag.cpp
Source/Core/VideoBackends/OGL/main.cpp
Source/Core/VideoCommon/HiresTextures.cpp

Gets them out of global scope.

FileSearch: Namespace functions under the Common namespace

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/HLE/HLE.cpp
Source/Core/Core/HLE/HLE.h
Source/Core/Core/PatchEngine.cpp
Source/Core/Core/PatchEngine.h

This fix a regression introduced by PR #4981 leading to the following issue: https://bugs.dolphin-emu.org/issues/10187.

Fix a regression when reloading a title

---

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp

Decided against doing anything fancy since they all were larger in codesize than this anyway.

Jit_LoadStore: Make dcbz PIE-compliant

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp

Introduced by c45028a7081f872e87c9d9b42f70f3086aa912f7.
Fixes https://github.com/dolphin-emu/dolphin/pull/5257#issuecomment-294267941.

JitArm64: Fix bugs introduced by #5257

---

Source/Core/Core/PowerPC/Jit64IL/IR_X86.cpp

Fixed casts and unnecessary trinaries.

IR_X86: Minor fixups

---

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp

EmuCodeBlock: Make CheckIfSafeAddress PIE-compliant

---

Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/FrameTools.cpp

This PR fixes [Issue 10213](https://bugs.dolphin-emu.org/issues/10213). I'm not sure if the way I implemented it is okay or not, but I'm willing to make changes if necessary.

Lazily initialize m_main_config_dialog to fix analytics issue (Issue #10213)

---

Data/Sys/GameSettings/GMPE01.ini

See [Issue #10197](https://bugs.dolphin-emu.org/issues/10197).

[Mario Party 4] Fix "All Mini Games Unlocked" AR Code (Issue #10197)

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFragmentPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/SettingsFile.java
Source/Android/app/src/main/res/values/strings.xml

Adds option to the settings menu.

Android: Add audio stretch setting

---

Source/Core/DolphinWX/MainMenuBar.cpp

Reorder the Tools menu.
As many options appeared, it had to be reordered a bit ;)

Reorder the Tools menu, with more separators

---

Source/Core/AudioCommon/DPL2Decoder.cpp

Just cleaning up, no behaviour change.

DPL2Decoder cleanup

---

Source/Core/Core/CoreTiming.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

JitArm64: Implement timer SPRs

---

Source/Core/DolphinWX/FrameTools.cpp

This PR allows debugging after a POWER/STOP button input.

DoStop() shouldn't unpause in debug mode

---

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp

JitArm64_SystemRegisters: Fix crXXX (set 32nd bit)

---

Source/Core/Core/HW/WiimoteCommon/WiimoteReport.h

I didn't catch the packing was changed in #5325 -- my bad. This should fix issues with emulated Wiimotes.

Fix emulated Wiimotes

---

Source/Core/DolphinWX/VideoConfigDiag.cpp
Source/Core/VideoBackends/D3D/main.cpp
Source/Core/VideoBackends/D3D12/main.cpp
Source/Core/VideoBackends/Null/NullBackend.cpp
Source/Core/VideoBackends/OGL/PostProcessing.h
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/OGL/main.cpp
Source/Core/VideoBackends/Vulkan/CMakeLists.txt
Source/Core/VideoBackends/Vulkan/ObjectCache.cpp
Source/Core/VideoBackends/Vulkan/ObjectCache.h
Source/Core/VideoBackends/Vulkan/PostProcessing.cpp
Source/Core/VideoBackends/Vulkan/PostProcessing.h
Source/Core/VideoBackends/Vulkan/RasterFont.cpp
Source/Core/VideoBackends/Vulkan/RasterFont.h
Source/Core/VideoBackends/Vulkan/Renderer.cpp
Source/Core/VideoBackends/Vulkan/Renderer.h
Source/Core/VideoBackends/Vulkan/Vulkan.vcxproj
Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
Source/Core/VideoCommon/PostProcessing.cpp
Source/Core/VideoCommon/PostProcessing.h
Source/Core/VideoCommon/VideoConfig.h

Nothing too fancy or any new features here, just bringing the Vulkan backend up to feature parity with OpenGL.

Vulkan: Implement support for post-processing

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This PR should prevent PPCAnalyst to trigger PanicAlert when analyzing function when not bootstrapped or in other cases causing potential invalid read.

PPCAnalyst: Prevent PanicAlert due to invalid read

---

Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp

Also remove some spaces before colons.

Mark "Host Code:" and "IP Address:" as translatable

---

Source/Core/DolphinWX/Debugger/MemoryWindow.cpp
Source/Core/DolphinWX/Debugger/MemoryWindow.h

Just basic housekeeping stuff. Each commit should be fairly self-explanatory.

MemoryWindow: Minor cleanup

---

Source/Core/DolphinQt2/GameList/GameTracker.cpp

Fixes a regression introduced by last-minute changes to my PR

Qt: Fix no games at all showing up all

---

Source/Core/Common/Arm64Emitter.cpp
Source/Core/Common/Arm64Emitter.h
Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp

"Fix" as in "estimate 1/x instead of 1/sqrt(x)" not as in "make it bit accurate" :P

JitArm64: fix ps_res

---

Source/Core/Common/Hash.cpp
Source/Core/Common/Hash.h

Haven't tried compiling the Android part, but according to degasus we already dropped GCC support on Android.

Common/Hash: small cleanup

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Source/Android/app/src/main/res/layout/activity_tv_main.xml

Whenever the EmulationActivity crashes and the app gets back to the
TvMainActivity, dolphin will crash tring to restor the mBrowseFragment
since we don't save the adapter data in the bundle.
This is quick hack to avoid the crash. The proper fix would be to save the
adapter data in the bundle and restore it before restoring the fragment
when the activity gets recreated.
Crash Stacktrace:
Process: org.dolphinemu.dolphinemu.debug, PID: 30353
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.dolphinemu.dolphinemu.debug/org.dolphinemu.dolphinemu.ui.main.TvMainActivity}: java.lang.IllegalArgumentException: Invalid position 1 requested
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2691)
at android.app.ActivityThread.handleLaunchActivity(ActivityThrea …

[Android] Fix crash on the Android TV

---

Source/Android/app/build.gradle
Source/Android/app/src/main/res/values/strings.xml
Source/Android/build.gradle

This change makes the user visible version string the same as what is displayed for desktop release builds (so atm it will be "5.0")

Android build files

---

Source/Core/DolphinWX/DolphinWX.vcxproj.filters

This PR fixes a mistake from [PR #4408](https://github.com/dolphin-emu/dolphin/pull/4408/files#diff-0d26dfb70cd60f536585f5ff54011bb4R449).

Fix DolphinWX.vcxproj.filters

---

Source/Core/Core/Boot/Boot.cpp

Brought up in https://github.com/dolphin-emu/dolphin/pull/5400#discussion_r116275508

Use console-appropriate SetupBAT when booting DOL files

---

Source/Core/Common/Config/Section.h
Source/Core/Core/ConfigLoaders/GameConfigLoader.cpp
Source/Core/Core/Core.vcxproj
Source/Core/Core/Core.vcxproj.filters

* MapINIToRealLocation and GetINILocationFromConfig were returning blank keys
* Section::Get has an incorrect implementation

Config: Minor fixups

---

Source/Core/Core/HW/DSPHLE/DSPHLE.cpp

Follow-up for #5306, as suggested by @Tilka.

DSPHLE: Typo fix

---

Source/Core/Core/PowerPC/PPCAnalyst.cpp

This PR enhances PPCAnalyst by detecting functions called via branch instructions (without link) and then fix an off by one instruction size if the maximum size is specified.

PPCAnalyst: Fix annoyances

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot_ELF.cpp

Use SetupBAT in Boot_ELF

---

Source/Core/DolphinQt2/Config/ControllersWindow.cpp
Source/Core/DolphinQt2/Config/ControllersWindow.h

Small PR that adds a minor feature that I previously forgot to implement.

Qt: Implement Wiimote Refresh button

---

Source/Core/DiscIO/Blob.h
Source/Core/DiscIO/Volume.cpp
Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DiscIO/VolumeWiiCrypted.cpp
Source/Core/DiscIO/WiiWad.cpp

More cleanup. We can simply put ReadSwapped directly in IBlobReader.

Remove CBlobBigEndianReader

---

Source/Core/DolphinQt2/Config/ControllersWindow.cpp

Thanks to @JosJuice for figuring this out.

Qt: Fix random crashes

---

Source/Core/DolphinQt2/Config/Mapping/WiimoteEmuMotionControl.cpp

Fixes a small labeling oversight of mine.

Qt: Fix Wii Motioncontrol button mapping labels

---

Source/Core/DolphinQt2/Main.cpp
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h

Adds a few missing analytics features to the DolphinQt2 frontend.

Qt: Implement analytics (+ prompt)

---

Source/Core/Core/IOS/ES/ES.cpp
Source/Core/Core/IOS/ES/ES.h
Source/Core/Core/IOS/ES/Formats.cpp
Source/Core/Core/IOS/ES/Formats.h
Source/Core/Core/IOS/ES/TitleManagement.cpp

Used by the Wii Shop in some cases. Implementing this also gets us closer to 100% completion.

IOS/ES: Implement ES_DeleteSharedContent

---

Source/Core/Core/ConfigManager.cpp

Otherwise, we may be missing some reports.

Analytics: Report game start on title change

---

Source/Core/DolphinQt2/Config/Mapping/MappingNumeric.cpp

Fixes a minor rounding error in the button mapping dialogs.

Qt: Fix rounding errors

---

Source/Core/Core/PowerPC/SignatureDB/SignatureDB.cpp
Source/Core/Core/PowerPC/SignatureDB/SignatureDB.h

Just fairly basic tiny changes

SignatureDB: Minor cleanup

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot.h
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Boot/Boot_ELF.cpp

Even more deduplication of this. Our boot code is very well designed /s

Use SetupBAT in Load_BS2

---

Source/Core/DolphinQt2/Settings/GeneralPane.cpp
Source/Core/DolphinQt2/Settings/GeneralPane.h
Source/Core/DolphinQt2/Settings/InterfacePane.cpp
Source/Core/DolphinQt2/Settings/InterfacePane.h

Adds the CPU Pane to settings: 
Notable differences:
- Dual-core is now called Multi-core. This is because Dolphin uses 3 cores (CPU, GPU, DSP), which is not 2.

Qt: Copy General Tab from WX

---

Source/Core/DolphinQt2/Settings/GeneralPane.cpp

Not sure why the lint script didn't catch this...

Qt: Fix code formatting

---

Tools/update-wiitdb.sh

After getting in touch with the GameTDB maintainer about using their databases, they have decided to implement a UNIQUE parameter so we don't need to deduplicate ourselves. This simplifies the script a bit.
Thanks to lustar for their help.

Tools: Simplify update-wiitdb.sh

---

Source/VSProps/QtCompile.props

Accompanying PR for https://github.com/dolphin-emu/ext-win-qt/pull/3

Update ext-win-qt submodule for Qt 5.8

---

Source/Core/VideoBackends/D3D/D3DState.h
Source/Core/VideoBackends/D3D/Render.cpp

Just a few things I noticed when doing #5234 earlier. The last one is the most important of the bunch.

D3D/Render: Minor cleanup

---

Source/Core/Core/IOS/Network/IP/Top.cpp

This PR fixes a crash in Netflix channel.

IP/Top: Use a constant for addrinfo size

---

Source/Core/VideoBackends/D3D/Render.cpp

Fix for loop in D3D Renderer ApplyState function

---

Source/Core/DolphinQt2/Resources.cpp

Adds @MayImilae's fancy new stars to Qt
**Depends on PR #5463**

Qt: Implement new, themed stars

---

Source/Core/Core/IOS/Network/IP/Top.cpp

Apparently, I messed up right before the merge of my previous PR https://github.com/dolphin-emu/dolphin/pull/5506#issuecomment-305536166 ><'. This one should actually fix the problem.

IP/Top: Properly fix GetAddrInfo

---

Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h

This is a follow up to #5516 to make Qt match WX.

Qt: Remove booting from the last path

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Common/GL/GLInterface/WGL.cpp
Source/Core/Core/HW/DVD/DVDInterface.cpp
Source/Core/Core/HW/EXI/BBA-TAP/TAP_Win32.h
Source/Core/Core/IOS/Network/Socket.cpp
Source/Core/DiscIO/CompressedBlob.cpp
Source/Core/DiscIO/WiiWad.cpp
Source/Core/DolphinQt2/Config/SettingsWindow.cpp
Source/Core/InputCommon/ControllerInterface/DInput/DInput.h
Source/UnitTests/Common/StringUtilTest.cpp

These were not caught by the lint script while it was broken.

Fix minor formatting issues

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/ConfigManager.h
Source/Core/DiscIO/Blob.h
Source/Core/DiscIO/DiscScrubber.cpp
Source/Core/DiscIO/FileSystemGCWii.cpp
Source/Core/DiscIO/FileSystemGCWii.h
Source/Core/DiscIO/Filesystem.h
Source/Core/DiscIO/Volume.cpp
Source/Core/DiscIO/Volume.h
Source/Core/DiscIO/VolumeDirectory.cpp
Source/Core/DiscIO/VolumeDirectory.h
Source/Core/DiscIO/VolumeGC.cpp
Source/Core/DiscIO/VolumeGC.h
Source/Core/DiscIO/VolumeWad.cpp
Source/Core/DiscIO/VolumeWad.h
Source/Core/DiscIO/VolumeWiiCrypted.cpp
Source/Core/DiscIO/VolumeWiiCrypted.h
Source/Core/DiscIO/WiiWad.cpp
Source/Core/DolphinQt2/GameList/GameFile.cpp
Source/Core/DolphinWX/ISOFile.cpp
Source/Core/DolphinWX/ISOProperties/InfoPanel.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/5530)

DiscIO: Use std::optional in Volume and Blob

---

Source/Core/Core/ConfigManager.cpp
Source/Core/Core/ConfigManager.h
Source/Core/DolphinQt2/RenderWidget.cpp
Source/Core/DolphinQt2/RenderWidget.h
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h
Source/Core/DolphinQt2/Settings/InterfacePane.cpp

Depends on #5504 for the Settings magic.

DolphinQt2: support hiding cursor over render window

---

Source/Core/DolphinQt2/GameList/GameListModel.h

DolphinQt2: reorder list columns to match DolphinWX

---

Source/Core/VideoCommon/RenderBase.cpp
Source/Core/VideoCommon/RenderBase.h

Extracted from #4992, as it's pretty orthogonal.

RenderBase: clean up UpdateDrawRectangle

---

Source/Core/Core/HW/WiimoteCommon/WiimoteReport.h
Source/Core/Core/HW/WiimoteEmu/Attachment/Guitar.cpp
Source/Core/Core/HW/WiimoteEmu/Attachment/Guitar.h
Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
Source/Core/DolphinWX/Input/GuitarInputConfigDiag.cpp

Implement slider bar present on GHWT and GH5 controllers

---

Source/Core/DiscIO/VolumeWii.cpp

Without this, we can end up in an inconsistent state where m_game_partition is set to a partition that isn't in the partition maps.

VolumeWii: Don't set m_game_partition until we know partition is valid

---

Source/Core/VideoBackends/Null/Render.cpp
Source/Core/VideoBackends/OGL/Render.cpp
Source/Core/VideoBackends/Software/SWRenderer.cpp
Source/Core/VideoBackends/Vulkan/Renderer.cpp
Source/Core/VideoCommon/VideoConfig.cpp
Source/Core/VideoCommon/VideoConfig.h

VideoConfig: Remove bRunning

---

Source/Core/Common/NandPaths.cpp
Source/Core/Common/StringUtil.cpp
Source/Core/Common/StringUtil.h
Source/Core/Core/ActionReplay.cpp
Source/Core/Core/ConfigManager.cpp
Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
Source/Core/Core/PatchEngine.cpp
Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp
Source/Core/DolphinWX/Debugger/CodeView.cpp
Source/Core/DolphinWX/FrameAui.cpp
Source/Core/InputCommon/ControllerInterface/Pipes/Pipes.cpp

StringUtil: Make SplitString return by value

---

Source/Core/DolphinWX/Main.cpp

This PR addresses the issue [#10333](https://bugs.dolphin-emu.org/issues/10333).
Ready to be reviewed and merged.

Silent GameList PNG warnings

---

Source/Core/DolphinQt2/Config/Mapping/MappingWidget.cpp
Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp
Source/Core/DolphinQt2/Config/Mapping/MappingWindow.h

Before: 
After: 
WX for reference:

Qt/MappingWindow: Update layout to match WX

---

Source/Core/DolphinQt2/Main.cpp

Pretty much the most important option to support, even for a UI frontend that's still a WIP. It's essential for testing.

Qt: Support custom user profile paths

---

Source/Core/Core/HW/WiimoteReal/IOWin.cpp

windows: fix handle leak when using continuous scan

---

Data/Sys/GameSettings/WYM.ini

The game is playable now, it just needs safe texture hashing.

GameSettings: update Yummy Yummy Cooking Jam

---

Source/Core/Common/Analytics.h

3 seconds is sometimes not enough.

Analytics: Set the timeout to 5 seconds

---

Source/Core/VideoBackends/D3D/DXTexture.h
Source/Core/VideoBackends/Null/NullTexture.h
Source/Core/VideoBackends/OGL/OGLTexture.h
Source/Core/VideoBackends/Software/SWTexture.h
Source/Core/VideoBackends/Vulkan/VKTexture.h
Source/Core/VideoCommon/AbstractTexture.cpp
Source/Core/VideoCommon/AbstractTexture.h

AbstractTexture: Minor changes

---

Source/Core/Core/FifoPlayer/FifoRecorder.cpp

Something I noticed when going through the core codebase in #5580 to look for headers to normalize/remove.
So, a FifoRecorder instance is instantiated as a file-local variable and used as a singleton (ugh). Since it's a file-local variable, this means it's allocating no matter what, since it's done in the constructor. FifoRecorder's internal RAM and ExRAM vectors are 33554432 and 67108864 bytes respectively, which is around 100.66MB in total. Most users likely don't regularly use the FIFO player/FIFO recorder at all, so this is kind of a substantial waste of memory
Just on the game list view on a clean build with nothing loaded, this knocks debug build memory usage down from ~232.4MB to ~137.5MB, and release build memory usage down from ~101MB to ~5.7MB on Windows.
Problem case: I'd like …

FifoRecorder: Don't allocate ~100.7MB on program startup

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp
Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp

The volume delta was being shifted twice.

DSPHLE: fix volume in NTSC IPL ucode

---

Source/Core/DolphinWX/ISOProperties/FilesystemPanel.cpp

Simpler, and puts the call to CheckIntegrity right where it should be, instead of being hidden somewhere in a thread class.
This also makes it more obvious what we're getting from the async task.
Oh, and coincidentally, this fixes a random crash that could occur during the check. I'm not sure why.

WX: Use std::future for checking disc integrity

---

Source/Core/Common/FileSearch.cpp

I was told this is "more correct", but tbh I'm not really sure if it matters for our use case.

Use CompareStringOrdinal in DoFileSearch instead of _wcsicmp

---

Source/Core/Common/FileSearch.cpp

FileSearch: Minor changes

---

Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MainWindow.h
Source/Core/DolphinWX/Frame.h
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/UICommon/UICommon.cpp
Source/Core/UICommon/UICommon.h

Allows games to safely shut down in Qt.

Qt: Implement safe shutdown

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/Config/SettingsWindow.cpp
Source/Core/DolphinQt2/Config/SettingsWindow.h
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/HotkeyScheduler.cpp
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h
Source/Core/DolphinQt2/Settings/AudioPane.cpp
Source/Core/DolphinQt2/Settings/AudioPane.h

Qt/Settings: Implement Audio tab

---

Source/Core/Common/CommonFuncs.cpp

Split off from #5411. We used to silently do something incorrect on systems where we got the GNU version by default.

Try to make sure that we have the XSI version of strerror_r

---

Source/Core/Common/FileSearch.cpp
Source/Core/DiscIO/Blob.h
Source/Core/DiscIO/Enums.cpp
Source/Core/DiscIO/Enums.h
Source/Core/DolphinWX/GameListCtrl.cpp
Source/Core/DolphinWX/GameListCtrl.h
Source/Core/DolphinWX/ISOFile.cpp
Source/Core/DolphinWX/ISOFile.h

More follow-up for the gamelist speedup PR

---

Source/Core/DiscIO/VolumeWii.cpp
Source/Core/DiscIO/VolumeWii.h

Having a separate map for each type of data is a bit unnecessary.

VolumeWii: Change the format of partition maps

---

Source/Core/DiscIO/FileSystemGCWii.cpp

Support leading slashes in FileSystemGCWii::FindFileInfo

---

Source/Core/Common/Assert.h

It's a bit confusing to get a yes/no dialogue box without any indication of what yes or no will do in this situation, so add a short explanatory sentence.
I also wanted a very small issue to work on to dip my toes into Dolphin.

Explain what Yes/No means in an assert window

---

Source/Core/DolphinQt2/InDevelopmentWarning.cpp

*Criticism and suggestions would be greatly appreciated.*

Qt: Make the "In Development" warning less threatening

---

Source/Core/DolphinWX/LogConfigWindow.cpp
Source/Core/DolphinWX/LogWindow.cpp
Source/Core/DolphinWX/LogWindow.h

I broke some things in #5764. Thanks to @mimimi085181 for finding them.

DolphinWX: fix logging crash + settings not being saved

---

Source/Core/Core/IOS/Network/KD/NetKDTime.cpp

This PR adds logs for kd/time IOCtls. I'm open to suggestions concerning the log messages.

NetKDTime: Log IOCtl

---

Tools/lint.sh

Now fails if any commands fail. I noticed that on the buildbot, the arguments to this script can be incorrect (somehow?) which can result in no lint checks happening but the buildbot still passing.

Tools/lint.sh: turn on Bash 'strict mode'

---

Source/Core/DolphinQt2/Main.cpp

"this" made sense when "Do you authorize..." was on the bottom, but it doesn't make sense when it's at the top.
Also removing unnecessary newlines.

DolphinQt2: Reword the analytics message

---

Data/Sys/GameSettings/G5S.ini
Data/Sys/GameSettings/G8M.ini
Data/Sys/GameSettings/GUT.ini
Data/Sys/GameSettings/R55.ini
Data/Sys/GameSettings/R59.ini

https://bugs.dolphin-emu.org/issues/10171
https://bugs.dolphin-emu.org/issues/10207
https://bugs.dolphin-emu.org/issues/10336
https://bugs.dolphin-emu.org/issues/10355
https://bugs.dolphin-emu.org/issues/10370
https://github.com/dolphin-emu/dolphin/pull/5726#discussion_r126879253

Update game INIs

---

Source/Core/DolphinQt2/Config/Mapping/GCKeyboardEmu.h
Source/Core/DolphinQt2/Config/Mapping/GCPadEmu.h
Source/Core/DolphinQt2/Config/Mapping/GCPadWiiU.h
Source/Core/DolphinQt2/Config/Mapping/WiimoteEmuExtension.h
Source/Core/DolphinQt2/Config/Mapping/WiimoteEmuGeneral.h
Source/Core/DolphinQt2/Config/Mapping/WiimoteEmuMotionControl.h
Source/Core/DolphinQt2/GameList/TableProxyModel.h

Apparently this was more widespread than I initially thought compared to #5824

DolphinQt2: Add missing include guards

---

Source/Core/DolphinQt2/Config/Graphics/GraphicsWidget.cpp
Source/Core/DolphinQt2/Config/Graphics/GraphicsWidget.h
Source/Core/DolphinQt2/Config/Mapping/GCKeyboardEmu.h
Source/Core/DolphinQt2/Config/Mapping/GCPadEmu.h
Source/Core/DolphinQt2/Config/Mapping/IOWindow.cpp
Source/Core/DolphinQt2/Config/Mapping/IOWindow.h
Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp
Source/Core/DolphinQt2/Config/Mapping/MappingWindow.h
Source/Core/DolphinQt2/Settings.h

Also removes an unnecessary include.

DolphinQt2: Remove unimplemented prototypes

---

Source/Core/DolphinQt2/Config/Mapping/GCPadEmu.h

Qt/Config: Remove unused members

---

Source/Core/Common/Logging/LogManager.cpp

LogManager: remove stand-alone semicolon

---

Externals/cubeb/CMakeLists.txt
Externals/cubeb/src/cubeb_jack.cpp
Externals/glslang/glslang/MachineIndependent/ParseHelper.h

Externals: Fix FreeBSD build

---

Source/Core/Common/TraversalClient.h
Source/Core/Core/HW/WiimoteReal/IOLinux.h
Source/Core/Core/HW/WiimoteReal/IOWin.cpp
Source/Core/Core/HW/WiimoteReal/IOdarwin.h
Source/Core/Core/HW/WiimoteReal/IOhidapi.h
Source/Core/Core/PowerPC/JitCommon/JitBase.h
Source/Core/DolphinQt2/Config/Graphics/GraphicsBool.h
Source/Core/DolphinQt2/Config/Graphics/GraphicsChoice.h
Source/Core/DolphinQt2/Config/Graphics/GraphicsSlider.h
Source/Core/DolphinQt2/Config/Mapping/MappingNumeric.h
Source/Core/DolphinQt2/WiiUpdate.cpp
Source/Core/DolphinQt2/WiiUpdate.h
Source/Core/DolphinWX/Debugger/DSPRegisterView.h
Source/Core/DolphinWX/Debugger/WatchView.h
Source/Core/DolphinWX/Frame.h
Source/Core/DolphinWX/ISOProperties/ISOProperties.h
Source/Core/DolphinWX/MemcardManager.h
Source/Core/VideoBackends/Software/SWRenderer.h
Source/Core/VideoBackends/Software/SWmain.cpp

Silences a few -Wextra-semi warnings in our code (the rest being in externals)

General: Remove unnecessary semicolons

---

Data/Sys/GameSettings/0000000100000002.ini
Data/Sys/GameSettings/HAB.ini

Otherwise, input fields do not update properly.

GameINI: Force safe texture cache for the System Menu and the shop

---

Source/Core/Core/Analytics.cpp

* per-pixel lighting
* usershader mode
* fast depth
* vertex rounding

Analytics: Report a few more video settings

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/Config/LoggerWidget.cpp
Source/Core/DolphinQt2/Config/LoggerWidget.h
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MainWindow.h
Source/Core/DolphinQt2/MenuBar.cpp
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h

Qt: Implement logging window

---

Source/Core/Core/Boot/Boot.cpp
Source/Core/Core/Boot/Boot.h
Source/Core/Core/Boot/Boot_BS2Emu.cpp
Source/Core/Core/Boot/Boot_WiiWAD.cpp

This gets rid of some cruft that's pointless now that VolumeDirectory is gone.

Emulated BS2 cleanup

---

Source/Core/InputCommon/GCAdapter.cpp

Calling `libusb_interrupt_transfer` stalls the emulation thread for up to 8 ms. The reason for this is that the USB polling done by the OS (every 8 ms) isn't in sync with the rumble commands.
This PR moves the `libusb_interrupt_transfer` used for the output endpoint to a thread, and sends the latest rumble data when it's available without interrupting the emulation.

Send rumble data to the adapter on a separate thread

---

Source/Android/jni/MainAndroid.cpp
Source/Core/Common/MsgHandler.cpp
Source/Core/Common/MsgHandler.h
Source/Core/DolphinQt2/Main.cpp
Source/Core/DolphinQt2/QtUtils/RunOnObject.h
Source/Core/DolphinWX/Main.cpp

This is the thing that pops up a message box when something goes wrong, or when you want to override a previously dumped file, etc.

Qt: register MsgAlertHandler

---

Languages/update-source-strings.sh
Languages/update-translated-strings.sh

update-source-strings.sh was already solving the same problem in the same way.

Handle update-translated-strings.sh being run from a different directory

---

Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp

ProgramShaderCache: Call glTexImage3D after glTexParameter

---

Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp
Source/Core/Core/IOS/SDIO/SDIOSlot0.h

This add support for SD protocol 2 while staying compatible with protocol 1.01.
Most of this is quite hacky, but it seems to be working well.
Because the original implementation was quite confusing I didn't touch most of the stuff I did not understand.

Add support for SDHC

---

Source/Core/VideoCommon/TextureCacheBase.cpp

I slowly realized these mistakes were my fault. 😳

VideoCommon: Fix typos in comments introduced by #5849

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/GameList/GameFile.cpp
Source/Core/DolphinQt2/GameList/GameFile.h
Source/Core/DolphinQt2/GameList/GameList.cpp
Source/Core/DolphinQt2/GameList/GameList.h
Source/Core/DolphinQt2/GameList/GameListModel.h
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MainWindow.h
Source/Core/DolphinQt2/MenuBar.cpp
Source/Core/DolphinQt2/MenuBar.h
Source/Core/DolphinQt2/NetPlay/GameListDialog.cpp
Source/Core/DolphinQt2/NetPlay/GameListDialog.h
Source/Core/DolphinQt2/NetPlay/MD5Dialog.cpp
Source/Core/DolphinQt2/NetPlay/MD5Dialog.h
Source/Core/DolphinQt2/NetPlay/NetPlayDialog.cpp
Source/Core/DolphinQt2/NetPlay/NetPlayDialog.h
Source/Core/DolphinQt2/NetPlay/NetPlaySetupDialog.cpp
Source/Core/DolphinQt2/NetPlay/NetPlaySetupDialog.h
Source/Core/DolphinQt2/NetPlay/PadMappingDialog.cpp
Source/Core/DolphinQt2/NetPlay/PadMappingDialog.h
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h

Ready to be reviewed and merged.
**Note: If DolphinQt crashes on startup, try starting it with the environment variable ``QT_NO_FT_CACHE`` set to ``1``.**

Qt: Implement Netplay

---

Source/Core/DiscIO/DiscExtractor.cpp
Source/Core/DiscIO/DiscScrubber.cpp
Source/Core/DiscIO/FileSystemGCWii.cpp
Source/Core/DiscIO/FileSystemGCWii.h
Source/Core/DiscIO/Volume.h
Source/Core/DiscIO/VolumeWii.cpp
Source/Core/DiscIO/VolumeWii.h

This is a fairly common operation, so let's make a utility function for it to cut down on code duplication.

DiscIO: Add a Volume::ReadSwappedAndShifted function

---

Source/Core/VideoCommon/UberShaderPixel.cpp

The switch statements in these functions appear to get transformed into an if..else chain on NVIDIA's OpenGL/Vulkan drivers (at least according to the IL asm), resulting in lower performance than the D3D counterparts. Transforming the switch into a binary tree of ifs can increase performance by up to 20%.
Marked WIP since it needs more testing, and we need to check the other vendors, as the switch may still be more efficient there.
I also have a version that uses shader subroutines instead of the switch statements, although this had similar performance with I'm guessing higher CPU overhead (as well as not working with Vulkan).

Ubershader optimizations for NVIDIA

---

Source/Core/Common/CommonFuncs.cpp
Source/Core/Common/CommonFuncs.h
Source/Core/Common/FileUtil.cpp
Source/Core/Common/MemArena.cpp
Source/Core/Common/MemoryUtil.cpp
Source/Core/Common/SDCardUtil.cpp

This PR prevents the wrong error code to be checked on Windows.

CommonFuncs: LastStrerrorString added

---

Source/Core/Common/FileUtil.cpp

Reverts dolphin-emu/dolphin#5939

Revert "Try to fix File::Copy with non-1024-byte aligned sizes"

---

Data/Sys/GameSettings/HA8.ini
Data/Sys/GameSettings/HA9.ini
Data/Sys/GameSettings/HBA.ini
Data/Sys/GameSettings/HBB.ini
Data/Sys/GameSettings/HBC.ini
Data/Sys/GameSettings/HBD.ini
Data/Sys/GameSettings/HBF.ini
Data/Sys/GameSettings/HBG.ini
Data/Sys/GameSettings/HBI.ini
Data/Sys/GameSettings/HBK.ini

Brawl ships with VC games that have their own ID and are different from the VC releases.

GameINI: Add INIs for Brawl VC games

---

Source/Core/DolphinQt2/Config/PropertiesDialog.cpp

Qt/PropertiesDialog: Make title more like Wx

---

Source/Core/Core/HW/WiimoteReal/IOWin.cpp

fail, my bad.
I have no idea how this didn't cause issues for more people.

WiimoteReal: Fix device handles not being closed

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Source/Android/jni/MainAndroid.cpp

This fits better as a function parameter than as global state.

MainAndroid: Remove s_filename

---

Source/Core/VideoCommon/CommandProcessor.h
Source/Core/VideoCommon/Fifo.cpp
Source/Core/VideoCommon/PixelEngine.cpp

Gets rid of some indirect inclusion.

CommandProcessor: Remove unnecessary include

---

Source/Core/VideoCommon/UberShaderPixel.cpp

Looks like I missed this in the ubershader PR, and it wasn't picked up by anyone else.
Should fix issue 10483: https://bugs.dolphin-emu.org/issues/10483

UberShaderPixel: Fix sampling of EFB copies in stereo modes

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/GameList/GameFile.cpp
Source/Core/DolphinQt2/GameList/GameFile.h
Source/Core/DolphinQt2/GameList/GameFileCache.cpp
Source/Core/DolphinQt2/GameList/GameFileCache.h
Source/Core/DolphinQt2/GameList/GameTracker.cpp
Source/Core/DolphinQt2/GameList/GameTracker.h

Qt: Implement gamelist caching

---

Source/Core/DolphinQt2/Config/FilesystemWidget.cpp
Source/Core/DolphinQt2/Config/FilesystemWidget.h
Source/Core/DolphinQt2/Config/PropertiesDialog.cpp

Ready to be reviewed and merged.

Qt/GameList: Implement "Filesystem" tab

---

Source/Core/Core/WiiUtils.cpp
Source/Core/DolphinQt2/Main.cpp

Fixes two -Wmissing-declarations warnings

Core: Fix warnings

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/CustomTitleView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Source/Android/app/src/main/res/layout/titleview.xml
Source/Android/app/src/main/res/layout/tv_title.xml
Source/Android/app/src/main/res/values/styles.xml

- Stop reading version number from native code and use the one from BuildConfig
- Show the version number on the title for the Android TV UI

[Android] Show the version number on the title for the Android TV UI

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableButton.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java
Source/Android/app/src/main/res/values/strings.xml

Android Studio wants to correct these automatically when editing files.

Remove trailing spaces from Android files

---

Source/Core/VideoBackends/Software/SWVertexLoader.cpp
Source/Core/VideoBackends/Software/SWVertexLoader.h

Each commit should be self-explanatory. Just does some minor cleanup/reorganizing of the class.

SWVertexLoader: Minor cleanup

---

Source/Core/DolphinQt2/GameList/GameList.cpp
Source/Core/DolphinQt2/GameList/GameListModel.cpp
Source/Core/DolphinQt2/GameList/GameListModel.h
Source/Core/DolphinQt2/MenuBar.cpp

* Add ``File Name`` column
* Change column naming to be more like Wx

Qt: Bring column selection up to par with Wx

---

Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/NetPlay/NetPlayDialog.cpp
Source/Core/DolphinQt2/QtUtils/QueueOnObject.h
Source/Core/DolphinQt2/QtUtils/RunOnObject.h

Simple, stupid, slightly nicer.

Qt QueueOnObject/RunOnObject: accept pointers to member functions

---

Source/Core/Core/IOS/Network/SSL.cpp
Source/Core/Core/IOS/Network/SSL.h

See: https://bugs.dolphin-emu.org/issues/10546

IOS/SSL: Show built-in cert error once per session

---

Source/Core/Core/DSP/DSPAccelerator.cpp

Fixes possible regression from #6069.

Fix sample wrapping with new DSP ADPCM decoding

---

Source/Core/DolphinQt2/Config/Graphics/GraphicsChoice.cpp

oops
cc @spycrab and @lioncash

[Qt] Fix bolding of GraphicsChoice.cpp

---

Source/Core/Core/DSP/DSPAccelerator.cpp
Source/Core/Core/DSP/DSPAccelerator.h
Source/Core/Core/DSP/DSPCore.cpp
Source/Core/Core/DSP/DSPCore.h
Source/Core/Core/DSP/DSPHWInterface.cpp
Source/Core/Core/DSP/DSPHWInterface.h
Source/Core/Core/DSP/Jit/DSPJitUtil.cpp
Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
Source/Core/Core/State.cpp
Source/DSPSpy/main_spy.cpp
Source/DSPSpy/tests/accelerator_loop_test.ds
Source/DSPSpy/tests/dsp_base.inc
Source/UnitTests/Core/CMakeLists.txt
Source/UnitTests/Core/DSP/DSPAcceleratorTest.cpp

A collection of small DSP accelerator fixes. Each commit is self contained and changes are explained in their respective commit messages.

Small DSP accelerator fixes

---

Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h

Cleans up the code and removes repeated calls to `GetProfileINIPath`

MappingWindow: store profile filename in QComboBox userdata

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/PlatformPagerAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/Game.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameDatabase.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainView.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/Platform.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/viewholders/TvGameViewHolder.java
Source/Android/app/src/main/res/drawable/tv_card_background_gamecube.xml
Source/Android/app/src/main/res/drawable/tv_card_background_wii.xml
Source/Android/app/src/main/res/drawable/tv_card_background_wiiware.xml

Minor cleanups, including making a proper GameCardView class (instead of an anonymous one), and creating a Platform enum.

Minor Android UI code cleanups

---

Source/Core/DolphinWX/Debugger/MemoryWindow.cpp

This PR rectifies the search result and adds the base address while using memory search.

MemoryWindow: base address search added

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java

This fixes a weird bug where the dpad up/down is swapped on the shield controller.

Android: refactor and bugfix for input settings

---

Source/Core/AudioCommon/AlsaSoundStream.cpp
Source/Core/AudioCommon/AlsaSoundStream.h
Source/Core/AudioCommon/AudioCommon.cpp
Source/Core/AudioCommon/AudioCommon.h
Source/Core/AudioCommon/NullSoundStream.cpp
Source/Core/AudioCommon/NullSoundStream.h
Source/Core/AudioCommon/OpenALStream.cpp
Source/Core/AudioCommon/OpenALStream.h
Source/Core/AudioCommon/SoundStream.h
Source/Core/AudioCommon/XAudio2Stream.cpp
Source/Core/AudioCommon/XAudio2Stream.h
Source/Core/AudioCommon/XAudio2_7Stream.cpp
Source/Core/AudioCommon/XAudio2_7Stream.h
Source/Core/Core/HW/CPU.cpp

AudioCommon: rename ClearAudioBuffer(mute) to SetSoundStreamRunning(running)

---

Source/Android/app/build.gradle
Source/Android/build.gradle
Source/Android/gradle/wrapper/gradle-wrapper.properties

Doing a simple version bump to the latest gradle version and plugin for building the android version

Android: Update gradle version to 4.1 and plugin to 3.0

---

Source/Core/DolphinQt2/AboutDialog.cpp
Source/Core/DolphinQt2/Config/FilesystemWidget.cpp
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MenuBar.cpp
Source/Core/DolphinQt2/Settings/AudioPane.cpp
Source/Core/DolphinWX/Cheats/GeckoCodeDiag.cpp
Source/Core/DolphinWX/Config/AdvancedConfigPane.cpp
Source/Core/DolphinWX/Config/AudioConfigPane.cpp
Source/Core/DolphinWX/Debugger/WatchView.cpp
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/DolphinWX/ISOProperties/ISOProperties.cpp

Most of the changes I've made here were because of small differences between DolphinWX and DolphinQt2.

Make GUI strings more consistent

---

Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
Source/Core/Core/WiiUtils.cpp

Core: Fix pragma pack usages.

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ControllerMappingHelper.java

Android reports the same physical axis multiple times for analog
triggers, and this handles this case.
There are also some controllers with broken mappings (eg the analog
triggers on a PS4 DualShock 4). This fixes them as well.

Android: Handle duplicate axis, and ignore known bad axis.

---

Source/Core/VideoCommon/TextureCacheBase.cpp

The neverending story!
While investigating why Mario Sunshine water doesn't trigger the mipmap fix (despite being obviously relying on mips for its effect) I found out a few things...
- Always inspect everything visually and dump all images. Always :P 
- Due to a pretty terrible typo in my old code, it was desaturating the expected mipmaps, then comparing them with saturated ones. That's why the differences were so high all the time! woops!
- Always downsampling the previous level wasn't strict enough - some textures gradually increased into something that had nothing to do with level 0. This is why Sunshine's water wasn't triggering the effect.
I've changed the detection to create the whole chain from mip0, so that if the last mip has nothing to do with the first, that's always …

Improved arbitrary mipmap detection (Mario Sunshine water fix)

---

Source/Core/Core/IOS/IOS.cpp

This should help us identify them and figure out which ones need to be fixed.
For example (haven't looked at which calls exactly just yet):
```
14:48:911 Core/IOS/IOS.cpp:519 W[IOS]: Previous request to device /dev/es blocked emulation for 43833 microseconds.
14:48:955 Core/IOS/IOS.cpp:519 W[IOS]: Previous request to device /dev/es blocked emulation for 43018 microseconds.
14:48:999 Core/IOS/IOS.cpp:519 W[IOS]: Previous request to device /dev/es blocked emulation for 43781 microseconds.
14:49:045 Core/IOS/IOS.cpp:519 W[IOS]: Previous request to device /dev/es blocked emulation for 45877 microseconds.
14:49:088 Core/IOS/IOS.cpp:519 W[IOS]: Previous request to device /dev/es blocked emulation for 43377 microseconds.
14:42:665 Core/IOS/IOS.cpp:519 W[IOS]: Previous request to device …
```

IOS: Warn on blocking IPC handlers.

---

Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinWX/FrameTools.cpp

Most users don't know what OTP/SEEPROM means.

Clarify the "Select the OTP/SEEPROM dump" message

---

Source/Core/VideoCommon/TextureConverterShaderGen.cpp

Instead of using colmat for all colours, rewrite most of them to use a simple swizzle in the shader.
This depends on #5882.

Simplify EFB copy shaders

---

Source/Core/DiscIO/WiiSaveBanner.cpp
Source/Core/DiscIO/WiiSaveBanner.h

WiiSaveBanner: Resolve a -Wreorder warning

---

Source/Core/DolphinWX/Main.cpp

Fixes issue [10685](https://bugs.dolphin-emu.org/issues/10685)

DolphinWX/Main: Fix shader compilation dialog translations

---

Source/Android/app/build.gradle
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/FileAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameDatabase.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesPresenter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_GCAdapter.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PermissionsHandler.java

Android supports Java 8 partially, this add the support and replace all anonymous class with lambdas or method reference where applicable. No changes in logic.
[for more details on what features from Java 8 android supports](https://developer.android.com/studio/write/java8-support.html#supported_features) 
one step toward less ugly java code :)

[Android] Enable Java 8 features in Dolphin Java code base

---

Source/Core/VideoCommon/RenderBase.cpp

Move frame advance and counter incrementing to only happen when we actually output a frame.

Video Common: frame logic fix

---

Source/Core/Common/BitField.h
Source/Core/Common/ChunkFile.h
Source/Core/VideoCommon/CommandProcessor.cpp
Source/Core/VideoCommon/CommandProcessor.h

https://bugs.dolphin-emu.org/issues/10002

Remove IsTriviallyCopyable hack for VS

---

Source/Core/VideoCommon/TextureConverterShaderGen.cpp

This finishes what #5887 started, and remove the last use of matrix multiplication in EFB copies.

Reimplement EFB copy for intensity formats

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFragmentPresenter.java

https://bugs.dolphin-emu.org/issues/10728

Fix default value for Show FPS in Android GUI

---

CMake/DolphinCompileDefinitions.cmake
Readme.md
Source/Core/DolphinQt2/Config/Graphics/SoftwareRendererWidget.cpp
Source/Core/DolphinQt2/Config/Graphics/SoftwareRendererWidget.h
Source/Core/DolphinWX/Config/WiiConfigPane.cpp
Source/Core/DolphinWX/SoftwareVideoConfigDialog.cpp
Source/Core/UICommon/CommandLineParse.cpp

Pulled from #6039. 
- Mention the purpose of the "Release" and "Debug" solution configurations
- Update -d argument help message (to match #6043)
- Grammar / consistency fixes
- Partially address https://bugs.dolphin-emu.org/issues/10563

Update Readme.md and various fixes

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/Debugger/BreakpointWidget.cpp
Source/Core/DolphinQt2/Debugger/BreakpointWidget.h
Source/Core/DolphinQt2/Debugger/NewBreakpointDialog.cpp
Source/Core/DolphinQt2/Debugger/NewBreakpointDialog.h
Source/Core/DolphinQt2/Debugger/RegisterColumn.cpp
Source/Core/DolphinQt2/Debugger/RegisterColumn.h
Source/Core/DolphinQt2/Debugger/RegisterWidget.cpp
Source/Core/DolphinQt2/Debugger/RegisterWidget.h
Source/Core/DolphinQt2/Debugger/WatchWidget.cpp
Source/Core/DolphinQt2/Debugger/WatchWidget.h
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/Main.cpp
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MainWindow.h
Source/Core/DolphinQt2/MenuBar.cpp
Source/Core/DolphinQt2/MenuBar.h
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h
Source/Core/DolphinQt2/Settings/InterfacePane.cpp
Source/Core/DolphinQt2/Settings/InterfacePane.h

This implements
- Windows
- Registers
- Watch
- Breakpoints
- Interface
- Add ability to enable / disable debugging from the interface tab
**The rest will be implemented in a later PR**

Qt: Implement Debugger (part 1 of ∞)

---

Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MainWindow.h
Source/Core/DolphinWX/Frame.cpp
Source/Core/DolphinWX/Frame.h
Source/Core/DolphinWX/FrameTools.cpp
Source/Core/UICommon/UICommon.cpp
Source/Core/UICommon/UICommon.h

Qt: Toggle Screensaver

---

Source/Core/Core/Core.cpp

Suggested by https://github.com/dolphin-emu/dolphin/pull/6271#discussion_r159868704

Don't involve host thread when booting from savestate

---

Data/Sys/GameSettings/GSN.ini

Works around https://bugs.dolphin-emu.org/issues/10776

[INI] Force Single Core mode in Sonic Adventure 2 Battle

---

Source/Core/VideoCommon/VertexManagerBase.cpp

We want to get the same mipmap level. And if the IR and the custom
texture upscaling fits, we don't need to modify the LOD bias.

VideoCommon: Apply custom texture scale for arbitrary mipmaps.

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/Config/ARCodeEditor.cpp
Source/Core/DolphinQt2/Config/ARCodeEditor.h
Source/Core/DolphinQt2/Config/ARCodeWidget.cpp
Source/Core/DolphinQt2/Config/ARCodeWidget.h
Source/Core/DolphinQt2/Config/PropertiesDialog.cpp
Source/Core/DolphinQt2/DolphinQt2.vcxproj

Qt: Implement "AR Codes"

---

Source/Android/build.gradle

Update the Android Gradle plugin to version 3.0.1

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
Source/Android/app/src/main/res/menu/menu_emulation.xml
Source/Android/app/src/main/res/values/strings.xml
Source/Android/jni/MainAndroid.cpp

Tested on Shield TV. Still needs to be verified on mobile devices.
@JosJuice :)

Android: Support change disc

---

Source/Core/DolphinQt2/HotkeyScheduler.cpp
Source/Core/DolphinQt2/HotkeyScheduler.h
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MainWindow.h
Source/Core/DolphinQt2/MenuBar.cpp
Source/Core/DolphinQt2/MenuBar.h

Implement ``Tools -> Connect Wii Remotes``.

Qt: Implement "Connect Wii Remotes" menu

---

Source/Core/Core/PowerPC/PPCSymbolDB.cpp

This PR adds support for two columns symbol maps like the Super Smash Bros. Brawl Korean one.
Regarding RSBK the symbol map doesn't have a section header (.text) and has symbols like :
```800107a8 DrawNonShadowBorder/[@unnamed@gf_3d_scene_cpp@]/(gf_3d_scene.o)```
This PR doesn't deal with the missing header but just with the two columns format issue.
At least, the symbol map now loads if the ".text" section header is added. 

PPCSymbolDB: two columns symbol map support added

---

Source/Core/DolphinQt2/Settings/GameCubePane.cpp

Fixes the bug mentioned in [this forum post](https://forums.dolphin-emu.org/Thread-dolphin-qt-not-remembering-memory-card-location).
Should fix [issue #10848](https://bugs.dolphin-emu.org/issues/10848) as well.

Qt/GameCubePane: Various fixes

---

Source/Core/DolphinQt2/Settings/GameCubePane.cpp

`absolutePath()` != `absoluteFilePath()` 🤦‍

Qt/GameCubePane: Fix file selection

---

Source/Core/DolphinQt2/Debugger/NewBreakpointDialog.cpp

Fixes [issue 10855](https://bugs.dolphin-emu.org/issues/10855).

Qt/NewBreakpointDialog: Fix radio button weirdness

---

Source/Core/DolphinQt2/MainWindow.cpp

Praying to the Qt gods this doesn't break literally everything.

Qt: Work around broken drivers that don't allow backend switching

---

Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp

Fix a `select()` and a fd leak.

evdev: Minor fixes

---

Data/Sys/GameSettings/GP3.ini

This fixes the menu screen which is shown incorrectly with Ignore Format Changes enabled:

GameINI: Fix menu in the polar express

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/Config/SettingsWindow.cpp
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/Settings/USBDeviceAddToWhitelistDialog.cpp
Source/Core/DolphinQt2/Settings/USBDeviceAddToWhitelistDialog.h
Source/Core/DolphinQt2/Settings/WiiPane.cpp
Source/Core/DolphinQt2/Settings/WiiPane.h

Rebased and updated based on #5804.

Qt: Implement Wiimote pane

---

Source/Core/DolphinQt2/GCMemcardManager.cpp

**Before:**
**After (Updated):**

Qt/GCMemcardManager: Misc. improvements

---

Source/Core/Core/IOS/VersionInfo.cpp

A slightly oversight from: https://github.com/dolphin-emu/dolphin/pull/6374

ES: Make it not fail on something that isn't IOS

---

Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/Config/Mapping/MappingButton.cpp
Source/Core/DolphinQt2/Config/Mapping/MappingButton.h
Source/Core/DolphinQt2/Config/Mapping/MappingIndicator.cpp
Source/Core/DolphinQt2/Config/Mapping/MappingIndicator.h
Source/Core/DolphinQt2/Config/Mapping/MappingWidget.cpp
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/Host.cpp
Source/Core/DolphinQt2/Settings.cpp
Source/Core/DolphinQt2/Settings.h

**Outdated**
Implements the fancy controller indicators from Wx, might require some overhauls before it can get merged.

Qt/Mapping: Implement indicators

---

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableJoystick.java

Brings joystick behavior more in line with the Android "standard" on screen joystick behavior. You can touch any part of the joystick image and it will center on where you touched instead of snapping to wherever it is relative to the center of the stick. This makes many games MUCH more playable in practice using touch controls.

Android: Make on-screen joysticks center on the initial touch input.

---

Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp

This was causing a large number of bad_p_nnn.txt files to be created on disk, from warnings alone. Some drivers are more verbose than others here.
Warnings are still logged as before.

OGL: Only create bad shader files in Dump when compile failed

---

Source/Core/DolphinWX/FrameTools.cpp

This fixes a regression introduced by de632fc9c.

Fix render surface when using Render to Main and debugger (regression fix)

---

CMakeSettings.json

Fixes https://bugs.dolphin-emu.org/issues/10559

Fix CMakeSettings buildRoot

---

Source/Core/DolphinQt2/Config/ARCodeWidget.h
Source/Core/DolphinQt2/Config/GeckoCodeWidget.h

Qt: Make game revision vars u16

---

Source/Core/DolphinQt2/GameList/GameList.cpp

This makes the ``Description``, ``Maker`` and ``Filename`` Section resizable.

Qt/GameList: Make a few columns resizable

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/Config/GameConfigWidget.cpp
Source/Core/DolphinQt2/Config/GameConfigWidget.h
Source/Core/DolphinQt2/Config/PropertiesDialog.cpp
Source/Core/DolphinQt2/DolphinQt2.vcxproj

Qt/PropertiesDialog: Add "Game Config" tab

---

Source/Core/DolphinQt2/DolphinQt2.vcxproj

Same problem as with PR #6283.

Fix launching DolphinQt2 from Visual Studio

---

Source/Core/Core/PowerPC/BreakPoints.cpp

Trims the direct usages of the global by making the code go through the JIT interface (where it should have been going in the first place).
This also removes direct JIT header dependencies from the breakpoints code as well. Now, no code uses the JIT global other than JIT code itself and the unit tests.

Breakpoints: Remove direct usages of the JIT global

---

Source/Core/DolphinQt2/MenuBar.cpp
Source/Core/DolphinWX/Debugger/CodeView.cpp
Source/Core/DolphinWX/ISOProperties/ISOProperties.cpp

Reduces the number of strings to translate.

Make strings more consistent between DolphinWX and DolphinQt2

---

Source/Core/DolphinQt2/Config/Graphics/GraphicsWindow.cpp
Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp
Source/Core/DolphinQt2/Config/PropertiesDialog.cpp
Source/Core/DolphinQt2/QtUtils/WrapInScrollArea.cpp
Source/Core/DolphinQt2/QtUtils/WrapInScrollArea.h

Qt: Improve spacing again

---

Source/Core/DolphinQt2/CMakeLists.txt
Source/Core/DolphinQt2/DolphinQt2.vcxproj
Source/Core/DolphinQt2/GameList/GameList.cpp
Source/Core/DolphinQt2/GameList/GameList.h
Source/Core/DolphinQt2/GameList/GameListModel.cpp
Source/Core/DolphinQt2/GameList/GameListModel.h
Source/Core/DolphinQt2/MainWindow.cpp
Source/Core/DolphinQt2/MainWindow.h
Source/Core/DolphinQt2/MenuBar.cpp
Source/Core/DolphinQt2/MenuBar.h
Source/Core/DolphinQt2/SearchBar.cpp
Source/Core/DolphinQt2/SearchBar.h

Adds the ability to search through your gamelist.
The searchbar can be opened / closed using:
* ``View -> Search``
* ``Ctrl + F``
It's still fairly basic at the moment (no fancy filters or anything).

Qt: Implement search

---

Source/Core/VideoBackends/Vulkan/VideoBackend.h

**Do not use this thread as a means to report bugs. Report them here.** [https://bugs.dolphin-emu.org](https://bugs.dolphin-emu.org
)
\<JMC47> Helios747: can you make a PR to remove experimental from teh vulkan backend
\<JMC47> people are talking shit about it being experimental on reddit and how it's not done
\<Helios747> Stenzek, are you cool with removing experimental from the Vulkan backend?
\<Helios747> It's primarily your work
\<Stenzek> Helios747: Sure, I guess

[UI] Remove experimental tag from Vulkan
