Source/Core/DolphinQt2/MainWindow.cpp
=> Qt/MainWindow: Remove obnoxious border

Source/Core/DolphinQt2/Debugger/CodeWidget.cpp, Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MainWindow.h, Source/Core/DolphinQt2/RenderWidget.cpp, Source/Core/DolphinQt2/RenderWidget.h
Fixes fullscreen crashes and should fix [issue #10951](https://dolp.in/i10951)
=> Qt: Fix fullscreen

Source/Core/DolphinQt2/MainWindow.cpp
Fixes Qt prompting you whether you want to quit when entering fullscreen.
=> Qt: Fix fullscreen quitting

Source/Core/DolphinQt2/CMakeLists.txt, Source/Core/DolphinQt2/DolphinQt2.vcxproj, Source/Core/DolphinQt2/Main.cpp, Source/Core/DolphinQt2/Settings.cpp, Source/Core/DolphinQt2/Settings.h, Source/Core/DolphinQt2/Settings/GeneralPane.cpp, Source/Core/DolphinQt2/Settings/GeneralPane.h, Source/Core/DolphinQt2/Updater.cpp, Source/Core/DolphinQt2/Updater.h, Source/Core/UICommon/AutoUpdate.cpp, Source/Core/UICommon/AutoUpdate.h
=> Qt: Improve and better integrate updater

Source/Core/Common/CMakeLists.txt
Continues the migration work that was started in 3a4c3bbe01e7a44ec997f4fbf0b678fba6f2d46c
=> Common/CMakeLists: Migrate off add_dolphin_library

Source/Core/InputCommon/CMakeLists.txt
Continues the migration work started in 3a4c3bbe01e7a44ec997f4fbf0b678fba6f2d46c
=> InputCommon/CMakeLists: Migrate off add_dolphin_library

Source/Core/DolphinQt2/Config/ControllersWindow.cpp, Source/Core/DolphinQt2/Config/Graphics/GraphicsWindow.cpp, Source/Core/DolphinQt2/Config/Graphics/GraphicsWindow.h, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt2/Config/PropertiesDialog.cpp, Source/Core/DolphinQt2/Config/SettingsWindow.cpp, Source/Core/DolphinQt2/GCMemcardManager.cpp
This PR replaces the "OK" buttons in dialogues with "Close" buttons.
=> Qt: Replace "OK" with "Close" buttons

Source/Core/Common/x64Emitter.h
These should all be fairly self-contained.
=> x64Emitter: Minor cleanup and changes

Source/Core/Updater/Main.cpp
The updater will now show a message box if a fatal error occurs and the update failed.
=> Updater: Provide basic user feedback

Source/Core/DolphinQt2/Debugger/CodeWidget.cpp, Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MenuBar.cpp, Source/Core/DolphinQt2/NetPlay/MD5Dialog.cpp, Source/Core/DolphinQt2/Resources.cpp, Source/Core/DolphinQt2/SearchBar.cpp, Source/Core/DolphinQt2/SearchBar.h, Source/Core/DolphinQt2/Settings/WiiPane.cpp
Also makes some slight other modifications which can be done local to their own files.
=> DolphinQt: Remove a few unused variables

Source/Core/VideoCommon/CMakeLists.txt
Continues the migration work started in 3a4c3bbe01e7a44ec997f4fbf0b678fba6f2d46c
=> VideoCommon/CMakeLists: Migrate off add_dolphin_library

Source/Core/DolphinQt2/Settings/GeneralPane.cpp
Fixes [issue #10970](https://bugs.dolphin-emu.org/issues/10970) for real this time.
=> GeneralPane: Fix settings resetting and improve code

Source/Android/app/build.gradle, Source/Android/build.gradle, Source/Android/gradle/wrapper/gradle-wrapper.properties
Fixes
[Release Notes](https://developer.android.com/studio/releases/gradle-plugin.html)
=> Android: Updates for Android Studio 3.1

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/DSP/DSPAssembler.cpp, Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp, Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/Core/PowerPC/PPCAnalyst.cpp
Unused, old code that is intended to be removed should not be left in comments -- that is what version control is for.
=> Remove dead code

Source/Core/DolphinQt2/Config/Graphics/GraphicsWindow.cpp
Before: ![Before](https://i.imgur.com/oClB3yN.png)
After: ![After](https://i.imgur.com/FyESuDn.png)
=> Qt/GraphicsWindow: Decrease description box size

Source/Core/Core/IOS/Network/Socket.h
Fairly minor tidying/correctness changes
=> IOS/Socket: Minor changes to WiiSocket

Source/Core/DolphinQt2/CMakeLists.txt, Source/Core/DolphinQt2/Debugger/BreakpointWidget.h, Source/Core/DolphinQt2/Debugger/CodeWidget.h, Source/Core/DolphinQt2/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt2/Debugger/MemoryViewWidget.h, Source/Core/DolphinQt2/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt2/Debugger/MemoryWidget.h, Source/Core/DolphinQt2/DolphinQt2.vcxproj, Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MainWindow.h, Source/Core/DolphinQt2/MenuBar.cpp, Source/Core/DolphinQt2/MenuBar.h, Source/Core/DolphinQt2/Settings.cpp, Source/Core/DolphinQt2/Settings.h
=> Qt/Debugger: Implement "Memory" widget

Source/Core/DolphinQt2/Config/Mapping/GCPadEmu.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingButton.h, Source/Core/DolphinQt2/Config/Mapping/MappingWidget.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWidget.h, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.h
Adds the ability to quickly assign all buttons without having to select them one after the other.
=> Qt/Mapping: Implement "Iterative Input"

Source/Core/Core/PowerPC/PPCAnalyst.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h
Fairly basic self-contained cleanups
=> PPCAnalyst: Minor cleanup

Source/Core/Core/HW/DVD/DVDInterface.cpp, Source/Core/Core/HW/ProcessorInterface.cpp, Source/Core/Core/HW/ProcessorInterface.h
=> DVDInterface: Deduplicate code in UpdateInterrupts()

Source/Core/DolphinQt2/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt2/Debugger/BreakpointWidget.h, Source/Core/DolphinQt2/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt2/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt2/Debugger/WatchWidget.cpp, Source/Core/DolphinQt2/Debugger/WatchWidget.h, Source/Core/DolphinQt2/ToolBar.cpp
=> Qt: Use new debugger icons

Source/Core/DolphinQt2/RenderWidget.cpp
=> Qt: Fix render size not matching window size

Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/PowerPC.h
This PR added HostRead/Write functions for floating points.
Ready to be review & merged.
=> PowerPC: HostR/W float/double added

Source/Core/DolphinQt2/CMakeLists.txt, Source/Core/DolphinQt2/CheatsManager.cpp, Source/Core/DolphinQt2/CheatsManager.h, Source/Core/DolphinQt2/Config/ARCodeWidget.cpp, Source/Core/DolphinQt2/Config/ARCodeWidget.h, Source/Core/DolphinQt2/Config/CheatWarningWidget.cpp, Source/Core/DolphinQt2/Config/CheatWarningWidget.h, Source/Core/DolphinQt2/Config/GeckoCodeWidget.cpp, Source/Core/DolphinQt2/Config/GeckoCodeWidget.h, Source/Core/DolphinQt2/DolphinQt2.vcxproj, Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MainWindow.h, Source/Core/DolphinQt2/MenuBar.cpp, Source/Core/DolphinQt2/MenuBar.h
Implements the "Cheats Manager" in Qt.
=> Qt: Implement Cheats Manager

Source/Android/build.gradle
=> Update Android Gradle Plugin

Source/Core/DolphinQt2/Config/Graphics/GeneralWidget.cpp, Source/Core/DolphinQt2/RenderWidget.cpp, Source/Core/DolphinQt2/RenderWidget.h, Source/Core/DolphinQt2/Settings.cpp, Source/Core/DolphinQt2/Settings.h, Source/Core/DolphinQt2/Settings/InterfacePane.cpp
Fixes [issue #11015](https://bugs.dolphin-emu.org/issues/11015).
=> Qt: RenderWidget fixes

Source/Core/DolphinQt2/Config/CheatCodeEditor.cpp, Source/Core/DolphinQt2/Config/GeckoCodeWidget.cpp
* Fix crashes when entering certain invalid gecko codes
* Fix the remove button not doing anything
=> Qt/GeckoCode: Fix multiple bugs

Source/Core/Core/IOS/Network/IP/Top.cpp
Allows the HBC to initialise network properly.
Also fixes [issue 7256](https://bugs.dolphin-emu.org/issues/7256).
=> IOS: Network fixes

Source/Core/DolphinQt2/Config/Mapping/MappingNumeric.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingNumeric.h
Fixes [issue #11029](https://bugs.dolphin-emu.org/issues/11029).
=> Qt/MappingNumeric: Calculate values properly

Source/Core/Core/IOS/Network/IP/Top.cpp
Move them closer to their usage and fix the naming.
=> IOS/SO: Clean up variable declarations

Source/Core/DolphinQt2/CheatsManager.cpp, Source/Core/DolphinQt2/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt2/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt2/Debugger/RegisterWidget.cpp
=> Qt: Minor changes

Source/Core/DolphinQt2/Settings/PathPane.cpp, Source/Core/DolphinQt2/Settings/PathPane.h
Fixes [issue #11034](https://bugs.dolphin-emu.org/issues/11034) among other things.
=> Qt/PathPane: Various fixes

Source/Core/DolphinQt2/Config/Graphics/GeneralWidget.cpp, Source/Core/DolphinQt2/Config/Graphics/GeneralWidget.h, Source/Core/DolphinQt2/Settings/InterfacePane.cpp, Source/Core/DolphinQt2/Settings/InterfacePane.h
Fixes [issue #11017](https://bugs.dolphin-emu.org/issues/11017).
=> Qt: Deduplicate settings

Source/Core/DolphinQt2/Config/Graphics/GeneralWidget.cpp
Fixes [issue #11043](https://bugs.dolphin-emu.org/issues/11043).
=> Qt/GraphicsSettings: Save Adapter index

Source/Core/DolphinQt2/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWidget.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWidget.h, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.h
Fixes [issue #11052](https://bugs.dolphin-emu.org/issues/11052) and [issue #11051](https://bugs.dolphin-emu.org/issues/11051).
=> Qt: Mapping fixes

Source/Core/Core/ConfigManager.cpp
Make sure that all our development build users are on beta...
=> Core/ConfigManager: Rename Track to UpdateTrack

Source/Core/Updater/Main.cpp
Fixes a regression introduced by #6694.
=> Updater: Fix UI not showing up

Source/Core/VideoCommon/TextureConversionShader.cpp
What the title says. I can't test this at the moment, but potentially on the weekend. If anyone wants to check first, that would be appreciated.
=> TextureConversionShader: Fix more implicit conversion errors

Source/Core/DolphinQt2/Config/Graphics/GraphicsSlider.cpp
[Fixes #11061](https://bugs.dolphin-emu.org/issues/11061).
=> Qt/GraphicsSlider: Fix random crashes

Source/Core/DolphinQt2/Config/ControllersWindow.cpp
This is important if we ever add or delete SI devices.
=> DolphinQt2: Don't crash on invalid SI devices

Source/Core/DolphinQt2/Config/Mapping/MappingButton.cpp
I screwed up again - what a suprise!
=> Qt/MappingButton: Fix bad range default

Source/Core/DolphinQt2/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt2/Config/Graphics/AdvancedWidget.h, Source/Core/DolphinWX/VideoConfigDiag.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureCacheBase.h
Not sure if this is worth merging, but it can be useful for debugging purposes.
=> UI: Add Disable EFB Copies to VRAM to Advanced Options

Source/Core/DolphinQt2/Config/Graphics/AdvancedWidget.cpp
Fixes [issue #11069](https://bugs.dolphin-emu.org/issues/11069)
=> Qt/AdvancedWidget: Fix progressive scan checkbox

Source/Core/DolphinQt2/Config/Graphics/GraphicsBool.cpp, Source/Core/DolphinQt2/Config/Graphics/GraphicsChoice.cpp, Source/Core/DolphinQt2/Config/Graphics/GraphicsRadio.cpp
Fixes more random crashes caused by GraphicsControls.
=> Qt/GraphicsControls: Fix more random crashes

Source/Core/DolphinQt2/QtUtils/WrapInScrollArea.cpp, Source/Core/DolphinQt2/Settings/AudioPane.cpp, Source/Core/DolphinQt2/Settings/GeneralPane.cpp, Source/Core/DolphinQt2/Settings/InterfacePane.cpp, Source/Core/DolphinQt2/Settings/PathPane.cpp, Source/Core/DolphinQt2/Settings/WiiPane.cpp
Fixes [issue #11048](https://bugs.dolphin-emu.org/issues/11048) and some other stuff.
=> Qt: Fix visual inconsistencies.

Source/Core/DolphinQt2/CheatsManager.cpp, Source/Core/DolphinQt2/Config/Mapping/GCPadWiiUConfigDialog.cpp, Source/Core/DolphinQt2/Config/Mapping/IOWindow.cpp, Source/Core/DolphinQt2/Config/NewPatchDialog.cpp, Source/Core/DolphinQt2/Config/PropertiesDialog.cpp, Source/Core/DolphinQt2/FIFOPlayerWindow.cpp, Source/Core/DolphinQt2/GCMemcardManager.cpp, Source/Core/DolphinQt2/NetPlay/MD5Dialog.cpp, Source/Core/DolphinQt2/NetPlay/NetPlaySetupDialog.cpp, Source/Core/DolphinQt2/TAS/GCTASInputWindow.cpp, Source/Core/DolphinQt2/TAS/WiiTASInputWindow.cpp
Removes the ``?``-Button from dialogues as we don't use them.
=> Qt: Remove "What's this" button

Source/Core/DolphinQt2/Main.cpp
It does look quite a bit better.
=> Qt/Win32: Force Segoe UI

Source/Core/DolphinQt2/Main.cpp
Combines the improved font of #6756 with not ignoring users font settings.
*Note: Qt should do this by default but doesn't* :cry:
=> Qt/Win32: Use better method to obtain the default font

Source/Core/VideoBackends/OGL/FramebufferManager.cpp
=> OGL/FramebufferManager: Clean up inline GLSL code

Source/Core/VideoBackends/OGL/FramebufferManager.cpp
Regression from #6646, as shown in fifoci: https://fifoci.dolphin-emu.org/version/e31c571f5162b90f8df7eeefd65008a1e2995f17/
=> OGL: Fix broken format changes in i965 driver

Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MainWindow.h
Fixes [issue #11073](https://bugs.dolphin-emu.org/issues/11073).
=> Qt: Implement custom fullscreen resolution support

Source/Core/DolphinQt2/Config/Graphics/GeneralWidget.cpp
Fixes
* "Render To Main" not being saved properly
* "Auto-adjust window size" not being saved properly
=> Qt/GeneralWidget: Various fixes

Source/Core/DolphinQt2/HotkeyScheduler.cpp, Source/Core/DolphinQt2/HotkeyScheduler.h, Source/Core/DolphinQt2/MainWindow.cpp
Implements the following hotkeys:
* Open
* Eject Disc
* Change Disc
=> Qt: Implement missing hotkeys

Source/Core/DolphinQt2/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt2/NetPlay/NetPlayDialog.h
=> Qt/NetPlayDialog: Multiple improvements

Source/Core/DolphinQt2/HotkeyScheduler.cpp, Source/Core/DolphinWX/Frame.cpp, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/RenderBase.h
As promised, my refactor of the ugly ``OSDChoice`` global variable.
=> VideoCommon/RenderBase: Refactor OSD messages

Source/Core/DolphinQt2/HotkeyScheduler.cpp
=> Qt/HotkeyScheduler: Use onion config

Source/Core/DolphinQt2/Config/Mapping/MappingButton.cpp
Fixes [issue #11086](https://bugs.dolphin-emu.org/issues/11086).
=> Qt/MappingButton: Fix occasionally broken indicator

Source/Core/DolphinQt2/NetPlay/NetPlayDialog.cpp
Getting the local IP address was broken by #6805.
=> Qt/NetPlayDialog: Fix broken IP label

Source/Core/Common/SDCardUtil.cpp, Source/Core/Common/SDCardUtil.h, Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp
Makes a few minor cleanup changes to SDCardUtil. Gets rid of a usage of IOFile's GetHandle() function, and also brings the header under the Common namespace.
=> SDCardUtil: Minor changes

Source/Core/DolphinQt2/HotkeyScheduler.cpp, Source/Core/DolphinQt2/HotkeyScheduler.h, Source/Core/DolphinQt2/MainWindow.cpp
Fixes [issue #11110](https://bugs.dolphin-emu.org/issues/11110).
=> Qt: Implement "Reset" hotkey

Source/Core/Core/IOS/Network/IP/Top.cpp
Rebase of #6811, which I closed by mistake during a failed rebase
---
This change makes dolphin pass the system's namespace resolver address on Linux to the Wii instead of the hard coded Google ones.
Google's DNS is still there as the backup.
Tested on Linux
Didn't try building on windows (No dev setup) but it should work as almost everything is in ifdefs.
This patch is mainly useful so that you can redirect dns requests from the Wii for testing.
Proper behavior would probably be to follow the settings the Wii sets up but I'm not sure where it keeps that setting. (wiibrew might have it documented somewhere)
=> Use resolver to get default DNS nameserver

Source/Core/Core/HW/GCMemcard/GCMemcard.cpp, Source/Core/DolphinQt2/GCMemcardManager.cpp
Fixes [issue #11095](https://bugs.dolphin-emu.org/issues/11095).
=> Qt/GCMemcardManager: Fix multiple issues

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Given we already know at the start of the loop which entry we need, we don't need to keep indexing into the buffer all the time. This moves the dependency on the buffer itself to one spot, which will be important for a future PR, since it'll make replacing the `PPCAnalyst::CodeBuffer` class with a `std::vector` alias less painful (CodeBuffer is essentially a poor-man's-vector, since it just `new`s a block of memory and `delete[]`s it in the destructor. It does nothing else of importance).
=> Jit/CachedInterpreter: Minor cleanup to code buffer accesses

Source/Core/DolphinQt2/Config/FilesystemWidget.cpp, Source/Core/DolphinQt2/GameList/GameList.cpp, Source/Core/DolphinQt2/NetPlay/PadMappingDialog.cpp, Source/Core/DolphinQt2/Updater.cpp
* Remove some more "What's this?" buttons
* Add some missing titles
=> Qt: Minor window fixes

Source/Core/DolphinQt2/Config/SettingsWindow.cpp, Source/Core/DolphinQt2/Settings/AdvancedPane.cpp, Source/Core/DolphinQt2/Settings/AudioPane.cpp, Source/Core/DolphinQt2/Settings/InterfacePane.cpp, Source/Core/DolphinQt2/Settings/PathPane.cpp, Source/Core/DolphinQt2/Settings/PathPane.h, Source/Core/DolphinQt2/Settings/WiiPane.cpp
* Wrap everything in scroll areas
* Improve audio pane layout
* Disable "Remove" button in path pane when there's nothing to remove
=> Qt/SettingsWindow: Multiple improvements

Source/Core/Common/MemArena.cpp, Source/Core/Common/MemArena.h, Source/Core/Core/HW/Memmap.cpp
Brings more common code under the Common namespace.
=> Common: Add MemArena.h/cpp to the Common namespace

Source/Core/Common/Hash.cpp, Source/Core/Common/Hash.h, Source/Core/Core/DSP/DSPCore.cpp, Source/Core/Core/DSP/DSPHWInterface.cpp, Source/Core/Core/HW/DSPHLE/UCodes/ROM.cpp, Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp, Source/Core/Core/Movie.cpp, Source/Core/DiscIO/CompressedBlob.cpp, Source/Core/VideoCommon/NativeVertexFormat.h, Source/Core/VideoCommon/TextureCacheBase.cpp
Brings more common code under the Common namespace.
=> Common/Hash: Namespace code under the Common namespace

Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
Cleans up remnant instances of Hungarian notation being used in variable names along with other spotted deviations.
=> Interpreter_SystemRegisters: Clean up variable naming

Source/Core/DolphinQt2/HotkeyScheduler.cpp, Source/Core/DolphinQt2/HotkeyScheduler.h, Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MainWindow.h
Fixes [issue #11134](https://bugs.dolphin-emu.org/issues/11134).
=> Qt/HotkeyScheduler: Fix state loading

Source/Core/Common/Arm64Emitter.h, Source/Core/Common/CodeBlock.h, Source/Core/Common/x64Emitter.h
Brings more common code under the Common namespace.
=> Common/CodeBlock: Namespace code under the Common namespace

Source/Core/DolphinQt2/HotkeyScheduler.cpp
e.g. getting stuck in fullscreen
=> Qt/HotkeyScheduler: Fix toggle fullscreen glitches

Source/Core/VideoBackends/Software/EfbInterface.cpp, Source/Core/VideoBackends/Software/EfbInterface.h, Source/Core/VideoBackends/Software/SWmain.cpp
Just minor tidying of EfbInterface
=> EfbInterface: Minor changes

Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/ES/TitleManagement.cpp
ImportTitleDone only checks if all required contents have been imported for system titles.
This fixes the system menu not being able to recreate title directories by using title import functionality when copying a save back to the NAND.
This PR also adds more logging to title import functions to make troubleshooting easier. Review separately.
=> ES: Fix content check in ImportTitleDone

Source/Core/DolphinQt2/Config/Graphics/GraphicsWindow.cpp
=> Qt/GraphicsWindow: Show display name in title

Source/Core/DolphinQt2/Config/Graphics/AdvancedWidget.cpp
Forgot to connect some signals.
=> Qt/AdvancedWidget: Save progressive scan when toggled

Source/Core/Core/PowerPC/PPCAnalyst.cpp
Given we just access the same member repeatedly, just use a reference and avoid repeated unnecessary indexing.
=> PPCAnalyst: Clean up indexing expressions in Analyze()

Source/Core/DolphinQt2/Debugger/JITWidget.cpp
=> Qt/JITWidget: Add object name

Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
If a program executing in user mode tries to write to any SPRs other than XER, LR, or CTR registers, then a program exception occurs. Similarly this also applies for reading SPRs as well, however the upper and lower timebase halves can also be read (but not written to).
This will be followed up by adding privilege checks to other relevant system register instructions.
=> Interpreter_SystemRegisters: Check processor privilege level in mfspr and mtspr

Source/Core/VideoCommon/PostProcessing.cpp, Source/Core/VideoCommon/PostProcessing.h
Individual minor changes that are most clean-up to the API
=> VideoCommon/PostProcessing: Minor changes

Source/Core/DolphinQt2/CMakeLists.txt, Source/Core/DolphinQt2/DolphinQt2.vcxproj, Source/Core/DolphinQt2/FIFO/FIFOAnalyzer.cpp, Source/Core/DolphinQt2/FIFO/FIFOAnalyzer.h, Source/Core/DolphinQt2/FIFO/FIFOPlayerWindow.cpp, Source/Core/DolphinQt2/FIFO/FIFOPlayerWindow.h, Source/Core/DolphinQt2/MainWindow.cpp
(Also features splitters so you can freely resize everything to your liking!)
=> Qt/FIFOPlayer: Implement Analyzer

Source/Core/DolphinQt2/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.h
=> Qt/Mapping: Add option to map all devices at once

Source/Core/DolphinQt2/Config/InfoWidget.cpp
* Don't show banner details if no data is present
* Don't show apploader date if it's not present
=> Qt/InfoWidget: Improve information display

Source/Core/Common/GekkoDisassembler.cpp, Source/Core/Common/GekkoDisassembler.h, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64Common/Jit64Base.cpp, Source/Core/DolphinQt2/Debugger/JITWidget.cpp, Source/Core/DolphinWX/Debugger/AssemblerEntryDialog.cpp, Source/Core/DolphinWX/Debugger/JitWindow.cpp, Source/Core/DolphinWX/Debugger/RegisterView.cpp
Moves more common code into the Common namespace where it belongs
=> Common: Namespace GekkoDisassembler.cpp/.h

Source/Core/Core/PowerPC/MMU.cpp
Makes all of the naming consistent with our code style, and makes parameters match their header equivalents.
Essentially just a clean-up of things that weren't migrated over already.
=> MMU: Normalize parameter naming

Source/Core/DolphinQt2/MenuBar.cpp, Source/Core/DolphinQt2/MenuBar.h, Source/Core/DolphinQt2/Updater.cpp, Source/Core/DolphinQt2/Updater.h
=> Qt: Add option to invoke the updater manually

Source/Core/DolphinQt2/Config/InfoWidget.cpp
=> Qt/InfoWidget: Don't display unavailable information

Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Forgot to add a few lines while cherry-picking the config changes for #6950
Fixes https://bugs.dolphin-emu.org/issues/11171
=> Config: Fix path settings not being saved

Source/Core/DolphinQt2/Settings/AdvancedPane.cpp
Fixes [issue #11172](https://bugs.dolphin-emu.org/issues/11172).
=> Qt/AdvancedPane: Show seconds in custom RTC

Source/Core/DolphinQt2/CMakeLists.txt, Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MainWindow.h, Source/Core/DolphinQt2/QtUtils/SignalDaemon.cpp, Source/Core/DolphinQt2/QtUtils/SignalDaemon.h
Fixes [issue #11155](https://bugs.dolphin-emu.org/issues/11155).
=> Qt/Unix: Implement signal handler

Source/Core/Common/PcapFile.cpp, Source/Core/Common/PcapFile.h, Source/Core/Core/DSP/DSPCaptureLogger.cpp, Source/Core/Core/DSP/DSPCaptureLogger.h
Brings more common code under the Common namespace.
=> PcapFile: Namespace code under the Common namespace

Source/Core/Common/Debug/MemoryPatches.cpp, Source/Core/Common/Debug/MemoryPatches.h
Minor individual changes that should be fairly self-explanatory.
=> MemoryPatches: Minor changes

Source/Core/Core/Analytics.cpp
Might be interesting to get some analytics data on this.
=> Analytics: Report update track

Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp, Source/Core/Core/HW/EXI/EXI_DeviceIPL.h
Just a minor clean-up of some basic things
=> EXI_DeviceIPL: Minor changes

Source/Core/DiscIO/Filesystem.cpp, Source/Core/DiscIO/Filesystem.h, Source/Core/DolphinQt2/Config/FilesystemWidget.cpp
=> Qt/FilesystemWidget: Add size column

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Fixes issue [11173](https://bugs.dolphin-emu.org/issues/11173)
I've been testing this a few days to see if there are performance implications, and a game I know uses this feature (Super Mario 64 on VC) is actually faster with this enabled for some reason.  Other games don't seem to have any noticeable impact.
=> [JIT] Enable Accurate Double to Single Conversion

Source/Core/Core/HW/WiiSave.cpp
All paths in SaveFile are relative to the title data directory, not absolute. Fixes an accidental regression from 5.0-7988 (PR #7059).
=> WiiSave: Fix the way paths are handled

Source/Core/DolphinQt2/HotkeyScheduler.cpp, Source/Core/DolphinWX/Frame.cpp, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/RenderBase.h
This pr adds an OnScreenDisplay message when you use the Volume hotkeys. Just to have visual feedback.
=> Add OSD message for Volume Hotkeys

Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.h, Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp, Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.h
Minor non-related changes that seem suitable for one PR. Mostly just const-correctness changes and deduplication (also geez, these classes crank it to 11 with prefixed underscores)
=> WiimoteDevice: Minor changes

Source/Core/DolphinQt2/GameList/GameList.cpp
Especially noticeable when resizing the window.
=> Qt/GameList: Greatly improve performance (List view)

Source/Core/DolphinQt2/HotkeyScheduler.cpp
Fixes [issue #11232](https://bugs.dolphin-emu.org/issues/11232).
=> Qt/HotkeyScheduler: Fix 3D Mode hotkeys not behaving properly

Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp
Several arrays within this source file are only ever read from, so the data can be made immutable.
=> BTEmu: Make read-only arrays const

Source/Core/Core/State.cpp
We used to show it for all failed savestate loads, no matter what the failure reason was. Fixes https://bugs.dolphin-emu.org/issues/9815
=> Only show savestate version mismatch OSD message when relevant

Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/VideoConfig.cpp, Source/Core/VideoCommon/VideoConfig.h
Under GFX::Enhancements::ArbitraryMipmapDetection - default enabled
=> Make arbitrary mipmap detection a config option

Source/DSPTool/DSPTool.cpp
Keeps all behavior localized in their own functions, making it a tiny bit nicer to read.
=> DSPTool: Factor out behavior from main()

Source/Core/Core/Movie.cpp, Source/Core/Core/Movie.h
A few functions don't actually modify the data being pointed to, so these can be made pointer-to-const.
=> Movie: Make pointer parameters const where applicable

Source/Core/Core/HW/Wiimote.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.h, Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp, Source/Core/Core/Movie.cpp, Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/MenuBar.cpp, Source/Core/DolphinWX/FrameTools.cpp
This is another class that had a somewhat intermixing of formatting in it. This makes it all uniform, like the rest of the bluetooth files. I've kept things separated so that review is more straightforward, but I can squash these down as well.
=> BTEmu: Amend variable naming

Source/DSPTool/DSPTool.cpp
Just individual minor cleanups that bring it in line with the rest of main codebase.
=> DSPTool: Minor cleanups

Source/Core/Core/DSP/DSPTables.h, Source/Core/Core/DSP/Interpreter/DSPIntArithmetic.cpp, Source/Core/Core/DSP/Interpreter/DSPIntExtOps.cpp, Source/Core/Core/DSP/Interpreter/DSPIntExtOps.h, Source/Core/Core/DSP/Interpreter/DSPIntMisc.cpp, Source/Core/Core/DSP/Interpreter/DSPIntMultiplier.cpp, Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp, Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp
Just a few minor self-contained changes that mainly apply to things defined within DSPIntExtOps.
=> DSPIntExtOps: Minor cleanups

Source/Core/DolphinQt2/GameList/GameTracker.cpp, Source/Core/DolphinQt2/GameList/GameTracker.h, Source/Core/DolphinQt2/Settings.cpp, Source/Core/DolphinQt2/Settings.h, Source/Core/DolphinQt2/Settings/PathPane.cpp
Should help a lot with performance when users have a large gamelist.
=> Qt: Add option to disable auto-refresh

Source/Core/VideoCommon/RenderBase.cpp
Looks like a botched copy/paste from Hybrid XFB changes. Easy fix.
=> VideoCommon: Fix auto IR being very overzealous

Source/VSProps/QtCompile.props
Has to be merged in conjungtion with https://github.com/dolphin-emu/ext-win-qt/pull/6 (Merged now).
=> Externals/Qt: Update to 5.11.1

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFragmentPresenter.java
~~The default value for Internal Resolution should be 0.~~ Also, Android studio also wanted me to use … instead of ...
=> Android: Properly set default Internal Resolution

Source/Core/DolphinQt2/Config/ControllersWindow.cpp, Source/Core/DolphinQt2/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt2/GameList/GameList.cpp, Source/Core/DolphinQt2/Main.cpp, Source/Core/DolphinQt2/MenuBar.cpp
=> Qt: Add titles to various message boxes

Source/Core/VideoBackends/D3D/main.cpp, Source/Core/VideoBackends/Null/VideoBackend.h, Source/Core/VideoBackends/OGL/main.cpp, Source/Core/VideoBackends/Software/SWmain.cpp, Source/Core/VideoBackends/Vulkan/VideoBackend.h
We're not sure if these are all translatable, but you never know what translators might like to do with names.
=> Mark all video backend names for translation

Source/Core/DolphinQt2/HotkeyScheduler.cpp, Source/Core/DolphinQt2/HotkeyScheduler.h, Source/Core/DolphinQt2/MainWindow.cpp
Fixes [issue #11249](https://bugs.dolphin-emu.org/issues/11249).
=> Qt/Hotkeys: Various fixes

Source/Core/DolphinQt2/GameList/GameList.cpp, Source/Core/DolphinQt2/Settings/PathPane.cpp
Fixes [issue 11254](https://bugs.dolphin-emu.org/issues/11254).
=> Qt/PathPane: Update "Default ISO" when changed

Source/Core/DolphinQt2/Config/FilesystemWidget.cpp, Source/Core/DolphinQt2/Config/FilesystemWidget.h, Source/Core/DolphinQt2/GameList/GameList.cpp
I was going to name the PR something funny, but I figured it would look too silly in the commit history, so I just put it in the branch name instead.
=> Qt: Various dialog fixes

Source/Core/DolphinQt2/MainWindow.cpp, Source/Core/DolphinQt2/NetPlay/NetPlaySetupDialog.cpp
Setup dialog used port from host tab for connecting, and stored IP address in the same config as host code.
=> Fix NetPlay using some config values wrongly

Data/Sys/GameSettings/N.ini, Source/Core/Core/BootManager.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/Movie.cpp, Source/Core/Core/Movie.h, Source/Core/Core/PowerPC/PPCAnalyst.cpp
Not even sure if I'm doing this right
=> Core/PowerPC: Add option to disable branch following

Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp
Should help with debugging NetPlay issues.
=> Core/NetPlay: Add debugging messages

Source/PCH/pch.h
just update to current version
=> bump msvc version check

Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
=> HW/WiimoteEmu: Add Forward Option

Source/Core/Common/CommonPaths.h, Source/Core/Common/FileUtil.cpp, Source/Core/Common/FileUtil.h, Source/Core/Core/Config/UISettings.cpp, Source/Core/Core/Config/UISettings.h, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameList.h, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/GameList/GameListModel.h, Source/Core/DolphinQt/GameList/GameTracker.cpp, Source/Core/DolphinQt/GameList/GameTracker.h, Source/Core/DolphinQt/GameList/GridProxyModel.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.h, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h, Source/Core/UICommon/GameFileCache.cpp, Source/Core/UICommon/UICommon.cpp
=> Qt/GameList: Add option to show covers in grid mode

Source/Core/Common/CommonPaths.h, Source/Core/Common/FileUtil.cpp, Source/Core/Common/FileUtil.h, Source/Core/Core/Config/UISettings.cpp, Source/Core/Core/Config/UISettings.h, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameList.h, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/GameList/GameListModel.h, Source/Core/DolphinQt/GameList/GameTracker.cpp, Source/Core/DolphinQt/GameList/GameTracker.h, Source/Core/DolphinQt/GameList/GridProxyModel.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.h, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h, Source/Core/UICommon/GameFileCache.cpp, Source/Core/UICommon/UICommon.cpp
Reverts dolphin-emu/dolphin#7285
> I'd also give them a heads up in case they mind the extra traffic / have a better way for us to integrate that doesn't blast hundreds of http queries at them on refresh.
This was not done.
=> Revert "Qt/GameList: Add option to show covers in grid mode"

Source/Core/Common/CommonPaths.h, Source/Core/Common/FileUtil.cpp, Source/Core/Common/FileUtil.h, Source/Core/Core/Config/UISettings.cpp, Source/Core/Core/Config/UISettings.h, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameList.h, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/GameList/GameListModel.h, Source/Core/DolphinQt/GameList/GameTracker.cpp, Source/Core/DolphinQt/GameList/GameTracker.h, Source/Core/DolphinQt/GameList/GridProxyModel.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.h, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h, Source/Core/UICommon/GameFileCache.cpp, Source/Core/UICommon/UICommon.cpp
Now that the issues resulting in the revert seem to be resolved this reverts the revert
=> Revert "Revert "Qt/GameList: Add option to show covers in grid mode""

Source/Core/UICommon/GameFile.cpp
Regression from PR #7285 / PR #7293.
=> Android: Don't crash when loading games into game list

Source/Core/Core/Boot/Boot_BS2Emu.cpp
BS2Emu was doing one extra DVD copy when AppLoaderMain returned 0. For normal AppLoader this doesn't matter - it just has the same values from the previous copy. For at least one unlicensed title (Action Replay), the values get zeroed out.
=> BS2Emu: Don't do a DVD Copy when AppLoaderMain returns 0

Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
Just basic cleanup to get the easy things out of the way for a future change.
=> WiimoteEmu: Minor changes

Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Quit the fifoplayer cpu idle loop if a shutdown has been requested
=> FifoPlayer: Actually exit on 'Stop' in dualcore

Source/Core/UICommon/Disassembler.cpp
Upper if branch use assignment to *p.
=> Core/UICommon: Fix assignment to pointer

Source/Core/DolphinQt/TAS/IRWidget.cpp, Source/Core/DolphinQt/TAS/StickWidget.cpp
[issue #11340](https://bugs.dolphin-emu.org/issues/11340)
=> Qt/TAS: Implement recentering feature

Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
Removed it by accident in #7299
=> Qt/Debugger: Readd title bar to breakpoint widget

Source/Core/Common/CommonPaths.h, Source/Core/UICommon/UICommon.cpp
add `.nomedia` in game cover directory.
=> Hide game cover in android gallery

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Reduces the scrolling speed for both keyboard and mouse scrolling so
users are able to navigate the code and memory view line by line
=> Qt/Debugger: Improve scrolling

Source/Core/DolphinQt/GameList/GridProxyModel.cpp
Should fix covers being randomly cut off.
=> Qt/GridProxyModel: Ensure uniform sizes in cover mode

Source/Core/UICommon/DiscordPresence.cpp
Since we don't have a way (AFAIK) to dynamically collect the list of
available art assets, we hardcode a list of gameids with available
artwork inside Dolphin. It's not great, but I don't think it's a
terrible solution either.
Art has to be manually uploaded to our Discord app configuration, and we
have a limit of ~150 assets, so most likely we'll limit ourselves to a
small set of popular games.
=> DiscordPresence: use game-specific artwork if available

Source/Android/build.gradle
=> Update Android Gradle Plugin to 3.1.4

Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayClient.h
=> NetPlay: Add additional comments for host input authority mode

Source/Core/Core/HW/WiimoteReal/IOWin.cpp
These functions aren't used outside of this translation unit, so we can make them internally linked.
=> IOWin: Make functions internally linked where applicable

Source/Core/Core/Core.cpp, Source/Core/Core/Core.h
Just putting the trash out as usual.
=> Core/Core: Remove another leftover part of frameskip

Source/Core/Common/Arm64Emitter.cpp
Incrementing `it` twice between sequence points is undefined behavior.
=> Arm64Emitter: Remove unsequenced expressions

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PicassoUtils.java, Source/Android/app/src/main/res/layout/card_game.xml, Source/Android/app/src/main/res/values-w1000dp/integers.xml, Source/Android/app/src/main/res/values-w500dp/integers.xml, Source/Android/app/src/main/res/values-w750dp/integers.xml, Source/Android/app/src/main/res/values/integers.xml
=> Android: Fix cover stretching and show more games per row

Source/Android/app/src/main/AndroidManifest.xml, Source/Android/app/src/main/assets/GCPadNew.ini, Source/Android/app/src/main/assets/WiimoteNew.ini, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/res/menu/menu_emulation.xml, Source/Android/app/src/main/res/menu/menu_emulation_wii.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/ButtonManager.cpp, Source/Android/jni/ButtonManager.h, Source/Core/InputCommon/ControllerInterface/Android/Android.cpp, Source/Core/InputCommon/ControllerInterface/Android/Android.h
This currently only supports using the internal vibrate on a phone for rumble.
=> Android: Add rumble for phone

Source/Android/app/src/main/res/menu/menu_emulation.xml, Source/Android/app/src/main/res/menu/menu_emulation_wii.xml
Use `app:showAsAction` when use `AppCompatActivity` otherwise it don't work as expect.
=> Menu show action fx for android

Source/Core/DiscIO/Volume.h, Source/Core/UICommon/GameFileCache.cpp
Partial revert of PR #7411. Should fix https://bugs.dolphin-emu.org/issues/11404.
=> Fix reading title IDs of Wii discs

Source/Core/Common/x64Emitter.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitArithmetic.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitUtil.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Various micro-optimizations that I felt didn't warrant separate pull requests.
=> Miscellaneous x64 micro-optimizations

Source/Core/VideoBackends/OGL/TextureCache.cpp
Seemed to work alright as far as I tested it.
=> GL/TextureCache: Clean up inline shader code

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
As asked by spycrab0, here's the pull request for #11026
Sorry about the delay, I was reluctant forking for a single line patch
Also sorry for opening a wrong PR before
=> #11026 fix

Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameList.h, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/GameList/GameListModel.h, Source/Core/DolphinQt/MenuBar.cpp
=> Qt/GameList: Implement tag system

Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Reverts dolphin-emu/dolphin#7491
=> Revert "Jit_SystemRegisters: Correct behaviour for mtspr SPR_HID0"

Readme.md
=> Update the Windows SDK version in the Readme file

Source/Core/VideoBackends/Vulkan/VertexManager.cpp
Required for performance analytics.
=> Vulkan: Add missing increment of draw call count

Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameList.h, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/GameList/GameListModel.h, Source/Core/DolphinQt/GameList/GameTracker.cpp, Source/Core/DolphinQt/GameList/GameTracker.h, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h, Source/Core/UICommon/GameFileCache.cpp, Source/Core/UICommon/GameFileCache.h
This is a missing feature from DolphinWX.
=> DolphinQt: Implement "Purge Game List Cache"

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/res/layout-television/activity_emulation.xml, Source/Android/app/src/main/res/layout/activity_emulation.xml, Source/Android/jni/MainAndroid.cpp
this transition is a little cheap. 
don't know this pr is appropriate.
:open_mouth:
=> [Android] Remove enter and exit transition

Source/Core/Common/Timer.cpp
Reported by https://forums.dolphin-emu.org/Thread-odd-codes-appear-in-save-load-state-when-chinese-language-is-used
=> Use wcsftime instead of strftime on Windows to fix encoding errors

Source/Core/Core/Config/NetplaySettings.cpp, Source/Core/Core/Config/NetplaySettings.h, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.h
Addresses issue: [11398](https://bugs.dolphin-emu.org/issues/11398)
EDIT: Apparently some these settings need to be synced with other clients, and it will probably need some actual netplay testing.
EDIT2: The bug report mentions "friends" ... note sure about that yet, will take a look.
=> Netplay: Properly save hosting settings

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
regression from 1e3a2979006ce5da1b8e7f196039def455411c9b pr7518
=> Android: fix ATV not exiting

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/InputBindingSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RumbleBindingViewHolder.java
=> Android: fix custom game control ui

Source/Core/Updater/Main.cpp, Source/Core/Updater/UI.cpp, Source/Core/Updater/UI.h
Changes:
* Shows the progress of the current item in the taskbar just as it is displayed with the progressbar
* Shows an error indicator in the taskbar when a fatal error occurs
=> Updater: Show progress in taskbar

Source/Core/Updater/Main.cpp, Source/Core/Updater/UI.cpp, Source/Core/Updater/UI.h
This gives a rough approximation of how far the whole update process has progressed instead of only showing the current progress.
=> Updater: Add total progressbar

CMakeLists.txt, Externals/minizip/CMakeLists.txt, Externals/minizip/LICENSE, Externals/minizip/README, Externals/minizip/ioapi.c, Externals/minizip/ioapi.h, Externals/minizip/minizip.vcxproj, Externals/minizip/unzip.c, Externals/minizip/unzip.h, Source/Core/Core/Core.vcxproj, Source/dolphin-emu.sln
Cherry-picked https://github.com/dolphin-emu/dolphin/pull/6178/commits/34707e9c2e825196134d5d62f6ca9874cf64593b - I was told that PR will probably never get finished. 
It will be needed for an auto-updater for #7110 in the future and possibly other things.
=> Externals: Add a stripped down version of minizip

Source/Core/Updater/UI.cpp
* Better handling of interface querying / instance creation failures.
* Call HrInit() as required on the ITaskbarlist3 instance after obtained.
=> Fix Updater crashes with new taskbar integration feature

CMakeLists.txt, Externals/imgui/CMakeLists.txt, Externals/imgui/LICENSE.txt, Externals/imgui/imconfig.h, Externals/imgui/imgui.cpp, Externals/imgui/imgui.h, Externals/imgui/imgui.vcxproj, Externals/imgui/imgui_draw.cpp, Externals/imgui/imgui_internal.h, Externals/imgui/imgui_widgets.cpp, Externals/imgui/imstb_rectpack.h, Externals/imgui/imstb_textedit.h, Externals/imgui/imstb_truetype.h, Source/VSProps/Base.props, Source/dolphin-emu.sln
What the title says. Adding this as a separate PR so that the integration PR is easier to review, once this is merged.
Note that the files I've bundled is not the full repository, and stripped down. I figured we have no need for the example files polluting the tree, since we have it inline.
=> Externals: Add imgui

Source/Core/DolphinQt/MainWindow.cpp
Saw a request for this, and it'd help me too.
=> Add nested docking to increase layout choices while debugging.

Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
Avoid loading the same value twice unnecessarily.
=> Jit_SystemRegisters: Special-case crXXX for CRBA == CRBB

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_GCAdapter.java
=> Android: fix gc adapter init

Source/Core/Core/WiiUtils.cpp
If the user tries to permanently install a title that has already been
imported, and if that title is currently marked as a temporary title
in IPL.TID, that flag should be cleared.
=> WiiUtils: Clear IPL.TID when re-installing a title manually

Source/Core/Core/HW/SI/SI_DeviceGCAdapter.cpp, Source/Core/Core/HW/SI/SI_DeviceGCController.cpp, Source/Core/Core/HW/SI/SI_DeviceGCController.h
I promise you that DK Bongos work now.
=> HW: DK Bongos actual fix

Data/Sys/GameSettings/GOW.ini
Most Wanted seems work fine without mmu.
=> Most Wanted mmu setting

Data/Sys/GameSettings/RYI.ini
screen is keep flicking with ImmediateXFB enabled.
=> Gamesetting for SPRay

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SingleChoiceViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SliderViewHolder.java
=> Android: show setting value as desc

Data/Sys/GameSettings/S3H.ini
Sengoku BASARA 3 Her need EFBEmulateFormatChanges or it will white screen in cut scene.
=> Gamesetting for Sengoku BASARA 3 Utage

Source/Core/InputCommon/GCAdapter.cpp
Make CheckDeviceAccess() more flat by inverting checks, reducing indentation and removing dead code.
This is a purely cosmetic pull request.
=> Flatten a GCAdapter function

Source/Core/DolphinQt/GameList/GameList.cpp
In _GameList.cpp_, null pointers were being dereferenced. It was assumed that `GetSelectedGame()` would never return a null pointer after having displayed the context menu, but that assumption is not correct.
**Reproduction steps:**
- Open **Dolphin**.
- Start copying (or downloading) a game into any of the directories monitored by **Dolphin**. This will make the game list to be refreshed every now and then, until the game is fully copied (or downloaded).
- Right-click on the game as soon as it appears on the list, which will then select the row, and display the context menu.
- However, because the game list is being refreshed every now and then, the game will be automatically deselected, whilst the context menu remains visible.
- Now select the **Properties** action from the context …
=> Fixed crash when dereferencing the potential null pointer returned by GetSelectedGame().

Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameTracker.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt/RenderWidget.cpp
Fixes some warnings that are shown when compiling with clang 10.
=> DolphinQt: Fix some warnings

Source/Core/DolphinQt/RenderWidget.cpp
=> RenderWidget: Fix mouse position for imgui on hidpi screens

Data/Sys/GameSettings/S5D.ini, Data/Sys/GameSettings/SBY.ini
Fixes https://bugs.dolphin-emu.org/issues/11541
=> Fixing some GameSettings

Source/Android/jni/MainAndroid.cpp
Fixes crash in single core when attaching the JVM
=> Android: Update touch pointer from thread.

Source/Core/Core/Analytics.cpp, Source/Core/Core/HW/Sram.cpp, Source/Core/Core/HW/SystemTimers.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp
Fixes some warnings that occur when compiling core with Apple clang
=> Core: Fix some warnings

Source/Core/DolphinQt/Config/LogWidget.cpp
Should fix [issue #11560](https://bugs.dolphin-emu.org/issues/11560)
=> Qt/LogWidget: Make logging asynchronous

Source/Core/DolphinQt/ResourcePackManager.cpp, Source/Core/DolphinQt/ResourcePackManager.h, Source/Core/UICommon/ResourcePack/Manager.cpp, Source/Core/UICommon/ResourcePack/ResourcePack.cpp
* Fixes some crashes
* Fixes some UI issues
* Fixes uninstalling packs installing other packs
=> ResourcePacks: Fix various bugs

Externals/FreeSurround/FreeSurround.vcxproj
Didn't catch this during my review :(
=> Externals: Set target platform to 10.0.17134 for FreeSurround

Source/Core/DolphinQt/CheatsManager.h, Source/Core/DolphinQt/DiscordJoinRequestDialog.h, Source/Core/DolphinQt/GCMemcardManager.h, Source/Core/DolphinQt/MenuBar.h, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/ToolBar.cpp, Source/Core/DolphinQt/ToolBar.h, Source/Core/UICommon/DiscordPresence.cpp
plus a typo fix for good measure
=> DolphinQt: clean up includes

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFile.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CoverHelper.java, Source/Android/jni/GameList/GameFile.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/GeckoCodeConfig.cpp, Source/Core/Core/GeckoCodeConfig.h, Source/Core/Core/IOS/ES/Formats.cpp, Source/Core/Core/IOS/ES/Formats.h, Source/Core/Core/TitleDatabase.cpp, Source/Core/Core/TitleDatabase.h, Source/Core/DiscIO/Volume.h, Source/Core/DiscIO/VolumeGC.cpp, Source/Core/DiscIO/VolumeGC.h, Source/Core/DiscIO/VolumeWad.cpp, Source/Core/DiscIO/VolumeWad.h, Source/Core/DiscIO/VolumeWii.cpp, Source/Core/DiscIO/VolumeWii.h, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.h, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h, Source/Core/UICommon/GameFileCache.cpp
See the commit messages for details.
=> Fix edge cases in TitleDatabase, cover downloading, Gecko code downloading

Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h
Fixes [issue #11588](https://bugs.dolphin-emu.org/issues/11588).
=> MenuBar: Implement proper update-capabilities check

Source/Core/MacUpdater/Info.plist.in
Fixes [issue #11586](https://bugs.dolphin-emu.org/issues/11586).
=> MacUpdater: Set LSUIElement to true

Source/Core/UpdaterCommon/UpdaterCommon.cpp
Changes (macOS only):
* Prevent duplicate downloads
* Respect symlinks
=> UpdaterCommon: Prevent duplicate downloads and respect symlinks

docs/ResourcePacks.md
Some documentation for resource packs, feel free to nitpick.
=> docs: Add ResourcePacks.md

Source/Core/InputCommon/ControllerEmu/StickGate.cpp
Dead zone was accidentally scaled/reshaped twice by the calibration shape.
It was only noticeable on non-circular inputs.
Other minor code and comment cleanups.
=> ControllerEmu: Deadzone math fix.

Source/Core/VideoCommon/AsyncRequests.cpp, Source/Core/VideoCommon/Statistics.cpp, Source/Core/VideoCommon/Statistics.h
Should have negligible perf impact considering the GPU stalls lol
=> VideoCommon: add EFB peek/poke stats

Source/Core/Common/Matrix.cpp, Source/Core/Common/Matrix.h, Source/Core/Core/Config/WiimoteInputSettings.cpp, Source/Core/Core/Config/WiimoteInputSettings.h, Source/Core/Core/HW/WiimoteEmu/Camera.cpp, Source/Core/Core/HW/WiimoteEmu/Camera.h, Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp, Source/Core/Core/HW/WiimoteEmu/Dynamics.h, Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Extension.h, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h, Source/Core/Core/State.cpp, Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp, Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h, Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Force.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Force.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.h
Emulated swing no longer sucks. It was basically completely unusable until now.
Swing mappings now result in smoothly adjusted acceleration data that would be produced by moving a wiimote about in your outstretched arm.
A "Distance" setting specifies the extremities of the swing (in centimeters).
A "Jerk" setting specifies the maximum change in acceleration (in m/s^3).
An "Angle" setting specifies an amount of twist applied to the wiimote at the edge of the swing motion (in degrees).
The indicator in the UI shows the effects of the distance and jerk. (angle coming later)
TODO later: Swing trajectory should be more of an arc rather than perfectly side to side with some twist. This will be easy to fix later.
The IR mappings now result in a tilt/twist of the wiimote (which affects …
=> WiimoteEmu: Reimplement tilt/swing/camera/orientation data using matrix math.

Source/Core/DolphinQt/MainWindow.cpp
Missing feature from DolphinWX.
=> DolphinQt: Save movie when closing emulation

Source/Core/DolphinQt/NetPlay/MD5Dialog.cpp
Fixes [issue #11613](https://bugs.dolphin-emu.org/issues/11613). Tested on macOS.
=> Qt/MD5Dialog: Make dialog modal

Source/Core/Core/Boot/Boot.cpp
See https://bugs.dolphin-emu.org/issues/11467. We now only have the hashes that have been confirmed on Redump.
For the reference, MAME's list of bad GameCube IPL dumps: https://github.com/mamedev/mame/blob/80b2ca6088281babff558b36a98d329aa60aa8ed/src/mame/drivers/gamecube.cpp#L152-L158
=> Remove invalid IPL hashes (NTSC-U and NTSC-J use same IPL)

Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MainWindow.h
=> DolphinQt: Add support for the --movie parameter

Source/Core/DolphinQt/TAS/GCTASInputWindow.cpp, Source/Core/DolphinQt/TAS/IRWidget.cpp, Source/Core/DolphinQt/TAS/IRWidget.h, Source/Core/DolphinQt/TAS/StickWidget.cpp, Source/Core/DolphinQt/TAS/StickWidget.h, Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp
Fixes [Issue #11620](https://bugs.dolphin-emu.org/issues/11620) and improves the layout of TAS windows.
=> Qt/TAS: Some fixes

Data/Sys/GameSettings/WMS.ini
Maybe we should get rid of all the boilerplate INI text...
=> GameSettings: fix Enjoy your massage! textures

Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoBackends/Vulkan/VulkanEntryPoints.inl, Source/Core/VideoBackends/Vulkan/VulkanLoader.cpp
=> Vulkan: Fix library load failure on Android

Source/Core/VideoCommon/FramebufferManager.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp
Fixes issue 11639: https://bugs.dolphin-emu.org/issues/11639
=> FramebufferManager: Fix broken EFB peeks in GL with MSAA on

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/TAS/GCTASInputWindow.cpp, Source/Core/DolphinQt/TAS/GCTASInputWindow.h, Source/Core/DolphinQt/TAS/TASCheckBox.cpp, Source/Core/DolphinQt/TAS/TASCheckBox.h, Source/Core/DolphinQt/TAS/TASInputWindow.cpp, Source/Core/DolphinQt/TAS/TASInputWindow.h, Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp, Source/Core/DolphinQt/TAS/WiiTASInputWindow.h
Fixes [issue #11338](https://bugs.dolphin-emu.org/issues/11338).
=> Qt/TAS: Implement turbo mode

Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp, Source/Core/DolphinQt/NetPlay/NetPlayBrowser.h, Source/Core/UICommon/NetPlayIndex.cpp, Source/Core/UICommon/NetPlayIndex.h
Changes:
* Fixes the In-Game column being editable
* Fixes the header getting bold when an item is selected
* Adds a version column
* Adds an option to show incompatible sessions
=> Qt/NetPlayBrowser: Various small fixes

Source/Core/Core/NetPlayClient.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.h, Source/Core/UICommon/NetPlayIndex.cpp, Source/Core/UICommon/NetPlayIndex.h
Shows a message when:
* There has been an error while adding a session to the index
* Adding the session has succeeded
* The game has been dropped from the index
=> Qt/NetPlay: Show feedback for index adding

Source/Core/Common/HttpRequest.cpp, Source/Core/Common/HttpRequest.h, Source/Core/UICommon/NetPlayIndex.cpp
This PR needs to be merged before https://github.com/dolphin-emu/netplay-index/commit/eae1f7c4b91581c13d01619ccdcde5696905107b can be deployed.
=> UICommon/NetPlayIndex: Handle non 200 HTTP return codes 

Externals/imgui/imgui.cpp, Externals/imgui/imgui.h, Externals/imgui/imgui_draw.cpp, Externals/imgui/imgui_internal.h, Externals/imgui/imgui_widgets.cpp, Externals/imgui/imstb_rectpack.h, Externals/imgui/imstb_textedit.h, Externals/imgui/imstb_truetype.h
Self explanatory. Needed for tab bars, which I'm using in the graphics window PR.
=> Externals: Update imgui to 1.70 WIP

Source/Core/DolphinQt/Config/GameConfigWidget.cpp
Fixes https://bugs.dolphin-emu.org/issues/11676
=> Qt/GameConfigWidget: Show revision specific INIs

Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp
Fixes https://bugs.dolphin-emu.org/issues/11680
=> Qt/NetPlayBrowser: Prevent word wrap

Source/Core/DolphinQt/Config/NewPatchDialog.cpp, Source/Core/DolphinQt/Config/NewPatchDialog.h
Fixes https://bugs.dolphin-emu.org/issues/11690
=> Qt/NewPatchDialog: Fix crashes on entry removal

Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWidget.h, Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt/Config/Mapping/MappingWindow.h
This removes iterative input as suggested in https://bugs.dolphin-emu.org/issues/11651.
It is currently plagued with issues that are non-trivial to fix and there doesn't seem to be great interest to do so.
There's always the option of readding it in the future if need be.
=> Qt/Mapping: Remove iterative input

Source/Core/Common/NandPaths.cpp, Source/Core/Common/NandPaths.h, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/WiiRoot.cpp
It's bundled with the Wii saves for simplicity, since it's quite small.
=> NetPlay: Synchronize Mii data

Readme.md
Addresses https://bugs.dolphin-emu.org/issues/11089.
Phrasing could probably need some tweaking. Nit picking welcome.
=> Readme.md: Add hint about Qt submodule under Windows

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/PatchInstructionDialog.cpp, Source/Core/DolphinQt/Debugger/PatchInstructionDialog.h, Source/Core/DolphinQt/DolphinQt.vcxproj
Fixes https://bugs.dolphin-emu.org/issues/10959.
=> Qt/Debugger: Implement patch instruction preview

Source/Android/app/src/main/res/values/arrays.xml, Source/Core/Core/PowerPC/PowerPC.cpp
Based on https://bugs.dolphin-emu.org/issues/11658
=> Re-order cpu emulation options from fastest to slowest

Source/Core/Core/WiiRoot.cpp
It only saved the current title ID, which means any other saves modified would not be written to main NAND.
=> Core/WiiRoot: Fix NetPlay full Wii save sync not copying all the saves back to main NAND

Source/Core/Core/CMakeLists.txt, Source/Core/Core/Core.vcxproj, Source/Core/Core/Core.vcxproj.filters, Source/Core/Core/HW/Wiimote.cpp, Source/Core/Core/HW/Wiimote.h, Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.h, Source/Core/Core/HW/WiimoteEmu/ExtensionPort.h, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtension.cpp, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtension.h
This is what everyone has been waiting for.
The TaTaCon extension is now fully emulated!
=> WiimoteEmu: Implement TaTaCon extension.

Source/Core/Core/HW/WiiSave.cpp
The system menu is passing the SHA1 hash of the save data to ES
to sign, not the save data itself.
Fixes save import in the System Menu for saves that were exported
by Dolphin.
=> WiiSave: Fix save signing

Source/Core/Core/CMakeLists.txt, Source/Core/Core/Core.vcxproj, Source/Core/Core/Core.vcxproj.filters, Source/Core/Core/HW/Wiimote.cpp, Source/Core/Core/HW/Wiimote.h, Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.h, Source/Core/Core/HW/WiimoteEmu/ExtensionPort.h, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtension.cpp, Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtension.h
We might as well emulate this too..
=> WiimoteEmu: Implement "Drawsome" tablet.

Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp
I'm mainly doing this to test our lint bot with structured bindings.
=> DolphinQt: Use a structured binding.

Source/Core/Core/HW/DVD/DVDInterface.cpp, Source/Core/Core/HW/DVD/DVDInterface.h, Source/Core/Core/HW/WiimoteEmu/Extension/Classic.h, Source/Core/Core/HW/WiimoteEmu/Extension/Drums.h, Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.h, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h, Source/Core/Core/HW/WiimoteEmu/Extension/Turntable.h, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h, Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
https://bugs.dolphin-emu.org/issues/11692#note-7
=> Turn more enum constants into constexpr

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/res/values/strings.xml
This is taken directly from an earlier version of PR #7908.
=> Android: Support changing Wii Remote extension while emulating

Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DiscIO/VolumeVerifier.h
The main commit is the one that resolves a case where a problem is given lower severity than it otherwise should have been (according to the comments at the problem area). The rest is minor touch-ups that were noticed along the way.
=> DiscIO/VolumeVerifier: Make use of unused variable (+ minor other changes)

Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h
Just minor cleanup of miscellaneous things. Avoids copies where applicable, and simplifies some usages of API. Each commit should be fairly explanatory.
=> UICommon/GameFile: Minor cleanup

Source/Core/VideoBackends/Vulkan/main.cpp
The Metal version included with MacOS 10.13 and below does not support several features we require. Furthermore, the drivers seem to choke on our shaders (mainly Intel).
This PR adds a warning message that they are using an unsupported configuration, and asks not report bugs encountered.
Note that this **only affects Vulkan/Metal**, using OpenGL will not result in any warning message.
=> Vulkan: Display a warning when using MoltenVK on HS and earlier

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp, Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
Made a second pass, mainly adjustments to linebreaks.
=> Qt: Minor adjustments to graphics window descriptions

Readme.md, Source/Core/Common/FileSearch.cpp, Source/Core/Core/Boot/Boot.cpp
https://bugs.dolphin-emu.org/issues/11770
=> Replace <experimental/filesystem> includes with <filesystem>

Source/Core/Common/FileSearch.cpp
https://bugs.dolphin-emu.org/issues/11771
=> Fix opening controller config when there is no profile directory

Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.h, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.h
Also supports alphabetical sorting
=> ActionReplay & GeckoCode reordering support

Source/Core/UpdaterCommon/UpdaterCommon.cpp
=> UpdaterCommon: Hide Updater before Dolphin quits

Source/Core/Common/FileSearch.cpp, Source/Core/Common/StringUtil.cpp, Source/Core/Common/StringUtil.h, Source/Core/Core/Boot/Boot.cpp
Fixes https://bugs.dolphin-emu.org/issues/11773.
=> Work around C++20 std::filesystem changes related to u8string

Installer/Installer.nsi
Added Qt dependencies, Updater, and DSPTool to the NSIS installer script
=> Update Installer.nsi for Qt support

Source/Core/DolphinQt/Debugger/WatchWidget.cpp, Source/Core/DolphinQt/Debugger/WatchWidget.h
This adds another column for the value as a float on the watch widget.
=> Show values as floats in watch

Source/Core/Common/Debug/Watches.cpp, Source/Core/Common/Debug/Watches.h, Source/Core/Common/DebugInterface.h, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/Debugger/PPCDebugInterface.h, Source/Core/Core/HW/DSPLLE/DSPDebugInterface.cpp, Source/Core/Core/HW/DSPLLE/DSPDebugInterface.h, Source/Core/Core/PowerPC/PPCSymbolDB.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Makes a few cleanup-related changes to the DebugInterface-related classes. Each change has its own description that expands on what it does. Most of them are fairly straightforward.
=> Common/DebugInterface: Minor cleanup changes

Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/ES/ES.h
https://bugs.dolphin-emu.org/issues/11804
=> Never set disc as active title when launching channel with same ID

Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp
This only fixes the build. The GDB stub itself doesn't quite work at the moment.
=> Fix GDB stub build

Source/Core/Core/State.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h
Only for about half a second but noticeable nonetheless
=> Fix saving states freezing up emulation

Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
https://bugs.dolphin-emu.org/issues/11692#note-11
Not sure if `REQUEST_TYPE` is the best name to use for the constant – suggestions welcome.
=> BTReal.cpp: Don't use bitwise operators on enum values

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java
https://bugs.dolphin-emu.org/issues/11767
This is completely untested since I don't have an Android TV device. If someone could test it, it would be appreciated.
=> Android: Fix race condition in AppLinkActivity

Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.cpp
Revert of https://github.com/dolphin-emu/dolphin/pull/8233#discussion_r306223322
=> DolphinQt: Fix whitelisting USB devices

Data/Sys/GameSettings/SDL.ini, Data/Sys/GameSettings/SKU.ini, Data/Sys/GameSettings/SMZ.ini, Data/Sys/GameSettings/SP8.ini, Data/Sys/GameSettings/SS8.ini
Fixes https://bugs.dolphin-emu.org/issues/11823
=> Add safe texture cache to some uDraw games' ini files

Source/Core/DolphinQt/GCMemcardManager.cpp
=> Fix import gc save file window title

Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
Previously when switching between backends that do/don't support "3D Vision" an attempt was made to remove the choice from the `QComboBox`.
This was problematic for a few reasons..
The wrong index was used (regression?) so the wrong item was removed.
Switching to an unsupported backend after having selected "3D Vision" activated the "Passive" stereo mode as it was the previous item in the list.
Adding additional items to the `StereoMode` enum after `Nvidia3DVision` (e.g. `OpenXR`) will have unmatched indices in the `QComboBox` which `GraphicsChoice` is not prepared for.
Now "NVIDIA 3D Vision" is always added to the stereo mode list. A popup message is shown when switching to an unsupported backend/3d-vision combo and stereoscopy is then disabled.
=> DolphinQt/Graphics: Fix NVIDIA 3D Vision support handling.

CMakeSettings.json, Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/RenderWidget.cpp, Source/Core/DolphinQt/ResourcePackManager.cpp, Source/VSProps/QtCompile.props
Update to 5.13.1
Replaces some deprecated stuff in order to avoid triggering warnings
=> Externals/Qt: Update to 5.13.1

Source/Core/Common/WorkQueueThread.h
- Do not use a lambda for std::thread as invoke constructor exists
- Use simpler std::lock_guard wherever possible
- Do not require T to be default constructible
- Move T out of the queue instead of copying
=> Improvements to WorkQueueThread

Source/Core/DolphinQt/Debugger/RegisterWidget.cpp, Source/Core/DolphinQt/Debugger/RegisterWidget.h, Source/Core/DolphinQt/MainWindow.cpp
Fix view in code/memory not working in the Qt backend.
=> RegisterWidget: Fix view in code/memory

Source/Core/DolphinQt/AboutDialog.cpp
Also adds a ``Using Qt VERSION`` line.
=> Qt/AboutDialog: Clean up code a bit

Source/Core/Core/ActionReplay.cpp
Migrates the ActionReplay logging over to using `fmt::format` instead of `StringFromFormat`.
=> ActionReplay: Make use of fmt where applicable

Source/Core/DiscIO/VolumeVerifier.cpp
=> VolumeVerifier: Fix "The data partition is missing" false positive

Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp, Source/Core/DolphinQt/Config/Mapping/MappingButton.h
Fixes: https://bugs.dolphin-emu.org/issues/11797
=> DolphinQt: Fix output mapping button spacebar activation and tooltip.

Source/Core/DolphinQt/Main.cpp, Source/Core/UICommon/CommandLineParse.cpp
https://bugs.dolphin-emu.org/issues/11888
=> Disable render to main when using batch mode

Source/Core/Core/HW/WiimoteCommon/WiimoteConstants.h, Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
Minor edge case accuracy fixes tested on my Nintendo Wii Remote Plus.
The changes don't affect any games as far as I know.
=> WiimoteEmu: Minor accuracy fixes.

Source/Core/InputCommon/CMakeLists.txt, Source/Core/InputCommon/ControllerEmu/StickGate.cpp, Source/Core/InputCommon/ControllerInterface/Device.cpp, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp, Source/Core/InputCommon/InputProfile.cpp
Continues the migration over to fmt
=> InputCommon: Make use of fmt where applicable

Source/Core/InputCommon/ControlReference/FunctionExpression.cpp, Source/Core/InputCommon/ControlReference/FunctionExpression.h
Performs a minor general cleanup of the source file. Each commit title should be fairly self-explanatory.
=> InputCommon/FunctionExpression: Minor cleanup

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameSettingsDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PermissionsHandler.java, Source/Android/app/src/main/res/layout/activity_main.xml
=> Moves AlertDialogs imports to AndroidX and fix tabs background color

Source/Core/VideoCommon/FrameDump.cpp
New segment wasn't properly initialized. Also when dumping ends, it wasn't clearing all the needed flags.
=> 2 minor dumping fixes

Source/Core/DolphinQt/GameList/GameList.cpp
It's pretty well tested at this point.
=> DolphinQt: Remove "Experimental" from "Export Wii Save"

Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DiscIO/VolumeVerifier.h
https://bugs.dolphin-emu.org/issues/11900
=> VolumeVerifier: Detect broken Super Paper Mario

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/CheckBoxSettingViewHolder.java
https://bugs.dolphin-emu.org/issues/11904
=> Android: Fix displaying checkbox settings with no description

Source/Core/VideoBackends/D3DCommon/Common.cpp, Source/Core/VideoBackends/D3DCommon/Common.h
Quick PR to:
- Tidy up D3DCommon a bit
- Fix a leaking handle to IDXGIAdapter
=> D3DCommon: Cleanups and resource leak fix

Source/Core/Core/ConfigManager.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.h
=> Disable full MMU by default and add it to global config GUI

Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
These spam logs on every run for no good reason.
=> DualShockUDPClient: downgrade spurious NOTICE_LOGs

Source/Core/Core/DSP/Jit/x64/DSPJitArithmetic.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitUtil.cpp, Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
DSPJit optimizations and one tiny Jit64 change.
=> x64 micro-optimizations

Source/Core/Core/NetPlayServer.cpp
This solves the issue of booting games locally while connected to NetPlay causing desync.
=> Core/NetPlayServer: Sync SRAM on every game start

Source/Core/Common/Analytics.h
It looks like original writer, delroth, was waiting on C++17.
=> Common/Analytics: Replace mutex with shared_mutex and minor cleanups.

Source/Core/InputCommon/ControllerInterface/Touch/ButtonManager.cpp
Device id is "" on ChromeOS when using gamepad
=> ButtonManager: Fix handling of empty device id.

CMakeSettings.json, Source/Core/DolphinQt/CMakeLists.txt, Source/VSProps/QtCompile.props
Should greatly improve HiDPI support :)
=> Update to Qt 5.14.1

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
These were fixed-size and auto-calculated every time you scrolled up or down, making them jump wildly when you're in the vicinity of long symbol names or `rlwinm` instructions. With this they don't, and you can resize them at will.
A minor issue is that Qt is pretty awful at eliding strings in table cells, which means if you have a branch target to a long symbol, even if there's enough space for 90% of the symbol name, it will cut off the entire symbol. This kinda sucks but I can't find a way to work around it without completely reimplementing the text painting logic, so I guess I'll live with it.
=> Qt/CodeViewWidget: Make columns resizable by the user and set sensible defaults.

Source/Core/Core/Boot/Boot_BS2Emu.cpp
As suggested by https://github.com/dolphin-emu/dolphin/pull/8673#discussion_r394945753.
=> Boot: Change pre-defined setting.txt CODE values

Source/Core/Common/GL/GLContext.cpp, Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp, Source/Core/DolphinQt/GCMemcardManager.cpp, Source/Core/UICommon/AutoUpdate.cpp
=> Cleanup warnings of -Wunused-[const]-variable

Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp
Remove unused lambda captures.
=> Cleanup warnings of -Wunused-lambda-capture

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
Now that #8711 is merged, this can be done too.
@JosJuice @JMC47
=> Android: Set Insert SD Card default setting to true

Source/Core/DolphinQt/Settings/PathPane.cpp
I'm not super familiar with Qt so I would appreciate it if someone could check my changes there.
Perhaps @spycrab ?
=> Qt: Display default Paths

Source/Core/Core/HW/GCMemcard/GCMemcard.cpp, Source/Core/Core/HW/SI/SI_DeviceGCSteeringWheel.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/VideoCommon/FramebufferShaderGen.cpp
Add default branch to the switch-case.
=> Cleanup warnings of -Wswitch

Source/Core/DiscIO/VolumeVerifier.cpp
Fixes a false positive for Mario Party 8.
=> VolumeVerifier: Treat IOS9 as always present

Source/Core/Core/WiiRoot.cpp
CopyNandFile must not create empty files on the destination filesystem
if the source file doesn't exist.
Otherwise, this can lead to an empty Mii database being created in the
session Wii root if there's no database in the configured Wii root and
netplay or Movie is used -- that database would then be copied back to
the configured root, which causes games like MKW to complain about
corrupted Mii data even when the player has stopped using netplay.
=> WiiRoot: Fix empty files being created when source is missing

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/IOS/Network/SSL.cpp, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
This PR migrates SSL options from the old config system to the new one.
=> Config: Migrate SSL options to Onion config

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/PlatformPagerAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Removed an apparently outdated TODO in PlatformPagerAdapter
- Formatted the TODOs to fully display in Android Studio's TODO panel.
=> Android: Consistent TODO formatting

Source/Core/Core/IOS/DolphinDevice.cpp
Related to issue 11930. 
Right now, when you import a NAND backup into Dolphin, the serial number from the NAND is used by Dolphin. As soon as you play an out-of-region game, the serial number prefix in the settings.txt is overwritten with one that matches the game region, unless you have the "Allow mismatched region settings" setting enabled. The original prefix is then permanently lost. 
However, as stated by JosJuice in the above issue report, it is possible that games don't like being booted with an out-of-region serial number, so this kind of prefix replacement is necessary. 
This pull request adds an ioctl value to the /dev/dolphin device that allows the game to access the REAL serial number prefix, meaning, the one that was imported from the actual NAND, no matter how many …
=> Add /dev/dolphin interface to allow game to read the REAL product code

Source/Core/Core/BootManager.cpp, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/Core.cpp, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp, Source/Core/DolphinQt/Config/Graphics/GraphicsWindow.cpp, Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp, Source/Core/DolphinQt/Config/Graphics/SoftwareRendererWidget.cpp, Source/Core/UICommon/UICommon.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp, Source/Core/VideoCommon/VideoBackendBase.h
Fixes https://bugs.dolphin-emu.org/issues/12087
=> Migrate video backend setting to the new config system

Source/Core/Core/DSP/Interpreter/DSPIntArithmetic.cpp, Source/Core/Core/DSP/Interpreter/DSPIntMisc.cpp, Source/DSPSpy/main_spy.cpp
=> DSPSpy: fix register editing using GC pad on Wii

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java, Source/Android/app/src/main/res/values/strings.xml
=> Android: Add option to disallow SD card writes

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/GameList/GameFileCache.cpp
Implements https://bugs.dolphin-emu.org/issues/10806
=> Android: Add recursive game paths to UI

Source/Core/Common/Logging/LogManager.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.cpp
I replaced some acronyms to help users figure out (or search for) what those settings change.
=> Replace some acronyms

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Implements https://bugs.dolphin-emu.org/issues/10716
=> Android: Refresh game library when resuming (Tv)MainActivity

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFile.java, Source/Android/app/src/main/res/layout/dialog_game_details.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/GameList/GameFile.cpp, Source/Android/jni/MainAndroid.cpp, Source/Core/DiscIO/Blob.cpp, Source/Core/DiscIO/Blob.h, Source/Core/DiscIO/CISOBlob.h, Source/Core/DiscIO/CompressedBlob.h, Source/Core/DiscIO/DirectoryBlob.h, Source/Core/DiscIO/DriveBlob.h, Source/Core/DiscIO/FileBlob.h, Source/Core/DiscIO/ScrubbedBlob.h, Source/Core/DiscIO/TGCBlob.h, Source/Core/DiscIO/VolumeFileBlobReader.cpp, Source/Core/DiscIO/VolumeFileBlobReader.h, Source/Core/DiscIO/WIABlob.cpp, Source/Core/DiscIO/WIABlob.h, Source/Core/DiscIO/WbfsBlob.h, Source/Core/DolphinQt/Config/InfoWidget.cpp, Source/Core/DolphinQt/Config/InfoWidget.h, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h, Source/Core/UICommon/GameFileCache.cpp
=> Show file format details in game properties

Source/Core/Core/State.cpp, Source/Core/VideoCommon/FreeLookCamera.cpp
Fixes https://bugs.dolphin-emu.org/issues/12168
=> FreeLookCamera: Fix savestate branch inconsistency.

Source/Core/VideoCommon/RenderBase.cpp
This profiler was added in PR #1574, but must've broken at some point.
=> VideoCommon: Show profiler output again

Source/Android/app/src/main/res/layout/dialog_game_details.xml
This makes the dialog scrollable if the contents don't fit on the screen. This happens for me in landscape but not in portrait.
The changeset is best read with whitespace differences ignored.
=> Android: Wrap game details dialog in ScrollView

Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h
https://bugs.dolphin-emu.org/issues/12190
=> DolphinQt: Show WAD as "WAD" instead of "" in file format column

Source/Android/jni/GameList/GameFile.cpp, Source/Android/jni/GameList/GameFileCache.cpp, Source/Android/jni/MainAndroid.cpp
=> Android: Some simple Clang-Tidy suggestions

Source/Core/Core/HW/EXI/EXI_Channel.h, Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/DiscIO/WIABlob.cpp, Source/Core/DolphinQt/Debugger/ThreadWidget.cpp, Source/Core/DolphinQt/GameList/GameList.cpp
=> Fix some GCC warnings

Data/Sys/GameSettings/REF.ini, Data/Sys/GameSettings/RES.ini, Data/Sys/GameSettings/SP7.ini, Data/Sys/GameSettings/WW2.ini, Data/Sys/GameSettings/WW3.ini, Data/Sys/GameSettings/WWI.ini
Safe texture cache for My French/Spanish coach (https://bugs.dolphin-emu.org/issues/12196).
XFB to Texture and Ram for Where is Wally? 1-3 (https://bugs.dolphin-emu.org/issues/12159).
EFB to texture and ram for Pac-Man Party (https://bugs.dolphin-emu.org/issues/12102).
=> INI updates

Source/Android/app/build.gradle, Source/Android/app/src/main/AndroidManifest.xml
When using the combination of Android 11 and HDMI 2.1, this will send a signal to the TV suggesting it to switch to a low latency mode ("game mode").
=> Android: Set preferMinimalPostProcessing="true"

Source/Core/DiscIO/WIABlob.cpp
Should fix https://bugs.dolphin-emu.org/issues/12208.
=> DiscIO: Fix conversion warning

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CoverHelper.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
Users may be surprised that "Clear Game Settings" doesn't also clear game profiles. I also specified when exceptions are ignored, as recommended by Android Studio.
=> Android: Clear game profiles and GameSettings

Source/Core/Common/Logging/LogManager.h
Follow-up to #7252. @Tilka 
Android Studio didn't catch this.
=> LogManager: Add missing include

Source/Core/Core/Analytics.cpp
Title. Some minor code reuse from ``IsRunningOnMojaveOrHigher()`` in ``VideoBackends/Vulkan/main.cpp``.
=> Analytics: Replace usage of Gestalt for retrieving macOS version

Source/Core/VideoCommon/FrameDump.cpp
Fixes a regression where PR #8988 made all dumped video super long.
=> FrameDump: Don't ignore the time base numerator

Source/Core/Core/Boot/DolReader.cpp
some homebrew sets `dataOffset[i]+dataSize[i]` larger than file size
=> DolReader: treat overly large data segment as bss

Source/Core/Core/HLE/HLE.cpp, Source/Core/Core/HLE/HLE.h, Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/Jit.h
This PR cleans up some stuff (function name, coding style, ...) in the HLE code.
=> HLE cleanup

Source/Core/DolphinQt/Settings.cpp
Was incorrectly changed here: https://github.com/dolphin-emu/dolphin/commit/b0f9bb9f136053c3fb164704e4d34a0ab0dd5dea#diff-ad53777a37ff0c5e93f0efa7951a7940
=> Settings: Fix incorrect config key for enabled analytics.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java, Source/Android/jni/MainAndroid.cpp, Source/Core/VideoCommon/OnScreenDisplay.cpp, Source/Core/VideoCommon/OnScreenDisplay.h
https://bugs.dolphin-emu.org/issues/12256
=> Android: Move OSD out of the way when menu is open

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FloatSliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/IntSliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/PercentSliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/res/values/arrays.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/NativeConfig.cpp, Source/Core/Core/BootManager.cpp, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Now that PR #8975 is merged, we can finally add this without hacks.
https://bugs.dolphin-emu.org/issues/11605
=> Android: Add Wii SYSCONF settings to GUI

Source/Android/app/src/main/res/values/arrays.xml
That's what I get for copy-pasting
=> Android: Fix convertCompressionLevelZstdValues

Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayClient.h, Source/Core/Core/NetPlayProto.h
This just fixes the regression of #8985.
Wii remotes in NetPlay still suck.
=> Core/NetPlay: Fix Wii Remote syncing.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFile.java, Source/Android/jni/GameList/GameFile.cpp, Source/Core/DolphinQt/Config/InfoWidget.cpp, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFile.h, Source/Core/UICommon/GameFileCache.cpp
To make people more aware that they're not using a normal disc image.
=> Show NKitness in file format string

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
=> Android: Correct SliderSetting minimum value behavior on API < 26

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/ConfirmRunnableViewHolder.java
=> Android: Remove finish from ConfirmRunnableViewHolder

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
It would be difficult to use the AlertMessage class for messages that need to be showed outside of emulation, but showing them as toasts is better than not showing them.
=> Android: Show alert messages as toasts outside of emulation

Languages/po/qt-strings.pot, Languages/update-source-strings.sh
https://bugs.dolphin-emu.org/issues/11507
=> Fix predefined Qt strings not getting translated

Source/Core/DiscIO/VolumeVerifier.cpp
Not much use in knowing that the H3 hashes are wrong when the partition consists of complete garbage.
=> VolumeVerifier: Make "no valid data in partition" hide some other errors

Source/Core/VideoCommon/GeometryShaderGen.cpp
Continues migration of the shader generators over to fmt.
=> GeometryShaderGen: Migrate over to fmt

Source/Core/VideoCommon/UberShaderCommon.cpp, Source/Core/VideoCommon/UberShaderCommon.h
Continues migration of the shader generators over to fmt.
=> UberShaderCommon: Migrate over to fmt

Source/Core/AudioCommon/AlsaSoundStream.cpp, Source/Core/AudioCommon/AudioCommon.cpp, Source/Core/AudioCommon/AudioStretcher.cpp, Source/Core/AudioCommon/CubebStream.cpp, Source/Core/AudioCommon/CubebUtils.cpp, Source/Core/AudioCommon/Mixer.cpp, Source/Core/AudioCommon/OpenALStream.cpp, Source/Core/AudioCommon/PulseAudioStream.cpp, Source/Core/AudioCommon/WASAPIStream.cpp
=> AudioCommon: Migrate logging over to fmt

Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp, Source/Core/InputCommon/ControllerInterface/DInput/DInput.cpp, Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp, Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp, Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPProto.h, Source/Core/InputCommon/ControllerInterface/OSX/OSX.mm, Source/Core/InputCommon/ControllerInterface/OSX/OSXJoystick.mm, Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp, Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.cpp, Source/Core/InputCommon/ControllerInterface/Win32/Win32.cpp, Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp, Source/Core/InputCommon/DynamicInputTextureConfiguration.cpp, Source/Core/InputCommon/GCAdapter.cpp, Source/Core/InputCommon/GCAdapter_Android.cpp
Continues the migration of the logging calls over to the fmt capable ones.
=> InputCommon: Migrate logging over to fmt

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/SaveLoadStateFragment.java, Source/Android/app/src/main/res/layout/fragment_saveload_state.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/app/src/main/res/values/styles.xml, Source/Android/jni/MainAndroid.cpp, Source/Core/Core/State.cpp, Source/Core/Core/State.h
=> Android: Show how long ago each savestate was created

Source/Core/Common/FileUtil.cpp
Fixes a recent regression: https://github.com/dolphin-emu/dolphin/pull/9187#issuecomment-716835091
=> FileUtil: Fix format string

Source/Core/DolphinQt/DolphinQt.vcxproj
=> dolphinqt msbuild: do not moc TASSlider.h

Source/Core/DolphinQt/Debugger/RegisterWidget.cpp
Resolves https://bugs.dolphin-emu.org/issues/12261
=> DolphinQt: Update register view font when Debug Font changes

Source/PCH/pch.h
Drops compile time by a couple seconds
=> Add some files to pch

Source/Core/Common/LinearDiskCache.h, Source/Core/VideoBackends/Vulkan/ObjectCache.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp
File::IOFile is better suited to this type of task. Split out from a future PR.
=> Common/LinearDiskCache: Replace std::fstream with File::IOFile

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Hopefully fixes https://bugs.dolphin-emu.org/issues/12316.
=> Android: Add null check for InputOverlay

Source/Core/InputCommon/InputConfig.cpp
Continues the migration over to fmt.
=> InputCommon: Migrate over to fmt-capable panic alerts

Source/Core/Core/WiiUtils.cpp
Fixes https://bugs.dolphin-emu.org/issues/12269 -- at least for Mega Man 9.
=> WiiUtils: Create Wii Shop log files when installing a WAD.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/WiimoteProfileSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
It's still not exactly pretty, but now all the mess is contained in one place and has a proper interface.
Fixes https://bugs.dolphin-emu.org/issues/12218.
=> Android: Remove hacks for Wii Remote extension setting, round 2

Source/Core/DolphinQt/MenuBar.cpp
If you wish to only display games from only one region you currently have to open the View -> Regions menu 13 times to manually deselect every other region.  This PR adds "Show All" and "Hide all" options to simplify the process.
=> DolphinQt: Add Show/Hide All options to gamelist region menu

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
See https://github.com/dolphin-emu/dolphin/pull/9095#pullrequestreview-535576465.
Marked as a draft because I haven't been able to build it yet. Latest master fails to compile on my Android Studio install.
=> Android: Fix IllegalStateException on startup

Source/Core/Common/FormatUtil.h, Source/Core/Common/MsgHandler.h, Source/Core/Core/HW/DVD/DVDInterface.cpp, Source/Core/Core/HW/DVD/DVDThread.cpp, Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/ImageWrite.cpp, Source/Core/VideoCommon/RenderBase.cpp
Like PR #9260, but for a different requirement (see PR #9253).
=> Common: Assert that translatable strings use positional arguments

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SettingsItem.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/CheckBoxSettingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/FilePickerViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/HeaderViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/InputBindingSettingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RumbleBindingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RunRunnableViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SettingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SingleChoiceViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SliderViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SubmenuViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java, Source/Android/app/src/main/res/values/strings.xml
This is particularly important for game INIs, where a setting being unset is not the same as it being set to the default value.
=> Android: Long press a setting to reset it

Source/Core/Core/ARDecrypt.cpp, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/HW/AudioInterface.cpp, Source/Core/Core/HW/EXI/EXI_DeviceAGP.cpp, Source/Core/Core/HW/WII_IPC.cpp, Source/Core/Core/NetPlayServer.cpp
Converts over some lingering log calls that I missed in previously converted files within Core.
=> Core: Convert missed log calls over to fmt

Source/Core/VideoCommon/UberShaderVertex.cpp
=> Fix vertex ubershader GLES compile errors

Source/Core/Core/IOS/ES/Identity.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.cpp, Source/Core/Core/IOS/FS/HostBackend/FS.cpp, Source/Core/Core/IOS/FS/HostBackend/File.cpp, Source/Core/Core/IOS/Network/IP/Top.cpp, Source/Core/Core/IOS/Network/KD/NWC24Config.cpp, Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp, Source/Core/Core/IOS/Network/KD/NetKDTime.cpp, Source/Core/Core/IOS/Network/MACUtils.cpp, Source/Core/Core/IOS/Network/NCD/Manage.cpp, Source/Core/Core/IOS/Network/NCD/WiiNetConfig.cpp, Source/Core/Core/IOS/Network/SSL.cpp, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/IOS/Network/Socket.h, Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp, Source/Core/Core/IOS/STM/STM.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTBase.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTStub.cpp, Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp, Source/Core/Core/IOS/USB/Host.cpp, Source/Core/Core/IOS/USB/LibusbDevice.cpp, Source/Core/Core/IOS/USB/OH0/OH0.cpp, Source/Core/Core/IOS/USB/USBV5.cpp, Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp, Source/Core/Core/IOS/USB/USB_KBD.cpp, Source/Core/Core/IOS/WFS/WFSI.cpp, Source/Core/Core/IOS/WFS/WFSSRV.cpp
Continues the migration of logging in the Core library. This part finishes up the remaining log calls within the IOS code.
=> Core: Convert logging over to fmt pt.4

Source/Core/Core/IOS/Network/IP/Top.cpp
I don't know if that will change anything but this PR should fix the IP fallback values.
=> IP/Top: Fix fallback IP address

Source/Core/Core/PowerPC/PowerPC.cpp
This issue is both severe and surprisingly difficult to find the root cause of, so I think it would make sense to add a simple hotfix for now. https://bugs.dolphin-emu.org/issues/12327
=> JitArm64: Add a workaround for issue 12327

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/res/values/strings.xml
This will make it easier to clear the log file of old entries. Clearing the file instead of deleting it will make the file easier to monitor.
=> Android: Clear Log file

Source/Core/DiscIO/DiscExtractor.cpp, Source/Core/DiscIO/FileSystemGCWii.cpp, Source/Core/DiscIO/FileSystemGCWii.h, Source/Core/DiscIO/Filesystem.h
https://bugs.dolphin-emu.org/issues/12331
=> DiscIO: Fix recursive directory extraction

Source/Core/InputCommon/DynamicInputTextureConfiguration.cpp
This fixes dynamic input textures not being generated when a host key isn't mapped.
I broke this when I switched the logic to use regions instead of color keys...
Master:
(mapped A -> B at the end just to show that we are using dynamic input textures)
This PR:
=> InputCommon: fix dynamic input textures when host key isn't mapped

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Add cases to handle all one and all zero masks.
=> Jit_Integer: Add trivial AndWithMask cases

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/BitUtils.h, Source/Core/Common/MathUtil.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp, Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Normalize on one common implementation for CLZ.
=> BitUtils: Add CountLeadingZeros

Source/Core/Core/PowerPC/Jit64/Jit.h, Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Small codesize reduction from MOV;ROL -> RORX.
=> Jit_Integer: Use RORX where possible

Source/Core/Core/DSP/DSPCore.cpp, Source/Core/Core/DSP/DSPCore.h, Source/Core/Core/DSP/Interpreter/DSPIntBranch.cpp, Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitBranch.cpp
Makes some values more immediately readable.
=> DSP: Eliminate some magic values related to the CR register

Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, Source/Core/Core/State.cpp, Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp, Source/Core/DolphinQt/QtUtils/ElidedButton.cpp, Source/Core/InputCommon/ControllerEmu/ControllerEmu.h, Source/Core/VideoCommon/RenderBase.cpp
and removed some unused includes.
=> Fix typos and code coding conventions

Source/Android/app/build.gradle
=> Android: Update dependencies to the latest version

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainView.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/BooleanSupplier.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CompletableFuture.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/WiiUtils.java, Source/Android/app/src/main/res/menu/menu_game_grid.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/AndroidCommon/IDCache.h, Source/Android/jni/CMakeLists.txt, Source/Android/jni/MainAndroid.cpp, Source/Android/jni/WiiUtils.cpp, Source/Core/Core/HW/WiiSave.h
Exporting will have to wait for another PR, because I need to implement more SAF stuff first.
=> Android: Add "Import Wii Save"

Source/Core/Common/Random.cpp, Source/Core/Common/Random.h, Source/UnitTests/Core/CMakeLists.txt, Source/UnitTests/Core/PowerPC/JitArm64/MovI2R.cpp
=> UnitTests: Add MOVI2R test

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java, Source/Android/app/src/main/res/values/arrays.xml
Android follow-up for PR #9461.
=> Android: Adjust logic for DOL/ELF long press

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.h, Source/Core/DolphinQt/Debugger/CodeWidget.cpp, Source/Core/DolphinQt/MainWindow.cpp
This PR adds another enum value to also update the function calls and callers which are CodeWidget views.
=> CodeViewWidget: Add WithDetailedUpdate to update CodeWidget

Source/Core/Common/Arm64Emitter.cpp
https://github.com/dolphin-emu/dolphin/pull/9412#issuecomment-779329306
Untested, since I don't have a GCC install.
=> JitArm64: Workaround for GCC ICE

Source/Core/Core/IOS/FS/FileSystemProxy.cpp
According to hwtests, older versions of IOS are slower at performing
various filesystem operations:
https://docs.google.com/spreadsheets/d/1OKo9IUuKCrniz4m0kYIaMP_qFtOCmAzHZ_zAmobvBcc/edit
(courtesy of JMC)
(More plots available at https://dolphin.leolam.fr/fs_timing/)
A quick glance at IOS9 reveals that older versions of IOS have a
simplistic implementation of memcpy that does not optimize large copies
by copying 16 bytes or 32 bytes per chunk, which makes cached reads
and writes noticeably slower -- the difference was significant enough
that the OoT speedrunning community noticed that IOS9 (the IOS that
is used for the OoT VC title) was slower.
=> IOS/FS: Implement timings for older IOS versions as well

Source/Core/DolphinLib.props, Source/Core/InputCommon/CMakeLists.txt, Source/Core/InputCommon/DynamicInputTextureManager.cpp, Source/Core/InputCommon/DynamicInputTextureManager.h, Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.cpp, Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.h, Source/Core/InputCommon/DynamicInputTextures/DITData.h, Source/Core/InputCommon/DynamicInputTextures/DITSpecification.cpp, Source/Core/InputCommon/DynamicInputTextures/DITSpecification.h
This will come across as a big change but really I'm just moving some code around and adding a "specification" option in json, so that I can add a new set of features in a future PR.
=> InputCommon: move some dynamic input texture logic and add specification option

Source/Core/Core/HW/Memmap.cpp
Mostly I have a build to suggest over here to see if this could be a failure in InitFastmemArena(), which is silent on master: https://forums.dolphin-emu.org/Thread-wii-games-extremely-slow-after-revision-5-0-11476
=> Core/Memmap: Give more detailed error messages if memory mapping fails.

Source/Core/Core/Debugger/PPCDebugInterface.cpp
This PR is an attempt to fix https://bugs.dolphin-emu.org/issues/12410.
=> DebugInterface: Check visited addresses in GetThreads

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/BooleanSupplier.java, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/IniFile.cpp, Source/Android/jni/MainAndroid.cpp, Source/Android/jni/NativeConfig.cpp
Details in the individual commits.
=> Android: Some JNI cleanup

Source/Core/Common/CMakeLists.txt, Source/Core/Common/SocketContext.cpp, Source/Core/Common/SocketContext.h, Source/Core/Core/IOS/Network/IP/Top.cpp, Source/Core/Core/IOS/Network/IP/Top.h, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/DolphinLib.props
=> Common / Core: add raii object that cleans up WSA on destruction in gdb-stub

Source/Core/Core/PowerPC/MMU.cpp
This PR fixes the `IsRAMAddress` function returning true when the RAM is NULL. It can happen very rarely when the hardware is shutting down and there is something interacting with the RAM at the same time like some debugger widgets.
=> MMU: Fix IsRAMAddress not working

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Deduplicates code between MainActivity and TvMainActivity.
=> Android: Move "skip scanning" logic to MainPresenter

Tools/ghidra/LoadDolphinMap.py, Tools/ghidra/SaveDolphinMap.py
This PR ports IDA scripts to ghidra.
=> Tools: Dolphin symbol map ghidra scripts added

Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
While looking at the DSU server stuff for the GDB stub, I noticed that the DSU logic has each server waiting individually for a timeout.  That has the potential to cause issues, so instead we should wait once for all servers.
Alternatively if the thread won't be spin-waiting, it may be more beneficial to have these sockets not block at all.  However, I decided to keep the original blocking timeout for now.
=> InputCommon: block on DSU servers collectively instead of individually

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Same approach as Jit64. A lot simpler, don't you think? :)
=> JitArm64: Optimize general case of srawx

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/res/values/strings.xml
This brings the available settings in the Hacks section in line with DolphinQt.
=> Android: Add some missing settings to Hacks section of Graphics

Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
I missed one place in PR #9485.
=> JitArm64: Use STP for pc/npc, part 2

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/BootManager.cpp, Source/Core/Core/CMakeLists.txt, Source/Core/Core/Config/DefaultLocale.cpp, Source/Core/Core/Config/DefaultLocale.h, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/SYSCONFSettings.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/Host.h, Source/Core/DiscIO/Enums.cpp, Source/Core/DiscIO/Enums.h, Source/Core/DolphinLib.props, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Host.cpp, Source/DSPTool/StubHost.cpp, Source/UnitTests/StubHost.cpp
Marking as a draft until PR #9571 is merged, to ensure that this doesn't cause any nasty desyncs for netplay and movies. Ready for review otherwise.
=> Set console's default language/country/region based on computer settings

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/CheckBoxSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FilePicker.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FloatSliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/HeaderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/InputBindingSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/IntSliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/InvertedCheckBoxSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/LogCheckBoxSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/PercentSliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/RumbleBindingSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/RunRunnable.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SettingsItem.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SingleChoiceSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SingleChoiceSettingDynamicDescriptions.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SliderSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/StringSingleChoiceSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SubmenuSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/CheckBoxSettingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/FilePickerViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/HeaderViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/InputBindingSettingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RumbleBindingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/RunRunnableViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SingleChoiceViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SliderViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SubmenuViewHolder.java
The first commit of this pull request is a refactorization commit I wanted to split out from PR #9696 because it touches many lines of code. The second commit is new and removes a hack that we don't need anymore after the refactorization.
=> Android: Use CharSequence for SettingsItem name/description

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, Source/Core/Core/PowerPC/PPCAnalyst.cpp
This is a port of PR #834 to JitArm64.
=> JitArm64: Fix fmul rounding issues

Source/Core/UICommon/AutoUpdate.cpp
=> DolphinQt: AutoUpdate.cpp should use scm_rev_git_str

Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp
This is based on #9720 so I don't have to deal with a merge conflict later. Merge that one first.
=> NetPlay: Add some missing synced settings

Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp, Source/Core/Core/HW/DSPHLE/UCodes/INIT.cpp, Source/Core/Core/HW/DSPHLE/UCodes/INIT.h, Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
=> DSP: small cleanup

Source/Core/Core/HLE/HLE.cpp, Source/Core/Core/HLE/HLE_OS.cpp, Source/Core/Core/HW/AudioInterface.cpp, Source/Core/Core/HW/DSP.h, Source/Core/Core/HW/DVD/DVDInterface.h, Source/Core/Core/HW/EXI/EXI.cpp, Source/Core/Core/HW/EXI/EXI.h, Source/Core/Core/HW/GPFifo.cpp, Source/Core/Core/HW/MemoryInterface.cpp, Source/Core/Core/HW/MemoryInterface.h, Source/Core/Core/HW/SI/SI.cpp, Source/Core/Core/HW/SI/SI.h, Source/Core/InputCommon/GCAdapter.cpp, Source/Core/InputCommon/GCAdapter.h, Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/PixelEngine.cpp, Source/Core/VideoCommon/PixelEngine.h
This PR homogenizes end of namespace comments.
=> Lint: End of namespace

Source/Core/Core/PowerPC/Interpreter/Interpreter.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp
=> Interpreter: deduplicate integer comparisons

Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
I'm also planning to implement the other system register instructions that deal with FPSCR. But you will have to merge this PR first :)
=> JitArm64: Implement mcrfs

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
=> JitArm64: Handle SO and LT simultaneously in mfcr

Source/Core/Common/UPnP.cpp
Mostly because I got confused by Dolphin reporting an error with `upnperror == UPNPDISCOVER_SUCCESS`.
=> UPnP: Improve error messages on initialization failure.

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
If a branch is unconditional, its target should not be in farcode, since that defeats the purpose of farcode (putting seldom executed code in farcode to keep it out of the icache when possible).
=> JitArm64: Get rid of an unconditional branch to farcode

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Part 2 of implementing the FPSCR system register instructions.
=> JitArm64: Implement mffsx

Source/Core/UpdaterCommon/UpdaterCommon.cpp
Because RenameFile on Windows is apparently cursed.
=> UpdaterCommon: Use File::Copy() on non-macOS platforms

Source/Core/Common/BitSet.h
seems to have been solved 5 years ago by
b707e199c2878d173c5d30f0a24db93d7de1d921
=> remove an outdated comment

Data/Sys/Shaders/lens_distortion.glsl, Source/Core/VideoCommon/PostProcessing.cpp
See individual commit messages.
=> PostProcessing: fix shader compilation failures

Data/Sys/Shaders/lens_distortion.glsl
I guess this has never worked when using Direct3D.
=> PostProcessing: fix lens distortion shader for HLSL

Source/Core/VideoCommon/PixelShaderGen.cpp
For whatever stupid reason, Mali drivers do not allow overloading built-in functions.
=> VideoCommon: Expand vector comparisons instead of overloading any()

Data/Sys/GameSettings/SHX.ini
Personally confirmed 2048 samples weren't enough.  Some text was still missing.
=> GameINI:  Fix Happy Feet 2 Text

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Part 3 of implementing the FPSCR system register instructions.
=> JitArm64: Implement mtfsb0x

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Part 4 of implementing the FPSCR system register instructions.
=> JitArm64: Implement mtfsb1x

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp, Source/Core/Core/State.cpp
=> DSPHLE: include compressor state in save states

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Part 5 of 6 of implementing the FPSCR system register instructions.
=> JitArm64: Implement mtfsfix

Externals/mGBA/mgba.vcxproj
=> msbuild: reduce number of cl batches for mgba

Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/DolphinAnalytics.h, Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
Not including GC DPL2 mixing here since it's easy to find games that use it.
=> DSPHLE: report games that use unimplemented AX features

Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
=> JitArm64: Fix W8 slowmem store

Source/Core/Core/PowerPC/MMU.cpp
Fixes https://bugs.dolphin-emu.org/issues/12611.
=> PowerPC: Fix bad copypaste in LookupTLBPageAddress

Source/Core/Core/ActionReplay.cpp, Source/Core/Core/BootManager.cpp, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/GeckoCode.cpp, Source/Core/Core/HLE/HLE.cpp, Source/Core/DolphinQt/Settings.cpp
Split out from my upcoming Android cheats PR.
=> Port Enable Cheats to the new config system

Data/Sys/GameSettings/ECH.ini, Data/Sys/GameSettings/ECM.ini
These two games were missed in PR #3841.
=> GameSettings: force DSPLLE in remaining Neo Geo games

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
After creating PR #10034 without realizing that we hadn't actually implemented the indexed paired loadstore instructions yet, I am now implementing them.
=> JitArm64: Implement indexed paired loadstore instructions

Source/Core/Core/HW/DVD/DVDInterface.cpp
Continues the migration of low hanging fruit over to Common::BitField
=> DVDInterface: Migrate bitfields over to Common::BitField

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/DolphinQt/Settings/AudioPane.cpp, Source/Core/DolphinQt/Settings/BroadbandAdapterSettingsDialog.cpp, Source/Core/DolphinQt/Settings/BroadbandAdapterSettingsDialog.h, Source/Core/DolphinQt/Settings/GameCubePane.cpp, Source/Core/DolphinQt/Settings/GeneralPane.cpp, Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.cpp, Source/Core/DolphinQt/Settings/WiiPane.cpp
See PR #10073. A beta build has been released now, so there's no reason to keep it reverted anymore.
=> Revert "Revert "DolphinQt: Minor consistency fixes for the Settings window""

Source/Core/Core/HW/SI/SI_DeviceKeyboard.cpp, Source/Core/Core/HW/SI/SI_DeviceKeyboard.h
We can wrap this logic into a lambda to avoid copy-pasted checking of over 400+ lines of code.
=> SI_DeviceKeyboard: Shorten MapKeys()

Source/Core/DiscIO/RiivolutionPatcher.cpp
This fixes the booting of Wii Sports Resort Storm Island, [as reported on the forums](https://forums.dolphin-emu.org/Thread-wii-sports-resort-storm-island-freezes-at-intro-screen-riivolution).
=> Fix some Riivolution file patching edge cases.

Source/Android/app/src/main/AndroidManifest.xml, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/model/RiivolutionPatches.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionBootActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionItem.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java, Source/Android/app/src/main/res/layout/activity_riivolution_boot.xml, Source/Android/app/src/main/res/layout/list_item_riivolution_header.xml, Source/Android/app/src/main/res/layout/list_item_riivolution_option.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/AndroidCommon/IDCache.h, Source/Android/jni/CMakeLists.txt, Source/Android/jni/MainAndroid.cpp, Source/Android/jni/RiivolutionPatches.cpp, Source/Core/DiscIO/RiivolutionParser.cpp, Source/Core/DiscIO/RiivolutionParser.h
=> Android: Allow starting game with Riivolution patches from the GUI

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
=> Jit_Integer: Fix pure rotation rlwimix case

Source/Core/Common/Matrix.cpp
Fix comment to say (NxM times MxP).
=> Minor comment fix in Matrix.cpp

Data/Sys/GameSettings/GJB.ini
Reverts dolphin-emu/dolphin#10217
This was fixed by PR #10244
=> Revert "Force Dual Core on for Bomberman Jetters"

Source/Core/DiscIO/RiivolutionParser.cpp
Apparently I forgot to do this and never noticed, oops.
=> RiivolutionParser: Create config xml directory if it does not exist yet.

Source/Core/Core/NetPlayCommon.cpp
https://bugs.dolphin-emu.org/issues/12765
=> Core: Add missing header to NetPlayCommon.cpp

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/res/values/strings.xml
The Android version of PR #10280. No scoped storage support, though...
=> Android: Make WFS directory configurable

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/FifoPlayer/FifoPlayer.cpp
=> Config: Port FifoPlayer setting to new config system.

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/IOS/USB/Host.cpp, Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.cpp, Source/Core/DolphinQt/Settings/WiiPane.cpp
Had to redesign this a bit due to the `std::set<std::pair<>>` nature of the setting... I think this is fine but I'm open to other ideas.
=> Config: Port USBPassthrough setting to new config system.

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/Core.cpp, Source/Core/Core/HLE/HLE.cpp, Source/Core/Core/HW/VideoInterface.cpp, Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/JitAsm.cpp, Source/Core/Core/PowerPC/Jit64Common/BlockCache.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.h, Source/Core/Core/PowerPC/PPCAnalyst.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h, Source/Core/Core/PowerPC/PowerPC.cpp, Source/Core/Core/TitleDatabase.cpp, Source/Core/DolphinNoGUI/PlatformX11.cpp, Source/Core/DolphinQt/Debugger/JITWidget.cpp, Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/RenderWidget.cpp, Source/Core/DolphinQt/Resources.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Translation.cpp
Pretty straightforward except for the 'debug UI' flag, which I have cached in the `JitBase` and `PPCAnalyzer`.
=> Config: Port remaining Interface settings to new config system.

AndroidSetup.md
=> Use HTTPS for images

Externals/MoltenVK/CMakeLists.txt
=> MoltenVK: Update to version 1.1.6

Source/Core/DiscIO/GameModDescriptor.cpp, Source/Core/DiscIO/GameModDescriptor.h, Source/Core/UICommon/GameFile.cpp, docs/game-mod-descriptor.json
This has been requested over in #10187.
=> Core: Add a Maker field for GameModDescriptors.

Source/Core/UICommon/USBUtils.cpp
Based on https://forums.dolphin-emu.org/Thread-wii-rock-band-3?pid=521274#pid521274.
=> USBUtils: Add/fix some Rock Band devices

Source/Core/Core/HW/SystemTimers.cpp
This static variable was only used within one function, so we can get rid of it.
=> SystemTimers: Refactor, get rid of s_audio_dma_period

Source/Core/AudioCommon/WaveFile.cpp, Source/Core/Common/IOFile.cpp, Source/Core/Common/IOFile.h, Source/Core/Common/LinearDiskCache.h, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/FifoPlayer/FifoDataFile.cpp, Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp, Source/Core/Core/HW/GCMemcard/GCIFile.cpp, Source/Core/Core/HW/GCMemcard/GCMemcard.cpp, Source/Core/Core/HW/WiiSave.cpp, Source/Core/Core/IOS/FS/HostBackend/File.cpp, Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp, Source/Core/Core/IOS/WFS/WFSSRV.cpp, Source/Core/Core/Movie.cpp, Source/Core/DiscIO/CISOBlob.cpp, Source/Core/DiscIO/CompressedBlob.cpp, Source/Core/DiscIO/DirectoryBlob.cpp, Source/Core/DiscIO/DriveBlob.cpp, Source/Core/DiscIO/FileBlob.cpp, Source/Core/DiscIO/NANDImporter.cpp, Source/Core/DiscIO/TGCBlob.cpp, Source/Core/DiscIO/WIABlob.cpp, Source/Core/DiscIO/WbfsBlob.cpp, Source/Core/DiscIO/WiiSaveBanner.cpp, Source/Core/VideoCommon/HiresTextures_DDSLoader.cpp, Source/Core/VideoCommon/ShaderCache.cpp
Better abstraction in Seek() and more obvious name for Clear().
=> Minor IOFile cleanup.

Source/Core/VideoCommon/TextureCacheBase.cpp
Also known as "Fix copy filter clamping (again (again))".  This is the same code as in #10396, just in a different location.  Note that "disable copy filter" is ignored (and the copy filter is always used) for EFB to RAM copies.
=> Fix copy filter clamping when EFB VRAM copies are disabled

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateProgressBarDialogFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateRegionSelectDialogFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateResultFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/SystemMenuNotInstalledDialogFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/SystemUpdateViewModel.java
=> Android: Add some missing license comments

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/ConvertActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/AlertMessage.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatDetailsFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatItemViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/HeaderViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionBootActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FilePicker.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/LogCheckBoxSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SettingsItem.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/CheckBoxSettingViewHolder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/ConvertFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesView.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/AlertDialogItemsBuilder.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ContentHandler.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/NetworkHelper.java, Source/Android/app/src/main/res/menu/menu_settings.xml
This was done using Android Studio. These imports are no longer used, so we might as well remove them.
=> Android: Optimize imports

Source/Core/Core/State.cpp
Probably fixes https://bugs.dolphin-emu.org/issues/12830.
=> Core/State: Add some multithreading protections.

Source/Core/Common/MemArena.h, Source/Core/Common/MemArenaWin.cpp
See https://github.com/dolphin-emu/dolphin/pull/9544#issuecomment-1039525456
I have no Win7 machine to test this so someone please do.
=> MemArena: Restore Windows 7 support.

Source/Core/Common/JitRegister.cpp, Source/Core/Common/JitRegister.h, Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp, Source/Core/Core/PowerPC/Jit64Common/TrampolineCache.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/VideoCommon/VertexLoaderX64.cpp
Prefer fmt to printf-style formatting.
=> JitRegister: Use fmt

Source/Core/DolphinQt/Config/Graphics/PostProcessingConfigWindow.cpp, Source/Core/VideoCommon/PostProcessing.cpp, Source/Core/VideoCommon/PostProcessing.h
Convert VideoCommon::PostProcessingConfiguration::ConfigurationOption::OptionType to enum class.
=> VideoCommon: Convert OptionType to enum class

Source/Core/DolphinQt/MenuBar.cpp
=> Fix manual update check which was hardcoded to "dev" track

Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinTool/ToolMain.cpp
=> windows: wrap all main funcs with utf8 conversions

Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayCommon.h, Source/Core/Core/NetPlayServer.cpp
Amendment to 600c816 as I missed the traversal case.
=> NetPlay: Add timeout to traversal code path

Source/VSProps/Base.props
#10516 inadvertently disabled autoupdating for our Windows builds...
=> Re-enable Auto-Update when building with VS project files.

Data/Sys/GameSettings/GRY.ini, Data/Sys/GameSettings/GRYE41.ini
This was a typo that I missed for some reason.
=> Rename GYRE41.ini to GRYE41.ini

Source/Core/DolphinQt/CheatSearchWidget.cpp, Source/Core/DolphinQt/CheatsManager.cpp
Some minor things requested here: https://forums.dolphin-emu.org/Thread-hexadecimal-searches-cheat-manager?pid=522280#pid522280
=> DolphinQt: More Cheat Search QoL

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
This PR fixes the preview of zero as float/double.
=> MemoryWidget: Fix preview of zero as float/double

Source/Core/InputCommon/ControllerInterface/WGInput/WGInput.cpp
Attempt to fix https://bugs.dolphin-emu.org/issues/12879, untested.
=> Core/WGInput: Dynamically load winrt function addresses.

Source/Core/Core/HW/Memmap.cpp
This is an extract of a change I made in the cancelled PR #8778.
=> Combine InitMMIO and InitMMIOWii

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
Should fix the crash reported in https://bugs.dolphin-emu.org/issues/12885
=> Android: Use AfterDirectoryInitializationRunner more comprehensively

.gitmodules, Source/Core/InputCommon/GCAdapter.cpp
fixes some regressions from updating libusb on macos
=> Libusb fixups

Data/Sys/GameSettings/GDK.ini, Data/Sys/GameSettings/GDQ.ini, Data/Sys/GameSettings/GWT.ini
Changed "memorycards" to "memory cards"
=> Added space in comment

Externals/MoltenVK/CMakeLists.txt
Fixes building on macOS Monterey 12.3+.
=> MoltenVK: Update to version 1.1.9

Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AX.h, Source/Core/Core/HW/DSPHLE/UCodes/AXStructs.h, Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
No functional change intended.
=> AX: preparatory cleanup

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
=> JitArm64: Implement low DCBZ hack

Source/Core/Core/PowerPC/PPCAnalyst.cpp
Otherwise every function will be the same color in the code view widget.
=> Index SymbolDB when generated from address

Source/Android/app/build.gradle
Upgrade material dependencies and Android NDK to current LTS version
=> Android: Upgrade dependencies

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Fixes https://bugs.dolphin-emu.org/issues/12912
=> Qt/MemoryViewWidget: Fix resizing.

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
Please
Please
I'm begging you to add this.
Having to click select after highlighting the cell.
Is draining me.
Please 
Please
Accept this poetry
For what it is
A cry for help
for the table widget hath sinned
=> Added double click to add expressions when mapping

Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp, Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
The DSP code only has minor differences to the final release.
=> DSPHLE: handle crc of Pikmin 1 GC US Demo

Externals/pugixml/pugiconfig.hpp, Externals/pugixml/pugixml.cpp, Externals/pugixml/pugixml.hpp
Updating pugixml to v1.12.1 resolves the following error, which seems to have originated on the exact commit of dolphin's previous version of pugixml.
=> Update pugixml to v1.12.1

Externals/MoltenVK/CMakeLists.txt
Title. Fixes https://bugs.dolphin-emu.org/issues/12840.
=> MoltenVK: Update to version 1.1.10

Contributing.md
This is a first draft of adding some help info to `Contributing.md`.
=> Added help information to Contributing.md

Source/dolphin-emu.sln
vs will make this change if it saves the sln, so i'm committing it to reduce unnecessary local diffs.
=> vs: uppercase a guid in the sln

Source/Core/AudioCommon/CubebUtils.cpp, Source/Core/Common/Logging/LogManager.h, Source/Core/DolphinQt/Config/LogWidget.cpp
- fix cubeb source file paths
- remove extra space inserted by Qt widget
=> logging improvements

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/res/values/arrays.xml, Source/Android/app/src/main/res/values/strings.xml
This makes the feature added in PR #10690 available in the Android GUI. My implementation of this builds on the code from PR #10625.
=> Android: Add "Broadband Adapter (Built In)" to settings

Source/Core/DiscIO/VolumeVerifier.cpp
We shouldn't set `m_read_errors_occurred` to true just because `is_data_needed` was false.
=> VolumeVerifier: Fix read_succeeded condition

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp
This PR addresses https://github.com/dolphin-emu/dolphin/pull/10896#discussion_r932729790.
=> BBA/BuiltIn: Fix network byte order issues

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp
This PR ensures that the required UDP ports are open.
=> BBA/BuiltIn: Ensure UDP ports are open

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp, Source/Core/Core/HW/EXI/EXI_DeviceEthernet.h
This PR implements an ARP table. _(This PR doesn't fix the SSDP issues)_
=> BBA/BuiltIn: Generate a MAC address for each new IP address

Source/Core/Common/Crypto/SHA1.cpp, Source/Core/Common/Crypto/SHA1.h, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DiscIO/VolumeVerifier.h, Source/Core/DolphinQt/Config/VerifyWidget.cpp, Source/Core/DolphinTool/VerifyCommand.cpp, Source/Core/DolphinTool/VerifyCommand.h
sets defaults based on cpu support
=> VolumeVerifier: enable fast hash functions by default

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
This had a lot of duplicated code and magic numbers.
=> Android: Refactor reading "wiiController" preference

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SyncChannelJobService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SyncProgramsJobService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/TvUtil.java
This a proper fix for https://bugs.dolphin-emu.org/issues/12561, which was previously fixed by a hackfix in PR #9841.
=> Android: Add app link intent URI to channels projection

Source/Android/app/src/main/res/layout-land/activity_user_data.xml
Alternative to PR #10823.
Master:
This PR:
=> Android: Add divider to landscape version of User Data activity

Readme.md
=> Fix minor typo in readme

Externals/MoltenVK/CMakeLists.txt
Solves a performance regression introduced in MoltenVK v1.1.3.
=> MoltenVK: Update to v1.1.11

Source/Core/Core/HW/ProcessorInterface.cpp, Source/Core/VideoCommon/AsyncRequests.cpp, Source/Core/VideoCommon/AsyncRequests.h
Fixes https://bugs.dolphin-emu.org/issues/13001
Not sure entirely if this is all proper, but it should work fine?
=> Fix crashes in dual core mode on a PI_FIFO_RESET

Externals/SDL/SDL2.vcxproj
post-v2.24.0 commit
fixes SDL hotplugging issues on windows
please also merge #11009
=> SDL: update to 42d09a8f42e3fbac7171d065199667b182da3fb4

Source/Core/VideoCommon/CommandProcessor.cpp
Edit error message to be less sarcastic. I doubt many users appreciate this when Dolphin has just crashed on them.
=> Edit error message

Source/Core/Core/HW/AudioInterface.cpp
This PR is another attempt to cleanup the audio interface.
There should be no functional changes.
=> AudioInterface: Cleanup

Source/Android/app/build.gradle
I looked through the behavioral changes found in [Android 13](https://developer.android.com/about/versions/13/behavior-changes-13) and none of the following should effect how the app behaves. The only application of intent-filters for our app are for the "channels" in the TV version and that will not be affected.
=> Android: Update target SDK version

Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.cpp
Not sure if this is a problem in practice, but better be safe than sorry.
=> TaTaCon: fix possible hotswap problem

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
Light
Before - 
After -
Dark
Before - 
After -
=> Android: Change swipe refresh colors to match other component colors

Readme.md
Fix Transifex link and update formatting.
=> Update Readme links

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
=> Jit64: boolX formatting fixes

Source/Core/Core/HW/WiimoteEmu/DesiredWiimoteState.cpp
=> Remove #pragma once in DesiredWiimoteState.cpp

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp, Source/Core/InputCommon/ControlReference/FunctionExpression.cpp
=> Input: Add "abs" input expression function.

Source/Core/Common/Matrix.cpp, Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
This should potentially fix IMU-simulated pointing occasionally going crazy.
=> Fix some bad quaternion math.

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h
This simplifies the callers of EmitShiftImm and EmitScalarShiftImm.
=> Arm64Emitter: Combine immh and immb for Emit(Scalar)ShiftImm

Source/Core/UpdaterCommon/UpdaterCommon.cpp
I realized we need to have a merge to master that actually modifies the Updater.exe file to test updating itself is really working.
=> this is a test commit for WinUpdater

Source/Core/UpdaterCommon/UpdaterCommon.cpp
this is intended to be merged after buildbot has generated a dev build from #11197
=> Updater: clarify a string

Data/Sys/GameSettings/SLE.ini
=> Add Safe Texture Cache for Deepak Chopra's Leela

Source/Core/Common/build_info.txt.in, Source/Core/MacUpdater/Info.plist.in, Source/Core/MacUpdater/MacUI.mm, Source/Core/UpdaterCommon/Platform.h, Source/Core/UpdaterCommon/UpdaterCommon.cpp, Source/Core/UpdaterCommon/UpdaterCommon.h, Source/Core/WinUpdater/Platform.cpp
uses the bundle version instead of build_info.txt
=> MacUpdater: check os version

Source/Core/DolphinQt/Info.plist.in
Adds a key to Info.plist with default value to test Updater - this commit is intended to be reverted
=> MacUpdater: test that os version check is working

Source/Core/DolphinQt/Info.plist.in
Reverts dolphin-emu/dolphin#11234
it is working correctly
=> Revert "MacUpdater: test that os version check is working"

Source/Core/VideoBackends/Metal/MTLMain.mm
Makes Metal backend compatible with headless rendering
=> VideoBackends:Metal: Headless render support

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/InsetsHelper.java
In Android 11, support for smooth keyboard animations was implemented. So here we enable them with the API level permitting.
Before - 
After -
=> Android: Use smooth keyboard animation in cheats activity

Data/Sys/GameSettings/G6S.ini
Fixes freezes/stuttering during FMV cutscenes.
=> Force Safe Texture Cache in Legend of Spyro: A New Beginning

Externals/SDL/SDL2.vcxproj, Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp, Source/Core/InputCommon/ControllerInterface/SDL/SDL.h
You can finally make a reasonable Joy Con → Wiimote + Nunchuck mapping!
=> Update SDL to 2.26

Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp
Someone on Discord is having issues with Netplay failing to sync saves for unclear reasons, and the current log output is not enough to diagnose the issue. So add some more logging here.
(Though after looking over the code, I suspect it's a corrupt Wii save, we don't handle that very gracefully.)
=> Netplay: Add more logging to save syncing.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/InsetsHelper.java, Source/Android/app/src/main/res/layout/activity_main.xml, Source/Android/app/src/main/res/values/strings.xml
This adds text to the FAB when expanded and shrinks the FAB on scroll. The text will return when scrolling up as well.
Basically making things clearer for first startup.
Demo - 
https://user-images.githubusercontent.com/14132249/205419796-4a8d2837-c521-47e1-b7d9-b1fc518f6a8c.mp4
=> Android: Use expanding Extended FAB

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateRegionSelectDialogFragment.java, Source/Android/app/src/main/res/values/arrays.xml, Source/Android/app/src/main/res/values/strings.xml
To prepare for Android translation support, I'm aggregating all of the strings into one place so they can all be translatable and be easier to work with.
=> Android: Migrate all strings to strings.xml

Source/Core/Core/MachineContext.h
=> MachineContext: Fix USE_SIGACTION_ON_APPLE on arm64

Source/Core/VideoCommon/PerformanceMetrics.cpp, Source/Core/VideoCommon/PerformanceMetrics.h, Source/Core/VideoCommon/PerformanceTracker.cpp, Source/Core/VideoCommon/PerformanceTracker.h
So #11348 gets a bit easier to review...
=> Performance tracker refactorings extracted from PR #11348.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThemeHelper.kt
=> Android: Fix navigation bar buttons appearing invisible on API 26

.gitmodules
See https://github.com/KhronosGroup/SPIRV-Cross/issues/2081 for more details.
=> .gitmodules: change SPIRV-Cross branch to main

Source/Core/DolphinQt/Debugger/WatchWidget.cpp
These new strings could use the same clarification as we have for the existing string "&Delete Watch".
=> DolphinQt: Add i18n comments for strings containing the word "watches"

Data/Sys/GameSettings/SMS.ini
Saw this on the forums, decided to fix.  I don't own the game, someone would need to test.
=> GameINI: Force safe texture cache on Marvel Super Hero Squad

Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp, Source/Core/Core/PowerPC/PPCAnalyst.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h, Source/Core/Core/PowerPC/PPCTables.h
Split out from PR #9857 for ease of review. Doesn't do much on it's own, it's mostly preparation and code cleanup.
=> PPCAnalyst: Actually check if instructions want CR

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/layout/AutofitGridLayoutManager.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesView.java
The previous implementation was unresponsive on platforms where you could resize the app window with a mouse. Now the span is adjusted by the layout manager itself and much more frequently.
=> Android: Responsive autofit grid

Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
https://bugs.dolphin-emu.org/issues/13182
=> workaround msvc optimizer bug

Source/Core/Core/PowerPC/Expression.cpp
See https://github.com/dolphin-emu/dolphin/pull/11554#discussion_r1113949572.
=> PowerPC: Rework CPUThreadGuard handling in Expression.cpp

Source/Core/Core/HW/AudioInterface.cpp, Source/Core/Core/HW/AudioInterface.h, Source/Core/Core/HW/DVD/DVDInterface.cpp, Source/Core/Core/HW/HW.cpp, Source/Core/Core/HW/Memmap.cpp, Source/Core/Core/HW/SystemTimers.cpp, Source/Core/Core/System.cpp, Source/Core/Core/System.h
In retrospect I'm not really sure what I was thinking with the `Data` struct, so let's clean this up.
=> HW/AudioInterface: Refactor to class.

Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/HW/HW.cpp, Source/Core/Core/HW/Memmap.cpp, Source/Core/Core/HW/SystemTimers.cpp, Source/Core/Core/HW/VideoInterface.cpp, Source/Core/Core/HW/VideoInterface.h, Source/Core/Core/State.cpp, Source/Core/Core/System.cpp, Source/Core/Core/System.h, Source/Core/VideoCommon/BPStructs.cpp, Source/Core/VideoCommon/FrameDumpFFMpeg.cpp, Source/Core/VideoCommon/PerformanceMetrics.cpp, Source/Core/VideoCommon/Present.cpp
I unpacked the `DoState()` function in the first commit so I wouldn't have to pack every member into a single struct in the second. I think that's better, but ymmv.
(Almost done with these, should be only SI left after this.)
=> HW/VideoInterface: Refactor to class.

Source/Core/WinUpdater/WinUI.cpp
=> winupdater: improve wording of UI::Error

Source/Core/Common/Debug/CodeTrace.cpp, Source/Core/Common/Debug/CodeTrace.h, Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/Core/HW/AddressSpace.cpp, Source/Core/Core/HW/HW.cpp, Source/Core/Core/HW/HW.h, Source/Core/Core/HW/Memmap.cpp, Source/Core/Core/HW/Memmap.h, Source/Core/Core/HW/ProcessorInterface.cpp, Source/Core/Core/HW/ProcessorInterface.h, Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/State.cpp, Source/Core/Core/System.cpp
A little bit of cleanup in HW and Core.
=> More passing of System instead of using the singleton.

Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp
We've gotten repeated support requests for netplay failing to start with Wii saves, log more so I can maybe figure out why.
=> Netplay: More logging before game start.

Source/Core/DiscIO/NANDImporter.cpp, Source/Core/DiscIO/NANDImporter.h
Someone was very optimistic about never getting bogus data here.
=> NANDImporter: Check data bounds.

Source/Core/Common/TypeUtils.h
I am the sole contributor (apart from e149ad4f0a9874f354221a7fc76d8f1841e47808 which only changed the license header). Requested at #11034.
=> Common: Relicense TypeUtils to CC0

Source/Core/Core/AchievementManager.cpp
=> AchievementManager: Fix crash when launching non-disc game.

Source/Core/VideoBackends/Metal/MTLStateTracker.h, Source/Core/VideoBackends/Metal/MTLStateTracker.mm
=> VideoBackends:Metal: Use max pixel samplers constant

Source/Core/Common/CommonFuncs.cpp, Source/Core/Common/CommonFuncs.h, Source/Core/Common/CompatPatches.cpp, Source/Core/Common/FileUtil.cpp, Source/Core/Core/HW/EXI/BBA/TAPServer_Apple.cpp, Source/Core/UICommon/AutoUpdate.cpp, Source/Core/UpdaterCommon/UpdaterCommon.cpp, Source/Core/WinUpdater/Main.cpp
Gets these functions out of the global namespace.
=> Common/CommonFuncs: Move interface into Common namespace

Externals/mGBA/mgba.vcxproj, Source/Core/Core/HW/GBACore.cpp
https://github.com/mgba-emu/mgba/commit/dd531637c20b2848d123440386895cc5db5a737f
=> GBACore.cpp: Update to revised screen size/info API

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Config/ToolTipControls/BalloonTip.cpp, Source/Core/DolphinQt/Config/ToolTipControls/ToolTipWidget.h, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt/GBAWidget.cpp, Source/Core/DolphinQt/MenuBar.cpp
for the love of god, let's get the builders updated to Qt6
=> qt: raise min version to 6

Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp
=> VideoCommon: check for successful graphics mod action creation before adding targets

Source/Core/VideoCommon/Assets/CustomAsset.h
@AdmiralCurtiss  - sorry missed this before :(
=> VideoCommon: fix issue in C++ template

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
fixes arm64 jit on msvc release build
=> msvc: workaround optimizer bug

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.kt
=> Android: Fix overlay d-pad

Source/Core/DolphinTool/ConvertCommand.cpp, Source/Core/DolphinTool/HeaderCommand.cpp, Source/Core/DolphinTool/ToolMain.cpp, Source/Core/DolphinTool/VerifyCommand.cpp
https://en.cppreference.com/w/cpp/utility/program/EXIT_status
=> DolphinTool: Use EXIT_SUCCESS and EXIT_FAILURE

Source/Core/DolphinTool/CMakeLists.txt, Source/Core/DolphinTool/ConvertCommand.cpp, Source/Core/DolphinTool/HeaderCommand.cpp, Source/Core/DolphinTool/ToolMain.cpp, Source/Core/DolphinTool/VerifyCommand.cpp
=> DolphinTool: Use {fmt} library

Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTarget.cpp, Source/Core/VideoCommon/GraphicsModSystem/Config/GraphicsTarget.h, Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModAction.h, Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModActionData.h, Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.cpp, Source/Core/VideoCommon/GraphicsModSystem/Runtime/GraphicsModManager.h
=> VideoCommon: add graphics mod callback interface for when a texture is created

Data/Sys/Shaders/default_pre_post_process.glsl
=> Video: Fix shaders on OpenGL 4.1

Source/Core/Common/GekkoDisassembler.cpp, Source/Core/Common/GekkoDisassembler.h
m_sreg and m_displacement are written to but never read.
=> GekkoDisassembler: Remove unread variables

Source/Core/VideoBackends/D3D/DXTexture.cpp, Source/Core/VideoBackends/D3D12/DX12Context.cpp, Source/Core/VideoBackends/D3D12/DX12Texture.cpp, Source/Core/VideoBackends/OGL/OGLTexture.cpp, Source/Core/VideoBackends/OGL/OGLTexture.h, Source/Core/VideoBackends/Vulkan/VKTexture.cpp, Source/Core/VideoCommon/TextureConfig.h
Pulled out of https://github.com/dolphin-emu/dolphin/pull/11783
=> VideoBackends: add support for cube maps for OGL, Vulkan, and D3D

Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureCacheBase.h
=> TextureCacheBase: Add m_ prefix to member variables

Source/Core/VideoBackends/Metal/MTLGfx.mm, Source/Core/VideoBackends/Metal/MTLObjectCache.mm, Source/Core/VideoBackends/Metal/MTLStateTracker.h, Source/Core/VideoBackends/Metal/MTLStateTracker.mm, Source/Core/VideoBackends/Metal/MTLTexture.h, Source/Core/VideoBackends/Metal/MTLTexture.mm
#11859 for Metal
(Untested, but probably works)
=> VideoBackends:Metal: Multi render target support

Source/Core/Common/Logging/Log.h, Source/Core/Common/Logging/LogManager.cpp
These probably should have their own category. Right now [it kinda hasn't been logging stuff at all](https://github.com/dolphin-emu/dolphin/pull/12026#discussion_r1271159221) which is not ideal.
=> Common/LogManager: Add logging category for Achievements.

Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp
…ms from being visible before their parents, thus getting rid of the rapid popups.
=> AchievementsWindow: Fix rapid popups on initial opening.

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp
Fixing a variety of lock/queue issues in AchievementManager.
=> Retroachievements bugfix

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp
=> Added error checking and logging to AchievementManager::GetAchievementProgress.

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp, Source/Core/Core/HW/EXI/BBA/BuiltIn.h
=> Core/BBA/BuiltIn: Replace IP_PROTOCOL with IPV4_ETHERTYPE to avoid conflict with Linux headers.

Source/Core/Core/AchievementManager.cpp
Scope issue in the event callback from `rc_runtime_do_frame()`. The pointer points to a variable on the stack from inside `rc_runtime_do_frame()`, so that's a race condition between the thread calling `rc_runtime_do_frame()` and the event queue thread.
=> AchievementManager: Don't store pointer to rc_runtime_event_t in lambda.

Contributing.md
We have been operating on this principle for a while. Let's make it explicit so that new contributors know about it.
Feedback on wording and structure is welcome.
=> Contributing.md: Make our stance on leaked information explicit

Externals/cubeb/CMakeLists.txt, Externals/cubeb/msvc/cubeb.vcxproj, Externals/cubeb/msvc/cubeb.vcxproj.filters
This fixes a heap-use-after-free bug among other things.
=> Externals: Update cubeb to mozilla/cubeb@54217bca3f3e0cd53c073690a23dd25d83557909

Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
A small optimization for AccurateNaNs.
=> JitArm64: Check packed NaNs without using extra register

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/controlleremu/EmulatedController.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/ProfileDialogPresenter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.kt, Source/Android/app/src/main/res/values/arrays.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/Input/EmulatedController.cpp, Source/Core/Core/FreeLookManager.cpp, Source/Core/Core/FreeLookManager.h, Source/Core/Core/HW/GBAPadEmu.cpp, Source/Core/Core/HW/GBAPadEmu.h, Source/Core/Core/HW/GCKeyboardEmu.cpp, Source/Core/Core/HW/GCKeyboardEmu.h, Source/Core/Core/HW/GCPadEmu.cpp, Source/Core/Core/HW/GCPadEmu.h, Source/Core/Core/HW/WiimoteEmu/Extension/Extension.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Extension.h, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h, Source/Core/Core/HotkeyManager.cpp, Source/Core/Core/HotkeyManager.h, Source/Core/InputCommon/ControllerEmu/ControllerEmu.h
=> Android: Add more GameCube controller types

Data/Sys/GameSettings/G2BE5G.ini, Data/Sys/GameSettings/G2BP7D.ini
This game comes with full debug info :)
=> GameSettings: add patch to disable interlacing in Black & Bruised

Source/Core/VideoBackends/Metal/MTLGfx.mm, Source/Core/VideoBackends/Metal/MTLPipeline.h, Source/Core/VideoBackends/Metal/MTLPipeline.mm, Source/Core/VideoBackends/Metal/MTLStateTracker.h, Source/Core/VideoBackends/Metal/MTLStateTracker.mm, Source/Core/VideoBackends/Metal/MTLUtil.mm
=> VideoBackends:Metal: Support multiple compute textures

Source/Core/Core/PowerPC/PPCSymbolDB.cpp
.data symbols point to memory values and can be any byte or length of bytes (such as a string).  They were being pushed through the Instruction symbol checking logic ( requires 4 byte alignment) and failing. They now go through basic RAM address logic instead.
@dreamsyntax Should make sure this properly loads and saves a large .data section.  Also, check the logger for error spam.  I don't have a map file with tons a .data lines.
Should reincorporate symbols in the MemoryViewWidget.
=> PPCSymbolDB. Bugfix. Fix .data symbols not loading

Source/Core/Core/Movie.cpp, Source/Core/Core/Movie.h
=> Use ExtensionNumber in Movie.cpp

Source/Core/Core/IOS/Network/KD/Mail/MailCommon.h, Source/Core/Core/IOS/Network/KD/Mail/WC24FriendList.cpp, Source/Core/Core/IOS/Network/KD/Mail/WC24FriendList.h, Source/Core/Core/IOS/Network/KD/Mail/WC24Send.cpp, Source/Core/Core/IOS/Network/KD/Mail/WC24Send.h
This was relying on a ton of indirect includes...
=> IOS/KD/Mail: Add missing includes.

Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp
https://github.com/dolphin-emu/dolphin/pull/12357#issuecomment-1846151067 pointed me here, and while I'm not sure what exact issue they're talking about there I did notice a few other things.
=> HW/CEXIIPL: Various fixes.

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
If a_is_addr_base_reg is true, discarding a before the end of the instruction would result in the instruction being miscompiled.
=> JitArm64: Guard against discarding a in lmw/stmw

Source/Core/Core/AchievementManager.cpp
Renames some variables to avoid shadowing warnings on gcc.
Also gets rid of a FilereaderState struct, since one is already defined in the declaration of the AchievementManager class.
=> AchievementManager: Resolve -Wshadow warnings

Source/Core/VideoCommon/TextureConverterShaderGen.cpp
Let's see what fifoci has to say about this.
=> VideoCommon: apply "force 24-bit color" to EFB-to-VRAM copies as well

Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
This PR adds a checkbox which when it is checked it maps mouse directions to the IR cursor.
One problem I didn't find how to save this state in the ini config. So when you close and restart dolphin it will disable checkbox even if it's enabled
=> DolphinQt/Mapping: Add "Use Mouse Controlled Pointing" button.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/DocumentProvider.kt
Implement Refresh.
On the DocumentUI internal Files Manager App, this will refresh folder after operation create, rename and delete
=> Improve DocumentProvider

Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/PowerPC.h
=> PowerPC: Add constants for the two TLB indices

Source/Android/app/build.gradle.kts
Hopefully we can get a better solution regarding the targets in the future, but for now, let's at least make it so the comments are correct.
=> Android: Fix the targets line in build.gradle.kts

Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/FifoPlayer/FifoPlayer.h, Source/Core/Core/HW/VideoInterface.cpp, Source/Core/Core/System.cpp, Source/Core/Core/System.h, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.h, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.h, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/VideoCommon/BPStructs.cpp
Not sure if this is really the right place for it, but I don't think there's a better one?
=> FifoPlayer: Move instance to System.

Source/Core/Core/FifoPlayer/FifoRecorder.cpp, Source/Core/Core/FifoPlayer/FifoRecorder.h, Source/Core/Core/System.cpp, Source/Core/Core/System.h, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.h, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/VideoCommon/BPStructs.cpp, Source/Core/VideoCommon/OpcodeDecoding.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp
=> FifoRecorder: Move instance to System.

CMakeLists.txt, Source/Core/InputCommon/ControllerInterface/CoreDevice.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.h, Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp, Source/Core/InputCommon/ControllerInterface/SDL/SDL.h
Dolphin uses the Joystick API on the SDL backend. However, this API doesn't have consistent mapping across controllers.
For instance, here is the same mapping between a Nintendo Switch Pro Controller and an Xbox controller:
This is extremely cumbersome when having to deal with multiple controllers, since it means you need to have a profile per controller. (And it makes Dolphin significantly less plug and play: for example, if a friend comes over with a new controller, here comes the need to remap everything for them.)
The GameController API instead has consistent mapping across all controllers it supports:
I also made sure that the names are the same from XInput, to allow for more profile portability (by default it uses `Button N/E/S/W`, but it supports `Button Y/B/A/X`).
Now, the notes: …
=> SDL: Add GameController API, cleanup

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp, Source/Core/InputCommon/ControllerInterface/SDL/SDL.h
The first one actually causes a crash when running through Steam, the rest I just noticed while I was here.
=> InputCommon/SDL: Fix potential issues in controller initialization.

Source/Core/DolphinQt/RenderWidget.cpp
This PR adds more infos on which functions to use to implement "Lock Mouse Cursor" on linux OS
=> Update comments RenderWidget.cpp

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h
Just a few things to tidy up the implementation (notably, not needing to check update callback state all the time).
=> AchievementManager: Minor cleanup

Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/Boot/Boot_BS2Emu.cpp, Source/Core/Core/Boot/Boot_WiiWAD.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/HW/HW.cpp, Source/Core/Core/HW/ProcessorInterface.cpp, Source/Core/Core/HW/SystemTimers.cpp, Source/Core/Core/HW/WII_IPC.cpp, Source/Core/Core/IOS/DI/DI.cpp, Source/Core/Core/IOS/Device.cpp, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/IOS/IOS.h, Source/Core/Core/System.cpp, Source/Core/Core/System.h, Source/Core/Core/WiiRoot.cpp, Source/Core/Core/WiiUtils.cpp, Source/Core/DolphinNoGUI/Platform.cpp, Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp, Source/Core/DolphinQt/Debugger/NetworkWidget.cpp, Source/Core/UICommon/UICommon.cpp
=> Core: Move Emulation IOS instance to System.

Externals/MoltenVK/CMakeLists.txt
Title. ~~I tried updating to 1.2.6 in #12296, but FifoCI reported some interesting results. Let's see if this newer version does the same.~~ Prior issues seem to be fixed.
=> Externals: Update MoltenVK to 1.2.7

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.kt
=> Android: Don't check Wii Menu version before directory initialization

Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
This PR does two things:
1. Correctly log CGI errors in the register ioctl
2. Correctly handle if a user with a default user ID tries to register.
Running an internet connection test calls the register ioctl, which causes issues to users with the default ID. Since majority of users share the same Wii Number (its generation is determined by multiple factors, one of them being the console ID), it was registered at least once causing subsequent registrations to result in a duplicate registration error. This would also cause the Wii to be unable to connect to the internet at all as the connection test failed. This is possibly one of the reasons why the register endpoint is the only one still active by Nintendo.
This blocks a user with the default ID to contact any server, while writing to the …
=> IOS/KD: Correctly handle registration of the default user ID

Data/Sys/GameSettings/G5B.ini, Data/Sys/GameSettings/G5BE4Z.ini
Fixes Strike Force Bowling blank texture
=> Create Strike Force Bowling INI

Source/Core/Core/IOS/Crypto/AesDevice.cpp
Not tested since it takes ages to compile dolphin on this laptop. But do I really need to
=> AesDevice: fix key & iv arrays

Source/Core/Core/AchievementManager.cpp
RetroAchievements plans to use the user_agent in unlock requests to determine which software version was used to play the game, and can filter older software versions out. As such, I have been given the go-ahead to remove the hardcoded line that forces hardcore to always be false.
=> Properly enable RetroAchievements hardcore mode

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/BootManager.cpp, Source/Core/Core/BootManager.h, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/MainWindow.cpp
=> BootManager: Avoid Global System Accessor

Source/Core/Core/AchievementManager.cpp
Testing found that spamming toggles for Enable Leaderboards etc risked leaderboards being deleted while the runtime was in the process of recalculating them; this should clear up those conflicts.
=> Added locks to achievement runtime calls

Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp, Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h, Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
=> DolphinQt: Add IRPassthrough indicator.

Source/Core/DolphinQt/CheatSearchWidget.cpp, Source/Core/DolphinQt/CheatSearchWidget.h
Fixes: https://bugs.dolphin-emu.org/issues/13054
=> DolphinQt: Allow Cheat Search to create multiple AR codes.

Source/Core/Core/State.cpp
Fixes https://bugs.dolphin-emu.org/issues/13475
Potential to produce an invalid state file still exists but at least there's an error message now.. at least in most cases.
=> Core/State: Display messages on state write failures.

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/PowerPC/BreakPoints.cpp, Source/Core/Core/PowerPC/JitInterface.cpp, Source/Core/Core/PowerPC/JitInterface.h, Source/Core/DolphinQt/MenuBar.cpp
It is recommended to view this diff with whitespace changes hidden.
=> JitInterface::ClearCache: Modernize With CPUThreadGuard

Data/Sys/Load/GraphicMods/Skylanders Giants/metadata.json, Data/Sys/Load/GraphicMods/Skylanders Trap Team/metadata.json
Follow up to #12016.
Before (4x resolution)
Native resolution bloom
Bloom removal
Also, completely unrelated, but I made a 60 FPS code. Tested on the NA version of the game, may work on EU too (since that's the case for the previous game) and others.
```
040293E8 60000000
```
=> Add Bloom Definitions for Skylanders Giants and Trap Team

Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
For some reason Linux is surprisingly slow at closing file descriptors of event devices. This commit improves GUI startup times on my computer by about 1.5 seconds.
=> evdev: close file descriptors in a separate thread

Source/Core/DolphinQt/MenuBar.cpp
This action has nothing to do with the JIT, so I wonder if it should be moved out from the JIT menu at some point.
=> MenuBar: Optimize SearchInstruction

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
=> CachedInterpreter: Skip Updating Instruction PERFMON When There Are None

Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp, Source/Core/Core/IOS/USB/USB_HID/HIDv4.h
=> HIDv4: Fix racy device change behavior

Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp
I put this messages in the DYNA_REC category for https://github.com/dolphin-emu/dolphin/pull/12723, so I'm changing them here as well for consistency.
=> JIT: Fix Incorrect Assert Category

Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.h
I don't even feel like tracking down the history for this one.
=> JitState: Remove Unused instructionNumber

CMakeLists.txt, Source/Core/Common/StringUtil.cpp, Source/Core/Core/PowerPC/Expression.cpp
See the commit message for details.
This is some code taken from my failed attempt at porting Dolphin to NetBSD in this PR: https://github.com/dolphin-emu/dolphin/pull/12716
=> improve NetBSD-specific code

Source/Android/jni/MainAndroid.cpp, Source/Core/Core/ConfigLoaders/BaseConfigLoader.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/Core/Debugger/Debugger_SymbolMap.cpp, Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/HW/ProcessorInterface.cpp, Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/Movie.cpp, Source/Core/Core/State.cpp, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Config/CheatWarningWidget.cpp, Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/WatchWidget.cpp, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt/Settings/GameCubePane.cpp, Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp
Part 4 of an effort to remove global state from one of the biggest offenders.
=> Core::IsRunning: Avoid Global System Accessor

Source/Core/Core/PowerPC/PPCAnalyst.cpp
Fixes https://bugs.dolphin-emu.org/issues/13526.
=> PPCAnalyst: Prevent discarding registers around breakpoints

Externals/rcheevos/CMakeLists.txt, Source/Core/DolphinNoGUI/CMakeLists.txt
This broke with some recent merges.
=> Fix building with CMake on Windows

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/AdvancedMappingDialog.kt
=> Android: Fix crash when no devices have outputs

Source/Core/Common/ArmCPUDetect.cpp, Source/Core/Core/MachineContext.h
Fix building on OpenBSD/arm64 and add CPU feature detection.
=> Add OpenBSD/arm64 support.

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Using shifts and bit tests makes the code unnecessarily annoying to reason about. I'm replacing it with subtracting from 3 to translate the bit order from the PowerPC format to the usual format.
=> Jit64: Clean up the test_bit variable

Source/Core/Common/CMakeLists.txt, Source/Core/Common/Unreachable.h, Source/Core/DolphinLib.props, Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/BranchWatchTableModel.cpp
The new `Common::Unreachable` function mirrors C++23's `std::unreachable`, lifted from the currently stagnant https://github.com/dolphin-emu/dolphin/pull/12714.
=> Branch Watch Tool: Optimizations

Source/Core/VideoCommon/OnScreenDisplay.cpp, Source/Core/VideoCommon/OnScreenUI.cpp
Some minor tweaks to how RetroAchievements icons appear on screen.
=> RetroAchievements On Screen Tweaks

Source/Android/app/src/main/res/values/strings.xml, Source/Core/DolphinQt/AboutDialog.cpp, Source/Core/DolphinQt/Settings/GeneralPane.cpp
Updates the Beta auto update string in DolphinQt and the copyright strings in DolphinQt and Android (it seemed appropriate, though I can drop those commits if requested).
=> Miscellaneous release string updates

Source/Core/DolphinQt/Achievements/AchievementBox.cpp, Source/Core/DolphinQt/Achievements/AchievementLeaderboardWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementProgressWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementsWindow.cpp, Source/Core/DolphinQt/Styles/Dark/dark.qss
A handful of improvements/fixes for the Achievements dialog.
=> RetroAchievements - Dialog Visual Improvements

Source/Core/DolphinQt/Achievements/AchievementBox.cpp, Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementHeaderWidget.h
Minor fixes and tweaks to game/achievement progress bars in the dialog.
=> Achievements Progress Bar Tweaks

Source/Core/Core/AchievementManager.cpp
Currently we're showing OSD messages for unknown patches in known INI files, but not for unknown patches in unknown INI files. I don't think this distinction makes much sense to the user. If there's a patch the user can't use, they probably want to be aware of that fact.
=> RetroAchievements: Show OSD messages also for unverified INI files

Source/Android/jni/MainAndroid.cpp
Based on feedback I received on https://github.com/dolphin-emu/dolphin/pull/12714.
=> MainAndroid: Use JNI_FALSE instead of static_cast<jboolean>(false)

Source/Core/DolphinQt/Achievements/AchievementBox.cpp, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Config/FilesystemWidget.cpp, Source/Core/DolphinQt/ConvertDialog.cpp, Source/Core/DolphinQt/Debugger/AssemblerWidget.cpp, Source/Core/DolphinQt/Debugger/BranchWatchDialog.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp, Source/Core/DolphinQt/GCMemcardManager.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/Settings/GameCubePane.cpp, Source/Core/DolphinQt/Settings/GeneralPane.cpp, Source/Core/DolphinQt/Settings/InterfacePane.cpp, Source/Core/DolphinQt/Settings/WiiPane.cpp
Most of these changes are to improve consistency in capitalization.
=> i18n: Add comments and improve source strings

Source/Core/Core/PowerPC/PPCAnalyst.cpp
Less magic numbers this way. No functional change.
=> PPCAnalyst: Refactor mtspr handling code

Source/Core/Common/CommonFuncs.h, Source/Core/Common/x64ABI.h, Source/Core/Core/HotkeyManager.cpp
End comment does not match macro name
=> Fix comment

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp, Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.h
The Cached Interpreter is the only JIT of the three that does not support software JIT profiling. The design of the Cached Interpreter prior to my [Cached Interpreter 2.0 PR](https://github.com/dolphin-emu/dolphin/pull/12723) made it outright impossible to pack enough data into a callback for software JIT profiling to work.
This PR mildly conflicts with my [JIT Widget Refresh PR](https://github.com/dolphin-emu/dolphin/pull/12714). Basically, if one gets merged before the other, there will be merge conflicts for sure.
=> CachedInterpreter: Software JIT Profiling Support

Source/UnitTests/VideoCommon/VertexLoaderTest.cpp
Most likely something has gone wrong here, but just in case I'll mark it for deletion
=> Remove self-comparison

Source/Android/jni/Cheats/GraphicsModGroup.cpp, Source/Core/Core/CoreTiming.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/DolphinQt/Config/GameConfigEdit.cpp, Source/Core/DolphinQt/Config/GraphicsModListWidget.cpp, Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm, Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp, Source/Core/VideoCommon/ShaderCache.cpp, Source/UnitTests/Core/MMIOTest.cpp, Source/UnitTests/VideoCommon/VertexLoaderTest.cpp
A few things missed by https://github.com/dolphin-emu/dolphin/pull/12990.
=> Use contains method 2

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/DolphinSensorEventListener.kt
This reverts commit 75fb1a7edfb12f490b08ab0b76a8e2f1536d2d9b and fixes the bugs that that commit was a workaround for.
=> Android: Fix and enable input device sensor input

Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/DolphinAnalytics.h, Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AXStructs.h, Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.h
This fixes e.g. the overly loud wind inside the house in "I SPY: Spooky Mansion".
=> AX: add support for biquad filtering

Source/Core/Common/StringUtil.cpp, Source/Core/Core/HW/EXI/EXI_Device.h, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/VideoBackends/OGL/OGLConfig.cpp, Source/Core/VideoCommon/VertexLoaderBase.cpp, Source/UnitTests/Common/BitFieldTest.cpp
fmt::join was moved into fmt/ranges.h
=> Add support for libfmt-11

Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp
Changes integer rounding to more closely meet the documentation (rounding before doing any bounds checks). All this really does is make sure some exception bits won't be erroneously set. This depends on the rounding mode, so with rounding to even, (0x7fffffff, 0x7fffffff.8) now works properly without setting these bits!!
This change also uses some standard functions for rounding instead of what was previously used (due to previously using them to cast to an s32 directly, while now needing that double value just a little bit longer)
Finally, due to comparing with a rounded double rather than a non-rounded one, a single >0x7fffffff was changed to >=0x80000000 because it ~~looks nicer~~ gives better codegen on Aarch64 ^^
=> Improve Integer Rounding Accuracy

Source/Core/Core/PowerPC/Interpreter/Interpreter_FPUtils.h
During 25-bit rounding, subnormals are "normalized", which would normally mean that the exponent needs to be able to be lower than -1023 (which is what PPC does internally), but in actuality it's possible to simply modify at what bit rounding occurs and get the same results!
This likely hasn't been an issue anywhere due to the odd requirements for it to be relevant -- You need to run some single-precision multiplication instruction, have an extremely large frA, and have a double precision subnormal in frC, which shouldn't ever get generated by any compilers (due to it throwing double precision values into a single precision instruction), but does improve the overall accuracy of the interpreter!!
This is also why it might be best not to add it into the JITs, adding a performance penalty in …
=> Proper Subnormal Rounding When Interpreting

Data/Sys/GameSettings/E78.ini, Data/Sys/GameSettings/G3Q.ini, Data/Sys/GameSettings/GNI.ini, Data/Sys/GameSettings/RHF.ini
Some changes for GameINI files with some issues, so mostly fixes for issues already marked fixed.
Fixes [Issue 13617](https://bugs.dolphin-emu.org/issues/13617) / [Issue 12415](https://bugs.dolphin-emu.org/issues/12415) 
Fixes [Issue 10059](https://bugs.dolphin-emu.org/issues/10059)
Fixes [Issue 10186](https://bugs.dolphin-emu.org/issues/10186)
=> GameINI: Fixing Various Mistakes

Source/Core/Core/Core.cpp, Source/Core/DolphinQt/Config/Graphics/GraphicsWindow.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp, Source/Core/VideoCommon/VideoBackendBase.h
I'm going to use this PR whenever I need to make a build that I can't do locally, instead of making a new PR each time.
=> [DO NOT MERGE] Testing PR

Source/Core/VideoBackends/Metal/MTLObjectCache.h, Source/Core/VideoBackends/Metal/MTLObjectCache.mm, Source/Core/VideoBackends/Metal/MTLShader.h, Source/Core/VideoBackends/Metal/MTLStateTracker.mm
Hopefully will make my life easier the next time someone comes up to me with an internal compiler error
=> VideoBackends:Metal: Log file on failed pipeline compile

Source/Core/Common/Assembler/CaseInsensitiveDict.h, Source/Core/Core/IOS/ES/Formats.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/InputCommon/ControllerEmu/StickGate.cpp, Source/Core/InputCommon/GCAdapter.cpp, Source/Core/UICommon/GameFile.cpp
While evaluating an entire codebase's usage of standard library algorithms, it was inevitable I would find a few stinkers. In a few places, I have completely rewritten code using standard algorithms to be more optimized and/or hopefully less idiomatic (more easily comprehensible).
=> Ranges Algorithms Modernization - Rewrite

Source/Core/Core/AchievementManager.cpp, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.cpp, Source/Core/DolphinQt/Achievements/AchievementSettingsWidget.h, Source/Core/DolphinQt/MainWindow.cpp
Added confirmation dialogs when RetroAchievements is logged out or hardcore mode is turned off.
=> Achievements Confirmation Dialogs

Source/Core/DolphinQt/QtUtils/QtUtils.h
=> Add include guard to QtUtils.h

Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
This is a rebase of #8849, if you could call it that.
=> Config/IsSettingSaveable: Use class template argument deduction.

Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
Reported by matthewgrey51 on Discord.
This regressed in #13102.
=> DSPHLE/AXWii: fix Elebits sound

docs/WiaAndRvz.md
https://bugs.dolphin-emu.org/issues/13671
=> docs: Clarify wia_except_list_t padding in uncompressed groups

Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp
Tested with a DualSense controller on Linux. I'm guessing it also works with a DS4.
=> InputCommon/SDL: Add touchpad inputs.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.kt
=> Android: Replace deprecated setSystemUiVisibility

Source/Core/VideoBackends/Vulkan/VKMain.cpp
This code doesn't apply to other platforms.
=> Vulkan: Only attempt to create a CAMetalLayer on macOS

Source/Core/Core/ConfigLoaders/GameConfigLoader.cpp
All the `first` and `second` members made it hard to wrap my head around things.
=> Core/Config: Replace some std::pair with struct to make code more readable.

Source/Core/VideoCommon/TextureConfig.h
Trying to remove some of my smaller commits from my editor PR.  Should reduce some of the 'noise' when I make my bigger PRs to pull stuff out.
=> VideoCommon: add formatter for AbstractTextureType

Externals/imgui/LICENSE.txt, Externals/imgui/imconfig.h, Externals/imgui/imgui.cpp, Externals/imgui/imgui.h, Externals/imgui/imgui_demo.cpp, Externals/imgui/imgui_draw.cpp, Externals/imgui/imgui_internal.h, Externals/imgui/imgui_tables.cpp, Externals/imgui/imgui_widgets.cpp, Externals/imgui/imstb_textedit.h, Externals/imgui/imstb_truetype.h, Externals/imgui/misc/cpp/imgui_stdlib.cpp, Externals/imgui/misc/cpp/imgui_stdlib.h, Source/Core/VideoCommon/AbstractTexture.cpp, Source/Core/VideoCommon/AbstractTexture.h, Source/Core/VideoCommon/OnScreenDisplay.cpp, Source/Core/VideoCommon/OnScreenUI.cpp
In my editor PR branch, I track latest imgui.  However, a [recent update](https://github.com/ocornut/imgui/issues/1641) caused some additional changes to be needed.  Rather than be conflict prone, I decided to move these changes to master.
=> Externals / VideoCommon: update imgui to 1.91.7 and implot to v0.16

Source/Core/Core/HW/WiimoteEmu/MotionPlus.cpp
`std::llround` was being used on `s32` values.
=> WiimoteEmu/MotionPlus: Gyro data calculation cleanup.

Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/UberShaderPixel.cpp
This saves three instructions on AMD GPUs. Dunno about Nvidia.
=> VideoCommon: simplify dither calculation

Source/Core/VideoCommon/VertexShaderGen.cpp
I realize how difficult #13346 would be to review, so I'm going to split it out in pieces.  This will also allow me to catch any fifo errors more easily.
This exposes functions getting the texcoord in the vertex shader.  This will hide some of emulation/implementation details so users don't have to manage it.
=> VideoCommon: move texcoord calculations to accessible functions in VertexShaderGen

Source/Core/DolphinQt/InfinityBase/InfinityBaseWindow.cpp
=> USB: Fix Infinity Manager icon

Source/Core/Common/FatFsUtil.h
=> Common: Make SD pack/unpack strings translatable

Source/Core/Core/HW/WiimoteEmu/DesiredWiimoteState.cpp
The `IRExtended` layout offers the same functionality (10bit x/y + 4bit size) but is more familiar and documented on wiibrew and whatnot.
Manipulating DTM files will be marginally less confusing.
=> WiimoteEmu: Make SerializedWiimoteState store camera points as IRExtended instead of custom layout.

Data/Sys/GameSettings/S3C.ini
As seen on TV: https://www.youtube.com/watch?v=HBsn7MvjDng
=> GameSettings: fix shadows in Triple Crown Championship Snowboarding

Flatpak/org.DolphinEmu.dolphin-emu.yml
This was reworked and moved to using dbus in #13076
=> Update the flatpak with the changes how screensavers are handled

Source/Core/Common/DynamicLibrary.cpp, Source/Core/Common/FatFsUtil.cpp, Source/Core/Common/GL/GLInterface/WGL.cpp, Source/Core/Common/IOFile.h, Source/Core/Common/Network.cpp, Source/Core/Core/AchievementManager.cpp, Source/Core/Core/HW/DSP.cpp, Source/Core/Core/HW/EXI/EXI_DeviceModem.cpp, Source/Core/Core/IOS/Network/KD/VFF/VFFUtil.cpp, Source/Core/Core/NetworkCaptureLogger.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/DolphinNoGUI/PlatformWin32.cpp, Source/Core/DolphinQt/RenderWidget.cpp, Source/Core/VideoBackends/D3D/D3DBoundingBox.cpp, Source/Core/VideoBackends/D3D/D3DVertexManager.cpp, Source/Core/VideoBackends/D3D/DXTexture.cpp, Source/Core/VideoBackends/D3D12/D3D12BoundingBox.cpp, Source/Core/VideoBackends/D3D12/DX12Texture.cpp, Source/Core/VideoBackends/OGL/OGLBoundingBox.cpp, Source/Core/VideoBackends/OGL/OGLTexture.cpp, Source/Core/VideoBackends/Vulkan/StagingBuffer.cpp, Source/Core/VideoBackends/Vulkan/VKStreamBuffer.cpp, Source/Core/VideoBackends/Vulkan/VKSwapChain.cpp, Source/Core/VideoCommon/AbstractStagingTexture.cpp, Source/Core/VideoCommon/OnScreenUI.cpp, Source/Core/VideoCommon/XFStructs.cpp
Same as #13007, which I accidentally closed.
=> Replace 'reinterpret_cast' with 'static_cast'

Source/Core/Core/AchievementManager.cpp, Source/Core/Core/AchievementManager.h, Source/Core/Core/ActionReplay.cpp, Source/Core/Core/ActionReplay.h, Source/Core/Core/GeckoCode.cpp, Source/Core/Core/GeckoCode.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/PatchEngine.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp
Refactors the AR/Gecko/Patch code approval process to verify from every possible game ini, not just the base game ID. This fixes codes on specific revisions or codes general to any region.
=> Fixed Multi Config Code Approvals

Source/Core/VideoCommon/LightingShaderGen.cpp, Source/Core/VideoCommon/LightingShaderGen.h, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/VertexShaderGen.cpp
I realize how difficult #13346 would be to review, so I'm going to split it out in pieces.  This will also allow me to catch any fifo errors more easily.
This exposes a function for setting lighting on a channel.
=> VideoCommon: move lighting shader logic to callable functions

Source/Core/Core/HW/EXI/BBA/BuiltIn.cpp
Also rewording the messages to make them clearer and fix typos.
=> EXI: Make HLE BBA panic alerts translatable

Source/Android/jni/Input/EmulatedController.cpp
Fixes my regression from #13295 
Fixes https://bugs.dolphin-emu.org/issues/13774
=> Android/Input: Fix crash when mapping wii remote extensions.

Source/Core/DolphinQt/Settings/AudioPane.cpp
This doesn't trigger on my system, so couldn't test it.
=> AudioPanel Bugfix

Source/Core/Core/HW/EXI/BBA/TAP_Win32.h
Replaces #13516 due to branch rename
=> Replace definitions with constant expressions - Core/HW/EXI/BBA/TAP_Win32

Source/Core/Common/CompatPatches.cpp
Dolphin has not supported a version of windows where these binaries exist for a while.
=> remove ucrt compat patches

Source/Core/Core/IOS/USB/OH0/OH0.cpp
I've been playing Rock Band 3 recently and have experienced a bug where sometimes if you disconnect and reconnect a USB microphone, the game won't pick up on it connecting, not even it you disconnect and reconnect it again. An investigation into what's going on inside Dolphin shows that when the game triggers a call to OH0::DeviceOpen after the device has been reinserted, Dolphin doesn't open the device because it's already present in m_opened_devices.
Removing the device from m_opened_devices after calling OH0::TriggerHook in OH0::OnDeviceChange resolves this specific issue in my testing. Doing this matches us removing the device from m_opened_devices after calling OH0::TriggerHook in OH0::DeviceClose, but I haven't looked at exactly what real IOS does.
I have been able to reproduce a …
=> IOS: Remove from m_opened_devices in OH0::OnDeviceChange

Source/Core/Core/AchievementManager.cpp
We have identified that a failed RetroAchievements game load (most easily done when closing a game before the server can finish responding) can leave data behind that causes problems. As such, refactored CloseGame to always delete data even if there wasn't a game loaded when it was called, and call it on the failure paths of LoadGameCallback.
=> Call AchievementManager CloseGame on load failures

Source/Core/Core/HW/DVD/DVDThread.cpp, Source/Core/Core/HW/DVD/DVDThread.h
Followup of #13431.
DVDThread is now much simpler with far fewer moving parts.
PR #13475 and #13579 will make it entirely mutex free.
=> DVDThread: Implement with WorkQueueThread and WaitableSPSCQueue.

Source/Core/DiscIO/DirectoryBlob.cpp
Extracted games contain a boot.bin file that contains the disc header. These boot.bin files are considered valid volumes by Dolphin, since Dolphin only checks the disc header to determine if something is a valid GC/Wii disc. Running them doesn't make any sense, though.
boot.bin files used to not be scanned by Dolphin due to their file extension, but .bin was added to the list of file extensions to scan for in 494e2c0. To stop them from showing up in the game list, let's update the ShouldHideFromGameList mechanism.
=> Hide DirectoryBlob boot.bin files from game list

Source/Core/Common/WorkQueueThread.h
Thank you to @Dentomologist for finding this issue.
`WorkQueueThreadBase::Cancel` was racey in that work `Push`d immediately after could also potentially be inadvertently canceled.
I already had some design changes for `WorkQueueThread` ready that I needed for #13612 and they eliminate the issue, so here's a PR of just those changes.
The `m_skip_work` (racey) and `m_run_thread` members are eliminated by having a separate command queue to control the worker thread.
I think it's overall less confusing and it will also easily allow adding future functionality like gathering the unprocessed items without the overhead of stopping the thread (for #13612).
=> WorkQueueThread: Fix Cancel() race with internal command queue.

Source/Core/DiscIO/DirectoryBlob.cpp
This is a continuation of PR #13597. That pull request hid `sys/boot.bin`, but not `disc/header.bin`, which is only present for Wii games.
Fixes https://bugs.dolphin-emu.org/issues/13810.
=> Hide DirectoryBlob header.bin files from game list

Source/Core/DolphinQt/Config/FilesystemWidget.cpp
Center header text to match all the other headers.
=> FilesystemWidget: Center header text

Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp
Follow-up for https://github.com/dolphin-emu/dolphin/pull/12918#discussion_r1785153070.
=> DolphinQt: Call FIFOPlayerWindow::UpdateControls for Starting/Stopping

Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
I was going to make each part separate, but the changes are so trivial I didn't want to block the CI queue for no reason.
=> DolphinQt/FIFO/FIFOAnalyzer: Make parameters, arguments etc. constant

Data/Sys/GameSettings/GQSEAF.ini
Prior codes were reorganized and new codes added. All codes have been thoroughly tested and are ensured to work on a vanilla NTSC .iso with added usage notes
=> Tales of Symphonia AR and Gecko Codes

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/NetPlay/ClickBlurLabel.cpp, Source/Core/DolphinQt/NetPlay/ClickBlurLabel.h, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.h
This is particularly useful for people who stream their desktop and don't want to accidentally leak their IP or room.
=> ClickBlurLabel: Create a label which is blurred until it is clicked

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsAdapter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/ControllerInterface.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/CoreDevice.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/model/view/InputMappingControlSetting.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/AdvancedMappingControlAdapter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/AdvancedMappingControlViewHolder.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/AdvancedMappingDialog.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/ControlStateBarHorizontal.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/ControlStateBarImpl.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/ControlStateBarVertical.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/input/ui/viewholder/InputMappingControlSettingViewHolder.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionAdapter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/SettingViewHolder.kt, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/LifecycleViewHolder.kt, Source/Android/app/src/main/res/layout-ldrtl/list_item_mapping.xml, Source/Android/app/src/main/res/layout/list_item_advanced_mapping_control.xml, Source/Android/app/src/main/res/layout/list_item_mapping.xml, Source/Android/app/src/main/res/layout/view_control_state_bar_horizontal.xml, Source/Android/app/src/main/res/layout/view_control_state_bar_vertical.xml, Source/Android/jni/Input/CoreDevice.cpp, Source/Core/InputCommon/ControllerInterface/Android/Android.cpp
https://github.com/user-attachments/assets/50367a71-07bc-4de0-98c0-edf2a077f89b
=> Android: Show input indicators in controller settings

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
PRs https://github.com/dolphin-emu/dolphin/pull/13786 and https://github.com/dolphin-emu/dolphin/pull/13797 had incompatible changes that resulted in the build being broken when they were both merged.
=> MemoryWidget: Fix build breakage from conflicting PRs

Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/VideoBackends/Software/SWEfbInterface.cpp
But wait! That's not all! In this limited time offer you will also receive a comment fix for no additional cost!
=> DolphinQt: fix two -Wunused-lambda-capture warnings

Source/Core/Core/CoreTiming.h, Source/Core/Core/HW/VideoInterface.h, Source/Core/Core/IOS/Network/WD/Command.cpp
I doubt anyone cares about which Wi-Fi channel was being selected, so no practical impact.
=> Fix some undefined behavior

Source/Core/VideoCommon/OpcodeDecoding.h
Just a minor code modernization.
=> VideoCommon/OpcodeDecoding: Replace enable_if with concepts.

Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
Since the most common operation for the cached interpreter is `Interpret`, add a check for that so it can get inlined.
Yields ~10% better performance for the cached interpreter on both the M1 and Skylake computers I tested.
<details>
<summary>I also tried collecting some performance counter data on M1</summary>
Interestingly, the biggest change was the drop in mispredictions for *non-indirect* jumps.  I'm guessing the conditional branch for `Instruction` / `Other` makes different interpreted paths look more different to the CPU's global branch history?
Test data is of the first 10 seconds from launch of Wind Waker.  I collected SIMD ALU instructions as a proxy for emulated cycles, since this change shouldn't affect those counts (while it does affect CYCLES, since the new code runs …
=> Cached Interpreter: Speculative devirtualization

Externals/discord-rpc/README.md, Externals/discord-rpc/include/discord_rpc.h, Externals/discord-rpc/src/connection_unix.cpp, Externals/discord-rpc/src/discord_register_linux.cpp, Externals/discord-rpc/src/discord_register_win.cpp, Externals/discord-rpc/src/discord_rpc.cpp, Externals/discord-rpc/src/rpc_connection.cpp, Externals/discord-rpc/src/serialization.cpp
* Updates discord-rpc to the [final commit](https://github.com/discord/discord-rpc/commit/963aa9f3e5ce81a4682c6ca3d136cddda614db33)
* Deleted the README since this software won't receive further updates
Note: This does not fix the [double activity "+1" RPC issue](https://bugs.dolphin-emu.org/issues/13665). I am looking into that unrelated to this.
https://github.com/dolphin-emu/dolphin/pull/13684 is also still relevant
=> Externals: Update discord-rpc

Source/Core/DolphinNoGUI/DolphinNoGUI.vcxproj
Add missing import of glslang.
=> Visual Studio: Fix DolphinNoGUI build
