- Source/Core/VideoCommon/ShaderCache.cpp
What the title says. Also removes the geometry shader in EFB2RAM pipelines, it was not needed as there is never a second layer for the RAM texture (only the left eye is used).
> Fix runtime stereoscopy mode switching

- Source/Core/VideoCommon/FrameDump.cpp
It looks like updated ffmpeg supports 2 versions of ffv1 (1 and 3), but we're not telling it what to use, so in the video it puts 0 if we dump at native resolution, but 3 if we dump at different resolution (not sure why).
I pass ffv1 version explicitly now, and using version 1 allows virtualdub/avisynth and similar VfW-based importers to decode it.
> Another AVI fix for WinAPI importers

- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
Previously, IR calibration data with an invalid checksum was used, because the calibration produced a strange offset.  I've replaced it with calibration data that encodes the same values as the data Nintendo falls back to when the checksum is bad.
I've also updated the [documentation on wiibrew](https://wiibrew.org/wiki/Wiimote#EEPROM_Memory), though I'm not completely happy with the naming and I'm still not 100% sure what these values _mean_ &mdash; but I know enough to at least replace it with the defaults.
It's worth noting that dolphin doesn't use the same value for acceleration as Nintendo defaults to &mdash; but it's probably not worth changing that as that would cause issues with TAS and such.  Since IR already behaved as if it were the default, it's fine to change this one.
> Use valid IR calibration data

- Source/Core/Core/HLE/HLE.cpp
This PR address the following issue: https://bugs.dolphin-emu.org/issues/11811
When multiple functions with the same name were patched, only the first one (earliest memory address) was properly patched.
Here is an example: [unittest_hle_printf.zip](https://github.com/dolphin-emu/dolphin/files/3665521/unittest_hle_printf.zip)
The expected behaviour with this PR is to print twice each message after loading the symbol map. One from the `my_puts_*` functions renamed as `printf` and the original `printf` function itself. The "Boot to Pause" option might be used to clear the ELF symbol and loading the symbol map before running the executable.
> HLE: Fix patching functions with the same name

- Source/Core/DolphinQt/Settings/AudioPane.cpp
It used to show the first option, No Audio Output (but audio output would work correctly anyway since AudioCommon didn't use this logic.)
> DolphinQt: When audio backend is invalid, show nothing in dropdown

- Source/Core/Common/FixedSizeQueue.h
The `storage = {};` statement in the `clear()` function causes GCC to blow up in memory usage when compiling LogWidget.cpp (approx. 16GB on my machine), and generate a 3.1GB assembly file in the `RelWithDebInfo` config. The `dolphin-emu` binary grows from ~300MB to ~900MB.
Not certain if this is a gcc bug or working as intended... I created a small repro program (albeit with a larger array size) which exhibits the same issue, and crashes gcc: https://pastebin.com/raw/iXrQEv0j
> FixedSizeQueue: Work around GCC generating large amounts of debug info

- Source/Core/AudioCommon/AlsaSoundStream.cpp
- Source/Core/AudioCommon/AudioCommon.cpp
After #8361 instead of falling back to null sound, it falls back to the ALSA driver on Linux. Which failed on the fifoci runner, which would've been fine except for the fact that the destructor calls `std::thread::join` without checking if the thread was actually created, which in the case of initialization failing, it wasn't.
Also adds a missing `Init()` call to the null backend, even though it's a no-op in case it changes in the future.
> Fix FifoCI

- Source/Core/Core/HW/WiimoteEmu/Camera.cpp
An old comment referred to some magic numbers that have been moved elsewhere.
> WiimoteEmu: Fix an outdated comment.

- .gitignore
Recent versions of Android Studio seem to put stuff here.
> Add /Source/Android/app/.cxx/ to .gitignore

- Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Pretty straightforward, connect the `returnPressed` signal to the same target as the `textChanged` one. This allows you to press Enter to go back to the address currently listed in the search box, which I feel like I need a surprising number of times while debugging...
> Qt/Debugger/CodeWidget: Allow pressing 'enter' in address search box.

- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/MenuBar.h
> SignatureDB: Add missing selectors

- Source/Core/InputCommon/ControllerEmu/ControlGroup/MixedTriggers.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Slider.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Triggers.cpp
Fixes: https://bugs.dolphin-emu.org/issues/11878
If a user increased the "Range" setting for a more sensitive input (common for the DJ Turntable extension) integer overflow was possible.
This PR clamps the results of the Slider and Trigger groups to prevent that.
Similar clamping is already done for `ReshapableInput` (analog sticks et al.).
> ControllerEmu: Clamp results of trigger/slider states to prevent integer overflow later on.

- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.h
Fixes: https://bugs.dolphin-emu.org/issues/11776
I've exposed the emulated tilt acceleration. It is calculated from a value in hertz referring to the peak turns per second when making a complete turn. This makes for a friendly default value of 7 which is approximately what the old hardcoded acceleration was.
The default maximum tilt angle is now 85 degrees. A full 90 degrees (old default) causes issues in some games, especially when tilting in two directions: e.g. Up+Left. Flying in Skyward Sword is an example.
Simulating centripetal acceleration doesn't really seem to help with MotionPlus accuracy in Skyward Sword at all and it was causing tilt responsiveness issues. I've removed it.
> WiimoteEmu: Tilt fixes.

- CMakeLists.txt
https://bugs.dolphin-emu.org/issues/11741 (and probably others)
Our IOKit code has problems with many controllers.
SDL seems to have fewer problems.
Let's see if our macOS buildbot can handle enabling SDL by default.
> CMake: Enable SDL by default on macOS.

- Source/Core/Core/NetPlayClient.cpp
Changed a do-loop to a while-loop so packets can be dropped when the buffer size is reduced.
The same logic is already used for GameCube controllers.
Fixes: https://bugs.dolphin-emu.org/issues/11830
> NetPlay: Allow Wii Remote buffer size to decrease

- Source/Core/DolphinQt/Config/SettingsWindow.cpp
- Source/Core/DolphinQt/Settings/AdvancedPane.cpp
- Source/Core/DolphinQt/Settings/AdvancedPane.h
- Source/Core/DolphinQt/Settings/GeneralPane.cpp
- Source/Core/DolphinQt/Settings/GeneralPane.h
Solves https://bugs.dolphin-emu.org/issues/11743
I changed the CPU Emulation options to a combobox selection and moved it over to the Advanced tab.
> Qt: Move CPU Emulation Engine options to the Advanced tab

- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/IOWindow.h
- Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp
- Source/Core/InputCommon/CMakeLists.txt
- Source/Core/InputCommon/ControlReference/ControlReference.cpp
- Source/Core/InputCommon/ControlReference/ControlReference.h
- Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
- Source/Core/InputCommon/ControlReference/ExpressionParser.h
- Source/Core/InputCommon/ControlReference/FunctionExpression.cpp
- Source/Core/InputCommon/ControlReference/FunctionExpression.h
- Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp
- Source/Core/InputCommon/ControllerEmu/ControllerEmu.h
- Source/Core/InputCommon/InputCommon.vcxproj
- Source/Core/InputCommon/InputCommon.vcxproj.filters
Demonstrations (**note: syntax has changed. function names used to be prefixed with !**)
https://i.imgur.com/9wCT3sH.gif
https://i.imgur.com/codD9p2.gif
https://i.imgur.com/PbeGoKl.gif
Added syntax highlighting and parse result display:
https://giant.gfycat.com/GlaringOddballGenet.webm
https://giant.gfycat.com/BasicScaredBarracuda.webm
When a function is inserted with the improper number of arguments the expected arguments are shown in the parse-result textbox.
Literals are now supported, e.g. `` `Trigger R`+0.25``
This is useful for:
- Holding Wiimote "Tilt" or IR "Forward/Backward" to a certain neutral value.
- Modifying dirty input values on troublesome gamepads.
- Math in advanced configurations
Additional binary and unary operators have been added for advanced configurations:
- `, * …
> Expression parser improvements

- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.h
- Source/Core/DolphinQt/GCMemcardManager.cpp
- Source/Core/DolphinQt/GCMemcardManager.h
The previous code had some odd assumptions that caused it to only show, at max, the first three frames of each animation. It also didn't handle the animation speed or the ping-pong frame order correctly. This should all be fixed with this.
The performance of this I mentioned in IRC is marginally improved by this due to the timer running less often, but it's still pretty poor; further investigation into that is necessary.
> Qt/GCMemcardManager: Fix icon animations displaying incorrectly.

- Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
These were marked as translatable in DolphinWX but not DolphinQt, yet both DolphinWX and DolphinQt tried to fetch translations for them. This meant that translations worked in both DolphinWX and DolphinQt back when DolphinWX existed, but that translations stopped working in DolphinQt once DolphinWX was removed (because the removal of DolphinWX triggered the removal of the strings from the .po files).
> DolphinQt: Mark ubershader setting names as translatable

- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.h
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
These classes are not copyable or movable because they indirectly have std::atomic members.
Defaulting their constructors and move operators was producing warnings in clang.
> Core/HW: Fix some explicitly defaulted but implicitly deleted warnings.

- Source/CMakeLists.txt
- Source/VSProps/Base.props
Hopefully helps us with whitelisting our updater...
> Windows: Make builds more reproducible

- Source/Core/Common/StringUtil.h
Our `TryParse` for integer types checks `strtoull`'s `endptr` to make sure the entire string is parsed.
Failure is returned for things like "42 " or "123 foobar".
I've changed the `TryParse` overload used for floating point types to check the `eof` flag for the same behavior.
Previously things like "4.5foobar" would successfully parse as a double.
> StringUtil: Require TryParse of float types to use the entire string.

- Source/Core/DolphinQt/GCMemcardManager.cpp
Small thing I messed up in #8304; this then leads to an out-of-bounds error when drawing the blank icon. In practice this almost never happens because all official save files have icons, but might as well fix this.
> Qt/GCMemcardManager: Fix incorrect placeholder frame timing.

- .gitignore
Not quite sure what this is, but Visual Studio creates it occasionally.
> Add enc_temp_folder to .gitignore

- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
- Source/Core/InputCommon/ControlReference/ExpressionParser.h
This adds support for the XOR operator `^` in input expressions.
While it might seem esoteric I often find myself needing it for things like:
``toggle(`Q`) ^ `E` ``
...where pressing `Q` toggles some action and holding `E` negates the state of the toggle.
> ExpressionParser: Add XOR operator.

- Source/Core/DolphinQt/GameList/GameListModel.cpp
- dataChanged takes "first" and "last" indices inclusive, not exclusive
- columnCount should return 0 for valid parents
This fixes a non-fatal assertion in debug builds while generating gamelist cache. Delete your `Cache` directory and run a debug compilation of Dolphin to repro.
> Fixup GameListModel::UpdateGame and columnCount

- Source/Core/DolphinQt/Debugger/WatchWidget.h
Fixes integer comparison signedness warnings.
> WatchWidget: Fix integer comparison signedness warnings

- Source/CMakeLists.txt
Fixes the build log being spammed with [Warning D9025](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/command-line-warning-d9025?view=vs-2019).
> CMake/Windows: Fix warnings about flags being overridden

- Source/Core/Common/FileUtil.cpp
- Source/Core/DiscIO/VolumeVerifier.cpp
This was making it impossible to use the Redump.org integration without first manually creating a Redump folder in the Cache folder. https://bugs.dolphin-emu.org/issues/11885
> Create necessary folder when using Redump.org integration

- Source/Android/app/build.gradle
When `git` isn't installed to the terminal the `getVersion()` and `getBuildVersionCode()` will use dummy values.
The problem is the dummy value for `getBuildVersionCode()` causes gradle to complain with the following error.
```
ERROR: android.defaultConfig.versionCode is set to 0, but it should be a positive integer.
See https://developer.android.com/studio/publish/versioning#appversioning for more information.
Affected Modules: app
```
Changed the dummy versionCode number to 1.
> Fix versionCode dummy value

- Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp
- Source/Core/VideoBackends/Vulkan/CommandBufferManager.h
- Source/Core/VideoBackends/Vulkan/Renderer.cpp
- Source/Core/VideoBackends/Vulkan/Renderer.h
- Source/Core/VideoBackends/Vulkan/SwapChain.cpp
- Source/Core/VideoBackends/Vulkan/SwapChain.h
- Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
- Source/Core/VideoBackends/Vulkan/VulkanContext.h
- Source/Core/VideoBackends/Vulkan/VulkanEntryPoints.inl
- Source/Core/VideoBackends/Vulkan/VulkanLoader.h
- Source/Core/VideoBackends/Vulkan/main.cpp
This PR uses the new `VK_EXT_full_screen_exclusive` extension to provide application-level control of the display. You can check if the extension is being used by looking at the log (enable "Video Backend", set to info level) to see if there is a message about "exclusive fullscreen being used", and acquired/released. Scary diff line count is due to the headers update, the actual changes are quite small (see the last 3 commits).
Unfortunately, the extension is (for now) Windows-only, sorry Linux users.. I hope your compositor is smart enough to scan out Dolphin's buffers directly...
I know the NVIDIA driver "attempts" to use exclusive fullscreen when it can, so this may not make a difference on such systems. However, the extension is also supported by AMD, and I'm not sure if their driver …
> Vulkan: Exclusive fullscreen support via VK_EXT_full_screen_exclusive

- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/VolumeVerifier.h
This happens if someone manually downloads a regular datfile from redump.org and puts it where Dolphin stores datfiles. Dolphin needs "special" datfiles that contain fields for serials and versions.
Before this change, all discs (except Datel discs) would show up as "Unknown disc" when using a regular datfile.
> RedumpVerifier: Show an error when datfile lacks serials or versions

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/NVidiaShieldWorkaroundView.java
This text has been taken from the message of the commit that added the class. (I don't have an Nvidia Shield to reproduce the bug with.)
> Android: Expand the comment for NVidiaShieldWorkaroundView

- Source/Core/DolphinQt/HotkeyScheduler.cpp
When emulation is not running our controller interface is updated by the hotkey scheduler.
A filter is installed to prevent hotkeys from triggering when configuring them.
This was preventing the mapping buttons from showing their activation by turning bold.
`UpdateInput` is now called before checking if hotkeys are filtered.
Fixes: https://bugs.dolphin-emu.org/issues/11835
> DolphinQt: Make HotkeyScheduler call UpdateInput when hotkeys are disabled.

- Source/Core/VideoBackends/D3D/main.cpp
- Source/Core/VideoCommon/FramebufferShaderGen.cpp
- Source/Core/VideoCommon/FramebufferShaderGen.h
- Source/Core/VideoCommon/PostProcessing.cpp
- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/RenderBase.h
Fixes:
- Fixes the same image was rendered to both eyes in quad-buffered modes in D3D/Vulkan modes.
- Removes the redundant geometry shader in OpenGL mode, as the eyes are rendered separately.
New:
- Renders the UI (ImGui) to both eyes. Previously, this was only rendered to the left eye, which I imagine would look incorrect if using a HMD.
I've only tested D3D and Vulkan by checking both layers in RenderDoc, as I don't have a compatible display to check against. GL just gives a `GL_INVALID_OPERATION` result when selecting the eyes via `glDrawBuffers`, which is expected without a display.
> Various quad-buffered ("HDMI 3D") stereo fixes

- Source/Core/DolphinQt/Config/ControllersWindow.cpp
Without this change, calling OnEmulationStateChanged undoes part of the enabling/disabling that OnWiimoteModeChanged has done.
> DolphinQt: Fix the enabling/disabling of ControllersWindow buttons

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
- Source/Android/jni/MainAndroid.cpp
- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
The workaround was added in 0446a58.
The underlying problem is that we must not destroy the surface while the video backend is initializing, otherwise the video backend may reference nullptr.
I've also cleaned up the logic for when to destroy the surface. Note that the comment in EmulationFragment.java about only being able to destroy the surface when emulation is running is not true anymore (due to de632fc, it seems like).
> Android: Replace emulation rotation crash workaround with proper fix

- Source/Core/Core/HW/VideoInterface.cpp
- Source/Core/Core/State.cpp
This wasn't changed when halfline counts were changed to 0-based. Also
included is a diagram showing an understanding of how the values in the VI
timing registers maps to the video signal.
> VI: Adjust start/end of ACV region for fields

- Source/Core/Core/HW/VideoInterface.cpp
Datel's Wii Freeloaders set `m_PictureConfiguration.WPL` to 0 for a while. Not sure if the fix in this commit is a proper fix or just a hack, since I'm not very familiar with this code.
With this change, it's possible to run a Wii Freeloader if you are running an old enough version of the Wii Menu, but the "coloured bars" that Datel reference in their documentation never show up. The screen just freezes for a few seconds instead.
> VideoInterface: Don't crash when running Wii Freeloader

- Source/Core/DolphinQt/Config/SettingsWindow.cpp
- Source/Core/DolphinQt/Settings/AudioPane.cpp
- Source/Core/DolphinQt/Settings/GeneralPane.cpp
- Source/Core/DolphinQt/Settings/WiiPane.cpp
- Source/Core/DolphinQt/Settings/WiiPane.h
Otherwise UI elements won't be disabled correctly if the config window is first opened while a game is running.
> DolphinQt: Call OnEmulationStateChanged when creating config window panes

- Source/Core/Common/GL/GLContext.cpp
- Source/Core/Common/GL/GLContext.h
- Source/Core/Common/GL/GLInterface/AGL.h
- Source/Core/Common/GL/GLInterface/AGL.mm
- Source/Core/Common/GL/GLInterface/EGL.cpp
- Source/Core/Common/GL/GLInterface/EGL.h
- Source/Core/Common/GL/GLInterface/EGLAndroid.cpp
- Source/Core/Common/GL/GLInterface/EGLX11.cpp
- Source/Core/Common/GL/GLInterface/GLX.cpp
- Source/Core/Common/GL/GLInterface/GLX.h
- Source/Core/Common/GL/GLInterface/WGL.cpp
- Source/Core/Common/GL/GLInterface/WGL.h
- Source/Core/Common/WindowSystemInfo.h
- Source/Core/DolphinNoGUI/CMakeLists.txt
- Source/Core/DolphinNoGUI/MainNoGUI.cpp
- Source/Core/DolphinNoGUI/Platform.h
- Source/Core/DolphinNoGUI/PlatformFBDev.cpp
Also adds fbdev support for GLInterface, and is sufficient for running Dolphin on an ODROID-N2 with the ARM blob.
I still want to rip out our GLInterface at some point and replace it with some cross-platform library, but the actual fbdev stuff is pretty self contained and only ~100 lines.
> DolphinNoGUI: Add a FBDev platform

- Source/Core/DolphinQt/GameList/GameTracker.cpp
- Source/Core/DolphinQt/GameList/GameTracker.h
- Source/Core/DolphinQt/Settings.cpp
- Source/Core/DolphinQt/Settings.h
- Source/Core/DolphinQt/ToolBar.cpp
This PR improves Game Tracker functionality by addressing the following:
* Fixes a race condition when rapidly clicking Refresh button - previously, game list would continuously be populated over and over, leaving itself in broken state where most entries were duplicated.
* Enables/disables Refresh button when refresh is already in place. While code technically should support "nested" refresh jobs, I don't know if you can actually end up in such state - maybe if you press Refresh button **and** use Refresh Game List hotkey at once? No idea.
This PR is generally finished, but I am marking it WIP because I am not satisfied with how it is possible to see _"Dolphin could not find any games..."_ for a split second while refreshing! Ideally, I would like it to just show something like …
> Qt: Game Tracker fixes

- Source/Core/DolphinQt/RenderWidget.cpp
Under KDE, there's not really a good way to turn the desktop compositor off while a game is running in Dolphin. However, KWin (and most likely other window managers) can be configured to turn the compositor off when it sees a window with a certain window role (a string that can be attached to a window in X11). This 1-line change uses QWidget::setWindowRole to set the role of the render window to "renderer" on initialisation so the window manager can match it to a rule and is (I think) a non-op on other platforms (I don't know if it sets the app_id on Wayland though). I'm also trying to find a way to see if compositing can be blocked automatically, but I'm not sure it can be done without linking to another library (either dbus or libkf5windowsystem).
> Qt: Add "renderer" window role to render window

- Source/Core/DolphinQt/Config/VerifyWidget.cpp
The case body is empty because VolumeVerifier doesn't actually report
problems with severity of None.
Fixes "warning: enumeration value ‘None’ not handled in switch [-Wswitch]"
warning reported by gcc.
> VerifyWidget: Handle Severity::None case in Verify()

- Data/Sys/GameSettings/GKB.ini
- Data/Sys/GameSettings/RMH.ini
Because of the EFB access optimization, games which were forced to skip EFB access in order to be playable don't need to be forced anymore. 
There are also reports of skip EFB access causing issues in Baten Kaitos: https://forums.dolphin-emu.org/Thread-gc-baten-kaitos-eternal-wings-and-the-lost-ocean?pid=493827#pid493827
Monster Hunter also doesn't need EFB to texture and ram.
> Enable EFB access in INI

- Source/Android/build.gradle
Android Studio recommends to update to Gradle 3.5.2.
> Android: Update to Gradle 3.5.2

- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/IOWindow.h
- Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
Input list in the "advanced" dialog now has a second column showing each input state in real-time.
This may help identify desired inputs in more advanced configurations.
e.g. when mapping raw accelerometer/gyroscope.
> Qt/Mapping: Show current input states in advanced dialog.

- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
Fix regression from #8396.
Some widgets are conditionally added to the layout.
The unused ones were showing up in the top-left corner.
This hides the unused widgets.
> DolphinQt: Hide unused buttons in the advanced mapping dialog.

- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/Config/MainSettings.h
- Source/Core/DolphinQt/ResourcePackManager.cpp
- Source/Core/DolphinQt/Settings/PathPane.cpp
- Source/Core/DolphinQt/Settings/PathPane.h
- Source/Core/UICommon/ResourcePack/ResourcePack.cpp
- Source/Core/UICommon/UICommon.cpp
If you have Dolphin installed on a SSD, you might not want to  have giant textures or giant zips installed in  your user directory.  Instead, you can delegate those folders to be off in another location.
Fixes:  https://bugs.dolphin-emu.org/issues/9970
> DolphinQt: Add ability to override ResourcePack and Load directory

- Source/Core/Common/CDUtils.cpp
- Source/Core/Common/Common.h
- Source/Core/Common/CommonFuncs.cpp
- Source/Core/Common/CommonFuncs.h
- Source/Core/Common/CompatPatches.cpp
- Source/Core/Common/FileUtil.cpp
- Source/Core/Common/FileUtil.h
- Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
- Source/Core/DolphinQt/DolphinQt.manifest
- Source/Core/UICommon/UICommon.cpp
- Source/Core/WinUpdater/Main.cpp
- Source/Core/WinUpdater/Updater.exe.manifest
This PR makes Dolphin compatible with Windows 10 long paths. Windows 10 1607 and newer allows applications to lift MAX_PATH limitation via manifest, so with a few code changes I was able to remove MAX_PATH dependency from all non-Qt code paths and opt in to that.
I verified against games and settings located in a path which has over MAX_PATH characters - game showed in the list and booted, settings also seem to save.
The only function still using MAX_PATH (and not being a third party) is `CreateTempDir` but as far as I can tell that is only used in unit tests, so I didn't bother.
> Support Windows 10 long paths

- .gitignore
Someone already thought about it for the Build, but not the rest.
This helps with the trick of having  "_Branch Specific IDE Output Directories_", which can be created and managed with the following script I made originally for myself. https://gist.github.com/altimumdelta/1d43053f7373baae1066194b0f765a63
> Git-Ignore: Also ignore other derivatives of VS output directories

- Source/Android/jni/GameList/GameFile.cpp
- Source/Core/DolphinQt/Config/InfoWidget.cpp
- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/GameList/GameListModel.cpp
- Source/Core/UICommon/CMakeLists.txt
- Source/Core/UICommon/GameFile.cpp
- Source/Core/UICommon/GameFile.h
- Source/Core/UICommon/GameFileCache.cpp
- Source/Core/UICommon/UICommon.vcxproj
This feature was originally exclusive to the previous iteration of DolphinQt (the one that was the reason for the current iteration being named DolphinQt2 initially).
https://bugs.dolphin-emu.org/issues/8949
> GameFile: Support HBC-style XML metadata

- Source/Core/DolphinQt/GCMemcardManager.cpp
- Source/Core/DolphinQt/GCMemcardManager.h
This just seems like a logical thing to do, as typically the user will want to mess with their currently configured memory card when using the memcard manager. They can still load a different memory card if they want, this doesn't change that functionality, just adds convenience for the common use case.
> Qt/GCMemcardManager: Load configured memory cards by default

- Source/Core/Common/MathUtil.h
- Source/Core/Core/HW/WiimoteEmu/Dynamics.h
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
- Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
- Source/Core/InputCommon/ControllerInterface/evdev/evdev.h
evdev devices with motion data are detectable be checking for `INPUT_PROP_ACCELEROMETER`.
Each axis then provides a resolution property to get the correct unit scaling.
This makes configuration much easier and there is no longer a need to manually scale values using input expression multiplication.
There doesn't seem to be consistent orientations across devices so I've been forced to use "Accel X"/"Gyro X" naming instead of the "Gyro Pitch Up" names our DSU client uses.
I've eliminated redundant `GRAVITY_ACCELERATION` constants.
> InputCommon: Detect when evdev exposes acceleration/gyroscope data.

- Source/Core/Core/HW/WiimoteReal/IOLinux.cpp
Remove an old comment about blocking time.
We've use an infinite timeout here since: 02fc68ea5d1466998c7d59b2882a5f9e348de24b
The first argument to `select` was never updated in this commit.
It was causing `m_wakeup_pipe_r` to not be checked on my system. (sometimes)
As a result, writes would not occur unless there was something to read. (sometimes)
Apparently FD sets (and select) can't handle descriptors with values higher than 1024 anyways so I've changed the code to use `poll` instead which seems to be recommended.
> HW/WiimoteReal: Linux fix.

- Source/Core/Core/BootManager.cpp
- Source/Core/Core/BootManager.h
- Source/Core/Core/CMakeLists.txt
- Source/Core/Core/Core.vcxproj
- Source/Core/Core/Core.vcxproj.filters
- Source/Core/Core/IOS/DolphinDevice.cpp
- Source/Core/Core/IOS/DolphinDevice.h
- Source/Core/Core/IOS/IOS.cpp
I added some code to Dolphin, mainly a new device `/dev/dolphin` that can be used by Dolphin-aware software like homebrew to query certain information about Dolphin. 
Currently, that includes the real system time in ms (not the emulated system time), and the Dolphin version. Now I know from past conversations on the forum that there is no way for emulated software to detect real system time as that might confuse games when system time and emulated time run at different speeds. 
However, implementing this as an additional device /dev/dolphin means that no official game will ever know of this, as no official game would ever access /dev/dolphin. 
For Wiimmfi it would be pretty cool to let the game know that it lags (doesn't run at full 60fps), by comparing emulated time with this real time. …
> Add /dev/dolphin for homebrew to get information about Dolphin

- Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
This should have been done in #8460.
`MotionDataInput` divides the integer resolution by a double. It should not be stored in m_range as an int.
> evdev: fix bad integer division.

- Source/Core/Common/Matrix.cpp
- Source/Core/Common/Matrix.h
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
These indicators will help in configuration and checking for proper orientation/scale.
It is currently a mystery if things are correct until you get in-game.
This is less of an issue when using the "Cemuhook" input backend (which has nicely named inputs) but more of an issue in Linux where evdev exposes the raw data.
Demonstration:
https://giant.gfycat.com/AllMediumFrillneckedlizard.webm
I've since added text to the gyroscope indicator with the red dot's angle from the upright position.
The accelerometer indicator shows the perceived orientation and g-force.
The colored dots provide a frame of reference.
The gyroscope indicator rotates in real time with the controller.
The red and blue dots are oriented differently so all three rotational axes can be followed and calibrated.
When the …
> DolphinQt: Add accelerometer/gyroscope mapping indicators.

- Source/Android/jni/MainAndroid.cpp
- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
- Source/Core/Core/HW/VideoInterface.cpp
- Source/Core/Core/Host.h
- Source/Core/Core/IOS/USB/USB_KBD.cpp
- Source/Core/DolphinNoGUI/MainNoGUI.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
- Source/Core/DolphinQt/Host.cpp
- Source/Core/DolphinQt/HotkeyScheduler.cpp
- Source/Core/DolphinQt/Settings.cpp
- Source/Core/DolphinQt/Settings.h
- Source/Core/InputCommon/ControlReference/ControlReference.cpp
- Source/Core/InputCommon/ControlReference/ControlReference.h
- Source/DSPTool/StubHost.cpp
- Source/UnitTests/StubHost.cpp
The "input gate" suppresses input to the game and the hotkey manager when the window is not focused (depending on settings).
In order to receive input in the controller config window a value was quickly set and cleared to override the input gate.
This periodically leaked input into the game. (noticeable when holding buttons in the config window)
Rather than testing the window focus, background input setting, and override value for each input, a `thread_local bool` is now maintained with the actual gate value.
This kills `Host_UINeedsControllerState`.
On the CPU thread the input gate is updated once per SI poll which is well enough granularity.
On the "Host" thread the input gate is updated before checking the hotkeys and then "opened" for everything else in the UI.
> InputCommon: Make the "input gate" not racy.

- Source/Core/DolphinQt/DolphinQt.manifest
- Source/Core/WinUpdater/Updater.exe.manifest
Fixes a regression caused by #8393. 2016 manifest XML schema removed a 2005 `dpiAware` attribute, which caused Dolphin's manifest to silently ignore this attribute, but in the case of updater it exploded loudly instead.
This PR fixes both manifests. Sadly, since updater cannot launch it means that those unlucky people who updated during the past 1.5 days have to update manually.
> Fix malformed manifests

- Source/Android/app/build.gradle
Since 11/01/2019, Android requires SDK version 28 (aka Android 9). If you submit an update with SDK version 27 and below, Google will reject the update. Read more here: https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html
I have tested this change on my phone and haven't encountered any issues.
> Android: Update target Android SdkVersion to 28

- Source/Android/app/build.gradle
This is a suggested change by Android Studio. Depends on #8461.
I've tested this change on my device and didn't encounter any issues.
> Android:  update androidSupportVersion and compileSdkVersion to 28

- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/DolphinQt/Config/ControllerInterface/DualShockUDPClientWidget.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
Small enhancements to PR #8352.
- ~Apply default accelerometer and gyroscope bindings (as shown) when loading an old input configuration.
**Reason:** If there exists a `WiimoteNew.ini` from an older Dolphin version, those bindings will be blank, and motion input won't work. You would have to either manually set each of the 12 controls (which is not hard, just time consuming) or press the `Default` button and lose all other bindings.
**Details:** This was accomplished by adding versioning to input config files, including input profiles.~
- Add checkbox for enabling/disabling the motion controlled pointer. This is useful if you want to control the pointer by other means, like a mouse or the DualShock 4's touch pad. 
- Enable `Server IP Address` and `Server Port` fields only when `Enable` is …
> Motion Input enhancements

- Source/Core/AudioCommon/AudioCommon.cpp
- Source/Core/AudioCommon/AudioCommon.h
- Source/Core/AudioCommon/AudioCommon.vcxproj
- Source/Core/AudioCommon/AudioCommon.vcxproj.filters
- Source/Core/AudioCommon/CMakeLists.txt
- Source/Core/AudioCommon/CubebStream.cpp
- Source/Core/AudioCommon/Enums.h
- Source/Core/AudioCommon/Mixer.cpp
- Source/Core/AudioCommon/Mixer.h
- Source/Core/AudioCommon/OpenALStream.cpp
- Source/Core/AudioCommon/PulseAudioStream.cpp
- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/Config/MainSettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/Core/ConfigManager.cpp
- Source/Core/Core/ConfigManager.h
- Source/Core/DolphinQt/Settings/AudioPane.cpp
- Source/Core/DolphinQt/Settings/AudioPane.h
Users were commenting that their games had now lower audio quality with the new DPLII decoder (the old one just did not work at all, however the new one can add annoying artifacts). It seems this was so because of the chosen SURROUND_BLOCK_SIZE which was set to a too low of a value.
All the games I tested and played did not have complex music or just simple SFX, so I did not detect this problem at all.
However I was not sure if I want to hard-code it to a higher value as it directly increases the audio latency, therefore this PR.
Quality/latency equivalency (assuming sample rate of 48000):
- Low - SURROUND_BLOCK_SIZE = 512 - Latency = ~10 ms **(old hard coded default)**
- Medium - SURROUND_BLOCK_SIZE = 1024 - Latency = ~20 ms
- High - SURROUND_BLOCK_SIZE = 2048 - Latency = ~40 ms **(new …
> Add slider to change DPLII decoder quality

- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/MainWindow.h
- Source/Core/DolphinQt/QtUtils/ModalMessageBox.cpp
- Source/Core/DolphinQt/QtUtils/ModalMessageBox.h
As per discussion on IRC, this PR makes "Do you want to exit emulation?" application modal and ensures only a single instance of it exists. This fixes numerous issues, eg.:
- Being able to spam dialogs by pressing Escape
- Being able to close emulation window by just pressing X twice
> UI: Fixes for exit dialog

- Data/Sys/GameSettings/E62.ini
- Data/Sys/GameSettings/G4Z.ini
- Data/Sys/GameSettings/G96.ini
- Data/Sys/GameSettings/GGC.ini
- Data/Sys/GameSettings/GIS.ini
- Data/Sys/GameSettings/GT3.ini
- Data/Sys/GameSettings/GWT.ini
- Data/Sys/GameSettings/R5P.ini
- Data/Sys/GameSettings/RDZ.ini
- Data/Sys/GameSettings/RH6.ini
- Data/Sys/GameSettings/RHA.ini
- Data/Sys/GameSettings/RHO.ini
- Data/Sys/GameSettings/RTB.ini
- Data/Sys/GameSettings/RYB.ini
- Data/Sys/GameSettings/SCI.ini
Dualcore changes taken from #8164.
I have re-evaluated all the dualcore changes and only included the most important INI changes based on the wiki, issue tracker and forum. 
Dualcore has been enabled for 'Baten Kaitos Eternal Wings and the Lost Ocean' as tests on wiki show that it can safely be enabled.
> Dualcore INI changes

- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.h
- Source/Core/DolphinQt/GCMemcardManager.cpp
Previously the code assumed that the data for the comments, banners, and icons was contiguous from the first block of the data's physical offset in the memory card, rather than referring to the logical position within the referenced save file, which is not only incorrect for the format but could also lead to out-of-bounds memory accesses. This should now be rectified.
Fixes:
https://bugs.dolphin-emu.org/issues/10600
https://bugs.dolphin-emu.org/issues/11820
Please scrutinize this, I'm not entirely sure if this is all correct. It seems to give correct results for all memory cards I have access to, but considering how long this old approach seemingly worked who knows.
~~The Icon/Banner code could probably use some additional rewriting on top of this to be honest, it's a mess. It also seems …
> GCMemcard: Read comments, banners, and icons via logical data offsets instead of physical ones.

- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
The accelerometer indicator was left/right reversed.
Apparently I didn't test it very well.
> DolphinQt: Fix accelerometer mapping indicator flipped X axis.

- Source/Core/DolphinQt/GCMemcardManager.cpp
as described in the issue tracker, if you load a bit of a bigger memory card that has a larger list of saves ( 39 in my raw ) the redrawing of the icons takes waaay to much cpu time and it semi kills the window.
i fixed this by 
1) skipping unloaded memory card slots.
2) skipping icons that don't have an animation or don't need updating
3) only redrawing icons currently being displayed in the table.
this made the window usable for me, and dropped the cpu time from ~30% to ~4%
this will probably conflict with a PR from AdmiralCurtiss (https://github.com/dolphin-emu/dolphin/pull/8304) , and i'll fix it after his stuff is merged
> GCMemcardManager : icon drawing takes to much cpu time

- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
- Source/Core/Core/HW/VideoInterface.cpp
Currently, frame-stepping and `Movie::FrameUpdate()` are dealt with at the beginning of each "active video field" (see `Core::Callback_VideoCopiedToXFB()`). 
This is [conceptually] inconsistent with accurate SI polling emulation (#8236 and other WIP branches) because SI polls may occur in the space between active video fields. Here's some log output from a game that does SI polling four times in one field:
```
// Current behavior
Core/HW/VideoInterface.cpp:809 I[SI]: new video interrupt, half_line=0000
Core/HW/VideoInterface.cpp:741 I[SI]: new field, half_line=0000 (start of full field)
Core/HW/VideoInterface.cpp:749 I[SI]: new poll, half_line=000f
VideoCommon/VideoBackendBase.cpp:73 I[SI]: Video_BeginField (start of active field)
!!!!!! Core/Core.cpp:843 I[SI]: <Movie::FrameUpdate() …
```
> Align frame advance and movies to full field boundaries

- Source/Core/Core/Core.cpp
- Source/Core/Core/HW/Wiimote.h
- Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
- Source/Core/Core/IOS/MIOS.cpp
- Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp
Previously, only Mii data was written.  Additionally, the file containing mii data was shared for all Wiimotes, which made it a lot less useful.
Additionally, the file was read/written on each Wiimote read, even though the whole EEPROM was kept in memory.  This was bad for performance and not particularly necessary (it did enforce that the data was properly shared between all Wiimotes, but that's not something I want).
-----
Some notes about this:
* If there is no `Wiimote#.bin` file, the previous `mii.bin` file will be read (if it exists) and used to populate the mii block.  However, since the `Wiimote#.bin` files are not written until a write to EEPROM happens, this will continue happening on each startup.  Also, the `mii.bin` file isn't ever deleted, which is probably fine but might …
> Write the entirety of the Wiimote EEPROM, in a per-Wiimote file

- Source/Android/app/build.gradle
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/RumbleBindingSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/InputBindingSettingViewHolder.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/DividerItemDecoration.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Rumble.java
- Source/Android/app/src/main/res/values/styles.xml
- Source/Android/build.gradle
- Source/Android/gradle.properties
- Source/Android/gradle/wrapper/gradle-wrapper.properties
This will help the Android client to evolve with the latest libraries (as the legacy support libs will not be shipped anymore with the com.android.support package).
This PR also makes the app compliant with the new API requirements to start later this year:
https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html
> Bumps compile API to 29 (Q) and removes deprecated calls and unnecessary casts

- Source/Core/DiscIO/VolumeVerifier.cpp
This was completely wrong, but I guess it happened to work correctly anyway due to timing reasons (MD5 is faster than SHA-1 + AES).
> VolumeVerifier: Fix a copypaste error

- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.h
Trims out unnecessary includes to avoid unnecessary header dependencies.
This also resolves indirect inclusions of `<optional>` within IMUAccelerometer.h and IMUGyroscope.h
> InputCommon/IMU*: Remove unnecessary includes

- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.h
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPProto.h
Initially intended to be a change adding missing header guards, this kind of snowballed into a general cleanup change. Many of the changes are fairly bog-standard in terms of modifications done.
We leverage std::array to simplify comparisons and copying of data, which makes many of these cases much nicer to read.
> InputCommon/DualShockUDPClient: Minor cleanup

- Source/Core/UICommon/CMakeLists.txt
- Source/Core/UICommon/Disassembler.cpp
- Source/Core/UICommon/Disassembler.h
- Source/Core/UICommon/DiscordPresence.cpp
- Source/Core/UICommon/GameFile.cpp
- Source/Core/UICommon/USBUtils.cpp
- Source/Core/UICommon/X11Utils.cpp
Continues the migration to using fmt.
Notably, this allows safely converting a map within USBUtils over to containing `std::string_view` instances, rather than `std::string` instances, as fmt safely handles the formatting of string views.
> UICommon: Make use of fmt where applicable

- Source/Core/Core/HW/CPU.cpp
This PR fixes a rare crash in Dolphin, easiest to reproduce by spamming volume up/down controls continuously in game. With a little bit of luck (and patience), it was possible to crash on recursive stepping mutex lock. It seems to be a lot easier to reproduce it after opening and closing Config window before running the game, so Audio settings window gets created and registers its config callbacks.
The underlying reason behind this crash was an infinite recursion caused by yielding to UI thread (processing Qt events) from `Core::RunAsCPUThread` running in a callback from another Qt event. Yielding was done only when `s_state_cpu_idle_cvar` wait timed out, which turned out to be **extremely** rare, so removing it does not impact UI responsiveness negatively.
The exact sequence of events …
> Do not yield to UI from PauseAndLock

- Source/Core/DiscIO/VolumeWii.cpp
Fixes using DirectoryBlob on extracted games that were unencrypted prior to being extracted.
(One day I'll make DirectoryBlob actually support raw reads and then the order of these two won't matter...)
> VolumeWii: Check SupportsReadWiiDecrypted before m_encrypted

- Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
Fixes a deadlock when accessing Graphics config **immediately** after booting up the game when using a LLE DSP.
DSP thread is considered "idle" when it signals `s_ppc_event` and waits for `s_dsp_event`, without putting it in this state when `m_dsp_thread_mutex` is locked it was possible to create a deadlock between a DSP thread, emulation thread and Qt thread.
> DSPLLE: Put DSP thread in idle state when it's paused

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/DolphinApplication.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
We must set `Java_GCAdapter.manager` before the GC adapter thread (C++) starts. We used to set it at emulation start, which was fine until PR #8190 made the GC adapter thread start much earlier.
> Android: Fix crash on enabling GC adapter

- Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
- Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
Fixes both issues from the report.
For set value:
The original code converts the string into a value and then attempts to work out the size of the input by downcasting and comparing. This breaks for leading zeros as, for example, 0042 == (u8)0042. The fix calculates the correct length from the original string, taking into account the possibility that the string is prefixed by "0x".
For copy hex:
The code already attempts to take the first "length" characters, however incorrectly converts/pads the value and so copies the first "length" nonzero characters. This meant that copying the 01 of 01 23 would result in the string 12 being copied. The fix always fully pads the read value and then correctly takes the leftmost characters.
> Fixed #11874 (leading 0s ignored by debugger)

- Source/Core/VideoCommon/BPStructs.cpp
- Source/Core/VideoCommon/CMakeLists.txt
- Source/Core/VideoCommon/FrameDump.cpp
- Source/Core/VideoCommon/HiresTextures.cpp
- Source/Core/VideoCommon/NetPlayGolfUI.cpp
- Source/Core/VideoCommon/OnScreenDisplay.cpp
- Source/Core/VideoCommon/PostProcessing.cpp
- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/ShaderGenCommon.cpp
- Source/Core/VideoCommon/TextureCacheBase.cpp
- Source/Core/VideoCommon/UberShaderCommon.h
- Source/Core/VideoCommon/VertexLoaderBase.cpp
Migrates most of VideoCommon over to using fmt, with the exception being the shader generator code. The shader generators are quite large and have more corner cases to deal with in terms of conversion (shaders have braces in them, so we need to make sure to escape them).
Because of the large amount of code that would need to be converted, the conversion of VideoCommon will be in two parts:
- This change (which converts over the general case string formatting),
- A follow up change that will specifically deal with converting over the shader generators.
> VideoCommon: Make use of fmt outside of shader generators

- Data/dolphin-emu.desktop
Dolphin doesn't have a working Wayland renderer (not even with `env SDL_VIDEODRIVER=wayland dolphin-emu`). By setting the `QT_QPA_PLATFORM` variable to "xcb" we ensure that Dolphin runs just fine in any Wayland-based desktop environment instead of displaying an error message.
> Always run as X11 app even under Wayland

- Source/Core/Core/Core.cpp
This was causing the FifoCI runners to crash, as the Wiimotes were not initialized in the first place.
The whole `g_wiimote_sources` setup seems kinda janky in the first place...
> Core: Only reset wiimotes in Wii mode

- Source/Core/Common/Network.cpp
- Source/Core/Common/Network.h
This function only ever reads the contents of the string in a non-owning manner, so we can change the parameter over to being a string view.
> Common/Network: Make StringToMacAddress use a string_view 

- Source/Core/VideoBackends/D3D/VertexManager.cpp
- Source/Core/VideoBackends/D3D12/VertexManager.cpp
- Source/Core/VideoBackends/OGL/Render.cpp
- Source/Core/VideoBackends/OGL/VertexManager.cpp
- Source/Core/VideoBackends/Software/SWVertexLoader.cpp
- Source/Core/VideoBackends/Vulkan/VertexManager.cpp
- Source/Core/VideoCommon/IndexGenerator.cpp
- Source/Core/VideoCommon/IndexGenerator.h
- Source/Core/VideoCommon/VertexLoaderManager.cpp
- Source/Core/VideoCommon/VertexManagerBase.cpp
- Source/Core/VideoCommon/VertexManagerBase.h
- Source/Core/VideoCommon/VideoBackendBase.cpp
Gets rid of the global state within the index generator and makes it a proper class. This can just be a member that sits within the vertex manager base class. By deglobalizing the state of the index generator we also get rid of the wonky dual-initializing that was going on within the OpenGL backend. (e.g. Initialize would be called once during initialization for general backend initialization, and then the OpenGL backend would call it again after checking whether or not primitive restart is supported).
Since the renderer is always initialized before the vertex manager, we now only call `IndexGenerator`'s `Init()` once throughout the execution lifecycle.
> VideoCommon/IndexGenerator: Eliminate static state

- Source/Core/VideoBackends/Software/SWRenderer.cpp
- Source/Core/VideoBackends/Software/Tev.cpp
- Source/Core/VideoCommon/BPStructs.cpp
- Source/Core/VideoCommon/BoundingBox.cpp
- Source/Core/VideoCommon/BoundingBox.h
- Source/Core/VideoCommon/PixelEngine.cpp
- Source/Core/VideoCommon/PixelShaderGen.cpp
- Source/Core/VideoCommon/VertexManagerBase.cpp
Rather than exposing the bounding box members directly, we can instead provide an interface for code to use. This makes it nicer to transition off of global data, as the interface function names are already in place when the stateful class is introduced, meaning only `BoundingBox::` generally needs to be replaced.
With this, we now also have a place for both the disabling of bounding box itself, but also a single location for notifying the pixel shader manager when bounding box is disabled or enabled.
> VideoCommon/BoundingBox: Make interface for querying bounding box data

- Source/Core/VideoCommon/BPStructs.cpp
- Source/Core/VideoCommon/OpcodeDecoding.cpp
- Source/Core/VideoCommon/OpcodeDecoding.h
- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/TextureCacheBase.cpp
- Source/Core/VideoCommon/VideoCommon.h
Performs a bit of clean-up to the opcode decoder and removes some usages of goto so that if constexpr can be leveraged in some code paths. Each commit should be relatively isolated from one another.
> VideoCommon/OpcodeDecoding: Make use of if constexpr 

- Source/Core/VideoCommon/FramebufferShaderGen.cpp
- Source/Core/VideoCommon/FramebufferShaderGen.h
Cleans up the framebuffer shader generator code in various ways, mostly by collapsing unnecessary repeated string literal insertions into string streams; making for a nicer transition over to fmt.
While in the same area, we can also:
- Make use of `std::string_view` to enforce the use of valid strings.
- Add missing initial source file comments.
- Remove an unused Config struct.
This isn't intended to perform any behavioral changes.
> VideoCommon/FramebufferShaderGen: Minor clean up

- Source/Core/VideoCommon/ShaderGenCommon.h
- Source/Core/VideoCommon/TextureConverterShaderGen.cpp
Begins the conversion of the shader generators over to using fmt formatting specifiers, starting with the easiest one.
This introduces the `WriteFmt` function as a transitional API until all of them are converted over, where the name will be changed back to `Write`
This also has a benefit over the older StringFromFormat-based API in that all formatted data is appended to the existing buffer rather than creating a completely separate string and then appending it to the internal string buffer.
> VideoCommon/TextureConverterShaderGen: Convert over to fmt

- Source/Core/DiscIO/DiscScrubber.cpp
Unlike what my past self apparently thought, `%` is in fact not the "round down" operator.
https://bugs.dolphin-emu.org/issues/11906
> Fix scrubbing unencrypted Wii disc images (for real this time)

- Source/Core/VideoBackends/D3D12/VertexManager.cpp
- Source/Core/VideoBackends/Vulkan/VertexManager.cpp
Apparently we weren't calling the base initialize method.. this was probably my mistake, and just exposed by #8512.
> Fix Vulkan and D3D12 video backends crashing on boot

- Source/Core/DolphinQt/CMakeLists.txt
Got error after successful build using CMake on Mac OSX High Sierra. Qt5 was installed using Qt Online Installer for macOS.
The error message when running Dolphin:
```
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
Available platform plugins are: cocoa.
After inspecting with otool the problem was the **@rpath** or
`LC_RPATH` which not set on the Dolphin executable (target **dolphin-emu**) which needed by `libqcocoa.dylib`.
> DolphinQt: Fix qt.qpa.plugin on MacOS

- Source/Core/Core/Core.cpp
This was causing a race which was crashing the FifoCI runners. The main thread called Stop() which in turn called ResetAllWiimotes() while the emu thread was still exiting, also shutting down the Wiimote class.
By shifting the reset to the emu thread, all cleanup operations happen on the same thread where they were initialized.
The whole startup/shutdown situation is not an ideal design anyway (e.g. the `join()` in `Start()`...). But at least this fixes the "random" crashes.
I'd make `Stop()` simply block until the emu thread shuts down, but if any part of the shutdown requires window messages to be pumped, as `Stop()` is called from the UI thread it'll deadlock. So probably requires some more thinking.
> Core: Reset Wiimotes/rumble/memwatcher on emu thread

- Source/Core/Core/PowerPC/PPCCache.cpp
- Source/Core/Core/PowerPC/PPCCache.h
- Source/Core/Core/State.cpp
We make use of std::array within the PPC cache code. While we're in there, we can make the initialization of two arrays constexpr and move them out of the save state data, shrinking the size of save states a little bits.
> PPCCache: Make arrays constexpr where applicable

- Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.h
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
ByteSwap can just be replaced with std::swap, and rather than use preprocessor macros for the swap functions, we can just use them directly.
> GCMemcard: Remove byteswapping functions and macros

- Source/Android/build.gradle
Android Studio recommends updating to Gradle 3.5.3
> Android: update to Gradle 3.5.3

- Source/Core/Core/PowerPC/PPCAnalyst.h
This doesn't have an implementation, so it can be removed
> PowerPC/PPCAnalyst: Remove unimplemented LogFunctionCall prototype

- Source/Core/Core/Boot/Boot.h
- Source/Core/Core/Boot/Boot_BS2Emu.cpp
See the discussion in https://bugs.dolphin-emu.org/issues/11930. (This probably doesn't really fix that issue, but it's something I thought would make sense anyway.)
> Boot: Optionally allow preserving region settings in setting.txt

- Source/Core/VideoBackends/D3D12/DXContext.h
`<array>` will no longer include `<memory>` in a future MSVC release.
> Include <memory> for std::unique_ptr in DXContext.h

- Source/Core/VideoCommon/FrameDump.cpp
This appears to cause ffmpeg to create invalid video files on output if the emulator only runs for a single frame, breaking FifoCI.
Someone with frame dumping knowledge should probably review this, but I suspect the regression started with the VI changes a little while back...
> FrameDump: Set first_frame if movie frame number <= 1

- Source/Core/Common/BitUtils.h
- Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp
- Source/Core/Core/HW/DSPHLE/UCodes/AX.h
- Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
Fixes no audio when compiled on VS2019 issue in Old_AXWii games (Wii Sports, Mario Party 8, WarioWare: Smooth Moves, probably a few others). ~~There are more undefined behaviors in AXWii code, I will address those soon.~~
Fixes https://bugs.dolphin-emu.org/issues/11781
> HW/DSPHLE: Fix struct aliasing undefined behavior in AX ucode

- Source/Core/AudioCommon/WaveFile.cpp
- Source/Core/Common/Debug/Watches.cpp
- Source/Core/Common/GL/GLExtensions/GLExtensions.cpp
- Source/Core/Common/StringUtil.cpp
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/Core/HW/SI/SI.cpp
- Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
- Source/Core/Core/IOS/USB/OH0/OH0Device.cpp
- Source/Core/Core/MemoryWatcher.cpp
- Source/Core/Core/Movie.cpp
- Source/Core/Core/PowerPC/BreakPoints.cpp
- Source/Core/Core/PowerPC/Jit64/Jit.cpp
- Source/Core/Core/PowerPC/PowerPC.cpp
- Source/Core/DiscIO/Enums.cpp
- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/InputCommon/InputConfig.cpp
- Source/Core/UICommon/ResourcePack/Manager.cpp
- Source/Core/UICommon/UICommon.cpp
- Source/Core/VideoBackends/D3D12/StreamBuffer.cpp
- Source/Core/VideoBackends/OGL/Render.cpp
- Source/Core/VideoBackends/Vulkan/StreamBuffer.cpp
- Source/Core/VideoCommon/PostProcessing.cpp
- Source/Core/VideoCommon/TextureConversionShader.cpp
- Source/Core/VideoCommon/VertexManagerBase.cpp
This PR has a few optimizations to reduce the total code size of the Dolphin emulator:
* VolumeVerifier.cpp: Use arrays of C strings for the disc IDs instead of unordered_map<string>. For small lists, use a linear search; for larger lists, use std::binary_search().
* CBoot::SetupWiiMemory(): Reworked `struct RegionSetting` to use C strings.
* PowerPC.cpp: Don't explicitly initialize ppcState. Explicit initialization results in ~4 MB of zeroes being added to the .data section. Without explicit initialization, this turns into an entry in the .bss section, which saves space on disk. The effective result is the same, since .bss entries are zeroed on load.
* GetSysMenuVersionString(): Use a char instead of std::string for the region letter.
* OGL/Render.cpp: Use C string functions and get rid …
> Various string and other optimizations

- Source/Core/Common/GL/GLInterface/AGL.mm
Hello, everybody.  First time here.
I discovered Dolphin today and tried out the development build on Catalina.  It didn't work too well with a bunch of hanging, so I built it up and pulled in #8530 to fix some of the chronic hangs and non-responsive controllers.
After configuring my controllers, selecting a ROM immediately led to this crash in AttachContextToView:
```
Process:               Dolphin [78328]
Path:                  /Users/USER/*/Dolphin.app/Contents/MacOS/Dolphin
Identifier:            org.dolphin-emu.dolphin
Version:               5.0-11422 (5.0)
Code Type:             X86-64 (Native)
Parent Process:        zsh [12794]
Responsible:           Terminal [2118]
User ID:               501
Date/Time:             2020-01-01 21:26:09.146 -0500
OS Version:            Mac OS X …
```
> MacOS: Dispatch GL calls to main thread to prevent crashes on Catalina

- Source/Core/Core/GeckoCodeConfig.cpp
A `std::string` is constructed from a `vector<u8>` data pointer casted to `char*`. This assumes the data is null terminated which is probably not the case.
Potential out-of-bounds access is fixed.
I looked at our other usages of `Common::HttpRequest` and they seem correct unlike this one.
> Core/GeckoCode: Fix DownloadCodes function assuming HTTP data is null terminated.

- Source/Core/Core/HW/GCKeyboardEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Now that input expressions support numeric literals some of our default mappings result in always pressed buttons when the device is changed from the default keyboard without clearing mappings.
e.g. The Wii Remote default mapping for "1" was `1`. This expression binds to an input called "1" so long as it exists. When this input doesn't exist it is evaluated as a literal value of 1, which is problematic.
This adds backticks to these default mappings to force interpretation as input names and prevent the problem.
> HW: Add ticks to default mappings that are valid numeric literals.

- Source/Core/Common/Config/Config.cpp
- Source/Core/Core/BootManager.cpp
- Source/Core/Core/HW/AddressSpace.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp
- Source/Core/Core/IOS/USB/USB_KBD.cpp
- Source/Core/DiscIO/Blob.h
- Source/Core/DiscIO/DirectoryBlob.cpp
- Source/Core/DiscIO/Volume.h
- Source/Core/DiscIO/VolumeVerifier.cpp
A small, nonexhaustive set of warning fixes. The DiscIO Volume change
is a workaround for a GCC bug [1] that causes returning an unengaged
std::optional to emit annoying -Wmaybe-uninitialized warnings.
This last change alone fixes pages upon pages of warnings since
Volume.h is included from several files.
-Wstringop-truncation is another irrelevant warning for us, but
unfortunately there seems to be no way to disable it without
adding ugly pragmas wherever the warning appears.
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635
> Fix several warnings

- Source/Core/Common/StringUtil.cpp
- Source/Core/Common/StringUtil.h
This should fix: https://bugs.dolphin-emu.org/issues/11899
(floats fail to parse on locales with non-dot decimal separators)
I also noticed signed integer and enum types were being handled by the overload intended for floats so I generalized the integer version of `TryParse`.
> StringUtil: Make TryParse of floats handle comma and dot decimal separators.

- Source/Core/Core/IOS/ES/ES.cpp
The ES sysmodule in IOS62 (v6430) has an exception for the
Wii U Transfer Tool in the SetUid function.
If the active title is the Wii U Transfer Tool, then calling SetUid
is always allowed. (The UID is still checked first, though.)
Fixes https://bugs.dolphin-emu.org/issues/10985
> IOS/ES: Add SetUid exception for the Wii U Transfer Tool

- Source/Core/Common/x64Emitter.cpp
- Source/UnitTests/Common/x64EmitterTest.cpp
Expands what we did in #7414 so it works for 32-bit immediates as well. We can emit a shorter 32-bit instruction for 32-bit immediates in [0, 0x7FFFFFFF]. 
We hit this in [cmpXX](https://github.com/dolphin-emu/dolphin/blob/2abe333ce94f63971cbee8ea51b22d1df4456ad4/Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp#L565), and possibly some other places too.
Before:
```
0:  48 c7 c0 ff ff ff 7f    mov    rax,0x7fffffff
```
After:
```
0:  b8 ff ff ff 7f          mov    eax,0x7fffffff
```
> x64Emitter: Emit shorter MOVs for 32-bit immediates

- Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
* Avoid `LEA` when one of the source registers matches the destination (a simple `ADD` will do in those cases).
Before:
```
45 8D 6C 35 00       lea         r13d,[r13+rsi]
```
After:
```
44 03 EE             add         r13d,esi
```
---
* Use `LEA` with displacement to handle immediate values.
Before:
```
44 8B EE             mov         r13d,esi
41 83 C5 20          add         r13d,20h
```
After:
```
44 8D 6E 20          lea         r13d,[rsi+20h]
```
> Jit64: addx optimizations

- Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
Was checking over this old code, and saw a comment calling me out for a lack of documentation.
It might be half a decade late, but better late then never.
> Document the evdev "interesting" heuristic

- .editorconfig
Follow up to #5541. [Fixed in 15.3](https://developercommunity.visualstudio.com/solutions/93089/view.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dolphin-emu/dolphin/6152)
> Enforce UTF-8 now that VS handles it sanely

- CMakeLists.txt
- Readme.md
- Source/Core/Common/Config/Config.cpp
Removed conditional use of std::mutex instead of std::shared_mutex on MacOS.
Because MacOS < 10.12 did not support std::shared_mutex, a previous commit
naïvely substituted std::mutex, which does not have the same behavior.
Reverses PR #8273, which substitues std::mutex for std::shared_mutex on
macOS, and results in several bugs that seem to only affect MacOS
- https://bugs.dolphin-emu.org/issues/11919
- https://bugs.dolphin-emu.org/issues/11842
- https://bugs.dolphin-emu.org/issues/11845
This change eliminates conditional code for MacOS in the core configuration
layer code and enables the use of modern language features that are more
secure and thread-safe.
> MacOS: Fixes configuration hang; bump MacOS SDK.

- Source/Core/Common/BitUtils.h
- Source/Core/Common/ChunkFile.h
- Source/Core/Core/Analytics.cpp
- Source/Core/Core/Analytics.h
- Source/Core/Core/Boot/Boot.cpp
- Source/Core/Core/Boot/Boot.h
- Source/Core/Core/Boot/Boot_BS2Emu.cpp
- Source/Core/Core/HW/DVD/DVDInterface.cpp
- Source/Core/Core/HW/DVD/DVDInterface.h
- Source/Core/Core/HW/DVD/DVDThread.cpp
- Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp
- Source/Core/Core/HW/EXI/EXI_DeviceIPL.h
- Source/Core/Core/HW/WII_IPC.cpp
- Source/Core/Core/HW/WII_IPC.h
- Source/Core/Core/HW/WiimoteEmu/Camera.cpp
- Source/Core/Core/IOS/DI/DI.cpp
- Source/Core/Core/IOS/DI/DI.h
- Source/Core/Core/IOS/IOS.cpp
- Source/Core/Core/State.cpp
- Source/Core/DolphinQt/MainWindow.cpp
An early draft of my improved DI work.  I still need to do some testing (and write automated hardware tests), but there [is documentation](https://wiibrew.org/wiki//dev/di) of what I've figured out so far.
The GPIO change fixes [bug 11818](https://bugs.dolphin-emu.org/issues/11818) (not DI related) and also implements GPIO-based ejection (which is used by the system menu when booting from the eject button in conjunction with the RTC flag; I don't think any games use it though.)
The RTC change should fix [bug 8115](https://bugs.dolphin-emu.org/issues/8115) (including the case when a channel other than the system menu is running which I reported as [bug 11803](https://bugs.dolphin-emu.org/issues/8115)).  Note that the trade-off is that currently, it *always* acts like the disc has changed …
> Various DI improvements

- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h
- Source/Core/DolphinQt/CMakeLists.txt
- Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingWindow.h
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtension.cpp
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtensionMotionInput.cpp
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtensionMotionInput.h
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtensionMotionSimulation.cpp
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuExtensionMotionSimulation.h
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuGeneral.cpp
- Source/Core/DolphinQt/DolphinQt.vcxproj
After discussions we ended up with the following UI layout. When (and only when) Nunchuk is selected as extension, two extra tabs appear: 'Extension Motion Simulation' and 'Extension Motion Input'.
The UI layout was slightly adjusted to allow fitting five control groups on a 1024 pixel wide screen.
Added the same warning text and `Alternate Input Sources` button as on the `Motion Input` tab.
> Add motion input support to nunchuk

- Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
- Source/Core/InputCommon/ControllerInterface/evdev/evdev.h
Unfortunately newer Linux drivers for DS4 (Playstation 4) controllers split the device into three separate event nodes.
On my system I get:
"Sony Interactive Entertainment Wireless Controller"
"Sony Interactive Entertainment Wireless Controller Touchpad"
"Sony Interactive Entertainment Wireless Controller Motion Sensors"
Apparently this is due to some evdev policy: "A device must not mix regular directional axes and accelerometer axes on the same event node."
Our input system does allow use of multiple devices via "All Devices" or so-called "absolute path" control expressions, but this is less than desirable especially when making use of multiple DS4s.
This PR combines evdev devices that return the same non-null unique ID (via libevdev_get_uniq).
Mapping of DS4 acceleration, gyroscope, …
> ControllerInterface: Combine evdev devices with the same unique ID.

- Source/Core/InputCommon/ControllerInterface/Device.h
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
Tested with an Android DSU Server.
I've named the input "Battery". It should be visible in the "Advanced" mapping dialog.
If someone prefers "Battery Level" or something else I don't have a strong opinion.
This is mainly intended to be used with PR #8417 to pass-through the battery level to an emulated Wii remote.
> ControllerInterface: Exposse DSU client battery level as an input.

- Source/Core/Core/HW/Memmap.cpp
- Source/Core/Core/HW/Memmap.h
- Source/Core/Core/PowerPC/Jit64/Jit.cpp
- Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
- Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
- Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
- Source/Core/Core/PowerPC/JitCommon/JitBase.cpp
- Source/Core/Core/PowerPC/JitCommon/JitBase.h
- Source/Core/Core/PowerPC/MMU.cpp
This pull request splits the fastmem arena construction out of the memory mapper. So for the generic emulation, we won't allocate the huge junk of virtual memory.
However the JIT now creates them the fastmem arena if needed. So with disabled fastmem, we won't allocate it any more.
> Core/HW -> PowerPC/JIT: Fastmem arena construction

- Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
When opening the dialog with extension set to "None" the tabs were incorrectly shown.
The tabs should only be shown when "Nunchuk" is selected (which triggers an event that unhides the tabs).
> DolphinQt: Properly hide Wii remote extension motion tabs when no extension is selected.

- Source/Core/Core/IOS/DI/DI.cpp
- Source/Core/Core/IOS/MIOS.cpp
This should the problem with launching Gamecube games from the Wii menu (through MIOS) that @Miksel12 mentioned on #8394.
My mistake was that `IOS::HLE::GetIOS()` can be empty, and is when launching with MIOS.  This was obscured by the existing checks, which assumed that `IOS::HLE::GetIOS()->GetDeviceByName("/dev/di")` could fail, but only with `GetDeviceByName` returning nothing.  As noted in the (existing!) comment about that behavior, it is hit from `UpdateRunningGameMetadata`, which MIOS calls:
https://github.com/dolphin-emu/dolphin/blob/9596fe75f12b9199057e357dc6ae78f150b1981f/Source/Core/Core/IOS/MIOS.cpp#L85
What tricked me was that `UpdateRunningGameMetadata` is not hit when launching Gamecube games directly (which might be a bug, perhaps explaining [issue …
> DI MIOS crash fixes

- Source/Core/Core/HW/DVD/DVDInterface.cpp
- Source/Core/Core/HW/DVD/DVDThread.cpp
This is an alternative to PR #8557 and PR #8558. The way this PR solves the problem is essentially the same as what we had before PR #8394 (except the code we had back then only worked because it was broken).
> Fix Error #001 (alternative solution)

- Source/Core/Core/SysConf.h
- Source/Core/DolphinQt/Settings/WiiPane.cpp
Big-endian values were not converted and the wrong limits were set in the UI.
> Core/DolphinQt: Fix IR Sensitivity slider.

- Data/Sys/GameSettings/RZL.ini
The main menu requires safe texture cache or some letters will look scrambled.
> GameSettings: fix Cook Wars main menu

- Source/Core/Common/Matrix.cpp
- Source/Core/Common/Matrix.h
- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/Core/HW/WiimoteEmu/Dynamics.h
- Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Replaced IMU cursor's hacky Euler angle math with 3x3 matrices.
- Enabled "Recenter" button for both yaw and pitch adjustment (previously just yaw was done).
- Added a couple of matrix functions and other minor cleanups.
Pointing now behaves when the controller is in odd orientations (e.g. tilted, sideways, upside-down).
There are fewer branches and special cases in the math and I think it's more readable.
> WiimoteEmu: IMU pointing behavior improvements and code cleanup.

- Source/Core/DiscIO/Blob.cpp
- Source/Core/DiscIO/CISOBlob.cpp
- Source/Core/DiscIO/DirectoryBlob.cpp
- Source/Core/DiscIO/WbfsBlob.cpp
Fixes the same problem as PR #8557 but for other formats. (No hacks this time!)
> DiscIO: Add out of bounds checks for blob reading

- Source/Core/Common/StringUtil.cpp
- Source/Core/Common/StringUtil.h
- Source/Core/Core/Core.cpp
- Source/Core/Core/IOS/ES/Formats.cpp
- Source/Core/Core/IOS/USB/USBV4.cpp
- Source/Core/DiscIO/VolumeWad.cpp
- Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
Add a function that safely returns whether a character is printable
i.e. whether 0x20 <= c <= 0x7e is true.
This is done in several places in our codebase and it's easy to run
into undefined behaviour if the C version defined in <cctype>
is used instead of this one, since its behaviour is undefined
if the character is not representable as an unsigned char.
This fixes UB in MemoryViewWidget which didn't cast the character value to `unsigned char`.
Split from #8539 since this change is not directly related to that PR.
> StringUtil: Add IsPrintableCharacter and use it (and fix UB in MemoryViewWidget)

- Source/Core/DolphinQt/CMakeLists.txt
While I was trying to compile the CMake project in VS2019, I spotted a mistake where if ARM64 configuration was chosen, the Intel path would be used instead of ARM64. I realise the section `if(NOT Qt5DIR AND MSVC)` may not be needed, it certainly wasn't evaulated true (because Qt5DIR was already defined by this point) when I ran CMake generation.
> Update Qt5_DIR path for ARM64 in CMake project

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/res/values/strings.xml
- Source/Core/Core/Config/GraphicsSettings.cpp
- Source/Core/Core/Config/GraphicsSettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/DolphinQt/Config/Graphics/HacksWidget.cpp
- Source/Core/DolphinQt/Config/Graphics/HacksWidget.h
- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/VideoConfig.cpp
- Source/Core/VideoCommon/VideoConfig.h
Currently, we do not display every second frame in 25fps/30fps games which run to vsync. This improves performance as there's less rendering for the GPU to perform, but when combined with vsync, could cause frame pacing issues.
This commit adds an option to force every frame generated by the console to be displayed to the host, which may improve pacing for these games.
> Add an option to present duplicate frames

- Readme.md
Qt no longer supports Vista.
https://doc.qt.io/qt-5.12/windows.html
Dolphin fails to run on Vista.
https://bugs.dolphin-emu.org/issues/11961
> Update Readme.md to remove mention of Vista.

- Source/Core/DiscIO/CISOBlob.cpp
Fixes being unable to run CISO games after the merge of PR #8558.
> DiscIO: Fix CISOFileReader::GetDataSize()

- Source/Core/DolphinQt/RenderWidget.cpp
We want the game displayed at its actual resolution, not a scaled resolution. Fixes https://bugs.dolphin-emu.org/issues/11861
> Qt/RenderWidget: Account for devicePixelRatio when auto-adjusting window size

- Source/Core/VideoCommon/ShaderCache.cpp
- Source/Core/VideoCommon/TextureConversionShader.cpp
- Source/Core/VideoCommon/TextureConversionShader.h
Previously the shader generation used a global text buffer to contain the generated text and then returned a pointer into the buffer. This was what a few of the other shader generators used to do until `ShaderCode` was introduced.
We can convert this over to use `ShaderCode` to make it consistent with the other generators and then convert it over to making use of the fmt-capable `WriteFmt`. I've done this in two parts to make it easier to review the initial conversion over to `ShaderCode` and the subsequent conversion over to making use of fmt.
> VideoCommon/TextureConversionShader: Convert over to using ShaderCode 

- Source/Core/VideoBackends/D3DCommon/Shader.cpp
- Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp
- Source/Core/VideoBackends/Vulkan/ShaderCompiler.cpp
- Source/Core/VideoCommon/VideoBackendBase.cpp
- Source/Core/VideoCommon/VideoBackendBase.h
Implements https://bugs.dolphin-emu.org/issues/9992
This makes it easier to quickly identify what version of Dolphin and video backend produced shader compilation issues.
> Add Dolphin version and current video backend to shader compilation logs

- Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
- Source/Core/Core/PowerPC/Jit64/Jit_LoadStoreFloating.cpp
- Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
- Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
- Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.h
- Source/Core/Core/PowerPC/JitCommon/JitAsmCommon.h
- Source/UnitTests/Core/CMakeLists.txt
- Source/UnitTests/Core/PowerPC/Jit64Common/ConvertDoubleToSingle.cpp
Apologies, @booto, there were bugs in the assembly I hastily wrote in #8111.
Decided to write a unit-test to test the generated code to ensure correctness.
Also decided to add ee0b678 to use the (obvious?) BMI2 instruction.
> Jit64: Make DoubleToSingle a common asm routine

- Source/Core/Common/x64Emitter.cpp
- Source/Core/Common/x64Emitter.h
- Source/UnitTests/Common/x64EmitterTest.cpp
Due to the way the ModRM encoding works on x86, memory addressing combinations involving RBP or R13 need an additional byte for an 8-bit displacement of zero.
However, this was also applied in cases where it is unnecessary, effectively wasting a byte.
This PR adds some tests, fixes the issue, refactors the relevant function, and cleans up some unrelated minor things in the neighborhood.
- MatR with RSP or R12
```
8B 44 24 00          mov         eax,dword ptr [rsp]
8B 04 24             mov         eax,dword ptr [rsp]
```
- MRegSum with base != RBP or R13
```
46 8D 7C 37 00       lea         r15d,[rdi+r14]
46 8D 3C 37          lea         r15d,[rdi+r14]
```
- MComplex without offset
```
8B 4C CA 00          mov         ecx,dword ptr [rdx+rcx*8]
8B 0C CA             mov         ecx,dword …
```
> x64Emitter: Avoid 8-bit displacement when possible

- Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
- Source/Core/InputCommon/ControllerInterface/ControllerInterface.h
- Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp
- Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.h
- Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.h
- Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm
- Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
- Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h
- Source/Core/VideoCommon/RenderBase.cpp
This adjusts ControllerInterface's mouse cursor inputs to the region of the render window actually being used.
Previously, the mouse cursor and in-game pointer diverged with any letterboxing/pillarboxing.
Adjustments to "Total Yaw" and "Total Pitch" could be used to compensate but that is no longer necessary.
Before: https://i.imgur.com/2Lb8MOt.png
After: https://i.imgur.com/K7PfLKn.png
> InputCommon: Make "Cursor" inputs aware of the rendered aspect ratio.

- Source/Core/Common/IniFile.cpp
- Source/Core/Common/IniFile.h
- Source/Core/Core/IOS/ES/Formats.cpp
- Source/Core/Core/IOS/ES/Formats.h
- Source/Core/Core/SysConf.cpp
- Source/Core/Core/SysConf.h
I found a few functions with overloads for both `const T&` and `T&&` parameters intending to take ownership either by-copy or by-move.
These functions can pass `T` by-value and `std::move` within the function body to handle both situations with one implementation.
> Common/Core: Minor rvalue reference related cleanups.

- Source/Core/VideoCommon/OnScreenDisplay.cpp
When OSD messages were disabled message handling was completely skipped and `s_messages` filled up indefinitely.
Now timeouts are still processed and only the actual drawing is skipped.
> VideoCommon/OSD: Process OSD messages even when they are disabled.

- Source/Core/Core/IOS/ES/NandUtils.cpp
- Source/Core/Core/IOS/FS/FileSystem.cpp
- Source/Core/Core/IOS/FS/FileSystem.h
- Source/Core/Core/IOS/FS/FileSystemProxy.cpp
- Source/Core/Core/IOS/FS/HostBackend/FS.cpp
- Source/Core/Core/IOS/FS/HostBackend/FS.h
- Source/Core/Core/NetPlayClient.cpp
- Source/Core/Core/WiiRoot.cpp
- Source/UnitTests/Core/IOS/FS/FileSystemTest.cpp
- Tools/print-fs-fst.py
Some official titles rely on implementation details of Nintendo's FS sysmodule and will not work properly if those are changed. Notably, some games and older versions of the System Menu appear to be relying on the order of files returned by FS::ReadDirectory and will either fail to find their save data (for [Bolt](https://wiki.dolphin-emu.org/index.php?title=Bolt)) or outright crash (for the [System Menu](https://wiki.dolphin-emu.org/index.php?title=Wii_Menu)).
Some titles also actually expect filesystem metadata to be correct. One title that has been confirmed to do this is [DQX](https://wiki.dolphin-emu.org/index.php?title=Dragon_Quest_X), which generates paths based on the GID of files within its own title directory.
While it is easy to make workarounds for these issues -- and in fact …
> IOS/FS: Reimplement many functions in a more accurate way

- Source/Core/Core/HW/WiimoteEmu/Extension/Classic.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Classic.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h
Nunchuk and Classic Controller calibration hold values imposed by the stick "gate" on real hardware.
We incorrectly provided the full range beyond the stick gate.
The Classic Controller's trigger calibration is the neutral value to 8 bits of precision, not the maximum value.
These changes are probably mostly unnoticeable. Games seem to mostly ignore the calibration data.
> WiimoteEmu: Nunchuk and Classic Controller calibration accuracy improvements.

- Source/Core/Core/BootManager.cpp
- Source/Core/Core/HW/Wiimote.cpp
- Source/Core/Core/HW/Wiimote.h
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
- Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp
- Source/Core/Core/Movie.cpp
- Source/Core/Core/NetPlayClient.cpp
- Source/Core/DolphinQt/Config/ControllersWindow.cpp
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/UICommon/UICommon.cpp
Replaced wide usages of `g_wiimote_sources` with get/set functions.
Made the unnamed enum type an enum class, `WiimoteSource`.
Connected real Wii remotes are now added to a "pool" when no open slot is available.
Wii remotes in the pool have LEDs 1 and 4 lit to make it apparent they are not active.
They are disconnected per normal after 5 seconds.
This allows reassigning sources and reordering remotes without the hassle of Bluetooth re-connections.
This is mainly in preparation for Wii remotes in controller interface.
My plan is an option on the Wii remote dialog, "Connect Wii Remotes for input configuration" (or something with a better name).
Enabling it will first fill any "Real" slots but additional remotes will be sent to controller interface.
Disabling the option will send spurious …
> Core/WiimoteReal: Wii remote connection pool and source change cleanup.

- Source/Core/DolphinQt/TAS/TASCheckBox.cpp
- Source/Core/DolphinQt/TAS/TASCheckBox.h
This doesn't actually modify the checkbox's state, so this can be marked as a const-qualified member function.
> DolphinQt/TASCheckBox: Mark GetValue() as const

- Source/Core/Common/CPUDetect.h
- Source/Core/Common/x64CPUDetect.cpp
- Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
- Source/Core/VideoCommon/VertexLoaderX64.cpp
For some unknown reason PDEP and PEXT are ridiculously slow on AMD Zen architecture, which is making DoubleToSingle an extremely costly operation on these CPUs, enough to cause severe slowdown in games. Unsure whether the usage in VertexLoaderX64 had any noticeable impact, but it's also been changed as a precautionary measure.
This should fix https://bugs.dolphin-emu.org/issues/11964
> Avoid using PDEP and PEXT on AMD Zen

- Source/Core/DolphinQt/Config/GameConfigEdit.h
- Source/Core/DolphinQt/Config/GameConfigWidget.h
- Source/Core/DolphinQt/MainWindow.h
- Source/Core/DolphinQt/NetPlay/NetPlayDialog.h
Removes three unimplemented function prototypes and also surrounds `OnSignal()` within MainWindow with a relevant ifdef (like its implementation is), so that it's not mistakenly considered an unimplemented function prototype on Windows.
> DolphinQt: Remove unimplemented function prototypes

- Source/Core/DolphinQt/GCMemcardManager.cpp
This is a string that can potentially be seen by a user, so it should be marked as translatable like the other strings are.
While we're in the same area, we can also make use of `QLatin1Char` instead of `QStringLiteral` in the following `join()` call. It provides the same behavior, but without the need for program-lifetime QString data.
> DolphinQt/GCMemcardManager: Mark string as translatable within GetErrorMessagesForErrorCode()

- Source/Core/Core/WiiRoot.cpp
Fixes a regression from #8539.
CreateDirectory was the correct function to use for creating
directories since parent directories already exist.
While using CreateFullPath would have worked, that currently fails because parent directories are not owned by the system menu. I will fix CreateFullPath to handle that case in a few hours, but for now this PR fixes the most urgent issue.
> WiiRoot: Fix CopySysmenuFilesToFS directory creation

- Source/Android/app/src/main/res/values/strings.xml
What the title says. Noticed this when fixing the Vulkan performance regression. My mistake when adding the skip duplicate frames option.
> Android: Fix typo in Skip Presenting Duplicate Frames setting name

- Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp
- Source/Core/VideoBackends/Vulkan/Renderer.cpp
Android 10 seems to expect a prerotated/transformed swap chain for optimal presentation. For now, until we implement that, just ignore the hint.
See: https://twitter.com/Themaister/status/1207062674011574273
This was causing us to recreate the swap chain every frame, with an identity pretransform which would return suboptimal for the next presentation, repeat. Hence performance loss, since it's not cheap. I'm surprised the hit wasn't higher to be honest.
Fixes https://bugs.dolphin-emu.org/issues/11946
> Vulkan: Treat VK_SUBOPTIMAL_KHR as VK_SUCCESS on Android

- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPProto.h
Eliminate `m_accl`/`m_gyro` members by accessing the pad data directly like every other input.
> ControllerInterface/DSUClient: Minor cleanup.

- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
I forgot to include this in PR #8568.
> WiimoteEmu: Fix default IMU accelerometer mappings.

- Source/Core/Core/Analytics.cpp
- Source/Core/Core/Analytics.h
- Source/Core/Core/IOS/DI/DI.cpp
- Source/Core/Core/IOS/DI/DI.h
This is a correction to some changes in #8394.  In it, I added `DVDLowUnmaskCoverInterrupt = 0x85` and `DVDLowEnableCoverInterrupt = 0x89` (marking 0x89 as an unconfirmed name).  After more investigation, I've decided that 0x85 is actually `DVDLowMaskCoverInterrupt`, while 0x89 is `DVDLowUnmaskCoverInterrupt` and the previously-unimplemented (as the actual implementation does nothing) 0x87 is `DVDLowUnmaskStatusInterrupts`.  Note that all of those commands are, as far as I can tell, dummied out on the PPC side to always return 1.  As such, I've also made use of those commands be reported as a game quirk.
-----
To explain how I made this mistake, first note that most of my research was based on symbols for the US version of [Kirby's Dream …
> Fix DI interrupt mask ioctl names

- Source/Core/Core/IOS/FS/FileSystem.cpp
- Source/UnitTests/Core/IOS/FS/FileSystemTest.cpp
Follow up to #8593.
This fixes CreateFullPath to not create directories when it is known
that they already exist, instead of calling CreateDirectory anyway
and checking if the error is AlreadyExists. (That doesn't work
now that we have an accurate implementation of CreateDirectory
that performs permission checks before checking for existence.)
I'm not sure what I was thinking when I wrote that function.
Also adds some tests for CreateFullPath.
> IOS/FS: Fix CreateFullPath to not create directories that already exist

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/res/values/strings.xml
- Source/Core/Core/ConfigManager.cpp
- Source/Core/Core/ConfigManager.h
- Source/Core/Core/PowerPC/Jit64/Jit.cpp
- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/MenuBar.h
This will help to disable all inter-instruction dependencies.
So android users can check if only a single instruction is broken without compiling dolphin on their own.
> Core/Jits: Adds an option to disable the register cache.

- Source/Core/Core/Config/GraphicsSettings.h
- Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
- Source/Core/DolphinQt/HotkeyScheduler.cpp
The "Decrease Depth" hotkey accidentally used `min` instead of `max` causing it drop to zero and then go negative.
The "Increase Convergence" hotkey used a different maximum value than that of our UI.
Fixes: https://bugs.dolphin-emu.org/issues/11745
> DolphinQt: Fix stereoscopy hotkeys.

- Source/Core/DolphinQt/CheatsManager.cpp
- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/DolphinQt/Config/VerifyWidget.cpp
- Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
- Source/Core/DolphinQt/Debugger/JITWidget.cpp
- Source/Core/DolphinQt/Debugger/RegisterWidget.cpp
- Source/Core/DolphinQt/Debugger/WatchWidget.cpp
- Source/Core/DolphinQt/GCMemcardManager.cpp
- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
- Source/Core/DolphinQt/ResourcePackManager.cpp
This allows tab-navigation to escape tables.
Arrow navigation within the table is still possible.
Fixes: https://bugs.dolphin-emu.org/issues/11790
See: https://stackoverflow.com/questions/46399167/how-to-move-from-a-qtablewidget-to-the-next-widget-using-the-tab-key
> DolphinQt: setTabKeyNavigation(false) on QTableWidget and QTableView.

- Source/Core/Common/MathUtil.h
- Source/Core/Core/HW/SystemTimers.cpp
- Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp
`std::abs` is the proper function.
This fixes some value truncation warnings.
> Cleanup: Use std::abs instead of abs.

- Source/CMakeLists.txt
Lets you do fun stuff like adding extra warnings + warnings as errors for Dolphin only.
Closed the original, #6137, in a momentary lapse of thinking.
> CMake: add DOLPHIN_CXX_FLAGS option

- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingNumeric.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingNumeric.h
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.h
- Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuGeneral.cpp
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuGeneral.h
- Source/Core/InputCommon/ControlReference/ControlReference.h
- Source/Core/InputCommon/ControlReference/FunctionExpression.cpp
- Source/Core/InputCommon/ControlReference/FunctionExpression.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Attachments.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Attachments.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Buttons.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ModifySettingsButton.cpp
- Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp
- Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.cpp
- Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h
I've added the ability for input expressions to be used for the values of controller settings.
This is an extension of functionality. Existing configurations remain valid.
A common use would be a button that adjusts the speed of emulated Wii Remote Tilt/Swing but the possibilities are as endless as our button mappings.
With the new `toggle()` function added in PR #7663 this provides a generic solution to the sideways/upright hotkeys and the "Relative Input Hold" mapping.
I plan on removing these in another PR with backwards compatibility by adapting them into these new "setting expressions".
Demonstration:
https://giant.gfycat.com/CompassionateAlienatedBobolink.webm
(controller icon has since been moved to the right of the spin-button text)
A button to the right of each setting opens the …
> InputCommon: Allow controller settings specified with input expresions.

- Source/Core/InputCommon/ControllerInterface/XInput/XInput.cpp
- Source/Core/InputCommon/ControllerInterface/XInput/XInput.h
Moved things that didn't need to be in the header.
Replaced c-arrays with `std::array`.
Killed some `memset`/`cmp`s.
Cleaned up some comments.
Marked classes as `final`.
> InputCommon/XInput: Expose battery as input and cleanups.

- Source/Core/DiscIO/DirectoryBlob.cpp
Someone reported a problem with DirectoryBlob at https://forums.dolphin-emu.org/Thread-feature-request-thread?pid=502820#pid502820. I'm not sure if the change in this commit actually fixes that problem, but it's something I found that should be changed regardless.
> DiscIO: Check for DirectoryBlob seek failure

- Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
- Source/Core/DolphinQt/Debugger/CodeWidget.cpp
- Source/Core/DolphinQt/Debugger/RegisterWidget.cpp
- Source/Core/DolphinQt/Debugger/WatchWidget.cpp
QDockWidget::setFloating ends up calling showEvent in the implementation class.
In BreakpointWidget and CodeWidget, this leads to Update() and a null pointer dereference on widgets that haven't been created yet. Moving the CreateWidgets call before setFloating fixes this. (JITWidget and MemoryWidget already do this.)
The rest of the widgets that call setFloating have also been updated to avoid similar bugs if they're changed in the future.
> DolphinQt/Debugger: Fix crash with floating debugger windows

- Source/Core/Core/HW/GCPadEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/InputCommon/ControlReference/ControlReference.h
- Source/Core/InputCommon/ControllerEmu/Control/Control.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Buttons.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Force.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/MixedTriggers.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ModifySettingsButton.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Slider.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Triggers.cpp
Added `GetState` function to `Control` towards allowing `control_ref` member to be private.
> InputCommon: Eliminate some duplicated button threshold logic.

- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/VolumeVerifier.h
Otherwise GetBiggestReferencedOffset might treat garbage data as a valid large offset, making Dolphin incorrectly say that the disc is too small.
> VolumeVerifier: Ignore invalid partitions in GetBiggestReferencedOffset

- Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h
Previously, battery level inputs would read as 0 when window focus was lost.
> InputCommon: Only update setting expressions when the input gate is enabled.

- Source/Core/Core/HW/GCKeyboardEmu.cpp
- Source/Core/Core/HW/GCPadEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Classic.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Drums.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Turntable.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/UDrawTablet.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/Core/HotkeyManager.cpp
- Source/Core/InputCommon/ControllerEmu/Control/Control.cpp
- Source/Core/InputCommon/ControllerEmu/Control/Control.h
- Source/Core/InputCommon/ControllerEmu/Control/Input.cpp
- Source/Core/InputCommon/ControllerEmu/Control/Input.h
- Source/Core/InputCommon/ControllerEmu/Control/Output.cpp
- Source/Core/InputCommon/ControllerEmu/Control/Output.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Force.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ModifySettingsButton.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Slider.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.cpp
Greatly simplifies creation of `Input` objects.
Eliminates `new` and `make_unique` calls all over the place.
`std::move` `std::string` arguments.
> InputCommon: Clean up creation of inputs.

- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h
Changed "dead zone" color to a transparent black or white depending on theme.
Inverted value of "gate" colors when active theme has a dark background.
Tweaked order of "shake" indicator axis colors so red is more often shown.
Indicators now look less horrible with dark themes and the dead zone is more subtle as it should be.
Before:
https://i.imgur.com/aUriQaT.png
https://i.imgur.com/aHCSYCj.png
After:
https://i.imgur.com/cWZu4IS.png
https://i.imgur.com/JR8anBW.png
> DolphinQt/Mapping: Tweak "Dead Zone" and "Gate" colors.

- Source/Core/Core/GeckoCodeConfig.cpp
Fixes https://bugs.dolphin-emu.org/issues/11809
I found on my system (Archlinux) that using a locale with UTF-8 was breaking loading of Gecko codes. Hopefully forcing the C locale on this string stream should be enough without breaking it on other systems.
> Fix Gecko codes loading

- Source/Core/Common/ScopeGuard.h
- Source/Core/Core/Core.cpp
So far in all our uses of ScopeGuard, the type of the callable is
usually just a lambda or a function pointer, so there is no need
to rely on std::function's type erasure.
While the cost of using std::function is probably negligible, it still
causes some unnecessary overhead that can be avoided by making
ScopeGuard a templated class. Thanks to class template argument
deduction in C++17 most existing usages do not even need to be changed.
See https://godbolt.org/z/KcoPni for a comparison between
a ScopeGuard that uses std::function and one that doesn't
> Common: Avoid std::function overhead in ScopeGuard

- Source/Core/DolphinQt/Main.cpp
On Windows, Qt's default system font (MS Shell Dlg 2) is outdated.
Dolphin previously used over 15 lines of code to compute a font closer to the proper font, but with an approximately correct font size. Using the QMenu font directly is both more concise and more elegant (in my opinion).
Successor to #8359.
Credit to https://stackoverflow.com/a/40380684 for discovering this method. Is it worth crediting in the source code? I think not?
> Windows GUI: Use QMenu font (Segoe UI) for entire application

- Source/Core/DolphinQt/TAS/IRWidget.cpp
- Source/Core/DolphinQt/TAS/StickWidget.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
- Use the Dolphin Icon in TAS Windows
- Prevent deformation of the stick widget (Bug #11988)
- Improve visual appearance
- Set a reasonable minimum size
**Before**:  
**After**:
> Qt/TAS: Improve TAS windows

- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/MixedTriggers.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/MixedTriggers.h
- Source/Core/InputCommon/ControllerEmu/ControllerEmu.h
- Source/Core/InputCommon/ControllerInterface/Device.cpp
Eliminate racy `UpdateInput` call within `DetectInput`.
(HotkeyManager/Core will already be doing this)
Split separate mapping indicator types into their own classes.
The "Point" indicator now uses the entire bounding box for drawing the "red dot".
The reduced box seemed to confuse some people into thinking it needed some kind of calibration.
Ensure the "state lock" is held when updating indicators.
Previously it was not held on a redraw invoked from Qt.
Cleaned up indicator code to eliminate some redundant logic and scalar multiplication all over the place.
Minor change to indicator colors for better contrast on some dark themes.
> InputCommon/DolphinQt: Mapping related race fixes and cleanups.

- Source/Core/DolphinQt/Info.plist.in
The Qt version we use now should support Dark Mode properly.
> Qt: Re-enable Dark Mode support

- Source/Core/Core/HW/WiimoteEmu/Extension/Classic.cpp
Digital button bits were not being set.
Fixes regression from #8575.
https://bugs.dolphin-emu.org/issues/11992
> HW/WiimoteEmu: Fix Classic Controller triggers.

- Source/Core/Core/ConfigManager.cpp
- Source/Core/Core/ConfigManager.h
- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/GameList/GameListModel.cpp
- Source/Core/DolphinQt/GameList/GameListModel.h
- Source/Core/DolphinQt/MenuBar.cpp
The path is generated by finding a file path that contains the filename, then removing the path to that path.
Example:
File paths: `/home/foo/games`, `/home/foo/Desktop/wii`
Game path: `/home/foo/games/gcn/ntsc/fun game.gcn`
~~File name listed: `gcn/ntsc/fun game.gcn`~~
File name listed: `games/gcn/ntsc/fun game.gcn`
`dir.lastIndexOf` uses `-2` in the case that the file path ends with a trailing slash.
Fixes https://bugs.dolphin-emu.org/issues/10567
This is my first PR to Dolphin, so a thorough review would be awesome, ~~and let me know if this would be better as its' own column instead of replacing "File name".~~
> DolphinQt: Add "File Path" column to Game Grid

- Source/Core/DolphinQt/Settings/AudioPane.cpp
This fixes the case when upon opening the Audio tab for the first time with LLE Audio selected, Dolby Pro Logic II quality slider would be enabled even if Dolby Pro Logic II itself wasn't.
> AudioPane: Do not enable DPLII quality slider if DPLII is off

- Source/Android/app/src/main/res/values/styles.xml
Fixes https://bugs.dolphin-emu.org/issues/11905
Partial revert of #7864 (@rafaeltoledo )
Before:
This PR:
> Android: Fix obscured Dolphin version

- Source/Android/jni/MainAndroid.cpp
- Source/Core/Common/WindowSystemInfo.h
- Source/Core/Core/Core.cpp
- Source/Core/DolphinNoGUI/PlatformFBDev.cpp
- Source/Core/DolphinNoGUI/PlatformHeadless.cpp
- Source/Core/DolphinNoGUI/PlatformWin32.cpp
- Source/Core/DolphinNoGUI/PlatformX11.cpp
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/RenderWidget.cpp
- Source/Core/DolphinQt/RenderWidget.h
- Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
- Source/Core/VideoBackends/Vulkan/VideoBackend.h
- Source/Core/VideoBackends/Vulkan/main.cpp
- Source/Core/VideoCommon/VideoBackendBase.h
Well, this was a fun debugging experience. At least it wasn't as borked as the last time.
Basically, the auto-fill-background stuff changing out paint engines broke on Qt 5.14. I'm swapping this out with a better method - letting the graphics backend take care of clearing the screen instead. The downside is there will be a slightly longer delay before it is cleared as the graphics API needs to initialize, but it's much cleaner code-wise.
It also now passes the layer to MoltenVK instead of the view, which prevents `[NSView layer]` from being called off the main thread. Which currently is just a warning, but with the way Apple seems to be going at some point in the future it'll probably become an error, and cause Dolphin to crash, so better safe than sorry.
... hopefully this stays working …
> Fix Vulkan/MoltenVK on macOS yet again

- Source/Core/Common/SettingsHandler.cpp
Related to bug 11930: https://bugs.dolphin-emu.org/issues/11930
The settings.txt file straight from a Wii NAND does sometimes contain one weird line ending - CR-LF-LF instead of CR-LF (0d0a0a). The current parsing code only searches for 0d0a, and doesn't find the line immediately after the broken line ending. 
This causes the bug described in issue 11930 - the serial number in the file is ignored and regenerated, until the file is re-written by Dolphin, with correct line endings. This causes problems, because it makes Dolphin regenerate the serial number when importing a NAND. 
My change makes a temporary copy of the decoded string, then removes all CR bytes from the string, leaving only LF line endings in the copy. This also replaces the broken CR-LF-LF line feed with LF-LF, making it …
> Fix settings.txt parsing in case of weird line endings

- Source/Core/Core/HW/WiimoteEmu/Camera.cpp
- Source/Core/Core/HW/WiimoteEmu/Camera.h
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Added Get/Setters. Added Comments. Renamed some variables.
Added more checks for camera being in a valid state.
Send 0xFF-filled data in more situations.
This fixes the flash of poorly positioned IR points when changing the sensor bar sensitivity in the Wii menu.
> HW/WiimoteEmu: Camera logic cleanups.

- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h
- Source/Core/InputCommon/ControllerEmu/StickGate.cpp
- Source/Core/InputCommon/ControllerEmu/StickGate.h
Because of poor math, calibration sometimes ends up being drawn outside of the mapping indicator.
Calibration values are now clamped within the square shape to prevent this.
Specify the default value when saving calibration center to prevent saving default values.
The eliminates a bunch of irrelevant entries in the ini file for extensions that aren't even configured...
> Drums/Stick/Center = 0.00 0.00
> Turntable/Stick/Center = 0.00 0.00
> uDraw/Stylus/Center = 0.00 0.00
> Drawsome/Stylus/Center = 0.00 0.00
`RoundStickGate::GetIdealCalibrationSampleCount` can return 1.
This makes swing's reshaping math use an actual circle rather than an n-gon.
Fix "Calibration" routine from always setting center value to {0,0} even on cancellation.
> InputCommon: Minor ReshapableInput related cleanups.

- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/MenuBar.cpp
There are a number of shortcuts built into Qt within the `QKeySequence` class. These have shortcuts for a number of different platforms and for Linux, respective desktop environments. This PR replaces the manually set keys with these builtins for opening, finding and quitting. It also adds a shortcut for opening the Configuration pane, using `QKeySequence::Preferences`.
> Qt: Use Builtin QKeySequence Shortcuts

- Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
- Source/Core/DolphinQt/Debugger/CodeViewWidget.h
Back in WX, the debugger would draw arrows to indicate branches, like this:
https://user-images.githubusercontent.com/4522237/75113262-83629280-564c-11ea-857e-b86459b47c08.png
https://user-images.githubusercontent.com/4522237/75113263-83629280-564c-11ea-865e-e672b01c57a6.png
I found this pretty useful at quickly determining conditionals and loops, but during the transition to Qt this feature was lost. This PR is a implementation of this feature for Qt.
Screenshots:
https://user-images.githubusercontent.com/4522237/75113260-82316580-564c-11ea-9057-bf7dc6cc169a.png
https://user-images.githubusercontent.com/4522237/75202872-eb0fff00-576c-11ea-869c-0a9ca0b208ef.png
One thing I'm not sure here is if I have to make sure `BranchDisplayDelegate::paint()` and `CodeViewWidget::Update()` don't run …
> Qt/CodeViewWidget: Implement branch arrows.

- Source/Core/VideoCommon/HiresTextures.cpp
- Source/Core/VideoCommon/HiresTextures.h
Currently, in your "Load" folder, you have a bunch of 3 letter or possibly more folders that reference some game.  Wouldn't it be nice if you instead could have a nice native language name instead?  Instead of "SLS", you could have "The Last Story".
Well now you can!
You only need to put a "SLS.txt" file in your directory and that's enough to tell Dolphin that is a directory of textures for "The Last Story".
This resolves two issues, neither were made on the issue tracker as far as I know:
* A user on the forum made a post in feature requests and they wanted the ability to have textures be read from subfolders.  They referenced a pack that might be stored on github where downloading automatically adds a subfolder.
* Admentus currently has to add multiple symlinks for his Majora's Mask / …
> VideoCommon: Allow texture folders to be determined by a <gameid>.txt

- Source/Core/Core/PowerPC/BreakPoints.cpp
- Source/Core/Core/PowerPC/BreakPoints.h
This PR fixes crash after clearing memory breakpoints by pressing Clear button.
> Breakpoints: Fix crash after clearing all memory breakpoints

- Source/Core/Core/NetPlayServer.cpp
- Source/Core/Core/NetPlayServer.h
- Source/Core/DolphinQt/MainWindow.cpp
Order of operations issue. I also made `SetupIndex` not hard dependent on `m_dialog` just in case.
> Core/NetPlayServer: Fix session not being added to index on direct connection type

- Source/Core/Core/Config/UISettings.cpp
- Source/Core/Core/Config/UISettings.h
- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
- Source/Core/Core/HW/VideoInterface.cpp
- Source/Core/DolphinQt/HotkeyScheduler.cpp
- Source/Core/DolphinQt/Settings/InterfacePane.cpp
- Source/Core/DolphinQt/Settings/InterfacePane.h
Setting is named "Hotkeys Require Window Focus".
Please give opinions on the naming in the UI+INI and whether the checked state should be enabled or disabled.
Fixes: https://bugs.dolphin-emu.org/issues/8262
> DolphinQt: Give hotkeys their own "background input" setting.

- Source/Core/DolphinQt/Config/LogWidget.cpp
Otherwise, a line that's too wide for the log widget will cause the horizontal scroll bar to appear, which reduces the vertical height, and causes the most recent line to be off screen.  Since that line is off screen, the log widget no longer scrolls as new lines appear, unless it's manually scrolled to the very bottom again.
> Always display the horizontal scroll bar when log word wrap is off

- Readme.md
Adds newer backends to readme + more positive about hle accuracy.
The command list itelf is still outdated, though.
> Readme.md Tweak Command Line section

- Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
- Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.h
- Source/Core/Core/Movie.cpp
The old code only handled a raw memory card in slot A, not taking GCI folders into account at all.
> Movie: Make checking for existing GC saves more reliable

- .gitmodules
Instead of cloning the entire history of the submodule, only fetch the latest commit. This saves about 300M of disk space currently and will only save more in the future.
**Caveats:**
* A shallow clone might be slower under some circumstances such as a very fast internet connection ([Try this test](https://gist.github.com/spycrab/41f994b015e4bf8efb64b8b2cf7e0e96))
* If you want to change anything in the Externals you will have to unshallow the clone (realistically only about 5 people ever needed to do this)
> [RFC] .gitmodules: Make Externals/Qt clone shallow

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java
This changes channel syncing to happen when the operating system is Android TV rather than when TvMainActivity is launched. (You can run TvMainActivity on a phone by specifying a launch activity manually in Android Studio, which I do sometimes for testing purposes. Without this change, you get an exception when channel syncing runs.)
I have tested this on my phone but not on Android TV.
> Android: More robust check for whether to sync channels

- Source/Core/Common/StringUtil.cpp
- Source/Core/Common/StringUtil.h
- Source/Core/Core/BootManager.cpp
- Source/Core/Core/WiiRoot.cpp
- Source/Core/Core/WiiRoot.h
- Source/Core/DolphinQt/Settings/InterfacePane.cpp
- Source/Core/UICommon/GameFile.cpp
- Source/Core/UICommon/UICommon.cpp
When booting a Wii game, Dolphin can overwrite certain settings in the SYSCONF file, such as turning off PAL60 for NTSC games. Normally, these settings get reverted at the end of emulation, but this does not happen if Dolphin crashes or force quits in some other way. (Personally, I have a tendency to use Visual Studio's Stop Debugging button, which kills the process...)
Dolphin also overwrites certain values in setting.txt when booting a Wii game. Unlike with SYSCONF, we currently make no effort to preserve the original values in this file.
This change fixes both of these problems by copying SYSCONF and setting.txt to the Backup folder when booting a Wii game, and then copying them back either when launching Dolphin (in case the previous run of Dolphin crashed) or when ending emulation.
> Back up Wii setting.txt and SYSCONF while emulating

- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
The "jitter" line which helps in configuration of the "Dead Zone" setting was broken.
A `QPainter::drawLine` overload taking `int` was inadvertently being used.
There is no four parameter overload that takes `float`.
> DolphinQt: Fix gyro mapping indicator's "jitter" drawing.

- Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
- Source/Core/Core/IOS/USB/Bluetooth/BTReal.h
This commit attempts to improve error handling for device opening by
reducing panic alert spam when opening one or several devices fails.
Currently, Dolphin shows a panic alert for every device that we fail
to open, and another panic alert at the end if no usable device was
found. That is certainly a bit excessive -- we should only keep the
very last panic alert (the one that is shown if everything fails)
and we can just put the error for the last device open operation there.
This also changes the PanicAlert to a CriticalAlert to ensure the
message is visible even if the user has disabled regular panic alerts.
The message has also been reworded and should hopefully be clearer.
> BTReal: Improve error handling for device opening

- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/MainWindow.cpp
This fixes an annoying case where installing the system menu via "Perform System Update" on a disc would fail to enable the Load Wii System Menu item in the tools menu until Dolphin is restarted.  If a system menu was already installed, then the old version would still be displayed, but the button was usable.
I also replace the call the "Perform Online Update" function uses to avoid this with a more general one.  Note that `NANDRefresh` is connected to `UpdateToolsMenu`:
https://github.com/dolphin-emu/dolphin/blob/0461170363693efec7d6a8a34baaa5fb2deb8954/Source/Core/DolphinQt/MenuBar.cpp#L265
> Fix Load Wii System Menu not updating after performing a disc update

- Source/Core/Common/IniFile.cpp
- Source/Core/Common/IniFile.h
- Source/Core/Core/HotkeyManager.cpp
For some reason every button group was shoved into the same config group called "Keys" which caused buggy behavior once someone tried to have hotkeys with the same name in different groups. This fixes that, and converts existing configs to the new group names so they don't get reset.
> Core/HotkeyManager: Fix group names in config

- Source/Android/jni/GameList/GameFile.cpp
This was probably a copypaste mistake of mine. (`env` is used as the first argument when calling `ToJString`.)
> Android/JNI: Remove odd usage of the comma operator

- Source/Core/DolphinQt/GameList/GameListModel.cpp
This is a fixup for #8580 - column now displays native separators consistently. Before the PR, on Windows paths would be displayed like:
```
C:/path/to/game\
```
Now separators are consistent.
> Qt/GameListModel: Use native separators in File Path column

- Source/Core/DolphinQt/Debugger/CodeWidget.cpp
Compare with line 67. This caused the vertical splitter state to be not restored properly when exiting and reopening Dolphin.
> Qt/CodeWidget: Typo in settings key.

- Source/Core/DiscIO/DiscExtractor.cpp
> DiscIO: cleanup warnings of -Wmaybe-uninitialized

- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
Fix build with Qt 5.15
~~~
95%] Building CXX object Source/Core/DolphinQt/CMakeFiles/dolphin-emu.dir/NetPlay/GameListDialog.cpp.o
/tmp/makepkg/sl1-dolphin-emu-git/src/dolphin-emu/Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp: En la función miembro ‘virtual void SwingIndicator::DrawUnderGate(QPainter&)’:
/tmp/makepkg/sl1-dolphin-emu-git/src/dolphin-emu/Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp:485:18: error: el agregado ‘QPainterPath path’ tiene un tipo incompleto y no se puede definir
485 |     QPainterPath path;
|                  ^~~~
~~~
> Fix build with Qt 5.15+

- Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
- Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h
Initialize m_state with the default constructor.
> InputCommon: cleanup warnings of -Wclass-memaccess

- Source/Core/DolphinQt/Config/LogWidget.cpp
moving a temporary object prevents copy elision. Remove std::move.
> Cleanup warnings of -Wpessimizing-move

- Source/Core/Common/SettingsHandler.cpp
Fixes https://bugs.dolphin-emu.org/issues/12019
Related to https://bugs.dolphin-emu.org/issues/11930 and to #8673 and #8670
The encrypted settings.txt can contain nullbytes - it's a binary file. The old code assumed a null byte means "end of file". That's not the case - for some files, the current code stops parsing in the middle of the file. (That took me a while to figure out ...)
This approach decrypts the junk data at the end of the file, too, but because the valid data always ends with a newline, all the junk ends up on new line(s) at the end, meaning, the parsing code should just ignore that junk. The decrypted data unfortunately doesn't end with a null byte, and we don't know the length of the decrypted data, so I don't see any way to detect and remove that junk data. 
Please merge …
> SettingsHandler: Always decode the whole settings.txt file

- Source/Core/DolphinQt/Main.cpp
This is so commands like `dolphin-emu --help` don't initialise Qt, which wastes memory and prints logs that shouldn't be printed
Before:
```
$ dolphin-emu --help
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Usage: dolphin-emu [options]... [FILE]...
Options:
--version             show program's version number and exit
...
-a AUDIO_EMULATION, --audio_emulation=AUDIO_EMULATION
Choose audio emulation from [HLE|LLE]
```
After:
```
$ dolphin-emu --help
Usage: dolphin-emu [options]... [FILE]...
Options:
--version             show program's version number and exit
...
-a AUDIO_EMULATION, --audio_emulation=AUDIO_EMULATION
Choose audio emulation from [HLE|LLE]
```
> Parse arguments before Qt

- Source/Android/app/build.gradle
- Source/Android/app/src/main/res/layout/activity_main.xml
- Source/Android/app/src/main/res/layout/fragment_settings.xml
- Source/Android/app/src/main/res/values-night/colors.xml
- Source/Android/app/src/main/res/values-night/styles_filepicker.xml
- Source/Android/app/src/main/res/values/styles.xml
- Source/Android/app/src/main/res/values/styles_filepicker.xml
Updated Material Components dependency and implemented System-controlled Day/Night (Light/Dark) theming
Testing notes: Dark theme can be toggled through system settings in Android 10 (Q) and higher, or through an app like [Night Mode](https://f-droid.org/en/packages/io.github.subhamtyagi.nightmode/) for earlier Android versions.
Light Mode vs Dark Mode Screenshots:
> Android: Set up Day/Night mode for system-compatible optional dark theme

- Source/Core/Core/Boot/Boot_BS2Emu.cpp
This is a part of fixing https://bugs.dolphin-emu.org/issues/11930.
PR #8672 should be merged before this one, otherwise Wiimmfi users may run into a situation where a 7-day wait isn't necessary at first but becomes necessary later after playing a game from a different region, which I think would be rather confusing for them.
EDIT: By request from @Leseratte10 (see comments below), do not merge this PR before PR #8680.
> Boot: Do a better job of preserving certain parts of settings.txt

- Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
While I am here, make g_wiimote_scanner as static as well.
> Wiimote: Cleanup warnings of -Wmissing-variable-declarations

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/CustomFilePickerActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/ConfirmRunnable.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FilePicker.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/SettingsItem.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/MenuTag.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/ConfirmRunnableViewHolder.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/FilePickerViewHolder.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/CustomFilePickerFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
- Source/Android/app/src/main/res/values/arrays.xml
- Source/Android/app/src/main/res/values/strings.xml
Implements https://bugs.dolphin-emu.org/issues/10781
- Android: Add Set as Default ISO to UI
- Android: Add Paths to UI
- Very useful for loading game mods
- Removed some unnecessary import statements
- Renamed some things now that `FilePicker` is more versatile
- Added `ConfirmRunnable` to confirm running arbitrary runnables (so they're not accidentally clicked). It will also be useful for future PRs, especially when modifying multiple settings (i.e. toggling all log types).
- Fixed a bug where `launchOpenFileActivity()` could select multiple files. We don't want to be able to load multiple games at once!
> Android: Add Paths to UI

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
This should fix #11944. But as I cannot get the gradle config in the project to cooperate with the android-sdk on my dev machine, I'm going to have to rely on the pr builder to test.
> Android: Fix ATV on API 28+

- Externals/MoltenVK/version.txt
- Source/Core/VideoBackends/Vulkan/SwapChain.cpp
- Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
- Source/Core/VideoBackends/Vulkan/VulkanEntryPoints.inl
- Source/Core/VideoBackends/Vulkan/VulkanLoader.h
- Source/Core/VideoBackends/Vulkan/main.cpp
Since we are creating the swap chain off the UI thread, we can't use anything which accesses the underlying NSView object. We create and set the Metal layer on the UI thread before the video backend is initialized. This extension is both compatible with MoltenVK and gfx-portability for accepting a layer at surface creation.
Also updates MoltenVK to the latest version since the older version probably doesn't support the new surface extension.
> Vulkan: Switch from vkCreateMacOSSurfaceMVK() to vkCreateMetalSurfaceEXT() and Update MoltenVK

- Source/Core/Core/Movie.cpp
PR #8347 made this function be called on the CPU thread.
> Remove outdated comment from Movie::FrameUpdate

- Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
https://bugs.dolphin-emu.org/issues/11920 - DSP LLE Interpreter does not have a DSP thread, so trying to wait would hang.  (DSP LLE recompiler also has no thread when in determinism mode).
> Fix bug 11920

- Source/Core/Core/IOS/USB/Host.cpp
The threads can't actually be started when determinism is enabled, as the behavior would not be deterministic, but Open() still tries to start the threads and wait, resulting in a deadlock when booting certain games and homebrew in NetPlay.
> IOS/USBHost: Skip starting threads when determinism is enabled

- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/RenderBase.h
- Source/Core/VideoCommon/VertexManagerBase.cpp
- Source/Core/VideoCommon/VertexManagerBase.h
Consider a projection "anamorphic" when the projection aspect ratio divided by the viewport aspect ratio is near 1.333... ((16/9) / (4/3))
Previously only 4:3 viewport and 16:9 projection situations were considered anamorphic.
This fixes the widescreen GeckoCode in "Gauntlet: Dark Legacy" which seems to maybe render the game to only an upper portion of the screen.
Keep separate counts for perspective and orthographic projections and compare them separately, apples to apples.
If either type of projection look overly anamorphic, go 16:9.
Otherwise, if orthographic projections were anamorphic and are now normal or perspective projections are normal, go 4:3.
This fixes Animal Crossing's inventory screen where perspective projections are temporarily not used.
It also fixes menus in SSX3 from …
> VideoCommon: Tweak widescreen heuristic.

- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.h
A checkbox has been added to the **NetPlay Session Browser** dialog, so that in-game sessions can be filtered out from the list.
> DolphinQt: Added checkbox to filter out NetPlay sessions that are already in-game.

- Source/Core/DolphinQt/GameList/GameList.cpp
Fixes the game file being locked until Dolphin closes.  The properties dialog *technically* didn't leak before this, since Qt will close it when its parent window closes, but that only happens when dolphin itself exits and that's way longer than it needs to be.  (See also: https://github.com/dolphin-emu/dolphin/pull/8088#issuecomment-491452256)
> Delete properties dialog on close

- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/ConfigManager.cpp
Enabling the SD card is useful for loading / saving data for games such as Super Smash Bros. Brawl. I assume most users won't encounter any problems with this setting enabled. Was there a reason why the default was set to false? Also, the virtual SD card is created regardless of this setting.
> Set Insert SD Card default value to true

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/res/values/strings.xml
- Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp
- Source/Core/DolphinQt/Settings/WiiPane.cpp
Implements https://bugs.dolphin-emu.org/issues/10700
Follow-up to #7920.
The path is modifiable by the user so we shouldn't mention it in the description.
> Android: Add Insert SD Card and update the description

- Source/Core/Core/HW/DVD/DVDInterface.cpp
https://bugs.dolphin-emu.org/issues/11997
The problem seemed to be that `s_DILENGTH` would get set to 0 at times when it shouldn't. Simply not changing it in case of `NoReply` or `DTK` seems to fix the problem. However, we can actually go one step further in accuracy and use `data.size()` to change `s_DIMAR` and `s_DILENGTH` as partial reads (`NoReply` commands) complete, instead of jumping directly to 0 when the whole read completes.
> Adjust s_DIMAR/s_DILENGTH behavior (fixes Baten Kaitos music)

- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
- Source/Core/Core/HW/VideoInterface.cpp
- Source/Core/VideoCommon/AsyncRequests.cpp
- Source/Core/VideoCommon/AsyncRequests.h
- Source/Core/VideoCommon/RenderBase.cpp
https://bugs.dolphin-emu.org/issues/12025
It used to be the case that frame advance skipped duplicate frames (i.e. it would take 30 frame advances to get through one second of emulated time in a 30 fps game), but this broke in PR #8347. Skipping duplicate frames making TASing less annoying.
> Core: Skip duplicate frames when using frame advance

- Source/Core/Core/Config/GraphicsSettings.cpp
- Source/Core/Core/Config/GraphicsSettings.h
- Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
This adds an ini-only setting under GFX.ini -> [Settings] -> MaxInternalResolution. Setting this will allow the user to select resolutions beyond the default 8x max scale in graphics options.
Also fixes the bug if a user had a >8xIR set, opening the graphics window would overwrite the value, and save it to the ini.
Requested by @MayImilae.
> DolphinQt: Don't overwrite >8x IR scale in ini, add maximum internal res option

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/jni/MainAndroid.cpp
Fixes https://bugs.dolphin-emu.org/issues/12043.
@JosJuice thanks for the help.
> Android: Reload Wii Remote settings upon saving them

- Source/Core/Core/IOS/FS/HostBackend/FS.cpp
On some platforms (like Windows), the temporary file must be closed
before it can be renamed.
I guess nobody noticed this for so long because (1) the FS code has a
failsafe for missing FST entries (because existing users do not have
a FST), and most games do not care about file metadata;
(2) the write failures can only be seen in the logs.
Because we don't want this to break, I have turned the ERROR_LOGs into
PanicAlerts.
> IOS/FS: Fix FST write failure on some platforms

- Source/Core/Core/Analytics.cpp
- Source/Core/Core/Analytics.h
- Source/Core/VideoCommon/VertexManagerBase.cpp
Hardware tests have shown that if the number of texgens/channels do not match, you get garbage rendering. Presumably because the output registers from the XF stage are fed into the incorrect input registers for TEV/BP.
Currently, this causes Dolphin to crash/generate invalid shaders with an assertion failure in the hardware backends. Instead, we log an error.
Perhaps in the future we should just spit out all texgens/colors anyway from both stages, and let cross-stage optimization take care of DCE'ing it away. But doing so would require changing the UIDs and invalidating everyone's shader caches.
> VertexManagerBase: Skip drawing objects with mismatched xf/bp stages

- Source/Core/Core/HLE/HLE.cpp
This PR adds 2 missing debug functions, one used by DSP and the other one by the defunct Nintendo ranking server.
These symbols can be found in symbol maps left on some game discs and in Rayman Raving Rabbids ELF file.
Ready to be reviewed & server.
> HLE: Add more debug functions

- Source/Core/Core/IOS/Network/Socket.cpp
It seems there was a network regression, I'm investigating to find the root cause of it.
Meanwhile, here is a quick fix which prevent closesocket to hang forever and instead return -1 on close.
Do not merge.
> Socket: Abort pending ops on close

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/ConfirmRunnableViewHolder.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PermissionsHandler.java
- Source/Android/app/src/main/res/values/styles.xml
Also fixes the same crash when accessing the game details (which only can be accessed after long pressing a game). The problem was that we were not using a theme that had an AppCompat theme as a parent.
After fixing the crashes, I discovered that the game details dialog unfortunately uses white on white on Android TV, and I don't know how to fix this in a clean way. But I guess that can be left for another PR?
> Android TV: Fix crash when long pressing a game

- Data/Sys/GameSettings/GK2.ini
Removed unnecessary EFBToTextureEnable=False for Spider-Man 2 from GK2.ini, as the game no longer requires it
Also removed empty config blocks
I've been testing with EFB to Texture enabled extensively for some time, and the game works just fine.
> Remove unnecessary EFB to Texture disabling for Spider-Man 2

- Source/Core/VideoCommon/VertexManagerBase.cpp
With #8717 @stenzek introduced two new quirks. However, @sebastiaangoossens noticed that the mismatched xf/bp texgens quirk was referenced twice, while the other went unused. This PR takes care of this.
> Analytics: Report correct quirk for mismatched xf/bp colors

- Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Similar to #8551. We start by deduplicating some of the existing logic so the optimizations don't have to be repeated. We then add special handling for constant 0 in several places, carefully swap operands around if it can get us shorter instructions, and use LEA for subfx too.
---
**addx - Emit nothing when possible**
Before:
```
83 C7 00             add         edi,0
```
After:
```
```
---
**addx - Emit MOV when possible**
Before:
```
41 8D 7D 00          lea         edi,[r13]
```
After:
```
41 8B FD             mov         edi,r13d
```
---
**addx - Prefer smaller MOV+ADD sequence**
Before:
```
41 BE 40 00 00 00    mov         r14d,40h
44 03 75 A8          add         r14d,dword ptr [rbp-58h]
```
After:
```
44 8B 75 A8          mov         r14d,dword ptr [rbp-58h]
41 83 C6 40 …
```
> Jit64: More addx and subfx optimizations

- Source/Core/DiscIO/CompressedBlob.cpp
These issues cannot happen with good dumps due to their size, but they can happen with trimmed dumps.
> DiscIO: Fix decompressing writing the wrong number of bytes sometimes

- Source/Core/DiscIO/Blob.h
- Source/Core/DiscIO/CMakeLists.txt
- Source/Core/DiscIO/DirectoryBlob.cpp
- Source/Core/DiscIO/DirectoryBlob.h
- Source/Core/DiscIO/DiscIO.vcxproj
- Source/Core/DiscIO/DiscIO.vcxproj.filters
- Source/Core/DiscIO/VolumeWii.cpp
- Source/Core/DiscIO/VolumeWii.h
- Source/Core/DiscIO/WiiEncryptionCache.cpp
- Source/Core/DiscIO/WiiEncryptionCache.h
This was originally created as part of the WIA PR, but since it also is useful for DirectoryBlob, I'm submitting it as a separate PR. (Not that the accuracy improvement will matter for emulated software other than CleanRip unless you disable `VolumeWii`'s `ReadWiiDecrypted` code path...)
> DiscIO: Implement re-encryption of Wii partition data

- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/Core/HW/WiimoteEmu/Dynamics.h
- Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
This should fix: https://bugs.dolphin-emu.org/issues/12058
Made the same changes to emulated Nunchuk to fix a probably rarely used tilted swinging.
> WiimoteEmu: Apply "Tilt" and "Point" rotations separately for proper tilted pointing.

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainView.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
- Source/Android/app/src/main/res/menu/menu_game_grid.xml
- Source/Android/app/src/main/res/values/strings.xml
- Source/Android/jni/MainAndroid.cpp
Implements https://bugs.dolphin-emu.org/issues/10788
Useful for setting up mod loaders.
> Android: Add Install WAD to menu_game_grid

- Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
- Source/Core/DolphinQt/Debugger/JITWidget.cpp
- Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
- Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
- Source/Core/DolphinQt/Debugger/WatchWidget.cpp
- Source/Core/DolphinQt/Host.cpp
- Source/Core/DolphinQt/Host.h
Pretty self-explanatory. The debugger windows would show stale data after a savestate load when the emulator was in a paused state.
~~I'm not sure if this is a good place to put the `SavestateLoaded` signal, but the `EmulationStateChanged` is already there so... maybe?~~ See comments below.
> Qt/Debugger: Refresh on savestate load.

- Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
- Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
- Source/Core/VideoBackends/Vulkan/ShaderCompiler.cpp
Add static to the functions which is not intentionally
export to big scope.
> Cleanup warnings of -Wmissing-declarations

- Source/Core/Core/IOS/Network/IP/Top.cpp
Previously Core::WantsDeterminism was only checked for pulling in the DNS servers on WIN32.
Same check should apply to Linux too.
> Respect Core::WantsDeterminism for DNS servers on Linux

- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/GameList/GameList.h
This fixes a bug where pressing Enter in the "Do you want to stop the current emulation?" confirmation popup also triggers a KeyRelease in GameList, which starts a new game. This is because the popup closes on KeyPress with the Enter key (I believe because of the Qt autodefault Yes button), which gives focus back to the main window, which receives the KeyRelease event. I have encountered this bug on both Arch Linux and Ubuntu 18.04 -- I'm not sure if this affects other systems.
Listening for KeyPress instead of KeyRelease in GameList fixes this issue. I think it makes more sense this way because we don't want to trigger a key event for the GameList when the key was pressed somewhere else. Please let me know if this fix is acceptable, thanks!
> Qt/GameList: Use KeyPress instead of KeyRelease

- Source/Core/DolphinQt/Settings/AudioPane.cpp
This PR is a de facto follow up to #8664, since there was one more case where DPL II audio quality slider was enabled when it shouldn't be - if Audio panel was opened with HLE audio selected and DPL II checkbox checked (as a "leftover" from using LLE audio, most likely), slider would be enabled while the checkbox itself was disabled. Now it's back in sync, as only this one code path seemed to be out of sync (for this reason candidate for refactor maybe?)
> AudioPane: Do not enable DPL II quality slider with HLE audio on init

- Data/Sys/GameSettings/G8M.ini
This resolves a few issues with bounding box animations and others. Most noticably, it greatly reduces the bounding box slowdown seen on some NVIDIA cards and also fixes the odd overlay glitches when moving between rooms on the Excess Express.
> Don't defer EFB Copies to RAM - PMTTYD Issues

- CMake/DolphinPostprocessBundle.cmake
Both `/tmp` and `/private/tmp` resolve to `/tmp` with `ABSOLUTE` and `/private/tmp` with `REALPATH` (details [here](https://gitlab.kitware.com/cmake/cmake/-/issues/20515))
BundleUtilities uses `ABSOLUTE` internally, so if you give it a `REALPATH` and compile from `/tmp` (which is a symlink to `/private/tmp`), BundleUtilities will complain about things not being inside the main app bundle because some paths don't match
> Match path type to BundleUtilities when running fixup_bundle

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
While having motion control emulation of IR enabled by default makes sense in situations like using a DualShock 4 on a PC, Android has the additional option of touch emulation of IR which seems to be better liked, and the default value which was chosen with PC in mind was carried over to Android without any particular consideration. This change disables motion control emulation of IR by default on Android only.
> Android: Use touch emulation of IR by default

- Source/Core/Core/IOS/Network/SSL.cpp
- Source/Core/Core/IOS/Network/SSL.h
- Source/Core/Core/IOS/Network/Socket.cpp
- Source/Core/Core/IOS/Network/Socket.h
- Source/Core/DolphinQt/CMakeLists.txt
- Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
- Source/Core/DolphinQt/Debugger/NetworkWidget.h
- Source/Core/DolphinQt/DolphinQt.vcxproj
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/MainWindow.h
- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/MenuBar.h
- Source/Core/DolphinQt/Settings.cpp
- Source/Core/DolphinQt/Settings.h
This PR adds a new Network widget that displays the socket table, SSL context and options.
Screenshots:
> Debugger: Add a Network widget

- Source/Core/Common/SettingsHandler.cpp
- Source/Core/Common/SettingsHandler.h
https://bugs.dolphin-emu.org/issues/12019, take two.
> SettingsHandler: Don't output null bytes

- Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp
address is unsigned, it is always greater or equal than zero.
Remove the asert of zero compare.
> HW: cleanup warnings of -Wtype-limits

- Source/Core/DolphinQt/Settings/AdvancedPane.cpp
- Source/Core/VideoBackends/Software/DebugUtil.cpp
- Source/Core/VideoBackends/Software/Rasterizer.cpp
- Source/Core/VideoBackends/Software/Tev.cpp
- Source/Core/VideoCommon/BPStructs.cpp
Cast the variable to the coresponding type.
> Remove warnings of -Wsign-compare

- Source/Core/Core/HW/AddressSpace.cpp
- Source/Core/Core/HW/AddressSpace.h
- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/MenuBar.h
This PR adds an auto-detect features to the Generate Symbols from > RSO modules.
> RSO: Auto-detect RSO location in RAM

- Source/Core/Core/HW/EXI/BBA-TAP/TAP_Unix.cpp
- Source/Core/Core/IOS/IOSC.cpp
- Source/Core/Core/State.cpp
Fix the right length when strncpy. And use specific version of copy
to copy GameID.
> Remove warning of -Wstringop-truncation

- Source/Core/DolphinQt/Config/ControllersWindow.cpp
- Source/Core/DolphinQt/Config/GameConfigEdit.cpp
- Source/Core/DolphinQt/Config/GameConfigWidget.cpp
- Source/Core/DolphinQt/Config/Graphics/EnhancementsWidget.cpp
- Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
- Source/Core/DolphinQt/Config/Graphics/GraphicsChoice.cpp
- Source/Core/DolphinQt/Config/Graphics/GraphicsInteger.cpp
- Source/Core/DolphinQt/Config/Graphics/SoftwareRendererWidget.cpp
- Source/Core/DolphinQt/Config/InfoWidget.cpp
- Source/Core/DolphinQt/Config/LogWidget.cpp
- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingNumeric.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingWidget.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/WiimoteEmuGeneral.cpp
- Source/Core/DolphinQt/Config/NewPatchDialog.cpp
- Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
- Source/Core/DolphinQt/NetPlay/NetPlaySetupDialog.cpp
- Source/Core/DolphinQt/NetPlay/PadMappingDialog.cpp
- Source/Core/DolphinQt/Settings/AudioPane.cpp
- Source/Core/DolphinQt/Settings/GameCubePane.cpp
- Source/Core/DolphinQt/Settings/GeneralPane.cpp
- Source/Core/DolphinQt/Settings/InterfacePane.cpp
- Source/Core/DolphinQt/Settings/WiiPane.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
- Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp
Provides the same behvaior, but in a much more concise manner.
> DolphinQt: Use qOverload where applicable

- Source/Core/Core/PowerPC/Jit64/Jit.cpp
- Source/Core/Core/PowerPC/Jit64/Jit.h
- Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp
Utilizing constexpr, we can eliminate the need to construct the tables at runtime and just do all the work at compile-time. Making for less moving parts overall.
The general structure is more or less the same, however rather than one single initialization function, each table is built off an immediately executed lambda function. This is nice, since it narrows the scope of the table building logic down to the table that actually uses it.
> Jit64/Jit64_Tables: Construct tables at compile-time

- Source/Core/DolphinQt/GameList/GameList.cpp
This should not be exposed to users before the merge of PR #8644. (PR #8738 was unintentionally merged before PR #8644.)
> DolphinQt: Disable converting from TGC

- Source/Core/Core/Boot/Boot_BS2Emu.cpp
- Source/Core/Core/Boot/DolReader.cpp
- Source/Core/Core/Boot/ElfReader.cpp
- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/Config/MainSettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/Core/FifoPlayer/FifoDataFile.cpp
- Source/Core/Core/FifoPlayer/FifoDataFile.h
- Source/Core/Core/FifoPlayer/FifoPlayer.cpp
- Source/Core/Core/FifoPlayer/FifoRecorder.cpp
- Source/Core/Core/HW/AddressSpace.cpp
- Source/Core/Core/HW/AddressSpace.h
- Source/Core/Core/HW/DSP.cpp
- Source/Core/Core/HW/DSPHLE/UCodes/UCodes.cpp
- Source/Core/Core/HW/HW.cpp
- Source/Core/Core/HW/Memmap.cpp
- Source/Core/Core/HW/Memmap.h
- Source/Core/Core/IOS/IOS.cpp
- Source/Core/Core/IOS/IOS.h
- Source/Core/Core/IOS/MIOS.cpp
- Source/Core/Core/IOS/VersionInfo.h
- Source/Core/Core/PowerPC/MMU.cpp
- Source/Core/Core/State.cpp
- Source/Core/DolphinQt/CheatsManager.cpp
- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/Settings/AdvancedPane.cpp
- Source/Core/DolphinQt/Settings/AdvancedPane.h
Changed several enums from Memmap.h to be static vars and implemented Get functions to query them. This seems to have boosted speed a bit in some titles? The new variables and some previously statically initialized items are now initialized via Memory::Init() and the new AddressSpace::Init(). s_ram_size_real and the new s_exram_size_real in particular are initialized from new OnionConfig values "MAIN_MEM1_SIZE" and "MAIN_MEM2_SIZE", only if "MAIN_RAM_OVERRIDE_ENABLE" is true.
GUI features have been added to Config > Advanced to adjust the new OnionConfig values.
A check has been added to State::doState to ensure savestates with memory configurations different from the current settings aren't loaded. The STATE_VERSION is now 115.
FIFO Files have been updated from version 4 to version 5, …
> Configurable MEM1 and MEM2 sizes at runtime via Dolphin.ini

- Source/Core/DolphinQt/CMakeLists.txt
- Source/Core/DolphinQt/DolphinQt.vcxproj
- Source/Core/DolphinQt/GCMemcardCreateNewDialog.cpp
- Source/Core/DolphinQt/GCMemcardCreateNewDialog.h
- Source/Core/DolphinQt/GCMemcardManager.cpp
- Source/Core/DolphinQt/GCMemcardManager.h
The current way is pretty poor UX -- try it yourself, manually type something in the Memory Card Manager's path boxes and see what happens. If we want this feature, we should add an explicit 'create new file' button or dialog.
Note that this is the only place where GCMemcard is ever instantiated without first checking if the file exists, so barring file system races it's the only place that can actually reach the 'create new file' branch.
Thoughts? The actual new UI here is pretty slapdash, but I figured I should collect some opinions before actually putting effort into making a nice dialog.
> GCMemcard/MemcardManager: Make creating a new card more explicit and UX-friendly.

- CMakeLists.txt
Minizip 1.x is the old broken version, while 2.x is the newer fork we use. Many distros ship the old version which is causing stack smashing in RedumpVerifier, so we'll only use the shared lib if it's the newer version.
> Require minizip 2.0.0 or newer

- CMakeLists.txt
- Source/Core/AudioCommon/AudioStretcher.h
- Source/Core/AudioCommon/OpenALStream.h
- Source/Core/Common/Common.vcxproj
- Source/Core/Common/MinizipUtil.h
- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DolphinQt/DiscordJoinRequestDialog.cpp
- Source/Core/UICommon/AutoUpdate.cpp
- Source/Core/UICommon/DiscordPresence.cpp
- Source/Core/UICommon/NetPlayIndex.cpp
- Source/Core/UICommon/ResourcePack/Manifest.cpp
- Source/Core/UICommon/ResourcePack/ResourcePack.cpp
- Source/Core/UICommon/UICommon.vcxproj
- Source/Core/UpdaterCommon/UpdaterCommon.cpp
- Source/Core/UpdaterCommon/UpdaterCommon.vcxproj
- Source/Core/VideoBackends/Vulkan/Vulkan.vcxproj
- Source/Core/VideoCommon/VideoCommon.vcxproj
- Source/VSProps/Base.props
- Source/VSProps/QtCompile.props
We must not provide the /Externals directory as global include directory.
Here, this yield a crash because of external minizip header and system library mismatch.
The wrong usage was written for soundtouch, and many libraries afterwards have been linked wrong.
Soundtouch itself recormends to include it with <SoundTouch.h> and -I/usr/include/soundtouch, so this should fit better.
> Externals: Do not expose the externals directory itself as include path.

- Source/Core/Core/FifoPlayer/FifoDataFile.cpp
Panic alerts don't use fixed width fonts, and translators are unlikely to preserve the exact spacing unless they are given specific instructions to do so and are willing to fight against the Transifex interface a bit.
> Don't assume fixed width for "Emulated memory size mismatch!" message

- Source/Core/DolphinQt/Settings.cpp
- Source/Core/DolphinQt/Settings.h
- Source/Core/DolphinQt/Settings/InterfacePane.cpp
This makes user styles not break when for instance moving a portable.txt install between different folders.
> DolphinQt: Store name of user style, not path

- Source/Core/DolphinQt/Config/VerifyWidget.cpp
- Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
- Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
- Source/Core/VideoCommon/CommandProcessor.cpp
Lambda expressions with uncaptured constants were leading to errors, and there were also some warnings about deprecated functions (QFontMetrics::width and inet_ntoa).
> Fix Windows CMake build errors

- Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
This PR will need a hardware test (similar #8389) to confirm this behaviour.
> IOS/KD: Cleanup sockets on IOCTL_NWC24_CLEANUP_SOCKET

- Source/Core/Common/MathUtil.h
`std::abs(x - y)` where x and y are unsigned integers fails to compile
with an "call of overloaded 'abs(unsigned int)' is ambiguous" error
on GCC, and even if it did compile, that expression still wouldn't
give the correct result since `x - y` is unsigned.
> MathUtil: Fix Rectangle::GetWidth/Height for unsigned types

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/res/values/arrays.xml
- Source/Android/app/src/main/res/values/strings.xml
Has multiple uses, including a temporary workaround for https://bugs.dolphin-emu.org/issues/10791
DSP Emulation Engine is actually two settings, so this is a `SingleChoiceSetting` special case.
> Android: Add DSP Emulation Engine

- Source/Core/Core/HW/WiimoteEmu/Encryption.cpp
Add parentheses around operator ^.
> WiimoteEmu: Cleanup warnings of -Wparentheses

- Source/Android/app/src/main/res/values/arrays.xml
- Source/Core/DolphinQt/Config/GameConfigWidget.cpp
- Source/Core/DolphinQt/Settings/AudioPane.cpp
HLE stands for "high-level emulation", so "DSP HLE Emulation" would
mean "DSP High-Level Emulation Emulation"
> Remove redundant "Emulation" from "DSP HLE Emulation"

- Source/Core/Core/Boot/Boot_BS2Emu.cpp
- Source/Core/Core/Core.h
This PR adds a ConsoleType enum class and replace the magic number (console type) used in boot.
> Boot: Add ConsoleType enum class

- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.h
The **NetPlay Session Browser** dialog's settings are now saved and restored when the widget is created/destroyed. This includes the widget's geometry, as well as the filter settings.
> DolphinQt: Saving and restoring NetPlay Session Browser dialog's settings.

- Source/Core/Core/PowerPC/Jit64/JitAsm.cpp
- Source/Core/Core/PowerPC/JitCommon/JitCache.h
Remove the warning:
warning: offsetof within non-standard-layout type ‘JitBlock’ is conditionally-supported
JitBlock contains non-trival types now. Split the fields with trival
types that needs to be access from JIT code into JitBlockData structure.
> Jit: remove warning -Winvalid-offsetof

- Source/Core/DiscIO/CMakeLists.txt
- Source/Core/DiscIO/CompressedBlob.cpp
- Source/Core/DiscIO/DiscIO.vcxproj
- Source/Core/DiscIO/DiscIO.vcxproj.filters
- Source/Core/DiscIO/MultithreadedCompressor.h
Split out from PR #8538. This PR makes the deflate compression of GCZ happen on multiple threads. Multithreading is more important for WIA than for GCZ because LZMA and bzip2 are much slower than deflate, but I thought this would make sense as its own PR anyway.
> DiscIO: Implement multithreaded compression

- docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex
Apart from improving readability, this also fixes a hex-vs-decimal mismatch.
> docs/DSP: fix $prod references

- Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Previously, when initializing the Win32 input layer (and as a result DirectInput), Dolphin would use the handle of the render widget, which isn't updated when `ControllerInterface::ChangeWindow` is called. This had the annoying side effect of making all mouse input to Dolphin on Windows relative to the main Dolphin window, not the actual render target or render window. 
This PR makes sure the Win32 controller interface is initialized using the actual window handle, which in turn makes mouse input relative to the render target itself, not the main window.
> InputCommon: Use the Window handle when initializing DirectInput.

- Source/Core/UICommon/UICommon.cpp
The include for X11Utils.h (and by extension Xlib.h) is gated behind HAVE_XRANDR, as well as the declaration for this function, but its definition was mistakenly gated behind HAVE_X11. Therefore, if we have X11 but not Xrandr, the build will fail due to declaration/definition mismatch and the missing Window type.
> Core/UICommon: Fix EnableScreenSaver preprocessor directive

- Source/Core/Core/Config/GraphicsSettings.cpp
- Source/Core/Core/Config/GraphicsSettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
- Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h
- Source/Core/DolphinQt/HotkeyScheduler.cpp
- Source/Core/DolphinQt/RenderWidget.cpp
- Source/Core/VideoCommon/CMakeLists.txt
- Source/Core/VideoCommon/FreeLookCamera.cpp
- Source/Core/VideoCommon/FreeLookCamera.h
- Source/Core/VideoCommon/VertexShaderManager.cpp
- Source/Core/VideoCommon/VertexShaderManager.h
- Source/Core/VideoCommon/VideoCommon.vcxproj
- Source/Core/VideoCommon/VideoConfig.h
This makes the freelook camera into a first class citizen (in both UI and code) and exposes a new option to change the freelook camera type to one of three options.
**Six Axis** is the type that Dolphin master uses.  It's essentially designed around those flight simulator games.  It makes it perfect for oddball screenshots because it allows roll but has the nasty side-effect of incurring unintended roll when pitching/yawing:
On the other hand **First Person** is what I would have expected a freelook to work like originally.  It's similar in control to your stereotypical first person games, no roll will happen:
Finally, the **Orbital** type allows for orbiting around the original game camera point.  There's no movement controls, just rotation and zoom.  It is often referred to as …
> Expand freelook camera with control options

- Source/Core/DolphinNoGUI/MainNoGUI.cpp
- Source/Core/DolphinQt/Main.cpp
- Source/Core/UICommon/CommandLineParse.cpp
It is now possible to boot directly into a save state.  The save state file is specified with the command line option `--save-state`.
This fixes issue [9987](https://bugs.dolphin-emu.org/issues/9987)
> Core: Add support for booting a save state from command line

- Source/Core/DolphinQt/CMakeLists.txt
- Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
- Source/Core/DolphinQt/Debugger/ThreadWidget.cpp
- Source/Core/DolphinQt/DolphinQt.vcxproj
- Source/Core/DolphinQt/QtUtils/FontMetricsHelper.h
QFontMetrics::width breaks building with CMake on Windows, due to a deprecation warning which gets promoted to an error.
> DolphinQt: Remove another usage of QFontMetrics::width

- Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
cControls -> controls, axis -> axes, removed leading spaces.
> DolphinQt: Fix freelook description typos

- Source/Core/Common/StringUtil.h
- Source/Core/Core/ActionReplay.cpp
In addition to updating 'TryParse' to support any base, this fixes the ActionReplay usage to specify base 16 instead of prepending a '0x' in front of the string.
> Common / Core: Update StringUtil to allow specifying the base

- Source/Core/Core/IOS/Network/IP/Top.cpp
- Source/Core/Core/IOS/Network/IP/Top.h
- Source/Core/Core/IOS/Network/KD/NetKDRequest.cpp
This PR implements IOCTL_NWC24_REQUEST_SHUTDOWN and renames some IOCTL names.
As far as I know, it's called during shutdown (when the stop button is pressed).
Based on IOS59 v9249.
Regarding the naming:
- **IOCTL_SO_GETLASTERROR** comes from the fact it grabs the IOS SO thread error value
- **IOCTLV_SO_STARTUP**/**IOCTLV_SO_CLEANUP** come from IOS KD strings
- **IOCTL_SO_INITINTERFACE** educated guess since it's not SOStartup and initialises global variables only used by **SO INTERFACE** ioctl(v)s.
> IOS/KD: Implement IOCTL_NWC24_REQUEST_SHUTDOWN

- Source/Core/VideoBackends/D3D/main.cpp
- Source/Core/VideoBackends/D3D12/VideoBackend.cpp
- Source/Core/VideoBackends/Null/NullBackend.cpp
- Source/Core/VideoBackends/OGL/Render.cpp
- Source/Core/VideoBackends/OGL/main.cpp
- Source/Core/VideoBackends/Software/SWmain.cpp
- Source/Core/VideoCommon/FramebufferManager.cpp
- Source/Core/VideoCommon/VideoConfig.h
glReadPixels() with depth formats is not supported.
Should fix broken EFB access on GLES.
> FramebufferManager: Copy to color format for depth readbacks on GLES

- Source/Core/VideoBackends/D3D/DXPipeline.cpp
- Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp
- Source/Core/VideoBackends/OGL/Render.cpp
- Source/Core/VideoBackends/OGL/main.cpp
- Source/Core/VideoBackends/Vulkan/ObjectCache.cpp
- Source/Core/VideoCommon/FramebufferManager.cpp
- Source/Core/VideoCommon/FramebufferShaderGen.cpp
- Source/Core/VideoCommon/GeometryShaderGen.cpp
- Source/Core/VideoCommon/PostProcessing.cpp
- Source/Core/VideoCommon/ShaderCache.cpp
- Source/Core/VideoCommon/ShaderCache.h
- Source/Core/VideoCommon/ShaderGenCommon.cpp
- Source/Core/VideoCommon/ShaderGenCommon.h
- Source/Core/VideoCommon/UberShaderCommon.cpp
- Source/Core/VideoCommon/UberShaderCommon.h
- Source/Core/VideoCommon/UberShaderPixel.cpp
- Source/Core/VideoCommon/UberShaderPixel.h
- Source/Core/VideoCommon/UberShaderVertex.cpp
- Source/Core/VideoCommon/VertexManagerBase.cpp
These helper functions are fairly trivial to convert over: no fancy formatting, just simple renaming `Write` over to `WriteFmt` and converting formatting specifiers over to `{}`. This'll make it more straightforward when converting over the shader generators, since `std::string_view` can now be used with these functions without needing to call `.data()`.
While we're in the same area, we can also convert several template functions into normal functions, given the type of their argument is always the same type (`ShaderCode&`). This allows hiding details within the translation unit, allowing changes to the implementation of the functions without needing to recompile every single shader generator translation unit. This also uncovered quite a few indirect inclusions in the process, which have …
> VideoCommon/ShaderGenCommon: Convert helper functions over to fmt where applicable

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
Requested by @Sanmorin
Install WAD doesn't normally have an icon and `ic_folder` appears unused on Android TV so I used that icon.
~~Note: I have no way of testing Android TV.~~
> Android TV: Add Open File and Install WAD

- Source/Core/VideoCommon/FramebufferManager.cpp
- Source/Core/VideoCommon/FramebufferManager.h
Fixes assertion tripping when saving state on Adreno.
Should fix https://bugs.dolphin-emu.org/issues/12040 but I don't have easy access to an Adreno device to check.
> FramebufferManager: Fix invalid readback of EFB D24S8 depth

- Source/Core/Core/Core.cpp
- Source/Core/DolphinQt/MainWindow.cpp
Fixes crashes with Vulkan on macOS. Regression from #8795.
Fixes https://bugs.dolphin-emu.org/issues/12107
I kinda wish we had a macOS maintainer or someone interested in doing it, it's not straightforward for me to set up/debug... :(
> Core: Use window instead of surface for ControllerInterface updates

- Source/Core/DolphinQt/QtUtils/RunOnObject.h
`std::result_of` is deprecated in C++17, and removed in C++20. Microsoft has gone ahead with the removal as of Visual Studio 16.6.0, so before this change our code is broken there.
Externals/Qt also needs to be updated to the latest version to fully fix the build.
> Replace usage of std::result_of with std::invoke_result

- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/Config/MainSettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
- Source/Core/DolphinQt/Settings/WiiPane.cpp
- Source/Core/DolphinQt/Settings/WiiPane.h
This is mainly useful when you have an SD card which you use for NetPlay and you don't want it accidentally written to when playing outside of NetPlay, as that results in a desync the next time it's used in NetPlay if you don't share your exact SD card with other players.
It's also fair to say that this kind of implements a hardware feature, as physical SD cards have a write lock switch. Although, this doesn't implement the actual IOS functionality that causes the write protection error message in Wii software. (Is this even a thing? Or does simply failing writes produce this behavior?)
> Add option to disallow SD card writes

- Source/Core/DolphinQt/GameList/GameListModel.cpp
canonicalPath is orders of magnitude slower as it has to perform actual disk I/O to resolve symlinks, which makes sorting by this column ridiculously slow for large game lists, especially if the games are on a NAS. We probably don't need that, simply resolving relative paths should be sufficient.
This should fix https://bugs.dolphin-emu.org/issues/12135
> Qt/GameListModel: Use absolutePath for file path column

- Source/Core/Core/HW/DSPLLE/DSPSymbols.cpp
- docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex
Fix the completely nonsensical pseudo code of the extended opcodes 'S and 'SN. Also explicitly refer to addressing and indexing registers where possible.
The DSPSymbols code is currently unused but had a typo and a dead std::map.
> DSP: fix typos and improve docs

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/viewholders/GameViewHolder.java
- Source/Android/app/src/main/res/layout/card_game.xml
- Source/Android/app/src/main/res/values/strings.xml
Fixes https://bugs.dolphin-emu.org/issues/11413.
The company can be found in Game Details too so I'd rather use that space to display disc number for multipart discs. See Tales of Symphonia's cards in the image below.
> Android: Display disc number instead of company if mulipart disc

- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/MenuBar.h
I'm adding this as a convenience for people like me who always forget to turn off fastmem before debugging a segfault. Less effort required than having to edit the config file manually and restart Dolphin, which might be extra inconvenient if you've gone through a bunch of steps to get to the state needed to debug an issue.
> DolphinQt: Add fastmem option to debugger UI

- Source/Core/Core/HW/DVD/DVDInterface.cpp
- Source/Core/DiscIO/Blob.h
- Source/Core/DiscIO/CISOBlob.h
- Source/Core/DiscIO/CompressedBlob.h
- Source/Core/DiscIO/DirectoryBlob.h
- Source/Core/DiscIO/DriveBlob.h
- Source/Core/DiscIO/FileBlob.h
- Source/Core/DiscIO/ScrubbedBlob.h
- Source/Core/DiscIO/TGCBlob.h
- Source/Core/DiscIO/Volume.h
- Source/Core/DiscIO/VolumeFileBlobReader.cpp
- Source/Core/DiscIO/VolumeFileBlobReader.h
- Source/Core/DiscIO/VolumeGC.cpp
- Source/Core/DiscIO/VolumeGC.h
- Source/Core/DiscIO/VolumeWad.cpp
- Source/Core/DiscIO/VolumeWad.h
- Source/Core/DiscIO/VolumeWii.cpp
- Source/Core/DiscIO/VolumeWii.h
- Source/Core/DiscIO/WbfsBlob.h
This is intended to catch WIA files which have been created using wit's default parameters (40 MiB block size), once PR #8538 is merged. The check does however also work for GCZ files – not that I think anyone has a GCZ file with a block size that large.
> Show an OSD message when running a disc image with a large block size

- Data/Sys/GameSettings/D85.ini
- Data/Sys/GameSettings/D86.ini
- Data/Sys/GameSettings/D95.ini
- Data/Sys/GameSettings/DAX.ini
- Data/Sys/GameSettings/G4P.ini
- Data/Sys/GameSettings/G95.ini
- Data/Sys/GameSettings/G99.ini
- Data/Sys/GameSettings/GCI.ini
- Data/Sys/GameSettings/GR6.ini
- Data/Sys/GameSettings/GYA.ini
- Data/Sys/GameSettings/HC4.ini
- Data/Sys/GameSettings/R6B.ini
- Data/Sys/GameSettings/RBK.ini
- Data/Sys/GameSettings/RBY.ini
- Data/Sys/GameSettings/RMHJ08.ini
- Data/Sys/GameSettings/RNB.ini
- Data/Sys/GameSettings/RPY.ini
- Data/Sys/GameSettings/RST.ini
- Data/Sys/GameSettings/RTH.ini
- Data/Sys/GameSettings/RW7.ini
- Data/Sys/GameSettings/RYB.ini
- Data/Sys/GameSettings/SEC.ini
- Data/Sys/GameSettings/SMN.ini
- Data/Sys/GameSettings/SOM.ini
- Data/Sys/GameSettings/SVM.ini
- Data/Sys/GameSettings/WL9.ini
Based on #8164 
-Adds a few games.
-Enables MMU for Crunchyroll Channel so it can boot and for Interactive Multi Game Demo Disc with demo's which require MMU.
-Enables FPRF for games that need it.
-Disables defered EFB for games that crashed or showed weird behaviour with defered EFB enabled.
-Sets TextureCacheAccuracy to safe for a few games that need it.
-Sets EFB to texture and ram for a few games that need it.
-Removes Wiimote.Shake and Wiimote.Swing as those are no longer functional.
I also removed TextureCacheAccuracy = Safe from NSMBW because accuracy on fast shows no issues. I think this was fixed with Partial Texture Updates.
> INI changes

- Source/Core/DolphinQt/GameList/GameList.cpp
`GetSelectedGames()` constructs a new list each time you call it.
> DolphinQt: Fix crash on right-clicking multiple games

- Source/Core/DolphinQt/ConvertDialog.cpp
I don't know why QErrorMessage doesn't work, but ModalMessageBox works, so let's use ModalMessageBox.
> DolphinQt: Make conversion error messages actually show up

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Fixes https://bugs.dolphin-emu.org/issues/11935
> Android: Disallow multiple launcher activities

- Source/Core/DolphinQt/GameList/GameList.cpp
When I made PR #8773, I only covered the case where multiple files are selected, not the more common case where only one file is selected. Oops
> DolphinQt: Actually disable converting from TGC

- Source/Core/Core/CMakeLists.txt
- Source/Core/Core/Core.vcxproj
- Source/Core/Core/Core.vcxproj.filters
- Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
- Source/Core/Core/HW/GCMemcard/GCIFile.cpp
- Source/Core/Core/HW/GCMemcard/GCIFile.h
- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.h
- Source/Core/Core/HW/GCMemcard/GCMemcardBase.h
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.h
- Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardRaw.h
- Source/Core/DolphinQt/GCMemcardCreateNewDialog.cpp
- Source/Core/DolphinQt/GCMemcardManager.cpp
- Source/Core/DolphinQt/GCMemcardManager.h
- Source/Core/DolphinQt/Settings/GameCubePane.cpp
See #8872. I've left out code improvements here even though I've seen a few sketchy things here, might do a followup on those later. This is just the namespacing.
Note that I've only moved the actual memory card structure and manipulation code into the namespace. The code related to the implementation of the emulated Raw and GCI Folder stuff has been left outside, and should IMO go into a different namespace.
> GCMemcard: Move into a Memcard namespace.

- CMakeLists.txt
- Externals/zstd/CMakeLists.txt
CMake does not have native support for zstd yet, so find_package() doesn't work out of the box.
@JosJuice: Note that #8538 will need to link against `zstd` instead of `zstd::zstd` since CMake's FindPkgConfig module doesn't add an alias like Externals/zstd/CMakeLists.txt does.
> CMake: support using system-wide zstd library

- Source/Core/DolphinQt/ConvertDialog.cpp
- Source/Core/DolphinQt/ConvertDialog.h
Mainly useful for WIA and RVZ, but also has some use for GCZ.
> DolphinQt: Allow converting to same format

- Source/Core/DolphinQt/ConvertDialog.cpp
This isn't really to my taste personally, but it was suggested in the comments of PR #8538.
> DolphinQt: Disable convert dialog dropdowns when they have one option

- Source/Core/VideoCommon/FreeLookCamera.cpp
- Source/Core/VideoCommon/FreeLookCamera.h
- Source/Core/VideoCommon/VertexShaderManager.cpp
Potentially fixes issue [12157](https://bugs.dolphin-emu.org/issues/12157)
> VideoCommon: Clean freelook camera dirty state when getting the new view

- Source/Core/Core/IOS/Network/Socket.cpp
For some reason, Dolphin returns `EAGAIN` rather than `ENOTCONN`.
In some circumstances, it creates an infinite loop. For instance, using `send` with a socket which is not connected.
Is there any reason to keep this legacy value? As far as I know, `ENOTCONN` is only returned by the following functions:
- `recv`, `recvfrom`
- `send`, `sendto`
- `shutdown`
> Socket: Fix ENOTCONN error code

- Source/Core/Core/PowerPC/Gekko.h
- Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
- Source/Core/Core/PowerPC/PowerPC.h
Doesn't support triggering interrupts when the thermal threshold is
exceeded, but allows polling for temperature information.
The THRM[123] registers are documented in most PPC datasheets, see e.g.
this PPC750CX one: http://datasheets.chipdb.org/IBM/PowerPC/750/750cx_um3-17-05.pdf
Fixes https://bugs.dolphin-emu.org/issues/12160 . See the nice 42°C display on Swiss in this screenshot:
> PowerPC: partially implement thermal related SPRs

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
- Source/Android/app/src/main/res/menu/menu_emulation.xml
- Source/Android/app/src/main/res/menu/menu_emulation_wii.xml
- Source/Android/app/src/main/res/values/arrays.xml
- Source/Android/app/src/main/res/values/strings.xml
Wii overlay changes will be made in a subsequent PR.
Other minor changes:
- Renamed emulation menu's "Configure Controls" to "Overlay Controls", since the former could be misinterpreted as applying to all players.
- Added a "None" controller. It is primarily used for disabled controllers and real controllers (as an overlay is useless if Player 1 is using a real controller).
> Android: Separate GameCube overlay refresh logic

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
Implements https://bugs.dolphin-emu.org/issues/10793
Prerequisite for https://bugs.dolphin-emu.org/issues/10957
Android-specific settings should be moved away from SharedPreferences and use INI settings. This allows these settings to be retained across multiple builds of Dolphin. I added an Android section to Dolphin.ini to make these settings easy to find. Most of the setting changes will happen in future PRs.
Android: Make last platform tab selection an INI setting was a test case. Now Dolphin will remember which platform tab was selected when (re)installing or starting Dolphin.
> Android: Android INI section and make platform tab selection an INI setting

- Source/Core/Core/HW/EXI/EXI.cpp
- Source/Core/Core/HW/EXI/EXI.h
- Source/Core/Core/HW/EXI/EXI_Channel.cpp
- Source/Core/Core/HW/EXI/EXI_Channel.h
- Source/Core/Core/HW/EXI/EXI_Device.cpp
- Source/Core/Core/HW/EXI/EXI_Device.h
- Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
- Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.h
- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.h
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.h
- Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp
- Source/Core/Core/State.cpp
- Source/Core/DolphinQt/GCMemcardCreateNewDialog.cpp
Note: The first two commits are also found in #8880. It doesn't really matter which gets merged first.
This is a safer but more complex implementation of #8476. Instead of hardcoding a card ID, we store the memory card header data in EXI_Channel and ensure the same game session (including savestates) always sees the same card header. This is necessary because some (apparently many!) games check this and will refuse to save to the memory card if they believe the card is a different card they initially loaded from.
Whenever we create a new GCI folder memory card, we pass along the header data to the device, which ensures that eg. switching from GCI folder to No Memory Card back to GCI folder while the game is running still results in the same header. Additionally, when loading a savestate, …
> Keep memory card header and use it to reinitialize GCI folders on mismatch. (Fix savestate with GCI folders)

- Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp
- Source/Core/Core/State.cpp
This fixes an issue with saving after loading a savestate in Pokemon Colosseum. Also seems like a good idea anyways, as SRAM is part of system state after all. Should we add a flag to not write the SRAM back to disk if it was loaded from a savestate?
> Include SRAM in savestates

- Source/Core/Core/IOS/Network/IP/Top.cpp
- Source/Core/Core/IOS/Network/IP/Top.h
- Source/Core/Core/IOS/Network/Socket.cpp
- Source/Core/Core/IOS/Network/Socket.h
- Source/Core/Core/State.cpp
This is to make the behavior more consistent with the behavior on console.
Currently, SO_POLL blocks the PPC until poll() completes, so this prevents PPC threads on DolphinOS and libogc's LWP from running while waiting for the call to complete, while on a real console, IOS lets the PPC run, as with most other calls, and notifies the PPC through the usual mechanism.
I don't know if how I implemented it is the preferred way in regard to Dolphin's internals: Basically each SO_POLL operation gets queued into a poll table with the associated request, and when an event happens on a socket that is referenced in a poll table in WiiSockMan::Update, an IPC reply is generated for the request.
> Make SO_POLL complete asynchronously in IOS_NET SO

- CMakeLists.txt
- Source/Core/DolphinQt/Config/VerifyWidget.cpp
- Source/Core/VideoCommon/CommandProcessor.cpp
While manually capturing constexpr variables used in lambda expressions does work, it's really easy to forget doing so since we don't have a Windows CMake builder and the workaround isn't necessary anywhere else. Fortunately, MSVC has a flag that fixes the constexpr capture behavior, so let's use that instead.
> Replace Windows CMake lambda constexpr capture workaround

- Source/Core/Core/ConfigManager.cpp
- Source/Core/Core/ConfigManager.h
- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/GameList/GameListModel.cpp
- Source/Core/DolphinQt/GameList/GameListModel.h
- Source/Core/DolphinQt/MenuBar.cpp
Same data as PR #8891, but now directly in the game list. The new columns are disabled by default.
> DolphinQt: Add columns with file format details

- Source/Core/Core/IOS/Network/Socket.cpp
- Source/Core/Core/IOS/Network/Socket.h
- Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
This PR adds a "Blocking" column to the Network widget telling if the socket is blocking.
> NetworkWidget: Add Blocking column

- Source/Core/Core/HW/VideoInterface.cpp
Fixes https://bugs.dolphin-emu.org/issues/12066.
I must've only tested the frame counter with an earlier version of the PR that broke this, not the final version...
> Core: Call Movie::FrameUpdate per field, not per line

- Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
Should fix JitArm64 crashing when fastmem is off. The instruction ``lfd`` also is causing a crash for me, but that might just be an issue with my local build. Testers are appreciated...
> JitArm64: Don't assume fastmem arena is available

- Source/Core/Common/MsgHandler.h
- Source/Core/VideoCommon/VideoCommon.h
Intends to fix https://bugs.dolphin-emu.org/issues/12170.
Untested, because I'm using VS 16.5 to avoid the std::result_of problem, and as far as I know the new preprocessor requires VS 16.6.
> Support the new MSVC preprocessor

- Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
> JitArm64: no intermediate rounding for FMA

- Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
> JitArm64_Paired: Fix ps_msub when d == b

- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/VertexShaderManager.cpp
- Source/Core/VideoCommon/VideoConfig.cpp
Another attempt to fix [12157](https://bugs.dolphin-emu.org/issues/12157).  I made the assumption that pulling from our onion config system was relatively fast but that doesn't seem to be the case from testing that fifolog (4fps difference)
> VertexShaderManager: Only look for freelook config changes if we're using freelook

- Source/Core/DolphinQt/ConvertDialog.cpp
The code for disabling scrubbing for RVZ was overriding the code for disabling scrubbing for Datel discs.
> DolphinQt: Fix scrubbing not being disabled for Datel discs

- Source/Core/DiscIO/VolumeVerifier.cpp
I forgot to do this in the PR where I added Volume::IsDatelDisc.
> DiscIO: Use Volume::IsDatelDisc in VolumeVerifier

- Source/Core/VideoBackends/OGL/Render.cpp
Some users who get this error don't seem to gain much understanding of how to resolve the problem from reading the error message.
> Reword "Please avoid forcing Dolphin to use MSAA by the driver" message

- Source/Core/InputCommon/GCAdapter.cpp
This makes my Nyko-branded GCAdapter work and probably others. Please test.
Note that `libusb_control_transfer` calls give a `LIBUSB_ERROR_BUSY` error within a hotplug callback so I've introduced an `Event` to initialize adapters in the "scanning" thread.
I'm not entirely happy with this fix but GCAdapter needs a complete rewrite. The error handling is bad. The inter-thread communication is bad. And 90% of the logic is copy-pasted to GCAdapter_Android.cpp.
This PR does not attempt to fix the Android-side of things. I can't test there.
> InputCommon/GCAdapter: Fix offbrand "GCAdapters".

- Source/Android/app/src/main/res/values/strings.xml
Changing this setting to 0% is how Dolphin interprets "Unlimited" speed limit.
@JMC47
> Android: Update "Speed Limit" for "Unlimited" value

- Source/Core/DolphinQt/TAS/GCTASInputWindow.cpp
- Source/Core/DolphinQt/TAS/TASCheckBox.cpp
- Source/Core/DolphinQt/TAS/TASCheckBox.h
- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.h
- Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp
As a side effect of PR #8347, Dolphin's frame counter was changed to run at 60/50 Hz even if the game is running at a lower framerate such as 30 fps. Since the TAS input turbo button functionality toggled the state of a button every other frame as reported by the frame counter, this change made the turbo button functionality not work with 30/25 fps games.
I believe it would be hard to change the frame counter back to how it used to work without undermining the point of PR #8347, and I'm not sure if doing so would be desireable or not anyway, so what I'm doing instead is letting the user determine how long turbo button presses should last. This lets users avoid the 30/25 fps game problem while also granting additional flexibility. Perhaps there is some game where it is useful to mash at a …
> DolphinQt: Allow customizing TAS input turbo interval

- Source/Core/Core/HW/WiimoteCommon/WiimoteConstants.h
- Source/Core/Core/HW/WiimoteCommon/WiimoteReport.h
- Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.cpp
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.h
Wii Remotes provide an 8-bit battery level.
Documentation thought the maximum value to be decimal 200.
My testing shows this is a direct reading of the battery voltage. 
The full range of values from 0 to 255 can be produced with voltages not possible from AA batteries.
For fun, a fitted equation is: `level = 176.6681 * volts - 372.1352 `
I've tested the battery levels required to produce 0 to 4 bars in the home menu and tweaked our battery calculations in WiimoteEmu and ControllerInterface to match this.
"Battery" settings of `0`, `25`, `50`, `75`, and `100%` now produce the matching number of bars in the home menu.
Battery level "passthrough" with DSU, XInput, etc. should now be more sensible.
ControllerInterface Wii Remote battery level inputs should be more accurate.
> WiimoteCommon: Tweak battery level math.

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
Probably didn't actually break anything in practice due to how the code for sticks works, but still.
> Android: Fix button ID typo

- Source/Core/DolphinQt/QtUtils/ParallelProgressDialog.h
This workaround is not timing sensitive, unlike the old one.
Hopefully fixes https://bugs.dolphin-emu.org/issues/12158 and https://bugs.dolphin-emu.org/issues/12180.
> DolphinQt: Replace QTBUG-10561 workaround with better workaround

- Source/Core/DolphinQt/QtUtils/ParallelProgressDialog.h
I believe the value returned by value() resets when we call setValue() with the maximum (due to auto-reset). I have been unable to test this because I can't reproduce the issue, which is described at https://bugs.dolphin-emu.org/issues/12158#note-9.
> DolphinQt: Attempt to fix ParallelProgressDialog constantly reopening

- Source/Core/DiscIO/WIACompression.cpp
This could cause read errors if chunks were laid out a certain way in the file and the whole chunk wasn't being read at once. Should fix https://bugs.dolphin-emu.org/issues/12184.
> RVZ: Fix split seed reads

- Source/Core/InputCommon/GCAdapter.cpp
This should fix regressions caused by PR #8933 (issue https://bugs.dolphin-emu.org/issues/12182).
> InputCommon/GCAdapter: Unbreak Mayflash GCAdapters by allowing libusb_control_transfer call to fail.

- Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
- Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
- Source/Core/Core/HW/WiimoteEmu/Speaker.h
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
Wii remote speaker data reports result in a write to the i2c bus on real hardware.
Explicitly sending the relevant write data reports will produce sound.
I'm guessing a specific "speaker data" report exists to avoid the overhead of sending i2c addresses and allow 20 bytes per report (vs 16).
Regardless, writing to the bus to produce sound is now supported.
Nothing will ever use this but it's a more accurate hardware simulation.
> WiimoteEmu: Allow writes of the i2c bus to play speaker data.

- Source/Core/InputCommon/ControllerEmu/ControllerEmu.h
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.cpp
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.h
Some Nunchuks and Classic Controllers have bad calibration data.
This was causing unusable inputs in ControllerInterface Wii Remotes (aka Hybrid Wiimote 2.0).
This PR adds fallback values to make things mostly usable if the calibration checksum is bad or values are not sane.
The sanity check is just that "min" and "max" values are on opposite sides of the "zero" value.
This fixes:
https://bugs.dolphin-emu.org/issues/12088
https://bugs.dolphin-emu.org/issues/12027
> ControllerInterface/Wiimote: Provide fallback values for extensions with bad calibration.

- Source/Core/Common/Timer.cpp
- Source/Core/Common/Timer.h
Dates before ~2008 underflowed in a `u64` and were then converted to a `u32`.
The year 2000 was saved as 2136. 
https://bugs.dolphin-emu.org/issues/12119
Other code in this file assumes the `time_t` epoch is 1970 so I'm making that same assumption.
We can safely use `time_since_epoch` when we switch to C++20.
Do we want to add some hax to read times that were saved incorrectly?
I don't think it's worth it.
> Common/Timer: Fix integer underflow in Timer::GetDoubleTime for dates before ~2008.

- Source/Core/Common/Timer.cpp
- Source/Core/Common/Timer.h
Fixes the timer returning 1 when it should return 0. The case mentioned by the comment does not exist anymore.
Also added a IsRunning function as it was impossible to know whether it had been started or not (I will use it in later PRs but it should be there anyway)
> Timer fixes

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFile.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PicassoUtils.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/TvUtil.java
- Source/Android/jni/MainAndroid.cpp
This lets Android automatically delete data in the cache directory when the device is running low on space or when Dolphin is uninstalled.
> Android: Use system cache directory as cache directory

- Source/Android/app/build.gradle
- Source/Android/app/src/main/AndroidManifest.xml
Since updating to 28 took us so long that Google Play started requiring updates to target 28 before we actually merged the PR that made us target 28, I'm trying to get the update to 29 done early.
Setting targetSdkVersion to 28 would normally force scoped storage on us, which we do not support yet. However, we can easily avoid this by setting android:requestLegacyExternalStorage="true". There will be no such luxury with targetSdkVersion 30, however...
> Android: Increase targetSdkVersion to 29

- Source/Core/Common/CommonFuncs.cpp
I don't know why Android does it like this, but at least it's easy to fix. (We are currently at `__ANDROID_API__` == 21.)
> Add Android check for strerror_r variant

- Source/Core/Common/MemArena.cpp
Fixes a critical regression where PR #8953 made us unable to start emulation on Android 10 and newer. Android is restricting direct access to `/dev/ashmem` starting with the new SDK version, but we can use the new (and simpler) `ASharedMemory` API instead.
While this change does fix the problem on Android 10, there is the problem that `ASharedMemory` was added in SDK version 26. We currently have `minSdkVersion` set to 21, and I do not want to increase it to as much as 26 unless it is absolutely necessary. My hope was that I could select between the two APIs at runtime, like we are able to do in Java, but it does not seem to be possible to link to `ASharedMemory` without increasing `minSdkVersion` (or its NDK equivalent, `ANDROID_PLATFORM`).
> Android: Don't access /dev/ashmem on newer Android versions

- Source/Core/DolphinQt/GameList/ListProxyModel.cpp
This fixes the root cause of the problem of #8887.
The sort direction was inadvertently inverted in the proxy providing the secondary sort key.
> DolphinQt: Fix default sort direction of game list.

- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/GameList/GameListModel.cpp
- Source/Core/DolphinQt/GameList/GameListModel.h
- Source/Core/DolphinQt/GameList/ListProxyModel.cpp
Our usage of `Qt::InitialSortOrderRole` as the sort role in our `GameListModel` is unusual.
> This role is used to obtain the initial sort order of a header view section. (Qt::SortOrder). This role was introduced in Qt 4.8.
It's intended to return a `Qt::SortOrder` (ascending/descending) in an entirely different overridden function.
While our usage probably isn't breaking anything it's unusual and had me barking up wrong trees in Qt documentation.
> DolphinQt: Replace unusual Qt::InitialSortOrderRole usage with a custom role.

- Source/Core/Core/DSP/DSPCore.cpp
- Source/Core/Core/DSP/DSPCore.h
- Source/Core/Core/DSP/DSPStacks.cpp
- Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp
- Source/Core/Core/DSP/Jit/x64/DSPEmitter.h
- Source/Core/Core/DSP/Jit/x64/DSPJitUtil.cpp
- Source/Core/Core/HW/DSPHLE/UCodes/Zelda.cpp
- Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
- Source/Core/Core/NetPlayClient.cpp
- Source/Core/Core/NetPlayServer.cpp
- Source/Core/DolphinQt/RenderWidget.cpp
- Source/Core/InputCommon/GCAdapter.cpp
- Source/Core/VideoBackends/Software/DebugUtil.cpp
- Source/Core/VideoBackends/Vulkan/Renderer.cpp
Should behave as original code, but without magic numbers and looks a bit simpler.
// not sure if formatting will satisfy you :(
> Use range loop (if possible)

- Source/Android/jni/AndroidCommon/AndroidCommon.cpp
- Source/Core/Common/FileUtil.cpp
- Source/Core/Common/Logging/ConsoleListenerWin.cpp
- Source/Core/Common/StringUtil.cpp
- Source/Core/Common/StringUtil.h
- Source/Core/Common/Timer.cpp
- Source/Core/Core/HW/WiimoteReal/IOWin.cpp
- Source/Core/Core/HW/WiimoteReal/IOWin.h
- Source/Core/Core/HW/WiimoteReal/IOhidapi.cpp
- Source/Core/DolphinNoGUI/PlatformWin32.cpp
- Source/Core/InputCommon/ControllerInterface/DInput/DInput.cpp
- Source/Core/UICommon/AutoUpdate.cpp
- Source/Core/VideoBackends/D3DCommon/Common.cpp
- Source/Core/WinUpdater/Main.cpp
- Source/Core/WinUpdater/WinUI.cpp
The functions with "UTF" in the name use "modified UTF-8" rather than the standard UTF-8 which Dolphin uses, at least according to Oracle's documentation, so it is incorrect for us to use them. This change fixes the problem by converting between UTF-8 and UTF-16 manually instead of letting JNI do it for us.
Also includes some related changes in StringUtil which are described by the commit messages.
> Android: Use correct encoding when converting strings

- Source/Core/Core/HW/GCPadEmu.cpp
- Source/Core/Core/HW/GCPadEmu.h
The old values were based on the clamping done by the SDK which worked out to around 68% and 58%.
These new values are based on actual hardware: ~79% and ~72%.
The calibration shape of a real GameCube controller is now much closer to our target "gate" shape.
Before:
After:
I've heard reports of users not being able to make their character run in Madden games without boosting their input values.
This should help with that.
> HW/GCPadEmu: Adjust gate radius values to more closely match the real hardware.

- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
Should make it both easier to edit and faster to run.
> Config: Simplify IsSettingSaveable

- Source/Core/DolphinQt/ConvertDialog.cpp
It wasn't clear whether the conversion would create a new file or replace the old one
Recreated #8952 directly from github
> Fix disc image conversion button not being clear #3

- Source/Core/Core/CMakeLists.txt
- Source/Core/Core/Core.vcxproj
- Source/Core/Core/Core.vcxproj.filters
- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.h
- Source/Core/Core/HW/GCMemcard/GCMemcardUtils.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardUtils.h
This modifies `GCMemcard::TitlePresent()` to match my findings of how the GC BIOS and various games behave when you muck with the fields in the directory entry.
It looks like for a save to be recognized by a game, the following have to be true:
- Game code and maker code must exactly match what the game expects.
- Filename is only checked up to the first null byte. All bytes afterwards can be whatever.
The BIOS itself does a full compare of the filename when checking for whether it should allow copying a file from one card to another, but behaves oddly in some cases when there's non-null bytes after the first null. See the big comment in `HasSameIdentity()` for details.
The new `GCMemcardUtils.cpp` file may seem a bit excessive for now, but I have some plans for some improvements to the …
> GCMemcard: Change behavior of TitlePresent() to more closely resemble how saves are actually identified.

- Source/Core/Core/Config/GraphicsSettings.cpp
- Source/Core/Core/Config/GraphicsSettings.h
- Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
- Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h
- Source/Core/VideoCommon/TextureCacheBase.cpp
- Source/Core/VideoCommon/VideoConfig.cpp
- Source/Core/VideoCommon/VideoConfig.h
Specifically, this enables users to choose whether to dump mip maps, or base level textures.
> DolphinQt / VideoCommon: Add additional texture dumping options

- Data/Sys/GameSettings/SEU.ini
- Data/Sys/GameSettings/SEV.ini
Works around a rendering error in Retro City Rampage (disc) and
Shakedown: Hawaii.  Fixes redmine issues #12197 and #12198.
> GameSettings: SafeTextureCacheColorSamples for SEUPEY and SEVPEY

- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
These don't modify internal class state, so they can be made const.
> WiimoteEmu: Mark several getters as const

- Source/Core/Core/FifoPlayer/FifoPlayer.cpp
- Source/Core/Core/HW/VideoInterface.cpp
- Source/Core/Core/HW/VideoInterface.h
- Source/Core/Core/State.cpp
- Source/Core/VideoCommon/FrameDump.cpp
We now provide a double to the FPS counter and exact values to FIFO recording and frame dumping.
> VideoCommon: Don't round the refresh rate

- Externals/curl/lib/CMakeLists.txt
Added a few flags to the curl external static build so that it has ssl capabilities. otherwise, it doesn't support protocols like https and you get errors trying to send curl requests to those kind of endpoints
> Curl: For windows cmake builds, build curl with schannel/winssl capability

- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/Config/MainSettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/DiscIO/Volume.h
- Source/Core/DiscIO/VolumeDisc.cpp
- Source/Core/DiscIO/VolumeDisc.h
- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/VolumeWad.cpp
- Source/Core/DiscIO/VolumeWad.h
- Source/Core/DolphinQt/CMakeLists.txt
- Source/Core/DolphinQt/DolphinQt.vcxproj
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/NKitWarningDialog.cpp
- Source/Core/DolphinQt/NKitWarningDialog.h
It is my opinion that nobody should use NKit disc images without being aware of the drawbacks of them. Since it seems like almost nobody who is using NKit disc images knows what NKit is (hmm, now how could that have happened...?), I am adding a warning to Dolphin so that you can't run NKit disc images without finding out about the drawbacks. In case someone really does want to use NKit disc images, the warning has a "Don't show this again" option. Unfortunately, I can't retroactively add the warning where it's most needed: in Dolphin 5.0, which does not support Wii NKit disc images.
> DolphinQt: Show a warning when launching an NKit disc image

- Source/CMakeLists.txt
The CMake Windows build was broken because of me adding a usage of `std::codecvt_utf8_utf16` to StringUtil.cpp. Kinda silly to have a warning for an API with no standard replacement available...
> CMake: Add -D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Rumble.java
That a device doesn't have a touchscreen doesn't necessarily mean that it doesn't support rumble (though it is usually the case). `setPhoneVibrator` already contains a check for whether the device supports rumble, so we can simply remove the touchscreen check.
> Android: Remove touchscreen check for rumble

- Source/Core/DolphinQt/NKitWarningDialog.cpp
This may be the cause of a crash that has been reported on the forums, but I'm not sure since I can't reproduce it myself.
> DolphinQt: Don't capture local pointer by reference

- Source/Core/Common/Hash.cpp
- Source/Core/Common/Hash.h
- Source/Core/Core/DSP/DSPCodeUtil.cpp
- Source/Core/Core/DSP/DSPCodeUtil.h
- Source/Core/Core/DSP/DSPCore.h
- Source/Core/Core/DSP/DSPHWInterface.cpp
- Source/Core/Core/DSP/DSPHost.h
- Source/Core/Core/HW/DSPLLE/DSPHost.cpp
- Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
- Source/DSPTool/DSPTool.cpp
Fixes [#11980](https://bugs.dolphin-emu.org/issues/11980).  `Memory::physical_base` does not exist when fastmem is disabled.
Note that I remove some SSSE3 code (originally added 9 years ago in 559fb7434e404e81bf2c742f076a630cc6999d78).  My machine is too old to support SSSE3, so I haven't tested the performance impact, but I don't think it's likely to make a difference in this one case (since it's not used by DSP HLE).  If it actually does matter, then `CopyFromEmuSwapped` and `CopyToEmuSwapped` should be changed to use it instead.
> Fix crash when using DSP LLE with CPU interpreter (or fastmem off)

- Source/Core/VideoCommon/OnScreenDisplay.cpp
- Source/Core/VideoCommon/OnScreenDisplay.h
Considering `Color::YELLOW` is `0xFFFFFF30`, and it looks yellow to me, this just seems to have been switched up.
> OnScreenDisplay: fix names rgba -> argb

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
- Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
- Source/Android/app/src/main/res/menu/menu_emulation.xml
- Source/Android/app/src/main/res/menu/menu_emulation_wii.xml
- Source/Android/app/src/main/res/values/strings.xml
Implements https://bugs.dolphin-emu.org/issues/10602 and should survive orientation changes.
> Android: Add Pause / Unpause Emulation Toggle

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Setting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/MenuTag.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/CheckBoxSettingViewHolder.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/res/values/arrays.xml
- Source/Android/app/src/main/res/values/strings.xml
- Source/Android/jni/AndroidCommon/IDCache.cpp
- Source/Android/jni/AndroidCommon/IDCache.h
- Source/Android/jni/MainAndroid.cpp
- Source/Core/Common/Logging/LogManager.cpp
- Source/Core/Common/Logging/LogManager.h
Implements https://bugs.dolphin-emu.org/issues/10709.
> Android: Add Log Configuration to UI

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
We want `(Tv)MainActivity` to rescan the game library during `onResume` but doing so after emulation or simply leaving `SettingsActivity` is useless.
> Android: Settings and Emulation activities skip (Tv)MainActivity library rescan

- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/RenderBase.h
This is now unused. Seems like it was an improper fix (there would be a race if saving the screenshot took longer than 2 seconds) back when it was used too.
> Remove wait_for_completion parameter from Renderer::SaveScreenshot

- Source/Android/app/build.gradle
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsViewModel.java
Just for maintainability. This is a shorter and more standard solution compared to our current one where the Fragment persists the Settings and passes it to the Activity.
> Android: Persist Settings using ViewModel

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentView.java
All of these have non-static equivalents (`mView` and `mClickedItem`).
> Android: Remove some static variables from SettingsAdapter

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java
Fixes https://bugs.dolphin-emu.org/issues/10815 and the behavior where the settings activity would go back to the top-level menu after switching to a different app and back.
> Android: Fix SettingsActivity lifecycle management

- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/InputCommon/ControlReference/FunctionExpression.cpp
Someone [on the forums](https://forums.dolphin-emu.org/Thread-feature-request-thread?pid=510144#pid510144) requested trigonometric functions to be added, so I figured might as well, easy enough. Also added a few more functions that seemed useful.
> Add a few input expression functions (trigonometry, sqrt, pow, min, max, clamp)

- Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
FCVT doesn't necessarily round to zero, so the result might be inaccurate if we use it. To ensure correct rounding, we use FCVTS from double FPR to 32-bit GPR. Unfortunately, FCVTS can't do double FPR to single FPR.
This is my first time making a JitArm64 PR, so apologies if the change doesn't make sense :)
> JitArm64: Avoid double rounding in fctiwzx

- Source/Core/Core/DSP/Jit/x64/DSPJitBranch.cpp
- Source/Core/Core/DSP/Jit/x64/DSPJitMultiplier.cpp
- Source/Core/Core/DSP/Jit/x64/DSPJitRegCache.cpp
See commit messages for details.
> DSPJit: Various minor improvements

- Source/Core/DolphinQt/Main.cpp
On an application's first launch on macOS, a command line option matching the format "-psn_X_XXXXXX" is passed. This is to set the ["ProcessSerialNumber", something used by the legacy Process Manager from Carbon](https://web.archive.org/web/20040705133028/developer.apple.com/documentation/Carbon/Reference/Process_Manager/prmref_main/data_type_5.html). optparse recognizes it as an unknown option and immediately quits, so the application appears to crash.
This PR makes DolphinQt ignore the "-psn" command line option if it's found.
> DolphinQt: Ignore "-psn" command line option on macOS

- Source/Core/DolphinQt/MainWindow.cpp
_Extremely_ minor UI tweak. Without this PR, the sheet would be attached to MainWindow and macOS would change the focused window to it. Always kinda annoyed me.
> MainWindow: Attach quit emulation sheet to RenderWidget if shown on macOS

- Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
- Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
We can avoid MOVAPS in a few places by taking advantage of AVX or by realizing when we can write the result directly into the target register.
I've only been able to find one game that uses ps_sel at all (Mario Kart Wii). If anyone knows of any others, please let me know.
---
**fsel with AVX**
Before:
```
66 0F 57 C0          xorpd       xmm0,xmm0
F2 41 0F C2 C6 06    cmpnlesd    xmm0,xmm14
41 0F 28 CE          movaps      xmm1,xmm14
66 41 0F 38 15 CA    blendvpd    xmm1,xmm10,xmm0
F2 44 0F 10 F1       movsd       xmm14,xmm1
```
After:
```
66 0F 57 C0          xorpd       xmm0,xmm0
F2 41 0F C2 C6 06    cmpnlesd    xmm0,xmm14
C4 C3 09 4B CA 00    vblendvpd   xmm1,xmm14,xmm10,xmm0
F2 44 0F 10 F1       movsd       xmm14,xmm1
```
---
**ps_sel with AVX**
Before:
```
66 0F 57 C0          xorpd …
```
> Jit64: Avoid unnecessary MOVAPS instructions

- Source/Core/DolphinQt/CMakeLists.txt
- Source/Core/DolphinQt/Config/ControllerInterface/DualShockUDPClientAddServerDialog.cpp
- Source/Core/DolphinQt/Config/ControllerInterface/DualShockUDPClientAddServerDialog.h
- Source/Core/DolphinQt/Config/ControllerInterface/DualShockUDPClientWidget.cpp
- Source/Core/DolphinQt/Config/ControllerInterface/DualShockUDPClientWidget.h
- Source/Core/DolphinQt/Config/ControllerInterface/ServerStringValidator.cpp
- Source/Core/DolphinQt/Config/ControllerInterface/ServerStringValidator.h
- Source/Core/DolphinQt/DolphinQt.vcxproj
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.h
- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPProto.h
This review allows support for multiple DSU servers, needed if you want to use a motion controller and a separate head tracking source (#8747)
Also, master made some assumptions about the name of the controller.  It basically copied what DS4Windows used, where the "Mode" dictated the controller name.  However, [this documentation](https://v1993.github.io/cemuhook-protocol/) is more flexible and is what is used in this PR.  This means mode is now just how much gyro functionality the server supports.  So where does the "name" of the device come from?
It is now based on the server's description for the server added in the "Add New DSU Server" configuration window.
> DolphinQt / InputCommon - Support multiple DSU servers

- Source/Core/Core/PatchEngine.cpp
- Source/Core/Core/PowerPC/MMU.cpp
HostIsInstructionRAMAddress uses XCheckTLBFlag::OpcodeNoException, so we should also use XCheckTLBFlag::OpcodeNoException when reading, to ensure that we use the IBAT (as opposed to the DBAT) for both.
I made this change in an attempt to fix a crash a user was experiencing at PatchEngine.cpp:234, but it seems like this change didn't actually fix that crash. I'm submitting it anyway because the mismatched behavior we have right now seems a little odd.
> PatchEngine: Attempt to fix crash in IsStackSane

- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/VolumeVerifier.h
When I first made VolumeVerifier, I figured that the distinction between an unsigned ticket and an unsigned TMD was a technical detail that users would have no reason to care about. However, while this might be true for discs, it isn't equally true for WADs, due to the widespread practice of fakesigning tickets to set the console ID to 0. This practice does not require fakesigning the TMD (though apparently people do it anyway, at least sometimes...), and the presence of a correctly signed TMD is a useful indicator that the contents have not been tampered with, even if the ticket isn't correctly signed.
> VolumeVerifier: Split TMD error from ticket error for WADs

- Source/Core/Core/HW/WiimoteEmu/Extension/Classic.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Classic.h
- Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Drums.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Drums.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Extension.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Extension.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.h
- Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.h
- Source/Core/Core/HW/WiimoteEmu/Extension/Turntable.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/Turntable.h
- Source/Core/Core/HW/WiimoteEmu/Extension/UDrawTablet.cpp
- Source/Core/Core/HW/WiimoteEmu/Extension/UDrawTablet.h
- Source/Core/Core/HW/WiimoteEmu/MotionPlus.cpp
- Source/Core/Core/HW/WiimoteEmu/MotionPlus.h
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
A real Wii remote only initiates reconnection on press of one of its own buttons, not any extensions.
This eliminates some code and it's more accurate.
> WiimoteEmu: Don't check extension button press for Wii remote reconnection.

- Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
I was hoping this would improve the performance of Cars 2 by avoiding interpreter fallbacks, but it doesn't seem to have made any measurable impact.
> Jit64: Implement low DCBZ hack

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/jni/MainAndroid.cpp
Long sequences of JNI calls are both hard to read and slow.
> Android: Rewrite GetRenderSurfaceScale in Java

- Source/Core/Core/Boot/Boot.cpp
- Source/Core/Core/HW/DVD/DVDInterface.cpp
- Source/Core/Core/HW/DVD/DVDInterface.h
- Source/Core/Core/HW/DVD/DVDThread.cpp
- Source/Core/Core/HW/ProcessorInterface.cpp
- Source/Core/Core/IOS/DI/DI.cpp
- Source/Core/Core/IOS/MIOS.cpp
- Source/Core/Core/State.cpp
Fixes [issue 9019](https://bugs.dolphin-emu.org/issues/9019).
The problems:
* Changing a disc reset the drive state completely (which was something I added in 55a88ba2ed).  This included the DI registers, meaning interrupts would no longer be sent (so the drive errors that were supposed to be sent in that case just weren't making it anywhere).  Now it only resets "internal" properties.  I don't know if this is 100% accurate behavior (and I only changed it for disc changes; other places that reset it were not changed)
* Although that allowed games to detect disc errors if they happened on e.g. request stream status, they still didn't care about errors on the read command (which are far more likely).  This happened to be because games look at `DILENGTH`, and if it's 0 they assume the read …
> Fix gamecube games not noticing disc changes

- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayBrowser.h
It was possible to enter a deadlock when the **NetPlay Session Browser** dialog was closed while a refresh was still ongoing.
**Reproduction steps:**
- Launch Dolphin.
- Open the **NetPlay Session Browser** dialog via **Tools > Browse NetPlay Sessions...**.
- Press `ESC` as soon as the dialog pops up, so it is dismissed straight away.
- Dolphin will (potentially) deadlock.
Stacktrace (Release build):
```
Thread 1 (Thread 0x7f3f319e6080 (LWP 4361)):
#0  0x00007fa6be274d2d in __GI___pthread_timedjoin_ex (threadid=140352865023744, thread_return=0x0, abstime=0x0, block=<optimised out>) at pthread_join_common.c:89
#1  0x00007fa6bdfa0933 in std::thread::join() () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000055c4f2f996ea in NetPlayBrowser::~NetPlayBrowser() ()
#3  0x000055c4f2f99799 in …
```
> DolphinQt: Prevent deadlock when exiting the NetPlay Session Browser dialog

- Source/Core/Core/HW/WiimoteCommon/WiimoteReport.h
Prevents the following, which appears to be bogus:
```
Wiimote.cpp(343): error C2220: the following warning is treated as an error
Wiimote.cpp(343): warning C4789: buffer 'rpt' of size 1 bytes will be overrun; 2 bytes will be written starting at offset 0
```
After some experimenting, it appears to be a fairly hard to hit edge case (as also evidenced by the fact that no code in the rest of dolphin triggers it). It has to do with the /permissive- flag and the exact way the struct is declared, concerning the ordering of named/unnamed fields. It also only repros on unoptimized builds (e.g. dolphin's Debug target).
Afterwards (and with Qt 5.15.0), dolphin builds fine on current msvc: `Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111`
> msvc: temporary workaround for C4789 false positive

- Externals/ed25519/ed25519.vcxproj
- Externals/imgui/imgui.vcxproj
- Externals/picojson/picojson.vcxproj
prevents the source dirs becoming dirty to git / causes log files to be placed correctly.
> vs/msbuild: fix the build generating log files in source dirs

- Source/Core/Core/Debugger/PPCDebugInterface.cpp
- Source/Core/DiscIO/Volume.h
- Source/Core/DiscIO/VolumeWii.cpp
- Source/Core/DiscIO/WIABlob.cpp
- Source/Core/DolphinQt/Debugger/ThreadWidget.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.cpp
- Source/Core/InputCommon/ControllerEmu/StickGate.cpp
This works around some GCC bugs:
- [-Wshadow warns three times when a constructor parameter shadows a data member](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78147)
- [std::optional can trigger bogus -Wmaybe-uninitialized warnings](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635)
> Fix some more GCC warnings

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
The default values need to match the default values defined in C++.
> Android: Fix defaults for WiimoteContinuousScanning/EnableSpeaker

- Source/Core/Common/ArmCPUDetect.cpp
- Source/Core/Core/MachineContext.h
- Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
This PR adds support for ARM64 on FreeBSD. Dolphin already supported ARM64 on Linux and Windows and FreeBSD x86_64 independently but lacked support for the combination of the two, which might be useful for people running FreeBSD on Raspberry Pi 3 and 4.
To get Dolphin to compile, two things had be fixed:
* `asm/hwcap.h`/`getauxval()` does not exist on FreeBSD. Instead FreeBSD has `elf_aux_info()` since FreeBSD 12.0: https://reviews.freebsd.org/rS324815. The two functions have a slightly different interface but work morally the same.
* FreeBSD/ARM64 was missing from `MachineContext.h`. From The `mcontext_t` definition (see https://github.com/freebsd/freebsd/blob/master/sys/arm64/include/ucontext.h#L62):
- `gp_elr` is equivalent of `PC` (see [arm …
> Add support for FreeBSD/arm64

- Source/Core/Core/MemoryWatcher.cpp
This prevents Dolphin from crashing when a structure specified in `Locations.txt` is yet to be initialized.
> MemoryWatcher: Do not follow invalid pointers

- Source/Core/DiscIO/Blob.h
- Source/Core/DiscIO/DirectoryBlob.cpp
- Source/Core/DiscIO/DirectoryBlob.h
- Source/Core/DiscIO/VolumeWii.cpp
- Source/Core/DiscIO/WIABlob.cpp
- Source/Core/DiscIO/WIABlob.h
- Source/Core/DiscIO/WiiEncryptionCache.cpp
It's possible (but rare) for a WIA or RVZ file to support this for some partitions but not all, and for the game and the blob code to disagree on how large a partition is.
> DiscIO: Add parameters to BlobReader::SupportsReadWiiDecrypted

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/jni/MainAndroid.cpp
Previously, the GCAdapter scanning thread would only be started if the GameCube adapter was enabled when starting the app. That's obviously a problem.
> Android: Better GCAdapter scanning thread management

- Source/Core/Core/IOS/USB/Host.cpp
- Source/Core/Core/IOS/USB/Host.h
- Source/Core/Core/IOS/USB/OH0/OH0.cpp
- Source/Core/Core/IOS/USB/OH0/OH0.h
- Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp
- Source/Core/Core/IOS/USB/USB_HID/HIDv4.h
- Source/Core/Core/IOS/USB/USB_HID/HIDv5.cpp
- Source/Core/Core/IOS/USB/USB_HID/HIDv5.h
- Source/Core/Core/IOS/USB/USB_VEN/VEN.cpp
- Source/Core/Core/IOS/USB/USB_VEN/VEN.h
This moves the scan thread logic and variables into a separate
ScanThread class. By turning ScanThread instances into members of the
most derived class, this ensures that the scan thread is always
properly stopped when the most derived class is destructed and fixes
a race condition that could cause the scan thread to call virtual
member functions from a derived class whose members have already
been destructed.
> IOS/USB: Move scan thread logic into a separate class

- Source/Core/DiscIO/WIABlob.cpp
The heuristic was not allocating enough space for Metroid: Other M, at least when using the default settings. (This didn't break the file, it just caused some headers to be placed at the end of the file instead of at the start and wasted a few hundred kilobytes.)
> DiscIO: Adjust WIA/RVZ header size heuristic

- Data/Sys/GameSettings/GC6E01.ini
- Data/Sys/GameSettings/GC6J01.ini
- Data/Sys/GameSettings/GC6P01.ini
- Data/Sys/GameSettings/GXXE01.ini
- Data/Sys/GameSettings/GXXJ01.ini
- Data/Sys/GameSettings/GXXP01.ini
I think the [last Progress Report](https://dolphin-emu.org/blog/2020/07/05/dolphin-progress-report-may-and-june-2020/) sums this up pretty well:
> Note: These fixes do not affect Pokemon Colosseum and Pokemon XD's save issues regarding savestates. They have purposeful memory card checks to prevent the duping of Pokemon. Unlike the previous problem, which was more of an emulation oversight, this one is something that should be solved through a game patch. Currently no one is investigating this issue and you should be wary of using savestates with these games. If someone does write a patch or a cheat for this issue, we will be happy to include it with the game's INI file for easy access to users.
These are the relevant patches.
I have not thoroughly tested this yet except for the simple …
> GameSettings: Add patches for Pokémon Colosseum and Pokémon XD to circumvent the check that the save being overwritten matches the last known save.

- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/VideoBackends/D3D/VideoBackend.h
- Source/Core/VideoBackends/D3D/main.cpp
- Source/Core/VideoBackends/D3D12/VideoBackend.cpp
- Source/Core/VideoBackends/D3D12/VideoBackend.h
- Source/Core/VideoBackends/Null/VideoBackend.h
- Source/Core/VideoBackends/OGL/VideoBackend.h
- Source/Core/VideoBackends/OGL/main.cpp
- Source/Core/VideoBackends/Software/SWmain.cpp
- Source/Core/VideoBackends/Software/VideoBackend.h
- Source/Core/VideoBackends/Vulkan/VideoBackend.h
- Source/Core/VideoCommon/VideoBackendBase.cpp
- Source/Core/VideoCommon/VideoBackendBase.h
Fixes https://bugs.dolphin-emu.org/issues/12245.
I considered making a change to DolphinQt instead of the core, but then additional effort would've been required to add the same fix to the Android GUI once we start using the new config system there.
> Make default graphics backend not show up as empty

- Source/Core/DiscIO/TGCBlob.cpp
- Source/Core/DiscIO/TGCBlob.h
- Source/Core/DolphinQt/GameList/GameList.cpp
Fixes https://bugs.dolphin-emu.org/issues/10654.
To quote the documenation file included with the program tgctogcm:
> TGC's are miniaturized .gcm images with a 32kB header.
> The embedded gcm contains some bogus data, namely:
> -FST Location (0x424 in gcm)
> -DOL Location (0x420 in gcm)
> -FST File offsets (all files are offset/spoofed by a certain amount)
Dolphin has been handling the values at 0x420 and 0x424 by simply overwriting them with a working value (just like tgctogcm does), but it has used a different approach for the file offsets in the FST. Instead of changing the offsets that are stored in the FST, Dolphin changed where the files actually are placed on the virtual disc. My hope was that this would make the loading times more accurate to how they are when running a TGC file …
> DiscIO: Rework the implementation of TGC reading

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
`saveControlPosition` was not applying the `_H` part of the key. Fixes https://bugs.dolphin-emu.org/issues/12120.
> Android: Fix saving Horizonal Wii Remote overlay A/B/1/2 positions

- Source/Core/Core/HW/DVD/DVDInterface.cpp
Hardware tested using cached reads.
Fixes Ed, Edd n Eddy (untested). https://bugs.dolphin-emu.org/issues/10373
> DVDInterface: Increase the latency for read commands

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/view/FilePicker.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/FilePickerViewHolder.java
The reason why the finish() call was added no longer exists. (Also, there was never a duplicate SettingsActivity as far as I can tell, only a duplicate SettingsFragment.)
Split out from PR #8975.
> Android: Make FilePicker act like a normal setting

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityView.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/AfterDirectoryInitializationRunner.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java
This centralizes the code for showing the `write_permission_needed` and `external_storage_not_mounted` toasts. Split out from PR #8962.
> Android: Optional AfterDirectoryInitializationRunner failure message

- Source/Core/AudioCommon/AudioCommon.cpp
- Source/Core/Core/HW/AudioInterface.cpp
- Source/Core/Core/HW/AudioInterface.h
- Source/Core/Core/HW/DVD/DVDInterface.cpp
In particular, I wanted to do change this in AudioInterface::Init so that dumped GC audio doesn't need to have a file split (changing from 32000 Hz to 32029 Hz) when the emulated software initializes the AI registers. I've also made the same change to DI's DTK code.
> AudioInterface: Use 32029/48043 Hz in more places

- Source/Core/Core/Analytics.cpp
- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/Config/MainSettings.h
- Source/Core/Core/Config/UISettings.cpp
- Source/Core/Core/Config/UISettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/Core/ConfigManager.cpp
- Source/Core/Core/ConfigManager.h
- Source/Core/DolphinQt/GameList/GameTracker.cpp
- Source/Core/DolphinQt/Main.cpp
- Source/Core/DolphinQt/Settings.cpp
- Source/Core/DolphinQt/Settings/InterfacePane.cpp
- Source/Core/DolphinQt/Settings/PathPane.cpp
- Source/Core/UICommon/UICommon.cpp
- Source/Core/VideoCommon/OnScreenDisplay.cpp
Split out from the Android PR #8975.
Other than the controller settings and JIT debug settings, these are the only settings which were defined in Java code but not defined in the new config system in C++. (There are still a lot of settings that are defined in the new config system but not yet saveable in the new config system, though.)
> Port some settings to the new config system

- Source/Core/Core/HW/ProcessorInterface.cpp
Fixes [bug 12241](https://bugs.dolphin-emu.org/issues/12241).  I did a quick hardware test, and it doesn't seem like writes to it actually do anything in Wii mode; IOS reads still return normally and the drive didn't make any noises that sound like it was reset (unlike when resetting it through IOS).  I'm guessing Project M's write to it is just a leftover.
I did notice a different oddity, though: even though I always wrote with bit 1 set, reading back never had bit 1 set.  Also, bit 2 was set by the time HBC loaded my code.  That should be investigated further (along with behavior in GameCube compatibility mode, and behavior on actual GameCubes).  So, there's probably further behavior that could be emulated, but this still seems to be accurate.
I've tested and confirmed that this does …
> Ignore PI_RESET_CODE resetting DI in Wii mode

- Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
- Source/Core/VideoCommon/DriverDetails.cpp
- Source/Core/VideoCommon/DriverDetails.h
It's broken and causes spectacular artifacts and crashes. Here's an example of what those look like: ![](https://dolphin-emu.org/m/user/blog/progress-report/2018-november/gputexturedecoding-melee_thumb.jpg)
I don't know if the problem has been fixed upstream in MoltenVK. If someone else wants to look into that, by all means, I lack the in-depth knowledge of the video backends to do that myself. In the meantime this seems like a reasonable solution to most of the reports of crashes when using Vulkan on MacOS, due to users not being aware the feature is broken.
> VideoBackends: Disable GPU Texture Decoding under MoltenVK

- Source/Core/Core/HW/WiimoteReal/IOWin.cpp
Prevents BluetoothApis.dll being continuously loaded/unloaded which is 1) very annoying during debugging 2) probably somewhat of a speed hit.
> windows: keep an extra reference to BluetoothApis.dll

- Source/Core/DolphinQt/Config/Graphics/GraphicsBool.cpp
- Source/Core/DolphinQt/Config/Graphics/GraphicsChoice.cpp
- Source/Core/DolphinQt/Config/Graphics/GraphicsInteger.cpp
- Source/Core/DolphinQt/Config/Graphics/GraphicsRadio.cpp
- Source/Core/DolphinQt/Config/Graphics/GraphicsSlider.cpp
- Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
- Source/Core/DolphinQt/Debugger/CodeWidget.cpp
- Source/Core/DolphinQt/Debugger/JITWidget.cpp
- Source/Core/DolphinQt/Debugger/MemoryWidget.cpp
- Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
- Source/Core/DolphinQt/Debugger/RegisterWidget.cpp
- Source/Core/DolphinQt/Debugger/ThreadWidget.cpp
- Source/Core/DolphinQt/Debugger/WatchWidget.cpp
- Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
- Source/Core/DolphinQt/GameList/GameTracker.cpp
- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/Settings/PathPane.cpp
- Source/Core/DolphinQt/Settings/WiiPane.cpp
- Source/Core/DolphinQt/ToolBar.cpp
When destroying a Dolphin "graphics" control, we were still connected to the settings ConfigChange event.  That was causing a segfault.
This is not required by any current Dolphin code but is used in #8823
> DolphinQt: properly remove slot connection for ConfigChange when object is destructed

- Source/Core/Core/Core.h
- Source/Core/Core/HW/Wiimote.cpp
- Source/Core/Core/HW/Wiimote.h
- Source/Core/Core/HW/WiimoteCommon/DataReport.cpp
- Source/Core/Core/HW/WiimoteCommon/DataReport.h
- Source/Core/Core/HW/WiimoteCommon/WiimoteConstants.h
- Source/Core/Core/HW/WiimoteCommon/WiimoteHid.h
- Source/Core/Core/HW/WiimoteCommon/WiimoteReport.h
- Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/Core/HW/WiimoteReal/IOLinux.cpp
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
- Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp
- Source/Core/Core/IOS/USB/Bluetooth/BTEmu.h
- Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp
- Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.h
- Source/Core/Core/IOS/USB/Bluetooth/hci.h
- Source/Core/Core/State.cpp
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.cpp
Cleaned up L2CAP channel establishment in `WiimoteDevice`.
When the ACL connection originates from the Wii it will establish HID channel connections but our `WiimoteDevice` was simultaneously doing so causing problems.
ACL connection establishment is less hacky now as well.
Cleaned up our "fake" inquiry response in BTEmu.
There were a few issues there.
Now only configured remotes will respond to an inquiry.
All of that fixes Wii remote reconnection in the home menu (issue: https://bugs.dolphin-emu.org/issues/11974)
Reconciled some duplicate HID logic in Emu and Real Wiimote code.
Introduced a `HIDWiimote` interface for `WiimoteDevice` to talk to either a real or emulated source.
General cleanups in related code.
Eliminated remnants of the Wii Remote "Plugin".
Advanced save state version …
> BTEmu/Wiimote: Fixes and Cleanups.

- Source/Core/DolphinQt/Settings/AdvancedPane.cpp
Using the local time zone doesn't make any sense, as the RTC does not have a time zone field. It just results in the actual time being offset from what is entered in the settings.
> Qt/AdvancedPane: Force UTC time for custom RTC entry

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
The only place where initTouchPointer was called automatically was Host_RequestRenderWindowSize, which is called at least once after emulation start, but not after activity recreation.
> Android: Fix touch pointer not working after activity recreation

- Source/Core/DolphinQt/Config/LogWidget.cpp
- Source/Core/DolphinQt/Settings.cpp
This should give us a nicer font on Windows, while also not severely impacting the existing behavior on Linux.
At least on my Linux system, it actually results in using the monospace font I have configured (which is "Hack").
Before ("Monospace")
After ("Hack")
> Qt: Use better method of getting default monospace font

- Source/Core/DolphinQt/RenderWidget.cpp
why are there so many ways to trigger this issue
> DolphinQt: Fix the panic alert deadlock, Pause on Focus Loss edition

- Source/Core/Core/Core.cpp
Fixes a crash on Android (probably nogui too?) caused by PR #8985:
```
std::__ndk1::__throw_out_of_range(char const*) stdexcept:265
std::__ndk1::__vector_base_common<true>::__throw_out_of_range() const vector:319
InputConfig::GetController(int) InputConfig.cpp:160
WiimoteCommon::GetHIDWiimoteSource(unsigned int) Wiimote.cpp:71
IOS::HLE::WiimoteDevice::WiimoteDevice(IOS::HLE::Device::BluetoothEmu*, int, std::__ndk1::array<unsigned char, 6ul>) WiimoteDevice.cpp:71
IOS::HLE::Device::BluetoothEmu::BluetoothEmu(IOS::HLE::Kernel&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) BTEmu.cpp:64
IOS::HLE::Kernel::AddStaticDevices() IOS.cpp:435
IOS::HLE::Init() IOS.cpp:837
Core::EmuThread(std::__ndk1::unique_ptr<BootParameters, …
```
> Core: Run Wiimote::Initialize before HW::Init to avoid crash

- Source/Core/VideoCommon/VideoBackendBase.cpp
Adding AmdPowerXpressRequestHighPerformance
This will allow AMD drivers to detect the request to use the dGPU instead of the iGPU on compatible hybrid graphics systems.
Reference: https://community.amd.com/thread/169965
> Adding AmdPowerXpressRequestHighPerformance

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
...instead of waiting for it after launching EmulationActivity. We need this because there is code that runs very early in EmulationActivity that accesses the settings.
> Android: Wait for initialization before launching EmulationActivity

- Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp
- Source/Core/Core/IOS/USB/Bluetooth/BTEmu.h
- Source/Core/Core/State.cpp
The member `m_ctrl_setup` here never has a value outside of one function.
It has no business as a member variable or being saved to state.
> Core/BTEmu: Change a member variable to a local variable.

- Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp
- Source/Core/InputCommon/ControllerInterface/evdev/evdev.h
Some off-brand devices always report the same unique ID, resulting in them being wrongly combined. The physical location for these devices should always be different, making that a better comparison. I'm currently unsure whether the DS4's devices (the original target of the combining behavior in #8473) all have the same physical location, but theoretically they should.
> ControllerInterface: Combine evdev devices with the same physical location in addition to unique ID

- Data/Sys/GameSettings/HAG.ini
I think #9093 attempted to fix https://bugs.dolphin-emu.org/issues/11198. This problem dealt with XFB, not EFB.
> Properly fix News Channel loading screen

- Source/Core/VideoCommon/FramebufferManager.cpp
> FramebufferManager: Fix EFB readbacks with MSAA on

- Source/Core/Core/HW/GCPadEmu.cpp
- Source/Core/Core/HotkeyManager.cpp
Hotfix for #8428.
`@(Shift+1)` hotkey expression needed 1 to be backticked.
The `fmt::format` string for Wii Remote hotkeys was bad.
Made default modifier mappings cleaner.
> Core: Unbreak default keyboard mappings.

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
Apparently there's no good alternative before `setMin` was implemented for dealing with minimums less than 0.
> Android: seekbar.setMin requires API level 26

- Data/Sys/Profiles/Wiimote/Wii Remote with MotionPlus Pointing.ini
- Source/Core/Common/MathUtil.h
- Source/Core/Core/HW/WiimoteEmu/Camera.cpp
- Source/Core/Core/HW/WiimoteEmu/Camera.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.cpp
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.h
I've measured the field of view of Nintendo Wii Remote IR cameras (original and "MotionPlus Inside") using the known distance of a sensor bar with LEDs of known separation and trigonometry!
It comes out at 42 degrees horizontally by 31.5 vertically.
This is an increase from the 33 by 23 guess we took from Wiibrew.
Increasing the FOV on the emulated camera makes `IMUPointer`'s simulated sensor bar pointing noticeably less sensitive.
Many users complained it was too sensitive. Gyro pointing should more closely match IR pointing now.
We could potentially expose the FOV as an adjustable setting.
Even though it shouldn't ever change it would allow adjusting the sensitivity of gyro pointing.
Point's "Total Yaw" and "Total Pitch" settings must be increased to compensate for the higher FOV to …
> WiimoteEmu: Increase camera FOV to match that of a real Wii remote.

- Source/Core/InputCommon/InputConfig.cpp
A very early call to Config::Save is now creating empty controller INI files.
https://bugs.dolphin-emu.org/issues/12283
> Fix controller defaults being empty on fresh run

- Source/Core/Core/IOS/Network/Socket.cpp
This PR is an attempt to fix a crash when running tests for https://github.com/dolphin-emu/dolphin/pull/8758 on macOS.
> Socket: Set SO_NOSIGPIPE on macOS

- Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
VK_LAYER_LUNARG_standard_validation is deprecated.
Tiny change, probably not useful to anyone unless they're debugging the Vulkan backend. But I had to make the change the other day (later versions of the validation layer drop the old name), so we may as well keep it upstream.
> Vulkan: Use VK_LAYER_KHRONOS_validation for validation

- Externals/MoltenVK/version.txt
Needs testing as my mac environment is not usable at the moment.
> Externals: Update MoltenVK to v1.1

- Source/Core/DolphinQt/NKitWarningDialog.cpp
Unlike Super Paper Mario, this game doesn't crash as soon as you try to start it, but rather if you try to skip a certain cutscene. Thanks to @JMC47 for letting me know about this.
> Add Metal Gear Solid: The Twin Snakes to NKit warning message

- Source/Core/Core/GeckoCodeConfig.cpp
> Replace geckocodes.org with mirror codes.rc24.xyz

- Source/Android/app/src/main/res/values/arrays.xml
Until now, when screen orientation is set to Landscape, the emulation activity will be fixed on a 90 degrees rotated position. 
This pull request aims at allowing 90 and 270 degrees landscape rotations, based on sensor data (independently of user android settings).
Controllers like the Gamesir X2, which have a USB Type-C port on the left will force the phone to a 270 degrees rotated state, so this is useful for those users (like me).
> Android: add reverse landscape to screen orientation settings

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/AlertMessage.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
- Source/Android/app/src/main/res/values/strings.xml
- Source/Android/jni/AndroidCommon/IDCache.cpp
- Source/Android/jni/MainAndroid.cpp
- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
Fixes https://bugs.dolphin-emu.org/issues/7988
Fixes https://bugs.dolphin-emu.org/issues/10770
As far as I can tell, this works (even with multiple panic alerts in quick succession) but there are some things that I'm not sure I've done properly:
- ~~Did I properly handle AlertMessages while booting the core?~~
- ~~Since `NativeLibrary.displayAlertMsg` has a lock object, pausing emulation while waiting on the lock would freeze AlertMessages after rotating the screen. As far as I can tell, pausing emulation here seems unnecessary but correct me if I'm wrong.~~
Test case was https://bugs.dolphin-emu.org/issues/11424
> Android: Use DialogFragment for AlertMessage

- Source/Core/AudioCommon/AudioStretcher.cpp
A user said Citra's sound stretching sounding much better than ours.
Looking at their code about the only difference was some explicit settings in Dolphin.
https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/AudioCommon/AudioStretcher.cpp
https://github.com/citra-emu/citra/blob/master/src/audio_core/time_stretch.cpp
It looks like the default "sequence" and "seek window" adjust automatically with the tempo, maybe?
> By default, this setting value is calculated automatically according to tempo value.
https://www.surina.net/soundtouch/README.html
The user said this change improved audio stretching.
I don't know if I can tell a difference one way or the other.
Please test.
> AudioStretcher: Keep default parameters.

- Source/Core/DiscIO/WIABlob.cpp
- Source/Core/DiscIO/WIACompression.cpp
- Source/Core/DiscIO/WIACompression.h
By calling `ZSTD_CCtx_setPledgedSrcSize`, we can let zstd know how large a chunk is going to be before which start compressing it, which lets zstd avoid allocating more memory than needed for various internal buffers. This greatly reduces the RAM usage when using a high compression level with a small chunk size, and doesn't have much of an effect in other circumstances.
A side effect of calling `ZSTD_CCtx_setPledgedSrcSize` is that zstd by default will write the uncompressed size into the compressed data stream as metadata. In order to save space, and since the decompressed size can be figured out through the structure of the RVZ format anyway, we disable writing the uncompressed size by setting `ZSTD_c_contentSizeFlag` to 0.
> DiscIO: Decrease RAM usage during zstd compression

- Source/Core/DiscIO/WIACompression.cpp
Noticed missing include as a build failure on gcc-11:
```
[ 26%] Building CXX object Source/Core/DiscIO/CMakeFiles/discio.dir/WIACompression.cpp.o
../../../../Source/Core/DiscIO/WIACompression.cpp: In lambda function:
../../../../Source/Core/DiscIO/WIACompression.cpp:170:31: error: 'numeric_limits' is not a member of 'std'
170 |         std::min<size_t>(std::numeric_limits<unsigned int>().max(), x));
|                               ^~~~~~~~~~~~~~
../../../../Source/Core/DiscIO/WIACompression.cpp:170:46: error: expected primary-expression before 'unsigned'
170 |         std::min<size_t>(std::numeric_limits<unsigned int>().max(), x));
|                                              ^~~~~~~~
```
> Source/Core/DiscIO/WIACompression.cpp: add missing <limits> include

- Source/Core/DolphinQt/CMakeLists.txt
- Source/Core/DolphinQt/DolphinQt.vcxproj
- Source/Core/DolphinQt/TAS/GCTASInputWindow.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.cpp
- Source/Core/DolphinQt/TAS/TASInputWindow.h
- Source/Core/DolphinQt/TAS/TASSlider.cpp
- Source/Core/DolphinQt/TAS/TASSlider.h
- Source/Core/DolphinQt/TAS/WiiTASInputWindow.cpp
This is a feature which existed in DolphinWX. Seems like it got implemented in DolphinQt for IRWidget/StickWidget but not sliders.
> DolphinQt: Reset TAS input slider to default on right-click

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AdHocBooleanSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/FloatSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/NativeConfig.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java
- Source/Android/jni/NativeConfig.cpp
During emulation, when `LocalGame` has a value but `CurrentRun` doesn't, we want to read from `LocalGame`, not `CurrentRun`. This change exposes a `LAYER_ACTIVE` option that handles this correctly.
> Android: Fix setting read during play with local game layer active

- Source/Core/DolphinQt/QtUtils/ParallelProgressDialog.h
> Qt/QtUtils: Fix accidental recursion in ParallelProgressDialog

- Source/Core/VideoCommon/LightingShaderGen.cpp
- Source/Core/VideoCommon/LightingShaderGen.h
- Source/Core/VideoCommon/VertexShaderGen.cpp
Continues the fmt migration by migrating these two generators over. Both were done at the same time, since the vertex shader generator relied on some defines that the lighting shader generator used.
> LightingShaderGen/VertexShaderGen: Migrate over to fmt

- Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
This PR builds upon optimizations introduced in pull request #8992, which were only applied to the packed variant of this instruction. As it turns out, these optimizations can also be applied to the non-packed variant when the destination register and a specific input register match. Luckily, according to my testing, this happens to be the case most of the time in games that use this instruction.
---
**fsel (AVX)**
Before:
```
66 0F 57 C0          xorpd       xmm0,xmm0
F2 41 0F C2 C6 06    cmpnlesd    xmm0,xmm14
C4 C3 09 4B CA 00    vblendvpd   xmm1,xmm14,xmm10,xmm0
F2 44 0F 10 F1       movsd       xmm14,xmm1
```
After:
```
66 0F 57 C0          xorpd       xmm0,xmm0
F2 41 0F C2 C6 06    cmpnlesd    xmm0,xmm14
C4 43 09 4B F2 00    vblendvpd   xmm14,xmm14,xmm10,xmm0
```
---
**fsel …
> Jit64: Optimize fsel a bit more

- Source/Core/DolphinQt/Debugger/RegisterWidget.cpp
This PR fixes the display of DBAT and IBAT registers past register 3 which is currently broken.  Behavior can be verified by running some code to put a value in SPR 570 which will update DBAT5, however it won't update in the register window. Further, values displayed for IBATs after IBAT3 are actually DBAT values.
The issue is caused by the registers being added using the row index and incrementing all the way up to register 7 when the actual order of DBAT and IBAT registers have a gap between registers 3 and 4. (e.g `SPR_IBAT3L` is 535, but `SPR_IBAT4U` is 560).
> DolphinQt/Debugger: Fix DBAT and IBAT registers in RegisterWidget

- Source/Core/Core/IOS/Network/IP/Top.cpp
This PR adds proper log for `IOCTL_SO_GETHOSTID`.
> IP/Top: Log IOCTL_SO_GETHOSTID properly

- Source/Core/Core/IOS/Network/IP/Top.cpp
This PRs adds the SO_LINGER optname and silents the following message `SO_SETSOCKOPT: unknown optname 128`.
> IP/Top: Add SO_LINGER optname

- CMakeLists.txt
- Languages/update-source-strings.sh
- Source/Android/jni/AndroidCommon/CMakeLists.txt
- Source/Android/jni/CMakeLists.txt
- Source/Core/AudioCommon/CMakeLists.txt
- Source/Core/Common/MsgHandler.h
- Source/Core/DiscIO/CMakeLists.txt
- Source/Core/DiscIO/CompressedBlob.cpp
- Source/Core/DiscIO/DiscExtractor.cpp
- Source/Core/DiscIO/NANDImporter.cpp
- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/WIABlob.cpp
- Source/Core/UICommon/GameFile.cpp
Once nice benefit of fmt is that we can use positional arguments in localizable strings. This a feature which has been requested for the Korean translation of strings like "Errors were found in %zu blocks in the %s partition." and which will no doubt be useful for other languages too.
> DiscIO: Make use of fmt where applicable

- Source/Core/VideoCommon/VertexShaderGen.cpp
Fixes crash from #8981 when using D3D.
> VertexShaderGen: Fix unescaped { in D3D shader.

- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/DolphinNoGUI/PlatformWin32.cpp
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/MainWindow.h
- Source/Core/DolphinQt/Settings/InterfacePane.cpp
- Source/Core/DolphinQt/Settings/InterfacePane.h
- Source/Core/UICommon/UICommon.cpp
- Source/Core/UICommon/UICommon.h
"Inhibit Screensaver During Emulation"
> Config: Expose "DisableScreenSaver" in the UI and default it to true.

- Source/Core/Common/StringUtil.cpp
- Source/Core/Common/StringUtil.h
- Source/Core/DolphinQt/Main.cpp
- Source/Core/WinUpdater/Main.cpp
- Source/VSProps/QtCompile.props
`CommandLineParse` expects UTF-8 strings. (`QApplication`, on the other hand, seems to be designed so that you can pass in the `char**` `argv` untouched on Windows and get proper Unicode handling.)
> DolphinQt: Handle non-ASCII characters in Windows cmd arguments

- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h
- Source/Core/InputCommon/ControllerEmu/StickGate.cpp
- Source/Core/InputCommon/ControllerEmu/StickGate.h
Previously, the closest (by angle) calibration point was set to the distance of the provided input.
This produced slightly wrong calibration that would even draw outside of indicator square.
Clamping was done which hid the problem.
Now calibration is calculated from intersection with a line segment of the last two input values.
This is cleaner and more accurate.
Also the calibration shape is no longer restricted to a convex polygon.
> ControllerEmu: Improve and simplify UpdateCalibrationData.

- Data/Sys/GameSettings/RFN.ini
- Data/Sys/GameSettings/RFP.ini
Refer to [bug 11858](https://bugs.dolphin-emu.org/issues/11858) for details; `EFBToTextureEnable` needs to be disabled for the channels' banners to work right.
> Add INI note for Wii Fit and Wii Fit Plus

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/AfterDirectoryInitializationRunner.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PermissionsHandler.java
Now just a cleanup PR. The original intention of this PR has been split into the mentioned PRs.
> Android: Improve WRITE_EXTERNAL_STORAGE denial

- Source/Core/VideoCommon/FramebufferShaderGen.cpp
Continures the migration of the shader generators over to fmt.
This also converts the generator over to making use of the ShaderCode API, instead of rolling its own by concatenating to an ostringstream, resulting in (in my opinion), nicer to read code.
> FramebufferShaderGen: Migrate over to fmt

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/AdHocStringSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/FloatSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesView.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PicassoUtils.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Rumble.java
- Source/Android/app/src/main/res/values/strings.xml
- Source/Core/Core/Config/UISettings.cpp
- Source/Core/UICommon/GameFile.cpp
In case someone wants to be very careful with how much bandwidth they use or with what data GameTDB.com collects on you. This is already an option in DolphinQt (though in DolphinQt it will switch entirely from using covers to banners when turned off).
> Android: Allow disabling cover downloading

- Source/PCH/pch.h
extracted from #9037 again, we'll see if it builds
> require msvc 19.27.29111 and Windows SDK 10.0.19041

- Source/Core/DiscIO/WiiEncryptionCache.cpp
- Source/Core/DiscIO/WiiEncryptionCache.h
Fixes the following warning:
```
../../../../../../Core\DiscIO/DirectoryBlob.h:156:3: warning: explicitly defaulted move constructor is implicitly deleted [-Wdefaulted-function-deleted]
DirectoryBlobReader(DirectoryBlobReader&&) = default;
^
../../../../../../Core\DiscIO/DirectoryBlob.h:205:22: note: move constructor of 'DirectoryBlobReader' is implicitly deleted because field 'm_encryption_cache' has a deleted move constructor
WiiEncryptionCache m_encryption_cache;
^
```
> DiscIO: Make WiiEncryptionCache moveable

- Source/Core/Core/HW/WiimoteEmu/Camera.cpp
- Source/Core/Core/HW/WiimoteEmu/Camera.h
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
This exposes the previously hardcoded field of view of the camera.
I've located the settings under the Point group of the Motion Input tab as the most common use case will be to adjust the sensitivity of gyroscope-based pointing.
> WiimoteEmu: Expose IR camera FOV to adjust IMU pointing sensitivity. 

- Source/Core/DiscIO/CMakeLists.txt
The "FindLibLZMA.cmake" module in CMake versions prior to 3.14 do not
set an alias like how "Externals/liblzma/CMakeLists.txt" does, so builds
performed using one of those older CMake versions will fail if the
system LZMA library is detected. To fix this, we need to link against
"lzma" instead of "LibLZMA::LibLZMA".
This is an update of #9017, with the zstd build changes removed and the commit message altered to make it more clear what problem it's fixing.
This patch is needed to fix builds on Debian 10 (buster).
> Fix builds with system LZMA when using versions of CMake before 3.14

- Source/Core/DolphinQt/GCMemcardCreateNewDialog.cpp
GUI code should not be directly accessing emulated hardware like this.
As for the CardFlashId value itself... frankly, I don't believe the value itself actually matters in the slightest. I've checked various dumped memory cards of mine and it looks like a completely random set of 12 bytes to me for them, while all my Dolphin-generated cards use either 12 zeros like what I'm using in this PR (which happens when you create a card before launching a game, as g_SRAM is zero-filled before first boot), or the ASCII `DOLPHINSLOTA` as seen [here](https://github.com/dolphin-emu/dolphin/blob/28c0b5338ee4c0ef1fc30c557e27e896c135c1ca/Source/Core/Core/HW/Sram.cpp#L20). Gamecube software does not seem to care what it is -- it probably just matters that the serial in the header is correctly synced with …
> Qt/GCMemcardCreateNewDialog: Use zero values for formatting instead of accessing g_SRAM.

- Source/Core/VideoCommon/DataReader.h
We can make use of if constexpr for cases where booleans will always statically be known at compile-time.
> DataReader: Make use of if constexpr where applicable

- Data/Sys/GameSettings/DPOJ8P.ini
- Data/Sys/GameSettings/DPSJ8P.ini
This pull request adds two new .ini configuration files for game IDs DPSJ8P (Phantasy Star Online Episode I&II Trial Edition) and DPOJ8P (Phantasy Star Online Episode III C.A.R.D. Revolution Trial Edition).
To summarize, both games require the same `SafeTextureCacheColorSamples = 512` configuration to render text more properly. PSO Episode III appears to have or had issues with Immediate XFB, so it is set to `ImmediateXFBEnable = False`.
In addition, the PSO Ep. I&II Trial Edition requires a modem to be present. Since the modem was the only option at the time, the BBA will not be recognized. This requires either a 32-bit patch (80194F40 4182002C, thank you to evilhamwizard) or an Action Replay code (04194F40 4182002C, thank you Sappharad) to bypass the initial screen as outlined on [the …
> Add .ini configuration files for Phantasy Star Online Episode I&II Trial Edition and Episode III Trial Edition

- Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
Unbreaks Windows CMake builds.
> ExpressionParser: Add missing <functional> include

- Source/Core/Core/ARDecrypt.cpp
We can boot the formation of the table off to the compiler at compile-time, rather than building the table at run-time.
> ARDecrypt: Resolve seedtable at compile-time

- Source/Core/Common/CMakeLists.txt
- Source/Core/Common/Common.vcxproj
- Source/Core/Common/Common.vcxproj.filters
- Source/Core/Core/CMakeLists.txt
- Source/Core/Core/Core.vcxproj
- Source/Core/Core/Core.vcxproj.filters
- Source/Core/Core/Debugger/OSThread.cpp
- Source/Core/Core/Debugger/OSThread.h
- Source/Core/Core/Debugger/PPCDebugInterface.cpp
Common shouldn't be depending on APIs in Core (in this case, depending on the PowerPC namespace). Because of the poor separation here, this moves OSThread functionality into core, so that it resolves the implicit dependency on core.
> Common: Move OSThreads into Core

- Source/Core/AudioCommon/CubebUtils.cpp
- Source/Core/Common/Logging/Log.h
- Source/Core/Common/Logging/LogManager.cpp
- Source/Core/Common/Logging/LogManager.h
Provides a basic extension to the interface to begin migration off of the printf-based logging system.
Everything will go through macros with the same style naming as the old logging system, except the macros will have the _FMT suffix, while the migration is in process. This allows for peacemeal migration over time instead of pulling everything out and replacing it all in a single pull request, which makes for much easier reviewing.
> Common/Log: Add basic fmt-capable functions to the interface.

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
This is part of my efforts to add support for scoped storage. I figured I would start with a relatively simple feature to make sure that everyone is fine with the approach I'm taking before I tackle more complicated features like the game list.
> Android: Use storage access framework for importing WADs

- Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
- Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h
This fixes the issue of "Alt" being stuck after an Alt+Tab away from Dolphin.
Keyboard state is now cleared on `XI_FocusOut`.
At least on my system, cycling Alt-Tab and refocusing Dolphin does not capture `XI_FocusOut` or `XI_KeyRelease`.
I've added a workaround with `XQueryKeymap`.
Other minor cleanups.
> Linux/XInput2: Fix keys being stuck pressed on focus loss.

- Source/Core/Core/HW/WiimoteEmu/Speaker.cpp
As in the code comment, the panning was denaturalizing the volume (when panning was set to 0).
Unless users actually want to use panning, their wii mote volume should not be reduced, it should come out at the same volume the samples were, without using the "Constant Power Pan Law" as we can't assume the original wii mote speakers loadness is comparable to the loudness of the audio device you are currently using (in fact, it's likely to be lower).
If users want to reduce the volume of the wii mote speakers, they can do so from the wii home menu.
I opted for this instead of adding another setting "Enable Panning" as it would have been confusing, and the changes in the panning formula are unlikely to have any negative effect, as it still works.
> Fixed volume of emulated wii mote speakers not being native.

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java
- Source/Android/jni/AndroidCommon/IDCache.cpp
- Source/Android/jni/AndroidCommon/IDCache.h
- Source/Android/jni/MainAndroid.cpp
- Source/Core/Core/CMakeLists.txt
- Source/Core/Core/ConfigManager.cpp
- Source/Core/Core/ConfigManager.h
- Source/Core/Core/Core.cpp
Trying to get it from a GameFile before emulation starts is unreliable.
> Android: Get game metadata from core

- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcard.h
This PR renames an unknown field based on the register value it uses (see [YAGCD](http://hitmen.c02.at/files/yagcd/yagcd/chap5.html#sec5.3)).
This value is set in the `__CARDFormatRegionAsync` function. I don't know if the old comments still apply.
Ready to reviewed.
> GCMemcard: Rename unknown field to m_dtv_status

- Source/Android/jni/GameList/GameFile.cpp
- Source/Android/jni/GameList/GameFileCache.cpp
- Source/Android/jni/MainAndroid.cpp
We generally have no reason to call these functions on our own, so there's not much reason to declare them, especially not in the cpp file where they're defined. In case we ever do get a reason to do it, we can add declarations for just the functions that need them.
> Android: Remove unnecessary JNI function declarations

- Source/Core/Core/HW/GCMemcard/GCMemcard.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
Just some cleanup of undefined behavior and unclear code. Should not change program behavior.
(Yes, ClearBlock() really dir call a member function on the wrong class. I'm amazed this worked at all.)
> Sketchy code cleanup in GCMemcard and GCMemcardDirectory.

- Source/Core/Common/Matrix.cpp
- Source/Core/Common/Matrix.h
- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/Core/HW/WiimoteEmu/Dynamics.h
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
- Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.h
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.h
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.cpp
- Source/Core/InputCommon/ControllerInterface/Wiimote/Wiimote.h
This is an attempt to fix: https://bugs.dolphin-emu.org/issues/12077
Wii remote orientations were maintained as `Matrix33`.
We never made any attempt to normalize these and floating point inaccuracies will eventually make them invalid rotational matrices.
Orientations now use quaternions and are normalized.
> Replace stateful rotational matrices with quaternions.

- Source/Core/Common/Matrix.h
Much of these classes are operating on integral types and are pretty standard behavior as far as vectors go. Some member functions can be made constexpr to make them more flexible and allow them to be used in constexpr contexts.
> Common/Matrix: Allow TVec classes to be used in constexpr contexts

- Externals/libpng/CMakeLists.txt
- Externals/minizip/CMakeLists.txt
- Source/Core/UpdaterCommon/CMakeLists.txt
On Linux, if shared zlib is present, zlib.h is always available and -lz
links to zlib, even if you don't run find_package(ZLIB).
For some reason I have zlib installed on Windows (possibly from vcpkg),
so find_package(ZLIB) succeeds and ZLIB_FOUND is true.
When Dolphin uses shared zlib on Windows, the problem is that zlib.h
is not in the default include path, and the CMake target is called
ZLIB::ZLIB and there's neither a target nor a library called z.
However, both find_package(ZLIB) and add_subdirectory(Externals/zlib)
create a target called ZLIB::ZLIB, so I'll switch to that instead.
Hopefully this change doesn't break anyone's build.
> Fix Windows CMake builds with shared zlib

- Source/Core/VideoCommon/UberShaderVertex.cpp
Continues migration of the shader generators over to fmt.
With this, all that's left to move over are the pixel shaders (regular and ubershader variants)
> UberShaderVertex: Migrate over to fmt

- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/MainWindow.h
Because config change events trigger `UpdateScreenSaverInhibition` a ridiculous number of processes were being spawned on Linux to enable an already enabled screensaver.
> DolphinQt: Don't call UICommon::InhibitScreenSaver if already in desired state.

- Source/Core/DiscIO/CompressedBlob.cpp
- Source/Core/DiscIO/DirectoryBlob.cpp
- Source/Core/DiscIO/DiscExtractor.cpp
- Source/Core/DiscIO/DiscScrubber.cpp
- Source/Core/DiscIO/DriveBlob.cpp
- Source/Core/DiscIO/Enums.cpp
- Source/Core/DiscIO/FileSystemGCWii.cpp
- Source/Core/DiscIO/NANDImporter.cpp
- Source/Core/DiscIO/VolumeGC.cpp
- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/VolumeWad.cpp
- Source/Core/DiscIO/WIABlob.cpp
Eliminates quite a bit of the PRI* macros used for handling 64-bit values.
> DiscIO: Migrate logging over to fmt

- Languages/po/qt-strings.pot
- Source/Core/DolphinQt/Translation.cpp
Now that we have a .pot file specifically for strings from Qt itself, it makes sense to move this into it.
> DolphinQt: Move QT_LAYOUT_DIRECTION string to qt-strings.pot

- Source/Core/Core/State.cpp
- Source/Core/VideoCommon/FrameDump.cpp
- Source/Core/VideoCommon/FrameDump.h
- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/RenderBase.h
Fixed calculation of PTS values.
This should fix: https://bugs.dolphin-emu.org/issues/12228
Warnings are issued on dropped/skipped frames.
Filename of dumped video now includes the GameID and timestamp like our screenshots.
e.g. "G9SE8P_2020-10-22_11-51-30_0.avi"
Dumping previously restarted on resolution change.
It now also restarts on VI refresh-rate change and savestate load.
Note these restarts maintain the original timestamp to help with file organization/splicing.
Eliminated static variables and general cleanup in FrameDump.
Variable renames and minor cleanup of related code in RenderBase.
> VideoCommon: FrameDump fixes/cleanups.

- Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
- Source/Core/DolphinQt/Config/Graphics/SoftwareRendererWidget.cpp
- Source/Core/UICommon/UICommon.cpp
- Source/Core/VideoCommon/VideoBackendBase.cpp
- Source/Core/VideoCommon/VideoBackendBase.h
Replace it with a function-local static that is initialized on first
use. This gets rid of a global variable and removes the need for
manual initialization in UICommon.
This commit also replaces the weird find_if that looks for a non-null
unique_ptr with a simple "is vector empty" check considering that
none of the pointers can be null by construction.
---
Also simplifies GetDefaultBackendName: now we can just call
GetDefaultVideoBackend to get the default backend
and get its name by calling GetName.
> VideoCommon: Get rid of the global g_available_video_backends

- Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
Currently, data reports of real remotes are repeated to trigger sending of speaker data.
This causes some games to fail at detecting motion gestures.
https://bugs.dolphin-emu.org/issues/10111
https://bugs.dolphin-emu.org/issues/12030
With this change if speaker data is disabled so is repeating of data reports.
This fixes gestures in these games so long as speaker data is disabled.
Another potential fix might be to interpolate accelerometer data in repeated reports but that is getting pretty hacky.
I think this is cleaner.
> WiimoteReal: Only duplicate data reports when speaker data is enabled.

- Source/Core/DiscIO/VolumeVerifier.cpp
The downloads page on redump doesn't link to the version that has serials and versions.  Since the Wii data needs to be manually downloaded, it's easy to download the version without them (if you have access to them, of course), and it's not immediately obvious how to get the right version.  I only found out by looking at the code that does the downloading for GC data.  This PR amends the message to explain how to include that data in the download.
> Explain how to fix "Serial and/or version data is missing"

- Source/Core/DolphinQt/Settings/AdvancedPane.cpp
I've run into a few users that think more memory is just better then they can't figure out why games stop working.
Maybe a warning will help at least a little.
> DolphinQt: Add a warning to the MEM1/MEM2 override setting description.

- Source/Core/VideoCommon/FrameDump.cpp
- Source/Core/VideoCommon/FrameDump.h
I've removed code that was supporting older versions of libavcodec.
Based on the `#ifdef`s I removed we now require 58.9.100.
Ubuntu 20.04 appears to currently provide 58.54.100.
This cleans up some logic that had to send a frame and receive a packet in the same deprecated call.
> VideoCommon/FrameDump: Remove code for older versions of avcodec.

- Source/Core/Common/Arm64Emitter.cpp
- Source/Core/Common/FileUtil.cpp
- Source/Core/Common/GL/GLExtensions/GLExtensions.cpp
- Source/Core/Common/GL/GLInterface/AGL.mm
- Source/Core/Common/GL/GLInterface/EGL.cpp
- Source/Core/Common/GL/GLInterface/GLX.cpp
- Source/Core/Common/GL/GLInterface/WGL.cpp
- Source/Core/Common/GL/GLUtil.cpp
- Source/Core/Common/HttpRequest.cpp
- Source/Core/Common/MemArena.cpp
- Source/Core/Common/MemoryUtil.cpp
- Source/Core/Common/MsgHandler.cpp
- Source/Core/Common/SDCardUtil.cpp
- Source/Core/Common/StringUtil.cpp
- Source/Core/Common/SymbolDB.cpp
- Source/Core/Common/TraversalClient.cpp
- Source/Core/Common/UPnP.cpp
- Source/Core/Common/x64Emitter.cpp
Continues the migration of our code over to the fmt logger.
> Common: Migrate logging to fmt

- Source/Core/VideoCommon/PixelShaderGen.cpp
- Source/Core/VideoCommon/PixelShaderGen.h
Continues the migration of the shader generators over to fmt.
After this, all that remains in the Ubershader pixel generator.
> PixelShaderGen: Migrate over to fmt

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
Fixes a regression from 0dc29c743b9b2ed2dabf9d510cafcf99ca46b1f5. @JosJuice we missed this.
> Android: Fix initTouchPointer

- Source/Core/Common/Config/Config.cpp
Noticed missing include as a build failure on gcc-11:
```
[ 15%] Building CXX object Source/Core/Common/CMakeFiles/common.dir/Config/Config.cpp.o
Source/Core/Common/Config/Config.cpp:23:24:
error: 'unique_lock' in namespace 'std' does not name a template type
23 | using WriteLock = std::unique_lock<std::shared_mutex>;
|                        ^~~~~~~~~~~
Source/Core/Common/Config/Config.cpp:11:1:
note: 'std::unique_lock' is defined in header '<mutex>';
did you forget to '#include <mutex>'?
```
> Source/Core/Common/Config/Config.cpp: add missing <mutex> include

- Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
- Source/Core/VideoCommon/DriverDetails.cpp
- Source/Core/VideoCommon/DriverDetails.h
Apparently working again with the MoltenVK update in #9126. This supersedes #9140 by not undoing the moving of the closing bracket. @Stenzek should we remove the DriverDetails bug itself as well, or keep it around in case it's needed again?
Would like to see some test cases just to be sure it's working properly.
> Re-enable GPU Texture Decoding under MoltenVK

- Source/Core/Core/IOS/USB/OH0/OH0.cpp
- Source/Core/Core/IOS/USB/OH0/OH0.h
- Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp
- Source/Core/Core/IOS/USB/USB_HID/HIDv4.h
- Source/Core/Core/IOS/USB/USB_HID/HIDv5.cpp
- Source/Core/Core/IOS/USB/USB_VEN/VEN.cpp
Unfortunately, compilers will issue warnings when using offsetof with
non-standard layout types even when offsetof actually works fine here;
just having a virtual function is enough to trigger the warning...
Let's just stop the scan threads explicitly in destructors instead of
relying on member destruction order.
> IOS/USB: Fix -Winvalid-offset warnings

- Source/Core/Common/HttpRequest.cpp
Fixes a regression introduced by #9187 where Dolphin would crash to desktop in the event the HTTP server returned a zero-length error response, which the update server appears to do occasionally. 
The exception in question seems intentional in the logger so I've added a case to make sure there is response body before trying to log it.
EDIT: This crash can also happen when GameTDB doesn't have covers for a game in your library and Dolphin attempts to download it.
> Fix logger related crash when HTTP response is empty.

- Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
`flush = cond ? flush : true` makes little sense when `flush` is always true at that point.
> Simplify Arm64GPRCache::Flush

- Source/Core/Core/IOS/Network/IP/Top.cpp
- Source/Core/Core/IOS/Network/Socket.cpp
- Source/Core/Core/IOS/Network/Socket.h
~~This PR will need a hardware test (similar #8389) to confirm this behaviour.~~
This PR tries to fix inconsistencies regarding `shutdown` implementation (on a socket) and be as close as possible to what the Wii does *(not sure about the GC behaviour)*.
It fixes crashes/hangs in some Just Dance games : https://dolp.in/i11910
* Dolphin not getting the right network interface on :
- Android (https://github.com/dolphin-emu/dolphin/pull/9191)
- MacOS (https://github.com/dolphin-emu/dolphin/pull/9214)
* Return values of other network functions
I created 2 hardware tests:
1. one that fires `shutdown` on blocking operations
2. the second one that checks return values of network functions after `shutdown` was called
1. Get the latest version of Dolphin (at least after …
> Socket: Abort pending operations on shutdown

- Source/Core/Core/IOS/Network/IP/Top.cpp
This fixes an issue that was found in #8758. Previously, the call to ``connect`` in ``GetSystemDefaultInterface`` would fail with ``EADDRNOTAVAIL`` on macOS.  If we set ``sin_port``, the call will succeed.
Tested on macOS 11 Big Sur beta 10.
cc @sepalani
> Top: Set port when connecting a socket to find the default interface

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
It's better to directly check whether we have an InputOverlay than to check a proxy for it.
> Android: Remove some touchscreen checks from EmulationActivity

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayPointer.java
This assumption is false both in portrait mode (where it only covers the top half of the screen) and when using two apps at once.
Fixes https://bugs.dolphin-emu.org/issues/12307. Alternative to PR #9208.
> Android/InputOverlayPointer: Don't assume surface covers whole screen

- Source/Core/VideoBackends/Vulkan/VKTexture.cpp
- Source/Core/VideoBackends/Vulkan/VKTexture.h
Hello,
I am getting errors on FreeBSD i386 (12.1-RELEASE/LLVM 8.0.1) when trying to build Dolphin 5.0.12716:
```
/usr/bin/c++ -DDATA_DIR=\"/usr/local/share/dolphin-emu/\" -DFMT_SHARED -DHAVE_EGL=1 -DHAVE_FFMPEG -DHAVE_X11=1 -DHAVE_XRANDR=1 -DUSE_ANALYTICS=1 -DUSE_MEMORYWATCHER=1 -DUSE_PIPES=1 -DUSE_UPNP -D_ARCH_32=1 -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_M_GENERIC=1 -D__LIBUSB__ -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/wrkdirs/usr/ports/emulators/dolphin-emu/work/dolphin-3152428/Source/Core -I/wrkdirs/usr/ports/emulators/dolphin-emu/work/dolphin-3152428/Externals/enet/include -I/wrkdirs/usr/ports/emulators/dolphin-emu/work/dolphin-3152428/External/minizip -I/usr/local/include/libpng16 -I/wrkdirs/usr/ports/emulators/dolphin-emu/work/dolphin-3152428/External …
```
> Fix build on FreeBSD i386 - nullptr vs VK_NULL_HANDLE

- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.h
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp
- Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.h
- Source/Core/InputCommon/ControllerEmu/StickGate.cpp
- Source/Core/InputCommon/ControllerEmu/StickGate.h
This is a feature that I wanted in Dolphin for quite some time now. It should make playing games like Super Monkey Ball feel a bit closer to using a GC controller when using a controller without an Octagonal gate (e.g. Xbox, PS4, Steam e.t.c).
Adds an option in the controller config to set the size of the virtual notches. These virtual notches add a sticky behaviour that will snap the controller to the different axis.
Disclaimer:
I've never written C++ before (besides Hello World about 10 years ago) so I'm completely open to suggestions for improvements. I was unable to get the linter running locally but I think Visual Studio was enforcing code styling while developing so I'm hoping it's already formatted correctly.
> Logic & UI for "Virtual Notches"

- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
- Source/Core/Core/PowerPC/JitArm64/Jit.h
Closely based on the x86-64 implementation. Fixes https://bugs.dolphin-emu.org/issues/10965.
> JitArm64: Implement HLE function hooking

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Instead of adding every case in the `IntDef`, it'd probably be better to suppress the `SwitchIntDef` warnings.
- Returning nothing instead of breaking after each switch case seems silly. Android Studio complains that the final `return` was also unnecessary.
> Android: Suppress warnings in EmulationActivity

- Source/Core/Common/CPUDetect.h
- Source/Core/Common/x64CPUDetect.cpp
With AMD Zen3, PDEP and PEXT performance is restored to levels comparable with Intel's counterparts.
https://www.anandtech.com/show/16214/amd-zen-3-ryzen-deep-dive-review-5950x-5900x-5800x-and-5700x-tested/6
Because Zen3 is _Family 25_ not _Family 23_, we only need to change the comments to indicate that the flag disabling PDEP and PEXT does not apply to Zen3.
For reference: #8586
> CPUDetect: Indicate slow PDEP/PEXT only for Zen1/+/2 (Family 23)

- Source/Core/VideoCommon/PixelShaderGen.cpp
- Source/Core/VideoCommon/UberShaderPixel.cpp
Completes the migration over to using the fmt-formatting WriteFmt function. The next PR will rename all usages of WriteFmt, while simultaneously getting rid of the old printf code.
> UberShaderPixel: Migrate over to fmt

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/SaveLoadStateFragment.java
Android Studio doesn't raise any warnings when these are removed.
> Android: Remove unnecessary WrongConstant warning suppression

- Source/Android/jni/AndroidCommon/IDCache.h
- Source/Android/jni/GameList/GameFile.cpp
- Source/Android/jni/GameList/GameFileCache.cpp
- Source/Android/jni/IniFile.cpp
- Source/Android/jni/MainAndroid.cpp
- Source/Android/jni/NativeConfig.cpp
Static methods use jclass, and non-static methods use jobject.
> Android: Fix jobject/jclass warnings

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
I didn't realize that onSaveInstanceState doesn't get called when finishing the activity.
> Android: Call saveSettings in EmulationActivity.onStop

- Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
Some users aren't noticing that the in-game menu can be scrolled. I hope this will help with that, though I'm not sure by how much.
> Android: Make scrollbar for in-game menu always visible

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/ConvertFragment.java
Not sure why I named it `path`, because it isn't a path.
> Android: Rename path variable in ConvertFragment

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java
- Source/Android/jni/AndroidCommon/IDCache.cpp
- Source/Android/jni/AndroidCommon/IDCache.h
- Source/Android/jni/MainAndroid.cpp
- Source/Core/Core/Core.cpp
- Source/Core/Core/Core.h
If you try to boot an invalid file in master (for instance if you pick Open File and try to open a PNG file you renamed to .iso), Dolphin more or less locks up. This PR aims to make that scenario work correctly.
> Android: Handle failed boots correctly

- Source/Core/UICommon/AutoUpdate.cpp
A very simple change that continues the migration of the logs over to fmt.
> UICommon: Migrate logging over to fmt

- Source/Core/VideoCommon/FramebufferShaderGen.cpp
- Source/Core/VideoCommon/GeometryShaderGen.cpp
- Source/Core/VideoCommon/LightingShaderGen.cpp
- Source/Core/VideoCommon/PixelShaderGen.cpp
- Source/Core/VideoCommon/ShaderGenCommon.cpp
- Source/Core/VideoCommon/ShaderGenCommon.h
- Source/Core/VideoCommon/TextureConversionShader.cpp
- Source/Core/VideoCommon/TextureConverterShaderGen.cpp
- Source/Core/VideoCommon/UberShaderCommon.cpp
- Source/Core/VideoCommon/UberShaderPixel.cpp
- Source/Core/VideoCommon/UberShaderVertex.cpp
- Source/Core/VideoCommon/VertexShaderGen.cpp
Now that we've converted all of the shader generators over to using fmt, we can drop the old printf-based `Write()` member function and perform a rename operation on `WriteFmt()` to turn it into the new `Write()` function.
All changes within this are the removal of a `<cstdarg>` header, since the previous printf-based `Write()` required it, and renaming. No functional changes are made at all.
> ShaderGenCommon: Rename WriteFmt() to Write()

- Languages/update-source-strings.sh
- Source/Core/Common/MsgHandler.cpp
- Source/Core/Common/MsgHandler.h
Adds an interface that uses fmt under the hood, which is much more flexible than printf, particularly for localization purposes, given fmt supports positional formatters in a cross-platform manner out of the box with no configuration necessary.
Now alerts can be progressively migrated over as well, like with the logging macros.
> Common/MsgHandler: Add fmt-capable variants of the alert macros

- Source/Core/DiscIO/CompressedBlob.cpp
- Source/Core/DiscIO/DirectoryBlob.cpp
- Source/Core/DiscIO/DriveBlob.cpp
- Source/Core/DiscIO/FileBlob.cpp
- Source/Core/DiscIO/FileSystemGCWii.cpp
- Source/Core/DiscIO/NANDImporter.cpp
- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/VolumeWii.cpp
- Source/Core/DiscIO/WIABlob.cpp
- Source/Core/DiscIO/WbfsBlob.cpp
Migrates the DiscIO code over to fmt. DiscIO is finally free from the printf hell that is the PRI* macros.
> DiscIO: Make use of fmt-capable panic alerts

- Source/Core/DiscIO/DiscExtractor.cpp
modify file export to create folder in OS when explicitly extracting a directory
> fix emulator issue #12139

- CMakeLists.txt
We use `make_args_checked`, which was added in 7.1.0.
> CMake: Bump fmt version requirement to 7.1.0

- Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
- Source/Core/Core/NetPlayServer.cpp
- Source/Core/DiscIO/CompressedBlob.cpp
- Source/Core/DiscIO/FileBlob.cpp
- Source/Core/DiscIO/NANDImporter.cpp
- Source/Core/DiscIO/VolumeVerifier.cpp
- Source/Core/DiscIO/WIABlob.cpp
- Source/Core/InputCommon/InputConfig.cpp
We want to use positional arguments in translatable strings that have more than one argument so that translators can change the order of them, but the question is: Should we also use positional arguments in translatable strings with only one argument? I think it makes most sense that way, partially so that translators don't even have to be aware of the non-positional syntax and partially because "translatable strings use positional arguments" is an easier rule for us to remember than "transitional strings which have more than one argument use positional arguments". But let me know if you have a different opinion.
> Use positional arguments in all translatable fmt strings

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFile.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CompressCallback.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ContentHandler.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/IniFile.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_GCAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java
This acts as a hint to both people and automated tools that a variable or method shouldn't be renamed or removed.
> Android: Add @Keep annotation to things accessed using JNI

- Source/Core/Core/IOS/Network/IP/Top.cpp
This PR adds missing opt conversion.
I'm working on PRs for https://github.com/dolphin-emu/hwtests to confirm the behaviour and get the default values for each constant. From reverse engineering, `SO_ERROR` is indeed `0x1009` at least on the latest version of IOS59.
> IP/Top: Add missing sockopt

- Source/Core/Common/WorkQueueThread.h
- Source/Core/DolphinQt/CheatsManager.cpp
- Source/Core/DolphinQt/CheatsManager.h
- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/GameList/GameList.h
- Source/Core/DolphinQt/GameList/GameTracker.cpp
- Source/Core/DolphinQt/GameList/GameTracker.h
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/NetPlay/GameListDialog.cpp
- Source/Core/DolphinQt/NetPlay/GameListDialog.h
- Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayDialog.h
- Source/Core/DolphinQt/NetPlay/NetPlaySetupDialog.cpp
- Source/Core/DolphinQt/NetPlay/NetPlaySetupDialog.h
- Source/Core/DolphinQt/Settings.cpp
- Source/Core/DolphinQt/Settings.h
- Source/Core/DolphinQt/Settings/InterfacePane.cpp
- Source/Core/DolphinQt/ToolBar.cpp
- Source/Core/UICommon/GameFileCache.cpp
- Source/Core/UICommon/GameFileCache.h
Because the **GameListModel** was never destroyed, its **GameTracker** instance outlived the **Config** module, which led to some crashes on shutdown.
The fix consists of binding the lifespan of **GameListModel** to the **GameList** instance, ensuring that the **GameTracker** is indeed destructed.
In order to be able to destroy the **GameTracker** instance, some _race conditions_, _deadlocks_ and _other crashes_ had to be addressed. These issues were all caused by a bad combination of the **GameTracker**'s worker thread and the `RunOnObject()` function.
To summarize the list of changes:
- All references to the **GameListModel** have been removed from **Settings**.
- The **GameListModel** instance is now owned by the **GameList** instance.
- Components that need to access the …
> DolphinQt: Avoid leaking the GameListModel instance to gracefully shutdown the GameTracker and prevent a crash on exit

- Source/Core/DolphinQt/Translation.cpp
`tr` calls with more than one argument would have a 0x04 byte in the returned string when no translation was found (which always is the case when using Dolphin in English).
> DolphinQt: Don't return 0x04 bytes from tr

- Externals/soundtouch/PeakFinder.cpp
Encoding of this file was iso-8859-1 instead of utf-8, this PR addresses that to bring it inline with the .editorconfig file : ) discovered while working on indexing dolphin repo with https://github.com/sourcegraph/lsif-clang, so thanks for surfacing this! :grin:
> Fixed non-UTF8 chars in PeakFinder.cpp

- Source/Core/UpdaterCommon/UpdaterCommon.cpp
Updater was only deleting TempUpdate folder when an error occured.
> Fix updater not always cleaning up temp directory

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
This was removed in PR #9152 when it should have been converted to the new setting instead, and it seems like I didn't notice when reviewing it.
I'm changing the `DirectoryInitialization` logic a little so that `clearWiimoteNewIniLinkedPreferences` also is called when there was no `WiimoteNew.ini` previously, in case the user deleted `WiimoteNew.ini` but not `Dolphin.ini`.
> Android: Re-add motionControlsEnabled to clearWiimoteNewIniLinkedPreferences

- Data/Sys/GameSettings/JAP.ini
- Data/Sys/GameSettings/JB6.ini
- Data/Sys/GameSettings/JBH.ini
- Data/Sys/GameSettings/JBO.ini
- Data/Sys/GameSettings/JC6.ini
- Data/Sys/GameSettings/JC9.ini
- Data/Sys/GameSettings/JCE.ini
- Data/Sys/GameSettings/LAD.ini
- Data/Sys/GameSettings/LAF.ini
- Data/Sys/GameSettings/LAK.ini
- Data/Sys/GameSettings/LAL.ini
- Data/Sys/GameSettings/LAO.ini
- Data/Sys/GameSettings/LAP.ini
- Data/Sys/GameSettings/MB9.ini
- Data/Sys/GameSettings/MCT.ini
- Data/Sys/GameSettings/MCV.ini
- Data/Sys/GameSettings/MCY.ini
- Data/Sys/GameSettings/S25.ini
This adds the INI changes to the SNES games which needed EFB Copies to Texture Only turned off to not display a black screen, the Dualcore issues with some SNES and Sega Genesis games in terms of stuttering and darkening the screen, and also the XFB issues for Sega Genesis and Sega Master System games in terms of purple screens
> Game INI Changes

- Source/Core/VideoBackends/Vulkan/StateTracker.cpp
In CreateDescriptorSetLayouts(), one less dynamic binding is created when
bSupportsGeometryShaders=false. Reduce the dynamicOffsetCount argument by
one in that case. Avoids this validation error:
Attempting to bind 3 descriptorSets with 2 dynamic descriptors, but
dynamicOffsetCount is 3. It should exactly match the number of dynamic
descriptors. The Vulkan spec states: dynamicOffsetCount must be equal to
the total number of dynamic descriptors in pDescriptorSets
> Vulkan: fix validation error in bSupportsGeometryShaders=false case

- Source/Core/Common/CMakeLists.txt
- Source/Core/Common/Common.vcxproj
- Source/Core/Common/Common.vcxproj.filters
- Source/Core/Common/FormatUtil.h
- Source/Core/Common/Logging/Log.h
- Source/Core/Common/Logging/LogManager.cpp
- Source/Core/Common/MsgHandler.h
As this is a common source of bugs since we started migrating to {fmt}, I think it's worth enabling and adding more compile-time format string checks. This should also make the migration PRs easier to review ^^
As an added bonus, the static_assert will cause an invalid format call to be identified as an error in IDEs immediately, rather than at compilation time.
> Common/Log: Add compile-time format string checks

- Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp
PR #9260 made the MsgAlert macros use lambdas so that local
constexpr variables can be added while keeping the ability to
return a boolean from the macros.
Unfortunately, C++17 forbids referring to structured bindings in lambda
captures. This is fixed in P1091R3 but we cannot rely on C++20 yet...
> Core: Fix invalid lambda captures

- Source/Core/VideoBackends/Software/SWVertexLoader.cpp
- Source/Core/VideoCommon/ConstantManager.h
- Source/Core/VideoCommon/GXPipelineTypes.h
- Source/Core/VideoCommon/LightingShaderGen.cpp
- Source/Core/VideoCommon/LightingShaderGen.h
- Source/Core/VideoCommon/PixelShaderGen.cpp
- Source/Core/VideoCommon/PixelShaderGen.h
- Source/Core/VideoCommon/ShaderGenCommon.h
- Source/Core/VideoCommon/UberShaderCommon.cpp
- Source/Core/VideoCommon/UberShaderVertex.cpp
- Source/Core/VideoCommon/VertexShaderGen.cpp
- Source/Core/VideoCommon/VertexShaderManager.cpp
Code copied from #4601 before it was changed to remove the Super Mario Sunshine debug cube fixes, specifically from commits 0ddcd28f16c4e57d7a3ad8b2665e947d242ddd81 and 8fa5b13afe25e3030be89c4482e3a74f66739136.  I haven't tested this code myself, and don't fully understand what it does; this is just those two commits cherry-picked with merge conflicts fixed (some parts were already merged).
FifoCI for these changes: ~~https://fifo.ci/version/07b69225a24138559aa36034104464b01ba85823/~~ https://fifo.ci/version/d6ce8eef36f5b0bfd0078c51701b052cc9a77005/
FifoCI for #4601's changes: https://fifo.ci/version/0ddcd28f16c4e57d7a3ad8b2665e947d242ddd81/
> Fix Super Mario Sunshine debug cubes (originally PR #4601 by stenzek)

- Source/Core/Core/Movie.cpp
- Source/Core/Core/Movie.h
gameID isn't null terminated since it is just an std::array<char, 6>
and .data() returns a char* so {fmt} would go way beyond the bounds of
the array when it attempts to determine the length of the string.
The fix is to pass a std::string_view to {fmt}. This commit adds
a GetGameID() function that can also be used to simplify
string comparisons.
> Core/Movie: Fix a likely out-of-bounds read for PanicAlertT

- CMakeLists.txt
https://github.com/dolphin-emu/dolphin/pull/9037/commits/969ea6e4f54f1021edaa8f565e20b17a78f6f753
Fixes non-conformant handling of `__VA_ARGS__`.
> CMake: Pass various /Zc flags to MSVC for consistency with Base.props

- Source/Core/VideoCommon/FrameDump.cpp
This was removed in PR #9188. We still need this for the ffmpeg version we're using on Windows.
> FrameDump: Re-add call to av_register_all

- Source/Core/UICommon/USBUtils.cpp
Based on info from https://forums.dolphin-emu.org/Thread-emulate-midi-pro-adapter
> Add Rock Band 3 MIDI PRO Adapter to known Wii peripherals

- Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
- Source/Core/DolphinQt/Config/Mapping/IOWindow.h
- Source/Core/InputCommon/ControlReference/ControlReference.cpp
- Source/Core/InputCommon/ControlReference/ControlReference.h
This displays the current result of an input expression right there in the editor, instead of the parser error box.
Updates automatically just like the available inputs table above and immediately reacts to any edits in the expression.
> Qt/IOWindow: Show result value in expression editor.

- Source/Core/Common/File.h
- Source/Core/Core/PowerPC/Jit64/Jit.cpp
- Source/Core/Core/PowerPC/JitInterface.cpp
- Source/Core/Core/PowerPC/PPCSymbolDB.cpp
- Source/Core/Core/PowerPC/PPCTables.cpp
- Source/Core/Core/PowerPC/SignatureDB/CSVSignatureDB.cpp
This actually started as an attempt to remove the `GetHandle()` method, but I figured this makes as a decent PR on its own.
> IOFile: Replace fprintf with WriteString/fmt.

- Source/Core/Core/PowerPC/BreakPoints.cpp
- Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
- Source/Core/Core/PowerPC/GDBStub.cpp
- Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
- Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp
- Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp
- Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
- Source/Core/Core/PowerPC/Jit64/Jit.cpp
- Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp
- Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
- Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
- Source/Core/Core/PowerPC/Jit64/Jit_Paired.cpp
- Source/Core/Core/PowerPC/Jit64Common/TrampolineCache.cpp
- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
- Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
- Source/Core/Core/PowerPC/JitInterface.cpp
- Source/Core/Core/PowerPC/MMU.cpp
- Source/Core/Core/PowerPC/PPCAnalyst.cpp
- Source/Core/Core/PowerPC/PPCCache.cpp
- Source/Core/Core/PowerPC/PPCSymbolDB.cpp
- Source/Core/Core/PowerPC/PPCTables.cpp
- Source/Core/Core/PowerPC/PowerPC.cpp
- Source/Core/Core/PowerPC/SignatureDB/CSVSignatureDB.cpp
- Source/Core/Core/PowerPC/SignatureDB/DSYSignatureDB.cpp
- Source/Core/Core/PowerPC/SignatureDB/MEGASignatureDB.cpp
- Source/Core/Core/PowerPC/SignatureDB/SignatureDB.cpp
Converts the remaining PowerPC code over to fmt-capable logging.
Now, all that's left to convert over are the lingering remnants within the frontend code.
> Core: Convert logging over to fmt pt.5

- Source/Core/Common/FileUtil.cpp
On Windows, when the Rename function fails to replace an existing file
it will now retry the operation multiple times with increasingly long
delays between attempts.  This fixes transient rename failures.
I've been getting sporadic yet annoyingly frequent errors saying:
'IOS_FS: Failed to rename temporary FST file'
These typically appear on startup but I've also gotten them randomly.
Investigation shows this happens when the Windows ReplaceFile function
returns the error ERROR_UNABLE_TO_REMOVE_REPLACED.  That happens in the
context of using ReplaceFile to perform an atomic file overwrite, which
is required when saving updates to a file to avoid corruption.  The
error mainly happens with the /Wii/fst.bin file but I've seen it
happen with multiple other files as well.
I haven't been able to …
> Fix file rename errors on Windows

- Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
- Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp
- Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp
- Source/Core/Core/HW/WiimoteEmu/I2CBus.cpp
- Source/Core/Core/PowerPC/GDBStub.cpp
- Source/Core/DolphinQt/ConvertDialog.cpp
- Source/Core/DolphinQt/GCMemcardManager.cpp
- Source/Core/DolphinQt/MenuBar.cpp
- Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
- Source/Core/DolphinQt/Translation.cpp
- Source/Core/UICommon/X11Utils.cpp
- Source/Core/VideoCommon/VertexLoader_TextCoord.cpp
Migrates the final remaining logs over to fmt-equivalents
After this PR, renaming of the new fmt functions to the old one can be undertaken. The printf logging can't be removed until all alerts and assertions are converted over however.
> Frontends: Migrate logs over to fmt

- Source/Core/Common/Config/Config.cpp
- Source/Core/Common/Config/Config.h
The way `Config::Get` works in master, it first calls `Config::GetActiveLayerForConfig` which searches for the setting in all layers, and then calls `Config::Layer::Get` which searches for the same setting again within the given layer. We can remove this second search by combining the logic of `Config::GetActiveLayerForConfig` and `Config::Layer::Get` into one function.
> Common: Optimize Config::Get

- Source/Core/VideoBackends/OGL/Render.cpp
Fixes bounding box games like Paper Mario on OpenGL ES Android phones.
> Fix bounding box incorrectly disabled on OpenGL ES 3.1, 3.2

- Externals/liblzma/config.h
/Externals/liblzma/config.h #defines HAVE_PTHREAD_CONDATTR_SETCLOCK
which results in /Externals/liblzma/tuklib/mythread.h calling the
function pthread_condattr_setclock.  This function doesn't exist in
macOS 10.12+, which are the only macOS versions Dolphin supports, but
inserting an include guard makes macOS use an alternate function.
> Fix liblzma config on macOS

- Source/Core/AudioCommon/OpenALStream.cpp
- Source/Core/AudioCommon/WaveFile.cpp
Continues the migration over to fmt
> AudioCommon: Convert alerts over to fmt-based variants

- Source/Android/app/src/main/AndroidManifest.xml
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/NetworkHelper.java
- Source/Android/jni/AndroidCommon/AndroidCommon.cpp
- Source/Android/jni/AndroidCommon/AndroidCommon.h
- Source/Android/jni/AndroidCommon/IDCache.cpp
- Source/Android/jni/AndroidCommon/IDCache.h
- Source/Core/Core/IOS/Network/IP/Top.cpp
This PR adds for (not so old) Android devices network interface support allowing to use network functions such as `bind`. This PRs should work for Ethernet, Wi-Fi and maybe other connection.
> IP/Top: Add Android network interface

- Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp
Unfortunately, adding a DEBUG_ASSERT_MSG_FMT isn't actually possible
right now because of compiler bugs:
https://github.com/dolphin-emu/dolphin/pull/9284
We could require a newer version of GCC (10) but that would require
updating GCC on the build machines.
For what it's worth, older versions of GCC (8, 9) are already broken in
many ways: adding constexpr to some Matrix functions causes GCC 8
to generate bugged code that causes the Wii IR pointer to disappear,
which means that the generated builds are already unusable
(see https://dolp.in/i12324).
Additionally,  we've already had to add workarounds for those versions
in the format macros to fix compilation bugs. This time, it looks like
workarounds won't cut it; even applying the workaround
described in …
> Core: Fix an assertion that mistakenly uses a fmt format string

- Source/Core/Core/Movie.cpp
- Source/Core/Core/Movie.h
1. Comparing `std::string_view`s does not behave the same as `strncmp` in the case where `SConfig`'s game ID is longer than 6 chars.
2. `DTMHeader::GetGameID` wasn't excluding null bytes for game IDs shorter than 6 chars.
3. `==` was accidentally used instead of `!=`.
> Movie: Fix 83b9fef regressions

- Source/Core/Core/Config/MainSettings.cpp
- Source/Core/Core/Config/MainSettings.h
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/Core/ConfigManager.cpp
- Source/Core/DolphinQt/Settings.cpp
- Source/Core/DolphinQt/Settings.h
- Source/Core/DolphinQt/Settings/GeneralPane.cpp
- Source/Core/DolphinQt/Settings/GeneralPane.h
A user-selected fallback to use instead of the default PAL
This can be used for unknown region or region free titles to give them the ability to force a different region than the current fallback region of PAL. This can be useful if a user is trying to play a region free title that is originally NTSC and expects to be run at NTSC speeds. This may be done when a user attempts to dump a WAD of their own without understanding the settings they have chosen, or could be an intentional decision by a developer of a ROM hack that can be injected into a Virtual Console WAD.
This is primarily a proof-of-concept in its current stage.
> Fallback Region Option

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/res/values/strings.xml
This will make debugging C++ issues more convient on Android. I also clarified `debug_warning` since settings no longer fall under one `HeaderSetting`.
> Android: Add "Disable Fastmem" debug setting

- CMakeLists.txt
This vendored library does not need to be installed,
as it is statically linked in. See https://github.com/dolphin-emu/dolphin/pull/6983#issuecomment-401833791
> Exclude Discord RPC lib from installation

- Source/Core/VideoCommon/FrameDump.cpp
- Source/Core/VideoCommon/FrameDump.h
- Source/Core/VideoCommon/RenderBase.cpp
- Source/Core/VideoCommon/RenderBase.h
@vadosnaprimer Does this fix your "frame 0" A/V sync problem?
> FrameDump: Start timing at 0 ticks when starting from boot

- Source/CMakeLists.txt
- Source/UnitTests/Core/PowerPC/Jit64Common/ConvertDoubleToSingle.cpp
- Source/UnitTests/Core/PowerPC/Jit64Common/Frsqrte.cpp
If the compiler can detect an issue with a format string at compile
time, then we should take advantage of that and turn the issue into a
hard compile-time error as such problems almost always lead to UB.
This helps with catching logging or assertion messages that have been
converted over to fmt but are still using the old, non-fmt variants
of the logging macros.
This commit also fixes all incorrect usages that I could find.
(Rebased version of #9284 which GitHub stopped updating for some reason)
> Turn format string issues into compile-time errors

- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
- Source/Core/Core/PowerPC/PowerPC.cpp
Fixes https://bugs.dolphin-emu.org/issues/12327.
When we started using fmt in CheckExternalExceptions, JitArm64 mysteriously stopped working even though the code path where fmt was used never was reached. This is because the compiler added a function prologue and epilogue to set up the stack, since the code path that used fmt required the use of the stack.
However, the breakage didn't actually have anything to do with the usage of the stack in itself, but rather with the compiler's insertion of a stack canary. In the function epilogue, a cmp instruction was inserted to check that the stack canary had not been overwritten during the execution of the function. This cmp instruction overwriting the status flags ended up having a disastrous side effect once execution returned to code emitted …
> JitArm64: Do downcount immediately before jumping to dispatcher

- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
In order to reach the middle guard (at `m_stack_base + GUARD_OFFSET`) before the bottom guard (at `m_stack_base`), the stack pointer must start at an address which is higher than the middle guard. It also didn't make sense that we were allocating memory and then not using the top part of it.
> JitArm64: Properly set m_stack_pointer

- Source/Core/Core/IOS/ES/ES.h
- Source/Core/Core/IOS/ES/NandUtils.cpp
- Source/Core/Core/IOS/FS/FileSystem.h
- Source/Core/Core/WiiUtils.cpp
Nintendo's official title installation code and ES both only look at
content IDs but we should probably check for content hashes in addition
to checking for IDs for at least two reasons:
1. Some of the installed contents could be corrupted -- this cannot be
easily detected without checking hashes.
2. Some mod distributors do not bother to update content IDs, which
means that installing updated WADs from the UI would not actually
update the installed game. This is confusing for users.
To keep the existing semantic (for IOS especially), the new content
hash checks are opt-in for callers of GetStoredContentsFromTMD.
This commit changes WiiUtils's WAD installation logic to enable
the content hash checks.
> WiiUtils: Check hashes to determine if a title is installed and up-to-date

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/MenuFragment.java
- Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
- Source/Android/app/src/main/res/values/strings.xml
- Source/Core/Core/Config/UISettings.cpp
- Source/Core/Core/Config/UISettings.h
I moved it from the main settings screen to the in-game menu in PR #8439 so that it could be changed while a game is running, but now that the main settings can be accessed while a game is running, there's no reason to not put it in the main settings.
https://bugs.dolphin-emu.org/issues/12067
> Android: Move orientation setting to main settings screen

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/viewholder/FilePickerViewHolder.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ContentHandler.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
- Source/Android/app/src/main/res/drawable/invalid_setting_background.xml
- Source/Android/app/src/main/res/values/colors.xml
- Source/Android/app/src/main/res/values/strings.xml
- Source/Android/jni/AndroidCommon/AndroidCommon.cpp
- Source/Android/jni/AndroidCommon/AndroidCommon.h
- Source/Core/Common/File.cpp
This is part of my efforts to add support for scoped storage.
> Android: Use storage access framework for custom SD card paths

- Source/Core/Common/FileUtil.cpp
- Source/Core/Common/FileUtil.h
- Source/UnitTests/FileUtil.cpp
- Source/UnitTests/UnitTests.vcxproj
Adds a flag to File::Delete and File::DeleteDir dictating whether they emit console warnings when the specified path doesn't exist.  The flags are true by default to maintain existing behavior.
Also modifies the return value of DeleteDir when attempting to delete a nonexistent path to better reflect the intention of the function (nothing's there after the call).  This change doesn't break anything because none of the existing callers actually check the return value.
Adds tests for Delete and DeleteDir.
> Add File::Delete and File::DeleteDir warning flags

- Data/Sys/GameSettings/SAOE78.ini
- Data/Sys/GameSettings/SAOEVZ.ini
The first call to GXCopyDisp() corrupts game data, but on real hardware it isn't observed thanks to the data cache. Skipping the call works too, preventing a crash on boot.
This patch is enabled default.
> GameSettings: Add patch for Monster High: Ghoul Spirit (SAOE78/SAOEVZ)

- Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
Fixes a regression from #9098 (https://bugs.dolphin-emu.org/issues/12322).
Makes `ProcessReadQueue` behaves like it did before the problem PR.
> HW/WiimoteReal: Drop stale data reports.

- Source/Android/jni/NativeConfig.cpp
- Source/Core/Common/Config/Config.cpp
- Source/Core/Common/Config/Config.h
- Source/Core/Common/Config/ConfigInfo.h
- Source/Core/Common/Config/Layer.h
- Source/Core/Core/BootManager.cpp
- Source/Core/Core/Config/SYSCONFSettings.cpp
- Source/Core/Core/Config/SYSCONFSettings.h
- Source/Core/Core/ConfigLoaders/BaseConfigLoader.cpp
- Source/Core/Core/ConfigLoaders/GameConfigLoader.cpp
- Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
- Source/Core/DolphinQt/Config/Graphics/GraphicsBool.h
- Source/Core/DolphinQt/Config/Graphics/GraphicsInteger.h
- Source/Core/DolphinQt/Config/Graphics/GraphicsSlider.h
- Source/Core/DolphinQt/NetPlay/NetPlaySetupDialog.cpp
- Source/Core/UICommon/CommandLineParse.cpp
- Source/Core/UICommon/DiscordPresence.cpp
The goal of this change is to make `Config::Get(const Info<T>&)` fast so that we can use it in hot paths.
This is the second iteration of PR #9103. The core idea is the same, but the way cache invalidation is handled is completely different. Compared to PR #9103, reading settings is slower (but still much faster than master) and changing settings is faster (very close to the speed of master).
A benchmark of one million calls to `Config::Get(const Info<bool>&)`, adding each returned value to an int variable:
5.0-13178: 930 ms
This PR: 27 ms
> Add caching to Config::Info

- Source/Core/Core/HW/AddressSpace.cpp
- Source/Core/Core/HW/AddressSpace.h
- Source/Core/Core/HW/HW.cpp
This prevents some crashes when clicking around the memory view when no game is running. For example, try hitting the 'Dump MRAM' button.
> Core/AddressSpace: Return null accessors when no game is running to prevent out-of-bounds memory accesses.

- Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
- Source/Core/InputCommon/ControllerInterface/ControllerInterface.h
- Source/Core/InputCommon/ControllerInterface/Win32/Win32.cpp
Fix for [issue 12253](https://bugs.dolphin-emu.org/issues/12253).
Make sure `m_is_populating_devices` is true when a `WM_INPUT_DEVICE_CHANGE` event is received directly on the ciface thread, so that callbacks aren't (improperly) dispatched while in the process of removing devices. This fixes a race condition between the ciface thread and the CPU thread that results in a deadlock when disconnecting an emulated Wii remote.
> InputCommon: Fix callback dispatch deadlock

- Source/Core/Core/HW/WiimoteEmu/Dynamics.cpp
- Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
Emulated Wii remote's tilt simulation will now wrap around to reach the target angle in the shortest direction.
This can easily be triggered when the "Angle" setting is higher than 90 degrees (it's 85 by default).
A full 360 degree rotation required by some games is now possible.
Fixes: https://bugs.dolphin-emu.org/issues/12289
> WiimoteEmu: Allow tilt to wrap around and simulate full 360 degree rotations.

- Data/Sys/GameSettings/GCC.ini
- Data/Sys/GameSettings/GCCE01.ini
This fixes the crash at Goblin Wall: https://bugs.dolphin-emu.org/issues/9915
A patch (for the US release only) that fixes the game's buffer overrun bug is included as an alternative with lower performance cost. It is disabled by default.
This game makes use of EFB to RAM copies for various post-processing effects. When doing so, it first attempts to copy texture data in RGBA8 format (8 bits per channel), presumably to maintain the best possible image quality. If the destination buffer is too small, it will fall back on RGB565, which only requires half the space.
Unfortunately, when calculating the required space, the game fails to take into account the padding introduced by tiling on the GPU. There is a helper function provided by the SDK for this purpose which the game does make use of …
> GameSettings: Disable "Store EFB Copies to Texture Only" for Final Fantasy Crystal Chronicles

- Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp
- Source/Core/DolphinQt/RenderWidget.cpp
MidButton has been deprecated since Qt 4.7. The replacement is
MiddleButton.
> Qt: Fix deprecated use of MidButton

- Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
The tooltips leverage rich-text which uses a type of html.  Therefore the text "< gameid >" was being interpreted as a tag (looks like github does that too!).  Instead, we need to use the html code for greater-than and less-than signs.
Fixes https://bugs.dolphin-emu.org/issues/12353
> DolphinQt: Fix all instances of <gameid> in AdvancedWidget

- Source/Core/Common/LinearDiskCache.h
Without this you run into two issues:
- Since it breaks out after reading the `value_size` but before reading the actual value, the file position is not aligned on a boundary between values, so it would have no chance to find any newly written values the next time the cachefile is opened.
- ...But it probably doesn't come to that because of a [quirk in files opened in r+ mode](https://stackoverflow.com/questions/3206913/c-standard-library-corner-case). Thankfully Visual Studio's debug mode [catches this](https://i.imgur.com/NgqVNC8.png), I would have never found this otherwise.
I also took the opportunity to replace the manual new/delete with an unique_ptr.
> Common/LinearDiskCache: Handle truncated shadercache files.

- Source/Core/Common/Image.cpp
Fixes writes to paths with non-ASCII characters, as discussed after the merge in #9289.
> Common: Write PNGs in two steps to allow Unicode target paths.

- Source/Core/Core/HW/EXI/EXI_Device.h
This keeps the enum values consistent across platforms in case new entries are added after EXIDEVICE_ETHTAPSERVER.
> EXI_Device: Always define EXIDEVICE_ETHTAPSERVER for consistency

- Source/Core/Core/CMakeLists.txt
- Source/Core/Core/Core.vcxproj
- Source/Core/Core/Core.vcxproj.filters
- Source/Core/Core/System.cpp
- Source/Core/Core/System.h
Introduces the system class that will eventually contain all relevant system state, as opposed to everything being distributed all over the place as global variables.
Throughout the codebase we have code that from its interface-view, does not actually require its dependencies to be described in the interface, and we routinely run into issues with initialization where we sometimes make use of a facility before it's been initialized, which leads to annoying to debug cases, because the reader needs to run through the codebase and see what order things get initialized in, and how they're being used. This is particularly a frequent issue in the video code.
Further, we also have a lot of code that makes use of file-scope variables (many of which are non-trivial), which must all be default …
> Core: Add initial System class

- Source/Core/Common/MemoryUtil.cpp
HW_PHYSMEM is deprecated on OpenBSD and only supplies a 32-bit value on NetBSD.
Relevant documentation:
* https://man.openbsd.org/sysctl.2
* https://man.netbsd.org/sysctl.7
> MemoryUtil: Use HW_PHYSMEM64 sysctl in MemPhysical

- Source/Core/Core/PowerPC/Jit64/RegCache/FPURegCache.cpp
This performance bug was probably a simple copy-paste error. (The function was identical to `GPRRegCache::GetRegUtilization`.)
> Jit64: Fix FPURegCache::GetRegUtilization

- CMakeLists.txt
CMake's CMAKE_SYSTEM_PROCESSOR call returns "arm64" on Apple Silicon.
> CMake: Apple Silicon detection

- Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
As pointed out by @MerryMage in PR #9262, signed bitwise left shift invokes UB when shifting a negative value.
> JitArm64: Fix signed bitwise left shift UB

- CMakeLists.txt
- Source/Core/Core/PowerPC/GDBStub.cpp
While the gdbstub is somewhat broken at the moment, building it by
default should keep us from breaking the build (which has happened
several times in the past: #2614, #5904, #8262, #9359).
It isn't very intrusive and it does nothing unless it is enabled
in the config file.
> Fix GDBStub build and build it by default 

- Source/Core/VideoCommon/FreeLookCamera.cpp
- Source/Core/VideoCommon/FreeLookCamera.h
- Source/Core/VideoCommon/RenderBase.cpp
During the Free Look refactor (#8867 ) I apparently forgot to test loading a fifo log.  A crash occurs there because the camera control type is not set and therefore the controller is null.
This fixes the crash and adds some safety checks to check for null pointers.
Sorry about that!
EDIT: This crash is not specific to fifo per-se.  It's just the fifo logs I tested had an initial frame of projection-type perspective where we call [GetView()](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/VideoCommon/VertexShaderManager.cpp#L423).  Most games I tested startup with a projection type of orthographic, giving time for `Renderer::CheckForConfigChanges()` to [update the control type](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/VideoCommon/RenderBase.cpp#L409).
> VideoCommon: Fix crash that occurs on loading a fifo log when Free Look is enabled

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Analytics.java
- Source/Android/app/src/main/res/values/strings.xml
In PR #9357, I intended to update the main activity, emulation activity and game properties dialog, but I forgot to actually update the game properties dialog. This commit fixes that.
The changes outside of GamePropertiesDialog.java are just to hide the Wii controller settings for GameCube games.
> Android: Only have one settings entrypoint in game properties

- Source/Core/Core/CoreTiming.cpp
- Source/Core/Core/PowerPC/CachedInterpreter/CachedInterpreter.cpp
- Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
I find the performance monitor functionality useful for timing hardware tests, but unfortunately it hasn't worked correctly in Dolphin except when using the x86-64 JIT with no idle skipping. This PR makes it work (mostly) correctly on all CPU emulation cores.
> Call UpdatePerformanceMonitor when needed

- Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
It is possible to generate more optimal instruction sequences for various instructions if some or all of the input registers are known to hold a specific value.
---
**subfic**
<details><summary>Example</summary>
Before:
```
BE 03 00 00 00       mov         esi,3
83 EE 08             sub         esi,8
0F 93 45 58          setae       byte ptr [rbp+58h]
```
After:
```
C6 45 58 00          mov         byte ptr [rbp+58h],0
```
</details>
---
**srwx**
<details><summary>Example 1</summary>
Before:
```
B9 18 00 00 00       mov         ecx,18h
45 8B C1             mov         r8d,r9d
49 D3 E8             shr         r8,cl
```
After:
```
45 8B C1             mov         r8d,r9d
41 C1 E8 18          shr         r8d,18h
```
</details>
<details><summary>Example 2</summary>
Before:
```
B9 00 00 00 00 …
```
> Jit64: More constant propagation optimizations

- Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
BEXTR is one uop on AMD only. On Intel one would prefer to shift+mask.
> Jit_Integer: rlwinmx: Use BEXTR where possible

- Externals/enet/CMakeLists.txt
- Externals/gtest/CMakeLists.txt
- Externals/mbedtls/CMakeLists.txt
- Externals/miniupnpc/CMakeLists.txt
- Externals/pugixml/CMakeLists.txt
My IDE was showing me CMake warnings and it was annoying.
"CMake Deprecation Warning at Externals/enet/CMakeLists.txt:1 (cmake_minimum_required):Compatibility with CMake < 2.8.12 will be removed from a future version of\nCMake.\n\nUpdate the VERSION argument <min> value or use a ...<max> suffix to tell\nCMake that the project does not need compatibility with older versions."
I've specified version 2.8.12 to eliminate the warnings.
> CMake: Update cmake_minimum_required calls using versions less than 2.8.12.

- Source/Core/Core/Core.vcxproj.filters
Without this, Visual Studio will try to fix the problem on its own any time the file is changed.
> Fix Core.vcxproj.filters

- Source/Core/Core/DSP/DSPCore.cpp
- Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp
The only usages of this define are within this source file.
> DSPCore: Move PRECISE_BACKLOG define to the interpreter code

- Source/Core/DolphinQt/Settings/AudioPane.cpp
On platforms where there is at least one audio backend supporting latency (e.g. Windows), the latency field was enabled on all backends, even if they don't support it, though it would become disabled after changing the backend.  This also happened after emulation is stopped.  The cause was `OnEmulationStateChanged` not checking if the backend supported latency; `OnEmulationStateChanged` is called when the audio pane is first constructed.
> Fix latency field being initially enabled on audio backends not supporting it

- Source/Core/Core/DSP/DSPAnalyzer.cpp
- Source/Core/Core/DSP/DSPAnalyzer.h
- Source/Core/Core/DSP/DSPCore.cpp
- Source/Core/Core/DSP/DSPCore.h
- Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp
- Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp
- Source/Core/Core/DSP/Jit/x64/DSPJitBranch.cpp
- Source/Core/Core/HW/DSPLLE/DSPHost.cpp
Turns the DSP analyzer into a class and situates it within the SDSP struct. With this, I believe all relevant state within the DSP code has been made non-global.
These changes were significantly easier to chunk out into parts for review, as opposed to the deglobalization efforts in DSPCore, as the file-scope state itself was already hidden behind an interface. This more-or-less allowed for "sliding" the class into place in an easier manner.
Each commit should explain what it does and any rationale for it if necessary.
> DSPAnalyzer: Migrate off file-scope state

- Source/Core/Core/DSP/DSPCore.cpp
- Source/Core/Core/DSP/DSPCore.h
- Source/Core/Core/DSP/DSPHWInterface.cpp
- Source/Core/Core/HW/DSPLLE/DSPLLE.cpp
Avoids implicit conversions and also prevents dumping identifiers into the current namespace.
While we're at it, we can make the mailbox members private, given they aren't accessed externally
> DSP: Convert Mailbox enum into an enum class

- Source/Core/Core/DSP/DSPCore.cpp
- Source/Core/Core/DSP/DSPCore.h
- Source/Core/Core/DSP/DSPHWInterface.cpp
- Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp
- Source/Core/Core/HW/DSPLLE/DSPHost.cpp
Makes all members that aren't used by the JIT private to reduce the number of freely modifiable members
> DSPCore: Make several SDSP members private

- Source/Core/Core/ActionReplay.cpp
- Source/Core/Core/Core.cpp
- Source/Core/Core/CoreTiming.cpp
- Source/Core/Core/GeckoCode.cpp
- Source/Core/Core/HW/EXI/EXI_DeviceGecko.cpp
- Source/Core/Core/HW/EXI/EXI_DeviceMic.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp
- Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp
- Source/Core/Core/HW/SI/SI_DeviceGBA.cpp
- Source/Core/Core/HW/SystemTimers.cpp
- Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
- Source/Core/Core/IOS/IOS.cpp
- Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp
- Source/Core/Core/IOS/USB/Host.cpp
- Source/Core/Core/IOS/USB/LibusbDevice.cpp
- Source/Core/Core/IOS/USB/OH0/OH0.cpp
- Source/Core/Core/IOS/USB/USBV5.cpp
- Source/Core/Core/IOS/USB/USB_HID/HIDv4.cpp
- Source/Core/Core/IOS/USB/USB_HID/HIDv5.cpp
- Source/Core/Core/IOS/USB/USB_VEN/VEN.cpp
- Source/Core/Core/Movie.cpp
- Source/Core/Core/NetPlayClient.cpp
- Source/Core/Core/State.cpp
C++17 allows omitting the mutex type, which makes for both less reading and more flexibility (e.g. The mutex type can change and all occurrences don't need to be updated).
> Core: Make use of C++17 deduction guides with locks

- Source/Core/Common/Config/Config.cpp
The config version should always be incremented whenever config is
changed, regardless of callbacks being suppressed or not.
Otherwise, getters can return stale data until another config change
(with callbacks enabled) happens.
> Config: Fix cache not being invalidated when callbacks are suppressed

- Source/Core/Core/FifoPlayer/FifoRecorder.cpp
- Source/Core/Core/NetPlayClient.cpp
- Source/Core/Core/NetPlayServer.cpp
Cleans up some locks that explicitly specify the recursive mutex type in it. Meant to be included with the previous commit that cleaned out regular mutexes, but I forgot.
> Core: Use C++17 deduction guides with locked recursive mutexes

- Source/Core/Core/SysConf.cpp
- Source/Core/Core/SysConf.h
Allows strings to be used in potentially non-allocating manners.
> SysConf: Make use of std::string_view 

- Source/Core/Core/IOS/IOS.cpp
- Source/Core/Core/IOS/IOS.h
Allows lookups to be done with std::string_view or any other string type. This allows for non-allocating strings to be used with the name lookup without needing to construct a std::string.
While we're at it, we can make use of `insert_or_assign` in AddDevice to elide unnecessary default constructions (not like it particularly matters, however it's essentially a "free" change, so why not).
> IOS: Allow for heterogenous name lookup

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsAdapter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/utils/SettingsFile.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ContentHandler.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/FileBrowserHelper.java
- Source/Android/app/src/main/res/values/strings.xml
- Source/Android/jni/AndroidCommon/AndroidCommon.cpp
- Source/Android/jni/AndroidCommon/AndroidCommon.h
- Source/Android/jni/AndroidCommon/IDCache.cpp
- Source/Android/jni/AndroidCommon/IDCache.h
- Source/Core/Common/FileSearch.cpp
- Source/Core/Common/FileUtil.cpp
- Source/Core/Common/FileUtil.h
- Source/Core/Core/Boot/Boot.cpp
This is part of my efforts to add support for scoped storage.
A commit from PR #9167 is included in this PR. It should be merged as part of this PR to avoid users getting old-style paths in Dolphin.ini.
> Android: Use storage access framework for game list

- Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Makes it explicit that these are intentional. Also prevents compiler warnings.
> JitArm64_LoadStore: Explicitly annotate switch fallthrough cases

- Source/Core/Common/ArmCommon.h
Adds a missing header guard to prevent inclusion issues from occurring.
While we're in the same area, we can also mark a constant as constexpr.
> ArmCommon: Add missing header guard

- Source/Core/Common/Arm64Emitter.cpp
- Source/Core/Common/Arm64Emitter.h
- Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Tidies up the interface a little by annotating switch fallthrough to avoid warnings. While we're at it we can convert quite a few enums into enum classes to prevent polluting namespaces and making their usage strongly typed.
> Arm64Emitter: Interface cleanup

- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
- Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h
- Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Tidies up the interface in various minor ways, such as:
- Marking member funcs as const when they don't modify internal state
- Converting enums to enum classes
- In-class initializing member variables where applicable.
Converting the RegType enum over to an enum class in particular uncovered an odd quirk in two places. RegType enum members were being passed as the second argument to `BindToRegister` [here](https://github.com/dolphin-emu/dolphin/commit/8659a4d6d02dc352d2c2e41f39d485d4efbf1ca1#diff-bc54c6351f0ce20b932a4aa98992e19a69cdc5c55d5be79f839b25c8bf4b6d7cR60) and [here](https://github.com/dolphin-emu/dolphin/compare/master...lioncash:arm?expand=1#diff-bc54c6351f0ce20b932a4aa98992e19a69cdc5c55d5be79f839b25c8bf4b6d7cR152) which is very unusual, as the second member of `BindToRegister` …
> JitArm64_RegCache: Interface cleanup

- Source/Core/Core/PowerPC/JitArm64/Jit.cpp
- Source/Core/Core/PowerPC/JitArm64/Jit.h
- Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Migrates the Aarch64 JIT tables over to the same tabling mechanism as the x64 JIT in which we just compute them all at compile-time.
> JitArm64_Tables: Construct tables at compile-time

- Source/Core/Common/Arm64Emitter.cpp
- Source/Core/Common/Arm64Emitter.h
Makes the enums strongly typed. While we're at it, we can also make these enums private.
> Arm64Emitter: Convert ArithOption enums into enum classes

- Source/Core/Common/Arm64Emitter.h
This isn't used anywhere, so we can remove it.
> Arm64Emitter: Remove unused OpType enum

- Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Applying PR #8687 to Arm64 JIT.
> JitArm64: Do not use offsetof on non-standard-layout types

- Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp
- Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm
- Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp
In every implementation.
Setting the window or renderer widget size to 0 is possible, at least in Windows, even when rendering in the main window, so it could probably happen under any OS, and anyway, it doesn't hurt to check.
> Fix cursor going to +infinite if the window size was 0

- Source/Core/Common/BitUtils.h
Introduced in #9374. `__builtin_clz(0)` produces an undefined value. 
Apologies for error.
> BitUtils: __builtin_clz is undefined when value == 0

- Source/Core/Core/HW/DSP.cpp
https://bugs.dolphin-emu.org/issues/6749
This change fixes the scratchy audio in Teenage Mutant Ninja Turtles (SX7E52/SX7P52). The game starts an audio interface DMA with an unaligned address, and because Dolphin was not masking off the low 5 bits of AUDIO_DMA_START_LO, all future AI DMAs were misaligned. To understand why, it is instructive to refer to AUDIO_InitDMA() in libogc, which behaves the same as the official SDK:
`_dspReg[25] = (_dspReg[25]&~0xffe0)|(startaddr&0xffff);`
The implementation does not mask off the low bits of the passed in value before it ORs them with low bits of the current register value. Therefore, if they are not masked off by the hardware itself, they become permanently stuck once set.
Adding a write mask for AUDIO_DMA_START_LO is enough to fix the bug in …
> DSP: Fix write masks on AUDIO_*/AR_* MMIO registers

- Externals/curl/lib/CMakeLists.txt
- Externals/hidapi/CMakeLists.txt
* curl requires zlib
* hidapi when not using libudev requires libusb
> Externals: Link against required libraries

- Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
-If adding 2 devices with the same name, their unique identifier wouldn't be increased, causing a conflict.
-Removing a device wouldn't actually remove it from the internal devices list because the local list of devices had already been updated when iterating it.
-It was possible to remove devices belonging to other input sources by adding a device with the same name and then removing it.
> Fix DualShockUDP not adding/removing devices correctly

- Source/Core/Core/HW/WiiSave.cpp
- Source/Core/Core/HW/WiiSave.h
- Source/Core/Core/HW/WiiSaveStructs.h
- Source/Core/Core/IOS/ES/ES.h
- Source/Core/Core/IOS/ES/TitleManagement.cpp
- Source/Core/Core/WiiUtils.cpp
- Source/Core/Core/WiiUtils.h
- Source/Core/DolphinQt/GameList/GameList.cpp
- Source/Core/DolphinQt/MenuBar.cpp
In practice, this means:
- ~~Saves are now only allowed to be imported if the game was previously 'seen' by ES. This includes launching it or even just inserting the game into the disc drive while the Wii Menu is running.~~ Turns out this was previously the case too, but in a rather implicit fashion. This is now more explicit and works like the Wii Menu where it reinstalls a TMD if it's in the `tmds.sys` backup file. (which can happen if you had a save once and then delete it)
- Saves are now deleted before a new one is imported. This prevents a few potential oddities like ending up with mixed old and new files, or [completely failing the import on saves with subdirectories](https://forums.dolphin-emu.org/Thread-problem-with-importing-game-save-file).
Please scrutinize this, I'm not …
> Make WiiSave::Import() behave closer to the Wii System Menu's SD Card save copying.

- CMakeLists.txt
- Source/Core/Common/CMakeLists.txt
- Source/Core/Common/GL/GLContext.cpp
- Source/Core/Common/GL/GLInterface/BGL.cpp
- Source/Core/Common/GL/GLInterface/BGL.h
- Source/Core/Common/WindowSystemInfo.h
- Source/Core/Core/HW/EXI/EXI_DeviceEthernet.h
- Source/Core/DolphinQt/MainWindow.cpp
- Source/Core/VideoCommon/DriverDetails.cpp
- Source/Core/VideoCommon/DriverDetails.h
Much less invasive than the equivalent changes that were removed; it looks like things are a lot simpler than they were a few years ago when I last attempted this.
Unlike that attempt, this one is indeed able to boot games (after fixing a bug in our Qt port): http://0x0.st/iFif.png
> Rehabilitate Haiku support.

- Source/Core/Core/Analytics.cpp
- Source/Core/Core/Analytics.h
- Source/Core/Core/IOS/Device.cpp
- Source/Core/Core/IOS/Device.h
- Source/Core/Core/IOS/Network/NCD/Manage.cpp
- Source/Core/Core/IOS/Network/NCD/Manage.h
- Source/Core/Core/IOS/Network/WD/Command.cpp
- Source/Core/Core/IOS/Network/WD/Command.h
- Source/Core/Core/State.cpp
This PR fixes the implementation of three ioctlvs: Lock, Unlock (in NCD) and GetInfo (in WD), based on the implementation in IOS59.
Without a correct implementation for those three ioctlvs, Nintendo's MPDL code (no clue what it stands for) will fail at initialization time and return an error to the caller. If a title does not check for errors correctly (e.g. Driver San Francisco or Tales of Graces), this can result in game crashes.
DS communication is still unimplemented but now it actually has a chance of working if it is implemented in the future.
Fixes [issue 11977](https://bugs.dolphin-emu.org/issues/11977) **but now the game hangs when cancelling**, so this is a partial fix. I am submitting this now to keep the diff small and avoid merge conflicts.
Also, the Mii Channel doesn't …
> IOS: WD and NCD fixes

- Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
The name was confusing as changing it at runtime would not change the window to fullscreen, as it effectively only affects the start of the emulation.
Also blocked the ability to change it when the emulation is running, to be more inline with other similar settings, like "Render to main Window".
> Rename "Use Fullscreen" setting to "Start in Fullscreen"

- Data/Sys/GameSettings/GHAE08.ini
- Data/Sys/GameSettings/GHAJ08.ini
- Data/Sys/GameSettings/GHAP08.ini
- Data/Sys/GameSettings/GLEE08.ini
- Data/Sys/GameSettings/GLEJ08.ini
- Data/Sys/GameSettings/GLEP08.ini
- Source/Core/Core/PatchEngine.cpp
- Source/Core/Core/PatchEngine.h
- Source/Core/DolphinQt/Config/NewPatchDialog.cpp
- Source/Core/DolphinQt/Config/NewPatchDialog.h
- Source/Core/DolphinQt/Config/PatchesWidget.cpp
These games are erroneously zeroing buffers before they can be fully copied to ARAM by DMA. The responsible memset() calls are followed by a call to DVDRead() which issues dcbi instructions that effectively cancel the memset() on real hardware. Because Dolphin lacks dcache emulation, the effects of the memset() calls are observed, which causes missing audio.
In a comment on the original bug, phire noted that the issue can be corrected by simply nop'ing out the offending memset() calls. Because the games dynamically load different .rel executables based on the character and/or language, the addresses of these calls can vary.
To deal generally with the problem of dynamic code being loaded to fixed, known addresses, the patch engine is extended to support conditional patches which require a …
> Patches for Resident Evil 2/3 audio issues

- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
- Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java
See the comment I added to the code. This is a rather serious issue for Android TV users from what I've heard.
For reference, we switched folder pickers in PR #9318.
> Android: Use old folder picker on Android TV

- Source/Core/Common/BitUtils.h
fixes C3615 on some msvc/cmake configs
> BitUtils: initialize variables

- Source/Core/Core/HW/WiimoteCommon/WiimoteReport.h
- Source/PCH/pch.h
The workaround is no longer required :)
> Bump msvc version check and revert a msvc workaround
