dolphin-emu/dolphin

Source/Core/Core/Core.vcxproj, Source/Core/Core/Core.vcxproj.filters, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/Core/PowerPC/GDBStub.h, Source/VSProps/Base.props
This does nothing about it actually being usable (it seems it has historically not really worked, but I haven't tested).
The windows cmake build tends to default to enabling this(causing build to fail). This commit keeps them in sync and fixes the build.
=> msbuild: enable USE_GDBSTUB

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
FinalizeCarryOverflow didn't maintain XER[OV/SO] properly due to an oversight. Here's the code it would generate:
```
0:  9c                      pushf
1:  80 65 3b fe             and    BYTE PTR [rbp+0x3b],0xfe
5:  71 04                   jno    b <jno>
7:  c6 45 3b 03             mov    BYTE PTR [rbp+0x3b],0x3
000000000000000b <jno>:
b:  9d                      popf
```
At first glance it seems reasonable. The host flags are carefully preserved with PUSHF. The AND instruction clears XER[OV]. Next, an conditional branch checks the host's overflow flag and, if needed, skips over a MOV that sets XER[OV/SO]. Finally, host flags are restored with POPF.
However, the AND instruction also clears the host's overflow flag. As a result, the branch that follows it is always taken and the MOV is …
=> Jit64: Fix FinalizeCarryOverflow XER[OV/SO]

Source/Core/Common/BitUtils.h
This is rather annoying...is there a better way to fix?
Currently build on msvc/arm64 is broken without this...I assume it's some msvc and/or sdk regression, not really sure.
(edit: oh, it's actually new code https://github.com/dolphin-emu/dolphin/commit/d695fcb1266f0d7776ec987afd7c4e49b764b7c2 so probably it was never tested on msvc/arm64)
=> BitUtils: loosen clz to inline on msvc/arm64

Source/Core/Common/BitUtils.h
* Can use _BitScanReverse{64} for all archs we support with msvc
* Can actually support being used in constexpr evaluation contexts
see https://developercommunity.visualstudio.com/idea/434712/make-intrinsic-functions-supported-in-a-constexpr.html
here is a small test: compiling the following with `cl /Ox /std:c++latest clz.cpp /link /debug`
```c
int main() {
const uint32_t val32 = 9;
const uint64_t val64 = 9;
int clz1 = CountLeadingZeros(val32);
int clz2 = CountLeadingZeros(val64);
constexpr int clz3 = CountLeadingZeros(val32);
constexpr int clz4 = CountLeadingZeros(val64);
printf("%d %d %d %d\n", clz1,  clz2,  clz3,  clz4);
return 0;
}
```
arm64:
```c
int __cdecl main(int argc, const char **argv, const char **envp)
{
unsigned int v3; // w10
__int64 v4; // x1
unsigned int v5; // w10 …
```
=> BitUtils: cleanup constexpr usage for msvc clz

Source/Core/Core/FifoPlayer/FifoAnalyzer.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
Defined to be 0x44 here:
https://github.com/dolphin-emu/dolphin/blob/79a234eff728b2aeb68c9848f2e4fe861d4f3b91/Source/Core/VideoCommon/OpcodeDecoding.h#L30
and already used in OpcodeDecoding here:
https://github.com/dolphin-emu/dolphin/blob/79a234eff728b2aeb68c9848f2e4fe861d4f3b91/Source/Core/VideoCommon/OpcodeDecoding.cpp#L202-L206
That log message also has a 0x44 in it, but since it seems like the exact purpose of this command is unknown, I think it's fine to leave it like that.  On the other hand, the code uses in both `FifoAnalyzer.cpp`s are a situation where we want `0x44` to match the name, especially if the name is later changed.
=> Use GX_CMD_UNKNOWN_METRICS instead of magic number 0x44

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Improved code generation for `subfx` in various cases.
---
**d == a and is constant**
<details><summary>Example 1</summary>
Before:
```
BF 1E 00 00 00       mov         edi,1Eh
8B C7                mov         eax,edi
8B FE                mov         edi,esi
2B F8                sub         edi,eax
```
After:
```
8D 7E E2             lea         edi,[rsi-1Eh]
```
</details>
<details><summary>Example 2</summary>
Before:
```
BE 00 AC 3F 80       mov         esi,803FAC00h
8B C6                mov         eax,esi
8B 75 EC             mov         esi,dword ptr [rbp-14h]
2B F0                sub         esi,eax
```
After:
```
8B 75 EC             mov         esi,dword ptr [rbp-14h]
81 EE 00 AC 3F 80    sub         esi,803FAC00h
```
</details>
---
**a == 0**
<details><summary>Example</summary> …
=> Jit64: subfx optimizations

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Avoid unnecessary `MOV` instructions and `RCX` use when BMI2 is available.
=> Jit_Integer: Use SHLX, SHRX, SARX

Source/Android/gradle.properties
PR #7864 accidentally duplicated two keys in gradle.properties
=> gradle.properties: Remove duplicate property keys

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp, Source/Core/VideoCommon/VertexLoaderARM64.cpp
Straightforward conversion of ShiftType from enum to enum class.
=> Arm64Emitter: Convert ShiftType to enum class

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
For certain occurrences of nandx/norx, we declare a ReadWrite constraint on the destination register, even though the value of the destination register is irrelevant. This false dependency would force the RegCache to generate a redundant MOV when the destination register wasn't already assigned to a host register.
Example 1:
```
BF 00 00 00 00       mov         edi,0
8B FE                mov         edi,esi
F7 D7                not         edi
```
Example 2:
```
8B 7D 80             mov         edi,dword ptr [rbp-80h]
8B FE                mov         edi,esi
F7 D7                not         edi
```
=> Jit64: boolx - Eliminate read dependency

Source/Core/Core/FreeLookManager.cpp
We need to acquire the global input lock before accessing any control states just to be safe.  This was missed when #8867 was merged.  Thanks to @Filoppi for catching it!
=> FreeLookManager: acquire global input lock

Tools/run-unit-tests-android.sh
Maybe a little wonky, but I needed a way to run unit tests on AArch64, and this was the best way of running unit tests on Android that I could come up with.
=> Add script for running unit tests on Android device

Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h
Let's reset `m_last_used` for each register that will be used in an instruction before we start allocating any of them, so that one of the earlier allocations doesn't spill a register that we want in a later allocation.
See the individual commits for details.
=> JitArm64: Update registers last used before start of instruction

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Config/CommonControllersWidget.cpp, Source/Core/DolphinQt/Config/CommonControllersWidget.h, Source/Core/DolphinQt/Config/ControllersWindow.cpp, Source/Core/DolphinQt/Config/ControllersWindow.h, Source/Core/DolphinQt/DolphinQt.vcxproj
Pulled from #8823 to make it easier to merge
Should have no functional or visual changes
=> DolphinQt: Move common controller interface logic to its own widget

Source/UnitTests/Core/CoreTimingTest.cpp, Source/UnitTests/Core/IOS/FS/FileSystemTest.cpp, Source/UnitTests/Core/MMIOTest.cpp
Check return value of calls to File::CreateTempDir() from CoreTiming,
FileSystem, and MMIO test classes to verify the test user directory
exists, and fail the tests otherwise.
=> UnitTests: Add setup error checking

Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
Code for attaching a real Wii remote's HID interface to our emulated Bluetooth device is a bit messy.
A dangling pointer in the disconnect routine was causing a crash on Windows.
Fixes:
https://bugs.dolphin-emu.org/issues/12329
https://bugs.dolphin-emu.org/issues/12343
https://bugs.dolphin-emu.org/issues/12351
Possibly fixes this issue on macOS?
https://bugs.dolphin-emu.org/issues/9520
=> WiimoteReal: Fix crash on real Wii Remote disconnect on Windows.

Source/Core/Core/MemTools.cpp, Source/UnitTests/Core/PageFaultTest.cpp, Source/VSProps/Base.props, Source/VSProps/Configuration.Base.props
Since VS 16.8, ASAN support is very usable and easy to enable. This commit adds the build configuration settings to use ASAN, you just need to uncomment the `EnableASAN` line in `Source/VSProps/Configuration.Base.props`.
Here's an example of introducing a simple out of bounds access into the dolphin bootup code:
```
c:\src\dolphin>Binary\x64\DolphinNoGUI.exe "e:\gamecube\Animal Crossing NTSC-U.iso"
=================================================================
==59956==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x12012d609bd0 at pc 0x7ff6eaaf2fd4 bp 0x005f9b6fe3b0 sp 0x005f9b6fe3b0
WRITE of size 4 at 0x12012d609bd0 thread T0
#0 0x7ff6eaaf2fd3 in BootManager::BootCore(class std::unique_ptr<struct BootParameters,struct std::default_delete<struct BootParameters> >,struct …
```
=> msvc: enable asan compat

Source/Core/Core/MemTools.cpp
fixes a regression (second emulation run with fastmem enabled will crash) introduced by #9436 :(
=> windows: fix unregistering VEH

Source/Core/Common/TraversalClient.cpp, Source/Core/Common/TraversalClient.h, Source/Core/Common/TraversalProto.h, Source/Core/Common/TraversalServer.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayClient.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/NetPlayServer.h, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Mainly consists of converting enums over to `enum class` to prevent implicit conversions and namespace pollution, along with converting typedefs into using aliases.
=> TraversalProto: Minor cleanup

Source/Core/Core/PowerPC/BreakPoints.cpp
When searching the breakpoint string for `"b"` for the `break_on_hit` flag you can get a false hit because the hex address may include the letter `b`. For example, `80,0cb,46c nl` was incorrectly enabling break on hit.
If you read the next token from the string stream, you will have the flags alone. You can then search these for each letter and you won't get a false hit.
This is quite a neat bug :smile:
=> Breakpoint from string flag parsing using token

Source/Android/jni/NativeConfig.cpp, Source/Core/Common/Config/Layer.h
`EmulationActivity` has an instance of `Settings`. If you go to `SettingsActivity` from `EmulationActivity` and change some settings, the changes get saved to disk, but `EmulationActivity`'s `Settings` instance still contains the old settings in its map of all settings (assuming the `EmulationActivity` was not killed by the system to save memory). Then, once you're done playing your game and exit `EmulationActivity`, `EmulationActivity` calls `Settings.saveSettings`. This call to `saveSettings` first overwrites the entire INI file with its map of all settings (which is outdated) in order to save any legacy settings that have changed (which they haven't, since the GUI doesn't let you change legacy settings while a game is running). Then, it asks the new config system to write the most …
=> Android: Fix in-game settings changes not getting saved

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Config/ControllersWindow.cpp, Source/Core/DolphinQt/Config/ControllersWindow.h, Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp, Source/Core/DolphinQt/Config/WiimoteControllersWidget.h, Source/Core/DolphinQt/DolphinQt.vcxproj
Pulled from #8823 to make it easier to merge
Should have no functional or visual changes
=> DolphinQt: Move wiimote controller ui logic to its own widget

Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
Also avoid files without a name before the extension (name: ".ini") from being added to the list because then they wouldn't be saveable and it would appear with an empty name anyway.
On Windows GetSysDirectory() was returning a path with `//` while being checked against one that had been converted to `\`, so the check would fail and you'd be able to delete system profiles.
=> Qt: Fix stock input profiles being deletable

Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp
QRectF was missing from drawRect which meant the deazone was casted to an int, flooring its value (it goes from 0 to 1).
=> Qt: Fix Shake Mapping Indicator not showing deadzone

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Config/ControllersWindow.cpp, Source/Core/DolphinQt/Config/ControllersWindow.h, Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp, Source/Core/DolphinQt/Config/GamecubeControllersWidget.h, Source/Core/DolphinQt/DolphinQt.vcxproj
Pulled from #8823 to make it easier to merge
Should have no functional or visual changes
=> DolphinQt: Move gamecube controller ui logic to its own widget

Source/Core/DolphinQt/Config/GameConfigEdit.cpp, Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp, Source/Core/DolphinQt/Debugger/NetworkWidget.cpp, Source/Core/DolphinQt/Debugger/RegisterWidget.cpp, Source/Core/DolphinQt/Debugger/ThreadWidget.cpp, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt/QtUtils/FlowLayout.cpp, Source/Core/DolphinQt/QtUtils/WrapInScrollArea.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.cpp
Makes changes that should ease us into transitioning over to Qt 6.0 in the future. Qt 6 brings a few breaking changes with it, and thankfully, replacements for most of those deprecated or removed features were introduced within Qt 5, so we can replace those obsoleted features.
This way when we move to Qt 6, way less things will break due to APIs being removed or changed.
=> DolphinQt: Qt 6.0 forward-compatibility changes

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableButton.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableDpad.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayDrawableJoystick.java, Source/Android/app/src/main/res/layout/dialog_input_adjust.xml, Source/Android/app/src/main/res/menu/menu_overlay_controls_gc.xml, Source/Android/app/src/main/res/menu/menu_overlay_controls_wii.xml, Source/Android/app/src/main/res/values/strings.xml
Added Opacity controls for the user to customize the opacity level of their touchscreen controls. Also, placed both Scale and Opacity settings into one window/option called Adjust Controls.
=> Added Opacity settings for touchscreen controls

Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameList.h
When a game is selected, the option to add a shortcut of the game to the desktop is given. Uses native Windows API since Qt lacks support for adding shortcuts.
This is a modification of #9365 , using WIL and handling all error/memory leak cases correctly (hopefully 🙂)
=> DolphinQT: Gives option to add desktop shortcut

Source/Core/Core/HW/GCKeyboardEmu.cpp, Source/Core/Core/HW/GCPadEmu.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Otherwise they give an error when clicking ok if trying to view or edit the input expressions.
These should be the last ones left that had not been converted yet.
=> InputCommon: Wrap remaining invalid default input expressions around ``

Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
At least on some CPUs (I found out about this from the Arm Cortex-A76 Software Optimization Guide), using X30 with BLR is one cycle slower than using another register.
=> JitArm64: Avoid using X30 with BLR

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.h
PR #2663 added a Jit64 implementation of dcbX and a fast path to skip JIT cache invalidation. Unfortunately, there is a mismatch between address spaces in this optimization. It tests the effective address (with the top 3 bits cleared) against the valid block bitset which is intended to be indexed by physical address. While this works in the common case, it fails (for example) when the effective address is in the 7E... region (a.k.a. "fake VMEM"). This may also fall apart under more complex memory mapping scenarios requiring full MMU emulation.
The good news is that even without this fast path, the underlying call to JitInterface::InvalidateICache() still does very little work in the common case. It correctly translates the effective address to a physical address which it tests against the …
=> Jit: Fix correctness issue in dcbf/dcbi/dcbst

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Fixes a regression from PR #9472.
=> JitArm64: Fix false positive "turned singles into doubles" asserts

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.h
Summary of changes:
- Added a new field for Search Address Offset
- Fixed a hard crash when trying set a value while the core is not running.
- Brushed up the UI and spacing
The primary change here is adding an `Offset` field next to `Search Address`. All this does is add the offset to the supplied search address. While this sounds mediocre on paper, this is incredibly convenient for hack and cheat developers (and especially reverse engineers) who frequently work with base addresses and classes. I have been working on [PrimeHack](https://github.com/shiiion/dolphin) for nearly a year, and I constantly need to work with addresses that are offset from dynamically allocated classes in memory. Adding this simple `Offset` field streamlines traversing through large classes in memory rather than …
=> MemoryWidget: Add 'Offset' and General Improvements

Source/VSProps/Base.props
=> msbuild: re-enable HAS_OPENGL and HAS_VULKAN

Tools/lint.sh
This is needed to bring *nix clang-format version in sync with the version packaged with VS.
The version parsing had to be changed because (Ubuntu 20.10):
```
$ clang-format-9 --version
clang-format version 9.0.1-14build1
$ clang-format-10 --version
Ubuntu clang-format version 10.0.1-6
$ clang-format --version
Ubuntu clang-format version 11.0.0-2
```
I've run clang-format-10 over `Source\**\*.cpp` and `Source\**\*.h`.
=> require clang-format 10.0

Externals/rangeset/include/rangeset/rangeset.h, Externals/rangeset/include/rangeset/rangesizeset.h
On clang-11 build failed as:
```
[ 42%] Building CXX object Source/Core/Core/CMakeFiles/core.dir/PowerPC/Jit64/Jit.cpp.o
In file included from ../../../../Source/Core/Core/PowerPC/Jit64/Jit.cpp:5:
In file included from ../../../../Source/Core/Core/PowerPC/Jit64/Jit.h:21:
../../../../Externals/rangeset/include/rangeset/rangesizeset.h:325:3: error: unknown type name 'size_t'; did you mean 'std::size_t'?
size_t size() const {
^
```
=> Externals/rangeset: use qualified 'size_t'

Source/Core/Core/CMakeLists.txt, Source/Core/Core/Core.cpp, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/Debugger/PPCDebugInterface.h, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/NetworkCaptureLogger.cpp, Source/Core/Core/NetworkCaptureLogger.h, Source/Core/DolphinLib.props, Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
This PR moves the SSL logging part to its own logger class. ~~Not sure, if putting it inside SConfig is a good idea so~~ I'm open to suggestions regarding where it should belong.
=> NetworkCaptureLogger: Move SSL logging

Readme.md
Small PR: The client certificate key file is called `clientcakey.pem`, not `clientcacakey.pem` as previously mentioned in the readme.
=> Fix clientcakey typo in Readme.md

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/PowerPC.h
The savestate incompatibility problem mentioned in a comment was solved by PR #4687.
=> JitArm64: Use STP for (parts of) ppcState.ps

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
* Check for case when source field is at LSB
* Use BFXIL if possible
* Avoid ROR where possible
=> JitArm64_Integer: Add optimizations for rlwimix

Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp
A regression caused by #9440 prevents users from putting in an actual gamepad control because all backticks get stripped.  I think an exact replacement would be just wrapping the expression with "^[a-zA-Z]$".  This is what the [exactMatch docs](https://doc.qt.io/archives/qt-4.8/qregexp.html#exactMatch) seems to indicate.
However, it wasn't immediately obvious what was going on, so I opted for a slightly different expression (and negated the if) along with a comment.  Please let me know if you'd prefer the other.
=> DolphinQt: Fix regression in input expressions

Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp
Fixes https://bugs.dolphin-emu.org/issues/12064
The timer called the lambda expression by interval, causing weird behavior for release functions.
Setting the timer to be one-shot fixes this issue.
=> Fix mapping window title bar becoming unresponsive

Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
PR #9262 added a bunch of Jit64 optimizations, some of which were already in JitArm64 and some which weren't. This PR ports the latter ones to JitArm64.
=> JitArm64: More constant propagation optimizations

Source/Core/DolphinQt/GameList/GameList.cpp
The dolphin-redirect.php script seems to have been present since 2012
at least, but we accidentally stopped using it when the "open wiki"
feature was reimplemented in DolphinQt2 in 2016.
<@delroth> dolphin-redirect.php is slightly smarter and tries to find gameid aliases for e.g. same region
<@delroth> uh, I mean different region
=> Qt: Fix "open wiki" option not using the wiki redirect script

Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/UICommon/GameFile.cpp, Source/Core/UICommon/GameFileCache.cpp
I've added game IDs for ELF and DOL files. This allows the user to set custom game configurations for ELF files and DOL files, as well as to load custom textures at a per elf/dol level. This is extremely useful if you have, for example, multiple mods of Super Smash Bros Brawl. At a technical level, all I'm doing is hashing the file name of the elf and using that as the game ID (thus collisions are possible but exceedingly unlikely). _The user may need to do View->Purge Game List Cache before the the new title IDs appear for their old ELFs and DOLS_. 
For a discussion of reasoning for this pull request see [here](https://forums.dolphin-emu.org/Thread-give-elf-files-unique-game-ids).
=> Working Game IDs for Elf/Dol files

Source/Core/Common/Network.cpp, Source/Core/Common/Network.h, Source/Core/Common/PcapFile.cpp, Source/Core/Common/PcapFile.h, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/Debugger/PPCDebugInterface.cpp, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/NetworkCaptureLogger.cpp, Source/Core/Core/NetworkCaptureLogger.h, Source/Core/DolphinQt/Debugger/NetworkWidget.cpp, Source/Core/DolphinQt/Debugger/NetworkWidget.h
This is more an experimental PR than anything else. It's faking Ethernet/IP headers using Dolphin's MAC and a dummy one. However, it lacks several things such as
- Proper TCP packets with flags, sequence number, etc.
- ~Dolphin's IP is hardcoded, FTM.~
- ~It's still WIP as I haven't tested many cases.~
What it does:
- Log SSL traffic
- Log TCP traffic
- Log UDP traffic
- Create a PCAP file (filename with gamename+timestamp) in Dump/SSL
Regardless, I tested it with different games and it seems to produce a valid PCAP file while logging TCP, UDP and SSL traffic. Config's ~~"NetworkDumpPCAP"~~ "DumpAsPCAP" can be switched to True/False to switch between binary SSL dump and TCP/UDP/SSL PCAP dump.
I'm quite skeptical regarding this method and really think a custom format (or another one) …
=> PCAP logging with fake TCP/UDP packet

Source/Core/VideoBackends/Software/SWVertexLoader.cpp, Source/Core/VideoBackends/Software/SWVertexLoader.h, Source/Core/VideoBackends/Software/TransformUnit.cpp, Source/Core/VideoBackends/Software/TransformUnit.h
The special case doesn't appear to make a significant difference in any games, and the current implementation has a (minor, fixable) issue that breaks Super Mario Sunshine (both with a failed assertion ([bug 11742](https://bugs.dolphin-emu.org/issues/11742)) and a rendering issue ([bug 7476](https://bugs.dolphin-emu.org/issues/7476))).  Hardware testing wasn't able to reproduce the special case, either, so it may just not exist.
PR #9315 contains a fixed implementation of the special case on all video backends, and can serve as a basis for it being reintroduced if it is found to exist under more specific circumstances.  For now, I don't see a reason to keep it present.
=> Software: Remove normalization special case

Source/Core/Core/IOS/Network/SSL.cpp, Source/Core/Core/IOS/Network/SSL.h, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
This PR is a **dirty** workaround to remove the SNI extension from ClientHello. This PR is an alternative to https://github.com/dolphin-emu/dolphin/pull/9406.
It does that by using the only hook that I could find that can be used between handshake steps (see `mbedtls_ssl_handshake_step`). My approach uses the send callback called in `mbedtls_ssl_flush_output` at the beginning of each handshake step. I delayed `mbedtls_ssl_set_hostname` after the client hello as the hostname is needed during the common name verification when connecting to an IP address.
This PR needs testing to be sure there isn't any regression introduced and that there isn't a better way to achieve this goal
=> SSL: Workaround to remove SNI from ClientHello

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp, Source/Core/DolphinQt/Config/Mapping/IOWindow.h
Fixes the expression window being spammed with the first entry in the
Operators or Functions select menus when scrolling the mouse wheel while
hovering over them.
Fixes https://bugs.dolphin-emu.org/issues/12405
=> Config: Fix expression window scroll wheel spam

Data/Sys/GameSettings/RUZ.ini
Ultimate I Spy requires EFB access from CPU to be enabled. Without it, the pointer will not function on the level selection screen, making the game unplayable past the menu.
=> GameINI: Enable EFB access from CPU for Ultimate I Spy

Source/Core/InputCommon/DynamicInputTextureConfiguration.cpp, Source/Core/InputCommon/DynamicInputTextureConfiguration.h, Source/Core/InputCommon/DynamicInputTextureManager.cpp, Source/Core/VideoCommon/HiresTextures.cpp
There was the possibility that a dynamic input texture change would cause a reload of textures while the prefetcher was sorting through them.  This would cause a crash.
Also for packs with multiple configurations, we were calling force reload too many times
=> InputCommon: fix potential dynamic input texture crash and an optimization

Source/Core/DolphinLib.props
It was first added in #3213, and lost in #9092.
=> Restore BitField Natvis

Externals/hidapi/CMakeLists.txt
Because we have an old-style find script that does not define a proper
CMake target for libusb, we need to use ${LIBUSB_LIBRARIES}
rather than "usb".
Ideally, we would fix the find script to define a target. However,
this issue breaks the fifoci-ogl-lin-mesa builder and I'd prefer it
to be fixed sooner rather than later.
=> hidapi: Use LIBUSB_LIBRARIES to link to libusb

Source/Core/Core/IOS/DI/DI.cpp, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/ES/ES.h, Source/Core/Core/IOS/ES/Formats.cpp, Source/Core/Core/IOS/ES/Identity.cpp, Source/Core/Core/IOS/ES/NandUtils.cpp, Source/Core/Core/IOS/ES/TitleContents.cpp, Source/Core/Core/IOS/ES/TitleInformation.cpp, Source/Core/Core/IOS/ES/TitleManagement.cpp, Source/Core/Core/IOS/ES/Views.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.h, Source/Core/Core/IOS/IOSC.cpp, Source/Core/Core/IOS/IOSC.h, Source/Core/Core/IOS/Network/SSL.cpp, Source/Core/Core/IOS/Network/SSL.h, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/IOS/Network/WD/Command.cpp, Source/Core/Core/IOS/VersionInfo.cpp, Source/Core/Core/IOS/WFS/WFSI.cpp, Source/Core/Core/IOS/WFS/WFSI.h
Now that the ES class (now called ESDevice) and the ES namespace do
not conflict anymore, "IOS::" can be dropped in a lot of cases.
This also removes "IOS::HLE::" for code that is already in that
namespace. Some of those names used to be explicitly qualified
only for historical reasons.
There are no functional changes.
=> IOS: Simplify unnecessarily qualified names

Source/Core/VideoBackends/Software/Rasterizer.cpp
Equivalent to da43f9a15 (#4197) for the software renderer.  This should fix Fishing Resort ([issue 3106](https://dolp.in/i3106) for HW renderer).
=> Software: Always divide the texture coordinates by q.

Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/NetworkCaptureLogger.cpp, Source/Core/Core/NetworkCaptureLogger.h
This PR improves TCP sessions logging for games using multiple sockets at the same time (for instance the Internet channel). That way, each socket tracks its sequence numbers and avoid sequence number mismatch when multiple of them are used.
Ready to reviewed & merged.
=> PCAP: Improve TCP session logging

Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
This PR adds the hostname column to the SSL table in the Network widget. This name is registered when initialising a new SSL context and will be used to verify the certificate CN if the verify option is enabled.
=> NetworkWidget: Add hostname to SSL table

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/UnitTests/Core/PowerPC/JitArm64/MovI2R.cpp, Source/UnitTests/UnitTests.vcxproj
More or less a complete rewrite of the function which aims to be equally good or better for each given input, without relying on special cases like the old implementation did.
In particular, we now have more extensive support for MOVN, as mentioned in a TODO comment.
=> Arm64Emitter: Improve MOVI2R

Source/Core/Core/IOS/Device.h, Source/Core/Core/IOS/IOS.cpp
PrepareForState is now unnecessary with the new implementation of
HostFileSystem::DoState, which does what the old implementation
(CWII_IPC_HLE_Device_FileIO::PrepareForState) used to do.
master:
https://github.com/dolphin-emu/dolphin/blob/2f85b80b7bf75434072c1245904587ee8c15fbe2/Source/Core/Core/IOS/FS/HostBackend/FS.cpp#L238-L242
2015 Dolphin:
https://github.com/dolphin-emu/dolphin/blob/7d80aaedc7bbeae0fbad8e45a45747c60611b7d2/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_FileIO.cpp#L360-L365
=> IOS: Remove unnecessary and unused PrepareForState

Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitRegCache.cpp
According to the C standard, an offsetof expression must evaluate to an
address constant, otherwise it's undefined behavior.
Fixes https://bugs.dolphin-emu.org/issues/12409
See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95942
There are still improper uses of offsetof (mostly in JitArm64) but
fixing that will take more effort since there's a PPCSTATE_OFF wrapper
macro that is sometimes used with non-array members and sometimes used
with arrays and variable indices... Let's keep that for another PR.
=> Core/DSP: Fix improper uses of offsetof

Source/Core/Core/IOS/Network/SSL.cpp
This PR allows the NetworkLogger to dump raw SSL packets in PCAP format when dumping decrypted SSL packets is disabled.
That way, most network related features would be supported by the logger except for WiiConnect24, DNS and ICMP packets.
Depends on https://github.com/dolphin-emu/dolphin/pull/9408.
=> PCAP: Add raw SSL packets logging support

Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Using a non-constant array index inside offsetof is not standards compliant, and is rejected by GCC 11.
https://bugs.dolphin-emu.org/issues/12409#note-5
=> JitArm64: Fix improper uses of offsetof

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.h, Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.h, Source/Core/DolphinQt/Debugger/RegisterWidget.cpp, Source/Core/DolphinQt/Debugger/RegisterWidget.h, Source/Core/DolphinQt/MainWindow.cpp
This PR fixes the "Add to watch" action not working (and was adding a memory BP instead) in the RegisterWidget and also adds this action in the MemoryWidget.
=> Debugger: Fix "Add to watch" not working

Source/Core/Core/IOS/DI/DI.cpp, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/ES/ES.h, Source/Core/Core/IOS/ES/Formats.cpp, Source/Core/Core/IOS/ES/Formats.h, Source/Core/Core/IOS/ES/NandUtils.cpp, Source/Core/Core/IOS/ES/TitleContents.cpp, Source/Core/Core/IOS/ES/TitleManagement.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.h, Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/IOS/IOS.h, Source/Core/Core/State.cpp
Filesystem accesses aren't magically faster when they are done by ES,
so this commit changes our content wrapper IPC commands to take FS
access times and read operations into account.
This should make content read timings a lot more accurate and closer
to console. Note that the accuracy of the timings are limited to the
accuracy of the emulated FS timings, and currently performance
differences between IOS9-IOS28 and newer IOS versions are not emulated.
Part 1 of fixing https://bugs.dolphin-emu.org/issues/11346
(part 2 will involve emulating those differences)
=> IOS: Emulate FS timings for ES content IPC commands

Source/Core/Core/HW/SystemTimers.h, Source/Core/Core/IOS/FS/FileSystemProxy.cpp, Source/Core/Core/IOS/IOS.h
And add a strongly typed integer type so that making this kind of mistake is more difficult
=> Core: Fix time base unit mixup

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/IOS/Network/Socket.cpp, Source/Core/Core/IOS/Network/Socket.h
This PR adds a timeout on connect for blocking sockets based on this hardware test. Beware that it tries to connect to an ubisoft server (which timeout after ~3 minutes on hardware).
[wii-connect-timeout.zip](https://github.com/dolphin-emu/dolphin/files/4516755/wii-connect-timeout.zip)
I'll need to reverse IOS to confirm that behaviour, however. The timeout value (in second) can also be changed in the config file under the `[Network]` section.
=> IOS/NET: Add timeout on blocking connect

Source/Core/Core/PowerPC/BreakPoints.cpp
This was caused, because we were saving the `break_on_hit` flag with the letter `p`. Then while loading the breakpoints, we read the flag with the letter `b`, resulting in the `break_on_hit` flag being always false.
=> Debugger: Fix issue were loaded memory breakpoints were not being triggered (break)

Source/Core/Core/MemoryWatcher.cpp
The MemoryWatcher probably shouldn't generate emulated exceptions or trigger memory breakpoints.
=> Core/MemoryWatcher: Use appropriate memory read function in ChasePointer().

Source/Core/Common/Config/Config.h, Source/Core/Common/Config/Layer.h, Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp
Also DualShock UDP Client was the only place in the code that assumed OnConfigChanged() was called at least once on startup or it won't load up the setting, so I took care of that.
OnConfigChanged() repopulates all the devices and it can be slow (and just plain unnecessary).
This might also help with any race conditions with devices population code, which as of now are unsafe and can break on some machines.
=> Don't call OnConfigChanged() unless config actually changed

Source/Core/DolphinQt/Config/Graphics/SoftwareRendererWidget.cpp
Same problem and same fix as in PR #9338. Also changing `<br />` to `<br>` for consistency with other strings while I'm at it.
=> DolphinQt: Fix <game_id> tag in SoftwareRendererWidget.cpp

Source/Core/DolphinQt/Config/InfoWidget.cpp, Source/Core/DolphinQt/Config/InfoWidget.h
This was accidentally removed during the Qt migration: https://github.com/dolphin-emu/dolphin/pull/4734
~~Also adds the TMD region to the game info tab, as it's useful for figuring out what region Dolphin is ultimately using for Wii games~~ The country field should suffice, as it shows the value of TypicalCountryForRegion(region) and TypicalCountryForRegion is bijective
=> Qt: Re-add IOS version to the game info tab

Source/Core/Common/IniFile.h, Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp, Source/Core/InputCommon/ControllerEmu/ControllerEmu.h, Source/Core/InputCommon/DynamicInputTextureManager.cpp, Source/Core/InputCommon/DynamicInputTextureManager.h, Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.cpp, Source/Core/InputCommon/DynamicInputTextures/DITConfiguration.h, Source/Core/InputCommon/InputConfig.cpp, Source/Core/InputCommon/InputConfig.h, Source/Core/InputCommon/InputProfile.cpp, Source/Core/InputCommon/InputProfile.h
This reduces the number of image loads and the number of texture cache invalidations (in particular on startup) by having all the controllers be iterated over once, instead of happening on each load / save of the individual controllers.
=> InputCommon: dynamic input textures more optimizations

Source/Core/VideoBackends/Software/Clipper.cpp, Source/Core/VideoBackends/Software/Clipper.h, Source/Core/VideoBackends/Software/SetupUnit.cpp
Somewhat equivalent to https://bugs.dolphin-emu.org/issues/7749 / #1706.  For whatever reason, textures aren't working (they already were broken for lines, but this change doesn't fix it even though I think it should).
=> Software: Implement line-width and point-width

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
The result of calls to PPCSTATE_OFF_PS0/1 were being cast to u32 and passed to functions expecting s32 parameters. This changes the casts to s32 instead.
One location was missing a cast and generated a warning with VS which is now fixed.
=> JitArm64: Fix unsigned/signed argument/parameter mismatch

Source/Core/DolphinQt/Host.cpp
The Host constructor sets a callback on a lambda that in turn calls Host_UpdateDisasmDialog. Since that function is not a member function capturing this is unnecessary.
Fixes -Wunused-lambda-capture warning on freebsd-x64.
=> DolphinQt: Removed unused this capture in lambda

Data/Sys/GameSettings/GOW.ini
Rebase of #9380 with proper commit message. Mostly because I genuinely smiled at the PR name of 'turn on the sun'.
=> GameSettings: Enable perf queries to fix sun in Need for Speed: Most Wanted.

CMakeLists.txt, Source/Core/DolphinQt/GameList/GameList.cpp
MSBuild does this, so CMake should too. Fixes the MSVC build when combined with PR #9457 or PR #9556.
=> CMake: Include WIL headers

Data/Sys/GameSettings/R38.ini, Data/Sys/GameSettings/RBP.ini, Data/Sys/GameSettings/RNB.ini, Data/Sys/GameSettings/S2D.ini, Data/Sys/GameSettings/SJC.ini, Data/Sys/GameSettings/SNQ.ini
Some fixes to dual core issues, Defer EFB Copies to RAM issues and Texture Cache Accuracy issues.
This should fix:
https://bugs.dolphin-emu.org/issues/11733
also this which seemed to still occur without Defer EFB Copies
https://bugs.dolphin-emu.org/issues/10758
=> Some Gameini Changes

Source/Core/Core/HW/Memmap.cpp
This fixes two potential (if unlikely to be relevant in practice) bugs:
- Remember which regions are mapped instead of re-checking via the flags each time. This fixes a potential issue where a memory region would not be unmapped when booting in Wii mode and then switching to GC mode by eg. using the Disc channel and a GC disc. (first commit)
- We didn't check which regions are active in `UpdateLogicalMemory()`, leading to an odd BAT config potentially attempting to map memory regions that haven't been allocated. (second commit)
=> Core/Memmap: Memory mapping logic fixes.

Source/Core/Core/PowerPC/BreakPoints.cpp, Source/Core/Core/PowerPC/BreakPoints.h, Source/Core/Core/PowerPC/PowerPC.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp, Source/Core/DolphinQt/Debugger/BreakpointWidget.h
This PR add a way to disable/enable breakpoints at runtime, by adding a context menu that let you toggle between the two state.
Also, added a `Go to` action, that let you go to breakpoint address, this action is only added when the breakpoint is a instruction breakpoint.
I removed the `itemClicked` listener since it was replaced with the context menu `Go to` action.
=> BreakpointWidget: Allow breakpoints to be toggled between enable/disable

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/PlatformPagerAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainView.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesView.java, Source/Android/app/src/main/res/layout/activity_tv_main.xml, Source/Android/app/src/main/res/layout/fragment_grid.xml, Source/Android/jni/GameList/GameFileCache.cpp
The main reason why I'm adding this isn't actually to allow users to swipe up to refresh, it's to add a loading indicator. Considering that the Storage Access Framework can be slow for folders with many items (many subfolders?), not showing a loading indicator might give users the impression that adding a folder resulted in nothing happening even though Dolphin is scanning for games in the background. But I suppose letting users swipe up to refresh is a nice bonus with the change.
=> Android: Use SwipeRefreshLayout in MainActivity

CMake/CheckAndAddFlag.cmake
Some flags do nothing but generate dozens of warnings later,
add '-Werror' during testing to catch those early.
Main culprit is '-fvisibility-inlines-hidden' which is invalid for C files
=> Stricter test for compiler flags

Source/Core/DolphinQt/Debugger/NetworkWidget.cpp, Source/Core/DolphinQt/Debugger/NetworkWidget.h
This PR splits SSL options group box into 2 group boxes. One dedicated to dumping options, the other to the network security options. On top of that a combo box was added to select the network dump format and a button to open the dump folder.
=> NetworkWidget: Reorganise SSL options group box

Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
This PR fixes (M)BP icon not being updated when changed from the BreakpointWidget.
Ready to be review & merged.
=> BreakpointWidget: Emit BreakpointsChanged to update views

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java
In master, the game scanning process looks like this:
1. Scan for games
2. Scan for additional metadata (icon.png and meta.xml)
3. Save the cache if needed
4. Update the game list with the results
This change makes the game scanning process look like this:
1. Scan for games
2. Update the game list with the results
3. Scan for additional metadata (icon.png and meta.xml)
4. Update the game list with the results
5. Save the cache if needed
Updating the game list as soon as possible means the user has to wait less before their games show up. The new behavior matches what DolphinWX did before it was removed. (DolphinQt has an even fancier approach where games get added one by one.)
=> Android: Broadcast update before updating additional metadata

Source/Core/Common/Debug/Watches.cpp
This PR fixes (de)serialisation issues where decimal separator can get inserted in the watch's address.
=> Watches: Fix Save and Load from strings

Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
This PR fixes the delete action which deletes everything matching the address of the selected item (i.e. both memory and regular breakpoints).
=> BreakpointWidget: Fix delete deleting both MBP and BP at address

Source/Core/Core/HW/SI/SI_DeviceGBA.cpp, Source/Core/Core/HW/SI/SI_DeviceGBA.h
When reading a reply from a message sent to the data socket there is the possibility that the other side gets sent multiple messages before replying to any of them, which can lead to multiple replies sent in a row. Though this only happens when things time out, it's quite possible for these timeouts to happen or build up over time, especially when initiating the connection.
This change makes sure to flush any pending bytes that have not been read yet out of the socket after a successful POLL reply is received, since that is the most common time when backups occur, and as well as using the exact number of bytes in an expected reply, to ensure the received data and the message it's replying to do not get out of sync.
---
An alternate approach not explored in this PR would be to modify …
=> SI/DeviceGBA: Ensure data socket isn't backed up

Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
This PR uses `QSignalBlocker` class instead of `blockSignals` methods.
~Depends on https://github.com/dolphin-emu/dolphin/pull/9564.~
=> BreakpointWidget: Use QSignalBlocker

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/FloatSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/StringSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java
We want to save the currently selected platform tab, but doing so immediately after switching tabs leads to unnecessarily much file I/O (on the main thread, no less). This change makes us defer the saving until later.
=> Android: Don't save settings immediately after switching platform tab

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
This PR changes the icon of breakpoints when disabled by making them more transparent.
What this PR won't do:
- Changing memchecks icons (will be addressed in another PR).
- ~The icons not updating in the code view will also be addressed in another PR since it affects mostly all BreakpointWidget features including creating a new breakpoint.~
Screenshot:
Ready to be review & merged.
=> Breakpoints: Change icon when disabled

Source/Core/AudioCommon/WASAPIStream.cpp, Source/Core/AudioCommon/WASAPIStream.h
This PR brings numerous improvements to WASAPI code in Dolphin, improving code readability as well as fixing numerous issues.
As a preparation, [WIL](https://github.com/microsoft/wil) has been added, since it's very useful for ensuring proper RAII-based destruction for several WinAPI types - in my case it was proper scoped calls to `CoUninitialize` and proper destruction of previously leaking (in some cases) `PROPVARIANT`.
All COM objects have been moved to use WRL, which ensures their proper release. Previously, there were numerous code paths where functions would return without cleaning up their COM objects, effectively leaking references.
`device->GetId(&device_id);` was present in several places, never using the return value nor freeing it - leaking memory for no reason.
Thread …
=> WASAPI code improvements

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp, Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp, Source/Core/Core/NetworkCaptureLogger.cpp, Source/Core/DolphinQt/Config/Graphics/GraphicsWidget.h, Source/Core/InputCommon/ControllerInterface/Touch/Touchscreen.h, Source/Core/InputCommon/ControllerInterface/evdev/evdev.cpp, Source/Core/InputCommon/InputConfig.cpp, Source/Core/InputCommon/InputConfig.h, Source/Core/VideoCommon/FreeLookCamera.cpp, Source/Core/VideoCommon/FreeLookCamera.h
Fix a number of build warnings on various platforms.
- Unused variables in Arm64Gen, FreeLookCamera and GraphicsWidget
- Variable shadowing in SDIOSlot0Device and NetworkCaptureLogger
- Missing maybe_unused attribute for unused but documenting constants in WiimoteDevice
- Missing override specifiers in Touchscreen subclasses and FreeLookCamera
- Spurious gcc warning about discarding return values with warn_unused_result attribute
- Signed/unsigned comparison in InputConfig
- Move Arm64Gen namespace variable into only consuming function (and make constexpr).
=> Fix various build warnings

Source/Core/Common/EnumFormatter.h
A mistake from #9497 &mdash; I added a unit test to catch this kind of issue, but didn't actually check whether it gave warnings on platforms other than MSVC (which it does).  See https://godbolt.org/z/PhMKo3.
=> EnumFormatter: fix signed/unsigned comparison warnings

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/PlatformPagerAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
4752ec8 broke this because I wasn't aware that a fragment has to have a constructor with no parameters in order for activity recreation to work.
=> Android: Fix recreating main activity

Source/Core/DolphinQt/GameList/GameList.cpp
Fix Gamelist context menu item 'Open Containing Folder' opening wrong
target on Windows when game parent folder is [foobar] and grandparent
folder contains file [foobar].bat or [foobar].exe
Add trailing directory separator to parent folder path to force Windows
to interpret path as directory.
Fixes https://bugs.dolphin-emu.org/issues/12411
=> Gamelist: Fix 'Open Containing Folder'

Source/Core/Core/HW/Wiimote.cpp
When a save state is loaded, the IOS device serving bluetooth is cast as BluetoothEmuDevice. If, however, a real Wiimote with BT passthrough is used, this caused the game to crash. Now the proper device class is used.
=> Fix loading save states with bluetooth passthrough

Source/Core/UICommon/AutoUpdate.cpp
Currently Dolphin just assumes that it only has one update running, if a user were to "accidentally" check for updates, check the "Update when dolphin closes" checkbox multiple times then closes dolphin, you get a ton of updaters running at once.
The solution is to only ever allow dolphin to trigger the update once then wait for dolphin to close.
=> [Updater] Check whether we've already had an update triggered

Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h
The current algorithm for detecting a RSO modules have a flaw. In which RSO modules are only detected if the byte before the name of the module is a null byte `\0`. This is wrong because before the name can be any arbitrary data.
I modify the approach. Instead of looking for the first null byte before the name. I count the bytes before a non-ascii character is found. After that, I look for a `uint32` offset that point to the name's bytes. Also, to be even more sure about it, after we have found the offset, the next 4 bytes are the module's name length and I also check against that. 
Also, even after this fix, we are not going to be capable of detecting every RSO module, since modules can come without name ([File Format Specification](http://www.metroid2002.com/retromodding/wiki/RSO_(File_F …
=> Symbols: Fix RSO Modules detection algorithm

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
At a first glance it may look like a part of the code I added to srawx in efeda3b has a bug when a == s. The code actually happens to work correctly, but in the interest of making the code easier to reason about, I'd like to change the way it's implemented. This change should improve the pipelining a little in the a == s case too.
=> JitArm64: Improve srawx special case carry calculation

Source/Core/DiscIO/WIABlob.cpp, Source/Core/DiscIO/WIABlob.h
The loop in `WIARVZFileReader::Chunk::Read` could terminate prematurely if the size argument was smaller than the size of an exception list which had only been partially loaded.
=> DiscIO: Fix reading certain WIA chunks with many exceptions

Source/Core/DiscIO/VolumeVerifier.cpp
The async operations may contain references to class members, so any running async operations must end before destroying the class.
=> VolumeVerifier: Fix potential crash when cancelling

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp, Source/Core/Core/PowerPC/JitArm64/Jit_Util.cpp, Source/Core/VideoCommon/VertexLoaderARM64.cpp, Source/UnitTests/Core/PowerPC/JitArm64/MovI2R.cpp
Most changes are just adding ARM64Reg:: in front of the constants.  
Add operator functions to reduce type casting spam
Make DecodeReg return int instead of ARM64Reg
Add EncodeRegTo32 with previous behavior of DecodeReg
Despite appearances, this does not change the value of 
ARM64Reg::INVALID_REG.  The previous value 0xFFFFFFFF was being cast to
an int and wrapping around to -1, this just makes that value explicit.
=> Arm64Gen: Convert ARM64Reg to enum class

Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.h
If we know at compile time that the PPC carry flag definitely has a certain value, we can bake that value into the emitted code and skip having to read from PPCState.
=> JitArm64: Constant carry flag optimizations

Source/Core/DiscIO/CompressedBlob.cpp, Source/Core/DiscIO/DriveBlob.cpp, Source/Core/DiscIO/VolumeWii.cpp, Source/Core/DiscIO/WbfsBlob.cpp
Panic alerts in DiscIO can potentially be very annoying since large amounts of them can pop up when loading the game list if you have some particularly weird files in your game list.
This was a much bigger problem back in 5.0 with its "Tried to decrypt data from a non-Wii volume" panic alert, but I figured I would take it all the way and remove the remaining panic alerts that can show up when loading the game list.
I have exempted uses of ASSERT/ASSERT_MSG since they indicate a bug in Dolphin rather than a malformed file.
=> Avoid using panic alerts in DiscIO

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java
GameFileCacheService.startRescan (in MainPresenter.onResume) does nothing if called before GameFileCacheService.startLoad. Fixes a PR #9569 regression where already added games would not show up after app launch under specific circumstances.
Unfortunately the loading indicator still doesn't show up during a rescan initiated by app launch, but that would be more annoying to fix, so I will leave it for now.
=> Android: Fix rescanning on first app launch after cache clear

Source/Core/Core/CMakeLists.txt, Source/Core/Core/PowerPC/Jit64/Jit.h, Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp, Source/Core/Core/PowerPC/JitCommon/DivUtils.cpp, Source/Core/Core/PowerPC/JitCommon/DivUtils.h, Source/Core/DolphinLib.vcxproj, Source/UnitTests/DivUtilsTest.cpp, Source/UnitTests/UnitTests.vcxproj
Optimize various occurrences of signed 32-bit integer division. Most notably, it implements the multiplication by magic number method to optimize divisions with a constant divisor (the Zelda games like to do this a bunch).
---
**Constant dividend**
<details><summary>Dividend != 0x80000000</summary>
Before:
```
B8 54 D3 E6 02       mov         eax,2E6D354h
85 FF                test        edi,edi
74 0C                je          overflow
3D 00 00 00 80       cmp         eax,80000000h
75 0C                jne         normal_path
83 FF FF             cmp         edi,0FFFFFFFFh
75 07                jne         normal_path
overflow:
C1 F8 1F             sar         eax,1Fh
8B F8                mov         edi,eax
EB 05                jmp         done
normal_path:
99                   cdq
F7 FF …
```
=> Jit64: Optimize divwx

Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DiscIO/VolumeVerifier.h
The performance gains of doing this aren't too important since you normally wouldn't run into any disc image that has overlapping blocks (which by extension means overlapping partitions), but this change also lets us get rid of things like VolumeVerifier's mutex that used to exist just for the sake of handling overlapping blocks.
=> VolumeVerifier: Handle overlapping blocks more efficiently

Source/Core/DiscIO/Volume.h, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DiscIO/VolumeVerifier.h, Source/Core/DiscIO/VolumeWii.cpp, Source/Core/DiscIO/VolumeWii.h
Dependent on PR #8625.
This improves the speed of verifying Wii WIA/RVZ files. For me, the verification speed for LZMA2-compressed files has gone from 11-12 MiB/s to 13-14 MiB/s.
One thing VolumeVerifier does to achieve parallelism is to compute hashes for one chunk of data while reading the next chunk of data. In master, when reading data from a Wii partition, each such chunk is 32 KiB. This is normally fine, but with WIA and RVZ it leads to rather lopsided read times (without the compute times being lopsided): The first 32 KiB of each 2 MiB takes a long time to read, and the remaining part of the 2 MiB can be read nearly instantly. (The WIA/RVZ code has to read the entire 2 MiB in order to compute hashes which appear at the beginning of the 2 MiB, and then caches the result afterwards.) …
=> VolumeVerifier: Align partition reads to groups

Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp, Source/Core/Core/PowerPC/PPCAnalyst.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h, Source/Core/Core/PowerPC/PPCTables.h
The output of instructions like fabsx and ps_sel is store-safe if and only if the relevant inputs are. The old code was always marking the output as store-safe if the output was a single, and never otherwise.
Also, the old code was treating the output of psq_l/psq_lu as store-safe, which seems incorrect (if dequantization is disabled).
Split out from PR #9458 because this affects the x64 JIT.
=> PPCAnalyst: Rework the store-safe logic

Source/Core/AudioCommon/AudioCommon.cpp, Source/Core/AudioCommon/AudioCommon.h, Source/Core/Core/Core.cpp, Source/Core/Core/HW/AudioInterface.cpp
This splits SoundStream initialization in two parts, allowing HW::Init to set sample rates and addresses a comment that's been around for a while
=> AudioCommon: Split Initialization

Source/Core/Core/HW/SI/SI_DeviceGBA.cpp
Building on #9550 I found some more issues that could cause the link to get out of sync.
The original flush technique didn't work properly; it didn't work before the first RESET was sent, which generally meant the first RESET would be junk too. This replaces it with flushing _before_ sending any message. This approach isn't perfect but clears out the junk much more reliably.
This also adds a minor wait for the "non-booted" state (polling for status instead of actual data transfer) to improve the stability further.
=> SI/DeviceGBA: Improve link stability

Source/Core/DolphinQt/GameList/GameList.cpp
This is a keyboard shortcut on Windows at least, and I've accidentally started games several times trying to use it in Dolphin.
=> Open the properties window when alt+enter is used on the game list

Source/Core/Core/HW/DSPHLE/DSPHLE.cpp
This performs a sanity check in case that assumption proves to be wrong, which can happen when connecting multiple GBAs simultaneously
=> DSPHLE: Don't restore the last UCode when the crc doesn't match

Source/Core/Core/Core.cpp, Source/Core/Core/PowerPC/JitInterface.cpp, Source/Core/DolphinQt/MainWindow.cpp
In places where applicable, Core::RunAsCPUThread has replaced Core::SetState workarounds to pause and resume emulation for thread-sensitive operations.
- void Core::SaveScreenShot()
- void Core::SaveScreenShot(std::string_view name)
- void JitInterface::GetProfileResults(Profiler::ProfileStats *prof_stats)
- void MainWindow::OnExportRecording()
=> Apply More Core::RunAsCPUThread

CMakeLists.txt
Add a check to define FMT_EXCEPTIONS = 0 when compiling on MacOS.
Replaces -fno-objc-exceptions, which also disabled fmt exceptions but generated warnings when compiling c++ files.
=> CMake: Fix unused compiler flag warning

Source/Core/Common/Config/Enums.h, Source/Core/Core/BootManager.cpp, Source/Core/Core/ConfigLoaders/BaseConfigLoader.cpp, Source/Core/Core/ConfigLoaders/BaseConfigLoader.h, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp, Source/Core/Core/HW/HW.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/WiiRoot.cpp, Source/Core/Core/WiiRoot.h, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Fixes certain netplay desyncs, https://bugs.dolphin-emu.org/issues/10328, and a bug where the Wii language stored in a DTM file would be ignored. Prerequisite for PR #9388.
=> NetPlay: Sync more settings

Source/Core/Core/FifoPlayer/FifoAnalyzer.cpp, Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.cpp, Source/Core/VideoCommon/CPMemory.h, Source/Core/VideoCommon/VertexLoaderARM64.cpp, Source/Core/VideoCommon/VertexLoaderManager.cpp, Source/Core/VideoCommon/VertexLoaderManager.h, Source/Core/VideoCommon/VertexLoaderX64.cpp, Source/Core/VideoCommon/VertexLoader_Color.cpp, Source/UnitTests/VideoCommon/VertexLoaderTest.cpp
The typo (from f749fcfa9f42cda679ff7f4288c8418d2b56b08d) was `ARRAY_POSITION` being used instead of `ARRAY_TEXCOORD0`.
=> Fix PanicAlert when recording FIFOs

Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/ES/ES.h, Source/Core/Core/IOS/ES/Formats.h, Source/Core/Core/IOS/ES/NandUtils.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.h, Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/IOS/IOS.h, Source/Core/Core/State.cpp, Source/Core/DiscIO/DirectoryBlob.cpp
(alternative title: make ES_Launch slower and potentially break it)
This is a series of commits to make ES launch timings closer to console:
* In BootstrapPPC, we no longer neglect the amount of time it takes to read the DOL/ELF into memory.
* IOS and ES's slow boot time (>400ms) is now taken into account.
* IOS reloads are no longer instant. This fixes [reloadtest (from this HackMii post)](https://hackmii.com/2009/08/timing-is-everything-the-case-of-the-unsoftmoddable-wii/) as it makes the reasonable assumption that ES launches for IOS titles do not complete instantly.
* We now simulate what IOS does with /sys/launch.sys when launching a PPC title because FS operations that modify the NAND are particularly slow.
(those commits can be reviewed one at a time)
This PR also simplifies IPC …
=> IOS: Improve timing accuracy for title launches (both ARM and PPC)

.git-blame-ignore-revs
* Enum and struct indentation cleanup: 40182a48a56b8e294e126c64f5f37910a40c67cd and ebb48d019eec1c29a37a406e2db16d7565367faa (#54)
* SVN line-ending conversion: 30c883bcfc65761dc9fb61fea16a25fb61a7e220
* Trialing whitespace: c579637eafb9e9eb7f83711569254bd8da6d09d2 and 664c8d30a055f4762a2a60be77c1c8eaec1a5d85
* Other reformatting: 40bb9974f21878e64fb03d70e717cb996bf13a29 (#6635)
=> Add additional commits to .git-blame-ignore-revs

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/res/values/strings.xml
This option does in fact not enable and disable logging as a whole. You can get logs through logcat regardless of this setting.
Also taking the opportunity to remove the reference to the "dolphin-emu" folder name since we will no longer be using that folder once scoped storage is applied to Dolphin.
=> Android: Rename "Enable Logging" to "Write Logs to File"

Source/Android/app/src/main/res/values/strings.xml
See PR #8203 for background on the game INI deletion prompt.
It's been almost two years since PR #8203 was merged, so you would think that people are no longer creating game INIs that contain a copy of every global setting, right? Unfortunately, MMJ was forked not too long before that and never backported the change, so right now there's a not insignificant number of people online posting game INIs full of this garbage for others to use.
One thing that's been missing from the game INI deletion prompt is a description of what the problem with having tons of extra lines in a game INI actually is. This change adds that, in the the hope that it will make people ignore the warning less often.
=> Android: Expand the game INI deletion prompt

Source/Core/Common/Matrix.cpp, Source/Core/Common/Matrix.h, Source/Core/Core/FreeLookManager.cpp, Source/Core/Core/FreeLookManager.h, Source/Core/Core/HW/SI/SI.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTEmu.cpp, Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/Config/Mapping/FreeLookRotation.cpp, Source/Core/DolphinQt/Config/Mapping/FreeLookRotation.h, Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/DolphinQt/HotkeyScheduler.h, Source/Core/DolphinQt/RenderWidget.cpp, Source/Core/DolphinQt/RenderWidget.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.cpp, Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp, Source/Core/InputCommon/ControllerInterface/ControllerInterface.h, Source/Core/InputCommon/ControllerInterface/CoreDevice.h, Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.cpp, Source/Core/InputCommon/ControllerInterface/DInput/DInputKeyboardMouse.h, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.cpp, Source/Core/InputCommon/ControllerInterface/Xlib/XInput2.h, Source/Core/VideoCommon/FreeLookCamera.cpp, Source/Core/VideoCommon/FreeLookCamera.h
I've always thought Free Look was such a cool and underutilized feature.  In an effort to make it more mainstream, I've removed the shackles of requiring to use the mouse.  Now you can assign motion controls (or gamepad) to the Free Look rotation movement.
_Rotation Free Look settings (mouse, gamepad, DSU or bluetooth emulated wiimote!)_
=> Support controlling Free Look via input bindings (motion controls, gamepad, etc!)

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
`JitArm64::DoJit` contains a check where it prints a warning and tries to pause emulation if instructed to compile code at address 0. I'm assuming this was done in order to provide a nicer error behavior in cases where PC was accidentally set to null. Unfortunately, it has started causing us problems recently, as 688bd61 writes and runs some code at address 0 to simulate the PPC being held in reset. What makes this worse is that calling `Core::SetState` from the CPU thread is actually not allowed and will cause a deadlock instead of  the intended behavior. I don't believe there is anything on a real console that would stop you from executing code at address 0 (as long as the MMU has been set up to allow it), and `Jit64::DoJit` doesn't contain any check like this, so let's remove the …
=> JitArm64: Allow DoJit at address 0 (fix launching Wii titles)

Source/Core/VideoCommon/VertexShaderGen.cpp
https://github.com/dolphin-emu/dolphin/pull/4164 moved the "Sonic epsilon hack" to vertex shaders. However, it was only done for targets with depth clamping. If this is not available, for example the target is OpenGL ES, the Sonic problem appears (https://bugs.dolphin-emu.org/issues/11897).
A version of the "Sonic epsilon hack" is added for targets without depth clamping.
=> VertexShaderGen: Sonic epsilon hack for OpenGL ES

Source/Core/AudioCommon/OpenSLESStream.cpp, Source/Core/AudioCommon/PulseAudioStream.cpp, Source/Core/Core/HW/GCMemcard/GCMemcard.cpp, Source/Core/Core/HW/GCMemcard/GCMemcardUtils.cpp, Source/Core/Core/HW/WiimoteCommon/DataReport.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Classic.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/DrawsomeTablet.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Drums.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/Turntable.cpp, Source/Core/Core/HW/WiimoteEmu/Extension/UDrawTablet.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DolphinQt/GCMemcardManager.cpp, Source/Core/InputCommon/ControlReference/ExpressionParser.cpp, Source/Core/VideoCommon/TextureDecoder_x64.cpp
This replaces the standard library `assert` with Dolphin's `ASSERT` macro.
I haven't changed any uses of cassert or assert.h in Externals, nor in pch (because the precompiled headers are used for externals, I'm pretty sure).
=> Replace uses of cassert with Common/Assert.h

Source/Core/Core/PowerPC/Interpreter/Interpreter_Tables.cpp, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/CachedReg.h, Source/Core/Core/PowerPC/Jit64/RegCache/FPURegCache.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/GPRRegCache.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/PPCAnalyst.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h, Source/Core/Core/PowerPC/PPCTables.h
This pull request adds a new "discarded" state for registers. Discarding a register is like flushing it, but without actually writing its value back to memory. We can discard a register only when it is guaranteed that no instruction will read from the register before it is next written to.
Discarding reduces the register pressure a little, and can also let us skip a few flushes on interpreter fallbacks.
=> Jits: Discard registers which we know will be overwritten

Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/GameList/GameListModel.h, Source/Core/DolphinQt/GameList/GridProxyModel.cpp, Source/Core/DolphinQt/GameList/ListProxyModel.cpp
Also adds a couple lambdas and using directives to reduce visual noise.
=> Convert GameList col enum to enum class

Source/Core/Core/Core.cpp
This can happen if it's called before the core has fully initialized, as is happening in https://bugs.dolphin-emu.org/issues/12473.
There might be other side effects from this, so it should probably be tested more thoroughly. Maybe need a mutex?
=> Core: Fix PauseAndLock segfaulting under certain circumstances

Data/Sys/GameSettings/G5D.ini, Data/Sys/GameSettings/GC3.ini, Data/Sys/GameSettings/RHF.ini, Source/Core/Core/BootManager.cpp, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/PowerPC/PPCCache.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
Specifically, 'Scooby-Doo! Mystery Mayhem' ([Bug 9561](https://bugs.dolphin-emu.org/issues/9561)) and 'Ed, Edd n Eddy: The Mis-Edventures'.
For Scooby-Doo!, I tested by loading the credits under the extras menu.  Prior to this change, it would fail to load; now, it loads successfully (even on exiting and re-entering the credits).  I haven't tested much actual gameplay.  I was also unable to confirm that there was ever an issue with loading save files; saving and loading at the first camera works fine in 5.0-12247.
For Ed, Edd n Eddy, the fix is only meaningful when combined with #8935; see https://github.com/dolphin-emu/dolphin/pull/8935#issuecomment-653928322.  (**EDIT**: It also is only necessary when MMU is disabled; the icache issue doesn't come up with MMU enabled.)
There may be …
=> Disable ICache emulation for some games

Source/Core/Common/MathUtil.h, Source/Core/DiscIO/WIACompression.cpp, Source/UnitTests/Common/MathUtilTest.cpp, Source/UnitTests/VideoCommon/VertexLoaderTest.cpp
A modified version of #8871 with the clamp function added to MathUtil along with tests.
The second commit makes VertexLoaderTest use it in order to avoid undefined behavior:
> A prvalue of a floating-point type can be converted to a prvalue of
> an integer type. The conversion truncates; that is, the fractional
> part is discarded. The behavior is undefined if the truncated value
> cannot be represented in the destination type. ([conv.fpint]/1)
=> MathUtil: Add SaturatingCast to cast floats more safely

Source/Core/Core/WiiUtils.cpp
Remove & to avoid reference to a temporary subobject.  Fixes error C2131 on upcoming version of msbuild.
=> WiiUtils: Remove reference qualifier

Source/Core/Core/PowerPC/MMU.cpp
While 6xx_pem.pdf §7.6.1.1 mentions that the number of trailing zeros in HTABORG must be equal to the number of trailing ones in the mask (i.e. HTABORG must be properly aligned), this is actually not a hard requirement. Real hardware will just OR the base address anyway. Ignoring SDR changes would lead to incorrect emulation.
Logging a warning instead of dropping the SDR update silently is a saner behaviour.
(Thanks to @booto for helping me understand this a bit better and to @JMC47 for testing)
---
The only reason the US version of Pokemon Box worked with Dolphin's faulty assumption is that the pagetable buffer is heap allocated and it happens to be located at 0xbc0000 on that version. `0xbc0000 >> 16` = 0xbc is even so the alignment check would pass.
On the JP version, the pagetable …
=> MMU: Fix SDR updates being silently dropped in some cases

Source/Core/Core/HW/Wiimote.cpp, Source/Core/Core/Movie.cpp, Source/Core/Core/WiiUtils.cpp, Source/Core/Core/WiiUtils.h, Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp
This adds a function to get the emulated or real Bluetooth device for
an active emulation instance. This lets us deduplicate all the
`ios->GetDeviceByName("/dev/usb/oh1/57e/305")` calls that are currently
scattered in the codebase and ensures Bluetooth passthrough is being
handled correctly.
This also fixes the broken check in WiimoteCommon::UpdateSource.
There was a confusion between "emulated Bluetooth" (as opposed to
"real Bluetooth" aka Bluetooth passthrough) and "emulated Wiimote".
=> WiiUtils: Add helper functions to get emulated/real Bluetooth device

Source/Core/VideoCommon/DriverDetails.cpp, Source/Core/VideoCommon/DriverDetails.h, Source/Core/VideoCommon/PixelShaderGen.cpp
Mali GPUs have been plagued by this issue since the dawn of time of Dolphin on Android (though I'm not sure if other OSes are also affected by this). This makes Super Mario Galaxy 1 and 2 completely unplayable on those GPUs, and I'm not aware of any othe games that are affected by this.
Here's the before and after:
=> DriverDetails: Fix broken vector bitwise AND on Mali drivers

Source/Core/VideoBackends/Vulkan/VKRenderer.cpp
AMD's binary driver as of 21.3 seems to return exclusive fullscreen lost even when it was never requested, so long as the caller requested it to be application controlled. Handle this ignoring the lost result and just continuing as normal if we never acquired it.
References:
- https://community.amd.com/t5/graphics/vulkan-spec-violation-vk-error-full-screen-exclusive-mode-lost/td-p/462283
- https://github.com/mpv-player/mpv/issues/8008#issuecomment-813747217
=> Vulkan: Work around AMD exclusive fullscreen bug (21.3+)

Source/PCH/CMakeLists.txt
fmt/format.h is included in the PCH, so we need to make sure fmt is
actually in the include path.
Not sure how Visual Studio + CMake manages to build without this.
=> Fix PCH when building with CMake + Ninja + MSVC on Windows

CMakeLists.txt
Xcode is configured by default to turn on the strict aliasing optimization through a separate project setting. This would cause the compiler to be called with both -fno-strict-aliasing(from the CMakeLists.txt) and -fstrict-aliasing(appended to the compiler arguments by Xcode) flags. This change turns off this default project setting, causing only the -fno-strict-aliasing flag to be provided to the compiler.
=> Build: Fix -fno-strict-aliasing on Xcode builds

Source/Core/Core/FifoPlayer/FifoPlayer.cpp
Copying with memcpy/std::copy is a lot faster than writing one byte at a time. And the behavior should be fully equivalent.
All FastWrite8 does is write a byte and increment the pointer:
https://github.com/dolphin-emu/dolphin/blob/5513d5f4f732fb1e436765ab87e7d60ba02b1ad6/Source/Core/Core/HW/GPFifo.cpp#L144-L148
Before: https://f.leolam.fr/out-rs3.svg
After: https://f.leolam.fr/out-rs3_v2.svg
=> FifoPlayer: Copy data with memcpy instead of one byte at a time

Source/Core/Core/HW/EXI/BBA/XLINK_KAI_BBA.cpp
This PR fixes a bug reported here https://bugs.dolphin-emu.org/issues/12273
Crash is caused by a thread being terminated that never started since the BBA wasn't activated.
=> Fix crash when stopping a game that does not use the BBA when XLink Kai BBA is selected in configuration

Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/Fifo.cpp, Source/Core/VideoCommon/Fifo.h
In Dolphin, we don't emulate the CPU and GPU in lock-step, for performance reasons. The CPU drives events, with the GPU emulation being one of these events which is fired periodically. This is the behavior in single core mode. Dual-core mode is completely non-deterministic here, and runs whenever Fifo::RunGpu() is called. Thus, I am mainly concerned about single-core mode.
Due to the GPU only being run every 1000 cycles or so, to a game, if it polled the command processor registers (for example, the read pointer, or distance), the GPU would appear to be stalled. Testing would suggest this is what causes FIFO resets/unknown opcodes in games such as F-Zero GX, and Rogue Squadron 3.
To work around this, each time these registers are accessed, we run the GPU for its time quantum. This way, to …
=> Fifo: Run/sync with the GPU on command processor register access

Source/Android/app/src/main/AndroidManifest.xml, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_GCAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java
We don't actually need to do this until we bump targetSdkVersion to Android 12 (which we can't do yet since we're not compatible with scoped storage), but I figured I'd get it out of the way early.
Not tested on Android 12, but tested to not break stuff on Android 10.
=> Android: Early changes to adapt for Android 12

Source/Core/Common/BlockingLoop.h, Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp
Makes it explicit that falling through into the next case is intended.
=> BlockingLoop/Jit64: Indicate explicit fallthrough where applicable

Source/Core/VideoBackends/Software/Clipper.cpp
Fixes [Jimmie Johnson's Anything with an Engine](https://wiki.dolphin-emu.org/index.php?title=Jimmie_Johnson%27s_Anything_with_an_Engine#Mirrored_Screen), which is [the only game that uses a positive viewport](https://dolphin-emu.org/blog/2017/04/05/dolphin-progress-report-march-2017/#50-3021-correct-for-negative-viewport-dimensions-by-armada651).  This is the same issue that #5096 fixed in hardware, but the actual fix here is different; that one was achieved by mirroring vertices while this only needs to change the backface test; the image was already right-side up on the software renderer.  I don't fully understand why.
=> Software: Invert backface test when viewport is positive

Source/Core/VideoBackends/Software/CopyRegion.h, Source/Core/VideoBackends/Software/EfbInterface.cpp, Source/Core/VideoBackends/Software/SWTexture.cpp
Fixes [issue 11393](https://bugs.dolphin-emu.org/issues/11393) (I haven't actually tested the game, only fifologs).
All of the Rogue Squadron 2 fifologs segfualt (per [the buildbot log](https://dolphin.ci/#/builders/17/builds/2416/steps/7/logs/stdio) (lines 309, 1624, 2939, and 4509)), starting in 609a17a0cd41a12c0fbf9a7c47c8889232594778 (hybrid XFB).  This also happens on Windows (where it fails with `Critical error detected c0000374` (heap corruption))
The problem is that left and top make no sense for a width by height array; they only make sense in a larger array where from which a smaller part is extracted.  EncodeXFB already handles the extraction, so CopyRegion's only use is to resize the image.  The rects in ScaleTexture have left and top as 0 (from …
=> Software: Fix out of bounds accesses in CopyRegion

Source/Core/Core/HLE/HLE.cpp, Source/Core/Core/IOS/MIOS.cpp
MIOS (the IPL code running on the PPC, not the ARM part) puts patch data in low MEM1 (0x1800-0x3000) for its own use. Overwriting data in this range can cause the IPL to crash when launching games that get patched by MIOS. See https://bugs.dolphin-emu.org/issues/11952 for more info.
Not applying the Gecko HLE patches means that Gecko codes will not work under MIOS, but this is better than the alternative of having specific games crash.
---
This also fixes an oversight from #9545, which moved the "new game has been loaded" logic to a separate OnNewTitleLoad function that has to be called explicitly *after* a title has loaded.
Those two changes fix Wind Waker and other MIOS-patched games when they are launched from the System Menu.
=> Fix IPL crash when launching MIOS-patched games

Source/Core/Core/IOS/ES/ES.cpp, Source/Core/Core/IOS/ES/Formats.cpp, Source/Core/Core/IOS/ES/NandUtils.cpp, Source/Core/Core/IOS/ES/TitleContents.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.cpp, Source/Core/Core/IOS/FS/FileSystemProxy.h, Source/Core/Core/IOS/IOS.cpp
This changes FileSystemProxy::Open to return a file descriptor wrapper
that will ensure the FD is closed when it goes out of scope.
By using such a wrapper we make it more difficult to forget to close
file descriptors.
This fixes a leak in ReadBootContent. I should have added such a class
from the beginning... In practice, I don't think this would have caused
any obvious issue because ReadBootContent is only called after an IOS
relaunch -- which clears all FDs -- and most titles do not get close
to the FD limit.
=> IOS/FS: Add a scoped FD class to make it harder to leak FDs

Source/Core/VideoBackends/Software/Clipper.cpp, Source/Core/VideoBackends/Software/Rasterizer.cpp, Source/Core/VideoCommon/BPFunctions.cpp, Source/Core/VideoCommon/BPMemory.h, Source/Core/VideoCommon/BPStructs.cpp
VideoCommon: Fix scissorOffset, handle negative value correctly
VideoBackends: Fix Software Clipper.PerspectiveDivide function, use bpmem.scissorOffset instead of hard code 342
Origin pull request: [#9656](https://github.com/dolphin-emu/dolphin/pull/9656)
Can some one help me to reopen #9656, I found a way to reset the commits.
=> VideoCommon: Fix scissorOffset, handle negative value correctly

Source/Core/VideoBackends/Software/TextureEncoder.cpp
This was causing issues in Software Renderer.
Attempting to solve https://bugs.dolphin-emu.org/issues/11487
=> SW: Fix alignedWidth in TextureEncoder

Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.cpp, Source/Core/Core/PowerPC/Jit64/RegCache/JitRegCache.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/PPCAnalyst.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h
When the interpreter writes to a discarded register, its type must be changed so that it is no longer considered discarded.
Fixes a PR #9351 regression.
=> Jits: Fix interpreter fallback handling of discarded registers

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Common/ArmCPUDetect.cpp, Source/Core/Common/ArmFPURoundMode.cpp, Source/Core/Common/CMakeLists.txt, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/Jit_LoadStoreFloating.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStoreFloating.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp, Source/Core/Core/PowerPC/JitArmCommon/BackPatch.h, Source/Core/Core/PowerPC/JitCommon/JitAsmCommon.h, Source/Core/Core/PowerPC/JitCommon/JitBase.h, Source/Core/Core/PowerPC/PPCAnalyst.cpp, Source/Core/Core/PowerPC/PPCAnalyst.h, Source/Core/DolphinLib.ARM64.props, Source/UnitTests/Core/CMakeLists.txt, Source/UnitTests/Core/PowerPC/JitArm64/ConvertSingleDouble.cpp, Source/UnitTests/UnitTests.vcxproj
Fixes https://bugs.dolphin-emu.org/issues/12388. Might also fix other games that have problems with float, paired, float loadstore, or paired loadstore instructions in JitArm64, but I haven't tested any.
Left to do:
=> JitArm64: Set flush-to-zero/rounding mode and improve float/double conversion accuracy

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.h
Repeated erase() + iteration on a std::multimap is extremely slow. Slow enough that it causes a 7 second long stutter during some transitions in F-Zero X (a N64 VC game that triggers many, many icache invalidations).
And slow enough that JitBaseBlockCache::DestroyBlock shows up on a flame graph as taking >50% of total CPU time on the CPU-GPU thread.
**Master**:
This PR optimises those block link queries by replacing the std::multimap (which is typically implemented with red-black trees) with hash tables, which seem better suited to our repeated insert/erase/iteration workload.
**PR**: ~0.7s stutters (10x less), which is pretty close to 5.0 stable. (5.0-2021 introduced the performance regression and it is especially noticeable when branch following is disabled, which is the case for all …
=> Jit: Optimize block link queries by using hash tables

Source/Core/DolphinQt/AboutDialog.cpp
=> DolphinQt: Get rid of an extraneous colon in About dialog

Source/Core/Core/HW/SI/SI_DeviceGBA.cpp
The 115200 baudrate that was previously in this connection was guessed, seemingly at random, and does not match hardware at all. It takes ~5 µs per bit when the GC sends and ~4 µs per bit when the GBA replies, confirmed by actual captures of logic analyzer data I did a few years back. The stop bit timing was also not present, which I have added somewhat rough approximations of. I can attach said data as proof if desired.
Marked as WIP because this will probably break VBA-M, and is mostly here for informational purposes for the time being.
=> SI/DeviceGBA: Fix SI timings to actually closely match hardware

Source/Android/app/src/main/res/values/arrays.xml, Source/Core/DolphinQt/Settings/AdvancedPane.cpp
I think the AArch64 JIT has come far enough that it doesn't have to be called experimental anymore.
I'm also labeling the x86-64 JIT as x86-64 for consistence with the AArch64 JIT. This will especially be helpful if we start supporting AArch64 on macOS, as AArch64 macOS can run both the x86-64 JIT and the AArch64 JIT depending on whether you enable Rosetta 2.
=> DolphinQt/Android: Unify the JIT naming scheme

Source/Core/DolphinQt/Config/Mapping/MappingWindow.cpp
This fixes the input profile drop down not resizing.  This regression was due to #8867 where I made that change because I was trying to fix the device drop down from disappearing with a small window (in order to do that I changed the size policy from `Ignored` to `Expanding`).  However, this  made the device drop down take up all the space!  So now I've tried changing the size policy from `Expanding` to `Minimum`.
Please test!
=> DolphinQt: fix input profile drop down not resizing

Source/Core/InputCommon/ControlReference/ExpressionParser.cpp
`EnableSuppression()` was called in `UpdateReferences()` but then not executed if `m_suppressor` is already valid, causing input to stay nullptr in the `m_suppressions` map, which would fail to find an element and crash because it wasn't checked for validity.
I fixed the source of that happening, but also added safety checks around against nullptr.
I had gotten this was crash twice in months, both times in Debug, on startup, without doing anything, while Dolphin was loading (from the hotkey thread). It was probably just an order/timing dependency between threads.
If I had to guess, I'd say that it worked before because `EnableSuppression()` is called constantly by `GetValue()` so it would constantly refresh, but if things didn't happen in a specific order, it would crash.
The crash (on …
=> Fix hotkey suppression crash

Source/Core/DolphinQt/Config/VerifyWidget.cpp, Source/Core/DolphinQt/Config/VerifyWidget.h
Verifying a Wii game creates an instance of IOS, and Dolphin can't handle more than one instance of IOS at the same time. Properly supporting it is probably more effort than it's worth.
Fixes https://bugs.dolphin-emu.org/issues/12494.
=> DolphinQt: Disable verify button when emulation is running

Source/Core/DolphinQt/Config/Mapping/MappingCommon.cpp
While this opens up the possibility to create more complex expressions, the half second delay was the source of much confusion and frustration for users who didn't know what the emulator was doing.  The emulator essentially hard locked for 500ms and sometimes would get all kinds of weird inputs because they'd start spamming buttons trying to unfreeze it.
This makes the delay 0, returning the behavior to the way it was before.  This means you cannot do | statements without using the advanced input expression anymore.
=> Remove Input Mapping Delay

Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/WiiRoot.cpp, Source/Core/Core/WiiRoot.h
The SaveToSYSCONF call in BootManager.cpp was unintentionally overriding the temporary NAND set by the preceding InitializeWiiRoot call. Fixes https://bugs.dolphin-emu.org/issues/12500.
=> IOS: Don't let Kernel initialize WiiRoot if already initialized

Source/Core/VideoCommon/BPFunctions.cpp, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/VideoCommon.h
Dolphin doesn't correctly emulate 3xMSAA mode. It probably never will as it's kind of pointless when users can just force everything to have 4xMSAA or 16xMSAA or even stupidly high Internal Resolutions.
Besides, Not many games uses the 3xMSAA mode. It's a real pain to use when it cuts the vertical EFB resolution in half to 640x264, requiring multiple passes to get a complete 4:3 frame. 
But Rogue Squadron uses it. Actually, Factor 5 cheap out and only uses it during cutscenes. They cheap out even further by rendering many of those cutscenes in a "cinematic widescreen" aspect ratio with a resolution of 512x264 that just so happens to fit inside a single 3xMSAA EFB buffer. 
Dolphin's trickery is usually hidden from games. Except RS3 also directly accesses the EFB framebuffer to check the …
=> Implement EFB Peeks for compressed z16 formats

Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
Seems like I made a little copy-paste error.
=> JitArm64: Fix JitRegister::Register call for cstd

Source/Android/app/src/main/AndroidManifest.xml
In PR #9654, I explicitly set `android:debuggable="true"` for Dolphin. (By default, it's set for debug builds but not release builds.) The reason I made the change is because debuggable must be set to true in order to allow `adb backup` to be used with apps which target Android 12. We have no reason to want to stop users from debugging Dolphin and certainly no reason to stop users from using `adb backup` (especially not after forced storage is going to force us to store the User folder in app-specific external storage!), but, it turns out that setting debuggable to true is forbidden by Google Play "for security reasons". Go figure. The beta build which was tagged earlier today was rejected because of this.
=> Android: Don't set android:debuggable="true"

Source/Core/Common/ChunkFile.h, Source/Core/VideoCommon/TextureCacheBase.cpp
I'm doing a project with Dolphin which wants to save state incredibly frequently (~every frame). Reallocating `texture_data` in `TextureCacheBase::SerializeTexture` takes up a non-negligible amount of the serialization time in my environment. For my own project I might be able to implement a check to see if textures have changed in the last frame and avoid re-serializing them, but this is general enough to save everybody some fractions of a second when they save state - maybe TASers would appreciate it?
This PR fixes the issue by adding a method to `PointerWrap` which sets aside some space for the caller to read/write/verify, then using it to set aside one large chunk of space all at once in the texture cache. This should not change the save-state format.
Additionally, the new method is …
=> Remove spurious memory allocations in TextureCacheBase::SerializeTexture and DeserializeTexture

Source/Core/Core/Core.cpp, Source/Core/Core/Core.h, Source/Core/DolphinNoGUI/MainNoGUI.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/VideoCommon/FPSCounter.cpp, Source/Core/VideoCommon/FPSCounter.h, Source/Core/VideoCommon/RenderBase.cpp
…by adding the pause state to FPSCounter.
-Add ability to have more than one "OnStateChanged" callback in core.
-Add GetActualEmulationSpeed() in Core, which will be used by input functions added by future commits (requires the new FPS counter features). It returns 1 if the emulation is not running.
Changes are actually really minor. I suggest just testing against master and seeing the problem being fixed for yourself.
=> Fix FPS counter and Game Window speed % breaking on pause/unpause

Source/Core/Common/BitField.h, Source/Core/Common/CMakeLists.txt, Source/Core/Common/TypeUtils.h, Source/Core/DolphinLib.props, Source/Core/VideoCommon/UberShaderCommon.cpp, Source/Core/VideoCommon/UberShaderCommon.h, Source/Core/VideoCommon/UberShaderPixel.cpp, Source/Core/VideoCommon/UberShaderVertex.cpp
This PR changes `BitfieldExtract` to use a pointer to a member to deduce information about the BitField instead of creating a temporary variable and passing its bitfield instance.  The pointer-to-member is also a template argument instead of a regular argument.  For example, `BitfieldExtract("colorreg", LitChannel().matsource)` is now `BitfieldExtract<&LitChannel::matsource>("colorreg")`, and `BitfieldExtract("ss.cc", TevStageCombiner().colorC.bias)` is now `BitfieldExtract<&TevStageCombiner::ColorCombiner::bias>("ss.cc")`.
As an additional change to make this work, I made `BitField::StartBit` and `BitField::NumBits` static.  The other code that already used `StartBit` is not affected by this change (for instance `int(TwoTevStageOrders().enable1.StartBit() - …
=> Change BitfieldExtract to use a pointer to the bitfield member

Source/Core/VideoBackends/Software/Tev.cpp, Source/Core/VideoCommon/BPMemory.h, Source/Core/VideoCommon/GXPipelineTypes.h, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/PixelShaderGen.h, Source/Core/VideoCommon/PixelShaderManager.cpp, Source/Core/VideoCommon/UberShaderPixel.cpp
Fixes the Mario portrait blur effect in Luigi's Mansion ([issue 11462](https://bugs.dolphin-emu.org/issues/11462)).  Closes #8296 (the older implementation).
When a tex coord is greater than or equal to the number of tex gens, the behavior is undefined on console, but it generally appears to be equivalent to using tex coord 0 (instead of clamping it, or setting the value to (0, 0), or just using whatever garbage is already around).  This applies to both direct and indirect textures.  There does seem to be some unpredictable garbage data that also can be used, but I don't know the details of it and that doesn't seem to be an issue with the Mario portrait.
There is an exception to this: when 0 tex gens are enabled, I always got a black image on console; ~~I didn't implement this in Dolphin …
=> Fix out of bounds tex coord behavior; always apply fb_addprev and tex coord wrapping

Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureCacheBase.h
Previously, when looking for XFBs in the texture cache, if their dimensions didn't match VI we were recomputing the hash.  However, when we did so we weren't using the same hash logic as we did when actually hashing the entry.
Additionally, when dealing with oversized XFBs (which are resized on creation) the hashing algorithm is actually different than the one used to hash the VI registers that we compare against.  This causes these copies to be invalidated, meaning we will fall back to stitching from guest memory (if it exists).
This change fixes both of those issues.  This seems to resolve [12392](https://bugs.dolphin-emu.org/issues/12392)
=> VideoCommon: update TextureCache logic for finding oversized XFBs

Source/Core/Core/HW/WiimoteCommon/DataReport.cpp
This particular range check is kind of odd, and would only interpret interleave mode 2 as a valid mode, while rejecting interleave mode 1 and the extension byte mode.
As far as I know, and, based off the information on Wiibrew, we should be considering all three values within this range as valid.
=> DataReport: Amend conditional test for data reports in IsValidMode

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Another tiny optimization.
By taking advantage of three-operand IMUL, we can eliminate a MOV instruction. This is a small code size win. However, due to IMUL sign extending the immediate value to 64 bits, we can only apply this when the magic number's most significant bit is zero.
To ensure this can actually happen, we also minimize the magic number by checking for trailing zeroes.
<details><summary>Unsigned division by 18</summary>
Before:
```
41 BE E4 38 8E E3    mov         r14d,0E38E38E4h
4D 0F AF F5          imul        r14,r13
49 C1 EE 24          shr         r14,24h
```
After:
```
4D 69 F5 39 8E E3 38 imul        r14,r13,38E38E39h
49 C1 EE 22          shr         r14,22h
```
</details>
<details><summary>Unsigned division by 52</summary>
Before:
```
B8 9E D8 89 9D       mov …
```
=> Jit64: divwux - Prefer three-operand IMUL

Source/Core/Core/IOS/Network/Socket.cpp
`WiiSockMan::NewSocket` in Socket.cpp is the function that's responsible for creating a host network socket when the emulated game wants to make a socket. 
Currently, Dolphin assumes that an IPv6 socket (AF_INET6) requested by the emulated software has the same integer value (23) on all operating systems and just passes that 23 through to the `socket` call. 
That assumption is true on Windows, but it's not true on other OSes. 
AF_INET6 is 23 on a Wii and on Windows, but it's 10 on most Linux systems, and 30 on MacOS or iOS. 
In theory, the same thing is true for IPv4 (AF_INET), too. AF_INET isn't 100% guaranteed to be 2, though it probably always is. Still, I added that bugfix for IPv4, too, just in case.
This particular issue is _probably_ not a big deal as I don't know of any Wii …
=> Socket: Fix AF_INET6 on non-Windows systems

Source/Core/DolphinLib.props, Source/Core/VideoCommon/CMakeLists.txt, Source/Core/VideoCommon/HiresTextures.cpp, Source/Core/VideoCommon/HiresTextures.h, Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureCacheBase.h, Source/Core/VideoCommon/TextureInfo.cpp, Source/Core/VideoCommon/TextureInfo.h
More stuff can be moved over if desired later, I tried to stick to the basic information needed to calculate the texture id.  This cleans up the code ever so slightly, the current TextureCacheBase code is hard to follow because it changes some of the parameters it passes in but not all.  This centralizes the code and makes its members const, hopefully making it easier to read.
Additionally, and more importantly, texture data is currently loaded and bound in [VertexManagerBase](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/VideoCommon/VertexManagerBase.cpp#L481).  By providing this class, the texture data can be leveraged in other areas of the code base, allowing us to provide new enhancements.
=> VideoCommon: move all texture calculations to a "TextureInfo" class

Source/Core/Common/StringUtil.cpp, Source/Core/Common/StringUtil.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/ControlGroup.cpp, Source/Core/InputCommon/ControllerEmu/Setting/NumericSetting.h
The control expression editor allows line breaks, but the serialization was losing anything after the first line break (/r /n).
Instead of opting to encode them and decode them on serialization,
which I tried but was not safe, as it would lose `\n` written in the expression by users,
I opted to replace them with a space, to at least maintain some of the spacing the user originally put in.
Completely removing them could also have caused the expression to be parsed differently.
This cannot cause any breaking differences on the expression, and its in any way better than before, as before part of the string could just get lost.
=> Fix serialization of control expressions with line breaks

Data/Sys/GameSettings/RJ8.ini
The option to disable ICache is recent but it allows Indiana Jones and the Staff of Kings to proceed where it would otherwise crash.
This game got past the first loading screen and in-game in 3.0-195(1387da790062f67ea79db470999e37d0ed43c57f), however at certain parts the game will crash. Recent logs will state that an ICache read returned stale data.
=> Gameini: Disable ICache for Indiana Jones and the Staff of Kings

Source/Core/Core/DSP/DSPCore.cpp, Source/Core/Core/DSP/DSPCore.h, Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp, Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp
Making this volatile accomplishes... Well, nothing in practice. Making it atomic, on the other hand, lets us enforce a memory ordering.
=> DSP: Change external_interrupt_waiting from volatile to atomic

Source/Core/Core/FifoPlayer/FifoAnalyzer.cpp, Source/Core/Core/FifoPlayer/FifoAnalyzer.h, Source/Core/Core/FifoPlayer/FifoPlaybackAnalyzer.cpp, Source/Core/Core/FifoPlayer/FifoPlaybackAnalyzer.h, Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/FifoPlayer/FifoPlayer.h, Source/Core/Core/FifoPlayer/FifoRecordAnalyzer.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.h, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp, Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.h, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/VideoCommon/CPMemory.h, Source/Core/VideoCommon/VertexLoader.cpp, Source/Core/VideoCommon/VertexLoader.h, Source/Core/VideoCommon/VertexLoaderARM64.cpp, Source/Core/VideoCommon/VertexLoaderARM64.h, Source/Core/VideoCommon/VertexLoaderBase.cpp, Source/Core/VideoCommon/VertexLoaderBase.h, Source/Core/VideoCommon/VertexLoaderManager.cpp, Source/Core/VideoCommon/VertexLoaderManager.h, Source/Core/VideoCommon/VertexLoaderX64.cpp, Source/Core/VideoCommon/VertexLoaderX64.h, Source/Core/VideoCommon/VertexLoader_Color.cpp, Source/Core/VideoCommon/VertexLoader_Color.h, Source/Core/VideoCommon/XFStructs.cpp, Source/Core/VideoCommon/XFStructs.h, Source/UnitTests/VideoCommon/VertexLoaderTest.cpp
Part 2 of #9497.  ~~Currently, the first commit stubs the changes it makes that are depended upon by later commits; once that is eventually emerged it should cleanly rebase with that commit dropped.~~
=> Fifo analyzer quality of life improvements

Source/Core/Core/PowerPC/PPCAnalyst.cpp
`code` points to the first instruction in the block, not the current instruction.
=> PPCAnalyst: Fix broken bitexact analysis

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/QtUtils/FlowLayout.cpp, Source/VSProps/QtCompile.props
Uses the [experimental external feature](https://devblogs.microsoft.com/cppblog/broken-warnings-theory/) to ignore warnings in header.  This is experimental right now but the [latest preview release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.10.0.pre.3.0) seem to indicate it's going out of experimental status.
This should fix the build errors we're seeing.
I wasn't sure if there was a better place for this.  Also, ideally this should be applied to _all_ our external library headers but that's a much larger change.
=> DolphinQt: ignore warnings from qt headers on buildbot

Source/VSProps/QtCompile.props
As of 99a724361abb5c9728761dfc13b9f58a0b4fff8b Visual Studio gets hopelessly confused if QtIncludeDirectory has any spaces in the path. Adding quotes around the include directive solves the issue.
=> DolphinQt: Add quotes around QtIncludeDir on Windows

Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
`Settings.SECTION_INI_ANDROID` and `Settings.SECTION_BINDINGS` both have the value `"Android"`, but we only want the former to be marked as being handled by the new config system.
This change fixes a problem where controller settings were not being properly saved to Dolphin.ini.
=> Fix Android controller mappings accidentally being in IsSettingSaveable

Source/Core/DolphinQt/Config/Graphics/BalloonTip.cpp, Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Settings.h
Dolphin still has a lot of tooltips which haven't been converted to BalloonTips, which is fine, and some are way harder to convert as there is no code for them yet (e.g. ComboBox per item ToolTips).
With this simple addition to the qApp style sheet (mostly using existing code), **ToolTips**, and only ToolTips, **will visualize themselves with the exact same colors and padding size of BalloonTips**. Plus, now parts of their code is shared, so it can safely be changed in one place to reflect to both.
Tested. Works with high and not high contrast, or any theme brightness. Also works on top of any other style sheet (the ToolTip style is only overridden if not already specified).
There should be no possible regression from this, and BalloonTips will still look exactly as before (and they will …
=> Make all Qt ToolTips look similar to BalloonTips

Source/Core/VideoCommon/OnScreenDisplay.cpp
Mainly fixed 2 things on "On Display Messages":
-They might have never drawn if DrawMessages wasn't called before they actually expired.
-Their fade was wrong if the duration of the message was less than the fade time.
This makes them much more useful for debugging, I know there might be other means of debugging like logs and imgui, but this was the simplest so that's what I used.
If you want to print the same message every frame, but with a slightly different value to see the changes, it now work.
To compensate for the fact that they are now always rendered once, so on start up a lot of old messages (printed while the emulation was off) could show up, I've added a "drop" time, which means if a msg isn't rendered for the first time within that time, it will be dropped and never rendered. …
=> fixes for "On Display Messages"

Source/Core/DolphinQt/Debugger/WatchWidget.cpp, Source/Core/DolphinQt/Debugger/WatchWidget.h
This PR adds to the Watch widget toolbar items to create, delete and clear watches.
Ready to reviewed & merged.
=> WatchWidget: Add new/delete/clear toolbar items

Source/Core/Core/HW/WiimoteEmu/Extension/Guitar.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Attachments.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUAccelerometer.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUGyroscope.h
Skimming of: https://github.com/dolphin-emu/dolphin/pull/9489
A few fixes/improvements/cleanup for input related stuff, nicely described in commits.
Separated from https://github.com/dolphin-emu/dolphin/pull/9688 because this one actually has behavioural changes and needs to be reviewed.
=> Input cleanup 2

Source/Core/Core/HW/GCPadEmu.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp
Sending an empty string to the translation system will not result in getting an empty string back, but rather a description of the currently loaded translations file. So empty strings should not be marked as translatable.
Also adding some i18n comments and rewording a string I thought was hard to understand.
=> Fixes to translatable strings

Source/Core/Core/HW/GCPadEmu.cpp
Sorry, the fix I made to the empty string in PR #9726 was not actually sufficient, as DolphinQt will call `tr` on the string regardless of whether it's marked with `_trans`. The proper fix is to use `nullptr`, which DolphinQt has a special check for.
=> Fixes to translatable strings, take 2

Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/NetPlayServer.h, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
It doesn't really belong in frontend code, and this change will make it easier to eventually support NetPlay on other UI frameworks. This should have no effect on current functionality, as it's more or less a refactor.
=> NetPlay: Move NetSettings initialization to backend

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Some of the optimizations introduced in #9566 can be tweaked to generate ever so slightly better code under specific circumstances.
---
<details><summary>Division by 2 (with d == a)</summary>
Before:
```
8B C7                mov         eax,edi
8B F8                mov         edi,eax
C1 EF 1F             shr         edi,1Fh
03 F8                add         edi,eax
D1 FF                sar         edi,1
```
After:
```
8B C7                mov         eax,edi
C1 EF 1F             shr         edi,1Fh
03 F8                add         edi,eax
D1 FF                sar         edi,1
```
</details>
<details><summary>Division by power of 2 (with d == a)</summary>
Before:
```
8B C6                mov         eax,esi
85 C0                test        eax,eax
8D 70 03             lea …
```
=> Jit64: Minor divwx optimizations

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
FMOV is faster than INS and ties UMOV. (On all CPUs I checked, at least. It certainly shouldn't be slower, though.)
=> JitArm64: Prefer using FMOV when doing single/double conversion

Source/Core/VideoBackends/D3D/D3DPerfQuery.cpp, Source/Core/VideoBackends/OGL/OGLPerfQuery.cpp
When trying to do a small optimization in PR #9710, I failed to take into account that `WeakFlush` and `FlushOne` update `m_query_count`.
Only D3D11 and OGL had this problem, not D3D12 and Vulkan.
=> Fix perf query regression

Source/Core/Common/Version.cpp, Source/Core/Common/Version.h, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/IOS/DolphinDevice.cpp, Source/Core/UICommon/AutoUpdate.cpp
Any file which includes scmrev.h must be rebuilt when scmrev.h is regenerated. By not including scmrev.h from any file other than Version.cpp, incremental builds become a little faster.
=> Avoid including scmrev.h except in Version.cpp

Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp
The interpreter implementation of fctiwx was treating rounding mode 0 as "round to nearest, ties towards zero", which is not an actual IEEE-754 rounding mode. The IBM document mentioned in a comment at the top of the function, on the other hand, treats rounding mode 0 as "round to nearest, ties to even", which makes more sense.
This fixes one of JMC's console-recorded F-Zero GX replays on JitArm64. (JitArm64 uses an interpreter fallback for fctiwx.)
=> Interpreter: Fix fctiwx rounding

Source/Core/VideoBackends/D3D/D3DRender.cpp, Source/Core/VideoBackends/D3D/D3DRender.h, Source/Core/VideoBackends/D3D12/D3D12Renderer.cpp, Source/Core/VideoBackends/D3D12/D3D12Renderer.h, Source/Core/VideoBackends/Null/NullRender.h, Source/Core/VideoBackends/OGL/OGLRender.cpp, Source/Core/VideoBackends/OGL/OGLRender.h, Source/Core/VideoBackends/Software/SWRenderer.cpp, Source/Core/VideoBackends/Software/SWRenderer.h, Source/Core/VideoBackends/Vulkan/VKRenderer.cpp, Source/Core/VideoBackends/Vulkan/VKRenderer.h, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/RenderBase.h
The GC/Wii GPU rasterizes in 2x2 pixel groups, so bounding box values will be rounded to the extents of these groups, rather than the exact pixel. To account for this, we'll round the top/left down to even and the bottom/right up to odd. I have verified that the values resulting from this change exactly match a real Wii.
I would have implemented this in the pixel shaders, but the NVIDIA driver seems to be outsmarting me and optimizes out all my attempts to perform these operations in there, as it works on Vulkan but not OpenGL.
I used this modified homebrew to perform the hardware test: https://qimg.techjargaming.com/f/vRk5NA28/triangle.elf
Source code (ignore the mess, I've used it for a number of tests): https://gist.github.com/Techjar/4f38aa7807d0f5334011ef14ec721219
The values it …
=> VideoCommon: Account for pixel quads in bounding box calculation

Source/Core/Core/PowerPC/MMU.cpp
Shouldn't have any behaviour change for regular usage as both masks are 32MB by default.
But fixes a theoretical buffer overrun when memory size override is larger than 32MB.
=> Use Correct mask for Fake VMem

Source/Core/VideoCommon/TextureInfo.cpp, Source/Core/VideoCommon/TextureInfo.h
A slight change to the logic here broke existing texture packs. While it's not ideal that texture names imply they have mipmaps when there's 0 mip levels, that's the way it was written so we're stuck with it.
Fixes https://bugs.dolphin-emu.org/issues/12514
=> VideoCommon/TextureInfo: Restore old mipmap detection logic

Source/Core/DolphinQt/Settings/GeneralPane.cpp
This fixes a nasty issue where you can change the Dual Core setting during emulation, if it has been overridden by GameINI or NetPlay, by simply changing any of the non-disabled settings. This is because changing any of the settings will write all of them to the config.
This issue is particularly nasty because managing to disable Dual Core during emulation, and then stopping it, results in the emulator core being totally deadlocked. It's impossible to recover from this state, and Dolphin will remain as a zombie process on the system, consuming resources and holding locks, until forcibly killed.
=> Qt/GeneralPane: Refresh widget state on config change

Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp
The picture should explain everything. Simply, if the mapping did not use a default device when it was made, its preview was completely "useless".
Splitting by "**`**" is 100% safe as special characters have a distinct and unique meaning in controls expressions, so there couldn't be any false positives from this code.
The only downside is not seeing what device a control corresponds to, but you can finally see the control at least, which is still better than only seeing (part of) the device name. We now add the prefix "**:**" if a control has got a device specifier in front of them.
We also remove white spaces and \n \t \r from the mapping preview.
**Extras:**
**bugfix**: fix EmulatedController::GetStateLock() not being acquired when reading the expression reference
**bugfix**: …
=> Simplify the preview of control mappings by removing the device path from controls

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp, Source/Core/DolphinQt/Config/Mapping/IOWindow.h, Source/Core/InputCommon/ControlReference/ExpressionParser.cpp, Source/Core/InputCommon/ControlReference/ExpressionParser.h, Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp, Source/Core/InputCommon/ControllerEmu/ControllerEmu.h
-add a way to reset their value (from the mappings UI)
-fix "memory leak" where they would never be cleaned, one would be created every time you wrote a character after a "$"
-fix ability to create variables with an empty string by just writing "$" (+ added a parsing error for the case)
-add $ operator to the UI operators list, to expose this functionality even more
The UI will now show all the custom variables used.
Their value is kept as long as there is at least one mapping (control expression) referencing them. You can ever change devices or input profile and as long as the variable was and is still referenced, the value will be kept.
Still, the ability to reset values without restarting Dolphin or being forced to change their names can be useful.
UI is always kept to date with the …
=> Expose Control Expression variables to mappings UI

Source/Core/Core/HW/SI/SI.cpp, Source/Core/Core/HW/SI/SI_DeviceGBA.cpp, Source/Core/Core/HW/SI/SI_DeviceGCController.cpp, Source/Core/Core/HW/SI/SI_DeviceNull.cpp
I've noticed that NOREP timeouts aren't actually generated in Dolphin when there's no reply, instead favoring generating the reply that I _believe_ is actually created by the Dolphin SDK instead. I don't have proof that this behavior is correct, but I'm also not sure where to begin investigating.
=> SI: Generate NOREP on timeout instead of generating Dolphin SDK reply

Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.cpp, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp
All the other CPU emulation cores do it on <= 0.
=> JitArm64: Jump to dispatcher on downcount <= 0, not < 0

Source/Android/jni/AndroidCommon/AndroidCommon.cpp, Source/Android/jni/GameList/GameFileCache.cpp
Any local references get cleaned up when returning to the JVM, but some of the functions in AndroidCommon return to C++ rather than the JVM, and functions with loops risk running into the limit of how many simultaneous local references are allowed.
=> Android: Use DeleteLocalRef more in AndroidCommon

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h
Looks like the option was added to the Wx UI at commit 198d3b69, which was a few months after the advancedWidget was originally ported from Wx to Qt, but before anyone was actually using Qt.
And it was simply forgotten in the transition. 
Screenshot of updated UI:
=> Port Dump XFB Target option to Qt UI.

Data/Sys/GameSettings/GCCE01.ini
There is a race condition in FFCC when entering any level: GBAs will be stuck on a flickering "Waiting for connection..." screen for a random amount of time
The race happens on the GBA side during the handshake process. If the game also tries to send data during that process it will be pushed into a queue and transfers won't resume once the connection is established, causing it to timeout after 10 frames before trying again
Although this happens on HW, Dolphin is much more likely to lose the race repeatedly due to timing inaccuracies and that can last up to a minute depending on your luck and configuration which is why I believe this should be enabled by default
These patches apply the necessary changes to the rom at ``/dvd/gba/ffcc_cli.bin`` to clear the transfer queue once connected
=> GameINI: Fix Final Fantasy Crystal Chronicles GBA race condition

Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/UberShaderPixel.cpp
This fixes rendering issues in Viewtiful Joe ([bug 12525](https://bugs.dolphin-emu.org/issues/12525)).  The issue was introduced in #9651, specifically by the "always apply fb_addprev and tex coord wrapping" aspect; with that, I also always applied the indirect operation.  Doing that is is not hardware accurate, but **skipping it (which is what this PR does) is not either**; [this test case](https://gist.github.com/Pokechu22/55cb365518defd58d6a294c22e566787) (specifically the files ending in 0Y) trigger this undefined behavior on console.  However, skipping gives a result that's close enough to avoid visual issues in Viewtiful Joe.
Based on the fifolog there, Viewtiful Joe tends to set the indirect configuration at the start of most objects, by clearing it for TEV stages 0 and 1 (with BP …
=> Skip indirect operation for out of bounds indirect stages

Source/Core/VideoBackends/D3D/D3DBoundingBox.cpp, Source/Core/VideoBackends/D3D/D3DBoundingBox.h, Source/Core/VideoBackends/D3D/D3DRender.cpp, Source/Core/VideoBackends/D3D/D3DRender.h, Source/Core/VideoBackends/OGL/OGLBoundingBox.cpp, Source/Core/VideoBackends/OGL/OGLBoundingBox.h, Source/Core/VideoBackends/OGL/OGLRender.cpp, Source/Core/VideoBackends/OGL/OGLRender.h
This was present in the Vulkan and DX12 renderers, but not DX11/GL.
Quick test shows 60fps->90fps at 1x, and 55fps->80fps at 3x on an AMD GPU.
Bounding box is broken on OpenGL/AMD due to what seems to be a driver bug - the atomic only works on one of the fields, so I can't test it.
=> Cache bounding box values between register reads in DX11/GL

Source/Core/VideoBackends/D3D/D3DRender.cpp, Source/Core/VideoBackends/D3D/D3DRender.h, Source/Core/VideoBackends/D3D12/D3D12Renderer.cpp, Source/Core/VideoBackends/D3D12/D3D12Renderer.h, Source/Core/VideoBackends/Null/NullRender.h, Source/Core/VideoBackends/OGL/OGLRender.cpp, Source/Core/VideoBackends/OGL/OGLRender.h, Source/Core/VideoBackends/Software/SWRenderer.cpp, Source/Core/VideoBackends/Software/SWRenderer.h, Source/Core/VideoBackends/Software/Tev.cpp, Source/Core/VideoBackends/Vulkan/VKRenderer.cpp, Source/Core/VideoBackends/Vulkan/VKRenderer.h, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/RenderBase.h
This avoids rounding values that the game writes to the bounding box registers, especially the default values.
Fixes corruption/crash in Paper Mario TTYD
https://bugs.dolphin-emu.org/issues/12524
=> VideoCommon: Move bounding box pixel quads rounding to shader

Source/Core/VideoBackends/OGL/OGLBoundingBox.cpp
We also need to ensure the the CPU does not receive stale values which have been updated by the GPU. Apparently the buffer here is not coherent on NVIDIA drivers.
Not sure if this is a driver bug/spec violation or not, one would think that glGetBufferSubData() would invalidate any caches as needed, but this path is only used on NVIDIA anyway, so it's fine.
A point to note is that according to ARB_debug_report, it's moved from video to host memory, which would explain why it needs the cache invalidate.
=> OGL: Force memory barrier when reading back bounding box values

Source/Core/Common/NandPaths.cpp, Source/Core/Common/NandPaths.h, Source/Core/Core/NetPlayClient.cpp
A sort of follow-up to #9754. ~~Has not yet been tested.~~
=> NetPlay: Check file names when receiving GCI folder

Source/Core/Core/State.cpp, Source/Core/VideoBackends/D3D/D3DRender.cpp, Source/Core/VideoBackends/D3D/D3DRender.h, Source/Core/VideoBackends/D3D12/D3D12Renderer.cpp, Source/Core/VideoBackends/D3D12/D3D12Renderer.h, Source/Core/VideoBackends/Null/NullRender.h, Source/Core/VideoBackends/OGL/OGLRender.cpp, Source/Core/VideoBackends/OGL/OGLRender.h, Source/Core/VideoBackends/Software/SWRenderer.cpp, Source/Core/VideoBackends/Software/SWRenderer.h, Source/Core/VideoBackends/Vulkan/VKRenderer.cpp, Source/Core/VideoBackends/Vulkan/VKRenderer.h, Source/Core/VideoCommon/BPStructs.cpp, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/RenderBase.h, Source/Core/VideoCommon/VideoBackendBase.cpp
The SDK seems to write "default" bounding box values before every draw (1023 0 1023 0 are the only values encountered so far, which happen to be the extents allowed by the BP registers) to reset the registers for comparison in the pixel engine, and presumably to detect whether GX has updated the registers with real values. Handling these writes and returning them on read when bounding box emulation is disabled or unsupported, even without computing real values from rendering, seems to prevent games from corrupting memory or crashing.
This obviously does not fix any effects that rely on bounding box emulation, but having the game not clobber its own code/data or just outright crash is a definite improvement.
=> VideoCommon: Add fallback handling for bounding box when disabled or unsupported

Source/Android/app/build.gradle
This reduces the build time for incremental builds from about 2 minutes to about 20 seconds. Most people never run the unit tests on Android anyway (I'm not aware of anyone other than me ever having done it).
=> Android: Disable building unit tests by default

Source/Core/VideoCommon/DriverDetails.cpp, Source/Core/VideoCommon/DriverDetails.h, Source/Core/VideoCommon/PixelShaderGen.cpp
At least on my (old) AMD device, bounding box does not work on OpenGL; using an `int4` works, while using 4 ints (either as an array or 4 separate fields) does not work.  The Metal shader compiler does not work with `int4`, though, so both variants need to be supported.
I don't know if this is an issue on newer AMD devices as well.
See also #9762.
=> VideoCommon: Fix bounding box on AMD/OpenGL/Windows

Source/Core/Common/StringUtil.cpp, Source/Core/Common/StringUtil.h, Source/Core/UICommon/AutoUpdate.cpp, Source/UnitTests/Common/StringUtilTest.cpp
Escapes &<>'" characters in the "Update available" modal's short commit descriptions.
Before:
After:
Fixes https://bugs.dolphin-emu.org/issues/12521
=> Updater: Escape HTML characters in commit descriptions

Source/Core/Core/HW/WiimoteCommon/WiimoteHid.h, Source/PCH/pch.h, Source/VSProps/Base.props, Source/VSProps/QtCompile.props
Add external include paths to ExternalIncludePath instead of
AdditionalIncludeDirectories. msbuild appends these paths to
EXTERNAL_INCLUDE env var, which is passed to /external:env:.
Specify /external:W0 and /external:templates-, with override for
DolphinQt for the template flag, since Qt 5.15.0 causes some warnings
in qmap.h
fixes the [(harmless) warnings](https://dolphin.ci/#/builders/21/builds/4024/steps/3/logs/warnings__18_) that showed up recently
=> msvc: use external header feature solution-wide

Source/Core/VideoCommon/PixelShaderGen.cpp
Fragment coordinates always have a 0.5 offset from a whole integer, as that's where the pixel center is on modern GPUs. Therefore, we want to always round the fragment coordinates down for bounding box calculations. This also renders the pixel center offset useless, as 0.5 vs ~0.5833333 makes no difference when rounding down.
Fixes softlocks in certain cutscenes of Paper Mario: TTYD and Super Paper Mario, caused (presumably) by rounding up to a coordinate outside the render area.
=> VideoCommon: Round bounding box coordinates down and remove pixel center offset

Source/Core/Common/ArmCPUDetect.cpp, Source/Core/Common/ArmFPURoundMode.cpp, Source/Core/Common/CPUDetect.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
See the added code comment for details. Fixes Pokémon Battle Revolution not progressing past the title screen.
=> JitArm64: Make fcmpX with flush-to-zero enabled less bad

Source/Core/Common/FileUtil.cpp
This is needed otherwise the config won't be saved (except GCKEYBOARD which seems to be handled elsewhere, but it doesn't hurt to add it here anyways). Only affected Linux, somehow Windows saves just fine. Must be a different code path somewhere.
=> Common/FileUtil: Add some missing configs to D_CONFIG_IDX

Source/Core/Core/PowerPC/Interpreter/Interpreter_FPUtils.h, Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
Thought my efforts to improve cross-architecture netplay sync would only involve making JitArm64 more accurate? Nope! It's time to make Jit64 more accurate now. (And the interpreter too, as a bonus.)
=> Interpreter/Jit64: Emulate FMA accurately in more cases

Source/Core/Core/PowerPC/Jit64/Jit.h, Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Fixes https://bugs.dolphin-emu.org/issues/12526.
=> Jits: Fix accidentally setting GT in CR when clearing EQ

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
`srwx` would like to be able to assume that the top 32 bits are zero, and `cmpl` is already doing so.
=> JitArm64: Discard top 32 bits in slwx result

Source/Core/Core/NetPlayProto.h
Fixes severe slowdown in affected titles (such as Rocket Power: Beach Bandits) when played in NetPlay.
=> NetPlay: Sync the EFB access tile size as an integer instead of a boolean.

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Fixes Need for Speed: Carbon accessing invalid memory when branch following and BLR optimization are enabled simultaneously.
=> JitArm64: Fix clobbering LR in FakeLKExit

Source/Core/Core/ConfigManager.h, Source/Core/DolphinQt/CheatsManager.cpp, Source/Core/DolphinQt/CheatsManager.h, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.h, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.h, Source/Core/DolphinQt/Config/PropertiesDialog.cpp, Source/Core/DolphinQt/MainWindow.cpp
While this does not fix the core issue, this does eliminate a big part of the lag you get after holding the Frame Advance button for a while -- enough for it to become unnoticeable on my system, but I suspect weaker systems might still run into it, though to a lesser degree.
=> CheatsManager: Avoid recreating child widgets on every OnStateChanged(), and take running game info directly from SConfig.

Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp, Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPProto.h
- Reworked the DSU to never hang the Host thread for more than a really small time (e.g. when disabling DSU its thread now closes almost immediately)
- Fix DSU using a different UID for every controller of the same server (that's not how its supposed to work)
- Add battery level input
- Improve robustness when a large amount of devices are connected
- Make sure inputs start from their resting pose instead of 0
- Add devices disconnection detection, previously they'd stay there forever until manually refreshed
Deeply tested with one and multiple controllers.
More improvements will be coming after this, including touch pad calibration and touch pad relative input (mapped 1:1 to the window screen, for the wii mote cursor).
=> DSU improvements

Source/Core/DolphinQt/GameList/GameList.cpp
Makes Gamelist's grid mode ZoomIn keybind behave as expected. Fixes https://bugs.dolphin-emu.org/issues/12538.
From the included comment:
On most keyboards the key to the left of the primary delete key represents 'plus' when shift is held and 'equal' when it isn't. By common convention, pressing control and that key is treated treated conceptually as 'control plus' (which is then interpreted as an appropriate zooming action) instead of the technically correct 'control equal'. Qt doesn't account for this convention so an alternate shortcut is needed to avoid counterintuitive behavior.
The above correction introduces a different inconsistency: now zooming in can be done using conceptual 'control plus' or 'control shift plus', while zooming out can only be done using 'control minus'. Adding …
=> GameList: Fix grid mode zoom keybind inconsistency

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java
`progressMessage` can have the invalid value of 0. That `progressMessage` was being used for the thread name was a typo anyway – it's supposed to use `progressTitle`.
=> Android: Fix WAD import crashing

Source/Core/DolphinQt/Host.cpp
When rendering to main and going full screen, we aren't using the main window handle as the code assumed, but the other, detached, render widget.
Fixes issue:
https://bugs.dolphin-emu.org/issues/12540
caused by https://github.com/dolphin-emu/dolphin/pull/9697
=> Fix input focus checks being wrong (issue 12540)

Source/Core/VideoBackends/Vulkan/ShaderCompiler.cpp
It seems that we were writing values from helper invocations, which produces wrong results.
Here's a hardware test to demonstrate the wrong results and the fix: https://qimg.techjargaming.com/f/Tzx3VrV2.7z
Hardware
Vulkan (Broken)
Vulkan (Fixed)
=> Vulkan: Fix subgroup reduction

Source/Core/VideoBackends/OGL/OGLRender.cpp, Source/Core/VideoCommon/PixelShaderGen.cpp
Running the min/max operation on the upside down, quad-rounded pixel coordinates before inverting them to the standard upper-left origin produces wrong results. Therefore, we need to do the inversion before rounding to pixel quads.
I have included results from a hardware test to confirm that this is correct. The hardware can be downloaded here: https://qimg.techjargaming.com/f/Tzx3VrV2.7z
Hardware
Before Change
After Change
=> VideoCommon: Perform OpenGL bounding box inversion in pixel shader

Source/Core/InputCommon/InputConfig.cpp
Also fixes this bug: At the moment, Qt does not support a controller not having any default device, so it will still show the first device from the devices list as default, but internally it won't actually be selected, so input detection won't work as expected, until the user manually changes the device from the drop down list.
Also added a check to avoid potential crashes if we had no controllers. That function is only called on the first start up so there is no need to set the default device on the controller unless the default device string is valid. There is also no need to update references as all bindings would be empty. 
This will work even better when other parts of my input improvements from https://github.com/dolphin-emu/dolphin/pull/9489 are merged.
=> Fix controllers after the first one not defaulting to the default device

Source/Core/VideoCommon/PixelShaderGen.cpp
At higher resolutions, our bounding box dimensions end up being slightly larger than original hardware in some cases. This is not necessarily wrong, it's just an artifact of rendering at a higher resolution, due to bringing out detail that wouldn't have appeared on original hardware. It causes a texel to fall partially on what would have been a single pixel at native resolution, resulting in the coordinates getting bumped up to the next valid value. In many cases, these slightly larger bounding boxes are perfectly fine, as games don't hard-code expected dimensions. It is problematic in Paper Mario TTYD though, for a somewhat complicated reason.
Paper Mario TTYD frequently uses EFB copies to pre-render a bunch of animation frames for a character sprite (especially in Chapter 2), so that it …
=> VideoCommon: Only include centered pixels in bounding box

Source/Core/DolphinQt/Settings.cpp
This often happens when changing certain settings and starting/stopping a game and it's just a waste.
I'm not even sure how safe it is to not call "OnConfigChanged()" inline when editing settings from the Qt UI with a cursor, given that a lot of widgets states are refreshed within that callback. But I guess a user couldn't interact with two widgets before Qt had actually run its next update and called that queued callback.
=> Qt: avoid queuing ConfigChanged() more than once

Source/Core/DolphinQt/Settings/AudioPane.cpp, Source/Core/DolphinQt/Settings/AudioPane.h
Fixes AudioPane's layout to prevent it from vertically stretching to fill the window, which looks bad and was inconsistent with the other panes.
Before:
After:
=> AudioPane: Remove main layout vertical stretching

Source/Core/Common/MsgHandler.cpp
I guess at some point they were inadvertently swapped and because of the contents of some of the messages displayed with those captions, the issue went unnoticed. For instance, `PanicYesNo` would be used with a question, so it makes sense that it would be captioned "Question" even though the code asks for "Warning".
Also, simply refer to `GetStringT` for marking the captions as it does the same thing but is easier to read at a glance.
=> MsgHandler: Correct question and warning captions

Source/Core/VideoCommon/PixelShaderGen.cpp
This fixes bounding box shaders failing to compile under Vulkan, due to differences between GLSL and HLSL in the return value of vector comparisons and what types these functions accept. I included all() for the sake of completeness.
=> VideoCommon: Define scalar any() and all() functions in GLSL

Source/Core/Common/ArmFPURoundMode.cpp, Source/Core/Common/FPURoundMode.h, Source/Core/Common/GenericFPURoundMode.cpp, Source/Core/Common/x64FPURoundMode.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/HW/CPU.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp, Source/Core/Core/PowerPC/PowerPC.cpp, Source/Core/Core/PowerPC/PowerPC.h
Not doing this can cause desyncs when TASing. (I don't know how common such desyncs would be, though. For games that don't change rounding modes, they shouldn't be a problem.)
=> PowerPC: Set host CPU rounding mode on init and savestate

Source/Core/Common/Config/Config.cpp, Source/Core/Common/Config/Enums.h, Source/Core/Core/CMakeLists.txt, Source/Core/Core/Config/SessionSettings.cpp, Source/Core/Core/Config/SessionSettings.h, Source/Core/Core/ConfigLoaders/BaseConfigLoader.cpp, Source/Core/Core/ConfigLoaders/GameConfigLoader.cpp, Source/Core/Core/ConfigLoaders/MovieConfigLoader.cpp, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/Movie.h, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/NetPlayServer.h, Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp, Source/Core/DolphinLib.props
When I added the software FMA path in 2c38d64 and made us use it when determinism is enabled, I was assuming that either the performance impact of software FMA wouldn't be too large or CPUs that were too old to have FMA instructions were too slow to run Dolphin well anyway. This was wrong. To give an example, the netplay performance went from 60 FPS to 30 FPS in one case.
This change makes netplay clients negotiate whether FMA should be used. If all clients use an x64 CPU that supports FMA, or AArch64, then FMA is enabled, and otherwise FMA is disabled. In other words, we sacrifice accuracy if needed to avoid massive slowdown, but not otherwise. When not using netplay, whether to enable FMA is simply based on whether the host CPU supports it.
The only remaining case where the software FMA …
=> NetPlay/Jit64: Avoid using software FMA

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFileCache.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java, Source/Android/jni/GameList/GameFileCache.cpp, Source/Core/UICommon/GameFileCache.cpp, Source/Core/UICommon/GameFileCache.h
Back when I wrote this code, I believe I set it to use a custom path so that the cache would end up in a directory which Android considers to be a cache directory. But nowadays the directory which Dolphin's C++ code considers to be the cache directory is such a directory, so there's no longer any reason to override the default path.
=> Android: Stop using custom path for GameFileCache

Source/Core/Core/HW/AudioInterface.cpp
`AIDFR` was initialised with the value 0 (`AID_48KHz`) which doesn't match what it does a [few lines below](https://github.com/dolphin-emu/dolphin/blob/eaf8e3000894a95d96a5ee8f27f3203cab0c2eaf/Source/Core/Core/HW/AudioInterface.cpp#L154):
```C++
s_aid_sample_rate = Get32KHzSampleRate();
```
This fixes libogc `AUDIO_Init` function taking the [AI_SAMPLERATE_48KHZ route](https://github.com/devkitPro/libogc/blob/bc4b778d558915aa40676e33514c4c9ba2af66b8/libogc/audio.c#L254) on Dolphin while it doesn't on real hardware.
It doesn't seem to fix what I was looking for, except the timing of some of my hardware tests.
=> AudioInterface: Fix AIDFR initialization

Source/Core/VideoBackends/OGL/OGLRender.cpp
The current warning is confusing to users as performance may be fine despite the warning. Many users also do not understand the device vendor sentence and the attempt at shaming vendors into supporting the feature clearly hasn't worked at this point so let's just get rid of it.
=> Update buffer_storage warning message

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/Config/SessionSettings.cpp, Source/Core/Core/Config/SessionSettings.h, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/HW/EXI/EXI_DeviceIPL.cpp, Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/PatchEngine.cpp
This moves some settings that are only used during a NetPlay session to the Session config, so there's no possibility of them being permanently set by accident.
=> Move some NetPlay-specific settings to SessionSettings

Data/Sys/GameSettings/GDK.ini, Data/Sys/GameSettings/GDQ.ini, Data/Sys/GameSettings/GDX.ini, Data/Sys/GameSettings/GPXJ01.ini, Data/Sys/GameSettings/GWL.ini, Data/Sys/GameSettings/GWT.ini, Source/Core/Core/HW/EXI/EXI.cpp, Source/Core/Core/HW/EXI/EXI_DeviceMemoryCard.cpp, Source/Core/Core/HW/GCMemcard/GCMemcard.cpp, Source/Core/Core/HW/GCMemcard/GCMemcard.h, Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp
This allows for a broader range of game-specific memory card sizes to be configured. Needed for Japanese version of Pokémon Box: Ruby & Sapphire, as that game requires a 59 block memory card.
Fixes https://bugs.dolphin-emu.org/issues/12185
The value follows a power of two scale, with 4 Mbit (59 blocks) as the base, so the sizes are as follows:
0 = 4 Mbit (59 blocks)
1 = 8 Mbit (123 blocks)
2 = 16 Mbit (251 blocks)
3 = 32 Mbit (507 blocks)
4 = 64 Mbit (1019 blocks)
Any value outside this range of 0-4 is simply ignored. 5 is technically valid, but we don't handle it specially as it would just be the default/maximum memory card size of 128 Mbit (2043 blocks).
=> Replace MemoryCard251 setting with generic MemoryCardSize

Source/Core/DiscIO/VolumeVerifier.cpp
To avoid problems, Dolphin currently enforces a 512 MB size limit to the emulated Wii NAND. Since this can be rather small (especially if you have a lot of Virtual Console or WiiWare titles), the Wii System Menu 4.0+ ability to move channels to the SD Card is extremely helpful, especially when you can create virtual SD Cards as big as 32 GB and have them working without issues with Dolphin.
While moving titles to the virtual SD Card, I stumbled upon a few that would behave oddly: Dolphin could successfully launch them if booted directly from the WAD, as well as if booted from inside the Wii System Menu while they were stored on the NAND. From the data management screen, System Menu would also successfully copy or move those channels to the SD Card without errors. However, the transfer was …
=> VolumeVerifier: increase problem severity for incorrectly signed TMDs

Source/Core/Core/HW/AudioInterface.cpp
I'm not sure what the previous default was, it doesn't seem to be anything sensible. I can trace it back to literally the first commit in the git but I haven't found an explanation for it.
Re-fixes the Naruto games after #9788.
=> AudioInterface: Initialize s_cpu_cycles_per_sample to a sane value.

Source/Core/Core/Core.cpp
Fixes a regression from [5.0-12066](https://dolphin-emu.org/download/dev/a660033e8c394634a22c02a031969685fcdb4fba/), where setting the GFXBackend variable to a backend other than the current global one would crash Dolphin upon launching that game.
Fixes [https://bugs.dolphin-emu.org/issues/12529](https://bugs.dolphin-emu.org/issues/12529)
=> GameINI: Fix GFXBackend crash

Source/Core/Common/ArmCPUDetect.cpp
Without this, the code added in PR #9804 misbehaves and considers AArch64 netplay clients to not have hardware FMA support, telling all clients to disable FMA support, which causes a desync between x64 and AArch64 due to JitArm64 not being able to disable FMA support. (The ability for JitArm64 to do so is added in PR #9815, but I thought I would submit this fix separately since that PR likely will take longer to review.)
=> Common: Set bFMA to true for AArch64

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
These optimizations were already present, but only when d == a. They also make sense when this condition does not hold.
---
<details><summary>imm == 0</summary>
Before:
```
41 BB 00 00 00 00    mov         r11d,0
45 2B DF             sub         r11d,r15d
```
After:
```
45 8B DF             mov         r11d,r15d
41 F7 DB             neg         r11d
```
</details>
<details><summary>imm == -1</summary>
Before:
```
41 BD FF FF FF FF    mov         r13d,0FFFFFFFFh
44 2B EE             sub         r13d,esi
0F 93 45 68          setae       byte ptr [rbp+68h]
```
After:
```
44 8B EE             mov         r13d,esi
41 F7 D5             not         r13d
C6 45 68 01          mov         byte ptr [rbp+68h],1
```
</details>
=> Jit64: subfic - Optimize constants for d != a

Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
I missed this one in PR #9819.
=> JitArm64: Use SBC/SBCS for emulating subfzex

Source/Core/VideoCommon/HiresTextures.cpp, Source/Core/VideoCommon/TextureInfo.cpp, Source/Core/VideoCommon/TextureInfo.h
Splits out the texture hash from the rest of the texture name generation, so that it can be "wildcard"'d out of the texture name.
Additionally, have exact texture matches take precedent over wildcard matches.  This is _technically_ a breaking change in that it could effect existing texture packs if they had both a wildcard and an exact match texture in the pack.  However, I imagine most packs aren't doing this because it'd be wasted space.
Should resolve [12505](https://bugs.dolphin-emu.org/issues/12505)
=> VideoCommon: enhance wildcard support in hi res texture lookup

Data/Sys/GameSettings/GLSE64.ini
This game can deadlock the CPU and GPU by setting FIFO breakpoints too infrequently, provided the CPU gets too far ahead, as can happen under Dolphin due to timing inaccuracies. The game never clears breakpoints, and it will skip setting them if the previous one has not been hit by the GPU. If the CPU gets far enough ahead it will reach the FIFO high water mark and trigger an overflow interrupt, causing the render thread to be suspended. The GPU will make forward progress until it hits the last set breakpoint. However, if the distance between that breakpoint and the FIFO write pointer is greater than the low water mark, then the GPU will never generate an underflow interrupt and the render thread will never be resumed. This patch forces the game to update the breakpoint unconditionally …
=> GameSettings: Patch for freezing in Gladius (GLSE64)

Source/Android/app/src/main/AndroidManifest.xml, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GamePropertiesDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/HomeScreenChannel.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SyncChannelJobService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SyncProgramsJobService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/Platform.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/AppLinkHelper.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/TvUtil.java, Source/Android/app/src/main/res/values/strings.xml
These would lead to problems if we ever add translation support.
=> Android: Clean up some hardcoded strings

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_GCAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java, Source/Android/app/src/main/res/values/strings.xml
The app context (which can be obtained though `DolphinApplication.getAppContext()`) should work just as well as an activity context.
Also moving a hardcoded string to strings.xml.
=> Android: Don't use getEmulationActivity in GCAdapter/Wiimote code

Source/Core/VideoCommon/TextureInfo.cpp
Even address needs to be offset to the first mipmap entry.
Fixes https://bugs.dolphin-emu.org/issues/12556
=> VideoCommon/TextureInfo: Fix mipmap loading from tmem

Source/Core/VideoBackends/Software/TransformUnit.cpp
The sourcerow asserts were removed for the hardware renderer in #3684, which was hardware tested.  Currently [ssbm-mod-lloyd](https://fifo.ci/dff/ssbb-mod-lloyd/) fails the `texinfo.sourcerow == SourceRow::Colors` assertion (sourcerow is set to Tex1).
There never was an equivalent for the input form asserts in the hardware renderer (I looked at [VertexShaderGen](https://github.com/dolphin-emu/dolphin/blob/9b16c360145e067172e6e6bbe5748f041c251f10/Source/Core/VideoCommon/Src/VertexShaderGen.cpp) as of 9b16c360145e067172e6e6bbe5748f041c251f10 and it didn't exist then).  As far as I can tell, nothing hits them (including the Lloyd test), but it does seem suspicious that the z-component is set to 1.0f with the assumption that AB11 is used.  I've left the assert since there's a chance that some …
=> Software: Remove texinfo.sourcerow == SourceRow::Colors assert

Source/Core/VideoBackends/Software/SWRenderer.cpp, Source/Core/VideoBackends/Software/SWRenderer.h
`MAX_XFB_WIDTH`/`HEIGHT` are the largest XFB sizes seen in practice, but do not make sense to use for the backbuffer size, which should be the size of the window.  The old code created screenshots with a size of 720x540 on NTSC games when "Dump Frames at Internal Resolution" is unchecked; now, the window size is used.  See [bug 12519](https://bugs.dolphin-emu.org/issues/12519) (though note that this does not entirely fix that).
With "Auto-Adjust Window Size" checked, screenshots of Super Mario Sunshine's title screen are now 640 by 480 with or without "Dump Frames at Internal Resolution" checked.  With "Dump Frames at Internal Resolution" unchecked, resizing the window results in the screenshot being saved at a 4:3 aspect ratio based on the window's height (the software renderer itself …
=> Software: Fix bad backbuffer size

Source/Core/VideoCommon/Fifo.cpp
This fixes https://bugs.dolphin-emu.org/issues/12558 for reasons that I don't fully understand myself.
Well okay, that's not true. I understand why this fix works. I don't understand why this issue happens in the first place.
Basically we're moving a `mov rdi,qword ptr [SConfig::m_Instance]` out of the GPU loop and instead pass the value as a parameter to the lambda. This avoids a memory load of `SConfig::m_Instance` each loop which is the cause of the slowdown... well, sort of.
See, this issue only happens on a current MSVC and only in specific circumstances. I'm not fully confident in this, but basically, there appears to be some [false sharing](https://en.wikipedia.org/wiki/False_sharing) or *something* like that between the `SConfig::m_Instance` and another thing. The second thing …
=> VideoCommon/Fifo: Move SConfig::GetInstance() outside the GPU loop.

Source/Core/VideoCommon/UberShaderPixel.cpp
This fixes NES game graphics when UberShaders are in use.
For performance reasons, ubershaders are supposed to skip some of the indirect texture logic when the indirect functionality isn't enabled, since an indirect configuration that's all zeros does nothing.  However, prior to e1d45e9ba66d3ba7d6769e36c0fc82ceb5028ecb (part of #9651), that wasn't actually done and it was only skipped when the indirect functionality referred to an indirect stage index that was greater than the number of enabled ones (despite there being a comment claiming it also could be disabled when set to zero).
Super Mario Bros. has 3 TEV stages and 2 indirect stages enabled, and uses indirect logic in TEV stage 1 (the indirect logic for TEV stages 0 and 2 are set to 0).  TEV stage 0 doesn't have any texture enabled, …
=> UberShaderPixel: always set tevcoord, even if the stage has no texture

BuildMacOSUniversalBinary.py, Source/UnitTests/Core/PowerPC/JitArm64/ConvertSingleDouble.cpp, Source/UnitTests/Core/PowerPC/JitArm64/FPRF.cpp, Source/UnitTests/Core/PowerPC/JitArm64/Fres.cpp, Source/UnitTests/Core/PowerPC/JitArm64/Frsqrte.cpp, Source/UnitTests/Core/PowerPC/JitArm64/MovI2R.cpp
This change adds support for unit testing to the universal binary build script through a new `--run_unit_tests` command line option. When this is specified, unit testing is performed for both the x86 and ARM64 slices that are built. 
It also fixes the PowerPC unit tests that were segfaulting on M1 silicon because they were not wrapping their code gen for W^X execution.
=> Apple M1: Add support for running unit tests on universal builds

Source/Core/Core/HW/AudioInterface.cpp
This PR fixes the sample counter being incremented even when it's not playing.
Confirmed with this hardware test: [wii-audio-samples.zip](https://github.com/dolphin-emu/dolphin/files/6681093/wii-audio-samples.zip).
> ## HWTEST - Sample Counter
>
> ### PSTAT = 0
> Counter = 2
> Counter = 2
> Counter = 2
> Counter = 2
> Counter = 2
>
> ### PSTAT = 1
> Counter = 49
> Counter = 64058
> Counter = 128112
> Counter = 192166
> Counter = 256215
It doesn't seem to affect the games I have.
=> AudioInterface: Fix sample counter

Source/Core/Core/MemoryWatcher.cpp
MemoryWatcher.cpp is missing the cstring include for strncpy.
On some platforms the missing header is included implicitly, but on musl we'll have to include cstring to build dolphin successfully.
```
./Source/Core/Core/MemoryWatcher.cpp: In member function 'bool MemoryWatcher::OpenSocket(const string&)':
./Source/Core/Core/MemoryWatcher.cpp:63:3: error: 'strncpy' was not declared in this scope
63 |   strncpy(m_addr.sun_path, path.c_str(), sizeof(m_addr.sun_path) - 1);
|   ^~~~~~~
./Source/Core/Core/MemoryWatcher.cpp:14:1: note: 'strncpy' is defined in header '<cstring>'; did you forget to '#include <cstring '?
13 | #include "Core/PowerPC/MMU.h"
+++ |+#include <cstring>
14 |
```
=> Fix includes for musl libc

Data/Sys/GameSettings/GKB.ini
This fixes crashes when attempting to shop with certain items in your inventory.  This can be observed with the picture of kalas found on this savefile.  Simply load the savefile and go to the building on the far left of the second screen.
[AF-GKBE-BKData-000.zip](https://github.com/dolphin-emu/dolphin/files/6705413/AF-GKBE-BKData-000.zip)
Dualcore, shortly before crashing.
Single Core
=> GameINI:  Enable Single Core for Baten Kaitos: Eternal Wings and the Lost Ocean

Source/Core/Core/HW/MMIO.cpp, Source/Core/Core/HW/MMIOHandlers.h
This PR moves MMIOHandlers method definitions to MMIO.cpp.
It prevents some compilation issues when editing the header file.
=> MMIOHandlers: Move method definitions to MMIO.cpp

Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp
The masking logic can be eliminated when the mask is known to be all ones. This case is very common.
In fact, it's so common that I haven't been able to find instances of this instruction where this did not apply. Similar optimizations could be done for `mask == 0`, but, well, do games actually do this?
---
<details><summary>Example</summary>
Before:
```
66 48 0F 7E F0       movq        rax,xmm6
8B 55 5C             mov         edx,dword ptr [rbp+5Ch]
83 E0 FF             and         eax,0FFFFFFFFh
83 E2 00             and         edx,0
0B C2                or          eax,edx
89 45 5C             mov         dword ptr [rbp+5Ch],eax
48 8D 15 C3 3C FE 01 lea         rdx,[19520020h]
83 E0 07             and         eax,7
0F AE 14 82          ldmxcsr     dword ptr [rdx+rax*4]
```
After:
``` …
```
=> Jit64: mtfsfx - Optimized masking

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
In the description of https://github.com/dolphin-emu/hwtests/pull/41, I said that it uncovered two issues in Dolphin... But after I wrote that, it actually uncovered a third issue which only happens when not using SSE4.1. Here's the fix for that issue.
=> Jit64: Fix FPRF non-SSE4.1 handling of negative zero

Source/Core/Core/PowerPC/Gekko.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp, Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
fcmpX only updates the FPCC bits, not the C bit. This was already correctly implemented in the interpreter.
Not known to affect any games, but affects https://github.com/dolphin-emu/hwtests/pull/41.
=> Jits: Fix fcmpX FPRF mask

Source/Core/Core/PowerPC/ConditionRegister.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp, Source/Core/Core/PowerPC/Jit64/Jit_SystemRegisters.cpp, Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Spacing the LT and SO bits like in the native PowerPC format makes it easier to convert to that format (see mfcr).
=> PowerPC: move SO bit to a more convenient location

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
This doesn't really add any new optimizations, but fixes an issue that prevented the optimizations introduced in #8551 and #8755 from being applied in specific cases. A similar issue was solved for subfx as part of #9425.
Consider the case where the destination register is also an input register and happens to hold an immediate value. This results in a set of constraints that forces the RegCache to allocate a register and move the immediate value into it for us. By the time we check for immediate values in the JIT, we're too late.
We solve this by refactoring the code in such a way that we can check for immediates before involving the RegCache.
---
<details><summary>Example 1</summary>
Before:
```
41 BF 00 68 00 CC    mov         r15d,0CC006800h
44 03 FF             add         r15d,edi …
```
=> Jit64: addx revisited

Source/Core/Common/x64Emitter.cpp, Source/Core/Common/x64Emitter.h, Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp, Source/UnitTests/Common/x64EmitterTest.cpp
The x87 instructions haven't been used outside of unit tests since 2795376b61371069ef2949eb31dbbddd7d9e209c and I doubt we'll find a new use.
=> x64Emitter: remove unused x87 instructions

Source/Core/Common/FloatUtils.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_FPUtils.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_Paired.cpp, Source/Core/Core/PowerPC/Jit64/Jit.h, Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp, Source/Core/Core/PowerPC/Jit64/Jit_Paired.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.h, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp, Source/Core/Core/PowerPC/PowerPC.cpp, Source/Core/Core/PowerPC/PowerPC.h, Source/UnitTests/Core/PowerPC/JitArm64/FPRF.cpp
We were classifying denormal singles as if they were normals (because we converted singles to doubles and then classified them using the same code as for doubles), but this behavior has been confirmed incorrect by https://github.com/dolphin-emu/hwtests/pull/41.
When fixing this, I went with an approach of performing classification on 32-bit floats in all CPU emulation cores (i.e. classification is performed after forcing the result to single but before converting it back to double). It would be possible to perform classification after converting to double, but that would require us to check if the exponent is in a certain range instead of just checking if it is zero, so I think the approach I went with is better.
=> Fix FPRF handling of denormal singles

Source/Core/Core/HW/DVD/DVDInterface.cpp
This broke ejecting Wii discs while the game is running, as the drive state was set to Ready even when no disc was present, but other code still reported the missing disc, which confused games as you can't be both ready to read and have no disc.  That would cause games to show an unrecoverable error screen, instead of a "please insert the game disc" screen.
This only affected Wii games; the GameCube games used regular disc reads which worked fine.
This issue was introduced in #8571.  Oops.  I only noticed it now when testing #9848.
Tested with a few different Wii games (Kirby's Dream Collection, NSMBW, Kirby's Epic Yarn), and also with some GameCube games (Paper Mario: TTYD, and the [GameCube Preview Disc](https://wiki.dolphin-emu.org/index.php?title=Nintendo_GameCube_Preview_Disc)).  I …
=> DVDInterface: Fix decrypting reads clearing the drive state

Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
While the third parameter of ANDI2R is u64, the upper half of it does not get read if we're emitting a 32-bit instruction (which we are doing here).
=> JitArm64: Fix MSVC warning '~': zero extending 'u32' to 'u64'

Source/Core/Core/HW/WiimoteReal/IOAndroid.h, Source/Core/Core/HW/WiimoteReal/IODummy.h, Source/Core/Core/HW/WiimoteReal/IOLinux.h, Source/Core/Core/HW/WiimoteReal/IOWin.h, Source/Core/Core/HW/WiimoteReal/IOdarwin.h, Source/Core/Core/HW/WiimoteReal/IOdarwin.mm, Source/Core/Core/HW/WiimoteReal/IOdarwin_private.h, Source/Core/Core/HW/WiimoteReal/IOhidapi.h, Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, Source/Core/Core/HW/WiimoteReal/WiimoteReal.h
* Minor clean up on `WiimoteScannerDarwin`.
* Moved `IOBluetoothHostController` initialization to the constructor.
* Used `defaultController` to get an instance of `IOBluetoothHostController` instead of creating one manually (`[[IOBluetoothHostController alloc] init]` is not mentioned anywhere in documentation, seems to work by coincidence).
* Removes a hack that only applies to old macOS SDKs.
* Fixes a potential issue where Wiimote scanning would continue even if `[IOBluetoothDeviceInquiry start]` returns an error.
* Fixes Dolphin hanging on quit if Continuous Scanning is enabled and no Wiimote was ever connected. ([#12424](https://bugs.dolphin-emu.org/issues/12424))
Tested on MBP 16" (2019), macOS Big Sur 11.4, Xcode 12.5. Continuous Scanning still works and I was able to play a game …
=> WiimoteScannerDarwin: fix hang on quit and clean up

Source/Core/Core/HW/DVD/DVDInterface.cpp
Intends to fix https://bugs.dolphin-emu.org/issues/12279. I have hardware tested the behavior, but I haven't tested the game.
=> DVDInterface: Don't evict cache block i unless block i + 2 was read

Source/Core/Core/HW/SI/SI.cpp
As far as I can tell there is no such thing as transfer cancelling, I don't know where that came from. This hasn't been an issue so far because Dolphin's transfer are instantaneous except for GBAs
This was confirmed on hardware with
```
printf("start csr %08X buf %08X%08X\n", *si_comcsr, si_buffer[0], si_buffer[1]);
si_buffer[0] = 0; *si_comcsr = 0x40010303;
printf("started csr %08X buf %08X%08X\n", *si_comcsr, si_buffer[0], si_buffer[1]);
*si_comcsr &= ~SICOMCSR_TSTART;
printf("cancelled csr %08X buf %08X%08X\n", *si_comcsr, si_buffer[0], si_buffer[1]);
while(*si_comcsr & SICOMCSR_TSTART);
printf("waited csr %08X buf %08X%08X\n", *si_comcsr, si_buffer[0], si_buffer[1]);
```
=> SI: Don't cancel transfer with TSTART=0

Source/Core/VideoCommon/PostProcessing.cpp
Those two floats were not used anyways and this mirrors how it's done for framebuffer resolution.
In post-processing shader use `GetInvWindowResolution()` to get reciprocal of window resolution.
=> Allow post-processing shaders to query reciprocal of window resolution

Source/Android/app/src/main/res/values/arrays.xml, Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
See https://github.com/dolphin-emu/dolphin/pull/8413#issuecomment-544006931
=> Change the names for shader compilation settings

Source/Core/Common/FileUtil.cpp, Source/Core/UICommon/AutoUpdate.cpp, Source/Core/UpdaterCommon/UpdaterCommon.cpp
Starting in macOS Sierra, if an app is downloaded from the Internet, the system may "translocate" an app's bundle to a read-only container elsewhere on the filesystem and execute it from there. This is done to protect against a trusted application's resources from being hijacked to load untrusted code. More information is available [here](https://objective-see.com/blog/blog_0x15.html) (with many thanks to Patrick Wardle).
Unfortunately, this has the side-effect of breaking the updater, as it'll attempt to find the updater app bundle from the read-only container. So, ``GetBundleDirectory()`` has been changed to "untranslocate" the app bundle's path if necessary. The APIs used to do this were briefly public in Xcode 8 beta 1, but they were [made private in a later …
=> macOS: Untranslocate the app bundle's path for the updater

Source/Core/UpdaterCommon/UpdaterCommon.cpp
Upon launching an app, macOS's kernel caches all code signatures from the main executable and any frameworks it uses.  When the updater notices a file needs to be updated, it uses ``File::Copy()``, which reads the contents of the new file and writes it over the contents of the old file. This operation does *not* invalidate the code signature cache. Therefore, when Dolphin is launched after the update operation is complete, the cached code signature is used to validate the new files. macOS then proceeds to kill Dolphin due to a code signing error.
The solution: Use Rename instead of Copy.
([Thanks to Quinn from the Apple Developer Forums for making a post about this quirk](https://developer.apple.com/forums/thread/130313?answerId=410704022#410704022).
Also, this PR only fixes one issue …
=> UpdaterCommon: Fix code signing error after updating on macOS

Source/Core/VideoCommon/CPMemory.h, Source/UnitTests/VideoCommon/VertexLoaderTest.cpp
Testing a fix for Debian unit test warning -Wclass-memaccess.
=> VertexLoaderTest: Fix memset assignment warning

Source/Core/Core/CMakeLists.txt, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayClient.h, Source/Core/Core/NetPlayCommon.cpp, Source/Core/Core/NetPlayCommon.h, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/NetPlayServer.h, Source/Core/DolphinLib.props
This moves some functions to a common place so that both sides can use them, which may be needed for future features. Also reduces the amount of code in the client and server a little bit. I also removed an unused struct, and renamed/restructured some things.
=> NetPlay: Refactor some functions into a common header

Source/Core/DiscIO/WIABlob.cpp, Source/Core/DiscIO/WIABlob.h
~The main reason I'm making this change is to avoid the ICE mentioned in https://github.com/dolphin-emu/dolphin/commit/e5b9e1ba1f7a8c7a48671f947cf096e0f4cb0fe9#r51445090, but there is also the advantage that~ this lets us reuse blocks in the case where different partition entries use the same key (which probably isn't actually all that common).
=> DiscIO: Store partition key directly in ReuseID

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SyncChannelJobService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SyncProgramsJobService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/TvUtil.java
This partially reverts commit cbc4989095baff7b84694802bb195c0c79d56ebe of PR #9835 due to a crash: https://bugs.dolphin-emu.org/issues/12561
I can't debug what the cause of the crash is due to not having an Android TV device. Let's just revert this for now to fix the crash.
=> Partially revert "Android: Clean up some hardcoded strings"

Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
Split out from PR #9865, since I don't think that PR is going to be merged any time soon.
Unlike most constants we emit in JitArm64, these constants are **not** inherent to the CPU we're emulating, and can have whatever  values we want, so let's handle them in a more robust way. I was rather confused when I found out that a previous iteration of PR #9865 broke JitArm64, because I hadn't thought that making some simple changes to the values of an enum would do it!
=> JitArm64: Don't hardcode exception constants

Source/Core/Common/MathUtil.h
Mostly everything else in MathUtil was already marked as constexpr
and the only function IntLog2 calls (CountLeadingZeros) is already constexpr.
=> MathUtil: Mark IntLog2 as constexpr

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
Fixes a PR #9866 regression. (The `EXCEPTION_EXTERNAL_INT` immediate being wrong meant that we never took the branch, masking the problem of the `MSR.EE` immediate being wrong...)
=> JitArm64: Check MSR.EE for external exceptions, not MSR.FE0

Source/Core/Core/FreeLookManager.cpp, Source/Core/Core/HW/WiimoteEmu/WiimoteEmu.cpp
Dolphin currently uses `Click 0`, `Click 1`, and `Click 2` as the default expressions for A, B and Shake. While this was correct for the (now removed) mouse support in the IOKit ciface, it is no longer true for the Quartz ciface, which defines these buttons as `Left Click`, `Right Click`, and `Middle Click`.
Fixes A, B, and Shake not being mapped to left, right, and middle click as intended when loading defaults on macOS.
=> Core: Use proper names for left, right, and middle click on Quartz ciface

Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/MMU.h
Alright, let's give this another shot. I'll summarize here, but if you want the previous attempts, see #6913, #8310, #8682, and sorta #9361.
Basically, our Cheat Search has a big problem where your search results may break (usually completely disappear, but sometimes other weird stuff if you do comparisons with 0) because the code calling the `HostRead_*()` functions cannot differentiate between them returning 0 because the actual value at that memory address is zero, or returning 0 because the address translation failed (eg. because the CPU is currently in an exception state).
To help with this, I've added new `Try` variants of the HostRead and HostWrite functions that allow specifying the expected address space of the given address and return whether the read or write succeeded or not.
=> Core/MMU: Add HostTryRead/HostTryWrite functions to allow specifying the desired address space, and return whether it succeeded.

Source/Core/Core/HW/WII_IPC.cpp, Source/Core/Core/IOS/DI/DI.cpp
This PR implements resetting DI via [HW_RESETS](https://github.com/Pokechu22/dolphin/pull/new/di-hw-resets).  This is mainly used for Wii homebrew that bypasses IOS (for instance, CleanRip now runs correctly in Dolphin, in case you want to copy dumped files in a slow, inconvenient way), but I also changed the implementation of IOS's [DVDLowReset](https://wiibrew.org/wiki//dev/di#0x8A_DVDLowReset) to use the MMIOs directly.  This also meant I needed to implement the starlet [GPIOs](https://wiibrew.org/wiki/Hardware/Hollywood_GPIOs), which Wiibrew says use the same backing value as the broadway-accessible ones; I haven't done any hardware testing on that recently, but my implementation at least seems to work.
=> Implement resetting DI via HW_RESETS

Source/Core/Common/Arm64Emitter.cpp
We haven't actually used 64-bit TBZ/TBNZ anywhere in Dolphin, so this mistake hasn't broken anything, but let's fix it regardless.
=> Arm64Emitter: Fix 64-bit TBZ/TBNZ encoding

Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
In cases where we already know that there is an exception, either because we just checked for it or because we were the ones that generated the exception to begin with, we can skip the branch inside WriteExceptionExit.
=> JitArm64: Add the ability to emit an unconditional exception exit

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
If we already have to use a GPR, we might as well take advantage of the nice immediate encodings provided by GPR ORR. This is faster, smaller, and saves a register.
=> JitArm64: Improve fctiwzx constant generation in double case

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
Some of the code used when the carry flag is known to be a constant value is really not much better than just setting the carry flag and then using the normal code, and with how rarely this code runs, it isn't well tested either. Might as well get rid of some of this code and simplify things.
=> JitArm64: Simplify addex/subfex

Source/Core/Core/PowerPC/MMU.cpp
My bad. Untested, but this should fix https://bugs.dolphin-emu.org/issues/12571
Compare with previous code: https://github.com/dolphin-emu/dolphin/commit/b59fcae70abd7bd14d0a87aef9f07cd2481f905c#diff-4e481906f161c6ca9062f7b02499e2eca16f00bab97f94bb44ab8bb292c47385L699-R832
https://github.com/dolphin-emu/dolphin/blob/954f27c5d7289b2b806d0fb94dd105edaa1bb4be/Source/Core/Core/PowerPC/MMU.cpp#L698-L699
https://github.com/dolphin-emu/dolphin/blob/b59fcae70abd7bd14d0a87aef9f07cd2481f905c/Source/Core/Core/PowerPC/MMU.cpp#L830-L832
=> Core/MMU: Fix inverted condition in HostIsInstructionRAMAddress().

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
Passing a width of 64 and registers encoded as double to DUP resulted in an invalid instruction. The registers should be encoded as quads in this situation.
Fixes https://bugs.dolphin-emu.org/issues/12575.
=> JitArm64: Fix ps_cmpXX

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Common/BitUtils.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitAsm.cpp, Source/Core/VideoCommon/VertexLoaderARM64.cpp
Manually encoding and decoding logical immediates is error-prone. Using ORRI2R and friends lets us avoid doing the work manually, but in exchange, there is a runtime performance penalty. It's probably rather small, but still, it would be nice if we could let the compiler do the work at compile-time. And that's exactly what this pull request does, so now I have no excuse for trying to manually write logical immediates anymore.
=> JitArm64: Encode logical immediates at compile-time where possible

Source/Core/VideoBackends/Software/Tev.cpp, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/UberShaderPixel.cpp
This affects the skyward sword map.  As mentioned in [issue 9070](https://bugs.dolphin-emu.org/issues/9070#note-11), this regressed in #68 (tev_fixes_new), specifically in 3ea97f77301d57f7ffddefb45f7e34ca926d5098.  It turns out that this commit swapped the shifts used for "bump alpha" and the indirect offset; [per libogc](https://github.com/devkitPro/libogc/blob/bd24a9b3f59502f9b30d6bac0ae35fc485045f78/gc/ogc/gx.h#L790-L800), the indirect offsets are the high bits and the bump alpha comes from the low bits.  (This is further confounded by bump alpha [being only 5 bits](https://github.com/devkitPro/libogc/blob/bd24a9b3f59502f9b30d6bac0ae35fc485045f78/gc/ogc/gx.h#L3038-L3041); in the most common ITF_8 case where bump alpha and the indirect offset are both from the same value, it seems like …
=> Fix indirect textures when format is not ITF_8

Source/Core/VideoCommon/BPMemory.h, Source/Core/VideoCommon/BPStructs.cpp
This PR replaces #9861; from that:
> This fixes the appearance of Zora eyes (and bodies) in Twilight Princess; see [bug 10346](https://bugs.dolphin-emu.org/issues/10346).  This originally regressed in #68, and I bisected the issue to cff952c397833873055e42a85b76ff8a621a0792 (though shaders from that commit will not run unless line 707 is changed by replacing `int2(round(dot(...), dot(...)))` with `int2(round(dot(...)), round(dot(...)))`).
However, this version should avoid introducing regressions.  I semi-hardware tested it and the behavior seems to be that the top bit of the scale factor is ignored, i.e. supplying a scale value of 47 is the same as supplying one of 15, resulting in a scale factor of 2^(15-17) = 2^(-2).  Specifically, I tested it with the Super Mario Bros. fifolog using …
=> Ignore the top bit of the indirect texture matrix scale

Source/Core/VideoCommon/VertexLoaderBase.cpp
On x86/ARM `Common/Assert.h` is included by way of
`VideoCommon/VertexLoader{X64,ARM64}.h`, on other platforms it is missing.
Commit is based on the breaking commit (daggy fix), not sure this is appreciated, considering Dolphin doesn't have maintenance branches to merge this into … `Contributing.md` doesn't say anything about it (and neither about commit naming). (*Update:* rebased onto master after advice on IRC)
=> VideoCommon: fix generic build

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/VideoCommon/VertexLoaderARM64.cpp
=> JitArm64: Stop using hand-encoded logical immediates

Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
Putting AX functions from AXVoice.h in an anonymous namespace does
successfully prevent compilers from merging those functions and
allows us to avoid ODR violations.
However, tools such as gdb still mix up AX GC and AX Wii functions
and variables because those have the exact same symbol names.
This can be fixed by using inline namespaces which are transparent
at the source code level but forces AX GC and AX Wii symbols to be
different.
=> DSPHLE: Prevent AX GC and AX Wii symbol mixups

Source/Core/Common/GL/GLInterface/AGL.h, Source/Core/Common/GL/GLInterface/AGL.mm, Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.h, Source/Core/InputCommon/ControllerInterface/Quartz/QuartzKeyboardAndMouse.mm
Just a minor cleanup that makes debugging in Xcode a better experience.
Some APIs must only be called from the main thread. The fact that these APIs were called from other threads and still worked without crashing / bugs is a coincidence. (The AGL GLInterface has apparently already been affected by this before, and was mostly fixed in #8544.)
Also, I define ``GL_SILENCE_DEPRECATION`` in all files that use the AppKit OpenGL APIs. This silences all warnings that say "OpenGL is deprecated, use Metal" when an OpenGL-related API is accessed. I think we all know that by now.
=> macOS: Move UI API calls to the main thread

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
It is enabled by default.
Untested.
This should unbreak input in Super Mario Galaxy.
It will also re-break gestures in "Jett Rocket" and "Sonic and the Secret Rings".
Game INIs should be updated.
=> Config: Add an ini setting to control real Wii Remote report duplication.

Source/Core/DolphinQt/Config/Graphics/GeneralWidget.cpp
Use a BalloonTip to inform the user when their selected backend (OpenGL or Null) doesn't support adapters, instead of using the default tooltips.
Before:
After:
Using a backend that supports adapters (unchanged by this PR):
=> GeneralWidget: Convert Adapter tooltip to BalloonTip

Data/Sys/GameSettings/DSR.ini, Data/Sys/GameSettings/RSR.ini, Data/Sys/GameSettings/WJE.ini, Data/Sys/GameSettings/XHL.ini
This pull request adds the setting to the INIs marked for these games.
=> Fix Motion Detection in Sonic and the Secret Rings and Jett Rocket

Source/Core/Core/HW/DSPHLE/UCodes/AXStructs.h, Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
A voice is considered running if and only if `running` equals 1, not if `running` is not equal to 0.
This fixes https://bugs.dolphin-emu.org/issues/12508 because for some reason *The Sims 2 - Castaway* sets `running` to 8 when a stream finishes playing; previously our AX HLE would just loop the voice and eventually crash after accessing invalid memory addresses.
Thanks to JMC47 and delroth's help, I've verified that this is the correct check for the following ucodes:
GC:
* 0x3ad3b7ac
* 0x3daf59b9
* 0x4e8a8b21
* 0x07f88145
* 0xe2136399
* 0x3389a79e
Wii:
* 0x347112ba
* 0xfa450138
* 0xadbc06bd
And while I was fixing the running check, I noticed that the is_stream field was also being handled incorrectly, so I've fixed that as well.
---
This PR also removes redundant accelerator end checks …
=> DSPHLE: Minor AX fixes

Data/Sys/GameSettings/ROD.ini
The line you're drawing in those games doesn't properly show up otherwise.
=> GameINI: Set safe texture cache in WarioWare: Smooth Moves for Writer's Block and Brain Age microgames.

Source/VSProps/Base.props
we were explicitly disabling it, which is
effectively the new behavior
=> msbuild: remove deprecated MinimalRebuild

Languages/Languages.vcxproj
the buildbot deletes complete Binary directory before each build.
to prevent re-creating po files for each build, this commit places them in the Build directory and then copies the results to Binary directory (like everything else in dolphin).
=> msbuild: use Build dir for Languages

Source/UnitTests/Common/FloatUtilsTest.cpp
compiles on contemporary msvc
checked there is still a mul in release codegen
=> unittests: remove some msvc-specific casts

Source/Core/Common/ArmFPURoundMode.cpp, Source/Core/Common/FPURoundMode.h, Source/Core/Common/GenericFPURoundMode.cpp, Source/Core/Common/x64FPURoundMode.cpp, Source/Core/Core/PowerPC/Gekko.h
This just addresses a comment I came across when grepping for `_MSC_VER`.
Compiles without warnings on msvc, unittests pass, and f-zero seems to run fine. The url in the comment is dead but I assume the issue was something relating to sign extension based on commit history and https://bugs.webkit.org/show_bug.cgi?id=134237
If this change isn't wanted anymore maybe we can just remove the comment instead?
=> make FPSCR.RN an enum

Readme.md
according to  [CommandLineParse.cpp](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/UICommon/CommandLineParse.cpp), the options are -v and -a, not -V and -A
=> Fix Readme.md's command line usage

Data/Sys/GameSettings/R6X.ini
Fixes :
https://bugs.dolphin-emu.org/issues/12534
=> INI settings for 'Hasbro Family Game Night 2'

Data/Sys/GameSettings/GS2.ini
I was testing out an issue on the tracker and noticed the invalid read memory address is usually where a game will load the error handler so I tried it with full MMU.  It resolved the issue.
I was unable to reproduce the other issues in the bug report.  
Fixes https://bugs.dolphin-emu.org/issues/12458
=> INI: Fix Summoner Invalid Reads

Source/Core/Common/FileUtil.cpp
On non-Windows platforms FileUtil's FileInfo(std::string) constructor initialized itself with the char* constructor, then did the same thing in its own function body. In addition to being duplicate code this resulted in two stats (or possibly worse on Android).
=> FileUtil: Remove duplication in FileInfo constructor

Data/Sys/GameSettings/D56E01.ini
Interactive Demo Disc Version 35 comes with Paper Mario: The Thousand-Year Door.  Note that D56J01 is a different game.  The settings are copied from the original game's INI as it contains scenes from the first couple of chapters.
The other games on the disc do not require any particular settings.
=> INI Settings for Paper Mario: Thousand-Year Door Demo Disc

Data/Sys/Shaders/swap_RGB_GBR.glsl, Data/Sys/Shaders/swap_RGB_GRB.glsl
I was trying out some of the shaders and noticed that, unlike the other similar shaders, `swap_RGB_GBR.glsl` and `swap_RGB_GRB.glsl` post-processing effects appeared to do nothing. This PR fixes both of them, which have been broken for at least seven years. I compared their output with swapping channels on a screenshot in GIMP to make sure that these new ones work properly.
=> Fix GBR and GRB post-processing effects

Data/Sys/GameSettings/GSV.ini
MX Superfly uses EFB copies to generate the outfit for your character in career mode.  This makes the game awkward to play without this setting.
=> GameINI: MX Superfly - fix player textures

Data/Sys/GameSettings/GQ4.ini
These games need MemoryCardSize = 2 or else they'll freak out and think the memory card is broken.
I also added the japanese version of SSX Tricky to the INI because it should be affected by GST.
=> INI: Fix Memcard detection in SSX Tricky and SpongeBob:CFtKK

Source/Core/Core/HW/EXI/EXI_DeviceGecko.cpp
Fixes https://bugs.dolphin-emu.org/issues/12153.
=> GeckoSockServer: Only join connectionThread if it is joinable

Source/Core/Core/NetPlayClient.cpp
release-ubu-x64 currently fails with "sorry, unimplemented: non-trivial designated initializers not supported". pr-ubu-x64 doesn't for some reason, but we might as well remove the designated initializer.
=> NetPlayClient: Remove a designated initializer

Data/Sys/GameSettings/GL8.ini
Disables Store EFB Copies to Texture Only.  As this game has a lot of water, the water not rendering correctly provides a pretty significant gameplay issue.
The game shows up in the gamelist as "Lara Croft Tomb Raider Legend" but I went with the wiki name instead as not to cause confusion.
=> GameINI:  Fix water in Tomb Raider Legend

Source/Core/Core/HW/AddressSpace.cpp
Previously, looking at MEM2 in the physical mode (at 10000000) would show all zeros.  However, the search feature would match the actual data.  This happened because ReadU8 and WriteU8 did not account for the accessor's base offset (though search did).  I'm somewhat surprised it didn't just crash in this case.
Note that effective mode (where MEM2 is at 90000000) worked properly before in most cases.  The one exception I know of is with the FIFO player, where nothing seems to be mapped at 90000000; this is probably because fifologs don't store BATs.  However, graphics-related logic all operates on physical addresses, so I'm not going to worry about that for now.
This change should have no impact on emulation, only on the memory viewer.
=> Fix MEM2 in the memory viewer in physical mode

Data/Sys/GameSettings/R2V.ini
Sin & Punishment: Star Successor has rendering issues in the upper left part of the screen.  While we can't completely fix it, by disabling Store EFB Copies to Texture only, we can make it from a missing box to just a couple of lines being incorrectly visible that make up the copy region's borders.
This makes the game much more playable in the meantime.
=> GameINI:  Improve Rendering in Sin & Punishment: Star Successor

Data/Sys/GameSettings/GKM.ini
At extreme angles, there is severe shadow zfighting with fast depth disabled.  Enabling it causes it work on all backends without issue.  Verified in OpenGL, D3D11, D3D12, and Vulkan.  I assume that this is the correct setting name, as I copied it out of the GFX config file.
=> GameINI: Fix PoP:TT Shadows

Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Branch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp
We currently have a bug when calling `Arm64GPRCache::Flush` with `FlushMode::MaintainState`, zero free host registers, and at least one guest register containing an immediate. We end up grabbing a temporary register from the register cache in order to be able to write the immediate to memory, but grabbing a temporary register when there are zero free registers causes the least recently used register to be flushed in a way which does not maintain the state of the register cache.
To get around this, require callers to pass in a temporary register in the GPR MaintainState case. In other cases, passing in a temporary register is not required but can help avoid spilling a register (if the caller already had a temporary register at hand anyway, which in particular will be the case in my …
=> JitArm64: Add temp reg parameter to Arm64RegCache::Flush

Source/Core/Common/StringUtil.cpp, Source/Core/Common/StringUtil.h
Aside from being unused it has a strange interface and implementation. 
It's barely been touched since the initial git megacommit; I'm guessing it was meant to work around missing Return Value Optimization in ancient compilers?
=> StringUtil: Remove unused function BuildCompleteFilename

Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
Sonic Colors probably needs this for underwater audio: https://bugs.dolphin-emu.org/issues/10069
No idea whether it's still broken or not.
=> DSPHLE: re-enable low-pass filter

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.h
If we're only using the lower 64 bits of a callee-saved register, GetCallerSavedUsed can return false for it.
=> JitArm64: Improve Arm64FPRCache::GetCallerSavedUsed

Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
The dcbz instruction needs to lock W30 so that the slowmem code will push and pop it when calling into C++. Also, the slowmem code expects that the address is present in W0, so replace the use of W0 as a scratch register in the fastmem code with the now locked W30.
=> JitArm64: Fix dcbz backpatch

Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
This column would end up containing junk data after changing the data type, specifically whatever data was already in that column in the previous datatype.
Column 0 is used for a breakpoint indicator (if the entire row has breakpoints).  Column 1 is the address.  Columns 2 through 2+n, exclusive, are used for the data for the row, where n varies by data type (for U8 it's 16, but for float and U32 it's 4); for example, with float, columns 2, 3, 4, and 5 are in use.  Thus, there are 6 columns (0 through 5), which is 2+4, not 3+4.
Before: [First set to U8](https://user-images.githubusercontent.com/8334194/126725530-33737d38-eee1-4d45-8a6d-2a1914fa7d64.png), [then change to float](https://user-images.githubusercontent.com/8334194/126725539-0883e351-755d-4cbe-84cd-643958deb9e3.png)
After: …
=> MemoryViewWidget: Remove unnecessary column

Data/Sys/GameSettings/SDB.ini
de Blob 2 has the same engine as de blob and shares a lot of the same issues.  I copied the settings used for de blob.  It seems defer EFB copies was the main culprit of the black box issue returning, but force texture filtering could also cause problems.
=> GameINI:  Fix de Blob 2 visual issues.

Source/Core/DolphinQt/Settings/AudioPane.cpp
I've seen a lot of users selecting DSP-LLE because they figure "how slow can audio emulation be?" and not really realizing that DSP-LLE is the reason that their game is lagging.  I don't know if this is the right thing to do, but I feel like our DSP emulation is good enough that every game that needs DSP-LLE to function has it enabled by default.
Anyway, I think to help reduce user confusion it might be good to explicitly mark DSP-HLE as recommended, and mark DSP-LLE Recompiler as slow.  DSP-LLE Interpreter I've marked as very slow as it is very slow.
=> AudioPane: Adjust DSP selection names

Source/Core/DolphinQt/GBAWidget.cpp, Source/Core/DolphinQt/GBAWidget.h
See [issue 12588](https://bugs.dolphin-emu.org/issues/12588).  This doesn't introduce any more complicated functionality; it only exposes the functionality that was already available via drag and drop in a more discoverable way.
I haven't tested this at all.
=> GBA: Add "Scan e-Reader Card(s)" context menu item

Source/Core/Core/BootManager.cpp, Source/Core/Core/Config/NetplaySettings.cpp, Source/Core/Core/Config/NetplaySettings.h, Source/Core/Core/Config/SessionSettings.cpp, Source/Core/Core/Config/SessionSettings.h, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/HW/GCMemcard/GCMemcardDirectory.cpp, Source/Core/Core/HW/GCMemcard/GCMemcardRaw.cpp, Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/WiiRoot.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp, Source/Core/DolphinQt/NetPlay/NetPlayDialog.h
This actually eliminates any setting pertaining to SD cards from the NetPlay dialog, as it would effectively just be a duplicate of the setting in the Wii pane, potentially causing confusion.
This also enables save data writing by default, as this is probably what most players want, and should avoid them losing hours of progress because they forgot to tick a checkbox.
=> NetPlay: Split save and SD card write settings

Source/Android/app/src/main/res/values/arrays.xml
The Android strings were not updated in PR #9941 along with the DolphinQt strings.
=> Android: Adjust DSP selection names

Data/Sys/GameSettings/SG7.ini
The Garfield Show: Threat of the Space Lasagna hangs on story mission start with Dual Core most of the time.
I didn't ask for SyncGPU to be tested as it's suffering from coderot at the moment and we're not sure of the future of it.  Single Core, isn't going anywhere, though.
=> GameINI:  Fix Garfield Hang

Source/Core/VideoBackends/Software/TextureSampler.cpp, Source/Core/VideoCommon/BPMemory.h, Source/Core/VideoCommon/RenderState.cpp
See https://bugs.dolphin-emu.org/issues/12408.  When texture wrapping is enabled, the texture size should be a power of two per [libogc](https://github.com/devkitPro/libogc/blob/bd24a9b3f59502f9b30d6bac0ae35fc485045f78/gc/ogc/gx.h#L4242-L4243); yagcd mentions (near [bp register](http://hitmen.c02.at/files/yagcd/yagcd/chap5.html#sec5.11.1) 0x80) that repeat and mirror "[require] the texture size to be a power of two. (wrapping is implemented by a logical AND (SIZE-1))".
Although I initially targeted this at the the non-power-of-2 issue, it also impacts the software renderer when wrapping textures in negative coordinates (https://dolp.in/i11834/6 is an example).  This is probably due to the modulus operator `%` returning negative numbers for negative inputs (e.g. `-1 % 4` is `-1`), while …
=> Software: Handle texture wrapping more accurately

Source/Core/DiscIO/WIABlob.h
The workaround added in PR #9855 caused a regression where Dolphin incorrectly replaced runs of one byte with runs of another byte when writing WIA and RVZ files. `ReuseID::operator<` was always returning false unless the `ReuseID`s being compared had different partition keys, which caused `std::map<ReuseID, GroupEntry>` to treat all `ReuseID`s with the same partition key as equal.
=> DiscIO: Fix broken workaround for MSVC ARM64 ICE

Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h
This fixes the title screen music of Snowpack Park (https://bugs.dolphin-emu.org/issues/12499).
=> DSPHLE: fix and re-enable polyphase resampling

Source/Core/Core/HW/GBACore.cpp, Source/Core/Core/HW/GBACore.h, Source/Core/DolphinQt/GBAHost.cpp, Source/Core/DolphinQt/GBAWidget.cpp, Source/Core/DolphinQt/GBAWidget.h
This adds features frequently requested by users to the GBA windows
- Borderless mode
- Always on top
- Interframe blending (see https://mgba.io/2020/01/21/mgba-0.8.0/#interframe-blending)
This also exposes Core features better to make a couple conditions in the context menu more accurate
=> Qt: GBA QoL improvements

Source/DSPSpy/main_spy.cpp
printf was getting very confused by the mismatches between the non-`long` format string placeholders and the `long` function arguments.
=> DSPSpy: fix $prod printing

Data/Sys/GameSettings/S5S.ini
Certain text characters do not render properly with any other texture cache setting.  We tested 2048 and 512, and that was not enough to completely remedy the issue.
=> GameINI: Add Safe Texture Cache to Inazuma Eleven GO: Strikers 2013

Data/Sys/GameSettings/GCCJGC.ini, Data/Sys/GameSettings/GCCP01.ini
This is a port of the NTSC patch to the Japanese and PAL regions. Bonta helped with the GBA code for both versions and wrote the original NTSC patch, and leoetlino helped convert some addresses for the japanese version.
=> GameINI: Add FFCC Connectivity patch to all regions

Source/Core/VideoCommon/BPMemory.h
This was added because YAGCD's info on MAXANISO (near TX_SETMODE0 in Section [5.11.1](http://hitmen.c02.at/files/yagcd/yagcd/chap5.html#sec5.11.1)) claims it's the case, but Extrems says it does work.  I haven't tested anything myself, and dolphin still does not actually implement anisotropic filtering based on this field.
=> Remove note about anisotropic filtering requiring edge LOD

Source/Core/Core/PowerPC/Jit64/Jit.h, Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp, Source/Core/Core/PowerPC/Jit64/Jit_Paired.cpp
So it turns out you have to pass `XMM0` as the clobber register to `HandleNaNs`, because `HandleNaNs` uses `BLENDVPD` and `BLENDVPD` implicitly uses `XMM0`, and nobody noticed when I broke this in 2c38d64 because nobody plays the one game that needs accurate NaNs.
=> Jit64: Fix fmaddXX with accurate NaNs

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.h, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.h
When PR #9314 fixed https://bugs.dolphin-emu.org/issues/12133, it did so by removing the broken address calculation entirely and always using the slow path. This caused a performance regression, https://bugs.dolphin-emu.org/issues/12477.
This pull request instead replaces the broken address calculation with a BAT lookup. If the BAT lookup succeeds, we can use the old fast path. Otherwise we use the slow path.
Intends to improve https://bugs.dolphin-emu.org/issues/12477.
@JMC47 Please test Happy Feet and some games with known performance problems.
Everyone else: I'm not entirely confident that I made no mistakes with the assembly, so don't let JMC merge this before it's been properly reviewed :)
=> Jit: Perform BAT lookup in dcbf/dcbi/dcbst

Readme.md
Pulling submodules is necessary now that mGBA is integrated.
Perhaps having the same submodule note repeated three times in the different sections of the readme file is a bit odd, but I don't know of a fitting section to put it in that isn't OS-specific...
=> Readme: Copy the submodule note to non-Windows sections

Source/Core/DolphinQt/GBAWidget.cpp
This is more a "windows is silly" thing: if a window is maximized but then resized, it'll remain maximized and in the top-left corner of the screen, but the size will change.  However, if you attempt to move the window to a different place, it'll become un-maximized and the size it had before maximizing will be used (and it'll ignore the size you set when it was maximized).  Returning the window to a normal state fixes this.
=> Qt: Un-maximize GBA widget before resizing it

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/VideoCommon/ShaderCache.cpp, Source/Core/VideoCommon/ShaderCache.h, Source/Core/VideoCommon/ShaderGenCommon.cpp, Source/Core/VideoCommon/ShaderGenCommon.h
This causes shaders to be reloaded when 'Enable API Validation Layers' is toggled.  It also does some general fixing and cleanup of related code.
=> Recompile shaders when 'Enable API Validation Layers' is toggled

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.h, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
Minor mistake in PR #9957. We should be using ibat_table instead of dbat_table, since we're dealing with invalidating icache.
=> Jit: Use ibat_table for dcbf/dcbi/dcbst address check

Data/Sys/GameSettings/SRX.ini
Generator Rex: Agent of Providence needs medium texture cache in order to render text without problems.
=> GameINI: Enable Medium Tex Cache for Generator Rex

Source/Core/Core/DSP/DSPDisassembler.cpp
Originally, 1479 (for example) would disassemble as `lsr $ACC0, #-7`.  At some point (likely the conversion to fmt), this regressed to `lsr $ACC0, #4294967289`.  Now, it disassembles as `lsr $ACC0, #7`.
<details><summary>Changes to DSP_UC_347112BA.txt (Wii Menu)</summary>
<pre lang="diff">
@@ -524,7 +524,7 @@
02b5 00fe 0cd4 sr          @0x0cd4, $AC0.M
02b7 00de 02d6 lr          $AC0.M, @0x02d6
02b9 009f 0d53 lri         $AC1.M, #0x0d53
-02bb 14fb      asr         $ACC0, #4294967291
+02bb 14fb      asr         $ACC0, #5
02bc 3400      andr        $AC0.M, $AX0.H
02bd 4c00      add         $ACC0, $ACC1
02be 1c7e      mrr         $AR3, $AC0.M
@@ -532,7 +532,7 @@
02c0 00fe 0cd5 sr          @0x0cd5, $AC0.M
02c2 00de 02d6 lr          $AC0.M, @0x02d6
02c4 009f 0d73 lri         $AC1.M, #0x0d73 …
=> DSPDisassembler: Fix LSR/ASR formatting

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
The sixth and final part of implementing the FPSCR system register instructions.
=> JitArm64: Implement mtfsfx

Source/Core/Core/PowerPC/Jit64/Jit_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
It was believed that this only mattered when the rounding mode was set to round to infinity, which games generally don't do, but it can also affect the sign of the output when the inputs are all zero.
=> Jit: Use accurate negation order for FMA instructions

Source/Core/VideoCommon/GeometryShaderGen.cpp, Source/Core/VideoCommon/GeometryShaderGen.h, Source/Core/VideoCommon/UberShaderPixel.cpp, Source/Core/VideoCommon/UberShaderPixel.h
This brings this parameter name in line with the coding style.  Note that PixelShaderGen was already corrected in #9171, and as far as I can tell this never applied to VertexShaderGen or UberShaderVertex.
=> VideoCommon: Rename ApiType to api_type

Source/Core/VideoCommon/VideoBackendBase.cpp
macOS's OpenGL support is terribly outdated - it's been stuck on OpenGL 4.1 since Mavericks (released in 2013!) and doesn't support key extensions like ``ARB_buffer_storage``. Plus, starting with macOS Mojave, OpenGL has been deprecated and may be removed in a future macOS.
Now that we have MoltenVK, it might be best to set the Vulkan backend as default for new users with Macs that run Mojave and newer. (High Sierra and older don't support some Metal features that Dolphin requires.)
=> VideoBackendBase: Prefer Vulkan over OGL on macOS Mojave and newer

Data/Sys/GameSettings/R8I.ini
Text in SpongeBob's Truth of Square needs Safe Texture Cache in order to render properly.
=> GameINI: Add Safe Texture Cache to SpongeBob's Truth or Square

Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
Fix a race condition in the WiimoteScanner thread which can cause a crash on Dolphin shutdown. This crash occurs when the following happens:
- Scanner: runs its main loop while m_scan_thread_running is set
- Main thread: calls WiimoteScanner::StopThread() which calls m_scan_thread_running.TestAndClear()
- Main thread: starts iterating over m_backends, using backend as a reference to each element
- Scan thread: finishes its current iteration of the loop. m_scan_thread_running is no longer set, so it breaks out of the loop.
- Scan thread: creates a lock_guard on m_backends_mutex then calls m_backends.clear(), calling the destructors of the underlying unique_ptrs
- Main thread: tries to dereference backend and crashes
This fix simply defers clearing the m_scan_thread_running flag until after …
=> WiimoteReal: Fix Dolphin shutdown crash

Data/Sys/GameSettings/GQP.ini, Data/Sys/GameSettings/GQPE78.ini, Data/Sys/GameSettings/GQPP78.ini
This enables Vertex Rounding Hack and has a game patch for two bugs resulting from game choices.  The game draws an EFB copy from texture coordinate 0.00195313 to 1.00195 repeating which only works due how to the numbers work out at low resolution.
The Vertex Rounding Hack is a null operation on 1x IR, so there should be no concern enabling it by default since higher resolutions are completely broken without it.
I spent all day testing the game and got nearly to the end with no crashes nor major graphical glitches at 4x internal resolution.  The PAL version of the patch I developed myself based on the NTSC version of the patch, which was based on the Action Replay code on the wiki - https://wiki.dolphin-emu.org/index.php?title=SpongeBob_SquarePants:_Battle_for_Bikini_Bottom
=> GameINI: SpongeBob SquarePants: Battle For Bikini Bottom Quality of Life settings

Source/Core/VideoBackends/Software/TransformUnit.cpp, Source/Core/VideoCommon/UberShaderVertex.cpp, Source/Core/VideoCommon/VertexShaderGen.cpp
This fixes eyelids in Shadow the Hedgehog during cutscenes (https://bugs.dolphin-emu.org/issues/11458).
The eyelids (objects 36 and 37) draw on the same data, but object 36 uses texture coord 0 for its texture coordinate while object 37 uses the normal for its texture coordinate.  The normal coordinates come from 00793400 (80793400 virtual), and some of them are NaN (specifically encoded as ffc00000).  This specifically affects the center of the white part of the eye and the top left part of it, but because of how NaN behaves, the result of trying to interpolate anything with those vertices is NaN.
I used the hardware fifoplayer with the fifolog from that issue, and things rendered correctly, so this isn't a case of bad emulation creating NaNs:
My fix is to convert NaN to 1 before doing …
=> Convert NaN to 1 when generating texture coordinates

Data/Sys/GameSettings/GLSD64.ini, Data/Sys/GameSettings/GLSF64.ini, Data/Sys/GameSettings/GLSP64.ini
Only the NTSC version of Gladius got a patch with smurf3tte's reverse engineering work.  Since most of the work was done, I ported over the fix to the PAL, French, and German releases.  Leoetlino helped figure out a consistent way to find the correct address.
These codes were tested to bypass the original crash in the intro, however I did not play the games beyond the 5 tutorial missions.
=> GameINI: Add Gladius Patch to Other Regions

Source/Core/DolphinQt/Config/Mapping/MappingButton.cpp
PR https://github.com/dolphin-emu/dolphin/pull/9700 removed spaces from within control names, which some user complained about, and their point of view is kind of understandable:
https://bugs.dolphin-emu.org/issues/12605
with this change, only spaces outside (between) control names are trimmed, which are the ones we wanted to trim in the first place.
This will still retain the major advantages from 9700.
Basically, "**Button 1   +  Button 2**" was showing as "**Button1+Button2**", while it will now show as "**Button 1+Button 2**".
=> Preserve spaces in mapping preview of control names

Data/Sys/GameSettings/GGV.ini, Data/Sys/GameSettings/GGVD78.ini, Data/Sys/GameSettings/GGVE78.ini, Data/Sys/GameSettings/GGVP78.ini, Data/Sys/GameSettings/GGVX78.ini
SpongeBob SquarePants: The Movie suffers from all of the same issues as Battle for Bikini Bottom.  These patches are not based on any existing cheats or codes, this one isn't as loved as Battle for Bikini Bottom and didn't receive an action replay code to fix everything.  There *is* a cheat that disables shadowing, but that wasn't good enough, so I sought out to make a new patch that does the same thing as the one for Battle for Bikini Bottom.
Heavy guidance was given by Pokechu22, who helped walking me through ghidra to find the memory addresses.  The game is rendering efb copies with coordinates 0.00390625 and 1.00390625, which cause severe problems at higher resolutions.  This patch adjusts them to render at 0 and 1, and enables the Vertex Rounding Hack to repair things at higher …
=> GameINI: SpongeBob SquarePants Movie QoL Settings

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
=> Jit64: Always pass effective address to InvalidateICache() in dcbx.

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp
BT sets the carry flag, not the zero flag.
~~Hopefully fixes https://bugs.dolphin-emu.org/issues/12608 (I don't have the game for testing).~~
=> Jit64: Fix BATAddressLookup bit test

Source/Core/DolphinQt/Config/FilesystemWidget.cpp
This adds the partition type, partition gameid, and partition title ID from the ticket into the filesystem widget.  This is mostly just information that's interesting but not particularly useful, but it does help with seeing how the different values differ.  Note that the partition gameid already shows up if you take screenshots while running something on a different partition (e.g. the Wii Fit Channel installer).
<details><summary>Screenshots</summary>
</details>
=> FilesystemWidget: Show more information about partitions

Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp, Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/MMU.h
This implements the behavior described in https://bugs.dolphin-emu.org/issues/12565.
The implementation requires writes to pass through slowmem in order to be affected. Since most users probably don't care about emulating this behavior and thus wouldn't want performance to get lower just for the sake of emulating it, I've added a new INI-only setting `AlignmentQuirks` which controls whether slowmem is forced for uncached memory.
Thank you to eigenform, delroth, phire, marcan, segher, and Extrems for all helping in one way or another with the efforts to reverse engineer this behavior, and to Rylie for reporting the issue.
=> PowerPC: Implement broken masking for uncached unaligned writes

Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp, Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp, Source/Core/Core/PowerPC/JitInterface.cpp, Source/Core/Core/PowerPC/JitInterface.h
When making PR #9957, I checked whether the ~0x1f masking in dcbx actually was necessary. I came to the conclusion that it wasn't, so I removed it. However, I hadn't checked the second half of InvalidateICache closely enough – the masking is actually needed.
This commit re-adds the masking, but this time in C++ code instead of in jitted code in order to save icache. Though I suppose the difference doesn't matter all that much, since this is in farcode and all...
Hopefully fixes https://bugs.dolphin-emu.org/issues/12612 (not tested).
=> Jit: Re-add dcbx masking

Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/VideoBackends/Vulkan/ShaderCompiler.cpp
Title.
This PR was opened mostly so I can take advantage of the Windows buildbot, but perhaps it would be useful to upstream as well.
=> ShaderCompiler: Attach shader source code to SPIR-V

Source/Core/Core/HW/WiimoteEmu/Extension/Nunchuk.cpp
=> Nunchuk: Use correct middle click expression on macOS

Source/Core/Core/FifoPlayer/FifoDataFile.cpp
The main thing I'm targeting here is opening a 0-byte file, as currently that produces the nonsensical error message "The DFF's minimum loader version (1) exceeds the version of this FIFO Player (5)" (due to the check on `header.fileId != FILE_ID`).  I often end up opening a 0-byte file if I try to open it while it's still downloading (as firefox creates a 0-byte file as well as a .tmp file).
The other checks were added for completeness; note that `Common::IOFile` uses RAII so the manual close calls aren't needed.  I removed them for `Load` but haven't touched anything in `Save`.
=> FifoDataFile: Improve error handling when reading

Data/Sys/GameSettings/GCH.ini, Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/Core/HW/VideoInterface.cpp, Source/Core/VideoCommon/Fifo.cpp, Source/Core/VideoCommon/VideoBackendBase.cpp, Source/Core/VideoCommon/VideoBackendBase.h
This adds about a frame of latency, and since most games don't change VI registers during scanout, we can get away with outputting the XFB at the start of scanout. WWE Crush Hour is the (only currently known) exception, which has flickering problems when doing it this way.
This adds a path to perform the output at the end of scanout, and gates it behind an option which defaults to using the latency-reducing pre-scanout path.
I also included the appropriate INI change.
=> VI: Implement post-scanout XFB output

Data/Sys/GameSettings/GICD78.ini, Data/Sys/GameSettings/GICF78.ini, Data/Sys/GameSettings/GICH78.ini, Data/Sys/GameSettings/GICJG9.ini, Data/Sys/GameSettings/GICP78.ini, Data/Sys/GameSettings/GIQ.ini, Data/Sys/GameSettings/GIQE78.ini, Data/Sys/GameSettings/GIQJ8P.ini, Data/Sys/GameSettings/GIQX78.ini, Data/Sys/GameSettings/GIQY78.ini, Data/Sys/GameSettings/GU2.ini, Data/Sys/GameSettings/GU2D78.ini, Data/Sys/GameSettings/GU2F78.ini, Data/Sys/GameSettings/GU3.ini, Data/Sys/GameSettings/GU3D78.ini, Data/Sys/GameSettings/GU3X78.ini, Data/Sys/GameSettings/GU4.ini, Data/Sys/GameSettings/GU4Y78.ini
SpongeBob SquarePants: Battle for Bikini Bottom and The Movie Game, along with the two Incredibles titles suffer from an EFB offset issue described in earlier commits.  This commit adds support for the Incredibles 1/2 revisions and adds additional inis for SpongeBob special releases.
To the best of my knowledge, no The Incredibles: Rise of the Underminer GIQP78 exists, but it is marked on our wiki so I added it to the base INI as a possible revision.  I did not provide a code for it, though.  These probably need a really good look over as this is probably the most changes I've ever packed into a single pull request.
=> GameINI:  Fix EFB Copy Offset in more games

Source/Core/AudioCommon/AlsaSoundStream.cpp, Source/Core/AudioCommon/AlsaSoundStream.h, Source/Core/AudioCommon/AudioCommon.cpp, Source/Core/AudioCommon/NullSoundStream.cpp, Source/Core/AudioCommon/NullSoundStream.h, Source/Core/AudioCommon/OpenALStream.cpp, Source/Core/AudioCommon/OpenALStream.h, Source/Core/AudioCommon/OpenSLESStream.h, Source/Core/AudioCommon/PulseAudioStream.h, Source/Core/AudioCommon/SoundStream.h, Source/Core/AudioCommon/WASAPIStream.cpp, Source/Core/AudioCommon/WASAPIStream.h
This gets rid of the bogus "AudioCommon/AudioCommon.cpp:181 E[Audio]: Error stopping stream." errors.
=> AudioCommon: fix bogus error + cleanup

Data/Sys/GameSettings/GLE.ini
This is already recommended by the wiki, but I think it should be set by default.
Without safe texture cache accuracy, item and weapon icons can disappear when picking an item up or transferring an item to/from an item box. In addition, when equipping/unequipping a weapon, the previous weapon icon (or lack thereof) may stay in its place instead of changing. This can cause confusion when playing the game.
On fast accuracy, this issue occurs often. I also tried with middle accuracy, and the frequency of occurrence decreased, but it still sometimes happens. Safe accuracy appears to eliminate the problem entirely.
<details>
<summary>Example</summary>
Here, I have the shotgun equipped. However, the equipped weapon icon tells me I have the pistol equipped.
</details>
=> GameINI: Force safe texture cache on Resident Evil 3

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/MMU.h
The only functional change is around `TranslateResult::from_bat`, which was previously true but is now false if `MSR.IR` is off... but since no one actually checks that variable at the moment even that doesn't actually change behavior. I'm keeping it around though because I found a use for it in #10007.
=> PowerPC: Minor cleanup around JitCache_TranslateAddress().

Data/Sys/GameSettings/GIQ.ini
This is necessary to actually fully fix the game at higher resolutions and was forgotten in the earlier batch of INI changes.
=> GameINI:  Add missing Vertex Rounding to GIQ.ini

Source/Core/VideoBackends/D3D12/D3D12Renderer.cpp
When doing GPU texture decoding Dolphin never transitions the decoding texture to RESOURCE_STATE_UNORDERED_ACCESS despite writing to it in a compute shader. It gets created with `RESOURCE_STATE_PIXEL_SHADER_RESOURCE` so there isn't any implicit state promotion going on either.
This could fix https://bugs.dolphin-emu.org/issues/12094. I can't reproduce that bug though, it seems to only affect AMD GPUs.
Nvidia GPUs ignore the VkImageLayout with Vulkan so the reason for why it works on Nvidia might be something similar.
=> D3D12: Transition compute textures to UAV state

Source/Core/DolphinQt/Debugger/NewBreakpointDialog.cpp
I found it a little bit annoying that you can't start typing the desired address immediately after opening the window.
Also getting rid of the window's ? button while I'm at it.
=> DolphinQt: Set default focus for NewBreakpointDialog

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinEmuDebug.entitlements
In order to attach a debugger to a process with a Hardened Runtime (e.g. on an M1 mac), one needs the `com.apple.security.get-task-allow` entitlement.
Normally this entitlement is injected by XCode when running from XCode (assuming the XCode attribute `CODE_SIGN_INJECT_BASE_ENTITLEMENTS` is enabled), but this doesn't happen when building from a makefile or when you manually specify entitlements directly to codesign like this.
=> DolphinQt: Add entitlement to allow debugger to attach in Debug builds

Source/Core/DolphinQt/Config/CheatCodeEditor.cpp
Also fixing a string mistake where the text for AR codes was copypasted for Gecko codes.
=> DolphinQt: Don't add trailing newline to Gecko notes

Source/Core/DolphinQt/Config/CheatCodeEditor.cpp
When you come across a cheat code in a place like the Dolphin wiki, it's often posted like this:
```
$16:9 Widescreen
0441187C 3FE38E39
```
Sometimes users try to paste this in its entirety into the Code field, which leads to Dolphin reporting an error on the first line. I think it would be nice to make this a little smoother by having Dolphin accept having a first line that starts with $.
=> DolphinQt: Allow $ line when entering AR/Gecko code

Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp, Source/DSPSpy/tests/less_test.ds
`IsLess` would incorrectly return true if both `SR_OVERFLOW` and `SR_SIGN` are set, as `(sr & SR_OVERFLOW) != (sr & SR_SIGN)` becomes `SR_OVERFLOW != SR_SIGN` which is true as the two masks are different.  This broke in e651592ef56521f6db71f8a671fe8c20b948d338.
This issue only affected the DSP LLE Interpreter, and not the DSP LLE JIT.
I've also included a simple test case for this.  `ax0.l` (on the top left) is set to 0 if the instruction following `IFL` does not execute and to 1 if it is executed.
<details><summary>On console</summary>
</details>
<details><summary>On Dolphin with JIT</summary>
</details>
<details><summary>On Dolphin before this change</summary>
</details>
<details><summary>On Dolphin with this change</summary>
</details>
=> DSPInterpreter: Fix IsLess

Source/Core/DiscIO/VolumeVerifier.cpp
Retail-signed discs use the format: IOS56-64-v5661.wad
Debug-signed discs use the format:  firmware.64.56.22.29.wad
Debug-signed discs usually have a 128 version of the firmware as well, since some devkits have 128 MB MEM2. (Retail has 64 MB.)
This fixes part of VolumeVerifier for debug discs. It's not validating the signatures properly. I attempted to add the debug root key (which is different from retail), and that helped, but ESDevice::VerifyContainer() was still getting an error from mbedtls, even though the public key appeared to be correctl
=> VolumeVerifier: Use correct IOS filename for development discs.

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
One of those fun "how did this ever work" bugs.
=> JitArm64: Fix paired loadstore instruction decoding

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.cpp, Source/Core/Core/PowerPC/JitCommon/JitCache.h, Source/Core/Core/PowerPC/JitInterface.cpp, Source/Core/Core/PowerPC/JitInterface.h, Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/MMU.h, Source/Core/Core/PowerPC/PPCCache.cpp
So unfortunately, I have to report that our recent dcbx fixes have once again made Mario Sunshine's boot sequence and A Boy and his Blob in general slow again.
I profiled this a bit and it turns out the big performance issue comes from a game calling dcbx, failing the BAT check on memory that is not mapped in the BAT, and then `JitCache_TranslateAddress()` having to go through the rather slow `TranslatePageAddress()`. This wouldn't be so bad once, but:
- Mario Sunshine calls this *on the entire address space*, one cache line at a time.
- A Boy and his Blob does this all the time in the background, on multiple ~266KB regions.
This, as it turns out, is slow. Profiler in Mario Sunshine's boot sequence shows >70% CPU usage in just the page translation code. Which makes sense when you think …
=> Jit64: dcbx loop detection for improved performance when invalidating large memory regions.

Source/Core/Core/PowerPC/Jit64/Jit_LoadStoreFloating.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
The fast path of using CVTSD2SS/FCVTN rounds the significand if it can't be exactly represented as a single, whereas the accurate path instead truncates the significand. So we should only use the fast path if we know that the lower bits of the significand are not set.
This is not known to affect any games.
=> Jits: Don't use fast double-to-single when input is double precision

BuildMacOSUniversalBinary.py, CMakeLists.txt, Readme.md, Source/Core/Common/FileUtil.cpp
As discussed [here](https://forums.dolphin-emu.org/Thread-unable-to-open-newest-version-of-dolphin-in-os-x-sierra?pid=520790#pid520790) and on IRC.
The minimum macOS version supported by Qt 5.14 is 10.13 High Sierra.
=> Bump minimum macOS to 10.13 High Sierra

Source/Core/Core/Config/UISettings.cpp, Source/Core/DolphinQt/AboutDialog.cpp, Source/Core/DolphinQt/CMakeLists.txt
Just some minor things that were missed in #9862.
* The About dialog had a link to the now removed `license.txt` file.
* ``UISettings.cpp`` had a stray comment that was missed in the mass comment replacement (presumably due to the missing period).
* Windows builds still attempted to add a non-existent `license.txt` to the output directory. This has been replaced with adding the ``COPYING`` file and the ``LICENSES`` directory.
=> Fix some missed items from SPDX transition 

Source/Core/Core/DSP/DSPCore.h, Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitRegCache.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitUtil.cpp, Source/DSPSpy/tests/dsp_base.inc, Source/DSPSpy/tests/reg_mask_test.ds
The `cr` and `prod.h` registers are 8 bits and do not experience sign extension.  Also, the `SR_100` bit always seems to read back as 0, regardless of what's written to it `sr`.  Lastly, `ac0.h` and `ac1.h` do experience sign extension; this is already implemented, but the implementation worked incorrectly on the interpreter when the whole `acc0` or `acc1` register was updated and then `ac0.h` or `ac1.h` were read back directly.
<details><summary>Results</summary>
Apologies for how unreadable this is.  Think of it more as a table of thumbnails than something you can directly compare.
| Test | Hardware | Old JIT | Old Int | New JIT | New Int |
|------|----------|---------|---------|---------|---------|
| Less | ![Screenshot 2021-08-15 …
=> DSP masking and sign extension fixes

Source/Core/Core/PowerPC/JitInterface.cpp
Noticed this while glancing over the code. Probably doesn't actually matter in practice, but might as well fix it...
=> PowerPC: Fix for calling InvalidateICacheLines() with a count of 1 causing a (harmless) second invalidation.

Source/Core/Core/DSP/Interpreter/DSPIntArithmetic.cpp, Source/Core/Core/DSP/Interpreter/DSPIntBranch.cpp, Source/Core/Core/DSP/Interpreter/DSPIntExtOps.cpp, Source/Core/Core/DSP/Interpreter/DSPIntLoadStore.cpp, Source/Core/Core/DSP/Interpreter/DSPIntMisc.cpp, Source/Core/Core/DSP/Interpreter/DSPIntMultiplier.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitArithmetic.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitBranch.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitExtOps.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitLoadStore.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitMisc.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitMultiplier.cpp, Source/DSPSpy/.gitignore, Source/DSPSpy/Config.h, Source/DSPSpy/Makefile, Source/DSPSpy/README.md, Source/DSPSpy/build.sh, Source/DSPSpy/sbuild.sh, Source/DSPSpy/tests/cr_test.ds, docs/DSP/GameCube_DSP_Users_Manual/.gitignore, docs/DSP/GameCube_DSP_Users_Manual/GameCube_DSP_Users_Manual.tex
A bunch of improvements to the DSP manual, bringing it in line with Dolphin's own code (and changes from #10032, #10038, and #10045) and making it easier to use.
For convenience, here is the newly compiled manual: [GameCube_DSP_Users_Manual.pdf](https://github.com/dolphin-emu/dolphin/files/7026050/GameCube_DSP_Users_Manual.pdf)
=> Improvements to DSP manual

Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
Since the merge of PR #10036, we've gotten reports that the following games are broken on JitArm64:
* Sonic Heroes
* The SpongeBob SquarePants Movie
* Astérix & Obélix XXL
* The Incredibles: Rise of the Underminer
Disabling the register cache avoids the issue, so the cause of the bug might not actually have anything to do with the newly implemented instructions. Nevertheless, I don't want to ship a beta with this problem present, so I would like to disable these instructions for the time being.
=> JitArm64: Disable indexed paired loadstore instructions

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
PR #10050 did not make the issue go away.
=> JitArm64: Indexed paired loadstores workaround, attempt 2

Source/Core/Core/DSP/Jit/x64/DSPJitRegCache.cpp
This reverts commit dc2eab17789b39d8fcd6e32e98f8920078f08841.  That commit broke the DSP recompiler for most games (causing a large number of unknown pointer errors), similar to what happened with the DSP interpreter before [bug 12633](https://bugs.dolphin-emu.org/issues/12633) was fixed (by a different change in #10045).
I'm not entirely sure why this commit causes issues.  It may be something to do with multiple registers being stored in one host register, and thus the 32-bit operation causing one to be clobbered, but I'm not certain of this.  Reverting it for now seems to be the best choice, especially as `cond_test` has the same results with it reverted so it doesn't seem to actually make much of a difference.
=> Revert "DSPJit: Sign-extend acS.h to 32 bits"

Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp
`HandleFastmemFault` works correctly when faults only happen in expected locations, but it does some things that are rather dangerous for faults in unexpected locations, like decrementing an iterator without checking whether it's equal to `begin`.
This change cleans up the logic by making `m_fault_to_handler`'s key be the end of the fastmem region instead of the start.
=> JitArm64: Make HandleFastmemFault less unsafe

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/Debugger/WatchWidget.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/MenuBar.cpp
Removes the Windows help button from a handful of dialogs. I left the XLinkKai and Ethernet dialogs alone because they're taken care of in https://github.com/dolphin-emu/dolphin/pull/10025.
Also throws a few consts around.
Fixes https://bugs.dolphin-emu.org/issues/11536.
As noted in that report there's an option to globally disable the help button, but that would require us to bump the minimum Qt version from 5.9 to 5.10. Once we do bump the version we'll want to go through and remove all the hints.
=> DolphinQt: Remove Windows dialog help buttons

Source/Core/Core/IOS/Network/IP/Top.cpp, Source/Core/Core/IOS/Network/IP/Top.h
This PR try to fix games hanging while resolving domain names using `gethostbyname` and `getaddrinfo`.
I'm open to suggestion, especially regarding the way the asynchronous part should be done.
=> IOS/Network: Make name resolution asynchronous

Source/Core/Core/PowerPC/PPCSymbolDB.cpp
This PR fixes https://dolp.in/i11995.
Ready to be review & merged.
=> PPCSymbolDB: Improve symbol map column detection

Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStore.cpp
=> JitArm64: dcbx loop detection for improved performance when invalidating large memory regions

Data/Sys/GameSettings/GIH.ini
This game is the earliest of Heavy Iron Studios' Gamecube games and has a similar offset issue to that of the SpongeBob and Incredibles games.  While they weren't offsetting it and breaking shadows like the other games, there's still an offset in the upper left corner of the screen, which is noticeable at 3x IR or higher.  This fixes that, and has no effect at 1x IR, so it's safe to enable by default.
=> GameINI: Add Vertex Rounding to Scooby-Doo: Night of 100 Frights

Source/Core/Common/MsgHandler.cpp, Source/Core/Common/MsgHandler.h, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/UICommon/UICommon.cpp
Prompted by https://dolphin.ci/#/builders/24/builds/985
A 1-character typo in a recent PR caused FifoCI builds to break
horribly and spew millions of panic alerts until buildbot crashed.
This PR adds a new config option -- defaulting to off -- that allows
Dolphin to abort early on when a panic alert occurs instead of
continuing forever.
=> Add an option to abort when a panic alert occurs

Source/Core/Core/PowerPC/Gekko.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp
Provides the same behavior, while also preventing undesirable type conversions and promotions on bitfield members in certain cases.
e.g.
```cpp
union Thing
{
u32 hex = 0;
struct
{
u32 value_1 : 5;
u32 padding : 27;
};
};
void SomeFunction(const Thing& thing)
{
// Assume the encoding stores some value - 1, so we add to get the full value
const u32 data = thing.value_1 + 1;
}
```
The intuitive (and completely expected most of the time) reading of this would be to think that `value_1` undergoes no type promotions or conversions, since everything is unsigned, however, this line:
```cpp
const u32 data = thing.value_1 + 1;
```
Actually results in `value_1` being converted to an `int`, incremented, and then assigned to data, implicitly converting it back to a `u32`
`UGQR` was already using this …
=> Gekko: Migrate register structs over to Common::BitField

Source/Core/Core/HW/DSPHLE/DSPHLE.cpp, Source/Core/Core/HW/DSPHLE/DSPHLE.h, Source/Core/Core/HW/DSPHLE/UCodes/AX.cpp, Source/Core/Core/HW/DSPHLE/UCodes/AX.h, Source/Core/Core/HW/DSPHLE/UCodes/AXWii.cpp, Source/Core/Core/State.cpp
Fixes audio breaking if you load a state while a non-AX ucode is running.
=> DSPHLE: Minor cleanup & savestate fix for AX coefficients.

Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_Branch.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_FPUtils.h, Source/Core/Core/PowerPC/Interpreter/Interpreter_FloatingPoint.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_Integer.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStore.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_LoadStorePaired.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_Paired.cpp, Source/Core/Core/PowerPC/Interpreter/Interpreter_SystemRegisters.cpp
Makes our conversions between different signs and cases where truncations would occur to be explicit to indicate that they're intentional and, well, make implicit conversions explicit for reading purposes, which I think is preferable for the interpreter, given it essentially partially doubles as a reading reference for faster CPU backends to base behavior off of in tandem with other documenation. This also resolves numerous compiler warnings when stricter conversion warnings are enabled.
Note that we have a bunch of seemingly... old history tracing code in Interpreter.cpp, if this isn't particularly useful, I'm fine with completely removing it, since it'd make the interpreter's Run() member function a little more compact and nicer to read without the ifdefs.
=> Interpreter: Make signedness and narrowing conversions explicit

Source/Core/DolphinQt/CMakeLists.txt, Source/Core/DolphinQt/DolphinQt.vcxproj, Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/Core/DolphinQt/Settings/AudioPane.cpp, Source/Core/DolphinQt/Settings/BroadbandAdapterSettingsDialog.cpp, Source/Core/DolphinQt/Settings/BroadbandAdapterSettingsDialog.h, Source/Core/DolphinQt/Settings/GameCubePane.cpp, Source/Core/DolphinQt/Settings/GeneralPane.cpp, Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.cpp, Source/Core/DolphinQt/Settings/WiiPane.cpp
During the (ongoing) review of the Brazilian Portuguese translation, I noticed various minor consistency issues with the main Settings window, and this PR fixes all of them. Here's a breakdown of what changed (with screenshots):
* Fixed Fallback region dropdown list misalignment in comparison to the other dropdown lists from this tab
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
* Fixed inconsistent usage of the ms and percent units (e.g. **20ms** and **100 %** instead of **20 ms** and **100%**)
* Removed ms abbreviation from the latency tooltip, to make it consistent with the buffer size tooltip where it's not abbreviated
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
* Made the dropdown lists …
=> DolphinQt: Minor consistency fixes for the Settings window

Data/Sys/GameSettings/GR6.ini, Data/Sys/GameSettings/GVD.ini, Data/Sys/GameSettings/R5F.ini, Data/Sys/GameSettings/R8R.ini, Data/Sys/GameSettings/RB5.ini, Data/Sys/GameSettings/RB9.ini, Data/Sys/GameSettings/RCK.ini, Data/Sys/GameSettings/RI8.ini, Data/Sys/GameSettings/RNO.ini, Data/Sys/GameSettings/RRL.ini, Data/Sys/GameSettings/RRT.ini, Data/Sys/GameSettings/RSJ.ini, Data/Sys/GameSettings/RVA.ini, Data/Sys/GameSettings/ST6.ini
Mostly fixes for Wii games # - B
Some fixes to dual core issues, EFB Copies to Texture and Ram, Defer EFB Copies to RAM issues and Texture Cache Accuracy issues.
=> Various GameINI Updates

Source/Core/Core/DSP/Interpreter/DSPInterpreter.cpp
Previously, when calling `RunCycles(1)` we would actually run two instructions. (We currently assume that all instructions take one cycle.)
=> DSPInterpreter: fix off-by-one errors in cycle counting

Source/Core/Core/PowerPC/BreakPoints.cpp, Source/Core/Core/PowerPC/BreakPoints.h, Source/Core/Core/PowerPC/MMU.cpp
Previously in Read_U64 and Write_U64 the value that was read or written would be truncated to a 32-bit value before being passed off to the memcheck handler, which can result in incorrect values being logged out.
=> MMU: Don't truncate 64-bit values when calling Memcheck()

Source/Core/Core/PowerPC/Gekko.h, Source/Core/Core/PowerPC/MMU.cpp, Source/Core/Core/PowerPC/PowerPC.h
This moves the split PTE definition unions into Gekko.h and eliminates the need for several macro definitions in the MMU code, since we can use the register unions to access the relevant info.
This also fixes the layout of the SDR1 union, which has been incorrect (from a little-endian POV) since it was introduced.
Each commit should be fairly self-isolated for review
=> MMU: Tidy up PTE-related code

Source/Core/DolphinQt/Settings.cpp
Fixes [12623](https://bugs.dolphin-emu.org/issues/12623).
=> DolphinQt: Make Windows tab bar scroll buttons opaque

Source/Core/DolphinLib.props, Source/Core/DolphinLib.vcxproj
It was accidentally put into the main DolphinLib.vcxproj in #9566.
=> msbuild: Move DivUtils to DolphinLib.props

Source/Core/VideoCommon/BPMemory.h, Source/Core/VideoCommon/ConstantManager.h, Source/Core/VideoCommon/PixelShaderGen.h
Avoids placing generic names in the surrounding namespace.
=> BPMemory: Make ZTexOp enum an enum class

Data/Sys/GameSettings/GGV.ini, Data/Sys/GameSettings/GIC.ini, Data/Sys/GameSettings/GIH.ini, Data/Sys/GameSettings/GIQ.ini, Data/Sys/GameSettings/GQP.ini
BFBB tends to crash when dual-core is enabled. Interestingly enough, this does not happen on 5.0 stable (actually, the loads are more accurate to an actual Gamecube on stable as well, but that's a different issue).
The main issue is that randomly while playing the game with dual-core enabled, the game will crash with a FIFO error. Disabling dual-core fixes the issue. I have seen many people ask why BFBB is giving them a FIFO error randomly, and every time they are able to fix it by disabling dual-core. Therefore, I believe it should be disabled by default for this game.
=> Disable Dual Core by default for multiple Heavy Iron games

Source/Core/Core/PowerPC/JitArm64/JitArm64_RegCache.cpp
Fixes a regression from PR #7155.
The GPR `allocation_order` is initialized with only 28 elements, so the 29th element ends up getting zero initialized. Very sneaky bug...
=> JitArm64: Fix W0 being present twice in register cache

Source/Core/VideoCommon/ShaderGenCommon.cpp, Source/Core/VideoCommon/ShaderGenCommon.h, Source/Core/VideoCommon/UberShaderVertex.cpp, Source/Core/VideoCommon/VertexShaderGen.cpp
This adjusts the NaN replacement logic introduced in #9928 to work around the HLSL compiler optimizing away calls to isnan, which caused that functionality to not work with ubershaders on D3D11 and D3D12 (it did work with specialized shaders, despite a warning being logged for both; that warning is also now gone).  Note that the `D3DCOMPILE_IEEE_STRICTNESS` flag did not solve this issue, despite the warning suggesting that it might.
Suggested by @kayru and @jamiehayes.
=> Use custom isnan implementation to avoid HLSL optimizer issues

Source/Core/Core/PowerPC/JitCommon/JitCache.cpp
No clue if this is actually a relevant performance increase or bottleneck but it's something I realized we aren't doing anywhere. Without this the fast check detects more cachelines as valid than there actually are.
=> PowerPC/JitCache: Clear valid_block bits for long invalidations.

Source/Core/Core/PowerPC/JitArm64/JitArm64_LoadStorePaired.cpp
This is a proper fix for the issue that PR #10052 was a workaround for. It wasn't some kind of bug in the register cache that had laid dormant, it was a simple mistake made in PR #10036.
=> JitArm64: Move psq_stXX GetCallerSavedUsed calls later

Source/Core/DolphinQt/CheatsManager.cpp, Source/Core/DolphinQt/ConvertDialog.cpp, Source/Core/DolphinQt/GBAWidget.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/ResourcePackManager.cpp
A few tweaks to the existing strings to make them a little more consistent
=> DolphinQt: Minor localization changes

Source/Core/Core/ActionReplay.cpp, Source/Core/Core/ActionReplay.h, Source/Core/Core/GeckoCodeConfig.cpp, Source/Core/Core/GeckoCodeConfig.h, Source/Core/Core/PatchEngine.cpp, Source/Core/Core/PatchEngine.h, Source/Core/DolphinQt/Config/CheatCodeEditor.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/DolphinQt/Config/PatchesWidget.cpp
Some refactoring to prepare for my upcoming Android cheats PR. I figured it would make sense to submit this as a separate PR, since C++-heavy and Java-heavy PRs tend to get reviewed by different people.
=> Split out code for serializing/deserializing cheat lines

Source/Core/VideoCommon/UberShaderVertex.cpp, Source/Core/VideoCommon/VertexShaderGen.cpp
Fixes https://bugs.dolphin-emu.org/issues/12620
The changed code did not match the corresponding code in VertexShaderGen.  Some parts of the sky have 2 color channels in each vertex, while others only have 1, despite only color channel 0 being used and XFMEM_SETNUMCHAN being set to 1 for both of them.  The old code (from #4601) caused channel 0 to be set to channel 1 if the vertex contained both color channels but the number of channels was set to 1, which is wrong.
This code was also a bit funky because the [per-pixel-lighting code below](https://github.com/dolphin-emu/dolphin/blob/128e1029ddf09258dd476e8c5cc9fda9e85c2936/Source/Core/VideoCommon/VertexShaderGen.cpp#L463-L483) also affects things, but the same code existed in ubershaders.  I've tidied up the redundancies there.
=> UberShaderVertex: Fix Tony Hawk Pro Skater 4

Data/Sys/GameSettings/GNM.ini
See https://bugs.dolphin-emu.org/issues/12658 for details.
This restores the performance back to 5.0 levels, though it's still not 100% perfect. Probably the best we can do for now though.
=> GameINI: Disable JIT branch following for Namco Museum.

Externals/hidapi/applied_patches/0003-hidapi-Stop-current-run-loop-in-removal-callback-ins.patch, Externals/hidapi/applied_patches/0004-hidapi-Don-t-leak-device-handle-in-macOS-10.10-or-ne.patch, Externals/hidapi/mac/hid.c, Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp
When disconnecting a Wiimote on macOS (whether by the Bluetooth menu, by pulling out the batteries, etc...), Dolphin may crash in hidapi code.
The first commit changes the device removal callback to use ``CFRunLoopGetCurrent()`` instead of getting the run loop ref from the context. For whatever reason (macOS bug?), while the callback is deregistered for closed ``hid_device``s in ``hid_close()``, IOKit may occasionally call the callback with ``hid_device`` pointers that have already been closed and ``free``'d. Because the device removal callback is always ran on the device's run loop, it is safer to use ``CFRunLoopGetCurrent()`` instead of accessing ``context->run_loop``.
The second commit [ports a patch](https://github.com/libusb/hidapi/commit/cdc473dfe43f6432dda7ad53d7656b8ae8ff968b) …
=> WiimoteReal: Fix Wiimote disconnection causing Dolphin to crash on macOS

Source/Core/Core/HW/SI/SI.cpp
Migrates the SI register union bitfields over to Common::BitField for consistency with the rest of the codebase.
While we're in the same area, we can simplify a trivial conditional
=> SI: Migrate bitfields to Common::BitField

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp
`fpr.RW` may clobber GPRs that are not locked. Fixes https://bugs.dolphin-emu.org/issues/12656.
=> JitArm64: Fix fresx/frsqrtex unlocking W0 too early

Source/Core/Common/GL/GLInterface/WGL.cpp
When RenderDoc is attached, `wglShareLists` fails for some reason (see baldurk/renderdoc#2361).  `wglCreateContextAttribsARB` has a parameter for the share context, so there's no reason to use a separate `wglShareLists` call.
Note that using OpenGL in Dolphin with RenderDoc still has a separate issue with this patch where the screen appears black initially.  This has been fixed on RenderDoc's side, but it seems to be possible to work around it by starting a game/fifolog, then closing it, then starting it again.
This patch is from https://github.com/baldurk/renderdoc/issues/2361#issuecomment-919342173.
=> GLInterface: Remove unneeded wglShareLists call

Source/Core/DiscIO/DirectoryBlob.cpp
If someone passes an offset past the end of a file but before the start of another file to `DiscContentContainer::Read()`, the `PadToAddress()` call completely fills the buffer with zeroes and reduces the length to 0, but the code flow then tries to call `it->Read()` anyway, triggering a debug assert about an out-of-bounds offset.
To easily observe this just launch an extracted game in a Debug build, the read from `VolumeDisc::IsNKit()` is between files in our built disc layout.
=> DiscIO/DirectoryBlob: Handle reads between files.

Source/Core/VideoCommon/BPStructs.cpp
Previous code from #7950 only clamps correctly when the efb copies left and top coordinates are (0, 0)
Now we should handle all situations.
Spyro: A hero's tail is an example of a game that does an oversized EFB copy with a non-zero origin.
=> BPStructs: fix out-of-range EFB copy clamping

Data/Sys/GameSettings/GXG.ini
This fixes https://wiki.dolphin-emu.org/index.php?title=Mega_Man_X_Collection#Odd_Grid
=> GameINI: Disable force texture filtering for Mega Man X Collection

Source/Core/VideoCommon/BPStructs.cpp
Regression from #10095
Apparently Mario Kart Wii in wifi mode can generate a deformed EFB copy of size 4x4 at offset (328,1020) with stride 64.
This seems to be completely malformed. Lets just skip it all together.
=> BPStructs: Ignore malformed efb copies

Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoCommon/DriverDetails.cpp, Source/Core/VideoCommon/DriverDetails.h
Based on #9783.
For whatever reason, attempting to access `gl_SubgroupInvocationID` causes `MTLCompilerService` to crash in LLVM code. This breaks bounding box. A crash log has been attached [here](https://bugs.dolphin-emu.org/issues/12667#note-2).
The relevant excerpt is as follows:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fffb1d44a50
Exception Note:        EXC_CORPSE_NOTIFY
[...]
Thread 1 Crashed:
0   ???                           	0x00007fffb1d44a50 0 + 140736176867920
1   libLLVM.dylib                 	0x00007fff68d6ddf9 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 1573
2   libLLVM.dylib                 	0x00007fff68d6cfd1 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + …
```
=> VulkanContext: Disable subgroup reduction on Macs with AMD GPUs

Source/Core/VideoCommon/BPStructs.cpp
I Missed this side effect when fixing crash in Mario Kart Wii wifi
Hopefully this fixes the bug in Paper Mario
=> BPStructs: ensure side effects are same

Source/Core/DolphinQt/Debugger/NetworkWidget.cpp
Like PR #8231 but for NetworkWidget (which was added later).
=> DolphinQt: Don't update NetworkWidget when hidden

Data/Sys/GameSettings/GWK.ini
The game has extra XFB copies in some menus, messing up framepacing on VRR monitors and breaking vsync in general.
=> Disable Immediate XFB in King Kong

Source/Core/Core/IOS/IOS.cpp
On a real Wii, these constants are normally written by the system menu
(maybe even as part of common SDK code?)
However, they're cleared by IOS whenever a PPC title is launched.
IOS memsets 0x0-0x3fff and then manually writes some constants
in low MEM1. PR #4723 added most of the writes in the 0x31xx region
but left out the four writes to the legacy constant region.
Previously Dolphin didn't actually clear 0-0x3fff so those constants
would stick around after a system menu execution.
011f7789e0 exposed those missing writes.
=> IOS: Add missing writes of low MEM1 constants

Source/Core/Core/CheatSearch.cpp
Small thing I overlooked. If you enter a cheat search with a region length smaller than the value length you're searching for, you may end up underflowing the length, practically deadlocking the emulator.
=> Core/CheatSearch: Avoid length underflow on new search.

Source/Core/Core/Core.cpp, Source/Core/Core/Core.h
It's only used for frame stepping. We can use s_frame_step instead.
=> Core: Remove s_request_refresh_info

Source/Core/DiscIO/DirectoryBlob.cpp, Source/Core/DiscIO/DiscExtractor.cpp, Source/Core/DiscIO/DiscScrubber.cpp, Source/Core/DiscIO/DiscUtils.h, Source/Core/DiscIO/VolumeWii.cpp, Source/Core/DiscIO/VolumeWii.h
I noticed a lot of these were duplicated across various files, figured it makes sense to collect them in one place.
=> Core/DiscIO: Extract disc and partition constants to DiscUtils.h.

Source/Core/DolphinQt/QtUtils/QueueOnObject.h, Source/Core/DolphinQt/TAS/TASInputWindow.cpp
Fixes https://bugs.dolphin-emu.org/issues/12676.
Needs testing to see if this impacts performance when controller inputs are changing.
=> DolphinQt: Reduce latency of TAS input's controller input passthrough

Source/Core/DolphinQt/CheatsManager.cpp, Source/Core/DolphinQt/CheatsManager.h, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/GeckoCodeWidget.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/MenuBar.h
Fixes some annoyances pointed out by @Dentomologist back in #9886.
Specifically:
- The Cheats Manager option is no longer mysteriously greyed out if no game is running or if cheats are disabled and is instead always active.
- If no game is running the code tabs are greyed out instead of completely missing.
- If cheats are disabled and the "Warning: Cheats are disabled! [Configure Dolphin]" header thing shows (as the equivalent tabs in the game properties), the button now actually works -- it didn't before. Granted, it was rather hard to even reach this window in that situation (you'd have to start a game, open the window, close the game, then disable cheats without closing the window), but either way, it works correctly now.
- This also now allows running memory searches even if cheats …
=> Cheats Manager UX improvements.

Source/Core/Common/FileUtil.cpp, Source/Core/Common/FileUtil.h
Noticed this during debugging. This causes an inconsistency between the path returned in the 'root' directory node and the path returned in all child directory nodes.
Before:
Note how the `rootEntry.physicalName` ends in a trailing slash but all child directories do not, and how all child names have a `//` after `files`.
After:
I hope no one is relying on this behavoir somewhere...
=> Common/FileUtil: Strip trailing path separator in ScanDirectoryTree().

Source/Core/Core/HW/MemoryInterface.cpp
Continues the migration of low hanging fruit over to Common::BitField
While we're in the area, we can get rid of some trivial implicit sign conversions
=> MemoryInterface: Migrate bitfields over to Common::BitField

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_Integer.cpp
=> JitArm64: Optimize divwx

Source/Core/DolphinQt/TAS/StickWidget.cpp
This PR creates a light gray box around ellipses in the StickWidget. This mimics the old GUI and is useful as it allows TASers to identify the edges of the interactive stick area when clicking outside of the circle.
5.0
5.0-15224
This PR
=> StickWidget: Inscribe stick circle within a square

Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.h
This PR fixes leading nul bytes being ignored in hex search. It also simplifies and deduplicates some of the code logic.
=> MemoryWidget: Simplify the search logic

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java, Source/Android/jni/MainAndroid.cpp
The purpose of this class is to keep track of state which the emulation core is also keeping track of. This is rather risky – if we update the state of one of the two without updating the other, the two become out of sync, leading to some rather confusing problems. I think we're better off only keeping this state in the emulation core.
In particular, this change fixes a panic alert deadlock when booting a file that isn't a valid GC/Wii file while holding the phone in an orientation which does not match the orientation set in the Dolphin settings.
=> Android: Remove the EmulationState class

Source/Core/DolphinQt/HotkeyScheduler.cpp
There are certain hotkeys that we absolutely want to be able to use without being in-game. Presently, no hotkeys are recognized unless we are in-game.
I've identified and moved the following hotkeys to be checked before the HotkeyScheduler checks to see if the Core is running:
- _Open_
- _Exit_
- _Start Recording_
- _Refresh Game List_
Note that _Play Recording_ should also be implemented here, however it looks like there is no signal for a PlayRecording() function, so this will have to be handled in a later PR once that signal is created and implemented.
=> HotkeyScheduler: Check for certain hotkeys in game list

Source/Core/VideoCommon/RenderBase.cpp
Previously, when playing back a movie, you could not see the total frame count of a movie, only the total number of input polls.
This change simply shows the total frame count on movie playback.
Note that this change also results in the framecount and framecount total ALWAYS being displayed if show_movie_window is true, regardless of whether or not m_ShowFrameCount is true. I believe this is fine, as TASers are much more likely to reference the framecount than the input poll count.
=> RenderBase: show total framecount on movie playback

Source/Core/Core/Core.cpp
Previously, only the number of total input polls would be shown in the window title when playing back a movie. This simply adds the VI / frame count total as well, which is a much more relevant number to look at while TASing.
=> Core: UpdateTitle with total framecount on recording playback

Source/Core/DolphinQt/MainWindow.cpp
Previously, the file dialog window was ambiguous between saving or loading a .dtm. This commit simply gives a bit more context to differentiate the two windows.
=> QFileDialog: differentiate between recording open/save

Source/Core/DolphinQt/HotkeyScheduler.cpp, Source/Core/DolphinQt/HotkeyScheduler.h, Source/Core/DolphinQt/MainWindow.cpp
This hotkey was not previously implemented in the scheduler, even though it's present in the hotkey menu.
=> HotkeyScheduler: add PlayRecording hotkey support

Source/Core/VideoCommon/RenderBase.cpp
Just to stay consistent, I believe it is best to show total input polls alongside the framecount if m_ShowFrameCount is true.
=> RenderBase: Show input count on m_ShowFrameCount

Source/Core/Core/Movie.cpp
Previously, s_temp_input was being used for BOTH the savestate's and the movie's input printout in the panic alert.
This commit simply performs memcpy from the correct vector for the movInput printout.
=> Movie: display correct input difference on movie mismatch

Source/Core/VideoCommon/VertexLoaderARM64.cpp
not sure why this diverged from x64 version of the file, seems to have been copy pasted at some point.
=> fix unused variable warning

Source/Core/DolphinQt/CheatSearchWidget.cpp
This string is extremely likely to be mistranslated without the proper context. Actually, it's probably impossible to translate this string in a good way to some languages, but I'm not sure how to solve that. Let's at least add an i18 comment for now.
=> DolphinQt: Add i18n comment for "Keep addresses where value in memory"

Source/Core/Common/MsgHandler.cpp
PR #10066 added functionality to call std::abort when a panic alert occurs; however, that PR only implemented it for `MsgAlert` and not `MsgAlertFmtImpl`, meaning that the functionality was not used with `PanicAlertFmt` (only `PanicAlert`, which is not used frequently).
=> Fix AbortOnPanicAlert with PanicAlertFmt

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/ConvertFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/GameFile.java, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/GameList/GameFile.cpp, Source/Core/DolphinQt/ConvertDialog.cpp, Source/Core/UICommon/GameFile.h
Yes, that's right! It's time to add even more NKit warnings, because users still don't understand what NKit is or how it works!
More specifically, some users seem to be under the impression that converting an NKit file to for instance RVZ using Dolphin's convert feature will result in a normal RVZ file, when it in fact results in an NKit RVZ file (since NKit is not a container format in the sense that GCZ/WIA/RVZ/WBFS/CISO is, but rather a kind of trimmed ISO). I can hardly blame users for not knowing this, because it's not intuitive unless you know the technical details of how NKit works.
=> DolphinQt/Android: Add warning when converting NKit files

Source/Core/DolphinQt/Config/Mapping/IOWindow.cpp
In the current Dolphin dev, typing anything into a hotkey formula box and clicking OK would prompt you with a syntax error window, only for your gibberish to be accepted as input. After closing out of the error window, your change would be applied and the formula window would close.
This PR fixes two issues, the latter of which is only exposed when the former is fixed.
1) Do not accept on hotkey syntax errors
- Pressing okay on the warning window when receiving a syntax error will still call accept() in the IOWindow. Thus, your syntactically incorrect changes will still be applied.
2) Do not overwrite hotkey config on window close
- With step 1 resolved, this then exposes the issue where the hotkey expression is already updated by the point that you hit "OK', regardless of whether or not …
=> IOWindow: Do not accept on syntax errors

Source/Core/DolphinQt/RenderWidget.cpp
This was originally intended to fix https://bugs.dolphin-emu.org/issues/12717 but this ended up not being the issue (instead it seems like files just weren't recompiled when imgui was updated due to MSVC weirdness).  Still, using brackets instead of quotes is preferable as this is a library include.
(Note that this PR is the same as #10191; I attempted to rename the branch while maintaining the pull request per [these instructions](https://stackoverflow.com/a/65799489) but it seems like that doesn't work for PRs from a fork.)
=> RenderWidget: Change "imgui.h" to <imgui.h>

Externals/discord-rpc/src/discord-rpc.vcxproj
The file is located at <code>Externals/discord-rpc/<ins>include/</ins>discord_register.h</code>, not `Externals/discord-rpc/discord_register.h`.  This didn't affect building (I think because of `..\include` being in `<AdditionalIncludeDirectories>`), but it did break trying to open `discord_register.h` in Visual Studio.
=> Externals/discord-rpc: Fix reference to discord_register.h

Source/Core/Core/HLE/HLE.cpp, Source/Core/Core/HLE/HLE.h, Source/Core/DiscIO/RiivolutionPatcher.cpp
This PR should fix HLE hooks overlapping Riivolution patches: https://github.com/dolphin-emu/dolphin/pull/10186#issuecomment-955634792
This should be thoroughly tested. Depending on the mods `HBReload` and `GeckoCodehandler` hooks can be overlapped.
I'm also open to other alternatives to fix this HLE over HLE issue.
=> HLE: Fix hooks overlapping Riivolution patches

Data/Sys/GameSettings/R44.ini
Suzumiya Haruhi no Heiretsu drops certain characters in medium texture cache, so it needs safe.  Considering other issues of this sort and the performance of the game, it seems like 0 is probably fine.
=> GameINI:  Change Texture Cache to Safe in R44J8P

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
The division by 2 case can be improved ever so slightly by using eax when possible to isolate the sign bit. This saves a byte when the destination ends up as r8-15, because those require a REX prefix.
I also improved the comments a little in this area.
---
Before:
```
41 8B C5             mov         eax,r13d
41 C1 ED 1F          shr         r13d,1Fh
44 03 E8             add         r13d,eax
41 D1 FD             sar         r13d,1
```
After:
```
41 8B C5             mov         eax,r13d
C1 E8 1F             shr         eax,1Fh
44 03 E8             add         r13d,eax
41 D1 FD             sar         r13d,1
```
=> Jit64: divwx - One more micro-optimization

Source/Core/Common/CMakeLists.txt, Source/Core/Common/CRC32.cpp, Source/Core/Common/CRC32.h, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp, Source/Core/DolphinLib.props, Source/Core/DolphinQt/GameList/GameListModel.cpp, Source/Core/DolphinQt/QtUtils/SignalDaemon.cpp, Source/Core/DolphinQt/Resources.cpp, Source/Core/DolphinQt/Resources.h, Source/Core/DolphinQt/Settings/GameCubePane.cpp, Source/Core/UICommon/GameFileCache.cpp, Source/Core/VideoCommon/BoundingBox.cpp, Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/CommandProcessor.h, Source/Core/VideoCommon/FrameDump.cpp
These are all mostly obvious.
The main remaining ones are:
- `DSP::SDSP` not being pod yet `offsetof()` being used on it, same for `memcpy()` on `CPMemory`.
- Some signed comparison issues where I’m not sure in which direction to cast.
- Some invalid size copies in `IOS/ES/Formats.cpp` which made me notice the addition of `ticket_version` in `Ticket` which isn’t there in `TicketView`, making me wonder just how this ever worked.
=> Fix some warnings found with gcc 11 and ffmpeg master

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Tables.cpp
As a FCVTS instruction that uses the current rounding mode does not exist on ARM64, the easiest way to implement fctiwx would be to first convert to an integral floating point using the native rounding mode, then converting that value to an integer (rounding mode doesn't matter in this second step as result would be exact).
TODO is [the same TODO as in the Jit64 backend](https://github.com/dolphin-emu/dolphin/pull/372/files#diff-2a89ab810baa62f5f81459187a693d35d3d4bc03fce2f190047c9e78b00d9e87R291).
Tested in FZGX.
=> JitArm64: Implement fctiwx

Source/Core/Core/MachineContext.h
`__x` is only 29 elements in size ([Reference: _struct.h](https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/osfmk/mach/arm/_structs.h#L155)).
`__x[30]` happens to alias to `__lr`, but relying on that is silly.
=> MachineContext: Correct CTX_LR for Apple ARM64

Source/Core/AudioCommon/AudioCommon.cpp, Source/Core/Common/SettingsHandler.cpp, Source/Core/Core/Core.cpp, Source/Core/VideoCommon/FrameDump.cpp
fmt::localtime is also less awkward to use compared to std::localtime.
=> Use fmt::localtime instead of thread-unsafe std::localtime

Data/Sys/GameSettings/RMHJ08.ini, Data/Sys/GameSettings/ROM.ini
This PR fixes text corruption issues on Japanese Monster Hunter games, similarly to https://github.com/dolphin-emu/dolphin/pull/10196.
Without it:
- NPC dialogs are displayed with wrong/corrupted characters.
- The online login progress bar displays the wrong percentage number (sometimes beyond 100%).
- It corrupts the on-screen keyboard used for chatting online.
=> GameINI: Change Texture Cache to Safe in RMHJ08.ini and ROM.ini

Readme.md, Source/Core/Common/SCMRevGen.vcxproj, Source/Core/Core/PowerPC/JitArm64/JitArm64_SystemRegisters.cpp, Source/PCH/pch.h, Source/VSProps/Base.Macros.props, Source/VSProps/Configuration.Base.props, Source/dolphin-emu.sln
bumps some version numbers so the build will use vs2022 toolchain.
The buildbot is already using vs2022 (but v142 toolset will be used for existing PRs) / latest sdk for all builds.
=> msvc: update to vs2022 and windows sdk 10.0.22000

CMakeLists.txt, Externals/MoltenVK/CMakeLists.txt, Externals/MoltenVK/version.txt, Source/Core/DolphinQt/CMakeLists.txt, Source/Core/VideoBackends/Vulkan/VulkanLoader.cpp
Changes the build system to build MoltenVK instead of having a dylib in the repository. This also opens up the opportunity to modify MoltenVK to our needs if needed.
Also, the MoltenVK version has been updated to v1.1.5 (Vulkan SDK 1.2.189).
~~**EDIT**: This PR is being blocked by the presence of the Intel macOS buildbot (``pr-osx-x64``). The M1 Mac Mini can build MoltenVK perfectly fine for both Intel and ARM, so the Intel buildbot needs to be shut down before can be merged.~~
=> MoltenVK: Use an external project instead of a pre-compiled dylib

Source/Android/app/build.gradle
This should make C++20 and `std::filesystem` work. (Not that we really can use `std::filesystem` much on Android since it doesn't work with scoped storage...)
=> Android: Bump NDK and CMake versions

Source/Core/Core/DSP/DSPCore.cpp
These messages apply to the User directory regardless of whether it's global or local, so we shouldn't specify "global".
Also changing "directory" to "folder", just for consistency with "GC folder" in the same sentence.
=> DSP: Reword inappropriate references to Global User Directory

Data/Sys/GameSettings/GP6E01.ini, Data/Sys/GameSettings/GP7E01.ini
It appears that this code is a Gecko Code and was mistakenly put as an Action Replay code.  I may be wrong and it may be a different problem, but based on the how the code looks I'm confident this was the problem.  The code didn't crash the game when I moved it to Gecko, and it was causing problems when it was under Action Replay.
=> GameINI: Fix Comment Causing Parsing Errors in Mario Party 6/7 INIs.

Source/Core/DolphinQt/DolphinQt.vcxproj, Source/VSProps/Base.props, Source/VSProps/QtCompile.props
Revert usage of ExternalIncludePath, as that var is specifically
for external includes which do not get scanned for changes.
Instead, use /external:anglebrackets , which causes anything `#include`d with `<>` to be considered "external" (for adjusting warning level only - not affecting out-of-date checking).
=> msbuild: use /external:anglebrackets

Source/Core/VideoCommon/BPStructs.cpp
This fixes the pink screens in EA Sports Active.  See https://gist.github.com/Pokechu22/49455f9094ed0ff017da64e3f7aa0404 for details.
This will also need to be implemented for the software renderer, which has its own implementation of EFB copies.  Unfortunately it doesn't seem like there is a quick fix for it, as the relevant code (in [TextureEncoder.cpp](https://github.com/dolphin-emu/dolphin/blob/2c5d11cacebe05450ee4c5d276044e110ed286c1/Source/Core/VideoBackends/Software/TextureEncoder.cpp#L1423), while XFBs are in [EfbInterface.cpp](https://github.com/dolphin-emu/dolphin/blob/2c5d11cacebe05450ee4c5d276044e110ed286c1/Source/Core/VideoBackends/Software/EfbInterface.cpp#L556)) is pretty complicated.
=> VideoCommon: Use the copy filter for EFB copies as well as XFB copies

Source/Android/app/src/main/AndroidManifest.xml, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameAdapter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/adapters/GameRowPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/GameDetailsDialog.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/Settings.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/ConvertFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheManager.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/SyncProgramsJobService.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
The past few Android releases have been adding restrictions to what services are allowed to do, for the sake of stopping services from using up too much battery in the background. The IntentService class, which GameFileCacheService uses, was even deprecated in Android 11 in light of this.
Typically, the reason why you would want use a service instead of using a simple thread or some other concurrency mechanism from the Java standard library is if you want to be able to run code in the background while the user isn't using your app. This isn't actually something we care about for GameFileCacheService – if Android wants to kill Dolphin there's no reason to keep GameFileCacheService running – so let's make it not be a service.
I'm changing this mainly for the sake of future proofing, but …
=> Android: Make GameFileCacheService not be a service

Data/Sys/GameSettings/GALE01r0.ini
Same problem as PR #10201... Except instead of just making the comments use #, I'm actually removing some of the codes entirely because they are of questionable value.
Should fix https://bugs.dolphin-emu.org/issues/12737.
=> GameINI: Fix comments causing errors in GALE01r0.ini

Data/Sys/GameSettings/GJB.ini
This game requires emulating the Fifo Pipeline or have Single Core be able to read ahead in the Fifo.  Because Single Core currently processes things in a serialized manner, this game will not run regardless of CPU/GPU timing hacks.
This was previously attempted a few years ago in Single Core, but was not merged due to performance being ~15% slower.
=> Force Dual Core on for Bomberman Jetters

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/AppLinkActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/services/GameFileCacheManager.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/platform/PlatformGamesFragment.java
This gets rid some uses of the deprecated LocalBroadcastManager.
=> Android: Make GameFileCacheManager use LiveData

Source/Core/VideoBackends/Software/EfbInterface.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp
This fixes horizontal lines in the bloom effect of Spyro: A Hero's Tail which is a regression caused by PR #10204.
<details><summary>Screenshot of regression</summary>
</details>
<details><summary>Fixed</summary>
</details>
Spyro uses an 640x80 pixel sub-buffer within the EFB to calculate
it's bloom effects, which it places below the main 640x448 buffer.
<details><summary>EFB layout</summary>
Note: Colors are wrong because the main color buffer uses RGBA6, while the bloom is calculated in RGB8
</details>
This allows it to do bloom without backing up part of the EFB to
main memory, as most games do.
But, since some of the sub-buffers used in the bloom effect are taller
than 80 pixels, they need to be sliced up into smaller sub, sub buffers
which get combined later when copied to main …
=> Fix copy filter clamping

Source/Core/DiscIO/RiivolutionPatcher.cpp
Should fix https://bugs.dolphin-emu.org/issues/12738
=> RiivolutionPatcher: Use case-insensitive filename comparison when searching for files in a folder patch.

Source/Core/Common/Arm64Emitter.cpp, Source/Core/Common/Arm64Emitter.h, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.h, Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64Cache.h, Source/Core/Core/PowerPC/JitArm64/JitArm64_BackPatch.cpp, Source/UnitTests/Core/PowerPC/JitArm64/ConvertSingleDouble.cpp
JitArm64 port of PR #8765. Fixes https://bugs.dolphin-emu.org/issues/11717.
=> JitArm64: Codegen space reuse

Data/Sys/GameSettings/GLZ.ini, Data/Sys/GameSettings/RWG.ini
This is to enable MMU for a couple games.
"007: From Russia with Love" requires MMU to display in-game menus. Otherwise they are black. Also I have enabled medium texture cache to fix the jittery intro video.
"We Love Golf!" crashes without full MMU. This was apparently fixed in 5.0-540 (Dynamic bat) which is true only if MMU is enabled. Since it's not enabled by default the game should overwrite the MMU setting to work.
=> Gameini: Enable MMU for some games

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java, Source/Android/app/src/main/res/values/strings.xml
Now that we have fast MMU emulation on AArch64, there's no reason to keep excluding this from the GUI like we've been doing.
=> Android: Add MMU setting to GUI

Source/Android/app/build.gradle, Source/Android/app/proguard-rules.pro
This decreases our APK size by a few megabytes. Most of the reduction is from Java libraries that we only use small parts of. Code shrinking gets rid of all the unused code from these libraries from the APK.
Because I highly value the ability to get stack traces that make sense, I have specifically disabled obfuscation (automatic renaming of symbols to short incomprehensible names).
I've only enabled code shrinking for release builds, purely because I feel like the extra build time (30 seconds on my machine) would be annoying when you want to make debug builds rapidly.
=> Android: Enable R8 code shrinking

Source/Core/Core/HW/GBACore.cpp, Source/Core/Core/HW/GBACore.h, Source/Core/DolphinQt/GBAWidget.cpp, Source/Core/DolphinQt/GBAWidget.h
Since users seem to be very confused about where save files should go for the emulator to pick them up.
=> GBA: Add import and export save options to context menu.

Source/Core/Core/NetPlayServer.cpp
Otherwise the QoSSession destructor attempts to access the already deleted ENetHost, which appears fairly harmless but is still technically a use-after-free. (and crashes Debug builds, which is how I found it)
e: Oh, to clarify, this is relevant when the host closes the window while some clients are still connected.
=> NetPlayServer: Clear remaining m_players when netplay thread ends so that their destructors can run while the ENetHost still exists.

Data/Sys/GameSettings/RD2.ini
Red Steel 2 has FMVs that get corrupted with Anisotropic filtering.  It also hangs on dualcore.  While SyncGPU works, both another user and myself saw much smoother gameplay when using Single Core for unknown reasons.
=> Compatibility Settings for Red Steel 2

Source/Core/DolphinQt/Settings.cpp, Source/Core/InputCommon/ControllerEmu/ControllerEmu.cpp, Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp
Removed useless locks to DeviceContainer::m_devices_mutex, as they were all already protected by m_devices_population_mutex.
We have no interest in blocking other threads that were potentially reading devices at the same time so this seems fine.
This simplifies the code, and I've adjusted a few comments which mentioned possible deadlock that should now be totally gone.
The deadlock could have happen if a thread directly called EmulatedController::UpdateReferences(), while another another thread also reached EmulatedController::UpdateReferences() within a call to ControllerInterface::UpdateDevices(), as the mentioned function locked both the DeviceContainer::m_devices_mutex and s_get_state_mutex at the same time.
The deadlock was frequent on game emulation startup on Android, due to the …
=> ControllerInterface: fix UpdateReferences() deadlock

Source/Core/Common/CMakeLists.txt, Source/Core/Common/Image.cpp, Source/Core/Common/Image.h, Source/Core/Common/ImageC.c, Source/Core/Common/ImageC.h, Source/Core/Core/Config/GraphicsSettings.cpp, Source/Core/Core/Config/GraphicsSettings.h, Source/Core/DolphinLib.props, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp, Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.h, Source/Core/InputCommon/ImageOperations.cpp, Source/Core/VideoCommon/RenderBase.cpp
When using large internal resolutions, it can take a while for the image to be compressed.  This PR adds a setting to change the zlib compression level, which enables a trade-off between smaller files and faster saving.  (Since PNG is lossless, the image quality is always the same).
Libpng notes this about the compression levels:
https://github.com/dolphin-emu/dolphin/blob/890a5ed99ad4130d68b3e7228c3398445c33cdc4/Externals/libpng/png.h#L1500-L1509
Libpng presumably uses zlib's default of 6 by default:
https://github.com/dolphin-emu/dolphin/blob/890a5ed99ad4130d68b3e7228c3398445c33cdc4/Externals/zlib/zlib.h#L235-L239 
Though libpng also does have a "fast" option which uses a value of 3:
https://github.com/dolphin-emu/dolphin/blob/890a5ed99ad4130d68b3e7228c3398445c33cdc4/Externals/libpng/png …
=> Add option for setting the PNG zlib compression level

Externals/MoltenVK/CMakeLists.txt, Externals/MoltenVK/configure.sh
Currently, MoltenVK's ``fetchDependencies`` script is ran on every build. The script clones various git repositories for dependencies and rebuilds each one of them. This causes rebuild times to take significantly longer, which makes development more annoying. To fix this, don't run the script after the initial build if MoltenVK's version hasn't been updated. 
Decreases rebuild times without any changes to source code from ~250s to ~10s on an M1 Mac Mini.
=> MoltenVK: Don't run fetchDependencies unnecessarily

Source/Core/Common/Image.cpp, Source/Core/Common/ImageC.c, Source/Core/Common/ImageC.h
Fixes [broken texture dumping](https://forums.dolphin-emu.org/Thread-texture-dumping).
`PNG_FORMAT_RGB` and `PNG_COLOR_TYPE_RGB` both evaluate to 2, but `PNG_FORMAT_RGBA` evaluates to 3 while `PNG_COLOR_TYPE_RGBA` evaluates to 6; the bit indicating a palette is 1 while the bit indicating alpha is 4.
This generates an error, but because the default libpng error handler logs to stderr, it wasn't seen.  I've also added custom error handlers that put it into Dolphin's logging system.  With that, the following message now showed up (prior to fixing the above issue):
```
30:33:346 Common\Image.cpp:140 E[FRAMEDUMP]: Failed to save 852 by 480 image to C:/Users/Pokechu22/Documents/Dolphin Emulator/Dump/Textures/OHBCHB/tex1_852x480_502591290a4f95cd_6.png at level 6: 0 warnings, 1 errors
30:33:346 …
```
=> Fix saving RGBA images

Source/Core/DolphinQt/GBAWidget.cpp
It's very easy to assume the "save" in this string is a verb.
=> DolphinQt: Add i18n comment for "Save Game"

Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/FifoPlayer/FifoPlayer.h
This fixes the bad rendering on the first frame when using the software renderer: the software renderer's Z buffer started out at 0, but most games clear it to 0xffffff instead; this means that things don't render correctly except for in the regions where the screen was cleared by an EFB copy earlier in the frame.
=> FifoPlayer: Clear EFB before starting playback

Source/Core/VideoCommon/BPMemory.h, Source/Core/VideoCommon/BPStructs.cpp, Source/Core/VideoCommon/OpcodeDecoding.cpp, Source/Core/VideoCommon/PixelEngine.cpp, Source/Core/VideoCommon/PixelEngine.h
Fixes Bomberman Jetters in single core mode.
When single core mode pauses the CPU to execute the GPU
FIFO it greedily executes the whole thing. Before this commit,
Finish and Token interrupts would happen instantly, not even
taking into account how long the current FIFO window has
taken to execute. The interrupts would be effectively backdated
to the start of this execution window.
This commit does two things: It pipes the current FIFO window
execution time though to the interrupt scheduling and it enforces
a minimum delay of 500 cycles before an interrupt will be fired.
=> Delay singlecore gpu interrupts; Fixes Bomberman Jetters in single core mode.

Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/Movie.cpp, Source/Core/Core/Movie.h, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/VideoCommon/RenderBase.cpp
This PR adds a "Show Rerecord Count" toggle under the Movie menu. When enabled, this causes the RenderBase to show `s_rerecords` in the Movie window.
Note that the rerecord count will show 0 if a movie is not being recorded or playing back. I'm curious if anyone has any thoughts about if this should be hidden? Perhaps check for if `IsMovieActive()`? Or perhaps if the rerecord count doesn't update, it's a healthy reminder to TASers that they aren't actively recording a movie (I sometimes accidentally forget to check if I am in read-only mode or not).
=> Renderbase: Show rerecord count

Source/Core/Core/Boot/Boot_BS2Emu.cpp
The system menu does clear the RTC flags, but we currently aren't updating the cache file, and since we clear them the system menu doesn't know to update the cache either.  This means that launching a game via the system menu, and then launching a game directly and exiting via HOME will result in the system menu using an outdated cache and displaying the old game.  This causes it to fail to launch the game on the disc channel (since it doesn't match the cache), resulting in it resetting (though it will ignore the cache after resetting).  Not clearing the cache avoids this issue.
=> BS2Emu: Stop clearing the RTC flags

Source/Core/DolphinQt/MainWindow.cpp, Source/Core/InputCommon/ControllerInterface/ControllerInterface.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.cpp, Source/Core/InputCommon/ControllerInterface/CoreDevice.h, Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.h, Source/Core/InputCommon/ControllerInterface/DualShockUDPClient/DualShockUDPClient.cpp, Source/Core/InputCommon/ControllerInterface/Wiimote/WiimoteController.cpp, Source/Core/InputCommon/ControllerInterface/Win32/Win32.cpp, Source/Core/InputCommon/ControllerInterface/XInput/XInput.h
Fixes bug: https://bugs.dolphin-emu.org/issues/12744
Before https://github.com/dolphin-emu/dolphin/commit/e1e3db13baabefa89991388d37db0bb260c4f535 the ControllerInterface m_devices_mutex was "wrongfully" locked for the whole Initialize() call, which included the first device population refresh, this has the unwanted (accidental) consequence of often preventing the different pads (GC Pad, Wii Contollers, ...) input configs from loading until that mutex was released (the input config defaults loading was blocked in EmulatedController::LoadDefaults()), which meant that the devices population would often have the time to finish adding its first device, which would then be selected as default device (by design, the first device added to the CI is the default default device, usually the …
=> Fix default input config default device not being loaded/found

Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp
Scrolling defaults to being centered around address 0x00000000, which means addresses before the start are visible (e.g. 0xffffffa8 - 0x00000050).  However, std::clamp has undefined behavior if the low value is greater than the high value (in MSVC, this results in a failed assertion in debug mode, and returning the max value in release mode (I think).)  This essentially means that using a debug build with the code view widget enabled results in a crash every time.
The new behavior should work correctly, though I'm not 100% sure it gives correct results for a branch from, say, address 0x10 to address 0xfffffff0.  That's not something that happens often in practice, so I'm not too worried about it.
=> CodeViewWidget: Fix undefined behavior when centered around address 0

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.java
Turns out that most phones ship with a special Google version of DocumentsUI instead of just using the AOSP version, despite the two being pretty similar as far as I can tell. This change makes us check for both package names instead of just the AOSP package name.
=> Android: Fix opening system file manager

Source/Core/Core/PowerPC/JitArm64/Jit.cpp
My change in 867cd99 caused farcode to fill up much more than before. Most games still ran fine, but certain games would have multiple cache clears per minute, on top of being overall slow.
Maybe there's something prettier we can do about this than just allocating more RAM, but we have the resource budget for making Dolphin use more RAM, so I consider increasing the size of the cache to be a good solution at least for the time being.
At least for Prince of Persia: The Forgotten Sands, 48 MB isn't enough to stop the cache clears, but 64 MB is. (I only played the game for a few minutes when testing, though.)
=> JitArm64: Allocate 64 MB for farcode

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
See https://forums.dolphin-emu.org/Thread-new-5-0-15445-causes-jump-target-too-far-away-needs-force5bytes-true
I didn't do it yet, but it might be worth bisecting what change exactly caused the distance to become too long?
=> Jit64: Use farcode for exception exit in twX.

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/DolphinQt/Settings/PathPane.cpp, Source/Core/DolphinQt/Settings/PathPane.h, Source/Core/UICommon/UICommon.cpp
While the wfs path is only used for one game (DQX), it is a *huge* game.  It's nice to be able to load the files from another location easily.
Fixes:  https://bugs.dolphin-emu.org/issues/10472
=> Core / DolphinQt: make WFS directory configurable

Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Last PR for a while.
The main purpose of this PR was the final commit, wherein we implement cases where mask is 0xFF or 0xFFFF with partial register writes.
A few additional commits for other things noticed along the way, these can be split into separate PRs if desired.
Sidenotes for future optimziations: 
* Using AH/BH/CH/DH is unlikely to be sufficiently profitable due to encoding limitations.
* Using pinsrb is unlikely to be profitable due to the cost of register moves.
=> Jit_Integer: Optimize rlwimix

Source/Core/Core/PowerPC/Jit64/Jit.h, Source/Core/Core/PowerPC/Jit64/Jit64_Tables.cpp, Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
Various optimizations for `addx`/`subfx` can be applied to `addcx`/`subfcx` as well. Rather than painstakingly replicating these optimizations in `arithcx`, I feel it makes more sense to remove it entirely and just add handling for the carry flag to `addx`/`subfx`.
---
**addcx**
<details><summary>Optimize for size</summary>
Before:
```
BE 01 00 00 00       mov         esi,1
03 75 A8             add         esi,dword ptr [rbp-58h]
```
After:
```
8B 75 A8             mov         esi,dword ptr [rbp-58h]
83 C6 01             add         esi,1
```
</details>
<details><summary>Optimize constant zero</summary>
Before:
```
44 8B C7             mov         r8d,edi
41 83 C0 00          add         r8d,0
```
After:
```
44 8B C7             mov         r8d,edi
F8                   clc
```
</details> …
=> Jit64: Merge arithcx into addx/subfx

Data/Sys/GameSettings/NAC.ini, Data/Sys/GameSettings/NAE.ini, Data/Sys/GameSettings/NAF.ini, Data/Sys/GameSettings/NAL.ini, Data/Sys/GameSettings/NAT.ini
This Pull Request updates N64 INIs based on what I know about various behaviors since the last time we updated it.  This should result in more sane settings for Mario Tennis and Super Smash Bros. while still preventing the out of memory crash due to the tremendous amounts of EFB copies.
=> Cleanup and Update N64 Virtual Console INIs

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/StartupHandler.java
It seems like Android frontend apps don't work with Dolphin anymore now that we're using scoped storage. With this PR, I'm providing a way for frontend apps to supply content URIs to Dolphin, since content URIs work with scoped storage. Frontend apps will probably need to be modified to make use of this, but there are already other emulators like PPSSPP that work the same way, so hopefully it's not a too big thing to ask them to do.
=> Android: Rework intent handling to work under scoped storage

Externals/MoltenVK/CMakeLists.txt, Externals/MoltenVK/patch.sh, Externals/MoltenVK/patches/0001-SPIRVToMSLConverter-Enable-use_framebuffer_fetch_sub.patch, Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp, Source/Core/VideoBackends/Vulkan/ShaderCompiler.cpp, Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoCommon/ConstantManager.h, Source/Core/VideoCommon/GXPipelineTypes.h, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/PixelShaderGen.h, Source/Core/VideoCommon/PixelShaderManager.cpp, Source/Core/VideoCommon/ShaderCache.cpp, Source/Core/VideoCommon/UberShaderPixel.cpp
This PR adds a shader logic ops implementation for Metal on Apple Silicon GPUs and OpenGL ES on mobile GPUs using framebuffer fetch.
Fixes Kirby's Air Ride (https://bugs.dolphin-emu.org/issues/11843).
All Apple Silicon GPUs support framebuffer fetch, so they will all gain logic ops support. However, Intel, AMD, and NVIDIA GPUs do not support it, so Intel Macs are not affected by this PR.
MoltenVK has been patched to enable SPIRV-Cross to convert Vulkan's subpass inputs into framebuffer fetch.
Devices that support either ``GL_EXT_shader_framebuffer_fetch`` or ``GL_ARM_shader_framebuffer_fetch`` can take advantage of this PR.
The following issues need to be resolved / investigated:
=> VideoCommon: Support shader logic ops on Metal (Apple GPUs) and OpenGL ES

Data/Sys/GameSettings/RPBE01.ini, Source/Core/VideoCommon/BPMemory.h, Source/Core/VideoCommon/TextureConverterShaderGen.cpp
We were already doing this for non-intensity formats, but it seems like the same applies to intensity formats.  Note that the software renderer already sets alpha to 1 for both intensity and regular formats.
~~This appears to fix [Rygar: The Battle of Argus's white screens](https://bugs.dolphin-emu.org/issues/12763), but I can't tell if this fix is actually correct (as the game's bloom effect doesn't seem to work properly still); I also haven't hardware tested this behavior (but it seems like it's probably correct to me).  It seems to roughly match the results I was getting with the hardware FIFO player, though.~~  The bloom effect works properly in areas where it is enabled (which does not include the area that was experiencing the white screen), and I've confirmed with the hardware FIFO …
=> TextureConverterShaderGen: Set alpha to 1 on intensity formats if EFB lacks alpha

Source/Core/VideoCommon/LightingShaderGen.h
This generated warnings on the freebsd builder ([example](https://dolphin.ci/#/builders/13/builds/5539)).
=> LightingShaderGen: Make s_lighting_struct not inline

Source/Core/Core/HW/Memmap.cpp, Source/Core/Core/HW/Memmap.h
These GetPointer calls could cause crashes, in part because the callers didn't do null checks and in part because GetPointer inherently is unsafe to use for accesses larger than 1 byte.
=> Memmap: Replace some GetPointer calls

Source/Core/Common/Config/Config.cpp, Source/Core/Common/Config/Config.h, Source/Core/Core/BootManager.cpp, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/CoreTiming.cpp, Source/Core/Core/CoreTiming.h, Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/IOS/DolphinDevice.cpp, Source/Core/DolphinQt/Settings/AdvancedPane.cpp, Source/UnitTests/Core/CoreTimingTest.cpp
Mostly so I can get a review on if this is the correct way to do it to avoid losing perf in hot code, in particular the config change callback.
=> Config: Port CPU overclock setting to new config.

Source/Core/Core/FifoPlayer/FifoPlayer.cpp, Source/Core/Core/FifoPlayer/FifoPlayer.h
Continues #10258.  If we don't wait, then the copy will be performed at a later time, which may overwrite memory updates.  This was causing problems for me when messing with memory updates, since the EFB copy would end up overwriting memory that had been written by the memory update.  I think this may have been the cause of some of the differences in #10264, and will submit a second PR to check.
=> FifoPlayer: Wait after clearing the screen

Source/Core/VideoCommon/GeometryShaderGen.cpp
Fixes https://bugs.dolphin-emu.org/issues/12548.
Both Vulkan and OpenGL use `gl_ClipDistance` when backend depth clamping is enabled.  However, the geometry shader was only copying it for OpenGL, not for Vulkan.  Since stereoscopic 3D uses a geometry shader, this was most visible there, but I suspect it could also affect line/point effects (I was unable to confirm this though).
Here's the relevant vertex shader code (skipping the non-geomerty-shader path):
https://github.com/dolphin-emu/dolphin/blob/6dae4043cb967925ae28cce92d9c100330a5d17e/Source/Core/VideoCommon/VertexShaderGen.cpp#L561-L568
https://github.com/dolphin-emu/dolphin/blob/6dae4043cb967925ae28cce92d9c100330a5d17e/Source/Core/VideoCommon/VertexShaderGen.cpp#L582-L599
=> GeomeryShaderGen: Set gl_ClipDistance on Vulkan as well as OpenGL

Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.cpp, Source/Core/Core/PowerPC/Jit64Common/EmuCodeBlock.h, Source/Core/Core/PowerPC/Jit64Common/Jit64AsmCommon.cpp
It's always a good sign when the comments say "this will definitely crash" and "I don't know if this is for a good reason".
Fixes https://bugs.dolphin-emu.org/issues/12762.
=> Jit64: Make paired loads always safe

Source/Core/VideoBackends/D3D/D3DMain.cpp, Source/Core/VideoBackends/D3D12/VideoBackend.cpp, Source/Core/VideoBackends/Null/NullBackend.cpp, Source/Core/VideoBackends/OGL/OGLMain.cpp, Source/Core/VideoBackends/OGL/OGLRender.cpp, Source/Core/VideoBackends/OGL/SamplerCache.cpp, Source/Core/VideoBackends/Software/SWmain.cpp, Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/ShaderGenCommon.cpp, Source/Core/VideoCommon/ShaderGenCommon.h, Source/Core/VideoCommon/VideoConfig.h
#9998, take two.
In Twilight Princess, the iris of Midna's eyes disappears as the camera moves further away from her model. This is done by using two mipmaps: one with her iris, and one with just the pale yellow of her sclera. The game sets the distance at which the transition between the two mipmaps occurs by setting the LOD bias value to a large negative value.
To emulate LOD bias in the Vulkan backend, ``mipLodBias`` in the ``VkSamplerCreateInfo`` for the texture's sampler is set. Unfortunately, Metal does not support setting LOD bias in a sampler, so `mipLodBias` is ignored by MoltenVK. On OpenGL ES, the sampler parameter for setting LOD bias (``GL_TEXTURE_LOD_BIAS``) is unsupported, unlike desktop OpenGL.
This causes Midna's iris to only appear when the camera is very close to her. …
=> PixelShaderGen: Use LOD bias when sampling texture on Metal and OpenGL ES

Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp
Noticed this while doing my config system sweep. Dentomologist traced this divergence back to 34aebffff92e8f3357dea14082f3ac0973243599 and it doesn't look like an intentional change, so let's fix it I guess.
=> Interpreter: Fix cycle counting inconsistency between debug mode and regular mode loops.

Source/Core/VideoCommon/PixelShaderGen.cpp
Another simple GLES shader compilation error.
=> GLES: Fix LOD bias int/float mismatch

Source/Core/Common/CMakeLists.txt, Source/Core/Common/MemArena.h, Source/Core/Common/MemArenaAndroid.cpp, Source/Core/Common/MemArenaUnix.cpp, Source/Core/Common/MemArenaWin.cpp, Source/Core/Core/HW/Memmap.cpp, Source/Core/DolphinLib.props
See #9544 and #9834.
Note that there are no functional changes in this PR. (or should be, anyway)
=> MemArena: Cleanup & interface changes for safer memory mapping.

Source/Core/Core/PowerPC/GDBStub.cpp
These tends to get requested from either pure GDB or Ghidra. They reduce the verbosity of the communications. The QSupported packet is also important to implement for future proofing too.
=> GDB Stub: add support for various query packets

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/DolphinAnalytics.cpp, Source/Core/DolphinQt/Main.cpp, Source/Core/DolphinQt/MenuBar.cpp, Source/Core/DolphinQt/Settings.cpp, Source/Core/DolphinQt/Updater.cpp, Source/Core/DolphinQt/Updater.h, Source/Core/UICommon/AutoUpdate.cpp, Source/Core/UICommon/AutoUpdate.h
I took the opportunity to do pass some data to `AutoUpdateChecker::CheckForUpdate()` so we don't have to do the weird set-call-revert thing in `InstallUpdateManually()`.
=> Config: Port AutoUpdate settings to new config system.

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/Jit64/Jit_LoadStore.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.cpp, Source/Core/Core/PowerPC/JitCommon/JitBase.h, Source/Core/DolphinQt/MenuBar.cpp
I've cached these in `JitBase` (see `JitBase::RefreshConfig()`) because that seemed like the easier approach -- otherwise I'd have to touch every single instruction codegen function. Likely better performance-wise too, though I haven't actually tested it.
=> Config: Port Debug settings to new config system.

Source/Core/Core/BootManager.cpp, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/Core.cpp, Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/IOS/USB/Bluetooth/BTReal.cpp, Source/Core/Core/WiiUtils.cpp, Source/Core/DolphinQt/Config/WiimoteControllersWidget.cpp
This one is untested because I don't have a bluetooth adapter handy at the moment. Someone should test if it still works as expected.
=> Config: Port BluetoothPassthrough settings to new config system.

Data/Sys/GameSettings/G2M.ini, Data/Sys/GameSettings/GEA.ini, Data/Sys/GameSettings/GFZ.ini, Data/Sys/GameSettings/GLS.ini, Data/Sys/GameSettings/GSZ.ini, Data/Sys/GameSettings/GXX.ini, Data/Sys/GameSettings/P2M.ini, Data/Sys/GameSettings/R64.ini, Data/Sys/GameSettings/RD2.ini, Data/Sys/GameSettings/RNO.ini, Data/Sys/GameSettings/RRB.ini, Data/Sys/GameSettings/RSN.ini, Data/Sys/GameSettings/RYB.ini
At least on Android, SyncGPU has really bad performance compared to single core. It's less stable too – I get fatal GPU desyncs in Pokémon XD using the default settings.
=> GameINI: Replace all uses of SyncGPU with single core

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/CoverHelper.java
This code seems to have been written as if GameFile.getCountry returns a language rather than a country, which is wrong.
=> Android: Fix country constants in CoverHelper.getRegion

Source/Android/jni/MainAndroid.cpp, Source/Core/Common/FileUtil.cpp, Source/Core/Common/FileUtil.h, Source/Core/Common/NandPaths.cpp, Source/Core/Core/IOS/FS/HostBackend/FS.cpp, Source/Core/Core/IOS/IOSC.cpp, Source/Core/Core/WiiRoot.cpp, Source/Core/DiscIO/NANDImporter.cpp, Source/Core/UICommon/UICommon.cpp, Source/Core/UICommon/UICommon.h
That is:
- All path separators are forward slashes.
- Directory paths end with a separator.
- File paths do not end with a separator.
=> Ensure user paths are stored in a consistent manner.

Source/Core/VideoBackends/Vulkan/VulkanContext.cpp
``VulkanContext::CreateDevice()`` attempts to find appropriate graphics queue and present queue families. It will skip trying to find a present queue family if the surface is ``VK_NULL_HANDLE`` (headless mode). However, even if the present queue family isn't valid, ``queueCreateInfoCount`` will be set to ``2`` as long as the graphics queue family index isn't the same as the present queue family index (which it won't, as the default value is the number of queues).
This causes DolphinNoGUI in headless mode on macOS to crash, as MoltenVK would attempt to create an ``MVKQueue`` using an invalid configuration.
=> VulkanContext: Ensure present queue family is valid before incrementing queueCreateInfoCount

Source/Core/Core/HW/EXI/BBA/TAP_Win32.cpp
Current code expects the component ID of the tap adapter to be equal to `tap0901`, however on my machine (Windows 10, latest TAP adapter) the component ID is `root\tap0901`. This should be a fix that is backwards compatible with "old"(?) setups.
=> BBA: Fix TAP detection

Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp
We don't use sampler2DMS, but we do use sampler2DMSArray.
I can't reproduce it on my phone, but a user who was running GLES on a Tegra X1 reported a shader compilation error related to this.
=> GLES: Fix missing precision for sampler2DMSArray

Data/Sys/GameSettings/RPBJ01r0.ini, Data/Sys/GameSettings/RPBJ01r1.ini, Data/Sys/GameSettings/RPBJ01r2.ini, Data/Sys/GameSettings/RPBP01.ini
See 254f39cf785e7dc4790acca38aa0dc10f506aa70 / https://bugs.dolphin-emu.org/issues/12629.
(Fun fact: The Japanese version of PBR does not support widescreen!)
=> GameSettings: Patches for black screen effect for remaining versions of Pokémon Battle Revolution.

Source/Core/InputCommon/ControllerEmu/ControlGroup/Cursor.cpp
Before, if the window was unfocused and background input was disabled, the cursor would become visible and move to the center of the screen.  Now, the cursor is set as hidden.
This is particularly useful for Super Paper Mario, where having the cursor on screen puts the game into a separate mode.  Without this change, even if Hide was bound to something like <code>!\`M\`</code>, the cursor would become visible when the window lost focus unless background input is enabled; this makes recording fifologs very annoying.
=> ControllerEmu: Hide the cursor if the input gate is disabled

Source/Core/Core/PowerPC/PPCAnalyst.cpp
This piece of code is rather hard to understand, but my best guess at what it's trying to do is that it tries to create opportunities to skip writing CRs back to ppcState if we know that there are no CR instructions (or branch instructions, etc) between an instruction that writes to a CR register and the next blr. This is technically inaccurate emulation, but as long as games don't do anything too weird with their ABIs, I suppose it doesn't break anything.
So why do I want to get rid of it? Well, other than breaking some hypothetical weird game, I imagine it could trip up people trying to debug a game who are looking at the CR contents. And the code is just plain confusing. (blr clearly doesn't write to CRs!)
=> PPCAnalyst: Don't treat blr as writing to CR

Source/Core/DolphinQt/RenderWidget.cpp
Fixes errors when building with CMake (Ninja).  
Currently it depends on PCH support, but it's broken currently.  
Not depending on PCH is good practice anyway.
Not sure if `Windows.h` is the most lightweight include though, but it at least fixes the error of there not being a target defined.
=> RenderWidget: Add include to Windows.h

Source/Core/VideoCommon/FramebufferManager.cpp, Source/Core/VideoCommon/FramebufferManager.h, Source/Core/VideoCommon/GeometryShaderGen.h, Source/Core/VideoCommon/PostProcessing.cpp, Source/Core/VideoCommon/RenderBase.cpp, Source/Core/VideoCommon/ShaderCache.cpp, Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureCacheBase.h, Source/Core/VideoCommon/TextureConverterShaderGen.h
This continues the work started in #10065.  Names are now present for all shaders other than the generated pixel/vertex shaders used for emulation and for all textures except the ones used in emulation (as there are a lot of these, and I haven't thought of a good way to create unique names for them).  Names are also not created for shaders created from a binary, but that only applies to shaders used for emulation.
=> VideoCommon: Add names for textures and shaders

Source/Core/Core/PowerPC/GDBStub.cpp
We are always reporting thread 1 existing and also fix an issue with a wrong memcmp size.
=> GDB Stub: fix thread report requests

Source/Core/Core/PowerPC/GDBStub.cpp
This prevented unknown pointer spams when you connect with ghidra because it seems to want to probe memory that happened to be invalid, this shouldn't happen, we should just return an error and not panic.
=> GDB Stub: validate the address exists before reading/writting to it

Source/Core/Core/PowerPC/GDBStub.cpp
This fixes 2 issues with watchpoints:
1: z4 packets would get ignored because of a bogus check for bogus types
2: read only watchpoint and write only watchpoint were reversed in the enum
=> Gdb stub: fix watchpoints

Source/Core/Core/HW/CPU.cpp, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/Core/PowerPC/GDBStub.h
When the CPU goes to stepping and gdb is active + has control, you are supposed to reply with a stop reply packet. The problem is we also do it if we just connected since the cpu will boot to stepping while it has connected with GDB just before.
This make sure we aren't sending the stop reply until the first processCommand loop.
=> GDB Stub: do not send a packet when we just connected

Source/Core/DolphinTool/CMakeLists.txt, Source/Core/DolphinTool/ConvertCommand.cpp, Source/Core/DolphinTool/VerifyCommand.cpp
Verify operation and potentially, convert, require ephemeral space to process Wii images
This should fix accidental deletion of Wii images on certain filesystems (tmpfs, zfs) and "IOS_FS: Failed to write new FST" warnings
=> DolphinTool: initialize user directories before verify/convert operations

Source/Core/Core/PowerPC/GDBStub.cpp
This along with #10319 is actually all it takes to make lldb work correctly and it's very easy to implement so might as well add it.
NOTE: this is specific to lldb, more info here: https://github.com/llvm/llvm-project/blob/main/lldb/docs/lldb-gdb-remote.txt#L867
In my test though, it seems to mix up the packets with read memory, but I have a suspicion that it's an unrelated issue that I will be trying to address because from dolphin's side, it is replying correctly.
=> GDB Stub: add support for lldb's qHostInfo

Source/Core/VideoBackends/D3D12/DX12Shader.cpp
`m_compute_pipeline` isn't initialized until `CreateComputePipeline()` is called.
=> D3D12: Fix nullptr dereference when creating a shader with a name.

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java
Our reasons for using `setRetainInstance` were gotten rid of in PRs #9011 and #10008, so let's remove our calls to this deprecated method.
=> Android: Remove all setRetainInstance calls

Source/Core/VideoBackends/Vulkan/VKShader.cpp, Source/Core/VideoBackends/Vulkan/VKTexture.cpp
Fixes a crash that has been present on Android (and probably also macOS) since the merge of PR #10269.
This is my first time touching Vulkan, and I don't know if this is a "proper" solution. (Should we check for the existence of VK_EXT_debug_utils rather than checking the vkSetDebugUtilsObjectNameEXT function pointer directly?)
=> Vulkan: Check for vkSetDebugUtilsObjectNameEXT before using it

Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp
This extends the timeout to 30 seconds, so users who have brief connection issues won't be so swiftly disconnected, allowing the NetPlay session to continue.
This isn't easy to test normally, but I happen to have the right setup locally to create artificial packet loss, so I was able to verify that it works as intended.
=> Core/NetPlay: Extend enet peer timeout

Source/Core/Core/BootManager.cpp, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/Core.cpp
These don't seem to actually do anything except disabling the JIT in some combinations. I assume the functionality was removed at some point but the settings themselves weren't?
=> Config: Remove CompareServer and CompareClient settings.

Source/Android/app/build.gradle, Source/Android/app/src/main/AndroidManifest.xml
Unlike with Android 11, there should be no downsides to doing this, so we might as well get this out of the way early. The main part of the work was already done in PR #9654.
Do not merge this until it has been tested by someone who has Android 12! I don't have Android 12 myself.
=> Android: Increase targetSdkVersion to 31 (Android 12)

Source/Core/Common/BitField.natvis, Source/Core/Common/EnumMap.natvis, Source/Core/DolphinLib.props
I've improved the natvis files for BitField, and added one for EnumMap.  See [this page](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022) for more info about natvis, and [here's Microsoft's STL natvis](https://github.com/microsoft/STL/blob/main/stl/debugger/STL.natvis).  Basically, it's an XML pseudo-language with a lot of quirks which is used for defining how things should show up in the visual studio debugger.
Here's some screenshots of the new EnumMap display in the debugger:
<details><summary>And here's a diff in formatting for all of the stuff in <code>BitFieldTest</code>:</summary>
```diff
TEST(BitField, Storage)
?object
{hex=0 full_u64=0 full_s64=0 ...}
hex: 0
full_u64: 0
full_s64: 0
regular_field_unsigned: 0 …
```
=> Natvis improvements

Source/Core/Common/AndroidAnalytics.cpp
=> Android: Mark s_android_send_report as static

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/ui/CheatsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java, Source/Android/app/src/main/res/menu/menu_settings.xml
This PR removes the save icon since it's no longer necessary. I've also added an up button to the top left of the screen in the settings and cheats view, which makes navigating feel much more natural.
Screenshots:
=> Android: remove save icon and add up button

Source/Core/Core/BootManager.cpp, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/GameConfigLoader.cpp, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/ConfigManager.cpp, Source/Core/Core/ConfigManager.h, Source/Core/Core/HW/EXI/EXI.cpp, Source/Core/Core/HW/SI/SI.cpp, Source/Core/Core/HW/SI/SI_DeviceGCAdapter.cpp, Source/Core/Core/HW/SI/SI_DeviceGCController.cpp, Source/Core/Core/HW/SI/SI_DeviceGCController.h, Source/Core/Core/Movie.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp, Source/Core/DolphinQt/Config/GamecubeControllersWidget.cpp, Source/Core/DolphinQt/GameList/GameList.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/Settings/GameCubePane.cpp, Source/Core/InputCommon/GCAdapter.cpp, Source/Core/InputCommon/GCAdapter_Android.cpp
Separate PR here because of this snippet of code that I'm not sure how to translate correctly into the new system:
```
for (unsigned int i = 0; i < SerialInterface::MAX_SI_CHANNELS; ++i)
{
int source;
controls_section->Get(fmt::format("PadType{}", i), &source, -1);
if (source >= SerialInterface::SIDEVICE_NONE && source < SerialInterface::SIDEVICE_COUNT)
{
StartUp.m_SIDevice[i] = static_cast<SerialInterface::SIDevices>(source);
config_cache.bSetPads[i] = true;
}
}
```
This happens while parsing GameINIs and basically means 'if `PadTypeN` is set to a valid value, override `SIDeviceN` with that, otherwise keep the value set by `SIDeviceN`'. I can and have added these to `GetINIToLocationMap()`, but that's not quite the same behavior -- if you set it to an invalid value, Dolphin will now use …
=> Config: Port EXI device and SI device settings to new config system.

Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp
For determinism compatibility with old x64 CPUs. Off by default.
I haven't tested this on netplay, but I've tested that the new code path doesn't break games in any obvious way. (Other than breaking existing F-Zero GX replays, which is unsurprising)
This is a follow-up to PR #9804.
=> JitArm64: Implement FMA-less path for FMA instructions

Source/Core/Core/PowerPC/PPCAnalyst.cpp
When these checks were originally added, we didn't have the nice `canCauseException` attribute. Now we do, so let's use it.
Split out from PR #9857, because it looks like that PR isn't getting reviewed any time soon.
=> PPCAnalyst: Less strict interrupt checks in CanSwapAdjacentOps

Source/Core/Core/ConfigLoaders/GameConfigLoader.cpp
The "DSP" and "Controls" section names were both supported by BootManager.cpp before the recent mass-porting of settings. For backwards compatibility, we should keep supporting them.
Should fix https://bugs.dolphin-emu.org/issues/12792
=> Config: Add missing legacy game INI mappings

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivityPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
It's a complete coincidence that both SIDEVICE_GC_CONTROLLER (6) and SIDEVICE_WIIU_ADAPTER (12) are divisible by 6. Dividing by 6 because of that doesn't make sense, especially not if we want to add support for more kinds of SI devices on Android later.
=> Android: Don't divide SI device by 6

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsFragmentPresenter.java
No functional difference. Just making sure that the settings have the same name in Java as in C++ so that they're easy to cross-reference.
=> Android: Make Main.Debug setting declarations match C++

Source/Core/Core/HW/GCPadEmu.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/AnalogStick.h, Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.cpp, Source/Core/InputCommon/ControllerEmu/ControlGroup/Tilt.h, Source/Core/InputCommon/ControllerEmu/StickGate.cpp, Source/Core/InputCommon/ControllerEmu/StickGate.h
Use value of "Modifier" button "Range" setting rather than always applying 50%.
Make "Clear" button reset "Modifier" "Range" settings to 50%.
=> InputCommon: Re-enable "Modifier" "Range" settings.

Source/Core/VideoCommon/PixelShaderGen.cpp
This syntax is [allowed by GLSL](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Vector_constructors), but HLSL doesn't allow it (I couldn't find any documentation explicitly rejecting it, but I couldn't find any allowing it either, and the shader compiler gets mad).  This meant that games using R8 comparisons in equal mode would produce shaders that failed to compile.  Super Mario Galaxy's water levels were affected by this; see https://github.com/dolphin-emu/dolphin/pull/9718#issuecomment-1011802368.
I initially used `int3(0)` in a bunch of places since it's simpler, but when I discovered that HLSL doesn't accept it, I changed it; I thought I changed all of the instances of it, but I guess I missed that one.
=> PixelShaderGen: Fix invalid use of int3(0)

Source/Android/jni/MainAndroid.cpp, Source/Core/Common/LinearDiskCache.h, Source/Core/Common/Version.cpp, Source/Core/Common/Version.h, Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Core.cpp, Source/Core/Core/DolphinAnalytics.cpp, Source/Core/Core/IOS/DolphinDevice.cpp, Source/Core/Core/Movie.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayServer.cpp, Source/Core/Core/State.cpp, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DolphinQt/AboutDialog.cpp, Source/Core/DolphinQt/MainWindow.cpp, Source/Core/DolphinQt/NetPlay/NetPlayBrowser.cpp, Source/Core/DolphinQt/Updater.cpp, Source/Core/UICommon/AutoUpdate.cpp, Source/Core/UICommon/CommandLineParse.cpp, Source/Core/UICommon/NetPlayIndex.cpp, Source/Core/VideoBackends/D3DCommon/Shader.cpp, Source/Core/VideoBackends/OGL/ProgramShaderCache.cpp, Source/Core/VideoBackends/Vulkan/ShaderCompiler.cpp
Fixes a crash that could occur if the static constructor function for
the MainSettings.cpp TU happened to run before the variables in
Common/Version.cpp are initialised. (This is known as the static
initialisation order fiasco.)
By using wrapper functions, those variables are now guaranteed to be
constructed on first use.
I didn't rename the variables to make reviewing this PR easier but at some point we'll probably want to give clearer names to scm_rev_str and scm_rev_git_str.
=> Fix static initialisation order fiasco issue for Version variables

Source/Core/DiscIO/CMakeLists.txt, Source/Core/DolphinTool/CMakeLists.txt
DiscIO depends on some IOS functions and other functions, which are in Core and not Common.  This results in link errors if using DiscIO on its own (which is why DolphinTool had a listed dependency on videocommon; videocommon has a dependency on core so adding that made things build).
=> CMakeLists: Change DiscIO dependency from common to core

Source/Core/Common/IniFile.h, Source/Core/Common/Logging/LogManager.cpp, Source/Core/Common/Network.cpp, Source/Core/Common/StringUtil.cpp, Source/Core/Common/StringUtil.h, Source/Core/Core/ARDecrypt.cpp, Source/Core/Core/Boot/Boot.cpp, Source/Core/Core/DSP/DSPDisassembler.cpp, Source/Core/Core/HW/DVD/FileMonitor.cpp, Source/Core/Core/HW/EXI/EXI_DeviceEthernet.cpp, Source/Core/DiscIO/DirectoryBlob.cpp, Source/Core/DiscIO/FileSystemGCWii.cpp, Source/Core/DiscIO/RiivolutionPatcher.cpp, Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp, Source/Core/InputCommon/ControllerInterface/SDL/SDL.cpp, Source/Core/UICommon/DiscordPresence.cpp, Source/Core/UICommon/GameFile.cpp, Source/UnitTests/Common/x64EmitterTest.cpp
This means that dol/elf files with upercase extensions (e.g. BOOT.DOL) are properly detected.  ISO files with uppercase extensions already worked.  This affected [Rick Dangerous Wii](https://wiibrew.org/wiki/Rick_Dangerous_Wii) (though it is still broken in [other ways](https://bugs.dolphin-emu.org/issues/12799)).
Note that the same case conversion is performed by `Boot.cpp`:
https://github.com/dolphin-emu/dolphin/blob/07fd17445c6ca4e89b0cef023ba711bb27c920aa/Source/Core/Core/Boot/Boot.cpp#L205-L208
=> GameList: Convert file extensions to lowercase

Source/Core/DolphinQt/FIFO/FIFOPlayerWindow.cpp
This resulted in the loop checkbox appearing unchecked, even though loop was enabled.  A mistake in #10355.
=> FifoPlayer: Add missing call to LoadSettings()

Source/Android/app/src/main/AndroidManifest.xml, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/NativeLibrary.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateProgressBarDialogFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateRegionSelectDialogFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/OnlineUpdateResultFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/SystemMenuNotInstalledDialogFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/sysupdate/ui/SystemUpdateViewModel.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/TvMainActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/WiiUpdateCallback.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/WiiUtils.java, Source/Android/app/src/main/res/menu/menu_game_grid.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Android/jni/AndroidCommon/IDCache.cpp, Source/Android/jni/AndroidCommon/IDCache.h, Source/Android/jni/MainAndroid.cpp, Source/Android/jni/WiiUtils.cpp, Source/Core/Core/WiiUtils.h
This PR adds the online system update functionality to the Android version of Dolphin.
Thanks to @OatmealDome for helping me to debug my issues and help me out on the C++ part.
- The update process is very similar to the desktop version of Dolphin.
- Two new buttons have been added to the main view's menu: launch Wii Menu and Perform Online System Update
- New buttons have been added to Android TV as well.
- Logic has been to handle cases like launching the Wii Menu if it has not been installed.
There are two remaining issues:
1. The update fails if the screen is being rotated during the update. We mitigated this issue by locking the device orientation to the current position with `setRequestedOrientation`. The rotation will be unlocked after the update is done. A log file for this …
=> Android: Add online system update functionality

Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/OpcodeDecoding.cpp, Source/Core/VideoCommon/OpcodeDecoding.h, Source/Core/VideoCommon/VideoBackendBase.cpp
A pop-up is no longer generated for the Wiggler capsule in Mario Party 5 (https://bugs.dolphin-emu.org/issues/8104).
Primitive data related to the unknown opcodes in Mario Party 5: https://gist.github.com/Pokechu22/83d5cd9443f3336f50bc5d626fb9636f
And some assorted images from the hardware fifo player: https://imgur.com/a/hx4qe42
Basically, the Wiggler capsule's animation draws a bunch of rings.  Each ring has 128 vertices in it, with positions moving around a circle and texture coordinates going up by .03125 (1/32) for each horizontal step.  The position, color, and texture coordinate data for each vertex is indexed into several arrays, with the first set of 4 vertices using indices 0, 1, 3, and 2.  However, after all 128 vertices are written, the game writes data for 4 more vertices, …
=> OpcodeDecoding: Don't raise panic alerts for unknown opcodes 0x01-0x07

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/IntSetting.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlayPointer.java, Source/Android/app/src/main/res/menu/menu_overlay_controls_wii.xml, Source/Android/app/src/main/res/values/arrays.xml, Source/Android/app/src/main/res/values/strings.xml, Source/Core/Core/ConfigLoaders/IsSettingSaveable.cpp
This PR adds the following settings:
* `IR Mode`: IR pointer can now follow the user's finger or be dragged around (see commit description for more info)
* `IR Always recenter`: recenter IR after every pointer interaction
These settings come from the MMJ fork, and were cleaned up and ported to the MMJR fork by me. Some users are still using those forks only because of these settings, so I figured I'd port them here too so we can finally get rid of them :)
=> Android: add two QoL settings to IR pointer

Source/Core/VideoCommon/GeometryShaderGen.cpp
At least in GLSL, after calling `EmitVertex()` the value of all 'out' variables ([including `gl_Layer`](https://www.khronos.org/opengl/wiki/Geometry_Shader#Layered_rendering) and `ps`) becomes undefined.  On OpenGL it seems like they were unchanged, but on Vulkan they became 0, resulting in bad rendering.  Note that this isn't exactly true; for the fire man stage the old behavior resulted in flickering even when looping the same frame of the fifolog, so there was an additional element of nondeterminism.
Fixes https://bugs.dolphin-emu.org/issues/12001.
Fifologs ([megaman-heat](https://fifo.ci/media/dff/FireManHeatShort.dff), [line-width-test](https://fifo.ci/media/dff/LineWidthTest.dff), and the fifolog from issue 12001):
<details><summary>Old</summary> …
=> GeometryShaderGen: Write the layer for every vertex

Source/Core/VideoCommon/UberShaderPixel.cpp
Fixes https://bugs.dolphin-emu.org/issues/12814.  The typo was introduced in #6352; see [specialized shaders](https://github.com/dolphin-emu/dolphin/pull/6352/files#diff-15dbecba159f6aa3db86aa8bad1b7f2d403e9de959d84c0d5d04af06b0f41414L1341-R1342) vs [ubershaders](https://github.com/dolphin-emu/dolphin/pull/6352/files#diff-cf173f4d3f10e7603ea9af059d550e4532033584d0b6fce2151a81306ba41163L1165-R1165).
=> UberShaderPixel: Fix typo in fog calculation

Source/Core/VideoCommon/TextureCacheBase.cpp, Source/Core/VideoCommon/TextureConverterShaderGen.cpp
Fixes https://bugs.dolphin-emu.org/issues/12813, which regressed in #10204.  The clamping logic was improved in #10222, but was off by half a pixel, which causes issues for the previous line when the copy filter is enabled.
Here's the EFB it's working with (as with before, the colors are weird because the EFB is RGBA6 for normal game logic, but RGB8 for the broken effect):
The EFB copy is for 152 by 85 at (336, 224).  The broken version produces this (upscaled 4x with nearest neighbor):
Now, it produces this:
The comment about clamping behavior is from the software renderer; I myself haven't performed the tests it is referring to:
https://github.com/dolphin-emu/dolphin/blob/b237c7479e21421e4017dea9df34309af4c0a2e8/Source/Core/VideoBackends/Software/EfbInterface.cpp#L589-L597
I also fixed …
=> Fix copy filter clamping (again)

Source/Android/app/src/main/res/layout-ldrtl/list_item_cheat.xml, Source/Android/app/src/main/res/layout/fragment_cheat_warning.xml, Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml, Source/Android/app/src/main/res/layout/list_item_cheat.xml, Source/Android/app/src/main/res/layout/list_item_setting_checkbox.xml
Settings checkbox:
Cheats checkbox:
In-game menu font spacing:
=> Android: Fix in-game menu font spacing and checkbox margin

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/Core/HW/EXI/EXI.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/NetPlayProto.h, Source/Core/Core/NetPlayServer.cpp
Found this straggler that was in neither config system!
=> Port memory card size override setting to new config system.

Source/Core/Core/ConfigLoaders/BaseConfigLoader.cpp
=> Core/BaseConfigLoader: Disallow loading the MAIN_MEMORY_CARD_SIZE from the global config INI.

Source/Android/jni/GameList/GameFile.cpp, Source/Android/jni/GameList/GameFileCache.cpp
These files cannot compile correctly as C, so there's no reason to have ifdefs for C compatibility.
We switched to not checking the __cplusplus macro in our JNI code some time ago, but it seems like I forgot to remove it from these two files.
=> Android: Get rid of __cplusplus macro checks

Data/Sys/GameSettings/STR.ini
Automatically set Texture Cache Accuracy to safe in game INI as per wiki entry:
https://wiki.dolphin-emu.org/index.php?title=Tron:_Evolution_-_Battle_Grids
=> Game INI update for Tron Evolution Battle Grids (all editions)

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/ui/SettingsActivity.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/DirectoryInitialization.java, Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/ThreadUtil.java, Source/Android/app/src/main/res/layout-land/activity_user_data.xml, Source/Android/app/src/main/res/values/strings.xml
Apparently there are phones where accessing Dolphin's app-specific directory isn't just annoyingly hard but actually impossible. To give users of those phones at least some kind of way to manage their data (even if it's a lot less convenient than if we were allowed to let the user open the app-specific directory in a file manager), I'm adding a way to export the directory to a zip file and then import it back.
=> Android: Add import/export options for user data

Source/Core/UpdaterCommon/UpdaterCommon.cpp
This fixes an issue with the auto updater that wasn't noticed until now.
On macOS, we rename files instead of copying them to avoid a quirk in the kernel's code signature cache (#9858). 
#10297 added two files: ``RPBJ01r1.ini‎‎`` and ``RPBJ01r2.ini‎‎``. These both have the same hash, so they have the same content file name. This caused the updater to break when updating ``RPBJ01r2.ini‎‎``, as the content file for ``RPBJ01r1.ini‎‎`` would be moved into the new path, making it impossible for ``RPBJ01r2.ini‎‎`` to be updated as the content file would no longer exist.
To fix this, we copy the content file to a temporary file and then move the temporary file to the target path.
Unfortunately, builds after #9858 will not be able to update to builds after #10297. They will need to do this …
=> UpdaterCommon: Copy content file to a temporary file before renaming on macOS

Source/Core/VideoBackends/D3D/D3DMain.cpp, Source/Core/VideoBackends/D3D12/VideoBackend.cpp, Source/Core/VideoBackends/Null/NullBackend.cpp, Source/Core/VideoBackends/OGL/OGLRender.cpp, Source/Core/VideoBackends/OGL/OGLShader.cpp, Source/Core/VideoBackends/OGL/OGLTexture.cpp, Source/Core/VideoBackends/Software/SWmain.cpp, Source/Core/VideoBackends/Vulkan/VKShader.cpp, Source/Core/VideoBackends/Vulkan/VKTexture.cpp, Source/Core/VideoBackends/Vulkan/VulkanContext.cpp, Source/Core/VideoBackends/Vulkan/VulkanEntryPoints.inl, Source/Core/VideoCommon/VideoConfig.h
Basically, the proper version of #10342.
A flag has been added to ``VideoConfig``: ``bSupportsSettingObjectNames``. This is now checked before calling ``glObjectLabel`` in the OpenGL backend and ``vkSetDebugUtilsObjectNameEXT`` in the Vulkan backend.
For the OpenGL backend, support is only set if on [OpenGL >4.3](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glObjectLabel.xhtml) or [OpenGL ES 3.2](https://www.khronos.org/registry/OpenGL-Refpages/es3/html/glObjectLabel.xhtml). This fixes a crash when using the OpenGL backend on macOS, the Android Emulator, and probably some other devices.
For the Vulkan backend, support is only set if the ``VK_EXT_debug_utils`` extension was loaded correctly. In addition, a bug has been fixed where ``vkSetDebugUtilsObjectNameEXT`` was loaded as …
=> VideoConfig: Add flag for whether the system supports setting object names

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/UserDataActivity.java
I think users will have a hard time figuring out where to place texture packs and Riivolution mods and so on without this.
=> Android: Include empty folders when exporting user data

Source/Core/VideoCommon/FrameDump.cpp
`av_guess_format` now returns a pointer to const.
https://ffmpeg.org/doxygen/trunk/group__lavf__encoding.html#ga00bceb049f2b20716e2f36ebc990a350
```cpp
#define FF_API_AVIOFORMAT               (LIBAVFORMAT_VERSION_MAJOR < 59)
```
```cpp
#if FF_API_AVIOFORMAT
#define ff_const59
#else
#define ff_const59 const
#endif
```
```cpp
ff_const59 AVOutputFormat *av_guess_format(const char *short_name,
const char *filename,
const char *mime_type);
```
=> VideoCommon/FrameDump: Build fix for libavformat major version 59 and newer.

Externals/MoltenVK/CMakeLists.txt
A MoltenVK release was made to coincide with Vulkan SDK 1.3.204.
=> MoltenVK: Update to v1.1.7 (Vulkan SDK 1.3.204)

Data/Sys/GameSettings/SCY.ini, Data/Sys/GameSettings/SQI.ini, Data/Sys/GameSettings/STS.ini
Apparently MMU is no longer needed in these titles.  All 3 booted and
played into gameplay in the latest builds without issues, and disabling
MMU results in a very slight, but noticeable performance boost.
=> Remove MMU Default in Disney Trio of Destruction

Source/Core/VideoBackends/OGL/OGLMain.cpp
I was able to reproduce the OpenGL crash from [12836](https://bugs.dolphin-emu.org/issues/12836), but only when starting Dolphin with Vulkan set, switching to OpenGL, and starting a game. I think this might be because the value from Vulkan carries over to OpenGL and doesn't get overwritten?
I tested my reproduction steps 5 times and it hasn't crashed yet, so I believe this fixes the issue.
=> OGLMain: Set default value for bSupportsSettingObjectNames

Source/Core/Common/MemArena.h, Source/Core/Common/MemArenaWin.cpp
This allocates and handles our fastmem address region as a placeholder on Windows. This avoids the possibility that something else allocates memory within the fastmem address region after it has been set up.
This should fix the bug (on Windows at least) where large texture packs break emulation, such as [12404](https://bugs.dolphin-emu.org/issues/12404) or [11994](https://bugs.dolphin-emu.org/issues/11994), but I cannot 100% confirm it.
References:
[Test code](https://gist.github.com/AdmiralCurtiss/0ba59f15710d919735f9f73ab20fb518)
[Docs on VirtualAlloc2](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc2)
[Docs on VirtualFree](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualfree)
[Docs on …
=> MemArena: Use memory placeholders for fastmem on Windows to ensure nothing allocates within the fastmem space.

Source/Core/VideoBackends/Software/Tev.cpp, Source/Core/VideoCommon/PixelShaderGen.cpp, Source/Core/VideoCommon/UberShaderPixel.cpp
Fixes https://bugs.dolphin-emu.org/issues/11909, partially by reverting #4514.  I still need to do further testing here; I'm fairly sure the first commit is correct (I was able to confirm that an alpha value of 1 is being generated by both Fortune Street and Mario Kart Wii), but am less sure about the second one.
=> Revert TEV alpha lerp change and special-case alpha=1 in blending

Source/Core/Core/Config/MainSettings.cpp, Source/Core/Core/Config/MainSettings.h, Source/Core/Core/ConfigLoaders/NetPlayConfigLoader.cpp, Source/Core/UICommon/UICommon.cpp
Currently, disabling mGBA when building gets rid of the ability to change the GBA saves directory in DolphinQt, but it doesn't actually get rid of Dolphin loading and storing the setting and creating the folder. If the setting is set to a path you don't want to use (perhaps you are trying to turn Dolphin portable), this is annoying.
To avoid accidentally making mistakes like this in the future, I'm gating the existence of the setting behind an ifdef.
=> Don't create GBA saves dir when building without mGBA

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/riivolution/ui/RiivolutionBootActivity.java
There is a Load path setting, so the Load part can't just be hardcoded.
=> Android: Fix the logic for getting the Riivolution path

Source/Core/Core/HW/GPFifo.cpp, Source/Core/Core/HW/GPFifo.h, Source/Core/Core/PowerPC/Jit64/Jit.cpp, Source/Core/Core/PowerPC/JitArm64/Jit.cpp, Source/Core/VideoCommon/CommandProcessor.cpp, Source/Core/VideoCommon/CommandProcessor.h, Source/Core/VideoCommon/Fifo.cpp
Fixes the unknown opcode with Prince of Persia: Rival Swords (https://bugs.dolphin-emu.org/issues/9203).
This bug occurs because the game has some sort of caching layer to reduce the number of calls to GX functions.  For instance, calls to their function to configure vertex descriptor (at `8010d558`) compare with a cached value before calling `GXSetVtxDesc` (at `80499164`).  I'm not sure whether this actually has any tangible benefit, as those functions don't directly send graphics commands but instead update other internal state, but still, it's something they do.
They have a function that draws a black rectangle over the entire screen (at `80111b40` via `800ae644`), which among other things configures the vertex descriptor to have a position and a color, and then draws the rectangle: …
=> Ignore unknown opcode for 0x3f

Source/Core/Common/CodeBlock.h
Fixes https://bugs.dolphin-emu.org/issues/12827.
A description of what was going wrong:
JitArm64::Init first calls CodeBlock::AllocCodeSpace, after which CodeBlock and Arm64Emitter consider us to have 96 MB of code space available. JitArm64::Init then calls AddChildCodeSpace, which is supposed to take 64 MiB of that space and give it to m_far_code. CodeBlock's view of how much space there is gets updated from 96 MiB to 32 MiB, but due to the missing call, Arm64Emitter keeps thinking that it has 96 MiB of space available.
The last thing JitArm64::Init does is to call ResetFreeMemoryRanges. This function asks Arm64Emitter how much code space is available and stores a range of that size in m_free_ranges_near, meaning that m_free_ranges_near ends up being backed by both nearcode and farcode! …
=> Common/CodeBlock: Call ResetCodePtr when decreasing region_size

Source/Core/VideoCommon/CommandProcessor.cpp
Moving the unknown opcode log log message before the panic alert means that the extra information is already in the log by the time the panic alert appears, which is _slightly_ more convenient for debugging.  And changing it to the warn level matters because large amounts of logging can have an impact on performance, so moving the messages for unknown opcodes that have been determined to not matter gives a way to hide those messages without hiding actual errors (and also gives a fast visual way of distinguishing between ignored and non-ignored ones due to the different colors).
=> CommandProcessor: Move unknown opcode log message before the panic alert and log ignored unknown opcodes at warn level

Source/Core/Core/Movie.cpp
Previously, when Pause at End of Movie was disabled, the game would continue running as it should, but the menu bar would think the game was paused, showing the play button instead of the pause button.  To make things worse, clicking the play button would then restart the game, instead of pausing or doing nothing.  F10 paused/unpaused as normal, though.
The old behavior was essentially to enable stepping/pause mode (via `CPU::Break()`) and then if Pause at End of Movie was disabled, to un-pause on the host thread (via `CPU::EnableStepping(false)`).  For reasons which aren't entirely clear to me, the first one notified the menu bar (through the `Host::UpdateDisasmDialog` callback, not the `Settings::EmulationStateChanged` one), and the second did not.  In any case, this approach does not …
=> Fix menu bar becoming desynced when Pause at End of Movie is disabled

Source/Core/VideoCommon/GXPipelineTypes.h
found when grepping for msvc hacks...
=> GXPipelineUid: remove explicit shallow copy where it's the default

Source/Core/Core/HotkeyManager.cpp
Shift+W in particular messes up very common keyboard control mappings.
=> HotkeyManager: Change defaults for GBA hotkeys so they don't conflict with common keyboard mappings.

Source/Core/Common/MathUtil.h, Source/Core/Core/Core.cpp, Source/Core/Core/DSP/Jit/x64/DSPEmitter.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitMultiplier.cpp, Source/Core/Core/DSP/Jit/x64/DSPJitRegCache.cpp, Source/Core/Core/FifoPlayer/FifoDataFile.cpp, Source/Core/Core/NetPlayClient.cpp, Source/Core/Core/PowerPC/GDBStub.cpp, Source/Core/DiscIO/VolumeVerifier.cpp, Source/Core/DolphinQt/Debugger/CodeViewWidget.cpp, Source/Core/DolphinQt/FIFO/FIFOAnalyzer.cpp, Source/Core/DolphinQt/RiivolutionBootWidget.cpp
See https://dolphin.ci/#/builders/19/builds/5836 for most of them.  Some of these fixes solve actual problems (e.g. https://github.com/dolphin-emu/dolphin/pull/10298#pullrequestreview-853889957), but several are just false positives.
I haven't included the fix from #10374, nor have I fixed the memcpy-relatated warnings or the conversion from `unsigned int` to `unsigned int:21` in PixelShaderGen.
=> Fix several compile warnings on GCC

Source/Core/DolphinQt/CheatSearchFactoryWidget.cpp, Source/Core/DolphinQt/Config/ARCodeWidget.cpp, Source/Core/DolphinQt/Config/ControllerInterface/DualShockUDPClientAddServerDialog.cpp, Source/Core/DolphinQt/Debugger/MemoryWidget.cpp, Source/Core/DolphinQt/Debugger/NewBreakpointDialog.cpp, Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.cpp, Source/Core/DolphinQt/Settings/USBDeviceAddToWhitelistDialog.h
[`QRadioButton`](https://doc.qt.io/qt-5/qradiobutton.html) has an `autoExclusive` function, but it only works if the buttons share the same parent widget.  [`QButtonGroup`](https://doc.qt.io/qt-5/qbuttongroup.html) can be used to manually specify groups.
<details><summary>Example of the problem</summary>
Open the breakpoints tab by selecting View &rarr; Breakpoints (the debugging UI may need to be enabled).  Then, while a game is running, select "New".  Then, click on the "Memory breakpoint" button 4 times.  _Weird_ stuff happens.
</details>
I'm not 100% sure that this doesn't leak memory; the documentation isn't explicit about what owns the `QButtonGroup` object (to my understanding, Qt normally manages deletion of objects, but I don't know if it'll follow the `addButton` chain …
=> Fix improperly exclusive radio buttons

Source/Core/Common/Logging/ConsoleListener.h
Add [[maybe_unused]] attribute to m_use_color in ConsoleListener.
Fixes a warning on the Android builder.
=> [Android] Fix unused variable warning

Source/Core/VideoCommon/FramebufferManager.cpp
I.e. flush EFB pokes before running an EFB peek, if the cache tile isn't present.  If the cache tile is present, then EFB pokes should have been written to the cache tile and thus don't need to be flushed.
Found while working on dolphin-emu/hwtests#44 ([permalink to the relevant version](https://github.com/pokechu22/hwtests/tree/archive/efb-copy-filter-4)).  As part of that test, I send a bunch of EFB pokes, and then to make sure I wrote the EFB correctly, I use EFB peeks immediately afterwards to verify those values.  That was giving incorrect results in Dolphin (Test 1 was failing) but now gives correct results.  (This PR does not fix the other issues covered by that hardware test; tests other than 1 and 2 still fail with this PR.)
=> FramebufferManager: Flush pending EFB pokes in PopulateEFBCache

Source/Android/jni/MainAndroid.cpp
We don't have a timeout like this on other platforms, and it doesn't accomplish anything useful as far as I can tell. If you trigger it, all that happens is that you don't get a working game and also can't press Exit Emulation without Dolphin hanging (stuck in Core::Shutdown).
=> Android: Get rid of the boot timeout

Source/Android/jni/Config/NativeConfig.cpp
Otherwise the value of the setting won't be updated properly.
=> Android: Call OnConfigChanged when resetting a setting

Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/settings/model/BooleanSetting.java, Source/Core/Core/IOS/IOS.cpp, Source/Core/Core/IOS/IOS.h, Source/Core/Core/IOS/SDIO/SDIOSlot0.cpp, Source/Core/Core/IOS/SDIO/SDIOSlot0.h, Source/Core/DolphinQt/Settings.cpp
This saves the GUI from having to manually call SDIO_EventNotify. With that out of the way, we can let users change the "Insert SD Card" setting on Android while a game is running.
=> Use config changed callback to detect SD insertion/ejection

Source/Core/VideoCommon/PixelShaderGen.cpp
On devices which have hardware support for dual source blending but not logic ops, this lets us skip performing the framebuffer fetch in situations where the game isn't actually using logic ops.
=> PixelShaderGen: Check uid_data for use_shader_logic_op

Source/Android/app/src/main/res/layout/fragment_ingame_menu.xml
PR #10402 set this for most buttons in the in-game menu but missed the savestate-related buttons and Unpause Emulation.
=> Android: Set letterSpacing for savestate options

Source/Core/VideoCommon/RenderState.cpp
Title. Kirby's Air Ride uses the alpha value as a multiplier for the pixel's color in shadow rendering. If we don't update it, then the alpha ends up being set to 0 for the entire frame, causing the entire world to be shadowed in darkness as every color gets multiplied by zero.
The FifoCI diff can be found [here](https://fifo.ci/compare/7365753-7365499/). Doesn't seem to affect any other games.
Fixes Kirby's Air Ride on Intel Macs.
=> BlendingState: Set source and destination alpha factors in logic op workaround

Source/Core/Common/MemArena.h, Source/Core/Common/MemArenaUnix.cpp
Same idea as #9544 but for Linux. As I understand correctly Linux allows this brutal clobbering of regions, but I honestly only have half an idea what I'm doing here. Please scrutinize.
This should fix the bug (on Linux) where large texture packs break emulation, such as [12404](https://bugs.dolphin-emu.org/issues/12404) or [11994](https://bugs.dolphin-emu.org/issues/11994), but I cannot 100% confirm it.
=> MemArena: Keep fastmem memory region mapped on Linux to ensure nothing allocates within the fastmem space.
